export default {
  id: 'ecosystems',
  title: 'Ecosystems & Food Chains',
  subtitle: 'The web of life that keeps our planet alive 🌍',
  emoji: '🌍',
  category: 'Biology',
  accentKey: 'earth',

  hook: {
    question: "Did you know that removing wolves from Yellowstone Park caused rivers to change course — because of deer? 🤯",
    reveal: "When wolves were reintroduced to Yellowstone in 1995 after 70 years, something extraordinary happened. Deer stopped grazing near rivers (fear kept them moving), allowing vegetation to recover. Trees returned, stabilising riverbanks, which changed water flow patterns. This 'trophic cascade' showed that ecosystems are so interconnected that one predator's absence can alter rivers, landscapes, and carbon storage. Everything in nature is connected in ways that constantly surprise even the best scientists. 🐺🌿🏞️",
    emoji: '🌍',
  },

  theory: [
    {
      id: 'what_ecosystem',
      title: 'What is an Ecosystem? 🌍',
      color: '#2ECC71',
      bgGradient: ['#041A0C', '#030D08'],
      icon: '🌍',
      svgIcon: 'earth',
      content: "An **ecosystem** is a community of living organisms interacting with each other AND with their non-living environment (soil, water, climate, nutrients) as a system.\n\n**Components:**\n🌱 **Biotic** (living): plants, animals, fungi, bacteria, protists\n🪨 **Abiotic** (non-living): sunlight, water, temperature, soil, gases, minerals\n\n**Examples of ecosystems:**\n🌊 Ocean, coral reef, estuary\n🌲 Rainforest, boreal forest, savannah\n🏜️ Desert, tundra\n💧 Freshwater lake, river, wetland\n🌾 Grassland, prairie\n🏙️ Even cities have their own urban ecosystems!\n\n**The biosphere** = all ecosystems combined. It's the thin layer of life on Earth's surface — just 20km from deep ocean to high atmosphere.\n\n**Ecology** is the scientific study of ecosystems. Every ecosystem study tells us something about sustainability, conservation, and our own survival on this planet! 🔬",
      highlight: "Ecosystems include ALL living AND non-living components — the entire biosphere is interconnected as one giant ecosystem! 🌍",
    },
    {
      id: 'food_chains',
      title: 'Food Chains & Webs 🔗',
      color: '#F39C12',
      bgGradient: ['#1A0A00', '#030D08'],
      icon: '🔗',
      svgIcon: 'link',
      content: "A **food chain** shows the flow of energy from one organism to the next in a linear sequence.\n\n**Example:**\n🌿 Grass → 🦗 Grasshopper → 🐸 Frog → 🐍 Snake → 🦅 Eagle\n\n**Trophic levels** (energy tiers):\n1️⃣ **Producers** — make energy from sunlight (photosynthesis) or chemicals (chemosynthesis)\n2️⃣ **Primary consumers** — eat producers (herbivores)\n3️⃣ **Secondary consumers** — eat primary consumers (carnivores/omnivores)\n4️⃣ **Tertiary consumers** — apex predators\n\nBut real life is more complex — a **food WEB** shows all the interconnected feeding relationships in an ecosystem. A fox eats rabbits, birds, berries, and voles — it participates in many chains simultaneously!\n\n**Decomposers** (bacteria, fungi) are crucial — they break down dead organisms, returning nutrients to the soil for producers. Without them, nutrients would be locked in corpses forever! 🍄\n\n**Detritivores** (earthworms, woodlice) physically break apart dead matter, helping decomposers access it. 🪱",
      highlight: "Food chains show energy flow — real ecosystems are food WEBS of thousands of interconnected chains! 🔗",
    },
    {
      id: 'energy_pyramid',
      title: 'The Energy Pyramid 🔺',
      color: '#E74C3C',
      bgGradient: ['#2A0A0A', '#030D08'],
      icon: '🔺',
      svgIcon: 'chart',
      content: "The **10% energy rule** is one of the most important laws in ecology:\n\n**Only ~10% of energy transfers to the next trophic level.**\nThe other ~90% is lost as heat (cellular respiration), movement, and body maintenance.\n\n**Example:**\n🌿 Grass captures 10,000 kJ of solar energy\n🦗 Grasshoppers get only 1,000 kJ (10%)\n🐸 Frog gets only 100 kJ (10% of 10%)\n🐍 Snake gets only 10 kJ\n🦅 Eagle gets only 1 kJ!\n\n**Why this matters profoundly:**\n🌾 Eating plants is ~10x more energy efficient than eating meat\n🐄 It takes ~8kg of grain to produce 1kg of beef\n🌍 If everyone ate one less meat meal per week, it would have more climate impact than the entire transport sector switching to electric cars!\n\n**Ecological pyramids:**\n📊 Pyramid of energy — always upright\n📊 Pyramid of biomass — usually upright\n📊 Pyramid of numbers — can be inverted (one tree supports thousands of insects) 🌳",
      highlight: "Only 10% of energy passes to the next trophic level — eating plants is 10x more efficient than eating meat! 🔺",
    },
    {
      id: 'nitrogen_carbon_cycles',
      title: 'The Great Element Cycles ♻️',
      color: '#3498DB',
      bgGradient: ['#0A1020', '#030D08'],
      icon: '♻️',
      svgIcon: 'cycle',
      content: "Elements cycle endlessly through ecosystems — atoms in your body were once in dinosaurs, then drifted as CO₂, then were locked in limestone.\n\n**Carbon Cycle:**\n☀️ Photosynthesis — removes CO₂ from atmosphere, stores in plants\n🌬️ Respiration — releases CO₂ from all living things\n💀 Decomposition — releases CO₂ from dead matter\n🏭 Combustion — releases ancient stored carbon (fossil fuels) → PROBLEM\n\n**Nitrogen Cycle:**\nNitrogen (N₂) makes up 78% of air but most organisms can't use it directly!\n🦠 **Nitrogen-fixing bacteria** (Rhizobium in legume roots) convert N₂ → ammonium (NH₄⁺)\nPlants absorb ammonium/nitrates → make proteins\nAnimals eat plants → use nitrogen in amino acids\n🦠 **Decomposers** break proteins → back to ammonium\n🦠 **Nitrifying bacteria** convert ammonium → nitrites → nitrates (plant food! 🌱)\n🦠 **Denitrifying bacteria** convert nitrates → N₂ back to atmosphere\n\n**Water Cycle:** Evaporation → condensation → precipitation → transpiration → back!\n\nHuman disruption of these cycles (CO₂ from fossil fuels, nitrogen fertilisers) is reshaping ecosystems globally. 🌍",
      highlight: "Nitrogen-fixing bacteria in soil convert atmospheric N₂ into forms plants can use — without them, all life would starve! ♻️",
    },
    {
      id: 'predator_prey',
      title: 'Predator-Prey Dynamics 🐺🐰',
      color: '#9B59B6',
      bgGradient: ['#1A0A2A', '#030D08'],
      icon: '🐺',
      svgIcon: 'target',
      content: "Predator and prey populations are locked in a perpetual dance — they regulate each other in cycles.\n\n**Lotka-Volterra equations** model predator-prey dynamics:\n📈 Prey increases → more food for predators → predator population rises\n📉 More predators → prey hunted faster → prey population falls\n📉 Less prey → predators starve → predator population falls\n📈 Fewer predators → prey recovers → cycle repeats! 🔄\n\n**Classic example:** Snowshoe hare and Canadian lynx populations cycle with ~10-year periods — perfectly recorded in 200 years of Hudson Bay Company fur trade records!\n\n**Keystone species** — species with disproportionately large effects on their ecosystem:\n🐺 Wolves in Yellowstone\n🦦 Sea otters (control sea urchins that destroy kelp forests)\n🐘 Elephants (create water holes, open forests)\n🦈 Sharks (regulate prey populations throughout ocean food webs)\n\nRemoving a keystone species can cause **trophic cascade** — collapse of multiple other species, cascading down the food web! ⚡",
      highlight: "Predator-prey populations cycle in waves — removing a keystone species triggers a trophic cascade affecting the entire ecosystem! 🐺",
    },
    {
      id: 'biodiversity',
      title: 'Biodiversity & Why It Matters 🌈',
      color: '#00BCD4',
      bgGradient: ['#0A1A1A', '#030D08'],
      icon: '🌈',
      svgIcon: 'sparkle',
      content: "**Biodiversity** = the variety of life. It has three levels:\n🧬 **Genetic diversity** — variation within a species\n🐾 **Species diversity** — number and abundance of different species\n🌍 **Ecosystem diversity** — variety of habitats and ecosystems\n\n**Why biodiversity matters:**\n🌾 **Food security** — diverse crop genetics prevent total crop failure\n💊 **Medicine** — 50% of drugs derived from natural compounds (aspirin from willow bark, penicillin from mould, taxol from yew tree for cancer!)\n💧 **Ecosystem services** — pollination, water purification, soil formation, flood control, climate regulation — worth $125-145 TRILLION/year!\n🧬 **Resilience** — diverse ecosystems recover better from disturbance\n🧪 **Science** — every species offers insights into evolution, genetics, chemistry\n\n**Current biodiversity crisis:**\nWe are in Earth's **6th mass extinction** — driven by humans:\n🌲 Habitat destruction (deforestation)\n🏭 Pollution and climate change\n🎣 Overhunting/overfishing\n🦠 Invasive species\n\nSpecies are disappearing 100-1000x faster than background extinction rate. The previous 5 mass extinctions took millions of years to recover from. 😢",
      highlight: "Biodiversity provides $125 trillion in ecosystem services per year — we're currently causing Earth's 6th mass extinction! 🌈",
    },
    {
      id: 'biomes',
      title: 'Major Biomes of Earth 🗺️',
      color: '#27AE60',
      bgGradient: ['#042008', '#030D08'],
      icon: '🗺️',
      svgIcon: 'globe',
      content: "**Biomes** are major regions of Earth defined by their climate, vegetation, and wildlife. Each biome has adapted organisms perfectly suited to its conditions.\n\n**Major terrestrial biomes:**\n🌧️ **Tropical Rainforest** — 12°N-12°S; warm, 2m+ rain/year; 50% of land species in 6% of land; Amazon, Congo, SE Asia\n🌾 **Tropical Savannah** — warm with seasonal rain; grasses + sparse trees; African plains\n🏜️ **Desert** — <250mm rain/year; extreme temp swings; 1/3 of land surface!\n🌿 **Temperate Grassland** — prairie, steppe, pampas; no trees; now mostly farmland\n🌲 **Temperate Deciduous Forest** — 4 seasons; oaks, beeches, maples; Europe, Eastern NA\n🌲 **Boreal Forest (Taiga)** — largest biome by land area; conifers; Alaska to Russia\n❄️ **Tundra** — Arctic; permafrost; extreme cold; fragile low-growing plants\n\n**Marine biomes:**\n🪸 Coral reefs — ocean's rainforests (25% of marine species, 1% of ocean floor!)\n🌊 Open ocean (pelagic zone) — largest by volume\n🌑 Deep sea (abyssal zone) — no light, extreme pressure, chemosynthetic bacteria! 🦠",
      highlight: "Tropical rainforests cover 6% of land but host 50% of all species — coral reefs support 25% of marine species on 1% of ocean floor! 🗺️",
    },
    {
      id: 'succession',
      title: 'Ecological Succession 🌱→🌲',
      color: '#8BC34A',
      bgGradient: ['#0A1A05', '#030D08'],
      icon: '🌱',
      svgIcon: 'leaf',
      content: "**Ecological succession** is the predictable process by which ecosystems change over time — from bare rock to complex forest.\n\n**Primary succession** (bare substrate — no soil):\n🪨 Bare rock → Pioneer species (lichens break rock, build soil) → Mosses → Grasses → Shrubs → Young trees → **Climax community** (mature, stable forest)\n\nThis can take **100-1000+ years**!\n\n**Secondary succession** (soil already exists — after disturbance):\n🔥 Abandoned farm/burned forest → Weeds (within weeks) → Grasses → Shrubs → Pioneer trees → **Climax forest** (decades)\n\n**Pioneer species** are ecosystem engineers:\n🌿 **Lichens** — first colonisers of bare rock; slowly weather it into soil\n🌱 **Nitrogen-fixers** (legumes, alder) — enrich soil for other plants\n🌾 Annual plants with windborne seeds — quickly colonise open areas\n\n**The Krakatau experiment!** After the 1883 eruption obliterated all life on Krakatau island, scientists tracked recolonisation from bare rock. Within 50 years, it had a complex forest — demonstrating succession in real time! 🌋\n\nSuccession shows nature's incredible resilience and capacity for self-repair. 🌱",
      highlight: "Primary succession from bare rock to forest takes 100-1000 years — Krakatau island was recolonised from zero after the 1883 eruption! 🌱",
    },
    {
      id: 'climate_change_ecosystems',
      title: 'Climate Change & Ecosystems 🌡️',
      color: '#FF5722',
      bgGradient: ['#2A0800', '#030D08'],
      icon: '🌡️',
      svgIcon: 'thermometer',
      content: "Climate change is the greatest threat to ecosystems in human history — and understanding ecology explains exactly why.\n\n**Direct impacts:**\n🌡️ **Temperature rise** — species must migrate poleward or to higher altitude, or go extinct\n🌊 **Sea level rise** — coastal ecosystems (mangroves, coral reefs, wetlands) submerge\n❄️ **Permafrost thaw** — releases stored methane (powerful greenhouse gas) — a feedback loop!\n☔ **Altered rainfall** — desertification and flooding\n\n**Phenological mismatch:**\n🌸 Flowers bloom earlier (warmer springs)\n🦋 Insects emerge at different times\n🐦 Migratory birds arrive at old times\nResult: Plants flower with no pollinators; caterpillars hatch with no birds to eat them — entire food webs desynchronise! ⏰\n\n**Ocean acidification:**\nCO₂ + H₂O → carbonic acid → lowers ocean pH\n🪸 Coral skeletons dissolve; shellfish can't form shells\n🦀 Pteropods (ocean snails) — key marine food web base — are dissolving\n\n**Feedback loops amplify warming:**\n❄️ Loss of Arctic ice → less sunlight reflected → more warming\n🌊 Warmer oceans absorb less CO₂\n🌲 Forest death → less carbon sequestration → more CO₂ 📈",
      highlight: "Climate change causes phenological mismatch — flowers bloom when pollinators aren't ready, desynchronising entire food webs! 🌡️",
    },
    {
      id: 'conservation',
      title: 'Conservation Science 🛡️',
      color: '#009688',
      bgGradient: ['#041410', '#030D08'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "**Conservation science** applies ecological knowledge to protect biodiversity and ecosystems.\n\n**Protected areas:**\n🌲 **National Parks** — 15% of land protected globally\n🌊 **Marine Protected Areas** — only 7% of oceans protected (should be 30%!)\n🔗 **Wildlife corridors** — connecting fragmented habitats so animals can move and breed\n\n**Rewilding:**\nDeliberately introducing keystone species to restore ecosystem function:\n🐺 Wolves in Yellowstone\n🦫 Beavers in UK rivers (create wetlands, regulate floods)\n🦁 Lions in Africa...\nResults can be dramatic and rapid!\n\n**IUCN Red List:** Scientists assess every known species' extinction risk:\n❌ **Extinct** (EX) — gone forever\n🔴 **Critically Endangered** (CR)\n🟠 **Endangered** (EN)\n🟡 **Vulnerable** (VU)\n🟢 **Least Concern** (LC)\n~42,000 species currently threatened!\n\n**Ecosystem services valuation:**\nAssigning economic value to nature's services:\n💧 Clean water provision: Amazon rainforest = $8.2 billion/year\n🌾 Pollination worldwide: $235-577 billion in crop value annually\n🛡️ Coastal protection by mangroves: $80 billion/year\n\nWhen we understand ecosystems, we understand our own survival! 🌍",
      highlight: "Rewilding wolves in Yellowstone changed rivers — 42,000 species are currently threatened with extinction on the IUCN Red List! 🛡️",
    },
  ],

  lab: {
    title: "Ecosystem Dynamics Lab 🌍",
    description: "Control prey population, predator numbers, plant resources, and CO₂ pollution. Discover the Lotka-Volterra cycle and trophic cascades!",
    hint: "Push predator numbers above 80% with low prey — watch the ecosystem collapse! Then try achieving perfect trophic balance. 🌍",
    scientistModeHint: "In Scientist Mode: discover trophic cascades, carrying capacity crashes, and carbon sequestration dynamics! 🧑‍🔬",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why removing wolves from Yellowstone changed the rivers? 🐺",
      answer: "When wolves were removed, elk/deer populations exploded and grazed riverbanks bare. Without vegetation roots, banks eroded. When wolves returned in 1995, deer avoided riverbeds (fear!), vegetation recovered, roots stabilised banks, and rivers narrowed and straightened — an effect called a 'trophic cascade'. The fear of wolves changed the physical landscape! This proved that top predators engineer entire ecosystems. 🏞️",
      emoji: '🐺',
    },
    {
      id: 'dyk2',
      question: "Do you know why bees are more important to the global economy than all zoos combined? 🐝",
      answer: "Honeybees and wild pollinators pollinate 75% of the world's food crops by volume. The economic value is estimated at $235-577 billion per year globally. Without pollinators, almonds, avocados, blueberries, coffee, cocoa (chocolate!), and thousands of other crops would disappear. Einstein's alleged quote — 'If bees disappeared, humans would have 4 years left' — while exaggerated, captures the reality that bee decline IS an agricultural and food security crisis. 🌍",
      emoji: '🐝',
    },
    {
      id: 'dyk3',
      question: "Do you know why cutting down rainforest actually reduces rainfall in nearby regions? 🌧️",
      answer: "Trees are giant water pumps — a single large tree can transport 1,000+ litres of water per day from soil to atmosphere through transpiration. Forests create their own rainfall: moisture evaporated from one tree condenses and rains further inland, only to be re-evaporated. The Amazon rainforest creates 'flying rivers' of moisture moving thousands of km inland. When you deforest, you break this cycle — rainfall can drop 25-30% in nearby regions, turning productive farmland to dust. Deforestation is self-defeating! ☁️",
      emoji: '🌧️',
    },
    {
      id: 'dyk4',
      question: "Do you know why sea otters are keystone species for entire coastlines? 🦦",
      answer: "Sea otters eat sea urchins. Without otters, urchin populations explode and graze kelp forests to bare rock ('urchin barrens'). Kelp forests are critically important ocean habitats — supporting hundreds of species, protecting coastlines from erosion, and sequestering carbon. When otters were hunted to near-extinction, entire Pacific coastlines transformed from thriving kelp forests to empty urchin barrens within decades. Otter reintroduction reversed this. One small mammal sustains an entire coastal ecosystem! 🌊",
      emoji: '🦦',
    },
    {
      id: 'dyk5',
      question: "Do you know why permafrost thawing is called a 'tipping point' for climate change? ❄️",
      answer: "Permafrost (permanently frozen ground in Arctic regions) stores twice as much carbon as is currently in the atmosphere — accumulated from thousands of years of dead organic matter. As global temperatures rise, permafrost thaws and bacteria decompose this organic matter, releasing CO₂ and methane (30x more powerful greenhouse gas). This extra warming causes MORE permafrost to thaw, releasing MORE greenhouse gases — an unstoppable self-reinforcing feedback loop. Once tipped, it could add 1.5°C of warming independently of any human action! 🌡️",
      emoji: '❄️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the '10% rule' in ecology? 🔺", options: ['10% of animals are predators', '10% of plants produce seeds', 'Only 10% of energy transfers to the next trophic level', 'Ecosystems lose 10% of species per decade'], answer: 2, explanation: "At each trophic level, only ~10% of energy passes to the next — the rest lost as heat from metabolism. So 10,000 kJ of plant energy becomes 1,000 kJ of herbivore, 100 kJ of carnivore, only 10 kJ of apex predator! 🔺" },
    { id: 'q2', question: "What is a 'keystone species'? 🔑", options: ['The most numerous species in an ecosystem', 'A species with disproportionately large effects on ecosystem structure', 'The first species to colonise a new habitat', 'An extinct species that shaped modern ecosystems'], answer: 1, explanation: "Keystone species have effects far larger than their population size would suggest. Wolves, sea otters, elephants, and sharks shape entire ecosystems — their removal causes trophic cascades! 🐺" },
    { id: 'q3', question: "What role do nitrogen-fixing bacteria play in ecosystems? 🌱", options: ['They break down dead organisms into CO₂', 'They convert atmospheric N₂ into forms plants can absorb', 'They produce oxygen in the soil', 'They transport nitrogen through water'], answer: 1, explanation: "Most organisms can't use atmospheric nitrogen (N₂) directly. Nitrogen-fixing bacteria (like Rhizobium in legume roots) convert N₂ into ammonium/nitrates that plants can absorb — without them, most life couldn't access nitrogen for proteins! 🦠" },
    { id: 'q4', question: "What is a food web? 🕸️", options: ['A linear sequence of who eats whom', 'A diagram showing all interconnected feeding relationships in an ecosystem', 'The total amount of food available in an ecosystem', 'The routes that animals use to find food'], answer: 1, explanation: "Unlike a food chain (linear sequence), a food web shows ALL the complex, overlapping feeding relationships in an ecosystem. Most organisms are part of multiple food chains simultaneously! 🕸️" },
    { id: 'q5', question: "What is ecological succession? 🌱", options: ['How species compete for the same food', 'The predictable progression of communities in an ecosystem from bare substrate to climax community', 'How predators track prey across seasons', 'The annual migration cycle of birds'], answer: 1, explanation: "Succession is the orderly process by which ecosystems develop over time. Primary succession starts on bare rock (1000+ years to mature forest). Secondary succession (after disturbance) is faster since soil already exists! 🌲" },
    { id: 'q6', question: "Why is biodiversity important for medicine? 💊", options: ['Diverse ecosystems produce more oxygen', 'Many medicinal drugs are derived from natural compounds found in diverse organisms', 'Biodiversity reduces the spread of disease', 'More species means more food for humans'], answer: 1, explanation: "About 50% of all medicines trace back to natural compounds! Aspirin from willow bark, penicillin from mould, taxol (cancer drug) from yew trees, morphine from poppies. Each species lost could be a cure lost! 💊" },
    { id: 'q7', question: "What is 'phenological mismatch' caused by climate change? ⏰", options: ['Animals migrating to the wrong locations', 'Seasonal events becoming misaligned — e.g. flowers bloom when pollinators aren\'t ready', 'Predators and prey populations falling out of sync over decades', 'Ocean and land temperatures warming at different rates'], answer: 1, explanation: "Climate change shifts the timing of biological events (phenology) but by different amounts for different species. Flowers bloom earlier, but bees or migratory birds haven't adjusted — they arrive to find no food, or flowers with no pollinators! ⏰" },
    { id: 'q8', question: "What percentage of marine species live in coral reefs? 🪸", options: ['5%', '15%', '25%', '50%'], answer: 2, explanation: "Coral reefs cover less than 1% of the ocean floor but support approximately 25% of all marine species — making them the ocean's equivalent of tropical rainforests in terms of biodiversity concentration! 🪸" },
    { id: 'q9', question: "What is ocean acidification? 🌊", options: ['Seawater becoming saltier due to evaporation', 'CO₂ dissolving in oceans to form carbonic acid, lowering pH', 'Industrial chemicals dumped in the ocean', 'Natural volcanic activity releasing acids underwater'], answer: 1, explanation: "As atmospheric CO₂ rises, oceans absorb ~30% of it. CO₂ + H₂O → carbonic acid, lowering ocean pH. This dissolves coral skeletons, prevents shellfish from forming shells, and disrupts marine food webs! 🪸" },
    { id: 'q10', question: "The Lotka-Volterra model describes: 🔄", options: ['How plants absorb sunlight in an ecosystem', 'The cycling oscillation of predator-prey populations over time', 'How biodiversity changes with altitude and latitude', 'The succession from grassland to forest'], answer: 1, explanation: "Lotka-Volterra equations predict the oscillating cycles of predator and prey populations — prey rises (more food for predators), predators rise (fewer prey), prey falls (predators starve), predators fall (prey recovers). This cycling pattern is seen in nature worldwide! 🐺🐰" },
  ],

  relatedTopics: ['evolution_natural', 'photosynthesis', 'cell_structure', 'human_body_systems'],
};
