export default {
  // ── IDENTITY ────────────────────────────────
  id: 'evolution_natural',
  title: 'Evolution & Natural Selection',
  subtitle: 'How life adapts, survives, and conquers 🦋',
  emoji: '🦋',
  category: 'Biology',
  accentKey: 'evolution',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "Do you know that you share 50% of your DNA with a banana?",
    reveal: "It's true! 🍌 All life on Earth—from the massive Blue Whale down to the grass in your yard—shares a single common ancestor that lived billions of years ago. Through a brilliant, brutal, and incredibly slow process called 'Natural Selection', nature sculpted that single microscopic organism into every living thing you see today. Let's travel through deep time and see how evolution actually works!",
    emoji: '🧬',
  },

  // ── THEORY CARDS (10) ───────────────────────
  theory: [
    {
      id: 'what_is_evolution',
      title: 'What is Evolution? ⏳',
      color: '#4CA050',
      bgGradient: ['#0A1A0F', '#050D0A'],
      icon: '⏳',
      svgIcon: 'dna',
      content: "Evolution is simply biological change over time.\n\nIt is the process by which modern organisms have descended from ancient ancestors. Millions of years ago, the ancestors of modern horses were the size of small dogs. Over thousands of generations, their bodies slowly mutated to become taller and faster to escape predators in open grasslands.\n\nEvolution doesn't happen to an *individual* during its lifetime. It happens to an entire *population* over hundreds of generations.",
      highlight: "Evolution is entirely driven by random genetic mutations. 🎲",
    },
    {
      id: 'charles_darwin',
      title: 'Charles Darwin & The HMS Beagle 🚢',
      color: '#3B82F6',
      bgGradient: ['#05101A', '#050D0A'],
      icon: '🚢',
      svgIcon: 'globe',
      content: "In 1831, a 22-year-old British naturalist named Charles Darwin boarded a ship called the HMS Beagle for a 5-year voyage around the world.\n\nWhen he reached the isolated Galapagos Islands, he noticed something shocking: the Finches (small birds) on each neighboring island looked almost identical, except for their beaks. Some had thick crushing beaks for cracking nuts. Others had thin, needle-like beaks for picking insects out of wood.\n\nDarwin realized they all came from one original flock, but *adapted* to the different food available on each island!",
      highlight: "Darwin published his world-changing book, 'On the Origin of Species', in 1859. 📖",
    },
    {
      id: 'natural_selection',
      title: 'Survival of the Fittest 🥊',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🥊',
      svgIcon: 'target',
      content: "Darwin's greatest idea was the *mechanism* of evolution, which he called **Natural Selection**.\n\nIt relies on 3 simple rules:\n1. **Variation:** Not all babies look the same (mutations happen).\n2. **Competition:** There isn't enough food/space for everyone, so organisms must fight to survive.\n3. **Selection:** The organisms with the best random mutations (e.g., thicker fur in the cold, longer legs to run) survive and have babies. The weaker ones die.\n\nNature 'selects' the winners!",
      highlight: "'Fittest' doesn't just mean strongest. It means 'best fitted' to the current environment! 🌱",
    },
    {
      id: 'mutations',
      title: 'Mutations: The Engine of Change 🧬',
      color: '#A855F7',
      bgGradient: ['#1A0A1F', '#050D0A'],
      icon: '🧬',
      svgIcon: 'hash',
      content: "Why are babies different from their parents?\n\nWhen cells divide to make eggs or sperm, they have to copy 3 billion letters of DNA. Sometimes, they make a 'typo'. This typo is a **Mutation**.\n\nMost mutations do nothing. Some are deadly. But very rarely, a mutation gives an animal an incredible advantage—like a moth born with naturally black wings that help it hide in the dark shadows of a forest. That lucky moth survives, breeds, and passes the 'dark wing' typo to its babies!",
      highlight: "Without random genetic mutations, evolution completely stops. We would still be single-celled bacteria! 🦠",
    },
    {
      id: 'artificial_selection',
      title: 'Artificial Selection 🐕',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🐕',
      svgIcon: 'person',
      content: "If *Nature* does Natural Selection, what happens when humans take control? We get **Artificial Selection** (also called selective breeding).\n\nEvery single breed of dog—from the tiny Chihuahua to the massive Great Dane—was artificially engineered by humans. Starting with wild grey wolves, ancient humans simply took the friendliest wolves and bred them together. Then bred the smallest ones together. Over thousands of years, we literally steered their evolution to design our perfect pets!",
      highlight: "Broccoli, cauliflower, kale, and cabbage are all actually the exact same wild mustard plant, selectively bred by humans to look different! 🥦",
    },
    {
      id: 'fossils',
      title: 'The Fossil Record 🦴',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🦴',
      svgIcon: 'leaf',
      content: "How do we know evolution is real? The earth kept a diary! \n\nWhen animals die and are rapidly buried in mud or ash, the minerals slowly turn their bones into stone, creating **Fossils**.\n\nWhen scientists dig deep into the earth, they consistently find older, simpler organisms buried at the bottom, and more complex, modern organisms near the top. We have actually found perfectly preserved \"transitional fossils\" showing dinosaurs slowly evolving feathers and turning into modern birds!",
      highlight: "The mighty T-Rex is evolutionarily closer in time to your iPhone than it was to the Stegosaurus! 🦖",
    },
    {
      id: 'convergent',
      title: 'Convergent Evolution 🦈🐬',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🦈',
      svgIcon: 'water',
      content: "Sometimes, nature solves the exact same problem twice.\n\nLook at a Shark (a fish) and a Dolphin (a mammal). They look incredibly similar: grey, streamlined bodies with dorsal fins and flippers. \n\nBut their ancestors are completely different! The Dolphin's ancestor was a dog-like land animal that walked back into the ocean. However, because both the shark and dolphin had to survive by swimming fast in the ocean, natural selection independently molded their bodies into the exact same shape! This is called **Convergent Evolution**.",
      highlight: "Bats (mammals) and Birds (dinosaurs) entirely independently evolved the ability to fly! 🦇🦅",
    },
    {
      id: 'vestigial',
      title: 'Vestigial Structures: Ghosts of the Past 👻',
      color: '#FF007F',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '👻',
      svgIcon: 'person',
      content: "Evolution isn't perfect. As animals change, they often keep absolutely useless leftover parts from their ancient ancestors, called **Vestigial Structures**.\n\nWhy do you get goosebumps when you are cold? Because your furry ancestors used that muscle to puff up their thick fur to trap heat! Since humans evolved to have no fur, puffing up does absolutely nothing, but the automatic reflex survived!\n\nOther human leftovers include your tailbone (from when we had tails) and your wisdom teeth.",
      highlight: "Whales actually still have a tiny, completely useless hip and leg bone floating inside their bodies from when they used to walk on land! 🐋",
    },
    {
      id: 'micro_macro',
      title: 'Micro vs Macro Evolution 🔬',
      color: '#7B2CBF',
      bgGradient: ['#0D051A', '#050D0A'],
      icon: '🔬',
      svgIcon: 'microscope',
      content: "Evolution happens at two scales.\n\n**Micro-Evolution:** Small changes within a species. For example, a population of beetles changing from green to brown over 10 years to hide on dead trees.\n\n**Macro-Evolution:** Massive changes over millions of years resulting in entirely new species. If you give Micro-Evolution enough time (millions of years), the genetic code changes so drastically that the animals can no longer breed together. They have permanently split into two different species!",
      highlight: "Lions and Tigers split apart relatively recently. They can still breed together to make 'Ligers', but Ligers are born sterile! 🦁🐅",
    },
    {
      id: 'extinction',
      title: 'Extinction: The Ultimate Test 🪦',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '🪦',
      svgIcon: 'alert',
      content: "If a species cannot adapt fast enough to a changing environment, it fails the test of Natural Selection and goes **Extinct**.\n\nOver 99% of all species that have *ever* lived on Earth are currently extinct!\n\nMass extinction events, like the asteroid that wiped out the dinosaurs 65 million years ago, hit the 'reset' button on life. But out of the ashes comes opportunity. The death of the giant dinosaurs allowed small, hiding mammals to finally emerge, evolve, and eventually become humans! ☄️",
      highlight: "We are currently living in the 'Sixth Mass Extinction' event, heavily driven by human destruction of habitats. 🌍",
    },
  ],
  
  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Darwin's Ecosystem Simulator 🦋",
    description: "Take control of the forces of evolution! You have 4 mini-simulations: Alter weather patterns to force finches to mutate their beaks, play the role of a predator in the Peppered Moth game, witness real-time antibiotic resistance, and trace the phylogenetic tree of humanity.",
    hint: "If rainfall is high, soft seeds grow, and birds with small, quick beaks survive best. If it is dry, only hard nuts grow, heavily favoring birds with massive crushing beaks!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time generational mortality rates and allele frequency shifts.",
  },

  // ── DO YOU KNOW WHY (5) ─────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why elephants are suddenly evolving to be born completely without tusks in Africa? 🐘",
      answer: "Because humans altered natural selection! Poachers illegally hunt and kill elephants with large tusks for ivory. Therefore, elephants with a genetic mutation causing them to have NO tusks are suddenly the ONLY ones surviving long enough to have babies. They pass on the 'tuskless' gene, rapidly changing the entire species to survive human poaching. 😞",
      emoji: '🚫',
    },
    {
      id: 'dyk2',
      question: "Do you know why human skin colors evolved to be different? 🧑🏾🧑🏼",
      answer: "It is an evolutionary adaptation to UV radiation (sunlight)! Humans living near the fiery equator evolved dark skin rich in Melanin, which acts as a natural sunscreen protecting DNA from skin cancer. Humans who migrated to cold, cloudy northern regions (like Europe) evolved pale skin because they *needed* to absorb the weak sunlight to produce enough Vitamin D for their bones. ☀️",
      emoji: '🌍',
    },
    {
      id: 'dyk3',
      question: "Do you know why blind cave fish completely lost their eyes? 🐟",
      answer: "Because eyes are incredibly biologically expensive to grow and maintain! In a pitch-black cave, having eyes gives you zero advantage. Worse, if they get scratched, they get infected. Fish possessing a genetic mutation making them born *without* eyes saved massive amounts of energy and simply out-competed the seeing fish in the darkness! 🌑",
      emoji: '🦇',
    },
    {
      id: 'dyk4',
      question: "Do you know why the Flu virus requires a brand new vaccine almost every single year while Polio only needed one? 💉",
      answer: "Rapid micro-evolution! Viruses like the Flu or COVID-19 have incredibly sloppy, fast-mutating RNA. They 'evolve' their shape so rapidly that the antibodies your immune system made last year literally don't recognize the new evolved shape this year. Our scientists are in an ongoing evolutionary arms race against microscopic invaders! 🦠",
      emoji: '🛡️',
    },
    {
      id: 'dyk5',
      question: "Do you know why peacocks evolved such massive, heavy, brightly colored tails that make it hard to fly and attract predators? 🦚",
      answer: "This is 'Sexual Selection', a special type of natural selection! While the giant tail is technically terrible for survival, female peahens find it irresistibly attractive. A male with a huge tail is basically flexing: 'I am so genetically healthy and strong that I can survive even while dragging this giant target around'. So, the flashy ones get ALL the mates! ✨",
      emoji: '🪶',
    },
  ],

  // ── QUIZ (20) ───────────────────────────────
  quiz: [
    { id: 'q1', question: "What is biological evolution?", options: ["Learning new behaviors", "Population change over time", "Sudden creation of life", "Instant physical transformation"], answer: 1, explanation: "Evolution is the natural change in the genetic traits of a biological *population* over successive generations. ⏳" },
    { id: 'q2', question: "Who wrote 'On the Origin of Species' and defined natural selection?", options: ["Scientist Albert Einstein", "Scientist Isaac Newton", "Scientist Charles Darwin", "Scientist Gregor Mendel"], answer: 2, explanation: "Charles Darwin proposed the theory of Evolution by Natural Selection in 1859! 🚢" },
    { id: 'q3', question: "For Natural Selection to occur, there must be variation. What causes new variation?", options: ["Desire to change", "Random genetic mutations", "Regular physical exercise", "Healthy daily diet"], answer: 1, explanation: "Random genetic 'typos' (mutations) in DNA create different traits. Nature then 'selects' the best ones! 🧬" },
    { id: 'q4', question: "In biology, what does 'Survival of the Fittest' mean?", options: ["Strongest individuals survive", "Most aggressive survive", "Best adapted survive", "Smartest individuals survive"], answer: 2, explanation: "Fittest means 'best fit'. If you live in a snowy forest, a slow white bear will survive better than a fast brown bear! 🐻‍❄️" },
    { id: 'q5', question: "Which island chain heavily inspired Darwin's theory after observing its finches?", options: ["The Hawaiian Islands", "The island Madagascar", "The Galapagos Islands", "The Canary Islands"], answer: 2, explanation: "The isolated Galapagos Islands featured animals that had clearly adapted from a single mainland ancestor. 🐢" },
    { id: 'q6', question: "When humans purposefully cross-breed the fastest horses to create racing horses, it is called:", options: ["Process of Natural Selection", "Process of Artificial Selection", "Process of Macro-Evolution", "Process of Genetic Drift"], answer: 1, explanation: "Artificial Selection (Selective Breeding) happens when humans, not nature, choose who survives and breeds. 🐎" },
    { id: 'q7', question: "What evidence of evolution is buried deep within the earth's crust?", options: ["Old buried photographs", "Old buried fossils", "Ancient genetic DNA", "Ancient cave paintings"], answer: 1, explanation: "Fossils are petrified remains that act as a geological timeline showing ancient ancestors evolving into modern animals. 🦴" },
    { id: 'q8', question: "Because a shark and a dolphin both swim fast in the ocean, they evolved similar streamlined shapes despite being unrelated. This is called:", options: ["Pattern of Sexual Selection", "Pattern of Divergent Evolution", "Pattern of Convergent Evolution", "Pattern of Artificial Selection"], answer: 2, explanation: "Convergent Evolution: Unrelated species independently evolve similar traits to solve the exact same environmental problem! 🦈🐬" },
    { id: 'q9', question: "The human tailbone and the whale's hip bone no longer serve any purpose. They are:", options: ["Essential body organs", "Vestigial body structures", "Random genetic mutations", "Harmful internal parasites"], answer: 1, explanation: "Vestigial structures are 'ghosts'—leftover anatomical parts from ancient ancestors that are completely useless today. 👻" },
    { id: 'q10', question: "What happens if an entire species cannot adapt fast enough to a massive climate change?", options: ["Rapidly mutate overnight", "Hibernate for eternity", "Go completely extinct", "Turn into plants"], answer: 2, explanation: "If they fail the test of natural selection, every single member dies, resulting in Extinction. 🪦" },
    { id: 'q11', question: "Why do peacocks have massive, heavy, colorful tails that attract predators?", options: ["To fight predators", "To attract mates", "To stay warm", "To fly faster"], answer: 1, explanation: "Sexual Selection! The females prefer the flashiest males, proving they are healthy enough to survive despite the big tail. 🦚" },
    { id: 'q12', question: "What is an example of Micro-Evolution?", options: ["Dinosaur to bird", "Ape to human", "Antibiotic resistant bacteria", "Fish growing lungs"], answer: 2, explanation: "Micro-evolution is small scale! Bacteria evolving resistance to our medicines over a few days is real-time evolution. 🦠" },
    { id: 'q13', question: "On dark, soot-covered trees, which moth has the highest chance of surviving hungry birds?", options: ["The white moths", "The black moths", "The green moths", "The blue moths"], answer: 1, explanation: "The black moth is camouflaged against the soot! The white ones stick out and get eaten immediately. 🦇" },
    { id: 'q14', question: "All modern breeds of dogs artificially evolved from which wild ancestor?", options: ["The Red Fox", "The Wild Coyote", "The Grey Wolf", "The Spotted Hyena"], answer: 2, explanation: "Ancient humans domesticated friendly Grey Wolves, artificially steering their evolution into Chihuahuas and Great Danes. 🐺" },
    { id: 'q15', question: "Why do humans native to the equator naturally have darker skin?", options: ["Absorb more heat", "Maintain specific diets", "Protect against UV radiation", "Sweat more efficiently"], answer: 2, explanation: "Melanin in dark skin acts as a natural sunscreen, preventing the intense sun from mutating DNA and causing skin cancer. ☀️" },
    { id: 'q16', question: "How long does macro-evolution (creating an entirely new complex species) generally take?", options: ["Five full years", "A few decades", "Millions of years", "One single lifetime"], answer: 2, explanation: "Macro-evolution is the accumulation of thousands of micro-mutations, requiring incredibly deep time (Millions of years). ⏳" },
    { id: 'q17', question: "Which event 65 million years ago wiped out 75% of life on Earth, including the non-avian dinosaurs?", options: ["The Ice Age", "Massive global flood", "Large asteroid impact", "Global volcanic activity"], answer: 2, explanation: "A massive 6-mile-wide asteroid hit Mexico, causing a dust cloud that blocked the sun and killed the dinosaurs. ☄️" },
    { id: 'q18', question: "What percentage of DNA do humans share with Chimpanzees?", options: ["Ten percent DNA", "Fifty percent DNA", "Eighty percent DNA", "Over ninety-eight percent"], answer: 3, explanation: "We share roughly 98.8% of our DNA with Chimpanzees. We didn't evolve *from* them, we simply share a very recent common ancestor! 🐵" },
    { id: 'q19', question: "Can a giraffe stretch its neck to reach high leaves, and then have a baby born with a longer neck?", options: ["Yes, physical changes inherit", "No, mutations drive evolution", "Only in dry seasons", "Only for male offspring"], answer: 1, explanation: "Physical changes during your life (like lifting weights) do not alter your DNA. Only genetic DNA mutations are passed down. 🦒" },
    { id: 'q20', question: "Without genetic mutations, what would happen?", options: ["Evolution would accelerate", "Animals would be perfect", "Evolution would stop", "Animals would live forever"], answer: 2, explanation: "Mutations are the engine! If all offspring were identical clones, the population could never change or adapt to new threats. 🛑" },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['dna_genetics', 'cell_structure', 'ancient_civilizations'],
};
