export default {
  id: 'solar_system',
  title: 'Solar System',
  subtitle: 'Planets, Moons, and our local neighborhood 🪐',
  emoji: '🪐',
  category: 'Space',
  accentKey: 'space',

  hook: {
    question: "How long would it take to drive a car to the Sun?",
    reveal: "If you got in a car and drove straight up at 60 mph (100 km/h) without ever stopping, it would take you 177 YEARS to reach the Sun! ☀️ Space is unfathomably, terrifyingly empty. All the planets you see in textbooks are drawn way too close together. If the Earth were the size of a marble, the Sun would be a giant yoga ball 300 yards away! Let's explore our massive, beautiful neighborhood.",
    emoji: '🚀',
  },

  theory: [
    {
      id: 'the_sun',
      title: 'The Sun (Our Star) ☀️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '☀️',
      svgIcon: 'star',
      content: "The Sun is the absolute boss of our neighborhood. It contains 99.8% of ALL the mass in the entire Solar System.\n\nIt is not solid—it is a gigantic ball of superheated Hydrogen and Helium plasma. In its core, gravity crushes atoms together so hard that they fuse into heavier elements (Nuclear Fusion), releasing the insane amounts of energy that light up our days and keep the Earth from freezing.",
      highlight: "Over 1 million Earths could fit inside the Sun! 🌍🌍🌍",
    },
    {
      id: 'inner_planets',
      title: 'The Rocky Planets 🪨',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🪨',
      svgIcon: 'earth',
      content: "The 4 planets closest to the sun are the 'Terrestrial' (rocky) planets: Mercury, Venus, Earth, and Mars.\n\nThey are relatively small, made of heavy metals and solid rock, and have very few moons. Mercury is blasted by the sun but has ice in its shadows. Venus is completely covered in a toxic runaway greenhouse effect, making it the hottest planet. Earth has liquid water. Mars is a frozen, rusty desert that used to have oceans.",
      highlight: "Venus is so hot that lead would instantly melt on its surface! 🔥",
    },
    {
      id: 'gas_giants',
      title: 'The Gas Giants 🌪️',
      color: '#3B82F6',
      bgGradient: ['#05101A', '#050D0A'],
      icon: '🌪️',
      svgIcon: 'planet',
      content: "Beyond the asteroid belt lie the monsters: Jupiter and Saturn.\n\nThese planets don't have solid surfaces! They are colossal spheres of swirling Hydrogen and Helium gas. If you tried to land on Jupiter, you would just fall through violent, crushing storms forever until the pressure crushed your spaceship.\n\nJupiter acts like a gravitational shield for Earth, using its massive pull to catch deadly asteroids before they can hit us!",
      highlight: "Jupiter's 'Great Red Spot' is a hurricane that has been raging for 300 years and is twice the size of Earth. 🔴",
    },
    {
      id: 'ice_giants',
      title: 'The Ice Giants 🧊',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧊',
      svgIcon: 'snowflake',
      content: "Way out in the freezing darkness are Uranus and Neptune.\n\nThey are similar to Gas Giants, but mostly made of 'ices' like frozen water, ammonia, and methane (which gives them their beautiful blue color).\n\nUranus is weird—it was knocked completely on its side long ago by a massive collision, so it rolls around the sun like a bowling ball! Neptune has the fastest winds in the solar system, whipping at 1,200 mph.",
      highlight: "It literally rains diamonds deep inside Neptune and Uranus due to insane atmospheric pressure! 💎",
    },
    {
      id: 'moons',
      title: 'The Weird Worlds of Moons 🌕',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌕',
      svgIcon: 'moon',
      content: "Planets aren't the only cool places; some Moons are even more likely to hold alien life!\n\nJupiter has 95 moons! The most famous is **Europa**, an ice ball that hides a massive, warm liquid water ocean underneath its frozen crust.\nSaturn's moon **Titan** is the only moon with a thick atmosphere, and it has literal lakes and rivers... but they are made of liquid methane, not water!",
      highlight: "Jupiter's moon 'Io' is the most volcanically active object in the solar system, constantly erupting lava! 🌋",
    },
    {
      id: 'asteroids',
      title: 'Asteroids & Comets ☄️',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '☄️',
      svgIcon: 'alert',
      content: "The solar system is full of leftover debris from its creation 4.5 billion years ago.\n\n**Asteroids** are giant space rocks, mostly found in the belt between Mars and Jupiter.\n**Comets** are 'dirty snowballs' made of dark rock and ice that live in the freezing outer edges. When their orbit brings them close to the sun, the sun's heat boils their ice, creating the beautiful glowing 'tail' we see in the sky!",
      highlight: "A comet's glowing tail doesn't point perfectly backwards—it is blown by the Solar Wind, so it always points exactly *away* from the sun! 🌬️",
    },
    {
      id: 'pluto',
      title: 'Poor Pluto (Dwarf Planets) 💔',
      color: '#A855F7',
      bgGradient: ['#1A0A1F', '#050D0A'],
      icon: '💔',
      svgIcon: 'snowflake',
      content: "Is Pluto a planet? No.\n\nIn 2006, scientists downgraded Pluto to a 'Dwarf Planet'. Why? Because we discovered thousands of other freezing ice balls flying around out near Pluto in the 'Kuiper Belt'. If we counted Pluto as a planet, we would have to count 50 others too!\n\nTo be a true planet, you must clear your orbit of all other debris. Pluto is too small to exert that kind of gravitational control.",
      highlight: "Pluto is so far away that sunlight takes 5.5 hours to reach it (it only takes 8 minutes to reach Earth)! 🕰️",
    },
    {
      id: 'gravity',
      title: 'Gravity: The Invisible Glue 🧲',
      color: '#7B2CBF',
      bgGradient: ['#0D051A', '#050D0A'],
      icon: '🧲',
      svgIcon: 'target',
      content: "Why do planets orbit the sun instead of flying off into deep space? Gravity.\n\nThe planets are essentially falling towards the sun! But because they are naturally moving sideways incredibly fast, they keep 'missing' the sun. This permanent, sideways free-fall is exactly what an Orbit is.\n\nThe heavier the object, the stronger its gravity. The Sun's gravity is so powerful it holds the solar system together across billions of miles.",
      highlight: "If you weighed 100 lbs on Earth, you would weigh a crushing 253 lbs on Jupiter due to its massive gravity! 🏋️",
    },
    {
      id: 'heliosphere',
      title: 'The Edge of the System 🛡️',
      color: '#FF007F',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "Where does the solar system end?\n\nThe Sun constantly blows out an invisible magnetic bubble called the **Heliosphere**. This bubble protects all the planets from deadly interstellar space radiation.\n\nIn 2012, NASA's Voyager 1 spacecraft (launched in 1977) finally pierced through the edge of this magnetic bubble and became the first human-made object to enter 'Interstellar Space'—the terrifyingly empty void between the stars.",
      highlight: "Voyager 1 carries a Golden Record holding human music and greetings in 55 languages, just in case aliens find it! 📀",
    },
    {
      id: 'goldilocks',
      title: 'The Goldilocks Zone 🌍',
      color: '#4CA050',
      bgGradient: ['#0A1A0F', '#050D0A'],
      icon: '🌍',
      svgIcon: 'leaf',
      content: "Why is Earth the only place with life?\n\nBecause we are in the 'Goldilocks Zone' (or Habitable Zone). We are not too close to the Sun (like Venus, where water boils instantly) and we are not too far (like Mars, where water freezes solid). \n\nWe are perfectly in the middle, allowing liquid water to exist on our surface. Without liquid water, the complex chemical reactions needed for biology and life simply cannot happen.",
      highlight: "Scientists are desperately searching the galaxy for other 'Exoplanets' that sit exactly in their star's Goldilocks Zone! 🔭",
    },
  ],

  lab: {
    title: "NASA Telemetry Lab 🚀",
    description: "Launch into 4 simulations! Rotate the 3D Orrery, test your orbital mechanics by Slingshotting a satellite around Jupiter, drag Earth through the Habitable Zone, and visualize the shocking scale of astronomical objects.",
    hint: "For the gravity slingshot game, if you aim too close to Jupiter, its gravity will crush your satellite. Aim just slightly off-center to steal momentum and get flung into deep space!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays true astronomical units (AU) and millions-of-kilometers metrics.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the footprints left by the Apollo astronauts on the Moon in 1969 are completely untouched today? 🥾",
      answer: "Because the Moon has absolutely no atmosphere! On Earth, wind blows dirt and rain washes away marks. Without an atmosphere, there is zero wind or weather. Unless a random meteor strikes the exact spot, those iconic footprints will stay completely perfect for millions of years. 🌕",
      emoji: '🌚',
    },
    {
      id: 'dyk2',
      question: "Do you know why Venus is hotter than Mercury, even though Mercury is much closer to the sun? 🔥",
      answer: "The Greenhouse Effect! Mercury is just exposed rock. Venus has an incredibly thick, heavy atmosphere made almost entirely of Carbon Dioxide. The sun's heat easily enters the clouds, but the CO2 completely traps the heat, baking the entire surface at a steady 900°F (475°C) day and night. 🌋",
      emoji: '🌫️',
    },
    {
      id: 'dyk3',
      question: "Do you know why Saturn has rings? 💍",
      answer: "Saturn's rings aren't solid hula-hoops! They are made of billions of chunks of glowing ice and rock, ranging from the size of a grain of sand to the size of a mountain. Scientists believe an ancient moon wandered too close to Saturn and was brutally ripped to shreds by Saturn's massive gravity! 🪐",
      emoji: '💥',
    },
    {
      id: 'dyk4',
      question: "Do you know why a day on Venus is actually LONGER than a year on Venus? ⏳",
      answer: "Venus rotates on its axis incredibly slowly. It takes 243 Earth-days for Venus to spin around once (one Venus Day). However, its orbit around the sun is faster! It only takes 225 Earth-days to complete a total lap around the Sun (one Venus Year). Yes, it takes longer to complete a day than a year! 🤯",
      emoji: '🗓️',
    },
    {
      id: 'dyk5',
      question: "Do you know why Mars is red? 🔴",
      answer: "It is literally rusting! Mars has a lot of iron in its soil. Billions of years ago, when Mars had an atmosphere and water, the iron reacted with oxygen to form iron oxide—which is the exact chemical name for Rust! The entire planet is covered in a fine layer of rusty dust. 🧲",
      emoji: '📉',
    },
  ],

  quiz: [
    { id: 'q1', question: "What percentage of the total mass in the solar system is contained within the Sun?", options: ['50%', '75%', '99.8%', '100%'], answer: 2, explanation: "The sun is so stupidly massive that everything else (all 8 planets and moons combined) making up only 0.2%. ☀️" },
    { id: 'q2', question: "What are the 4 terrestrial (rocky) planets?", options: ['Mercury, Venus, Earth, Mars', 'Jupiter, Saturn, Uranus, Neptune', 'Earth, Mars, Jupiter, Pluto', 'Venus, Earth, Mars, Moon'], answer: 0, explanation: "The inner four planets are solid, rocky worlds. 🪨" },
    { id: 'q3', question: "Which planet is completely made of swirling Hydrogen and Helium gas and has no solid surface?", options: ['Mars', 'Jupiter', 'Mercury', 'Venus'], answer: 1, explanation: "Jupiter (and Saturn) are Gas Giants! 🌪️" },
    { id: 'q4', question: "Which planet is the hottest in the solar system due to a runaway toxic greenhouse effect?", options: ['Mercury', 'Mars', 'Jupiter', 'Venus'], answer: 3, explanation: "Even though Mercury is closer, Venus's thick CO2 atmosphere totally traps the sun's heat. 🔥" },
    { id: 'q5', question: "Why is Earth the only planet we know of that currently supports life?", options: ['It has the biggest moon', 'It is made of gas', 'It sits exactly in the Goldilocks Zone', 'It creates its own light'], answer: 2, explanation: "The Goldilocks zone is the exact right distance from a star to allow liquid water to exist! 💧" },
    { id: 'q6', question: "Methane gas gives these two 'Ice Giant' planets their beautiful bright blue color:", options: ['Earth and Mars', 'Uranus and Neptune', 'Jupiter and Saturn', 'Mercury and Venus'], answer: 1, explanation: "Uranus and Neptune are the freezing Ice Giants at the edge of the system. 🧊" },
    { id: 'q7', question: "What is Saturn's gorgeous ring system actually made of?", options: ['Solid gold', 'Liquid water', 'Billions of chunks of floating ice and rock', 'Plasma'], answer: 2, explanation: "The rings are the shredded remains of moons or comets trapped in orbit! 🪐" },
    { id: 'q8', question: "The Asteroid Belt is located between the orbits of which two planets?", options: ['Earth and Mars', 'Mars and Jupiter', 'Jupiter and Saturn', 'Uranus and Neptune'], answer: 1, explanation: "It sits exactly on the border separating the Rocky planets from the Gas Giants. ☄️" },
    { id: 'q9', question: "Why is Pluto no longer considered a true planet?", options: ['It exploded', 'It was stolen by aliens', 'It was reclassified as a Dwarf Planet because it hasn\'t cleared its orbit', 'It crashed into Neptune'], answer: 2, explanation: "Pluto is just one of many thousands of ice-balls floating in the outer Kuiper belt. 💔" },
    { id: 'q10', question: "What is the invisible force that prevents planets from flying off into deep space?", options: ['Magnetism', 'Friction', 'Gravity', 'Wind'], answer: 2, explanation: "The Sun's massive gravity acts as the glue holding the entire spinning system together. 🧲" },
    { id: 'q11', question: "How does the Sun physically produce so much heat and light?", options: ['Burning coal', 'Nuclear Fission (splitting atoms)', 'Nuclear Fusion (crushing atoms together)', 'Reflecting other stars'], answer: 2, explanation: "The immense gravity crushes Hydrogen atoms into Helium, releasing nuclear energy! 💥" },
    { id: 'q12', question: "Which of Jupiter's terrifying storms has been raging for 300 years?", options: ['The Great Dark Spot', 'The Eye of Jupiter', 'The Great Red Spot', 'The Hexagon'], answer: 2, explanation: "The Great Red Spot is a hurricane twice the size of planet Earth! 🔴" },
    { id: 'q13', question: "Because of its intense gravity, if you jump on Jupiter, you would feel:", options: ['Much lighter', 'Exactly the same as Earth', 'A lot heavier, you\'d be crushed', 'You would float away'], answer: 2, explanation: "Jupiter has 2.5x the gravity of Earth. We would be completely crushed! 🏋️" },
    { id: 'q14', question: "What are comets mostly made out of?", options: ['Fire', 'Ice and dark dust (dirty snowballs)', 'Solid iron', 'Hot plasma'], answer: 1, explanation: "Comets are freezing ice balls that grow glowing tails when the Sun's heat begins to melt them! ☄️" },
    { id: 'q15', question: "Which spacecraft is the first human-made object to entirely leave the Solar System?", options: ['Apollo 11', 'The Hubble Telescope', 'Voyager 1', 'The Mars Rover'], answer: 2, explanation: "Voyager 1 escaped the Sun's magnetic bubble (Heliosphere) in 2012! 🛰️" },
    { id: 'q16', question: "Why doesn't the Moon have weather or wind?", options: ['It\'s too small', 'It spins too fast', 'It doesn\'t have an atmosphere', 'It\'s painted on the sky'], answer: 2, explanation: "Because it lacks an atmosphere, the Moon is completely silent and perfectly preserves astronaut footprints. 🥾" },
    { id: 'q17', question: "Which planet rolls slowly on its side like a bowling ball, instead of spinning like a top?", options: ['Earth', 'Mars', 'Uranus', 'Venus'], answer: 2, explanation: "Uranus was knocked entirely on its side by a massive collision billions of years ago. 🎳" },
    { id: 'q18', question: "What causes the glowing 'tail' of a comet to always point away from the Sun?", options: ['Air resistance', 'The Solar Wind blowing it', 'The comet flies backward', 'Optical illusion'], answer: 1, explanation: "The physical pressure of the radiation blowing off the Sun (Solar Wind) pushes the melted tail backward. 🌬️" },
    { id: 'q19', question: "Which moon in the solar system hides a massive, deep ocean of liquid water beneath an ice shell?", options: ['Earth\'s Moon', 'Jupiter\'s moon \'Europa\'', 'Mars\'s moon \'Phobos\'', 'Pluto'], answer: 1, explanation: "Europa is considered one of the best places to search for alien life in our solar system! 🌊" },
    { id: 'q20', question: "Due to zero atmosphere and dead geology, Mercury's surface is completely covered in:", options: ['Lava', 'Forests', 'Impact Craters', 'Oceans'], answer: 2, explanation: "Just like our Moon, Mercury has no defense against asteroids and is covered in blast craters! 🌚" },
  ],

  relatedTopics: ['gravity', 'stars_lifecycle', 'space_exploration'],
};
