export default {
  // ── IDENTITY ────────────────────────────────
  id: 'dna_genetics',
  title: 'DNA & Genetics',
  subtitle: 'The secret code of all living things 🧬',
  emoji: '🧬',
  category: 'Biology',
  accentKey: 'genetics',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "You share 99.9% of your DNA with every other human on Earth. But did you know you also share 50% of your DNA with a banana? 🍌 How is that possible?",
    reveal: "All life on Earth runs on the exact same operating system: DNA! It is a microscopic instruction manual tightly coiled inside every single cell in your body. If you uncoiled all the DNA in just your body, it would stretch to the Sun and back over 60 times! Written using an alphabet of only 4 chemical letters (A, T, C, G), this incredible molecule builds muscles, colors eyes, and creates every living thing from bacteria to blue whales. Let's crack the code! 🔍",
    emoji: '🔬',
  },

  // ── THEORY CARDS (10) ───────────────────────
  theory: [
    {
      id: 'blueprint',
      title: 'The Blueprint of Life 🏗️',
      color: '#00D4A0',
      bgGradient: ['#0A1A14', '#050D0A'],
      icon: '📐',
      svgIcon: 'grid',
      content: "DNA stands for *Deoxyribonucleic Acid*. It is basically a giant recipe book containing the instructions to build and maintain you.\n\nEvery single cell in your body (except red blood cells) contains a complete copy of your DNA trapped inside a vault called the Nucleus.\n\nEven though DNA is microscopic, it is massively long. To fit inside a tiny cell, it is tightly wrapped around proteins forming structures called *Chromosomes*. Humans have 46 chromosomes (23 from your mother, 23 from your father).",
      highlight: "DNA is so packed with information that a single gram of DNA can store 215 million gigabytes of data! 💾",
    },
    {
      id: 'double_helix',
      title: 'The Double Helix 🧬',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🧬',
      svgIcon: 'sparkle',
      content: "For a long time, scientists didn't know what DNA looked like. In 1953, James Watson and Francis Crick (using crucial X-ray data from Rosalind Franklin) discovered its shape: The Double Helix.\n\nIt looks like a twisted ladder. \nThe 'side rails' (backbone) are made of sugar and phosphate. \nThe 'rungs' (the steps) are made of chemical pairs called Nitrogenous Bases.\n\nBecause it has two matching sides, when a cell needs to divide, it simply 'unzips' the ladder down the middle and builds a new matching side for both halves! ✂️",
      highlight: "The discovery of the Double Helix in 1953 is considered one of the greatest scientific achievements in human history.",
    },
    {
      id: 'base_pairs',
      title: 'Base Pairing: The 4 Letters 🔠',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔠',
      svgIcon: 'hash',
      content: "The entire code of life is written in an alphabet of only 4 letters (bases):\n🟢 **A** (Adenine)\n🔴 **T** (Thymine)\n🔵 **C** (Cytosine)\n🟡 **G** (Guanine)\n\nBecause of their chemical shapes, they follow a strict pairing rule, known as Chargaff's rule:\n👉 **A** always pairs with **T** (Apples in the Tree)\n👉 **C** always pairs with **G** (Cars in the Garage)\n\nThis simple rule ensures that when DNA copies itself, it is perfectly identical every time!",
      highlight: "The human genome is made of 3 BILLION of these base pairs. It takes 13 years to read out loud!",
    },
    {
      id: 'genes',
      title: 'What is a Gene? 📖',
      color: '#7B6FFF',
      bgGradient: ['#100A1A', '#050D0A'],
      icon: '📖',
      svgIcon: 'book',
      content: "If DNA is the whole recipe book, a *Gene* is a single recipe.\n\nA Gene is a specific stretch of DNA that contains the instructions to build one specific Protein. Proteins are the actual workers of the cell—they build your hair, digest your food, and fight off viruses.\n\nYou have approximately 20,000 to 25,000 genes! For example, there's a specific gene that determines if you have attached or detached earlobes. We share many identical genes with animals, which is why we have similar organs (like hearts and eyes).",
      highlight: "Only 1% of your DNA actually consists of Genes! The other 99% is 'non-coding' DNA regulating the system. ⚙️",
    },
    {
      id: 'rna',
      title: 'RNA: The Messenger ✉️',
      color: '#A855F7',
      bgGradient: ['#1A0A1A', '#050D0A'],
      icon: '✉️',
      svgIcon: 'paperplane',
      content: "DNA is too precious to leave the nucleus vault. If it gets damaged, the cell dies. \nSo how does the recipe get to the kitchen (the ribosomes) to make proteins?\n\nEnter **RNA**!\nRNA is very similar to DNA, but it is a *single* strand (half a ladder) and uses the letter **U** (Uracil) instead of T.\n\nThe cell makes a temporary copy of a gene using RNA (called mRNA or messenger RNA). The mRNA leaves the nucleus, goes to the ribosome, and gets 'read' to assemble a protein. Once the protein is built, the mRNA is safely destroyed.",
      highlight: "This process (DNA -> RNA -> Protein) is called the 'Central Dogma' of biology. It is how life actually functions! 🧬",
    },
    {
      id: 'mutations',
      title: 'Mutations: Typos in the Code ⚠️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚠️',
      svgIcon: 'radiation',
      content: "Sometimes, when DNA is being copied, a mistake happens. An 'A' might accidentally get swapped with a 'C'. This typo is called a *Mutation*.\n\nMost mutations do absolutely nothing because they happen in the 99% of 'junk' non-coding DNA. \nSometimes, they are dangerous. A single wrong letter in a gene can cause the resulting protein to act incorrectly, leading to diseases like Sickle Cell Anemia or Cancer.\n\nBut rarely, a mutation is *helpful*. It might make an animal run slightly faster or resist a disease. Over millions of years, these helpful mutations build up. This is the engine of **Evolution**! 🦋",
      highlight: "Without random genetic mutations, all life on Earth would still be microscopic single-celled bacteria! 🦠",
    },
    {
      id: 'mendelian',
      title: 'Mendelian Traits 🫛',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🫛',
      svgIcon: 'person',
      content: "How are traits passed from parent to child? The rules were discovered in the 1860s by a monk named Gregor Mendel, who patiently studied thousands of pea plants.\n\nHe discovered that traits are passed down in strict units (which we now call Genes). You get one copy of a gene from your Dad, and one from your Mom.\n\nSome versions of genes are **Dominant** (they easily overpower other genes and usually show up). Some are **Recessive** (they hide quietly unless you get a recessive copy from BOTH parents).\nExample: Brown eyes are dominant over blue eyes. 👁️",
      highlight: "Because of hidden recessive genes, two brown-eyed parents can actually have a blue-eyed child! 👶",
    },
    {
      id: 'punnett',
      title: 'Punnett Squares 🔲',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🔲',
      svgIcon: 'grid',
      content: "A *Punnett Square* is a simple 2x2 grid used by scientists to predict the probability of a child inheriting a specific trait.\n\nWe use capital letters for Dominant genes (B) and lowercase letters for Recessive genes (b).\nIf Dad is Bb (Brown eyes) and Mom is Bb (Brown eyes):\n1. Top row is Dad: B, b\n2. Side column is Mom: B, b\n3. The four resulting squares will be: BB, Bb, Bb, bb.\n\nThis means the child has a 75% chance of Brown eyes, and a 25% chance of Blue eyes (bb). Math meets biology! 🧮",
      highlight: "Punnett Squares are powerful tools! Farmers use them to breed better crops, and doctors use them to predict genetic diseases. 🏥",
    },
    {
      id: 'crispr',
      title: 'CRISPR Gene Editing ✂️',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '✂️',
      svgIcon: 'cut',
      content: "What if we could fix a mutation, just like fixing a typo in a Word document?\n\nIn 2012, scientists discovered **CRISPR-Cas9**, a system originally used by bacteria to fight off viruses. Cas9 is a protein that acts like a pair of molecular scissors.\nScientists can program CRISPR to find a very specific sequence of DNA letters, snip it out, and paste in a new, healthy piece of DNA.\n\nWe are now entering an era where we might be able to 'cure' genetic diseases, create drought-resistant super-crops, and possibly even de-extinct animals! 🦖",
      highlight: "CRISPR won the Nobel Prize in Chemistry in 2020 because it completely revolutionized humanity's ability to edit the code of life. 🥇",
    },
    {
      id: 'genome',
      title: 'The Human Genome Project 🗺️',
      color: '#3B82F6',
      bgGradient: ['#050A1A', '#050D0A'],
      icon: '🗺️',
      svgIcon: 'globe',
      content: "In 1990, scientists around the world launched the Human Genome Project. The goal? To read and map out all exactly 3 Billion letters of human DNA in order.\n\nIt took 13 years and cost $3 billion dollars. But they succeeded. We finally had the complete map of human biology.\n\nToday, the technology has advanced so fast that you can sequence a whole human genome in a couple of days for just a few hundred dollars! \nThis allows personalized medicine, where doctors can look at your specific DNA and tailor treatments exactly for your body. The future is genetic! 🚀",
      highlight: "The Human Genome Project proved conclusively that all humans, regardless of race or appearance, are 99.9% genetically identical. 🤝",
    },
  ],
  
  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Genetic Engineering Lab 🔬",
    description: "Welcome to the microbiology laboratory! Spin the breathtaking 3D Double Helix to study structural bonds. Predict inheritance percentages using the Punnett Simulator, or step into the future as a genetic engineer by using CRISPR to snip out mutated DNA! ✂️",
    hint: "Features: Try increasing the UV radiation slider on the 3D Helix. In the Punnett Square, tap the parent Genotypes to flip them and watch the math change instantly. Can you find the mutation in the CRISPR scanner?",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks molecular bond visuals on the Helix and advanced mutation percentages in CRISPR mode!",
  },

  // ── DO YOU KNOW WHY (5) ─────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why you are 99.9% identical to every other human on Earth? 🌍",
      answer: "Because building a human is incredibly complex! 99.9% of the 'operating system' code is strictly required just to give you a heart, lungs, millions of nerves, and a working brain. Only that tiny remaining 0.1% of the 3 billion letters accounts for all the incredible diversity in eye color, height, and appearance we see across the entire world! 👥",
      emoji: '🧬',
    },
    {
      id: 'dyk2',
      question: "Do you know why identical twins still have totally different fingerprints? 🖐️",
      answer: "Because DNA isn't the ONLY thing that shapes you! Fingerprints are formed while a baby is developing inside the womb. The exact way the baby moves, touches the amniotic sac, and how the skin folds determines the fingerprint ridges. Even though twins have identical DNA, they have different physical experiences in the womb, resulting in unique prints! 🔍",
      emoji: '👶',
    },
    {
      id: 'dyk3',
      question: "Do you know why red hair is so rare? 🧑‍🦰",
      answer: "Red hair is caused by a completely Recessive gene on Chromosome 16! Because it is recessive (weak), if you get a dominant brown-hair gene from just one parent, it overpowers the red hair gene. To actually have red hair, you must inherit the rare recessive red gene from BOTH your mother and your father simultaneously! 🎲",
      emoji: '🧬',
    },
    {
      id: 'dyk4',
      question: "Do you know why a tiny mutation can cause a massive disease? ⚠️",
      answer: "Proteins are like 3D puzzle pieces; they must be folded into the exact correct shape to work. A mutation in the DNA code is like changing the instructions for building a Lego block. If just one amino acid is wrong, the protein folds incorrectly, the puzzle piece no longer clicks into place, and the whole cellular machine breaks down (like in Sickle Cell disease). 🧩",
      emoji: '🔴',
    },
    {
      id: 'dyk5',
      question: "Do you know why we share 50% of our DNA with bananas? 🍌",
      answer: "Because we share a common ancestor! Billions of years ago, all life originated from the same single-celled organisms. Essential cellular functions—like how to use sugar for energy, or how to divide cells—were perfected early on. Humans, dogs, and bananas all still use the exact same ancient genetic code to run those basic housekeeping tasks inside our cells! 🦠",
      emoji: '🌿',
    },
  ],

  // ── QUIZ (20) ───────────────────────────────
  quiz: [
    { id: 'q1', question: "What does DNA stand for? 🧬", options: ['Dynamic Nano Acid', 'Deoxyribonucleic Acid', 'Dual Nitrogen Alloy', 'Deoxyribose Neutral Atom'], answer: 1, explanation: "Deoxyribonucleic Acid! The 'D' comes from the Deoxyribose sugar that makes up the backbone of the ladder. 🪜" },
    { id: 'q2', question: "What shape is the DNA molecule? 🪜", options: ['A flat circle', 'A Double Helix (twisted ladder)', 'A single square', 'A zig-zag line'], answer: 1, explanation: "Watson and Crick identified the Double Helix shape, which allows the code to easily 'unzip' and copy itself. 🧬" },
    { id: 'q3', question: "Which of the following is NOT one of the 4 letters (bases) in DNA? 🔠", options: ['A (Adenine)', 'B (Bromine)', 'C (Cytosine)', 'G (Guanine)'], answer: 1, explanation: "The four bases of DNA are A, T, C, and G. Bromine is a completely different chemical element. 🧪" },
    { id: 'q4', question: "According to base pairing rules, what does 'A' always pair with? 👉👈", options: ['T (Thymine)', 'C (Cytosine)', 'G (Guanine)', 'Another A'], answer: 0, explanation: "A always pairs with T (Apples in the Tree), and C always pairs with G (Cars in the Garage)! 🌳" },
    { id: 'q5', question: "Where is almost all of the DNA stored inside a human cell? 🏢", options: ['The Mitochondria', 'The Cell Wall', 'The Nucleus', 'Floating freely'], answer: 2, explanation: "The Nucleus acts like a highly secure vault to protect the precious DNA instructions from getting damaged. 🛡️" },
    { id: 'q6', question: "How many chromosomes do human cells (except sperm/egg) typically have? 🧑", options: ['46', '23', '100', '12'], answer: 0, explanation: "Humans have 46 chromosomes in total: 23 inherited from your mother, and 23 inherited from your father! 👨‍👩‍👦" },
    { id: 'q7', question: "What is a single specific stretch of DNA that codes for one protein called? 📖", options: ['A Mutation', 'A Gene', 'A Cell', 'A Helix'], answer: 1, explanation: "A Gene is a single 'recipe' inside the giant DNA 'recipe book' that tells the cell how to build one specific protein. 🥩" },
    { id: 'q8', question: "What temporary messenger molecule copies DNA to take it out of the nucleus? ✉️", options: ['TNA', 'CRISPR', 'RNA', 'Protein'], answer: 2, explanation: "mRNA (Messenger RNA) acts as a temporary photocopy so the original DNA can stay safely locked in the nucleus! 🖨️" },
    { id: 'q9', question: "A physical trait that overpowers other traits (like brown eyes over blue) is called: 💪", options: ['Recessive', 'Dominant', 'Mutated', 'Invisible'], answer: 1, explanation: "Dominant genes overpower Recessive ones. You only need one copy of a dominant gene to show that trait! 👁️" },
    { id: 'q10', question: "If a person has a genotype of 'bb' for eye color, they must be showing a trait that is: 🟦", options: ['Dominant', 'Recessive', 'Impossible', 'Mutated'], answer: 1, explanation: "Because both letters are lowercase (bb), the recessive trait (like blue eyes) will finally be visible! 👀" },
    { id: 'q11', question: "What grid do scientists use to predict the probability of traits in offspring? 🔲", options: ['Watson Grid', 'Punnett Square', 'Newton Cube', 'Mendel Matrix'], answer: 1, explanation: "The Punnett Square is a basic 2x2 mathematical grid that perfectly predicts Mendelian inheritance probabilities. 🧮" },
    { id: 'q12', question: "What is it called when there is a 'typo' or mistake made while copying the DNA code? ⚠️", options: ['Translation', 'Extinction', 'A Mutation', 'A Fold'], answer: 2, explanation: "A Mutation is exactly that—a typo. Most do nothing, some cause disease, and rarely, some drive evolutionary leaps! ⚡" },
    { id: 'q13', question: "What was the massive scientific effort to map all 3 billion letters of human DNA called? 🗺️", options: ['The CRISPR Initiative', 'The Human Genome Project', 'Project Double Helix', 'The Manhattan Project'], answer: 1, explanation: "The Human Genome Project took 13 years and definitively mapped out the exact code needed to build a human! 🧬" },
    { id: 'q14', question: "What incredible modern technology allows scientists to 'cut and paste' live DNA like molecular scissors? ✂️", options: ['PCR', 'Radiotherapy', 'CRISPR', 'Cloning'], answer: 2, explanation: "CRISPR-Cas9 acts as programmable molecular scissors, revolutionizing medicine and agriculture. 💉" },
    { id: 'q15', question: "What letter does RNA use instead of the 'T' used in DNA? 🅰️", options: ['U (Uracil)', 'X (Xylitol)', 'M (Methionine)', 'R (Ribose)'], answer: 0, explanation: "RNA replaces Thymine with Uracil, meaning in RNA, 'A' pairs directly with 'U'! 🔠" },
    { id: 'q16', question: "Exactly what percentage of your DNA is actually genes that code for proteins? 🥩", options: ['1%', '50%', '99%', '100%'], answer: 0, explanation: "Only about 1%! The rest is once considered 'junk DNA' but is actually vital for regulating exactly when genes turn on and off. 🎛️" },
    { id: 'q17', question: "Who is famous for studying pea plants and discovering the basic rules of genetic inheritance? 🫛", options: ['Albert Einstein', 'Gregor Mendel', 'Charles Darwin', 'Isaac Newton'], answer: 1, explanation: "Gregor Mendel, an Austrian monk, patiently cross-bred thousands of peas to mathematically prove how traits are inherited! 🌱" },
    { id: 'q18', question: "If the DNA sequence is 'A-T-G', what must the matching sequence on the other side of the ladder be? 👉👈", options: ['A-T-G', 'T-C-A', 'T-A-C', 'U-A-C'], answer: 2, explanation: "Because A pairs with T, and G pairs with C, the matching pair to A-T-G must be T-A-C! 🧩" },
    { id: 'q19', question: "Which molecule actually does all the physical work of building organs and running the cell? 🏗️", options: ['DNA', 'Sugar', 'Proteins', 'Water'], answer: 2, explanation: "DNA is just the silent blueprint. Proteins (like keratin, hemoglobin, or enzymes) are the actual busy workers getting things done! 🛠️" },
    { id: 'q20', question: "In a Punnett square where a mother is 'Aa' and a father is 'Aa', what is the chance of getting a recessive 'aa' child? 🎲", options: ['0%', '25%', '50%', '100%'], answer: 1, explanation: "The four possibilities are AA, Aa, aA, and aa. So there is a 1 in 4 (25%) chance of inheriting the pure recessive trait! 🤓" },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['evolution', 'human_body', 'viruses'],
};
