// ─────────────────────────────────────────────────────────
//  TOPIC: DEBT & CREDIT
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'debt_credit',
  title: 'Debt & Credit Score',
  subtitle: 'The chainsaw of finance: it builds or destroys 🪚',
  emoji: '💳',
  category: 'Finance',
  accentKey: 'danger',

  hook: {
    question: "Is all debt evil? Should you avoid borrowing money at all costs? 🛑",
    reveal: "No! Debt is like a chainsaw. If you use it to build a house (Good Debt), it makes you rich. If you swing it around wildly to buy toys and clothes (Bad Debt), it will cut your financial arm off. Understanding your Credit Score is the difference between freedom and struggle. 🪚💸",
    emoji: '⚔️',
  },

  theory: [
    {
      id: 'what_is_credit',
      title: 'The Trust Meter 🤝',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🤝',
      svgIcon: 'star',
      content: "'Credit' is just a fancy word for 'Trust.' \n\nWhen a bank gives you credit, they are trusting that your future self will pay back your present self. You are literally borrowing money from your own future. If you break that trust, the 'Trust Meter' (your score) drops, and no one will want to play with you anymore.",
      highlight: "Credit is trust translated into mathematics. 📊",
    },
    {
      id: 'the_credit_score',
      title: 'Your Adult GPA 💳',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '💳',
      svgIcon: 'eye',
      content: "Your Credit Score is a 3-digit number (300 to 900) that grades how good you are with money. \n\nIt's like your school report card, but for grown-ups. \n1. **Payment History:** Do you pay on time? (Most important!)\n2. **Utilization:** How much of your limit are you using?\n3. **Age:** How long have you had credit?\nA high score is like a 'Golden Ticket' that makes life cheaper.",
      highlight: "A bad score is a massive invisible tax on your life. 🎓",
    },
    {
      id: 'cost_of_bad_credit',
      title: 'The Hidden Tax 🩸',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🩸',
      svgIcon: 'alert',
      content: "If two people buy the same ₹50 Lakh house, but one has a bad credit score, they might end up paying ₹20 Lakhs MORE in interest over time! \n\nThe bank thinks the person with the bad score is 'dangerous,' so they charge them a higher price for the loan. Having a good score is like having a permanent discount code for everything in life.",
      highlight: "A good score is the ultimate discount code. 🎫",
    },
    {
      id: 'good_vs_bad_debt',
      title: 'Chainsaws: Good vs Bad 🪚',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🪚',
      svgIcon: 'balance',
      content: "**Good Debt:** Using the chainsaw to build a house. You borrow money at a low cost to buy something that makes you MORE money (like a rental property or a great education).\n\n**Bad Debt:** Using the chainsaw to cut your own furniture. You borrow money at a high cost to buy something that loses value (like a fancy TV, expensive shoes, or a luxury vacation).",
      highlight: "Good debt builds wealth; Bad debt destroys it. ⚖️",
    },
    {
      id: 'credit_card_trap',
      title: 'The Mouse Trap 🪤',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🪤',
      svgIcon: 'alert',
      content: "Credit cards are the most dangerous traps in the world. \n\nIf you don't pay the full bill every month, the bank charges you a HUGE interest rate (like 40%!). If you only pay the 'Minimum,' it could take you 20 years to pay off a single laptop. The bank wants you to stay trapped in this loop forever. Don't touch the cheese unless you can pay for the whole trap! 🧀",
      highlight: "Pay your credit card in full. Every. Single. Month. 🛑",
    },
    {
      id: 'credit_utilization',
      title: 'The 30% Rule 📏',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📏',
      svgIcon: 'target',
      content: "If your credit card has a limit of ₹100, you shouldn't spend more than ₹30. \n\nEven if you can pay it back, using too much of your limit makes you look 'desperate' to the bank's computers. They think you are out of money! By keeping your spending low, you prove that you don't actually 'need' the bank's help, which makes them trust you even more.",
      highlight: "Keep your usage under 30% to look like a pro. 🛡️",
    },
    {
      id: 'emi_amortization',
      title: 'The Interest Cliff 📉',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📉',
      svgIcon: 'chart',
      content: "When you pay a home loan EMI, the bank takes almost all the interest at the beginning! \n\nFor the first few years, you are mostly just paying the bank's profit and barely paying for your house. This is called **Amortization.** If you pay just one 'Extra' payment a year, you can skip past the cliff and finish your loan 5 years earlier, saving lakhs in interest! 🏔️",
      highlight: "Extra payments at the start are worth 10x later on. 🏛️",
    },
    {
      id: 'debt_snowball',
      title: 'The Debt Snowball ⛄',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '⛄',
      svgIcon: 'refresh',
      content: "If you have many debts, start by paying off the SMALLEST one first. \n\nWait, math says pay the highest interest first! But humans aren't robots. Paying off a small debt gives you a 'Win' and makes you feel powerful. That feeling is like a snowball rolling down a hill—it gets bigger and faster until you've crushed all your debts! 🏔️",
      highlight: "Personal finance is about feelings, not just math. 🧠",
    },
    {
      id: 'student_loans',
      title: 'The Knowledge Loan 🎓',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🎓',
      svgIcon: 'book',
      content: "Borrowing money for school is a bet on yourself. \n\nIf you borrow ₹10 Lakhs to get a job that pays ₹20 Lakhs, you won the bet! But if you borrow ₹50 Lakhs for a degree that only pays ₹2 Lakhs, you are in trouble. Student loans stay with you forever, even if you go bankrupt. Calculate the 'Return' before you take the 'Risk.' 💼",
      highlight: "Never borrow more than you expect to earn in your first year. 💼",
    },
    {
      id: 'rebuilding_credit',
      title: 'The Credit Hospital 🏗️',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'shield',
      content: "If you broke your credit score, you can heal it! \n\n1. **Stop borrowing.** \n2. **Pay everything on time.** \n3. **Use a 'Secured Card':** You give the bank cash as a deposit, and they give you a card. It's like 'Training Wheels' for your credit. Over time, the bank sees you are responsible again and your score starts to climb. 🏗️",
      highlight: "Consistency and Time heal all financial wounds. ⏳",
    },
  ],

  lab: {
    title: "The Debt Destroyer ⚔️",
    description: "Welcome to the Debt Lab! Here you can see the 'Mouse Trap' in action. Watch how the 'Interest Cliff' eats your money, test the 'Snowball' vs 'Avalanche' methods, and see how much a bad credit score actually costs you in real life! 📈",
    hint: "Try the 'Credit Card Trap' mode. Look at what happens to the red bar (Interest) if you only pay the minimum. It becomes bigger than the item you bought!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks exact Amortization tables and the mathematical difference between the Snowball and Avalanche methods.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why banks LOVE 'Minimum Payments'? 🪤",
      answer: "It's a trap! The 'Minimum Payment' is just enough to keep you as a 'customer' without ever letting you be free. It covers the interest but barely touches the principal. This keeps you paying the bank for decades, turning a ₹10,000 phone into a ₹50,000 profit for the bank! 💳",
      emoji: '🪤',
    },
    {
      id: 'dyk2',
      question: "Do you know why closing an old credit card can hurt your score? ✂️",
      answer: "History! 15% of your score is about how long the bank has known you. If you close your oldest card, you 'delete' years of trust history. It's like deleting your oldest friend from your life—the bank feels like they don't know you as well anymore! 📉",
      emoji: '⏳',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'Buy Now, Pay Later' is a trick? 🎭",
      answer: "Psychology! It makes a ₹50,000 laptop feel like it only costs ₹2,000 a month. This tricks your brain into buying things you can't actually afford. It's a way to drain your 'Future Money' before you've even earned it! 🎣",
      emoji: '🎣',
    },
    {
      id: 'dyk4',
      question: "Do you know why rich people use credit cards but pay them instantly? 🛡️",
      answer: "Security! If someone steals your Debit Card, they are stealing YOUR actual cash. If they steal your Credit Card, they are stealing the BANK'S money. Plus, rich people get free flights and points, but ONLY because they are disciplined enough to never pay a single rupee in interest! 💳",
      emoji: '🛡️',
    },
    {
      id: 'dyk5',
      question: "Do you know why checking your own score is 'Free'? 🔍",
      answer: "Soft vs Hard Checks! When a bank checks your score for a loan, it's a 'Hard Check' and it drops your score slightly because you look 'desperate' for money. But when YOU check your own score, it's a 'Soft Check.' It doesn't hurt you at all, and you should do it often to make sure no one is stealing your identity! 🕵️‍♂️",
      emoji: '📈',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is Credit basically?", options: ["Free money", "Trust translated into math", "A plastic card", "A bank fee"], answer: 1, explanation: "Credit is the bank's trust in your future self! 🤝" },
    { id: 'q2', question: "What is the most important factor in your Credit Score?", options: ["Your age", "Payment History (paying on time)", "Your salary", "Your looks"], answer: 1, explanation: "Being on time is the #1 rule of finance! ⏱️" },
    { id: 'q3', question: "A bad credit score makes life:", options: ["Cheaper", "More expensive because of higher interest rates", "Easier", "Illegal"], answer: 1, explanation: "It's an invisible tax on everything you buy with a loan! 🩸" },
    { id: 'q4', question: "What is 'Good Debt'?", options: ["Borrowing for a vacation", "Borrowing at low cost to buy an asset that grows in value", "Buying shoes on credit", "A high-interest car loan"], answer: 1, explanation: "Good debt builds your future! ⚖️" },
    { id: 'q5', question: "Why are credit card 'Minimum Payments' dangerous?", options: ["They are illegal", "They keep you in debt for decades by mostly paying interest", "They are too expensive", "They make you rich"], answer: 1, explanation: "They are designed to keep you trapped! 🪤" },
    { id: 'q6', question: "What is the '30% Rule'?", options: ["Save 30% of your food", "Never use more than 30% of your credit limit", "Pay 30% tax", "Invest 30% in gold"], answer: 1, explanation: "Using too much makes you look desperate! 📏" },
    { id: 'q7', question: "What is 'Amortization'?", options: ["A type of building", "The way banks take interest before principal in a loan", "A government law", "A bank holiday"], answer: 1, explanation: "Banks take their profit first! 📉" },
    { id: 'q8', question: "What is the 'Debt Snowball'?", options: ["A winter sport", "Paying smallest debts first for psychological wins", "Ignoring debt", "Buying a house in the snow"], answer: 1, explanation: "Small wins build big momentum! ⛄" },
    { id: 'q9', question: "Student loans are unique because:", options: ["They are free", "They usually cannot be erased by bankruptcy", "They pay you interest", "They are only for genius kids"], answer: 1, explanation: "They stay with you for life until paid! 🎓" },
    { id: 'q10', question: "A 'Secured Credit Card' is like:", options: ["Free money", "Training wheels to rebuild your credit", "A VIP card", "A scam"], answer: 1, explanation: "It's a safe way to prove you can be trusted again! 🏗️" },
    { id: 'q11', question: "Why keep your oldest credit card open?", options: ["To spend more", "To keep your 'History' and 'Average Age' high", "Because the plastic is pretty", "To avoid taxes"], answer: 1, explanation: "History is trust! ✂️" },
    { id: 'q12', question: "A 'Hard Inquiry' happens when:", options: ["You check your own score", "A bank checks your score for a new loan", "You look at a bank", "You pay a bill"], answer: 1, explanation: "Too many makes you look 'loan-hungry'! 🔍" },
    { id: 'q13', question: "Why use Credit instead of Debit for big purchases?", options: ["To look rich", "For better fraud protection and security", "Because it's faster", "To avoid the bank"], answer: 1, explanation: "It's a firewall between your cash and the world! 🛡️" },
    { id: 'q14', question: "What is the true cost of '0% EMI' electronics?", options: ["They are free", "They trick you into overspending on things that lose value", "They actually charge 50% interest", "There is no cost"], answer: 1, explanation: "The cost is your future freedom! 🎣" },
    { id: 'q15', question: "What happens if you use 90% of your credit limit?", options: ["You get a reward", "Your score drops because you look desperate", "The bank gives you more money", "Nothing"], answer: 1, explanation: "High usage = High risk! 📉" },
    { id: 'q16', question: "One extra EMI payment a year can save:", options: ["A few days", "Years of time and lakhs in interest", "Your life", "Nothing"], answer: 1, explanation: "Beating amortization is the ultimate hack! ⚔️" },
    { id: 'q17', question: "A 'Late Payment' mark stays on your report for:", options: ["1 month", "7 years", "Forever", "1 day"], answer: 1, explanation: "One mistake has long-lasting consequences! 🛑" },
    { id: 'q18', question: "Why is a car loan usually 'Bad Debt'?", options: ["Cars are too loud", "You pay interest on an asset that is rapidly dying in value", "Car loans are free", "Banks hate cars"], answer: 1, explanation: "Paying to lose money is a bad deal! 🚗" },
    { id: 'q19', question: "Does your salary affect your credit score?", options: ["Yes, a lot", "No, only your behavior with debt does", "Only on Tuesdays", "If you are a billionaire"], answer: 1, explanation: "Scores measure trust, not wealth! 💰" },
    { id: 'q20', question: "What is APR?", options: ["A month in the spring", "The true yearly cost of borrowing (Annual Percentage Rate)", "A bank fee", "A type of stock"], answer: 1, explanation: "APR reveals the true cost of the loan! 📈" }
  ],

  relatedTopics: ['personal_finance', 'banking', 'taxation'],
};
