// ─────────────────────────────────────────────────────────
//  TOPIC: OVERTHINKING (ओवरथिंकिंग)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'overthinking',
  title: 'Overthinking',
  subtitle: 'The Illusion of Control 🧠🌪️',
  emoji: '🌪️',
  category: 'Mental Health',
  accentKey: 'overthinking',

  hook: {
    question: "Why do you suddenly remember something embarrassing you did 5 years ago right as you are trying to fall asleep?",
    reveal: "Because your brain is bored, and a bored brain goes hunting for problems.\n\nOverthinking is not 'problem-solving'. It is an evolutionary glitch where your brain confuses 'worrying' with 'doing something'. We overthink because we desperately want to control an unpredictable future. Let's explore why your mind gets trapped in endless loops, and how to finally hit the emergency brake. 🛑💭🛤️",
    emoji: '💭',
  },

  theory: [
    {
      id: 'rumination_vs_problem_solving',
      title: "Rumination vs. Problem Solving 🔧",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'tool',
      svgIcon: 'target',
      content: "**Problem Solving** asks: 'What can I do *right now* to fix this?' (Produces an action plan).\n\n**Rumination (Overthinking)** asks: 'Why is this happening to me? What if it gets worse?' (Produces zero action).\nIf you have been thinking about a problem for 30 minutes and have not written down a single actionable step, you are not solving it. You are just suffering.",
      highlight: "Problem-solving moves you forward. Overthinking runs you on a treadmill. 🏃‍♂️",
    },
    {
      id: 'illusion_of_control',
      title: "The Illusion of Control 🎛️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'sliders',
      svgIcon: 'lock',
      content: "Why do we overthink? Because the brain hates uncertainty.\nThe subconscious mind believes: *'If I imagine every single terrible thing that could possibly happen, I will be prepared for them.'*\nWorrying gives you a false, intoxicating sense of control over the future. It tricks you into feeling productive when you are really just torturing yourself.",
      highlight: "You cannot worry your way into a predictable future. 🔮",
    },
    {
      id: 'the_default_mode_network',
      title: "The Default Mode Network (DMN) 🕸️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "When you are not focused on a specific task (like washing dishes or doing math), your brain switches to the **Default Mode Network (DMN)**.\nThe DMN is responsible for time-travel: it either replays the past (regret) or imagines the future (anxiety). \nWhen you lie down to sleep, the DMN activates fully, dragging up your cringe memories and future fears.",
      highlight: "An unfocused brain naturally drifts toward anxiety to 'scan for threats'. 🦇",
    },
    {
      id: 'analysis_paralysis',
      title: "Analysis Paralysis 🛑",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'octagon',
      svgIcon: 'flame',
      content: "Having too much information makes decision-making *harder*, not easier.\n**Analysis Paralysis** occurs when you overthink a decision (like what car to buy) to the point of complete mental freeze. You become terrified of making the 'wrong' choice.\nThe truth? Most decisions are reversible. There is rarely a 'perfect' choice, only a choice you make and then *manage*.",
      highlight: "Any decision made today is usually better than a perfect decision made next year. ⏱️",
    },
    {
      id: 'the_what_if_virus',
      title: "The 'What If' Virus 🦠",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'help-circle',
      svgIcon: 'eye',
      content: "Overthinkers are infected by the 'What If' virus: 'What if I fail? What if they laugh?'\nTo cure it, you must answer the question and walk it to its logical conclusion. \n*What if I fail?* -> 'I will feel embarrassed.' \n*Then what?* -> 'I will try again or find a new job.'\nOnce the brain sees that the 'worst case scenario' isn't death, it stops panicking.",
      highlight: "Don't let a 'What If' hang in the air. Finish the sentence. 📝",
    },
    {
      id: 'mind_reading',
      title: "The Mind Reading Fallacy 🔮",
      color: '#673AB7',
      bgGradient: ['#1A0030', '#050010'],
      icon: 'users',
      svgIcon: 'users',
      content: "A massive portion of overthinking is spent trying to guess what other people are thinking. ('They looked at me weird, they must hate my outfit.')\nThis is a cognitive distortion. You are terrible at mind reading. Most people are not thinking about you at all; they are obsessing over their own insecurities.",
      highlight: "You are the main character in your life, but you are an extra in everybody else's. 🎭",
    },
    {
      id: 'the_two_minute_rule',
      title: "The 2-Minute Rule ⏱️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'clock',
      svgIcon: 'target',
      content: "If an action takes less than two minutes (replying to a text, putting a dish in the dishwasher, paying a small bill), **do it immediately**.\nOverthinkers often procrastinate small tasks, which pile up and create massive background anxiety. Doing it immediately steals the 'fuel' away from your overthinking engine.",
      highlight: "Thinking about doing a task drains more energy than actually doing the task. 💪",
    },
    {
      id: 'naming_the_story',
      title: "Naming the Story 📖",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'book-open',
      svgIcon: 'heart',
      content: "When you catch yourself spiraling, say out loud: **'I am telling myself the story that...'**\nInstead of 'I am going to get fired,' say 'I am telling myself the *story* that I am going to get fired.'\nThis creates psychological distance. It reminds your brain that thoughts are just electrical signals, not absolute facts.",
      highlight: "You are the sky. Your thoughts are just the weather. ☁️",
    },
    {
      id: 'the_parking_lot',
      title: "Worry Appointments 📅",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'calendar',
      svgIcon: 'compass',
      content: "You cannot just order your brain to 'stop worrying'.\nInstead, create a 'Worry Appointment'. Tell your brain: 'We will worry about this at 7:00 PM for 15 minutes.'\nWhen the thought arises at 2:00 PM, you don't suppress it, you strictly defer it. By 7:00 PM, the emotional urgency has usually vanished.",
      highlight: "Give your worry a schedule, so it stops controlling your entire day. ⏳",
    },
    {
      id: 'the_54321_method',
      title: "The 5-4-3-2-1 Grounding 🤚",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'eye',
      svgIcon: 'target',
      content: "When your mind is time-traveling, force it back into the physical present using the senses:\nName 5 things you can see.\nName 4 things you can physically feel.\nName 3 things you can hear.\nName 2 things you can smell.\nName 1 thing you can taste.\nThis forcefully crashes the 'Default Mode Network' and activates the sensory processing areas.",
      highlight: "You cannot be trapped in your head if you are deeply engaged with your physical body. 🧘‍♀️",
    },
    {
      id: 'perfectionism',
      title: "Perfectionism is Procrastination 🏹",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'target',
      svgIcon: 'alert',
      content: "Overthinkers often delay launching a project or sending an email because it isn't 'perfect'.\nPerfectionism is just fear in a tuxedo. It is the fear of being judged.\nAdopt the mantra: **'Done is better than perfect.'** Send the email with a typo. Launch the messy prototype. Real-world feedback is infinitely more valuable than theoretical perfection.",
      highlight: "A messy action beats a perfect theory every single time. 🚀",
    },
    {
      id: 'decision_fatigue',
      title: "Automate the Trivial 🤖",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'cpu',
      svgIcon: 'activity',
      content: "Overthinkers exhaust themselves on meaningless choices (what to eat, what to wear).\nAutomate them. Eat the same breakfast every weekday. Buy 5 of the same work shirt. Build a rigid morning routine.\nSave your precious 'decision-making' mental energy for the things that actually matter.",
      highlight: "Boring routines create mental freedom. 🗓️",
    },
    {
      id: 'the_10_10_10_rule',
      title: "The 10-10-10 Rule 🔭",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'camera',
      svgIcon: 'eye',
      content: "When agonizing over a mistake, ask yourself:\nWill this matter in 10 days?\nWill this matter in 10 months?\nWill this matter in 10 years?\n99% of the things that keep you awake at night will be completely irrelevant in 10 months. Zoom out.",
      highlight: "Time makes almost every crisis look ridiculously small. ⏳",
    },
    {
      id: 'gut_feelings',
      title: "Trusting the Somatic Marker 🧬",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'activity',
      svgIcon: 'star',
      content: "Overthinkers rely solely on purely logical pros/cons lists, which often fail.\nNeuroscientists have found 'Somatic Markers'—physical 'gut feelings'. Your subconscious processes millions of data points your conscious mind misses, and sends the answer as a physical feeling (a tight chest vs. feeling light).\nIf your gut screams 'No', no amount of overthinking pros/cons will make it a 'Yes'.",
      highlight: "Your body usually knows the right answer before your brain finishes making the spreadsheet. ⚖️",
    },
    {
      id: 'letting_go',
      title: "Surrendering Control 🌊",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'wind',
      svgIcon: 'leaf',
      content: "The ultimate cure for overthinking is Radical Acceptance. \nYou cannot control the economy, the traffic, or what other people think of you. \nStop trying to script the universe. Accept that chaos is the default state of life, and trust in your ability to handle whatever wave comes, rather than trying to flatten the ocean.",
      highlight: "Peace begins where the need for control ends. 🕊️",
    },
  ],

  lab: {
    title: "Rumination Interceptor 🛑🚇",
    description: "Your subject is trying to sleep, but the 'Default Mode Network' is throwing painful intrusive 'What If' thoughts. You must intercept them before they turn into full anxiety loops. Label the thoughts correctly to discard them.",
    hint: "Identify if the thought is 'Mind Reading', 'Catastrophizing', or 'Living in the Past'. Labeling the glitch destroys its power.",
    scientistModeHint: "Cognitive Parsing 🧑‍🔬: Target DMN hyperactivity and apply semantic labeling to reduce Amygdala arousal.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why is overthinking worse at night?", answer: "During the day, external stimuli (work, noise, phones) occupy your brain. At night, the sensory input drops to zero. The brain, having nothing to chew on, turns inward and activates the Default Mode Network, pulling up unresolved anxieties to 'process' them. 🌙", emoji: '🛏️' },
    { id: 'dyk2', question: "Why do 'Pros and Cons' lists sometimes make decisions harder?", answer: "Because human emotions don't carry equal weight. A list might have 10 'Pros' and 1 'Con', but if that one Con makes you physically terrified, the list is useless. Overthinkers try to use logic to solve emotional problems. ⚖️", emoji: '📝' },
    { id: 'dyk3', question: "Why do we overthink texts constantly? ('Why did they use a period?')", answer: "Texting lacks tone, facial expressions, and body language (which make up 90% of human communication). The brain hates missing context, so it hyper-analyzes punctuation and emojis to fill in the dangerous blanks, usually assuming the worst. 📱", emoji: '💬' },
    { id: 'dyk4', question: "Why does getting out of bed instantly stop overthinking loops?", answer: "Lying still while anxious signals 'helplessness' to the brain. Standing up and moving physically changes your blood flow and forces the brain to process spatial environments, immediately dragging it out of the 'past/future' DMN and into the present physical reality. 🚶‍♂️", emoji: '🚪' },
    { id: 'dyk5', question: "Why is taking a deep breath the oldest advice in the book?", answer: "Because it physically hijacks the nervous system. A slow exhale stimulates the Vagus Nerve, which dumps acetylcholine onto your heart, literally forcing your heart rate to slow down regardless of what you are worrying about. 🫁", emoji: '🌬️' },
  ],

  quiz: [
    { id: 'q1', question: "What is the difference between Problem Solving and Rumination (Overthinking)?", options: ['Problem solving takes longer', 'Problem solving asks \'What can I do right now\' (action). Rumination asks \'Why me\' (dwelling with zero action)', 'Rumination is positive', 'They are the exact same'], answer: 1, explanation: "If you aren't making an action plan, you are just suffering on a treadmill. 🏃‍♂️" },
    { id: 'q2', question: "Why does the brain subconsciously WANT to overthink (worry)?", options: ['Because it is fun', 'It creates the illusion of Control. The brain falsely believes that imagining every bad scenario prepares it for the future', 'To build memory', 'To burn calories'], answer: 1, explanation: "Worrying tricks you into feeling productive without doing anything. 🎛️" },
    { id: 'q3', question: "What is the Default Mode Network (DMN)?", options: ['A computer router', 'The brain network that activates when you are not focused on a task, responsible for time-traveling to the past (regret) or future (anxiety)', 'The part of the brain that sleeps', 'A vision center'], answer: 1, explanation: "When left idle, an unfocused brain naturally drifts toward anxiety. 🕸️" },
    { id: 'q4', question: "What is 'Analysis Paralysis'?", options: ['A leg cramp', 'Overthinking a decision to the point where you freeze up completely out of fear of making the \'wrong\' choice', 'Reading too fast', 'Typing mistakes'], answer: 1, explanation: "More information often makes decisions harder, not easier. 🛑" },
    { id: 'q5', question: "How do you cure the 'What If' virus?", options: ['Take a nap', 'Finish the sentence. Ask \'Then what?\' and walk it to its logical conclusion to prove it isn\'t the end of the world', 'Ignore it entirely', 'Watch TV'], answer: 1, explanation: "Once the brain sees the worst-case scenario is survivable, it stops panicking. 🦠" },
    { id: 'q6', question: "What is the cognitive distortion of 'Mind Reading'?", options: ['Winning at poker', 'Assuming you know what someone else is thinking (usually assuming they hate you) without any actual evidence', 'Having high empathy', 'Reading books fast'], answer: 1, explanation: "Most people are not judging you; they are too busy judging themselves. 🔮" },
    { id: 'q7', question: "What is the '2-Minute Rule'?", options: ['Boiling eggs', 'If a task takes less than 2 minutes, do it immediately to prevent it from becoming background anxiety fuel', 'Hold your breath', 'Talk for 2 minutes'], answer: 1, explanation: "Thinking about doing the dishes drains more energy than actually washing them. ⏱️" },
    { id: 'q8', question: "Why is saying 'I am telling myself the story that...' effective?", options: ['It sounds cool', 'It creates psychological distance, reminding your brain that thoughts are not absolute facts', 'It improves speaking skills', 'It is a lie'], answer: 1, explanation: "You are the observer of your thoughts, not the thoughts themselves. 📖" },
    { id: 'q9', question: "What is a 'Worry Appointment'?", options: ['A meeting with a boss', 'Scheduling a 15-minute window (e.g., at 7 PM) to \'worry\'. If a thought comes up earlier, you defer it to that time', 'A doctor\'s visit', 'Waking up early'], answer: 1, explanation: "You can't suppress thoughts, but you can successfully defer them. 📅" },
    { id: 'q10', question: "How does the 5-4-3-2-1 method work?", options: ['A countdown to sleep', 'It uses the 5 physical senses to force the brain out of the \'past/future\' loop and violently anchor it in the present moment', 'A math trick', 'A workout routine'], answer: 1, explanation: "You cannot be trapped in your head if you are focused on the texture of a carpet. 🤚" },
    { id: 'q11', question: "What is the relationship between Perfectionism and Procrastination?", options: ['They are opposites', 'Perfectionism IS procrastination. It is the fear of being judged, which causes you to delay taking action indefinitely', 'They both build wealth', 'No relation'], answer: 1, explanation: "A messy prototype beats a perfect theory every time. 🏹" },
    { id: 'q12', question: "Why did Steve Jobs wear the same outfit every day?", options: ['He only owned one shirt', 'To automate a trivial choice and save his brain\'s limited \'decision-making fuel\' for important things (preventing decision fatigue)', 'To be famous', 'It was cheap'], answer: 1, explanation: "Boring daily routines create mental freedom. 🤖" },
    { id: 'q13', question: "What is the 10-10-10 Rule used for?", options: ['Buying stocks', 'Zooming out by asking if this problem will matter in 10 days, 10 months, or 10 years, which instantly shrinks the crisis', 'Breathing exercises', 'Dieting'], answer: 1, explanation: "Time makes almost every huge crisis look ridiculously small. 🔭" },
    { id: 'q14', question: "What is a 'Somatic Marker' (Gut Feeling)?", options: ['A stomach ache', 'The subconscious mind processing millions of data points and sending the answer as a physical sensation (e.g., a tight chest)', 'A birthmark', 'Hunger'], answer: 1, explanation: "Your body often calculates the correct answer faster than your logical brain. 🧬" },
    { id: 'q15', question: "What is 'Radical Acceptance'?", options: ['Giving up on life', 'Accepting that you cannot control the universe/other people, and letting go of the exhausting need to script the future', 'Fighting everyone', 'Agreeing with everything'], answer: 1, explanation: "Peace begins where the need for control ends. 🌊" },
    { id: 'q16', question: "Why is overthinking commonly worse immediately before falling asleep?", options: ['Gravity affects blood flow', 'Sensory input drops to zero in a dark room. The bored brain turns on the DMN to hunt for unresolved problems', 'The bed is uncomfortable', 'Pillows cause stress'], answer: 1, explanation: "A bored brain will invent a tiger if it can't find one. 🌙" },
    { id: 'q17', question: "Why do we overanalyze text messages?", options: ['Because reading is hard', 'Text lacks tone and body language (90% of communication). The brain hates missing context and fills the dangerous blanks with anxiety', 'Because phones are bright', 'Typographical errors'], answer: 1, explanation: "A period at the end of a sentence can look like an act of war to an overthinker. 💬" },
    { id: 'q18', question: "How does getting out of bed immediately stop an overthinking spiral?", options: ['It wakes you up', 'It physically forces the brain to process spatial environments, dragging it out of the \'mental simulation\' and into physical reality', 'It makes you cold', 'It exercises the legs'], answer: 1, explanation: "Change your physical state to snap your mental state. 🚶‍♂️" },
    { id: 'q19', question: "What physiological change happens when you take a slow, deep exhale?", options: ['Lungs shrink', 'It stimulates the Vagus Nerve, dumping chemicals that biologically force the heart rate to slow down, regardless of your thoughts', 'It makes you dizzy', 'Nothing'], answer: 1, explanation: "You can hack your anxiety through your respiratory system. 🫁" },
    { id: 'q20', question: "What does it mean to say 'You are the sky, thoughts are the weather'?", options: ['Predicting rain', 'Thoughts are temporary, passing events. You are the permanent observer. You do not have to become every thought you have', 'Looking up', 'Flying'], answer: 1, explanation: "Don't fight the storm. Just watch it pass. ☁️" },
  ],

  relatedTopics: ['anxiety', 'stress', 'perfecting'],
};
