export default {
  id: "black_holes",
  title: "Black Holes",
  subtitle: "The gravity traps of eternity 🕳️",
  emoji: "🕳️",
  category: "Space",
  accentKey: "space",

  hook: {
    question: "What happens if you fall into a Black Hole? Do you get crushed, stretched, or frozen in time forever? 🌀",
    reveal: "All of the above! As you approach the 'Event Horizon,' time slows down so much that an outside observer would see you frozen at the edge for eternity. But for you, gravity's 'tidal forces' become so strong that your feet are pulled much harder than your head, stretching your body into a thin string of atoms. This is literally called **Spaghettification**! 🍝",
    emoji: "🍝",
  },

  theory: [
    {
      id: "bh_0",
      title: "What is a Black Hole? 🌑",
      color: "#F1F5F9",
      bgGradient: ["#000000", "#050D0A"],
      icon: "🌑",
      svgIcon: "blackhole",
      content: "A Black Hole is a region of space where gravity is so strong that NOTHING—not even light—can escape. \n\nIt's formed when a massive star collapse into a point of zero volume and infinite density called a **Singularity**. Imagine crushing the entire Earth into the size of a marble! 🔮",
      highlight: "The ultimate 'No Entry' zone of the universe! 🏛️",
    },
    {
      id: "bh_1",
      title: "The Event Horizon 🌒",
      color: "#FF3131",
      bgGradient: ["#200000", "#050D0A"],
      icon: "🌒",
      svgIcon: "target",
      content: "This is the 'Point of No Return.' Once you cross this invisible boundary, you can never get out, even if you had a rocket moving at the speed of light. \n\nInside the Event Horizon, the paths of all light rays are bent inward toward the center. Escape becomes mathematically impossible! 🛑",
      highlight: "The shell where light itself gets trapped! 🕸️",
    },
    {
      id: "bh_2",
      title: "Spaghettification! 🍝",
      color: "#FFD166",
      bgGradient: ["#202000", "#050D0A"],
      icon: "🍝",
      svgIcon: "activity",
      content: "The technical term is 'Tidal Forces.' Near a black hole, gravity increases so sharply with distance that the pull on your feet (closer to the hole) is millions of times stronger than the pull on your head. \n\nThis difference aggressively stretches you into a long, thin vertical strand of atoms before you even reach the singularity! 🧶",
      highlight: "Gravity's ultimate stretching rack! 🥨",
    },
    {
      id: "bh_3",
      title: "Gravitational Time Dilation ⏳",
      color: "#00E5FF",
      bgGradient: ["#001020", "#050D0A"],
      icon: "⏳",
      svgIcon: "clock",
      content: "Einstein proved that gravity warps time. Near a black hole, time flows MUCH slower than on Earth. \n\nIf you spent an hour orbiting a massive black hole and then came back to Earth, you might find that 50 years have passed! This is essentially a 'one-way time machine' to the future! 🚀",
      highlight: "Gravity makes time move like molasses! 🍯",
    },
    {
      id: "bh_4",
      title: "The Accretion Disk 🍩",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🍩",
      svgIcon: "sun",
      content: "Black holes themselves are invisible, but they are often surrounded by a swirling 'donut' of gas and dust called an Accretion Disk. \n\nThis material spins so fast that friction heats it up to millions of degrees, making it glow with X-rays. This is how we 'see' black holes! 🔭",
      highlight: "The glowing 'Dinner Plate' of a black hole! 🍛",
    },
    {
      id: "bh_5",
      title: "Singularity: The End of Physics 🕳️",
      color: "#888888",
      bgGradient: ["#101010", "#050D0A"],
      icon: "🕳️",
      svgIcon: "grid",
      content: "At the very center of a black hole lies the Singularity. It is a point where the mass of a giant star is crushed into zero space. \n\nHere, the curvature of space-time becomes infinite. Our current math and physics (like General Relativity and Quantum Mechanics) simply stop working here. It is the ultimate mystery! 🏛️",
      highlight: "Where space and time simply... end! 🛑",
    },
    {
      id: "bh_6",
      title: "Schwarzschild Radius 📏",
      color: "#A855F7",
      bgGradient: ["#150A20", "#050D0A"],
      icon: "📏",
      svgIcon: "ruler",
      content: "Every object has a 'Schwarzschild Radius.' If you crush any object smaller than this radius, it becomes a black hole! \n\nFor the Sun, this radius is about 3 km. For the Earth, it's about 9 millimeters—the size of a grape! 🍇",
      highlight: "The 'Critical Density' threshold! 📐",
    },
    {
      id: "bh_7",
      title: "Hawking Radiation 💡",
      color: "#6366F1",
      bgGradient: ["#100A25", "#050D0A"],
      icon: "💡",
      svgIcon: "zap",
      content: "Stephen Hawking discovered that black holes aren't 100% black. They slowly 'leak' radiation due to quantum effects at the edge. \n\nOver trillions upon trillions of years, a black hole will eventually evaporate entirely and vanish! But for big ones, this takes longer than the current age of the universe! ⏳",
      highlight: "Black holes slowly 'evaporate' over eons! 🕯️",
    },
    {
      id: "bh_8",
      title: "Quasars: Cosmic Flashlights 🔦",
      color: "#FFD166",
      bgGradient: ["#201500", "#050D0A"],
      icon: "🔦",
      svgIcon: "layers",
      content: "When a supermassive black hole at the center of a galaxy eats too much gas at once, it shoots out massive jets of energy from its poles. \n\nThese are Quasars. They are the brightest objects in the entire universe—one Quasar can shine brighter than 1,000 Milky Way galaxies combined! ☄️",
      highlight: "Black holes power the universe's brightest lights! 💡",
    },
    {
      id: "bh_9",
      title: "Spacetime Warping 🕸️",
      color: "#10B981",
      bgGradient: ["#0A2010", "#050D0A"],
      icon: "🕸️",
      svgIcon: "repeat",
      content: "Imagine a heavy bowling ball on a trampoline. A black hole is like a heavy lead ball that rips a hole straight through the fabric! \n\nIt doesn't just pull things; it literally curves the 'road' (space) so that every path leads toward the center. You aren't being 'pulled' so much as 'falling' down a hole that never ends! 🌀",
      highlight: "Gravity is just 'Curved Space'! 📐",
    },
  ],

  lab: {
    title: "Event Horizon Voyager 🌌",
    description: "Launch science probes toward a 10-Solar-Mass black hole. Observe how gravity stretches the probe (Spaghettification) and how time dilates as it nears the Event Horizon.",
    hint: "Launch at 0.5c for a stable orbit, or 0.1c to witness a total collapse!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays the Schwarzschild Radius ($R_s$), Gravitational Redshift factor, and the exact Time Dilation ratio ($dt/dt'$).",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know if our Sun will become a black hole? ☀️",
      answer: "Nope! To become a black hole, a star needs at least 3-4 times the Sun's mass in its core after it dies. Our Sun is just a lightweight! 🥚",
      emoji: "🥚",
    },
    {
      id: "dyk2",
      question: "Do you know what 'Spaghettification' feels like? 🍝",
      answer: "Extremely painful (if you could survive)! Your feet are pulled so much harder than your head that your body is literally stretched like a rubber band until you're a single atom thick! 🧶",
      emoji: "🧶",
    },
    {
      id: "dyk3",
      question: "Do you know why black holes are black? 🌑",
      answer: "Because to escape their gravity, you'd need to move faster than light (300,000 km/s). Since nothing can go that fast, not even light can leave to reach our eyes! 🌒",
      emoji: "🌒",
    },
    {
      id: "dyk4",
      question: "Do you know how we photographed a black hole? 📸",
      answer: "We didn't see the hole! We saw its 'Shadow' against the glowing gas of the Accretion Disk. It took 8 telescopes around the world working together! 🔭",
      emoji: "🔭",
    },
    {
      id: "dyk5",
      question: "Do you know what's 'inside' a black hole? 🕳️",
      answer: "We don't know! Einstein's math says it's a Singularity, but Quantum Mechanics says that's impossible. It's the biggest unsolved puzzle in science! 🧩",
      emoji: "🧩",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What is the boundary of a black hole called?",
      options: ["Gravity Wall", "The Singularity", "The Event Horizon", "The Solar Shell"],
      answer: 2,
      explanation: "The Event Horizon is the 'Point of No Return'! 🌒",
    },
    {
      id: "q2",
      question: "What is the point of infinite density at the center?",
      options: ["Core", "Singularity", "Photon Sphere", "Star Point"],
      answer: 1,
      explanation: "The Singularity is where all the mass is crushed into zero volume! 🕳️",
    },
    {
      id: "q3",
      question: "What happens to time as you approach a black hole?",
      options: ["It speeds up", "It stays the same", "It slows down", "It flows backward"],
      answer: 2,
      explanation: "Massive gravity slows down the flow of time (Time Dilation)! ⏳",
    },
    {
      id: "q4",
      question: "The process of being stretched into a thin strand is...",
      options: ["Pasta-fication", "Spaghettification", "Noodling", "Tidal Rippling"],
      answer: 1,
      explanation: "You are stretched vertically and crushed horizontally into a 'noodle'! 🍝",
    },
    {
      id: "q5",
      question: "What can escape from inside the Event Horizon?",
      options: ["Light", "Radio waves", "Nothing", "Fast Rockets"],
      answer: 2,
      explanation: "Not even light moves fast enough to escape a black hole! 🛑",
    },
    {
      id: "q6",
      question: "What is the swirling disk of hot gas around a black hole?",
      options: ["Nebula", "Accretion Disk", "Galaxy Ring", "Solar Flare"],
      answer: 1,
      explanation: "Friction in the Accretion Disk makes the gas glow brilliantly! 🍩",
    },
    {
      id: "q7",
      question: "Who predicted that black holes leak radiation?",
      options: ["Albert Einstein", "Stephen Hawking", "Isaac Newton", "Galileo"],
      answer: 1,
      explanation: "This 'Hawking Radiation' means black holes can eventually evaporate! 💡",
    },
    {
      id: "q8",
      question: "A black hole 10x the mass of the Sun would be how large?",
      options: ["Size of a galaxy", "Size of the Earth", "Size of a city (30km)", "Size of an atom"],
      answer: 2,
      explanation: "Black holes are incredibly compact—just 3km per solar mass! 📏",
    },
    {
      id: "q9",
      question: "What are the bright jets of energy from supermassive black holes?",
      options: ["Pulsars", "Quasars", "Comets", "Novas"],
      answer: 1,
      explanation: "Quasars are the brightest objects in the known universe! 🔦",
    },
    {
      id: "q10",
      question: "Gravity is actually the result of mass doing what to space?",
      options: ["Heating it", "Cooling it", "Warping/Curving it", "Filling it"],
      answer: 2,
      explanation: "Mass curves the fabric of spacetime, creating what we feel as gravity! 🕸️",
    },
    {
      id: "q11",
      question: "Why can't we see a black hole directly?",
      options: ["It moves too fast", "It emits no light", "It is smaller than an atom", "It is invisible gas"],
      answer: 1,
      explanation: "If no light escapes, there's no light to reach our eyes! 🌑",
    },
    {
      id: "q12",
      question: "Tidal forces are caused by...",
      options: ["Wind", "Magnetic repulsion", "Difference in gravity over distance", "Centrifugal force"],
      answer: 2,
      explanation: "The pull on your feet being stronger than on your head causes the stretch! 🍝",
    },
    {
      id: "q13",
      question: "Schwarzschild radius for Earth is about the size of a...",
      options: ["Marble / Grape", "City", "Mountain", "Basketball"],
      answer: 0,
      explanation: "To become a black hole, Earth would have to be crushed to ~9mm! 🍇",
    },
    {
      id: "q14",
      question: "What is a 'Supermassive' black hole?",
      options: ["One that eats stars", "One at the center of a galaxy", "One that exploded", "A large star"],
      answer: 1,
      explanation: "These monsters weigh millions or billions of times more than the Sun! 🏛️",
    },
    {
      id: "q15",
      question: "Einstein said gravity is not a force but a property of...",
      options: ["Electricity", "Magnetism", "Geometry (Spacetime)", "Biology"],
      answer: 2,
      explanation: "Gravity is the shape of the space you are moving through! 📐",
    },
    {
      id: "q16",
      question: "Do black holes keep growing forever?",
      options: ["Yes, greedily", "Only if they eat matter", "No, they shrink", "They stay constant"],
      answer: 1,
      explanation: "They only get bigger by consuming gas, dust, stars, or other black holes! 🍽️",
    },
    {
      id: "q17",
      question: "A 'Photon Sphere' is a region where light...",
      options: ["Is absorbed", "Orbits in circles", "Reflects backward", "Speeds up"],
      answer: 1,
      explanation: "Gravity is so bent that light beams travel in circles around the hole! 🎡",
    },
    {
      id: "q18",
      question: "Which type of black hole forms when a massive star dies?",
      options: ["Supermassive", "Stellar-mass", "Primordial", "Invisible"],
      answer: 1,
      explanation: "Stellar-mass black holes are the 'children' of dead giant stars! 🌟",
    },
    {
      id: "q19",
      question: "If the Sun became a black hole, would Earth be sucked in?",
      options: ["Yes, instantly", "No, we'd orbit it as usual (but freeze)", "Maybe slowly", "The Earth would explode"],
      answer: 1,
      explanation: "Gravity depends on mass and distance. If the mass is the same, the orbit stays the same! 🛰️",
    },
    {
      id: "q20",
      question: "What is the ultimate fate of all black holes?",
      options: ["Collision", "Become stars again", "Evaporation via Hawking Radiation", "Become a universe"],
      answer: 2,
      explanation: "Over trillions of years, they will eventually dissolve! 🕯️",
    },
  ],

  relatedTopics: ["stars_lifecycle", "gravity", "big_bang"],
};
