// ─────────────────────────────────────────────────────────────────
//  TOPIC REGISTRY - EXPANDED WITH PHILOSOPHY, RELIGION & MIND TOPICS
//  Priority order: High-demand skills + Foundational knowledge
//  Status: 'ready' = launch ready, 'coming' = roadmap
// ─────────────────────────────────────────────────────────────────

export const TOPIC_REGISTRY = [
  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 1: FOUNDATIONS (Must-know for EVERYTHING else) - 12 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "gravity",
    icon: "planet",
    category: "Foundations",
    title: "Gravity & Gravitation",
    priority: 1,
    status: "ready",
  },
  {
    id: "scientific_method",
    icon: "microscope",
    category: "Foundations",
    title: "Scientific Method",
    priority: 1,
    status: "ready",
  },
  {
    id: "measurement_units",
    icon: "ruler",
    category: "Foundations",
    title: "Measurement & SI Units",
    priority: 1,
    status: "ready",
  },
  {
    id: "matter_states",
    icon: "snowflake",
    category: "Foundations",
    title: "States of Matter",
    priority: 1,
    status: "ready",
  },
  {
    id: "social_media_trap",
    category: "Society",
    title: "Social Media Trap (Dopamine & Addiction)",
    emoji: "📱",
    priority: 2,
    status: "ready",
  },
  {
    id: "happiness_science",
    category: "Society",
    title: "The Happiest Person on Earth (Science of Joy)",
    emoji: "☀️",
    priority: 2,
    status: "ready",
  },
  {
    id: "meaningful_life",
    category: "Society",
    title: "Meaningful Life (Purpose & Ikigai)",
    emoji: "🧭",
    priority: 2,
    status: "ready",
  },
  {
    id: "science_of_emotion",
    category: "Society",
    title: "Science of Emotion (How Feelings Work)",
    emoji: "❤️",
    priority: 2,
    status: "ready",
  },
  {
    id: "manipulation_tactics",
    category: "Society",
    title: "Manipulation (Recognize & Defend)",
    emoji: "🛡️",
    priority: 2,
    status: "ready",
  },
  { id: "mental_syndromes",    icon: "brain",    category: "Society", title: "Mental Syndromes (Imposter, Dunning-Kruger…)",     priority: 2, status: "ready" },
  { id: "phobias",             icon: "alert",    category: "Society", title: "Phobias (Types, Causes & Cures)",                  priority: 2, status: "ready" },
  { id: "good_citizen",        icon: "users",    category: "Society", title: "Be a Good Citizen (Rights & Responsibilities)",   priority: 3, status: "ready" },
  { id: "why_be_good",         icon: "star",     category: "Society", title: "Why Become a Good Person (Ethics & Character)",   priority: 2, status: "ready" },
  { id: "basic_understanding", icon: "book",     category: "Society", title: "Basic Understanding (Self-Awareness Foundations)",priority: 1, status: "ready" },
  {
    id: "atoms_molecules",
    icon: "atom",
    category: "Foundations",
    title: "Atoms & Molecules",
    priority: 1,
    status: "ready",
  },
  {
    id: "study_tips",
    icon: "brain",
    category: "Personal Development",
    title: "Study Tips",
    priority: 1,
    status: "ready",
  },
  {
    id: "mastery_expertise",
    icon: "star",
    category: "Personal Development",
    title: "How to Become Exceptionally Good at Something",
    priority: 1,
    status: "ready",
  },
  {
    id: "earn_money",
    icon: "dollar",
    category: "Personal Development",
    title: "How to Earn Money",
    priority: 1,
    status: "ready",
  },
  {
    id: "love",
    icon: "heart",
    category: "Personal Development",
    title: "Love",
    priority: 1,
    status: "ready",
  },
  {
    id: "anger",
    icon: "fire",
    category: "Personal Development",
    title: "Anger",
    priority: 1,
    status: "ready",
  },
  {
    id: "lust",
    icon: "flame",
    category: "Personal Development",
    title: "Lust",
    priority: 1,
    status: "ready",
  },
  {
    id: "greed",
    icon: "gem",
    category: "Personal Development",
    title: "Greed",
    priority: 1,
    status: "ready",
  },
  {
    id: "envy",
    icon: "eyes",
    category: "Personal Development",
    title: "Envy",
    priority: 1,
    status: "ready",
  },
  {
    id: "sloth",
    icon: "sleep",
    category: "Personal Development",
    title: "Sloth",
    priority: 1,
    status: "ready",
  },
  {
    id: "wrath",
    icon: "volcano",
    category: "Personal Development",
    title: "Wrath",
    priority: 1,
    status: "ready",
  },
  {
    id: "relationships",
    icon: "handshake",
    category: "Personal Development",
    title: "Relationships",
    priority: 1,
    status: "ready",
  },
  {
    id: "consistency",
    icon: "repeat",
    category: "Personal Development",
    title: "Consistency (Making Habits Easy)",
    priority: 1,
    status: "ready",
  },
  {
    id: "life_hacks",
    icon: "zap",
    category: "Personal Development",
    title: "Life Hacks (Science-Backed Optimizations)",
    priority: 1,
    status: "ready",
  },

  {
    id: "periodic_table",
    icon: "grid",
    category: "Foundations",
    title: "Periodic Table Basics",
    priority: 1,
    status: "ready",
  },
  {
    id: "energy_types",
    icon: "zap",
    category: "Foundations",
    title: "Energy Types & Conservation",
    priority: 1,
    status: "ready",
  },
  {
    id: "forces_motion",
    icon: "target",
    category: "Foundations",
    title: "Forces & Motion",
    priority: 1,
    status: "ready",
  },
  {
    id: "work_power",
    icon: "lightning",
    category: "Foundations",
    title: "Work, Power & Energy",
    priority: 1,
    status: "ready",
  },
  {
    id: "heat_temperature",
    icon: "thermometer",
    category: "Foundations",
    title: "Heat & Temperature",
    priority: 1,
    status: "ready",
  },
  {
    id: "waves_sound",
    icon: "waves",
    category: "Foundations",
    title: "Waves & Sound",
    priority: 1,
    status: "ready",
  },
  {
    id: "light_optics",
    icon: "lightbulb",
    category: "Foundations",
    title: "Light & Optics",
    priority: 1,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 2: PHYSICS (High demand - Engineering & Tech) - 8 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "electricity_circuits",
    icon: "lightning",
    category: "Physics",
    title: "Electricity & Circuits",
    priority: 2,
    status: "ready",
  },
  {
    id: "magnetism",
    icon: "magnet",
    category: "Physics",
    title: "Magnetism & Electromagnetism",
    priority: 2,
    status: "ready",
  },
  {
    id: "thermodynamics_laws",
    icon: "fire",
    category: "Physics",
    title: "Thermodynamics (Laws of Heat)",
    priority: 2,
    status: "ready",
  },
  {
    id: "momentum_collisions",
    icon: "target",
    category: "Physics",
    title: "Momentum & Collisions",
    priority: 2,
    status: "ready",
  },
  {
    id: "pressure_fluids",
    icon: "pressure",
    category: "Physics",
    title: "Pressure & Fluid Mechanics",
    priority: 2,
    status: "ready",
  },
  
  {
    id: "relativity_basics",
    icon: "rocket",
    category: "Physics",
    title: "Einstein's Relativity (Intro)",
    priority: 3,
    status: "ready",
  },
  {
    id: "quantum_basics",
    icon: "atom",
    category: "Physics",
    title: "Quantum Mechanics (Intro)",
    priority: 3,
    status: "ready",
  },
  {
    id: "physics_multi_lab",
    icon: "zap",
    category: "Physics",
    title: "Physics Master Lab",
    priority: 1,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 3: CHEMISTRY (High demand - Medicine & Materials) - 8 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "chemical_bonding",
    icon: "link",
    category: "Chemistry",
    title: "Chemical Bonding (Ionic/Covalent)",
    priority: 2,
    status: "ready",
  },
  {
    id: "chemical_reactions",
    icon: "flask",
    category: "Chemistry",
    title: "Chemical Reactions & Equations",
    priority: 2,
    status: "ready",
  },
  {
    id: "acids_bases_ph",
    icon: "beaker",
    category: "Chemistry",
    title: "Acids, Bases & pH Scale",
    priority: 2,
    status: "ready",
  },
  {
    id: "periodic_trends",
    icon: "chart",
    category: "Chemistry",
    title: "Periodic Trends (Reactivity etc.)",
    priority: 2,
    status: "ready",
  },
  {
    id: "stoichiometry",
    icon: "balance",
    category: "Chemistry",
    title: "Stoichiometry (Mole Math)",
    priority: 2,
    status: "ready",
  },
  {
    id: "organic_chemistry",
    icon: "molecule",
    category: "Chemistry",
    title: "Organic Chemistry (Carbon Compds)",
    priority: 3,
    status: "ready",
  },
  {
    id: "electrochemistry",
    icon: "battery",
    category: "Chemistry",
    title: "Electrochemistry (Batteries)",
    priority: 3,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 4: BIOLOGY (High demand - Health & Life Sciences) - 8 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "cell_structure",
    icon: "microscope",
    category: "Biology",
    title: "Cell Structure & Function",
    priority: 2,
    status: "ready",
  },
  {
    id: "dna_genetics",
    icon: "hash",
    category: "Biology",
    title: "DNA & Genetics (The Code of Life)",
    priority: 3,
    status: "ready",
  },
  {
    id: "evolution_natural",
    icon: "dna",
    category: "Biology",
    title: "Evolution & Natural Selection",
    priority: 2,
    status: "ready",
  },
  {
    id: "human_body_systems",
    icon: "person",
    category: "Biology",
    title: "Human Body Systems Overview",
    priority: 2,
    status: "ready",
  },
  {
    id: "nervous_system",
    icon: "brain",
    category: "Biology",
    title: "Nervous System & Brain",
    priority: 2,
    status: "ready",
  },
  {
    id: "immune_system",
    icon: "shield",
    category: "Biology",
    title: "Immune System & Vaccines",
    priority: 2,
    status: "ready",
  },
  {
    id: "photosynthesis",
    icon: "leaf",
    category: "Biology",
    title: "Photosynthesis & Plants",
    priority: 2,
    status: "ready",
  },
  {
    id: "ecosystems",
    icon: "earth",
    category: "Biology",
    title: "Ecosystems & Food Chains",
    priority: 3,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 5: PSYCHOLOGY (High demand - Self improvement & UX) - 6 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "brain_structure",
    icon: "brain",
    category: "Psychology",
    title: "Brain Anatomy & Functions",
    priority: 2,
    status: "ready",
  },
  {
    id: "memory_how_it_works",
    icon: "book",
    category: "Psychology",
    title: "How Memory Works (Learning Hack)",
    priority: 2,
    status: "ready",
  },
  {
    id: "cognitive_biases",
    icon: "target",
    category: "Psychology",
    title: "Cognitive Biases (Think Better)",
    priority: 2,
    status: "ready",
  },
  {
    id: "emotions_motivation",
    icon: "heart",
    category: "Psychology",
    title: "Emotions & Motivation",
    priority: 2,
    status: "ready",
  },
  {
    id: "learning_behavior",
    icon: "sparkle",
    category: "Psychology",
    title: "Learning & Behaviorism",
    priority: 3,
    status: "ready",
  },
  {
    id: "mental_health_basics",
    icon: "leaf",
    category: "Psychology",
    title: "Mental Health Basics (Anxiety/Depression)",
    priority: 2,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 6: HISTORY (High demand - Understanding today's world) - 6 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ancient_civilizations",
    icon: "history",
    category: "History",
    title: "Ancient Civilizations (Egypt, Indus, Rome)",
    priority: 3,
    status: "ready",
  },
  {
    id: "industrial_revolution",
    icon: "factory",
    category: "History",
    title: "Industrial Revolution (How World Changed)",
    priority: 2,
    status: "ready",
  },
  {
    id: "world_wars",
    icon: "bomb",
    category: "History",
    title: "World Wars (WW1 & WW2)",
    priority: 2,
    status: "ready",
  },
  {
    id: "indian_freedom",
    icon: "flag",
    category: "History",
    title: "Indian Freedom Struggle (Gandhi, Nehru)",
    priority: 3,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 7: SPACE & FUTURE (High demand - Curiosity & Careers) - 6 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "solar_system",
    icon: "planet",
    category: "Space",
    title: "Solar System (Planets & Moons)",
    priority: 2,
    status: "ready",
  },
  {
    id: "stars_lifecycle",
    icon: "star",
    category: "Space",
    title: "Stars & Their Life Cycles",
    priority: 2,
    status: "ready",
  },
  {
    id: "black_holes",
    icon: "blackhole",
    category: "Space",
    title: "Black Holes (Mind-Blowing)",
    priority: 2,
    status: "ready",
  },
  {
    id: "big_bang",
    icon: "galaxy",
    category: "Space",
    title: "Big Bang Theory (Origin of Universe)",
    priority: 2,
    status: "ready",
  },
  {
    id: "exoplanets",
    icon: "telescope",
    category: "Space",
    title: "Exoplanets & Alien Life Search",
    priority: 3,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 8: TECH & AI (HIGHEST DEMAND - Careers & Future) - 6 topics
  // ═══════════════════════════════════════════════════════════════
  {
    id: "binary_computers",
    icon: "binary",
    category: "Technology",
    title: "Binary & How Computers Work",
    priority: 2,
    status: "ready",
  },
  {
    id: "internet_how_it_works",
    icon: "wifi",
    category: "Technology",
    title: "How the Internet Works",
    priority: 2,
    status: "ready",
  },
  {
    id: "ai_machine_learning",
    icon: "robot",
    category: "Technology",
    title: "AI & Machine Learning (Intro)",
    priority: 2,
    status: "ready",
  },
  {
    id: "digital_circuits",
    icon: "cpu",
    category: "Technology",
    title: "Digital Circuits & Logic Gates",
    priority: 3,
    status: "ready",
  },
  {
    id: "cryptography",
    icon: "key",
    category: "Technology",
    title: "Cryptography (Passwords & Security)",
    priority: 2,
    status: "ready",
  },
  {
    id: "data_science",
    icon: "data",
    category: "Technology",
    title: "Data Science & Statistics Basics",
    priority: 2,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 9: EXISTING ADDITIONS (Phase 5)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "financial_literacy",
    icon: "chart",
    category: "Society",
    title: "Financial Literacy (Money & Markets)",
    priority: 1,
    status: "ready",
  },
  {
    id: "critical_thinking",
    icon: "target",
    category: "Psychology",
    title: "Critical Thinking & Logic Fallacies",
    priority: 1,
    status: "ready",
  },
  {
    id: "climate_change",
    icon: "earth",
    category: "Biology",
    title: "Climate Science & The Earth System",
    priority: 1,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 10: PHILOSOPHY (NEW - Big life questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "atheism",
    icon: "question",
    category: "Philosophy",
    title: "Atheism (Life Without God — Why & How)",
    priority: 2,
    status: "ready",
  },
  {
    id: "nihilism",
    icon: "void",
    category: "Philosophy",
    title: "Nihilism (Nothing Matters — Or Does It?)",
    priority: 2,
    status: "ready",
  },
  {
    id: "absurdism",
    icon: "chaos",
    category: "Philosophy",
    title: "Absurdism (Camus, Meaning in a Meaningless World)",
    priority: 2,
    status: "ready",
  },
  {
    id: "stoicism",
    icon: "mountain",
    category: "Philosophy",
    title: "Stoicism (Control What You Can)",
    priority: 1,
    status: "ready",
  },
  {
    id: "existentialism",
    icon: "compass",
    category: "Philosophy",
    title: "Existentialism (You Define Your Own Meaning)",
    priority: 2,
    status: "ready",
  },
  {
    id: "enlightenment",
    icon: "sun",
    category: "Philosophy",
    title: "The Enlightenment (Age of Reason & Freedom)",
    priority: 2,
    status: "ready",
  },
  {
    id: "great_philosophers",
    icon: "scroll",
    category: "Philosophy",
    title: "Greatest Philosophers (Socrates to Nietzsche)",
    priority: 1,
    status: "ready",
  },
  {
    id: "ethics_morality",
    icon: "scale",
    category: "Philosophy",
    title: "Ethics & Morality (What is Right & Wrong?)",
    priority: 1,
    status: "ready",
  },
  {
    id: "free_will",
    icon: "key",
    category: "Philosophy",
    title: "Free Will vs Determinism (Are You in Control?)",
    priority: 2,
    status: "ready",
  },
  {
    id: "consciousness",
    icon: "eye",
    category: "Philosophy",
    title: "Consciousness (The Hard Problem of Mind)",
    priority: 3,
    status: "ready",
  },
  {
    id: "eastern_philosophy",
    icon: "lotus",
    category: "Philosophy",
    title: "Eastern Philosophy (Buddhism, Taoism, Vedanta)",
    priority: 2,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 11: RELIGION & GOD (NEW - Biggest human questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "how_religion_evolved",
    icon: "history",
    category: "Religion & God",
    title: "How Religion Evolved (From Myths to Monotheism)",
    priority: 1,
    status: "ready",
  },
  {
    id: "science_vs_god",
    icon: "microscope",
    category: "Religion & God",
    title: "Why Science Can't Disprove God (The Limits of Science)",
    priority: 1,
    status: "ready",
  },
  {
    id: "world_religions",
    icon: "globe",
    category: "Religion & God",
    title: "World Religions Compared (Islam, Hinduism, Christianity…)",
    priority: 2,
    status: "ready",
  },
  {
    id: "god_arguments",
    icon: "debate",
    category: "Religion & God",
    title: "Arguments For & Against God's Existence",
    priority: 2,
    status: "ready",
  },
  {
    id: "spirituality_vs_religion",
    icon: "flame",
    category: "Religion & God",
    title: "Spirituality vs Religion (What's the Difference?)",
    priority: 2,
    status: "ready",
  },
  {
    id: "afterlife_beliefs",
    icon: "star",
    category: "Religion & God",
    title: "Afterlife Beliefs Across Cultures (Heaven, Karma, Rebirth)",
    priority: 3,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 12: MENTAL HEALTH & EMOTIONS (NEW - Most searched topics)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "depression",
    icon: "rain",
    category: "Mental Health",
    title: "Depression (Causes, Signs & How to Heal)",
    priority: 1,
    status: "ready",
  },
  {
    id: "anxiety",
    icon: "storm",
    category: "Mental Health",
    title: "Anxiety (Why It Happens & How to Calm It)",
    priority: 1,
    status: "ready",
  },
  {
    id: "fear",
    icon: "alert",
    category: "Mental Health",
    title: "Fear (The Science of What Scares Us)",
    priority: 1,
    status: "ready",
  },
  {
    id: "loneliness",
    icon: "moon",
    category: "Mental Health",
    title: "Loneliness (Why We Feel Alone & How to Fix It)",
    priority: 2,
    status: "ready",
  },
  {
    id: "trauma",
    icon: "broken_heart",
    category: "Mental Health",
    title: "Trauma & PTSD (What It Does to the Brain)",
    priority: 2,
    status: "ready",
  },
  {
    id: "self_esteem",
    icon: "mirror",
    category: "Mental Health",
    title: "Self-Esteem (How to Value Yourself)",
    priority: 2,
    status: "ready",
  },
  {
    id: "burnout",
    icon: "fire",
    category: "Mental Health",
    title: "Burnout (Why You're Exhausted & How to Recover)",
    priority: 2,
    status: "ready",
  },
  {
    id: "overthinking",
    icon: "spiral",
    category: "Mental Health",
    title: "Overthinking (How to Quiet Your Mind)",
    priority: 1,
    status: "ready",
  },
  {
    id: "meditation",
    icon: "lotus",
    category: "Mental Health",
    title: "Meditation (Neuroscience of Focus)",
    priority: 1,
    status: "ready",
  },
  {
    id: "addiction",
    icon: "chain",
    category: "Mental Health",
    title: "Addiction (Dopamine & Breaking Habits)",
    priority: 1,
    status: "ready",
  },

  // ═══════════════════════════════════════════════════════════════
  //  BLOCK 13: MODERN LIFE & SOCIETY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "politics",
    icon: "scales",
    category: "Society",
    title: "Politics & Bias (Understanding Who is Right)",
    priority: 2,
    status: "ready",
  },
];

// ═══════════════════════════════════════════════════════════════════
//  UTILITIES
// ═══════════════════════════════════════════════════════════════════
export const CATEGORIES = [...new Set(TOPIC_REGISTRY.map((t) => t.category))];

export const getTopicById = (id) => TOPIC_REGISTRY.find((t) => t.id === id);
export const getTopicsByCategory = (cat) =>
  TOPIC_REGISTRY.filter((t) => t.category === cat);
export const getTopicsByPriority = (priority) =>
  TOPIC_REGISTRY.filter((t) => t.priority === priority);
export const getReadyTopics = () =>
  TOPIC_REGISTRY.filter((t) => t.status === "ready");

// Priority 1 = Absolute must-know (Launch these FIRST)
// Priority 2 = High demand (Launch in Phase 2)
// Priority 3 = Advanced/Niche (Launch in Phase 3)