export default {
  id: 'heat_temperature',
  title: 'Heat & Temperature',
  subtitle: 'The molecular dance of energy 🔥',
  emoji: '🔥',
  category: 'Foundations',
  accentKey: 'chemical',

  hook: {
    question: "Did you know that absolute cold definitively exists, but there is mathematically no known limit to absolute hot? 🥶",
    reveal: "Temperature is fundamentally just a measurement of how aggressively atoms are moving. Absolute zero (-273.15°C) occurs when atoms stop moving entirely. You simply cannot go slower than a complete stop! However, you can theoretically continue adding energy to atoms (making them move faster and faster) infinitely until they tear themselves apart into a sea of absolute subatomic soup. 🌡️",
    emoji: '🧊',
  },

  theory: [
    { id: '1', title: 'Temperature vs. Heat', color: '#FF4D6D', bgGradient: ['#2A0A0A', '#05050A'], icon: '🌡️', svgIcon: 'thermometer', content: "**Temperature** is the precise average kinetic energy of the particles inside a substance. \n\n**Heat**, conversely, is the total transferable thermal energy moving between two systems. \n\nA towering iceberg possesses a dangerously low temperature, but it holds massive heat energy purely because it's so incredibly large! A tiny spark from a bonfire has a devastatingly high temperature, but very little heat energy.", highlight: "Temperature is AVERAGE atomic energy. Heat is TOTAL atomic energy. 🔥" },
    { id: '2', title: 'Brownian Motion', color: '#FFB347', bgGradient: ['#2A1A00', '#05050A'], icon: '⚛️', svgIcon: 'atom', content: "In 1827, botanist Robert Brown noticed tiny pollen grains jiggling entirely randomly in a drop of water. \n\nIn 1905, Albert Einstein mathematically proved this chaotic jiggling was directly caused by invisible water molecules constantly and violently crashing into the floating pollen. This was the exact proof that firmly established that atoms are physically real objects!", highlight: "Brownian Motion was one of the first irrefutable, visible proofs that the universe is made of microscopic moving atoms! 🔬" },
    { id: '3', title: 'The Laws of Thermodynamics', color: '#4ECDC4', bgGradient: ['#0A2A2A', '#05050A'], icon: '⚙️', svgIcon: 'lightning', content: "The **1st Law** states that energy cannot be created or destroyed, only changed in form. \n\nThe **2nd Law** dictates that heat ALWAYS inherently flows from a hotter object directly to a colder one. You literally cannot fundamentally cool your kitchen by leaving the refrigerator door open, because the motor running the fridge actively generates more heat than the cooling coils can absorb!", highlight: "The universe is constantly, aggressively trying to equalize temperature everywhere, driving toward maximum entropy. 🌌" },
    { id: '4', title: 'Conduction', color: '#FFD166', bgGradient: ['#2A2A00', '#05050A'], icon: '🍳', svgIcon: 'grid', content: "**Conduction** is the transfer of severe heat through direct physical contact. \n\nWhen you place an iron skillet on a roaring stove, the atoms at the very bottom heat up. They vibrate violently, physically crashing into the atoms above them, passing the kinetic energy all the way up into the handle and into your food! Metals conduct exceptionally well because their electrons are free loosely to race around.", highlight: "Wood is an incredible insulator because its atoms are locked tight organically, preventing rapid kinetic transfer! 🪵" },
    { id: '5', title: 'Convection', color: '#A855F7', bgGradient: ['#1A0A2A', '#05050A'], icon: '🌪️', svgIcon: 'waves', content: "**Convection** is the transfer of profound heat through the aggressive movement of fluids (like water or atmospheric air).\n\nWhen air is heavily heated, the atoms spread drastically apart, becoming less dense and violently rising. Cooler, denser air immediately rushes in beneath to replace it. This massive circular flow creates convection currents, which exclusively drive the Earth's weather, tornadoes, and bubbling boiling water!", highlight: "The tectonic plates shifting under your feet are physically driven by colossal, slow-moving convection currents in Earth's magma! 🌋" },
    { id: '6', title: 'Radiation', color: '#00D4FF', bgGradient: ['#001A2A', '#05050A'], icon: '☀️', svgIcon: 'sparkle', content: "**Radiation** is the transfer of heat purely through electromagnetic waves across completely empty space. \n\nThere are exactly zero atoms located between the Sun and the Earth (a true vacuum), meaning conduction and convection are completely impossible! The Sun exclusively heats our entire planet by blasting trillions of radiant photons 150 million kilometers into the vacuum.", highlight: "Every single object above absolute zero rigidly emits thermal radiation. Yes, even you are glowing invisibly in the dark right now! 🦉" },
    { id: '7', title: 'Absolute Zero (0 Kelvin)', color: '#39FF14', bgGradient: ['#0A2A0A', '#05050A'], icon: '❄️', svgIcon: 'target', content: "The Kelvin scale doesn't utilize degrees; it strictly measures raw atomic vibration.\n\n**0 Kelvin (-273.15°C)** is Absolute Zero. At this exact terrifying boundary, all thermodynamic atomic motion completely stops. It represents a state of zero heat energy. Interestingly, due to terrifying quantum mechanics, electrons never actually stop entirely, retaining 'zero-point' energy.", highlight: "We have artificially cooled lasers in labs to within a billionth of a degree of Absolute Zero, but hitting 0K exactly is mathematically impossible! 🔬" },
    { id: '8', title: 'Specific Heat Capacity', color: '#FF3131', bgGradient: ['#2A000A', '#05050A'], icon: '🌊', svgIcon: 'cube', content: "**Specific Heat** measures exactly how much massive energy an object requires to raise its temperature by exactly 1 degree. \n\nLiquid Water is a complete freak of nature—it possesses one of the highest specific heat capacities of any substance on Earth. It requires a colossal amount of solar energy to warm up, and retains that heat incredibly well.", highlight: "Water's freakishly high specific heat is precisely why coastal cities have exceptionally mild climates compared to harsh deserts! 🏖️" },
    { id: '9', title: 'Latent Heat & State Changes', color: '#6C5CE7', bgGradient: ['#1A0A2A', '#05050A'], icon: '🧊', svgIcon: 'link', content: "When you boil an aggressive pot of water, the temperature strictly hits 100°C and stays exactly there! \n\nThe roaring fire is still dumping energy in, but instead of raising the temperature, the energy is entirely hijacked to violently break the structural atomic bonds, turning the liquid into an atmospheric gas. This hidden energy absorption is called **Latent Heat**.", highlight: "Sweating aggressively cools your body because the dying sweat drops absorb massive body heat to achieve the state change necessary to evaporate! 🥵" },
    { id: '10', title: 'Thermal Expansion', color: '#55EFC4', bgGradient: ['#0A2A1A', '#05050A'], icon: '🌉', svgIcon: 'shield', content: "As things heavily heat up, their atoms intensely vibrate significantly faster, violently pushing apart from each other. \n\nConsequently, almost every solid object visibly expands when heated! This is why severe bridges have metal 'expansion joints' built into the asphalt. Without them, the hot summer sun would aggressively expand the concrete until the massive structural pressure snapped the bridge in half.", highlight: "Water is arguably the ONLY chemical exception! When it massively freezes into rigid ice, its crystalline structure expands instead of shrinking! 🧊" }
  ],

  lab: {
    title: "Thermodynamics Chamber 🌡️",
    description: "Welcome to the Thermodynamic Engine. Take precision control of a closed-system beaker, adjusting kinetic energy transfers. Push the atoms towards absolute zero or force them to violently shatter bonds through boiling.",
    hint: "Push the thermal dial aggressively past 100°C and observe the molecular chain breakdown.",
    scientistModeHint: "Scientist Mode reveals exact Joules transferred and live Kelvin scaling.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why metal physically feels significantly colder than wood at room temperature? 🧊", answer: "All metals are exceptionally excellent thermal conductors. When you touch wood, your immediate body heat strongly stays in your sensitive fingertips. When you physically touch metal, the metal rapidly and ruthlessly sucks the heat away from your skin down the rod, making it 'feel' incredibly cold even though both objects are the exact same temperature!", emoji: '🪚' },
    { id: 'dyk2', question: "Do you know why humans aggressively blow on extremely hot food to cool it down? 🍲", answer: "Hot soup violently heats the tiny layer of atmospheric air immediately above the bowl. If that exact air stays stagnant, cooling effectively slows down drastically. By aggressively blowing, you forcibly establish strong convection currents, ripping that hot air away and replacing it with brutally cold air to suck out more soup heat!", emoji: '🌬️' },
    { id: 'dyk3', question: "Do you know why space blankets made of extremely thin tin-foil keep severely freezing people warm? 🏕️", answer: "Because conduction and convection are largely irrelevant to deep body heat loss—the primary killer is invisible Thermal Radiation. Reflective silver foil acts as an absolute physical mirror, bouncing the escaping invisible infrared photons perfectly back into the body!", emoji: '🛰️' },
    { id: 'dyk4', question: "Do you know why thick black asphalt roads intensely crack relentlessly during brutal winters? 🛣️", answer: "Water is uniquely dangerous—when it naturally freezes, it massively expands. Deep rainwater seeps violently into tiny micro-fissures in the asphalt. When brutal winter hits, the water violently expands by 9%, acting like microscopic wedge bombs that physically tear the massive stone roads apart from the inside!", emoji: '❄️' },
    { id: 'dyk5', question: "Do you know why a massive pot of actively boiling water will never exceed 100 degrees Celsius regardless of the fire? ♨️", answer: "Once water forcefully hits 100°C, it reaches its absolute phase threshold limit. Every single extra Joule of fire energy pumped into it doesn't arbitrarily raise the temperature—it completely focuses on ripping the structural H2O bonds apart to create atmospheric steam! (Latent Heat)", emoji: '💨' }
  ],

  quiz: [
    { id: 'q1', question: "Absolute Zero, the terrifying temperature where all atomic motion completely ceases, occurs precisely at:", options: ['0 Degrees Celsius', '0 Kelvin', '-100 Degrees Celsius', '-273.15 Kelvin'], answer: 1, explanation: "0 Kelvin (or -273.15°C) is mathematically the absolute coldest anything in the universe can be without breaking physics." },
    { id: 'q2', question: "Which primary scientific mechanism involves heat energy transferring directly through heavy physical contact?", options: ['Radiation', 'Convection', 'Conduction', 'Insulation'], answer: 2, explanation: "Conduction physically transfers energy by having hot, intensely vibrating atoms aggressively crash deeply into slower, colder atoms." },
    { id: 'q3', question: "How does the intensely glowing Sun exclusively transfer its massive heat to the frozen Earth?", options: ['Through massive celestial conduction', 'Through atmospheric convection currents', 'Through pure electromagnetic Radiation', 'Through gravitational dragging'], answer: 2, explanation: "Space is an absolute vacuum. Radiation utilizes distinct invisible infrared electromagnetic waves that require absolutely no atoms to travel." },
    { id: 'q4', question: "What profound thermodynamic principle dictates that heat will ALWAYS inherently flow from hot specifically to cold?", options: ["Newton's First Law", "The Second Law of Thermodynamics", "Boyle's Law", "The Law of Thermal Extraction"], answer: 1, explanation: "The Second Law of Thermodynamics mathematically proves that energy always actively tries to spread out rapidly, increasing the system's entropy." },
    { id: 'q5', question: "The intense random chaotic jiggling of microscopic particles strictly caused by invisible atoms severely crashing into them is:", options: ['Brownian Motion', 'Thermal Expansion', 'Absolute Convection', 'Isotopic Decay'], answer: 0, explanation: "Brownian Motion, explicitly explained by Albert Einstein, was the brutal ultimate proof that structural atoms were not simply a myth." },
    { id: 'q6', question: "Why do civil engineers deliberately build small physical gaps (expansion joints) into massive super-bridges?", options: ['To violently reduce earthquake tremors', 'Because incredibly hot summer days cause the solid steel to heavily expand', 'To prevent strong wind from snapping it', 'To reduce the bridge weight limit'], answer: 1, explanation: "Thermal Expansion dictates that brutal heat severely vibrates the heavy steel atoms apart, requiring structural survival room to expand safely." },
    { id: 'q7', question: "What is uniquely dangerous about liquid water when the brutal winter aggressively freezes it into solid ice?", options: ['It heavily absorbs all radiation', 'It shrinks violently into a dense core', 'It forcefully expands its physical volume', 'It becomes a super-conductor'], answer: 2, explanation: "In a total freak of chemistry, freezing water structures its hydrogen bonds into rigid hexagonal lattices, making ice uniquely expand instead of shrinking." },
    { id: 'q8', question: "The specific amount of massive energy rigidly required to heat 1 kilogram of a substance by precisely 1 degree is its:", options: ['Thermal Tolerance', 'Specific Heat Capacity', 'Latent Flashpoint', 'Absolute Entropy'], answer: 1, explanation: "Specific heat completely determines how violently fast a substance heats up. Water has an incredibly high capacity, refusing to boil instantly." },
    { id: 'q9', question: "When boiling aggressive water perfectly reaches 100°C, the incoming fire energy stops raising the temperature and is instead highly used to:", options: ['Create a plasma arc', 'Physically tear the molecular bonds apart to generate steam', 'Expand the metal pot significantly', 'Reverse the atomic structure entirely'], answer: 1, explanation: "This incredibly hidden energy transition is officially Latent Heat. The energy violently diverts to ripping liquid bonds apart entirely." },
    { id: 'q10', question: "A massive, towering glacier undeniably possesses significantly MORE total Heat Energy than a tiny boiling kettle because:", options: ['Ice is uniquely radioactive', 'The glacier reflects pure radiation heavily', 'Heat strictly measures the TOTAL energy of all atoms combined', 'Ice intrinsically generates internal friction slowly'], answer: 2, explanation: "Although the iceberg is brutally cold on average, its colossal size heavily means it contains quadrillions more atoms, yielding a much larger sum of Heat." },
    { id: 'q11', question: "Why does brutally hot air severely rise upward to create massive convection weather forces?", options: ['It reacts chemically with atmospheric nitrogen', 'Heat structurally reduces the effects of gravity', 'Hot air expands wildly, heavily decreasing its density', 'It generates a negative electrical charge instantly'], answer: 2, explanation: "As fierce thermal energy heavily pushes the hot air atoms effectively apart, it violently becomes less dense than cold air, making it aggressively float." },
    { id: 'q12', question: "Which heavy material makes for an incredibly effective thermal insulator against aggressive cold?", options: ['Thick Oak Wood', 'Solid Steel', 'Liquid Mercury', 'Pure Copper'], answer: 0, explanation: "Wood rigidly traps its heavily bound atomic electrons tightly, heavily preventing kinetic vibrations from efficiently travelling through the heavy log." },
    { id: 'q13', question: "A brutally black car powerfully becomes vastly hotter than a pure white car in the screaming summer sun because:", options: ['Black paint is chemically radioactive', 'White paint deeply absorbs severe radiation', 'Black surfaces aggressively absorb absolutely all visible light wavelengths', 'Black severely repels heavy atomic convection'], answer: 2, explanation: "Black objects ruthlessly absorb every single photon that directly strikes them, violently turning that heavy electromagnetic energy into pure heat." },
    { id: 'q14', question: "What completely invisible form of heavy radiation do all living creatures fiercely emit?", options: ['Visible Light', 'Ultraviolet Rays', 'Microwaves', 'Infrared Radiation'], answer: 3, explanation: "Infrared strictly transfers thermal photon energy. Extreme high-tech military night-vision deeply relies on catching these terrifyingly invisible thermal waves." },
    { id: 'q15', question: "If you radically leave your refrigerator heavily open, the precise room temperature will fundamentally do what?", options: ['Severely freeze heavily', 'Slightly cool down', 'Remain identically the same', 'Vastly increase and heavily heat up'], answer: 3, explanation: "The Second Law dictates that the heavy compressor motor wildly working completely overtime to dump the heavy heat actually heavily expels more severe heat than the fierce cold it creates." },
    { id: 'q16', question: "What heavily hidden thermodynamic property heavily cools humans rapidly through severe vicious sweating?", options: ['Heavy Conduction', 'Evaporative Cooling (Latent Heat)', 'Thermal Shielding', 'Radiant reflection'], answer: 1, explanation: "When the heavy water forcibly evaporates violently off your skin, it aggressively steals massive volumes of precious body heat to forcefully tear the heavy liquid bonds." },
    { id: 'q17', question: "Which scientific temperature scale fiercely positions its absolute starting point rigidly at Absolute Zero?", options: ['Celsius', 'Fahrenheit', 'Kelvin', 'Rankine'], answer: 2, explanation: "Kelvin utilizes no arbitrary numbers. It fiercely starts entirely at the absolute bottom of physics (0K) and heavily moves aggressively up from there." },
    { id: 'q18', question: "Fierce tectonic plates massively shift around the deep Earth purely due to what heavy driving process down in the magma?", options: ['Heavy Convection Currents', 'Thermal Radiation', 'Static Magnetic Discharge', 'Solar Bombardment'], answer: 0, explanation: "The violently hot molten core heavily heats the heavy bottom magma, violently causing it to float aggressively up, slowly dragging the fierce heavy crust." },
    { id: 'q19', question: "What effectively occurs violently at a massive molecular level when severe heat is heavily added to heavy ice?", options: ['The solid atoms shrink drastically together', 'The dense ice heavily expels violent infrared rays', 'The rigid atoms significantly vibrate faster, deeply loosening the solid dense bonds', 'The hydrogen fiercely combusts'], answer: 2, explanation: "Heat purely equals raw atomic speed. The solid atoms aggressively vibrate faster until the fierce crystalline rigid bond entirely breaks down into heavy liquid." },
    { id: 'q20', question: "Why do heavily insulated intense metal thermos flasks powerfully keep hot fierce coffee hot for profound hours?", options: ['They generate a heavy magnetic field', 'They severely incorporate a heavy pure vacuum layer completely blocking severe conduction/convection', 'They actively produce extreme microwaves', 'They structurally absorb all fierce infrared'], answer: 1, explanation: "Since profound conductions completely require solid vibrating atoms, completely sucking heavily all the atoms violently out (creating a massive vacuum) forcefully halts extreme heat loss entirely." }
  ],

  relatedTopics: ['energy_types', 'waves_sound'],
};
