// ─────────────────────────────────────────────────────────
//  TOPIC: PHOBIAS
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'phobias',
  title: 'Phobias',
  subtitle: 'The evolutionary neuroscience of fear 🕷️🚨',
  emoji: '😱',
  category: 'Society',
  accentKey: 'phobias',

  hook: {
    question: "Why are you absolutely terrified of a tiny spider, but you aren't afraid of driving a car at 70 mph, which is a million times more deadly? 🕷️🚗",
    reveal: "Because your brain's fear system hasn't received a software update in 50,000 years! Cars were invented 100 years ago, so your genes haven't learned to fear them. But spiders, snakes, and heights killed your ancient ancestors for millions of years. A phobia isn't 'crazy'; it is an ancient survival mechanism that is misfiring in the modern world. Let's look inside the Amygdala to see how fear works—and how to delete a phobia! 🧬🧠",
    emoji: '🚨',
  },

  theory: [
    {
      id: 'fear_vs_phobia',
      title: 'Fear vs Phobia 🕷️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🕷️',
      svgIcon: 'alert',
      content: "**Fear** is a rational biological response to an immediate, actual threat (e.g., a bear in the woods). \n\nA **Phobia** is an *irrational, overwhelming* anxiety response to a trigger that poses little or no actual danger (e.g., a spider in a glass tank). \nWhen you have a phobia, the fear response is so powerful that it interferes with your daily life, forcing you to go to extreme lengths to avoid the trigger. 🛑",
      highlight: "Fear keeps you alive. A phobia traps you in an imaginary cage. 🕸️",
    },
    {
      id: 'amygdala_hijack',
      title: 'The Amygdala Hijack 🚨',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🚨',
      svgIcon: 'zap',
      content: "Inside your brain is an almond-shaped structure called the **Amygdala**. It is your biological smoke detector. \n\nWhen you see your phobia trigger, the visual data hits the Amygdala *before* it even reaches your logical Prefrontal Cortex. The Amygdala hits the panic button instantly! \nThis is called an **Amygdala Hijack**. Your logical brain is completely bypassed. This is why you can *know* a spider is harmless, but your body still screams in terror. The logical brain is literally locked out of the control room! 💥",
      highlight: "You cannot reason your way out of a phobia because logic isn't even online! 🧠",
    },
    {
      id: 'evolutionary_preparedness',
      title: 'Evolutionary Preparedness 🧬',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🧬',
      svgIcon: 'eye',
      content: "Why are the most common phobias about snakes (Ophidiophobia) and spiders (Arachnophobia)? \n\nPsychologist Martin Seligman proposed **Evolutionary Preparedness**. Our ancient ancestors who were naturally terrified of snakes survived to pass on their genes. Those who thought snakes were cute got bitten and died. \nWe are genetically 'prepared' to easily learn fears of ancient threats, but we rarely develop phobias of modern threats like guns, cars, or electricity! ⚡",
      highlight: "Your phobia is ancient genetic wisdom that is no longer useful. 🏺",
    },
    {
      id: 'the_startle_reflex',
      title: 'The Startle Reflex ⚡',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⚡',
      svgIcon: 'refresh',
      content: "When confronted with a phobia, your body triggers the **Startle Reflex** (Fight-or-Flight). \n\nInstantly, your body releases Adrenaline and Cortisol.\n1. Your pupils dilate (to see the threat). 👀\n2. Blood rushes from your stomach to your legs (ready to run). 🏃‍♂️\n3. Your breathing becomes rapid and shallow (getting oxygen). 🫁\n\nIt feels like a Panic Attack, but your body is actually functioning perfectly—it's just fighting a ghost! 👻",
      highlight: "Panic is just your body preparing you for an Olympic sprint. 🎖️",
    },
    {
      id: 'classical_conditioning',
      title: 'Little Albert & Conditioning 👶',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '👶',
      svgIcon: 'target',
      content: "Phobias can also be learned through **Classical Conditioning**. \n\nIn the infamous 1920 'Little Albert' experiment, Watson showed a baby an innocent white rat. At the same time, he smashed a hammer against a steel bar, terrifying the baby. \nAfter a few repetitions, the baby became terrified of the rat even without the noise! The brain associated the harmless object with extreme pain. Many phobias start with a single terrifying childhood event. 🐀",
      highlight: "Your brain links objects to trauma to protect you in the future. 🔗",
    },
    {
      id: 'observational_learning',
      title: 'Observational Learning 👀',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '👀',
      svgIcon: 'users',
      content: "You don't even have to experience trauma yourself to get a phobia! \n\nThrough **Observational Learning**, if a child sees their mother scream in absolute terror at a dog, the child's brain takes notes: 'Mother is terrified $\\rightarrow$ Dogs equal death.' \nPhobias are highly contagious within families purely through social mimicry. Our brains learn from the mistakes and fears of the tribe to save time! 🏕️",
      highlight: "Fear is contagious. You can inherit a phobia just by watching someone else. 👥",
    },
    {
      id: 'generalization',
      title: 'Fear Generalization 🌫️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌫️',
      svgIcon: 'cloud',
      content: "When a phobia starts, it often spreads through **Generalization**. \n\nIf you get bitten by a Golden Retriever, your brain first fears Golden Retrievers. But to be 'safe,' the brain expands the rule: Now you fear ALL dogs. Then, you fear ALL fluffy animals. Eventually, you might panic when you see a fluffy rug! \nThe brain's safety mechanism is incredibly sloppy and aggressively over-generalizes threats. 🐩",
      highlight: "Better to mistake a stick for a snake, than a snake for a stick. 🐍",
    },
    {
      id: 'the_avoidance_trap',
      title: 'The Avoidance Trap 🪤',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🪤',
      svgIcon: 'lock',
      content: "If you have a phobia of elevators, what happens when you take the stairs instead? \n\nYou feel massive relief! This relief is a dopamine reward. Therefore, **Avoidance is highly addictive.** \nEvery time you avoid your trigger, you reinforce the neural pathway that says: 'The elevator is deadly, and avoiding it saved my life.' Avoidance feels like the cure, but it is actually the glue that makes the phobia permanent! 🚪",
      highlight: "Running away from fear feeds it. Avoidance guarantees the phobia survives. 🏃‍♂️",
    },
    {
      id: 'exposure_therapy',
      title: 'Exposure Therapy 🪜',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🪜',
      svgIcon: 'shield',
      content: "To cure a phobia, you must stop avoiding it. The gold-standard treatment is **Exposure Therapy** (Systematic Desensitization). \n\nYou cannot reason with the Amygdala using words; you must speak to it in its native language: *Experience and Time*.\nIf you stay in the presence of the fear trigger long enough, without running away, the Amygdala eventually realizes you aren't dead. It slowly turns off the alarm. 🛑",
      highlight: "You have to show the ancient brain that the modern trigger is safe. 🖼️",
    },
    {
      id: 'fear_ladder',
      title: 'Building a Fear Ladder 📈',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📈',
      svgIcon: 'chart',
      content: "Exposure therapy uses a 'Fear Ladder' (Fear Hierarchy). You don't start by touching the spider! \n\n1. Look at a cartoon drawing of a spider. (Anxiety spikes, then drops).\n2. Look at a real photo of a spider.\n3. Watch a video of a spider.\n4. Look at a spider in a jar 10 feet away.\n5. Touch the jar.\n\nBy taking tiny steps, you rewrite the Amygdala's software one safe prediction at a time! 🪜🕷️",
      highlight: "Gradual exposure reprograms the brain without causing an overwhelming hijack. 🧩",
    },
    {
      id: 'flooding',
      title: 'Flooding (The Hard Way) 🌊',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🌊',
      svgIcon: 'waves',
      content: "An alternative to the Fear Ladder is **Flooding**. \n\nIn Flooding, you jump straight to the top of the ladder. If you fear enclosed spaces (Claustrophobia), the therapist locks you in a closet for an hour. \nYour anxiety spikes to absolute maximum, but biologically, the body cannot sustain maximum panic forever. Eventually, the adrenaline runs out, the heart rate drops, and your brain realizes you survived. It is highly effective but brutally terrifying! 🚪",
      highlight: "Flooding proves to the brain: 'I experienced my worst nightmare, and I survived.' 💪",
    },
    {
      id: 'vr_therapy',
      title: 'Virtual Reality Therapy 🥽',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🥽',
      svgIcon: 'brain',
      content: "Neuroscience is now using **Virtual Reality (VR)** to cure phobias! \n\nIf someone has a fear of flying (Aviophobia), buying 10 plane tickets for Exposure Therapy is too expensive. \nInstead, they put on a VR headset. The brain is so reliant on visual data that the Amygdala genuinely believes the VR airplane is real and triggers anxiety. The patient can practice conquering their fear from the safety of a couch! ✈️ Couch 🛋️ $\\rightarrow$ Plane ✈️",
      highlight: "VR tricks the ancient Amygdala while keeping the logical brain feeling safe. 🎮",
    },
    {
      id: 'trypophobia',
      title: 'Trypophobia: The Weird One 🧀',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🧀',
      svgIcon: 'eye',
      content: "**Trypophobia** is an intense disgust or fear of clustered holes (like a lotus seed pod, a sponge, or honeycomb). \n\nWhy on earth would we fear holes?\nEvolutionary biologists believe this isn't a 'fear' response, but a 'disgust' response to avoid infectious diseases. Clustered holes visually resemble skin lesions, pox, or parasites. Your brain triggers a powerful revulsion to keep you away from potential pathogens! 🦠",
      highlight: "Some phobias are triggered by an evolutionary mandate to avoid disease. 🛡️",
    },
    {
      id: 'megalophobia',
      title: 'Megalophobia & Thalassophobia 🌊',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌊',
      svgIcon: 'users',
      content: "Other common modern phobias include:\n\n• **Megalophobia:** Fear of massive objects (like giant statues or massive cruise ships). This likely triggers our predator-prey system, making us feel small and vulnerable. 🚢\n• **Thalassophobia:** Fear of the deep, dark ocean. The brain hates the unknown. When you look into dark water, your brain automatically predicts the worst-case scenario (a hidden predator) swimming beneath you. 🦈",
      highlight: "The brain fills an empty void with its worst nightmares to keep you on guard! 👁️",
    },
    {
      id: 'the_cure_is_courage',
      title: 'Reclaiming Your Brain 🧗‍♂️',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🧗‍♂️',
      svgIcon: 'sparkle',
      content: "A phobia is just a learned misprediction by your brain. Because it was *learned*, it can be *un-learned*. \n\nThe cure for a phobia isn't logic; it is courage. Courage doesn't mean you aren't afraid. Courage means your heart is pounding, your palms are sweating, but you touch the spider's jar anyway. Exposure is the fire that burns away the phobia. 🔥",
      highlight: "On the other side of your maximum fear, lies your ultimate freedom. 🦋",
    },
  ],

  lab: {
    title: "Exposure Therapy VR 🥽🕷️",
    description: "Welcome to the Clinic. Your patient presents with severe Arachnophobia. Your goal is to guide them down the 'Fear Ladder'. First, lower the 'Distance to Target' slider. If you go too fast, their Cortisol (Panic) meter will explode and cause an Amygdala Hijack. Use 'Breathing Exercises' to lower their heart rate before taking the next step. Can you touch the jar without causing a panic attack? 🎛️",
    hint: "Don't just jump to '0 yards' (Flooding) unless you are prepared for massive panic! Move the distance slider gradually. When Cortisol spikes into the red, pause and use the Breathing button until it drops, then move closer.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Amygdalar Hyperactivity index, GABA neuroreceptor synthesis rates, and real-time HPA-axis data.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we scream when we are startled? 😱",
      answer: "The 'Scream' is a dual-purpose evolutionary reflex! First, it is an acoustic alarm system to warn the rest of your tribe that a predator is near. Second, screaming forces a massive, rapid exhale of air from the lungs, preparing your body to take an immediate, deep gasp of fresh oxygen so you can sprint away! 🏃‍♂️💨",
      emoji: '🚨',
    },
    {
      id: 'dyk2',
      question: "Do you know why phobias often cause people to faint (like the sight of blood)? 🩸",
      answer: "Fainting is usually caused by the Vagus Nerve overreacting! While most fears cause your heart rate to spike (Fight or Flight), the sight of blood (Hemophobia) sometimes triggers a sudden, massive drop in blood pressure. This ancient response might have evolved so a bleeding human would collapse, lie still, and 'play dead' so the predator loses interest! 👻",
      emoji: '📉',
    },
    {
      id: 'dyk3',
      question: "Do you know why we freeze when we see a snake? 🐍",
      answer: "Fight, Flight... or Freeze! Freezing is often the very first reflex. Because many predators (like snakes and T-Rexes in movies) hunt based on movement, freezing makes you instantly invisible to their visual cortex. Your brain hits the brakes before it even decides whether to fight or run! 🛑",
      emoji: '🧊',
    },
    {
      id: 'dyk4',
      question: "Do you know why agoraphobia is often misunderstood as 'fear of the outdoors'? 🏡",
      answer: "Agoraphobia is actually the fear of having a panic attack in a place where escape is difficult or embarrassing! It's not a fear of grass or sun. People get terrified of being trapped in crowds, bridges, or malls. To ensure they always have an 'escape Route', they just stop leaving their house altogether. 🚪",
      emoji: '🪤',
    },
    {
      id: 'dyk5',
      question: "Do you know why fear makes time seem to slow down? ⏳",
      answer: "Memory densification! When you are terrified, the Amygdala triggers hyper-focus, taking vastly more 'pictures' of the event per second than normal. When you remember the event later, your brain stretches out those extra details, giving you the illusion that the terrifying 5-second car crash actually lasted for a whole minute! 📸",
      emoji: '⏱️',
    },
    {
      id: 'dyk6',
      question: "Do you know why beta-blockers are given to performers with severe stage fright? 💊",
      answer: "Beta-blockers physically block Adrenaline from binding to receptors in your heart! Your Amygdala still says 'PANIC!', but your heart cannot physically race, and your hands cannot shake. Because the body stays calm, the 'feedback loop' is broken, and the mind soon realizes there is actually no danger. 🛡️",
      emoji: '💉',
    },
    {
      id: 'dyk7',
      question: "Do you know why you sweat when you are terrified, even if you are cold? 🥶",
      answer: "Thermal regulation for the sprint! Your brain knows that you are about to either fight a bear or run 5 miles. Because extreme muscle exertion generates massive heat, your body pre-emptively starts sweating *before* you run to prevent your internal organs from cooking during the escape! 💦",
      emoji: '🏃‍♂️',
    },
    {
      id: 'dyk8',
      question: "Do you know why people with severe phobias 'scan' rooms constantly? 👁️",
      answer: "Hypervigilance! When the Amygdala is locked into a fear state, it forces the eyes to constantly scan the horizon for threats. This drains a massive amount of cognitive energy. People with phobias or PTSD are exhausted at the end of the day because their brain ran a threat-radar 24/7! 📡",
      emoji: '🔋',
    },
    {
      id: 'dyk9',
      question: "Do you know why clowns are one of the most common phobias (Coulrophobia)? 🤡",
      answer: "The 'Uncanny Valley.' The human brain relies on reading facial expressions to predict if someone is friendly or a threat. A clown's makeup paints a permanent, static emotion (a huge smile). The brain knows the face is human, but the lack of micro-expressions makes it look like an unpredictable, soulless threat! 🎭",
      emoji: '😶‍🌫️',
    },
    {
      id: 'dyk10',
      question: "Do you know why we sometimes feel the urge to jump when looking over a tall ledge? 🏢",
      answer: "The 'High Place Phenomenon' (The Call of the Void)! This is actually a glitch in your survival instinct. Your balance system realizes 'I am too close to the edge!' and you reflexively step back. Your logical brain then asks 'Why did I step back?' and misinterprets the data, concluding: 'Oh my god, I must have wanted to jump!' It's a misread safety signal! 🛑",
      emoji: '🕳️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the biological difference between a Fear and a Phobia?", options: ['Fear is fake, Phobias are real', 'Fear is a rational response to an actual threat; a Phobia is an irrational response to a safe/unlikely trigger', 'Fear lasts longer', 'They are the exact same thing'], answer: 1, explanation: "A phobia is your threat-radar malfunctioning! 🚨" },
    { id: 'q2', question: "During an 'Amygdala Hijack', which part of your brain is completely bypassed?", options: ['The Brainstem', 'The logical Prefrontal Cortex', 'The visual cortex', 'The spinal cord'], answer: 1, explanation: "You can't logic your way out of a phobia because the logic center is offline! 🧠" },
    { id: 'q3', question: "Evolutionary Preparedness explains why we are much more likely to develop phobias of:", options: ['Cars and guns', 'Snakes, spiders, and heights', 'Books', 'Chairs'], answer: 1, explanation: "We carry the genetic memories of the things that killed our ancient ancestors! 🐍" },
    { id: 'q4', question: "What does the 'Startle Reflex' (Fight or Flight) physically do to the body?", options: ['Slows the heart rate', 'Releases adrenaline, dilates pupils, and pushes blood to the legs', 'Makes you sleepy', 'Stops digestion permanently'], answer: 1, explanation: "It prepares your body for an Olympic sprint to survive! 🏃‍♂️" },
    { id: 'q5', question: "In the 'Little Albert' experiment, a baby learned to fear a white rat because:", options: ['Rats are evil', 'It was conditionally paired with a terrifying loud noise', 'The rat bit him', 'He was allergice'], answer: 1, explanation: "Classical Conditioning links a neutral object to trauma. 🔗" },
    { id: 'q6', question: "Can you develop a phobia by watching someone ELSE be terrified of something?", options: ['Yes, through Observational Learning', 'No, impossible', 'Only if you are under 5', 'Only with spiders'], answer: 0, explanation: "Fear is socially contagious; we learn from the herd's mistakes! 👥" },
    { id: 'q7', question: "Fear 'Generalization' occurs when the brain:", options: ['Forgets the fear', 'Expands the fear from one specific trigger (a dog) to all similar things (all fluffy things)', 'Makes the fear smaller', 'Writes an essay'], answer: 1, explanation: "A sloppy brain expands the threat to guarantee safety. 🌫️" },
    { id: 'q8', question: "Taking the stairs to avoid a terrifying elevator creates a dopamine reward that:", options: ['Cures the phobia', 'Makes you fit', 'Heavily reinforces and locks in the phobia (The Avoidance Trap)', 'Fixes the Amygdala'], answer: 2, explanation: "Avoidance is the superglue that makes phobias permanent! 🪤" },
    { id: 'q9', question: "The gold-standard psychological treatment for curing a phobia is:", options: ['Surgical removal of the Amygdala', 'Exposure Therapy (Systematic Desensitization)', 'Ignoring it', 'Yelling at it'], answer: 1, explanation: "You must prove to the primal brain that the trigger is safe. 🪜" },
    { id: 'q10', question: "What is a 'Fear Ladder'?", options: ['A scary ladder', 'A step-by-step approach to exposure, starting with looking at a photo before touching the real trigger', 'A ladder used by spiders', 'A bad dream'], answer: 1, explanation: "Gradual exposure reprograms the brain without causing a massive panic attack! 📈" },
    { id: 'q11', question: "What is 'Flooding' in phobia therapy?", options: ['Drowning the person', 'Jumping to the absolute top of the fear ladder immediately until the adrenaline runs out', 'Taking a bath', 'Crying'], answer: 1, explanation: "It is terrifying, but it proves to the brain that the worst-case scenario isn't fatal. 🌊" },
    { id: 'q12', question: "Why is Virtual Reality (VR) used to treat Aviophobia (fear of flying)?", options: ['It is a video game', 'It perfectly tricks the visual-heavy Amygdala into triggering anxiety while keeping the patient safe in a clinic', 'It is loud', 'It cures vision'], answer: 1, explanation: "VR safely 'hacks' the visual cortex to practice exposure! 🥽" },
    { id: 'q13', question: "Trypophobia (fear of clustered holes) is believed to be an evolutionary defense against:", options: ['Cheese', 'Infectious diseases and parasites', 'Bees', 'Falling'], answer: 1, explanation: "It triggers profound disgust to keep you away from pox and lesions! 🦠" },
    { id: 'q14', question: "Thalassophobia is the fear of:", options: ['Glass', 'The deep, dark ocean (fear of the unknown)', 'Lassoes', 'Tall buildings'], answer: 1, explanation: "The brain projects its worst nightmares into empty darkness! 🦈" },
    { id: 'q15', question: "The ultimate cure for a learned phobia is the courage to:", options: ['Hide forever', 'Endure the exposure so the Amygdala can relearn that the trigger is safe', 'Sleep', 'Read a book'], answer: 1, explanation: "Experience is the only language the primal brain understands! 🔥" },
    { id: 'q16', question: "Why do some people faint when they see blood (Hemophobia)?", options: ['They are tired', 'A Vagus nerve overreaction causes a massive drop in blood pressure (playing dead)', 'They forget to breathe', 'They fall asleep'], answer: 1, explanation: "The brain decides playing dead is safer than fighting! 🩸" },
    { id: 'q17', question: "Why do we 'freeze' when we see a threat?", options: ['We are cold', 'It makes us visually invisible to motion-based predators while the brain decides what to do', 'To take a photo', 'To trick them'], answer: 1, explanation: "Hitting the brakes hides you from a T-Rex's vision! 🧊" },
    { id: 'q18', question: "Agoraphobia is often misunderstood, but fundamentally it is the fear of:", options: ['Grass', 'Having a panic attack in a place where escape is difficult or embarrassing', 'Spiders in the yard', 'Clouds'], answer: 1, explanation: "They trap themselves at home to guarantee an escape route. 🏡" },
    { id: 'q19', question: "Why does fear make time seem to 'slow down'?", options: ['Gravity shifts', 'The Amygdala takes vastly more memory snapshots per second, stretching the memory out', 'Light moves slower', 'You blink less'], answer: 1, explanation: "Memory densification makes a 5-second crash feel like a minute! 📸" },
    { id: 'q20', question: "The 'Call of the Void' (urge to jump off a ledge) is actually:", options: ['A death wish', 'A delay in your brain interpreting its own automatic safety reflex (stepping back)', 'Gravity', 'Wind'], answer: 1, explanation: "Your balance system triggered a step back, and the logical brain misread the data! 🕳️" },
  ],

  relatedTopics: ['science_of_emotion', 'mental_syndromes', 'mental_health_basics'],
};
