export default {
  // ── IDENTITY ────────────────────────────────
  id: 'industrial_revolution',
  title: 'The Industrial Revolution',
  subtitle: 'Steam, steel, and the birth of the modern world 🏭',
  emoji: '🏭',
  category: 'History',
  accentKey: 'industrial',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "For 10,000 years, the fastest a human could travel was the speed of a horse. Then, in just one century, we built steam trains, spanned continents with telegraph wires, and electrified cities. How did the world change so fast? 🚂",
    reveal: "It all started with WATER and COAL! We figured out how to use heat to boil water, create steam, and use that expansion to push a piston. That simple machine — the steam engine — replaced muscle and wind power. Suddenly, factories could run day and night, trains could haul massive loads, and humanity unlocked limitless energy. The Industrial Revolution didn't just change how we made things; it invented the weekend, standardized time zones, and created the modern city! 🤯",
    emoji: '🔥',
  },

  // ── THEORY CARDS (10) ───────────────────────
  theory: [
    {
      id: 'pre_industrial',
      title: 'The World Before 🌍',
      color: '#8DB600',
      bgGradient: ['#1A250A', '#0D0D1A'],
      icon: '🌾',
      svgIcon: 'leaf',
      content: "Before 1750, 80% of the world's population lived in rural areas. Life was dictated by the sun and the seasons. \n\n🧵 *Cottage Industry* — Most goods (like clothing) were made by hand in people's homes. A merchant would bring wool, and a family would spin and weave it over weeks.\n🐎 *Travel* — The fastest you could go was on horseback. Moving heavy goods over land was insanely expensive, so most trade happened by boat.\n⏳ *Pace of Life* — Productivity was limited by human and animal muscle. If you were tired, the work stopped.\n\nEverything changed when we figured out how to unlock the stored energy inside the earth. The world was about to speed up... permanently. ⏳",
      highlight: "Before the Industrial Revolution, 80% of people lived on farms, and human/animal muscle did all the work! 💪",
    },
    {
      id: 'textile_boom',
      title: 'The Textile Boom 🧵',
      color: '#FF9F1C',
      bgGradient: ['#2A1800', '#0D0D1A'],
      icon: '🧵',
      svgIcon: 'star',
      content: "The Industrial Revolution started in the clothing industry! Britain had massive supplies of wool and imported cotton, but hand-spinning was too slow.\n\n⚙️ *Spinning Jenny* (1764) — Invented by James Hargreaves. It allowed one worker to spin 8 threads at once instead of just one! Soon, it was improved to spin 120 threads at once.\n🌊 *Water Frame* (1769) — Richard Arkwright hooked a spinning machine to a water wheel. Suddenly, machines were too big for homes. *The first factories were born!* They had to be built next to fast-flowing rivers.\n\nThese machines made cloth insanely cheap and plentiful. But they had a flaw: if the river froze or dried up, the factory stopped. They needed a power source that worked anywhere, anytime. 💧",
      highlight: "The very first factories were built next to rivers because they used giant water wheels for power! 🌊",
    },
    {
      id: 'steam_engine',
      title: 'The Power of Steam 🚂',
      color: '#FF4444',
      bgGradient: ['#2A0A0A', '#0D0D1A'],
      icon: '🚂',
      svgIcon: 'fire',
      content: "The greatest invention of the era: The Steam Engine. The concept was simple: boil water to create steam. Steam expands 1,600 times in volume! If you trap it in a cylinder, it pushes a piston.\n\n🔧 *Thomas Newcomen* (1712) built the first engine to pump water out of coal mines, but it was incredibly inefficient.\n💡 *James Watt* (1776) revolutionized it by adding a separate condenser. His engine was smaller, required a quarter of the coal, and used rotary motion. \n\nWatt's engine didn't just pump water — it could turn wheels! Factories no longer needed to be next to rivers. They could be built in cities, powered by coal. The age of relentless, 24/7 machine power had begun! 🔥",
      highlight: "James Watt didn't invent the steam engine, he perfected it — making it efficient enough to power factories anywhere! ⚙️",
    },
    {
      id: 'coal_iron',
      title: 'Coal & Iron: The Muscle 🪨',
      color: '#A0A0A0',
      bgGradient: ['#1A1A1A', '#0D0D1A'],
      icon: '🪨',
      svgIcon: 'construction',
      content: "To build steam engines, you need Iron. To make iron and run steam engines, you need Coal.\n\n⛏️ *Coal* — Wood forests in Britain were running out. Coal burned hotter and longer. Mining was brutal: men, women, and children worked in dark, cramped, explosive tunnels.\n🔥 *Iron Smelting* — Abraham Darby discovered how to smelt iron using purified coal (coke) instead of wood charcoal. This made iron cheap and incredibly strong.\n\nBy 1850, Britain was producing more iron than the rest of the world COMBINED. It was used to build bridges, giant factory machines, and the most world-changing invention of all... the railway. 🛤️",
      highlight: "Coal and Iron were the lifeblood of the Revolution. Coal provided the heat, and iron provided the unyielding strength for new machines! 🏭",
    },
    {
      id: 'railways',
      title: 'The Age of Railways 🛤️',
      color: '#D4A74A',
      bgGradient: ['#201A0D', '#0D0D1A'],
      icon: '🛤️',
      svgIcon: 'rocket',
      content: "What happens if you turn a steam engine sideways and put it on wheels? You get a locomotive!\n\n🚀 *Stephenson\'s Rocket* (1829) — George Stephenson won a competition with a locomotive that could go 29 mph (47 km/h) — unimaginably fast for the time!\n\nThe impact was staggering:\n1️⃣ *Speed* — A 10-day journey by horse carriage dropped to just 15 hours by train.\n2️⃣ *Fresh Food* — Fish could be caught at the coast and eaten in London the same day.\n3️⃣ *Standard Time* — Every town used to have its own local time (based on the sun). Railways forced the creation of synchronized Time Zones so trains wouldn't crash into each other! ⏱️",
      highlight: "Railways were so fast they literally changed how humans experienced time, resulting in the invention of standard Time Zones! ⏰",
    },
    {
      id: 'factory_system',
      title: 'The Factory System & Labor ⏰',
      color: '#6C63FF',
      bgGradient: ['#100E20', '#0D0D1A'],
      icon: '⏰',
      svgIcon: 'bolt',
      content: "The Revolution changed *how* people worked. \n\nInstead of controlling their own hours at home, workers now clocked into giant factories. The machine dictated the pace. If the machine ran fast, you worked fast. 14-hour workdays, 6 days a week, were standard.\n\n👶 *Child Labor* — Factory owners loved hiring children. They were cheap, didn't form unions, and their tiny hands could reach into jammed machines to pull out threads. Many children worked in deafening, dangerous textile mills or crawled through narrow coal mine shafts.\n\nMachinery was exposed and dangerous. There were no safety laws, no compensation for missing fingers or broken arms. The machines never slept, and the workers were treated as just another replaceable cog. ⚙️",
      highlight: "The factory system replaced independent craftsmen with clock-driven shifts, leading to grueling 14-hour days and child labor. 🕰️",
    },
    {
      id: 'urbanization',
      title: 'Rise of the Cities 🏙️',
      color: '#4ECDC4',
      bgGradient: ['#0A1D1A', '#0D0D1A'],
      icon: '🏙️',
      svgIcon: 'globe',
      content: "As factories popped up, rural populations flooded into cities looking for work. *Urbanization* happened overnight.\n\nManchester's population exploded from 25,000 in 1770 to over 300,000 by 1850! \n\nCities were NOT ready. \n🤢 *The Slums* — Entire families lived in single dark rooms. \n💩 *Disease* — There were no sewers. Human waste was tossed into the streets or seeped into the drinking water. Cholera outbreaks killed thousands.\n🌫️ *The Smog* — Thousands of coal-burning chimneys blocked out the sun. In towns like London, the thick, toxic fog was called a \"Pea Souper.\"\n\nCities became engines of wealth, but for the poor, they were filthy, disease-ridden nightmares. 😷",
      highlight: "Industrial cities grew so fast they lacked sewers and clean water, leading to massive disease outbreaks like Cholera! 🦠",
    },
    {
      id: 'second_rev',
      title: 'The Second Industrial Revolution ⚡',
      color: '#FF6B9D',
      bgGradient: ['#200A13', '#0D0D1A'],
      icon: '⚡',
      svgIcon: 'zap',
      content: "The First Industrial Revolution (1760-1840) was about Coal, Iron, and Steam. \nThe *Second* Industrial Revolution (1870-1914) was about Steel, Electricity, and Chemicals.\n\n🏗️ *Bessemer Process* — Made steel incredibly cheap. Steel is stronger and lighter than iron, allowing us to build skyscrapers and massive ships.\n💡 *Electricity* — Edison and Tesla captured electrical power, lighting up the night and powering silent, clean electric motors.\n📞 *Communication* — The Telegraph (Morse) and later the Telephone (Bell) meant messages didn't have to physically travel anymore. Information moved at the speed of light.\n🛢️ *Oil & Engines* — The internal combustion engine was invented, paving the way for automobiles and airplanes! 🚗",
      highlight: "While the First Revolution ran on Steam and Iron, the Second was powered by Electricity, Steel, and Oil! ⚡",
    },
    {
      id: 'reforms',
      title: 'Social Reforms & Rights ✊',
      color: '#FFD166',
      bgGradient: ['#201A0A', '#0D0D1A'],
      icon: '✊',
      svgIcon: 'shield',
      content: "The horrific conditions of early factory life didn't last forever. People fought back.\n\n🛑 *Luddites* — Weavers whose skills were replaced by machines literally broke into factories and smashed the looms! (Today, a 'Luddite' means someone who hates technology).\n📜 *Labor Unions* — Workers eventually banded together to strike, demanding better pay and safer conditions.\n⚖️ *The Factory Acts* — The UK government finally passed laws banning children under 9 from working, and limiting the hours of older children and women.\n🚰 *Sanitation* — After the \"Great Stink\" of London in 1858 (when the River Thames smelled so bad Parliament had to close!), massive modern sewer systems were built.\n\nSlowly, the wealth generated by the revolution began to improve the standard of living for the middle and working classes. 🎉",
      highlight: "Workers formed unions, fought for child labor laws, and eventually won the rights to safe work and weekends! ⚖️",
    },
    {
      id: 'modern_impact',
      title: 'The Global Impact 🌍',
      color: '#A855F7',
      bgGradient: ['#170A25', '#0D0D1A'],
      icon: '🌍',
      svgIcon: 'planet',
      content: "The Industrial Revolution fundamentally altered the trajectory of human history.\n\nFor 10,000 years, global wealth and population were almost flat. After 1750, they spiked upward like a rocket! 🚀\n\nIt created the modern world: mass production, consumer goods, fast travel, global trade, and the middle class. But it also armed nations with industrialized, devastating weapons (leading into World War I).\n\nAnd there was one massive, invisible cost: *Carbon*. The billions of tons of coal and oil burned to build the modern world released CO₂ into the atmosphere, triggering the global climate change crisis we face today. 🌡️\n\nWe are absolutely living inside the consequences — both the miraculous and the dangerous — of the Industrial Revolution.",
      highlight: "The Industrial Revolution gave us unprecedented wealth, technology, and population growth — but kickstarted modern climate change. 🌍",
    },
  ],
  
  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Industrial Revolution Lab 🏭",
    description: "Explore a fully 3D steam engine, manage factory power belts, and watch urbanization explode across the map! 🚂",
    hint: "Rotate the Steam Engine 360° to see the piston and flywheel working. In the Factory, connect belts from the spinning overhead shaft to power all the looms!",
    scientistModeHint: "In Scientist Mode 🧑‍🔬: Monitor exact Boiler PSI, Steam Temperature, and Factory Output RPM metrics!",
  },

  // ── DO YOU KNOW WHY (5) ─────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the Industrial Revolution started in Britain first? 🇬🇧",
      answer: "Britain had the 'perfect storm' of advantages! 1. Geography: It had massive, easily accessible coal and iron deposits. 2. Economy: It was a wealthy empire with global colonies to supply raw cotton. 3. Political Stability: A stable government that protected inventors' patents. 4. High Wages: British workers were expensive, so factory owners were highly motivated to invent machines to replace them! 🧠",
      emoji: '⚓',
    },
    {
      id: 'dyk2',
      question: "Do you know why early factories loved to hire children? 👶",
      answer: "Three terrible reasons: First, children were paid a fraction of an adult's wage. Second, they didn't complain or form labor unions. Third, and most dangerously, their small hands and bodies were the perfect size to crawl under functioning machines to tie broken threads or dig into narrow coal mining shafts, often resulting in tragic accidents. ⚙️",
      emoji: '😢',
    },
    {
      id: 'dyk3',
      question: "Do you know why the steam engine was so revolutionary compared to water wheels? 🔥",
      answer: "LOCATION! Water wheels were great, but you HAD to build your factory next to a fast-flowing river, often in the middle of nowhere. A steam engine runs on coal and water. You can build a steam factory anywhere—like right in the middle of a big city where all the workers and trade ports are. It untethered industry from geography! 🚂",
      emoji: '🏭',
    },
    {
      id: 'dyk4',
      question: "Do you know why trains forced the invention of Standard Time Zones? ⏰",
      answer: "Before trains, every town set its clock to noon when the sun was highest. London time was 10 minutes ahead of Bristol time! That was fine when travel took days. But steam trains traveled so fast that timetables became a nightmare, and trains were literally crashing into each other because their clocks didn't match. The railways forced the creation of synchronized 'Greenwich Mean Time' (GMT) for everyone! 🚂",
      emoji: '⏱️',
    },
    {
      id: 'dyk5',
      question: "Do you know why 1858 London had 'The Great Stink'? 🤢",
      answer: "London's population exploded due to factories, but it had no modern sewers! Over 2.5 million people's raw waste flowed directly into the River Thames. During an unusually hot summer in 1858, the river essentially boiled with sewage. The stench was so horrific that Parliament (located right on the riverbank) had to soak their curtains in chloride of lime just to breathe. This finally forced them to build London's modern sewer system! 💩",
      emoji: '😷',
    },
  ],

  // ── QUIZ (20) ───────────────────────────────
  quiz: [
    { id: 'q1', question: "What was the main power source before the Industrial Revolution? 💪", options: ['Wind and solar', 'Human and animal muscle', 'Coal and steam', 'Electricity'], answer: 1, explanation: "Before steam engines, almost all work relied on humans, horses, oxen, or small water wheels! 🐴" },
    { id: 'q2', question: "Which industry was the first to industrialize? 🧵", options: ['Farming', 'Weapons', 'Textiles (clothing)', 'Transportation'], answer: 2, explanation: "The textile industry! Inventions like the Spinning Jenny and Water Frame automated the spinning of cotton and wool. 👗" },
    { id: 'q3', question: "Why were the very first factories built next to rivers? 🌊", options: ['For boat access', 'To dump waste', 'To power massive water wheels', 'To drink the water'], answer: 2, explanation: "Before reliable steam engines, massive water wheels powered the early textile machines! ⚙️" },
    { id: 'q4', question: "Who is credited with perfecting the Steam Engine? 🚂", options: ['Thomas Edison', 'James Watt', 'Henry Ford', 'Richard Arkwright'], answer: 1, explanation: "James Watt didn't invent the first steam engine, but his addition of a separate condenser made it incredibly efficient and practical for factories! 🔥" },
    { id: 'q5', question: "What two raw materials were essential for building and running steam engines? 🪨", options: ['Wood and gold', 'Coal and iron', 'Copper and silver', 'Oil and steel'], answer: 1, explanation: "Coal provided the intense heat needed to boil water, and iron was the strong metal used to build the engines and machines! 🏭" },
    { id: 'q6', question: "What was a major result of George Stephenson’s 'Rocket' locomotive? 🛤️", options: ['Travel times dropped drastically', 'People stopped using boats', 'The end of the revolution', 'It replaced coal with oil'], answer: 0, explanation: "The railways shrunk the world! Journeys that took weeks by horse now took mere hours. 🚂" },
    { id: 'q7', question: "Why did factory owners prefer to hire children? 👶", options: ['They learned faster', 'They were cheap and their small hands could fix machines', 'They were stronger', 'It was required by law'], answer: 1, explanation: "Children were paid extremely low wages and could squeeze under heavy machinery to fix jammed threads, which was very dangerous! 😢" },
    { id: 'q8', question: "What does 'urbanization' mean? 🏙️", options: ['Building larger farms', 'People moving from farms to cities', 'The invention of the steam engine', 'Creating labor unions'], answer: 1, explanation: "Urbanization is the massive shift of populations leaving rural areas to move into concentrated, densely packed cities for factory work. 🏘️" },
    { id: 'q9', question: "What was a major negative side-effect of early industrial cities? 😷", options: ['Too much noise limits', 'Lack of raw materials', 'Massive disease outbreaks like cholera due to lack of sewers', 'Too few jobs available'], answer: 2, explanation: "Cities grew so fast they lacked basic sanitation and clean water, leading to deadly diseases spreading rapidly. 🦠" },
    { id: 'q10', question: "What fueled the SECOND Industrial Revolution? ⚡", options: ['Coal, Iron, and Steam', 'Wood, Water, and Wind', 'Steel, Electricity, and Oil', 'Nuclear and Solar'], answer: 2, explanation: "The First revolution was Coal/Steam. The Second (late 1800s) was driven by Steel, Electricity, Chemicals, and the Internal Combustion Engine! 💡" },
    { id: 'q11', question: "What did the Bessemer Process do? 🏗️", options: ['Purified water', 'Made steel cheap and easy to mass-produce', 'Generated electricity', 'Mined coal safely'], answer: 1, explanation: "The Bessemer process blasted air through molten iron, burning out impurities and making high-quality, cheap steel! 🌉" },
    { id: 'q12', question: "Who were the 'Luddites'? 🛑", options: ['Factory owners', 'Inventors of the steam engine', 'Workers who smashed factory machines in protest', 'Train conductors'], answer: 2, explanation: "Luddites were skilled weavers who lost their jobs to machines, so they formed groups to secretly smash the power looms! 🔨" },
    { id: 'q13', question: "What forced the creation of standardized Time Zones? ⏱️", options: ['Factory shifts', 'Railways and train schedules', 'The telegraph', 'The invention of watches'], answer: 1, explanation: "To prevent high-speed trains from crashing and to make schedules make sense, towns had to stop using their own local sun-based time! 🚂" },
    { id: 'q14', question: "What caused the 'Great Stink' of London in 1858? 💩", options: ['A massive chemical spill', 'Burning too much low-grade coal', 'Raw sewage from 2.5 million people dumped directly into the River Thames', 'Rotting fish markets'], answer: 2, explanation: "The horrible smell actually forced the government to finally fund and build a modern, underground sewer system! 🚽" },
    { id: 'q15', question: "How did the Industrial Revolution change global populations? 📈", options: ['It decreased due to war', 'It remained flat', 'It spiked massively due to better goods and food transport', 'Only city populations grew, total died down'], answer: 2, explanation: "For 10,000 years human population was somewhat flat. After 1750, it exploded upward like a rocket! 🚀" },
    { id: 'q16', question: "If you worked in a factory in 1820, what was your likely schedule? ⏰", options: ['8 hours a day, 5 days a week', '4 hours a day, 7 days a week', '14 hours a day, 6 days a week', 'Work from home whenever'], answer: 2, explanation: "There were no labor laws protecting workers yet! 14-hour days with dangerous machines were totally normal. 😥" },
    { id: 'q17', question: "Prior to the revolution, what was 'Cottage Industry'? 🏡", options: ['Building small houses', 'Making goods at home by hand over a long time', 'Farming cheese', 'The first factories'], answer: 1, explanation: "Merchants would bring raw materials to families in cottages, who would spin and weave it by hand at their own pace. 🧶" },
    { id: 'q18', question: "What invention revolutionized long-distance communication instantly? 📞", options: ['The Steam Train', 'The Printing Press', 'The Telegraph', 'The Pony Express'], answer: 2, explanation: "The Telegraph (using Morse Code) separated communication from physical travel. Messages moved at the speed of electricity! ⚡" },
    { id: 'q19', question: "What is a massive, invisible consequence of the Industrial Revolution we face today? 🌡️", options: ['Too much noise', 'Global climate change from burning fossil fuels', 'Loss of all forests', 'Magnetic pole shifting'], answer: 1, explanation: "The billions of tons of coal and oil burned since 1750 have released trapped carbon into the atmosphere, heating the planet. 🌍" },
    { id: 'q20', question: "What geographic feature did Britain have that massively helped them industrialize first? 🇬🇧", options: ['Vast deserts', 'Easily accessible coal and iron deposits', 'The highest mountains', 'No oceans'], answer: 1, explanation: "Britain was basically sitting on top of an island made of coal and iron, exactly what they needed to build and fuel steam engines! 🪨" },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['ancient_civilizations', 'world_wars', 'colonization'],
};
