// ─────────────────────────────────────────────────────────
//  TOPIC: AFTERLIFE BELIEFS ACROSS CULTURES
//  Category: Religion & God
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'afterlife_beliefs',
  title: 'Afterlife Beliefs Across Cultures',
  subtitle: 'Every civilization\'s answer to the hardest question: What happens when you die? 💀🌌',
  emoji: '💀',
  category: 'Religion & God',
  accentKey: 'afterlife_beliefs',

  hook: {
    question: "There are 8 billion people on Earth, and every single one of them will die. It's the ONE experience guaranteed to every human being — yet we have absolutely ZERO data about what happens next. So how has every culture in history answered the unanswerable?",
    reveal: "Every civilization has invented an afterlife because the alternative — total, permanent nothingness — is psychologically unbearable to a brain designed for survival.\n\nTerror Management Theory (TMT) in psychology has proven that even SUBTLE reminders of death (seeing a cemetery, reading the word 'coffin') change human behavior — making people more nationalistic, more religious, and more aggressive.\n\nAfterlife beliefs are not just comforting stories. They are psychological INFRASTRUCTURE — load-bearing walls that prevent the collapse of meaning in the face of inevitable annihilation. Remove them without a replacement, and the human psyche cracks. 🧠💀",
    emoji: '⚰️',
  },

  theory: [
    {
      id: 'christian_afterlife',
      title: "Christianity — Heaven, Hell, and Judgment ✝️",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'cloud',
      svgIcon: 'star',
      content: "**The System**: After death, each soul faces Final Judgment.\n\n**Heaven**: Eternal paradise in the presence of God. No suffering, no tears, no death. The ultimate reward.\n\n**Hell**: Eternal separation from God (traditionally depicted with fire and torment, increasingly reinterpreted as spiritual anguish).\n\n**Purgatory** (Catholic only): A temporary cleansing state for souls not quite ready for Heaven.\n\n**Second Coming**: At the end of history, all dead will be physically resurrected for Final Judgment.\n\n**Key Variation**: Protestants say salvation comes through FAITH alone. Catholics say faith PLUS good works. Orthodox emphasize 'theosis' (becoming one with God's nature).",
      highlight: "The medieval Church sold 'indulgences' — literally purchasing reduced time in Purgatory. This corruption triggered the Protestant Reformation. 💰",
    },
    {
      id: 'islamic_afterlife',
      title: "Islam — The Bridge, The Scales, and The Gardens 🌙",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'scale',
      svgIcon: 'scale',
      content: "**The System**: After death, the soul enters Barzakh (a waiting realm). On the Day of Judgment:\n\n1. **The Scales** (Mizan): Every deed is weighed — good on one side, bad on the other.\n2. **The Bridge** (Sirat): A razor-thin bridge over Hell. The righteous cross easily; sinners fall.\n3. **Jannah** (Paradise): Multiple levels. Rivers of milk and honey, eternal youth, reunion with loved ones. The highest level (Firdaws) offers direct nearness to Allah.\n4. **Jahannam** (Hell): Extreme physical punishment. Some theologians say it purifies and eventually empties (not eternal for all sinners).\n\n**Key Detail**: The Quran emphasizes that NO soul will bear the burden of another — your judgment is YOURS alone.",
      highlight: "Islam describes 7 gates of Hell and 8 gates of Paradise. The extra gate of Paradise suggests God's mercy will ALWAYS outweigh His punishment. 🚪",
    },
    {
      id: 'hindu_afterlife',
      title: "Hinduism — The Wheel of Reincarnation 🕉️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'refresh',
      svgIcon: 'flame',
      content: "**The System**: The soul (Atman) is ETERNAL. It does not die — it transmigrates into a new body after death.\n\n**Samsara**: The cycle of birth, death, and rebirth. Your next life is determined by **Karma** (the sum of your actions).\n\n**Good Karma** → Higher rebirth (human, deva/god, wealthier, healthier)\n**Bad Karma** → Lower rebirth (animal, insect, lower caste, suffering)\n\n**Moksha**: The ultimate goal — liberation from the cycle entirely. The Atman merges back into Brahman (universal consciousness). No more birth, no more death, no more suffering.\n\n**Paths to Moksha**: Bhakti (devotion), Jnana (knowledge), Karma (selfless action), Dhyana (meditation).",
      highlight: "There are 8.4 MILLION species souls can reincarnate through before becoming human — making a human birth extraordinarily precious. 🌱",
    },
    {
      id: 'buddhist_afterlife',
      title: "Buddhism — Rebirth Without a Soul ☸️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'recycle',
      svgIcon: 'eye',
      content: "**The System**: Buddhism accepts rebirth but DENIES a permanent soul (Anatta = no-self).\n\nWhat gets reborn is not 'you' — it's a stream of consciousness, like a flame being passed from one candle to another. The new flame is caused by the old, but is not THE SAME flame.\n\n**Six Realms of Rebirth**: God realm, Human realm, Asura (jealous god), Animal, Hungry Ghost, Hell — each caused by dominant mental states.\n\n**Nirvana**: The goal — complete cessation of craving, aversion, and ignorance. Not heaven; not a place. It is the EXTINGUISHING of the causes of suffering. 'Like a flame that goes out — not to another place, just... out.'\n\n**Key Difference from Hinduism**: No Atman. No permanent self that transmigrates. Just a river of causes and effects.",
      highlight: "The Buddha said Nirvana is like a flame going out — not relocating to paradise, but ceasing. This terrifies Westerners and liberates Buddhists. 🕯️",
    },
    {
      id: 'jewish_afterlife',
      title: "Judaism — Surprisingly Ambiguous ✡️",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'question',
      svgIcon: 'scroll',
      content: "**The System**: Judaism is remarkably vague about the afterlife — by design.\n\nThe Torah barely mentions it. The focus is on THIS life and THIS world. Key concepts:\n\n**Olam Ha-Ba** (The World to Come): A vague paradise, rarely described in detail.\n**Sheol**: The ancient Hebrew underworld — a shadowy, neutral place for ALL dead (not punishment).\n**Gehinnom**: A temporary cleansing (usually no more than 12 months), NOT eternal Hell.\n**Resurrection**: Orthodox Jews believe in bodily resurrection when the Messiah comes.\n\n**Why It's Vague**: The rabbis intentionally refused to speculate about the afterlife, arguing that detailed promises of heaven can be used to manipulate people. Judaism insists: focus on being good NOW, not on earning a reward later.",
      highlight: "Jewish mourners recite Kaddish (memorial prayer) — which never mentions death or the afterlife. It is entirely about praising God in THIS life. 🕊️",
    },
    {
      id: 'ancient_egypt',
      title: "Ancient Egypt — The Hall of Maat 🏛️",
      color: '#D4A74A',
      bgGradient: ['#201500', '#0A0800'],
      icon: 'temple',
      svgIcon: 'scale',
      content: "**The System**: After death, the soul travels through the Underworld (Duat) facing trials and monsters.\n\nThe climax: **The Weighing of the Heart** in the Hall of Maat.\n\n• The dead person's heart is placed on one side of a scale.\n• The Feather of Truth (Maat) is placed on the other.\n• If the heart is lighter than the feather (lived a good life) → enter the Field of Reeds (paradise).\n• If the heart is heavier (burdened with sin) → it is devoured by Ammit, a monster with a crocodile head, lion body, and hippo legs. The soul ceases to exist.\n\n**Key Concept**: This is one of the OLDEST recorded afterlife judgments (~2400 BCE). It directly influenced later Jewish, Christian, and Islamic concepts.",
      highlight: "Egyptian mummification was a technology — designed to preserve the body so the soul (Ba and Ka) could return to it for eternity. 🪦",
    },
    {
      id: 'greek_afterlife',
      title: "Ancient Greece — The River Styx 🏺",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'boat',
      svgIcon: 'compass',
      content: "**The System**: After death, the soul descends to Hades (the Underworld). The ferryman Charon carries you across the River Styx — but only if your corpse was buried with a coin!\n\n**Three Destinations**:\n1. **Elysium** (Elysian Fields): Paradise for heroes and the virtuous. Eternal feasting and joy.\n2. **Asphodel Meadows**: For ordinary, unremarkable people. Not bad, not good — just... existing. Eternally bored.\n3. **Tartarus**: Prison for the truly wicked. ETERNAL punishment (Sisyphus rolling a boulder forever, Tantalus reaching for unreachable food).\n\n**Key Insight**: The Greeks viewed death as a diminishment — even heroes in Elysium were less than the living. Achilles in Hades said: 'I would rather be a slave on earth than king of the dead.'",
      highlight: "Greeks buried their dead with a coin in their mouth — payment for Charon. Without it, your soul wandered the river bank for 100 years. 🪙",
    },
    {
      id: 'norse_afterlife',
      title: "Norse — Valhalla and Ragnarök ⚔️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'sword',
      svgIcon: 'flame',
      content: "**The System**: The Norse afterlife depended on HOW you died:\n\n**Valhalla** 🏰: Hall of the slain. Warriors who died gloriously in battle were chosen by Valkyries to feast with Odin, fighting each day and feasting each night — training for Ragnarök.\n\n**Fólkvangr**: Freya's hall. Another paradise for brave warriors. (Yes, even the afterlife had two factions.)\n\n**Helheim**: For everyone else (death by old age, disease, or cowardice). Cold, dull, ruled by the half-dead goddess Hel. Not punishment — just boring eternity.\n\n**Ragnarök**: The apocalypse. Even the GODS die. But from the ashes, a new world is born. The cycle continues.\n\n**Key Insight**: The Norse view was uniquely fatalistic — even the gods couldn't escape death. Honor wasn't about avoiding death, but about HOW you met it.",
      highlight: "Viking warriors would literally smile while being killed in battle — dying with joy because it guaranteed entry to Valhalla. 😁⚔️",
    },
    {
      id: 'scientific_perspective',
      title: "The Scientific Perspective — Lights Out? 🔬",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'microscope',
      svgIcon: 'brain',
      content: "**Materialism/Physicalism**: Consciousness is produced entirely by the brain. When the brain dies, consciousness ceases. Period. There is no afterlife.\n\n**Evidence cited**:\n• Brain damage changes personality (proving mind = brain)\n• Anesthesia removes consciousness entirely (proving it can be 'turned off')\n• No confirmed communication from dead people\n• No mechanism for consciousness without neurons\n\n**The uncomfortable implication**: If materialism is correct, death is identical to the billions of years before you were born. You didn't suffer then. You won't suffer after.\n\n**The honest gap**: Materialism cannot explain HOW neurons produce subjective experience (the Hard Problem). If consciousness isn't purely physical, then physicalism's prediction about death might be wrong.",
      highlight: "Mark Twain: 'I do not fear death. I was dead for billions of years before I was born and suffered not the slightest inconvenience from it.' 🎩",
    },
    {
      id: 'nde_research',
      title: "Near-Death Experiences — Evidence or Illusion? 💫",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'eye',
      svgIcon: 'eye',
      content: "Millions of people who were clinically dead but resuscitated report remarkably consistent experiences:\n\n1. **Tunnel of light** (70% of NDEs)\n2. **Out-of-body experience** (seeing their own body from above)\n3. **Life review** (seeing their entire life flash before them)\n4. **Encountering deceased relatives**\n5. **Overwhelming peace and unconditional love**\n6. **A 'border' or barrier** they choose not to cross\n\n**Skeptical Explanations**: Oxygen deprivation, DMT release, dying brain's final neural cascade.\n\n**Anomalies**: Some NDE patients accurately report events that happened in OTHER rooms while they were flatlined. The AWARE study (2014) placed hidden images in hospital rooms — so far, results are inconclusive but tantalizing.",
      highlight: "Cardiologist Pim van Lommel's study: 18% of cardiac arrest patients had NDE awareness during FLAT EEG (zero measurable brain activity). 🧠=0 👀=✓",
    },
    {
      id: 'reincarnation_evidence',
      title: "Reincarnation Research — Past Lives? 🔄",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'clock',
      svgIcon: 'refresh',
      content: "Dr. Ian Stevenson (University of Virginia) spent 40 years documenting ~3,000 cases of children who claimed to remember past lives.\n\n**The evidence is startling**:\n• Children (ages 2-5) described specific people, addresses, and events from past lives\n• Many details were verified against historical records when the named person was located\n• Some children had **birthmarks** matching the fatal wounds of the person they claimed to be\n• Cases occur worldwide, not just in reincarnation-believing cultures (40% are in Western countries)\n\n**Skeptical Explanations**: Cryptomnesia (hidden memories), parental coaching, confirmation bias.\n\n**The problem**: Some cases involve details the child could not have possibly known through any normal channel.",
      highlight: "A child in Lebanon described his murder, named his killer, led investigators to the site of his buried body, and described details only the dead man could know. 😳",
    },
    {
      id: 'tmt_psychology',
      title: "Terror Management Theory — Why Afterlife Matters 🧠",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'brain',
      svgIcon: 'alert',
      content: "**Terror Management Theory (TMT)** is the most well-supported psychological theory about death:\n\n**Core Claim**: Humans are the only animals aware that they WILL die. This knowledge creates existential terror that would paralyze us — unless managed.\n\n**How we manage it**:\n1. **Cultural Worldviews**: Religions, ideologies, and national identities provide symbolic immortality ('My contribution will outlast me')\n2. **Self-Esteem**: Feeling valuable within your culture buffers against death anxiety\n3. **Afterlife Beliefs**: The most direct solution — simply denying death's finality\n\n**Experimental Proof**: When researchers subtly remind people of death:\n• They become more nationalistic\n• They cling harder to their religion\n• They become more aggressive toward 'outsiders'\n• They spend more money on status goods\n\nDeath awareness drives an enormous amount of human behavior — usually unconsciously.",
      highlight: "Just having people walk past a cemetery (vs. a normal street) made them significantly more hostile to people who criticized their country. 🪦➡️🤬",
    },
    {
      id: 'ancestor_tablets',
      title: "East Asian Traditions — Ancestor Tablets 🏮",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'home',
      svgIcon: 'users',
      content: "In Chinese, Japanese, and Korean traditions, the dead don't go to 'heaven' or 'hell' — they join the FAMILY.\n\n**Ancestor Tablets**: Wooden tablets inscribed with family names placed in household shrines. The living communicate with dead relatives through offerings, incense, and prayer.\n\n**The Dead NEED the Living**: Unlike Western afterlife, East Asian ancestors require ongoing food offerings, paper money burning, and rituals. Without them, they become 'hungry ghosts' — suffering because no one remembers them.\n\n**Obon Festival** (Japan): An annual festival where the spirits of dead relatives return home. Families light lanterns to guide them back.\n\n**Qingming Festival** (China): Families visit graves, clean them, and have picnics with the dead.\n\n**Key Insight**: Death doesn't sever the relationship — it transforms it. The dead are still family.",
      highlight: "In Japan, 76% of homes have a household shrine (butsudan) where families talk to deceased relatives every day. 🏠",
    },
    {
      id: 'simulation',
      title: "Modern Theories — Are We Already Dead? 🖥️",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'cpu',
      svgIcon: 'lock',
      content: "Modern philosophy and physics have generated strange new afterlife-adjacent theories:\n\n**Simulation Theory**: If we're in a simulation, 'death' is just the end of one run. What happens to characters when the game ends?\n\n**Quantum Immortality**: In the Many-Worlds interpretation, every possibility branches into a new universe. In some branches, you ALWAYS survive. You can never experience your own death because your consciousness always 'selects' the branch where you're alive.\n\n**Digital Afterlife**: Companies like Eternos and HereAfter are creating AI chatbots trained on dead people's data — allowing you to 'talk' to your deceased grandmother. Is that immortality?\n\n**Biocentrism** (Robert Lanza): Consciousness creates reality, not the other way around. Death is impossible because time and space are constructs of consciousness.",
      highlight: "Elon Musk believes there's a 1-in-billions chance we're NOT in a simulation. If true, 'death' is just a program ending. 🎮",
    },
    {
      id: 'living_with_death',
      title: "Living With Death — The Final Lesson 🌅",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'sunrise',
      svgIcon: 'heart',
      content: "No one knows what happens after death. Maybe heaven. Maybe nothing. Maybe rebirth. Maybe something we can't imagine.\n\nBut every tradition agrees on one thing: **awareness of death IMPROVES the quality of life**.\n\n• **Stoics**: 'Memento Mori' — Remember you will die. It strips away pettiness.\n• **Buddhism**: Death meditation (Maranasati) reduces anxiety and increases gratitude.\n• **Existentialism**: Heidegger said confronting death 'Being-toward-death' is the only path to authentic living.\n• **Palliative Care Research**: The #1 regret of the dying is 'I wish I'd had the courage to live a life true to myself, not the life others expected of me.'\n\nThe afterlife question is unknowable. The THIS-life question is urgent: Are you spending your finite, non-renewable time on what actually matters to you?",
      highlight: "Steve Jobs: 'Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life.' 🍎",
    },
  ],

  lab: {
    title: "The Afterlife Architect 💀🏗️",
    description: "Design your OWN afterlife! Choose mechanisms (judgment, karma, oblivion), criteria (deeds, faith, character), and destinies (paradise, rebirth, merge with cosmos). Compare your design to the world's major traditions and discover which you most closely align with.",
    hint: "Your afterlife design reveals your deepest values — fairness, mercy, justice, or transcendence. There are no wrong answers!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks TMT anxiety correlations, NDE data overlays, and philosophical consistency scores.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why Egyptians removed the brain through the nose during mummification but carefully preserved the heart? 🧠", answer: "Ancient Egyptians believed the HEART was the seat of the soul, intelligence, and memory — NOT the brain. The brain was considered useless waste, pulled out through the nostrils with hooks and discarded! The heart was left inside the body because it would be weighed against the Feather of Truth in the afterlife judgment. Getting the heart wrong = soul annihilation. 💔", emoji: '⚱️' },
    { id: 'dyk2', question: "Do you know why Tibetan Buddhists practice 'sky burials'? 🦅", answer: "In Tibet, bodies of the deceased are placed on mountaintops and carved up for vultures to consume. This isn't disrespectful — it's the HIGHEST honor. Since Buddhism teaches there is no permanent self, the body is just an empty vessel. Feeding it to birds is the final act of generosity (dana). The soul has already moved on; the body should nourish other living beings. 🏔️", emoji: '🐦' },
    { id: 'dyk3', question: "Do you know why Victorian-era people took photographs of their DEAD relatives posed as if alive? 📸", answer: "In the 1800s, photography was new and expensive. Many people NEVER had a photograph taken during their lifetime. The only family portrait was taken after death — with the deceased propped up, eyes painted on closed lids, and arranged with living family members. These 'memento mori' photos were the most treasured possessions of Victorian families. 🖼️", emoji: '🪦' },
    { id: 'dyk4', question: "Do you know why Mexican Día de los Muertos (Day of the Dead) is a CELEBRATION, not a mourning? 🎉", answer: "In Mexican culture (blending Catholic and ancient Aztec beliefs), death is not an ending — it's a transition. On November 1-2, the dead RETURN to visit the living. Families build altars (ofrendas) with the deceased's favorite food, drinks, music, and marigold flowers. They celebrate because the dead are HERE, right now, eating their favorite tamales. It's a family reunion, not a funeral. 💀🌺", emoji: '🇲🇽' },
    { id: 'dyk5', question: "Do you know why cryonics companies freeze dead bodies in liquid nitrogen? 🧊", answer: "Over 500 people worldwide have been cryogenically frozen after death (at -196°C) — betting that future technology will be able to repair whatever killed them and revive them. Alcor Life Extension Foundation charges ~$200,000 for full-body preservation. They've essentially created a technological afterlife — 'I'm not dead, I'm paused.' Whether it will ever work is an open question. 🔬", emoji: '❄️' },
  ],

  quiz: [
    { id: 'q1', question: "In Christianity, the Catholic concept of Purgatory is:", options: ['Another name for Hell', 'A temporary cleansing state for souls not yet ready for Heaven', 'A type of prayer', 'Accepted by all denominations'], answer: 1, explanation: "Purgatory is Catholic-only. Protestants reject it, arguing salvation is through faith alone. ✝️" },
    { id: 'q2', question: "Islam's afterlife judgment involves:", options: ['Only faith', 'A weighing of deeds on divine scales (Mizan), crossing a bridge over Hell (Sirat)', 'Random selection', 'No judgment'], answer: 1, explanation: "Every deed is measured — but the Quran emphasizes God's mercy always exceeds His wrath. ⚖️" },
    { id: 'q3', question: "Hindu reincarnation (Samsara) is determined by:", options: ['Random chance', 'Karma — the accumulated consequences of all your actions across lifetimes', 'God\'s mood', 'Your wishes'], answer: 1, explanation: "Karma is an impersonal cosmic law, not divine punishment. Actions have consequences. 🕉️" },
    { id: 'q4', question: "Buddhism's concept of rebirth DIFFERS from Hindu reincarnation because:", options: ['Buddhism doesn\'t believe in rebirth', 'Buddhism denies a permanent soul (Anatta) — rebirth is a stream of consciousness, not a soul transferring', 'They are identical', 'Buddhism only allows human rebirth'], answer: 1, explanation: "A candle lighting another candle — the flame is caused by but is NOT the same flame. 🕯️" },
    { id: 'q5', question: "Judaism's afterlife is NOTABLY:", options: ['Extremely detailed', 'Remarkably vague — deliberately focused on THIS life rather than speculating about the next', 'Nonexistent', 'Identical to Christianity'], answer: 1, explanation: "Rabbis intentionally avoided detailed afterlife promises, fearing they'd be used for manipulation. ✡️" },
    { id: 'q6', question: "In ancient Egypt, if your heart was HEAVIER than the Feather of Truth:", options: ['You went to Heaven', 'Your heart was devoured by Ammit and your soul CEASED to exist', 'You got a second chance', 'Nothing happened'], answer: 1, explanation: "Egyptian judgment was total annihilation, not eternal punishment. There was no Hell — just nonexistence. 💀" },
    { id: 'q7', question: "The Greek hero Achilles, speaking from the afterlife (Hades), famously said:", options: ['The afterlife is paradise', 'I would rather be a slave on earth than king of the dead', 'Death is beautiful', 'I enjoy Elysium'], answer: 1, explanation: "The Greeks viewed death as diminishment — even heroes were less than the living. 🏺" },
    { id: 'q8', question: "Norse warriors SMILED while dying in battle because:", options: ['They were in shock', 'A glorious death in battle guaranteed entry to Valhalla — paradise for warriors', 'They were crazy', 'Vikings couldn\'t feel pain'], answer: 1, explanation: "How you died mattered more than how you lived. Dying of old age sent you to boring Helheim. ⚔️" },
    { id: 'q9', question: "From a scientific materialist perspective, death is:", options: ['A doorway', 'Identical to the billions of years before you were born — complete cessation of consciousness', 'Temporary', 'A new beginning'], answer: 1, explanation: "Mark Twain: 'I was dead for billions of years before I was born and suffered not the slightest inconvenience.' 🔬" },
    { id: 'q10', question: "Near-Death Experiences (NDEs) are scientifically puzzling because:", options: ['They don\'t exist', 'Some patients accurately report events from OTHER rooms while their brain showed ZERO electrical activity', 'Everyone has them', 'They prove God'], answer: 1, explanation: "The AWARE study found cases of awareness during flat EEG — challenging physicalism. 💫" },
    { id: 'q11', question: "Dr. Ian Stevenson's reincarnation research found:", options: ['No evidence', 'Children accurately describing verifiable details of dead strangers\' lives, sometimes with matching birthmarks', 'Proof of fraud', 'Only evidence in Hindu countries'], answer: 1, explanation: "40% of his cases came from Western, non-reincarnation-believing cultures. 🔄" },
    { id: 'q12', question: "Terror Management Theory (TMT) proves that reminders of death make people:", options: ['Calmer', 'More nationalistic, more religious, more aggressive to outsiders, and more materialistic', 'Happier', 'Sleepy'], answer: 1, explanation: "Just walking past a cemetery makes people measurably more hostile to those who threaten their worldview. 🪦" },
    { id: 'q13', question: "In East Asian ancestor traditions, the dead:", options: ['Go to Heaven', 'Remain part of the family, need ongoing offerings, and can become \'hungry ghosts\' if neglected', 'Disappear', 'Are feared'], answer: 1, explanation: "Death doesn't sever the relationship — the dead are still family members who need care. 🏮" },
    { id: 'q14', question: "Quantum Immortality suggests that:", options: ['Quantum mechanics proves the afterlife', 'In the Many-Worlds interpretation, your consciousness always selects the branch where you survive', 'Quantum physics is magic', 'Death is impossible'], answer: 1, explanation: "A bizarre but logically consistent implication of the Many-Worlds interpretation. 🌌" },
    { id: 'q15', question: "Ancient Egyptians discarded the BRAIN during mummification because:", options: ['They didn\'t know what it did', 'They believed the HEART, not the brain, contained the soul, intelligence, and memory', 'It was too heavy', 'Religious law required it'], answer: 1, explanation: "The brain was pulled out through the nose with hooks and thrown away! The heart stayed. 🧠🚮" },
    { id: 'q16', question: "Tibetan sky burials (feeding the dead to vultures) reflect:", options: ['Disrespect', 'Buddhist teaching that the body is an empty vessel — feeding it to birds is the final act of generosity', 'Poverty', 'Laziness'], answer: 1, explanation: "No permanent self means the body is just material. Its last gift should nourish living beings. 🦅" },
    { id: 'q17', question: "Día de los Muertos is a CELEBRATION because:", options: ['Death is fun', 'The dead RETURN to visit the living — it\'s a family reunion, not a funeral', 'Mexican law requires it', 'It\'s a tourist attraction'], answer: 1, explanation: "The dead are right here, eating their favorite tamales. Death is a transition, not an ending. 🌺" },
    { id: 'q18', question: "Cryonics (freezing bodies after death) is essentially:", options: ['Medical science', 'A technological bet on achieving afterlife through future revival technology', 'Proven to work', 'Free'], answer: 1, explanation: "'I'm not dead, I'm paused.' Whether it will ever work remains an open question. 🧊" },
    { id: 'q19', question: "The #1 regret of the dying, according to palliative care research, is:", options: ['Not making enough money', 'I wish I\'d had the courage to live a life true to MYSELF, not the life others expected of me', 'Not traveling enough', 'Not exercising'], answer: 1, explanation: "Nobody on their deathbed wishes they'd spent more time at the office. 🌅" },
    { id: 'q20', question: "What ALL afterlife traditions agree on, across cultures, is:", options: ['The specific destination', 'That awareness of death IMPROVES the quality of life by stripping away pettiness and focusing on what matters', 'That there is definitely an afterlife', 'Nothing'], answer: 1, explanation: "Memento Mori. Whether you believe in heaven or oblivion — remembering death makes you live better. 💀🌱" },
  ],

  relatedTopics: ['spirituality_vs_religion', 'world_religions', 'consciousness', 'how_religion_evolved'],
};
