export default {
  id: "magnetism",
  title: "Magnetism",
  subtitle: "The invisible forces ruling the universe 🧲",
  emoji: "⚡",
  category: "Physics",
  accentKey: "physics",

  hook: {
    question: "How do giant rollercoaster brakes completely stop a 10,000-pound train instantly WITHOUT ever physically touching it? 🎢",
    reveal: "The violent power of Electromagnetism! They use massive Neodymium magnets dropping past copper plates. As the magnet flies past, it aggressively induces a violent 'Eddy Current' in the copper, which instantly fights back with an exact opposite magnetic field! A totally invisible, friction-free wall of pure kinetic denial! 🛑",
    emoji: "🧲",
  },

  theory: [
    {
      id: "mag_1",
      title: "Magnetic Fields: The Invisible Ocean 🌊",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "🧲",
      svgIcon: "magnet",
      content: "Magnets don't just pull things—they mathematically completely warp the physical space around them into an aggressively active **Magnetic Field**! \n\nThis field flows violently out of the North pole and arcs endlessly back to the South pole. Any magnetic material caught in this invisible ocean is forcefully dragged along its current!",
      highlight: "Magnetic fields technically extend forever! A magnet on your fridge is technically pulling on the Andromeda Galaxy right now, just extremely weakly! 🌌",
    },
    {
      id: "mag_2",
      title: "Ferromagnetism: The Atomic Army 🪖",
      color: "#FF3131",
      bgGradient: ["#200A0A", "#050D0A"],
      icon: "🪖",
      svgIcon: "shield",
      content: "Why are some metals magnetic and some violently aren't? \n\nInside Iron, billions of atoms fiercely naturally group together into 'Domains'. Normally, they point dynamically in random directions and cancel out. But when a real magnet gets close, it aggressively forces ALL billions of atomic domains to instantly snap into perfect military alignment, turning the entire chunk of iron into a massive super-magnet! ⚡",
      highlight: "If you physically violently hit a magnet with a hammer enough times, you scramble the army and mathematically DESTROY its magnetism permanently! 🔨",
    },
    {
      id: "mag_3",
      title: "Electromagnetism: The Ultimate Team-Up ⚡",
      color: "#A855F7",
      bgGradient: ["#1A0A1F", "#050D0A"],
      icon: "⚡",
      svgIcon: "zap",
      content: "Electricity and Magnetism are NOT two different things! They are the exact same fundamental force completely viewed from different speeds! \n\nAny time electricity physically moves through a wire, it fiercely spawns a spiraling magnetic field around it. You can literally just wrap copper wire around a rusty nail, run a battery through it, and instantly physically create a violent electromagnet! 🔋",
      highlight: "This is exactly how massive scrap-yard cranes easily lift 5,000-pound cars with a simple flick of an electrical switch! 🏗️",
    },
    {
      id: "mag_4",
      title: "The Lorentz Force: The Deflector Shield 🛡️",
      color: "#39FF14",
      bgGradient: ["#0A200A", "#050D0A"],
      icon: "🛡️",
      svgIcon: "target",
      content: "When a charged particle (like a speeding electron) violently flies into a magnetic field, the field does NOT pull it straight in! \n\nInstead, it aggressively mathematically fiercely pushes the particle perfectly SIDEWAYS! This is called the **Lorentz Force**. It forces massive high-speed particles to completely physically curve and trap themselves in endless spirals!",
      highlight: "Earth's core generates a massive magnetic field that actively violently deflects deadly solar radiation sideways into space, saving all life on Earth daily! 🌍",
    },
    {
      id: "mag_5",
      title: "Faraday's Law: Free Electric Magic 🪄",
      color: "#FFB347",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🪄",
      svgIcon: "zap",
      content: "If electricity can aggressively spawn magnets, can magnets aggressively spawn electricity? YES! \n\nMichael Faraday proved that if you simply violently move a physical magnet back and forth near a wire, it forcefully actively pushes the electrons inside the wire, creating completely raw electrical current! ⚡",
      highlight: "This is mathematically how EVERY power plant on Earth works! They just use coal, wind, or nuclear power to forcefully physically spin giant magnets! 🏭",
    },
    {
      id: "mag_6",
      title: "Eddy Currents: The Invisible Brakes 🛑",
      color: "#FFD166",
      bgGradient: ["#2A2A00", "#050D0A"],
      icon: "🛑",
      svgIcon: "stop-circle",
      content: "Lenz's Law ensures that the universe violently hates sudden changes! \n\nIf you drop a magnet down a copper pipe, the moving magnetic field aggressively forces electricity (Eddy Currents) to instantly spiral inside the pipe! These new currents fiercely spawn their OWN exact opposite magnetic fields specifically designed to violently fight the falling magnet, slowing its fall to a crawl! 🐌",
      highlight: "Rollercoasters and high-speed bullet trains use Eddy Currents to instantly brake massively safely without generating any physical frictional heat! 🚄",
    },
    {
      id: "mag_7",
      title: "Magnetic Monopoles: The Missing Link ❓",
      color: "#FF4D6D",
      bgGradient: ["#2A0A1A", "#050D0A"],
      icon: "❓",
      svgIcon: "help-circle",
      content: "If you cut a magnet perfectly in half, do you get one pure North pole and one pure South pole? NO! \n\nYou instantly violently mathematically just get two smaller magnets, each with their own exact complete North and South! Scientists have spent decades aggressively hunting for a 'Magnetic Monopole' (a magnet with only one pole), but the universe strictly seems to absolutely forbid them! ❌",
      highlight: "The fact that monopoles theoretically should exist but completely don't is one of the greatest violent mysteries in quantum physics today! 🌌",
    },
    {
      id: "mag_8",
      title: "The Dynamo Theory: Earth's Core 🌋",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🌋",
      svgIcon: "globe",
      content: "How does the entire Earth have a magnetic field? \n\nDeep brutally inside the Earth is a violently spinning, turbulent ocean of super-heated liquid iron! As this massive molten metal aggressively churns due to intense heat, the moving electrons spawn a massive, continuously self-sustaining colossal electromagnet! 🌍",
      highlight: "Every 300,000 years, the violent churning becomes so totally chaotic that Earth's North and South poles completely physically reverse! 🧭",
    },
    {
      id: "mag_9",
      title: "Superconductors: Absolute Defiance 🧊",
      color: "#00D4A0",
      bgGradient: ["#00201A", "#050D0A"],
      icon: "🧊",
      svgIcon: "wind",
      content: "When you deeply freeze certain metals to near absolute zero, they become **Superconductors**! \n\nThey completely violently lose ALL electrical resistance! Even crazier, they aggressively expel all magnetic fields from inside themselves (the Meissner Effect). If you place a magnet on top of them, it mathematically physically completely locks in mid-air and violently severely levitates forever! 🚀",
      highlight: "Quantum levitation allows objects to stay perfectly aggressively locked in physical space, totally defying Earth's gravity with zero energy input! 🌌",
    },
    {
      id: "mag_10",
      title: "Magnetic Resonance Imaging (MRI) 🏥",
      color: "#6C5CE7",
      bgGradient: ["#100A20", "#050D0A"],
      icon: "🏥",
      svgIcon: "activity",
      content: "An MRI machine uses a seriously aggressively powerful magnetic field—thousands of times stronger than Earth's! \n\nIt fiercely forces every single water molecule in your entire physical body to violently snap to attention and align with the magnet. Then it blasts you with radio waves, knocking them over. As they snap back, they transmit exact mathematical signals used to build a perfect 3D map of your brain! 🧠",
      highlight: "The magnet in an MRI is so violently fundamentally powerful it can completely aggressively rip a metal chair across the room instantly! 🪑",
    },
  ],

  lab: {
    title: "Lorentz Force Accelerator 💥",
    description: "Welcome to the High-Energy Particle Collider. Aggressively inject multi-selected particles into extreme magnetic fields. Visualize the violent Lorentz force mathematically curving their strict trajectories!",
    hint: "Increase the Magnetic Field (Tesla) to strictly violently shrink the particle's turning radius! Watch heavy objects aggressively resist curvature.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time exact Tesla fields and strictly calculated relativistic Cyclotron Radii.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why compasses furiously point North? 🧭",
      answer: "A compass is literally just a physically tiny magnet balanced on a pin! The Earth acts like a massive magnet, and opposites fiercely attract! The 'North' pole of your completely tiny magnet aggressively actively seeks the physical 'Magnetic South' pole of the Earth (which is confusingly located in the geographic North!). 🌍",
      emoji: "🧭",
    },
    {
      id: "dyk2",
      question: "Do you know why magnets mathematically NEVER ever run out of energy? 🔋",
      answer: "Because magnetism is completely NOT an energy source! It is a fundamental force, exactly like Gravity. A magnet passively aggressively sitting on your fridge uses exactly zero energy, just like the floor completely uses zero energy to physically forcibly hold you up! 🧲",
      emoji: "💡",
    },
    {
      id: "dyk3",
      question: "Do you know why Birds can actively mathematically navigate across the entire ocean? 🐦",
      answer: "Many birds possess specialized physically magnetic proteins fiercely locked inside their actual eyes! This allows them to physically literally 'see' Earth's magnetic grid as a pure visual overlay on the sky! 🦅",
      emoji: "👀",
    },
    {
      id: "dyk4",
      question: "Do you know why completely heating a magnet brutally instantly destroys it? 🔥",
      answer: "A magnet relies completely on trillions of perfectly aligned atomic soldiers. When you violently heat the metal, the atoms fiercely aggressively vibrate randomly. Once it passes the 'Curie Temperature', the atomic army completely violently breaks rank, permanently shattering the magnetic field! 🔨",
      emoji: "🔥",
    },
    {
      id: "dyk5",
      question: "Do you know why Northern Lights (Auroras) aggressively physically appear? 🌌",
      answer: "The Sun violently continuously fires highly charged, utterly deadly plasma directly at Earth! The Lorentz Force of Earth's magnetic shield violently heavily deflects the particles toward the poles. When they violently smash into the oxygen in our atmosphere, it fiercely releases bright pure green and purple glowing light! 🎆",
      emoji: "✨",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What physical aggressive action creates an Electromagnet?",
      options: ["Violently burying iron", "Fiercely running electrical current through a coiled wire", "Freezing oxygen", "Splitting an atom"],
      answer: 1,
      explanation: "Electricity fiercely violently moving through a coiled wire instantly completely generates a massive magnetic field! ⚡",
    },
    {
      id: "q2",
      question: "What does the intense 'Lorentz Force' physically aggressively do to a speeding electron entering a magnetic field?",
      options: ["Fiercely pushes it sideways and curves its path", "Completely stops it instantly", "Violently sets it on fire", "Turns it into a solid neutron"],
      answer: 0,
      explanation: "The magnetic field mathematically physically totally bends the high-speed particle strictly sideways! 🔄",
    },
    {
      id: "q3",
      question: "According to strict fundamental physics, if you aggressively cut a magnet perfectly in half, what occurs?",
      options: ["You violently get one North magnet and one South magnet", "It completely mathematically shatters into two smaller complete magnets", "It explodes fiercely", "All magnetism vanishes completely"],
      answer: 1,
      explanation: "The universe fundamentally strictly outright forbids Monopoles! You just violently create two smaller standard complete magnets! 🧲",
    },
    {
      id: "q4",
      question: "What extremely violent fundamental natural phenomenon mathematically generates Earth's colossal magnetic shield?",
      options: ["Millions of tiny magnets in the dirt", "A violently spinning liquid iron core aggressively churning electrons", "Moon gravity", "The ozone layer"],
      answer: 1,
      explanation: "Deep Earth acts severely completely mathematically exactly like a constantly fierce Dynamo generating an endless magnetic force! 🌋",
    },
    {
      id: "q5",
      question: "How do massively high-speed bullet trains completely violently brake using magnets without friction?",
      options: ["By physically harshly scraping the metal", "By aggressively heavily spawning 'Eddy Currents' that physically fight back", "By fiercely firing retro rockets", "By turning the train sideways"],
      answer: 1,
      explanation: "Falling magnetic fields aggressively generate huge opposing electric loops called Eddy Currents that brake instantly! 🛑",
    },
    {
      id: "q6",
      question: "What does Faraday's Law aggressively precisely prove?",
      options: ["Spiders fall fast", "Physically fiercely moving a magnet past a wire completely creates pure electrical current", "Light is slow", "Gas expands hotly"],
      answer: 1,
      explanation: "Fierce physical motion of a magnet completely mathematically forces electrons to flow, inventing the electrical generator! 🏭",
    },
    {
      id: "q7",
      question: "When an atom strictly naturally aligns with its neighbors inside iron to create magnetism, the group is aggressively called:",
      options: ["A Magnetic Domain", "A Metal Squad", "An Iron Platoon", "An Electron Block"],
      answer: 0,
      explanation: "Billions of domains fiercely strictly point in the same absolute direction to produce massive physical force! 🪖",
    },
    {
      id: "q8",
      question: "What violently aggressively completely destroys a permanent magnet permanently?",
      options: ["Putting it in water", "Looking at it", "Fiercely heavily heating it past its Curie point", "Cooling it down brutally"],
      answer: 2,
      explanation: "Extreme massive heat wildly vibrates the precise aligned atoms completely totally out of order instantly! 🔥",
    },
    {
      id: "q9",
      question: "What happens to a completely 'Superconducting' metal when you fiercely cool it near absolute zero?",
      options: ["It violently forcefully expels all magnetic fields and can perfectly levitate", "It turns fully to rust", "It mathematically explodes", "It becomes totally transparent"],
      answer: 0,
      explanation: "The Meissner Effect actively violently rejects fields, causing completely frictionless pure levitation! 🧊",
    },
    {
      id: "q10",
      question: "Which completely massive astronomical events do Magnetic forces naturally physically cause on Earth?",
      options: ["Earthquakes", "Tornados", "The aggressive Northern Lights (Auroras)", "Tsunamis"],
      answer: 2,
      explanation: "Fierce solar death rays aggressively deflecting into oxygen atoms completely creates massive sky lights! 🌌",
    },
    {
      id: "q11",
      question: "A compass strictly physically points to the 'North'. But structurally, the geographic North pole acts completely exactly like what magnetic pole?",
      options: ["Magnetic Zero", "Magnetic South", "True North", "Electric Center"],
      answer: 1,
      explanation: "Opposites fundamentally completely aggressively attract! If your compass 'North' points at it, it must physically mathematically be a magnetic South! 🧭",
    },
    {
      id: "q12",
      question: "Which of the following entirely completely fiercely relies on Electromagnetic Induction to violently function?",
      options: ["A candle", "An acoustic guitar", "A colossal electric power plant generator", "A bicycle"],
      answer: 2,
      explanation: "Every power generator fiercely mathematically perfectly relies on moving giant magnets near wires to force current out! ⚡",
    },
    {
      id: "q13",
      question: "MRI machines are fundamentally violently massive 3D cameras that mathematically map what bodily component by using magnets?",
      options: ["Raw bone calcium", "Intense exact alignment of water molecules", "Oxygen gas", "Electric nerves entirely"],
      answer: 1,
      explanation: "The aggressive magnetic force strictly forces the protons in body-water to severely perfectly stand at attention! 🏥",
    },
    {
      id: "q14",
      question: "In physics, what exactly completely physically is entirely required for a standard 'Magnetic Field' to fundamentally exist?",
      options: ["Still metal", "Fiercely physically actively moving electrical charges!", "Total cold", "Pure gravity"],
      answer: 1,
      explanation: "Magnetism is fundamentally purely strictly completely the massive physical side effect of moving electrons! 🏃‍♂️",
    },
    {
      id: "q15",
      question: "Why does dropping a powerful super-magnet violently exactly through a totally pure straight copper pipe slow it down?",
      options: ["Copper is fiercely completely actually magnetic", "The pure violent motion forces immense Eddy Currents that powerfully fight gravity", "It hits air bumps", "The pipe physically squeezes the magnet"],
      answer: 1,
      explanation: "The totally changing field forces copper electrons to spiral, creating a fierce brake! 🛑",
    },
    {
      id: "q16",
      question: "What physical force aggressively severely completely prevents solar flares from physically mathematically burning off Earth's atmosphere?",
      options: ["The Ozone Field", "The immense brutal Lorentz Force of Earth's magnetic shield", "The ocean entirely", "The moon strictly"],
      answer: 1,
      explanation: "The Lorentz Force radically extremely completely violently pushes the heavily charged solar death-plasma perfectly sideways! 🛡️",
    },
    {
      id: "q17",
      question: "Is 'Magnetism' fundamentally completely an aggressive physical source of infinite unending Energy?",
      options: ["Yes, completely", "No, it's a completely passive fundamental force precisely exactly like normal gravity", "Only on Mars", "Only when completely wet"],
      answer: 1,
      explanation: "Magnets absolutely strictly completely expend zero energy; they just severely mathematically curve physical space completely! 🔋",
    },
    {
      id: "q18",
      question: "When birds dynamically physically accurately completely migrate over total empty oceans, they use what to severely pinpoint location?",
      options: ["Smell alone", "Internal completely natural totally built-in magnetic eye sensors", "Wind completely", "Star maps only"],
      answer: 1,
      explanation: "Birds severely aggressively hack quantum electromagnetism directly perfectly inside their retinas! 🐦",
    },
    {
      id: "q19",
      question: "Do physicists fundamentally completely severely aggressively currently believe 'Magnetic Monopoles' strictly exist in nature?",
      options: ["Yes they are fully absolutely common", "No, they fiercely mathematically actively appear entirely entirely impossible so far", "Only inside pure iron completely", "Inside deep volcanoes"],
      answer: 1,
      explanation: "The absolute complete intense mathematical missing of monopoles drives physicists entirely completely utterly crazy! ❓",
    },
    {
      id: "q20",
      question: "What absolutely strictly drastically totally essentially occurs when the Earth's fierce internal continuous massive Dynamo physically becomes perfectly unstable?",
      options: ["The core freezes strictly totally", "The entire massive completely magnetic poles violently aggressively wildly reverse absolutely", "The Earth stops completely completely spinning entirely", "Lava erupts completely everywhere entirely"],
      answer: 1,
      explanation: "The severe immense complete absolute intense churn flips the total magnetic shield entirely upside down exactly roughly every 300,000 years! 🔄",
    },
  ],

  relatedTopics: ["electricity_circuits", "quantum_basics"],
};
