export default {
  id: 'energy_types',
  title: 'Energy Types & Conservation',
  subtitle: 'The currency that powers the entire universe ⚡',
  emoji: '⚡',
  category: 'Foundations',
  accentKey: 'zap',

  hook: {
    question: "Did you know that the kinetic energy of a mosquito in flight is enough to power the entire internet for much less than a nanosecond — and yet it feels like almost nothing? 🤯",
    reveal: "Energy is the most fundamental concept in all of physics — yet it's invisible, cannot be created or destroyed, only transformed. Every explosion, every thought in your brain, every star's glow, every living heartbeat, is just energy changing form. The universe's total energy has been exactly constant since the Big Bang — not one joule has been created or lost in 13.8 billion years. Understanding energy means understanding WHY everything happens — because the universe always moves toward states of lower usable energy. ⚡🌌",
    emoji: '⚡',
  },

  theory: [
    { id: 'what_is_energy', title: 'What IS Energy? 🌟', color: '#FDCB6E', bgGradient: ['#2A1A00', '#05050A'], icon: '🌟', svgIcon: 'lightning', content: "Energy is deceptively hard to define precisely — physicists typically say it is **the capacity to do work**.\n\n**Richard Feynman's honest assessment:**\n'It is important to realise that in physics today, we have no knowledge of what energy IS. We have formulas for calculating numbers, and when we add all the numbers up they equal the same number. It\'s an abstract thing.'\n\nYet despite this philosophical mystery, energy is the most practically useful concept in all of science.\n\n**Units of energy:**\n🔋 Joule (J) = 1 kg·m²/s² (SI unit)\n🔋 Calorie = 4.184 J (heat energy)\n🔋 Kilocalorie (kcal) = 4184 J ('food Calories' with capital C)\n🔋 Kilowatt-hour (kWh) = 3,600,000 J (electricity billing)\n🔋 Electronvolt (eV) = 1.6×10⁻¹⁹ J (atomic/nuclear physics)\n\n**The Law of Conservation of Energy:**\nEnergy cannot be created or destroyed — only converted between forms. This is the **1st Law of Thermodynamics** — possibly the most important law in all of science. Every perpetual motion machine ever invented violates this and cannot work. 🚫\n\n**Einstein's E=mc²:**\nMass is frozen energy! A 1kg object contains: E = 1 × (3×10⁸)² = 9×10¹⁶ J — enough energy to power New York City for 2+ years. Nuclear reactions release a tiny fraction of this. ☢️", highlight: "E=mc² means a 1kg mass contains 9×10¹⁶ joules — enough to power New York City for over 2 years if fully converted! ⚡" },
    { id: 'kinetic', title: 'Kinetic Energy: Energy of Motion 🏃', color: '#00CEC9', bgGradient: ['#001A18', '#05050A'], icon: '🏃', svgIcon: 'target', content: "**Kinetic Energy (KE)** is the energy an object has because it is moving:\n\n📐 **KE = ½mv²**\n\nWhere m = mass (kg) and v = velocity (m/s)\n\n**The v² relationship is surprising:**\nDouble the speed → 4× the kinetic energy!\nTriple the speed → 9× the kinetic energy!\n\nThis is why car crash deaths increase rapidly with speed:\n30 mph crash KE vs 60 mph = 4× more energy to absorb! 🚗💥\n\n**Types and examples:**\n🏃 Person running at 3 m/s, mass 70kg: KE = ½×70×9 = 315 J\n🚂 Train at 50 m/s, mass 500,000kg: KE = 625,000,000 J (625 MJ!) — why trains need km to stop\n⚛️ Thermal energy = kinetic energy of atoms/molecules\n\n**Kinetic energy at the atomic scale:**\nTemperature IS the average kinetic energy of particles!\n🌡️ At room temperature, air molecules move at ~500 m/s\n🌡️ At absolute zero (0K), particles have minimum possible kinetic energy\n\n**Relativistic kinetic energy:**\nAt speeds near light, Einstein's formula differs: KE = (γ-1)mc²\nAt 99% light speed, KE is 6× more than Newtonian formula predicts! Particle accelerators must use relativistic equations. ⚡", highlight: "Doubling speed quadruples kinetic energy — this is why 60 mph car crashes are 4× more deadly than 30 mph crashes! 🏃" },
    { id: 'potential', title: 'Potential Energy: Stored Potential 🌀', color: '#6C5CE7', bgGradient: ['#0A001A', '#05050A'], icon: '🌀', svgIcon: 'battery', content: "**Potential Energy (PE)** is stored energy — the capacity to do work due to position or configuration.\n\n**Gravitational PE:**\n📐 GPE = mgh\nm = mass, g = 9.81 m/s² (Earth's gravity), h = height above reference\n\nA 1kg book sitting on a 1m shelf has 9.81 J of GPE — that's where it came from when you lifted it!\n\n**Elastic PE:**\nStored in stretched/compressed springs, rubber bands, bent beams:\n📐 EPE = ½kx²\nk = spring constant (N/m), x = extension/compression (m)\n\n**Chemical PE:**\nThe energy stored in chemical bonds:\n⛽ 1L of petrol: ~34 MJ\n🥜 1g of fat: ~37 kJ\n🌰 1g of carbohydrate: ~16 kJ\n\n**Nuclear PE:**\nEnergy stored in nuclear binding:\n⚛️ 1g of U-235 fission: ~82,000 MJ (one gram!) vs 34,000 MJ from 1 tonne of oil!\n\n**Converting between forms:**\nA stretched rubber band: Elastic PE → Kinetic (when released)\nWater behind a dam: Gravitational PE → Kinetic → Electrical\nFood / Petrol: Chemical PE → Kinetic/Thermal\nNuclear reaction: Nuclear PE → Thermal → Kinetic → Electrical ⚡", highlight: "One gram of uranium-235 nuclear PE = 82,000 megajoules — equal to burning an entire tonne of oil! ☢️" },
    { id: 'thermal', title: 'Thermal Energy & Heat ♨️', color: '#FF7675', bgGradient: ['#2A0A00', '#05050A'], icon: '♨️', svgIcon: 'thermometer', content: "**Thermal Energy** is the total kinetic + potential energy of all particles within an object — distinct from temperature!\n\n**Temperature vs Thermal Energy:**\n🌡️ A large ice cube at −10°C has MORE thermal energy than a tiny candle flame at 800°C — it contains far more particles!\n🌡️ Temperature = average KE per particle. Thermal energy = total for all particles.\n\n**Heat transfer mechanisms:**\n🔴 **Conduction** — particle-to-particle KE transfer through direct contact. Metals conduct well (free electrons carry energy); wood poorly (few free electrons)\n🔴 **Convection** — bulk movement of hot fluid. Hot air rises (less dense), cool air sinks → convection current. This drives weather patterns, ocean currents, and Earth's magma movement!\n🔴 **Radiation** — electromagnetic waves carry energy through empty space. Sun → Earth through 150 million km of vacuum. All objects above 0K emit radiation!\n\n**Specific Heat Capacity (c):**\nEnergy needed per kg per °C temperature rise:\nQ = mcΔT\n💧 Water: c = 4200 J/(kg·K) — very high! Explains why coastal climates are mild and why water is coolant\n🔩 Iron: c = 449 J/(kg·K) — heats up / cools down faster\n\n**The 2nd Law of Thermodynamics:**\nHeat ALWAYS flows from hot to cold — never spontaneously from cold to hot. This explains why ice cubes melt in drinks and why refrigerators need electricity to move heat 'uphill'. 🧊", highlight: "A large ice cube has MORE thermal energy than a candle flame — thermal energy depends on particle count, not just temperature! ♨️" },
    { id: 'electrical', title: 'Electrical Energy ⚡', color: '#FDCB6E', bgGradient: ['#2A1A00', '#05050A'], icon: '⚡', svgIcon: 'lightning', content: "**Electrical Energy** is carried by moving electric charges (electrons in wires, ions in solutions).\n\n**Key quantities:**\n⚡ **Voltage (V)** — potential difference driving charge flow (like pressure in a hose)\n⚡ **Current (I)** — charge flow rate in amperes (A) (like flow rate in hose)\n⚡ **Resistance (R)** — opposition to current flow (Ohm: Ω)\n\n**Ohm's Law:** V = IR\n\n**Power:** P = IV = I²R = V²/R (watts, W)\n**Energy:** E = Pt = IVt (joules, J)\n\n**Global scale:**\n🌍 World electricity consumption: ~28,000 TWh/year (2024)\n🌍 An average home: ~10,000 kWh/year\n⚡ Lightning bolt: ~1 billion volts, ~20,000 amps — but only 5 GJ total (surprisingly little energy, very short duration!)\n\n**Alternating vs Direct current:**\n🔄 DC (Direct Current) — electron flow in one direction (batteries, solar panels, electronics)\n🔄 AC (Alternating Current) — electrons oscillate back and forth (50-60 Hz) — what comes from wall sockets. Edison vs Tesla 'War of Currents'! AC won because it can be easily transformed to high voltage for long-distance transmission (less energy lost)\n\n**Superconductivity:**\nAt extreme cold, some materials become perfect conductors with ZERO resistance — R=0, P=I²×0=0. No energy lost to heat! Used in MRI magnets and maglev trains. Room-temperature superconductors would revolutionise energy. ⚡", highlight: "Edison vs Tesla's War of Currents ended in AC winning because transformers can boost voltage for efficient long-distance transmission! ⚡" },
    { id: 'chemical_energy', title: 'Chemical Energy: Bonds as Batteries 🔋', color: '#55EFC4', bgGradient: ['#001A14', '#05050A'], icon: '🔋', svgIcon: 'battery', content: "**Chemical Energy** is stored in the bonds between atoms — when reactions break and form bonds, energy is released or absorbed.\n\n**Exothermic reactions** — release energy (heat):\n🔥 Burning (combustion): CH₄ + 2O₂ → CO₂ + 2H₂O + 890 kJ/mol\n🔋 Respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 2870 kJ/mol\n⚡ Explosives: TNT releases 3.4 kJ/g in microseconds\n\n**Endothermic reactions** — absorb energy (get cold):\n❄️ Photosynthesis (storing solar energy)\n❄️ Dissolving ammonium nitrate in water (instant cold packs)\n❄️ Cooking (breaking protein bonds)\n\n**Bond energy:**\nBreaking bonds REQUIRES energy. Forming bonds RELEASES energy.\nExothermic overall = bonds formed are stronger than bonds broken.\n\n**Food as fuel — real numbers:**\n🍫 Chocolate bar (50g): ~1000 kJ\n🔸 You'd need to run for 30 minutes to use that energy!\n🏃 Running burns ~60 kJ/minute (1 kJ/second)\n⚡ Your brain alone uses ~1400 kJ per day just existing — 20% of your body's energy!\n\n**ATP — The universal energy currency:**\nEvery cell uses ATP (adenosine triphosphate) as its internal currency. When a bond in ATP breaks: ~30 kJ/mol released. Your body makes ~40 kg of ATP per day! (and immediately recycles it — you never store more than a few grams at once) 💪", highlight: "Your body produces 40kg of ATP per day — but immediately recycles it, so you never store more than a few grams of this energy currency at once! 🔋" },
    { id: 'nuclear_energy', title: 'Nuclear Energy: E=mc² in Action ☢️', color: '#FD79A8', bgGradient: ['#2A001A', '#05050A'], icon: '☢️', svgIcon: 'atom', content: "**Nuclear Energy** is 1 million times more energy-dense than chemical energy. It comes in two forms:\n\n**Nuclear Fission — splitting heavy nuclei:**\n⚛️ U-235 + neutron → Ba + Kr + 2-3 neutrons + 200 MeV\n⚛️ Chain reaction: each fission releases neutrons that trigger more fissions\n⚛️ Controlled: nuclear power plant (heat → steam → electricity)\n⚛️ Uncontrolled: nuclear weapon (microsecond chain reaction)\n\n**Energy comparison:**\n1 kg coal → 8 kWh\n1 kg crude oil → 12 kWh\n1 kg uranium fission → 45,000 kWh (!)\n1 kg hydrogen fusion → 90,000 kWh (!!)\n\n**Nuclear Fusion — combining light nuclei:**\n⚛️ D + T → He-4 + n + 17.6 MeV (deuterium + tritium → helium)\n⚛️ Fuel source: Deuterium from seawater (essentially infinite!)\n⚛️ Waste: non-radioactive helium! (vs fission waste lasting thousands of years)\n⚛️ Challenge: plasma must reach 150 million°C, and be confined long enough\n\n**NIF (National Ignition Facility) breakthrough — December 2022:**\nA fusion experiment produced 3.15 MJ of energy from 2.05 MJ laser input → **net energy GAIN** from fusion for the first time in history! This is the start of the fusion age. 🔥\n\n**Why fusion would be transformative:**\nAlmost unlimited clean fuel. No carbon emissions. No long-lived nuclear waste. No risk of meltdown (if disrupted, plasma instantly cools). 🌍", highlight: "December 2022: NIF achieved the first fusion ignition — producing more energy than input for the first time in history! Fusion could end the energy crisis. ☢️" },
    { id: 'renewable_energy', title: 'Renewable Energy Sources 🌱', color: '#00B894', bgGradient: ['#001A14', '#05050A'], icon: '🌱', svgIcon: 'leaf', content: "All renewable energy sources ultimately come from three origins:\n1. The Sun (solar, wind, hydroelectric, biomass)\n2. Gravity (tidal power)\n3. Earth's internal heat (geothermal)\n\n**Solar:** \n☀️ 1.7×10¹⁷ watts of solar power hits Earth continuously\n☀️ 1 hour of sunlight = more energy than humanity uses in a year!\n☀️ Photovoltaic cells efficiency: ~22-25% (best research cells), 46% theoretical limit\n☀️ Solar costs fallen 90% in 10 years (2014-2024)\n\n**Wind:**\n🌬️ Wind turbines convert kinetic energy of air → electrical\n🌬️ Betz limit: maximum 59.3% efficiency for a wind turbine (theoretical)\n🌬️ Modern offshore turbines: 14 MW (Siemens Gamesa), rotor diameter 222m!\n\n**Hydroelectric:**\n💧 GPE of water → kinetic → electrical\n💧 Most efficient energy conversion: ~90%!\n💧 Three Gorges Dam (China): 22.5 GW (world's largest power station)\n\n**Serious challenge — intermittency:**\nSun doesn't always shine; wind doesn't always blow.\nSolution: grid-scale batteries (lithium-ion, vanadium flow, compressed air), pumped hydro storage, hydrogen electrolysis, interconnected smart grids. Energy storage is the most critical technological challenge of our time! 🔋\n\n**Energy transition:**\nRenewables already provide 30%+ of global electricity. On current trajectory, 80%+ by 2040. The energy transition is already the fastest technology transformation in history. 🌍", highlight: "One hour of sunlight hitting Earth contains more energy than humanity uses in an ENTIRE year — the challenge is capturing and storing it! ☀️" },
    { id: 'energy_conservation_law', title: 'Conservation Laws: The Deepest Truth ⚖️', color: '#A29BFE', bgGradient: ['#10002A', '#05050A'], icon: '⚖️', svgIcon: 'balance', content: "Conservation of energy is not just a useful rule — it's connected to the deepest symmetry in nature.\n\n**Noether's Theorem (1915):** Emmy Noether proved that every conservation law corresponds to a symmetry in nature:\n🕰️ Conservation of Energy ↔ Symmetry in time (laws of physics are same at any time)\n🔄 Conservation of Momentum ↔ Symmetry in space (laws are same at any location)\n🌀 Conservation of Angular Momentum ↔ Rotational symmetry\n\n**This means:** Energy is conserved because the laws of physics are the same today as yesterday. If time symmetry were violated — energy would not be conserved. Conservation laws are DEEP.\n\n**The 3 laws of thermodynamics as jokes (really taught this way!):**\n1st: You can't win (you can't get more energy out than you put in)\n2nd: You can't break even (some useful energy is always lost as waste heat)\n3rd: You can't quit the game (you can never reach absolute zero)\n\n**Entropy (2nd Law):**\nUsable energy always degrades to waste heat. The universe tends toward states of maximum disorder (entropy). This is why:\n🌡️ Engines always waste heat\n🔋 Batteries degrade over time\n🕰️ Time flows in one direction — the direction of increasing entropy\n☀️ The universe will eventually reach 'heat death' when entropy is maximum\n\n**The ultimate fate of the universe:** After ~10¹⁰⁰ years, all arranged matter decays to maximum entropy — a cold, dark, evenly distributed sea of photons. 🌌", highlight: "Noether's Theorem proves energy conservation is a consequence of time symmetry — if physics changed over time, energy wouldn't be conserved! ⚖️" },
    { id: 'energy_efficiency', title: 'Energy Efficiency & the Real World 🔧', color: '#E17055', bgGradient: ['#2A0A00', '#05050A'], icon: '🔧', svgIcon: 'flask', content: "Energy efficiency = useful output energy / total input energy × 100%\n\n**Real-world efficiencies:**\n⚡ Electric motor: 85-97% efficient (best common device!)\n⚡ LED light: 40-50% efficient\n💡 Incandescent bulb: 5% efficient (95% is heat — why they're banned!)\n🚗 Petrol car engine: 20-35% efficient (most is waste heat)\n🚗 Electric car motor: >90% efficient\n🔋 Power plant (coal): 33-40% efficient\n☀️ Solar panel: 22-25% efficient\n🌬️ Wind turbine: 35-45% efficient (vs max 59.3%)\n🧠 Human body: 25% mechanical, but 35% efficient at walking specifically\n\n**Why can't we reach 100%?**\nThe 2nd Law of Thermodynamics — every energy conversion produces some waste heat. Entropy always increases in a closed system.\n\n**The global energy budget:**\n🌍 World primary energy: ~600 EJ/year (600×10¹⁸ J)\n🌍 About 2/3 is WASTED as heat in power plants, engines, and appliances!\n🌍 Improving efficiency from 33% to 50% would cut energy need by 33% — equivalent to closing 4000 power stations\n\n**Why EVs are better even if charged from coal:**\nCoal plant: 35% efficient → charging: 90% → motor: 90% = 28% total\nPetrol car: 28% total\nAbout the same! But EVs can use renewable sources. As the grid gets greener, EVs automatically get cleaner. ♻️", highlight: "Incandescent bulbs waste 95% of electricity as heat — LEDs use the same electricity 10x more efficiently, saving 1 billion tonnes of CO₂ yearly! 🔧" },
  ],

  lab: {
    title: "Energy Transformer Lab ⚡",
    description: "Convert energy between types — gravitational, kinetic, thermal, electrical, and chemical! Watch conservation laws in action and find where energy is wasted!",
    hint: "Drop a mass from maximum height and watch kinetic energy peak at the bottom. Then try converting to electrical and see efficiency losses as heat! ⚡",
    scientistModeHint: "Scientist Mode: see real energy equations (KE=½mv², GPE=mgh, Q=mcΔT), live power calculations, and efficiency percentages as energy converts.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why you can't make a perpetual motion machine? 🔄", answer: "Every energy conversion produces some waste heat (2nd Law of Thermodynamics). Even the most efficient machines (superconducting magnets at 100% electrical efficiency) still had energy input to cool them to superconducting temperature. Over time, friction, air resistance, and thermal losses always drain the system. Thousands of patents for perpetual motion machines have been filed — none ever worked. The patent office now requires a working model before granting patents for perpetual motion (after being deluged with obvious frauds). Energy must come from somewhere! 🚫", emoji: '🔄' },
    { id: 'dyk2', question: "Do you know why nuclear bombs are millions of times more powerful than chemical bombs? ☢️", answer: "E=mc². Chemical explosions (TNT) rearrange electron bonds releasing ~3 kJ/g. Nuclear fission rearranges NUCLEONS — converting a tiny fraction (0.1%) of nuclear mass directly to energy via E=mc². Since c²=9×10¹⁶ m²/s², even 0.1% of a gram is enormous. 1kg of fissile uranium = 45,000 kWh vs 1kg of TNT = 0.001 kWh — a factor of 45 million. A hydrogen bomb fuses hydrogen nuclei, converting ~0.7% of mass to energy — even more efficient. This is why nuclear weapons are in a completely different category. ⚡", emoji: '☢️' },
    { id: 'dyk3', question: "Do you know why your laptop runs hot and why that heat is 'wasted'? 💻", answer: "Your laptop does useful computation (electrical → information processing), but resistance in semiconductors causes electrons to lose kinetic energy as heat (Joule heating: P=I²R). Even the most efficient chips convert 30-40% of their electrical input to heat. Heat must be removed to prevent damage — hence fans, heatsinks, and thermal paste. GPUs running AI models can draw 300-500W and dump all that as heat. Data centres globally generate enough waste heat to warm entire city districts — 'waste heat recovery' projects pipe this heat to homes! ♨️", emoji: '💻' },
    { id: 'dyk4', question: "Do you know why lightning rods work — and what Ben Franklin actually proved? ⚡", answer: "The popular story is that Franklin flew a kite in a lightning storm to ATTRACT lightning. He didn't — doing so would have killed him (several early followers who tried it died!). His kite experiment showed that thunderclouds are charged, not that lightning struck his kite. Lightning rods work by providing a LOW RESISTANCE PATH for charge to equalize between clouds and ground — the sharp tip creates a corona discharge that gradually bleeds charge, often PREVENTING a massive lightning strike by releasing charge slowly. Franklin never patented it — he gave it to humanity free of charge (pun intended). ⚡", emoji: '⚡' },
    { id: 'dyk5', question: "Do you know why the Sun will eventually consume the Earth — and why that's beautiful from a physics perspective? ☀️", answer: "The Sun is powered by hydrogen fusion in its core (proton-proton chain). In ~5 billion years, it will exhaust its hydrogen fuel, causing the core to collapse and the outer layers to expand into a Red Giant — engulfing Mercury, Venus, and probably Earth. From a physics perspective, this is just energy conservation at the largest scale. The Sun stores nuclear PE in hydrogen; fusion converts it to radiant energy; Earth captures a tiny fraction powering all life. Eventually, all the 'organised' energy structure of our solar system will disperse as heat — the universe marching toward maximum entropy. ✨", emoji: '☀️' },
  ],

  quiz: [
    { id: 'q1', question: "What is the Law of Conservation of Energy? ⚖️", options: ['Energy decreases over time as it is used', 'Energy can be neither created nor destroyed — only converted between forms', 'The amount of energy in the universe increases as stars are born', 'Chemical energy is always conserved but heat energy can be created'], answer: 1, explanation: "The 1st Law of Thermodynamics: total energy in a closed system is constant. Every joule must come from somewhere — perpetual motion machines violate this and are impossible. This law has never been violated even once in all of physics! ⚖️" },
    { id: 'q2', question: "If you double an object\'s speed, what happens to its kinetic energy? 🏃", options: ['Kinetic energy doubles', 'Kinetic energy triples', 'Kinetic energy quadruples (×4)', 'Kinetic energy stays the same — only momentum doubles'], answer: 2, explanation: "KE = ½mv². Speed is SQUARED — so doubling v means v² increases by 4×! KE quadruples. This is why high-speed car crashes are exponentially more deadly than low-speed ones. Driving at 60 mph is 4× more dangerous than 30 mph from a KE perspective! 🚗" },
    { id: 'q3', question: "Why can no engine ever be 100% efficient? 🔧", options: ['No material can withstand the required temperatures', 'The 2nd Law of Thermodynamics requires some energy to be converted to waste heat', 'Engineers aren\'t skilled enough yet', 'Energy efficiency only applies to electrical systems'], answer: 1, explanation: "2nd Law of Thermodynamics: every energy conversion produces some waste heat. This is NOT an engineering limitation — it's a fundamental law of physics. Even perfect machines lose some energy as heat. The universe is always increasing in entropy! ♨️" },
    { id: 'q4', question: "What is the formula for gravitational potential energy? 🌀", options: ['GPE = mv²', 'GPE = ½mv²', 'GPE = mgh', 'GPE = Fh²'], answer: 2, explanation: "GPE = mgh where m=mass, g=gravitational field strength (9.81 m/s² on Earth), h=height above reference point. A 70kg person at the top of a 10m building: GPE = 70×9.81×10 = 6,867 J. All this converts to kinetic energy if they fall! 🌀" },
    { id: 'q5', question: "What makes nuclear energy approximately 1 million times more energy-dense than fossil fuels? ☢️", options: ['Nuclear reactions operate at higher temperatures', 'Mass is partly converted to energy via E=mc² — the speed of light squared is an enormous multiplier', 'Nuclear fuels have more chemical bonds per gram', 'Radioactive decay continuously produces new energy'], answer: 1, explanation: "E=mc² — even 0.1% mass conversion: 1g × c² = 9×10¹³ J. Chemical bonds involving electron rearrangements release ~kJ/mol. Nuclear reactions rearrange nucleons — energy scale millions of times larger because nuclear forces are millions of times stronger than electromagnetic! ☢️" },
    { id: 'q6', question: "Which energy conversion happens in a hydroelectric dam? 💧", options: ['Chemical → Electrical', 'Nuclear → Thermal → Electrical', 'Gravitational PE → Kinetic → Electrical', 'Thermal → Mechanical → Electrical'], answer: 2, explanation: "Water behind the dam has Gravitational PE (mgh). As it falls, this converts to Kinetic Energy (½mv²). The turbine converts kinetic to rotational mechanical energy → generator converts to Electrical. Hydroelectric is ~90% efficient — highest of any common energy source! 💧" },
    { id: 'q7', question: "What does E=mc² actually mean? ✨", options: ['Energy equals mass times the speed of sound squared', 'Mass and energy are equivalent — mass can be converted to energy and vice versa', 'The energy of a photon equals its mass times light speed', 'Electrical energy is always greater than mechanical energy'], answer: 1, explanation: "Einstein's mass-energy equivalence: mass IS energy in a different form. c²=9×10¹⁶ J/kg is an enormous multiplier. Even a tiny mass converts to vast energy — this is what powers stars (fusion) and nuclear weapons (fission). 1kg mass = 9×10¹⁶ J if fully converted! 🌟" },
    { id: 'q8', question: "Why is an LED bulb far more efficient than an incandescent bulb? 💡", options: ['LEDs use higher voltage which is more efficient', 'LEDs produce light directly from electron transitions; incandescents heat a wire and only 5% becomes light', 'LED bulbs have less resistance creating less energy loss', 'LED chips are made from superconducting materials'], answer: 1, explanation: "Incandescents heat tungsten to 2500°C — only ~5% of electrical energy becomes visible light (95% wasted as heat). LEDs directly convert electron energy to photons via semiconductor band gap — ~40-50% efficient. Replacing all bulbs globally with LEDs saves >1 billion tonnes CO₂/year! 💡" },
    { id: 'q9', question: "What is ATP and why is it called the 'energy currency' of cells? 🔋", options: ['A protein that stores food energy long-term', 'Adenosine triphosphate — a molecule that stores and releases small packets of chemical energy for cellular processes', 'A vitamin that regulates energy metabolism', 'A hormone that signals cells to produce energy'], answer: 1, explanation: "ATP (adenosine triphosphate) releases ~30 kJ/mol when one phosphate bond breaks. Your body makes AND recycles ~40 kg of ATP per day! It's the universal energy currency because almost every cellular process (muscle contraction, protein synthesis, ion pumps) is powered by ATP hydrolysis! 💪" },
    { id: 'q10', question: "Why are electric vehicles (EVs) considered more efficient than petrol cars even if charged from coal power? 🚗", options: ['EVs have a better aerodynamic design that reduces energy loss', 'EVs capture all braking energy whereas petrol cars cannot', 'The total energy chain (coal→power→charging→motor) is similar, but EVs improve as grid gets greener', 'EVs have lower mass, so require less energy to accelerate'], answer: 2, explanation: "Coal plant (35%) → charging (90%) → motor (90%) ≈ 28% total. Petrol car ≈ 28% total. About even! BUT: EVs can capture braking energy (regenerative braking), and as the grid develops more renewables, they automatically get cleaner. Also: urban driving favours EVs massively as stop-start wastes much less energy! 🌱" },
    { id: 'q11', question: "What type of energy does a stretched rubber band store? 🪢", options: ['Kinetic energy', 'Elastic potential energy', 'Chemical energy', 'Thermal energy'], answer: 1, explanation: "A stretched rubber band stores elastic potential energy (EPE = ½kx²). When released, this converts to kinetic energy as the band snaps back. The further you stretch, the more energy stored — quadratically! 🪢" },
    { id: 'q12', question: "What is the Betz limit for wind turbines? 🌬️", options: ['100% — all wind energy can be captured', '59.3% — the theoretical maximum energy extractable from wind', '25% — limited by blade friction', '80% — limited by generator efficiency'], answer: 1, explanation: "The Betz limit (59.3%) is the theoretical maximum fraction of wind energy a turbine can extract. If a turbine captured 100%, the air behind it would stop — blocking new wind from arriving! Real turbines achieve 35-45%. 🌬️" },
    { id: 'q13', question: "What is the relationship between temperature and kinetic energy of particles? 🌡️", options: ['Temperature equals total kinetic energy of all particles', 'Temperature is proportional to the average kinetic energy of particles', 'Temperature is inversely proportional to kinetic energy', 'There is no relationship between temperature and kinetic energy'], answer: 1, explanation: "Temperature = average kinetic energy per particle. Higher temperature means particles move faster on average. At absolute zero (0K), particles have minimum possible kinetic energy. This is the foundation of the kinetic theory of matter! 🌡️" },
    { id: 'q14', question: "What did Emmy Noether's theorem prove about energy conservation? ⚖️", options: ['Energy conservation is just an approximation', 'Energy conservation is a consequence of time symmetry in physics', 'Conservation only applies to closed systems on Earth', 'Energy is created during the Big Bang and slowly consumed'], answer: 1, explanation: "Noether's Theorem (1915) proved that energy conservation arises because the laws of physics are the same at all times (time translation symmetry). If physics changed over time, energy would NOT be conserved. This is one of the deepest results in all of physics! ⚖️" },
    { id: 'q15', question: "Why is latent heat of vaporisation (2260 J/g) much higher than latent heat of fusion (334 J/g) for water? 💨", options: ['Vaporisation requires more energy because ALL intermolecular bonds must be completely broken', 'Fusion involves chemical bond breaking which uses more energy', 'Vaporisation happens at higher temperatures so needs more input', 'Steam molecules are heavier than liquid water molecules'], answer: 0, explanation: "During vaporisation, molecules must completely escape ALL intermolecular forces to become gas — requiring ~7× more energy than melting (which only loosens the lattice structure). This is why steam burns at 100°C are far worse than boiling water burns! 💨" },
    { id: 'q16', question: "What is 'regenerative braking' in electric vehicles? 🔋", options: ['Braking that regenerates worn brake pads', 'Converting kinetic energy back to electrical energy during braking', 'Using engine heat to recharge the battery', 'A braking system that uses solar panels'], answer: 1, explanation: "Regenerative braking reverses the motor — it acts as a generator, converting the car's kinetic energy back into electrical energy stored in the battery. Traditional brakes waste ALL kinetic energy as heat. EVs can recover 60-70% of braking energy! 🔋" },
    { id: 'q17', question: "Why does the Sun produce energy through fusion rather than fission? ☀️", options: ['The Sun contains uranium that naturally fissions', 'Light elements like hydrogen release energy when fused; heavy elements release energy when split', 'Fusion requires less temperature than fission', 'The Sun uses both equally'], answer: 1, explanation: "Elements lighter than iron release energy when FUSED (combined). Elements heavier than iron release energy when SPLIT (fissioned). Hydrogen is the lightest element — fusion into helium releases massive energy. This is why stars shine! ☀️" },
    { id: 'q18', question: "What is the energy efficiency of a typical incandescent light bulb? 💡", options: ['About 50% — half becomes light', 'About 25% — a quarter becomes light', 'About 5% — most energy becomes waste heat', 'About 75% — most energy becomes light'], answer: 2, explanation: "Incandescent bulbs convert only ~5% of electricity to visible light — the other 95% is wasted as infrared heat! This extreme inefficiency is why they've been banned or phased out globally in favour of LEDs (40-50% efficient). 💡" },
    { id: 'q19', question: "What is the principle behind a heat pump? 🏠", options: ['It creates heat from nothing using a special chemical', 'It moves existing heat from a cold place to a warm place using work input', 'It converts electrical energy directly to heat through resistance', 'It burns fuel more efficiently than a normal heater'], answer: 1, explanation: "A heat pump moves heat 'uphill' (cold→hot) by doing work (electricity). For every 1 kWh of electricity, it can move 3-4 kWh of heat — giving 300-400% apparent efficiency! It doesn't create energy, it transfers environmental heat into your home. 🏠" },
    { id: 'q20', question: "What happens to the total energy of the universe over time? 🌌", options: ['It slowly decreases as stars burn out', 'It increases as new matter is created', 'It remains exactly constant — energy is never created or destroyed', 'It fluctuates randomly due to quantum effects'], answer: 2, explanation: "The 1st Law of Thermodynamics: the universe's total energy has been exactly constant since the Big Bang — not one joule has been created or lost in 13.8 billion years. Stars convert nuclear PE to radiation, but the total is always the same! 🌌" },
  ],

  relatedTopics: ['forces_motion', 'heat_temperature', 'electricity_circuits', 'matter_states'],
};
