// ─────────────────────────────────────────────────────────
//  TOPIC: INSURANCE
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'insurance',
  title: 'Insurance & Protection',
  subtitle: 'Buying a safety net for your life 🛡️',
  emoji: '🛡️',
  category: 'Finance',
  accentKey: 'danger',

  hook: {
    question: "Is insurance just 'throwing money away' if you never have an accident? 📉",
    reveal: "No! Insurance is the only product in the world you buy hoping you NEVER use it. It's like a parachute. You don't buy a parachute because you want to jump; you buy it so that IF the plane fails, you don't hit the ground. Let's learn how to build your financial safety net! 🛡️💸",
    emoji: '🛡️',
  },

  theory: [
    {
      id: 'what_is_insurance',
      title: 'The Group Safety Net 🛡️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'star',
      content: "Imagine 1,000 people. Each puts ₹100 into a bucket every month. \n\nOne day, one person's house burns down. The bucket now has ₹1,00,000! That money is given to the victim to rebuild. This is **Insurance.** You pay a small 'Subscription' (Premium) to protect yourself from a 'Disaster' (Claim). It's the community sharing the risk so no one person is destroyed by bad luck.",
      highlight: "Insurance is sharing the risk with thousands of others. 🤝",
    },
    {
      id: 'premium_deductible',
      title: 'Premium vs Deductible ⚖️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'eye',
      content: "**Premium:** The 'Subscription Fee' you pay every month/year to stay protected.\n\n**Deductible:** The 'Small Share' you pay when an accident happens. If you have a ₹5,000 deductible, and your car repair costs ₹50,000, YOU pay ₹5,000 and the insurance company pays the remaining ₹45,000. Higher deductibles make your monthly premium cheaper! 📉",
      highlight: "Premium is what you pay to HAVE insurance; Deductible is what you pay to USE it. ⚖️",
    },
    {
      id: 'life_insurance',
      title: 'The Love Letter (Life) ❤️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '❤️',
      svgIcon: 'heart',
      content: "Life Insurance isn't for you—it's for the people you love. \n\nIf you earn the money that buys the pizza and pays the rent, and you suddenly 'vanish,' your family will be in trouble. Life insurance sends them a giant bag of money so they can keep living in their house and eating pizza even when you aren't there to provide it. It's the ultimate 'I Love You' gift. 🎁",
      highlight: "Life insurance protects your family from your absence. 🕊️",
    },
    {
      id: 'term_vs_endowment',
      title: 'Term vs Everything Else ⏳',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⏳',
      svgIcon: 'balance',
      content: "**Term Insurance:** Pure protection. Very cheap. If you die, they pay. If you live, you get nothing. This is the best type! \n\n**Endowment/ULIP:** A mix of insurance and investing. They are very expensive and usually do a bad job at both. It's like a spoon that's also a fork—it's bad at eating soup AND bad at eating salad. Buy Term and invest the rest yourself! 🥄🍴",
      highlight: "Keep your insurance and your investments separate! 🛡️📈",
    },
    {
      id: 'health_insurance',
      title: 'The Hospital Shield 🏥',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🏥',
      svgIcon: 'activity',
      content: "Hospital bills can cost more than a luxury car! \n\nOne surgery could wipe out your entire life savings in a single day. **Health Insurance** pays the hospital directly so you don't have to. In the modern world, not having health insurance is like walking through a battlefield without armor. One 'bullet' (illness) could end your financial life forever. 🛡️",
      highlight: "Health insurance protects your wealth from your health. 🏥",
    },
    {
      id: 'auto_insurance',
      title: 'The Car Guard 🚗',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🚗',
      svgIcon: 'shield',
      content: "**Third-Party:** Mandatory by law. If you hit someone else's car, the insurance pays for THEIR repairs. \n\n**Comprehensive:** Protects YOUR car too! If a tree falls on it or it gets stolen, the insurance gives you the money to buy a new one. Without auto insurance, one tiny mistake on a rainy day could cost you lakhs of rupees. 🌧️",
      highlight: "Don't drive a car you can't afford to insure. 🚗",
    },
    {
      id: 'property_insurance',
      title: 'The House Protector 🏠',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🏠',
      svgIcon: 'home',
      content: "Your home is likely the most expensive thing you will ever own. \n\n**Home Insurance** protects it from fire, floods, and earthquakes. If your house burns down, the insurance company gives you the millions of rupees needed to build a brand new one. It's a tiny price to pay to make sure you'll always have a roof over your head, no matter what happens. 🏗️",
      highlight: "Protect the roof over your head. 🏠",
    },
    {
      id: 'disability_insurance',
      title: 'The Paycheck Protector 💸',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '💸',
      svgIcon: 'refresh',
      content: "What if you get hurt and can't work for a year? \n\n**Disability Insurance** acts like a fake 'Job.' It pays you a percentage of your salary every month while you are recovering and can't go to the office. It ensures your lifestyle doesn't crash just because your body needs a break. It's insurance for your most valuable asset: Your ability to earn money! 🧠",
      highlight: "Your brain and body are your biggest income engines. Insure them! 🧠",
    },
    {
      id: 'underwriting',
      title: 'The Risk Detective 🕵️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🕵️',
      svgIcon: 'search',
      content: "Why do smokers pay more for insurance? \n\n**Underwriting** is the process where the company acts like a detective. They look at your age, your health, and your habits to guess how likely you are to have an accident. If you take big risks, they charge you a higher 'Price' (Premium). They aren't being mean; they are just doing the math of probability! 🧮",
      highlight: "Healthy habits lead to cheaper insurance. 🍏",
    },
    {
      id: 'liability_insurance',
      title: 'The Lawsuit Shield 🧑‍⚖️',
      color: '#e4a11cff',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🧑‍⚖️',
      svgIcon: 'lock',
      content: "If someone trips in your store and sues you for ₹1 Crore, what do you do? \n\n**Liability Insurance** pays for your lawyers and the settlement money. It protects you from mistakes that hurt other people. In our modern world where people love to sue each other, a liability shield is what keeps you from losing everything over one accidental slip. 🛡️",
      highlight: "Protect yourself from your own accidents. ⚖️",
    },
  ],

  lab: {
    title: "The Safety Net Lab 🛡️",
    description: "Welcome to the Insurance Lab! Explore 3 modes: See how the 'Group Bucket' works (The Insurance Pool), compare Term vs Endowment costs over 30 years, and visualize how a single hospital stay without insurance can 'reset' your life to zero. 📈",
    hint: "Try the 'Health Shock' mode. Watch the blue 'Savings' bar drop to zero in one click, while the 'Insured' bar stays strong. That's the power of protection!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks exact Actuarial math, showing the probability curves and 'Loss Ratios' used by insurance companies to stay profitable.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why insurance companies ask if you are a smoker? 🚬",
      answer: "Math! Smokers are statistically 50% more likely to get sick or die young. If the insurance company charged everyone the same price, the healthy people would be 'paying' for the smokers' risks. To be fair, the 'Risk Detective' (Underwriter) charges higher prices to people who take more risks. 🧮",
      emoji: '🚬',
    },
    {
      id: 'dyk2',
      question: "Do you know why you can't buy insurance for your house while it's ALREADY on fire? 🔥",
      answer: "That's not insurance; that's a bailout! Insurance is about 'Possible' risks in the future, not 'Certain' disasters in the present. If companies let you buy it after the fire, they would go bankrupt instantly, and there would be no 'Bucket' left for anyone else! 🛑",
      emoji: '🔥',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'Term Insurance' is the secret the agents don't tell you? 🤫",
      answer: "Low Commissions! Term insurance is so cheap that agents don't make much money selling it. They'd rather sell you a complex 'Savings + Insurance' plan because they get a HUGE cut of your first year's payment. Term is 10x cheaper and gives you more protection! 🕵️‍♂️",
      emoji: '🕵️‍♂️',
    },
    {
      id: 'dyk4',
      question: "Do you know why younger people pay LESS for life insurance? 👶",
      answer: "Probability! A 20-year-old has a very low chance of dying in the next year compared to an 80-year-old. The insurance company knows they will likely collect your 'Subscription' for 40+ years before ever having to pay a claim. Buying young locks in a cheap price for life! ⏳",
      emoji: '⏳',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Free' insurance from your job isn't enough? 💼",
      answer: "The Trap! If you get sick and have to quit your job, your job's insurance usually VANISHES instantly. Now you are sick, unemployed, AND have no insurance. You should always have your own personal safety net that isn't tied to your boss! 🛡️",
      emoji: '🛡️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the basic concept of insurance?", options: ["A way to get rich quick", "A group of people sharing the risk of a disaster", "A type of bank loan", "A government tax"], answer: 1, explanation: "Everyone chips in a little so no one loses a lot! 🛡️" },
    { id: 'q2', question: "What is an insurance 'Premium'?", options: ["A special prize you win", "The monthly/yearly fee you pay for protection", "The money you get when you have an accident", "A type of car"], answer: 1, explanation: "It's your subscription fee for the safety net! 💰" },
    { id: 'q3', question: "What is a 'Deductible'?", options: ["A discount on your taxes", "The small amount YOU pay before insurance covers the rest", "The total value of your car", "A type of hospital"], answer: 1, explanation: "It's your 'Skin in the Game' when an accident happens! ⚖️" },
    { id: 'q4', question: "Why is 'Term Insurance' usually better than 'Endowment'?", options: ["It's more colorful", "It provides the most protection for the lowest price", "It gives you a car", "It's free"], answer: 1, explanation: "Keep your protection cheap and your investments separate! 🛡️" },
    { id: 'q5', question: "Health insurance is primarily designed to protect:", options: ["The hospital", "Your life savings from massive medical bills", "Your doctors", "The government"], answer: 1, explanation: "One surgery can cost more than a house! 🏥" },
    { id: 'q6', question: "What does 'Third-Party' auto insurance cover?", options: ["Your car's repairs", "Repairs for the other person's car that you hit", "New tires", "A stolen car"], answer: 1, explanation: "It's mandatory to protect other people from your mistakes! 🚗" },
    { id: 'q7', question: "What does 'Underwriting' mean in insurance?", options: ["Writing a book about money", "The process of checking your risk to decide your price", "Signing a check", "Deleting an account"], answer: 1, explanation: "The 'Risk Detectives' do the math! 🕵️" },
    { id: 'q8', question: "Why should you buy life insurance?", options: ["To make yourself rich", "To protect your family's lifestyle if you are gone", "Because the law requires it", "To get a better credit score"], answer: 1, explanation: "It's a gift of safety for the people you love! ❤️" },
    { id: 'q9', question: "Disability insurance protects your:", options: ["Car", "Income while you are too hurt to work", "House", "Vacation"], answer: 1, explanation: "It insures your biggest asset: Your ability to earn! 💸" },
    { id: 'q10', question: "Liability insurance is like a shield against:", options: ["Fires", "Lawsuits if you accidentally hurt someone", "Thefts", "Bad grades"], answer: 1, explanation: "It protects you from expensive legal mistakes! 🧑‍⚖️" },
    { id: 'q11', question: "Why is insurance like a parachute?", options: ["It helps you fly", "You hope you never use it, but you need it if things go wrong", "It is made of silk", "It is very light"], answer: 1, explanation: "You buy it for the 'Worst-Case' scenario! 🛡️" },
    { id: 'q12', question: "If you have a ₹1,000 Premium and a ₹10,000 Deductible, which one do you pay EVERY month?", options: ["The Premium", "The Deductible", "Both", "Neither"], answer: 0, explanation: "Premium = Subscription. Deductible = Usage fee. 💰" },
    { id: 'q13', question: "Can you buy insurance for a car after you've crashed it?", options: ["Yes, if you pay more", "No, insurance is for future risks, not past certainties", "Only on Tuesdays", "If the police say it's okay"], answer: 1, explanation: "You can't buy a parachute while you're already falling! 🛑" },
    { id: 'q14', question: "Why do insurance agents push 'Invest-and-Insure' plans (ULIPs)?", options: ["They are the best for you", "Because they get much higher commissions (profit) for selling them", "They are easier to explain", "The government requires it"], answer: 1, explanation: "Agents are paid to sell you the expensive stuff! 🕵️‍♂️" },
    { id: 'q15', question: "What happens to your workplace insurance if you quit your job?", options: ["It stays with you forever", "It usually vanishes immediately", "It gets cheaper", "The government takes it over"], answer: 1, explanation: "Always own your own safety net! 🛡️" },
    { id: 'q16', question: "Which factor makes your auto insurance CHEAPER?", options: ["Driving faster", "Having a history of zero accidents", "Buying a more expensive car", "Being a teenager"], answer: 1, explanation: "Low risk = Low price! 🏎️" },
    { id: 'q17', question: "What is an 'Insurance Pool'?", options: ["A place where insurance agents swim", "The collective fund of money from all members used to pay for accidents", "A type of investment", "A bank vault"], answer: 1, explanation: "The bucket we all put our candy into! 🤝" },
    { id: 'q18', question: "Property insurance usually covers:", options: ["The value of your car", "The cost to rebuild your home after a fire or disaster", "Your grocery bill", "Your monthly rent"], answer: 1, explanation: "It protects the bricks and mortar of your life! 🏠" },
    { id: 'q19', question: "A 'Claim' is when you:", options: ["Pay your premium", "Ask the insurance company to pay for an accident", "Cancel your policy", "Buy a new car"], answer: 1, explanation: "It's calling for the safety net! 🛡️" },
    { id: 'q20', question: "Insurance is basically the opposite of:", options: ["Banking", "Gambling", "Investing", "Taxation"], answer: 1, explanation: "Gambling is taking a risk to get rich; Insurance is paying to avoid being poor! 🛡️" }
  ],

  relatedTopics: ['personal_finance', 'banking', 'debt_credit'],
};
