// ─────────────────────────────────────────────────────────
//  TOPIC: EXOPLANETS - WORLDS BEYOND OURS
//  Category: Space / Astronomy
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'exoplanets',
  title: 'Exoplanets',
  subtitle: 'The hunt for Earth 2.0 🌌🔭',
  emoji: '🪐',
  category: 'Space',
  accentKey: 'exoplanets',

  hook: {
    question: "Do you know how many planets are in our Milky Way galaxy? 🌌",
    reveal: "Latest estimates suggest there are over 100 BILLION planets in our galaxy alone—more planets than there are stars! 🤯 For thousands of years, humans didn't know if other suns had worlds like ours. Now, we've found thousands of them, from 'Hot Jupiters' that rain liquid iron to 'Water Worlds' covered in thousands of miles of ocean. Let's explore the final frontier! 🚀",
    emoji: '🛰️',
  },

  theory: [
    {
      id: 'what_is_exoplanet',
      title: 'Worlds Beyond Our Sun 🪐',
      color: '#A855F7',
      bgGradient: ['#050A1A', '#0D0D1A'],
      icon: '🪐',
      svgIcon: 'planet',
      content: "An **Exoplanet** (Extra-solar planet) is simply a planet that orbits a star other than our Sun ☀️.\n\nBecause stars are so incredibly far away, we can almost never see exoplanets directly with a telescope—they are millions of times dimmer than the stars they orbit. Imagine trying to see a tiny firefly 🪰 buzzing around a massive lighthouse 💡 from 10 miles away. That is what astronomers are trying to do!\n\nTo find them, we have to become 'Interstellar Detectives', looking for subtle clues in the star's light to prove a planet is hiding there.",
      highlight: "Exoplanets were science fiction until the first one was confirmed in 1992! 🕰️",
    },
    {
      id: 'first_discovery',
      title: '51 Pegasi b: The First 🥇',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#0D0D1A'],
      icon: '🥇',
      svgIcon: 'star',
      content: "In 1995, Michel Mayor and Didier Queloz made history by discovering a planet orbiting a Sun-like star for the first time: **51 Pegasi b**.\n\nScientists expected other solar systems to look like ours—small rocky planets near the star and giant gas giants far away. But 51 Pegasi b was a 'Hot Jupiter'—a massive gas giant orbiting so close to its sun that its 'year' is only 4 days long! 🔥\n\nThis discovery proved that the universe is far stranger and more diverse than we ever imagined. It earned them the Nobel Prize in Physics in 2019! 🏆",
      highlight: "51 Pegasi b orbits its sun so close that its surface temperature is over 1,000°C! ☄️",
    },
    {
      id: 'transit_method',
      title: 'The Transit Method 📉',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#0D0D1A'],
      icon: '📉',
      svgIcon: 'target',
      content: "This is the most successful way to find planets. When a planet crosses (transits) in front of its star, it blocks a tiny bit of the star's light 🌑.\n\nImagine a mosquito flying across a car headlight. The headlight gets slightly dimmer for a moment. By measuring this dip in light, astronomers can tell:\n• **Size:** How big the planet is (deeper dip = bigger planet).\n• **Orbit:** How far it is (longer time between dips = further out).\n\nThe Kepler Space Telescope used this method to find over 2,700 planets in one tiny patch of the sky! 🔭",
      highlight: "If the planet doesn't cross perfectly in front of the star from our view, we can't see the dip! 🤞",
    },
    {
      id: 'radial_velocity',
      title: 'Radial Velocity: The Wobble 💃',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#0D0D1A'],
      icon: '💃',
      svgIcon: 'waves',
      content: "Gravity is a two-way street. While a star pulls on a planet, the planet also pulls on the star! 🧲\n\nAs a massive planet orbits, it pulls the star back and forth, making it 'wobble' in place. Astronomers use the **Doppler Effect** to measure this. When the star wobbles toward us, its light shifts blue; when it wobbles away, it shifts red 🔴🔵.\n\nThis method is amazing because it tells us the **Mass** (weight) of the planet. The heavier the planet, the harder it pulls the star and the bigger the wobble!",
      highlight: "Radial Velocity measures the 'dance' between a star and its hidden planet. 🕺",
    },
    {
      id: 'goldilocks_zone',
      title: 'The Habitable Zone 🌡️',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#0D0D1A'],
      icon: '🌡️',
      svgIcon: 'globe',
      content: "To find life as we know it, we need liquid water 💧. To have liquid water, a planet must be at the perfect distance from its star. This is the **Goldilocks Zone** (Habitable Zone).\n\n• **Too Close:** Water boils into steam (Venus) ♨️.\n• **Too Far:** Water freezes into solid ice (Mars) ❄️.\n• **Just Right:** Liquid water can flow on the surface (Earth) 🌍.\n\nLarge stars have a Goldilocks zone much further out, while tiny Red Dwarf stars have a Goldilocks zone that is very close and tight.",
      highlight: "Finding a planet in the Goldilocks Zone is the first major step in finding aliens! 👽",
    },
    {
      id: 'hot_jupiters',
      title: 'Strange Worlds: Hot Jupiters 🔥',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#0D0D1A'],
      icon: '🔥',
      svgIcon: 'zap',
      content: "One of the biggest surprises was the discovery of **Hot Jupiters**. These are massive gas giants like Jupiter, but they orbit 20x closer to their star than Earth orbits the Sun! ☄️\n\nBecause they are so close, they are tidally locked—one side always faces the sun and is meltingly hot, while the other is in permanent darkness. The temperature difference creates supersonic winds faster than the speed of sound 💨.\n\nSome even orbit 'backwards' compared to their star's rotation, suggesting a violent and chaotic history! 🌪️",
      highlight: "WASP-76b is a Hot Jupiter where it's so hot that it actually rains liquid iron at night! ☔",
    },
    {
      id: 'super_earths',
      title: 'Super-Earths & Mini-Neptunes 🏔️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#0D0D1A'],
      icon: '🏔️',
      svgIcon: 'grid',
      content: "The most common type of planet found in the galaxy is one we don't even have in our own solar system: **Super-Earths**.\n\nThese are rocky planets that are 2 to 10 times more massive than Earth. They might have crushing gravity and thick atmospheres, or be covered entirely in oceans hundreds of miles deep 🌊.\n\nOn the other hand, **Mini-Neptunes** are slightly larger and have thick gas envelopes but no solid surface. These 'missing links' suggest that planets can come in any size imaginable! 🧱",
      highlight: "Super-Earths might be even more habitable than Earth due to their ability to hold a thicker atmosphere. 🛡️",
    },
    {
      id: 'atmospheres',
      title: 'Atmosphere: Seeing Light 🌈',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#0D0D1A'],
      icon: '🌈',
      svgIcon: 'sparkle',
      content: "How can we tell if a planet 100 light-years away has oxygen or water? We use **Spectroscopy** 🌈.\n\nWhen a planet transits in front of a star, a tiny bit of starlight passes through the planet's atmosphere. Different gases absorb different colors of light. By looking at the 'missing' colors in the star's spectrum, we can see the chemical fingerprints of Oxygen, Methane, Water Vapor, and Carbon Dioxide!\n\nThis is how the James Webb Space Telescope (JWST) is searching for 'Biosignatures'—chemical proof of alien life. 🧬",
      highlight: "A planet's atmosphere is like a chemical ID card that light carries to our telescopes. 🆔",
    },
    {
      id: 'proxima_b',
      title: 'Our Closest Neighbor: Proxima b 🏠',
      color: '#FF6B9D',
      bgGradient: ['#1A0D14', '#0D0D1A'],
      icon: '🏠',
      svgIcon: 'rocket',
      content: "In 2016, we found the closest exoplanet possible: **Proxima Centauri b**. It orbits the nearest star to our Sun, only 4.2 light-years away 🛰️.\n\nProxima b is roughly Earth-sized and sits right in the Goldilocks Zone of its Red Dwarf star. However, Red Dwarfs are famous for violent solar flares that could strip a planet's atmosphere away 💥. \n\nEven though it's the 'neighbor next door', it would take a current spacecraft about 70,000 years to reach it. We need new tech like 'Laser Sails' to get there in a human lifetime! 🌌",
      highlight: "Proxima b is the #1 target for our first-ever interstellar probe mission. 🚀",
    },
    {
      id: 'drake_equation',
      title: 'The Drake Equation: Are We Alone? 👽',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#0D0D1A'],
      icon: '👽',
      svgIcon: 'search',
      content: "Frank Drake created a mathematical formula in 1961 to estimate how many intelligent civilizations might exist in our galaxy: $N = R^* \\cdot f_p \\cdot n_e \\cdot f_l \\cdot f_i \\cdot f_c \\cdot L$\n\n• $f_p$: The fraction of stars with planets (We now know this is almost 100%!) 🌟\n• $n_e$: Number of habitable planets per system.\n• $f_l$: Percentage of those where life actually starts.\n\nIf even a tiny fraction of planets develop life, there could be thousands of civilizations. If life is extremely rare, we might be the only ones. The hunt for exoplanets is the race to solve this equation once and for all! 🏁",
      highlight: "The more planets we find, the more certain it becomes that we are NOT alone! 📡",
    },
  ],

  lab: {
    title: "Goldilocks Architect Lab 🧪",
    description: "Design your own solar system! Select a star type, drag a planet into orbit, and monitor its Habitability Index. Watch the 'Transit Graph' in real-time as your planet crosses the star, and try to find the perfect 'just right' zone for liquid water 💧",
    hint: "Try placing a massive Gas Giant near a Blue Giant star—watch the 'Wobble' in Scientist Mode. Can you place a rocky planet in the narrow Goldilocks zone of a Red Dwarf without it tidally locking?",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Orbital Mechanics ($v = \\sqrt{GM/r}$) and Light-Curve flux percentages (ppm).",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we can't just points a telescope and take a photo of an exoplanet? 📸",
      answer: "Contrast! A star is about 10 billion times brighter than a planet. It's like trying to see a speck of dust sitting on a giant searchlight beam from miles away. The star's light completely 'drowns out' the planet. We have to use 'Coronagraphs' to physically block the star's disk to see the tiny specks around it! 🕶️",
      emoji: '🔦',
    },
    {
      id: 'dyk2',
      question: "Do you know why most exoplanets discovered so far are 'Gas Giants'? 🎈",
      answer: "Selection Bias! Big, heavy planets are much easier to find because they block more light (Transit) and pull harder on their stars (Wobble). Tiny rocky planets like Earth are very hard to see. It’s like looking into a forest and only seeing the elephants—it doesn't mean there aren't thousands of birds too! 🐘",
      emoji: '🔍',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'Goldilocks' planets near Red Dwarfs might be dangerous? 💥",
      answer: "Radiation! Because Red Dwarfs are cool, the Goldilocks zone is very close. But Red Dwarfs are also very 'cranky'—they blast out massive X-ray solar flares. If a planet is that close, the flares could literally fry any life and blow the atmosphere into deep space like a leaf in a windstorm! 🌪️",
      emoji: '☢️',
    },
    {
      id: 'dyk4',
      question: "Do you know why we call them 'Hot Jupiters' instead of just big planets? 🌭",
      answer: "Because they shouldn't be there! Our theories said gas giants only form far away where it's cold enough for ice to help them grow. Finding them near stars proved that planets can 'migrate'—they form far away and then slowly spiral inward due to friction with space dust. The universe is a messy place! 🌀",
      emoji: '🪐',
    },
    {
      id: 'dyk5',
      question: "Do you know why finding 'Methane' on a planet is such a big deal? 💨",
      answer: "Because Methane is a 'Biosignature'! On Earth, almost all methane is produced by living things (like cows and bacteria). It breaks down quickly due to sunlight, so if we find a planet full of methane, it means something is *constantly* producing it right now. Could be aliens! 🐄",
      emoji: '🧬',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is an 'Exoplanet'?", options: ["A planet made of ice", "A planet orbiting another star", "A planet without an atmosphere", "A moon orbiting a planet"], answer: 1, explanation: "Extra-solar means 'outside our solar system'! 🪐" },
    { id: 'q2', question: "Which method finds planets by looking for a tiny dip in a star's brightness?", options: ["The Wobble Method", "The Transit Method", "The Imaging Method", "The Echo Method"], answer: 1, explanation: "Like a mosquito crossing a headlight, the planet blocks a tiny bit of light as it passes! 📉" },
    { id: 'q3', question: "The 'Goldilocks Zone' is the region around a star where:", options: ["Gravity is at zero", "Liquid water can exist", "Asteroids cannot form", "The star is gold"], answer: 1, explanation: "Not too hot, not too cold—just right for life's essential ingredient: water! 💧" },
    { id: 'q4', question: "The 'Radial Velocity' method detects planets by measuring a star's:", options: ["The surface temperature", "A slight color wobble", "The total mass", "Distance from Earth"], answer: 1, explanation: "The planet's gravity pulls the star, causing a Doppler shift (red/blue) in its light! 💃" },
    { id: 'q5', question: "What is a 'Hot Jupiter'?", options: ["A planet of fire", "A close-orbiting gas giant", "A gravity-free planet", "A small rocky planet"], answer: 1, explanation: "These giants are so close to their suns that they can orbit in just a few days! 🔥" },
    { id: 'q6', question: "Which space telescope found thousands of planets using the Transit method?", options: ["The Hubble Telescope", "The Kepler Telescope", "The Webb Telescope", "The Voyager Probe"], answer: 1, explanation: "Kepler was a 'planet hunter' that stared at 150,000 stars to find tiny light dips! 🔭" },
    { id: 'q7', question: "Which type of planet is more massive than Earth but smaller than Neptune?", options: ["A massive Super-Earth", "A close Hot Jupiter", "A bright Mini-Sun", "A large rocky asteroid"], answer: 0, explanation: "These common worlds might be rocky or water-covered and come in sizes we don't have in our solar system! 🏔️" },
    { id: 'q8', question: "How can scientists tell if a planet has oxygen without visiting it?", options: ["Using a long probe", "Analyzing light through atmosphere", "Guessing by surface color", "It is currently impossible"], answer: 1, explanation: "Light carries the 'chemical fingerprint' of the gases it passes through! 🌈" },
    { id: 'q9', question: "What is the name of the closest known exoplanet to Earth?", options: ["The planet Kepler-186f", "The planet Proxima Centauri", "The planet Mars", "The planet Alpha Prime"], answer: 1, explanation: "It orbits our nearest neighbor star, only 4.2 light-years away! 🏠" },
    { id: 'q10', question: "The Drake Equation is used to estimate:", options: ["Total stars in universe", "Intelligent civilizations in galaxy", "The speed of light", "Mass of a planet"], answer: 1, explanation: "It uses probabilities to guess how common 'aliens' might be! 👽" },
    { id: 'q11', question: "WASP-76b is a planet so hot that it actually rains:", options: ["Rains of solid diamonds", "Rains of liquid iron", "Rains of sulfuric acid", "Rains of liquid water"], answer: 1, explanation: "At night, the iron vapor in the air cools and falls as metallic rain! ☔" },
    { id: 'q12', question: "Why is a Red Dwarf's Goldilocks zone so close to the star?", options: ["They have more gravity", "They are cooler and dimmer", "They pull planets inward", "They have no zones"], answer: 1, explanation: "Because the heater (the star) is smaller, you have to stand closer to stay warm! 🌡️" },
    { id: 'q13', question: "What is 'Tidal Locking'?", options: ["Magnetic field capture", "One side faces star", "Extremely high tides", "Lack of planetary spin"], answer: 1, explanation: "Common in close-in planets, one side is forever day, the other forever night! 🌓" },
    { id: 'q14', question: "The James Webb Space Telescope (JWST) is primarily designed to look for:", options: ["Only distant black holes", "Searching for biosignatures", "Life on Mars", "New Jupiter moons"], answer: 1, explanation: "JWST can see the infrared light needed to 'breathe' in the chemical makeup of distant worlds! 🛰️" },
    { id: 'q15', question: "What happened to the first-ever discovered Hot Jupiter, 51 Pegasi b?", options: ["The planet exploded", "It was a mistake", "It won a Nobel Prize", "It hit its sun"], answer: 2, explanation: "In 2019, Mayor and Queloz were awarded the Nobel Prize for their 1995 discovery! 🏆" },
    { id: 'q16', question: "What is 'Limb Darkening' on a Transit graph?", options: ["Dimmer star edges", "Darker planet surface", "Broken telescope lens", "A solar eclipse"], answer: 0, explanation: "It causes the 'U' shape in the dip because the edges of a star aren't as bright as the center. 📉" },
    { id: 'q17', question: "In the 'Wobble' method, when a star moves TOWARD us, its light shifts:", options: ["To the red", "To the blue", "To the green", "To the invisible"], answer: 1, explanation: "Blue-shift occurs when light waves are 'compressed' by the star moving toward us! 🔵" },
    { id: 'q18', question: "Why is finding an 'Earth-sized' planet in the Goldilocks zone so important?", options: ["They look prettier", "They can hold water", "They are easy reach", "They contain oxygen"], answer: 1, explanation: "Size determines gravity, which determines if a planet can 'keep' its air and water! 🌍" },
    { id: 'q19', question: "How many exoplanets were estimated to exist in our galaxy in the 1980s?", options: ["Billions of planets", "No planets at all", "Existence was unknown", "Thousands of planets"], answer: 2, explanation: "Until 1992, exoplanets were purely theoretical—we have learned so much in 30 years! 🕰️" },
    { id: 'q20', question: "If a planet blocks 1% of a star's light, it is likely:", options: ["An Earth-sized planet", "A Jupiter-sized giant", "A small moon", "A thick dust cloud"], answer: 1, explanation: "Earth only blocks 0.01% of the Sun's light, while Jupiter blocks about 1%! 📐" },
  ],

  relatedTopics: ['solar_system', 'black_holes', 'astronomy_basics', 'gravity'],
};
