export default {
  id: 'human_body_systems',
  title: 'Human Body Systems',
  subtitle: 'The most complex machine ever built 🫀',
  emoji: '🫀',
  category: 'Biology',
  accentKey: 'person',

  hook: {
    question: "Did you know your heart beats 100,000 times a day and pumps enough blood to fill an Olympic swimming pool every 2 weeks? 🤯",
    reveal: "Your body is the most sophisticated engineering marvel ever assembled. 11 organ systems work in perfect coordination 24/7 — breathing, pumping, sending messages, fighting invaders, digesting, and repairing — all without you thinking about it. Understanding body systems is the foundation of medicine. Doctors, athletes, and engineers all study the same blueprint: YOU. 🫀🧠💪",
    emoji: '🫀',
  },

  theory: [
    {
      id: 'overview',
      title: 'The 11 Body Systems 🏗️',
      color: '#FF6B9D',
      bgGradient: ['#1A0820', '#05050A'],
      icon: '🏗️',
      svgIcon: 'person',
      content: "The human body has **11 organ systems** that work together:\n\n🫀 **Circulatory** — heart and blood vessels\n🫁 **Respiratory** — lungs and breathing\n🧠 **Nervous** — brain, spinal cord, nerves\n💪 **Muscular** — movement\n🦴 **Skeletal** — structure and support\n🛡️ **Immune/Lymphatic** — fighting disease\n🍎 **Digestive** — breaking down food\n🔬 **Endocrine** — hormones and signals\n⚗️ **Excretory (Urinary)** — waste removal\n👶 **Reproductive** — creating new life\n🌡️ **Integumentary** — skin, hair, nails\n\nNo system works in isolation — your heart can't beat without signals from the nervous system. Your muscles can't contract without oxygen from the lungs. Life is a symphony of systems! 🎼",
      highlight: "The body has 11 organ systems working simultaneously — they are so interconnected that failure in one affects all others! 🏗️",
    },
    {
      id: 'circulatory',
      title: 'The Circulatory System 🫀',
      color: '#FF4444',
      bgGradient: ['#2A0A0A', '#05050A'],
      icon: '🫀',
      svgIcon: 'heart',
      content: "The **circulatory system** is the body's delivery network — pumping blood, nutrients, oxygen, and hormones to every single cell.\n\n**The Heart:**\n❤️ Beats ~72 times/minute → 3.7 billion times in a lifetime!\n❤️ 4 chambers: right atrium/ventricle (to lungs), left atrium/ventricle (to body)\n❤️ The left ventricle is the most powerful — it pumps blood against systemic pressure\n\n**Two circuits:**\n🔴 **Pulmonary circulation** — right side pumps deoxygenated blood to lungs\n🔵 **Systemic circulation** — left side pumps oxygenated blood to body\n\n**Blood composition:**\n🔴 Red blood cells (RBCs) — carry O₂ via haemoglobin\n⚪ White blood cells — fight infection\n🟡 Platelets — clot wounds\n💛 Plasma — carries everything in solution\n\n**Blood pressure** is measured as systolic/diastolic (120/80 mmHg is normal). 💉",
      highlight: "Your heart beats 100,000 times a day and pumps blood through 100,000 km of blood vessels — enough to circle Earth 2.5 times! 🫀",
    },
    {
      id: 'respiratory',
      title: 'The Respiratory System 🫁',
      color: '#4FC3F7',
      bgGradient: ['#0A1520', '#05050A'],
      icon: '🫁',
      svgIcon: 'waves',
      content: "The **respiratory system** brings oxygen in and carbon dioxide out:\n\n**Pathway of air:**\nNose/Mouth → Pharynx → Larynx → Trachea → Bronchi → Bronchioles → **Alveoli** 🎯\n\n**Alveoli** — tiny balloon-like air sacs at the end. You have ~600 million of them! Their total surface area = a tennis court (70 m²). This enormous surface enables rapid gas exchange. 🎾\n\n**Gas Exchange:**\nO₂ diffuses from air (high O₂) into blood (low O₂)\nCO₂ diffuses from blood (high CO₂) into air (low CO₂)\n\n**Control of breathing** is automatic! The **medulla oblongata** in the brainstem monitors CO₂ levels in blood. When CO₂ rises, it triggers breathing — you don't breathe when you need O₂, you breathe when CO₂ gets too high!\n\n**Fun fact:** Your lungs float on water! If you put a lung in a tank of water, it would float because of all the trapped air. 🎈",
      highlight: "Your 600 million alveoli create the surface area of a tennis court for gas exchange — breathing is controlled by CO₂ not O₂! 🫁",
    },
    {
      id: 'nervous_system',
      title: 'The Nervous System 🧠',
      color: '#F9CA24',
      bgGradient: ['#2A1A0A', '#05050A'],
      icon: '🧠',
      svgIcon: 'brain',
      content: "The **nervous system** is the body's electrical communication network — faster than any computer system humans have built.\n\n**Divisions:**\n🧠 **Central Nervous System (CNS)** — brain + spinal cord\n🔌 **Peripheral Nervous System (PNS)** — all other nerves\n\n**PNS further divides:**\n✅ **Somatic** — voluntary movements (you control these)\n⚡ **Autonomic** — involuntary (heart rate, digestion, etc.)\n&nbsp;&nbsp;→ **Sympathetic** — fight-or-flight (accelerates heartrate, dilates pupils)\n&nbsp;&nbsp;→ **Parasympathetic** — rest-and-digest (slows heart, aids digestion)\n\n**Neurons** (nerve cells) communicate via electrical signals called **action potentials**:\n⚡ Speed: up to 120 m/s (432 km/h)\n⚡ 100 billion neurons in the brain\n⚡ Each neuron connects to up to 10,000 others\n\nThe synapse is the gap between neurons — signals cross it using **neurotransmitters** (dopamine, serotonin, etc.) 🧪",
      highlight: "Your nervous system sends signals at 120 m/s — 100 billion neurons each connected to up to 10,000 others! 🧠",
    },
    {
      id: 'digestive',
      title: 'The Digestive System 🍎',
      color: '#FF9F1C',
      bgGradient: ['#2A1A0A', '#05050A'],
      icon: '🍎',
      svgIcon: 'flask',
      content: "The **digestive system** breaks food into molecules small enough for cells to use:\n\n**Journey of food (9 metres total!):**\n👄 **Mouth** — mechanical digestion (chewing) + salivary amylase starts breaking starch\n🍽️ **Oesophagus** — muscular tube; peristalsis (wave contractions) pushes food down\n🟡 **Stomach** — HCl acid (pH 2!) + pepsin destroys proteins; churns food into chyme\n🟠 **Small intestine** (6m!) — main digestion + absorption. Villi and microvilli massively increase surface area\n🔴 **Large intestine** — absorbs water; bacteria produce vitamins B and K (**your microbiome!**)\n💩 **Rectum/Anus** — waste elimination\n\n**Accessory organs:**\n🫏 Liver — makes bile, detoxifies blood\n🟡 Pancreas — enzymes + insulin/glucagon for blood sugar\n💛 Gallbladder — stores bile\n\nYour gut has its own nervous system (the enteric nervous system) — called the **second brain**! 🧠",
      highlight: "Food travels through 9 metres of digestive tract — your gut has its own nervous system called the 'second brain'! 🍎",
    },
    {
      id: 'skeletal_muscular',
      title: 'Skeletal & Muscular Systems 💪',
      color: '#EEEEEE',
      bgGradient: ['#1A1A1A', '#05050A'],
      icon: '💪',
      svgIcon: 'balance',
      content: "**Skeletal System:**\n🦴 206 bones in adults (babies have ~270 — they fuse!)\n🦴 Functions: support, protection, movement, blood cell production, mineral storage\n🦴 Bone is living tissue — it constantly remodels itself\n🦴 Red bone marrow makes 200 billion red blood cells per day!\n\n**Three types of joints:**\n🔩 **Synovial** — freely moveable (knee, hip, shoulder)\n🔧 **Cartilaginous** — limited movement (vertebrae)\n🔒 **Fibrous** — immoveable (skull sutures)\n\n**Muscular System:**\n💪 ~600+ muscles in the body\n💪 **Skeletal muscle** — voluntary, striated; contracts when actin+myosin filaments slide past each other\n💪 **Cardiac muscle** — involuntary; only in the heart; self-pacing (has its own electrical system!)\n💪 **Smooth muscle** — involuntary; walls of organs (gut, blood vessels)\n\nThe **sartorius** is the longest muscle (hip to knee). The **stapedius** in the ear is the smallest! 👂",
      highlight: "You have 206 bones and 600+ muscles — bone marrow makes 200 billion red blood cells every single day! 💪",
    },
    {
      id: 'endocrine',
      title: 'The Endocrine System 🔬',
      color: '#C77DFF',
      bgGradient: ['#1A0A2A', '#05050A'],
      icon: '🔬',
      svgIcon: 'flask',
      content: "The **endocrine system** communicates using chemical messengers called **hormones** — slower than nerve signals but longer-lasting.\n\n**Key glands and hormones:**\n🧠 **Hypothalamus** — master controller; links nervous and endocrine systems\n🔮 **Pituitary gland** (\"master gland\") — controls all other glands; releases growth hormone, FSH, LH\n🦋 **Thyroid** — controls metabolism; thyroxine speeds up body processes\n🫙 **Adrenal glands** — adrenaline (epinephrine) for fight-or-flight; cortisol for stress\n🟡 **Pancreas** — insulin (lowers blood sugar), glucagon (raises blood sugar)\n🎠 **Gonads** — oestrogen/progesterone, testosterone\n\n**Blood sugar control (negative feedback):**\nBlood sugar rises → Pancreas releases insulin → Cells absorb glucose → Sugar drops → Glucagon released → Liver releases glucose 🔄\n\n**Diabetes** occurs when this cycle breaks down! Type 1 = no insulin made; Type 2 = cells resist insulin. 💊",
      highlight: "The endocrine system uses hormones as chemical messengers — the pituitary gland controls all other glands! 🔬",
    },
    {
      id: 'homeostasis',
      title: 'Homeostasis: Body Balance ⚖️',
      color: '#06B6D4',
      bgGradient: ['#0A1A20', '#05050A'],
      icon: '⚖️',
      svgIcon: 'balance',
      content: "**Homeostasis** is the body's ability to maintain a stable internal environment despite external changes — the key to survival.\n\n**What the body regulates:**\n🌡️ **Temperature** — 37°C (±0.5°C); even 4°C above or below can be fatal\n🔬 **Blood pH** — 7.35-7.45 (slightly alkaline); 0.3 change = coma\n💧 **Water balance** — kidneys filter 180L of blood/day, producing 1.5L urine\n🍬 **Blood glucose** — 80-120 mg/dL\n🧂 **Ion balance** — Na⁺, K⁺, Ca²⁺ controlled precisely\n\n**Negative feedback** is the main mechanism:\nDeviation → Detected by receptor → Control centre (brain/gland) → Effector corrects it → Back to normal ↩️\n\n**Example — temperature:**\nToo hot → Hypothalamus detects → Sweat glands activated + blood vessels dilate → Heat lost → Temperature drops → Sweating stops 🌡️\n\nPerfect balance = health. Homeostasis failure = disease! ⚖️",
      highlight: "Homeostasis keeps body temperature at 37°C and blood pH at 7.4 — even tiny deviations can be life-threatening! ⚖️",
    },
    {
      id: 'excretory',
      title: 'The Excretory System ♻️',
      color: '#FACC15',
      bgGradient: ['#2A2A0A', '#05050A'],
      icon: '♻️',
      svgIcon: 'cycle',
      content: "The **excretory system** removes metabolic waste — things the body makes but can't use:\n\n**Main organs:**\n🫘 **Kidneys** — filter all your blood every 30-40 minutes! Each kidney has ~1 million filtering units called **nephrons**. They remove:\n• Urea (from protein breakdown)\n• Excess water and salts\n• Drug metabolites and toxins\n\n**How nephrons work:**\n1. **Filtration** — blood forced through glomerulus under pressure; everything except blood cells and large proteins filtered out\n2. **Reabsorption** — 99% of the filtered fluid is reabsorbed back into blood (glucose, amino acids, water, salts)\n3. **Secretion** — extra toxins added to filtrate\n4. **Excretion** — final urine collected in renal pelvis → ureter → bladder → expelled\n\n**Other excretory organs:**\n👃 Lungs — remove CO₂ and water vapour\n💧 Skin (sweat glands) — remove water, salts, urea\n🫏 Liver — breaks down old red blood cells and toxins ♻️",
      highlight: "Your kidneys filter all your blood every 30-40 minutes — 1 million nephrons in each kidney working continuously! ♻️",
    },
    {
      id: 'integumentary',
      title: 'Skin — Your Largest Organ 🌡️',
      color: '#F59E0B',
      bgGradient: ['#2A1A0A', '#05050A'],
      icon: '🌡️',
      svgIcon: 'thermometer',
      content: "**Skin** is the body's largest organ by surface area (~2 m²) and accounts for ~16% of body weight.\n\n**Three layers:**\n🟠 **Epidermis** (outer) — dead skin cells (keratinocytes), waterproof; renews every ~28 days; contains melanocytes (skin colour)\n🟡 **Dermis** (middle) — hair follicles, sweat glands, nerve endings, blood vessels, collagen\n🔴 **Hypodermis** (inner) — fat layer for insulation and cushioning\n\n**Functions (SHAPES):**\n🛡️ **S**ensation — temperature, touch, pain, pressure\n🌡️ **H**eat regulation — sweat glands + blood vessel dilation/constriction\n🔒 **A**bsorption barrier — keeps pathogens and toxins out, water in\n🏗️ **P**rotection — physical barrier\n☀️ **E**xcretion — sweat removes waste\n🌞 **S**ynthesis — Vitamin D made when UV hits skin (triggers calcium absorption!)\n\nYour skin sheds ~30,000-40,000 dead skin cells per hour — you replace your entire outer skin layer every month! 🔄",
      highlight: "Skin is your largest organ (2 m²) — it synthesises Vitamin D from sunlight and sheds 30,000 cells per hour! 🌡️",
    },
  ],

  lab: {
    title: "Human Body Control Lab 🫀",
    description: "Adjust heart rate, oxygen levels, nerve speed, and cortisol. Discover how these systems interact in real time!",
    hint: "Try raising heart rate above 170 bpm to trigger the danger response — or push oxygen below 90% to simulate hypoxia! 🫀",
    scientistModeHint: "In Scientist Mode: discover flow states, anaerobic threshold, and athletic bradycardia! 🧑‍🔬",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why your heart rate slows down when you plunge your face in cold water? 🌊",
      answer: "This is the 'diving reflex' — an ancient mammalian survival mechanism. Cold water on your face triggers the vagus nerve (parasympathetic), dramatically slowing your heart and redirecting blood to vital organs. Freediving champions use this reflex to slow their hearts to as low as 7 bpm, massively extending their time underwater! Even splashing cold water on your face can break an anxiety panic attack! 💧",
      emoji: '🌊',
    },
    {
      id: 'dyk2',
      question: "Do you know why your stomach growls when you're hungry? 🍽️",
      answer: "Stomach growling (borborygmi) isn't just from hunger! The digestive muscles contract constantly to move food — but when your stomach is empty, those contractions are audible because air and fluid slosh around inside. Interestingly, your small intestine makes more noise than your stomach. And your gut bacteria produce most of the gas that causes bloating! 🦠",
      emoji: '🍽️',
    },
    {
      id: 'dyk3',
      question: "Do you know why you bruise when you bump yourself? 💙",
      answer: "When a blood vessel breaks under the skin, blood leaks into surrounding tissue. Platelets form a clot to stop the bleeding, but the leaked blood gets trapped. Haemoglobin in the red blood cells breaks down, changing colour through pigments: first red/purple (haemoglobin), then blue/green (biliverdin), then yellow (bilirubin). That colour progression you see IS the body's repair process! 🔧",
      emoji: '💙',
    },
    {
      id: 'dyk4',
      question: "Do you know why you can't tickle yourself? 😂",
      answer: "The cerebellum predicts the sensory signals caused by your own movements and subtracts them from your perception. When YOU tickle yourself, the brain already predicts the sensation and cancels the surprise response. But when someone ELSE tickles you, the sensation is unpredicted — triggering the full tickle laughter reflex! This is why surprise is fundamental to tickling. 😂",
      emoji: '😂',
    },
    {
      id: 'dyk5',
      question: "Do you know why muscles get sore 24 hours AFTER exercise? 💪",
      answer: "This is called DOMS (Delayed Onset Muscle Soreness), and contrary to popular belief, it's NOT caused by lactic acid! Intense exercise causes microscopic tears in muscle fibres. Over the next 24-48 hours, inflammation rushes in — bringing excess fluid, white blood cells, and repair proteins. This inflammatory response causes the soreness. But the rebuilt muscle is thicker and stronger — that's how exercise builds muscle! 🏋️",
      emoji: '💪',
    },
  ],

  quiz: [
    { id: 'q1', question: "How many times does the human heart beat per day on average? 🫀", options: ["10,000 times", "50,000 times", "100,000 times", "500,000 times"], answer: 2, explanation: "At ~72 beats/minute, the heart beats about 100,000 times per day — equalling around 3.7 billion beats in an average lifetime! Each beat pumps about 70ml of blood. 🫀" },
    { id: 'q2', question: "What is the role of alveoli in the respiratory system? 🫁", options: ["Trap pathogens with mucus", "Carry oxygen through blood", "Exchange gases in lungs", "Expand the chest cavity"], answer: 2, explanation: "Alveoli are microscopic balloon-like sacs at the end of bronchioles. Their enormous combined surface area (like a tennis court!) allows rapid diffusion of O₂ into blood and CO₂ out. 🎾" },
    { id: 'q3', question: "What triggers your body to breathe faster? 🌬️", options: ["Low oxygen levels", "High carbon dioxide levels", "Low blood pressure", "High nitrogen levels"], answer: 1, explanation: "Your medulla oblongata monitors CO₂ — not O₂! When CO₂ rises in blood, it triggers breathing to expel it. This is why holding your breath feels like a burning urge — CO₂ is accumulating! 🔥" },
    { id: 'q4', question: "What is homeostasis? ⚖️", options: ["Breaking down cellular sugar", "Maintaining stable internal conditions", "Supporting total body weight", "Producing new blood cells"], answer: 1, explanation: "Homeostasis is the body's extraordinary ability to maintain stable conditions (temperature, pH, blood sugar, water) despite external changes. It's the foundation of all health! ⚖️" },
    { id: 'q5', question: "Which hormone is released during a 'fight-or-flight' response? ⚡", options: ["Insulin", "Thyroxine", "Adrenaline", "Growth hormone"], answer: 2, explanation: "Adrenaline (epinephrine) is released by adrenal glands in response to stress. It raises heart rate, dilates pupils, redirects blood to muscles, and prepares the body for rapid action! ⚡" },
    { id: 'q6', question: "How many bones does an adult human body have? 🦴", options: ["270 bones", "206 bones", "180 bones", "320 bones"], answer: 1, explanation: "Adults have 206 bones — but babies are born with ~270! Many bones fuse during development. The longest bone is the femur (thigh bone); the smallest is the stapes (in the ear). 🦴" },
    { id: 'q7', question: "What is the 'enteric nervous system' often called? 🧠", options: ["The spinal cord", "The second brain", "The autonomic system", "The fight-or-flight network"], answer: 1, explanation: "The gut has its own nervous system of ~500 million neurons — the 'enteric' or 'second brain'. It controls digestion independently and communicates with your actual brain via the vagus nerve! 🧠" },
    { id: 'q8', question: "How often do kidneys filter all the blood in your body? 🫘", options: ["Every 5 minutes", "Every 40 minutes", "Every 2 hours", "Once a day"], answer: 1, explanation: "Your two kidneys filter your entire blood supply every 30-40 minutes! They filter about 180 litres per day, producing about 1.5 litres of urine. Each kidney has about 1 million filtering nephrons! 🫘" },
    { id: 'q9', question: "What is unique about cardiac muscle compared to skeletal muscle? ❤️", options: ["Largest muscle in body", "Self-pacing and never tires", "Only voluntary muscle type", "Functions without using ATP"], answer: 1, explanation: "Cardiac muscle is unique — it has an intrinsic electrical pacemaker (SA node) that keeps it beating automatically. It also has special proteins that make it fatigue-resistant — your heart NEVER takes a break! ❤️" },
    { id: 'q10', question: "What does the skin do when UV light from the sun hits it? ☀️", options: ["Produces melanin for protection", "Synthesizes essential Vitamin D", "Releases histamine into blood", "Produces adrenaline for stress"], answer: 1, explanation: "When UV light hits skin, it triggers the synthesis of Vitamin D — essential for calcium absorption and bone health! This is why sun exposure is important for bone development in children. ☀️" },
    { id: 'q11', question: "Which blood vessel type carries blood AWAY from the heart? 🔴", options: ["Veins", "Capillaries", "Arteries", "Venules"], answer: 2, explanation: "Arteries (A for Away) carry high-pressure oxygenated blood away from the heart. Veins bring deoxygenated blood back. 🔴" },
    { id: 'q12', question: "What is the typical pH of stomach acid (HCl)? 🧪", options: ["pH 7 (Neutral)", "pH 12 (Basic)", "pH 2 (Acidic)", "pH 5 (Weak)"], answer: 2, explanation: "Stomach acid is incredibly potent (pH 1.5 to 3.5) to dissolve proteins and kill bacteria! 🥩" },
    { id: 'q13', question: "Which part of the brain controls automatic functions like breathing and heart rate? 🧠", options: ["Cerebrum", "Cerebellum", "Medulla Oblongata", "Thalamus"], answer: 2, explanation: "The Brainstem is the 'autopilot' center of the brain, keeping you alive without you even thinking about it. 🧠" },
    { id: 'q14', question: "The three types of muscle tissue in the human body are: 💪", options: ["Bone, Skin, Fat", "Skeletal, Cardiac, Smooth", "Long, Short, Round", "Fast, Slow, Medium"], answer: 1, explanation: "Skeletal (voluntary), Cardiac (heart), and Smooth (organs) are the three specialized muscle types. 💪" },
    { id: 'q15', question: "Which gland is considered the 'Master Gland' because it controls many others? 🔬", options: ["Thyroid gland", "Adrenal gland", "Pituitary gland", "Pancreas gland"], answer: 2, explanation: "The Pituitary gland, located at the base of the brain, releases hormones that signal other glands to start or stop production. 🔬" },
    { id: 'q16', question: "Which system is responsible for producing red blood cells? 🦴", options: ["Circulatory system", "Nervous system", "Skeletal system", "Digestive system"], answer: 2, explanation: "Your bones aren't just for support; the red marrow inside produces billions of new blood cells every single day! 🦴" },
    { id: 'q17', question: "What is the wave-like muscular contraction that moves food down the esophagus? 🍎", options: ["Peristalsis", "Gravity", "Digestion", "Diffusion"], answer: 0, explanation: "Peristalsis is so strong that you can actually swallow food while standing on your head! 🤸" },
    { id: 'q18', question: "Which layer of the skin contains most of the nerves, blood vessels, and sweat glands? 🌡️", options: ["Epidermis", "Dermis", "Hypodermis", "Keratin"], answer: 1, explanation: "The Dermis is the 'living' middle layer where all the complex machinery of the skin is located. 🌡️" },
    { id: 'q19', question: "What are the millions of microscopic filtering units in the kidneys called? 🫘", options: ["Neurons", "Alveoli", "Nephrons", "Villi"], answer: 2, explanation: "Nephrons are the workers that filter waste from your blood and decide what to keep and what to flush as urine. 🫘" },
    { id: 'q20', question: "In the lungs, what gas moves FROM the blood INTO the air to be exhaled? 🌬️", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], answer: 2, explanation: "Carbon Dioxide (CO₂) is the waste product of cellular energy production that the lungs dump out into the air. 🌬️" },
  ],

  relatedTopics: ['cell_structure', 'immune_system', 'brain_structure', 'ecosystems'],
};
