// ─────────────────────────────────────────────────────────
//  TOPIC: THE PSYCHOLOGY OF LOVE
//  Category: Personal Development
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'love',
  title: 'The Psychology of Love',
  subtitle: 'The neuroscience of why we fall, and how we stay 💖🔬',
  emoji: '💖',
  category: 'Personal Development',
  accentKey: 'love',

  hook: {
    question: "Why does the intense, dizzying, can't-eat-can't-sleep feeling of falling in love always disappear after 12 to 18 months, no matter who the person is?",
    reveal: "Because 'falling' in love is not a spiritual event; it is a temporary, biological state of extreme intoxication. Nature floods your brain with dopamine and oxytocin to guarantee reproduction. \n\nBut if your brain stayed in that hyper-aroused state permanently, the stress would literally kill you! When the chemical high inevitably crashes, most people think they 'fell out of love'. In reality, that is the exact moment true love finally begins. 🧬💔➡️❤️",
    emoji: '💭',
  },

  theory: [
    {
      id: 'sternberg_triangle',
      title: "Sternberg's Triangular Theory 🔺",
      color: '#EF476F',
      bgGradient: ['#30000A', '#0A0005'],
      icon: 'triangle',
      svgIcon: 'target',
      content: "Psychologist Robert Sternberg proved that Love is not one single emotion, but a recipe made of three distinct ingredients:\n\n1. **Intimacy**: Emotional closeness, vulnerability, and sharing secrets. (The Friendship)\n2. **Passion**: Physical attraction and sexual desire. (The Fire)\n3. **Commitment**: The logical decision to stay together and plan a future. (The Anchor)\n\nDifferent combinations of these three ingredients create drastically different types of relationships.",
      highlight: "A relationship with only Passion is just a crush. A relationship with only Commitment is an empty marriage.",
    },
    {
      id: 'consummate_love',
      title: "Consummate Love 👑",
      color: '#FF007F',
      bgGradient: ['#300015', '#0A0005'],
      icon: 'star',
      svgIcon: 'heart',
      content: "When a relationship contains high levels of ALL THREE ingredients (Intimacy + Passion + Commitment), it forms **Consummate Love**. \n\nThis is the societal ideal we see in movies. However, Sternberg warned that achieving Consummate Love is easier than maintaining it. \nIt is not a permanent state; it is a delicate balancing act. Like a muscle, if you stop intentionally feeding the Passion or Intimacy, it quickly degrades back into 'Companionate Love' (just being roommates).",
      highlight: "Consummate love is a verb, not a noun. It requires daily maintenance. 🛠️",
    },
    {
      id: 'the_honeymoon_phase',
      title: "The Honeymoon Illusion 🧪",
      color: '#FF9F1C',
      bgGradient: ['#301500', '#0A0500'],
      icon: 'zap',
      svgIcon: 'bolt',
      content: "The 'Honeymoon Phase' (Limerence) is biologically identical to a cocaine high. Your brain wildly overproduces Dopamine (craving) and suppresses your Prefrontal Cortex (logic/judgment).\n\nYou biologically CANNOT see your partner's flaws during this phase. You literally hallucinate a perfect human. \n\nThis phase evolved solely to keep humans together long enough to produce an infant. It universally expires between 6 to 18 months. Expect the crash.",
      highlight: "You never know who you are actually dating until the Honeymoon Phase ends. 🎭",
    },
    {
      id: 'attachment_styles',
      title: "Attachment Styles 🧩",
      color: '#00E5FF',
      bgGradient: ['#002025', '#000A0A'],
      icon: 'puzzle',
      svgIcon: 'shield',
      content: "How your parents treated you as a toddler permanently wire-frames how you handle romantic anxiety as an adult:\n\n1. **Secure (50%)**: Comfortable with intimacy and independence.\n2. **Anxious (20%)**: Terrified of abandonment; clings tightly, needs constant reassurance.\n3. **Avoidant (25%)**: Equates intimacy with a loss of freedom; pulls away when things get 'too close'.\n4. **Fearful-Avoidant (5%)**: Craves love but is terrified of it; chaotic push-pull dynamic. ",
      highlight: "The most toxic trap in dating is the 'Anxious-Avoidant Loop'. One chases, the other runs. 🏃‍♂️💨",
    },
    {
      id: 'love_languages',
      title: "The 5 Love Languages 🗣️",
      color: '#D4A74A',
      bgGradient: ['#201500', '#050500'],
      icon: 'message-circle',
      svgIcon: 'users',
      content: "Dr. Gary Chapman discovered that people naturally 'speak' and 'hear' love in five different dialects:\n1. Words of Affirmation\n2. Acts of Service\n3. Receiving Gifts\n4. Quality Time\n5. Physical Touch\n\nThe tragedy of most breakups is that both people were trying to show love, but in a language the other person couldn't understand. (e.g., A husband vacuums the house [Acts of Service], but the wife feels unloved because he didn't hug her [Physical Touch]).",
      highlight: "Stop loving your partner the way YOU want to be loved. Love them the way THEY want it. 🔄",
    },
    {
      id: 'gottman_four_horsemen',
      title: "The Four Horsemen ☠️",
      color: '#9370DB',
      bgGradient: ['#1A0033', '#05000A'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "Dr. John Gottman can predict divorce with 90% accuracy by observing a couple argue for just 5 minutes. He looks for 'The Four Horsemen':\n\n1. **Criticism**: Attacking their character ('You always...').\n2. **Contempt**: Sneering, eye-rolling, acting superior. (The #1 predictor of divorce).\n3. **Defensiveness**: Playing the victim to avoid taking responsibility.\n4. **Stonewalling**: Completely shutting down and ignoring the partner.",
      highlight: "Contempt is psychological poison. If you roll your eyes at your partner, the relationship is dying. ☠️",
    },
    {
      id: 'repair_attempts',
      title: "Repair Attempts 🩹",
      color: '#4ECDC4',
      bgGradient: ['#002020', '#000A0A'],
      icon: 'band-aid',
      svgIcon: 'shield',
      content: "What separates successful couples from divorced ones isn't the absence of fighting. ALL couples fight. \n\nThe difference is the ability to use **Repair Attempts**—a silly joke, a gentle touch, or a soft apology right in the middle of a screaming match to de-escalate the tension. \n\nEmotionally intelligent couples accept each other's repair attempts instead of staying aggressively petty. ",
      highlight: "A fight is just a test of how quickly you can forgive each other. 🕊️",
    },
    {
      id: 'bid_for_connection',
      title: "Bids for Connection 📡",
      color: '#3B82F6',
      bgGradient: ['#001530', '#00050A'],
      icon: 'wifi',
      svgIcon: 'chart',
      content: "A 'Bid' is any tiny attempt to connect. E.g., Your partner points out the window and says, 'Wow, look at that bird!'\n\nYou have 3 options:\n• **Turn Toward**: 'Oh yeah, what kind is it?' (Builds trust)\n• **Turn Away**: You ignore them and keep scrolling your phone. (Kills trust)\n• **Turn Against**: 'Can't you see I'm busy!?' (Causes trauma)\n\nMaster couples 'Turn Toward' their partner's bids 86% of the time. Divorced couples only did it 33% of the time.",
      highlight: "Love is not grand gestures. Love is answering thousands of tiny, boring bids for attention. 🧱",
    },
    {
      id: 'projection',
      title: "Psychological Projection 🪞",
      color: '#F472B6',
      bgGradient: ['#2A0A1A', '#0A0005'],
      icon: 'sun',
      svgIcon: 'eye',
      content: "In the early stages of love, we don't actually see the other person. We project our own deepest unmet childhood needs onto them, expecting them to be our 'Savior'.\n\nWhen they inevitably fail to read your mind or heal your trauma, you become furious and resentful. But they didn't change! You just finally stopped projecting a fantasy and started seeing a flawed human being.",
      highlight: "Your partner's job is not to fix your childhood trauma. That is your job. 🪞",
    },
    {
      id: 'vulnerability',
      title: "The Vulnerability Paradox 🛡️",
      color: '#8B5CF6',
      bgGradient: ['#150025', '#05000A'],
      icon: 'unlock',
      svgIcon: 'heart',
      content: "We wear 'armor' (acting stoic, rich, or cool) to make people like us. But armor prevents actual connection.\n\nBrene Brown discovered the Vulnerability Paradox: **We are drawn to vulnerability in others, but terrified to show it in ourselves.** \n\nTrue Intimacy (the first pillar of Sternberg's Triangle) is mathematically impossible without vulnerability. You cannot be truly loved unless you allow yourself to be truly seen—flaws, fears, and all.",
      highlight: "If you never risk getting hurt, you will never experience true love. 🎲",
    },
    {
      id: '50_50_myth',
      title: "The 50/50 Myth ⚖️",
      color: '#F59E0B',
      bgGradient: ['#251500', '#0A0500'],
      icon: 'balance',
      svgIcon: 'grid',
      content: "Modern society tells us relationships should be a perfectly equal 50/50 split. This is incredibly toxic because it turns love into a transactional spreadsheet.\n\nHealthy relationships are almost never 50/50 on a given day. Sometimes her mother dies, and it's 90/10. Sometimes he loses his job, and it's 10/90. \n\nThe goal isn't daily equality; the goal is pulling the collective wagon together, trusting that the other person will carry the weight when you stumble.",
      highlight: "Keeping a mental 'scorecard' of who did the dishes last will eventually destroy a marriage. 📝",
    },
    {
      id: 'oxytocin',
      title: "Oxytocin and Bonding 🧪",
      color: '#10B981',
      bgGradient: ['#052510', '#000A05'],
      icon: 'droplet',
      svgIcon: 'star',
      content: "While Dopamine creates the frantic, obsessive 'chase' of early love, **Oxytocin** is the 'cuddle hormone' that creates deep, peaceful, long-term bonding. \n\nOxytocin is released during physical touch, hugs (longer than 20 seconds), and orgasm. \nThis is why having physical intimacy too early with someone highly toxic can trap you! Your brain literally chemically bonds to them before your logic can identify all the red flags.",
      highlight: "Your brain's chemistry does not care about background checks. It bonds via touch. 🫂",
    },
    {
      id: 'distance',
      title: "The Power of Distance 🌌",
      color: '#F87171',
      bgGradient: ['#250505', '#0A0000'],
      icon: 'moon',
      svgIcon: 'planet',
      content: "Esther Perel asks: 'If we want closeness, why does physical closeness eventually kill sexual desire?'\n\nBecause Desire (Passion) requires **Space**. Fire needs oxygen! You cannot 'want' something you already possess 24/7. \nTo keep passion alive in a long-term marriage, you must maintain separate identities, hobbies, and a healthy degree of mystery. When you see your partner shining in *their* element from a distance, desire re-ignites.",
      highlight: "Smothering someone with constant closeness creates a roommate, not a lover. Give them space to miss you. 🌬️",
    },
    {
      id: 'choice_paralysis',
      title: "The Paradox of Choice 📱",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#000010'],
      icon: 'smartphone',
      svgIcon: 'lock',
      content: "Dating apps present an illusion of infinite choice. Swiping past 5,000 faces tricks the brain into thinking the 'perfect, flawless soulmate' is just one swipe away.\n\nThis leads to **Choice Paralysis** and 'Maximizing' behavior—the second your current partner does something mildly annoying, you dump them because 'there must be someone better.'\n\nThere is no flawless soulmate. Every relationship requires putting up with a specific set of unresolvable flaws.",
      highlight: "Dating apps optimize for endless swiping, not for finding peace. 🛑",
    },
    {
      id: 'purpose_of_marriage',
      title: "The Crucible of Growth 🌋",
      color: '#EC4899',
      bgGradient: ['#2A0515', '#0A0005'],
      icon: 'flame',
      svgIcon: 'zap',
      content: "Despite what Disney taught us, the goal of a long-term relationship is NOT simply to 'make you happy'. \n\nA great relationship is a mirror holding up all your deepest insecurities, selfish tendencies, and ego.\nThe true purpose of lifelong commitment is a crucible for extreme psychological growth. It forces you to learn patience, compromise, and selflessness—qualities you would never develop if you stayed comfortably alone.",
      highlight: "Love is not a cozy blanket; it is a fire that burns away your selfishness. 🔥",
    },
  ],

  lab: {
    title: "The Relationship Ecosystem ⚖️💞",
    description: "You just started dating! Time is ticking. Balance Intimacy, Passion, and Commitment. Handle random 'Life Stressors' (Arguments, Work Stress). If the 'Breakup Score' hits 100%, it's over! Survive 24 months to reach true 'Consummate Love'.",
    hint: "Neglecting the relationship to focus heavily on solving 'Work Stress' will kill Intimacy. If Passion drops to 0, you become 'just roommates' and the breakup score spikes!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Oxytocin decay rates, secure/anxious attachment bias coefficients, and the Gottman separation probability.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why heartbreak literally causes physical pain in your chest? 💔", answer: "Functional MRI scans show that social rejection and romantic heartbreak activate the exact same regions in the brain (anterior cingulate cortex) as physical bodily injury! Tylenol has actually been shown to slightly reduce the emotional pain of a breakup. 💊", emoji: '🧠' },
    { id: 'dyk2', question: "Do you know why we often attract partners similar to our parents? 👨‍👩‍👧", answer: "Our brains crave familiarity over happiness. If you had a chaotic, emotionally unavailable parent, a stable and boring partner feels 'wrong' to your brain. You subconsciously seek out toxic, unavailable people because your brain knows how to navigate that specific trauma playbook. 🎭", emoji: '🔄' },
    { id: 'dyk3', question: "Do you know why doing something scary together makes you fall in love faster? 🎢", answer: "Misattribution of Arousal! If you go on a rollercoaster on a first date, your adrenaline spikes and your heart races from fear. Your brain misinterprets this physical 'Fear' arousal as intense 'Sexual/Romantic' attraction toward the person sitting next to you! ⚡", emoji: '😱' },
    { id: 'dyk4', question: "Do you know why 'Opposites Attract' usually ends in disaster? 🧲", answer: "Opposites attract initially because they provide the missing pieces to our own psyche (a messy person loves an organized person). But over years, the exact trait that attracted them becomes the exact thing they despise ('You are too rigid!'). Shared core values predict long-term success much better. 🧭", emoji: '⚖️' },
    { id: 'dyk5', question: "Do you know why long-distance relationships feel so incredibly passionate? ✈️", answer: "Because it completely artificially inflates 'Passion' via the mechanism of extreme separation. You never have to deal with the boring, ugly reality of their daily habits. It is a fantasy bubble of intense weekends, stripped of the mundane responsibilities that slowly erode romance. 🫧", emoji: '🌍' },
    { id: 'dyk6', question: "Do you know why the 7-Year Itch is biologically real? 📅", answer: "Anthropologist Helen Fisher theorizes that human pair-bonding evolved to last approximately 4 years—just long enough for a female to raise an infant through the most vulnerable stage before the male's biological imperative pushes him to seek genetic diversity. We are fighting our own evolutionary hardware! 🧬", emoji: '🐒' },
    { id: 'dyk7', question: "Do you know why men fall in love faster than women? 🕒", answer: "Despite stereotypes, multiple studies show men report feelings of love and say 'I love you' an average of 42 days earlier than women. Evolutionarily, women bear the massive biological cost of pregnancy (9 months + risk of death), so their hardware is wired to evaluate potential mates much more slowly and skeptically. ⏳", emoji: '🧬' },
    { id: 'dyk8', question: "Do you know why pupil dilation is the ultimate non-verbal sign of attraction? 👁️", answer: "You cannot consciously control your pupils. When the brain sees something it desires (or wants to take in more information about), the sympathetic nervous system forcibly dilates the pupils. Subconsciously, humans rate photos of people with dilated pupils as significantly more attractive! ✨", emoji: '🧠' },
    { id: 'dyk9', question: "Do you know why we close our eyes when we kiss? 💋", answer: "The brain cannot fully process highly intense sensory data from multiple channels at once. To maximize the intense tactile pleasure of the lips and the rush of oxytocin, the brain forcibly shuts off the visual cortex to dedicate all computing power to the physical touch! 💻", emoji: '🙈' },
    { id: 'dyk10', question: "Do you know why couples start to visually look like each other after 25 years? 👴👵", answer: "Empathic Mimicry. Over decades, emotionally attuned couples constantly mirror each other's facial expressions (smiling at the same jokes, frowning at the same stress). This repeated mimicking causes them to develop identical facial wrinkles and muscle structures! 🎭", emoji: '🪞' },
  ],

  quiz: [
    { id: 'q1', question: "According to Sternberg, a relationship with ONLY Passion (and no intimacy or commitment) is categorized as:", options: ['Consummate Love', 'Companionate Love', 'Empty Love', 'Infatuation / Crush'], answer: 3, explanation: "Passion without friendship or an anchor is just a temporary chemical fire. 🔥" },
    { id: 'q2', question: "The intense 'Honeymoon Phase' is biologically designed to last:", options: ['Forever, if it is true love', '6 to 18 months', '5 years', 'Until marriage'], answer: 1, explanation: "It is a temporary state of chemical intoxication strictly designed to encourage reproduction. 🧬" },
    { id: 'q3', question: "In attachment theory, someone who desperately craves love but clings too tightly and needs constant reassurance is:", options: ['Secure', 'Fearful-Avoidant', 'Anxious', 'Dismissive'], answer: 2, explanation: "Anxious attachers are terrified of abandonment and often accidentally push their partner away by suffocating them. 🏃‍♂️" },
    { id: 'q4', question: "If a husband shows love by washing the wife's car (Acts of Service), but the wife feels unloved because he rarely hugs her, what is the core issue?", options: ['He does not love her', 'She is ungrateful', 'They are speaking different Love Languages', 'The car didn\'t need washing'], answer: 2, explanation: "We natively speak the language WE want to receive. We must learn to speak our partner's native language. 🗣️" },
    { id: 'q5', question: "According to Dr. John Gottman, what is the absolute #1 predictor of a future divorce?", options: ['Arguing too much', 'Not having enough money', 'Contempt (eye-rolling, disgust, superiority)', 'Different political views'], answer: 2, explanation: "Contempt implies you view your partner as inferior. It is psychological acid to a bond. ☠️" },
    { id: 'q6', question: "What is a 'Repair Attempt' during a fight?", options: ['Calling a therapist', 'A small gesture (a joke, an apology) made mid-fight to de-escalate tension and prevent nuclear war', 'Buying an expensive gift afterward', 'Winning the argument logically'], answer: 1, explanation: "Master couples never fight perfectly, they just repair quickly before lasting damage is done! 🩹" },
    { id: 'q7', question: "If your partner points at a bird and you ignore them to look at your phone, you just:", options: ['Turned Away from a Bid for Connection', 'Established boundaries', 'Saved time', 'Demonstrated Secure Attachment'], answer: 0, explanation: "Ignoring small, boring bids destroys trust over years by communicating 'You do not matter to me right now'. 📡" },
    { id: 'q8', question: "Dr. Brene Brown's 'Vulnerability Paradox' states that:", options: ['Showing weakness gets you fired', 'We are drawn to vulnerability in others, but terrified to show it in ourselves', 'Armor makes you stronger', 'Vulnerability is dangerous'], answer: 1, explanation: "We want to see our partner's true soul, but we are too cowardly to show them our own flaws. 🛡️" },
    { id: 'q9', question: "Why is the idea that a relationship should be perfectly '50/50' toxic?", options: ['Math is hard', 'It makes you keep a mental scorecard, trapping you in a transactional, petty mindset', 'It should be 80/20', 'Women should do more'], answer: 1, explanation: "A relationship is a partnership of trust, where you pull 90% of the weight on the days your partner only has 10% to give. ⚖️" },
    { id: 'q10', question: "What hormone is released during a 20-second hug and causes deep, long-term pair bonding?", options: ['Adrenaline', 'Cortisol', 'Oxytocin', 'Insulin'], answer: 2, explanation: "Oxytocin literally socially glues your brain to another human being through physical touch. 🫂" },
    { id: 'q11', question: "Esther Perel argues that to keep 'Passion' (Desire) alive in a long-term marriage, you MUST maintain:", options: ['A shared bank account', 'Constant unbreaking physical closeness', 'Space, distance, and mystery', 'The exact same hobbies'], answer: 2, explanation: "Fire needs oxygen. You cannot deeply 'desire' someone you possess entirely 24/7. Let them cultivate their own garden. 🌌" },
    { id: 'q12', question: "Dating apps biologically cause 'Choice Paralysis' because:", options: ['The apps crash frequently', 'The illusion of infinite choice makes the brain hold out for a flawless \'perfect\' person who does not exist', 'Swiping burns calories', 'They cost money'], answer: 1, explanation: "Endless options destroy our ability to commit to normal, flawed human beings. 📱" },
    { id: 'q13', question: "Romantic heartbreak feels like physical chest pain because:", options: ['You ate something bad', 'Emotional rejection and physical injury activate the exact same pain centers in the brain', 'The heart muscle tears', 'A drop in oxygen'], answer: 1, explanation: "To our tribal ancestors, social rejection meant death by starvation, so the brain treats it like an extreme physical injury! 💔" },
    { id: 'q14', question: "Taking a first date to a scary horror movie often creates attraction due to:", options: ['The dark room', 'Misattribution of Arousal (brain confuses fear-adrenaline for sexual attraction)', 'The popcorn', 'The actors in the movie'], answer: 1, explanation: "A racing heart from fear feels remarkably similar to a racing heart from lust! 🎢" },
    { id: 'q15', question: "Why do we subconsciously seek out toxic partners deeply similar to our abusive/unavailable parents?", options: ['Because bad boys are fun', 'Because the brain prefers familiarity (known trauma) over the terrifying uncertainty of a healthy dynamic', 'Coincidence', 'It builds character'], answer: 1, explanation: "You accept the love you think you deserve, based strictly on the love you received as a toddler. 👨‍👩‍👧" },
    { id: 'q16', question: "In Sternberg's theory, an arranged marriage often starts as:", options: ['Empty Love (Only Commitment)', 'Fatuous Love', 'Consummate Love', 'Romantic Love'], answer: 0, explanation: "They start with the Anchor (Commitment) and hope the Fire (Passion) and Friendship (Intimacy) grow over time. ⚓" },
    { id: 'q17', question: "Psychological 'Projection' during a new relationship means:", options: ['Going to a movie theater', 'We project a fantasy of our perfect Savior onto a flawed human, then get mad when they act human', 'Talking loudly', 'Showing them photos'], answer: 1, explanation: "You fall in love with the fantasy in your head, not the actual person sitting across from you. 🪞" },
    { id: 'q18', question: "Which is biologically true regarding gender and falling in love?", options: ['Women fall in love instantly', 'Men and women fall in love at the exact same second', 'Men report falling in love 42 days faster than women do on average', 'Men cannot feel love'], answer: 2, explanation: "Because pregnancy carries an extreme biological cost for females, their software requires more time to evaluate a threat/mate. 🕒" },
    { id: 'q19', question: "What is 'Stonewalling' (One of the Four Horsemen)?", options: ['Building a house together', 'Completely shutting down, going silent, and ignoring your partner during a conflict', 'Throwing rocks', 'Crying loudly'], answer: 1, explanation: "Stonewalling physically overwhelms the partner, making resolution impossible. 🧱" },
    { id: 'q20', question: "Instead of just 'being happy', the true psychological purpose of a lifelong marriage is:", options: ['Tax benefits', 'To serve as a ruthless crucible for extreme psychological growth, destroying your selfishness', 'To have a roommate', 'To prove your friends wrong'], answer: 1, explanation: "Marriage forces you to confront every ugly, selfish part of your ego that you could easily hide while single. 🌋" },
  ],

  relatedTopics: ['cognitive_biases', 'social_media_trap', 'memory_how_it_works'],
};
