// ─────────────────────────────────────────────────────────
//  TOPIC: STOICHIOMETRY - THE MATH OF CHEMISTRY
//  Category: Chemistry / Foundations
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'stoichiometry',
  title: 'Stoichiometry',
  subtitle: 'The perfect recipe for chemistry ⚖️🧪',
  emoji: '⚖️',
  category: 'Chemistry',
  accentKey: 'stoichiometry',

  hook: {
    question: "If you want to build exactly 100 cars, you know you need exactly 400 tires. But how do chemists know exactly how many billions of oxygen atoms they need to burn a single drop of fuel? ⛽",
    reveal: "They use **Stoichiometry**! It sounds like a scary word, but it's just 'Chemistry Math.' It allows scientists to count atoms by weighing them. Without it, we couldn't make medicine that works, rockets that reach the moon, or even bake a perfect cake. Let's learn to speak the language of quantities! 🧮",
    emoji: '🛰️',
  },

  theory: [
    {
      id: 'what_is_mole',
      title: 'The Mole: A Giant Dozen 🥑',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🥑',
      svgIcon: 'atom',
      content: "Atoms are too tiny to count one by one. If you tried to count the atoms in a glass of water, it would take you quadrillions of years! ⏳\n\nSo, chemists use a giant unit called the **Mole**. Just like a 'dozen' means 12, a 'mole' means **$6.022 \times 10^{23}$**. That is a 6 followed by 23 zeros!\n\nThis number is called **Avogadro's Number**. It is so large that if you had a mole of basketballs, they would create a new planet the size of the Earth! 🏀🌍",
      highlight: "A mole is the bridge that lets us talk about trillions of atoms as a single easy number. 🌉",
    },
    {
      id: 'molar_mass',
      title: 'Molar Mass: The Weight Link ⚖️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'target',
      content: "How do we 'count' a mole of atoms? We weigh them! \n\nThe Periodic Table gives us the **Atomic Mass**. For example, Carbon's mass is 12.01. This means that exactly 12.01 grams of Carbon contains exactly one mole ($6.022 \times 10^{23}$) of atoms! 💎\n\nThis is the secret key of chemistry: **Grams $\\leftrightarrow$ Moles $\\leftrightarrow$ Particles**. If you know the weight, you know the count. It's like knowing that a bag of 100 pennies always weighs exactly 250 grams! 💰",
      highlight: "Atomic mass in grams = 1 mole of that element. 🔑",
    },
    {
      id: 'balanced_equations',
      title: 'Balancing the Recipe 🍳',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🍳',
      svgIcon: 'grid',
      content: "A chemical equation is a recipe. For example: \n**$2H_2 + O_2 \\rightarrow 2H_2O$**\n\nThe numbers in front (coefficients) tell us the **Mole Ratio**. This recipe says: 'For every 2 moles of Hydrogen, you need exactly 1 mole of Oxygen to make 2 moles of Water.' 💧\n\nAtoms cannot be created or destroyed (Law of Conservation of Mass). If you start with 4 Hydrogen atoms, you MUST end with 4 Hydrogen atoms, even if they are now part of a water molecule! ⚖️",
      highlight: "Equations must be balanced because nature never loses an atom! 🔍",
    },
    {
      id: 'mole_ratios',
      title: 'Mole Ratios: The Conversion 🔄',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔄',
      svgIcon: 'waves',
      content: "Mole ratios are the most important tools in stoichiometry. They act as a 'currency exchange' between different chemicals 💹.\n\nIn the water recipe ($2H_2 : 1O_2$), if you have 10 moles of Hydrogen, you can use the ratio to figure out you need 5 moles of Oxygen. \n\nIt works just like a kitchen: If 1 cake needs 3 eggs, then 4 cakes need 12 eggs. Stoichiometry is just 'Mole Kitchen Math'! 🍰",
      highlight: "Ratios allow us to predict how much of one chemical reacts with another. 📈",
    },
    {
      id: 'limiting_reactants',
      title: 'Limiting Reactants 🛑',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🛑',
      svgIcon: 'zap',
      content: "In the real world, you rarely have the perfect amount of everything. One ingredient usually runs out first. This is the **Limiting Reactant**.\n\nImagine you have 10 slices of bread but only 2 slices of cheese. You can only make 2 cheese sandwiches 🥪. The cheese 'limits' how many sandwiches you can make, and you'll have 'excess' bread left over.\n\nIn a rocket engine, if the fuel runs out before the oxygen, the fuel is the Limiting Reactant. The reaction stops the moment the limiter is gone! 🚀",
      highlight: "The limiting reactant determines exactly how much product you can possibly make. 🏁",
    },
    {
      id: 'theoretical_yield',
      title: 'Theoretical vs Actual Yield 📈',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '📈',
      svgIcon: 'star',
      content: "**Theoretical Yield** is the 'Perfect World' answer. It's the maximum amount of product you can make according to your math 📝.\n\n**Actual Yield** is what you *actually* get in the lab. In reality, some chemicals stick to the beaker, some spill, or some don't react fully 🧪.\n\n**Percent Yield = (Actual / Theoretical) × 100%**. \nIf your math says you should get 100g but you only get 90g, your Percent Yield is 90%. In professional drug manufacturing, even a 1% loss can cost millions of dollars! 💸",
      highlight: "Math gives the goal; the lab gives the reality. 🎯",
    },
    {
      id: 'concentration_molarity',
      title: 'Molarity: Strength in Liquid 🧪',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🧪',
      svgIcon: 'beaker',
      content: "Most chemistry happens in liquids (solutions). To do stoichiometry there, we need **Molarity (M)**.\n\nMolarity is a measure of concentration: **Moles of stuff / Liters of liquid** 💧.\n\nIf you have '1 Molar' salt water, it means there is exactly 1 mole of salt dissolved in every 1 liter of water. Knowing the Molarity allows chemists to 'pour out' a specific number of atoms just by measuring the volume! 📏",
      highlight: "Molarity is the bridge between volume and moles. 🌊",
    },
    {
      id: 'gas_stoich',
      title: 'Gases: The Volume Link 🎈',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎈',
      svgIcon: 'cloud',
      content: "Gases are even easier to count! Amadeo Avogadro discovered that at the same temperature and pressure, equal volumes of gases contain the **same number of particles** 💨.\n\nAt Standard Temperature and Pressure (STP), exactly **22.4 liters** of ANY gas (Oxygen, Hydrogen, Helium) contains exactly **1 mole** of particles. \n\nThis means a balloon the size of a microwave holds about 1 mole of air! 🎈",
      highlight: "For gases, volume is a direct shortcut to moles. ⚡",
    },
    {
      id: 'empirical_formulas',
      title: 'Empirical Formulas: The Blueprint 🏗️',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'book',
      content: "Sometimes chemists find a mysterious white powder and need to know what it is. They perform 'Elemental Analysis' to find the percentage of each atom 🔬.\n\nBy using stoichiometry in reverse, they can find the **Empirical Formula**—the simplest whole-number ratio of atoms in a compound. \n\nFor example, Glucose ($C_6H_{12}O_6$) has an empirical formula of $CH_2O$ (a 1:2:1 ratio). It's the basic 'ID card' for a chemical's structure. 🆔",
      highlight: "Stoichiometry is the tool used to discover the formulas of new chemicals! 🧩",
    },
    {
      id: 'space_stoich',
      title: 'Stoichiometry in the Stars 🌌',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🚀',
      svgIcon: 'rocket',
      content: "Stoichiometry is a life-or-death matter in space travel. \n\nOn the ISS, 'Scrubbers' use Lithium Hydroxide to remove $CO_2$ from the air 💨. If the astronauts produce more $CO_2$ than the scrubbers can handle (based on mole counts), the air becomes toxic.\n\nEngineers must calculate the EXACT amount of fuel and oxygen to bring. Too little, and you don't reach orbit. Too much, and the rocket is too heavy to lift off! Everything in aerospace is balanced on a stoichiometric scale. ⚖️",
      highlight: "Precision math is the only thing keeping astronauts breathing and rockets flying. 🛰️",
    },
  ],

  lab: {
    title: "The Precision Reaction Lab 🧪",
    description: "Design the perfect water-making reaction! Use sliders to add Hydrogen and Oxygen gas to the chamber. Watch the mole counts update in real-time, and 'Ignite' to see your Percent Yield. Can you reach a perfect 100% with no limiting reactants left over? ⚖️",
    hint: "Remember the water recipe: 2 parts Hydrogen for every 1 part Oxygen. If you see 'Excess' particles after an explosion, you had a Limiting Reactant! Switch to Scientist Mode to see Molar Mass calculations.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks real-time Grams to Moles conversion ($n=m/M$) and Avogadro count displays.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we use 'Avogadro's Number' instead of just counting millions? 🥑",
      answer: "Because it's a 'Link'! This specific number ($6.022 \\times 10^{23}$) was chosen because it makes the mass on the periodic table (which is in atomic mass units) exactly equal to grams! Without this number, we'd have to use crazy conversion factors every time we used a scale. It's the 'Universal Translator' of chemistry! 📈",
      emoji: '🥑',
    },
    {
      id: 'dyk2',
      question: "Do you know why car Airbags are a miracle of stoichiometry? 🚗💥",
      answer: "Inside an airbag is Sodium Azide ($NaN_3$). When you crash, a sensor triggers a reaction that turns that solid powder into Nitrogen gas. Stoichiometry is used to calculate the EXACT amount of powder needed to fill the bag's volume perfectly in milliseconds—too much and the bag explodes; too little and it's too soft! ⚡",
      emoji: '🎈',
    },
    {
      id: 'dyk3',
      question: "Do you know why you can't just 'double a recipe' in chemistry without care? 🌡️",
      answer: "Energy! Every mole of a reaction releases or absorbs a specific amount of heat. If you double the moles in a test tube, you double the heat produced. If you aren't careful, the 'Stoichiometry of Energy' can turn a safe experiment into a molten explosion! 💥",
      emoji: '🔥',
    },
    {
      id: 'dyk4',
      question: "Do you know why iron rusts faster near the ocean? 🌊",
      answer: "It's an 'Electrochemical Stoichiometry' problem! Salt acts as a catalyst, making the electron transfer from Iron to Oxygen much faster. The 'yield' of rust ($Fe_2O_3$) increases because the salt provides a highway for the atoms to meet and react more efficiently! 🦀",
      emoji: '🏗️',
    },
    {
      id: 'dyk5',
      question: "Do you know why humans breathe out Carbon Dioxide ($CO_2$)? 😤",
      answer: "Biological Stoichiometry! For every 1 mole of Glucose ($C_6H_{12}O_6$) your cells 'burn' for energy, your body must intake 6 moles of Oxygen and produces exactly 6 moles of $CO_2$ as waste. You are a walking chemical equation! 👟",
      emoji: '🧬',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is 'Avogadro's Number'?", options: ['6.022 x 10^12', '6.022 x 10^23', '3.14 x 10^23', 'Exactly 1 billion'], answer: 1, explanation: "This is the number of particles in exactly one mole of any substance! 🥑" },
    { id: 'q2', question: "What is the GIANT unit chemists use to group atoms together for counting?", options: ['The Dozen', 'The Mole', 'The Gram', 'The Liter'], answer: 1, explanation: "Just like 12 = dozen, 6.022 x 10^23 = 1 mole! 🧪" },
    { id: 'q3', question: "If the molar mass of Carbon is 12g, how many atoms are in exactly 12g of Carbon?", options: ['12 atoms', '1 million atoms', '6.022 x 10^23 atoms', 'Zero'], answer: 2, explanation: "12g is one mole of Carbon, so it contains Avogadro's number of atoms! 💎" },
    { id: 'q4', question: "In the equation 2H₂ + O₂ → 2H₂O, what is the mole ratio of H₂ to O₂?", options: ['1:1', '2:1', '1:2', '2:2'], answer: 1, explanation: "The coefficients tell the ratio: 2 H₂ for every 1 O₂! ⚖️" },
    { id: 'q5', question: "What happens to the 'Limiting Reactant' in a reaction?", options: ['It is never used', 'It is the leftover amount', 'It is completely used up first', 'It makes the reaction faster'], answer: 2, explanation: "Like the cheese in a 2-slice sandwich, the limiting reactant stops the show! 🛑" },
    { id: 'q6', question: "What is 'Theoretical Yield'?", options: ['What you get in the lab', 'The maximum amount of product calculated using math', 'A type of gas', 'The weight of a beaker'], answer: 1, explanation: "It is the perfect 'on-paper' result of your stoichiometry math! 📝" },
    { id: 'q7', question: "If you calculate you should get 10g but you only get 8g in the lab, what is your Percent Yield?", options: ['10%', '8%', '80%', '125%'], answer: 2, explanation: "(Actual 8 / Theoretical 10) x 100 = 80%! 📈" },
    { id: 'q8', question: "Molarity is a measure of concentration defined as:", options: ['Grams per Liter', 'Moles per Liter', 'Atoms per Gram', 'Liters per Mole'], answer: 1, explanation: "Molarity (M) tells you how 'crowded' the molecules are in a liquid! 🧪" },
    { id: 'q9', question: "At Standard Temperature and Pressure (STP), 1 mole of ANY gas occupies how much volume?", options: ['1 Liter', '22.4 Liters', '100 Liters', '6.022 Liters'], answer: 1, explanation: "This is a convenient 'gas shortcut' discovered by Avogadro! 🎈" },
    { id: 'q10', question: "The Law of Conservation of Mass states that atoms in a reaction cannot be:", options: ['Liquid', 'Moved', 'Created or Destroyed', 'Counted'], answer: 2, explanation: "This is why we MUST balance chemical equations! ⚖️" },
    { id: 'q11', question: "What is an 'Empirical Formula'?", options: ['The name of the scientist', 'The simplest whole-number ratio of atoms in a compound', 'The exact weight of a molecule', 'A fake formula'], answer: 1, explanation: "It gives the basic blueprint of a substance's identity! 🏗️" },
    { id: 'q12', question: "Stoichiometry is crucial for NASA because they must calculate the exact ratio of:", options: ['Astronauts to food', 'Fuel to Oxygen (Oxidizer)', 'Radio signals to Earth', 'Stars to planets'], answer: 1, explanation: "Without the perfect stoichiometric ratio, a rocket won't have the thrust to reach orbit! 🚀" },
    { id: 'q13', question: "Why does the Percent Yield matter in a medicine factory?", options: ['It tells the color of pills', 'It measures efficiency and potential waste/loss', 'It makes the pills taste better', 'It isn\'t important'], answer: 1, explanation: "High yield means less waste and lower costs for life-saving drugs! 💊" },
    { id: 'q14', question: "Which value from the Periodic Table is used as the 'Number of Grams in 1 Mole'?", options: ['Atomic Number', 'Atomic Mass', 'Group Number', 'The Symbol'], answer: 1, explanation: "Atomic mass is the bridge between the subatomic and our scales! ⚖️" },
    { id: 'q15', question: "If you have 4 moles of H₂ and 10 moles of O₂, which is the Limiting Reactant for making water (2H₂ + O₂ → 2H₂O)?", options: ['H₂', 'O₂', 'Water', 'Both'], answer: 0, explanation: "You need 2 H₂ for every 1 O₂. 4 H₂ only needs 2 O₂. Since you have 10 O₂, the O₂ is in excess and H₂ runs out first! 🛑" },
    { id: 'q16', question: "Avogadro's Number is approximately:", options: ['6.022 x 10^23', '6.022 x 10^-23', '3 x 10^8', '9.8'], answer: 0, explanation: "A massive number for a massive amount of tiny particles! 🥑" },
    { id: 'q17', question: "In a 'Solution', the substance being dissolved is called the:", options: ['Solvent', 'Solute', 'Molarity', 'Residue'], answer: 1, explanation: "The solute is the 'stuff' you are counting in moles! 🧪" },
    { id: 'q18', question: "Why do we balance equations by changing coefficients and NOT subscripts?", options: ['Subscripts are easier', 'Changing subscripts changes the identity of the chemical', 'Coefficients are prettier', 'There is no reason'], answer: 1, explanation: "Changing H₂O to H₂O₂ turns water into hydrogen peroxide—a very different (and dangerous) substance! ⚠️" },
    { id: 'q19', question: "If you have 2 moles of O₂, how many Liters would that occupy at STP?", options: ['22.4 L', '44.8 L', '11.2 L', '6.022 L'], answer: 1, explanation: "2 moles x 22.4 L/mole = 44.8 Liters! 🎈" },
    { id: 'q20', question: "Stoichiometry comes from the Greek words 'stoicheion' and 'metron', meaning:", options: ['Fire and Measure', 'Element and Measure', 'Atom and Math', 'Secret and Count'], answer: 1, explanation: "It literally translates to 'The measurement of elements'! 📏" },
  ],

  relatedTopics: ['atoms_molecules', 'chemical_reactions', 'matter_states'],
};
