// ─────────────────────────────────────────────────────────
//  TOPIC: PHYSICS MASTER LAB (Unified Engineering)
//  Category: Physics
//  Standard: v2.0 Extreme (Unified Lab Suite)
// ─────────────────────────────────────────────────────────

export default {
  id: 'physics_multi_lab',
  title: 'Physics Master Lab',
  subtitle: 'The ultimate sanctuary for laws of the universe 🌌⚙️',
  emoji: '⚛️',
  category: 'Physics',
  accentKey: 'physics',

  hook: {
    question: "Is there a single set of rules that governs everything from the hum of a bee's wing to the explosion of a star? 🔊💥",
    reveal: "Yes! Beneath the chaos of the world lie the elegant mathematical laws of Physics. Whether it's light bending through a prism, heat driving an engine, or a ball thrown in zero-g, everything follows predictable patterns. Welcome to the Master Lab, where you control the core variables of reality itself! 🛠️🔬",
    emoji: '🧪',
  },

  theory: [
    {
      id: 'unified_physics',
      title: 'The Unified Language 🔢',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔢',
      svgIcon: 'activity',
      content: "Physics isn't a collection of random facts; it's a unified language of math. Energy isn't created or destroyed—it just changes hats! \n\nIn this Master Lab, we explore 5 pillars of the physical world: \n1. **Optics** (Light behavior)\n2. **Acoustics** (Sound & Waves)\n3. **Thermodynamics** (Heat & Energy)\n4. **Mechanics** (Work & Power)\n5. **Dynamics** (Gravity & Motion).",
      highlight: "Change one variable, and the whole universe reacts. 🌎",
    },
    {
      id: 'the_critical_angle',
      title: 'Optics: The Critical Angle 🌈',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌈',
      svgIcon: 'search',
      content: "When light travels from glass to air, it usually bends (refraction). But at a specific angle—the **Critical Angle** (about 42°)—the light stops escaping and reflects back perfectly inside the glass! \n\nThis is called **Total Internal Reflection**. It's the reason diamonds sparkle so intensely and how fiber-optic cables carry high-speed internet across the ocean! 💎🌐",
      highlight: "Light can be trapped inside a transparent material simply by its angle. 📐",
    },
    {
      id: 'resonance_power',
      title: 'Acoustics: Resonance 🔊',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🔊',
      svgIcon: 'waves',
      content: "Every object has a 'Natural Frequency' it likes to vibrate at. If you hit it with energy at that exact frequency, you cause **Resonance**. \n\nThe amplitude of the vibration explodes. This is how opera singers break wine glasses, and how a small wind can collapse a giant bridge if it hits the resonance frequency! 🌉🎻",
      highlight: "Timing is everything. Small forces at the right frequency create massive power. ⚡",
    },
    {
      id: 'entropy_arrow',
      title: 'Thermodynamics: Entropy ⏳',
      color: '#FF6B6B',
      bgGradient: ['#200A0A', '#050D0A'],
      icon: '⏳',
      svgIcon: 'refresh',
      content: "The Second Law of Thermodynamics states that the total **Entropy** (disorder) of an isolated system always increases. \n\nThink of a glass of water. If it falls and shatters, it moves from order to disorder. You never see the shards jump back together to form a glass. This is 'The Arrow of Time.' The universe is slowly but surely moving toward a state of maximum disorder. 🌌📉",
      highlight: "Order requires energy. Disorder happens for free. 📉",
    },
    {
      id: 'torque_lever',
      title: 'Mechanics: Torque 🔧',
      color: '#F1C40F',
      bgGradient: ['#221A05', '#050D0A'],
      icon: '🔧',
      svgIcon: 'target',
      content: "Archimedes once said: *'Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.'*\n\nThis is the power of **Torque** (rotational force). By increasing the distance from the pivot point (the lever arm), you multiply the force you can apply. This is why it's easier to open a heavy door by pushing the edge furthest from the hinges. 🏗️📐",
      highlight: "Distance multiplied by Force = Turning Power. 🔧",
    },
    {
      id: 'friction_reality',
      title: 'Dynamics: Friction ⛸️',
      color: '#95A5A6',
      bgGradient: ['#1A1A1A', '#050D0A'],
      icon: '⛸️',
      svgIcon: 'activity',
      content: "Friction is the force that opposes motion between two surfaces in contact. Without it, you couldn't walk, cars couldn't brake, and every object on Earth would slide forever. \n\nThere are two types: **Static Friction** (the force keeping a heavy box from moving) and **Kinetic Friction** (the force slowing down a sliding puck). Static friction is almost always stronger! 🥌🧊",
      highlight: "Friction turns motion into heat. It is the tax we pay for movement. 🔥",
    },
    {
      id: 'doppler_effect',
      title: 'Acoustics: Doppler Effect 🏎️',
      color: '#3498DB',
      bgGradient: ['#001828', '#050D0A'],
      icon: '🏎️',
      svgIcon: 'waves',
      content: "Why does an ambulance siren sound higher-pitched as it approaches and lower-pitched as it drives away? \n\nAs the source moves toward you, it 'bunches up' the sound waves in front of it, increasing the frequency (higher pitch). As it moves away, it 'stretches' the waves behind it, decreasing the frequency (lower pitch). This is the **Doppler Effect**. 🚑🔊",
      highlight: "Sound waves are compressed or stretched by the motion of the source. 🔉",
    },
    {
      id: 'diffraction_bending',
      title: 'Optics: Diffraction 🌈',
      color: '#9B59B6',
      bgGradient: ['#1A0B2E', '#050D0A'],
      icon: '🌈',
      svgIcon: 'search',
      content: "Waves don't always travel in straight lines. When a wave hits an obstacle or a small slit, it bends around the corner and spreads out. This is **Diffraction**. \n\nThis is why you can hear someone talking from around a corner even if you can't see them—sound waves are long and diffract easily. Light waves are tiny, so they only diffract through very small gaps (like the data pits on a CD, creating a rainbow effect). 📀🔦",
      highlight: "Waves are flexible; they wrap around the world. 🌊",
    },
    {
      id: 'wave_particle',
      title: 'Quantum: Duality ⚛️',
      color: '#1ABC9C',
      bgGradient: ['#002E25', '#050D0A'],
      icon: '⚛️',
      svgIcon: 'atom',
      content: "In the quantum world, things get weird. Light and electrons behave like both a **Wave** (spreading out and interfering) and a **Particle** (hitting a detector like a tiny bullet). \n\nThis **Wave-Particle Duality** means that everything in the universe has a wavelength. Even you! But because you are so massive, your wavelength is so small it can never be detected. 🌌🔬",
      highlight: "Reality is a blur of waves and particles until we look at it. 👁️",
    },
    {
      id: 'emc2_energy',
      title: 'Nuclear: E=mc² 💥',
      color: '#E67E22',
      bgGradient: ['#2E1A0A', '#050D0A'],
      icon: '💥',
      svgIcon: 'zap',
      content: "Einstein's most famous equation revealed that mass and energy are just two forms of the same thing. \n\n**E = mc²** (Energy = Mass × Speed of Light²)\n\nBecause the speed of light (c) is such a huge number (300,000 km/s), even a tiny amount of mass contains a colossal amount of energy. This is the power that fuels the Sun and nuclear reactors. ☀️🔋",
      highlight: "A single gram of matter contains enough energy to power a city. 🏙️",
    }
  ],

  lab: {
    title: "The Multiverse Viewport 🔭",
    description: "Welcome to the Unified Physics Engine. You have control over 5 distinct experimental zones. Use the Dials to adjust the Prism Angle and Chamber Heat. Use the Switch-Bank to toggle Gravity, Friction, and Air Resistance. \n\nYour Goal: Discover all 5 'Physical Breakthroughs' hidden in the instruments! 🏆🔍",
    hint: "Try hitting exactly 440Hz for Resonance, or 42° for Total Internal Reflection. Scientist Mode reveals the hidden math!",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why fiber optic cables are better than copper wires? 🌐",
      answer: "Total Internal Reflection! Light pulses travel inside the glass core with almost zero loss of signal, allowing data to travel at near the speed of light for thousands of miles. Copper signals slow down due to electrical resistance! ⚡",
      emoji: '💎',
    },
    {
      id: 'dyk2',
      question: "Do you know why we use 'Concert A' at 440 Hz to tune orchestras? 🎻",
      answer: "Standardization! Before 1939, different countries tuned to different frequencies. By standardizing at 440Hz, every instrument on Earth can finally play in perfect resonance with each other! 🎼",
      emoji: '🎵',
    },
    {
      id: 'dyk3',
      question: "Do you know why mirrors flip left/right but NOT up/down? 🪞",
      answer: "Mirrors actually flip front-to-back! Imagine pushing a transparent mask through the mirror. Your left hand is still on the left side, but it is facing the opposite direction. It only *looks* like a left-right flip to your brain because that's how we imagine turning around. 🎭",
      emoji: '🪞',
    },
    {
      id: 'dyk4',
      question: "Do you know why the sky is blue? ☀️",
      answer: "Rayleigh Scattering! As sunlight hits Earth's atmosphere, it is scattered in all directions by the gases in the air. Blue light travels in shorter, smaller waves and is scattered much more than the other colors, making the sky look blue to our eyes. 🌍",
      emoji: '🌍',
    },
    {
      id: 'dyk5',
      question: "Do you know why a spinning ice skater goes faster when they pull their arms in? ⛸️",
      answer: "Conservation of Angular Momentum! By pulling their arms in, the skater reduces their 'moment of inertia' (they become more compact). To keep the total momentum the same, the 'angular velocity' (spinning speed) must increase. ⛸️🌪️",
      emoji: '⛸️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What happens to light above the 'Critical Angle' in a glass prism?", options: ['It disappears', 'Total Internal Reflection', 'It slows down', 'It changes color'], answer: 1, explanation: "Above the critical angle, light is trapped inside the material! 🌈" },
    { id: 'q2', question: "The phenomenon where energy builds up because input frequency matches natural frequency is:", options: ['Interference', 'Resonance', 'Diffraction', 'Silence'], answer: 1, explanation: "Resonance causes systems to vibrate with explosive amplitude! 🔊" },
    { id: 'q3', question: "In Physics, Work (W) is calculated as:", options: ['Force / Time', 'Force x Distance', 'Mass x Gravity', 'Heat x Speed'], answer: 1, explanation: "Work is energy transferred by a force acting over a distance. ⚙️" },
    { id: 'q4', question: "What is the First Law of Thermodynamics?", options: ['Entropy always increases', 'Energy cannot be created or destroyed, only transformed', 'Friction is unavoidable', 'Heat always flows to cold'], answer: 1, explanation: "The Law of Conservation of Energy states that the total energy in a system remains constant. 🔋" },
    { id: 'q5', question: "What does 'Entropy' measure in a system?", options: ['Speed', 'Disorder and randomness', 'Magnetic field strength', 'Electrical current'], answer: 1, explanation: "Entropy is a measure of the disorder or randomness in a physical system. 📉" },
    { id: 'q6', question: "What is 'Torque'?", options: ['Speed in a straight line', 'Rotational force around a pivot', 'The weight of an object', 'Resistance to air'], answer: 1, explanation: "Torque is the measure of the force that can cause an object to rotate about an axis. 🔧" },
    { id: 'q7', question: "The change in frequency of a wave due to the motion of the source or observer is called:", options: ['The Newton Effect', 'The Doppler Effect', 'The Einstein Effect', 'The Refraction Law'], answer: 1, explanation: "The Doppler Effect explains why sirens change pitch as they move past you. 🚑" },
    { id: 'q8', question: "Which phenomenon explains light bending around the edges of an obstacle?", options: ['Reflection', 'Diffraction', 'Refraction', 'Absorption'], answer: 1, explanation: "Diffraction allows waves to spread out and bend around corners. 🌈" },
    { id: 'q9', question: "What does 'Wave-Particle Duality' imply?", options: ['Objects can only be waves', 'Objects can only be particles', 'Quantum objects behave as both waves and particles', 'Light is an illusion'], answer: 2, explanation: "In quantum mechanics, all matter and energy exhibit both wave-like and particle-like properties. ⚛️" },
    { id: 'q10', question: "In E=mc², what does the 'c' represent?", options: ['The speed of sound', 'The speed of light', 'The density of carbon', 'A constant force'], answer: 1, explanation: "c is the speed of light in a vacuum (~300,000 km/s). ⚡" },
    { id: 'q11', question: "Why is the sky blue during the day?", options: ['The ocean reflects blue light', 'Oxygen is a blue gas', 'Rayleigh Scattering of sunlight by the atmosphere', 'It is the color of space'], answer: 2, explanation: "Blue light has a shorter wavelength and scatters more easily in our atmosphere. ☀️" },
    { id: 'q12', question: "What is 'Absolute Zero'?", options: ['0° Celsius', 'The temperature where all molecular motion stops (0 Kelvin)', 'The freezing point of alcohol', 'The temperature of the Moon'], answer: 1, explanation: "Absolute Zero (0K or -273.15°C) is the lowest possible temperature. 🧊" },
    { id: 'q13', question: "Smooth, parallel fluid flow without mixing is known as:", options: ['Turbulent flow', 'Laminar flow', 'Chaotic flow', 'Viscous flow'], answer: 1, explanation: "Laminar flow occurs when a fluid flows in parallel layers with no disruption. 🌊" },
    { id: 'q14', question: "What is 'Inertia'?", options: ['A type of fuel', 'The resistance of an object to any change in its motion', 'The speed of a falling object', 'The force of gravity'], answer: 1, explanation: "Inertia is the tendency of an object to remain at rest or in uniform motion. 🗿" },
    { id: 'q15', question: "What is the unit of 'Power' in physics?", options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 1, explanation: "One Watt (W) is equal to one Joule of work done per second. ⚡" },
    { id: 'q16', question: "What is a 'Photon'?", options: ['A positive part of an atom', 'A particle of light', 'A type of battery', 'A sound wave'], answer: 1, explanation: "A photon is an elementary particle that is a quantum of light. 💡" },
    { id: 'q17', question: "What is the 'Normal Force'?", options: ['A force that is usually expected', 'The support force exerted by a surface perpendicular to an object', 'Gravity', 'Air resistance'], answer: 1, explanation: "The Normal Force is what prevents you from falling through the floor. 🏗️" },
    { id: 'q18', question: "The bending of light as it passes from one medium to another (like air to water) is:", options: ['Reflection', 'Refraction', 'Diffraction', 'Polarization'], answer: 1, explanation: "Refraction happens because light changes speed in different materials. 🥤" },
    { id: 'q19', question: "Which of these is the energy of motion?", options: ['Potential Energy', 'Kinetic Energy', 'Thermal Energy', 'Nuclear Energy'], answer: 1, explanation: "Kinetic energy (½mv²) is the energy an object possesses due to its motion. 🏎️" },
    { id: 'q20', question: "What is 'Potential Energy'?", options: ['Energy that might happen', 'Stored energy based on position or state', 'Energy lost to friction', 'Maximum possible energy'], answer: 1, explanation: "Gravitational potential energy (mgh) is stored when you lift an object up. 🏔️" }
  ],

  relatedTopics: ['light_optics', 'waves_sound', 'thermodynamics_laws', 'forces_motion'],
};
