export default {
  id: 'cell_structure',
  title: 'Cell Structure & Function',
  subtitle: 'The building blocks of all life 🔬',
  emoji: '🔬',
  category: 'Biology',
  accentKey: 'microscope',

  hook: {
    question: "Did you know your body contains 37 trillion cells — and each one is more complex than a modern city? 🤯",
    reveal: "Every cell is a self-contained universe with its own power plant, library, post office, recycling centre, and protective wall — all packed into a space 10 times smaller than a grain of sand! The cell is the fundamental unit of life. Everything alive — from bacteria to blue whales — is made of cells. Understanding cells is like learning the alphabet of biology: once you know it, everything else clicks. 🌟",
    emoji: '🔬',
  },

  theory: [
    {
      id: 'cell_basics',
      title: 'What is a Cell? 🧫',
      color: '#7B61FF',
      bgGradient: ['#1A1040', '#05050A'],
      icon: '🧫',
      svgIcon: 'microscope',
      content: "A **cell** is the smallest unit of life. Every living thing is made of cells — from a single-celled bacterium to the trillions in your body.\n\nRobert Hooke first saw cells in 1665 using a primitive microscope when he looked at cork — he named them 'cells' because they looked like small rooms (cella in Latin). 🏠\n\nThe **Cell Theory** (1838) states:\n🔹 All living things are made of cells\n🔹 The cell is the basic unit of life\n🔹 Cells come from pre-existing cells\n\nThere are two fundamental types:\n🟣 **Prokaryotic** — simple, no nucleus (bacteria)\n🟣 **Eukaryotic** — complex, with a nucleus (plants, animals, fungi)",
      highlight: "All life is made of cells — they are the basic unit of structure and function in all living organisms! 🧫",
    },
    {
      id: 'cell_membrane',
      title: 'The Cell Membrane 🛡️',
      color: '#00FFD1',
      bgGradient: ['#0A2020', '#05050A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "The **cell membrane** (plasma membrane) is the cell's security guard. It's a thin, flexible layer made of a **phospholipid bilayer** — two layers of fat molecules arranged like a sandwich.\n\nThe heads of phospholipids are water-loving (hydrophilic) and face outward. The tails are water-fearing (hydrophobic) and hide inside. This arrangement creates a selective barrier. 🥪\n\n**Selective permeability** means it lets some things in and keeps others out:\n✅ Small molecules (O₂, CO₂, water) pass freely\n❌ Large molecules and ions need protein channels/pumps\n\nThis control is essential — it keeps the cell's chemistry balanced. The famous **fluid mosaic model** (Singer & Nicolson, 1972) describes it as a sea of fluid lipids with protein 'icebergs' floating in it. 🌊",
      highlight: "The cell membrane controls what enters and exits the cell — it's a selective gate, not a solid wall! 🛡️",
    },
    {
      id: 'nucleus',
      title: 'The Nucleus: Command Centre 🧬',
      color: '#C77DFF',
      bgGradient: ['#1A0A30', '#05050A'],
      icon: '🧬',
      svgIcon: 'book',
      content: "The **nucleus** is the control centre of the cell — it contains the cell's DNA (the genetic blueprint).\n\nIt's surrounded by a **double membrane** (nuclear envelope) with thousands of **nuclear pores** that act like security checkpoints, controlling what messages leave the nucleus.\n\nInside are **chromosomes** — tightly coiled DNA. Human cells have 46 chromosomes containing ~3.2 billion base pairs of DNA!\n\nWhen a gene needs to be 'read', the DNA is transcribed into **mRNA**, which exits through the pores and travels to ribosomes to build proteins. 🏗️\n\nThe **nucleolus** inside the nucleus manufactures ribosomes. It's the busiest 'factory' in the cell — making millions of ribosomes per day! 🏭",
      highlight: "The nucleus stores DNA and controls all cell activity — it's the master blueprint library! 🧬",
    },
    {
      id: 'mitochondria',
      title: 'Mitochondria: Power Plant ⚡',
      color: '#FF6B6B',
      bgGradient: ['#2A0A0A', '#05050A'],
      icon: '⚡',
      svgIcon: 'lightning',
      content: "\"**Mitochondria is the powerhouse of the cell**\" — the most famous biology fact ever! But why?\n\nMitochondria make **ATP** (adenosine triphosphate) — the universal energy currency of life. Through **cellular respiration**, they burn glucose with oxygen to release energy:\n\n🔋 Glucose + O₂ → ATP + CO₂ + Water\n\nMitochondria have **two membranes**: the outer membrane and a folded inner membrane called **cristae** — these folds massively increase surface area for ATP production.\n\nMost remarkably: mitochondria have their **own DNA** and reproduce by splitting! This is evidence they were once free-living bacteria that were swallowed by ancient cells (~2 billion years ago). This is called **endosymbiotic theory**. 🦠\n\nYour muscle cells contain 1,000-2,000 mitochondria each! ⚡",
      highlight: "Mitochondria make ATP from glucose and oxygen — they were originally free-living bacteria that got absorbed! ⚡",
    },
    {
      id: 'ribosomes_er',
      title: 'Ribosomes & The ER 🏗️',
      color: '#FFD93D',
      bgGradient: ['#2A200A', '#05050A'],
      icon: '🏗️',
      svgIcon: 'flask',
      content: "**Ribosomes** are the protein-building machines of the cell. They read mRNA instructions from the nucleus and string amino acids together to build proteins. Every cell makes millions of proteins!\n\nRibosomes can float freely in the cytoplasm or be attached to the **Endoplasmic Reticulum (ER)**.\n\n**Rough ER** — studded with ribosomes (looks rough), it manufactures and folds proteins destined for export outside the cell or to the membrane. 🏭\n\n**Smooth ER** — no ribosomes; it manufactures lipids, detoxifies drugs, and stores calcium. Your liver cells are packed with Smooth ER to break down alcohol! 🍺\n\nThe ER is a huge interconnected membrane network — if you unfolded all the ER in one liver cell, it would be the size of a football pitch! ⚽",
      highlight: "Ribosomes read DNA's instructions and build proteins — they're the construction workers of the cell! 🏗️",
    },
    {
      id: 'golgi_lysosome',
      title: 'Golgi: The Post Office 📦',
      color: '#4D96FF',
      bgGradient: ['#0A1530', '#05050A'],
      icon: '📦',
      svgIcon: 'target',
      content: "The **Golgi apparatus** is the cell's postal service. It receives proteins from the Rough ER, modifies them, packages them, and ships them to the right destination — inside or outside the cell.\n\nIt's made of stacked, flattened membrane sacs called **cisternae** (looks like a stack of pita breads 🫓). Proteins arrive on one side (cis face), get processed through the stack, and leave from the other side (trans face).\n\n**Vesicles** are tiny membrane-wrapped bubbles that carry cargo between organelles — like delivery trucks. 🚚\n\n**Lysosomes** are produced by the Golgi and contain ~50 digestive enzymes. They destroy:\n💀 Old organelles (autophagy — self-eating!)\n🦠 Bacteria and viruses that enter the cell\n🗑️ Waste products\n\nLysosomes are so powerful that if they leak inside the cell, they digest it from within — cellular suicide (apoptosis)! 😮",
      highlight: "The Golgi is the post office that packages and ships proteins — lysosomes are the cell's waste disposal system! 📦",
    },
    {
      id: 'plant_vs_animal',
      title: 'Plant vs Animal Cells 🌱🐾',
      color: '#22C55E',
      bgGradient: ['#052010', '#05050A'],
      icon: '🌱',
      svgIcon: 'leaf',
      content: "Plant and animal cells are both eukaryotic, but they have key differences:\n\n**Unique to Plant Cells 🌱:**\n🟢 **Cell Wall** — rigid outer layer made of cellulose (gives plants their stiffness)\n🟢 **Chloroplasts** — for photosynthesis\n🟢 **Large Central Vacuole** — holds water to maintain pressure (turgor pressure), keeping plants upright\n\n**Unique to Animal Cells 🐾:**\n🟣 **Centrioles** — help organise cell division (mitosis)\n🟣 **Lysosomes more prominent**\n🟣 No cell wall (more flexible shape)\n\n**Found in Both:**\nNucleus, Mitochondria, ER, Ribosomes, Golgi, Cell Membrane\n\nFun fact: The cellulose cell wall makes wood so strong! Every tree trunk is billions of cell walls stacked together. 🌲",
      highlight: "Plant cells have a cell wall, chloroplasts, and a large vacuole — animal cells have centrioles but no cell wall! 🌱",
    },
    {
      id: 'osmosis_transport',
      title: 'Osmosis & Cell Transport 💧',
      color: '#06B6D4',
      bgGradient: ['#0A1A20', '#05050A'],
      icon: '💧',
      svgIcon: 'water',
      content: "How do things get in and out of cells? There are several mechanisms:\n\n**Passive Transport (no energy needed):**\n💧 **Diffusion** — molecules move from HIGH to LOW concentration\n💧 **Osmosis** — water moves across a membrane from low to high solute concentration\n💧 **Facilitated Diffusion** — molecules use protein channels to cross (e.g. glucose)\n\n**Active Transport (energy/ATP needed):**\n⚡ **Sodium-Potassium Pump** — pumps 3 Na⁺ out, 2 K⁺ in (critical for neurons!)\n⚡ **Endocytosis** — cell engulfs large particles by wrapping membrane around them\n⚡ **Exocytosis** — vesicles fuse with membrane to release contents outside\n\n**Osmosis determines life or death!**\n🔴 Too much water in → cell lyses (bursts)\n🟡 Right amount → turgid and healthy\n🔵 Too little water → cell shrivels (plasmolysis)",
      highlight: "Osmosis moves water across membranes by concentration gradient — too much water bursts the cell! 💧",
    },
    {
      id: 'cell_division',
      title: 'Cell Division: Mitosis 🔄',
      color: '#F43F5E',
      bgGradient: ['#2A0510', '#05050A'],
      icon: '🔄',
      svgIcon: 'cycle',
      content: "Cells reproduce by dividing. **Mitosis** produces two identical daughter cells for growth and repair:\n\n🔵 **Interphase** — DNA replicates (cell doubles its contents)\n🟣 **Prophase** — chromosomes condense, visible under microscope\n🟠 **Metaphase** — chromosomes line up in the middle\n🟡 **Anaphase** — sister chromatids pulled to opposite ends\n✅ **Telophase + Cytokinesis** — two new nuclei form, cell splits in two\n\nYour body replaces 3.8 million cells every second! 🤯\n\n**Meiosis** (for sex cells) is different — it produces 4 daughter cells with HALF the chromosomes (23 instead of 46) for fertilisation.\n\n**Cancer** occurs when cell division controls break down — cells divide uncontrollably. Understanding mitosis is key to developing cancer treatments! 💊",
      highlight: "Mitosis creates two identical daughter cells — your body replaces 3.8 million cells every single second! 🔄",
    },
    {
      id: 'stem_cells',
      title: 'Stem Cells: Blank Slates 🌟',
      color: '#A855F7',
      bgGradient: ['#1A0A2A', '#05050A'],
      icon: '🌟',
      svgIcon: 'sparkle',
      content: "**Stem cells** are special undifferentiated cells that can develop into any cell type. They are the body's ultimate shape-shifters! 🔮\n\n**Types:**\n🌱 **Embryonic Stem Cells** — can become any cell (totipotent), found in early embryos\n🧬 **Adult Stem Cells** — found in bone marrow, can become blood cells and some other types\n🔬 **iPSCs** (induced Pluripotent) — reprogrammed adult cells (Nobel Prize 2012!)\n\n**Why they're revolutionary:**\n🏥 Could replace damaged heart tissue after heart attack\n🧠 Potential to repair spinal cord injuries\n👀 Growing new retinal cells to treat blindness\n🦷 Regrowing teeth!\n\nStem cell research is one of the most promising frontiers in medicine. The ability to 'reset' adult cells to an embryonic state (iPSC) won Shinya Yamanaka the 2012 Nobel Prize! 🏆",
      highlight: "Stem cells can become any cell type — iPSC technology won the 2012 Nobel Prize and could regenerate organs! 🌟",
    },
  ],

  lab: {
    title: "Virtual Cell Explorer 🔬",
    description: "Control cell size, RNA activity, membrane permeability, and energy levels. Discover what happens when you push cells to their limits!",
    hint: "Try maxing out cell size AND energy together — or push membrane permeability above 85% and watch what happens! 🔬",
    scientistModeHint: "In Scientist Mode: discover ribosome storms, energy crises, and the secret of osmotic lysis! 🧑‍🔬",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why your liver can regenerate itself even after 75% is removed? 🫁",
      answer: "The liver contains abundant stem-like cells that retain the ability to divide. When liver tissue is damaged, these cells rapidly proliferate (multiply) using mitosis to restore the original mass. This remarkable regeneration takes about 8 weeks! Ancient Greeks knew this — in the myth of Prometheus, an eagle ate his liver every day, and it regrew every night. 🦅",
      emoji: '🫁',
    },
    {
      id: 'dyk2',
      question: "Do you know why your red blood cells have no nucleus? 🩸",
      answer: "Red blood cells eject their nucleus during maturation to make more room for haemoglobin — the protein that carries oxygen. Without a nucleus, they cannot repair themselves, so they only live about 120 days before being recycled by the spleen. This is a beautiful trade-off: less DNA = more space for oxygen transport! 🅾️",
      emoji: '🩸',
    },
    {
      id: 'dyk3',
      question: "Do you know why mitochondria have their own DNA? 🧬",
      answer: "Mitochondria were once free-living bacteria! About 2 billion years ago, an ancient cell engulfed a bacterium instead of digesting it. This 'endosymbiosis' was mutually beneficial — the host got energy, the bacterium got protection. Over billions of years, most bacterial genes transferred to the host nucleus, but mitochondria kept some. That's why you can trace maternal ancestry through mitochondrial DNA! 🌳",
      emoji: '🧬',
    },
    {
      id: 'dyk4',
      question: "Do you know why cells need the sodium-potassium pump to fire nerve signals? ⚡",
      answer: "Your neurons communicate by creating voltage differences across their membrane. The Na-K pump uses ATP to push 3 sodium ions out and pull 2 potassium ions in, creating an electrochemical gradient. When a stimulus arrives, sodium floods in suddenly — this is the 'action potential' that fires as a nerve signal travelling at 120 m/s! Without ATP, this pump fails and you become paralysed. ⚡",
      emoji: '⚡',
    },
    {
      id: 'dyk5',
      question: "Do you know why cancer cells are essentially immortal? 💀",
      answer: "Normal cells have a biological clock — their telomeres (protective chromosome caps) shorten with each division, eventually triggering cell death (apoptosis). Cancer cells activate an enzyme called telomerase that rebuilds telomeres, making them effectively immortal. The HeLa cells taken from Henrietta Lacks in 1951 are still alive in labs today — over 70 years later! 🔬",
      emoji: '💀',
    },
  ],

  quiz: [
    { id: 'q1', question: "Which organelle is known as the 'powerhouse of the cell'? ⚡", options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi Apparatus'], answer: 2, explanation: "Mitochondria produce ATP through cellular respiration — they are literally the cell's power plant! They even have their own DNA from their bacterial ancestors. ⚡" },
    { id: 'q2', question: "What is the function of the cell membrane? 🛡️", options: ['Stores DNA', 'Produces energy', 'Controls what enters/exits the cell', 'Manufactures proteins'], answer: 2, explanation: "The phospholipid bilayer membrane is selectively permeable — it acts as a security guard deciding what molecules can pass in or out of the cell! 🛡️" },
    { id: 'q3', question: "Which cell structures are unique to PLANT cells but NOT animal cells? 🌱", options: ['Mitochondria and Nucleus', 'Ribosomes and Cell Membrane', 'Cell Wall, Chloroplasts, and Large Vacuole', 'Golgi Apparatus and Lysosomes'], answer: 2, explanation: "Plant cells have three exclusive structures: a rigid Cell Wall (cellulose), Chloroplasts (for photosynthesis), and a Large Central Vacuole (for water storage and pressure). 🌱" },
    { id: 'q4', question: "What does the Golgi apparatus do? 📦", options: ['Makes ATP energy', 'Packages and ships proteins to their destination', 'Stores genetic information', 'Controls cell division'], answer: 1, explanation: "The Golgi is the cell's postal service! It modifies proteins from the ER, packages them into vesicles, and ships them to the right location inside or outside the cell. 📦" },
    { id: 'q5', question: "What is osmosis? 💧", options: ['Movement of proteins through the cell', 'Energy production from glucose', 'Movement of water across a membrane from low to high solute concentration', 'DNA replication before cell division'], answer: 2, explanation: "Osmosis is the movement of water molecules across a semipermeable membrane — moving from where there is less dissolved solute to where there is more. Too much osmosis can burst or shrivel a cell! 💧" },
    { id: 'q6', question: "How many chromosomes do human body cells have? 🧬", options: ['23', '46', '64', '92'], answer: 1, explanation: "Human cells contain 46 chromosomes (23 pairs). Sperm and egg cells have only 23 (produced by meiosis), so when they combine during fertilisation, the full 46 is restored! 🧬" },
    { id: 'q7', question: "What is the endosymbiotic theory? 🦠", options: ['Cells develop from chemicals in the sea', 'Mitochondria and chloroplasts were once free-living bacteria', 'All life shares a common ancestor', 'Viruses evolved from cell organelles'], answer: 1, explanation: "Mitochondria and chloroplasts have their own DNA and replicate independently — strong evidence they were once free-living bacteria engulfed by ancient cells over 2 billion years ago! 🦠" },
    { id: 'q8', question: "What do ribosomes do? 🏗️", options: ['Store DNA instructions', 'Build proteins from amino acids', 'Digest old organelles', 'Pump ions across the membrane'], answer: 1, explanation: "Ribosomes are protein-building machines that read mRNA instructions from the nucleus and link amino acids together to make proteins — the molecules that do almost everything in the body! 🏗️" },
    { id: 'q9', question: "What happens during the Anaphase stage of mitosis? 🔄", options: ['DNA replicates', 'Chromosomes line up in the middle', 'Sister chromatids are pulled to opposite poles', 'The cell membrane pinches in two'], answer: 2, explanation: "During Anaphase, sister chromatids are pulled apart to opposite ends of the cell by spindle fibres — ensuring each new daughter cell gets an identical set of chromosomes! 🔄" },
    { id: 'q10', question: "Why are stem cells considered revolutionary for medicine? 🌟", options: ['They produce more ATP than normal cells', 'They can divide into any cell type and repair damaged tissues', 'They are immune to all viruses', 'They make the body age more slowly'], answer: 1, explanation: "Stem cells are undifferentiated — they can be guided to become any specialised cell type. This makes them potentially able to repair heart muscle, spinal cords, and even grow replacement organs! 🌟" },
  ],

  relatedTopics: ['dna_genetics', 'photosynthesis', 'evolution_natural', 'human_body_systems'],
};
