export default {
  id: 'internet_how_it_works',
  title: 'How the Internet Works',
  subtitle: 'The invisible web connecting the planet 🌐',
  emoji: '🌐',
  category: 'Technology',
  accentKey: 'network',

  hook: {
    question: "Is the internet a cloud floating in the sky?",
    reveal: "No! The 'Cloud' is just someone else's computer. The internet is actually a massive, physical machine. It is a terrifyingly huge web of extremely thick fiber-optic cables lying on the bottom of the world's oceans, directly connecting your phone to giant warehouses full of blinking servers in other countries. Let's trace a message across the globe!",
    emoji: '🌊',
  },

  theory: [
    {
      id: 'what_is_internet',
      title: 'The Physical Internet 🌍',
      color: '#3B82F6',
      bgGradient: ['#05101A', '#050D0A'],
      icon: '🌍',
      svgIcon: 'globe',
      content: "We talk about 'Wi-Fi' and 'The Cloud', making the internet sound like invisible magic.\n\nBut the internet is highly physical. If you send a WhatsApp message to a friend in London, that message travels from your phone to a local cell tower, runs down wires into the ground, shoots across the bottom of the Atlantic Ocean through a massive submarine fiber-optic cable, and pops up in the UK!\n\nIf a shark bites that underwater cable (which has actually happened), the internet literally breaks.",
      highlight: "Over 99% of all international data is carried by underwater submarine cables, NOT satellites! 🦈",
    },
    {
      id: 'clients_servers',
      title: 'Clients & Servers 🖥️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🖥️',
      svgIcon: 'cpu',
      content: "Every computer on the internet acts as either a Client or a Server.\n\n**Clients:** Your phone, your laptop, your smart TV. Clients *request* information.\n**Servers:** Massive, powerful computers sitting in giant air-conditioned warehouses (Data Centers). Their only job is to *serve* information when a Client asks for it.\n\nWhen you open YouTube, your phone (Client) yells across the ocean to Google's warehouse (Server) asking for a video. The Server immediately shoots the video file back to you.",
      highlight: "Google processes over 99,000 search requests every single second! 🕒",
    },
    {
      id: 'ip_addresses',
      title: 'IP Addresses: Digital Homes 🏠',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🏠',
      svgIcon: 'grid',
      content: "If there are billions of computers talking at once, how does a YouTube video know exactly which phone to return to?\n\nBecause every single device connected to the internet is assigned a unique **IP Address** (Internet Protocol Address). It looks like this: `192.168.1.5`.\n\nIt works exactly like your physical home mailing address. The Server slaps your IP Address on the video file like a postage stamp so the postal workers (Routers) know exactly where to deliver it.",
      highlight: "We actually ran out of the old style of IP addresses (IPv4) because we built too many smart devices! 📱",
    },
    {
      id: 'packets',
      title: 'Packets: Chopping it Up ✂️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '✂️',
      svgIcon: 'hash',
      content: "When a Server sends you a video, it doesn't send it as one giant file.\n\nIf a giant file got corrupted halfway across the ocean, it would have to resend the whole thing! Instead, the internet uses **Packets**. It chops the video up into thousands of tiny, numbered pieces (e.g., Packet 1 of 500).\n\nIt sends these tiny packets across the world. When they arrive at your phone, your phone reads the numbers and glues them all back together in order!",
      highlight: "If you watch a video and it 'buffers', your phone is just waiting for a missing Packet to arrive! ⏳",
    },
    {
      id: 'dns',
      title: 'DNS: The Phonebook 📖',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📖',
      svgIcon: 'book',
      content: "Computers only understand numbers (IP Addresses like `142.250.190.46`). But humans are terrible at memorizing random numbers.\n\nHumans like words (like `google.com`).\n\nTo bridge this gap, the internet uses the **DNS** (Domain Name System). DNS is a gigantic digital phonebook. When you type `google.com`, your browser silently asks the DNS phonebook for the number. The DNS replies, 'Ah, google is at 142.250.190.46!', and connects you.",
      highlight: "If the global DNS servers crash, nobody can load websites because the internet forgets everyone's phone number! 📞",
    },
    {
      id: 'routers',
      title: 'Routers: The Traffic Cops 🚦',
      color: '#A855F7',
      bgGradient: ['#1A0A1F', '#050D0A'],
      icon: '🚦',
      svgIcon: 'target',
      content: "When a tiny data Packet leaves your house, how does it know how to navigate the massive maze of global cables to reach its destination?\n\nIt jumps from **Router** to **Router**. A router is a specialized traffic-cop computer.\nWhen it receives a packet, it reads the destination IP Address stamp, looks at its map of the internet, and throws the packet in the best direction to get it there faster.\n\nYour home Wi-Fi box is just the very first Router in the chain!",
      highlight: "A single packet might jump between 15 different routers in 3 different countries in less than a second! ⚡",
    },
    {
      id: 'tcp_ip',
      title: 'TCP/IP: The Unbreakable Rulebook 📜',
      color: '#4CA050',
      bgGradient: ['#0A1A0F', '#050D0A'],
      icon: '📜',
      svgIcon: 'shield',
      content: "The internet works flawlessly because every computer, regardless of whether it's an Apple iPhone or a Windows PC, agrees to follow the exact same rulebook: **TCP/IP**.\n\n**IP (Internet Protocol):** Controls the routing and addressing (Postage stamps).\n**TCP (Transmission Control Protocol):** Controls the chop and glue. It double-checks every single packet. If Packet 42 goes missing because a cable broke, TCP actively yells at the server to resend Packet 42!",
      highlight: "Because of TCP/IP, the internet is decentralized. If a bomb destroys a city's cables, the routers intelligently route packets around the crater! 💣",
    },
    {
      id: 'http_html',
      title: 'HTTP & HTML: Painting the Web 🎨',
      color: '#FF007F',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '🎨',
      svgIcon: 'star',
      content: "Once the packets are glued back together by TCP/IP, what are they?\n\nUsually, they are **HTML** (HyperText Markup Language) files. HTML is just plain text code that says 'Make this text bold' or 'Put an image here'.\n\nYour Web Browser (like Chrome or Safari) speaks a language called **HTTP** (HyperText Transfer Protocol) to politely ask the server for these files. When it gets the HTML text file, it paints it onto your screen as a beautiful, colorful webpage!",
      highlight: "Right-click on any webpage and click 'Inspect'. You will suddenly see the raw, ugly HTML code hiding behind the beauty! 👩‍💻",
    },
    {
      id: 'encryption',
      title: 'HTTPS & Encryption 🔐',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '🔐',
      svgIcon: 'key',
      content: "When you type your credit card into Amazon, what stops an evil router from reading the packets as they fly by?\n\n**Encryption!** When you see HTTPS (the 'S' stands for Secure) and a little padlock in your browser, the math gets wild.\n\nBefore your phone sends the Packet, it scrambles the data into total gibberish using complex math. Even if a hacker intercepts the packet, it looks like `XJ9@!L$P`. Only the Amazon Server has the mathematical 'Private Key' required to unscramble it!",
      highlight: "Modern 256-bit encryption is so strong that it would take a supercomputer millions of years to crack by guessing. 🛡️",
    },
    {
      id: 'future_web',
      title: 'The Future: Starlink & Web3 🚀',
      color: '#00D4A0',
      bgGradient: ['#001A13', '#050D0A'],
      icon: '🚀',
      svgIcon: 'planet',
      content: "The physical internet is evolving rapidly.\n\nInstead of laying thousands of miles of cables in the dirt, companies like SpaceX (Starlink) are constantly launching 'Constellations' of thousands of low-earth-orbit satellites. These satellites beam packets using lasers in the vacuum of space, providing blazing fast internet to the most remote jungles on Earth.\n\nMeanwhile, Web3 concepts (like Blockchain) are pushing towards an internet that has no central Servers at all—just purely connected Clients!",
      highlight: "Light actually travels 47% faster through the vacuum of space than it does through glass fiber-optic cables! ☄️",
    },
  ],

  lab: {
    title: "Network Hacker Lab 💻",
    description: "Welcome to the Cybersecurity routing terminal. Track the physical Submarine Cables connecting the continents, cut fiber lines to watch the TCP/IP algorithm re-route packets dynamically, execute a DNS lookup, and test your encryption keys.",
    hint: "If you cut the main fiber-optic trunk line in the Routing game, the packets will instantly swarm the slower backup routers to avoid dropping the connection!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays latent ping (ms) times and raw active port connections.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the Internet was originally entirely funded by the US Military in the 1960s? 🪖",
      answer: "Fear of nuclear war! During the Cold War, the military realized their communications relied on a single central hub. If a Soviet nuke hit that hub, all communication died. They funded the 'ARPANET' (the first internet) to build a decentralized web. Because there is no 'center' to a web, if a nuke destroys one city, the routers simply bounce the signal around the crater! ☢️",
      emoji: '🗺️',
    },
    {
      id: 'dyk2',
      question: "Do you know why high-speed internet cables are made of completely clear glass? 🪟",
      answer: "Because they use lasers! Copper wires use electricity, which slows down and gets weak over very long distances. Modern Fiber-Optic cables are thinner than a human hair and made of pure, flawless glass. We shoot data using blinking lasers that travel at the literal speed of light through the glass, carrying massive amounts of data instantly! 🔦",
      emoji: '⚡',
    },
    {
      id: 'dyk3',
      question: "Do you know why you instantly lose internet walking into the basement or an elevator? 🏢",
      answer: "Unlike the wired internet, your phone uses Wi-Fi or 5G, which rely on invisible Radio Waves flying through the air. However, concrete walls and thick metal (like the walls of an elevator) physically absorb and block these specific radio frequencies. The waves bounce off the metal, completely trapping you in a digital dead zone! 📶",
      emoji: '🧱',
    },
    {
      id: 'dyk4',
      question: "Do you know why deep web / dark web sites end in '.onion' instead of '.com'? 🧅",
      answer: "The 'Tor' network uses an incredibly specific routing protocol called The Onion Router. Instead of jumping directly from router to router, your data is wrapped in multiple layers of heavy encryption (like the layers of an onion). As it jumps randomly around the world, each router only peels off ONE layer. Nobody knows who sent the message or where it is going! 🕵️",
      emoji: '👤',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Cookies' on websites are actually super important? 🍪",
      answer: "Without cookies, the internet would have permanent amnesia! HTTP is a 'stateless' protocol, meaning every single time you click a link, the server forgets who you are. Cookies are tiny text files the server hides in your browser. When you click a new page, it spots the cookie and remembers 'Ah yes, this person is logged in to this account'. 🔑",
      emoji: '🧠',
    },
  ],

  quiz: [
    { id: 'q1', question: "Where is the vast majority of international internet data physically carried?", options: ['Satellites in space', 'Radio towers', 'Underwater submarine fiber-optic cables', 'Underground train tunnels'], answer: 2, explanation: "Over 99% of global internet traffic travels through huge armored fiber-optic cables laying on the ocean floor! 🌊" },
    { id: 'q2', question: "In computing, your phone requesting a YouTube video makes your phone the:", options: ['Server', 'Router', 'Client', 'Host'], answer: 2, explanation: "Your phone 'requests' data, marking it as a Client. The massive Google computer answering is the Server! 📱" },
    { id: 'q3', question: "Every device on the internet needs a unique digital home address to receive data. This is called an:", options: ['URL', 'IP Address', 'HTML tag', 'SSID'], answer: 1, explanation: "An IP (Internet Protocol) Address acts as your exact physical mailing address so the internet knows where to send your packets. 🏠" },
    { id: 'q4', question: "Instead of sending a massive 10GB game as one file, the internet chops it into tiny manageable pieces called:", options: ['Pixels', 'Nodes', 'Packets', 'Bits'], answer: 2, explanation: "Packets are tiny envelopes of data. If one gets lost, the system only has to resend that specific tiny piece! ✂️" },
    { id: 'q5', question: "Which system acts as the 'phonebook' of the internet, translating 'google.com' into a messy IP address?", options: ['VPN', 'DNS (Domain Name System)', 'HTML', 'Firewall'], answer: 1, explanation: "The DNS silently looks up human-readable URLs and finds their true numerical IP Addresses. 📖" },
    { id: 'q6', question: "What specialized computer acts as a 'traffic cop', reading packets and throwing them in the best direction?", options: ['A Router', 'A Hard Drive', 'A Keyboard', 'A Client'], answer: 0, explanation: "Routers constantly look at maps of the network and choose the fastest path to forward your packet. 🚦" },
    { id: 'q7', question: "What is the unbreakable, universal set of rules all computers use to communicate across the web?", options: ['TCP/IP', 'Unicode', 'ASCII', 'USB'], answer: 0, explanation: "Transmission Control Protocol / Internet Protocol (TCP/IP) ensures every brand of computer formats packets the exact same way. 📜" },
    { id: 'q8', question: "Which component of TCP/IP ensures that lost or corrupted packets are immediately re-sent?", options: ['IP (Internet Protocol)', 'TCP (Transmission Control Protocol)', 'HTTP', 'DNS'], answer: 1, explanation: "TCP is aggressive. It double-checks every packet and forces the server to resend any missing pieces! 🕵️" },
    { id: 'q9', question: "The code that dictates how a webpage physically looks (text size, colors, images) is:", options: ['Python', 'HTML', 'C++', 'Binary'], answer: 1, explanation: "HyperText Markup Language (HTML) is the structure that your browser paints onto the screen. 🎨" },
    { id: 'q10', question: "When your browser shows a Padlock icon and 'HTTPS', what is it doing to protect your credit card?", options: ['Hiding your IP address', 'Using military guards', 'Scrambling the data using Encryption', 'Making the password invisible'], answer: 2, explanation: "Encryption uses insane math to turn your data into pure gibberish that only the Amazon server has the key to decrypt. 🔐" },
    { id: 'q11', question: "Why was the early internet (ARPANET) designed to be decentralized with no central core?", options: ['To look like a spiderweb', 'So it could survive a nuclear strike destroying one city', 'Because it was cheaper', 'To confuse hackers'], answer: 1, explanation: "The military designed it to physically route around damage. If a city explodes, the packets just take a detour! 🗺️" },
    { id: 'q12', question: "A single piece of fiber-optic cable transmits data using:", options: ['High voltage electricity', 'Sound waves', 'Blinking laser light', 'Water pressure'], answer: 2, explanation: "Optics means light! The cables are pure glass, shooting microscopic lasers at the speed of light. ⚡" },
    { id: 'q13', question: "Why do you lose cell service inside an elevator?", options: ['The elevator moves too fast', 'The thick metal physically traps and blocks radio waves', 'The cables disconnect', 'The phone gets confused'], answer: 1, explanation: "Radio waves easily pass through air, but metal acts as a physical shield, bouncing the signal away. 🧱" },
    { id: 'q14', question: "If a webpage suddenly stops loading halfway and gets stuck, it is usually because:", options: ['The server exploded', 'Your computer broke', 'A Packet was lost and TCP is waiting for it to be resent', 'The DNS forgot you'], answer: 2, explanation: "Buffering usually means TCP noticed Packet #57 was missing and paused the video until it arrives! ⏳" },
    { id: 'q15', question: "What is 'The Cloud'?", options: ['A satellite network', 'A literal weather phenomenon', 'Servers (Someone else\'s computers) sitting in a giant warehouse', 'A magic trick'], answer: 2, explanation: "The Cloud just means you are storing your data on a massive Amazon or Google Server instead of your local phone drive. ☁️" },
    { id: 'q16', question: "Why did the world run out of IPv4 addresses?", options: ['They expire after 10 years', 'We built too many smart devices (phones, TVs, fridges)', 'Hackers stole them', 'They were mathematically flawed'], answer: 1, explanation: "IPv4 only had 4.3 billion addresses. Because everyone now has 3 devices, we completely ran out and had to upgrade! 📱" },
    { id: 'q17', question: "The dark web relies on 'The Onion Router' (Tor). Why is it called an onion?", options: ['It makes hackers cry', 'It uses layers of heavy encryption that peel off slowly', 'It routes through farms', 'It is cheap'], answer: 1, explanation: "The message jumps through 3 random routers, and each one peels exactly one layer of encryption off. 🧅" },
    { id: 'q18', question: "What tiny file does a website drop onto your browser so it remembers who you are on the next click?", options: ['A packet', 'A virus', 'A Cookie', 'A token'], answer: 2, explanation: "Cookies are essential memory blocks that keep you logged in to accounts as you traverse a site! 🍪" },
    { id: 'q19', question: "Starlink is changing the internet by beaming packets from:", options: ['Large blimps', 'Low-Earth-Orbit satellite constellations', 'Deep sea submarines', 'Drones'], answer: 1, explanation: "By beaming lasers through the vacuum of space, Starlink can provide blazing fast internet without tearing up the ground to lay physical cables. 🚀" },
    { id: 'q20', question: "What is the primary language web browsers (like Chrome) speak to request HTML files back and forth?", options: ['HTTP', 'SQL', 'CSS', 'Java'], answer: 0, explanation: "HyperText Transfer Protocol (HTTP) is the specific dialect clients and servers use to ask for web pages. 🗣️" },
  ],

  relatedTopics: ['binary_computers', 'electricity_circuits', 'ai_machine_learning'],
};
