// ─────────────────────────────────────────────────────────
//  TOPIC: INDIAN FREEDOM STRUGGLE
//  Category: History
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'indian_freedom',
  title: 'Indian Freedom',
  subtitle: 'The non-violent revolution that shook an empire 🇮🇳🕊️',
  emoji: '🇮🇳',
  category: 'History',
  accentKey: 'freedom',

  hook: {
    question: "How did a man in a simple loincloth defeat the most powerful, heavily armed global empire in human history without firing a single bullet? 🕊️",
    reveal: "The British Empire controlled 25% of the Earth's surface and had an unstoppable military. But Mahatma Gandhi and the Indian freedom fighters didn't fight fire with fire. They invented 'Satyagraha' (Truth-Force). By using strategic non-violent non-cooperation, they economically starved the Empire and morallybankrupted it on the world stage. Let's trace the epic 190-year struggle for Independence! 🇮🇳⚔️",
    emoji: '✊',
  },

  theory: [
    {
      id: 'the_eic',
      title: 'The East India Company 🚢',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🚢',
      svgIcon: 'target',
      content: "India wasn't originally conquered by the British Government; it was conquered by a merciless corporation! \n\nIn the 1600s, the **British East India Company (EIC)** arrived as traders looking for spices. By the 1750s, using a private army, they began violently annexing Indian kingdoms (starting with Bengal at the Battle of Plassey in 1757). \nFor 100 years, a ruthless corporation ruled millions of Indians purely to extract wealth for London shareholders! 💰",
      highlight: "Imagine Amazon having its own military and conquering your entire country. That was the EIC. ⚔️",
    },
    {
      id: 'mutiny_1857',
      title: 'The First War of Independence (1857) 🧨',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🧨',
      svgIcon: 'zap',
      content: "In 1857, the Indian soldiers (Sepoys) working for the EIC finally snapped. \n\nThe immediate spark was a rumor that the new rifle cartridges were greased with cow and pig fat, deeply offending both Hindu and Muslim soldiers. But the real fire was 100 years of crushing taxes and racist oppression. \nThe **Revolt of 1857** was a massive, bloody uprising. Though the British brutally crushed it, the EIC was disbanded, and the British Crown directly took over India (The British Raj). 👑",
      highlight: "It proved that India could unite, planting the seed for total independence. 🌱",
    },
    {
      id: 'divide_and_rule',
      title: 'Divide & Rule ⚖️',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'shield',
      content: "How did 100,000 British rule 300 million Indians? Through the insidious policy of **Divide and Rule**. \n\nThe British realized that if Hindus and Muslims united, the Empire would fall overnight. So, they deliberately fueled religious tension, favoring one group over the other in jobs and creating separate voting electorates. \nThey kept the population fighting each other so they were too distracted to fight their true oppressor. 🐍",
      highlight: "A divided house cannot overthrow its landlord. 🏰",
    },
    {
      id: 'enter_gandhi',
      title: 'Enter Mahatma Gandhi 👓',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '👓',
      svgIcon: 'user',
      content: "Mohandas K. Gandhi was a London-educated lawyer who spent 21 years fighting racism in South Africa. When he returned to India in 1915, he brought a revolutionary weapon: **Satyagraha (Truth-Force)**. \n\nGandhi realized violent rebellion was suicide against British machine guns. Instead, he proposed *Non-Violent Non-Cooperation*. \nIf 300 million Indians simply refused to work, refused to buy British clothes, and refused to pay taxes, the Empire would paralyze and collapse financially! 🛑",
      highlight: "First they ignore you, then they laugh at you, then they fight you, then you win. 🕊️",
    },
    {
      id: 'jallianwala_bagh',
      title: 'The Jallianwala Bagh Massacre (1919) 🩸',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🩸',
      svgIcon: 'alert',
      content: "On April 13, 1919, thousands of unarmed men, women, and children gathered peacefully in Amritsar to celebrate a festival and protest draconian new laws. \n\nWithout warning, British General Reginald Dyer ordered his troops to block the only exit and open fire on the trapped crowd until they ran out of ammunition. Over 379 innocent people were slaughtered (Indian numbers suggest over 1,000). \nThis horrific atrocity permanently alienated Indians; any lingering trust in British 'justice' was dead. ☠️",
      highlight: "The massacre turned millions of loyal subjects into furious revolutionaries. 🔥",
    },
    {
      id: 'non_cooperation',
      title: 'Non-Cooperation Movement (1920) 🚫',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🚫',
      svgIcon: 'lock',
      content: "Following the massacre, Gandhi launched the **Non-Cooperation Movement**. \n\nHe asked Indians to drop out of British schools, resign from government jobs, and most importantly, boycott British cotton. Indians started spinning their own cloth (**Khadi**) on simple wooden wheels (Charkhas). \nBy burning imported British textiles, they hit the Empire where it hurt most: the wallet. The British economy bled millions of pounds! 💸",
      highlight: "The Charkha (spinning wheel) became the ultimate symbol of economic independence. 🎡",
    },
    {
      id: 'chauri_chaura',
      title: 'Chauri Chaura & The Pause 🛑',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🛑',
      svgIcon: 'waves',
      content: "The Non-Cooperation movement was working brilliantly. But in 1922, an angry Indian mob in Chauri Chaura chased 22 British police officers into a station and burned them alive. \n\nGandhi did the unthinkable: **He called off the entire national movement!** \nWhy? Because Satyagraha required ABSOLUTE non-violence. He knew that if the movement became violent, the British would use it as an excuse to unleash their military and slaughter millions. He went on a hunger strike to repent for the violence. 🛡️",
      highlight: "To win the moral war, the movement had to remain perfectly pure. ✨",
    },
    {
      id: 'bhagat_singh',
      title: 'Bhagat Singh: The Firebrand 🔥',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔥',
      svgIcon: 'star',
      content: "Not everyone agreed with Gandhi's peaceful approach! \n\n**Bhagat Singh** was a brilliant, Marxist revolutionary who believed the British would never leave without experiencing fear. He famously threw a non-lethal smoke bomb into the Central Legislative Assembly, not to kill, but 'to make the deaf hear'. \nHe was hanged by the British at age 23, dying with a smile on his face while reading Lenin. He became an immortal martyr for the youth! 🧨",
      highlight: "While Gandhi provided the patience, Bhagat Singh provided the fiery soul of the youth! ❤️‍🔥",
    },
    {
      id: 'salt_march',
      title: 'The Salt March (1930) 🧂',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🧂',
      svgIcon: 'cloud',
      content: "The British held a monopoly on Salt. It was illegal for Indians to make or sell it, and it was heavily taxed. \n\nIn a stroke of PR genius, Gandhi marched 240 miles to the sea at Dandi. When he arrived, he reached down, picked up a handful of muddy salt, and broke the law. \nInstantly, millions of Indians began making illegal salt. The British arrested 60,000 peaceful people. The world watched in horror as armed police beat unarmed, non-resisting Indians. The British lost the PR war forever. 🌍",
      highlight: "With a pinch of salt, he shook the foundations of the British Empire. 🏛️",
    },
    {
      id: 'subhas_chandra_bose',
      title: 'Netaji Subhas Chandra Bose 🦅',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🦅',
      svgIcon: 'target',
      content: "**Netaji Bose** was a fierce patriot who fiercely disagreed with Gandhi. \n\nWhen WW2 broke out, Bose believed 'the enemy of my enemy is my friend'. He dramatically escaped house arrest, traveled to Germany, and eventually Japan, to raise the **Indian National Army (INA)** from captured Indian POWs. \nHe planned to march into India and violently overthrow the British! While his army was defeated, his sheer audacity terrified the British military. ⚔️",
      highlight: "'Give me blood, and I shall give you freedom!' 🩸",
    },
    {
      id: 'quit_india',
      title: 'Quit India Movement (1942) 🚪',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🚪',
      svgIcon: 'alert',
      content: "Amidst the chaos of WW2, Gandhi gave his final, ultimate ultimatum to the British Empire: **'Quit India.'** \n\nHe gave the mantra 'Do or Die.' The British arrested the entire Congress leadership on the very first night. Leaderless, the country erupted into spontaneous, massive riots, strikes, and sabotage of railways. \nThe British realized that ruling India was becoming financially and militarily impossible. 📉",
      highlight: "It was the final nail in the coffin of British imperialism. 🔨",
    },
    {
      id: 'naval_mutiny',
      title: 'The Naval Mutiny (1946) ⚓',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⚓',
      svgIcon: 'waves',
      content: "The history books often forget this, but this was the breaking point. \n\nIn 1946, 20,000 Indian sailors in the Royal Indian Navy mutinied against their British officers, taking over 78 ships. The mutiny spread to the air force and army. \nThe British Prime Minister Clement Attlee realized the terrifying truth: The British military could no longer trust the Indian soldiers to oppress their own people. Without the Indian army, the British had zero power. It was over. 🚢",
      highlight: "When the sword refuses to strike, the Empire is finished. 🗡️",
    },
    {
      id: 'ambedkar_constitution',
      title: 'B.R. Ambedkar & The Constitution 📜',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '📜',
      svgIcon: 'book',
      content: "Freedom from the British wasn't enough; India needed freedom from internal oppression. \n\n**Dr. B.R. Ambedkar**, a brilliant scholar born into the heavily oppressed 'Untouchable' (Dalit) caste, became the chief architect of the Indian Constitution. \nHe fought relentlessly for the rights of minorities and women, drafting a visionary document that united a staggeringly diverse nation under a central democratic law! ⚖️",
      highlight: "Political tyranny is nothing compared to social tyranny. (B.R. Ambedkar) 🏛️",
    },
    {
      id: 'the_partition',
      title: 'The Tragedy of Partition (1947) 💔',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '💔',
      svgIcon: 'shield',
      content: "Independence arrived on August 15, 1947, but it came with a bleeding scar. \n\nThe British 'Divide & Rule' policy, combined with political stubbornness, led to the horrific **Partition**. The country was sliced apart along religious lines to create Hindu-majority India and Muslim-majority Pakistan. \nOver 15 million people were uprooted overnight, and up to 2 million were killed in sectarian riots. Gandhi, heartbroken, skipped the independence celebrations to fast for peace in the riot-torn streets. 🥀",
      highlight: "Freedom came at midnight, bathed in tears. 🕰️",
    },
    {
      id: 'legacy_of_freedom',
      title: 'The Legacy 🌍',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌍',
      svgIcon: 'star',
      content: "The Indian Freedom Struggle changed the world forever. \n\nIt was the beginning of the end for global colonialism. Dozens of nations in Africa and Asia followed India's lead and demanded independence. \nFurthermore, Gandhi's blueprint of non-violent civil disobedience was studied and directly used by **Martin Luther King Jr.** in the American Civil Rights Movement, and by Nelson Mandela in South Africa! 🕊️",
      highlight: "A single man in a dhoti changed the moral axis of the 20th century. ✨",
    },
  ],

  lab: {
    title: "The Satyagraha Scale ⚖️🕊️",
    description: "Welcome to the Resistance Simulator (1920-1947). You are organizing the freedom movement. You must deploy 'Non-Violent Protests' (Boycotts, Salt Marches) to drain the British Economy. BUT, as their economy drops, the 'Empire Panic' meter rises, leading to brutal military crackdowns. If you allow protests to turn violent (Chauri Chaura), the world will side with the British, and you lose. Can you reach 100% Economic Drain while keeping Violence at 0%? 📈",
    hint: "If the Empire Panic meter gets too high, you must intentionally 'Call Off the Movement' (like Gandhi did) to let tensions cool down, before launching an even bigger boycott later!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Geopolitical PR algorithms, Imperial Treasury flow rates, and kinetic radicalization thresholds.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the British initially forced Indians to grow Indigo (a blue dye)? 🔵",
      answer: "The European textile industry was booming, and they needed blue dye for jeans and military uniforms. The British forced Indian farmers to grow Indigo instead of food crops, and paid them pennies. This caused massive artificial famines! Gandhi's first major Satyagraha experiment in India (Champaran in 1917) was specifically to free these Indigo farmers! 👕",
      emoji: '🌾',
    },
    {
      id: 'dyk2',
      question: "Do you know why Gandhi chose to protest SALT of all things? 🧂",
      answer: "PR Genius! Congress leaders originally wanted to protest complex land taxes, which the poor didn't fully understand. But *everyone* needs salt to survive in the Indian heat. The cruel British salt tax affected the poorest begger just as much as the richest merchant. Salt unified 300 million people under a single, easily understood symbol of injustice! 🏖️",
      emoji: '🧠',
    },
    {
      id: 'dyk3',
      question: "Do you know why Winston Churchill absolutely hated Gandhi? 🇬🇧",
      answer: "Churchill was a fierce imperialist who believed the British Empire was biologically superior and destined to rule. He found it deeply humiliating that a 'half-naked fakir' was successfully destroying the greatest empire on Earth without weapons. Churchill famously allowed millions to die in the 1943 Bengal Famine without sending aid. 💀",
      emoji: '🎩',
    },
    {
      id: 'dyk4',
      question: "Do you know why Gandhi spun cotton on a wheel every single day? 🎡",
      answer: "The British had destroyed India's native textile industry! They took cheap cotton from India, milled it in UK factories, and sold it back to Indians at high prices. By spinning his own Khadi cloth daily, Gandhi was telling Indians: 'We do not need their factories. We can clothe ourselves. We can collapse their economy with our own two hands.' 🧶",
      emoji: '👕',
    },
    {
      id: 'dyk5',
      question: "Do you know why Bhagat Singh chose to get arrested after bombing the assembly? 🧨",
      answer: "He wanted the courtroom! If he escaped, he would just be labeled a 'faceless terrorist' by the British media. By surrendering willingly, he used the highly-publicized British trial to deliver massive, fiery speeches against imperialism that were printed in every newspaper across India! He turned the courtroom into a mega-phone for revolution! 📰",
      emoji: '🗣️',
    },
    {
      id: 'dyk6',
      question: "Do you know why the Indian National Army (INA) terrified the British so much, even after they were defeated? ⚔️",
      answer: "The Red Fort Trials! When the British tried to execute the captured INA soldiers for treason in 1945, the entire Indian population (Hindus, Muslims, and Sikhs) united in absolute fury to defend them. The British realized that the Indian military and police were now actively sympathetic to the rebels. The Empire's sword had turned against them! 🛡️",
      emoji: '🦅',
    },
    {
      id: 'dyk7',
      question: "Do you know why Gandhi never won the Nobel Peace Prize? 🏅",
      answer: "European Bias! The Nobel committee nominated him 5 times but never gave it to him. At the time, giving the prize to a man actively destroying a European empire was considered 'too radical'. Decades later, the Nobel committee publicly admitted omitting Gandhi was their greatest historical mistake! 🕊️",
      emoji: '❌',
    },
    {
      id: 'dyk8',
      question: "Do you know why the British actually left in 1947? (It wasn't just out of the goodness of their hearts!) 🇬🇧",
      answer: "World War 2 bankrupted them! Britain was utterly devastated by Hitler's bombings. They were deeply in debt to the USA. Meanwhile, India was an absolute powder keg of riots and naval mutinies. The British literally could no longer afford the money or the troops required to hold onto an explosive continent! 💥",
      emoji: '📉',
    },
    {
      id: 'dyk9',
      question: "Do you know why January 26 is Republic Day, but August 15 is Independence Day? 🗓️",
      answer: "India gained independence on Aug 15, 1947. However, the Constitution wasn't ready! For 3 years, India was a 'Dominion' using British laws. On January 26, 1950, Dr. Ambedkar's majestic Constitution was officially adopted, severing the last legal tie to the British Crown and turning India into a fully sovereign Republic! 📜",
      emoji: '🇮🇳',
    },
    {
      id: 'dyk10',
      question: "Do you know why Gandhi was assassinated by an Indian? 🔫",
      answer: "Nathuram Godse was an extremist who blamed Gandhi for the Partition of India and Pakistan. He was furious that Gandhi forced the Indian government (via a hunger strike) to release 550 million rupees to Pakistan after independence. Godse saw Gandhi's extreme pacifism and tolerance as a weakness that betrayed the nation. 💔",
      emoji: '🥀',
    },
  ],

  quiz: [
    { id: 'q1', question: "Which corporate entity initially conquered and ruled India before the British Crown took over?", options: ["The Royal Navy", "The East India Company", "The Dutch Bank", "The Hudson Bay Company"], answer: 1, explanation: "A corporation with a private army extracted wealth for London shareholders! 🚢" },
    { id: 'q2', question: "What was the spark that ignited the 1857 Mutiny (First War of Independence)?", options: ["High taxes on tea", "Greased rifle cartridge rumors", "New religious laws", "Severe local droughts"], answer: 1, explanation: "It deeply offended both Hindu and Muslim Sepoys, triggering a massive rebellion. 🧨" },
    { id: 'q3', question: "How did 100,000 British manage to rule 300 million Indians?", options: ["Superior military technology", "Divide and rule policy", "Widespread economic support", "Advanced medical care"], answer: 1, explanation: "A divided house cannot overthrow its landlord! 🐍" },
    { id: 'q4', question: "What is 'Satyagraha'?", options: ["A traditional weapon", "Non-violent truth force", "A religious text", "A political treaty"], answer: 1, explanation: "You don't fight fire with fire; you fight it with water! 🕊️" },
    { id: 'q5', question: "The horrific 1919 Jallianwala Bagh Massacre resulted in:", options: ["A formal peace treaty", "Massacre of unarmed civilians", "New educational reforms", "Reduced colonial taxes"], answer: 1, explanation: "It turned millions of loyal subjects into furious revolutionaries overnight. 🩸" },
    { id: 'q6', question: "During the Non-Cooperation movement, why did Indians burn British clothes and spin their own 'Khadi' cloth?", options: ["To survive cold winters", "To achieve economic independence", "To follow religious traditions", "To create new jobs"], answer: 1, explanation: "Economic boycotts are more powerful than bullets! 🧶" },
    { id: 'q7', question: "Why did Gandhi bizarrely call off the massive Non-Cooperation movement after the Chauri Chaura incident?", options: ["He lost public support", "Protesters turned to violence", "The British offered concessions", "He fell seriously ill"], answer: 1, explanation: "If it turned violent, the British could justify sending in tanks! 🛑" },
    { id: 'q8', question: "Bhagat Singh threw a non-lethal smoke bomb into the assembly because:", options: ["He hated the architecture", "To publicize revolutionary ideas", "He made a mistake", "To cause physical harm"], answer: 1, explanation: "He turned the courtroom into a mega-phone for revolution! 🗣️" },
    { id: 'q9', question: "Why was Gandhi's 1930 'Salt March' an absolute PR masterclass?", options: ["Salt was very valuable", "It unified the masses", "Salt improved public health", "It was easy to carry"], answer: 1, explanation: "With a pinch of salt, he shook the foundations of an empire! 🧂" },
    { id: 'q10', question: "Subhas Chandra Bose (Netaji) believed in:", options: ["Strict non-violent protest", "Armed struggle for freedom", "Diplomatic letter writing", "Passive civil disobedience"], answer: 1, explanation: "'Give me blood, and I shall give you freedom!' 🦅" },
    { id: 'q11', question: "The 1942 'Quit India' movement gave the masses which famous slogan?", options: ["Quit India Now", "Do or Die", "Freedom at Last", "Victory for All"], answer: 1, explanation: "It led to massive, leaderless sabotage of British infrastructure across the country. 🚪" },
    { id: 'q12', question: "What terrifying 1946 event finally convinced the British that they could not hold India?", options: ["A royal decree", "The Royal Naval Mutiny", "A massive cyclone", "A general election"], answer: 1, explanation: "When the sword refuses to strike, the Empire is finished! ⚓" },
    { id: 'q13', question: "Dr. B.R. Ambedkar was the chief architect of:", options: ["The Taj Mahal", "The Indian Constitution", "The British Raj", "The Indian Navy"], answer: 1, explanation: "Political freedom means nothing without social equality! 📜" },
    { id: 'q14', question: "The 1947 Partition tragically resulted in:", options: ["A national celebration", "Mass migration and violence", "Extended British rule", "New infrastructure projects"], answer: 1, explanation: "Freedom came at midnight, bathed in tears. 💔" },
    { id: 'q15', question: "Martin Luther King Jr. famously modeled the American Civil Rights Movement on:", options: ["The French Revolution", "Gandhi's non-violent strategy", "The Russian Revolution", "The Roman Empire"], answer: 1, explanation: "A single man in a dhoti changed the moral axis of the 20th century! 🌍" },
    { id: 'q16', question: "Why did Winston Churchill hate Gandhi so much?", options: ["Personal cultural differences", "Gandhi challenged the Empire", "A dispute over land", "Conflicting military strategies"], answer: 1, explanation: "Churchill believed the British were biologically meant to rule over India. 🇬🇧" },
    { id: 'q17', question: "The British forced Indian farmers to grow 'Indigo' instead of food, which caused:", options: ["Better soil quality", "Massive artificial famines", "Increased livestock health", "Higher farmer profits"], answer: 1, explanation: "Extracting wealth while millions starved! 🌾" },
    { id: 'q18', question: "Ultimately, why did the British leave in 1947?", options: ["They lost interest", "Post-war economic bankruptcy", "The climate was difficult", "A diplomatic agreement"], answer: 1, explanation: "The empire was financially drained and militarily exhausted by Hitler! 📉" },
    { id: 'q19', question: "Why is January 26 celebrated as Republic Day?", options: ["A random selection", "Enactment of the Constitution", "Gandhi's official birthday", "The British departure"], answer: 1, explanation: "Severing the final legal tie to the British crown! 🇮🇳" },
    { id: 'q20', question: "Why did Nathuram Godse assassinate Gandhi?", options: ["Desire for financial gain", "Opposition to Gandhi's policies", "A tragic accident", "Personal political fame"], answer: 1, explanation: "He hated Gandhi's insistence on paying out 550 million rupees to Pakistan. 🔫" },
  ],

  relatedTopics: ['ancient_civilizations', 'world_wars', 'industrial_revolution'],
};
