// ─────────────────────────────────────────────────────────
//  TOPIC: BASIC UNDERSTANDING
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'basic_understanding',
  title: 'Basic Understanding',
  subtitle: 'Self-awareness, Metacognition, & Blind Spots 🪞🧠',
  emoji: '🪞',
  category: 'Society',
  accentKey: 'awareness',

  hook: {
    question: "Do you think you know yourself better than anyone else does? 👁️",
    reveal: "Science disagrees! Studies show that your friends and family are often much better at predicting your behavior than you are. This is because of the 'Introspection Illusion'. You judge YOURSELF based on your internal intentions ('I meant to be nice!'), while the rest of the world judges you purely on your external actions ('You yelled!'). Welcome to the final pillar: True self-awareness and the mastery of the mind. Let's map your blind spots! 🗺️💡",
    emoji: '🧭',
  },

  theory: [
    {
      id: 'metacognition',
      title: 'Metacognition 🧠',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧠',
      svgIcon: 'eye',
      content: "Humans have a superpower that (as far as we know) no other animal possesses: **Metacognition**. \n\nMetacognition is *thinking about thinking*. You can literally hover above your own brain and evaluate your thoughts. When you get angry, a dog just bites. But a human can pause and say, 'Why am I angry right now? Am I actually just hungry?' \nThis fraction of a second between stimulus and response is the birthplace of all human freedom! 🕊️",
      highlight: "Between stimulus and response, there is a space. In that space is our power to choose our response. (Viktor Frankl) ⚡",
    },
    {
      id: 'the_johari_window',
      title: 'The Johari Window 🪟',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🪟',
      svgIcon: 'grid',
      content: "Created by Joseph Luft and Harrington Ingham (Jo-Hari), this framework divides your identity into 4 rooms:\n\n1. **Open Area:** Things both YOU and OTHERS know about you (e.g., your eye color, your job). ☀️\n2. **Hidden Area:** Things YOU know, but keep secret from others (fears, trauma). 🕵️‍♂️\n3. **Blind Area:** Things OTHERS know about you, but you don't realize (you interrupt people, you play with your hair when nervous). 🙈\n4. **Unknown:** Things nobody knows yet (untested potential). 🌌",
      highlight: "Self-awareness is the process of shrinking your Blind and Hidden areas to expand the Open Area! 🔓",
    },
    {
      id: 'the_blind_spot',
      title: 'Shrinking the Blind Spot 🙈',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🙈',
      svgIcon: 'target',
      content: "How do you shrink the Blind Area in the Johari Window? \n\nThere is only one way: **Feedback**. You cannot see what you cannot see. You must actively ask other people to hold up a mirror. \n'Hey, what is something I do that annoys you?' \nThis requires massive ego-strength because the ego hates criticism! But a high-level mind craves feedback because it is the only way to upgrade the software. 🛠️",
      highlight: "Feedback is the breakfast of champions. Don't defend yourself; just listen! 🥞",
    },
    {
      id: 'emotional_intelligence',
      title: 'Emotional Intelligence (EQ) ❤️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '❤️',
      svgIcon: 'heart',
      content: "IQ measures logic. **EQ (Emotional Intelligence)** measures how well you handle yourself and others. \n\nPsychologist Daniel Goleman broke EQ into 4 pillars:\n1. **Self-Awareness:** Knowing what you feel. 🤔\n2. **Self-Management:** Controlling your impulses. 🛑\n3. **Social Awareness:** Empathy (reading the room). 👁️\n4. **Relationship Management:** Communicating effectively. 💬\n\nStudies show EQ is vastly more important than IQ for career success and happiness! 📈",
      highlight: "A genius with zero emotional control will eventually self-destruct. 💥",
    },
    {
      id: 'introspection_illusion',
      title: 'The Introspection Illusion 🪞',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🪞',
      svgIcon: 'lock',
      content: "Why are we so bad at evaluating ourselves? \n\nThe **Introspection Illusion**. When assessing our own character, we heavily weigh our *intentions*. ('I intended to call my mom, so I am a good son'). \nBut when evaluating *others*, we have no access to their intentions! We can only judge their *actions*. ('He didn't call his mom, he is a terrible son!'). \nWe judge ourselves by our invisible ideals, while the world judges us by our visible actions. ⚖️",
      highlight: "You are what you DO, not what you intended to do. 🏃‍♂️",
    },
    {
      id: 'attachment_theory',
      title: 'Attachment Styles 🔗',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🔗',
      svgIcon: 'users',
      content: "Your 'Basic Understanding' is heavily influenced by how you were raised. **Attachment Theory** argues that early childhood shapes how you treat adults later:\n\n• **Secure:** Comfortable with intimacy. Trusting. 💚\n• **Anxious:** Terrified of abandonment; constantly needs reassurance. 💔\n• **Avoidant:** Equates intimacy with a loss of independence; pushes people away when they get too close. 🛡️\n\nRecognizing your style allows you to stop repeating toxic patterns! 🔄",
      highlight: "Your childhood wrote the script. Self-awareness lets you rewrite it. ✍️",
    },
    {
      id: 'fixed_vs_growth',
      title: 'Fixed vs Growth Mindset 🪴',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🪴',
      svgIcon: 'refresh',
      content: "Carol Dweck's research revealed two operating systems for the brain:\n\n1. **Fixed Mindset:** 'I am either smart or dumb. Talent is genetic.' A fixed mindset avoids challenges because failure mathematically proves they are 'dumb'. 🧱\n2. **Growth Mindset:** 'The brain is a muscle. I can learn anything with effort.' A growth mindset loves failure because failure is just data required for the next attempt! 🚀",
      highlight: "Stop saying 'I am bad at math.' Start saying 'I am not good at math YET.' ⏳",
    },
    {
      id: 'imago_theory',
      title: 'Projecting the Imago 👻',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '👻',
      svgIcon: 'cloud',
      content: "Why do you keep dating the exact same toxic person over and over? \n\nPsychology calls this the **Imago**. Your subconscious builds a composite image of the love you received as a child (including the flaws, like a distant father or anxious mother). As an adult, you subconsciously seek out partners who match this flawed blueprint because it feels *familiar*, and the brain prefers painful familiarity over safe un-familiarity. 🏡\nAwareness breaks the cycle! 🔨",
      highlight: "We don't seek what makes us happy; we seek what feels familiar. 🔄",
    },
    {
      id: 'active_listening',
      title: 'Active Listening 👂',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '👂',
      svgIcon: 'waveform',
      content: "Most people do not listen to understand; they listen to reply! \n\n**Active Listening** is a rare, high-level skill. It means:\n1. Putting your phone down. 🚫📱\n2. Not interrupting. 🤐\n3. Reflecting back: 'What I hear you saying is that you felt ignored. Is that right?' 🪞\nIt validates the other person's reality. Empathy isn't agreeing with them; it is proving that you comprehend their emotional state! 🤝",
      highlight: "Being truly heard is so close to being loved that the brain cannot tell the difference. ❤️",
    },
    {
      id: 'the_shadow',
      title: 'Carl Jung’s Shadow 🌘',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌘',
      svgIcon: 'shield',
      content: "Carl Jung believed we all have a **Shadow**—the dark, suppressed, 'unacceptable' parts of our personality (anger, selfishness, lust). \n\nMost people shove their shadow into the basement and pretend it doesn't exist. This is dangerous! Unacknowledged shadows leak out as passive-aggression or explode in mid-life crises. \nJung said we must 'integrate' the shadow. Acknowledge your capacity for darkness, and tame it. A monster you tame is a monster that works for you! 🐉",
      highlight: "A harmless man is not a good man. A good man is a very dangerous man who has that under voluntary control. ⚔️",
    },
    {
      id: 'imposter_syndrome',
      title: 'The Inner Critic 🗣️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🗣️',
      svgIcon: 'alert',
      content: "Everyone has a voice in their head. Sadly, for most people, that voice is an abusive tyrant. \n\nThe **Inner Critic** constantly tells you that you are ugly, stupid, or a fraud. If a friend spoke to you the way you speak to yourself, you would cut them out of your life immediately! \nSelf-awareness allows you to separate 'You' from 'The Voice.' You are the sky; the anxious thoughts are just passing clouds. ☁️",
      highlight: "Don't believe everything you think. The brain lies constantly! 🤥",
    },
    {
      id: 'neuroplasticity',
      title: 'Neuroplasticity 🧬',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧬',
      svgIcon: 'brain',
      content: "For a long time, scientists thought the brain stopped growing at age 25. \n\nWe now know about **Neuroplasticity**. Every time you think a new thought, learn a new skill, or practice gratitude, physical neurons fire and wire together, literally changing the anatomical structure of your brain! \nYou are not completely fixed. You are a biological clay that can mold itself until the day you die! 🏺",
      highlight: "'Neurons that fire together, wire together. Neurons that fire apart, wire apart.' ⚡",
    },
    {
      id: 'the_end_of_history',
      title: 'The End of History Illusion ⏳',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⏳',
      svgIcon: 'chart',
      content: "If I ask a 30-year-old: 'How much have you changed since you were 20?', they say, 'Massively! I am a totally different person.'\n\nIf I ask that same 30-year-old: 'How much will you change between now and 40?', they say, 'Not much. I pretty much figured out who I am.' \nThis is the **End of History Illusion**. We acknowledge past growth, but foolishly assume our present self is the final, finished product. You are always under construction! 🏗️",
      highlight: "Human beings are works in progress that mistakenly think they are finished. 🎨",
    },
    {
      id: 'flow_state',
      title: 'The Flow State 🌊',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🌊',
      svgIcon: 'zap',
      content: "When is the human brain happiest? When it is in **Flow** (discovered by Mihaly Csikszentmihalyi). \n\nFlow happens when you are doing a task that is difficult enough to demand 100% of your focus, but not so insanely difficult that it causes anxiety. \nIn Flow, the Prefrontal Cortex actually deactivates (Transient Hypofrontality). Your inner critic shuts down, the sense of 'time' vanishes, and you merge completely with the activity! ⛷️",
      highlight: "Happiness isn't relaxing on a beach. Happiness is total engagement in a meaningful struggle. 🧗‍♂️",
    },
    {
      id: 'the_final_frontier',
      title: 'The Final Frontier 🌌',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌌',
      svgIcon: 'compass',
      content: "We have mapped the stars, split the atom, and built the internet. \n\nBut the most complex structure in the known universe is sitting right between your ears. There are more neural connections in your brain than there are stars in the Milky Way galaxy. \nBasic Understanding means realizing that mastering the external world means nothing if you have not mastered your internal world. The journey inward is the ultimate adventure! 🚀🧘‍♂️",
      highlight: "He who conquers others is strong; He who conquers himself is mighty. (Lao Tzu) ⛰️",
    },
  ],

  lab: {
    title: "Johari Window Mapper 🪟🧩",
    description: "Welcome to your Psychological Grid. Below are 4 personality traits. Your goal is to map them into the correct 'Room' of the Johari Window. Remember: The Open Area is known to both. The Blind Spot is known only to others. The Hidden Area is your secret. And the Unknown is yet to be discovered. Sort them correctly to shrink the void! 🗺️",
    hint: "If a trait says: 'A dark childhood fear you never told anyone', it belongs in the Hidden Area! If it says 'Your annoying habit of tapping your foot that you don't realize you do', it belongs in the Blind area!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Introspection-Asymmetry coefficients and DMN (Default Mode) predictive coding mismatches.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why thinking wastes so much physical energy? 🔋",
      answer: "The brain is extremely expensive! It only accounts for 2% of your body weight, but it burns 20% of your daily calories (glucose). Hard metacognition literally depletes your blood sugar, which is why you feel physically exhausted after a difficult math exam even though you were just sitting in a chair! 🍫",
      emoji: '🧠',
    },
    {
      id: 'dyk2',
      question: "Do you know why we get our best ideas in the shower? 🚿",
      answer: "The Default Mode Network (DMN)! When you are intensely focusing on a spreadsheet, the DMN is turned off. But when you do a mindless task (showering, washing dishes, walking), the DMN turns on. It acts as a massive background processing system, connecting random memories and thoughts together, leading to sudden 'AHA!' moments! 💡",
      emoji: '🛁',
    },
    {
      id: 'dyk3',
      question: "Do you know why writing down your feelings reduces anxiety? 📝",
      answer: "Affect Labeling! When anxiety spikes in the emotional Amygdala, writing it out forces the logical Prefrontal Cortex to turn on (because language is logical). The Prefrontal Cortex acts like a brake pedal, physically sending inhibitory signals to the Amygdala to calm it down. Journaling is biological therapy! 📓",
      emoji: '🛑',
    },
    {
      id: 'dyk4',
      question: "Do you know why you hate the sound of your own recorded voice? 🎧",
      answer: "Bone Conduction! When you speak, you hear two things: the sound traveling through the air, AND the sound vibrating through your massive skull bones. Bone conduction lowers the pitch, making your voice sound deep and rich to YOU. A microphone only captures the high-pitch air vibrations, which sounds thin and completely alien! 🎤",
      emoji: '🦴',
    },
    {
      id: 'dyk5',
      question: "Do you know why it's so hard to read someone's sarcasm over a text message? 📱",
      answer: "Loss of Para-linguistics! 93% of human emotional communication is non-verbal (body language, tone of voice, facial micro-expressions). Texting strips away 93% of the biological data package, leaving only the raw, dry text. Your brain is essentially blindfolded, which leads to massive misinterpretations! 🙈",
      emoji: '📵',
    },
    {
      id: 'dyk6',
      question: "Do you know why forcing a fake smile actually tricks your brain into being happier? 😁",
      answer: "Facial Feedback Hypothesis! The connection goes both ways. Being happy makes you smile, but smiling also signals the brain: 'Hey, the face muscles are contracting, we must be happy!' The brain releases a tiny bit of dopamine to match the physical state of the face. Biology is a two-way street! 🛣️",
      emoji: '🌝',
    },
    {
      id: 'dyk7',
      question: "Do you know why toddlers constantly throw tantrums? 🤬",
      answer: "The Prefrontal Cortex (the brain's logic and impulse-control center) doesn't finish developing until age 25! A toddler has a fully formed emotional Amygdala but literally NO neurological brake pedal to stop the emotion. A tantrum isn't them being 'bad'; it's a hardware limitation! 👶",
      emoji: '🧠',
    },
    {
      id: 'dyk8',
      question: "Do you know why we conform to group opinions even when we know the group is wrong? 🐑",
      answer: "Evolutionary exile! In ancient times, being kicked out of the tribe meant absolute death by starvation or predators. The brain evolved to view 'social rejection' as equivalent to physical death. The anterior cingulate cortex actually produces physical pain when we steps out of line with the group! 💥",
      emoji: '🏔️',
    },
    {
      id: 'dyk9',
      question: "Do you know why 'venting' anger by punching a pillow is actually scientifically terrible advice? 🥊",
      answer: "It reinforces the neural pathway! Studies show that venting anger physically doesn't 'release' it (like steam in a kettle). Instead, it trains your brain to associate anger with physical violence. People who punch pillows actually become MORE aggressive in the long run. To calm down, it is better to distract or meditate! 🧘‍♂️",
      emoji: '🔥',
    },
    {
      id: 'dyk10',
      question: "Do you know why learning a second language delays Dementia and Alzheimer's by up to 5 years? 🇪🇸",
      answer: "Cognitive Reserve! Learning a complex skill like a language forces the brain to build incredibly dense networks of new physical neurons. Even if Alzheimer's starts destroying parts of the brain later in life, the brain has built so many 'backup roads' (neuroplasticity) that it can route thoughts around the damage for years! 🛣️",
      emoji: '🧠',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is 'Metacognition'?", options: ['A superhero', 'Thinking about thinking (the ability to observe and evaluate your own thoughts)', 'Fast driving', 'Sleep walking'], answer: 1, explanation: "It is the fraction of a second between stimulus and response where human freedom lives! 🧠" },
    { id: 'q2', question: "In the Johari Window, what is the 'Blind Area'?", options: ['A dark room', 'Things OTHERS know about you, but YOU don\'t realize about yourself', 'A secret', 'Your name'], answer: 1, explanation: "Like having spinach in your teeth... everyone sees it but you! 🙈" },
    { id: 'q3', question: "How do you shrink your Blind Area?", options: ['Closing your eyes', 'By asking for and accepting honest Feedback from others', 'Yelling', 'Running'], answer: 1, explanation: "You must rely on other people to act as your mirror! 🪞" },
    { id: 'q4', question: "What does EQ (Emotional Intelligence) measure that IQ does not?", options: ['Math skills', 'Self-awareness, empathy, and the ability to manage impulses and relationships', 'Typing speed', 'Height'], answer: 1, explanation: "A genius without EQ will self-destruct! ❤️" },
    { id: 'q5', question: "The Introspection Illusion explains that we judge ourselves based on our _________, but judge others based on their _________.", options: ['Shoes, Hats', 'Intentions, Actions', 'Words, Money', 'Age, Height'], answer: 1, explanation: "I meant to be nice (Intention) vs You yelled at me (Action)! ⚖️" },
    { id: 'q6', question: "According to Attachment Theory, someone who pushes partners away when things get 'too close' has an:", options: ['Anxious attachment', 'Avoidant attachment', 'Secure attachment', 'Sticky attachment'], answer: 1, explanation: "They equate intimacy with a terrifying loss of independence! 🛡️" },
    { id: 'q7', question: "A 'Growth Mindset' (Carol Dweck) is the belief that:", options: ['You are permanently dumb', 'Intelligence and skills are like muscles that can be developed through effort and failure', 'Plants are nice', 'Money is easy'], answer: 1, explanation: "Failure is just data! You aren't bad at it, you just aren't good at it YET. 🚀" },
    { id: 'q8', question: "What is 'Active Listening'?", options: ['Listening while running', 'Fully focusing, not interrupting, and reflecting back to prove you comprehended the emotional state', 'Ignoring them', 'Listening to music'], answer: 1, explanation: "Most people just listen to reply. Empathy requires listening to understand! 👂" },
    { id: 'q9', question: "Carl Jung warned that if we suppress our 'Shadow' (dark/selfish traits) entirely, it will:", options: ['Disappear', 'Leak out toxically or explode later in life; we must tame it instead', 'Turn white', 'Melt'], answer: 1, explanation: "A monster you tame is a monster that works for you! 🐉" },
    { id: 'q10', question: "What is Neuroplasticity?", options: ['Plastic surgery', 'The brain\'s ability to physically grow, rewire, and change its anatomical structure based on experience', 'Brain damage', 'A type of rock'], answer: 1, explanation: "You are not fixed; your brain is biological clay molding itself until you die! 🧠" },
    { id: 'q11', question: "The 'End of History Illusion' is the funny fact that human beings:", options: ['Hate history books', 'Acknowledge they changed in the past, but foolishly assume their present self is their \'final\' version', 'Live forever', 'Forget time'], answer: 1, explanation: "You are a work in progress that constantly thinks it is finished! 🏗️" },
    { id: 'q12', question: "What happens to the brain during a 'Flow State'?", options: ['It turns into a liquid', 'The prefrontal cortex deactivates, silencing the inner critic and merging you completely into the task', 'It falls asleep', 'It hurts'], answer: 1, explanation: "Transient Hypofrontality! The ego shuts off entirely. 🌊" },
    { id: 'q13', question: "Why do we get our best ideas in the shower?", options: ['Water is magical', 'Mindless tasks activate the Default Mode Network (DMN), a massive background processor that connects ideas', 'Soap cleans the brain', 'We are loud'], answer: 1, explanation: "The brain solves problems best when you stop staring intensely at them! 🚿" },
    { id: 'q14', question: "How does writing out your feelings (Affect Labeling) biological calm anxiety?", options: ['Pen ink is magic', 'Using language activates the logical Prefrontal Cortex, which sends a physical brake signal to the Amygdala', 'It wastes paper', 'It hurts your hand'], answer: 1, explanation: "Logic acts as a wet blanket on the fire of emotion! 📓" },
    { id: 'q15', question: "Why is 'venting' by punching a pillow a terrible idea?", options: ['Pillows are soft', 'It trains the brain to mistakenly associate anger with physical violence, making you more aggressive', 'It ruins feathers', 'It is loud'], answer: 1, explanation: "The brain doesn't 'release steam'; it builds neural pathways! 🥊" },
    { id: 'q16', question: "Why do toddlers throw terrible tantrums?", options: ['They are evil', 'Their Prefrontal Cortex (the logic/brake pedal) hasn\'t developed yet, so the Amygdala runs wild', 'They hate their parents', 'They are hungry'], answer: 1, explanation: "It is a hardware limitation, not a moral failure! 👶" },
    { id: 'q17', question: "The Facial Feedback hypothesis proves that:", options: ['Mirrors lie', 'Smiling artificially actually signals the brain to release dopamine, making you physically happier', 'Faces are hard', 'You need teeth'], answer: 1, explanation: "Biology is a two-way street! You can hack your emotion with your muscles. 😁" },
    { id: 'q18', question: "Why is texting terrible for emotional arguments?", options: ['Text is boring', 'Text strips away 93% of human communication (tone, body language), leaving the brain blind', 'Thumbs get tired', 'It costs data'], answer: 1, explanation: "Without the para-linguistics, the brain assumes the worst possible intention! 📵" },
    { id: 'q19', question: "Why do we hate the sound of our own recorded voice?", options: ['Microphones are cheap', 'Bone conduction in our skull makes our voice sound deep to us. A recording sounds thin and alien', 'We speak too loud', 'Ears are broken'], answer: 1, explanation: "You are hearing yourself purely through air for the first time! 🎧" },
    { id: 'q20', question: "What is 'Imago Theory' regarding toxic relationships?", options: ['Magic spells', 'Subconsciously seeking partners who match the flawed blueprint of your childhood because it feels \'familiar\'', 'Dating tall people', 'Hating romance'], answer: 1, explanation: "The brain prefers painful familiarity over safe un-familiarity until you become self-aware! 🔁" },
  ],

  relatedTopics: ['science_of_emotion', 'manipulation_tactics', 'mental_syndromes'],
};
