export default {
  id: 'immune_system',
  title: 'Immune System & Vaccines',
  subtitle: 'Your internal army of 37 billion soldiers 🛡️',
  emoji: '🛡️',
  category: 'Biology',
  accentKey: 'shield',

  hook: {
    question: "Did you know your immune system destroys over 1 million potentially cancerous cells in your body every single day? 🤯",
    reveal: "Your immune system is a military operation of staggering sophistication. It has memory, strategy, special forces, heavy artillery, and intelligence networks — all without a single conscious thought from you. Every second, it identifies millions of molecules, distinguishes friend from foe, and neutralises threats invisible to the naked eye. Understanding immunity isn't just biology — it's the key to vaccines, cancer treatment, and stopping pandemics. 🦠🛡️",
    emoji: '🛡️',
  },

  theory: [
    {
      id: 'two_lines',
      title: 'Two Lines of Defence 🏰',
      color: '#00D4FF',
      bgGradient: ['#081828', '#04070F'],
      icon: '🏰',
      svgIcon: 'shield',
      content: "The immune system has **two main divisions** that work together:\n\n🧱 **Innate Immunity (First Line)** — fast, non-specific, ancient:\n• Skin and mucous membranes (physical barriers)\n• Fever (makes body hostile to pathogens)\n• Inflammation (rushes blood and immune cells to wounds)\n• Phagocytes (cells that eat bacteria whole)\n• Natural Killer cells (destroy infected/cancer cells)\n• Responds in minutes to hours\n\n🎯 **Adaptive Immunity (Second Line)** — slow, highly specific, modern:\n• Takes 1-2 weeks to fully activate\n• Creates antibodies perfectly shaped for ONE specific pathogen\n• **Immunological memory** — remembers pathogens for decades\n• B-cells (make antibodies)\n• T-cells (killer T-cells destroy infected cells directly)\n\nThey constantly communicate and cooperate — innate immunity alerts adaptive immunity which pathogens to target! 📡",
      highlight: "Innate immunity responds within hours (non-specific); adaptive immunity takes 1-2 weeks but creates perfect antibodies and MEMORY! 🏰",
    },
    {
      id: 'antigens_antibodies',
      title: 'Antigens & Antibodies 🔑',
      color: '#FF9500',
      bgGradient: ['#1A0A00', '#04070F'],
      icon: '🔑',
      svgIcon: 'key',
      content: "**Antigens** are molecules on the surface of pathogens that the immune system recognises as foreign. Think of them as molecular 'name tags'.\n\n**Antibodies** (immunoglobulins) are Y-shaped proteins produced by B-cells, each perfectly shaped to grab ONE specific antigen — like a lock and key. 🗝️\n\n**How antibodies work:**\n🔒 **Neutralisation** — block pathogen from entering cells\n🏷️ **Opsonisation** — coat pathogen with flags that say 'eat me!' to phagocytes\n💥 **Complement activation** — trigger a cascade that lyses (pops) the pathogen\n🔗 **Agglutination** — stick multiple pathogens together, making them easier to engulf\n\n**5 antibody classes:**\nIgM — first antibody made (first responder)\nIgG — most abundant; crosses placenta (protects babies!)\nIgA — found in saliva, breast milk, mucus\nIgE — involved in allergies 🤧\nIgD — on B-cell surface; role still partially mysterious 🔮",
      highlight: "Antibodies are Y-shaped proteins — each one perfectly locks onto ONE specific antigen like a key to its lock! 🔑",
    },
    {
      id: 'b_and_t_cells',
      title: 'B-Cells & T-Cells: The Specialists 🎯',
      color: '#38BDF8',
      bgGradient: ['#0A1828', '#04070F'],
      icon: '🎯',
      svgIcon: 'target',
      content: "Both B-cells and T-cells are **lymphocytes** — white blood cells born in bone marrow. They are the adaptive immune system's special forces.\n\n**B-Cells (B for Bone marrow):**\n🦠 Each B-cell has unique receptors that match ONE specific antigen\n💉 When activated, they become **Plasma cells** — antibody factories producing 2,000 antibodies per second!\n🧠 Some become **Memory B-cells** that persist for decades\n\n**T-Cells (T for Thymus — where they mature):**\n🔴 **Helper T-cells (CD4+)** — coordinate the immune response; activate B-cells and Killer T-cells; these are the cells HIV destroys!\n💀 **Cytotoxic T-cells (CD8+)** — directly kill infected cells and tumour cells by injecting proteins that trigger apoptosis\n🛑 **Regulatory T-cells** — put the brakes on immune responses to prevent autoimmunity\n\n**Clonal selection:** When a B or T-cell finds its antigen, it rapidly divides to create millions of identical copies — an army perfectly trained against that specific enemy! 🪖",
      highlight: "Plasma cells produce 2,000 antibodies per second — HIV destroys Helper T-cells, collapsing the entire immune response! 🎯",
    },
    {
      id: 'vaccines',
      title: 'How Vaccines Work 💉',
      color: '#22C55E',
      bgGradient: ['#052010', '#04070F'],
      icon: '💉',
      svgIcon: 'heart',
      content: "**Vaccines** are the greatest medical achievement in history — they've saved over 150 million lives since 1974 alone!\n\n**How they work:**\nA vaccine introduces a harmless version of a pathogen to teach the immune system WITHOUT causing disease:\n\n**Types of vaccines:**\n🦠 **Live-attenuated** — weakened live virus (MMR, chickenpox, yellow fever). Strongest immune response\n💀 **Killed/inactivated** — dead pathogen (flu shot, polio). Safer but needs boosters\n🔬 **Subunit** — only specific proteins (Hepatitis B, whooping cough). Very safe\n📧 **mRNA vaccines** (COVID-19, flu) — instructions to make spike protein; no DNA involved; cannot change your genes\n🦠 **Viral vector** — different virus carries genetic instructions (AstraZeneca, Ebola)\n\n**Herd immunity:** When ~70-90% of population is immune, pathogens can't spread — this **protects babies and immunocompromised people** who can't be vaccinated! 🤝\n\nSmallpox was completely eradicated in 1980 through vaccination — the only human disease ever eliminated! 🌍",
      highlight: "mRNA vaccines cannot change your DNA — they destroy the mRNA within days. Vaccines have saved 150+ million lives since 1974! 💉",
    },
    {
      id: 'inflammation',
      title: 'Inflammation: Helpful & Harmful 🔥',
      color: '#FF6B35',
      bgGradient: ['#2A1005', '#04070F'],
      icon: '🔥',
      svgIcon: 'fire',
      content: "**Inflammation** is a crucial defence response — but it's a double-edged sword.\n\n**Acute inflammation** (good — temporary):\nWhen tissue is damaged or infected:\n1. Mast cells release **histamine** → blood vessels dilate (redness, warmth)\n2. Vessels become leaky → fluid floods tissue (swelling)\n3. Neutrophils and macrophages rush in → eat bacteria (pus = dead neutrophils!)\n4. Platelets arrive → clotting begins\n5. Tissue is repaired 🩺\n\n**The classic signs (PRISH):** Pain, Redness, Immobility, Swelling, Heat\n\n**Chronic inflammation** (bad — ongoing):\nWhen inflammation persists without resolution:\n❌ **Autoimmune diseases** — immune attacks own tissue: Rheumatoid arthritis, Type 1 diabetes, lupus, MS\n❌ **Cardiovascular disease** — inflamed arterial walls attract plaque\n❌ **Cancer** — inflamed tissue is more likely to accumulate mutations\n\n**Cytokine storm** — extreme immune overreaction where massive inflammation damages organs. This is what made COVID-19 deadly in some patients — not the virus but the immune response! 🌪️",
      highlight: "Pus is dead neutrophils — chronic inflammation causes autoimmune diseases, heart disease, and cancer! 🔥",
    },
    {
      id: 'phagocytes',
      title: 'The Phagocytes: First Responders 🦠',
      color: '#A855F7',
      bgGradient: ['#1A0828', '#04070F'],
      icon: '🦠',
      svgIcon: 'microscope',
      content: "**Phagocytes** (Greek: 'eating cells') are the immune system's first responders — they engulf and destroy pathogens.\n\n**Key phagocytes:**\n🔵 **Neutrophils** — most abundant white blood cell (50-70%); first to arrive at infections; very aggressive; short-lived (5 days)\n🟡 **Macrophages** — large, long-lived; clean up debris; also PRESENT antigens to T-cells (linking innate to adaptive immunity!)\n🔴 **Dendritic cells** — best antigen presenters; bridge between innate and adaptive systems\n\n**How phagocytosis works:**\n1. Cell detects chemical signals from pathogen\n2. Membrane wraps around pathogen (phagosome)\n3. Lysosome fuses and dumps digestive enzymes\n4. Pathogen is destroyed\n5. Fragments are displayed on surface (antigen presentation) 🏷️\n\n**Natural Killer (NK) cells** are different — they don't eat pathogens. Instead, they scan cells for 'MHC-I' markers. Normal cells display MHC-I; cancer/infected cells lose it or display abnormal ones. NK cells then inject proteins that trigger cell suicide (apoptosis)! 💀",
      highlight: "Macrophages eat bacteria AND present their fragments to T-cells, linking the innate and adaptive immune systems! 🦠",
    },
    {
      id: 'complement_system',
      title: 'The Complement System 💥',
      color: '#FFD166',
      bgGradient: ['#2A1A00', '#04070F'],
      icon: '💥',
      svgIcon: 'lightning',
      content: "The **complement system** is a set of ~30 proteins in blood plasma that 'complement' antibody action with devastating precision.\n\n**It can be activated three ways:**\n1. Directly by pathogen surfaces (Classical pathway)\n2. Spontaneously on foreign surfaces (Alternative pathway)\n3. Via mannose-binding lectin recognising bacterial sugars\n\n**What complement proteins do:**\n🔴 **Opsonisation** — coat pathogens with C3b, making them much easier for phagocytes to eat\n💥 **Membrane Attack Complex (MAC)** — proteins drill holes in bacterial membranes, causing them to burst! It's like drilling holes in a submarine\n📢 **Recruit more immune cells** — small fragments (C3a, C5a) signal inflammation and recruit neutrophils\n\nComplement is part of the *innate* immune system — no memory, but instant action.\n\n**When complement goes wrong:**\n⚠️ Too much activation → attacks own cells (as in some autoimmune diseases)\n⚠️ Some bacteria evolved to HIDE from complement by coating themselves in host proteins!\n🦠 Streptococcus pneumoniae coats itself in capsule to resist phagocytes — this is how it causes pneumonia. 💊",
      highlight: "The Membrane Attack Complex drills holes in bacteria and causes them to burst — like sinking a submarine from the inside! 💥",
    },
    {
      id: 'immunological_memory',
      title: 'Memory: Why You Don\'t Get Chickenpox Twice 🧠',
      color: '#06B6D4',
      bgGradient: ['#0A1820', '#04070F'],
      icon: '🧠',
      svgIcon: 'brain',
      content: "**Immunological memory** is one of the most remarkable features in biology — and the scientific basis of vaccination.\n\n**Primary response** (first exposure):\n⏱️ 7-14 days to build antibodies\n📈 Antibody levels peak then fall\n😷 You feel the FULL disease\n\n**Secondary response** (second exposure, same pathogen):\n⚡ Memory B and T-cells recognise pathogen INSTANTLY\n⚡ Massive antibody surge within 24-48 hours\n⚡ Pathogen destroyed before you feel sick\n✅ You are effectively immune!\n\nMemory cells can last:\n• Decades (smallpox vaccination from 1950s still provides some protection today!)\n• Sometimes lifetime\n\n**Why flu vaccines need yearly updates:**\nInfluenza mutates its surface proteins (haemagglutinin, neuraminidase) rapidly. What your memory cells remember from last year no longer matches the new viral surface — so new vaccines are needed! 🔄\n\n**Original Antigenic Sin** — your immune system tends to use memory from the FIRST exposure as the template, even for new variants — sometimes a disadvantage. 🤔",
      highlight: "Memory cells respond in 24-48 hours on second exposure — this is why vaccines work and why you don't get chickenpox twice! 🧠",
    },
    {
      id: 'autoimmunity',
      title: 'Autoimmune Diseases: Friendly Fire 🎯',
      color: '#F43F5E',
      bgGradient: ['#2A050A', '#04070F'],
      icon: '🎯',
      svgIcon: 'target',
      content: "**Autoimmune diseases** occur when the immune system mistakenly attacks the body's own healthy tissues — friendly fire.\n\n**How 'self-tolerance' normally works:**\nDuring T-cell development in the thymus, cells that react to self-proteins are DELETED (negative selection). B-cells undergo similar screening. This keeps the immune system from attacking you.\n\n**When tolerance breaks down:**\n❌ Regulatory T-cells fail to suppress autoreactive cells\n❌ Molecular mimicry — pathogen antigens look like self-antigens; immune cells trained against pathogen accidentally attack own tissue\n❌ Inflammation persistently activates immune cells near healthy tissue\n\n**Major autoimmune diseases:**\n🦴 **Rheumatoid Arthritis** — attacks joint cartilage\n🧠 **Multiple Sclerosis (MS)** — attacks myelin sheath of neurons\n🍬 **Type 1 Diabetes** — destroys insulin-producing pancreatic beta cells\n🔴 **Lupus (SLE)** — attacks DNA itself; affects many organs\n🦋 **Hashimoto's/Grave's** — attacks thyroid\n\n**Treatment:** Immunosuppressive drugs reduce immune activity — but increase infection risk. Research into targeted therapies that only stop the specific autoimmune attack is the holy grail of immunology! 💊",
      highlight: "Autoimmune diseases happen when the immune system attacks your own body — molecular mimicry means infections can trigger autoimmunity! 🎯",
    },
    {
      id: 'allergies',
      title: 'Allergies: Overreaction Mode 🤧',
      color: '#EC4899',
      bgGradient: ['#2A0818', '#04070F'],
      icon: '🤧',
      svgIcon: 'waves',
      content: "**Allergies** are immune overreactions to harmless substances (allergens). Your immune system mistakenly treats pollen, peanuts, or pet dander as dangerous pathogens.\n\n**How allergies develop (sensitisation):**\n1. First exposure: B-cells make IgE antibodies against allergen (unusual — normally IgE fights parasites)\n2. IgE binds to mast cells (tissue cells) and basophils\n3. **Second exposure**: Allergen crosslinks IgE on mast cells → massive histamine release!\n4. Histamine causes: sneezing, itching, watery eyes, mucus production, swelling\n\n**Anaphylaxis** — the most extreme allergic reaction:\n❌ Massive histamine + other mediators released systemically\n❌ Blood pressure drops dangerously (vasodilation)\n❌ Airway swells shut\n❌ Can be fatal in minutes\n✅ Reversed by adrenaline (EpiPen!) which constricts vessels and opens airways\n\n**Why allergies are increasing:**\n🌱 **Hygiene hypothesis** — excessive cleanliness means immune systems don't develop tolerance; without training against real parasites/microbes, IgE 'searches' for other targets\n🏙️ Urbanisation and reduced early microbial exposure\n🧫 Disrupted gut microbiome 🦠",
      highlight: "Allergies happen when IgE antibodies built for parasites accidentally target harmless pollen or food — anaphylaxis needs immediate adrenaline! 🤧",
    },
  ],

  lab: {
    title: "Immune System War Room 🛡️",
    description: "Control pathogen load, T-cell response, antibody levels, and inflammation. Can you defeat the infection before it overwhelms your immune system?",
    hint: "Try raising pathogen load above 80% with low immune response — watch the cytokine storm! Then build your antibodies to fight back. 🛡️",
    scientistModeHint: "In Scientist Mode: discover humoral immunity, clonal selection, and the peak coordinated immune response! 🧑‍🔬",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why a fever actually helps you fight infection? 🌡️",
      answer: "Fever is not a symptom — it's a weapon! When bacteria or viruses enter, macrophages release cytokines that travel to the hypothalamus and deliberately raise body temperature. Most pathogens are evolved to work at 37°C — even 1-2°C above this significantly slows their reproduction AND speeds up immune cell activity. Artificially lowering a mild fever can actually prolong infection! The body knows what it's doing. 🔥",
      emoji: '🌡️',
    },
    {
      id: 'dyk2',
      question: "Do you know why breast milk gives babies immunity? 🍼",
      answer: "Breast milk contains a specific antibody — IgA — that the mother has already made against pathogens in her environment. These antibodies coat the baby's gut and respiratory tract, blocking pathogen entry without activating the baby's own immune system. It's passive immunity — the baby borrows Mum's immunological memory! This is why breastfed babies have fewer infections. Colostrum (first milk) has the highest antibody concentration. 🤱",
      emoji: '🍼',
    },
    {
      id: 'dyk3',
      question: "Do you know why organ transplants require immunosuppressive drugs? 💊",
      answer: "Your immune system is so good at detecting non-self that it recognises transplanted organs as foreign and ATTACKS them! Every cell in your body displays MHC proteins that act like identity cards. Unless the donor's MHC profile closely matches yours (why closely related donors work better), your immune system launches a full attack on the new organ. Immunosuppressive drugs (cyclosporin etc.) reduce this, but also reduce your ability to fight infections — a constant balancing act. 🩺",
      emoji: '💊',
    },
    {
      id: 'dyk4',
      question: "Do you know why HIV was so devastating — and why ART keeps it under control? 🔬",
      answer: "HIV specifically targets Helper T-cells (CD4+ cells) — the commanders of the adaptive immune response. Without them, neither B-cells nor Cytotoxic T-cells can be properly activated. As HIV destroys Helper T-cells, the immune system collapses entirely (AIDS). ART (Antiretroviral Therapy) uses multiple drugs that block HIV at different stages of its lifecycle — keeping viral load so low that immune cells recover and HIV can't spread. Undetectable = Untransmittable. 💊🌟",
      emoji: '🔬',
    },
    {
      id: 'dyk5',
      question: "Do you know why some people's immune systems fight cancer while others' don't? 🎗️",
      answer: "Cancer cells constantly display mutated proteins (neoantigens) on their surface that the immune system CAN detect — and healthy immune systems DO destroy millions of potential cancer cells daily (immune surveillance). But clever tumours evolve mechanisms to escape: they reduce MHC display, release immunosuppressive signals, or recruit regulatory T-cells. Checkpoint inhibitor drugs (Pembrolizumab etc.) 'take the brakes off' T-cells, letting them attack tumours — earning the 2018 Nobel Prize! 🏆",
      emoji: '🎗️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the key difference between innate and adaptive immunity? 🛡️", options: ["Innate is fast; adaptive is specific", "Innate uses antibodies; adaptive uses phagocytes", "Innate is skin; adaptive is blood", "Innate is adults; adaptive is children"], answer: 0, explanation: "Innate immunity responds in minutes-hours with general defences; adaptive immunity takes 1-2 weeks but produces antibodies specifically matching ONE pathogen AND creates long-lasting memory! 🎯" },
    { id: 'q2', question: "What is an antibody? 🔑", options: ["A type of white blood cell", "A protein binding to specific antigens", "A chemical causing body inflammation", "A virus fighting other viruses"], answer: 1, explanation: "Antibodies are Y-shaped immunoglobulin proteins produced by plasma cells (activated B-cells). Each antibody has a unique variable region that perfectly matches ONE specific antigen — like a lock and key! 🗝️" },
    { id: 'q3', question: "HIV is dangerous because it destroys which type of immune cell? 🔴", options: ["Neutrophils", "Red blood cells", "Helper T-cells", "Platelets"], answer: 2, explanation: "HIV specifically attacks and destroys Helper T-cells (CD4+ cells) — the commanders that activate all other immune cells. Once these collapse, the entire adaptive immune system fails, causing AIDS. 💔" },
    { id: 'q4', question: "How do mRNA vaccines work? 💉", options: ["Injecting a live weakened virus", "Injecting DNA to change genes", "Giving instructions to make proteins", "Injecting pre-made protective antibodies"], answer: 2, explanation: "mRNA vaccines deliver temporary instructions for cells to make a harmless pathogen protein (like a spike). Your immune system builds antibodies against it. The mRNA degrades within days and CANNOT alter your DNA! 🧬" },
    { id: 'q5', question: "What is 'herd immunity'? 🐑", options: ["Animals developing resistance to disease", "Population immunity stopping pathogen spread", "Immune systems strengthening with age", "Combining multiple vaccines into shots"], answer: 1, explanation: "When the majority (~70-90%) of a population is immune, pathogens can't find enough susceptible hosts to keep spreading — protecting even those who cannot be vaccinated (babies, immunocompromised). 🤝" },
    { id: 'q6', question: "What causes anaphylaxis? ⚠️", options: ["Bacterial toxins in the blood", "Massive histamine release from allergens", "T-cells attacking healthy body tissue", "Overactivation of the complement system"], answer: 1, explanation: "Anaphylaxis occurs when massive IgE-driven histamine release from mast cells throughout the body drops blood pressure, swells airways, and can be fatal within minutes — reversed by adrenaline (EpiPen). 💉" },
    { id: 'q7', question: "Why do you NOT get chickenpox twice? 🧠", options: ["The virus weakens after infection", "Memory cells recognize it instantly", "The virus destroys itself permanently", "Immunity is genetic, not acquired"], answer: 1, explanation: "After the first infection, some B and T-cells become long-lived memory cells. On second exposure, they recognise the pathogen within 24-48 hours and overwhelm it before you feel sick! 🎯" },
    { id: 'q8', question: "What is an autoimmune disease? 🎗️", options: ["Strengthening the immune system", "Immune system attacking healthy tissues", "Disease spreading between immune cells", "Inability to produce any antibodies"], answer: 1, explanation: "Autoimmune diseases occur when self-tolerance breaks down and immune cells attack healthy body tissue — like rheumatoid arthritis attacking joints, Type 1 diabetes attacking pancreatic cells, or MS attacking neurons! 💔" },
    { id: 'q9', question: "What is the Membrane Attack Complex (MAC)? 💥", options: ["Structure presenting antigens to T-cells", "Proteins drilling holes in bacteria", "Antibody clusters on B-cell surfaces", "Cells that engulf harmful pathogens"], answer: 1, explanation: "The MAC is a complement system structure that assembles on bacterial membranes — like drilling holes in a submarine! Water and ions flood in, the pathogen loses osmotic balance and bursts! 💥" },
    { id: 'q10', question: "Why do flu vaccines need to be updated yearly? 🔄", options: ["The vaccine degrades very quickly", "The virus mutates surface proteins", "Immune memory fades within months", "New viruses come from animals"], answer: 1, explanation: "Influenza rapidly mutates haemagglutinin and neuraminidase surface proteins (antigenic drift/shift). Memory cells from last year's vaccine recognise last year's shape, not this year's — so updated vaccines are needed! 🦠" },
    { id: 'q11', question: "Which white blood cell is the most abundant and usually the first to arrive at a site of infection? 🔵", options: ["Macrophages", "Neutrophils", "B-cells", "Basophils"], answer: 1, explanation: "Neutrophils make up 50-70% of white blood cells. They are aggressive, short-lived 'foot soldiers' that rush to infection sites within minutes. 🔵" },
    { id: 'q12', question: "The word 'Phagocyte' literally means: 🦠", options: ["Antibody maker", "Eating cell", "Moving cell", "Killer protein"], answer: 1, explanation: "Phagocytes (like Macrophages and Neutrophils) protect the body by engulfing (eating) and digesting harmful foreign particles and bacteria. 🦠" },
    { id: 'q13', question: "Which antibody class is the most abundant in the blood and can cross the placenta to protect babies? 👶", options: ["IgM", "IgA", "IgG", "IgE"], answer: 2, explanation: "IgG is the only antibody capable of crossing the placenta, providing the baby with the mother's immunological protection for several months after birth. 🛡️" },
    { id: 'q14', question: "What are the five classic signs of inflammation? 🔥", options: ["Pain, redness, swelling, and heat", "Coughing, sneezing, itching, and rash", "Nausea, dizziness, fatigue, and chills", "Hives, sweating, shivering, and numbness"], answer: 0, explanation: "The PRISH acronym (Pain, Redness, Immobility, Swelling, Heat) describes the physiological response as blood and immune cells rush to damaged tissue. 🔥" },
    { id: 'q15', question: "What is 'Clonal Selection' in the immune system? 🪖", options: ["Choosing which vaccine to take", "Activated cells dividing into copies", "Selecting which bacteria to eat", "Natural selection of new viruses"], answer: 1, explanation: "When a specific lymphocyte matches an antigen, it clones itself millions of times to create a massive army perfectly trained to fight that specific enemy. 🪖" },
    { id: 'q16', question: "Which division of the immune system includes physical barriers like skin and stomach acid? 🧱", options: ["Adaptive Immunity", "Innate Immunity", "Active Immunity", "Passive Immunity"], answer: 1, explanation: "Innate immunity is your ancient, first line of defense. It's non-specific and includes skin, mucus, and chemical barriers that keep pathogens out. 🏰" },
    { id: 'q17', question: "How do Natural Killer (NK) cells identify 'bad' cells? 💀", options: ["They look for specific antibodies", "They scan for MHC-I markers", "They smell the invading bacteria", "They only attack large parasites"], answer: 1, explanation: "NK cells look for the 'missing self'. Healthy cells show MHC-I markers; if a cell hides them (common in cancer/viruses), the NK cell triggers its suicide. 💀" },
    { id: 'q18', question: "Where do T-cells go to 'mature' and learn to distinguish friend from foe? 🦋", options: ["Bone Marrow", "Liver", "Thymus", "Spleen"], answer: 2, explanation: "T-cells are born in the bone marrow but migrate to the Thymus (a gland in the chest) to be 'educated' and screened for self-reactivity. 🦋" },
    { id: 'q19', question: "What is a 'Cytokine Storm'? 🌪️", options: ["A type of seasonal allergy", "Dangerous overreaction causing organ damage", "Massive production of red cells", "The moment vaccines start working"], answer: 1, explanation: "In a cytokine storm, the immune system panics and releases too many signals, leading to systemic inflammation that can be more deadly than the virus itself. 🌪️" },
    { id: 'q20', question: "Which antibody type is primarily responsible for triggering allergic reactions and fighting parasites? 🤧", options: ["IgG", "IgA", "IgE", "IgM"], answer: 2, explanation: "IgE antibodies normally fight parasites, but in allergies, they mistakenly trigger mast cells to release histamine in response to harmless things like pollen. 🤧" },
  ],

  relatedTopics: ['cell_structure', 'human_body_systems', 'dna_genetics', 'evolution_natural'],
};
