// ─────────────────────────────────────────────────────────
//  TOPIC: BANKING
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'banking',
  title: 'Banking & Money Flow',
  subtitle: 'The magic of the playground middleman 🏦',
  emoji: '🏦',
  category: 'Finance',
  accentKey: 'primary',

  hook: {
    question: "When you put ₹1 Lakh in a bank, does the bank lock it in a safe with your name on it? 🏦",
    reveal: "No! Within minutes, the bank gives your money to someone else to buy a car or a house. They only keep a tiny 'fraction' of your cash. The bank is like a magician that makes your money exist in two places at once! Let's uncover the secrets of the banking world! 🪄💸",
    emoji: '🔓',
  },

  theory: [
    {
      id: 'what_is_a_bank',
      title: 'The Playground Middleman 🏛️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'star',
      content: "Imagine a kid on a playground named 'The Bank.' \n\nSome kids have extra candy and want to keep it safe (Savers). Other kids want to buy a toy now but have no candy (Borrowers). \n'The Bank' takes the candy from the Savers, gives them a tiny piece of chocolate as a 'Thank You' (Interest), and then lends that candy to the Borrowers for a BIG piece of chocolate. The Bank eats the difference! 🍫",
      highlight: "A bank is just a factory that buys and sells money. ⚖️",
    },
    {
      id: 'fractional_reserve',
      title: 'The Trust Illusion 🪄',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🪄',
      svgIcon: 'eye',
      content: "If everyone tried to take their money out of the bank on the same day, the bank would vanish! \n\nThis is because of **Fractional Reserve Banking.** By law, a bank only has to keep a tiny bit (like 10%) of your cash. The rest is out in the world as loans. The entire global economy is built on one simple rule: Everyone trusts that they can get their money back, but nobody asks for it at the same time. 🤫",
      highlight: "Banking is 90% trust and 10% actual cash. 📱",
    },
    {
      id: 'types_of_accounts',
      title: 'Savings vs Current 🏦',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🏦',
      svgIcon: 'book',
      content: "Banks have different 'boxes' for your money:\n\n**Savings Account:** For normal people. The bank pays you a tiny bit of interest. You can't take out huge amounts 100 times a day.\n**Current Account:** For businesses. Zero interest, but the business can swipe their card 1,000 times a day and move millions of rupees instantly. It's built for speed, not for growing wealth.",
      highlight: "Savings accounts are for you; Current accounts are for businesses. 🛑",
    },
    {
      id: 'fixed_recurring_deposits',
      title: 'The Time Lock (FD) 🔒',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔒',
      svgIcon: 'shield',
      content: "If you promise the bank you won't touch your money for 5 years, they reward you with more interest! \n\n**Fixed Deposit (FD):** You lock a big bag of money for a set time. \n**Recurring Deposit (RD):** You lock a small bag of money every single month. \nBanks love these because they know they have 'stable' money to lend out to people buying houses. 🏗️",
      highlight: "FDs offer safety, but they grow very, very slowly. 🐢",
    },
    {
      id: 'central_banks',
      title: 'The Oxygen Tank 👑',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '👑',
      svgIcon: 'target',
      content: "Every country has a 'Boss of Banks' called the **Central Bank** (RBI in India). \n\nThey don't have normal customers. They print the actual money and control how much 'oxygen' (cash) is in the economy. If they turn the valve up, money is easy to get. If they turn it down, loans get expensive! They are the guardians of the country's financial health. 🌬️",
      highlight: "The Central Bank is the heart of the national economy. 🌬️",
    },
    {
      id: 'neft_rtgs_upi',
      title: 'Digital Magic (UPI) ⚡',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '⚡',
      svgIcon: 'zap',
      content: "In the old days, moving money took days and paper forms. Now we have magic:\n\n**UPI:** Instant, free, and works 24/7 on your phone. It's like sending a WhatsApp message but with real money! \n**NEFT/RTGS:** These are for the 'big boys' moving millions of rupees between bank branches. UPI changed the world by making money move as fast as light. 📱",
      highlight: "UPI turned your phone into a global bank branch. ⚡",
    },
    {
      id: 'repo_rate',
      title: 'The Steering Wheel 📉',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '📉',
      svgIcon: 'chart',
      content: "When banks need money, they borrow from the Central Bank. The interest they pay is called the **Repo Rate**. \n\nIf the Repo Rate goes UP, the bank makes *your* home loan more expensive to cover their cost. This 'one number' acts like a steering wheel. By turning it, the government can slow down or speed up the entire country's spending! 🏎️",
      highlight: "One number controls the cost of every loan in the country. 📈",
    },
    {
      id: 'bank_runs_dicgc',
      title: 'The Panic Monster 🏃‍♂️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🏃‍♂️',
      svgIcon: 'alert',
      content: "A **Bank Run** happens when people hear a rumor that the bank is broke. Everyone runs to get their cash at once! \n\nBut remember the 'Trust Illusion'? The bank only has 10% of the cash. So they run out, and the bank 'dies.' To stop the Panic Monster, the government provides **Insurance.** They guarantee that even if the bank fails, you will get your money back (up to a limit). 🛡️",
      highlight: "Insurance is the shield that stops bank panics. 😱",
    },
    {
      id: 'kyc_aml',
      title: 'The ID Check (KYC) 🕵️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🕵️',
      svgIcon: 'lock',
      content: "Why does the bank ask for your ID and photo? \n\nIt's called **KYC (Know Your Customer).** It's a way to stop 'Bad Guys' from using banks to hide stolen money or fund crimes. By knowing exactly who you are, the bank makes sure only 'Clean' money is moving through the system. It's the law fighting invisible crimes! ⚖️",
      highlight: "KYC is the bank's way of keeping the playground safe. 🕵️‍♂️",
    },
    {
      id: 'neo_banks',
      title: 'The Digital Ghost 🚀',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🚀',
      svgIcon: 'refresh',
      content: "A **Neo-Bank** is a bank that doesn't exist in the real world—it only exists in your phone! \n\nThey have zero buildings, zero physical vaults, and zero tellers. Because they save money on 'bricks and concrete,' they can give you better apps and lower fees. They are the 'Ghosts' of the future, haunting the old, slow banks. 💻",
      highlight: "The future of banking is code, not concrete. 💻",
    },
  ],

  lab: {
    title: "The Bank Engine 🏛️",
    description: "Welcome to the Banking Lab! Explore the 'Magic' of interest. Compare the slow Turtle (Savings) to the Time-Lock (FD), see how Compound Interest turns a snowball into an avalanche, and calculate how much 'Big Chocolate' you have to pay back on a loan! 📈",
    hint: "Check out the 'Compound vs Simple' mode. Notice how the simple line stays flat, while the compound line shoots up like a rocket! Time is your best friend.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks exact tax (TDS) math and inflation-adjusted 'Real Returns' so you see the truth behind the numbers.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why banks give you credit cards for 'Free'? 💳",
      answer: "It's a bait! Banks make money when you swipe (the store pays them a fee). But more importantly, they are betting that you will forget to pay on time. When that happens, they charge you a HUGE interest rate (like 40%!). You aren't the customer; you are the product they are selling to the future! 🎣",
      emoji: '💸',
    },
    {
      id: 'dyk2',
      question: "Do you know why inflation makes your FD a 'Losing' game? 🐢",
      answer: "The Silent Thief! If your FD pays 6% interest, but the price of milk goes up by 7%, you can actually buy LESS milk with your money next year. Even though your 'Number' went up, your 'Power' went down. FDs are safe, but they don't beat the inflation monster! 📉",
      emoji: '🎈',
    },
    {
      id: 'dyk3',
      question: "Do you know why you can't just print infinite money? 🖨️",
      answer: "Supply and Demand! If everyone in the world got ₹1 Crore today, everyone would try to buy the same things. Stores would raise their prices to ₹10 Lakhs for a loaf of bread. Money is just a 'Token' for value. If you have too many tokens and not enough stuff, the tokens become worthless! 💸",
      emoji: '📜',
    },
    {
      id: 'dyk4',
      question: "Do you know why UPI is totally free in India? 🇮🇳",
      answer: "Public Infrastructure! The government built UPI like a public road. They want everyone to use digital money because it's easier to track (no more suitcase cash) and makes the economy move faster. It's a gift to the citizens to make life simpler! ⚡",
      emoji: '⚡',
    },
    {
      id: 'dyk5',
      question: "Do you know why bank buildings have giant stone pillars? 🏛️",
      answer: "Mind Games! In the old days, people were scared to give their money to strangers. So banks built massive, heavy stone buildings to look 'Permanent' and 'Unbreakable.' It was a psychological trick to make you feel safe. Today, we trust computer code more than stone pillars! 💻",
      emoji: '🧠',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the primary way a bank makes money?", options: ["Printing their own cash", "Taking candy from children", "Paying low interest to savers and charging high interest to borrowers", "Charging for parking at the bank"], answer: 2, explanation: "The 'Net Interest Margin' is the engine of the bank! ⚖️" },
    { id: 'q2', question: "What does 'Fractional Reserve' mean?", options: ["The bank keeps all your money in a box", "The bank only keeps a tiny bit of cash and lends the rest out", "The bank only works for a fraction of the day", "Banks use fractions for math"], answer: 1, explanation: "Most of your money is out in the world as loans! 🪄" },
    { id: 'q3', question: "Which account is best for a big business with 1,000 daily sales?", options: ["Savings Account", "Fixed Deposit", "Current Account", "Piggy Bank"], answer: 2, explanation: "Current accounts are built for speed and unlimited transactions! 🏦" },
    { id: 'q4', question: "What is the difference between FD and RD?", options: ["FD is a lump sum; RD is a little every month", "FD is for cars; RD is for houses", "RD is illegal", "They are exactly the same"], answer: 0, explanation: "FD = One time. RD = Every month! 🔒" },
    { id: 'q5', question: "What is the 'Boss of Banks' called?", options: ["The Prime Minister", "The Central Bank (RBI)", "The Police", "Google"], answer: 1, explanation: "The Central Bank controls the money for the whole country! 👑" },
    { id: 'q6', question: "What makes UPI special?", options: ["It uses paper checks", "It is instant, free, and works on your phone 24/7", "It only works for billionaires", "It is a type of credit card"], answer: 1, explanation: "It's like sending a text message but with real money! ⚡" },
    { id: 'q7', question: "What is the 'Repo Rate'?", options: ["The rate of repo music", "The interest rate the Central Bank charges other banks", "The tax on bank profits", "The price of gold"], answer: 1, explanation: "It's the steering wheel of the national economy! 📉" },
    { id: 'q8', question: "What happens if everyone tries to withdraw their money at once?", options: ["A Bank Party", "A Bank Run (the bank might fail)", "The bank prints more money", "Nothing happens"], answer: 1, explanation: "Panic breaks the trust illusion of banking! 🏃‍♂️" },
    { id: 'q9', question: "What is DICGC/FDIC insurance for?", options: ["Insuring the bank manager's car", "Guaranteeing you get your money back even if the bank fails", "Paying for bank snacks", "Stopping hackers"], answer: 1, explanation: "It's the shield that stops people from panicking! 🛡️" },
    { id: 'q10', question: "What does KYC stand for?", options: ["Keep Your Cash", "Know Your Customer", "Kill Your Credit", "Knot Your Currency"], answer: 1, explanation: "It's the ID check to keep the playground safe! 🕵️" },
    { id: 'q11', question: "A 'Neo-Bank' is unique because:", options: ["It has zero physical buildings", "It only uses gold", "It is 1,000 years old", "It is owned by the government"], answer: 0, explanation: "No buildings = lower fees for you! 🚀" },
    { id: 'q12', question: "How do credit cards make money if you pay on time?", options: ["They don't", "By charging 'Swipe Fees' to the stores you buy from", "By stealing your data", "By charging for the plastic card"], answer: 1, explanation: "The store pays a hidden fee every time you swipe! 💳" },
    { id: 'q13', question: "Why is inflation the 'Silent Thief' of your FD?", options: ["It steals the physical cash", "It makes prices rise faster than your interest grows", "It's a type of computer virus", "It's a bank fee"], answer: 1, explanation: "A 6% gain minus 7% inflation is a 1% loss in power! 🐢" },
    { id: 'q14', question: "Why do banks have massive stone buildings?", options: ["To hide gold in the walls", "To psychologically make you feel trust and security", "Because stone was cheap", "To keep it cool inside"], answer: 1, explanation: "Trust was built with stone before it was built with code! 🏛️" },
    { id: 'q15', question: "What is 'Net Interest Margin'?", options: ["The size of the bank's profit from lending", "The color of the bank logo", "The depth of the vault", "The interest on a savings account"], answer: 0, explanation: "It's the difference between what the bank pays and what it charges! ⚖️" },
    { id: 'q16', question: "Which transfer is best for sending ₹50 Lakhs instantly?", options: ["UPI", "RTGS", "Mailing a check", "Cash in a bag"], answer: 1, explanation: "Real-Time Gross Settlement is for the 'big boys' moving millions! ⚡" },
    { id: 'q17', question: "Money Laundering means:", options: ["Washing physical bills in a laundry machine", "Making 'Dirty' illegal money look 'Clean' and legal", "Giving money to charity", "Opening a new bank account"], answer: 1, explanation: "It's a crime to hide where money came from! 🕵️" },
    { id: 'q18', question: "If the government raises the Repo Rate, what happens?", options: ["Taxes go down", "Home loans and car loans get more expensive", "Everyone gets free money", "Banks close for a holiday"], answer: 1, explanation: "The steering wheel turns and the economy slows down! 🏎️" },
    { id: 'q19', question: "Why can't you spend unlimited money on a Savings account?", options: ["You'll run out of money", "It's built for stability, not for hundreds of daily transactions", "The bank doesn't have enough cash", "It's illegal"], answer: 1, explanation: "Savings accounts are for saving, not for high-speed trading! 🏦" },
    { id: 'q20', question: "The most important asset a bank has is:", options: ["Gold", "Stone buildings", "Public Trust", "Computer servers"], answer: 2, explanation: "Without trust, the whole magic trick falls apart! 🪄" }
  ],

  relatedTopics: ['personal_finance', 'investing', 'wealth_loops'],
};
