// ─────────────────────────────────────────────────────────
//  TOPIC: CRITICAL THINKING & FALLACIES
//  Category: Psychology
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'critical_thinking',
  title: 'Critical Thinking',
  subtitle: 'Defending your mind from logical fallacies 🕵️‍♂️🛡️',
  emoji: '🕵️‍♂️',
  category: 'Psychology',
  accentKey: 'logic',

  hook: {
    question: "If a politician says: 'My opponent wants to reduce the military budget! He clearly hates our troops and wants our country to be invaded by terrorists!' ... what did he just do? 🤨",
    reveal: "He just committed a 'Straw Man Fallacy'. He didn't argue against the actual point (the budget); he built a fake, ridiculous scarecrow ('he hates troops') and attacked that instead because it's easier to defeat! The modern world is a warzone of manipulation. Advertising, politics, and social media are designed to bypass your logic and hack your emotions. It's time to build a mental firewall. Welcome to Critical Thinking! 🧠🔥",
    emoji: '🛡️',
  },

  theory: [
    {
      id: 'what_is_logic',
      title: 'The Firewall of Logic 🧱',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧱',
      svgIcon: 'shield',
      content: "**Critical Thinking** isn't about being negative or 'critical' of people. It is the objective analysis of information to form a rigorous judgment. \n\nYour brain is fundamentally lazy (Cognitive Ease). It prefers to believe comforting lies rather than do the hard math required to find the complex truth. Logic is the artificial software you must install over your primitive hardware to prevent people from hacking your beliefs! 💻",
      highlight: "A lie can travel halfway around the world while the truth is putting on its shoes. (Mark Twain) 🌍",
    },
    {
      id: 'burden_of_proof',
      title: 'The Burden of Proof ⚖️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'book',
      content: "If an internet guru says, 'I have a magic crystal that cures cancer! Prove me wrong!' ... how do you reply? \n\nYou don't have to prove anything! The **Burden of Proof (Onus Probandi)** states that the person *making* the extraordinary claim is the one required to provide the extraordinary evidence. \nIf they cannot provide peer-reviewed evidence, you are mathematically required to dismiss the claim. You don't have to prove a negative! 🛑",
      highlight: "What can be asserted without evidence can also be dismissed without evidence. (Hitchens's Razor) 🪒",
    },
    {
      id: 'occams_razor',
      title: 'Occam’s Razor 🪒',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🪒',
      svgIcon: 'target',
      content: "Imagine you hear hoofbeats outside your window. Is it a horse, or a zebra? \n\nUnless you live in Africa, it's a horse! **Occam's Razor** is a philosophical tool that states: 'When presented with competing hypotheses about the same prediction, one should select the solution with the fewest assumptions.' \nConspiracy theories violate this constantly. They require 10,000 people to keep a secret perfectly. The simpler explanation is usually just human incompetence! 🐴",
      highlight: "Don't invent a hyper-complex conspiracy when simple stupidity explains it perfectly. 📉",
    },
    {
      id: 'correlation_causation',
      title: 'Correlation vs Causation 📊',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '📊',
      svgIcon: 'chart',
      content: "In summer, ice cream sales go up. Also in summer, shark attacks go up. Therefore, eating ice cream causes shark attacks! Right? \n\nWrong! This is the fallacy of **Assuming Causation from Correlation**. Two things moving together doesn't mean one caused the other. The extremely obvious 'Confounding Variable' here is the hot weather (which causes both swimming and ice cream eating independently). 🦈",
      highlight: "Just because the rooster crows before sunrise doesn't mean the rooster *caused* the sun to rise! 🐓",
    },
    {
      id: 'ad_hominem',
      title: 'Ad Hominem (Attacking the Person) 🗡️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🗡️',
      svgIcon: 'users',
      content: "When someone is losing an argument on the facts, they will attack your character. \n\n**Ad Hominem (To the man):** \n*You:* 'The math proves we need to fix this bridge.'\n*Them:* 'Why should we listen to you? You're a lazy, ugly idiot who failed college!'\nThis is a logical fallacy! Even if you *are* a lazy idiot, that doesn't change the structural math of the bridge! They abandoned the argument to attack the messenger. 🚫",
      highlight: "Insults are the final refuge of a defeated mind. 🏳️",
    },
    {
      id: 'straw_man',
      title: 'The Straw Man Fallacy 🌾',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🌾',
      svgIcon: 'eye',
      content: "Instead of fighting a real, heavily-armored knight, it is much easier to tie straw together, paint a face on it, and punch the fake straw-man! \n\n*Person A:* 'I think we should put more money into schools.'\n*Person B:* 'So you want to cut the defense budget and leave our country defenseless to terrorists!'\nPerson A never said that! Person B invented a terrifying, extreme version of the argument because it is easier to destroy. 👺",
      highlight: "A Straw Man is a deliberate, grotesque exaggeration of an opponent's point. 🤡",
    },
    {
      id: 'appeal_to_authority',
      title: 'Appeal to Authority 👑',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '👑',
      svgIcon: 'star',
      content: "Just because a celebrity or a doctor says something, does not make it true! \n\nAn **Appeal to Authority** happens when an arguer claims a statement must be true because an 'expert' said it, rather than providing the actual data. \nWorse is the *False Authority*: when an actor in a lab coat tries to sell you medical pills on TV! Isaac Newton was a genius who invented calculus, but he also believed he could turn lead into gold (Alchemy). Experts can be wrong! 🧫",
      highlight: "In science, there are no kings. Data is the only king. 📊",
    },
    {
      id: 'appeal_to_nature',
      title: 'The Appeal to Nature 🌿',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🌿',
      svgIcon: 'leaf',
      content: "Marketing companies make billions off this fallacy:\n**'Our product is 100% all-natural, therefore it is better and healthier for you!'**\n\nReally? Arsenic is 100% natural. Cyanide is natural. The Bubonic Plague, snake venom, and Uranium are perfectly natural. Meanwhile, antibiotics and eyeglasses are 'unnatural' human inventions that save millions of lives. \n'Natural' does not automatically equal 'Good' or 'Safe'. 🐍",
      highlight: "Mother Nature is a brutal chemist trying to kill you just as often as feed you. 💀",
    },
    {
      id: 'false_dilemma',
      title: 'The False Dilemma (Black & White) 🔲',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔲',
      svgIcon: 'grid',
      content: "Politicians love to trap you in a **False Dilemma**. \n\n'You are either entirely with us, or you are with the terrorists!' \n'Either we charge a 50% tax rate, or the poor will starve in the streets.'\nThey present a complex spectrum as if there are only two extreme binary choices, forcing you to pick their side out of fear. But reality almost always exists in the nuanced gray area between the extremes! 🌫️",
      highlight: "Any time someone says 'It is either A or B!', automatically ask: 'What about C, D, and E?' 🗺️",
    },
    {
      id: 'sunk_cost_fallacy',
      title: 'Sunk Cost Fallacy ⚓',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚓',
      svgIcon: 'lock',
      content: "You buy a $15 ticket to a terrible movie. 30 minutes in, you hate it. Do you leave? \n\nMost people stay because 'I already paid $15, I don't want to waste the money.' \nThis is awful logic! The $15 is deeply GONE (Sunk). That transaction is locked in the past. Your only choice *now* is: Do I also want to waste the next 90 minutes of my life suffering? By staying, you waste money AND time! Leave the theater! 🚪",
      highlight: "Never let a past mistake hold your present hostage. ✂️",
    },
    {
      id: 'bandwagon_fallacy',
      title: 'The Bandwagon Fallacy 🐑',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🐑',
      svgIcon: 'users',
      content: "'Millions of people believe in this astrology claim, so it must be true!' \n\nThis is the **Bandwagon Fallacy (Argumentum ad populum)**. Truth is not a democratic election. For millions of years, 100% of the Earth's population believed the world was perfectly flat and the sun revolved around us. The entire human race was objectively, mathematically wrong. \nPopularity is a measure of marketing, not a measure of scientific truth! 🌍",
      highlight: "Even if a million people repeat a lie, it remains a lie. 🚫",
    },
    {
      id: 'no_true_scotsman',
      title: 'No True Scotsman Fallacy 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
      svgIcon: 'shield',
      content: "This happens when someone tries to protect a group they belong to by arbitrarily changing the definition. \n\n*Person A:* 'No Scotsman puts sugar in his porridge.'\n*Person B:* 'But my uncle Angus is from Scotland, and he puts sugar in his porridge.'\n*Person A:* 'Ah, but no *TRUE* Scotsman puts sugar in his porridge!'\nWhenever evidence violates their perfect rule, they just redefine the rule to reject the evidence. 🥅",
      highlight: "Moving the goalposts mid-game is intellectual cowardice! 🏟️",
    },
    {
      id: 'red_herring',
      title: 'The Red Herring 🐟',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🐟',
      svgIcon: 'waves',
      content: "Named after the practice of dragging a strong-smelling smoked fish across a trail to distract hunting dogs! \n\nA **Red Herring** is a deliberate diversion tactic. \n*Reporter:* 'Senator, did you steal the tax money?'\n*Senator:* 'I love this country. I grew up poor in a small town. Let me tell you about my grandmother...' \nHe threw a stinky fish to distract the reporter from the terrifying question about the money! 🎣",
      highlight: "When they change the subject completely, it means you have trapped them. 🪤",
    },
    {
      id: 'confirmation_bias',
      title: 'Confirmation Bias 🪞',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🪞',
      svgIcon: 'eye',
      content: "This isn't a fallacy, it's a terrifying cognitive bias. \n\n**Confirmation Bias** is the brain's tendency to eagerly search for, instantly believe, and permanently remember information that *agrees* with what we already believe. \nSimultaneously, the brain instantly attacks, ignores, and forgets any data that proves us wrong. The brain acts as a heavily biased lawyer defending its ego, rather than an impartial judge seeking the truth. 👨‍⚖️",
      highlight: "You cannot learn if you only read articles that confirm you are already right! 📖",
    },
    {
      id: 'epistemic_humility',
      title: 'Epistemic Humility 🧘‍♂️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧘‍♂️',
      svgIcon: 'star',
      content: "The ultimate goal of critical thinking is not to 'win' arguments and scream at people. \n\nThe goal is **Epistemic Humility**. This is the profound, quiet realization that the universe is infinitely complex, your brain is deeply flawed, and you might actually be wrong about your most cherished belief. \nA true critical thinker approaches a debate not as a battlefield to conquer, but as a laboratory to hunt for the absolute truth. 🔬",
      highlight: "The smartest person in the room is the one who says, 'I don't know, let's find out.' 🌌",
    },
  ],

  lab: {
    title: "The Fallacy Detector 🕵️‍♂️🎤",
    description: "Welcome to the Live Presidential Debate! The politicians on stage are throwing highly manipulative arguments to trick the voters. The 'Voter Manipulation Meter' will rapidly rise if they succeed. Your job is to act as the Fact Checker. Listen to their statement, quickly identify the exact Logical Fallacy they are using, and hit the buzzer to break the illusion and drop their manipulation score! Can you survive the spin zone? 🌪️",
    hint: "If they attack the opponent's haircut instead of their tax policy, slam the 'Ad Hominem' button! If they claim 'If we ban violent video games, next they will ban breathing!', hit 'Slippery Slope / Straw Man'!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks real-time rhetoric waveform analysis, Epistemic-breach flags, and Cognitive-Dissonance tracking metrics.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why conspiracy theories are so psychologically comforting to people? 👽",
      answer: "The human brain is terrified of chaos. The idea that a random, lone gunman could assassinate a powerful President is deeply unsettling (it means the world is dangerously random). A Conspiracy Theory provides false comfort: It forces a narrative of 'Shadowy Elites' being in complete control. Believing in a hyper-competent evil cabal is actually less scary than accepting the universe is chaotic and out of control! 🌍",
      emoji: '🧠',
    },
    {
      id: 'dyk2',
      question: "Do you know why 'Fake News' spreads 6 times faster on Twitter than the actual truth? 🦅",
      answer: "The Amygdala Hijack! Fake news is deliberately engineered by algorithms to trigger intense moral outrage and disgust. This triggers the survival center of the brain (Amygdala), forcing you to smash the 'Retweet' button instantly to warn your tribe. The Truth, on the other hand, is usually boring, complex, and nuanced, which doesn't trigger a dopamine hit. 📈",
      emoji: '🩸',
    },
    {
      id: 'dyk3',
      question: "Do you know why cult leaders make horrific predictions that fail (e.g. 'The world will end Tuesday'), but their followers still don't leave? 🛸",
      answer: "Cognitive Dissonance! When Tuesday passes and the world doesn't end, the follower has two choices: Admit they threw away their entire life/family for a fraud, OR believe the leader ('Our prayers were so good, we saved the world!'). The brain literally cannot handle the crushing pain of admitting massive failure, so it doubles down on the crazy illusion! 🧱",
      emoji: '🤯',
    },
    {
      id: 'dyk4',
      question: "Do you know why the 'Texas Sharpshooter Fallacy' tricks so many people in statistics? 🎯",
      answer: "Imagine a cowboy shooting 100 random holes in the side of a barn. Then, he walks up and paints a bulls-eye directly over a cluster of 3 holes that happened to land close together, shouting 'Look how accurate I am!' The fallacy occurs when people see random data clusters (like a 'cluster' of rare diseases in one neighborhood) and falsely assume there must be a specific cause, ignoring the massive randomness of the universe! 🔫",
      emoji: '📊',
    },
    {
      id: 'dyk5',
      question: "Do you know why casinos display the recent winning/losing numbers on Roulette tables? 🎰",
      answer: "The Gambler's Fallacy! The screen shows that 'Red' just hit 5 times in a row. Human brains instantly think: 'Black is definitely due to hit next to balance it out!' This is mathematically false! The spinning ball has zero memory. Every single spin is a completely independent 50% chance. Casinos use this cognitive flaw to make millions off people who think they see 'patterns'! 🎲",
      emoji: '💰',
    },
    {
      id: 'dyk6',
      question: "Do you know why politicians kiss babies on the campaign trail? 👶",
      answer: "The Halo Effect bias! Because the politician is seen doing something universally perceived as kind, warm, and protective (kissing a baby), the lazy human brain unconsciously assumes those positive traits must also apply to their economic and foreign policies. The 'Halo' of one good trait bleeds over into everything else they do! 😇",
      emoji: '💋',
    },
    {
      id: 'dyk7',
      question: "Do you know why the phrase 'You can't prove ghosts don't exist!' is a terrible argument? 👻",
      answer: "It reverses the Burden of Proof! It is logically impossible to prove a negative space everywhere in the universe simultaneously. I can claim there is a tiny, invisible pink unicorn floating behind your head. You can't prove it isn't there! But because I made the ridiculous claim, I must provide the evidence, otherwise the claim is worthless! 🦄",
      emoji: '⚖️',
    },
    {
      id: 'dyk8',
      question: "Do you know why 'survivor bias' made WW2 engineers put armor on the wrong parts of airplanes? 🛩️",
      answer: "Engineers looked at the returning bomber planes and saw they were heavily shot up on the wings and tail. They started to put armor there! But mathematician Abraham Wald realized the truth: The planes that got shot in the *engine* didn't survive to return home! They were only looking at the surviving data. He told them to armor the engines, saving thousands of lives! 🛡️",
      emoji: '🔧',
    },
    {
      id: 'dyk9',
      question: "Do you know why brands use the phrase 'Dermatologist Recommended'? 🧴",
      answer: "The Appeal to Authority Fallacy! They want your brain to shut off its critical thinking by invoking the 'White Coat'. But notice they don't say WHICH dermatologist, or what the data actually says. It is a completely empty phrase designed to hack your trust psychology! 🥼",
      emoji: '🧪',
    },
    {
      id: 'dyk10',
      question: "Do you know why debating someone with facts usually makes them MORE angry, not less? 🗣️",
      answer: "The Backfire Effect! When you show someone ironclad data that proves their deepest core belief is wrong, the brain's Amygdala perceives it as a physical threat to its existence. Instead of changing its mind, the brain releases adrenaline, fights back violently, and actually ends up believing in the crazy idea even STRONGER than before! 💥",
      emoji: '🧱',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is 'Critical Thinking'?", options: ["Criticizing other people", "Logical analysis of information", "Processing data quickly", "Forming opinions based on feelings"], answer: 1, explanation: "It is the mental firewall against the noise of the world. 🛡️" },
    { id: 'q2', question: "What does the 'Burden of Proof' state?", options: ["Government must provide evidence", "Claimants must provide evidence", "Skeptics must provide evidence", "Everyone must provide evidence"], answer: 1, explanation: "What is asserted without evidence can be dismissed without evidence! ⚖️" },
    { id: 'q3', question: "Occam's Razor is a rule that states:", options: ["Complex theories are better", "Simplest explanations are usually correct", "Scientific laws are absolute", "Assumptions are always necessary"], answer: 1, explanation: "When you hear hoofbeats, think horses, not zebras! 🪒" },
    { id: 'q4', question: "If a politician says: 'My opponent is an ugly, lazy idiot!' instead of debating the actual policy, what fallacy is this?", options: ["The bandwagon fallacy", "Ad Hominem attack", "Red Herring fallacy", "Slippery Slope fallacy"], answer: 1, explanation: "Even if they are ugly, it doesn't mean their math is wrong! 🗡️" },
    { id: 'q5', question: "What is the 'Straw Man' fallacy?", options: ["Building a garden scarecrow", "Misrepresenting an opponent's argument", "Farming wheat crops", "Attacking a weak position"], answer: 1, explanation: "You aren't fighting their real argument, you are fighting a fake straw-dummy! 🌾" },
    { id: 'q6', question: "Why is 'Assuming Causation from Correlation' a mistake?", options: ["Mathematical calculations are difficult", "Linked trends don't prove cause", "Data is often misinterpreted", "Correlation implies direct causation"], answer: 1, explanation: "A third 'hidden' variable (like hot weather) might be causing both! 📊" },
    { id: 'q7', question: "The 'Appeal to Nature' fallacy assumes that:", options: ["Trees are always green", "Natural things are always safe", "Synthetic products are dangerous", "Modern medicine is unnatural"], answer: 1, explanation: "Mother nature is a brutal chemist! 🌿" },
    { id: 'q8', question: "What is a 'False Dilemma' (Black & White fallacy)?", options: ["Watching old movies", "Presenting only two extreme choices", "Ignoring the middle ground", "Limiting available options"], answer: 1, explanation: "'You are either with me, or you are an enemy!' 🔲" },
    { id: 'q9', question: "You sit through 30 minutes of a terrible movie but refuse to leave because 'I already paid $15'. This is the:", options: ["Sunk cost fallacy", "Good financial decision", "Valuing your time", "Following theater rules"], answer: 0, explanation: "The $15 is gone anyway. Don't let a past mistake waste your present time! ⚓" },
    { id: 'q10', question: "The 'Bandwagon Fallacy' argues that:", options: ["Wagons are heavy objects", "Popularity proves a claim true", "Consensus equals absolute truth", "Majority opinion is irrelevant"], answer: 1, explanation: "Millions of people once believed the earth was flat. Popularity does not equal scientific truth! 🐑" },
    { id: 'q11', question: "When someone says 'No TRUE Scotsman puts sugar in porridge' to ignore evidence against their rule, they are:", options: ["Cooking traditional food", "Redefining criteria to exclude exceptions", "Following strict cultural rules", "Defending national identity"], answer: 1, explanation: "Moving the goalposts is intellectual cowardice! 🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    { id: 'q12', question: "A 'Red Herring' is a logical fallacy where the speaker:", options: ["Eating rare seafood", "Introducing irrelevant distractions", "Changing the speaker's appearance", "Shouting at the opponent"], answer: 1, explanation: "They throw a stinky fish to distract the hunting dogs! 🐟" },
    { id: 'q13', question: "What happens during 'Confirmation Bias'?", options: ["Receiving official confirmation", "Seeking data that supports beliefs", "Reading many different books", "Forgetting important information"], answer: 1, explanation: "Your brain acts as a biased defense lawyer, not an impartial judge! 🪞" },
    { id: 'q14', question: "Why do conspiracy theories psychologically comfort people?", options: ["They are entertaining stories", "They provide a sense of order", "Aliens are visiting Earth", "They dislike political leaders"], answer: 1, explanation: "The brain is terrified of random chaos! 👽" },
    { id: 'q15', question: "The 'Gambler's Fallacy' tricks people in casinos into believing:", options: ["Red is a lucky color", "Past events influence future odds", "Machines follow predictable patterns", "Betting high increases wins"], answer: 1, explanation: "The spinning wheel has absolutely zero memory of the past! 🎰" },
    { id: 'q16', question: "What is 'Survivor Bias' (e.g. the WW2 Bomber planes)?", options: ["Watching television shows", "Studying only successful examples", "Planes flying at altitude", "Adding extra armor plating"], answer: 1, explanation: "The planes that got shot in the engine didn't survive to be counted! 🛩️" },
    { id: 'q17', question: "The ultimate goal and peak of critical thinking is 'Epistemic Humility', which means:", options: ["Winning every argument", "Accepting that you might be wrong", "Yelling at opponents loudly", "Earning an advanced degree"], answer: 1, explanation: "The smartest person says: 'I don't know, let's find out.' 🧘‍♂️" },
    { id: 'q18', question: "If an actor in a lab coat tries to sell you medical pills on TV, this is an attempt at:", options: ["Effective sales techniques", "False appeal to authority", "Expert medical testimony", "Basic biological research"], answer: 1, explanation: "The white coat bypasses your logic engines! 🥼" },
    { id: 'q19', question: "Why does debating someone with hard facts often trigger the 'Backfire Effect'?", options: ["Facts are often confusing", "Beliefs are defended like threats", "Logic is often ignored", "Adrenaline is naturally enjoyable"], answer: 1, explanation: "They believe the lie even stronger just to protect their ego! 💥" },
    { id: 'q20', question: "Why does 'Fake News' spread 6 times faster than truth on social media?", options: ["Truth is too complex", "It triggers intense moral outrage", "Algorithms prefer automated bots", "Truth lacks emotional appeal"], answer: 1, explanation: "Algorithms hack your primal, tribal survival instincts! 🦅" },
  ],

  relatedTopics: ['manipulation_tactics', 'cognitive_biases', 'basic_understanding'],
};
