// ─────────────────────────────────────────────────────────
//  TOPIC: HUMAN NERVOUS SYSTEM
//  Category: Biology / Health
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'nervous_system',
  title: 'Human Nervous System',
  subtitle: 'The electricity that brings you to life ⚡🧤',
  emoji: '⚡',
  category: 'Biology',
  accentKey: 'nervous',

  hook: {
    question: "How does your brain know that you stubbed your toe before you even feel the pain? 🦶💥",
    reveal: "Because your nervous system is essentially a biological internet! Electrical signals travel from your toe up to your brain and back down to your muscles at speeds of up to 268 mph (120 m/s). But pain is a 'low-priority' signal compared to 'Reflexes'. Your spinal cord actually makes decisions *without* your brain's permission to pull your foot away instantly. You are literally moving before you know why! Let's trace the signal. 🏎️💨",
    emoji: '🧬',
  },

  theory: [
    {
      id: 'biological_internet',
      title: 'The Body\'s Electrical Network ⚡',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚡',
      svgIcon: 'zap',
      content: "The **Nervous System** is a complex network of nerves and cells that transmit signals between different parts of the body. It is your body's communication system 📞.\n\nIt runs on electricity! Tiny electrical pulses called **Action Potentials** fly through your nerves. This allows you to perceive the world, think thoughts, and move your limbs.\n\nThere are two main 'headquarters':\n1. **CNS (Central Nervous System):** The Brain and Spinal Cord (The Command Center).\n2. **PNS (Peripheral Nervous System):** All the other nerves that fan out to your fingertips and toes (The Field Agents).",
      highlight: "Everything you feel, think, and do is an electrical signal in this network! 💡",
    },
    {
      id: 'cns_vs_pns',
      title: 'Central vs Peripheral Systems 🏛️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'grid',
      content: "Think of the **CNS** like the massive servers at Google. It processes information and makes big decisions. It is protected by the 'Armor' of your skull and spine 🛡️.\n\nThe **PNS** is like the millions of Wi-Fi routers and cables in the world. Its job is to collect data (I feel heat!) and carry orders (Move the hand!).\n\nThe PNS is divided into the **Somatic** system (things you control, like waving) and the **Autonomic** system (things that happen on autopilot, like your heart beating).",
      highlight: "The CNS decides; the PNS connects and executes! 🛠️",
    },
    {
      id: 'sensory_motor',
      title: 'Sensory vs Motor Neurons 📥📤',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🧬',
      svgIcon: 'paperplane',
      content: "Not all nerves are the same. Information travels on a two-way street using two types of 'Messengers':\n\n• **Sensory Neurons (Afferent):** These carry data *INWARD* from your eyes, ears, and skin to the brain. They are the 'Input' 📥.\n• **Motor Neurons (Efferent):** These carry orders *OUTWARD* from the brain to your muscles. They are the 'Output' 📤.\n\nIf you see a ball flying at your face, Sensory neurons send the image to your brain, and Motor neurons instantly order your hands to catch it! 🏐",
      highlight: "Sensory = Feeling. Motor = Moving. They work in a continuous loop! 🔄",
    },
    {
      id: 'spinal_cord',
      title: 'Information Highway 🛣️',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🛣️',
      svgIcon: 'target',
      content: "The **Spinal Cord** is a thick bundle of nerves that runs down your back. It is the main trunk line of your body 🧵.\n\nAlmost every signal from your neck down must travel through the spinal cord to reach the brain. It is like a multi-lane highway—data from the left side of your body stays on one side, and data from the right on the other.\n\nBecause it is so critical, any damage to the spinal cord can result in **Paralysis**, where the 'cable' is cut and the brain can no longer talk to the legs or arms below the break.",
      highlight: "The spinal cord is the bridge between your body and your mind. 🌉",
    },
    {
      id: 'autonomic_system',
      title: 'Autonomic: The Autopilot ✈️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '✈️',
      svgIcon: 'shield',
      content: "You don't have to 'remind' your heart to beat or your lungs to breathe. The **Autonomic Nervous System** (ANS) handles these vital tasks automatically 💓.\n\nIt is always active, even when you are asleep and unconscious. It manages your digestion, temperature, and blood pressure. \n\nThe ANS has two modes: **Sympathetic** (The Gas Pedal) and **Parasympathetic** (The Brake Pedal). Your brain is constantly balancing these two to keep you alive and healthy in different situations.",
      highlight: "The Autonomic system keeps you alive while you sleep! 🌙",
    },
    {
      id: 'fight_or_flight',
      title: 'Fight or Flight! 🐆🔥',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🐆',
      svgIcon: 'zap',
      content: "When you are scared or stressed, your **Sympathetic** system takes control. This is the 'Fight or Flight' response 🚨.\n\nYour pupils dilate (to see better), your heart rate spikes (to pump blood to muscles), and your digestion STOPS (to save energy). \n\nThis system was designed to help you run away from a tiger 🐅, but today, it gets triggered by things like school exams or public speaking. Being in 'Fight or Flight' too much is what we call Chronic Stress, and it can be hard on the body.",
      highlight: "In a 'Fight or Flight' emergency, your brain shuts down digestion to power your muscles! 🛑",
    },
    {
      id: 'rest_and_digest',
      title: 'Parasympathetic: Rest & Digest 🧘',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🧘',
      svgIcon: 'sparkle',
      content: "Once the danger is gone, the **Parasympathetic** system kicks in. This is the 'Rest and Digest' mode 🥗.\n\nYour heart rate slows down, your breathing becomes deep and steady, and your body focuses on healing and digestion. \n\nDeep breathing or meditation can actually 'force' your brain to switch into this mode. By slowing your breath, you are sending a signal to your nervous system saying: 'The tiger is gone, we are safe now.' 🌿",
      highlight: "Deep breathing is a 'hack' to manually trigger your calm Parasympathetic system. 🌬️",
    },
    {
      id: 'reflex_arc',
      title: 'The Reflex Arc: Instant Action ⚡',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '⚡',
      svgIcon: 'flash',
      content: "If you touch a hot stove 🔥, you don't 'think' about moving your hand away. In fact, your hand moves *before* you feel the pain!\n\nThis is a **Reflex**. The sensory signal goes to the spinal cord, and instead of waiting for the brain to reply, a motor signal is sent immediately back to the muscle ↩️.\n\nThis 'shortcut' saves precious milliseconds that prevent serious burns. The signal to the brain goes up separately, which is why you pull away first and then say 'OUCH!' a second later. 🤕",
      highlight: "Reflexes happen in the spinal cord, skipping the brain to save time! 🏃‍♂️💨",
    },
    {
      id: 'synaptic_gaps',
      title: 'Synaptic Gaps: Chemical Bridges 🌉',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌉',
      svgIcon: 'flask',
      content: "Neurons don't actually touch each other. There is a tiny gap between them called a **Synapse** 🕳️.\n\nTo cross this gap, the electrical signal must turn into a chemical one. The first neuron releases chemicals called **Neurotransmitters** (like Dopamine or Serotonin). \n\nThese chemicals float across the gap and 'unlock' the next neuron, starting the electrical pulse again. This is why things like caffeine or medicine can affect your mood and energy—they are interfering with the chemistry of these bridges! 💊",
      highlight: "Your nervous system is part-Electricity, part-Chemical. 🧪⚡",
    },
    {
      id: 'myelin_insulation',
      title: 'Myelin: High-Speed Cables 🏎️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🏎️',
      svgIcon: 'link',
      content: "Nerves are like electrical wires, and just like wires, they need insulation 🧥. This layer of fatty insulation is called **Myelin**.\n\nNerves covered in Myelin can send signals 10 to 100 times faster than those without it! The signal 'jumps' between gaps in the myelin (Nodes of Ranvier).\n\nDiseases like Multiple Sclerosis (MS) happen when the body's immune system accidentally eats the Myelin. Without insulation, the electrical signals get lost or slow down, making it hard for the person to see or move correctly. 📉",
      highlight: "Myelin is the 'Superfast Fiber-Optic' upgrade for your nerves! ⚡",
    },
  ],

  lab: {
    title: "Reflex Arc Simulator 🧪",
    description: "Witness the speed of biology! Trigger a 'Heat Stimulus' and watch the electrical signal race through the sensory nerve. Observe how the spinal cord orders an immediate reflex BEFORE the signal even reaches the brain! ⚡",
    hint: "Try adding 'Myelin' in Scientist Mode to see the signal speed increase from 2 m/s to 120 m/s! Can you time the millisecond delay between the hand moving and the 'Pain' node in the brain lighting up?",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Conduction Velocity calculations ($v = d/t$) and synaptic delay modeling.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why you have a 'Funny Bone' that tingles when hit? 🦴",
      answer: "It's not a bone—it's your **Ulnar Nerve**! It's one of the only places in your body where a major nerve sits right against a bone with almost no padding. When you hit it, you are literally crushing the nerve against your bone, sending a massive 'Static Blast' of electrical confusion to your brain! ⚡",
      emoji: '😖',
    },
    {
      id: 'dyk2',
      question: "Do you know why we have goosebumps when we're scared or cold? 🥶",
      answer: "It's a leftover reflex from your ancestors! Your Autonomic system triggers tiny muscles (Arrector Pili) to pull your hair upright. In furry animals, this traps heat or makes them look BIGGER to predators. Since humans have very little hair, we just get tiny bumps on our skin! 🦔",
      emoji: '🦁',
    },
    {
      id: 'dyk3',
      question: "Do you know why you can't tickle yourself? 🧤",
      answer: "Your Cerebellum (part of the brain) predicts your own movements! When you try to tickle yourself, your motor system tells your sensory system: 'Hey, I'm doing this on purpose.' The brain ignores the signal as 'Self-Generated' and unimportant. But when someone else does it, it's a surprise, and the brain triggers a laughing reflex! 🤡",
      emoji: '🤫',
    },
    {
      id: 'dyk4',
      question: "Do you know why sleep is so important for your nerves? 😴",
      answer: "Cleaning day! While you sleep, your 'Glymphatic System' washes away the chemical waste that builds up during a busy day of thinking. Without sleep, this 'brain-gunk' slows down the synapses, making you feel foggy and slow-witted. 🧼",
      emoji: '🧠',
    },
    {
      id: 'dyk5',
      question: "Do you know why caffeine makes you feel 'Awake'? ☕",
      answer: "Molecular Disguise! Your brain naturally produces a chemical called Adenosine that tells your nerves to 'Slow down and get sleepy'. Caffeine has almost the exact same shape as Adenosine, so it plugs into the receptors first, blocking the 'Sleep' signal from getting through! ⚡",
      emoji: '🚀',
    },
  ],

  quiz: [
    { id: 'q1', question: "What are the two main divisions of the Nervous System?", options: ["The upper and lower parts", "Central and peripheral systems", "Fast and slow pathways", "Liquid and solid tissues"], answer: 1, explanation: "CNS is the brain/spine; PNS is everything else! 🏛️" },
    { id: 'q2', question: "Which neurons carry 'Input' from your skin to your brain?", options: ["Motor nerve cells", "Sensory nerve cells", "Glial support cells", "Myelin nerve fibers"], answer: 1, explanation: "Sensory neurons are the 'Feeling' wires! 📥" },
    { id: 'q3', question: "What is the thick bundle of nerves protected by your backbone called?", options: ["The main brainstem", "The spinal cord", "The primary nerve cable", "The central nerve trunk"], answer: 1, explanation: "The Spinal Cord is the main highway for all signals! 🛣️" },
    { id: 'q4', question: "A 'Reflex Arc' (like pulling away from fire) happens entirely in the:", options: ["The human brain", "The beating heart", "The spinal cord", "The skeletal muscle"], answer: 2, explanation: "Shortcuts! Skipping the brain saves lives in emergencies. ⚡" },
    { id: 'q5', question: "Which system is responsible for the 'Fight or Flight' response?", options: ["The parasympathetic system", "The sympathetic system", "The somatic system", "The digestive system"], answer: 1, explanation: "Sympathetic = STRESS/Action. Parasympathetic = Peace/Rest. 🐆" },
    { id: 'q6', question: "What is the fatty insulation that speeds up nerve signals?", options: ["Sticky gluten proteins", "Fatty myelin sheaths", "Small synapse gaps", "Hard keratin layers"], answer: 1, explanation: "Myelin is the super-insulation of the nervous system! 🏎️" },
    { id: 'q7', question: "The tiny gap between two neurons is called the:", options: ["A deep canyon", "A neural synapse", "A protein bridge", "A signal node"], answer: 1, explanation: "Neurons never actually touch! They communicate across Synapses. 🕳️" },
    { id: 'q8', question: "What chemicals carry a signal across a synaptic gap?", options: ["Endocrine system hormones", "Chemical neurotransmitter signals", "Circulating blood cells", "Dissolved oxygen molecules"], answer: 1, explanation: "Like Dopamine and Serotonin, these are the 'Chemical Keys'. 🔑" },
    { id: 'q9', question: "Which system controls voluntary movements like waving your hand?", options: ["The autonomic system", "The somatic system", "The endocrine system", "The automatic system"], answer: 1, explanation: "Somatic = Social/Manual control. 🖐️" },
    { id: 'q10', question: "What happens to your digestion during a 'Fight or Flight' response?", options: ["It speeds up significantly", "It slows to save energy", "It remains completely unchanged", "It produces excess acid"], answer: 1, explanation: "Priorities! You don't need to digest a burger while running from a bear. 🥗" },
    { id: 'q11', question: "Multiple Sclerosis (MS) is a disease that attacks which part of the nerve?", options: ["The cell nucleus", "The myelin sheath", "The synaptic gap", "The muscle fiber"], answer: 1, explanation: "Without insulation, the electrical signal leaks and fails. 📉" },
    { id: 'q12', question: "An electrical pulse traveling down a nerve is called:", options: ["A small spark", "An action potential", "A steady current", "A conscious thought"], answer: 1, explanation: "The Action Potential is the fundamental unit of nerve signal! ⚡" },
    { id: 'q13', question: "How fast can a signal travel in a myelinated nerve?", options: ["One mile per hour", "The speed of sound", "Over two hundred mph", "The speed of light"], answer: 2, explanation: "Faster than a Formula 1 race car! 🏎️💨" },
    { id: 'q14', question: "Which system helps you 'Rest and Digest' after a big meal?", options: ["The sympathetic system", "The parasympathetic system", "The somatic system", "The immune system"], answer: 1, explanation: "Para-sympathetic = Peace. 🧘" },
    { id: 'q15', question: "Why do you 'Jump' when you touch something hot before feeling the pain?", options: ["Pain signals travel faster", "Reflexes bypass the brain", "The brain processes slowly", "Muscles react independently"], answer: 1, explanation: "The Spinal Cord is the faster shortcut for reflexes! ⚡" },
    { id: 'q16', question: "The brain and spinal cord together make up which system?", options: ["The peripheral system", "The central system", "The autonomic system", "The somatic system"], answer: 1, explanation: "Central Nervous System! 🏛️" },
    { id: 'q17', question: "What is the job of 'Glial Cells'?", options: ["To carry electrical signals", "To support and feed neurons", "To pump oxygenated blood", "To process complex thoughts"], answer: 1, explanation: "Glial cells are the 'Maintenance Crew' of the brain. 🛠️" },
    { id: 'q18', question: "Adrenaline is the primary chemical used by which system?", options: ["The parasympathetic system", "The sympathetic system", "The somatic system", "The sensory system"], answer: 1, explanation: "Adrenaline powers the Fight or Flight mode! 🔥" },
    { id: 'q19', question: "Which sense has the SHORTEST nerve path to the brain?", options: ["Touch from the toes", "Sight from the eyes", "Smell from the nose", "Hearing from the ears"], answer: 1, explanation: "Vision and Hearing travel just a few centimeters to the brain! 👁️" },
    { id: 'q20', question: "Caffeine blocks which chemical in the brain?", options: ["The chemical dopamine", "The chemical adenosine", "The simple sugar", "The gaseous oxygen"], answer: 1, explanation: "Coffee tricks your brain into thinking you aren't tired! ☕" },
  ],

  relatedTopics: ['brain_structure', 'human_body_systems', 'memory_how_it_works'],
};
