export default {
  id: 'binary_computers',
  title: 'Binary & Computers',
  subtitle: 'The secret language of machines 💻',
  emoji: '💻',
  category: 'Technology',
  accentKey: 'cyberpunk',

  hook: {
    question: "How can a computer play extremely complex 3D video games if it only understands 'On' and 'Off'?",
    reveal: "Everything your computer does—from playing Minecraft to sending this message—is an aggressively fast illusion built entirely out of millions of microscopic light switches turning ON (1) and OFF (0) billions of times per second. Let's peel back the screen and see the raw electricity powering the matrix!",
    emoji: '🔌',
  },

  theory: [
    {
      id: 'what_is_binary',
      title: 'What is Binary? 0️⃣1️⃣',
      color: '#FF007F',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '0️⃣',
      svgIcon: 'binary',
      content: "As humans, we count using 10 digits (0 through 9). This is Base-10 (Decimal). We probably invented it because we have 10 fingers!\n\nComputers don't have fingers. They run on electricity. Electricity only has two states: Flowing (ON) or Not Flowing (OFF).\n\nBecause they only have two states, computers must count using Base-2, which we call **Binary**. They only use two digits: **0** and **1**.",
      highlight: "In Binary, '0' literally means no electricity is flowing, and '1' means electricity is flowing! ⚡",
    },
    {
      id: 'bits_bytes',
      title: 'Bits and Bytes 📦',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '📦',
      svgIcon: 'grid',
      content: "A single '0' or '1' is called a **Bit** (short for Binary Digit). It is the smallest piece of data in the universe.\n\nBut a single bit is almost useless. So computers group them together in boxes of 8. \n\nA group of 8 Bits is called a **Byte**.\n\nEverything in your computer is measured in Bytes! A Kilobyte (KB) is about 1,000 Bytes. A Megabyte (MB) is 1 Million Bytes. A Gigabyte (GB) is 1 Billion Bytes!",
      highlight: "A single Byte (like '01100001') is exactly enough space to store one alphabet letter, like 'A'. 🅰️",
    },
    {
      id: 'transistors',
      title: 'The Transistor: The Tiny Switch ⚙️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '⚙️',
      svgIcon: 'cpu',
      content: "How does a computer actually physically store a '1' or '0'? Using a microscopic electrical switch called a **Transistor**.\n\nA transistor has no moving parts. It is made of silicon (sand) and acts as a gate. When electricity hits the 'gate', it opens and lets power flow through (1). When electricity is removed, it snaps shut (0).\n\nBy putting billions of these microscopic gates together, we build complex computer brains!",
      highlight: "The processor chip inside your phone is the size of a fingernail, but contains over 15 BILLION microscopic transistors! 🤯",
    },
    {
      id: 'logic_gates',
      title: 'Logic Gates (AND, OR, NOT) 🧠',
      color: '#3B82F6',
      bgGradient: ['#05101A', '#050D0A'],
      icon: '🧠',
      svgIcon: 'target',
      content: "How do switches actually do math? By wiring them together into **Logic Gates**.\n\n- **AND Gate:** Needs two '1's to output a '1'. (Only opens if Switch A AND Switch B are ON).\n- **OR Gate:** Needs at least one '1' to output a '1'. (Opens if Switch A OR Switch B is ON).\n- **NOT Gate:** A rebel! It flips the input. If it gets a '1', it outputs a '0'.\n\nBy chaining millions of these tiny logic gates together, computers can naturally 'think' and solve math problems solely using flowing electricity!",
      highlight: "Every video game you've ever played is just billions of AND/OR gates opening and closing rapidly! 🎮",
    },
    {
      id: 'cpu',
      title: 'The CPU: The Brain 🤖',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🤖',
      svgIcon: 'cpu',
      content: "The **CPU** (Central Processing Unit) is the main brain of your computer. It is a massive city of transistors.\n\nIts entire job is to constantly fetch instructions (lines of code), decode what they mean, and execute them by routing electricity through the correct logic gates. \n\nThe speed of a CPU is measured in Hertz (Hz). If you have a 3.0 GHz processor, your CPU is opening and closing its transistor switches 3 BILLION times every single second!",
      highlight: "Clock speed is the 'heartbeat' of the CPU. Overclocking makes the heart beat faster, but generates extreme heat! 🔥",
    },
    {
      id: 'ram_vs_storage',
      title: 'RAM vs Hard Drive 📂',
      color: '#4CA050',
      bgGradient: ['#0A1A0F', '#050D0A'],
      icon: '📂',
      svgIcon: 'lightning',
      content: "Your computer has two main memories.\n\n**Storage (Hard Drive/SSD):** The giant, slow filing cabinet. It permanently remembers your photos and games even when the power is turned off.\n\n**RAM (Random Access Memory):** The small, lightning-fast desk. To actually 'play' a game, the CPU pulls it out of the slow filing cabinet and puts it on the fast RAM desk to work on it. \nBut if the power goes out, the RAM desk instantly wipes clean!",
      highlight: "This is why you lose unsaved work if your computer crashes! It was sitting on the volatile RAM desk, not in the permanent Hard Drive filing cabinet. 💥",
    },
    {
      id: 'ascii',
      title: 'ASCII: Translating Text 🔤',
      color: '#A855F7',
      bgGradient: ['#1A0A1F', '#050D0A'],
      icon: '🔤',
      svgIcon: 'book',
      content: "If computers only know numbers (0s and 1s), how do you read this text right now?\n\nThey use a secret decoder ring called **ASCII** (American Standard Code for Information Interchange).\n\nIn ASCII, every letter is assigned a specific number. \nThe capital letter 'A' is assigned the number 65. In binary, 65 is '01000001'. So when the computer sees that electrical pattern, it paints an 'A' on the screen!",
      highlight: "Emojis use a bigger decoder ring called 'Unicode'. An emoji is just a massive binary number! 😂",
    },
    {
      id: 'pixels_colors',
      title: 'Pixels & RGB Colors 🎨',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🎨',
      svgIcon: 'star',
      content: "Look closely at your screen. It is made of millions of tiny glowing dots called **Pixels**.\n\nEvery single pixel is actually 3 tiny lights glued together: **Red, Green, and Blue (RGB)**. \nThe computer sends a Byte (number from 0 to 255) to each light telling it how bright to be.\n\n- Full Red, Full Green, No Blue? The spot looks glowing Yellow! \n- All lights to 0? The spot is pitch Black.\n- All lights to 255? The spot is bright White!",
      highlight: "Your 4K TV has over 8.2 million pixels. That's 24 million tiny colored lights blinking constantly! 📺",
    },
    {
      id: 'software',
      title: 'Software vs Hardware 💿',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '💿',
      svgIcon: 'shield',
      content: "Computers are defined by a strict dual reality: Hardware and Software.\n\n**Hardware** is stuff you can physically kick. The screen, the keyboard, the silicon CPU chip, the battery.\n\n**Software** is the invisible thoughts of the machine. It is the code, the apps, the video games, and the Operating System. Software is simply massive lists of instructions (compiled perfectly into 1s and 0s) telling the hardware exactly which logic gates to fire.",
      highlight: "Without an Operating System (like Windows or iOS) to act as a translator, the CPU and RAM wouldn't know how to talk to each other! 🗣️",
    },
    {
      id: 'moores_law',
      title: 'Moore\'s Law & The Limits 📉',
      color: '#FF7A59',
      bgGradient: ['#1A0905', '#050D0A'],
      icon: '📉',
      svgIcon: 'rocket',
      content: "In 1965, Gordon Moore noticed that we were able to shrink transistors so effectively that the number of transistors on a microchip doubled every two years, making computers exponentially faster and cheaper. This phenomenon became known as **Moore's Law**.\n\nBecause of Moore's Law, the smartphone in your pocket is millions of times more powerful than the giant room-sized computers NASA used to send astronauts to the moon in 1969!",
      highlight: "We are reaching the end! Transistors are now only a few atoms wide. If we make them smaller, quantum physics ruins them! ⚛️",
    },
  ],

  lab: {
    title: "Cyberpunk Logic Lab 💻",
    description: "Welcome to the Terminal! Enter the 4 hacking modules to translate Decimal to Binary using 8-Bit Lightbulbs, wire up live AND/OR Logic Gates to restore power, build a basic calculator, and intercept an ASCII data stream.",
    hint: "For the Logic Gates: an AND gate needs BOTH inputs to be glowing green (1). An OR gate only needs ONE input to glow!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Reveals raw Hexadecimal conversion values and visualizes active logic truth tables.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the original computers had 'Bugs'? 🐛",
      answer: "In 1947, a massive room-sized computer at Harvard suddenly stopped working. When scientist Grace Hopper investigated, she literally found a dead moth trapped inside a physical mechanical relay switch, stopping the electricity from flowing! She taped the moth into her logbook and wrote 'First actual case of bug being found'. To this day, we still call software errors 'bugs'! 🦋",
      emoji: '🪲',
    },
    {
      id: 'dyk2',
      question: "Do you know why there are exactly 256 colors in older 8-bit games? 🕹️",
      answer: "Because 8 bits form one Byte, and a Byte is literally a line of 8 binary switches (like 11111111). If you calculate all the possible mathematical combinations of those 8 switches flipping on and off, the highest number you can create is exactly 256 (0 through 255). Computers are entirely bound by the math of their physical switches! 🔢",
      emoji: '👾',
    },
    {
      id: 'dyk3',
      question: "Do you know why restarting your computer usually magically fixes it? 🔄",
      answer: "Because of RAM! Hardware is rarely broken; usually, the Software code just got tangled up and stuck in an infinite loop while sitting in the temporary RAM memory. Turning off the physical power cuts the electricity holding those trapped 1s and 0s in the RAM. It wipes the desk perfectly clean, forcing the computer to load a fresh, untangled copy from the hard drive! 🧹",
      emoji: '🔌',
    },
    {
      id: 'dyk4',
      question: "Do you know why SSDs (Solid State Drives) are so much faster than older Hard Drives? ⚡",
      answer: "Old Hard Drives literally relied on a spinning metal magnetic disk and a tiny mechanical needle to physically read data (like a record player). An SSD has absolutely NO moving parts. It stores data by trapping electrons inside microscopic flash-memory grids. Because it uses pure electricity instead of moving metal parts, it is nearly instantly fast! 🚀",
      emoji: '💽',
    },
    {
      id: 'dyk5',
      question: "Do you know why Quantum Computers are so terrifying to traditional security? 🤯",
      answer: "Normal computers use Bits, which are strictly locked as a 1 OR a 0. Quantum computers use 'Qubits', taking advantage of the bizarre quantum physics rule of Superposition, meaning they can act as a 1 AND a 0 at the exact same time! This allows them to calculate millions of possibilities instantly, meaning they could instantly crack passwords that would take a normal computer millions of years to guess! 🔐",
      emoji: '⚛️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What number base system do computers use to process all data?", options: ['Base-10 (Decimal)', 'Base-16 (Hexadecimal)', 'Base-2 (Binary)', 'Base-8 (Octal)'], answer: 2, explanation: "Computers use Base-2 Binary (0s and 1s) because hardware runs on electricity, which only has two states (On or Off). ⚡" },
    { id: 'q2', question: "What does the binary number '0' physically represent inside a computer?", options: ['A red light', 'No electricity flowing through the switch', 'A broken wire', 'High voltage'], answer: 1, explanation: "Zero simply means the switch is 'Off', blocking electricity. 🛑" },
    { id: 'q3', question: "A single '1' or '0' is called a:", options: ['Byte', 'Pixel', 'Bit', 'Chip'], answer: 2, explanation: "It is called a 'bit' (short for BInary digiT). 👆" },
    { id: 'q4', question: "How many Bits are grouped together to make one standard Byte?", options: ['4', '8', '16', '100'], answer: 1, explanation: "There are 8 Bits in a Byte! (E.g. 01000001). 📦" },
    { id: 'q5', question: "What is the microscopic silicon switch that controls the flow of electricity inside a processor called?", options: ['Capacitor', 'Laser', 'Transistor', 'Diode'], answer: 2, explanation: "A transistor is a tiny gate without moving parts that controls the electrical 1s and 0s. ⚙️" },
    { id: 'q6', question: "Which Logic Gate requires ALL of its inputs to be ON (1) in order to output an ON (1)?", options: ['OR Gate', 'NOT Gate', 'AND Gate', 'NAND Gate'], answer: 2, explanation: "An 'AND' Gate acts like a strict bouncer. Switch A AND Switch B must be turned on to pass. 🧠" },
    { id: 'q7', question: "What does a NOT gate do?", options: ['It turns off the computer', 'It flips the input (Turns a 1 into a 0)', 'It burns out', 'It multiplies the input'], answer: 1, explanation: "The NOT gate simply inverts the signal. If electricity hits it, it blocks it. 🚫" },
    { id: 'q8', question: "What part of the computer is the main 'brain' that executes instructions?", options: ['The RAM', 'The CPU', 'The Hard Drive', 'The Graphics Card'], answer: 1, explanation: "The Central Processing Unit (CPU) is a massive grid of transistors executing all math and logic. 🤖" },
    { id: 'q9', question: "If a CPU has a speed of 3 GHz (Gigahertz), what does that mean?", options: ['It holds 3 Gigabytes of data', 'It opens and closes its switches 3 Billion times a second', 'It takes 3 seconds to turn on', 'It uses 3 Gigawatts of power'], answer: 1, explanation: "Hertz measures cycles per second. A 3 GHz processor is pulsing electricity 3 billion times every single second! 💥" },
    { id: 'q10', question: "Which type of memory is volatile, meaning it completely wipes clean the instant the power is turned off?", options: ['SSD', 'Hard Drive', 'RAM', 'USB Drive'], answer: 2, explanation: "RAM acts as a temporary workbench for the CPU. If power drops, the workbench is wiped! 🧹" },
    { id: 'q11', question: "To permanently save your video game so you can play it tomorrow, it must be stored in the:", options: ['RAM', 'CPU', 'Monitor', 'Storage (Hard Drive/SSD)'], answer: 3, explanation: "Storage drives magnetically or electrically trap the data so it safely survives without active power! 💾" },
    { id: 'q12', question: "What is the secret code system computers use to translate binary numbers into text characters (like letters)?", options: ['Morse Code', 'ASCII', 'HTTP', 'HTML'], answer: 1, explanation: "ASCII is a standard map telling the computer that '01000001' equals the letter 'A'. 🔤" },
    { id: 'q13', question: "A single pixel on your computer monitor is actually made of what 3 tiny colored lights?", options: ['Cyan, Magenta, Yellow', 'Red, Green, Blue (RGB)', 'Black, White, Grey', 'Orange, Purple, Green'], answer: 1, explanation: "By blending Red, Green, and Blue at different brightness levels, a pixel can display millions of colors! 🎨" },
    { id: 'q14', question: "If a pixel receives the instruction [Red:255, Green:255, Blue:255], what color does it display?", options: ['Black', 'White', 'Purple', 'Brown'], answer: 1, explanation: "When you blast all 3 light colors at maximum (255), they merge into pure White light. 💡" },
    { id: 'q15', question: "Is your Operating System (Windows/macOS) considered Hardware or Software?", options: ['Hardware', 'Software', 'Both', 'Neither'], answer: 1, explanation: "The OS is Software—a massive block of code telling the physical Hardware how to behave. 💿" },
    { id: 'q16', question: "What observation stated that the number of transistors on a chip doubles roughly every two years?", options: ['Newton\'s Law', 'Moore\'s Law', 'Darwin\'s Theory', 'Ohm\'s Law'], answer: 1, explanation: "Gordon Moore accurately predicted the insane, exponential shrinking of technology over the last 50 years. 📈" },
    { id: 'q17', question: "Why do programmers complain about 'Bugs'?", options: ['Computers attract insects', 'A massive software glitch in 1947 was caused by an actual dead moth', 'It sounds cool', 'Code looks like bugs'], answer: 1, explanation: "Grace Hopper literally pulled a dead moth out of a Harvard computer to fix it in 1947. 🐛" },
    { id: 'q18', question: "What does an SSD (Solid State Drive) use instead of moving metal disks?", options: ['Lasers', 'Microscopic flash memory grids', 'Water pressure', 'Radio waves'], answer: 1, explanation: "SSDs trap electrons in tiny cells. Because there are no spinning metal platters, they are incredibly fast. ⚡" },
    { id: 'q19', question: "An 8-bit video game system could only process numbers up to:", options: ['8', '100', '256', '1000'], answer: 2, explanation: "The maximum binary number you can make using exactly 8 switches (11111111) is 255 (plus 0 gives 256 states). 👾" },
    { id: 'q20', question: "The computer that sent astronauts to the Moon in 1969 was:", options: ['More powerful than your phone', 'Exactly as powerful as modern PCs', 'Millions of times LESS powerful than the smartphone in your pocket', 'Powered by steam'], answer: 2, explanation: "NASA's Apollo computer ran at 0.043 MHz. Your phone is literally billions of times faster! 🚀" },
  ],

  relatedTopics: ['internet_how_it_works', 'electricity_circuits', 'ai_machine_learning'],
};
