export default {
  id: 'digital_circuits',
  title: 'Digital Circuits',
  subtitle: 'The binary heartbeat of machines 💻',
  emoji: '🔌',
  category: 'Technology',
  accentKey: 'electricity',

  hook: {
    question: "How does a flat piece of sand (silicon) somehow manage to run incredibly complex 3D video games? 🎮",
    reveal: "It uses microscopic electrical switches called Transistors. If you wire billions of these tiny on/off switches together in incredibly specific patterns, they mathematically act like a physical brain! They add numbers, store memories, and eventually calculate the complex lighting of an entire 3D gaming universe! ⚡",
    emoji: '💾',
  },

  theory: [
    { id: '1', title: 'The Transistor', color: '#00D4FF', bgGradient: ['#002A35', '#050A0F'], icon: '🔌', svgIcon: 'cpu', content: "A **Transistor** is essentially just a microscopic light switch with absolutely no moving physical parts. \n\nIt strictly uses raw electricity to aggressively turn itself on or off! Every single phone or computer on Earth is functionally just a perfectly arranged massive rock holding billions of these tiny electrical switches.", highlight: "Modern CPU chips literally cram over 50 BILLION microscopic transistors onto a piece of silicon the size of your fingernail! 🧊" },
    { id: '2', title: 'Binary Code (1s and 0s)', color: '#39FF14', bgGradient: ['#0A200A', '#050A0F'], icon: '1️⃣', svgIcon: 'grid', content: "Because a transistor is only a simple switch, it literally only has two possible physical states: \n\nON (Current is flowing) = **1**\nOFF (No current) = **0**\n\nComputers fundamentally mathematically cannot understand English, Spanish, or numbers like '7'. They strictly and purely only understand high voltage (1) and low voltage (0).", highlight: "Everything you see on a computer screen—from a YouTube video to a text message—is just an ultra-fast translation of billions of microscopic 1s and 0s! 📺" },
    { id: '3', title: 'Logic Gates', color: '#FFD166', bgGradient: ['#2A2A00', '#050A0F'], icon: '⛩️', svgIcon: 'link', content: "When you wire a few simple transistors together, they form a **Logic Gate**.\n\nA Logic Gate takes simple electrical inputs, mathematically compares them, and strictly makes a decision based on rigid rules! It takes the raw electricity and perfectly weaponizes it to do fundamental logic.", highlight: "Logic Gates are perfectly comparable to digital bouncers at a club. They only let the electricity out if the specific strict rules are met! 🛑" },
    { id: '4', title: 'The AND Gate', color: '#FF3131', bgGradient: ['#200A0A', '#050A0F'], icon: '➕', svgIcon: 'target', content: "The **AND Gate** strictly requires ALL of its electrical inputs to be loudly ON (1) to let the electricity through the output. \n\nImagine needing exactly two keys to launch a massive missile. If you turn Key A, nothing happens. If you turn Key B, nothing. If you mathematically turn Key A **AND** Key B, the output fires! (1 AND 1 = 1)", highlight: "If any single input is a 0, the AND gate strictly shuts completely down and outputs a 0! 🔒" },
    { id: '5', title: 'The OR Gate', color: '#A855F7', bgGradient: ['#1A0A2A', '#050A0F'], icon: '⚖️', svgIcon: 'pulse', content: "The **OR Gate** is extremely friendly! It strictly lets the electricity successfully flow through if literally ANY of its inputs are ON (1). \n\nThink of arriving at a house with a front door and a back door. You can successfully get inside if the front door is open, **OR** the back door is open, **OR** both are open!", highlight: "The only mathematical way an OR gate fails (outputs 0) is if absolutely EVERY single input is aggressively turned OFF (0). 🚪" },
    { id: '6', title: 'The NOT Gate (Inverter)', color: '#FF4D6D', bgGradient: ['#2A0A1A', '#050A0F'], icon: '🔄', svgIcon: 'cube', content: "The **NOT Gate** is the rebellious teenager of the computer world. It aggressively looks at the electrical input and violently flips it strictly backwards!\n\nIf you mathematically feed it a 1, it outputs exactly 0. If you firmly give it a 0, it physically aggressively spits out a 1. It structurally inverts the logic entirely.", highlight: "It is the absolutely simplest gate mathematically, possessing exactly ONE single input wire! ⚡" },
    { id: '7', title: 'The XOR Gate (Exclusive OR)', color: '#00D4A0', bgGradient: ['#00201A', '#050A0F'], icon: '❌', svgIcon: 'sparkle', content: "The **XOR Gate** is incredibly picky. It strictly outputs a 1 if the inputs are undeniably DIFFERENT from each other. \n\nIf both inputs are exactly 1, or both exactly 0, it aggressively shuts down and outputs a 0. It wants exactly one or the other, strictly NEVER both!", highlight: "XOR gates are the absolute mathematical backbone of how computers perform physical Addition with binary numbers! 🧮" },
    { id: '8', title: 'Moore\'s Law', color: '#6C5CE7', bgGradient: ['#100A20', '#050A0F'], icon: '📈', svgIcon: 'lock', content: "In 1965, engineer Gordon Moore observed that the total number of microscopic transistors we could safely cram onto a single silicon chip was exactly doubling every two years!\n\nThis fierce exponential mathematical growth is exactly why a modern iPhone is violently millions of times more powerful than the entire massive NASA computer that flew humans to the moon!", highlight: "However, we are reaching the utter limit! Transistors are now approaching the literal size of individual atoms! ⚛️" },
    { id: '9', title: 'Integrated Circuits (Microchips)', color: '#FFB347', bgGradient: ['#201000', '#050A0F'], icon: '💽', svgIcon: 'waves', content: "An **Integrated Circuit (IC)** is violently just millions of specific logic gates permanently etched into a perfectly flat silicon chip. \n\nBefore ICs, engineers had to hand-wire thousands of physical heavy vacuum tubes together in a massive room to build one single basic calculator!", highlight: "The IC allowed computers to aggressively shrink from the size of a gymnasium down to the size of a wristwatch. ⌚" },
    { id: '10', title: 'Boolean Algebra', color: '#55EFC4', bgGradient: ['#0A2010', '#050A0F'], icon: '🔢', svgIcon: 'planet', content: "When software engineers write complex logic, they map it using **Boolean Algebra**. \n\nInstead of numbers (2+2=4), Boolean Algebra strictly uses TRUE (1) and FALSE (0) combined with logical operators (AND, OR, NOT). The expression \"(A AND B) OR C\" is physically built exactly using those distinct digital logic gates on the silicon motherboard!", highlight: "Every video game IF/THEN coding statement aggressively compiles completely down to physical Boolean circuits! 🕹️" }
  ],

  lab: {
    title: "Cascading Logic Board 🔌",
    description: "Welcome to the Digital Circuit Sandbox. Construct a logic path connecting binary inputs to output.",
    hint: "Toggle inputs and swap gates to explicitly route electricity physically through to light the LED.",
    scientistModeHint: "Scientist Mode explicitly physically reveals raw boolean algebra logic strings.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why programmers obsess massively over the exact number 256? 🔢", answer: "Because computers group exactly 8 bits (1s and 0s) together into a 'Byte'. Mathematically, an 8-bit byte can strictly physically hold exactly 2 to the 8th power combinations. 2^8 equals precisely 256 unique values! That is the fundamental math of computers! 🧮", emoji: '💻' },
    { id: 'dyk2', question: "Do you know why old computers used to mathematically fill an entire gymnasium? 🏫", answer: "Before the invention of the microscopic silicon transistor, computers used massive, incredibly hot physical glass 'Vacuum Tubes' acting as light switches. You physically needed 20,000 of massive tubes just to calculate basic algebra! The microchip shrunk them all to atomic sizes. 🔬", emoji: '🔥' },
    { id: 'dyk3', question: "Do you know why RAM strictly loses all memory when the power turns off? ⚡", answer: "RAM uses a specific type of logic gate and capacitor that is aggressively 'volatile'. It strictly requires a live, continuous physical stream of electricity to keep the internal gates holding the '1's. When the power shuts off, the juice definitively drains, and the mathematically locked gates all instantly collapse to 0! 🪫", emoji: '📉' },
    { id: 'dyk4', question: "Do you know why the Apple M1/M2 chips drastically crush old Intel chips in battery life? 🔋", answer: "Apple mathematically shifted to an 'ARM' integrated architecture, physically moving the CPU, RAM, and Graphics into the exact same single microscopic chip! Because the electricity explicitly physically travels shorter microscopic distances, very little energy aggressively bleeds off as waste heat! ❄️", emoji: '📱' },
    { id: 'dyk5', question: "Do you know why there is a physical limit to how fast a CPU can physically run (GHz)? ⏱️", answer: "Because electricity aggressively physically generates heat. If you violently toggle billions of logic gates mathematically faster than 5 GHz, the silicon physically violently overheats so aggressively that it actually melts the physical circuit board tracks inside the chip into molten slag! 🔥", emoji: '🌡️' }
  ],

  quiz: [
    { id: 'q1', question: "What is an OR gate strictly mathematically designed to do?", options: ["Outputs one if any input is one", "Outputs one if all inputs are one", "Outputs zero for all inputs", "Outputs one if inputs differ"], answer: 0, explanation: "An OR gate mathematically effectively physically safely lets current flow if explicitly strictly firmly logically ANY path is actively ON!" },
    { id: 'q2', question: "What does a Transistor definitively functionally act as?", options: ["Moves physical gears", "Acts as an electrical switch", "Generates infinite power", "Cools the system"], answer: 1, explanation: "It is literally purely solidly just a microscopic strictly physical electrical switch physically toggling logically cleanly firmly explicitly purely solidly 0 and exactly solidly purely smoothly 1." },
    { id: 'q3', question: "Which exact logic gate behaves precisely like two identical keys required to launch a physical missile?", options: ["The OR gate", "The NOT gate", "The AND gate", "The NAND gate"], answer: 2, explanation: "The AND gate requires both inputs to be ON." },
    { id: 'q4', question: "What does an OR gate output if both inputs are OFF?", options: ["The value one", "The value zero", "A system error", "Undefined electrical sparks"], answer: 1, explanation: "An OR gate requires at least one input to be ON. If both are OFF, it outputs 0." },
    { id: 'q5', question: "Which logic gate strictly flips the input to its exact opposite?", options: ["The NAND gate", "The XOR gate", "The OR gate", "The NOT gate"], answer: 3, explanation: "The NOT gate (inverter) flips 1 to 0 and 0 to 1." },
    { id: 'q6', question: "What is the primary function of an XOR (Exclusive OR) gate?", options: ["Outputs one if inputs differ", "Outputs one if inputs match", "Outputs zero for all inputs", "Amplifies the electrical signal"], answer: 0, explanation: "XOR only fires if the inputs are different from each other." },
    { id: 'q7', question: "Moore's Law originally stated that:", options: ["Computers get hotter annually", "Transistor counts double every two years", "Memory becomes volatile", "Software slows down hardware"], answer: 1, explanation: "Gordon Moore observed the exponential doubling of transistors!" },
    { id: 'q8', question: "Before silicon microchips, early computers used massive glass tubes called:", options: ["Fluorescent light bulbs", "Glass vacuum tubes", "Bright neon lights", "Cathode ray tubes"], answer: 1, explanation: "Vacuum tubes were huge, hot, and acted as physical switches." },
    { id: 'q9', question: "What exactly is an Integrated Circuit (IC)?", options: ["A robotic arm", "Gates etched on silicon", "A power supply", "A hard drive platter"], answer: 1, explanation: "An IC is a complete circuit compressed into a microscopic space." },
    { id: 'q10', question: "Boolean Algebra revolves entirely around which two concepts?", options: ["Positive and negative", "True and false", "Odd and even", "Analog and digital"], answer: 1, explanation: "Boolean logic strictly uses True (1) and False (0)." },
    { id: 'q11', question: "Why do programmers frequently reference the number 256?", options: ["It is a lucky number", "Maximum speed of electricity", "Byte holds 256 combinations", "Number of keyboard keys"], answer: 2, explanation: "A Byte (8 bits) mathematically calculates out to 2^8, which is exactly 256!" },
    { id: 'q12', question: "Why does RAM lose its data when you turn off the computer?", options: ["Erased by a virus", "Requires constant electrical power", "Hard drive steals data", "Enters a sleep mode"], answer: 1, explanation: "RAM gates instantly collapse back to 0 without continuous voltage." },
    { id: 'q13', question: "If an AND gate receives a 1 and a 0, what does it output?", options: ["The value one", "The value zero", "Both values simultaneously", "Half of the power"], answer: 1, explanation: "AND requires ALL inputs to be 1. It fails and outputs 0." },
    { id: 'q14', question: "If an OR gate receives a 1 and a 0, what does it output?", options: ["The value one", "The value zero", "Both values simultaneously", "Half of the power"], answer: 0, explanation: "OR only needs ONE input to be ON. It successfully outputs 1." },
    { id: 'q15', question: "What physical limit prevents CPUs from clocking at incredible speeds like 50 GHz?", options: ["Excessive air resistance", "Force of gravity", "Heat melting the silicon", "Strong magnetic fields"], answer: 2, explanation: "Flipping billions of switches that fast generates enough heat to melt the board!" },
    { id: 'q16', question: "Which computer structure allows the Apple M-series chips to be incredibly battery efficient?", options: ["They use magic", "They use water cooling", "Combined CPU and RAM chip", "They use larger transistors"], answer: 2, explanation: "Shrinking the distance electricity travels reduces massive heat and energy waste." },
    { id: 'q17', question: "Without logic gates, a computer processor is functionally just a:", options: ["A simple calculator", "Rock with electricity", "A dangerous bomb", "A standard radio"], answer: 1, explanation: "It is essentially just a highly organized piece of sand (silicon) channeling raw electricity." },
    { id: 'q18', question: "The mathematical backbone of all binary addition heavily relies on which specific gate?", options: ["The NOT gate", "The AND gate", "The XOR gate", "The OR gate"], answer: 2, explanation: "XOR gates naturally handle the 'carry' logic required for binary math." },
    { id: 'q19', question: "If you wire two NOT gates back-to-back in a line, what happens to the input?", options: ["The system explodes", "Outputs the original input", "Doubles the input voltage", "The signal vanishes"], answer: 1, explanation: "The first flips 1 to 0, and the second flips that 0 back to 1. It acts as a wire!" },
    { id: 'q20', question: "What is currently the greatest physical threat to Moore's Law continuing forever?", options: ["Running out of silicon", "Transistors reaching atomic size", "Lack of consumer demand", "Batteries are too heavy"], answer: 1, explanation: "We are hitting the physical limits of quantum mechanics as transistors reach atomic scales." }
  ],
  relatedTopics: ['ai_machine_learning'],
};
