// ─────────────────────────────────────────────────────────
//  TOPIC: ELECTROCHEMISTRY
//  Category: Chemistry
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'electrochemistry',
  title: 'Electrochemistry',
  subtitle: 'The magic of batteries and electron flow 🔋⚡',
  emoji: '🔋',
  category: 'Chemistry',
  accentKey: 'energy',

  hook: {
    question: "How does a heavy block of cold, dead metal in your phone suddenly 'wake up' and allow you to watch 10 hours of videos? 📱",
    reveal: "It isn't magic; it's Electrochemistry! Inside that battery, a silent war is happening. Billions of hungry atoms are ripping electrons away from weaker atoms. By forcing these stolen electrons to run through a wire before they reach their destination, we harness their raw energy to power the modern world. Let's look inside a battery! ⚡🔋",
    emoji: '⚡',
  },

  theory: [
    {
      id: 'redox_reactions',
      title: 'REDOX: The Core Engine ⚛️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚛️',
      svgIcon: 'refresh',
      content: "The foundation of electrochemistry is the **REDOX (Reduction-Oxidation) reaction**. \n\nIn a REDOX reaction, one atom 'loses' an electron, and another atom 'gains' it. \nIt is essentially an atomic game of tug-of-war. If you put a strong metal next to a weak metal, the strong metal will rip the weak metal's electrons right off! This violent transfer of electrons is the beating heart of every battery on Earth! ⚔️",
      highlight: "Batteries are just highly organized wars between different metals. 🛡️",
    },
    {
      id: 'oxidation_reduction',
      title: 'OIL RIG (How to remember) 🛢️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🛢️',
      svgIcon: 'target',
      content: "Chemistry uses a massive brain-twister: When an atom *gains* a negative electron, its overall charge *reduces* (from 0 to -1). \n\nTo remember this, use the acronym **OIL RIG**:\n• **O**xidation **I**s **L**osing (an electron). 📤\n• **R**eduction **I**s **G**aining (an electron). 📥\n\nThe atom that gets 'oxidized' is the loser. The atom that gets 'reduced' is the winner that stole the electron! 👑",
      highlight: "Gaining a negative makes your score drop. Reduction is winning! 📉",
    },
    {
      id: 'galvanic_cells',
      title: 'The Galvanic Cell 🔋',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔋',
      svgIcon: 'zap',
      content: "If you just mix the two metals together, the electrons transfer instantly and generate *heat*, which is useless for your phone! \n\nTo make a battery (a **Galvanic/Voltaic Cell**), you must separate the two fighting metals into two different cups. To let the winning metal steal the electrons, you connect them with a copper wire. Now, the electrons MUST travel through the wire to get to the winner. We put a lightbulb in the middle of that wire to steal the energy as they run past! 💡",
      highlight: "A battery forces the electrons to run a marathon before they can reach the finish line! 🏃‍♂️",
    },
    {
      id: 'anode_cathode',
      title: 'Anode & Cathode 🔌',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🔌',
      svgIcon: 'link',
      content: "The two separate metals in the battery are called **Electrodes**.\n\n1. **The Anode (Negative):** This is the weak metal. It undergoes Oxidation (loses electrons). It slowly dissolves away! 📉\n2. **The Cathode (Positive):** This is the strong metal. It undergoes Reduction (gains electrons). It actually grows larger as it collects the prize! 📈\n\nElectrons *always* flow from Anode to Cathode (A to C). ⚡",
      highlight: "Anode = Attacked. Cathode = Collects. 🛡️",
    },
    {
      id: 'the_salt_bridge',
      title: 'The Salt Bridge 🌉',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🌉',
      svgIcon: 'waves',
      content: "If electrons are flowing from the Anode to the Cathode, eventually the Cathode cup will become incredibly negatively charged. Because negative repels negative, the electrons will stop flowing. The battery dies instantly! \n\nTo fix this, we add a **Salt Bridge**. It is a tube connecting the two cups filled with neutral salt ions. As the electrons move right, negative salt ions move left to balance the charge! It acts like a pressure-release valve. 🚰",
      highlight: "Without a Salt Bridge, the battery chokes on its own electricity in 1 second! 🛑",
    },
    {
      id: 'voltage_potential',
      title: 'Voltage (The Push) ⚡',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '⚡',
      svgIcon: 'chart',
      content: "Not all batteries are equal. A standard AA battery is 1.5 Volts. A car battery is 12 Volts. \n\n**Voltage (Potential Difference)** measures how desperately the Cathode wants to steal the Anode's electrons! \nIf you pair Zinc and Copper, you get a mild 1.1 Volts. But if you pair extremely weak Lithium with extremely greedy Fluorine, the electrons are violently ripped across the wire at massive Voltage! 💥",
      highlight: "Voltage is just the 'thirst' level of the winning atom. 💧",
    },
    {
      id: 'electrolytic_cells',
      title: 'Recharging (Electrolytic Cells) 🔌',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔌',
      svgIcon: 'refresh',
      content: "When your phone battery hits 0%, all the electrons have moved to the Cathode. The war is over. \n\nHow do you 'charge' it? You plug it into the wall. The wall outlet acts as an **Electrolytic Cell**. It uses massive electrical force to literally shove the electrons BACKWARD, uphill, against their will, back to the Anode. It resets the trap so the war can start all over again tomorrow morning! 🌅",
      highlight: "Charging a battery is rolling the boulder back up the hill. 🪨",
    },
    {
      id: 'lithium_ion',
      title: 'The Lithium-Ion Revolution 📱',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '📱',
      svgIcon: 'battery',
      content: "Why did cell phones become so small? Because of the **Lithium-Ion Battery** (Nobel Prize, 2019). \n\nLithium is the lightest solid element on the periodic table, and it is DESPERATE to give away its electron (high voltage!). Because it is so light and so powerful, we can pack immense energy into a tiny space. Without Lithium, your incredibly thin iPhone would need to be the size of a brick! 🧱",
      highlight: "Lithium is the holy grail of batteries: feather-weight and explosive power. 🦅",
    },
    {
      id: 'electroplating',
      title: 'Electroplating (Fake Gold!) 🥇',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🥇',
      svgIcon: 'star',
      content: "Electrochemistry isn't just for batteries! Have you ever bought a 'Gold Plated' watch? \n\nFactories use an **Electrolysis bath**. They put a cheap steel watch (Cathode) into a liquid filled with dissolved Gold ions. They run a battery through it, forcing the gold ions to bond to the steel! They can coat cheap metal with a microscopic layer of real gold using the exact same electron physics! ✨",
      highlight: "Electricity is the ultimate metallic paint! 🎨",
    },
    {
      id: 'corrosion',
      title: 'Corrosion (The Enemy) 🏚️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🏚️',
      svgIcon: 'alert',
      content: "Rust is actually a horrible, unwanted electrochemical reaction! \n\nWhen a steel bridge gets wet, the water acts as a Salt Bridge. The oxygen in the air acts as a Cathode and slowly steals electrons from the Iron (Anode) in the bridge. As the Iron loses electrons, it turns into Iron Oxide (Rust) and crumbles. \nMother Nature is constantly running a slow battery on our infrastructure, destroying trillions of dollars of metal! 💸",
      highlight: "Rust is just the slow electrocution of your car by the atmosphere. 🚗",
    },
    {
      id: 'galvanization',
      title: 'Galvanization (The Shield) 🛡️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "How do we stop bridges from rusting? We use a **Sacrificial Anode** (Galvanization). \n\nIf we coat a steel bridge with Zinc, the Oxygen in the air will attack the shiny Zinc instead of the steel, because Zinc gives up its electrons much faster than Iron! The Zinc 'sacrifices' itself, dying slowly so the underlying steel can live forever! ✝️",
      highlight: "We save the king by putting a willing pawn on the front line! ♟️",
    },
    {
      id: 'fuel_cells',
      title: 'Hydrogen Fuel Cells 🚀',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🚀',
      svgIcon: 'cloud',
      content: "The future isn't just batteries; it's **Fuel Cells**. \n\nA Hydrogen Fuel Cell takes Hydrogen gas (H2) and Oxygen gas (O2) and pushes them through a membrane. This reaction steals their electrons to power an electric car. \nBut the most beautiful part? When Hydrogen and Oxygen combine, the ONLY exhaust product that comes out of the tailpipe is pure, drinkable Water (H2O)! 💧",
      highlight: "A car that runs on gas and 'exhausts' a majestic waterfall! 🌊",
    },
    {
      id: 'solid_state',
      title: 'Solid-State Batteries 🧊',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🧊',
      svgIcon: 'lock',
      content: "Modern Lithium-Ion batteries use a liquid to let ions move (the electrolyte). The problem? This liquid is highly flammable (which is why cheap hoverboards exploded in 2015). 🔥\n\nThe bleeding-edge of science is the **Solid-State Battery**, which replaces the liquid with a hard, fireproof ceramic crystal. It charges in 10 minutes, holds double the energy, and will never catch fire! It will revolutionize electric cars. 🚗⚡",
      highlight: "Replacing the flammable liquid with solid crystal is the next trillion-dollar invention! 🔮",
    },
    {
      id: 'nervous_system',
      title: 'Your Biological Battery 🧠',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🧠',
      svgIcon: 'zap',
      content: "You are an electrochemical machine! \n\nYour neurons don't use wires; they use 'Action Potentials.' Your brain pumps Sodium (Na+) and Potassium (K+) ions across cell membranes to create tiny voltages. When a neuron fires, the 'battery' discharges, shooting a tiny electrical zap down your spine to move your muscles. \nEvery thought you've ever had was just a biological battery turning on and off! 🤖",
      highlight: "You are literally powered by the exact same physics as an electric car. 🔋",
    },
    {
      id: 'future_of_energy',
      title: 'The Energy Bottleneck 🌍',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌍',
      svgIcon: 'star',
      content: "We know how to harvest endless solar and wind energy. The problem? The sun sets, and the wind stops. \n\nThe true crisis of the 21st century is **Storage**. We need massive, cheap, grid-scale electrochemistry. If we cannot build batteries big enough to store the daytime sun for nighttime use, the green revolution fails. The chemist who solves grid-storage will literally save the planet! 🦸‍♀️",
      highlight: "Generating power is easy; holding onto it is the hardest puzzle on Earth! 🧩",
    },
  ],

  lab: {
    title: "The Battery Builder 🔋💡",
    description: "Welcome to the REDOX Lab! You need to power a small 2.0-Volt LED bulb. Your job is to select the perfect pair of metals to act as your Anode (which loves to lose electrons) and Cathode (which loves to gain them). Check their Standard Reduction Potentials. If you pick metals that are too similar, the voltage will be too weak. If you hook them up backwards, the battery will reverse polarity! 🎛️",
    hint: "Lithium (Li) is an incredible Anode because it actively hates its electron (-3.04V). Fluorine (F) or Gold (Au) make incredible Cathodes because they desperately want electrons! Combine extremes for max voltage!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Nernst Equation parameters, Gibbs Free Energy ($\Delta G$) calculations, and real-time molarity decay rates.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why dropping your smartphone in rice doesn't actually fix it? 🍚",
      answer: "The rice might absorb some water, but the real enemy is ELECTROCHEMISTRY! When water hits the powered circuits inside your phone, it creates hundreds of tiny, unintentional batteries. Electrolysis instantly begins ripping the delicate gold and copper traces off the circuit board. By the time the rice dries it out, the microscopic wires are already corroded and gone! 💥",
      emoji: '📱',
    },
    {
      id: 'dyk2',
      question: "Do you know why licking a 9-Volt battery shocks your tongue, but touching it with your finger does nothing? 👅",
      answer: "Your skin is dry, meaning it is an insulator (high resistance). The 9-volts isn't strong enough to push electrons through dead skin. But your tongue is covered in saliva (a salty liquid). Saltwater is a perfect Electrolyte! The saliva acts exactly like the 'Salt Bridge' in a battery, allowing the electrons to flow directly through your taste buds! ⚡",
      emoji: '🧂',
    },
    {
      id: 'dyk3',
      question: "Do you know why old AA batteries leak white crusty stuff? 🔋",
      answer: "Alkaline batteries work by oxidizing a Zinc shell. Over time, the chemical reaction produces Hydrogen gas as a byproduct. The gas builds up massive pressure inside the cylinder until the battery physically ruptures, leaking out Potassium Hydroxide (the white, highly corrosive crust). 💥",
      emoji: '🏚️',
    },
    {
      id: 'dyk4',
      question: "Do you know why ships put big blocks of Zinc on their steel hulls? 🚢",
      answer: "Sacrificial Anodes! Seawater is the ultimate battery electrolyte, and it rapidly oxidizes (rusts) the steel hull. By attaching Zinc to the hull, the saltwater attacks the Zinc first because Zinc is fundamentally weaker at holding its electrons than Iron. The Zinc dies so the ship can cross the ocean! 🌊",
      emoji: '🛡️',
    },
    {
      id: 'dyk5',
      question: "Do you know why lemon batteries actually work? 🍋",
      answer: "You can stick a Copper penny and a Zinc nail into a lemon, and it generates electricity! The lemon juice contains Citric Acid (a strong electrolyte). The Zinc nail dissolves into the acid (Oxidation), pushing its abandoned electrons up the wire to the Copper penny. A lemon is literally a wet Galvanic cell! 💡",
      emoji: '🍋',
    },
    {
      id: 'dyk6',
      question: "Do you know why electric cars like Tesla are so heavy? 🚗",
      answer: "Energy Density! A gallon of liquid gasoline holds a staggering amount of chemical energy in its carbon bonds. To get the exact same amount of energy using Lithium-Ion batteries, the battery pack has to weigh over 1,000 pounds (500kg)! Electrochemistry is powerful, but it is incredibly heavy to scale up compared to fossil fuels. ⚖️",
      emoji: '🔋',
    },
    {
      id: 'dyk7',
      question: "Do you know why your phone gets hot when you charge it fast? 🔥",
      answer: "Internal Resistance! When you hit a battery with a 'fast charger', you are violently shoving billions of electrons backward (Electrolytic cell). Pushing them quickly creates massive electrical friction inside the chemical paste. This friction is released as waste heat. Heat degrades the battery chemicals, meaning fast-charging slowly kills your phone's lifespan! 📉",
      emoji: '🌡️',
    },
    {
      id: 'dyk8',
      question: "Do you know why the earliest batteries in 19th-century telegraphs used liquid acid in glass jars? 🏺",
      answer: "The 'Voltaic Pile' (the first battery) had to use wet acid or saltwater because ions must be able to swim freely between the metals. They used open glass jars because they didn't know how to make 'dry' pastes yet (like the ones in modern Duracell batteries). If you knocked over the jar, the acid spilled and the telegraph went dead! 📜",
      emoji: '💧',
    },
    {
      id: 'dyk9',
      question: "Do you know why we can't just make a battery that lasts forever? ⏳",
      answer: "Entropy! Every time you charge and discharge a battery, the physical structure of the Anode expands and contracts like a lung. Over thousands of cycles, the physical metal begins to crack and pulverize into dust. Eventually, there isn't enough solid metal structure left to hold the electrons. The battery structurally dies of old age! 🏚️",
      emoji: '🛑',
    },
    {
      id: 'dyk10',
      question: "Do you know why Lithium batteries will aggressively explode if you stab them with a knife? 🔪",
      answer: "Thermal Runaway! The ultra-thin barrier separating the Anode and Cathode is punctured by the knife. The electrons bypass the safety wire and flood straight across instantly. This massive instantaneous current generates thousands of degrees of heat, igniting the highly flammable liquid electrolyte into a jet-engine-style fire! 🔥",
      emoji: '🔥',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the acronym to remember REDOX reactions?", options: ["CAT DOG acronym", "OIL RIG acronym", "BAT MAN acronym", "RED BLUE acronym"], answer: 1, explanation: "Remember: gaining a negative electron reduces your charge! 🛢️" },
    { id: 'q2', question: "In a battery, what is the 'Anode'?", options: ["The positive terminal", "The negative electrode", "The liquid electrolyte", "The outer casing"], answer: 1, explanation: "Anode = Attacked. It gives up the electrons! 📉" },
    { id: 'q3', question: "Why is a 'Salt Bridge' critical for a battery to function?", options: ["It generates current", "Balancing internal charges", "Connecting the wires", "It stores energy"], answer: 1, explanation: "Without it, the receiving cup becomes too negative, repelling any further electrons instantly! 🌉" },
    { id: 'q4', question: "Voltage (Potential Difference) measures:", options: ["Total current flow", "Force pulling electrons", "The circuit resistance", "Stored chemical energy"], answer: 1, explanation: "It is the \"thirst\" level of the winning atom! ⚡" },
    { id: 'q5', question: "When you plug your phone into the wall, the charger acts as an 'Electrolytic Cell'. What does it do?", options: ["It creates heat", "Reversing electron flow", "It stabilizes voltage", "It filters current"], answer: 1, explanation: "It resets the mouse-trap for the next day! 🔌" },
    { id: 'q6', question: "Why is Lithium the holy grail metal for modern cell phone batteries?", options: ["It is abundant", "Losing electrons easily", "It conducts heat", "It remains stable"], answer: 1, explanation: "Featherweight power! 📱" },
    { id: 'q7', question: "Electroplating is the process of:", options: ["Melting metals together", "Coating metal electrically", "Cleaning metal surfaces", "Hardening metal alloys"], answer: 1, explanation: "Electricity is the ultimate expensive paint! 🥇" },
    { id: 'q8', question: "What is 'Corrosion' (like Rust) in electrochemical terms?", options: ["A cooling process", "Oxygen stealing electrons", "Static charge buildup", "Loss of magnetism"], answer: 1, explanation: "Mother nature's slow destruction battery! 🏚️" },
    { id: 'q9', question: "How does a 'Sacrificial Anode' protect a steel ship?", options: ["Improving fuel efficiency", "Reactive metal corroding", "Strengthening the hull", "Preventing barnacle growth"], answer: 1, explanation: "A willing pawn dies to save the queen! 🛡️" },
    { id: 'q10', question: "A Hydrogen Fuel cell generates electricity and only releases what out of the tailpipe?", options: ["Toxic exhaust fumes", "Pure liquid water", "Carbon dioxide gas", "Nitrogen and oxygen"], answer: 1, explanation: "Hydrogen + Oxygen = Power + Water. The dream of the future! 💧" },
    { id: 'q11', question: "What is the problem with the liquid electrolyte in modern Lithium-Ion batteries?", options: ["It is heavy", "It is flammable", "It leaks slowly", "It freezes easily"], answer: 1, explanation: "This is why cheap hoverboards exploded! 🔥" },
    { id: 'q12', question: "A 'Solid-State Battery' replaces the flammable liquid with:", options: ["Compressed oxygen gas", "A fireproof ceramic", "A liquid alloy", "A dense polymer"], answer: 1, explanation: "The bleeding-edge multi-trillion dollar quest for perfect batteries! 🧊" },
    { id: 'q13', question: "Your own nervous system acts like a battery by pumping which specific ions?", options: ["Gold and silver", "Sodium and potassium", "Iron and zinc", "Lead and mercury"], answer: 1, explanation: "You are an electrochemical computer! 🧠" },
    { id: 'q14', question: "To get the maximum Voltage in a battery, you should pair:", options: ["Two identical metals", "Highly different metals", "Two conductive liquids", "Metal and plastic"], answer: 1, explanation: "Combine the extremes to maximize the electrostatic pull! ⚡" },
    { id: 'q15', question: "In a lemon battery, the citric acid serves as the:", options: ["The negative anode", "The liquid electrolyte", "The positive cathode", "The external wire"], answer: 1, explanation: "The juice dissolves the nail to start the reaction! 🍋" },
    { id: 'q16', question: "Why does fast-charging physically damage your phone battery over time?", options: ["Draining the software", "Heat degrading chemicals", "Overloading the screen", "Weakening the casing"], answer: 1, explanation: "Heat is the ultimate enemy of batteries! 🌡️" },
    { id: 'q17', question: "When water hits a circuit board (like dropping a phone in a toilet), what actually kills it?", options: ["Shorting the screen", "Corroding copper traces", "Diluting the battery", "Blocking the signal"], answer: 1, explanation: "The water acts as a massive short-circuiting electrolyte! 💥" },
    { id: 'q18', question: "A battery eventually dies permanently (can't be recharged) because:", options: ["Losing its magnetism", "Internal structures cracking", "Using up electrons", "Turning to gas"], answer: 1, explanation: "It structurally falls apart from the physical stress of charging! 🏚️" },
    { id: 'q19', question: "Why does licking a 9-volt battery shock you, but touching it doesn't?", options: ["Skin is thick", "Saliva conducts electricity", "Tongues have nerves", "Metal reacts chemically"], answer: 1, explanation: "Saltwater bridges the gap instantly! 👅" },
    { id: 'q20', question: "What is the biggest bottleneck in transitioning the world entirely to Solar and Wind energy?", options: ["Lack of sunlight", "Large scale storage", "High panel cost", "Inefficient power lines"], answer: 1, explanation: "Generating power is easy. Keeping it is the hardest puzzle on Earth! 🌍" },
  ],

  relatedTopics: ['periodic_table', 'chemical_bonding', 'energy_types'],
};
