export default {
  id: "chemical_reactions",
  title: "Chemical Reactions",
  subtitle: "The violent rearrangement of the universe 🧪",
  emoji: "🧪",
  category: "Chemistry",
  accentKey: "chemistry",

  hook: {
    question: "What actually happens when you drop a tiny piece of Sodium metal into a glass of pure water? 💥",
    reveal: "A violent atomic war! The Sodium atoms aggressively rip the Oxygen-Hydrogen bonds apart, releasing explosive Hydrogen gas and creating enough heat to ignite it instantly! This is a **Chemical Reaction** — where atoms break their old friendships to form new, stronger bonds! 🧪",
    emoji: "🔥",
  },

  theory: [
    {
      id: "cr_0",
      title: "Reactants vs Products 🧪",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "🧪",
      svgIcon: "target",
      content: "A reaction starts with **Reactants** and ends with **Products**. It's like a recipe! 👨‍🍳\n\nIf you mix Vinegar and Baking Soda, they are the reactants. The result is Carbon Dioxide gas (bubbles), water, and a salt. The atoms don't vanish — they just get a total makeover! 🎭",
      highlight: "Nothing is created, nothing is destroyed; everything is just rearranged! ♻️",
    },
    {
      id: "cr_1",
      title: "Synthesis: The Builder 🏗️",
      color: "#F59E0B",
      bgGradient: ["#201500", "#050D0A"],
      icon: "🏗️",
      svgIcon: "plus",
      content: "In a Synthesis reaction ($A + B \rightarrow AB$), two or more simple substances combine to form a complex one! 🧩\n\nThink of Iron and Oxygen combining to make Rust. It's a slow-motion building process where the oxygen 'glues' itself to the iron atoms! 🧱",
      highlight: "Synthesis is the 'Marriage' of the chemical world! 💍",
    },
    {
      id: "cr_2",
      title: "Decomposition: The Destroyer 💥",
      color: "#EF4444",
      bgGradient: ["#200A0A", "#050D0A"],
      icon: "💥",
      svgIcon: "minus",
      content: "The opposite of Synthesis ($AB \rightarrow A + B$). One complex molecule aggressively breaks down into simpler pieces! 🌪️\n\nThis is how air bags work! A chemical called Sodium Azide is triggered by a spark and instantly decomposes into a massive volume of Nitrogen gas, inflating the bag in milliseconds! 🛡️",
      highlight: "Decomposition is the 'Divorce' of the chemical world! 💔",
    },
    {
      id: "cr_3",
      title: "Exothermic: Releasing Heat 🔥",
      color: "#FF3131",
      bgGradient: ["#300A0A", "#050D0A"],
      icon: "🔥",
      svgIcon: "zap",
      content: "Some reactions release energy into the surroundings as heat or light! 🕯️\n\nFire is the ultimate example. When wood burns, it reacts with oxygen to release a massive amount of 'trapped' chemical energy. You feel this as heat! 🌡️",
      highlight: "If the test tube gets hot, it's EXOTHERMIC! 🔥",
    },
    {
      id: "cr_4",
      title: "Endothermic: Sucking Cold ❄️",
      color: "#3B82F6",
      bgGradient: ["#0A1220", "#050D0A"],
      icon: "❄️",
      svgIcon: "snowflake",
      content: "These reactions actually ABSORB energy from the surroundings to break bonds! 🍦\n\nEver used a 'cold pack' for an injury? You pop the inner seal, a reaction happens, and it sucks the heat from your skin, making it feel freezing cold! 🧊",
      highlight: "If the test tube gets cold, it's ENDOTHERMIC! 🧊",
    },
    {
      id: "cr_5",
      title: "Combustion: Eating Oxygen 🌪️",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🌪️",
      svgIcon: "activity",
      content: "A high-speed reaction where a fuel reacts with Oxygen! 🌬️\n\nThis doesn't just mean fire. Your body uses 'cellular combustion' to react the sugar in your blood with the oxygen you breathe to power your brain and muscles! 🧠",
      highlight: "Oxygen is the universal 'Chemical Fire' fuel! 🌬️",
    },
    {
      id: "cr_6",
      title: "Catalysts: The Speeders ⚡",
      color: "#10B981",
      bgGradient: ["#0A2015", "#050D0A"],
      icon: "⚡",
      svgIcon: "zap",
      content: "A Catalyst is a substance that speeds up a reaction without being used up itself! 🏎️\n\nYour spit contains a catalyst called Amylase. It aggressively helps break down starches into sugars instantly. Without it, your lunch would take weeks to digest! 🥨",
      highlight: "Catalysts are like 'Wingmen' for chemical reactions! 🤝",
    },
    {
      id: "cr_7",
      title: "Conservation of Mass ⚖️",
      color: "#EC4899",
      bgGradient: ["#200A15", "#050D0A"],
      icon: "⚖️",
      svgIcon: "layers",
      content: "The Law of Conservation of Mass states that matter is never lost. 📐\n\nIf you burn a log, the ash, smoke, and gases released weigh EXACTLY as much as the log and the oxygen combined! You just have to count the invisible gas atoms! 🌬️",
      highlight: "The number of atoms in = The number of atoms out! ⚖️",
    },
    {
      id: "cr_8",
      title: "Activation Energy: The Spark 🧨",
      color: "#6C5CE7",
      bgGradient: ["#100A20", "#050D0A"],
      icon: "🧨",
      svgIcon: "power",
      content: "Even explosive reactions need a tiny 'push' to start! 🕯️\n\nThis is the Activation Energy. It's like the initial push needed to get a ball rolling down a hill. Matches need the friction of a strike to provide the heat that triggers the phosphorus reaction! 🕯️",
      highlight: "No reaction happens without the first spark! ⚡",
    },
    {
      id: "cr_9",
      title: "Replacement Reactions 🔄",
      color: "#F472B6",
      bgGradient: ["#200A1A", "#050D0A"],
      icon: "🔄",
      svgIcon: "repeat",
      content: "In a Single Replacement reaction, one element 'kicks out' another from a compound ($A + BC \rightarrow AC + B$). 🦵\n\nIf you put a copper wire in silver nitrate, the copper aggressively kicks the silver out, and you end up with beautiful silver crystals growing on the wire! 💎",
      highlight: "It's like Musical Chairs with atoms! 🪑",
    },
  ],

  lab: {
    title: "Reaction Reactor 💥",
    description: "Welcome to the Absolute Reaction Chamber. Balance equations, initiate atomic collisions, and observe the violent thermal consequences!",
    hint: "Try balancing the Combustion of Methane ($CH_4 + 2O_2$) for a high-intensity exothermic show!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time Enthalpy maps (ΔH) and Activation Energy barriers.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why iron rusts faster near the ocean? 🌊",
      answer: "Saltwater acts as an electrolyte, helping electrons move between the iron and oxygen much faster, aggressively accelerating the oxidation (rusting) reaction! ⚓",
      emoji: "⚓",
    },
    {
      id: "dyk2",
      question: "Do you know why hydrogen peroxide comes in brown bottles? 🍼",
      answer: "Light is a catalyst! UV rays provide enough activation energy to decompose peroxide into water and oxygen gas. The brown bottle blocks the light to keep the reaction from happening early! ☀️",
      emoji: "🧴",
    },
    {
      id: "dyk3",
      question: "Do you know how fireflies glow? 🦗",
      answer: "Chemiluminescence! They have a reaction between a molecule called Luciferin and Oxygen that releases almost 100% of its energy as light, with almost zero heat! It's a 'cold' light reaction! 💡",
      emoji: "✨",
    },
    {
      id: "dyk4",
      question: "Do you know why we put food in the fridge? ❄️",
      answer: "Heat provides kinetic energy. In the cold, atoms move slower, making chemical reactions (like food rotting) happen at a snail's pace! 🍎",
      emoji: "🍦",
    },
    {
      id: "dyk5",
      question: "Do you know why cut apples turn brown? 🍎",
      answer: "Enzymatic browning! When the apple's cells are broken, enzymes react with oxygen to create 'melanin' — the same pigment that tans your skin! 🍎",
      emoji: "🍂",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What are the starting substances in a reaction called?",
      options: ["Products", "Reactants", "Catalysts", "Solvents"],
      answer: 1,
      explanation: "Reactants are the 'ingredients' that go into the reaction! 🧪",
    },
    {
      id: "q2",
      question: "A reaction that releases heat into its surroundings is...",
      options: ["Endothermic", "Exothermic", "Isothermic", "Hydrothermic"],
      answer: 1,
      explanation: "Exo = Exit. Heat exits the reaction and warms up the surroundings! 🔥",
    },
    {
      id: "q3",
      question: "What does a Catalyst do?",
      options: ["Stops a reaction", "Slows a reaction", "Speeds up a reaction", "Changes the product"],
      answer: 2,
      explanation: "Catalysts provide a 'shortcut' for atoms to react faster! ⚡",
    },
    {
      id: "q4",
      question: "A + B → AB is the general formula for what reaction?",
      options: ["Decomposition", "Replacement", "Synthesis", "Combustion"],
      answer: 2,
      explanation: "Two things are combining (synthesizing) into one compound! 🧱",
    },
    {
      id: "q5",
      question: "AB → A + B is the general formula for what reaction?",
      options: ["Synthesis", "Decomposition", "Replacement", "Hydration"],
      answer: 1,
      explanation: "One complex molecule is breaking down into simpler pieces! 💥",
    },
    {
      id: "q6",
      question: "Which gas is required for a combustion reaction to occur?",
      options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Helium"],
      answer: 1,
      explanation: "Combustion is essentially a high-speed reaction with Oxygen! 🌬️",
    },
    {
      id: "q7",
      question: "The Law of Conservation of Mass says atoms are neither created nor...",
      options: ["Visible", "Molecular", "Destroyed", "Reactive"],
      answer: 2,
      explanation: "You can't lose atoms; they just change partners! Total mass stays identical! ⚖️",
    },
    {
      id: "q8",
      question: "What is the 'push' needed to start a reaction?",
      options: ["Kinetic Push", "Atomic Jump", "Activation Energy", "Spark Potency"],
      answer: 2,
      explanation: "Even dynamite needs a spark or heat to get over the energy barrier! 🧨",
    },
    {
      id: "q9",
      question: "If a cold pack feels freezing, the reaction inside is...",
      options: ["Exothermic", "Endothermic", "Hyperthermic", "Electronic"],
      answer: 1,
      explanation: "Endo = Into. It sucks heat into the reaction from your skin! ❄️",
    },
    {
      id: "q10",
      question: "A reaction where one element 'kicks out' another is a...",
      options: ["Replacement", "Synthesis", "Decomposition", "Catalysis"],
      answer: 0,
      explanation: "One atom replaces another in a compound! 🔄",
    },
    {
      id: "q11",
      question: "Why does grinding a solid reactant speed up the reaction?",
      options: ["It changes the color", "It increases surface area", "It makes it heavier", "It adds catalysts"],
      answer: 1,
      explanation: "More surface area means more 'collision sites' for atoms to react! 🏺",
    },
    {
      id: "q12",
      question: "What are enzymes in the human body?",
      options: ["Fuels", "Reactants", "Biological Catalysts", "Wastes"],
      answer: 2,
      explanation: "Enzymes make life possible by speeding up vital reactions! 🥨",
    },
    {
      id: "q13",
      question: "When vinegar and baking soda mix, the 'bubbles' are...",
      options: ["Water", "Carbon Dioxide", "Oxygen", "Hydrogen"],
      answer: 1,
      explanation: "The reaction releases CO2 gas as a product! 🫧",
    },
    {
      id: "q14",
      question: "Rusting is a slow-motion version of which process?",
      options: ["Decomposition", "Oxidation", "Reduction", "Combustion"],
      answer: 1,
      explanation: "Oxidation is the reaction of a material with Oxygen over time! ⚓",
    },
    {
      id: "q15",
      question: "The total mass of products in a chemical reaction is always...",
      options: ["Less than reactants", "Greater than reactants", "Equal to reactants", "Zero"],
      answer: 2,
      explanation: "Mass doesn't vanish; it just changes form according to the Law of Conservation of Mass! ⚖️",
    },
    {
      id: "q16",
      question: "Which of these is a sign of a chemical change?",
      options: ["Melting ice", "Color change / Gas bubbles", "Cutting paper", "Mixing salt and pepper"],
      answer: 1,
      explanation: "New colors or gases indicate new substances were chemically formed! 🧪",
    },
    {
      id: "q17",
      question: "In a 'Double Replacement' reaction ($AB + CD \rightarrow AD + CB$), how many elements swap?",
      options: ["Zero", "One", "Two", "All of them"],
      answer: 2,
      explanation: "Two compounds swap their ion partners! 🕺💃",
    },
    {
      id: "q18",
      question: "Chemiluminescence is a reaction that releases what?",
      options: ["Heat", "Light", "Sound", "Electricity"],
      answer: 1,
      explanation: "It's the 'cold light' reaction seen in fireflies and glowsticks! ✨",
    },
    {
      id: "q19",
      question: "Activation energy is lowest when using a...",
      options: ["Fuel", "Freezer", "Catalyst", "Solid"],
      answer: 2,
      explanation: "Catalysts lower the energy barrier needed to start a reaction! ⚡",
    },
    {
      id: "q20",
      question: "What does the arrow ($\rightarrow$) in a chemical equation mean?",
      options: ["Equals", "Produces / Yields", "Goes to", "Increases"],
      answer: 1,
      explanation: "The reactants 'yield' or 'produce' the products! ➡️",
    },
  ],

  relatedTopics: ["atoms_molecules", "matter_states", "chemical_bonding"],
};
