// ─────────────────────────────────────────────────────────
//  TOPIC: REAL ESTATE FINANCE
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'real_estate_finance',
  title: 'Real Estate Finance',
  subtitle: "The art of buying the world with other people's money 🏠",
  emoji: '🏗️',
  category: 'Finance',
  accentKey: 'success',

  hook: {
    question: "How can you buy a ₹1 Crore house if you only have ₹10 Lakhs in your pocket? 🏘️",
    reveal: "Welcome to the magic of 'Leverage.' In real estate, you can use a small amount of your money to control a massive asset. The bank provides the rest, and your tenant effectively pays the bank for you! You are essentially using 'Other People's Money' (OPM) to build your own empire. 🏗️💸",
    emoji: '🏢',
  },

  theory: [
    {
      id: 'what_is_real_estate',
      title: 'The Un-Printable Asset 🌍',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌍',
      svgIcon: 'star',
      content: "Real Estate is simple: It's land and the buildings on it. \n\nWhy is it so valuable? Because they aren't making any more land! You can print more money, and you can create more digital stocks, but you cannot 'create' more land in Mumbai or New York. It is a finite, physical piece of the Earth that people will always need to live, work, and sleep on.",
      highlight: "Buy land, they're not making it anymore. (Mark Twain) 🏗️",
    },
    {
      id: 'leverage_opm',
      title: 'The Financial Lever (OPM) 🏗️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'eye',
      content: "In the stock market, if you have ₹1 Lakh, you buy ₹1 Lakh of stocks. \n\nIn Real Estate, if you have ₹1 Lakh, you can use it as a 'Down Payment' and the bank will lend you ₹9 Lakhs more to buy a ₹10 Lakh house! This is **Leverage.** You now own a ₹10 Lakh asset. If the house price goes up by 10%, you didn't just make ₹10k—you made ₹1 Lakh! You doubled your money using the bank's cash. 🤯",
      highlight: "Leverage turns small savings into massive control. 📈",
    },
    {
      id: 'rental_yield_loop',
      title: 'The Tenant Loop 🔄',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🔄',
      svgIcon: 'refresh',
      content: "The goal of a real estate investor is to find a **Tenant.** \n\nThe tenant lives in your house and pays you **Rent.** If your rent is bigger than your bank loan payment (EMI), you are 'Cash Flow Positive.' The tenant is effectively buying the house for you! After 20 years, the loan is gone, and you own a giant building for 'free' because someone else paid the bill. 🤝",
      highlight: "In this game, the tenant is your wealth partner. 🤝",
    },
    {
      id: 'appreciation_math',
      title: 'The Growth Engine (Appreciation) 📈',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📈',
      svgIcon: 'trending-up',
      content: "While you collect rent, something else is happening: The value of the land is going UP. This is **Appreciation.** \n\nAs cities grow and more people want to live in the same area, your ₹1 Crore house might become worth ₹2 Crores in 10 years. You make money in two ways: monthly rent (income) AND the increase in value (wealth). It's like a money tree that also produces gold leaves! 🌳",
      highlight: "Rent pays the bills; Appreciation builds the empire. 🏰",
    },
    {
      id: 'mortgages_emi',
      title: 'The 30-Year Chain (Mortgage) ⛓️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '⛓️',
      svgIcon: 'lock',
      content: "A **Mortgage** is a long-term loan (usually 15-30 years) to buy property. \n\nThe bank 'owns' the house until you pay the last rupee. If you stop paying, the bank takes the house (Foreclosure). Mortgages are usually the cheapest debt you can get because the house itself is the 'Guarantee' (Collateral). It's a long chain, but it's the only way most people can buy their first home. 🏠",
      highlight: "A mortgage is a bet that your future self will be wealthier than today. 🏛️",
    },
    {
      id: 'commercial_vs_residential',
      title: 'Stores vs Houses 🏢',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🏢',
      svgIcon: 'home',
      content: "**Residential:** Renting houses to families. Stable, emotional, and easy to understand. \n\n**Commercial:** Renting offices or shops to businesses (like Starbucks or a bank). They pay higher rent and stay for 10+ years, but it's much more expensive to buy. Commercial real estate is how the 'Big Boys' build generational wealth that lasts hundreds of years. 🏗️",
      highlight: "Residential is for living; Commercial is for business. 🏢",
    },
    {
      id: 'reits_digital',
      title: 'Digital Land (REITs) 💻',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '💻',
      svgIcon: 'zap',
      content: "What if you want to invest in real estate but only have ₹500? \n\nA **REIT (Real Estate Investment Trust)** is like a mutual fund for property. A giant company buys thousands of malls and offices. You buy a tiny 'Share' of that company. You get your slice of the rent every month without ever having to fix a leaky toilet or talk to a tenant! It's real estate on autopilot. 🤖",
      highlight: "REITs are real estate for the 'lazy' and smart investor. 📱",
    },
    {
      id: 'flipping_vs_holding',
      title: 'The Flip vs The Hold 🔄',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🔄',
      svgIcon: 'activity',
      content: "**Flipping:** Buying an ugly house, fixing it up fast, and selling it for a profit in 6 months. It's high-speed and risky. \n\n**Holding:** Buying a good house and keeping it for 30 years. This is the slow and steady way to get rich. Flipping is a job; Holding is an investment. Most millionaires were made by holding, not by flipping! 🐢",
      highlight: "Flipping is for cash today; Holding is for wealth tomorrow. 🏰",
    },
    {
      id: 'property_taxes_maintenance',
      title: 'The Hidden Costs 💸',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '💸',
      svgIcon: 'alert',
      content: "A house isn't just a one-time cost. It's a 'Living Thing' that demands money! \n\n1. **Property Tax:** Every year, you must pay the government just for the right to own the land. \n2. **Maintenance:** Roofs leak, pipes burst, and walls need paint. You should set aside 1% of the house's value every year just for repairs. If you don't, your beautiful asset will slowly turn into a 'Money Pit.' 🏚️",
      highlight: "A house is an asset that 'eats' cash to stay alive. 🛠️",
    },
    {
      id: 'real_estate_cycle',
      title: 'The Boom and Bust 🎢',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🎢',
      svgIcon: 'chart',
      content: "Real estate moves in slow waves. \n\n**Boom:** Everyone is buying, prices are sky-high, and it's hard to find a deal. \n**Bust:** The economy slows, people can't pay their mortgages, and prices crash. \nThe best time to buy is when everyone is scared and the 'For Sale' signs are everywhere. In real estate, you make your money when you BUY, not when you sell! 📉",
      highlight: "Buy the panic, sell the hype. 🧠",
    },
  ],

  lab: {
    title: "The Property Empire Lab 🏗️",
    description: "Welcome to the Real Estate Simulator! Use 'The Financial Lever' to see how a small deposit controls a big house. Simulate the 'Tenant Loop' to see how long it takes for rent to pay off your loan, and test 'The Flip' to see if you can profit from a fixer-upper! 🏘️",
    hint: "Try the 'Leverage' mode. Watch what happens if the house price drops by just 10%—you can lose your entire deposit! Leverage magnifies both wins AND losses. Be careful!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks exact Rental Yield calculations, Stamp Duty math, and 'Equity Multiple' projections for professional investors.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why banks give the lowest interest rates for Home Loans? 🏠",
      answer: "Security! Unlike a car (which can drive away) or a business (which can go bankrupt), a house is stuck to the ground. If you stop paying, the bank can simply take the house and sell it to someone else. Because the risk for the bank is very low, they charge you the lowest price! 🛡️",
      emoji: '🏠',
    },
    {
      id: 'dyk2',
      question: "Do you know why the ultra-rich love 'Refinancing' their houses? 🔄",
      answer: "Tax-Free Cash! If your house value grows from ₹1 Crore to ₹2 Crores, you can't spend that 'extra' ₹1 Crore. But you can ask the bank for a NEW loan against that value. The bank gives you cash, and you don't pay any tax on it because it's a 'loan.' They use that cash to buy MORE houses! 🤯",
      emoji: '🏦',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'Location' is the only thing that matters? 📍",
      answer: "You can change the kitchen, you can paint the walls, and you can fix the roof. But you cannot move the house! A tiny shack in the center of a growing city is worth more than a mansion in the middle of a desert. Real estate is a bet on the *people* around the house, not the house itself! 📍",
      emoji: '🗺️',
    },
    {
      id: 'dyk4',
      question: "Do you know why 'Rental Yield' in India is so low compared to the US? 🇮🇳",
      answer: "Expectations! In India, people buy houses mainly because they expect the price to TRIPLE (Appreciation). Because they expect to get rich from the land value, they are okay with collecting tiny rent. In the US, people buy for the monthly rent income. It's a different way to play the same game! 📈",
      emoji: '⚖️',
    },
    {
      id: 'dyk5',
      question: "Do you know why you should never buy the 'Best House' on the street? 🏘️",
      answer: "The Ceiling Effect! If your house is the most expensive one in the neighborhood, its value is 'dragged down' by the cheaper houses around it. It's better to buy the UGLIEST house on the best street—the expensive neighbors will 'pull' your value up while you fix it! 🏗️",
      emoji: '🛠️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What makes Real Estate 'Finite'?", options: ["It's made of gold", "They aren't making any more land", "It's digital", "It's illegal to build"], answer: 1, explanation: "Land is the only asset that cannot be created or printed! 🌍" },
    { id: 'q2', question: "What is 'Leverage' in real estate?", options: ["Using a heavy tool to lift bricks", "Using a small amount of your money to control a large property with a bank loan", "Selling a house fast", "Paying zero taxes"], answer: 1, explanation: "Leverage lets you control a ₹10 Lakh asset with just ₹1 Lakh! 🏗️" },
    { id: 'q3', question: "What is 'Rental Yield'?", options: ["The speed at which you sell a house", "The annual rent income as a percentage of the house's cost", "The height of the building", "The color of the walls"], answer: 1, explanation: "It's the 'Fruit' your money tree produces every year! 🔄" },
    { id: 'q4', question: "What does 'Appreciation' mean?", options: ["Saying thank you to the tenant", "The increase in the market value of the property over time", "Paying off the loan", "The cost of repairs"], answer: 1, explanation: "It's the wealth built by the land getting more valuable! 📈" },
    { id: 'q5', question: "A 'Mortgage' is basically:", options: ["A type of insurance", "A long-term loan for a house where the house is the guarantee", "A tax on property", "A way to get free rent"], answer: 1, explanation: "The bank holds the house until you pay the debt! ⛓️" },
    { id: 'q6', question: "Commercial Real Estate involves renting to:", options: ["Families", "Businesses (Offices, Shops, Warehouses)", "Pets", "The government only"], answer: 1, explanation: "It's about business tenants and long-term contracts! 🏢" },
    { id: 'q7', question: "What is a REIT?", options: ["A type of concrete", "A digital way to own slices of many properties without actually buying them", "A law against renting", "A bank for builders"], answer: 1, explanation: "It's real estate for the stock market! 💻" },
    { id: 'q8', question: "What is 'House Flipping'?", options: ["Turning a house upside down", "Buying, fixing, and selling a property quickly for profit", "Renting to students", "Living in a house for 50 years"], answer: 1, explanation: "It's high-speed real estate trading! 🔄" },
    { id: 'q9', question: "What is the 'Hidden Cost' of owning a home?", options: ["Free cable TV", "Property Taxes and Maintenance/Repairs", "Winning the lottery", "Having too many windows"], answer: 1, explanation: "A house 'eats' money to stay healthy! 🛠️" },
    { id: 'q10', question: "Why is 'Location' so critical?", options: ["It determines the color of the paint", "You can change everything about a house except where it sits", "It's required by law", "It makes the house bigger"], answer: 1, explanation: "Location determines the demand and the future value! 📍" },
    { id: 'q11', question: "If you hit a 'Bust' in the real estate cycle, prices will:", options: ["Go up forever", "Drop or stay flat because nobody wants to buy", "Become zero", "Be controlled by the UN"], answer: 1, explanation: "Cycles mean prices go down as well as up! 🎢" },
    { id: 'q12', question: "What is OPM?", options: ["Old People's Money", "Other People's Money (using bank/investor cash to build wealth)", "Official Property Maker", "Only Property Matters"], answer: 1, explanation: "It's the secret to getting rich without being rich! 🏗️" },
    { id: 'q13', question: "Why are home loans safer for banks?", options: ["They like families", "The house is 'Collateral'—they can take it if you don't pay", "Houses never lose value", "It's illegal to not pay"], answer: 1, explanation: "The physical asset is the bank's safety net! 🛡️" },
    { id: 'q14', question: "In real estate, you make your profit when you:", options: ["Sell the house", "BUY the house at a good price", "Paint the house", "Call the agent"], answer: 1, explanation: "Buying cheap is how you guarantee a win later! 🧠" },
    { id: 'q15', question: "What is the 'Down Payment'?", options: ["The last payment of the loan", "The initial cash you pay from your own pocket (usually 10-20%)", "A bribe to the builder", "The tax on the sale"], answer: 1, explanation: "It's your 'Skin in the Game' to start the loan! 💰" },
    { id: 'q16', question: "Renting is often better than buying if:", options: ["You plan to move in 2 years", "You want to own a dog", "You have too much cash", "You hate the bank"], answer: 0, explanation: "Buying has high 'Entry/Exit' costs (taxes, fees) that need time to recover! ⏳" },
    { id: 'q17', question: "What is 'Foreclosure'?", options: ["Closing the front door", "When the bank takes the house because you stopped paying the loan", "A type of roof", "Renovating a kitchen"], answer: 1, explanation: "It's the end of a failed mortgage. 🏚️" },
    { id: 'q18', question: "A 'Fixer-Upper' is:", options: ["A specialized tool", "A run-down house bought cheaply to be repaired for profit", "A person who sells houses", "A brand new mansion"], answer: 1, explanation: "It's where you put in 'Sweat Equity' to build value! 🛠️" },
    { id: 'q19', question: "If a tenant's rent covers your full EMI, the house is:", options: ["Expensive", "Cash Flow Neutral (or Positive)", "A scam", "Free"], answer: 1, explanation: "It's the ultimate loop where someone else buys your asset! 🔄" },
    { id: 'q20', question: "Why buy the 'Uglies' on the 'Best Street'?", options: ["You like ugly things", "The high value of the neighbors' houses will pull your value up as you fix it", "It's cheaper to paint", "The street is safer"], answer: 1, explanation: "Neighbors determine the 'Price Ceiling' of your home! 🏘️" }
  ],

  relatedTopics: ['investing', 'personal_finance', 'banking'],
};
