// ─────────────────────────────────────────────────────────
//  TOPIC: MENTAL HEALTH BASICS
//  Category: Psychology / Health
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'mental_health_basics',
  title: 'Mental Health Basics',
  subtitle: 'Understanding the weather of the mind 🌤️🧠',
  emoji: '🧠',
  category: 'Psychology',
  accentKey: 'mental_health',

  hook: {
    question: "If you broke your leg, you would go to a doctor and wear a cast without feeling ashamed. Why do we feel differently when our mind feels 'broken'? 🩹",
    reveal: "Because for a long time, we didn't understand that mental health IS physical health! Your brain is an organ, just like your heart or lungs. It can get tired, overwhelmed, or sick. Understanding the 'Biological Weather' of your mind—from chemical imbalances to stress responses—is the first step to building a resilient, happy life. Let's destigmatize and dive in! 🌊🌿",
    emoji: '🌱',
  },

  theory: [
    {
      id: 'what_is_mental_health',
      title: 'Mental Health vs Illness ⚖️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'brain',
      content: "Mental health is not just the absence of mental illness. It is a state of well-being where you can realize your potential, cope with normal stresses, and work productively 📈.\n\nThink of it like a **Spectrum**. We all move back and forth between 'Healthy', 'Stressed', 'Struggling', and 'Unwell' depending on what is happening in our lives. \n\nJust as you exercise to keep your body fit, you can practice mental 'fitness' to keep your mind resilient! 🧘‍♂️",
      highlight: "Mental health is a spectrum, and everyone is on it! 🌈",
    },
    {
      id: 'anxiety_alarm',
      title: 'Anxiety: The Broken Alarm 🚨',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🚨',
      svgIcon: 'zap',
      content: "Anxiety is your body's natural response to stress—the **Fight or Flight** reflex. It is designed to keep you safe from predators 🦁.\n\nIn an anxiety disorder, the 'Alarm' (the Amygdala) becomes too sensitive. It starts going off for things that aren't actually dangerous, like a math test or a social gathering. \n\nPhysical symptoms include a racing heart, shallow breathing, and 'butterflies' 🦋. Your brain is preparing for a battle that isn't happening, which can feel exhausting.",
      highlight: "Anxiety is a survival system that is simply working 'overtime.' 🕹️",
    },
    {
      id: 'depression_cloud',
      title: 'Depression: The Heavy Cloud ☁️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '☁️',
      svgIcon: 'cloud',
      content: "Depression is more than just 'feeling sad'. It is a persistent feeling of heaviness, low energy, and a loss of interest in things you used to love (Anhedonia) 📉.\n\nBiologically, it's often linked to low levels of **Serotonin** and **Dopamine**—the chemicals that help you feel 'content' and 'rewarded'. \n\nIt's like trying to run a computer on low battery mode. Everything feels slower, harder, and less 'colorful'. It is a medical condition, not a choice or a weakness. 🔋",
      highlight: "Depression is a biological 'low energy' state, not a personality flaw. 🛑",
    },
    {
      id: 'neurochemistry',
      title: 'The Chemical Balance 🧪',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧪',
      svgIcon: 'flask',
      content: "Your mood is governed by **Neurotransmitters**—chemical messengers in the brain:\n\n• **Serotonin:** The 'Mood Stabilizer'. It helps with sleep, eating, and feeling calm 🧘.\n• **Dopamine:** The 'Reward'. It creates motivation and the 'spark' of joy 🏆.\n• **GABA:** The 'Brake'. It slows down neuron firing to reduce anxiety 🛑.\n\nMedications (like SSRIs) work by helping your brain maintain a healthy balance of these chemicals, similar to how insulin helps a diabetic manage sugar. 💊",
      highlight: "Your feelings have a biological foundation in your brain's chemistry. 🔬",
    },
    {
      id: 'stress_hpa_axis',
      title: 'The HPA Axis: Stress Boss 🏗️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'target',
      content: "When you're stressed, your brain triggers the **HPA Axis** (Hypothalamus-Pituitary-Adrenal). This sends a flood of **Cortisol** through your body 🧪.\n\nCortisol helps you act fast in an emergency, but if it stays high for weeks or months (Chronic Stress), it can damage your immune system and make it hard to sleep 😴.\n\nLearning to 'de-activate' this axis through breathing and relaxation is a vital skill for mental health. 🌬️",
      highlight: "Managing stress is about telling your HPA axis: 'The emergency is over.' 🛡️",
    },
    {
      id: 'power_of_therapy',
      title: 'The Power of Therapy 🗣️',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🗣️',
      svgIcon: 'sparkle',
      content: "Why does 'just talking' help? It's about **Neuroplasticity** 🧠.\n\n**Cognitive Behavioral Therapy (CBT)** helps you identify 'loops' of negative thoughts and manually re-wire them. By talking through a problem, you move the information from the emotional Amygdala to the logical **Prefrontal Cortex**. \n\nYou are literally teaching your brain new, healthier pathways to process the world! 🛤️ It's like 'Physical Therapy' for your thoughts.",
      highlight: "Therapy is the process of re-wiring your brain for better resilience. 🛠️",
    },
    {
      id: 'mindfulness_grounding',
      title: 'Mindfulness & Grounding 🧘',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🧘',
      svgIcon: 'eye',
      content: "When your mind is racing into the future (Anxiety) or lagging in the past (Regret), **Mindfulness** brings you back to the **Present Moment** 🕰️.\n\n**The 5-4-3-2-1 Technique:**\n• 5 things you can See 👀\n• 4 things you can Feel 🤚\n• 3 things you can Hear 👂\n• 2 things you can Smell 👃\n• 1 thing you can Taste 👅\n\nThis 'Grounding' forces your brain to focus on sensory input, which naturally lowers your heart rate and cuts through emotional 'fog.' 🌫️",
      highlight: "Grounding exercises 'pull' your brain out of its thoughts and back into your body. 🚶‍♂️",
    },
    {
      id: 'building_resilience',
      title: 'Building Resilience 🧱',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🧱',
      svgIcon: 'link',
      content: "Resilience is the ability to 'bounce back' from adversity. It's not about never feeling pain—it's about having the tools to recover 🩹.\n\nKey pillars of resilience:\n1. **Social Support:** Having even ONE person you can truly trust 🫂.\n2. **Self-Care:** Proper sleep, nutrition, and movement 🥗🏃.\n3. **Purpose:** Finding meaning in your daily actions 🌟.\n\nResilience is a muscle. The more you practice healthy coping mechanisms, the stronger it gets! 💪",
      highlight: "Resilience is built one small healthy choice at a time. 🧗‍♂️",
    },
    {
      id: 'ending_stigma',
      title: 'Ending the Stigma 🤫🚫',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🤫',
      svgIcon: 'shield',
      content: "Stigma is when we treat people with mental health struggles as 'weak' or 'different'. This shame often stops people from getting the help they need 🛑.\n\nIn reality, 1 in 4 people will experience a mental health issue in their lifetime. By talking openly about it, we prove that it's just another part of being human.\n\n**Words Matter:** Instead of saying 'He is crazy,' we say 'He is struggling with his health.' Moving from judgment to empathy saves lives. ❤️",
      highlight: "Speaking up is the 'antidote' to the silence of mental health struggles. 🗣️❤️",
    },
    {
      id: 'seeking_help',
      title: 'When & How to Seek Help 🆘',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🆘',
      svgIcon: 'target',
      content: "Recognizing when you need help is a sign of immense STRENGTH, not weakness 💪.\n\nIf you or a friend feel 'stuck' in a negative state for more than two weeks, or if thoughts become overwhelming, it's time to reach out. \n\n• **Talk to a trusted adult/friend** 🫂\n• **See a doctor or school counselor** 🏥\n• **Crisis Hotlines:** There are people available 24/7 to listen without judgment. \n\nYou don't have to carry the weight of the world alone. There is always a way forward! ✨",
      highlight: "Asking for help is the bravest thing a person can do. 🛡️",
    },
  ],

  lab: {
    title: "Resilience Garden Lab 🌿✨",
    description: "Experience the power of grounding! Your digital mind is currently caught in a 'Stress Storm' ⛈️. Use the 5-4-3-2-1 technique to find hidden elements in the environment. Watch as each 'Focus Task' lowers the Cortisol meter and transforms the grey storm into a vibrant, peaceful garden. 🧘‍♂️",
    hint: "Click on the colorful flowers to 'See,' the birds to 'Hear,' and the textures to 'Feel.' Watch the Amygdala glow (red) fade away as your Prefrontal Cortex (the Adult) takes back control of the brain's weather.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Vagus Nerve activation metrics, heart-rate variability (HRV) simulation, and real-time synaptic GABA release visuals.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why a 10-minute walk can change your entire mood? 🚶‍♂️✨",
      answer: "Biological flush! Exercise triggers the release of BDNF (Brain-Derived Neurotrophic Factor), which acts like 'Miracle-Gro' for your brain cells. It also uses up the excess Adrenaline and Cortisol floating in your blood, helping your body return to a 'Rest and Digest' state much faster! 🌳",
      emoji: '🌳',
    },
    {
      id: 'dyk2',
      question: "Do you know why teenagers' moods can be so 'Explosive'? 🌋",
      answer: "Brain construction! In teens, the Amygdala (Emotional Center) is already fully developed, but the Prefrontal Cortex (Logic/Regulatory Center) isn't finished until age 25. It's like having a Ferrari engine with bike brakes! It's not 'rebellion'—it's biology. 🏎️🛑",
      emoji: '🔋',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'Doomscrolling' makes you feel anxious? 📱🌀",
      answer: "Threat Detection! Your brain is evolved to pay 10x more attention to BAD news than good news (to keep you alive). When you scroll through negative headlines, your Amygdala thinks you are in a war zone and keeps the Stress Response permanently 'ON.' 🚨",
      emoji: '🚨',
    },
    {
      id: 'dyk4',
      question: "Do you know why petting a dog lowers your stress? 🐶❤️",
      answer: "Oxytocin! Physical contact with a pet triggers the release of the 'Bonding Hormone.' Oxytocin directly suppresses the production of Cortisol, making you feel safe and connected. It's a biological 'Anti-Stress' shield! 🛡️",
      emoji: '🐕',
    },
    {
      id: 'dyk5',
      question: "Do you know why you 'freeze' when you're terrified? 🥶",
      answer: "Parietal Hijack! When fear is too high, your brain decides that 'Fighting' or 'Fleeing' is impossible. It triggers the 'Freeze' response to make you less visible to a predator. It's your brain's last-ditch attempt to save you by making you 'disappear.' 🐭",
      emoji: '🦁',
    },
  ],

  quiz: [
    { id: 'q1', question: "Mental health is best described as:", options: ['The absence of all problems', 'A spectrum of well-being that everyone is on', 'A sign of weakness', 'Only for people who are sick'], answer: 1, explanation: "Everyone has mental health, just as everyone has physical health! 🌈" },
    { id: 'q2', question: "Which brain structure is the 'Emotional Alarm' that triggers anxiety?", options: ['Hippocampus', 'Amygdala', 'Skull', 'Prefrontal Cortex'], answer: 1, explanation: "The Amygdala is our ancient threat-detection center! 🚨" },
    { id: 'q3', question: "Depression is often linked to low levels of which 'Mood Stabilizer' chemical?", options: ['Oxygen', 'Serotonin', 'Sugar', 'Melanin'], answer: 1, explanation: "Serotonin helps balance mood, sleep, and appetite! 🧘" },
    { id: 'q4', question: "What is the 'Stress Hormone' produced by the HPA axis?", options: ['Adrenaline', 'Dopamine', 'Cortisol', 'Estrogen'], answer: 2, explanation: "Cortisol is great for emergencies but toxic if it stays high for too long! 🧪" },
    { id: 'q5', question: "The '5-4-3-2-1' technique is used for what purpose?", options: ['To count calories', 'To ground yourself in the present moment', 'To memorize math', 'To fall asleep faster'], answer: 1, explanation: "Grounding uses your senses to calm a racing mind! 👀" },
    { id: 'q6', question: "Which part of the brain acts as the 'Adult' that regulates emotional impulses?", options: ['Brainstem', 'Amygdala', 'Prefrontal Cortex (PFC)', 'Cerebellum'], answer: 2, explanation: "The PFC provides logic to counter emotional alarms! 🏛️" },
    { id: 'q7', question: "Cognitive Behavioral Therapy (CBT) primarily focuses on:", options: ['Taking medicine', 'Identifying and changing negative thought patterns', 'Sleeping better', 'Lifting weights'], answer: 1, explanation: "CBT is about re-wiring the way you perceive the world! 🛠️" },
    { id: 'q8', question: "What is 'Resilience'?", options: ['The ability to never feel sad', 'The ability to bounce back from challenges', 'Perfect physical health', 'Ignoring problems'], answer: 1, explanation: "Resilience is having the tools to recover when things get tough! 🧱" },
    { id: 'q9', question: "Stigma surrounding mental health often leads to:", options: ['Better hospitals', 'People feeling ashamed to seek help', 'More money for research', 'Better diets'], answer: 1, explanation: "Silence and shame are the biggest barriers to mental well-being! 🤫" },
    { id: 'q10', question: "If a friend feels 'stuck' in a negative state for over two weeks, you should:", options: ['Tell them to just be happy', 'Help them reach out to a trusted adult or professional', 'Ignore it', 'Give them a cookie'], answer: 1, explanation: "Professional help is vital when a state becomes 'stuck.' 🆘" },
    { id: 'q11', question: "Mental health is considered:", options: ['Minor compared to physical health', 'Equally important as physical health', 'A myth', 'Only for adults'], answer: 1, explanation: "Healthy mind = Healthy body! They are inseparable. 🧬" },
    { id: 'q12', question: "Anxiety is a survival reflex designed to prepare the body for:", options: ['Sleep', 'Fight or Flight', 'Digestion', 'Reading'], answer: 1, explanation: "Your body is trying to protect you from a perceived threat! 🦁" },
    { id: 'q13', question: "BDNF (released during exercise) is often called what for the brain?", options: ['A Poison', 'Miracle-Gro (helps neurons grow)', 'A map', 'A lock'], answer: 1, explanation: "Exercise literally helps your brain repair and grow! 🌳" },
    { id: 'q14', question: "Why can long-term stress cause memory problems?", options: ['You run out of space', 'Chronic Cortisol can shrink the Hippocampus', 'Brains get full', 'None of these'], answer: 1, explanation: "Stress physically impacts the memory-forming centers of the brain! 📉" },
    { id: 'q15', question: "Holding a cold ice cube to snap out of a panic attack is an example of:", options: ['Grounding', 'Self-harm', 'A joke', 'Hypnosis'], answer: 0, explanation: "Sudden sensory input breaks the emotional 'loop'! 🧊" },
    { id: 'q16', question: "The feeling that 'nothing matters' or a lack of interest in hobbies is called:", options: ['Laziness', 'Anhedonia', 'Boredom', 'Hunger'], answer: 1, explanation: "This is a core symptom of clinical depression! 🔋" },
    { id: 'q17', question: "Oxytocin (The 'Bonding Hormone') has what effect on Cortisol?", options: ['It raises it', 'It suppresses/lowers it', 'No effect', 'It turns it into sugar'], answer: 1, explanation: "Connection and love are biological antidotes to stress! ❤️" },
    { id: 'q18', question: "At what approximate age is the human brain's regulatory system (PFC) fully developed?", options: ['12', '18', '25', '40'], answer: 2, explanation: "This is why young adults are more prone to emotional risk-taking! 🏎️" },
    { id: 'q19', question: "What is the first step in helping someone with a mental health struggle?", options: ['Fixing their life', 'Listening without judgment', 'Giving them money', 'Telling them they are wrong'], answer: 1, explanation: "Empathy and listening are the foundation of support! 🫂" },
    { id: 'q20', question: "Mindfulness basically means:", options: ['Having a full brain', 'Focusing on the present moment without judgment', 'Doing math', 'Sleeping deeply'], answer: 1, explanation: "It's about 'Checking in' with yourself right now! 🕰️" },
  ],

  relatedTopics: ['brain_structure', 'emotions_motivation', 'cognitive_biases'],
};
