export default {
  id: "big_bang",
  title: "Big Bang Theory",
  subtitle: "The origin of space, time, and matter 🌌",
  emoji: "🌌",
  category: "Space",
  accentKey: "space",

  hook: {
    question: "If you could rewind time by 13.8 billion years, would the entire universe fit inside your pocket? 🌌",
    reveal: "Yes! In the very beginning, every star, every galaxy, and every atom in existence was crushed into a point smaller than a single electron—it was infinitely hot and infinitely dense. Then, in a fraction of a second, it aggressively expanded (inflated), creating the fabric of space itself. The universe didn't 'explode' INTO space; space itself was created and stretched! 💥",
    emoji: "💥",
  },

  theory: [
    {
      id: "bb_0",
      title: "The Singularity 🧶",
      color: "#0c0d0eff",
      bgGradient: ["#000000", "#050D0A"],
      icon: "🧶",
      svgIcon: "blackhole",
      content: "Before the Big Bang, there was no 'where' and no 'when.' Everything was a Singularity—a point of infinite density. \n\nTime and space did not exist yet. It wasn't 'empty space' waiting to be filled; the Singularity was the ONLY thing that existed. Then, 13.8 billion years ago, the stopwatch of the universe started! ⏱️",
      highlight: "The ultimate cosmic starting line! 🚩",
    },
    {
      id: "bb_1",
      title: "Cosmic Inflation 🎈",
      color: "#FF3131",
      bgGradient: ["#200000", "#050D0A"],
      icon: "🎈",
      svgIcon: "zap",
      content: "In a tiny fraction of a second ($10^{-36}$ s), the universe expanded from the size of an atom to the size of a galaxy! \n\nThis is called **Inflation**. It happened faster than the speed of light because it wasn't matter moving through space—it was space itself stretching! This explains why the universe looks so smooth in every direction. 🛋️",
      highlight: "The most aggressive growth spurt in history! 📈",
    },
    {
      id: "bb_2",
      title: "Quark-Gluon Plasma 🍲",
      color: "#FFD166",
      bgGradient: ["#201500", "#050D0A"],
      icon: "🍲",
      svgIcon: "sun",
      content: "In the first few microseconds, the universe was a super-hot 'soup' of quarks and gluons. \n\nIt was too hot for atoms or even protons to form. The energy was so high that matter and anti-matter were constantly being created and destroying each other. Eventually, a tiny bit more matter survived than anti-matter—and that's what we are made of! 🏛️",
      highlight: "The universe's hottest, thickest soup! 🥣",
    },
    {
      id: "bb_3",
      title: "Nucleosynthesis ⚛️",
      color: "#10B981",
      bgGradient: ["#002010", "#050D0A"],
      icon: "⚛️",
      svgIcon: "atom",
      content: "After about 3 minutes, the universe cooled enough for protons and neutrons to stick together. \n\nThis formed the first atomic nuclei: Hydrogen, Helium, and a tiny bit of Lithium. This 'Big Bang Nucleosynthesis' set the recipe for every star that would ever be born! 🍳",
      highlight: "The first 3 minutes built the cosmic foundation! 🧱",
    },
    {
      id: "bb_4",
      title: "Recombination: Let there be Light! ✨",
      color: "#00E5FF",
      bgGradient: ["#001020", "#050D0A"],
      icon: "✨",
      svgIcon: "sun",
      content: "For 380,000 years, the universe was a foggy mess of charged particles that trapped light. \n\nWhen it finally cooled enough for electrons to join nuclei and form neutral atoms, the fog cleared. Light was finally free to travel across space! This first light is still visible today as the **Cosmic Microwave Background (CMB)**. 📸",
      highlight: "The moment the universe turned the lights on! 💡",
    },
    {
      id: "bb_5",
      title: "The Dark Ages 🌑",
      color: "#888888",
      bgGradient: ["#101010", "#050D0A"],
      icon: "🌑",
      svgIcon: "cloud",
      content: "After the first light, there were no stars yet. The universe was just a vast, dark sea of Hydrogen gas expanding in total silence. \n\nFor 100 million years, gravity slowly worked in the shadows, pulling gas clouds together into tighter and tighter knots until the first stars finally ignited! 🕯️",
      highlight: "The long-wait for the first sunrise! ⏳",
    },
    {
      id: "bb_6",
      title: "The Big Freeze vs. Big Crunch ❄️",
      color: "#3B82F6",
      bgGradient: ["#051020", "#050D0A"],
      icon: "❄️",
      svgIcon: "snowflake",
      content: "What is the end of the story? If the universe keeps expanding, it will eventually become too cold and empty for life—the **Big Freeze**. \n\nIf gravity somehow pulls it all back together, it could end in a **Big Crunch**. Currently, evidence suggests Dark Energy is winning, and the universe will expand forever! 🌌",
      highlight: "The final fate of all things! 🕰️",
    },
    {
      id: "bb_7",
      title: "Dark Matter & Dark Energy 🕶️",
      color: "#A855F7",
      bgGradient: ["#150A20", "#050D0A"],
      icon: "🕶️",
      svgIcon: "layers",
      content: "We can only see 5% of the universe. The rest is invisible. \n\n**Dark Matter** provides the extra gravity to hold galaxies together, and **Dark Energy** is a mysterious force pushing space apart faster and faster every second. We are living in a universe dominated by ghosts! 👻",
      highlight: "The invisible masters of the cosmos! 🏛️",
    },
    {
      id: "bb_8",
      title: "Redshift: The Smoking Gun 🔭",
      color: "#EF4444",
      bgGradient: ["#200A0A", "#050D0A"],
      icon: "🔭",
      svgIcon: "activity",
      content: "How do we know the Big Bang happened? Edwin Hubble saw that distant galaxies are all moving away from us. \n\nThe light from these galaxies is stretched out (reddened), which is called **Redshift**. This proves that the 'fabric' of the universe is still expanding today! 🥖",
      highlight: "The universe is growing like rising bread dough! 🍞",
    },
    {
      id: "bb_9",
      title: "Timeline of Everything 📅",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "📅",
      svgIcon: "repeat",
      content: "A quick summary: Singularity ($0s$) → Inflation ($10^{-36}s$) → Nucleosynthesis ($3 mins$) → First Light ($380k yrs$) → First Stars ($100M yrs$) → Today ($13.8B yrs$). \n\nOn this scale, human history is just the final millisecond of a 24-hour day! ⏳",
      highlight: "Humanity is a tiny blip on a cosmic calendar! 🗓️",
    },
  ],

  lab: {
    title: "Inflation Engine 🎈",
    description: "Welcome to the Beginning of Time. Control the clock of the universe and observe how its temperature, density, and contents change from the first microsecond to the modern era.",
    hint: "Click 'IGNITE' to trigger the 10^-36s Inflation phase!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time Cosmological Redshift ($z$), Temperature ($T$), and the scale factor of space ($a$).",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know where the 'Static' on old TVs comes from? 📺",
      answer: "About 1% of that 'snow' static is actually the Cosmic Microwave Background—the actual leftover heat and noise from the Big Bang itself! 🌌",
      emoji: "📺",
    },
    {
      id: "dyk2",
      question: "Do you know what 'Dark Energy' is doing? 🚀",
      answer: "It is aggressively pushing galaxies apart! Even though gravity tries to pull them together, space itself is expanding so fast that most galaxies will eventually vanish from our view! 🔭",
      emoji: "🔭",
    },
    {
      id: "dyk3",
      question: "Do you know what happened 'Before' the Big Bang? 🧶",
      answer: "This is a trick question! Time didn't exist yet, so there was no 'before.' It's like asking 'What is North of the North Pole?' 🧭",
      emoji: "🧭",
    },
    {
      id: "dyk4",
      question: "Do you know how big the observable universe is? 📏",
      answer: "93 Billion light-years across! Because space has been expanding while light travels, the edge of what we can see is much further than 13.8 billion light-years! 🌌",
      emoji: "🌌",
    },
    {
      id: "dyk5",
      question: "Do you know if the Big Bang had a 'Center'? 🎯",
      answer: "Nope! It didn't happen in a place; it happened EVERYWHERE at once. Every point in space was once part of the same tiny speck! 🌍",
      emoji: "🌍",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "The universe began approximately how many years ago?",
      options: ["4.5 Billion", "13.8 Billion", "1 Trillion", "100 Million"],
      answer: 1,
      explanation: "Analysis of the CMB and expansion rates gives us the 13.8B figure! 🕰️",
    },
    {
      id: "q2",
      question: "What was the initial ultra-dense point of the universe called?",
      options: ["Black Hole", "Nebula", "Singularity", "Protostar"],
      answer: 2,
      explanation: "A point of infinite density where all of space-time was compressed! 🧶",
    },
    {
      id: "q3",
      question: "The extremely rapid expansion in the first fraction of a second was...",
      options: ["The Big Crunch", "Inflation", "Supernova", "Formation"],
      answer: 1,
      explanation: "Inflation caused the universe to grow by trillions of times in an instant! 🎈",
    },
    {
      id: "q4",
      question: "What is the 'leftover noise' from the Big Bang visible today?",
      options: ["Starlight", "Dark Matter", "Cosmic Microwave Background (CMB)", "Solar Wind"],
      answer: 2,
      explanation: "It's the first light that traveled freely after the universe cooled! 📸",
    },
    {
      id: "q5",
      question: "In the first few minutes, which three elements were forged?",
      options: ["Iron, Gold, Silver", "Hydrogen, Helium, Lithium", "Carbon, Oxygen, Nitrogen", "Uranium, Plutonium, Lead"],
      answer: 1,
      explanation: "Only the simplest nuclei could form in the Big Bang furnace! ⚛️",
    },
    {
      id: "q6",
      question: "What is the invisible force currently pushing the universe apart?",
      options: ["Gravity", "Static Electricity", "Dark Energy", "Nuclear Force"],
      answer: 2,
      explanation: "Dark Energy is the mysterious force accelerating expansion! 🚀",
    },
    {
      id: "q7",
      question: "The stretching of light from distant galaxies is called...",
      options: ["Whiteshift", "Blueshift", "Redshift", "Yellowshift"],
      answer: 2,
      explanation: "Distant light waves are 'stretched' into longer, redder wavelengths! 🔭",
    },
    {
      id: "q8",
      question: "For the first 380,000 years, the universe was...",
      options: ["Frozen solid", "Transparent", "A dense, opaque fog", "Full of stars"],
      answer: 2,
      explanation: "Light couldn't move because it kept hitting charged particles! 🌫️",
    },
    {
      id: "q9",
      question: "What happened after the 'Recombination' era?",
      options: ["The universe became dark", "Stars ignited immediately", "Matter vanished", "Black holes formed"],
      answer: 0,
      explanation: "The universe entered the 'Dark Ages' before the first stars formed! 🌑",
    },
    {
      id: "q10",
      question: "Which invisible stuff provides the gravity to hold galaxies together?",
      options: ["Space Gas", "Dark Matter", "Cosmic Dust", "Anti-matter"],
      answer: 1,
      explanation: "Dark Matter doesn't emit light but has massive gravity! 🕶️",
    },
    {
      id: "q11",
      question: "What did anti-matter do in the early universe?",
      options: ["Created the stars", "Cooled the gas", "Annihilated with matter", "Formed the Earth"],
      answer: 2,
      explanation: "Matter and Anti-matter destroyed each other, but a tiny bit of matter survived! 💥",
    },
    {
      id: "q12",
      question: "Inflation happened faster than what speed?",
      options: ["Speed of sound", "Speed of a rocket", "Speed of light", "Speed of thought"],
      answer: 2,
      explanation: "Because space itself was stretching, it ignored the 'light speed' limit! ⚡",
    },
    {
      id: "q13",
      question: "The 'Dark Ages' ended when which events happened?",
      options: ["The Big Bang", "The First Stars Ignited", "Humans evolved", "Earth formed"],
      answer: 1,
      explanation: "First-generation stars (Population III) finally lit up the dark! 🕯️",
    },
    {
      id: "q14",
      question: "Edwin Hubble discovered the expansion of the universe by observing...",
      options: ["Planets", "The Sun", "Distant Galaxies", "Black Holes"],
      answer: 2,
      explanation: "He saw that almost every galaxy was rushing away from us! 🏃‍♂️",
    },
    {
      id: "q15",
      question: "Current evidence suggests the universe will likely end in a...",
      options: ["Big Crunch", "Big Freeze / Heat Death", "Big Splat", "Solid Ice Cube"],
      answer: 1,
      explanation: "Due to expansion, everything will eventually be too far apart to interact! ❄️",
    },
    {
      id: "q16",
      question: "The Singularity is a point of ______ density.",
      options: ["Zero", "Low", "Infinite", "Average"],
      answer: 2,
      explanation: "An unimaginable amount of mass in a point of zero size! 🧶",
    },
    {
      id: "q17",
      question: "What is the 'Era of Nuclei'?",
      options: ["First 3 minutes", "380k to 1B years", "Modern age", "First trillion years"],
      answer: 0,
      explanation: "This was when the first Hydrogen and Helium centers formed! ⚛️",
    },
    {
      id: "q18",
      question: "Which force is currently trying to SLOW DOWN the expansion?",
      options: ["Dark Energy", "Centrifugal", "Gravity", "Light Pressure"],
      answer: 2,
      explanation: "Gravity pulls things together, while Dark Energy pushes apart! ⚖️",
    },
    {
      id: "q19",
      question: "Inflation happened ________ after the start.",
      options: ["1 Billion Years", "3 Minutes", "$10^{-36}$ seconds", "1 Hour"],
      answer: 2,
      explanation: "It was nearly instantaneous at the very beginning! ⏱️",
    },
    {
      id: "q20",
      question: "Are we moving away from the 'Center' of the Big Bang?",
      options: ["Yes, to the left", "No, we are at the center", "No, everyone moves away from everyone else", "Yes, toward Andromeda"],
      answer: 2,
      explanation: "Space expands everywhere simultaneously, like a balloon inflating! 🎈",
    },
  ],

  relatedTopics: ["stars_lifecycle", "gravity", "solar_system"],
};
