export default {
  id: "relativity_basics",
  title: "Relativity",
  subtitle: "Einstein's mind-bending rule of light 🚀",
  emoji: "🚀",
  category: "Physics",
  accentKey: "physics",

  hook: {
    question: "If you travel exactly at the speed of light for 10 years and return to Earth, why are you physically violently exactly the mathematically same age, but your friends are profoundly completely fiercely dead of old age? ⏳",
    reveal: "The absolute violent reality of Time Dilation! Einstein strictly mathematically proved that Time completely is NOT a constant ticking clock. It is physically bendy! The faster you aggressively move through physical space, the fiercely violently strictly slower you mathematically strictly move through absolute Time! 🌌",
    emoji: "🚀",
  },

  theory: [
    {
      id: "rel_0",
      title: "The Speed of Light: The Hard Limit 🚫",
      color: "#FF3131",
      bgGradient: ["#200A0A", "#050D0A"],
      icon: "🚫",
      svgIcon: "alert-triangle",
      content: "The speed of light ($c = 299,792,458$ m/s) is the absolute, ultimate speed limit of the universe! \n\nNothing with mass can ever reach it. As you move faster, your mass effectively increases toward infinity, demanding infinite energy to accelerate further! Light is the only thing fast enough to outrun everything else! 🚧",
      highlight: "Light is so fast it could circle the entire Earth 7.5 times in exactly one second! 🌍",
    },
    {
      id: "rel_1",
      title: "Time Dilation: Stretching Time ⏳",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "⏳",
      svgIcon: "clock",
      content: "Time is relative! The faster you move through space, the slower you move through time! \n\nThis isn't a trick or an illusion—clocks on speeding spaceships literally tick slower than clocks on Earth. If you spent a few years moving at 99.9% light speed, you might return to an Earth that is hundreds of years in the future! 🕰️",
      highlight: "Astronauts on the ISS age 0.007 seconds slower than us every 6 months! 👨‍🚀",
    },
    {
      id: "rel_2",
      title: "Length Contraction: Squashing Space 📏",
      color: "#FFD166",
      bgGradient: ["#2A2A00", "#050D0A"],
      icon: "📏",
      svgIcon: "target",
      content: "As you approach the speed of light, physical space actually shrinks in the direction you are moving! \n\nTo an outside observer, your 100-meter long spaceship would look like it's only 10 meters long! Space and Time are locked together in a single fabric called **Space-Time**, and they bend together! 🌌",
      highlight: "From the perspective of a photon (light particle), the distance across the entire universe is ZERO! 🎆",
    },
    {
      id: "rel_3",
      title: "E = mc²: Energy is Mass ⚡",
      color: "#A855F7",
      bgGradient: ["#1A0A1F", "#050D0A"],
      icon: "⚡",
      svgIcon: "zap",
      content: "Einstein's most famous equation proves that Energy and Mass are the same thing in different forms! \n\nA tiny amount of mass contains a colossal, violent amount of energy ($c^2$ is a huge number). This is the secret power behind the Sun, nuclear reactors, and the most powerful explosions in history! ☀️",
      highlight: "The energy inside a single paperclip is enough to power a small city for an entire day! 🏙️",
    },
    {
      id: "rel_4",
      title: "Simultaneity: It's All Subjective 👁️",
      color: "#39FF14",
      bgGradient: ["#0A200A", "#050D0A"],
      icon: "👁️",
      svgIcon: "activity",
      content: "Two events that look like they happen at the same time to you might happen at totally different times to someone moving fast! \n\nThere is no 'Absolute Now' in the universe. Everyone has their own personal clock and their own personal version of reality depending on their speed! 🕰️",
      highlight: "Relativity means 'Now' is a local concept, not a universal one! 🌌",
    },
    {
      id: "rel_5",
      title: "General Relativity: Bending Gravity 🪐",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🪐",
      svgIcon: "globe",
      content: "Gravity isn't a 'pulling' force—it's the warping of Space-Time itself! \n\nImagine placing a bowling ball on a trampoline. It curves the fabric. Massive objects like stars and planets curve the fabric of the universe, and objects (like moons) simply fall along those curves. This is why light itself bends when it passes a star! ✨",
      highlight: "Black holes are regions where the curve is so deep and steep that even light can't climb back out! 🕳️",
    },
    {
      id: "rel_6",
      title: "Gravitational Time Dilation 🕰️",
      color: "#6C5CE7",
      bgGradient: ["#100A20", "#050D0A"],
      icon: "🕰️",
      svgIcon: "hash",
      content: "It's not just speed—Gravity also slows down time! \n\nThe stronger the gravity, the slower time ticks. A clock on the surface of a massive planet ticks slower than a clock floating in deep space. If you hung out near a black hole for an hour, decades would pass for everyone else! ⌚",
      highlight: "Your feet are actually slightly 'younger' than your head because they are closer to Earth's gravity! 🦵",
    },
    {
      id: "rel_7",
      title: "GPS: Relativity in Your Pocket 🛰️",
      color: "#10B981",
      bgGradient: ["#0A2015", "#050D0A"],
      icon: "🛰️",
      svgIcon: "navigation",
      content: "Relativity isn't just for science fiction! \n\nGPS satellites involve high speeds (Time Dilation) and weak gravity (Gravitational Dilation). Without Einstein's math, GPS clocks would get out of sync by 10 kilometers every single day! Your phone literally uses relativity to find the nearest coffee shop. 📱",
      highlight: "The math of Relativity is used billions of times a day by our technology! 📶",
    },
    {
      id: "rel_8",
      title: "The Twin Paradox: Forever Young 👬",
      color: "#EC4899",
      bgGradient: ["#200A15", "#050D0A"],
      icon: "👬",
      svgIcon: "heart",
      content: "If one twin stays on Earth and the other flies to a star at 90% light speed, the traveling twin returns to find their brother is much older! \n\nEach twin thought the OTHER person's clock was slower, but because the traveler had to accelerate and turn around, they are the one who actually 'skipped' through time relative to Earth! 🚀",
      highlight: "This is a real effect confirmed by experiments with atomic clocks on airplanes! ✈️",
    },
    {
      id: "rel_9",
      title: "Wormholes: Cosmic Shortcuts 🌀",
      color: "#8B5CF6",
      bgGradient: ["#150A20", "#050D0A"],
      icon: "🌀",
      svgIcon: "repeat",
      content: "General Relativity allows for 'bridges' through Space-Time! \n\nA wormhole is a theoretical tunnel that connects two distant points in space, allowing you to travel across the galaxy faster than light could through normal space! While we haven't found one yet, the math says they *could* exist. 🌌",
      highlight: "Traveling through a wormhole could theoretically be a way to travel backward in time! ⏪",
    },
  ],

  lab: {
    title: "Twin Paradox Racer 🛸",
    description: "Launch your spaceship near the speed of light! Observe how Time Dilation mathematically stretches the years between you and Earth as you push the limits of Einstein's speed limit!",
    hint: "Push your velocity to 99% of light speed (c) to see years pass on Earth while only months pass for you!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays the real-time Lorentz Factor ($γ$) and relativistic mass equations.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why we can't see a Black Hole? 🕳️",
      answer: "Because their gravity is so violent that even light—the fastest thing in the universe—isn't fast enough to escape. Since no light reflects or emits from it, the hole remains perfectly invisible to our eyes! 🌌",
      emoji: "🔦",
    },
    {
      id: "dyk2",
      question: "Do you know why we see stars where they aren't? ✨",
      answer: "Gravitational Lensing! Massive objects like the Sun curve space-time. As a star's light passes the Sun, it follows the curve, making the star appear to be in a slightly different position than it actually is! 🔭",
      emoji: "😵",
    },
    {
      id: "dyk3",
      question: "Do you know why Nothing can go faster than light? 🚫",
      answer: "Because Mass and Energy are linked! To make an object hit light speed, you'd need to give it more energy. But that energy turns into more mass. At $c$, the object would have infinite mass and require infinite energy—which is impossible! ⚡",
      emoji: "🔋",
    },
    {
      id: "dyk4",
      question: "Do you know why the Sun takes 8 minutes to reach us? ☀️",
      answer: "Light speed is finite! Even though it's 300,000 km/s, the Sun is 150 million km away. If the Sun exploded right now, we wouldn't know or even see it until 8 minutes later! ⏳",
      emoji: "🕰️",
    },
    {
      id: "dyk5",
      question: "Do you know how gravity affects your lifespan? ⌚",
      answer: "Gravitational Time Dilation! Time moves slower in stronger gravity. Technically, someone living in a penthouse on the 100th floor ages slightly faster than someone living in the basement! 🏢",
      emoji: "🏙️",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What is the universal speed limit for anything with mass?",
      options: ["10,000 mph", "The Speed of Sound", "The Speed of Light (c)", "Mach 5"],
      answer: 2,
      explanation: "Einstein proved that nothing with mass can ever reach or exceed 300,000 km/s! 🚀",
    },
    {
      id: "q2",
      question: "What happens to time as you move faster through space?",
      options: ["Time speeds up", "Time stays the same", "Time slows down (Time Dilation)", "Time stops entirely"],
      answer: 2,
      explanation: "The more space you cover, the less time you 'experience'! ⏳",
    },
    {
      id: "q3",
      question: "What does Einstein's famous equation E = mc² prove?",
      options: ["Energy and Mass are the same thing", "Electricity is fast", "Gravity is a pull", "Magnetic force is heavy"],
      answer: 0,
      explanation: "Mass is essentially 'locked up' energy, and energy has equivalent mass! ⚡",
    },
    {
      id: "q4",
      question: "According to General Relativity, what is Gravity?",
      options: ["A mysterious invisible rope", "The curvature of Space-Time fabric", "Magnetic attraction", "Air pressure"],
      answer: 1,
      explanation: "Massive objects like stars warp the 'fabric' of the universe itself! 🪐",
    },
    {
      id: "q5",
      question: "What is 'Length Contraction'?",
      options: ["Time getting shorter", "Space shrinking in the direction of motion", "Stars getting smaller", "Planets getting heavier"],
      answer: 1,
      explanation: "Fast-moving objects actually take up less space in the direction they are traveling! 📏",
    },
    {
      id: "q6",
      question: "Why do GPS satellites need Relativity math to work?",
      options: ["To find the moon", "To adjust for time differences caused by speed and gravity", "To save battery", "To talk to phones"],
      answer: 1,
      explanation: "Without adjustment, GPS locations would be off by miles every day! 🛰️",
    },
    {
      id: "q7",
      question: "What happens near a Black Hole?",
      options: ["Time ticks faster", "Gravity is zero", "Time slows down massively", "Space becomes flat"],
      answer: 2,
      explanation: "Intense gravity causes extreme gravitational time dilation! 🕳️",
    },
    {
      id: "q8",
      question: "What is a 'Wormhole'?",
      options: ["A hole in a star", "A theoretical shortcut through Space-Time", "A dead planet", "A magnetic field"],
      answer: 1,
      explanation: "It's a mathematical bridge connecting two distant points in space! 🌀",
    },
    {
      id: "q9",
      question: "Who was the legendary physicist who formulated Relativity?",
      options: ["Isaac Newton", "Albert Einstein", "Nikola Tesla", "Marie Curie"],
      answer: 1,
      explanation: "Einstein revolutionized our understanding of the universe in 1905 and 1915! 👴",
    },
    {
      id: "q10",
      question: "As an object approaches the speed of light, its mass...",
      options: ["Decreases", "Stays the same", "Effectively increases toward infinity", "Becomes zero"],
      answer: 2,
      explanation: "More energy turns into more mass, making it harder and harder to accelerate! 🏗️",
    },
    {
      id: "q11",
      question: "What is 'Simultaneity'?",
      options: ["Two things happening at once", "A type of light", "A gravity wave", "Absolute rest"],
      answer: 0,
      explanation: "Relativity proves that 'at the same time' depends on your speed! 👁️",
    },
    {
      id: "q12",
      question: "From a photon's perspective, how long does it take to cross the universe?",
      options: ["Billions of years", "Exactly zero time", "10 seconds", "One hour"],
      answer: 1,
      explanation: "At the speed of light, time dilation is so infinite that time doesn't exist! 🎆",
    },
    {
      id: "q13",
      question: "Which twin ages more in the Twin Paradox?",
      options: ["The one in the spaceship", "The one who stayed on Earth", "They age the same", "Neither ages at all"],
      answer: 1,
      explanation: "The stationary twin on Earth experiences the full passage of time! 👬",
    },
    {
      id: "q14",
      question: "Where is time ticking slower: Earth or the Moon?",
      options: ["Earth (higher gravity)", "The Moon (lower gravity)", "They are identical", "Deep space is faster"],
      answer: 0,
      explanation: "Higher gravity slows down the tick-rate of time! 🌍",
    },
    {
      id: "q15",
      question: "What proved General Relativity in 1919?",
      options: ["A car race", "Observing a solar eclipse bending starlight", "A radio broadcast", "The First World War"],
      answer: 1,
      explanation: "Light from stars was curved by the Sun's gravity, just as Einstein predicted! ☀️",
    },
    {
      id: "q16",
      question: "Why can't we go back in time using current physics?",
      options: ["No batteries", "It would require going faster than light (impossible mass)", "The sun is too hot", "Gravity is too weak"],
      answer: 1,
      explanation: "Breaking the light-speed barrier is the only theoretical 'door' to the past! ⏪",
    },
    {
      id: "q17",
      question: "What is the 'Space-Time' continuum?",
      options: ["A movie theater", "The 4-dimensional fabric of space and time coupled together", "Empty air", "The solar system"],
      answer: 1,
      explanation: "Space and Time are not separate; they are one locked grid! 🌌",
    },
    {
      id: "q18",
      question: "A Black Hole's 'Event Horizon' is the point where...",
      options: ["Space starts", "Gravity becomes weak", "Not even light can escape", "Time stops moving"],
      answer: 2,
      explanation: "Once you cross this 'border', there is no returning! 🚪",
    },
    {
      id: "q19",
      question: "How long is a light-year?",
      options: ["The distance light travels in a year", "The time it takes for a year to pass", "One million miles", "The weight of light"],
      answer: 0,
      explanation: "It's a measure of distance (about 6 trillion miles), not time! 📏",
    },
    {
      id: "q20",
      question: "Einstein's 'Special' Relativity dealt with...",
      options: ["Planets and Suns", "Constant speed and the Speed of Light", "Volcanoes", "Human biology"],
      answer: 1,
      explanation: "Special relativity focused on speed, while General focused on Gravity! 🔬",
    },
  ],

  relatedTopics: ["quantum_basics", "gravity"],
};
