// ─────────────────────────────────────────────────────────
//  TOPIC: SELF-ESTEEM (आत्म-सम्मान)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'self_esteem',
  title: 'Self-Esteem',
  subtitle: 'The Architecture of Self-Worth 🏛️🪞',
  emoji: '🪞',
  category: 'Mental Health',
  accentKey: 'self_esteem',

  hook: {
    question: "If someone spoke to you the way you speak to yourself inside your head, how long would you stay friends with them?",
    reveal: "Probably not even a day.\n\nYet, we accept a level of vicious, constant criticism from our own minds that we would never accept from a stranger. Self-esteem isn't about looking in the mirror and shouting, 'I am the greatest!' It is about dismantling the deep-rooted programming of the 'Inner Critic' and building a foundation of unconditional self-reliance. Let's explore how to finally make peace with the person you spend every second of your life with: You. 🪞🤝🧱",
    emoji: '🧱',
  },

  theory: [
    {
      id: 'what_is_self_esteem',
      title: "Confidence vs. Self-Esteem 🎭",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'shield',
      svgIcon: 'eye',
      content: "**Confidence** is about your *abilities*. It's situational. ('I am confident I can pass this math test.')\n\n**Self-Esteem** is about your *inherent worth*. It's global. ('Even if I fail this math test, I am still a worthy human being.')\nYou can be highly confident in your career (a CEO) but have terribly low self-esteem (believing you are unlovable).",
      highlight: "Confidence is how you perform. Self-Esteem is how you value the performer. ⚖️",
    },
    {
      id: 'the_inner_critic',
      title: "The Inner Critic 👿",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'mic',
      svgIcon: 'flame',
      content: "We all have an 'Inner Critic'—a voice that tells us we are lazy, ugly, or stupid.\nWhere did it come from? Psychologists believe it is an internalized voice of demanding parents, bullies, or societal standards. \nIronically, the critic was originally formed as a clumsy defense mechanism: *'If I criticize myself first and make myself perfect, nobody else can hurt me.'*",
      highlight: "The critic is just a scared child trying to protect you. You don't have to listen to it. 🛡️",
    },
    {
      id: 'conditional_worth',
      title: "The Trap of Conditional Worth 📎",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'paperclip',
      svgIcon: 'lock',
      content: "Many of us operate on **Conditional Worth**: 'I am only valuable IF I get good grades, IF I am skinny, IF I make money.'\nThis is a psychological trap. If your worth is tied to external achievements, your self-esteem will crash the moment you fail.\nHealthy self-esteem requires detaching your identity from your output.",
      highlight: "You are not a human *doing*; you are a human *being*. 🧘‍♂️",
    },
    {
      id: 'imposter_syndrome',
      title: "Imposter Syndrome 🕵️‍♂️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'user-x',
      svgIcon: 'users',
      content: "Do you ever feel like a fraud who is going to be 'found out' at any moment?\n**Imposter Syndrome** happens when you achieve something great, but your internal self-esteem is so low that your brain cannot accept the success. Instead of feeling proud, you attribute your success to 'luck' or 'accident'.",
      highlight: "Up to 82% of people experience Imposter Syndrome. Even Albert Einstein admitted to feeling like a swindler. 🧩",
    },
    {
      id: 'neuroplasticity_self_talk',
      title: "The Neuroplasticity of Self-Talk 🧠",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "Words physically change the brain.\nEvery time you think, 'I'm an idiot,' you thicken a neural pathway making it easier to think that thought again tomorrow. It becomes a paved highway of self-hatred.\nTo build self-esteem, you must actively reroute the traffic. When you catch the negative thought, you must consciously force a neutral one to build a new pathway.",
      highlight: "You are not just changing your mind; you are rewiring your physical brain biology. 🛣️",
    },
    {
      id: 'toxic_positivity',
      title: "Why Positive Affirmations Fail 🛑",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'x-circle',
      svgIcon: 'alert',
      content: "If you hate your body, looking in the mirror and shouting, 'I am a supermodel!' will trigger a rejection response in your brain. Your brain knows you are lying.\nThis is **Toxic Positivity**.\nThe cure is 'Neutrality'. Instead of 'I am gorgeous', practice saying, 'I have a body, and it helps me walk and breathe.'",
      highlight: "The bridge from self-hatred to self-love is built with self-neutrality. 🌉",
    },
    {
      id: 'boundaries',
      title: "Boundaries = Self-Respect 🚧",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'minus-circle',
      svgIcon: 'target',
      content: "People pleasing is a sign of low self-esteem. It says: 'Your comfort is more important than my mental health.'\nSetting a **Boundary** (saying 'No') is terrifying because you risk upsetting someone. But every time you say 'No' to something you don't want to do, you are saying 'Yes' to yourself.",
      highlight: "A boundary is not a wall to keep people out; it's a fence to protect your garden. 🏡",
    },
    {
      id: 'the_comparison_trap',
      title: "The Comparison Trap 📱",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'smartphone',
      svgIcon: 'compass',
      content: "'Comparison is the thief of joy.' - Theodore Roosevelt\n\nEvolution designed us to compare ourselves to the 50 people in our local tribe. Today, social media forces us to compare our behind-the-scenes reality to the heavily edited highlight reels of 8 billion people.\nYou will always lose a game where the opponent's score is photoshopped.",
      highlight: "Unfollow accounts that make you feel bad about yourself. Protect your digital diet. 🗑️",
    },
    {
      id: 'self_compassion',
      title: "Self-Compassion vs. Pity 💖",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'heart',
      svgIcon: 'heart',
      content: "Self-pity says: 'Poor me, I am a victim.'\n**Self-Compassion** says: 'This is a moment of suffering. Suffering is a normal part of life. May I be kind to myself in this moment.' (Dr. Kristin Neff)\nTreating yourself with grace during a failure drastically increases your motivation to try again compared to punishing yourself.",
      highlight: "You cannot whip yourself into lasting self-improvement. 🛋️",
    },
    {
      id: 'core_beliefs',
      title: "Core Beliefs 🗄️",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'database',
      svgIcon: 'lock',
      content: "We all have underlying scripts running in our subconscious, formed in childhood. \nCommon toxic core beliefs:\n• 'I am unlovable.'\n• 'I am a burden.'\n• 'I must be perfect to be accepted.'\nWhen a friend doesn't text you back, you don't just feel annoyed; the event validates your broken core belief ('See? I knew I was unlovable').",
      highlight: "To fix the house, you have to dig up the foundation. 🏗️",
    },
    {
      id: 'the_mirror_test',
      title: "The Mirror Test 🪞",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'monitor',
      svgIcon: 'eye',
      content: "Next time you make a mistake, imagine your best friend made the exact same mistake. \nWhat would you say to them? You would probably say, 'It's okay, everyone messes up, don't worry about it.'\nNow look at what you say to yourself ('You stupid idiot, you ruin everything'). Why do you have a different set of rules for yourself?",
      highlight: "Become your own best friend. It is the most profitable relationship you will ever build. 🤝",
    },
    {
      id: 'shadow_work',
      title: "Integrating the Shadow 🌑",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'users',
      content: "Carl Jung coined the 'Shadow'—the parts of ourselves we deem ugly, shameful, or unacceptable, so we hide them.\nTrue self-esteem requires **Shadow Work**. It is accepting that you have flaws, you get jealous, you are sometimes selfish, and deciding that *you are still worthy of love anyway*.",
      highlight: "You cannot truly love yourself if you only love the 'good' half. 🌗",
    },
    {
      id: 'competence_loop',
      title: "The Competence-Confidence Loop 🔄",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'refresh-cw',
      svgIcon: 'leaf',
      content: "How do you build self-worth? Keep promises to yourself.\nWe expect confidence to come *before* action. It's the opposite. \nYou take action (make the bed, go for a walk), you prove to your brain you are capable (Competence), which generates respect for yourself (Self-Esteem/Confidence).",
      highlight: "Self-esteem is a reputation you build with yourself. 🧱",
    },
    {
      id: 'forgiveness',
      title: "Forgiving Your Past Self 🕊️",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'feather',
      svgIcon: 'star',
      content: "Many people hate themselves for cringy or harmful things they did years ago. \nBut cringing at your past means you have *grown*. The person you are today is not the person who made those mistakes. \nYour past self was operating on the limited information and emotional maturity they had at the time.",
      highlight: "Thank your past self for surviving, and then let them rest. 🌅",
    },
    {
      id: 'unconditional_worth',
      title: "Unconditional Worth 💎",
      color: '#673AB7',
      bgGradient: ['#1A0030', '#050010'],
      icon: 'award',
      svgIcon: 'heart',
      content: "A $100 bill crumpled up, stepped on, or thrown in the mud is still worth exactly $100.\nYour value as a human being does not fluctuate based on the stock market, your weight, your relationship status, or other people's opinions.\nYou were born worthy, and nothing can ever alter that fundamental truth.",
      highlight: "You don't have to earn your right to exist. Breathe. 🌬️",
    },
  ],

  lab: {
    title: "The Inner Critic Interrogator ⚖️🧠",
    description: "Your 'Inner Critic' is launching brutal, illogical attacks against you. You must put these thoughts on trial! Use Cognitive Behavioral restructuring to identify the logical fallacy and select the correct 'Neutral / Compassionate' rebuttal.",
    hint: "Don't swing to toxic positivity! If the critic says 'You're ugly', don't reply 'I am a glowing god!' Reply with logic: 'My worth isn't defined by my appearance.'",
    scientistModeHint: "CBT Restructuring Mode 🧑‍🔬: Analyze cognitive distortions (Overgeneralization, Filtering) in real-time.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why is it physically uncomfortable to receive a compliment if you have low self-esteem?", answer: "Cognitive Dissonance. The brain fiercely defends its established beliefs. If your core belief is 'I am worthless,' and someone says 'You are amazing,' it creates a jarring psychological conflict. Your brain immediately rejects the compliment to maintain its familiar internal reality. 🛑", emoji: '🧠' },
    { id: 'dyk2', question: "Why do we remember insults for years but forget compliments in 5 minutes?", answer: "The 'Negativity Bias'. Evolutionarily, remembering threats (like criticism/rejection) kept our ancestors alive much better than remembering praise. The brain treats a compliment like a feather, but an insult like a brick. 🧱", emoji: '📉' },
    { id: 'dyk3', question: "Why do perfectionists usually have the lowest self-esteem?", answer: "Because perfectionism is not about high standards; it is a shield. Perfectionists believe, 'If I am absolutely flawless, I can finally escape criticism and rejection.' Since perfection is impossible, they are locked in a cycle of constant failure and self-punishment. 🛡️", emoji: '🎯' },
    { id: 'dyk4', question: "Why does standing up straight actually make you feel more confident?", answer: "Embodied Cognition. The brain constantly monitors the body's posture to decide how it should feel. Slouching tells the brain 'We are defeated/hiding.' Standing tall physically lowers cortisol (stress) and slightly boosts testosterone (confidence) within minutes. 🧍‍♂️", emoji: '🧍‍♀️' },
    { id: 'dyk5', question: "Why is 'People Pleasing' a form of manipulation?", answer: "It sounds harsh, but people-pleasing is often a subconscious way to control others' emotions. By being 'too nice' and having no boundaries, you are trying to manipulate people into never abandoning or getting angry with you. It is rooted in fear, not generosity. 🎭", emoji: '🤝' },
  ],

  quiz: [
    { id: 'q1', question: "What is the primary difference between Confidence and Self-Esteem?", options: ["They are identical concepts", "Confidence is specific, self-esteem global", "Confidence is negative, self-esteem positive", "You can only possess one"], answer: 1, explanation: "You can confidently fly an airplane but still hate yourself as a person. ⚖️" },
    { id: 'q2', question: "What is the original, subconscious purpose of the 'Inner Critic'?", options: ["To generate feelings of anger", "A defense mechanism seeking perfection", "To provide helpful life advice", "To help you achieve fame"], answer: 1, explanation: "It is a misguided bodyguard trying to protect you from social rejection. 🛡️" },
    { id: 'q3', question: "What is the danger of 'Conditional Worth'?", options: ["It makes you overly polite", "It ties worth to external success", "It leads to financial wealth", "It helps resolve clinical depression"], answer: 1, explanation: "You are not your job, your bank account, or your weight. 📎" },
    { id: 'q4', question: "What is Imposter Syndrome?", options: ["Intentionally lying to others", "Feeling like a lucky fraud", "Taking credit for others' work", "A physical illness or disease"], answer: 1, explanation: "Even the highest achievers in the world struggle with feeling like fakes. 🕵️‍♂️" },
    { id: 'q5', question: "Why do 'Positive Affirmations' (e.g., shouting 'I am perfect!') often fail?", options: ["They are spoken too quietly", "The brain rejects unbelievable claims", "They produce immediate results", "They require financial investment"], answer: 1, explanation: "The brain needs believable, neutral truths, not extreme lies. 🛑" },
    { id: 'q6', question: "What is the psychological purpose of setting a 'Boundary'?", options: ["To be unkind to others", "To protect your mental health", "To build a physical barrier", "To isolate yourself from society"], answer: 1, explanation: "People pleasers lack boundaries because they fear rejection more than self-abandonment. 🚧" },
    { id: 'q7', question: "Why is social media a unique threat to self-esteem?", options: ["Screens emit harmful radiation", "Comparing reality to highlight reels", "The high cost of subscriptions", "The content is often boring"], answer: 1, explanation: "You cannot win a comparison game against photoshopped reality. 📱" },
    { id: 'q8', question: "What is the difference between Self-Pity and Self-Compassion?", options: ["Pity is joy, compassion sadness", "Pity is victimhood, compassion kindness", "There is no psychological difference", "Pity helps build physical strength"], answer: 1, explanation: "Compassion motivates recovery; pity sinks you into the mud. 💖" },
    { id: 'q9', question: "What is a 'Core Belief'?", options: ["A specific religious practice", "A subconscious script about yourself", "A strong political viewpoint", "A preference for certain colors"], answer: 1, explanation: "If your core belief is 'I am stupid', a single C- on a test proves your entire worldview right. 🗄️" },
    { id: 'q10', question: "What is the 'Mirror Test' in psychology?", options: ["Checking your physical appearance", "Treating yourself like a friend", "Smiling at your own reflection", "Breaking glass for good luck"], answer: 1, explanation: "We accept abuse from our own minds that we would never tolerate from a stranger. 🪞" },
    { id: 'q11', question: "What is Carl Jung's concept of 'The Shadow'?", options: ["The absence of light", "Repressed parts of the personality", "A supernatural or ghostly entity", "A phobia of the dark"], answer: 1, explanation: "You cannot love yourself conditionally and call it self-esteem. 🌑" },
    { id: 'q12', question: "According to the Competence-Confidence loop, how do you build self-esteem?", options: ["By avoiding all difficult tasks", "By taking action and keeping promises", "By waiting for feelings of confidence", "By repeating loud positive affirmations"], answer: 1, explanation: "Action comes first. Confidence is the byproduct. 🔄" },
    { id: 'q13', question: "Why do we cringe at our past selves?", options: ["Because you are inherently bad", "It is a sign of growth", "Because you are mentally stuck", "Because you have not changed"], answer: 1, explanation: "Cringing means you have leveled up emotionally. Forgive the old you. 🕊️" },
    { id: 'q14', question: "How does neuroplasticity relate to self-talk?", options: ["Thoughts change your hair color", "Thoughts physically shape neural pathways", "The brain learns complex mathematics", "It helps you fall asleep"], answer: 1, explanation: "What fires together, wires together. 🧠" },
    { id: 'q15', question: "What does 'Cognitive Dissonance' explain about compliments?", options: ["Compliments create loud mental noises", "Compliments conflict with your self-view", "Compliments make you feel tired", "Compliments require a financial fee"], answer: 1, explanation: "Your brain would rather be miserable and 'right' than happy and 'wrong'. 🛑" },
    { id: 'q16', question: "Perfectionism is usually a symptom of what?", options: ["Possessing a high level of intelligence", "A shield against perceived inadequacy", "Having too much free time", "Being naturally neat and organized"], answer: 1, explanation: "It is driven by fear, not excellence. 🛡️" },
    { id: 'q17', question: "Why is 'People Pleasing' sometimes considered manipulative?", options: ["It involves giving expensive gifts", "An attempt to control others", "It causes frequent verbal arguments", "It makes other people laugh"], answer: 1, explanation: "True generosity comes from a full cup, not from a fear of abandonment. 🎭" },
    { id: 'q18', question: "What is the 'Negativity Bias'?", options: ["Disliking the color black", "Prioritizing threats over positive feedback", "Being a naturally pessimistic person", "A complex mathematical equation"], answer: 1, explanation: "Sticks and stones break bones, but words wire the brain. 📉" },
    { id: 'q19', question: "What does the $100 bill analogy teach us?", options: ["Money is physically dirty", "Your inherent value never decreases", "The importance of saving money", "Avoiding mud and dirt"], answer: 1, explanation: "Your worth is unconditional. Period. 💎" },
    { id: 'q20', question: "How does 'Embodied Cognition' affect confidence?", options: ["Thinking about human anatomy", "Posture affects your mental state", "Exercise builds physical muscle", "Wearing expensive or nice clothes"], answer: 1, explanation: "Fixing your posture literally changes your brain chemistry in minutes. 🧍‍♂️" },
  ],

  relatedTopics: ['depression', 'overthinking', 'trauma'],
};
