export default {
  id: "quantum_basics",
  title: "Quantum Basics",
  subtitle: "The mind-bending rules of the microscopic universe! 🌌",
  emoji: "🌀",
  category: "Foundations",
  accentKey: "physics",

  hook: {
    question: "How can a Quantum Computer solve a 10,000-year problem in just seconds? ⏱️",
    reveal: "The power of 'Qubits'! Unlike a normal computer bit locked into being a 0 or a 1, a Qubit exists in a state called Superposition — acting as both 0 and 1 simultaneously. It doesn't test paths one by one; it explores the entire mathematical landscape all at once! 🌀",
    emoji: "🤯",
  },

  theory: [
    {
      id: "qubit_power",
      title: "Superposition: The Digital Hacker 💾",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "💾",
      svgIcon: "cpu",
      content: "A traditional computer bit is locked into being either ON (1) or OFF (0). \n\nA **Qubit** can exist in a linear combination of both states simultaneously. This is **Superposition**. While 300 normal bits represent just one number, 300 Qubits represent a superposition of all $2^{300}$ possibilities at the same time, unlocking massive parallel-processing power!",
      highlight: "300 Qubits can represent more states than there are atoms in the observable universe! 💥",
    },
    {
      id: "spooky_entanglement",
      title: "Entanglement: Quantum Linkage 👻",
      color: "#A855F7",
      bgGradient: ["#1A0A1F", "#050D0A"],
      icon: "👻",
      svgIcon: "link",
      content: "Albert Einstein famously called this 'Spooky Action at a Distance.' \n\nWhen two particles become **Entangled**, their fates are permanently linked. If you measure one particle on Earth and find it spinning 'Up', its partner on Mars will instantly snap into the 'Down' state. Distance seemingly does not exist for entangled pairs! 🔗",
      highlight: "The connection is instantaneous, yet physics prevents using it to send messages faster than light! 🚀",
    },
    {
      id: "quantum_tunneling",
      title: "Tunneling: The Ghost Walk 🚶‍♂️💨",
      color: "#3B82F6",
      bgGradient: ["#0A1220", "#050D0A"],
      icon: "🚶‍♂️",
      svgIcon: "fast-forward",
      content: "If you throw a ball at a brick wall, it bounces back. But in the quantum realm, particles act like waves of probability. \n\nWhen an electron hits an energy barrier it technically can't cross, there is a small mathematical chance it will simply 'appear' on the other side. This is **Quantum Tunneling**. Without it, the Sun wouldn't have enough pressure to fuse atoms together! ☀️",
      highlight: "Particles can 'teleport' through solid walls by following probability waves! 🕳️",
    },
    {
      id: "uncertainty_principle",
      title: "Heisenberg: No Peeking! 🚫",
      color: "#FF4444",
      bgGradient: ["#1A0505", "#050D0A"],
      icon: "🚫",
      svgIcon: "alert-triangle",
      content: "The universe enforces a strict 'Uncertainty Principle.' \n\nWerner Heisenberg proved that you cannot know a particle's exact position and momentum at the same time. The more accurately you measure one, the more blurred the other becomes. This isn't a failure of our tools; it's a fundamental blurriness built into the fabric of reality! 🌫️",
      highlight: "The universe refuses to let us know everything about a particle at once! 📐",
    },
    {
      id: "wave_duality",
      title: "The Ultimate Identity Crisis 🌊🏀",
      color: "#FF9F1C",
      bgGradient: ["#1A0D05", "#050D0A"],
      icon: "🌊",
      svgIcon: "activity",
      content: "Is light a rippling wave or a solid particle? It's both! \n\nQuantum objects behave like waves (ripples in a pond) until the moment they are observed. Measurement causes the 'Wave Function' to collapse, forcing the object to settle into a single, solid location as a particle. This is **Wave-Particle Duality**. 👁️",
      highlight: "Observation transforms a spread-out wave into a localized particle! ✌️",
    },
    {
      id: "quantum_decoherence",
      title: "Decoherence: Fragile Reality ❄️",
      color: "#00D4A0",
      bgGradient: ["#001A13", "#050D0A"],
      icon: "❄️",
      svgIcon: "wind",
      content: "The quantum realm is incredibly fragile. \n\nThe moment a quantum wave-function interacts with its environment — like bumping into a single air molecule — its 'waviness' is lost, and it collapses into the normal, 'classical' world. This is why we don't see quantum weirdness in our everyday lives! 💥",
      highlight: "Constant collisions with the environment keep our world solid and predictable! 🧊",
    },
    {
      id: "superfluidity",
      title: "Superfluids: Frictionless Flow 🧪",
      color: "#FF007F",
      bgGradient: ["#1A000D", "#050D0A"],
      icon: "🧪",
      svgIcon: "droplet",
      content: "When Helium is cooled near Absolute Zero, it becomes a **Superfluid**. \n\nIt achieves zero viscosity, meaning it has zero friction. It can flow through microscopic holes, climb up the sides of containers, and drip out of solid beakers by literally defying gravity via quantum effects! 🌀",
      highlight: "A spinning cup of superfluid would theoretically never stop rotating! 🌀",
    },
    {
      id: "vacuum_energy",
      title: "The Boiling Vacuum 🌌",
      color: "#7B2CBF",
      bgGradient: ["#0D051A", "#050D0A"],
      icon: "🌌",
      svgIcon: "aperture",
      content: "Outer space looks empty, but it is actually boiling with energy. \n\nDue to uncertainty, 'Virtual Particles' are constantly popping into existence and annihilating each other in fractions of a second. This leaves behind a residual 'Vacuum Energy' that permeates every inch of the universe! 🕳️",
      highlight: "Absolute 'nothingness' is mathematically impossible in our universe! 🌌",
    },
    {
      id: "quantum_biology",
      title: "Quantum Biology 🐦",
      color: "#D4A74A",
      bgGradient: ["#1A1505", "#050D0A"],
      icon: "🐦",
      svgIcon: "compass",
      content: "Life has been utilizing quantum mechanics for billions of years! \n\nCertain birds are believed to use quantum entanglement in their eyes to 'see' Earth's magnetic field for navigation. Even plants use 'quantum walks' to transport energy during photosynthesis with near 100% efficiency! 🧬",
      highlight: "You are a macroscopic being powered by microscopic quantum magic! 🧬",
    },
    {
      id: "multiverse",
      title: "Many Worlds: Parallel Splits 🛤️",
      color: "#FF7A59",
      bgGradient: ["#1A0905", "#050D0A"],
      icon: "🛤️",
      svgIcon: "git-branch",
      content: "Where do 'other' possibilities go when a wave function collapses? \n\nThe **Many Worlds Interpretation** suggests the universe splits. Every time a quantum event occurs, a new parallel branch is created where the alternative outcome happened. We just happen to live in one of the countless versions of history! 🛤️",
      highlight: "In another branch of reality, you might be an astronaut! 🎓",
    },
  ],

  lab: {
    title: "The Probability Forge 🔬",
    description: "Welcome to the Quantum Bench. Manipulate wave-function amplitudes, test the Double Slit effect, and observe the results of Wave Collapse!",
    hint: "Toggle the 'Observer' to see the interference pattern vanish as the wave collapses into particles!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays the complex Probability Density ($|\Psi|^2$) and Bell Inequality metrics.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why the Sun doesn't explode all at once? ☀️",
      answer: "Quantum Tunneling! Protons repel each other, but they 'tunnel' through the barrier to fuse. Because this is rare, the Sun burns its fuel slowly over billions of years instead of one giant flash! 🔥",
      emoji: "☀️",
    },
    {
      id: "dyk2",
      question: "Do you know how lasers work? 🔦",
      answer: "Stimulated Emission! Using quantum mechanics, atoms are encouraged to release photons that are perfectly synchronized in wavelength and direction, creating a concentrated beam of light! 🎯",
      emoji: "⚡",
    },
    {
      id: "dyk3",
      question: "Do you know what a 'Quantum Leap' really is? 🏃‍♂️",
      answer: "It refers to an electron jumping between energy levels. Because energy is quantized, the electron vanishes from one level and appearing in the next without ever existing in the space between! 🪜",
      emoji: "🪜",
    },
    {
      id: "dyk4",
      question: "Do you know how 'ghost' particles are found? 👻",
      answer: "Neutrino detectors use massive tanks of water deep underground. These 'ghost' particles rarely interact with anything, but when they hit an atom, they release a tiny blue flash of light! 🌊",
      emoji: "🔍",
    },
    {
      id: "dyk5",
      question: "Do you know how geckos climb glass? 🦎",
      answer: "Van der Waals forces! On a microscopic scale, the electrons on the gecko's feet interact with the electrons on the wall, creating temporary quantum attractions strong enough to hold its weight! 🧗",
      emoji: "🦎",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What does the word 'Quantum' refer to?",
      options: ["A giant explosion", "The smallest discrete unit of something", "A black hole", "A random guess"],
      answer: 1,
      explanation: "Quantum refers to the fundamental 'bits' of energy and matter! 📦",
    },
    {
      id: "q2",
      question: "The idea that light is both a wave and a particle is called:",
      options: ["Binary Physics", "Double Trouble", "Wave-Particle Duality", "The Light Paradox"],
      answer: 2,
      explanation: "Light behaves differently depending on whether it is being measured! 🌊🏀",
    },
    {
      id: "q3",
      question: "Existing in multiple states at once is called:",
      options: ["Duplication", "Superposition", "Entanglement", "Tunneling"],
      answer: 1,
      explanation: "Superposition allows a system to hold multiple values simultaneously! 🌀",
    },
    {
      id: "q4",
      question: "What happens when you 'observe' a quantum system?",
      options: ["It explodes", "It vanishes", "The wave function collapses into one state", "It speeds up"],
      answer: 2,
      explanation: "Measurement forces the system to choose a single definite reality! 👁️",
    },
    {
      id: "q5",
      question: "The 'Uncertainty Principle' was proposed by:",
      options: ["Einstein", "Heisenberg", "Newton", "Tesla"],
      answer: 1,
      explanation: "Heisenberg proved we cannot know position and speed simultaneously! 📏",
    },
    {
      id: "q6",
      question: "What is 'Spooky Action at a Distance'?",
      options: ["Quantum Tunneling", "Gravity", "Quantum Entanglement", "Magnetism"],
      answer: 2,
      explanation: "Entangled particles share states instantly across any distance! 👻",
    },
    {
      id: "q7",
      question: "Quantum Tunneling allows particles to...",
      options: ["Live forever", "Pass through solid energy barriers", "Move backward in time", "Create gravity"],
      answer: 1,
      explanation: "Probability waves allow particles to 'ghost' through walls! 🕳️",
    },
    {
      id: "q8",
      question: "A quantum packet of light is called a:",
      options: ["Electron", "Proton", "Photon", "Neutrino"],
      answer: 2,
      explanation: "Photons are the fundamental units of electromagnetic energy! 💡",
    },
    {
      id: "q9",
      question: "Which device relies on stimulated emission of photons?",
      options: ["Toaster", "Laser", "Battery", "Wind Turbine"],
      answer: 1,
      explanation: "Lasers amplify light through quantum synchronized emission! 🔦",
    },
    {
      id: "q10",
      question: "A 'Qubit' is the building block of:",
      options: ["A normal PC", "A Quantum Computer", "A battery", "A calculator"],
      answer: 1,
      explanation: "Qubits unlock the massive parallel potential of quantum computing! 💻",
    },
    {
      id: "q11",
      question: "Why don't we see quantum effects in the human world?",
      options: ["Gravity is too strong", "Decoherence shatters quantum states", "Quantum waves are invisible", "It's too hot"],
      answer: 1,
      explanation: "Interactions with the environment force quantum waves to collapse! 🌍",
    },
    {
      id: "q12",
      question: "In the Double Slit experiment, unobserved electrons create a:",
      options: ["Single dot", "Two bands", "Interference pattern (Wave)", "Black hole"],
      answer: 2,
      explanation: "Without an observer, the electron travels as a rippling wave! 🌊",
    },
    {
      id: "q13",
      question: "Schrödinger's Cat experiment illustrates...",
      options: ["Animal health", "Superposition in a closed box", "Radiation poisoning", "Gravity's pull"],
      answer: 1,
      explanation: "It shows how a system can be in multiple states until witnessed! 🐱",
    },
    {
      id: "q14",
      question: "Particle 'Spin' is best described as:",
      options: ["Actual rotation", "Intrinsic angular momentum", "Weight", "Color"],
      answer: 1,
      explanation: "Spin is a quantum property, not actual physical turning like a ball! 🔄",
    },
    {
      id: "q15",
      question: "The 'Many Worlds' theory suggests the universe:",
      options: ["Is empty", "Is shrinking", "Splits into parallel branches", "Has no end"],
      answer: 2,
      explanation: "Every quantum choice could create a new alternative history! 🛤️",
    },
    {
      id: "q16",
      question: "Quantum mechanics is mostly based on:",
      options: ["Rigid facts", "Probabilities", "Visual clues", "Gravity"],
      answer: 1,
      explanation: "The quantum world deals in chances and wave functions! 🎲",
    },
    {
      id: "q17",
      question: "The 'Observer Effect' means measurement...",
      options: ["Is easy", "Changes the system's state", "Is always wrong", "Requires light"],
      answer: 1,
      explanation: "Interacting with a system irrevocably alters its quantum behavior! 👁️",
    },
    {
      id: "q18",
      question: "Tunneling is essential for which solar process?",
      options: ["Fission", "Nuclear Fusion", "Cooling", "Magnetism"],
      answer: 1,
      explanation: "Protons must tunnel into each other to fuse and power the Sun! ☀️",
    },
    {
      id: "q19",
      question: "Zero viscosity in Helium is a sign of:",
      options: ["Boiling", "Superfluidity", "Freezing", "Magnetism"],
      answer: 1,
      explanation: "Superfluids have zero friction and exhibit strange quantum behaviors! 🌀",
    },
    {
      id: "q20",
      question: "Virtual particles popping in and out of space create:",
      options: ["Vacuum Energy", "Dark Matter", "Gravity", "Sound"],
      answer: 0,
      explanation: "Even empty space is filled with quantum fluctuations! 🌌",
    },
  ],

  relatedTopics: ["atoms_molecules", "digital_circuits", "light_optics", "thermodynamics_laws"],
};
