// ─────────────────────────────────────────────────────────
//  TOPIC: SCIENCE OF EMOTION
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'science_of_emotion',
  title: 'Science of Emotion',
  subtitle: 'How feelings are made 🎭🧠',
  emoji: '❤️',
  category: 'Society',
  accentKey: 'emotions',

  hook: {
    question: "Are you born with a 'sadness' circuit and a 'happiness' circuit in your brain? Are emotions universal instincts we can't control? 🎭",
    reveal: "For decades, science believed emotions were universal 'reactions' hardwired into our animal brains. But revolutionary new neuroscience proves this is wrong! Your brain doesn't 'react' with emotions; it 'constructs' them. Emotions are simply your brain's best guess about what your bodily sensations mean, based on your past experiences. You don't have an 'anger' circuit—you create anger! Let's discover how you are the architect of your own feelings. 🧬🧠",
    emoji: '🏗️',
  },

  theory: [
    {
      id: 'classical_view',
      title: 'The Classical View (Debunked) 🏛️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'book',
      content: "For 2,000 years, from Plato to modern psychology, we believed in the **Classical View of Emotion**.\n\nThis view says emotions are 'built-in' reflexes. It claims you have an 'anger circuit' and a 'fear circuit' inside your ancient lizard brain (the Amygdala). When something happens, the circuit triggers, you feel the emotion, and you make a universal facial expression. 🐍\n\nModern fMRI brain scans have proven that this is **false**. There is no single 'fear' center in the brain! ❌",
      highlight: "Emotions are not hardwired animal reflexes waiting to be triggered. 🛑",
    },
    {
      id: 'theory_of_constructed_emotion',
      title: 'Constructed Emotion 🏗️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'zap',
      content: "Neuroscientist Dr. Lisa Feldman Barrett introduced the **Theory of Constructed Emotion**.\n\nShe proved that emotions are not 'reactions' to the world; they are **Constructs**. \nYour brain takes raw physical data (a beating heart, sweaty palms) and looks at the context (Are you on a rollercoaster? Or giving a speech?). \n\nThen, based on your past experiences and vocabulary, your brain *constructs* an emotion ('I am thrilled!' vs 'I am terrified!'). You *build* your feelings in real-time! 🧱",
      highlight: "Emotions are guesses your brain makes to give meaning to bodily sensations. 🧠",
    },
    {
      id: 'interoception',
      title: 'Interoception: The 6th Sense 🫀',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🫀',
      svgIcon: 'eye',
      content: "You know about your 5 senses. But your brain has a 6th sense called **Interoception**.\n\nInteroception is your brain constantly monitoring your internal organs: your heart rate, lung expansion, stomach acidity, and immune system. \n\nIt compresses all this massive internal data into a simple feeling of 'Pleasant/Unpleasant' and 'Calm/Aroused'. This raw, nameless feeling is called **Affect**. Affect is the basic ingredient out of which all complex emotions are baked! 🧁",
      highlight: "Before you feel 'sadness' or 'joy', you just feel a raw biological shift. 🌊",
    },
    {
      id: 'body_budget_allostasis',
      title: 'The Body Budget (Allostasis) 🏦',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🏦',
      svgIcon: 'target',
      content: "Why does the brain do all this? To manage your **Body Budget (Allostasis)**.\n\nYour brain is like a financial manager. It doesn't use money; it uses glucose, water, and salt. Every time you move, learn, or stress out, you make a 'Withdrawal.' When you sleep and eat, you make a 'Deposit.' 💵\n\nIf your body budget goes into the negative (you are tired and hungry), your interoceptive network sends a distress signal. You feel 'crappy.' Your brain tries to explain this biological deficit by constructing an emotion like 'Depression' or 'Anger.' 😡",
      highlight: "Many 'emotional' problems are actually just a bankrupt body budget! 📉",
    },
    {
      id: 'emotional_granularity',
      title: 'Emotional Granularity 🎨',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🎨',
      svgIcon: 'grid',
      content: "If emotions are constructed using your past experiences and *words*, then your vocabulary determines what you can feel!\n\n**Emotional Granularity** is the ability to use highly specific words for your feelings. \nInstead of just saying 'I feel bad,' someone with high granularity says, 'I feel *melancholic*,' or 'I feel *overwhelmed*.' \n\nStudies show that people with high granularity go to the doctor less, recover from stress faster, and are far more emotionally resilient. Words are tools for emotional regulation! 🛠️",
      highlight: "Expanding your vocabulary literally expands your emotional intelligence. 📚",
    },
    {
      id: 'prediction_machine',
      title: 'The Prediction Machine 🔮',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔮',
      svgIcon: 'brain',
      content: "Your brain does not react to the world; it **predicts** the world. \n\nBy the time you see an apple or feel an emotion, your brain had already predicted it was going to happen milliseconds beforehand. It uses predictions to save energy. \n\nIf you see a dark alley, your brain predicts danger, raises your heart rate, and *then* constructs 'Fear.' The physical change actually happens *before* the conscious emotion! 🏃‍♂️",
      highlight: "Emotions are your brain preparing your body for action before it even happens! ⚡",
    },
    {
      id: 'cultural_emotions',
      title: 'Culturally Specific Emotions 🌍',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🌍',
      svgIcon: 'users',
      content: "Because emotions are constructed by our concepts, different cultures literally experience different emotions! \n\n• **Schadenfreude (German):** Pleasure derived from another's misfortune.\n• **Liget (Ilongot):** An intense, electric energy generated by grief that moves you to violently work or act. \n• **Amae (Japanese):** The comforting feeling of depending on someone else's love.\n\nIf you learn these words, you actually gain the ability to *construct* and feel these emotions! 🧩",
      highlight: "Your culture provides the 'recipes' you use to bake your emotions. 🍳",
    },
    {
      id: 'myth_of_universal_faces',
      title: 'The Myth of Universal Faces 🎭',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🎭',
      svgIcon: 'eye',
      content: "We are taught that a 'Smile' universally means 'Happy' and a 'Scowl' means 'Angry.'\n\nExtensive research among isolated tribes (like the Himba in Namibia) shows they do NOT match the same faces to the same emotions as Westerners! \n\nA scowl can mean anger, but it can also mean deep concentration or physical pain. A smile can mean joy, but it can also mean embarrassment or submission. There is no universal 'fingerprint' for any emotion in the face or the brain! 🧬",
      highlight: "Context is everything. A face means nothing without the story behind it. 📖",
    },
    {
      id: 'affective_realism',
      title: 'Affective Realism 🕶️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🕶️',
      svgIcon: 'shield',
      content: "Have you ever been in a bad mood, and suddenly everyone around you seems annoying and mean? \n\nThis is **Affective Realism**: the phenomenon where you experience your internal feelings as if they are facts about the outside world. \nIf you have a body budget deficit (you are tired), your brain literally alters your vision and hearing to perceive the world as darker and more hostile. You aren't seeing reality; you are seeing your own body budget! 📉",
      highlight: "Your mood is a lens that distorts reality. Don't trust your eyes when you are exhausted! 👓",
    },
    {
      id: 'anger_vs_fear',
      title: 'Anger vs. Fear ⚔️',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⚔️',
      svgIcon: 'lock',
      content: "Biologically, anger and fear are almost identical. Both feature a racing heart, sweating, and high adrenaline (High Arousal). \n\nThe only difference is the **Story** your brain tells.\n\n• If your brain predicts you have the power to overcome the threat $\\rightarrow$ **Anger** 😡.\n• If your brain predicts the threat will overcome you $\\rightarrow$ **Fear** 😱.\n\nBy believing in your own power, you can literally re-construct Fear into Anger (or Excitement) in real-time! 🛡️",
      highlight: "Anxiety and Excitement are the exact same biology; only the label is different! 🏷️",
    },
    {
      id: 'emotion_regulation',
      title: 'Mastering Emotion Regulation 🎛️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🎛️',
      svgIcon: 'refresh',
      content: "If your brain constructs emotions, how do you change them? \n\n1. **Manage the Body Budget:** Eat, sleep, or hydrate. (Fix the biological foundation first!) 💧🛌\n2. **Re-Categorize:** When you feel a tight chest before a test, don't label it 'Anxiety'. Re-label it 'Excitement.' Your brain will construct a helpful emotion instead of a paralyzing one. 🔄\n3. **Deconstruct:** Reduce the feeling back to basic Affect. 'I am not depressed. I am just experiencing high unpleasantness and low energy.' 🧬",
      highlight: "You cannot stop the physical sensations, but you *can* choose the label. 🏷️",
    },
    {
      id: 'emotional_intelligence',
      title: 'The New EQ ❤️',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '❤️',
      svgIcon: 'heart',
      content: "Classic Emotional Intelligence (EQ) assumes you can 'read' people's faces.\n\nThe *New* EQ understands that you cannot read minds. True EQ is about **Empathy and Context**.\nInstead of assuming a coworker is 'angry' because they are frowning, high EQ individuals ask questions. They realize the frown might be a bad back, an argument at home, or deep focus on a spreadsheet. 📊",
      highlight: "High EQ means stopping yourself from predicting other people's inner worlds. 🛑",
    },
    {
      id: 'emotions_are_actions',
      title: 'Emotions are Actions 🏃‍♂️',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🏃‍♂️',
      svgIcon: 'zap',
      content: "Emotions are not passive things that 'happen' to you (like getting hit by a rock). \n\nEmotions are active instructions. They are your brain changing your blood flow, releasing hormones, and tensing muscles to prepare you to **Act**. \n\nSadness slows you down to conserve energy and signal for help. Anger prepares your muscles for a fight. Joy encourages you to repeat a beneficial action. Emotions are biological verbs! ⚡",
      highlight: "You don't 'have' an emotion; you 'do' an emotion. 🛠️",
    },
    {
      id: 'social_reality',
      title: 'Social Reality 🌍',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🌍',
      svgIcon: 'users',
      content: "If emotions aren't physically real (like an apple), what are they? \n\nThey exist as **Social Reality**, just like Money or Laws. A $100 bill is just paper, but it has power because we all *agree* it has power. 💵\n\nEmotions are the same. 'Guilt' only exists because human society created the concept of right and wrong, and we all agree to enforce it. Without human culture, there is no Guilt—only animals interacting. Our shared minds create the emotional world! 🌐",
      highlight: "Emotions are invisible forces that bind human civilization together. 🏗️",
    },
    {
      id: 'architect_of_mind',
      title: 'You Are The Architect 🏛️',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'sparkle',
      content: "This new science of emotion is incredibly empowering. \n\nYou are not at the mercy of reptilian circuits deep in your brain. You are the architect of your own experience. \nBy taking care of your body budget, learning new emotional concepts, and choosing how you label your physical sensations, you can literally design a more resilient, joyful mind. 🧱✨",
      highlight: "You have more control over your emotions than you ever thought possible. 🚀",
    },
  ],

  lab: {
    title: "The Emotion Constructor 🧬🔄",
    description: "Welcome to the Brain's Control Room! Your task is to 'Construct' specific emotions using raw biological data. You have sliders for 'Arousal' (Heart rate/Energy) and 'Valence' (Pleasant/Unpleasant). Shift the biological base, and then apply a 'Context Lens' (e.g., 'At a party' vs 'In a dark alley') to see how the exact same biology creates totally different emotions! 🎛️",
    hint: "If you set Arousal high and Valence low, you get 'Fear' in a dark alley, but switch the context to 'A rollercoaster', and the brain constructs 'Exhilaration' using the exact same body data!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Interoceptive Network activity, Adrenalin vs Serotonin ratios, and Allostatic Load graphing.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we get 'Hangry' (Hungry/Angry)? 🍔😡",
      answer: "Allostasis! When you are hungry, your body budget is severely bankrupt. Your interoceptive network sounds the alarm, causing high arousal and negative valence (feeling terrible). Your brain looks for a reason. If a friend makes a joke, your predicting brain blames the friend for the bad feeling and constructs 'Anger', even though the real cause is just a lack of glucose! 📉",
      emoji: '🔋',
    },
    {
      id: 'dyk2',
      question: "Do you know why court judges give harsher sentences before lunch? ⚖️",
      answer: "Affective Realism. Studies show judges are significantly more likely to deny parole right before lunch. Because they are hungry, their body budget is low, making them feel unpleasant. Their brain misinterprets this internal physical unpleasantness as 'This prisoner is a bad, dangerous person.' After they eat, parole approval rates spike back up! 🥪",
      emoji: '📉',
    },
    {
      id: 'dyk3',
      question: "Do you know why deep breathing calms anxiety? 🌬️",
      answer: "It hacks the Interoceptive Network! The brain usually controls the heart and lungs automatically. But by consciously taking long exhales, you stimulate the Vagus Nerve. This sends a physical signal back to the brain saying 'We are safe, lower the heart rate.' The brain receives this new data and re-constructs the emotion from Anxiety to Calm! 🧘‍♂️",
      emoji: '🫁',
    },
    {
      id: 'dyk4',
      question: "Do you know why reading fiction increases emotional intelligence? 📖",
      answer: "Emotional Granularity! Fiction exposes you to complex, nuanced emotional situations and new vocabulary. By learning words like 'Schadenfreude' or 'Melancholy' through stories, you are literally downloading new 'Emotion Concepts' into your brain, giving you more tools to regulate your own feelings in the future! 📚",
      emoji: '🧠',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Venting' your anger usually makes you MORE angry? 🌋",
      answer: "Prediction loops! The classical view says anger is pressure in a pot that needs to 'blow off steam.' But neuroscience shows that emotions are habits. When you scream into a pillow, you are practicing and reinforcing the neural pathways for anger. You are teaching your brain to predict anger more easily next time! 🛑",
      emoji: '🔄',
    },
    {
      id: 'dyk6',
      question: "Do you know why heartbreak literally hurts your chest? 💔",
      answer: "Shared Neural Circuitry. The brain evolved to use the exact same neural networks to process physical pain (like a burn) and social pain (like rejection). To the brain, being kicked out of the tribe was a death sentence, so it uses the intense physical sensation of pain to force you to fix the social relationship! 🤕",
      emoji: '🧠',
    },
    {
      id: 'dyk7',
      question: "Do you know why baby brains are born 'under construction'? 👶",
      answer: "Because hardware is stiff, but software is adaptable! A horse can run hours after birth, but a human takes a year to walk. However, because our brains are unfinished, they hardwire themselves using the culture, language, and emotion concepts of the parents. We are born without emotions, and we 'learn' how to construct them from our caregivers! 🧬",
      emoji: '🏗️',
    },
    {
      id: 'dyk8',
      question: "Do you know why you can't tickle yourself? 🧤",
      answer: "Prediction! The brain is a prediction machine. When you try to tickle yourself, your brain predicts the exact sensory input before your fingers even touch your skin. Because there is zero 'Prediction Error' (surprise), the brain ignores the sensation entirely! 🤫",
      emoji: '🔮',
    },
    {
      id: 'dyk9',
      question: "Do you know why caffeine can cause panic attacks? ☕",
      answer: "Misattribution of Arousal! Caffeine causes your heart to race and hands to shake (High Arousal). If you are sitting in a quiet room, your brain thinks: 'My heart is racing, but there is no tiger. Why am I aroused? I must be in danger!' It then constructs a Panic Attack to explain the biological data! 🚨",
      emoji: '📈',
    },
    {
      id: 'dyk10',
      question: "Do you know why 'Butterflies in your stomach' happen? 🦋",
      answer: "The Gut-Brain Axis. When your brain predicts high stakes (like a speech), it pulls blood away from non-essential systems like digestion, sending it to your muscles. The physical sensation of blood leaving the stomach is felt as 'butterflies.' You can construct this as Anxiety, or re-label it as Excitement! 🚀",
      emoji: '🫀',
    },
  ],

  quiz: [
    { id: 'q1', question: "The debunked 'Classical View of Emotion' stated that:", options: ["Emotions are social constructs", "Emotions are hardwired animal reflexes", "Emotions are purely chemical reactions", "Emotions are unique to humans"], answer: 1, explanation: "We used to think we had an 'anger circuit' built-in from birth. We don't! ❌" },
    { id: 'q2', question: "According to the Theory of Constructed Emotion, your brain:", options: ["Reacts directly to external stimuli", "Predicts meaning from bodily sensations", "Follows signals from the heart", "Ignores all physical body signals"], answer: 1, explanation: "You are the architect of your feelings in real-time! 🏗️" },
    { id: 'q3', question: "What is 'Interoception'?", options: ["Reading the thoughts of others", "Monitoring the body's internal state", "Navigating through complete darkness", "Communicating without using any words"], answer: 1, explanation: "It is how the brain tracks heart rate, lungs, and glucose! 🫀" },
    { id: 'q4', question: "The brain manages your 'Body Budget' (Allostasis). A bankrupt body budget often feels like:", options: ["Feelings of intense joy", "Negative states like depression", "A state of total numbness", "A sense of inner peace"], answer: 1, explanation: "When you lack sleep or food, the brain's alarm bells sound! 🏦" },
    { id: 'q5', question: "What is 'Emotional Granularity'?", options: ["Using specific words for emotions", "Feeling intense emotions constantly", "Crying at very small things", "Lacking any emotional feelings"], answer: 0, explanation: "High granularity means saying 'I feel melancholic' instead of just 'bad'. 🎨" },
    { id: 'q6', question: "Your brain is not a reaction machine; it is a:", options: ["A complex biological calculator", "A proactive prediction machine", "A mental time travel device", "A simple physical muscle"], answer: 1, explanation: "It predicts what will happen to save energy, altering biology before you even know it! 🔮" },
    { id: 'q7', question: "Are facial expressions like a 'scowl' a universal biological sign for anger?", options: ["Yes, they are universal signs", "No, they depend on context", "Yes, but only for adults", "Yes, animals show them too"], answer: 1, explanation: "A scowl can mean anger, deep concentration, or a bad stomach ache! 🎭" },
    { id: 'q8', question: "What is 'Affective Realism'?", options: ["Believing all emotions are fake", "Mistaking internal feelings for facts", "Expressing emotions through physical acting", "Seeing only the positive outcomes"], answer: 1, explanation: "Your bad mood literally changes how you see and hear the world! 🕶️" },
    { id: 'q9', question: "Biologically, Anxiety and Excitement are:", options: ["Complete opposites of each other", "Identical states with different labels", "States caused by different organs", "Purely mythical psychological concepts"], answer: 1, explanation: "Both feature racing hearts. You choose the label! ⚔️" },
    { id: 'q10', question: "If emotions are constructed, what is the best FIRST step to regulate a bad mood?", options: ["Screaming loudly into a pillow", "Addressing basic physical body needs", "Ignoring the feeling completely", "Thinking deeply about the past"], answer: 1, explanation: "Fix the biology before you try to fix the psychology! 💧🛌" },
    { id: 'q11', question: "True Emotional Intelligence (the New EQ) relies heavily on:", options: ["Using context and empathy", "Reading other people's minds", "Possessing a very high IQ", "Never failing at social tasks"], answer: 0, explanation: "You can't read a mind from a face; you have to understand the context! 📊" },
    { id: 'q12', question: "Emotions are not passive reactions; they are:", options: ["Random psychological accidents", "Biological instructions for action", "Heavy emotional burdens", "Permanent states of being"], answer: 1, explanation: "Anger prepares your muscles to fight; they are biological verbs! 🏃‍♂️" },
    { id: 'q13', question: "Emotions like 'Guilt' only exist because of:", options: ["Ancient lizard brain instincts", "Shared cultural social concepts", "Inherited genetic traits", "The physical laws of nature"], answer: 1, explanation: "Without human culture to define right and wrong, guilt does not exist in nature! 🌍" },
    { id: 'q14', question: "Why does 'Hangry' happen?", options: ["Low blood sugar causing irritability", "Misinterpreting hunger as anger", "The physical discomfort of digestion", "A lack of focus from hunger"], answer: 1, explanation: "Your brain blames the person next to you instead of blaming the lack of glucose! 🍔" },
    { id: 'q15', question: "Deep breathing calms anxiety because:", options: ["Increasing oxygen to the blood", "Signaling safety to the brain", "Lowering the body's core temperature", "Increasing the heart rate significantly"], answer: 1, explanation: "You use a physical action to force the brain to change its prediction! 🌬️" },
    { id: 'q16', question: "Why does 'venting' anger usually fail to help?", options: ["Releasing the built-up energy", "Reinforcing the habit of anger", "Calming the nervous system down", "Distracting the mind from pain"], answer: 1, explanation: "Neurons that fire together wire together. Don't practice being miserable! 🌋" },
    { id: 'q17', question: "Why does social rejection (heartbreak) hurt physically?", options: ["The heart stopping briefly", "Processing social and physical pain similarly", "Tears burning the skin", "Physical damage to the heart"], answer: 1, explanation: "In evolutionary history, leaving the tribe meant death, so the brain treats it as a critical physical injury! 💔" },
    { id: 'q18', question: "Caffeine can trigger a panic attack in a quiet room because of:", options: ["A reaction to caffeine toxicity", "Misinterpreting physical arousal as panic", "A sudden drop in blood sugar", "Dehydration affecting the nervous system"], answer: 1, explanation: "The brain feels the racing heart and 'invents' a threat to explain it! ☕" },
    { id: 'q19', question: "A 'Prediction Error' in the brain happens when:", options: ["Making a logical reasoning error", "Input mismatching the brain's prediction", "Forgetting a specific piece of information", "Experiencing a sudden loss of memory"], answer: 1, explanation: "That stomach-dropping feeling when you miss a stair is a massive prediction error! ⚡" },
    { id: 'q20', question: "If you have high 'Emotional Granularity', you are more likely to:", options: ["Developing chronic physical illnesses", "Recovering from stress more quickly", "Feeling confused by social situations", "Having difficulty focusing on tasks"], answer: 1, explanation: "Words are tools for your brain to finely regulate your biology! 🛠️" },
  ],

  relatedTopics: ['happiness_science', 'cognitive_biases', 'mental_health_basics'],
};
