// ─────────────────────────────────────────────────────────
//  TOPIC: ANXIETY (चिंता)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'anxiety',
  title: 'Anxiety',
  subtitle: 'The False Alarm of the Mind 🚨🧠',
  emoji: '🌪️',
  category: 'Mental Health',
  accentKey: 'anxiety',

  hook: {
    question: "Why does your heart pound and your chest tighten before sending an email, as if a hungry tiger is about to attack you?",
    reveal: "Because as far as your brain's alarm system is concerned, the email *is* the tiger.\n\nAnxiety is not a character flaw or 'weakness'. It is a biological survival mechanism—the 'Fight, Flight, or Freeze' response—that has malfunctioned. Your brain's ancient threat-detector (the Amygdala) is pulling the fire alarm when there's only burnt toast. Let's look under the hood of panic and see how to shut the alarm off. 🚨🐅🧩",
    emoji: '🚨',
  },

  theory: [
    {
      id: 'anxiety_vs_fear',
      title: "Anxiety vs. Fear 🐅",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'alert-circle',
      svgIcon: 'alert',
      content: "**Fear** is your reaction to a *present, actual* danger. (E.g., A loose dog barking at you right now).\n\n**Anxiety** is your reaction to a *future, imagined* danger. (E.g., What if I stutter during my presentation tomorrow and everyone laughs at me?)\nFear keeps you alive. Anxiety keeps you suffering over things that haven't happened yet.",
      highlight: "Mark Twain: 'I am an old man and have known a great many troubles, but most of them never happened.' 🧠",
    },
    {
      id: 'the_amygdala',
      title: "The Smoke Detector (Amygdala) 🧠",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'bell',
      svgIcon: 'flame',
      content: "Deep inside your brain is the **Amygdala**, an almond-shaped structure that acts as a smoke detector. \nWhen it senses danger, it bypasses your logical brain (Prefrontal Cortex) and instantly floods your body with adrenaline and cortisol.\nIn an anxious brain, the smoke detector is too sensitive. It goes off for emails, social gatherings, and awkward silences.",
      highlight: "Your body is acting exactly as it should during a crisis. It just has the wrong definition of 'crisis'. 🚨",
    },
    {
      id: 'fight_flight',
      title: "Fight, Flight, or Freeze ⚡",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'zap',
      svgIcon: 'activity',
      content: "When the alarm rings, your body prepares to survive:\n• **Heart races**: To pump blood to muscles.\n• **Breathing quickens**: To get more oxygen.\n• **Digestion stops**: (Causing nausea/butterflies) to save energy.\n• **Sweating**: To cool the body down.\nThis is a superpower if you're escaping a bear. It's a nightmare if you're trying to fall asleep.",
      highlight: "Panic attacks are just the 'Fight or Flight' response happening when you are sitting perfectly still. 🏃‍♂️",
    },
    {
      id: 'the_equation',
      title: "The Anxiety Equation ✖️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'x-square',
      svgIcon: 'lock',
      content: "Cognitive psychologists define anxiety using a simple mental equation:\n\n**Anxiety = (Overestimating the Threat) / (Underestimating your Coping Ability)**\n\nYou tell yourself the outcome will be 10x worse than it actually is, AND you tell yourself you are 10x weaker than you actually are.",
      highlight: "To reduce anxiety, either realize the threat is small, or realize your strength is huge. ⚖️",
    },
    {
      id: 'avoidance_trap',
      title: "The Avoidance Trap 🕳️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'corner-down-right',
      svgIcon: 'compass',
      content: "When something makes you anxious (like going to a party), and you decide to **avoid** it (stay home), you feel instant relief.\n\nHowever, this relief acts as a 'reward' for your brain. Your brain learns: 'The party WAS dangerous, and staying home saved my life!' Avoidance shrinks your comfort zone until it becomes a prison.",
      highlight: "Short-term relief = Long-term suffering. Avoidance is the fuel for future anxiety. ⛽",
    },
    {
      id: 'GAD_and_panic',
      title: "Types of Anxiety 🧩",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'grid',
      svgIcon: 'users',
      content: "Anxiety isn't just one thing:\n• **GAD (Generalized Anxiety Disorder)**: A constant, low-level hum of worry about everyday things.\n• **Social Anxiety**: Intense fear of being judged, humiliated, or rejected.\n• **Panic Disorder**: Sudden, unexpected terror attacks that feel like heart attacks.\n• **OCD/Phobias**: Specific, localized fears.",
      highlight: "They all use the same biological circuitry, just triggered by different 'perceived' threats. ⚙️",
    },
    {
      id: 'what_if_mind',
      title: "The 'What If?' Disease ❓",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'help-circle',
      svgIcon: 'question',
      content: "The anxious brain is obsessed with the future. It constantly plays scenarios beginning with 'What if...'\n*What if I fail? What if they laugh? What if I get sick?*\n\nBecause the brain can't tell the difference between a real vividly imagined threat, your body reacts to these 'What ifs' as if they are happening *right now*.",
      highlight: "Anxiety is living in a terrifying future that doesn't exist yet. ⏳",
    },
    {
      id: 'intrusive_thoughts',
      title: "Intrusive Thoughts 🔪",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "These are sudden, bizarre, or terrifying thoughts that pop into your head (e.g., 'What if I steered my car into oncoming traffic?').\n\nPeople with anxiety are horrified by these thoughts because they think thinking it means they want to do it. **Truth:** Intrusive thoughts are just the brain producing random 'junk mail'. The anxiety comes from how tightly you hold onto the thought.",
      highlight: "A thought is just a thought. Having a bad thought doesn't make you a bad person. 🗑️",
    },
    {
      id: 'gut_brain_axis',
      title: "The Second Brain (Your Gut) 🦠",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'activity',
      svgIcon: 'leaf',
      content: "Have you ever felt 'sick to your stomach' from nerves? \nYour gut is lined with 100 million neurons and produces 95% of your body's serotonin. The **Gut-Brain Axis** connects your digestion to your emotional state via the vagus nerve. When you are anxious, your brain shuts down digestion, causing nausea, IBS, and cramps.",
      highlight: "Your stomach literally 'feels' your thoughts. 🍔",
    },
    {
      id: 'breathing_hack',
      title: "The Biological Hack: Breathing 🌬️",
      color: '#009688',
      bgGradient: ['#001A18', '#000A08'],
      icon: 'wind',
      svgIcon: 'zap',
      content: "You cannot reason with an active panic attack. The logical brain is offline.\n\nThe only bridge to the nervous system is the **breath**. When you exhale longer than you inhale (e.g., 4 seconds in, 6 seconds out), you stimulate the Vagus Nerve to release acetylcholine, which physically puts the brakes on your pounding heart.",
      highlight: "Long exhales flip the switch from 'Fight or Flight' to 'Rest and Digest'. 🎚️",
    },
    {
      id: 'grounding',
      title: "Grounding: The 5-4-3-2-1 Fix 🌍",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'anchor',
      svgIcon: 'target',
      content: "When anxiety throws you into the future, force your brain back to the present using your senses.\nName aloud:\n👁️ 5 things you can see\n✋ 4 things you can physically feel\n👂 3 things you can hear\n👃 2 things you can smell\n👅 1 thing you can taste\nThis physically hijacks the brain's processing power away from the amygdala.",
      highlight: "Anxiety cannot survive in the present moment. ⏳",
    },
    {
      id: 'exposure_therapy',
      title: "Exposure: The Antidote 🛡️",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'shield',
      svgIcon: 'star',
      content: "The only way out is through. **Exposure Therapy** involves facing the absolute thing you fear in small, manageable doses.\n\nIf you fear elevators, you start by standing near one. Then stepping inside without the doors closing. You teach the brain, through actual experience, that the 'tiger' isn't real. You retrain the alarm system.",
      highlight: "Courage isn't the absence of fear, but acting despite it. 🦁",
    },
    {
      id: 'caffeine_alcohol',
      title: "Liquid Anxiety ☕🍷",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'coffee',
      svgIcon: 'droplet',
      content: "• **Caffeine** mimics panic. It raises your heart rate and blocks sleep receptors. If you have anxiety, coffee is literally liquid panic.\n• **Alcohol** suppresses the nervous system, giving temporary relief. But when it wears off, the brain's alarm rebounds twice as hard (Hanxiety).\n\nManaging biology is step one in managing anxiety.",
      highlight: "You might not need a therapist today; you might just need to quit energy drinks. 🛑",
    },
    {
      id: 'acceptance',
      title: "The Law of Reversed Effort 🌊",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'droplet',
      svgIcon: 'heart',
      content: "Philosopher Alan Watts noted that the harder you try to float in water, the more you sink.\n\nTrying to 'force' yourself to calm down during panic actually causes more panic. The secret is **Acceptance**. Allow the feeling. Say, 'Okay, I am having a panic attack. Let it happen.' When you stop fighting the wave, it washes over you and passes.",
      highlight: "What you resist, persists. What you accept, transforms. 🌊",
    },
    {
      id: 'modern_world',
      title: "You Are Normal 📱",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'smartphone',
      svgIcon: 'users',
      content: "Our brains evolved on the quiet African savanna. Now, we are bombarded with 24/7 news, social media comparisons, and hyper-caffeinated hustle culture.\n\nYour anxiety isn't necessarily a broken brain; it's an ancient brain having a perfectly normal reaction to a highly unnatural, modern environment. Give yourself grace.",
      highlight: "To be a little anxious today isn't a disorder; it's just paying attention. 🌍",
    },
  ],

  lab: {
    title: "Amygdala Override System 🎛️🚨",
    description: "A panic attack sequence has initiated! Your heart rate is spiking and logic is offline. You must use 'Box Breathing' and 'Present-Moment Grounding' to shut down the Amygdala before the Panic Meter hits 100%.",
    hint: "Breathe OUT slowly! Exhaling triggers the parasympathetic nervous system.",
    scientistModeHint: "Neurology Mode 🧑‍🔬: Monitor Vagus Nerve stimulation and Cortisol half-life metrics.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why does anxiety make your hands and feet feel cold/numb?", answer: "During 'Fight or Flight', your body literally pulls blood away from your extremities (hands/feet) and pushes it toward your major organs and thigh muscles so you can run away or fight. 🏃‍♂️🩸", emoji: '🥶' },
    { id: 'dyk2', question: "Why do you feel a knot in your throat when anxious?", answer: "It's called the 'Globus Sensation'. The muscles in your throat expand to let in maximum oxygen for survival, which feels like a lump you can't swallow away! 🗣️", emoji: '🪢' },
    { id: 'dyk3', question: "Why does anxiety make you need to use the bathroom?", answer: "When facing a life-or-death threat, your body tries to lighten its load to run faster. Digestion stops entirely, leading to sudden nausea or 'The Runs'. Survival over comfort! 🚽", emoji: '🏃' },
    { id: 'dyk4', question: "Why do some people with anxiety bite their nails or pick their skin?", answer: "These are called 'Body-Focused Repetitive Behaviors'. Pain or grooming provides a tiny, immediate hit of relief and physical stimulation that temporarily distracts the brain from the psychological overwhelming feeling. 💅", emoji: '🦷' },
    { id: 'dyk5', question: "Why does deep breathing actually work?", answer: "It's pure biology. The Vagus Nerve runs from your brain to your diaphragm. When you physically move the diaphragm with a deep, slow exhale, you mechanically signal the nerve to release acetylcholine, which slows the heart. It's a physical brake pedal. 🎚️", emoji: '🫁' },
  ],

  quiz: [
    { id: 'q1', question: "What is the core difference between Fear and Anxiety?", options: ['Fear is fake, Anxiety is real', 'Fear is a reaction to present danger; Anxiety is about imagined future danger', 'Fear is loud, Anxiety is quiet', 'No difference'], answer: 1, explanation: "We fear the dog right in front of us. We have anxiety about the dog that *might* be there tomorrow. 🐅" },
    { id: 'q2', question: "What part of the brain acts as the 'smoke detector'?", options: ['The Prefrontal Cortex', 'The Amygdala', 'The Hippocampus', 'The Brain Stem'], answer: 1, explanation: "The Amygdala sizes up threats instantly, bypassing logic. 🚨" },
    { id: 'q3', question: "Why does your heart race during a panic attack?", options: ['You are dying', 'Your body is pumping blood to muscles preparing you to fight or run (Fight/Flight)', 'Your heart is failing', 'Too much sugar'], answer: 1, explanation: "Your body is acting exactly as it should to survive off a physical threat. ⚡" },
    { id: 'q4', question: "What is 'The Avoidance Trap'?", options: ['Dodging taxes', 'Avoiding what scares you brings short-term relief but teaches the brain the danger was real, worsening future anxiety', 'Walking around puddles', 'Ignoring friends'], answer: 1, explanation: "Avoidance shrinks your world. Exposure expands it. 🕳️" },
    { id: 'q5', question: "What is the Anxiety Equation?", options: ['Stress + Time = Panic', 'Overestimating the Threat / Underestimating Coping Ability', 'Age x Fear = Anxiety', 'Water + Caffeine = Anxiety'], answer: 1, explanation: "Anxiety lies to you twice: It says the monster is huge, and you are weak. ✖️" },
    { id: 'q6', question: "How does the 'Gut-Brain Axis' explain stomach aches during exams?", options: ['You ate bad food', 'The gut produces most of the body\'s serotonin and is connected to the brain via the vagus nerve', 'Paper makes you sick', 'It is a coincidence'], answer: 1, explanation: "Emotional turmoil almost always results in gastrointestinal distress. 🦠" },
    { id: 'q7', question: "What is the 5-4-3-2-1 technique used for?", options: ['Baking a cake', 'Grounding yourself in the present moment by using the 5 senses', 'Counting down to jump', 'Math homework'], answer: 1, explanation: "It forces the brain's processing power away from the amygdala and into the physical world. 🌍" },
    { id: 'q8', question: "Why is a LONG exhale important in breathing exercises?", options: ['It empties the lungs', 'It stimulates the Vagus Nerve to slow the heart rate', 'It makes a sound', 'It prepares you to scream'], answer: 1, explanation: "The exhale is the biological 'brake pedal' for your nervous system. 🌬️" },
    { id: 'q9', question: "What are 'Intrusive Thoughts'?", options: ['Neighbors walking in', 'Sudden, unwanted, bizarre or scary thoughts that do not reflect your true desires', 'Memories', 'Great ideas'], answer: 1, explanation: "They are mental 'junk mail'. Having them doesn't mean you will act on them. 🗑️" },
    { id: 'q10', question: "What is the most effective psychological treatment for phobias?", options: ['Avoidance', 'Exposure Therapy (facing the fear safely in small steps)', 'Sleeping', 'Caffeine'], answer: 1, explanation: "You must teach the brain that the 'tiger' isn't real through actual experience. 🛡️" },
    { id: 'q11', question: "According to Alan Watts, what makes a panic attack worse?", options: ['Breathing', 'Fighting it and trying to force yourself to calm down (The Law of Reversed Effort)', 'Acceptance', 'Laying down'], answer: 1, explanation: "Fighting the adrenaline rush just causes more adrenaline to be released. 🌊" },
    { id: 'q12', question: "What does 'Hanxiety' refer to?", options: ['Anxiety about hands', 'The intense anxiety rebound the day after drinking alcohol, as the nervous system overcorrects', 'Fear of heights', 'A type of medication'], answer: 1, explanation: "Alcohol acts as a chemical loan for calmness, with heavy interest paid the next day. 🍷" },
    { id: 'q13', question: "Why do your hands get cold during severe anxiety?", options: ['The weather changes', 'Blood is shunted away from extremities towards major organs for survival', 'You hold your breath', 'You need gloves'], answer: 1, explanation: "You don't need warm fingers to outrun a bear; you need strong thigh muscles. 🥶" },
    { id: 'q14', question: "What is Generalized Anxiety Disorder (GAD)?", options: ['Fear of specific insects', 'A continuous, low-level worry about many different everyday things', 'Sudden terror', 'Social fear'], answer: 1, explanation: "GAD is like having 100 tabs open in a browser and music playing from one of them. 🧩" },
    { id: 'q15', question: "What is the logic-processing center of the brain that the Amygdala bypasses during panic?", options: ['Prefrontal Cortex', 'Occipital Lobe', 'Brain stem', 'Cerebellum'], answer: 1, explanation: "This is why you cannot 'reason' with someone mid-panic. The logic center is offline. 🧠" },
    { id: 'q16', question: "What happens to digestion during Fight or Flight?", options: ['It speeds up', 'It stops completely to save energy for survival', 'It reverses', 'Nothing'], answer: 1, explanation: "This causes nausea, butterflies, and the urge to empty the bowels. 🦋" },
    { id: 'q17', question: "Why is high caffeine intake bad for an anxious person?", options: ['It causes weight gain', 'It biologically mimics a panic attack (raised heart rate), tricking the brain into feeling anxious', 'It stains teeth', 'It is too hot'], answer: 1, explanation: "Caffeine triggers the exact same physical symptoms as the 'Flight or Fight' response. ☕" },
    { id: 'q18', question: "What is 'Social Anxiety'?", options: ['Hate for parties', 'Intense fear of being judged, negatively evaluated, or rejected in social situations', 'Being an introvert', 'Fear of talking too much'], answer: 1, explanation: "It's deeply tied to human evolution; being kicked out of the tribe used to mean death. 🎭" },
    { id: 'q19', question: "Is a panic attack dangerous to your physical health?", options: ['Yes, it causes heart attacks', 'No, it feels terrible but it is physically harmless and will pass', 'Yes, it damages lungs', 'It causes strokes'], answer: 1, explanation: "A panic attack cannot kill you or make you go crazy, even if it feels exactly like it. 🫀" },
    { id: 'q20', question: "How does modern life contribute to our high levels of anxiety?", options: ['We eat too much', 'Our ancient brains treating 24/7 news/notifications as constant survival threats', 'We sleep too much', 'Because of cars'], answer: 1, explanation: "We have paleolithic brains living in a digital, hyper-stimulated world. 📱" },
  ],

  relatedTopics: ['depression', 'overthinking', 'trauma'],
};
