// ─────────────────────────────────────────────────────────
//  TOPIC: SOCIAL MEDIA TRAP
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'social_media_trap',
  title: 'Social Media Trap',
  subtitle: 'The dark psychology of the scroll 📱🌀',
  emoji: '📱',
  category: 'Society',
  accentKey: 'social_media',

  hook: {
    question: "Have you ever opened an app just to check a message, and suddenly an hour has vanished? Where did the time go? 🕒",
    reveal: "It didn't just 'vanish.' It was carefully, scientifically extracted from you. Modern social media platforms aren't just apps; they are multi-billion-dollar psychology experiments. Utilizing neurobiology, casino mechanics, and advanced AI, they are designed with one singular goal: to maximize your 'Time on Screen'. Let's peek behind the curtain and see exactly how your dopamine is being weaponized. 🧠🎣",
    emoji: '🎣',
  },

  theory: [
    {
      id: 'attention_economy',
      title: 'The Attention Economy 💰',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '💰',
      svgIcon: 'target',
      content: "In the past, the most valuable resource was oil or gold. Today, it is **Human Attention** 👀.\n\nWhen you use a 'free' app, YOU are the product. Social media companies make money by selling your attention to advertisers. To make more money, they need you to stare at the screen for as long as possible.\n\nEvery feature—from the color of a notification to the lack of a 'bottom' to the feed—is engineered to monopolize your visual and cognitive focus. 📵",
      highlight: "If you aren't paying for the product, you ARE the product. 🎯",
    },
    {
      id: 'dopamine_loop',
      title: 'The Dopamine Loop 🧪',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🧪',
      svgIcon: 'zap',
      content: "Why does it feel so good to get a 'Like'? Because of **Dopamine**, the brain's anticipation molecule 🏆.\n\nDopamine isn't just about pleasure; it's about motivation. Every time your phone buzzes, your brain releases dopamine, driving you to see who texted or liked your post. \n\nThis creates a powerful feedback loop: \n**Trigger (Buzz) $\\rightarrow$ Action (Check) $\\rightarrow$ Reward (Like) $\\rightarrow$ Craving (More)**. This is the exact same chemical loop that drives gambling addiction! 🎰",
      highlight: "Your phone is practically an IV drip of digital dopamine. 💉",
    },
    {
      id: 'variable_rewards',
      title: 'Variable Rewards 🎰',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🎰',
      svgIcon: 'star',
      content: "Psychologist B.F. Skinner discovered that the most addictive way to reward a behavior is randomly, known as a **Variable Ratio Schedule** 🎲.\n\nIf you knew you'd get a 'Like' exactly every 5 minutes, you'd get bored. But on social media, you never know *when* or *if* a reward is coming. \n\nEvery time you swipe down to refresh, you are pulling the lever of a virtual slot machine. The uncertainty makes the dopamine spike massive! 💥",
      highlight: "The 'Pull to Refresh' feature was literally modeled after casino slot machines. 🕹️",
    },
    {
      id: 'infinite_scroll',
      title: 'The Infinite Scroll 🌀',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🌀',
      svgIcon: 'refresh',
      content: "In the early days of the internet, you had to click 'Next Page.' This provided a **Stopping Cue**—a moment for your brain to say, 'Okay, I'm done.' 🛑\n\nIn 2006, Aza Raskin invented the **Infinite Scroll**. Content loads automatically as you scroll down, completely removing the stopping cue. \n\nWithout an endpoint, your brain goes into a frictionless trance. Your sense of time distorts, and a 'quick check' easily turns into a 45-minute binge. 🕒",
      highlight: "A frictionless environment prevents your brain from making conscious choices. 🛒",
    },
    {
      id: 'fomo',
      title: 'FOMO & Social Validation 📉',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📉',
      svgIcon: 'users',
      content: "Humans are deeply social animals. For thousands of years, survival depended on belonging to a tribe 🏕️.\n\nSocial media hijacks this biological need through **FOMO (Fear Of Missing Out)**. We constantly check our phones to ensure we aren't excluded from the 'tribe.'\n\nFurthermore, 'Likes' and 'Followers' quantify our social worth into a measurable score 💯. This tricks our primitive brains into equating a low like-count with social rejection, which biologically feels like physical pain! 💔",
      highlight: "The fear of social exclusion is a deeply primal survival instinct. 🦅",
    },
    {
      id: 'algorithms_echo',
      title: 'Algorithms & Echo Chambers 🗣️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🗣️',
      svgIcon: 'grid',
      content: "What you see on your feed isn't an accident. AI **Algorithms** track exactly what you linger on, what you click, and what you skip 👁️.\n\nTheir goal isn't to show you the 'truth'; it's to show you what keeps you clicking. \n\nThis creates an **Echo Chamber**. If you click on a video about cats, the algorithm feeds you 100 more cat videos. Soon, your entire digital world only reflects your own opinions back to you, making the world seem much narrower than it is. 🪞",
      highlight: "Algorithms care about engagement, not accuracy or healthy debates. 🧮",
    },
    {
      id: 'rage_engagement',
      title: 'Outrage as Engagement 😡',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '😡',
      svgIcon: 'alert',
      content: "What holds human attention better than cute animals? **Anger.** 🔥\n\nStudies show that 'Moral Outrage' spreads on social media 6x faster than positive news. Algorithms quickly 'learned' that if they show you content that makes you angry, you will stay on the app to argue in the comments.\n\nThis is why your feed often feels stressful or polarizing. The system is literally optimizing for outrage because it drives up screen time! 📈",
      highlight: "Conflict is profitable. Anger is the most 'engaging' emotion. 💸",
    },
    {
      id: 'phantom_vibration',
      title: 'Phantom Vibration Syndrome 📳',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '📳',
      svgIcon: 'phone',
      content: "Have you ever felt your phone buzz in your pocket, only to find you didn't get a notification? Or maybe your phone wasn't even in your pocket? 👻\n\nThis is **Phantom Vibration Syndrome**. Because your brain expects a dopamine hit, your sensory cortex becomes hyper-vigilant. \n\nIt begins misinterpreting random nerve twitches or the friction of your clothes as a phone vibration. Your nervous system has actually re-wired itself around the device! 🧬",
      highlight: "Your brain is so desperate for the digital reward that it hallucinates the trigger. 🤯",
    },
    {
      id: 'comparison_trap',
      title: 'The Comparison Trap 🏆',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🏆',
      svgIcon: 'eye',
      content: "Social media shows the 'Highlight Reel' of someone's life—filtered, edited, and perfectly curated ✨.\n\nBut you compare their *highlight reel* to your *behind-the-scenes*. \n\nThis constant upward comparison leads to feelings of inadequacy, depression, and anxiety. It warps our perception of reality, making us believe everyone else is richer, happier, and better looking than they actually are. 🎭",
      highlight: "You are comparing your reality to someone else's carefully constructed illusion. 🖼️",
    },
    {
      id: 'multitasking_myth',
      title: 'The Myth of Multitasking 🤹',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🤹',
      svgIcon: 'brain',
      content: "We think we can scroll through TikTok while studying or watching a movie. \n\nNeuroscience proves that **Multitasking is a myth**. You cannot focus on two complex tasks at once. Instead, your brain rapidly 'switches' between tasks (Task-Switching) 🔄.\n\nEvery switch drains cognitive energy. By the end of an hour of 'multitasking,' your brain is exhausted, your memory retention plummets, and your stress levels rise due to constant cognitive friction. 📉",
      highlight: "Checking your phone while working lowers your functional IQ by up to 10 points! 🧠",
    },
    {
      id: 'sleep_disruption',
      title: 'Blue Light & Sleep 💤',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '💤',
      svgIcon: 'cloud',
      content: "Scrolling before bed is one of the most destructive habits for your health.\n\nThe screens emit **Blue Light**, which mimics daylight. This light enters your eyes and completely blocks the production of **Melatonin** (the sleep hormone) 🛑.\n\nCombine the bright light with the high-dopamine anxiety of reading comments, and your brain thinks it's 2 PM in the middle of a social war. Restful, deep sleep becomes impossible. 🌙",
      highlight: "Your phone artificially forces your brain into 'daytime survival mode.' ☀️",
    },
    {
      id: 'digital_minimalism',
      title: 'Digital Minimalism 🌿',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🌿',
      svgIcon: 'shield',
      content: "So, do we throw our phones in the river? No! We practice **Digital Minimalism**.\n\nAuthored by Cal Newport, this philosophy means using technology intentionally. \n\n• **Batching:** Check social media only 2 times a day for 15 minutes, rather than 100 times for 1 minute.\n• **Grayscale:** Turn your phone to black-and-white mode to remove the vibrant, dopamine-triggering colors. ⬛⬜\nTake control back from the algorithms! 🕹️",
      highlight: "Technology should be a tool we use, not a tool that uses us. 🛠️",
    },
    {
      id: 'dark_patterns',
      title: 'Dark Patterns 🕸️',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🕸️',
      svgIcon: 'lock',
      content: "UX (User Experience) designers sometimes use **Dark Patterns**—tricks designed to manipulate you into doing things you didn't mean to do 🕷️.\n\nExamples include making the 'Unsubscribe' button invisible, 'Confirm-Shaming' ('No thanks, I hate saving money'), or burying account-deletion deep in 15 menus.\n\nThese patterns take advantage of our tendency to skim read and our desire for cognitive ease to trap us in subscriptions and apps! 🪤",
      highlight: "Dark patterns exploit human psychology to trap you in an action. ⛓️",
    },
    {
      id: 'notification_hijack',
      title: 'The Red Dot Hijack 🔴',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🔴',
      svgIcon: 'alert',
      content: "Why are notification badges always Red? \n\nColors have deep biological meanings. Red triggers our evolutionary alarms—it is the color of blood, poison berries, and emergency 🚨. \n\nWhen you see a red dot on an app icon, your brain immediately flags it as urgent and high-priority, forcing your hand to tap it to resolve the 'threat.' It is a biological hijack! 🩸",
      highlight: "A simple color change turns a minor update into a biological emergency. 🛑",
    },
    {
      id: 'reclaiming_time',
      title: 'Reclaiming Your Mind 🧘',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🧘',
      svgIcon: 'sparkle',
      content: "The first step to escaping a trap is knowing you are in one. \n\nTo reclaim your mind:\n1. **Turn off non-human notifications:** If an actual human didn't text you, your phone shouldn't buzz. 📴\n2. **Physical Boundaries:** Never sleep with your phone in the bedroom.\n3. **Curate your feed:** Unfollow anything that makes you feel purely angry or inadequate. 🧹\n\nYour attention is your life. Protect it fiercely! 🛡️",
      highlight: "Your mind is your kingdom; the algorithms are trying to siege it. Defend the walls! 🏰",
    },
  ],

  lab: {
    title: "Algorithm Architect 🧮🕹️",
    description: "Flip the script! You are the AI Algorithm for a new social media app. Your objective: Maximize the user's 'Screen Time'. Balance your feed mixing 'Cute Animal 🐶', 'Moral Outrage 😡', and 'Friend Update 👫' content. Watch how the user's Dopamine and Cortisol metrics respond. Can you keep them scrolling without breaking their brain? 📉📊",
    hint: "Too many 'Cute Animals' causes Dopamine Habituation (they get bored). Too much 'Outrage' spikes Cortisol, and they will rage-quit the app! You have to mix it up using the 'Variable Ratio' theory.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks real-time probabilistic retention metrics, engagement decay rates ($\\lambda$), and Neuro-Linguistic weighting.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why Snapchat created 'Snapstreaks'? 🔥",
      answer: "Loss Aversion! Humans are psychologically wired to hate losing something more than they love gaining something. By showing you a 'Streak Count', the platform threatens you with the 'loss' of that streak if you don't use the app every single day. It's a high-pressure psychological trap! 📉",
      emoji: '🔥',
    },
    {
      id: 'dyk2',
      question: "Do you know why YouTube auto-plays the next video? ⏩",
      answer: "Frictionless Consumption. Without auto-play, you would have to make an active, conscious choice to click a new video. Auto-play relies on 'Default Bias'—humans are incredibly lazy and tend to just go with the default option. By making 'watching more' the default, they bypass your critical thinking! 🛋️",
      emoji: '▶️',
    },
    {
      id: 'dyk3',
      question: "Do you know why we feel 'exhausted' after 3 hours on TikTok even if we didn't move? 🫠",
      answer: "Task-Switching Fatigue. A 15-second video forces your brain to process a completely new context, audio, emotional tone, and narrative. Watching 3 hours of TikTok means your brain had to completely 'reset' its cognitive context over 700 times! This drains your brain's glucose supplies massively. 🔋",
      emoji: '🧠',
    },
    {
      id: 'dyk4',
      question: "Do you know why Facebook's early motto was 'Move Fast and Break Things'? 🔨",
      answer: "It defined an era of tech where growth was valued above consequences. They pushed new psychological hooks (like the Like button, which the creator later regretted) without studying the long-term mental health effects on society. They 'broke' democratic discourse and teenage self-esteem just to gain daily active users. 📉",
      emoji: '💥',
    },
    {
      id: 'dyk5',
      question: "Do you know why high-tech executives in Silicon Valley send their kids to 'Tech-Free' schools? 🏫🚫",
      answer: "The 'Dealers Don't Use' principle. Executives at Apple, Google, and Meta often ban iPads and social media in their own homes. They know exactly how addictive and destructive the algorithms they build are, so they send their children to Waldorf schools where learning is done with chalkboards and pencils! ✏️",
      emoji: '📵',
    },
    {
      id: 'dyk6',
      question: "Do you know why 'Typing...' bubbles exist in messaging apps? 💬",
      answer: "Anticipatory Dopamine. Seeing someone is typing spikes your dopamine much higher than actually reading the message! It forces you to freeze and stare at the screen, waiting for the reward. It capitalizes on suspense to hold your attention hostage. ⏳",
      emoji: '⌨️',
    },
    {
      id: 'dyk7',
      question: "Do you know why turning your screen to Grayscale works so well? ⬛⬜",
      answer: "Candy colors are a biological hack. Vibrant reds and blues stimulate the optic nerve and tell our ancient brains, 'High energy food/alert here!' Grayscale strips the visual 'sugar' out of the interface, revealing the app for what it actually is: a boring list of text and grey boxes. The craving vanishes! 🌪️",
      emoji: '🦓',
    },
    {
      id: 'dyk8',
      question: "Do you know why algorithms love recommending Conspiracy Theories? 👽",
      answer: "Cognitive 'Aha!' moments. Deep down, humans love uncovering 'secrets.' Conspiracy theories provide a false sense of profound understanding, which gives a massive dopamine hit. Because they are controversial, they generate more comments and outrage, ensuring higher engagement metrics. 👁️",
      emoji: '🛸',
    },
    {
      id: 'dyk9',
      question: "Do you know why we 'hate follow' people we dislike? 😡📱",
      answer: "Evolutionary Threat Monitoring. Your brain is wired to keep a close eye on potential threats or enemies in your tribe. By 'hate tracking' an influencer, you are fulfilling a biological urge to gather intel on perceived rivals, but you are just giving them ad revenue! 🕵️‍♂️",
      emoji: '📉',
    },
    {
      id: 'dyk10',
      question: "Do you know why it's so hard to read a physical book after being addicted to short-form videos? 📖",
      answer: "Dopamine Tolerance. Your brain has adapted to getting a massive reward every 15 seconds. Reading a book provides a slow, steady trickle of reward over hours. Your dopamine receptors are 'fried', so reading feels incredibly boring and under-stimulating until the brain has a chance to detox and reset. 📉",
      emoji: '📚',
    },
  ],

  quiz: [
    { id: 'q1', question: "In the 'Attention Economy', what is the product being sold to advertisers?", options: ['The App', 'Your Personal Data & Attention', 'The Internet', 'Smartphones'], answer: 1, explanation: "If an app is free, YOU are the 'crop' they are harvesting! 🌾" },
    { id: 'q2', question: "Which brain chemical is heavily exploited by social media to create a 'craving' loop?", options: ['Adrenaline', 'Dopamine', 'Cortisol', 'Insulin'], answer: 1, explanation: "Dopamine is the 'anticipation' molecule that makes you want to see what is next! 🧠" },
    { id: 'q3', question: "The 'Variable Ratio Schedule' (like slot machines) makes rewards:", options: ['Predictable and boring', 'Random and highly addictive', 'Happen every 5 minutes', 'Cost money'], answer: 1, explanation: "Uncertainty is the strongest hook for the human brain! 🎰" },
    { id: 'q4', question: "What UI feature removed the 'Stopping Cue' and led to hours of mindless use?", options: ['The Like Button', 'The Infinite Scroll', 'The Share Button', 'Dark Mode'], answer: 1, explanation: "Without an endpoint, the brain forgets to ask 'Should I stop now?' 🌀" },
    { id: 'q5', question: "FOMO stands for the Fear Of...", options: ['Meaningless Opinions', 'Missing Out', 'Making Offenses', 'Morning Options'], answer: 1, explanation: "It hijacks our tribal survival instinct of not wanting to be excluded! 🦅" },
    { id: 'q6', question: "What emotion do algorithms often promote because it spreads 6x faster?", options: ['Joy', 'Moral Outrage/Anger', 'Sadness', 'Fear'], answer: 1, explanation: "Anger drives comments and arguments, which keeps you glued to the screen! 😡" },
    { id: 'q7', question: "Feeling your phone buzz in your pocket when it actually didn't is called:", options: ['Ghost Call', 'Phantom Vibration Syndrome', 'Digital Hallucination', 'App Delirium'], answer: 1, explanation: "Your nervous system becomes hyper-vigilant expecting a dopamine hit! 📳" },
    { id: 'q8', question: "The 'Comparison Trap' happens because we compare our 'behind-the-scenes' to someone else's:", options: ['Highlight Reel', 'Darkest Moments', 'Finances', 'Browser History'], answer: 0, explanation: "We compare our messy reality to their perfectly filtered illusions. ✨" },
    { id: 'q9', question: "Neuroscience proves that human 'Multitasking' is actually:", options: ['A superpower', 'Rapid Task-Switching that drains brain energy', 'Easy for teens', 'Great for memory'], answer: 1, explanation: "You literally cannot focus on two complex thoughts simultaneously without losing IQ points! 🤹" },
    { id: 'q10', question: "Blue light from our screens halts the production of which sleep hormone?", options: ['Adrenaline', 'Melatonin', 'Serotonin', 'Cortisol'], answer: 1, explanation: "Your brain interprets blue light as 'Midday Sun' and keeps you awake! ☀️" },
    { id: 'q11', question: "Turning your phone to 'Grayscale' (Black & White) helps combat addiction by:", options: ['Saving battery', 'Removing the vibrant colors that trigger our biological reward sensors', 'Making the text larger', 'Speeding up the internet'], answer: 1, explanation: "It strips the 'visual sugar' out of the app! ⬛⬜" },
    { id: 'q12', question: "What is a 'Dark Pattern' in User Experience (UX)?", options: ['A dark theme mode for the app at night', 'A design trick meant to manipulate you into a behavior you didn\'t intend', 'A virus', 'A broken image link'], answer: 1, explanation: "Like a 'confirm-shaming' button or an invisible 'unsubscribe' link! 🕸️" },
    { id: 'q13', question: "Notification badges are usually Red because:", options: ['It is a cheap color to render', 'Red triggers a biological urgency/threat response in the brain', 'It is Apple\'s favorite color', 'No reason'], answer: 1, explanation: "Red means blood or danger in nature, demanding instant attention! 🔴" },
    { id: 'q14', question: "Snapchat Streaks exploit an evolutionary bias called:", options: ['Loss Aversion', 'Sunk Cost', 'Reciprocity', 'Anchoring'], answer: 0, explanation: "We hate 'losing' our streak more than we enjoy the app itself! 🔥" },
    { id: 'q15', question: "The 'Echo Chamber' effect occurs because algorithms prioritize:", options: ['Truthful reporting', 'Showing you content you already agree with to keep you engaged', 'Opposing viewpoints', 'Random noise'], answer: 1, explanation: "The algorithm wraps you in a comforting (but blinding) bubble of your own opinions! 🪞" },
    { id: 'q16', question: "The 'Default Bias' is famously used in which app feature to keep you watching?", options: ['The Like button', 'YouTube\'s Auto-Play mechanism', 'The Comments section', 'The Share arrow'], answer: 1, explanation: "We are wired to take the path of least resistance, so we just let the next video play! ▶️" },
    { id: 'q17', question: "A healthy 'Digital Minimalism' boundary would be to:", options: ['Buy a more expensive phone', 'Turn off all non-human notifications (like app alerts)', 'Scroll faster', 'Follow more people'], answer: 1, explanation: "If a human didn't reach out to you, your phone has no right to interrupt your life! 📴" },
    { id: 'q18', question: "Tech executives often send their kids to 'Tech-Free' schools because:", options: ['They can\'t afford iPads', 'They know exactly how destructive and addictive their own algorithms are', 'It is a trend', 'They hate technology'], answer: 1, explanation: "Never get high on your own supply. They know the danger of the code! 🚫📱" },
    { id: 'q19', question: "Why do we struggle to read a physical book after extreme TikTok use?", options: ['Books are heavy', 'Our Dopamine receptors require massive, rapid spikes to feel anything', 'Our eyesight degrades', 'Books have no pictures'], answer: 1, explanation: "Our brains build a 'tolerance' to dopamine, making slow media feel agonizingly boring. 📉" },
    { id: 'q20', question: "The 'Typing...' bubble in messaging apps creates engagement via:", options: ['Anxiety', 'Anticipatory Suspense and Dopamine buildup', 'Faster reading', 'Error correction'], answer: 1, explanation: "The suspense holds your attention hostage while you wait for the 'reward'! ⌨️" },
  ],

  relatedTopics: ['cognitive_biases', 'emotions_motivation', 'learning_behavior', 'manipulation_tactics'],
};
