// ─────────────────────────────────────────────────────────
//  TOPIC: ATHEISM (नास्तिकता)
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'atheism',
  title: 'Atheism',
  subtitle: 'The Default State? 🌌🚫',
  emoji: '🚫',
  category: 'Philosophy',
  accentKey: 'atheism',

  hook: {
    question: "Do you believe in Zeus, Thor, or Ra?",
    reveal: "Probably not. As Ricky Gervais famously said, 'There are nearly 3,000 gods worshipped by humanity. You don't believe in 2,999 of them. I just don't believe in one more.'\n\nAtheism is not the 'worship of nothing'; it is simply the rejection of the claim that a god exists due to a lack of evidence. But what happens to morality, meaning, and purpose when there is no divine creator to give them to us? Let's explore the world of the non-believers. 🔭⚖️🌍",
    emoji: '🔭',
  },

  theory: [
    {
      id: 'what_is_atheism',
      title: "What is Atheism? 🤔",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'slash',
      svgIcon: 'eye',
      content: "The word comes from Greek: *a* (without) + *theos* (god).\n**Atheism** is not a religion, a belief system, or a philosophy. It is literally just the lack of belief in any deity.\nIf someone says, 'I have an invisible dragon in my garage', and you say, 'I don't believe you until I see evidence', you are an *A-Dragonist*. To an atheist, rejecting God is exactly the same logical process.",
      highlight: "Atheism is just a single answer to a single question: 'Do you believe in God?' Answer: 'No.' ❌",
    },
    {
      id: 'burden_of_proof',
      title: "The Burden of Proof ⚖️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'anchor',
      svgIcon: 'target',
      content: "In logic, the **Burden of Proof** lies on the person making the claim, not the person rejecting it.\nIf you claim you can fly, it is not my job to prove you *can't* fly; it is your job to prove you *can*. \nBecause religions claim that a supernatural creator exists, atheists argue that religions must provide irrefutable evidence. Until then, rejecting the claim is the logical default.",
      highlight: "Extraordinary claims require extraordinary evidence. (Carl Sagan) 🌌",
    },
    {
      id: 'russells_teapot',
      title: "Russell's Teapot 🫖",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'coffee',
      svgIcon: 'zap',
      content: "Philosopher Bertrand Russell created a famous analogy: \nSuppose I claim there is a tiny china teapot orbiting the Sun between Earth and Mars. Because it is too small to be seen by telescopes, you cannot prove it is *not* there.\nDoes your inability to disprove the teapot mean my claim is reasonable? No. Believing in the teapot without evidence would be absurd.",
      highlight: "Just because something cannot be disproven doesn't mean it should be believed. 🪐",
    },
    {
      id: 'agnosticism_vs_atheism',
      title: "Atheist vs. Agnostic 🧭",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'help-circle',
      svgIcon: 'users',
      content: "People often confuse these terms. They answer two entirely different questions:\n**Atheism/Theism** is about *Belief*. (Do you believe?)\n**Agnosticism/Gnosticism** is about *Knowledge*. (Are you 100% certain?)\nMost atheists are **Agnostic Atheists**: They do not believe in God (Atheist), but they admit they cannot know for 100% certainty that one doesn't exist out there somewhere (Agnostic).",
      highlight: "Agnosticism handles what you know. Atheism handles what you believe. 🧠",
    },
    {
      id: 'the_problem_of_evil',
      title: "The Problem of Evil 🔥",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert-triangle',
      svgIcon: 'flame',
      content: "This is the oldest argument against a 'benevolent' God, formulated by Epicurus:\n1. If God knows about suffering (Omniscient),\n2. And has the power to stop it (Omnipotent),\n3. And actually wants to stop it (Omnibenevolent),\n...Then why does childhood cancer exist?\nIf He can't stop it, He isn't all-powerful. If He won't stop it, He isn't all-loving. Therefore, a perfect God cannot exist in a world with immense suffering.",
      highlight: "Atheists argue that the universe looks exactly as it would if no one was in charge: random and indifferent. 🎲",
    },
    {
      id: 'god_of_the_gaps',
      title: "God of the Gaps 🧩",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'minimize-2',
      svgIcon: 'lock',
      content: "Historically, humans used 'God' to explain what they didn't understand. \nLightning? Must be Zeus. Diseases? Demon possession. The Sun moving? A chariot in the sky.\nAs Science advanced, the 'gaps' in our knowledge shrank, leaving fewer places for God to hide. Atheists argue that 'God' is just a placeholder for 'We don't know yet'.",
      highlight: "Using God to explain the unknown means God gets smaller every time science makes a discovery. 🔬",
    },
    {
      id: 'secular_humanism',
      title: "Morality Without Religion 🤝",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'heart',
      svgIcon: 'heart',
      content: "If a person says 'I only don't murder people because God will punish me in Hell', they are not a good person; they are just a bad person on a leash.\n**Secular Humanism** is the atheist framework for ethics. It argues that morality comes from evolution and empathy. We don't murder because it causes suffering, and as social creatures, we thrive when we cooperate and care for each other.",
      highlight: "You don't need a fiery underworld to know that hurting people is wrong. ❤️",
    },
    {
      id: 'the_meaning_of_life',
      title: "Creating Your Own Meaning 🌟",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'compass',
      svgIcon: 'star',
      content: "If there is no Creator, then there is no 'predetermined destiny' for your life.\nFar from being depressing, atheists find this incredibly freeing. You are not a pawn in a divine chess game. You are the author of your own story. You get to decide what your life means through your passions, relationships, and art.",
      highlight: "Life is a blank canvas. The absence of an instruction manual is a feature, not a bug. 🎨",
    },
    {
      id: 'evolutionary_psychology',
      title: "Why Humans Invented Gods 🧠",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'users',
      svgIcon: 'eye',
      content: "Psychologists believe humans are hardwired for religion via the **Hyperactive Agency Detection Device (HADD)**.\nIn the jungle, if you hear a rustle in the bushes, you assume it's a predator (an Agency) rather than just the wind. Assuming 'someone is there' kept our ancestors alive.\nThis evolved trait makes humans naturally assume that lightning, earthquakes, and the universe itself must have 'someone' behind them.",
      highlight: "We evolved to see faces in the clouds and intent in the chaos. 🌴",
    },
    {
      id: 'fear_of_death',
      title: "The Ultimate Coping Mechanism ☠️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'lock',
      content: "Death is the ultimate terror for a conscious creature. \nThe concept of an afterlife (Heaven, Nirvana) is the ultimate psychological coping mechanism to deal with our impending doom. \nAtheists accept that death is absolute. As Mark Twain said: *'I was dead for billions of years before I was born, and had not suffered the slightest inconvenience.'*",
      highlight: "Accepting that life is temporary makes every single day infinitely more valuable. ⏳",
    },
    {
      id: 'geography_of_belief',
      title: "The Geography of Belief 🗺️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'map',
      svgIcon: 'compass',
      content: "Richard Dawkins notes that isn't it a remarkable coincidence that almost everyone has the same religion as their parents?\nIf you are born in India, you are likely Hindu. In Saudi Arabia, Muslim. In Alabama, Christian.\nIf religion was purely a matter of seeking the 'objective truth', belief wouldn't be perfectly split by geographical borders. It is a cultural inheritance.",
      highlight: "Your deepest spiritual truths are vastly determined by where you happened to be born. 📍",
    },
    {
      id: 'the_fine_tuning_rebuttal',
      title: "The Puddle Analogy 💧",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'droplet',
      svgIcon: 'activity',
      content: "Theists often argue the universe is fine-tuned for us. \nAuthor Douglas Adams rebutted this with the **Puddle Analogy**: Imagine a puddle waking up in a hole and saying, 'Wow! This hole fits me perfectly! It matches my shape exactly! Someone must have designed this hole just for me!'\nThe puddle doesn't realize *it* adapted to the hole, the hole wasn't made for it. Humans adapted to Earth; Earth wasn't custom-made for us.",
      highlight: "We fit the universe because we evolved to survive it. 🌍",
    },
    {
      id: 'the_anti_theist',
      title: "Atheism vs. Anti-Theism ⚔️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'shield',
      svgIcon: 'target',
      content: "An **Atheist** simply doesn't believe in God.\nAn **Anti-Theist** (like Christopher Hitchens) actively believes that religion is harmful to humanity. They point to holy wars, oppression of women, suppression of science, and religious trauma. They view religion not just as 'wrong', but as a dangerous force that must be dismantled.",
      highlight: "Atheist: 'I don't believe.' Anti-Theist: 'I am glad it's not real, because it's terrifying.' 🔥",
    },
    {
      id: 'spiritual_atheism',
      title: "Awe Without the Supernatural 🌌",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'aperture',
      svgIcon: 'leaf',
      content: "Many assume atheists are cold and robotic. \nBut looking at a Hubble Space Telescope image or understanding the DNA in a leaf can produce profound feelings of awe, wonder, and connectedness. \nYou don't need magic to feel magic. Reality itself is spectacular enough.",
      highlight: "Carl Sagan: 'We are a way for the cosmos to know itself.' 🌠",
    },
    {
      id: 'conclusion',
      title: "The Honest Stance 🕊️",
      color: '#9E9E9E',
      bgGradient: ['#151515', '#050505'],
      icon: 'search',
      svgIcon: 'eye',
      content: "Ultimately, atheists value truth over comfort. \nIt is much more comforting to believe that a cosmic father is watching over you and that you will see your dead relatives again.\nBut comfort does not dictate reality. Atheism is the courage to look into the vast, silent void of space and say, 'I don't know everything, but I won't pretend to know what I don't.'",
      highlight: "Truth requires no faith; it only requires evidence. 🔍",
    },
  ],

  lab: {
    title: "Burden of Proof Sandbox ⚖️🧪",
    description: "You are the Logic Adjudicator. Theological and pseudoscientific claims will be placed on the scale. Is the claim falsifiable? Where does the burden of proof lie? Reject logical fallacies and demand evidence.",
    hint: "If a claim cannot be tested or proven false (like an invisible, untouchable dragon), it has zero logical value. You cannot prove a negative.",
    scientistModeHint: "Epistemology Mode 🧑‍🔬: Analyze Russell's Teapot, God of the Gaps, and the Null Hypothesis in real-time.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why is Atheism the 'default' state of humanity?", answer: "Because nobody is born believing in a specific religion. A baby is an atheist (they lack belief). They have to be taught the concepts of gods, heaven, and hell by their parents or society. You cannot be born a Christian or a Muslim; you are born entirely blank. 👶", emoji: '🍼' },
    { id: 'dyk2', question: "Why is the phrase 'Prove God doesn't exist' logically invalid?", answer: "Because it asks you to 'prove a negative'. You cannot search the entire infinite universe to confirm a god isn't hiding somewhere. This is why the 'Burden of Proof' always lies on the person saying 'God exists'. If they can't prove it, the claim is dismissed. ❌", emoji: '⚖️' },
    { id: 'dyk3', question: "Did Einstein believe in God?", answer: "No. He believed in 'Spinoza's God', which is just a poetic metaphor for the laws of physics and nature. He explicitly stated, 'The word God is for me nothing more than the expression and product of human weaknesses, the Bible a collection of honorable, but still primitive, legends.' 🔭", emoji: '🧠' },
    { id: 'dyk4', question: "Why are some of the most peaceful countries highly atheistic?", answer: "Studies show that secular democracies like Sweden, Denmark, and Japan have the lowest levels of crime and highest well-being. This disproves the claim that society would collapse into murder and chaos without religion. Secular humanism and strong social safety nets create highly moral societies. 🇸🇪", emoji: '🏛️' },
    { id: 'dyk5', question: "Why did people historically say 'God bless you' when you sneezed?", answer: "During plagues long ago, people thought sneezing meant the soul was trying to escape the body or demons were entering it. 'God bless you' was a literal magical incantation to stop demonic possession. Today, we still say it out of cultural habit, despite knowing it's just dust in the nose. 🤧", emoji: '🦠' },
  ],

  quiz: [
    { id: 'q1', question: "What is the literal definition of Atheism?", options: ['Hating God', 'The belief that science is the only truth', 'The lack of belief in any gods/deities', 'Worshipping Satan'], answer: 2, explanation: "It simply means you don't say 'yes' to the claim that a god exists. 🚫" },
    { id: 'q2', question: "In a debate, where does the 'Burden of Proof' lie?", options: ['On whoever speaks loudest', 'On the person who challenges a belief', 'On the person making the positive claim (e.g., \'Dragons exist\')', 'It is split equally'], answer: 2, explanation: "You must prove your claim; I don't have to disprove it. ⚖️" },
    { id: 'q3', question: "What is 'Russell's Teapot' meant to demonstrate?", options: ['That tea is good for thinking', 'That just because a claim cannot be disproven (like an invisible teapot in space), doesn\'t mean it is reasonable to believe it', 'That God likes tea', 'That aliens exist'], answer: 1, explanation: "You cannot prove the teapot isn't there, but believing in it is absurd. 🫖" },
    { id: 'q4', question: "What is the difference between an Atheist and an Agnostic?", options: ['They are the same thing', 'Atheism is about Belief (I don\'t believe); Agnosticism is about Knowledge (I don\'t know for 100% certainty)', 'Agnostics hate religion, atheists don\'t', 'Atheists believe in science, agnostics believe in nothing'], answer: 1, explanation: "Most modern atheists identify as 'Agnostic Atheists'. 🧭" },
    { id: 'q5', question: "What is the 'Problem of Evil' argument?", options: ['Evil people go to hell', 'A God cannot be All-Powerful and All-Loving if immense, pointless suffering (like childhood cancer) exists in the world', 'Satan causes all evil', 'Humans are naturally bad'], answer: 1, explanation: "If He wants to stop cancer but can't, He isn't all-powerful. If He can but won't, He isn't all-loving. 🔥" },
    { id: 'q6', question: "What is the 'God of the Gaps' fallacy?", options: ['Believing God hides in caves', 'Using \'God\' to explain whatever science hasn\'t figured out yet, meaning God gets smaller as science advances', 'The gap between Heaven and Earth', 'A scientific theory'], answer: 1, explanation: "We used to think lightning was Zeus. Now we know it's electricity. 🧩" },
    { id: 'q7', question: "What is Secular Humanism?", options: ['A new religion', 'A framework showing morality comes from empathy and evolution, meaning we don\'t need religion to be good people', 'Worshipping human bodies', 'A political party'], answer: 1, explanation: "You don't need the threat of Hell to know murder is wrong. ❤️" },
    { id: 'q8', question: "How do atheists generally view the 'meaning of life'?", options: ['Life has absolutely no meaning and is depressing', 'There is no pre-written destiny; you are free to create your own meaning through passions and love', 'The meaning is to make money', 'Science will find the meaning'], answer: 1, explanation: "A blank canvas isn't a tragedy; it's an opportunity. 🎨" },
    { id: 'q9', question: "What is the evolutionary 'Hyperactive Agency Detection Device' (HADD)?", options: ['A police scanner', 'An evolved brain trait that makes us assume a rustling bush is a predator (an Agency/intent) rather than wind, causing us to invent Gods to explain nature', 'A tool to find ghosts', 'How memory works'], answer: 1, explanation: "We see faces in the clouds because our ancestors needed to spot predators quickly. 🐅" },
    { id: 'q10', question: "What is an 'Anti-Theist'?", options: ['Someone who simply doesn\'t believe in God', 'Someone who actively believes religion is a dangerous, harmful force to society that should be dismantled', 'A person who worships the Devil', 'A type of scientist'], answer: 1, explanation: "Atheism is passive. Anti-Theism is an active opposition to religion. ⚔️" },
    { id: 'q11', question: "What does Richard Dawkins' 'Geography of Belief' point out?", options: ['Mountains cause religion', 'It is a suspicious coincidence that almost everyone conveniently follows the exact religion of the region they were born in', 'Everyone travels', 'Maps are inaccurate'], answer: 1, explanation: "If eternal truth existed, it wouldn't perfectly match national borders. 🗺️" },
    { id: 'q12', question: "What does Douglas Adams' \"Puddle Analogy\" explain?", options: ['Water is essential for life', 'It mocks the idea that the universe was \'custom-made\' for us. The puddle fits the hole because it adapted to it, not because the hole was designed for the puddle', 'How rain falls', 'Global warming'], answer: 1, explanation: "We evolved to survive the universe; the universe wasn't made for us. 💧" },
    { id: 'q13', question: "Why is atheism considered the 'default' state by philosophers?", options: ['Because nobody is born with an understanding of religion; a baby lacks belief until society teaches them a specific mythos', 'Because everyone secretly is an atheist', 'Because science says so', 'Because religion is new'], answer: 0, explanation: "You have to be taught to be a Hindu, Muslim, or Christian. 👶" },
    { id: 'q14', question: "Did Albert Einstein believe in a personal God?", options: ['Yes, he was a devout Christian', 'No, he referred to God as just a metaphor for the laws of physics and called the Bible \'primitive legends\'', 'He started a new religion', 'He refused to say'], answer: 1, explanation: "He believed in 'Spinoza's God', not a bearded man in the sky. 🔭" },
    { id: 'q15', question: "What happens when you ask an atheist to 'prove a negative' (e.g., Prove Zeus isn't real)?", options: ['They use a telescope', 'It is a logical fallacy. You cannot search the entire universe to prove something DOESN\'T exist; the burden is on the person making the claim', 'They usually guess', 'They get angry'], answer: 1, explanation: "I can't prove an invisible unicorn isn't in my room. That doesn't make it real. 🦄" },
    { id: 'q16', question: "What did Mark Twain say about the fear of death?", options: ['Death is terrifying', '\'I was dead for billions of years before I was born, and had not suffered the slightest inconvenience.\'', 'We will all be ghosts', 'He wrote a book about heaven'], answer: 1, explanation: "Atheists believe death is exactly like the time before you were born. ☠️" },
    { id: 'q17', question: "What is an 'Agnostic Atheist'?", options: ['Someone who hates knowledge', 'Someone who does not believe in God (Atheist), but admits they cannot be 100% absolutely certain (Agnostic)', 'Someone who prays sometimes', 'A type of Christian'], answer: 1, explanation: "This is the most intellectually honest stance for most non-believers. 🧠" },
    { id: 'q18', question: "How do secular countries (like Denmark/Sweden) fare in societal health?", options: ['They have high crime rates', 'They consistently rank as some of the safest, happiest, and most moral societies on Earth, refuting the idea that society needs religion to function', 'They are very poor', 'They have no laws'], answer: 1, explanation: "Morality thrives in secular democracies through education and empathy. 🇸🇪" },
    { id: 'q19', question: "Why do atheists generally reject 'faith' as a pathway to truth?", options: ['Because it is spelled wrong', 'Because faith is believing something without evidence, which can be used to justify literally any claim, true or false', 'Because it costs money', 'Because science is boring'], answer: 1, explanation: "If faith can lead one man to Islam and another to Hinduism, faith is not a reliable tool for finding objective truth. 🔬" },
    { id: 'q20', question: "What does Carl Sagan's famous quote mean: 'Extraordinary claims require extraordinary evidence'?", options: ['Aliens exist', 'If you claim you have a dog, I believe you. If you claim you have a fire-breathing dragon (God), you better show me massive evidence before I believe you', 'Space is huge', 'Scientists need more money'], answer: 1, explanation: "The larger the claim, the heavier the burden of proof. 🌌" },
  ],

  relatedTopics: ['science_vs_god', 'nihilism', 'existentialism'],
};
