// ─────────────────────────────────────────────────────────
//  TOPIC: SPIRITUALITY VS RELIGION
//  Category: Religion & God
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'spirituality_vs_religion',
  title: 'Spirituality vs Religion',
  subtitle: 'One is a map. The other is the territory. Know the difference. 🗺️✨',
  emoji: '🔥',
  category: 'Religion & God',
  accentKey: 'spirituality_vs_religion',

  hook: {
    question: "Why are millions of people worldwide calling themselves 'spiritual but NOT religious' — and why is this the fastest-growing identity in Western countries?",
    reveal: "Because religion gives you a STRUCTURE (rules, rituals, community, identity). But spirituality gives you the EXPERIENCE (awe, connection, transcendence, peace).\n\nMany modern people crave the experience but reject the structure. They want to feel connected to something larger without being told what to eat, who to marry, or which building to enter on which day.\n\nThe problem? Without structure, spirituality can become vague, self-indulgent, and narcissistic. Without experience, religion becomes empty ritual. You actually need BOTH. 🏛️❤️🔥",
    emoji: '🤔',
  },

  theory: [
    {
      id: 'definitions',
      title: "Definitions — What's the Actual Difference? 📐",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'book',
      svgIcon: 'target',
      content: "**Religion** is an organized system of:\n• Shared beliefs (creeds, doctrines)\n• Shared practices (rituals, sacraments)\n• Shared community (congregations, clergy)\n• Shared identity (Christian, Muslim, Hindu)\n• Sacred texts and moral codes\n\n**Spirituality** is a personal experience of:\n• Connection to something larger than yourself\n• Inner peace, awe, transcendence\n• Meaning and purpose beyond material life\n• Self-discovery and consciousness exploration\n\n**Key distinction**: Religion is COMMUNAL and INSTITUTIONAL. Spirituality is INDIVIDUAL and EXPERIENTIAL. You can have one without the other.",
      highlight: "Religion asks: 'What should I believe?' Spirituality asks: 'What have I experienced?' 🏛️ vs 🌌",
    },
    {
      id: 'four_quadrants',
      title: "The Four Identity Quadrants 🔲",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'grid',
      svgIcon: 'grid',
      content: "People fall into four distinct categories:\n\n1. **Religious + Spiritual**: Follow a tradition AND have genuine inner experiences (the ideal, according to most religions)\n\n2. **Religious + NOT Spiritual**: Go to church, follow rules, but have never felt God. Ritual without experience. (The 'going through the motions' crowd)\n\n3. **Spiritual + NOT Religious**: Feel deep connection to the universe but reject organized religion. Meditation without membership. (The fastest-growing group)\n\n4. **NOT Religious + NOT Spiritual**: No system, no experience. Pure secular materialism. (Also growing rapidly in Europe)",
      highlight: "Quadrant 2 ('religious but not spiritual') is what drives people toward Quadrant 3 — empty ritual pushes seekers away. 🚪",
    },
    {
      id: 'why_leave_religion',
      title: "Why People Leave Religion 🚶",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'exit',
      svgIcon: 'alert',
      content: "Research identifies the top reasons people leave organized religion:\n\n1. **Hypocrisy**: Leaders preach morality but commit scandals (abuse, corruption, greed)\n2. **Exclusivity**: 'Only WE go to heaven' feels arrogant and unfair\n3. **Anti-science**: Rejecting evolution, age of Earth, or medical science\n4. **Rigidity**: Inability to adapt to modern social values (LGBTQ+ rights, gender equality)\n5. **Control**: Too many rules about food, clothing, relationships, thought\n6. **Trauma**: Shaming, guilt, fear-based indoctrination, especially during childhood\n7. **Intellectual Growth**: Education exposes contradictions between scripture and reality\n\nNotice: People rarely leave because they stopped wanting MEANING. They leave because the institution failed to deliver it authentically.",
      highlight: "Pew Research: The #1 reason Americans leave religion is NOT atheism — it is 'I just don't find it meaningful anymore.' 📊",
    },
    {
      id: 'spiritual_marketplace',
      title: "The Spiritual Marketplace 🛒",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'shopping-cart',
      svgIcon: 'star',
      content: "Modern spirituality has become a consumer product:\n\n• **Yoga**: An ancient Hindu spiritual discipline — now a $100 billion fitness industry\n• **Meditation Apps**: Calm, Headspace — Buddhist practice packaged for Silicon Valley\n• **Crystals**: $2 billion industry with zero scientific evidence for healing powers\n• **Astrology**: Renaissance among millennials (30% believe stars influence their lives)\n• **Psychedelics**: Psilocybin, ayahuasca — ancient shamanic tools repackaged as 'wellness'\n• **Manifestation**: 'The Secret' / Law of Attraction — wish hard enough and the universe delivers\n\nThe risk: Commodifying spirituality strips it of depth and replaces genuine transformation with feel-good consumerism.",
      highlight: "Americans spend $1.2 billion per year on yoga alone — a practice originally designed to prepare the body for hours-long meditation, not to tone abs. 🧘‍♀️💰",
    },
    {
      id: 'religion_strengths',
      title: "What Religion Gets RIGHT ✅",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'check',
      svgIcon: 'shield',
      content: "Organized religion provides things solo spirituality CANNOT:\n\n1. **Community**: Weekly gatherings create deep social bonds. Lonely people die younger.\n2. **Accountability**: A community holds you to your stated values. Alone, you drift.\n3. **Tradition**: 3,000-year-old wisdom traditions refined by millions of minds.\n4. **Structure**: Clear moral frameworks prevent 'I'll do whatever feels good' relativism.\n5. **Ritual**: Baptisms, weddings, funerals mark life's transitions with collective meaning.\n6. **Service**: Religious organizations are the world's LARGEST providers of charity, hospitals, and schools.\n7. **Discipline**: Fasting, prayer routines, and study create mental resilience.\n\nStudies consistently show religious people are healthier, happier, live longer, and have stronger social support networks.",
      highlight: "Religious attendance reduces mortality risk by 20-35% — primarily through social connection and health behaviors. 📈",
    },
    {
      id: 'spirituality_strengths',
      title: "What Spirituality Gets RIGHT ✅",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'sparkle',
      svgIcon: 'eye',
      content: "Spirituality addresses failures that religion often creates:\n\n1. **Freedom**: No one telling you WHAT to believe or HOW to practice\n2. **Inclusivity**: No in-group/out-group. No 'chosen people' vs 'infidels'\n3. **Direct Experience**: Prioritizes personal encounter over secondhand doctrine\n4. **Adaptability**: Can integrate science, psychology, art — no dogma to protect\n5. **Self-discovery**: Focused on inner transformation, not external conformity\n6. **Non-judgmental**: Doesn't condemn people for their sexuality, diet, or doubts\n7. **Perennial Wisdom**: Takes the best insights from ALL traditions without tribal loyalty\n\nFor many, spirituality is the cure for religion's institutional diseases.",
      highlight: "Spiritual practices like meditation have been clinically proven to reduce anxiety by 40%, improve focus, and literally grow gray matter in the brain. 🧠📈",
    },
    {
      id: 'religion_dangers',
      title: "What Religion Gets WRONG ⚠️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "At its worst, organized religion can produce:\n\n1. **Fundamentalism**: Literal interpretation of ancient texts designed for ancient contexts\n2. **Tribalism**: 'Us vs. Them' thinking (believers vs. infidels/pagans/heretics)\n3. **Control**: Using guilt, shame, and fear of Hell to manipulate behavior\n4. **Anti-intellectualism**: Discouraging questioning ('Just have faith!')\n5. **Abuse Protection**: Institutions protecting abusive leaders to protect the institution\n6. **Stagnation**: Refusing to evolve with moral progress (slavery was once 'biblical')\n7. **Conformity Pressure**: Suppressing authentic individuality in favor of group identity\n\nThese are NOT inherent to religion — they emerge when institutions prioritize their own survival over the people they claim to serve.",
      highlight: "Every horror committed in religion's name is a betrayal of that religion's own core teachings. The disease is human ego, not theology. 🦠",
    },
    {
      id: 'spirituality_dangers',
      title: "What Spirituality Gets WRONG ⚠️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "Solo spirituality has its own dangers:\n\n1. **Narcissism**: 'MY personal truth' can become an excuse for ignoring reality\n2. **Lack of Accountability**: Nobody challenges your blind spots or bad behavior\n3. **Cherry-Picking**: Taking the 'nice' parts of Buddhism while ignoring its rigorous discipline\n4. **Spiritual Bypassing**: Using 'positive vibes' to avoid confronting real problems (grief, injustice)\n5. **Commodification**: Expensive retreats, crystals, and gurus become spiritual consumerism\n6. **Pseudoscience**: Healing crystals, astrology, 'quantum manifestation' — feelings mistaken for facts\n7. **Isolation**: Without community, spiritual practice becomes lonely and undisciplined\n\nSpiritual-but-not-religious can easily become spiritual-but-not-rigorous.",
      highlight: "Meditation teacher Jack Kornfield: 'After ecstasy, the laundry.' Spiritual highs are meaningless without mundane discipline. 🧺",
    },
    {
      id: 'mystics',
      title: "The Mystics — Religion's Spiritual Core 🌀",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'star',
      svgIcon: 'sparkle',
      content: "Every religion has a mystical tradition — an inner circle that prioritizes direct experience over doctrine:\n\n• **Christianity → Mysticism**: Meister Eckhart, St. John of the Cross, Thomas Merton\n• **Islam → Sufism**: Rumi, Hafiz, Al-Ghazali (poetry, dance, divine love)\n• **Judaism → Kabbalah**: Zohar, tree of life, divine emanations\n• **Hinduism → Vedanta/Yoga**: Shankara, Ramana Maharshi (self-inquiry)\n• **Buddhism → Zen**: Direct experience, koans, sitting meditation\n\nMystics are often the MOST spiritual people in their religion — AND the most persecuted by their own institution. Institutions fear direct experience because it makes the institution unnecessary.",
      highlight: "Meister Eckhart was condemned as a heretic by the Pope for teaching that every soul could experience God directly — without needing the Church. ⛪🚫",
    },
    {
      id: 'neuroscience_spirituality',
      title: "The Neuroscience of Spiritual Experience 🧠",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'brain',
      svgIcon: 'brain',
      content: "Neuroscience has identified what happens in the brain during spiritual experiences:\n\n1. **Decreased Parietal Lobe Activity**: The brain region that creates the sense of 'self' quiets down → feeling of 'dissolving into everything'\n2. **Increased Prefrontal Activity**: Heightened attention and emotional regulation\n3. **Serotonin Release**: Feelings of bliss, peace, love (same pathway as MDMA and psilocybin)\n4. **Temporal Lobe Activation**: Can produce visions, feelings of a 'presence', déjà vu\n5. **Default Mode Network Suppression**: Quieting the 'ego' network → loss of sense of time\n\nDoes this prove spiritual experiences are 'just brain chemistry'? Or does it prove that the brain has a built-in antenna for receiving something beyond itself? Neuroscience can describe the mechanism — it cannot determine the source.",
      highlight: "Monks with 10,000+ hours of meditation show brain patterns radically different from non-meditators — suggesting practice literally rewires the brain. 🔌",
    },
    {
      id: 'psychedelics_spirituality',
      title: "Psychedelics and Spiritual Experience 🍄",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'flask',
      svgIcon: 'eye',
      content: "Clinical research at Johns Hopkins and NYU has revealed stunning findings:\n\n• **Psilocybin** (magic mushrooms) triggers mystical experiences indistinguishable from spontaneous religious ones\n• **67%** of participants rated it among the top 5 most meaningful experiences of their entire lives\n• **80%** showed sustained increases in openness, empathy, and life satisfaction 14 months later\n• Psilocybin is now in FDA breakthrough therapy trials for depression and end-of-life anxiety\n\nAncient cultures have used psychedelics for spiritual purposes for millennia:\n• Ayahuasca (Amazonian shamanism)\n• Soma (ancient Hinduism — identity debated)\n• Peyote (Native American Church)\n\nThe question: If a molecule can produce 'encounter with the divine', is the divine real or chemical?",
      highlight: "Roland Griffiths (lead researcher): 'These experiences are among the most personally meaningful and spiritually significant that people report.' 🔬",
    },
    {
      id: 'meditation_science',
      title: "Meditation — Where Science Meets Spirit 🧘",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'leaf',
      svgIcon: 'heart',
      content: "Meditation is the ONE spiritual practice with massive scientific validation:\n\n• **Anxiety reduction**: 40-60% improvement (comparable to medication)\n• **Gray matter growth**: 8 weeks of practice increases hippocampal density\n• **Attention**: 23% improvement in sustained focus\n• **Compassion**: Increases measurable empathic behavior\n• **Telomere length**: Meditators' telomeres (aging markers) stay longer → slower biological aging\n• **Pain management**: Reduces subjective pain perception by 40%\n• **Default Mode Network**: Quiets the brain's 'rumination' circuit\n\nMeditation originated as a SPIRITUAL practice (Buddhist/Hindu) but works perfectly well as a SECULAR one. You don't need to believe in anything to benefit from it.",
      highlight: "The U.S. Marine Corps now teaches meditation to combat troops — the most skeptical audience imaginable — because the data is undeniable. 🎖️",
    },
    {
      id: 'secular_spirituality',
      title: "Secular Spirituality — Spirit Without God 🌊",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'globe',
      svgIcon: 'compass',
      content: "Is spirituality possible without any belief in God or the supernatural?\n\nSam Harris (atheist neuroscientist) argues YES:\n• Awe at the universe's vastness IS a spiritual experience\n• The dissolution of self during deep meditation IS transcendence\n• Unconditional love for strangers IS the mystical experience\n• A sense of interconnection with all life IS the spiritual insight\n\nAlbert Einstein: 'The most beautiful emotion we can experience is the mysterious. He who can no longer wonder is as good as dead.'\n\nYou can experience everything the mystics described — wonder, unity, dissolution of ego, cosmic awe — without believing in ANY supernatural entity. The universe itself IS astonishing enough.",
      highlight: "Carl Sagan: 'Science is not only compatible with spirituality; it is a profound source of spirituality.' 🌌",
    },
    {
      id: 'integration',
      title: "The Integration — Can You Have Both? 🤝",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'handshake',
      svgIcon: 'star',
      content: "The healthiest position may be BOTH spiritual AND connected to tradition:\n\n1. **Take meaning seriously**: Human beings NEED meaning, community, ritual, and moral frameworks. These aren't optional.\n\n2. **Demand authenticity**: Any tradition, practice, or community must produce genuine inner transformation — not just social conformity.\n\n3. **Stay intellectually honest**: Never sacrifice truth for comfort. If evidence contradicts belief, update the belief.\n\n4. **Practice rigorously**: Whether you sit in a church or on a meditation cushion, genuine spiritual growth requires DISCIPLINE — not just 'good vibes'.\n\n5. **Serve others**: Every genuine spiritual tradition in EVERY religion agrees: the purpose of inner transformation is OUTER service.\n\nThe mystics were right: it was never about labels. It was always about transformation.",
      highlight: "Rumi (13th century): 'Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.' 🌾",
    },
    {
      id: 'the_question',
      title: "The Real Question You Must Answer 🔑",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'key',
      svgIcon: 'key',
      content: "The real question isn't 'Religion or Spirituality?'\n\nIt's: **'What will you DO with the short time you have?'**\n\nWill you:\n• Sit in a building every week without genuine inner transformation? (Dead religion)\n• Collect crystals and attend retreats without actually changing your behavior? (Shallow spirituality)\n• Reject everything and live in comfortable nihilistic numbness? (Secular despair)\n\nOr will you:\n• Commit to daily practice (meditation, prayer, self-examination)\n• Serve others with no expectation of reward\n• Pursue truth with radical intellectual honesty\n• Build genuine community — not just an Instagram aesthetic\n• Face death with courage, knowing you lived with purpose\n\nThe label doesn't matter. The practice does.",
      highlight: "It doesn't matter whether you call it God, Brahman, the Tao, the Universe, or Nothing. What matters is what you DO before you die. 💀🌱",
    },
  ],

  lab: {
    title: "The Inner Compass Explorer 🧭✨",
    description: "Answer 12 questions about your personal beliefs, practices, and experiences. The engine maps you onto the Spirituality-Religion matrix and reveals your inner compass orientation — are you a Mystic, an Institutionalist, a Seeker, or a Secular Humanist?",
    hint: "Answer honestly! There are no 'right' answers. Self-awareness is the goal.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks personality correlations, Jungian archetype mappings, and practice-to-wellbeing coefficients.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why 'Sunday Scaries' exist for ex-religious people? 😰", answer: "People who leave religion often experience intense anxiety on their former worship day (Sunday, Friday, Saturday). Neuroscience shows that deeply ingrained weekly rituals create powerful neural pathways. When you suddenly stop, the brain registers absence-of-ritual as a threat — similar to breaking any deep habit. Some ex-religious people replace church with intentional Sunday morning nature walks or community brunches to fill the 'ritual void'. 🧠", emoji: '📅' },
    { id: 'dyk2', question: "Do you know why Silicon Valley billionaires are investing in psychedelic research? 💊", answer: "Tech executives who spent years optimizing productivity realized they were deeply unhappy. Many had transformative experiences with psilocybin or ayahuasca. Companies like Compass Pathways (backed by Peter Thiel) are now pursuing FDA approval for psychedelic-assisted therapy. The most materialistic culture on Earth is spending billions to rediscover experiences indigenous healers have facilitated for 10,000 years. 🍄💰", emoji: '🏢' },
    { id: 'dyk3', question: "Do you know why Japan has BOTH the lowest religiosity AND the lowest crime rates? 🇯🇵", answer: "Japan is one of the least religious countries on Earth (only ~13% identify as religious) yet has exceptionally low crime, strong social cohesion, and deep cultural rituals. This suggests that the social FUNCTIONS of religion (community, moral behavior, shared rituals) can be maintained through cultural norms WITHOUT supernatural belief. Japan's success is the strongest argument for secular spirituality. 🏯", emoji: '🗾' },
    { id: 'dyk4', question: "Do you know why every known human culture has had some form of funeral ritual? ⚰️", answer: "Even Neanderthals (~100,000 years ago) buried their dead with flowers. Funeral rituals serve a critical evolutionary function: they help the living PROCESS grief, they reaffirm group bonds in the face of existential terror, and they provide a narrative framework for death ('She is in a better place'). Without rituals, death anxiety becomes overwhelming. This is one function religion/spirituality serves that pure atheism struggles to replace. 🌸", emoji: '💐' },
    { id: 'dyk5', question: "Do you know why 'spiritual but not religious' people have HIGHER rates of anxiety? 😟", answer: "Studies show that 'spiritual but not religious' individuals have higher anxiety and depression rates than both conventionally religious people AND committed atheists. Why? Because they have ENOUGH belief to worry about cosmic meaning, but NOT enough community or structure to feel anchored. They exist in a liminal space — too much meaning to be nihilists, too little community to feel safe. The cure? Community and discipline. 🏘️", emoji: '📊' },
  ],

  quiz: [
    { id: 'q1', question: "The key difference between religion and spirituality is:", options: ['Religion is true, spirituality is not', 'Religion is communal and institutional; spirituality is individual and experiential', 'They are identical', 'Spirituality is modern, religion is ancient'], answer: 1, explanation: "Religion = shared structure. Spirituality = personal experience. 📐" },
    { id: 'q2', question: "The fastest-growing religious identity in Western countries is:", options: ['Islam', 'Christianity', 'Spiritual but not religious', 'Hinduism'], answer: 2, explanation: "Millions are leaving institutions but still craving meaning. 🚶" },
    { id: 'q3', question: "The #1 reason Americans leave organized religion is:", options: ['Atheism', 'Science', 'They don\'t find it meaningful anymore', 'Political disagreement'], answer: 2, explanation: "Not atheism — disillusionment. They still want meaning; the institution failed to deliver. 📊" },
    { id: 'q4', question: "'Spiritual Bypassing' means:", options: ['Skipping church', 'Using positive vibes and spiritual language to AVOID confronting real problems like grief, injustice, or personal flaws', 'Being too spiritual', 'Meditation'], answer: 1, explanation: "'Just send good energy!' is not a substitute for actual emotional work or social justice action. 🙈" },
    { id: 'q5', question: "Religious attendance reduces mortality risk by:", options: ['0%', '5%', '20-35%', '80%'], answer: 2, explanation: "The health benefit is primarily through social connection and health behaviors, not divine intervention. 📈" },
    { id: 'q6', question: "Meditation's scientific benefits include:", options: ['Levitation', 'Anxiety reduction (40-60%), gray matter growth, improved focus, slower biological aging', 'Perfect memory', 'Seeing the future'], answer: 1, explanation: "Meditation is the ONE spiritual practice with overwhelming scientific validation. 🧠" },
    { id: 'q7', question: "Yoga was originally designed for:", options: ['Weight loss', 'Toning muscles', 'Preparing the body for extended meditation — a spiritual discipline', 'Instagram photos'], answer: 2, explanation: "Yoga's $100 billion fitness industry would horrify its original practitioners. 🧘" },
    { id: 'q8', question: "Mystics are often persecuted by their OWN religious institutions because:", options: ['They break rules', 'Direct experience of God makes the institution unnecessary — threatening its power', 'They can\'t pay tithes', 'They are heretics'], answer: 1, explanation: "If anyone can find God alone, why do you need priests, temples, and hierarchies? 🏛️" },
    { id: 'q9', question: "During a spiritual/mystical experience, the brain's parietal lobe:", options: ['Overactivates', 'Quiets down — dissolving the sense of individual self, creating a feeling of \'oneness\'', 'Explodes', 'Does nothing'], answer: 1, explanation: "The brain literally turns off its 'boundary-making' module, causing the self to dissolve into everything. 🌊" },
    { id: 'q10', question: "Psilocybin research at Johns Hopkins found that 67% of participants:", options: ['Got sick', 'Rated the experience among the top 5 most meaningful events of their entire lives', 'Forgot the experience', 'Became religious'], answer: 1, explanation: "A single molecule producing life's most meaningful experience challenges every materialist assumption. 🍄" },
    { id: 'q11', question: "Sam Harris argues that secular spirituality is possible because:", options: ['He doesn\'t', 'Awe, wonder, ego-dissolution, and unconditional love require no supernatural belief', 'Science is spiritual', 'He is religious'], answer: 1, explanation: "The universe itself is astonishing enough to produce every mystical experience — no gods required. 🌌" },
    { id: 'q12', question: "The 'spiritual but not religious' group has HIGHER anxiety rates because:", options: ['Spirits are scary', 'They have enough belief to worry about meaning, but lack the community and structure to feel anchored', 'They meditate too much', 'Astrology is confusing'], answer: 1, explanation: "The cure is community and discipline — exactly what religion provides and solo spirituality lacks. 😟" },
    { id: 'q13', question: "Japan's low religiosity + low crime suggests:", options: ['Japanese are naturally good', 'Religion\'s social functions (moral behavior, community, rituals) can be maintained through cultural norms without supernatural belief', 'Crime statistics are wrong', 'Nothing'], answer: 1, explanation: "Japan is the strongest evidence that secular societies can be deeply ethical and cohesive. 🇯🇵" },
    { id: 'q14', question: "Every known human culture in history has had:", options: ['Writing', 'The internet', 'Some form of funeral/death ritual', 'Democracy'], answer: 2, explanation: "Even Neanderthals buried their dead with flowers. Death-processing may be spirituality's oldest function. ⚰️" },
    { id: 'q15', question: "The '$2 billion crystal healing industry' is criticized because:", options: ['Crystals are ugly', 'There is zero scientific evidence for healing properties — it commodifies spirituality into feel-good consumerism', 'Crystals are expensive', 'Geologists oppose it'], answer: 1, explanation: "Genuine spiritual transformation requires discipline, not purchases. 💎" },
    { id: 'q16', question: "Jack Kornfield's quote 'After ecstasy, the laundry' means:", options: ['Monks need clean clothes', 'Spiritual highs are meaningless without mundane, daily discipline and real-world engagement', 'Laundry is spiritual', 'Meditation makes you tired'], answer: 1, explanation: "The test of spiritual growth is not what you experience on the cushion — it's how you treat people at the grocery store. 🧺" },
    { id: 'q17', question: "Carl Sagan said science is a 'profound source of spirituality' because:", options: ['He was religious', 'Understanding the cosmos through science produces genuine awe, wonder, and humility', 'Science is a religion', 'Sagan never said this'], answer: 1, explanation: "A single Hubble Deep Field photo — 10,000 galaxies in a patch of sky the size of a grain of sand — produces authentic awe. 🔭" },
    { id: 'q18', question: "Silicon Valley's investment in psychedelic research reveals:", options: ['Tech people are drug addicts', 'The most materialistic culture on Earth is rediscovering ancient spiritual tools to address meaning-deprivation', 'Psychedelics are profitable', 'Nothing significant'], answer: 1, explanation: "Optimizing every metric except meaning leaves a void that only spiritual experience seems to fill. 💊" },
    { id: 'q19', question: "Rumi's quote 'Out beyond ideas of wrongdoing and rightdoing, there is a field' suggests:", options: ['Ethics don\'t matter', 'At the deepest spiritual level, labels and categories dissolve into direct experience of reality', 'Rumi was confused', 'Farming is spiritual'], answer: 1, explanation: "The mystics of every tradition point beyond concepts to direct, unmediated experience. 🌾" },
    { id: 'q20', question: "The healthiest approach to spirituality vs religion is probably:", options: ['Reject both', 'Choose one and condemn the other', 'Integrate both — demand genuine experience within a disciplined, community-oriented framework', 'Neither matters'], answer: 2, explanation: "Experience without structure drifts. Structure without experience dies. You need BOTH. 🤝" },
  ],

  relatedTopics: ['world_religions', 'how_religion_evolved', 'afterlife_beliefs', 'meaningful_life'],
};
