export default {
  id: 'data_science',
  title: 'Data Science',
  subtitle: 'Finding strict truth inside chaos 📊',
  emoji: '📉',
  category: 'Technology',
  accentKey: 'cyan',

  hook: {
    question: "How do credit card companies instantly know when your card has been stolen, blocking it before the thief even leaves the store? 💳",
    reveal: "Data Science! They use algorithms to map out the 'Average' geographic and spending behavior of your entire life. If a purchase suddenly occurs 500 miles away for 10x your normal spending limit, the algorithm mathematically flags it as a massive 'Deviation from the Mean' and locks the card instantly! 📈",
    emoji: '🚨',
  },

  theory: [
    { id: '1', title: 'Mean, Median, & Mode', color: '#00D4FF', bgGradient: ['#002A35', '#050A0F'], icon: '🧮', svgIcon: 'grid', content: "The absolute foundation of understanding raw data involves finding the center point. \n\n**Mean (Average):** Add everything up and divide by the total.\n**Median:** The exact physical middle number when sorted lowest to highest.\n**Mode:** The number that appears the most often.", highlight: "If Bill Gates walks into a bar with 10 broke people, the 'Average' person in that bar is instantly a billionaire! This is why averages can be mathematically dangerous! 💰" },
    { id: '2', title: 'Standard Deviation (σ)', color: '#39FF14', bgGradient: ['#0A200A', '#050A0F'], icon: '📏', svgIcon: 'target', content: "**Standard Deviation** is a mathematical formula that tells you exactly how 'spread out' your data is from the exact average. \n\nA low standard deviation means all the data is cleanly clumped perfectly together near the average. A violently high standard deviation means the data is completely wildly scattered everywhere!", highlight: "If a roller coaster has an average speed of 50mph, but a massive Standard Deviation, that means it suddenly jerks to 100mph and then stops completely. Terrifying! 🎢" },
    { id: '3', title: 'Correlation vs Causation', color: '#FFD166', bgGradient: ['#2A2A00', '#050A0F'], icon: '🔗', svgIcon: 'link', content: "This is the Golden Rule of Data Science!\n\n**Correlation:** Two completely random things happen to mathematically move at the exact same time.\n**Causation:** Thing A actually directly physically caused Thing B to happen.", highlight: "Ice cream sales and shark attacks definitively peak in the exact same month (July). They mathematically 'Correlate', but eating ice cream does NOT cause sharks to attack you! Heat causes both! 🦈" },
    { id: '4', title: 'Outliers', color: '#FF4D6D', bgGradient: ['#2A0A1A', '#050A0F'], icon: '🚨', svgIcon: 'pulse', content: "An **Outlier** is a piece of data that violently breaks the pattern by being way too high or way too low compared to everything else. \n\nOutliers physically destroy predictive algorithms and heavily skew the Mean. A massive part of a Data Scientist's job is hunting down outliers and deciding whether to delete them or study them.", highlight: "If 9 people score a 70% on a test, and 1 person scores a 0% because they slept through it, mathematically deleting the 0% gives you the 'True' class average! 🗑️" },
    { id: '5', title: 'Normal Distribution (Bell Curve)', color: '#A855F7', bgGradient: ['#1A0A2A', '#050A0F'], icon: '🔔', svgIcon: 'waves', content: "In nature, data almost always mathematically naturally organizes itself into a **Bell Curve**. \n\nIf you measure the height of 100,000 men, the vast majority explicitly cluster right in the exact middle (around 5'9\"). As you move towards extreme outliers (like a 7-foot tall giant or a 4-foot tall man), the incredibly rare numbers fiercely curve downwards to near zero.", highlight: "The Bell Curve is heavily built into the literal physics of the universe. It applies to test scores, weights, blood pressure, and even the size of apples on a tree! 🍎" },
    { id: '6', title: 'Linear Regression', color: '#FF3131', bgGradient: ['#200A0A', '#050A0F'], icon: '📈', svgIcon: 'sparkle', content: "**Linear Regression** is a predictive mathematical algorithm. \n\nYou plot a bunch of old, historical data on a graph (like house prices vs. square footage). The algorithm mathematically calculates a purely perfect 'Line of Best Fit' that slices exactly through the chaotic dots.", highlight: "By following the literal line physically off the edge of the graph, you can mathematically predict the exact price of a house that hasn't even been built yet! 🏠" },
    { id: '7', title: 'Overfitting', color: '#00D4A0', bgGradient: ['#00201A', '#050A0F'], icon: '🤯', svgIcon: 'cpu', content: "When you train a predictive mathematical model, you NEVER want it to be 100% physically perfect! This is called **Overfitting**. \n\nIf you train a model to memorize old data perfectly, capturing every tiny error and bump, it aggressively loses the ability to generalize. When you feed it New data, it completely physically crashes and fails! It \"memorized the test\" instead of learning the concepts.", highlight: "A good machine learning model explicitly ignores the tiny chaotic errors and heavily focuses purely on the broad general trend! 🧠" },
    { id: '8', title: 'Big Data (The 3 Vs)', color: '#6C5CE7', bgGradient: ['#100A20', '#050A0F'], icon: '💾', svgIcon: 'lock', content: "When a company like Google analyzes the internet, they are dealing perfectly with pure **Big Data**. Big Data is classified strictly by 3 Vs:\n1. **Volume:** Petabytes of massive information.\n2. **Velocity:** The data is violently streaming in continuously by the millisecond.\n3. **Variety:** It is chaotic mixed text, video, numbers, and garbage.", highlight: "Normal computers physically burst into flames trying to load this much data! Big Data requires thousands of computers mathematically working massively entirely in parallel! 🔥" },
    { id: '9', title: 'A/B Testing', color: '#FFB347', bgGradient: ['#201000', '#050A0F'], icon: '⚖️', svgIcon: 'cube', content: "Companies like Netflix use strict mathematical **A/B Testing** to control human behavior. \n\nThey split their users into two secret groups. Group A sees a Red 'Sign Up' button. Group B sees a Blue button. They mathematically track which color purely generates more clicks over 24 hours.", highlight: "Netflix tested 5 different thumbnail posters for 'Stranger Things' and definitively found that posters with 'Glowing Red Text' dramatically triggered more clicks! 🔴" },
    { id: '10', title: 'Data Scraping', color: '#55EFC4', bgGradient: ['#0A2010', '#050A0F'], icon: '🕷️', svgIcon: 'planet', content: "Data is the most wildly expensive digital currency on Earth. \n\nData Scientists build automated bots called 'Spiders' or 'Scrapers' that aggressively violently read thousands of Wikipedia pages or Twitter posts per second, mathematically extracting just the pure text/numbers, and cleanly saving it instantly into a massive Excel database for training AI.", highlight: "This is strictly exactly how ChatGPT was built! OpenAI scraped almost the entire massive searchable internet! 🕸️" }
  ],

  lab: {
    title: "Linear Regression Engine 📉",
    description: "Welcome to the Data Science Outlier Pipeline. Inject chaos into the scatter plot and watch algorithms fix it.",
    hint: "Use the sliders to adjust dataset Variance. Hit 'Clean Data' to forcefully purge outliers.",
    scientistModeHint: "Scientist Mode reveals explicit Standard Deviation (z-score) zones and Mean Squared Error matrices.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do 'Survivorship Bias' algorithms trick military engineers into heavily guarding the wrong parts of bomber planes? 🛩️", answer: "During WWII, engineers looked at returning planes covered in bullet holes on the wings, and armor-plated the wings. A Data Scientist pointed out: 'The planes that got shot in the Engine never returned.' They were heavily armoring the areas that were safe to get shot at! Always study the missing data! 🧠", emoji: '🎯' },
    { id: 'dyk2', question: "Why do shopping sites mathematically suggest items you actually want to buy? 🛒", answer: "They use 'Collaborative Filtering'. If Customer A buys eggs, milk, and bread, and Customer B buys eggs and milk, the algorithm mathematically predicts Customer B also wants bread, and shoves it in their face! 🍞", emoji: '💡' },
    { id: 'dyk3', question: "Why is a sample size of 5 statistically totally useless? 📉", answer: "The 'Law of Large Numbers' dictates that small groups are easily skewed by outliers. If you flip a coin 5 times, you might get 5 heads! If you completely flip it 10,000 times, the math forces it to heavily stabilize firmly at a perfect exactly 50/50 ratio! 🪙", emoji: '🎲' },
    { id: 'dyk4', question: "Why do airlines routinely purposely overbook their flights beyond physical capacity? ✈️", answer: "Algorithms actively calculate exactly how many people mathematically 'No-Show' for every specific route based on historical data. They know exactly 3 people usually physically miss flight 101, so they sell exactly 3 extra tickets to forcefully legally maximize millions in pure profit! 💵", emoji: '💺' },
    { id: 'dyk5', question: "Why do Data Scientists spend 80% of their actual job just 'cleaning' data? 🧹", answer: "Real world data is horrible. Someone types 'Twenty' instead of '20'. Someone leaves a box blank. A sensor aggressively breaks and records a temperature of -9999 degrees. If you feed garbage directly into an algorithm, the math spits out pure perfect garbage! 🗑️", emoji: '🧼' }
  ],

  quiz: [
    { id: 'q1', question: "If 10 poor people and 1 billionaire are in a room, which basic metric is terribly mathematically misleading to use?", options: ["The median value", "The mean average", "The most frequent mode", "The total range"], answer: 1, explanation: "The Mean gets violently skewed by massive outliers (like a billionaire) making the entire group look incredibly rich." },
    { id: 'q2', question: "What does a high Standard Deviation specifically indicate?", options: ["Data is tightly clustered", "Data is perfectly flat", "Data is widely spread", "The average is zero"], answer: 2, explanation: "A high deviation means high chaos and scatter!" },
    { id: 'q3', question: "What is the extreme difference between 'Correlation' and 'Causation'?", options: ["They are identical concepts", "Association versus direct cause", "Causation is always fake", "Correlation is legally prohibited"], answer: 1, explanation: "Just because ice cream sales and shark attacks rise together (correlation) doesn't mean ice cream actively causes the sharks to attack!" },
    { id: 'q4', question: "What is an 'Outlier' in a massive dataset?", options: ["A software coding bug", "Data deviating from patterns", "The exact mathematical average", "An empty data cell"], answer: 1, explanation: "An outlier is an extreme value, like an adult who is mathematically 8 feet tall." },
    { id: 'q5', question: "What physical curve naturally perfectly appears when plotting the heights of 100,000 random humans?", options: ["A straight flat line", "A standard bell curve", "A perfect round circle", "A rising staircase shape"], answer: 1, explanation: "Nature heavily heavily favors placing the vast majority precisely right into the solid mathematical center (the Bell)." },
    { id: 'q6', question: "What is Linear Regression fundamentally used for?", options: ["Deleting unnecessary files", "Predicting trends using lines", "Optimizing code execution speed", "Drawing perfect geometric circles"], answer: 1, explanation: "You fit a straight line through the past dots, and follow the exact line forward to predict." },
    { id: 'q7', question: "What does 'Overfitting' mean in Machine Learning?", options: ["The code is long", "Memorizing data without generalizing", "The hardware battery overheats", "The device screen cracks"], answer: 1, explanation: "A model must avoid perfectly memorizing exact data bumps to remain flexible." },
    { id: 'q8', question: "What does 'A/B Testing' practically allow companies to do?", options: ["Sorting alphabetized letters", "Comparing two webpage versions", "Checking device battery life", "Deleting old user data"], answer: 1, explanation: "They divide the crowd and mathematically see which version wins." },
    { id: 'q9', question: "Which is NOT one of the 3 Vs of Big Data?", options: ["Total data volume", "Data processing velocity", "Diverse data variety", "Data storage vacuum"], answer: 3, explanation: "The 3 Vs stand for Volume, Velocity, and Variety." },
    { id: 'q10', question: "How do Data Scientists gather massive datasets from the whole internet?", options: ["Typing data by hand", "Scraping websites with bots", "Asking Google for files", "Buying physical data CDs"], answer: 1, explanation: "Scraping bots mathematically pull data automatically." },
    { id: 'q11', question: "If the 'Mean' is dangerous because it is affected by outliers, what should a Data Scientist use instead?", options: ["The standard deviation", "The most frequent mode", "The middle median value", "The total data range"], answer: 2, explanation: "The Median is the exact physical middle number, so a giant outlier doesn't ruin it." },
    { id: 'q12', question: "Why is a Bell Curve called a Normal Distribution?", options: ["It represents abnormal data", "Most natural data follows it", "It rings like bells", "Scientists voted on naming"], answer: 1, explanation: "Most people cluster down the middle, making it 'Normal'." },
    { id: 'q13', question: "What defines 'Velocity' in Big Data?", options: ["The computer processor speed", "Speed of incoming data", "The constant speed light", "The local Wi-Fi speed"], answer: 1, explanation: "Big Data implies the data is arriving incredibly fast!" },
    { id: 'q14', question: "What is 'Collaborative Filtering' used for?", options: ["Filtering contaminated water", "Deleting harmful computer viruses", "Suggesting products to users", "Finding statistical data outliers"], answer: 2, explanation: "This is the algorithm Amazon uses to recommend items to you." },
    { id: 'q15', question: "A Data Scientist spends the vast majority of their time doing what?", options: ["Building complex neural networks", "Cleaning messy raw data", "Playing digital video games", "Writing abstract mathematical theory"], answer: 1, explanation: "Data must be carefully cleaned before passing it to AI." },
    { id: 'q16', question: "The 'Law of Large Numbers' states that:", options: ["Large numbers are bad", "Larger samples increase certainty", "Mathematics is inherently hard", "Only huge companies use data"], answer: 1, explanation: "The more people you test, the more accurate your average becomes." },
    { id: 'q17', question: "What does 'Survivorship Bias' mathematically teach us?", options: ["Always study the survivors", "Ignore all the survivors", "Consider missing data points", "Planes crash very often"], answer: 2, explanation: "If you only look at data that 'survived', your math is totally backward." },
    { id: 'q18', question: "If 'A' always happens right before 'B', does 'A' cause 'B'?", options: ["Yes, it absolutely does", "No, correlation isn't causation", "Only on specific Tuesdays", "Depends on the mean"], answer: 1, explanation: "They might just be correlated due to a third hidden factor." },
    { id: 'q19', question: "What is the Mode?", options: ["The middle center point", "The highest numerical value", "The most frequent number", "The calculated average value"], answer: 2, explanation: "It simply counts frequency." },
    { id: 'q20', question: "Why do airlines purposely overbook flights?", options: ["By simple human mistake", "Predicting passenger no-shows", "Having too many seats", "To maximize corporate greed"], answer: 1, explanation: "They know exactly how many no-shows happen on average." }
  ],
  relatedTopics: ['ai_machine_learning'],
};
