// ─────────────────────────────────────────────────────────
//  TOPIC: TRAUMA & PTSD (ट्रॉमा और पीटीएसडी)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'trauma',
  title: 'Trauma & PTSD',
  subtitle: 'The Body Keeps the Score 🧠⚡',
  emoji: '💔',
  category: 'Mental Health',
  accentKey: 'trauma',

  hook: {
    question: "Why does the smell of a certain perfume, or the sound of a specific song, instantly make your stomach drop and your heart race?",
    reveal: "Because trauma isn't just a 'bad memory' stored in your mind; it is an unfinished threat physically frozen in your nervous system.\n\nWhen a traumatic event occurs, the brain's filing system breaks down. Instead of being stored as a 'past event', the memory shatters into fragments of sounds, smells, and feelings. Let's look at what happens when the brain's alarm system gets stuck in the 'ON' position, and how we can finally turn it off. 🧩⏱️🚨",
    emoji: '⏱️',
  },

  theory: [
    {
      id: 'what_is_trauma',
      title: "Big 'T' vs. Little 't' 🌪️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'zap',
      svgIcon: 'alert',
      content: "**Trauma is not what happens to you; it's what happens *inside* you as a result of what happens to you.** (Dr. Gabor Maté)\n• **Big 'T' Trauma**: Life-threatening events (war, assault, car crashes).\n• **Little 't' Trauma**: Non-life-threatening but highly emotionally distressing events (bullying, emotional neglect, sudden job loss).\nBoth overwhelm the nervous system's ability to cope.",
      highlight: "Trauma is the psychological equivalent of a circuit breaker blowing out during a power surge. 🔌",
    },
    {
      id: 'the_hippocampus_failure',
      title: "A Broken Filing Cabinet 🗄️",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'archive',
      svgIcon: 'lock',
      content: "Normally, your **Hippocampus** acts as a librarian. It stamps a memory with a timestamp ('This happened in 2012') and files it away.\nDuring a traumatic event, the amygdala (alarm system) is so loud that the hippocampus shuts down completely.\nThe memory is never stamped with 'PAST'. So, when a trigger brings it up, your body reacts as if it is happening right *NOW*.",
      highlight: "PTSD is literally a disease of time. The brain cannot tell the past from the present. ⏳",
    },
    {
      id: 'triggers',
      title: "Triggers: The Invisible Landmines 💣",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'crosshair',
      svgIcon: 'target',
      content: "Because the memory was stored as raw sensory data instead of a story, **Triggers** can be anything present during the event: the smell of rain, a tone of voice, or a specific visual pattern.\nWhen you encounter the trigger, the amygdala fires instantly. The conscious brain has no idea why you are suddenly having a panic attack in the grocery store.",
      highlight: "A trigger is a sensory shortcut straight to the alarm system. 🚦",
    },
    {
      id: 'the_body_keeps_the_score',
      title: "The Body Keeps the Score 🧍‍♂️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'activity',
      svgIcon: 'leaf',
      content: "As psychiatrist Bessel van der Kolk explains, unresolved trauma gets trapped in the body's tissues and nervous system.\nSurvivors often suffer from unexplained chronic pain, autoimmune diseases, fibromyalgia, and migraines. \nYou may try to forget the event with your conscious mind, but your immune system and muscle tension remember exactly what happened.",
      highlight: "You cannot 'think' your way out of trauma, because the trauma isn't stored in the thinking part of your brain. 🧠",
    },
    {
      id: 'dissociation',
      title: "Dissociation: Leaving the Body 👻",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'cloud-off',
      svgIcon: 'eye',
      content: "When physical escape from a threat is impossible, the brain provides a psychological escape: **Dissociation**.\nIt's a heavy numbing mechanism. You might feel like you are floating above your body, that the world isn't real (Derealization), or that you aren't real (Depersonalization). \nIt's a brilliant survival mechanism during an attack, but a devastating symptom in daily life.",
      highlight: "Dissociation is the brain saying, 'This is too much to process; I am turning the cameras off.' 🎥🚫",
    },
    {
      id: 'flashbacks',
      title: "Flashbacks vs. Memories 🎞️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'film',
      svgIcon: 'star',
      content: "A bad memory is recalling that you were hurt. \nA **Flashback** is *re-experiencing* the hurt physically. During a flashback, the same exact chemicals (adrenaline/cortisol) flood the body as during the original event. Heart rate spikes, sweating begins, and the Prefrontal Cortex (logic) goes completely offline.",
      highlight: "You cannot reason with someone in a flashback; you can only ground them in the present physical space. 🎛️",
    },
    {
      id: 'complex_ptsd',
      title: "CPTSD (Death by a Thousand Cuts) 🔪",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'layers',
      svgIcon: 'alert',
      content: "**PTSD** often comes from a single, distinct event (a car crash).\n**C-PTSD (Complex PTSD)** comes from prolonged, repeated trauma over months or years, from which escape was impossible (childhood abuse, domestic violence, being a prisoner of war).\nCPTSD fundamentally alters your core identity, making it incredibly difficult to regulate emotions or trust anyone.",
      highlight: "PTSD is a torn muscle. CPTSD is a bone that grew back crooked. 🦴",
    },
    {
      id: 'hyperarousal',
      title: "Window of Tolerance 🪟",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'maximize',
      svgIcon: 'compass',
      content: "Every person has a **'Window of Tolerance'**—a zone where they can handle stress while staying calm.\nTrauma shrinks this window dramatically.\n• **Hyperarousal**: Pushed above the window (Anxious, angry, panic, fight/flight).\n• **Hypoarousal**: Pushed below the window (Numb, disconnected, exhausted, freeze/dissociate).",
      highlight: "Traumatized people rarely feel 'just okay'. They bounce between rage/panic and total numbness. 🌡️",
    },
    {
      id: 'intergenerational_trauma',
      title: "Inheriting the Scars (Epigenetics) 🧬",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'git-merge',
      svgIcon: 'users',
      content: "Can trauma be passed down? Yes. \n**Epigenetics** shows that severe trauma changes how genes are expressed in the survivor's body. These genetic markers can literally be passed down to their children and grandchildren, making the offspring highly reactive to stress, even if they never experienced the trauma themselves.",
      highlight: "The pain of your ancestors is written sideways into your DNA. 📜",
    },
    {
      id: 'emdr_therapy',
      title: "EMDR: The Brain Hacker 👁️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'eye',
      svgIcon: 'zap',
      content: "**Eye Movement Desensitization and Reprocessing (EMDR)** is a gold-standard trauma treatment.\nWhile recalling the trauma, you move your eyes rapidly back and forth (or use tapping). This mimics REM sleep, distracting the amygdala and allowing the logical brain to finally file the memory as 'IN THE PAST'.",
      highlight: "EMDR takes the intense 'heat' out of the burning memory, turning a flashback into just a bad story. 🧊",
    },
    {
      id: 'somatic_experiencing',
      title: "Somatic Experiencing 🧍‍♀️",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'wind',
      svgIcon: 'leaf',
      content: "Since trauma lives in the body, **Somatic Therapy** works bottom-up.\nInstead of talking about the event, you focus on where you feel it physically. If you wanted to run but couldn't during the event, the therapist might have you physically mimic running on a treadmill to 'complete the biological stress cycle' that was interrupted years ago.",
      highlight: "The body must feel safe before the brain can hear the words. 🧘‍♀️",
    },
    {
      id: 'post_traumatic_growth',
      title: "Post-Traumatic Growth 🌳",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'trending-up',
      svgIcon: 'heart',
      content: "While trauma destroys, the healing process can build something stronger.\n**Post-Traumatic Growth** is a psychological phenomenon where survivors experience profound positive changes after trauma: a deeper appreciation for life, vastly increased empathy, and a realization of exactly how indestructible they are.",
      highlight: "A bone that breaks often heals stronger at the fracture site. 🦾",
    },
    {
      id: 'the_shame_factor',
      title: "Trauma and Shame 🎭",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'shield-off',
      svgIcon: 'lock',
      content: "Guilt says: 'I did something bad.'\n**Shame** says: 'I *am* bad.'\nTrauma survivors almost always carry deep shame. Children who are abused will subconsciously blame themselves because believing 'I am bad' is less terrifying for a child than believing 'My parents are dangerous and the world is random.'",
      highlight: "Shame thrives in secrecy. Speaking it out loud is the only way to kill it. 🗣️",
    },
    {
      id: 'helping_a_survivor',
      title: "How to Support a Survivor 🤝",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'heart',
      svgIcon: 'users',
      content: "What NOT to do:\n🚫 Say 'Everything happens for a reason.'\n🚫 Ask for graphic details.\n🚫 Say 'You need to let it go.'\n\nWhat TO do:\n✅ Say 'I believe you. It wasn't your fault.'\n✅ Ask before touching them (hugging).\n✅ Recognize that their sudden anger/panic is their trauma, not a personal attack on you.",
      highlight: "You do not need to fix them. You just need to witness them safely. 🛋️",
    },
    {
      id: 'healing_timeline',
      title: "The Non-Linear Path 🛤️",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'map',
      svgIcon: 'compass',
      content: "Healing from trauma is not a straight line ascending to happiness.\nIt is messy. You will have two great weeks, and then a smell will trigger a 3-day panic spiral. That is not a failure; that is the 'two steps forward, one step back' rhythm of neurological rewiring.",
      highlight: "Give yourself the grace to heal at a pace that frustrates you. ⏳",
    },
  ],

  lab: {
    title: "EMDR Desensitization Protocol 👁️🏃",
    description: "Your subject's Hippocampus failed to file a traumatic memory, making it play on a constant loop in the present. You must initiate Bilateral Stimulation (moving the eyes left and right) to keep the Amygdala distracted while the memory is safely re-filed into the 'PAST' folder.",
    hint: "Keep your eyes locked on the moving target! The dual-attention task taxes working memory, forcing the brain to reduce the vividness and emotion of the memory.",
    scientistModeHint: "Neurology Mode 🧑‍🔬: Monitor Hippocampal Filing Status and Working Memory Load limiters.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do trauma survivors often have physical memory loss (Amnesia) regarding the event?", answer: "During extreme trauma, the brain releases a flood of stress hormones that act as a chemical 'kill switch' for the Hippocampus (the memory recorder). It's a biological fuse blowing out to protect your conscious mind from the horror. 🧠", emoji: '🔌' },
    { id: 'dyk2', question: "Why does trauma seemingly 'strike' when things are suddenly going well?", answer: "When you are in constant crisis, your brain represses trauma just to survive the day. But when you finally reach a safe environment (a good relationship, a stable job), the brain drops its guard and says, 'Okay, we are safe now, time to process all that backlogged trauma!' 🏡", emoji: '📦' },
    { id: 'dyk3', question: "Why do some people continuously date toxic people who treat them like their abusive parents did?", answer: "It's called 'Trauma Reenactment'. The brain hates the unknown more than it hates pain. It subconsciously seeks out familiar painful situations (like a toxic partner) in a desperate attempt to finally 'get it right' this time and heal the original wound. 🔄", emoji: '💔' },
    { id: 'dyk4', question: "Why can tetris be used as a trauma intervention?", answer: "Studies show that playing a visually demanding game like Tetris *immediately* after a traumatic event interrupts the visual consolidation of the memory. It takes up so much of the brain's processing power that the traumatic images cannot permanently burn themselves into long-term memory. 🧱", emoji: '🎮' },
    { id: 'dyk5', question: "Why do traditional 'talk therapies' sometimes fail to cure PTSD?", answer: "Because trauma is stuck in the emotional (Limbic) and survival (Brain stem) parts of the brain, which do not have language. You cannot 'logic' your way out of a survival response. You have to heal the body first. 🗣️", emoji: '🚫' },
  ],

  quiz: [
    { id: 'q1', question: "What is the key difference between a bad memory and trauma?", options: ['Trauma makes you angry', 'Trauma is stored as an active, unfinished threat in the nervous system rather than a past event', 'Bad memories go away', 'No difference'], answer: 1, explanation: "Bad memories are in the past. Trauma feels like it is happening right now. ⏳" },
    { id: 'q2', question: "Which brain structure acts as the 'filing cabinet' and fails during a traumatic event?", options: ['The Frontal Lobe', 'The Hippocampus', 'The Brain Stem', 'The Optic Nerve'], answer: 1, explanation: "Because the Hippocampus shuts off, the memory is never stamped with 'Past'. 🗄️" },
    { id: 'q3', question: "What is 'Little t' trauma?", options: ['Small physical injuries', 'Highly distressing emotional events (like severe bullying or neglect) that aren\'t life-threatening but overwhelm the nervous system', 'Watching a scary movie', 'Getting a bad grade'], answer: 1, explanation: "Death is not required to overwhelm the nervous system's capacity to cope. 🌪️" },
    { id: 'q4', question: "According to Bessel van der Kolk, where does unresolved trauma live?", options: ['In the subconscious mind entirely', 'Trapped within the physical body, the nervous system, and muscles (The Body Keeps the Score)', 'In the frontal lobe', 'In dreams'], answer: 1, explanation: "This is why trauma survivors suffer from severe, unexplained physical health issues. 🧍‍♂️" },
    { id: 'q5', question: "What is a 'Trigger'?", options: ['A sudden burst of energy', 'A sensory shortcut (smell, sound) that instantly reactivates the unfiled traumatic memory as if it is happening now', 'A type of gun', 'A bad mood'], answer: 1, explanation: "Triggers bypass logic, taking you instantly from the grocery store back to the warzone. 💣" },
    { id: 'q6', question: "What is the biological purpose of 'Dissociation'?", options: ['To fall asleep', 'When physical escape is impossible, the brain provides psychological escape by numbing reality to protect the mind', 'To think creatively', 'To forget names'], answer: 1, explanation: "It is essentially the brain turning off the cameras because the horror is too bright. 👻" },
    { id: 'q7', question: "How is Complex PTSD (C-PTSD) different from PTSD?", options: ['It involves mathematics', 'It results from repeated, prolonged trauma where escape was impossible (e.g., childhood abuse), altering core identity', 'It is less severe', 'It only happens to soldiers'], answer: 1, explanation: "CPTSD is death by a thousand cuts, not one single explosion. 🔪" },
    { id: 'q8', question: "What happens when someone is pushed ABOVE their 'Window of Tolerance'?", options: ['They get tired', 'They enter Hyperarousal (panic, rage, anxiety, fight/flight)', 'They sleep', 'They dissociate'], answer: 1, explanation: "Below the window is numbness; above the window is chaos. 🪟" },
    { id: 'q9', question: "What does 'Epigenetics' prove about trauma?", options: ['Trauma causes wrinkles', 'Severe trauma can alter gene expression, meaning heightened stress responses can be inherited by future generations', 'Trauma is fake', 'Trauma improves DNA'], answer: 1, explanation: "The ghosts of your grandparents' trauma can physically live in your genes. 🧬" },
    { id: 'q10', question: "How does EMDR therapy work?", options: ['Listening to music', 'Using bilateral eye movements (mimicking REM sleep) to distract the amygdala while the hippocampus finally files the memory', 'Taking a pill', 'Talking for hours'], answer: 1, explanation: "The eye movements tax the working memory, pulling the vividness out of the flashback. 👁️" },
    { id: 'q11', question: "What is the core belief resulting from 'Shame'?", options: ['I made a mistake', 'I *am* a mistake (fundamental belief of being broken or bad)', 'Other people are bad', 'I forgot something'], answer: 1, explanation: "Traumatized children take the blame to avoid recognizing their caretakers are dangerous. 🎭" },
    { id: 'q12', question: "Why is 'Somatic Experiencing' effective for trauma?", options: ['It makes you sweat', 'It treats the trauma through the body first (bottom-up), completing stress cycles that language cannot reach', 'It improves flexibility', 'It is cheap'], answer: 1, explanation: "The body must believe it is safe before the brain can relax. 🧘‍♀️" },
    { id: 'q13', question: "What is 'Post-Traumatic Growth'?", options: ['Getting taller', 'Experiencing profound positive psychological changes and deeper meaning after surviving trauma', 'Gaining weight', 'Becoming famous'], answer: 1, explanation: "You can be shattered, and the pieces can be glued back together stronger than before. 🌳" },
    { id: 'q14', question: "What is the worst thing to say to a trauma survivor?", options: ['I believe you', 'Everything happens for a reason (invalidates the horror of the trauma)', 'Would you like some tea', 'Take your time'], answer: 1, explanation: "Do not put a shiny sticker on a gaping wound. Sit with them in the mess. 🚫" },
    { id: 'q15', question: "What characterizes the 'Freeze' response during trauma?", options: ['A drop in temperature', 'The body paralyzing itself, dropping heart rate, and numbing pain when fighting or escaping is impossible', 'Screaming loudly', 'Running fast'], answer: 1, explanation: "It is an involuntary biological defense, not an indicator of cowardice. 🧊" },
    { id: 'q16', question: "Why do trauma symptoms sometimes appear years after the event when the survivor is finally safe?", options: ['Because they are bored', 'The brain only drops its repression defenses to process the backlog of trauma once it feels the environment is safe enough to do so', 'Karma', 'Old age'], answer: 1, explanation: "The brain says: 'Okay, we survived. Now we must clean up the mess.' 📦" },
    { id: 'q17', question: "Playing Tetris right after a traumatic event is proven to do what?", options: ['Improve hand-eye coordination', 'Interrupt the visual consolidation of the traumatic memory, reducing future flashbacks', 'Make you forget the event', 'Increase stress'], answer: 1, explanation: "Tetris hogs the visual processing power, preventing the images from burning into long-term memory. 🧱" },
    { id: 'q18', question: "What is 'Trauma Reenactment'?", options: ['A stage play', 'Subconsciously seeking out familiar painful or abusive situations in an attempt to finally \'get it right\'', 'Acting crazy', 'Telling stories'], answer: 1, explanation: "The brain prefers the devil it knows over the heaven it doesn't. 🔄" },
    { id: 'q19', question: "Why do 'talk therapies' alone often fail severe PTSD?", options: ['It takes too long', 'The trauma is stuck in the emotional/survival parts of the brain which don\'t communicate via language', 'Therapists are bad', 'It is too expensive'], answer: 1, explanation: "You cannot reason with the amygdala using language. 🗣️" },
    { id: 'q20', question: "What is a flashback?", options: ['A bad thought', 'Re-experiencing the traumatic event with the exact same physical flood of chemicals as if it is happening right now', 'A bright light', 'A type of dream'], answer: 1, explanation: "It is an involuntary time-travel back to the moment of terror. 🎞️" },
  ],

  relatedTopics: ['fear', 'anxiety', 'resilience'],
};
