export default {
  id: "stars_lifecycle",
  title: "Stars Lifecycle",
  subtitle: "The cosmic forge of the elements 🌟",
  emoji: "🌟",
  category: "Space",
  accentKey: "space",

  hook: {
    question: "Did you know that every single Oxygen atom you breathe and every Iron atom in your blood was forged inside the heart of an exploding star? 🌋",
    reveal: "It's true! The early universe had only Hydrogen and Helium. Stars are the ultimate cosmic factories—they crush simpler atoms together using massive gravity to create the building blocks of life. When these stars die in massive explosions (Supernovae), they scatter these elements across the galaxy. You are literally made of 'Stardust'! 🏛️",
    emoji: "🌋",
  },

  theory: [
    {
      id: "sl_0",
      title: "Nebulae: The Star Nurseries ☁️",
      color: "#A855F7",
      bgGradient: ["#1A0020", "#050D0A"],
      icon: "☁️",
      svgIcon: "cloud",
      content: "Stars begin as massive clouds of gas and dust called Nebulae. Gravity slowly pulls the gas together. As it compresses, it heats up until it reaches millions of degrees! \n\nOnce it's hot enough, Hydrogen atoms start slamming together to form Helium. This is **Nuclear Fusion**, and it's the 'Ignition' of a brand new star! 🔥",
      highlight: "Nebulae are the 'Maternity Wards' of the universe! 🌌",
    },
    {
      id: "sl_1",
      title: "Main Sequence: The Long Grind ☀️",
      color: "#FFD166",
      bgGradient: ["#202000", "#050D0A"],
      icon: "☀️",
      svgIcon: "sun",
      content: "This is the 'Adult' phase of a star. Our Sun is currently in this phase! \n\nThe star is in a perfect balance: Gravity wants to crush it inward, but the massive energy from Nuclear Fusion pushes outward. This balance (Hydrostatic Equilibrium) can last for billions of years! ⚖️",
      highlight: "Gravity vs. Fusion: The ultimate cosmic tug-of-war! 🏎️",
    },
    {
      id: "sl_2",
      title: "Red Giants: Running Out of Fuel 🍎",
      color: "#FF3131",
      bgGradient: ["#300A0A", "#050D0A"],
      icon: "🍎",
      svgIcon: "activity",
      content: "When a star like our Sun runs out of Hydrogen fuel in its core, it starts burning Helium. This causes the outer layers to puff out massively! \n\nAs a Red Giant, the Sun will expand so far it will swallow Mercury and Venus, and scorched Earth will be orbiting just outside its outer atmosphere! 😵",
      highlight: "Old Age makes stars 'Inflate' with power! 🎈",
    },
    {
      id: "sl_3",
      title: "White Dwarfs: The Dying Embers 🥚",
      color: "#ddcf0dff",
      bgGradient: ["#151515", "#050D0A"],
      icon: "🥚",
      svgIcon: "target",
      content: "Medium-sized stars (like our Sun) don't explode. Instead, they gently puff off their outer layers into a 'Planetary Nebula' and leave behind a glowing core the size of Earth! \n\nThis core is a White Dwarf. It's incredibly dense—one teaspoon of White Dwarf material would weigh as much as an elephant! 🐘",
      highlight: "The smoldering core of a dead star! 🕯️",
    },
    {
      id: "sl_4",
      title: "Massive Stars: The Heavyweights 🥊",
      color: "#3B82F6",
      bgGradient: ["#0A1220", "#050D0A"],
      icon: "🥊",
      svgIcon: "zap",
      content: "Stars 10x larger than our Sun live fast and die hard! They burn through their fuel incredibly quickly. \n\nBecause they have so much mass, they can forge even heavier elements like Carbon, Silicon, and finally Iron! Once they hit Iron, they can no longer produce energy, and the core collapses instantly! 💥",
      highlight: "High mass = High energy = Short life! 🏎️💨",
    },
    {
      id: "sl_5",
      title: "Supernova: The Ultimate Boom 🎆",
      color: "#EF4444",
      bgGradient: ["#300A10", "#050D0A"],
      icon: "🎆",
      svgIcon: "activity",
      content: "This is the most violent event in the universe! When a massive star collapses, it rebounds in a titanic explosion that can outshine an entire galaxy for weeks! \n\nIn these seconds of intense heat and pressure, the star creates all the rarest elements like Gold, Silver, and Uranium and blasts them into space! 💎",
      highlight: "The universe's element-scattering explosion! 🎇",
    },
    {
      id: "sl_6",
      title: "Neutron Stars: Density Kings ⚛️",
      color: "#6366F1",
      bgGradient: ["#100A20", "#050D0A"],
      icon: "⚛️",
      svgIcon: "grid",
      content: "If the collapsing core of a supernova is heavy enough, it crushes all its atoms into neutrons! \n\nA Neutron Star is only about 20 km wide but weighs more than twice the Sun! They spin hundreds of times per second (Pulsars) and are the densest objects in the universe you can actually see! 🌪️",
      highlight: "A star crushed into a city-sized city! 🏢",
    },
    {
      id: "sl_7",
      title: "Black Holes: The Final Exit 🕳️",
      color: "#000000",
      bgGradient: ["#000000", "#050D0A"],
      icon: "🕳️",
      svgIcon: "blackhole",
      content: "If the remaining core is MORE than 3x the mass of the Sun, NOTHING can stop the collapse. Not even neutron pressure! \n\nGravity wins completely, crushing the core down to a mathematical point (Singularity). The gravity is so strong even light can't escape. This is a Black Hole! 🌑",
      highlight: "The place where the laws of physics break down! 🏛️",
    },
    {
      id: "sl_8",
      title: "The H-R Diagram 📈",
      color: "#10B981",
      bgGradient: ["#0A2010", "#050D0A"],
      icon: "📈",
      svgIcon: "layers",
      content: "Scientists track stars using the Hertzsprung-Russell diagram. It plots a star's brightness against its temperature! \n\nMost stars fall along a line called the 'Main Sequence.' By looking at where a star sits on this map, we can predict exactly when and how it will die! 🔭",
      highlight: "The GPS for stellar destiny! 🗺️",
    },
    {
      id: "sl_9",
      title: "Stellar Nucleosynthesis 🧪",
      color: "#EC4899",
      bgGradient: ["#200A15", "#050D0A"],
      icon: "🧪",
      svgIcon: "flask",
      content: "This is the 'Art of making atoms.' Stars fuse Hydrogen into Helium → Helium into Carbon → Carbon into Neon... and so on. \n\nEach step releases less energy until Iron. Iron is the 'Death' of a star because fusing it REQUIRES energy instead of giving it. The star's engine simply stalls! 🛑",
      highlight: "Stars are the ultimate alchemists! 🧞",
    },
  ],

  lab: {
    title: "Stellar Forge 🌟",
    description: "Welcome to the Cosmic Nursery. Set the initial mass of your Protostar and fast-forward through billions of years. Will your star end as a peaceful White Dwarf or a terrifying Black Hole?",
    hint: "Try setting the mass to 25.0 Solar Masses to trigger a Supernova!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time H-R Diagram coordinates (Luminosity vs Temperature) and core element progression.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why the Sun is yellow? ☀️",
      answer: "Temperature! Our Sun is about 5,500°C. Objects at that temperature glow most strongly in the green-yellow part of the light spectrum. Cooler stars are Red, and much hotter stars are Blue! 🌡️",
      emoji: "🌡️",
    },
    {
      id: "dyk2",
      question: "Do you know why stars twinkle? ✨",
      answer: "They don't! Space is vacuum. What you see is 'Atmospheric Turbulence.' Earth's air aggressively bends the star's pin-point light, making it look like it's dancing! 🌬️",
      emoji: "🌬️",
    },
    {
      id: "dyk3",
      question: "Do you know where the gold in your jewelry came from? 💍",
      answer: "Supernovae! The massive energy needed to forge gold atoms only exists for a few seconds during the final collapse of a heavy star! 💥",
      emoji: "💥",
    },
    {
      id: "dyk4",
      question: "Do you know what 'Pulsars' are? 📻",
      answer: "Spinning Neutron Stars! They shoot beams of radiation from their poles like cosmic lighthouses. Some spin faster than a kitchen blender! 🌪️",
      emoji: "🌪️",
    },
    {
      id: "dyk5",
      question: "Do you know if the Sun will ever become a Black Hole? 🕳️",
      answer: "Nope! It is too small. It doesn't have enough gravity to overcome electron pressure. It's destined to end as a peaceful White Dwarf! 🥚",
      emoji: "🥚",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What are the massive clouds of gas where stars are born?",
      options: ["Galaxies", "Nebulae", "Comets", "Asteroids"],
      answer: 1,
      explanation: "Nebulae are the cosmic dust and gas 'nurseries' for new stars! ☁️",
    },
    {
      id: "q2",
      question: "What is the primary fuel for a young star?",
      options: ["Gold", "Oxygen", "Hydrogen", "Carbon"],
      answer: 2,
      explanation: "Stars start by fusing Hydrogen into Helium! ⛽",
    },
    {
      id: "q3",
      question: "The 'Adult' phase of a star is called the...",
      options: ["Red Giant", "Main Sequence", "White Dwarf", "Supernova"],
      answer: 1,
      explanation: "This is where stars spend most of their lives in perfect balance! ☀️",
    },
    {
      id: "q4",
      question: "Which force pulls the gas together to form a star?",
      options: ["Magnetism", "Gravity", "Electricity", "Wind"],
      answer: 1,
      explanation: "Gravity is the 'Builder' that pulls everything together! 🏗️",
    },
    {
      id: "q5",
      question: "What happens when a star runs out of fuel and expands massively?",
      options: ["It becomes a White Dwarf", "It becomes a Red Giant", "It turns into a Planet", "It disappears"],
      answer: 1,
      explanation: "A star expands significantly in its old age! 🍎",
    },
    {
      id: "q6",
      question: "What will our Sun eventually end its life as?",
      options: ["Black Hole", "Neutron Star", "White Dwarf", "Supernova"],
      answer: 2,
      explanation: "Medium stars like the Sun end as small, dense White Dwarfs! 🥚",
    },
    {
      id: "q7",
      question: "Supernovae only happen to...",
      options: ["Small stars", "Medium stars", "Massive stars", "All stars"],
      answer: 2,
      explanation: "Only heavyweights (10x Sun mass) have the gravity to go Supernova! 🥊",
    },
    {
      id: "q8",
      question: "What is the densest object in the universe?",
      options: ["Sun", "Neutron Star", "Earth", "Nebula"],
      answer: 1,
      explanation: "A teaspoon of a Neutron Star would weigh billions of tons! ⚛️",
    },
    {
      id: "q9",
      question: "What lies at the center of a Black Hole?",
      options: ["A Sun", "A vacuum", "A Singularity", "A white dwarf"],
      answer: 2,
      explanation: "A point of infinite density where physics as we know it ends! 🕳️",
    },
    {
      id: "q10",
      question: "Which element is the 'Death' of a massive star's fusion?",
      options: ["Carbon", "Helium", "Iron", "Oxygen"],
      answer: 2,
      explanation: "Fusing Iron consumes energy instead of releasing it, causing collapse! 🛑",
    },
    {
      id: "q11",
      question: "What diagram plots star temperature vs brightness?",
      options: ["Einstein Plot", "H-R Diagram", "Hubble Chart", "Galactic Map"],
      answer: 1,
      explanation: "The Hertzsprung-Russell diagram is the master map of stellar life! 📈",
    },
    {
      id: "q12",
      question: "Hotter stars tend to be which color?",
      options: ["Red", "Blue", "Yellow", "Orange"],
      answer: 1,
      explanation: "Blue stars are the hottest; Red are the relatively 'coolest'! 🌡️",
    },
    {
      id: "q13",
      question: "Stellar Nucleosynthesis is the process of creating...",
      options: ["Planets", "Life", "Heavier Elements", "Black Holes"],
      answer: 2,
      explanation: "It's the forging of atoms inside the stellar furnace! 🧪",
    },
    {
      id: "q14",
      question: "Planetary Nebulae are formed when...",
      options: ["Planets explode", "A star is born", "A medium star sheds its outer layers", "Black holes merge"],
      answer: 2,
      explanation: "It's the beautiful final 'breath' of a Sun-like star! 💨",
    },
    {
      id: "q15",
      question: "What keeps a star from collapsing while it's 'alive'?",
      options: ["Magnetic Force", "Outward Fusion Pressure", "Centrifugal Motion", "Solid Core"],
      answer: 1,
      explanation: "Nuclear fusion prevents gravity from crushing the star! 🏎️",
    },
    {
      id: "q16",
      question: "A 'Pulsar' is a rapidly spinning...",
      options: ["White Dwarf", "Neutron Star", "Black Hole", "Red Giant"],
      answer: 1,
      explanation: "They pulse like lighthouses across the cosmos! 🚨",
    },
    {
      id: "q17",
      question: "What is the 'Event Horizon'?",
      options: ["The birth of a star", "The edge of a black hole", "The end of a galaxy", "A solar flare"],
      answer: 1,
      explanation: "The 'Point of No Return' where even light is trapped! 🌒",
    },
    {
      id: "q18",
      question: "Most stars spend 90% of their life in which phase?",
      options: ["Red Giant", "Supernova", "Main Sequence", "Protostar"],
      answer: 2,
      explanation: "Main Sequence is the 'stable middle-age' for stars! ⏳",
    },
    {
      id: "q19",
      question: "Where did the heaviest elements in your body come from?",
      options: ["Big Bang", "The Earth", "Star Explosions (Supernova)", "Volcanoes"],
      answer: 2,
      explanation: "You are truly legacy stardust! 🌟",
    },
    {
      id: "q20",
      question: "The Sun is about how far through its life cycle?",
      options: ["Finished", "Starting", "Halfway", "Almost end"],
      answer: 2,
      explanation: "The Sun is roughly 4.6 billion years old, with 5 billion more to go! 🕶️",
    },
  ],

  relatedTopics: ["solar_system", "gravity", "big_bang"],
};
