// ─────────────────────────────────────────────────────────
//  TOPIC: MASTERY & EXPERTISE
//  Category: Personal Development
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'mastery_expertise',
  title: 'Mastery & Expertise',
  subtitle: 'How to become exceptionally good at anything 🌟',
  emoji: '🌟',
  category: 'Personal Development',
  accentKey: 'mastery_expertise',

  hook: {
    question: "Why do some people drive a car for 30 years, putting in thousands of hours behind the wheel, but never get any better at it than they were in year two?",
    reveal: "Because experience does NOT equal expertise! The human brain is lazy; once a task becomes 'good enough' to survive, it shifts the process to the basal ganglia (autopilot) to save energy. You stop paying attention, and your skill level permanently flatlines. \n\nTo actually achieve world-class mastery, you must violently force yourself out of autopilot and step back into the terrifying 'struggle zone'. 🧗‍♂️🧠",
    emoji: '💭',
  },

  theory: [
    {
      id: 'deliberate_practice',
      title: "Deliberate Practice 🎯",
      color: '#6C63FF',
      bgGradient: ['#1A1040', '#0D0D1A'],
      icon: 'target',
      svgIcon: 'zap',
      content: "Mindless repetition makes you permanent, not perfect.\n\nCoined by psychologist K. Anders Ericsson, **Deliberate Practice** is a highly structured activity designed specifically to improve performance. It requires:\n1. A well-defined, extremely specific micro-goal (not 'play guitar better', but 'perfect the C-to-F chord transition at 120 bpm').\n2. Intense, excruciating focus.\n3. Reaching just slightly beyond your current abilities.",
      highlight: "If practice feels comfortable and easy, you aren't improving. Growth only happens in the struggle. 💪",
    },
    {
      id: 'the_10000_hour_rule',
      title: "The 10,000 Hour Myth ⏱️",
      color: '#00E5A0',
      bgGradient: ['#0A2620', '#0D0D1A'],
      icon: 'clock',
      svgIcon: 'chart',
      content: "Malcolm Gladwell popularized the idea that it takes 10,000 hours to become a world-class expert. But researchers heavily criticize this oversimplification!\n\n10,000 hours of playing casual tennis with a friend will just make you a very experienced amateur. \n10,000 hours of *deliberate practice* under the watchful eye of a coach correcting your specific flaws makes you Serena Williams. \n\n**The quality of hours matters exponentially more than the quantity.**",
      highlight: "10,000 hours of mindless repetition just deeply ingrains your bad habits until they are impossible to unlearn.",
    },
    {
      id: 'feedback_loops',
      title: "Immediate Feedback Loops 🔄",
      color: '#FF9F1C',
      bgGradient: ['#2A1A00', '#0D0D1A'],
      icon: 'refresh',
      svgIcon: 'bolt',
      content: "Imagine trying to learn to shoot a basketball in pitch darkness. You throw the ball, but you never see where it lands or hear if it hits the net. Without seeing the result, you can't adjust your aim! 🏀🌑\n\nThe fastest learners have the tightest possible feedback loops. \n• Bad feedback: Waiting 2 weeks to get a graded essay back.\n• Good feedback: A chess engine telling you your move was a blunder 0.5 seconds after you play it.\n\nSeek out mentors or software that expose your errors instantly.",
      highlight: "Expertise accelerates exponentially when feedback is instantaneous and ruthlessly objective. ⏱️",
    },
    {
      id: 'plateau',
      title: "Escaping the OK-Plateau ⛰️",
      color: '#FFE66D',
      bgGradient: ['#2A260A', '#0D0D1A'],
      icon: 'trending-up',
      svgIcon: 'planet',
      content: "Everyone hits a plateau where progress completely stops. This happens because your brain has 'chunked' the skill into an automated routine.\n\nTo break the plateau, you must break the automation:\n1. Deconstruct the skill into micro-components.\n2. Identify the specific bottleneck holding you back.\n3. Design strange, novel drills that isolate and attack *only* that weak point (e.g., a typist covering their eyes, or a pianist playing with one hand tied behind their back).",
      highlight: "A plateau is simply your brain telling you: 'I can do this on autopilot now.' Turn autopilot off.",
    },
    {
      id: 'growth_mindset',
      title: "The Growth Mindset 🌱",
      color: '#FF6B9D',
      bgGradient: ['#2A0A1A', '#0D0D1A'],
      icon: 'leaf',
      svgIcon: 'heart',
      content: "Stanford psychologist Carol Dweck discovered two foundational mindsets that dictate human achievement:\n• **Fixed Mindset:** Believes talent is genetic ('I am just not a math person'). Views failure as defining their identity. Avoids challenges to look 'smart'.\n• **Growth Mindset:** Believes abilities are built like muscles ('I am not good at math *yet*'). Views failure purely as data for the next attempt. Actively seeks out difficult challenges.",
      highlight: "'Yet' is the most dangerous, powerful word in the master's vocabulary.",
    },
    {
      id: 'flow_state',
      title: "The Flow State 🌊",
      color: '#00D4FF',
      bgGradient: ['#001A20', '#0D0D1A'],
      icon: 'wave',
      svgIcon: 'shield',
      content: "Mihaly Csikszentmihalyi coined 'Flow'—the psychological state of complete absorption in an activity. You lose your sense of time, hunger, and ego.\n\nFlow ONLY occurs in a very specific channel: when the **Challenge Level** perfectly matches your **Current Skill Level**.\n• If Challenge > Skill = Severe Anxiety.\n• If Challenge < Skill = Extreme Boredom.\n\nMasters constantly adjust the difficulty of their practice to stay perfectly balanced on the razor's edge of Flow.",
      highlight: "Flow is where human potential peaks. Too easy = Boredom. Too hard = Panic.",
    },
    {
      id: 'mental_models',
      title: "Mental Representations 🧩",
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#0D0D1A'],
      icon: 'puzzle',
      svgIcon: 'grid',
      content: "A beginner looks at a car engine and sees a chaotic jumble of 1,000 random metal parts. A master mechanic looks at the exact same engine and sees just 4 distinct, interacting systems.\n\nThis is a **Mental Representation**. Experts do not have faster eyes or better raw memory; they have built deeply sophisticated, interconnected webs of knowledge in their brains that allow them to 'chunk' massive amounts of data instantly.",
      highlight: "Expertise is not about knowing more facts; it's about seeing how the facts connect. 🕸️",
    },
    {
      id: 'the_dip',
      title: "Surviving 'The Dip' 📉",
      color: '#FF4444',
      bgGradient: ['#1A0505', '#0D0D1A'],
      icon: '📉',
      svgIcon: 'alert',
      content: "Seth Godin writes about 'The Dip', the long, grueling slog between beginner's luck and true mastery.\n\nWhen you start a new skill, it's fun! You improve rapidly (the beginner phase). Then, the fun stops, the easy gains vanish, and it becomes incredibly hard work. \n\n99% of people quit in The Dip. The people who become the top 1% in the world are simply the ones who push through the agonizing boredom and frustration of The Dip.",
      highlight: "The Dip creates scarcity; the fact that it is miserable is exactly what makes the skill valuable if you survive it.",
    },
    {
      id: 'igniting_passion',
      title: "Passion Follows Progress 🔥",
      color: '#FF8C00',
      bgGradient: ['#1A0C00', '#0D0D1A'],
      icon: '🔥',
      svgIcon: 'star',
      content: "We are often told to 'follow our passion' to become great at something. Cal Newport argues the exact opposite!\n\nPassion is rarely something you just 'discover' pre-installed in your soul. Passion is usually a byproduct of becoming exceptionally good at something. As your skill grows, your impact grows, which generates intense passion. \nDon't wait for passion to strike to start working. Start working, and the passion will follow the competence.",
      highlight: "Competence creates passion. Get so good they can't ignore you. 🎸",
    },
    {
      id: 'coaching',
      title: "The Necessity of Coaches 🗣️",
      color: '#A855F7',
      bgGradient: ['#1A0830', '#0D0D1A'],
      icon: '🗣️',
      svgIcon: 'users',
      content: "Even Tiger Woods famously had swing coaches at the peak of his career when he was dominating the world. Why?\n\nBecause you cannot observe yourself objectively. Your brain suffers from extreme cognitive biases that blind you to your own fundamental errors. \nA Great Coach does three things:\n1. Breaks your automated bad habits.\n2. Provides instantaneous feedback.\n3. Pushes you into the uncomfortable zone you would avoid on your own.",
      highlight: "You cannot see the label when you are inside the jar. You need a coach.",
    },
    {
      id: 'unlearning',
      title: "The Pain of Unlearning 💥",
      color: '#FF007F',
      bgGradient: ['#1A000A', '#0D0D1A'],
      icon: '💥',
      svgIcon: 'lock',
      content: "Sometimes, progressing from a 'Good' amateur to a 'Great' professional requires breaking down your entire technique and starting over. \n\nThis is called **Unlearning**. It means your performance will actually get *worse* temporarily as you rewire your neural pathways with the correct, advanced technique.\n\nMost people refuse to do this because their ego cannot handle the temporary drop in status. Masters embrace temporary incompetence for long-term dominance.",
      highlight: "To level up, you often have to tear down the very foundation that got you this far. 🏗️",
    },
    {
      id: 'sleep_myelin',
      title: "Myelin and Sleep 🛏️",
      color: '#8A2BE2',
      bgGradient: ['#150020', '#0D0D1A'],
      icon: '🛏️',
      svgIcon: 'cloud',
      content: "Every time you practice a piano chord, a tiny electrical signal travels through the neurons in your brain. \n\nWhen you engage in deep *Deliberate Practice*, your brain wraps those specific neural axons in a white fatty tissue called **Myelin** 🧈. Myelin acts like insulation on a copper wire, increasing the speed of the electrical signal up to 100x!\nCrucially, myelin is wrapped *primarily while you sleep*. You literally physically wake up a faster, better performer than you went to bed.",
      highlight: "Practice fires the signal. Sleep builds the high-speed Myelin highway. ⚡",
    },
    {
      id: 'talent_myth',
      title: "The Myth of 'Natural Talent' 🧬",
      color: '#32CD32',
      bgGradient: ['#051A05', '#0D0D1A'],
      icon: '🧬',
      svgIcon: 'eye',
      content: "We love to label exceptional performers as 'Prodigies' or naturally 'Gifted'. It excuses us from having to do the brutal work they did. \n\nWhile genetics cap physical limits (you must be tall to play center in the NBA), almost all cognitive and artistic 'prodigies' share a similar background: they were exposed to intense, high-quality, deliberate practice environments from an extremely early age (like Mozart's tyrannical father).",
      highlight: "Calling someone 'naturally gifted' is the greatest insult to the 10,000 hours they bled in the dark. 🩸",
    },
    {
      id: 'micro_habits',
      title: "The Aggregation of Marginal Gains 📈",
      color: '#00FA9A',
      bgGradient: ['#001A0D', '#0D0D1A'],
      icon: '📈',
      svgIcon: 'chart',
      content: "In 2003, British Cycling was the laughingstock of the sports world. Then Sir Dave Brailsford took over with one philosophy: **Improve every single detail by 1%**.\n\nThey redesigned the bike seats, tested massage gels, painted the inside of the truck white to spot dust, and even found the best pillows for athletes to sleep on. \nThese tiny 1% improvements compounded, and within 10 years, they won 178 world championships and 5 Tour de France victories! 🚴‍♂️🏆",
      highlight: "Don't look for one 50% improvement. Look for fifty 1% improvements.",
    },
    {
      id: 'obsession',
      title: "The Burden of Obsession 🌌",
      color: '#FFFFFF',
      bgGradient: ['#1A1A1A', '#0D0D1A'],
      icon: '🌌',
      svgIcon: 'target',
      content: "Ultimate mastery demands sacrifices that most sane people are unwilling to make.\n\nWorld-class experts live asymmetric lives. They often sacrifice relationships, health, and a 'balanced' life to achieve god-like status in one extremely narrow domain. \n\nYou must ask yourself: Do you actually want to be the best in the world, or do you just want to be *good enough* to enjoy it? Both are valid, but the price of the former is everything you have.",
      highlight: "Balance is the enemy of extreme mastery. Choose your sacrifices. ⚖️",
    },
  ],

  lab: {
    title: "10,000 Hour Gauntlet 🥊🧪",
    description: "You are an aspiring grandmaster. The clock is ticking! Manage your 'Difficulty' and 'Focus' levels in real-time. Hit the 'Flow Zone' to skyrocket your skill points, but watch out: high difficulty without focus leads to intense Frustration and Burnout! Can you break out of the Amateur Plateau?",
    hint: "To maintain exponential growth, you must constantly increase the Difficulty as your Skill rises! If Difficulty stays low, you plateau instantly.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks raw Myelin Myelination metrics, Flow-State Deltas, and Cognitive Overload threshold limits.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why chess grandmasters can memorize a chessboard instantly? ♟️", answer: "It's a process called 'Chunking'. They don't see 32 individual pieces; their brain recognizes large structural patterns—'chunks'—built from thousands of hours of studying tactics. If you place the pieces randomly (not following chess rules), their memory is no better than a beginner! 🧩", emoji: '🧠' },
    { id: 'dyk2', question: "Do you know why babies can learn languages but adults struggle? 🍼", answer: "Neuroplasticity! A baby's brain has wildly chaotic, unpruned neural networks, allowing them to absorb any phoneme effortlessly. As we age, our brains 'prune' the connections we don't use to become hyper-efficient at our native language. Adults must use sheer, agonizing deliberate practice to force adult neuroplasticity. 🗣️", emoji: '👶' },
    { id: 'dyk3', question: "Do you know why top musicians practice slower than amateurs? 🎻", answer: "Amateurs rush through pieces at full speed, glossing over mistakes, which permanently 'bakes in' microscopic errors into their Myelin. Professionals practice at a grueling, agonizingly slow pace where mistake-free perfection is possible, ensuring that only flawless neural pathways are insulated. ⏳", emoji: '🎶' },
    { id: 'dyk4', question: "Do you know why London Taxi drivers actually have physically larger brains? 🚕", answer: "Before GPS, London cabbies had to pass 'The Knowledge', memorizing 25,000 streets blindly. MRI scans revealed that their posterior hippocampi (the brain's spatial map center) were physically engorged and significantly thicker than normal humans! The brain literally grows like a muscle in response to extreme practice. 🗺️", emoji: '🧠' },
    { id: 'dyk5', question: "Do you know why reading 100 books on golf won't make you Tiger Woods? 🏌️‍♂️", answer: "Procedural vs. Declarative Memory. Reading books stores facts in your Declarative memory (hippocampus). Hitting a golf ball requires Procedural memory (cerebellum/basal ganglia). You cannot transfer knowledge between these two systems without massive physical repetition. 📚", emoji: '❌' },
    { id: 'dyk6', question: "Do you know why the best athletes choke under extreme pressure? 😰", answer: "Explicit Monitoring! When highly stressed, athletes stop relying on their perfectly automated basal ganglia (autopilot) and try to 'consciously' control their movements using the prefrontal cortex. This introduces lag and clumsiness into a process that should be fluid. They literally overthink themselves into failure! 📉", emoji: '🏌️' },
    { id: 'dyk7', question: "Do you know why we feel 'in the zone' (Flow) during video games but rarely at work? 🎮", answer: "Video games perfectly ride the 'Edge of Flow' by utilizing dynamic difficulty scaling. As your skill goes up, the enemies get exactly that much harder. Conversely, modern office work is either crushing with impossible stress or mind-numbing with repetitive boredom, missing the core requirement for Flow. ⚖️", emoji: '🌊' },
    { id: 'dyk8', question: "Do you know why you cannot tickle yourself? 🪶", answer: "Your cerebellum monitors your own motor intentions and immediately predicts the sensory consequence. Because it perfectly predicts the touch, it cancels the sensation out! This same prediction-loop is what experts use to instantly correct a golf swing or a piano strike a millisecond *before* it happens. 🤖", emoji: '🧠' },
    { id: 'dyk9', question: "Do you know why the 'Sophomore Slump' happens? 📉", answer: "A beginner achieves rapid success and gets praised for being 'talented'. This praise forces them into a Fixed Mindset—they become terrified of failing and losing their 'talented' label. So, they stop taking risks, refuse to dive into the 'Dip' of hard, ugly practice, and inevitably plateau. 🎭", emoji: '🔒' },
    { id: 'dyk10', question: "Do you know why visually visualizing a free-throw literally improves your shot? 🏀", answer: "Mental simulation triggers the exact same motor neurons in the cortex as actually doing it! While it doesn't build physical muscle, it actively thickens the myelin sheath on the neural circuits for that movement. The brain cannot perfectly tell the difference between vivid imagination and reality! 👁️", emoji: '⚡' },
  ],

  quiz: [
    { id: 'q1', question: "What is the critical failure of the popular '10,000 Hour Rule'?", options: ['It takes 20,000 hours', 'It ignores the quality and type of practice', 'Only children can achieve it', 'Humans cannot focus for 10,000 hours'], answer: 1, explanation: "10k hours of bad practice just makes you a world champion of bad habits! Deliberate Practice is required. ⏱️" },
    { id: 'q2', question: "Deliberate Practice requires you to constantly operate in...", options: ['The comfortable autopilot zone', 'The zone of complete relaxation', 'The struggle zone, slightly beyond your current abilities', 'The panic zone'], answer: 2, explanation: "Growth only occurs at the absolute edges of your current abilities. If it's easy, you aren't growing. 💪" },
    { id: 'q3', question: "What biological substance wraps around heavily used neural pathways to make them lightning fast?", options: ['Cortisol', 'Melatonin', 'Myelin', 'Adrenaline'], answer: 2, explanation: "Myelin is the brain's fatty insulation that speeds up electrical signals by 100x! 🧈⚡" },
    { id: 'q4', question: "An 'OK-Plateau' occurs when:", options: ['You reach the absolute physical limit of the human body', 'Your brain shifts a skill to the basal ganglia (autopilot) to save energy', 'You get too old to learn', 'You run out of passion'], answer: 1, explanation: "Once you are 'good enough' to survive, the brain automates the skill and stops actively improving it. ⛰️" },
    { id: 'q5', question: "A person with a 'Fixed Mindset':", options: ['Loves challenging puzzles', 'Believes abilities are built like muscles', 'Avoids failure at all costs because it threatens their identity as being smart', 'Thrives in deliberate practice'], answer: 2, explanation: "Fixed mindsets fear failure because they believe their abilities are genetically 'fixed' and immutable. 🎭" },
    { id: 'q6', question: "The 'Flow State' occurs ONLY when:", options: ['You are deeply relaxed and resting', 'Challenge level perfectly matches your current Skill level', 'The challenge is impossibly hard', 'You are heavily caffeinated'], answer: 1, explanation: "Flow sits on the razor's edge between anxiety (too hard) and boredom (too easy). 🌊" },
    { id: 'q7', question: "Why do expert mechanics or chess players seem to 'see' things faster?", options: ['They have better optical vision', 'They have higher IQs', 'They have built sophisticated Mental Representations (chunking)', 'They use performance enhancing drugs'], answer: 2, explanation: "They don't see 1,000 random pieces; their brain sees 4 connected patterns. 🧩" },
    { id: 'q8', question: "What is Seth Godin's 'The Dip'?", options: ['The drop in blood sugar after studying', 'The brutal, boring slog between beginner gains and true mastery where most people quit', 'A sleep cycle', 'A type of fitness exercise'], answer: 1, explanation: "The Dip acts as a filter. Surviving the agonizing middle phase is what makes the final skill valuable. 📉" },
    { id: 'q9', question: "Cal Newport argues that 'Passion' is usually:", options: ['Pre-installed in your soul at birth', 'A byproduct of becoming exceptionally competent at something', 'An illusion', 'Required before you start practicing'], answer: 1, explanation: "Don't wait for passion. Start working, get insanely good, and the passion will naturally follow the extreme competence! 🔥" },
    { id: 'q10', question: "Why did Tiger Woods need a coach at his absolute peak?", options: ['To carry his bags', 'Because cognitive biases prevent you from seeing your own fundamental errors objectively', 'For moral support', 'It was required by law'], answer: 1, explanation: "You cannot see the label from inside the jar. An objective, ruthless outside perspective is always required for mastery. 🗣️" },
    { id: 'q11', question: "The process of purposefully breaking down your current technique to rebuild a better one is called:", options: ['Unlearning', 'Forgetting', 'Brainwashing', 'The Flow State'], answer: 0, explanation: "Unlearning is agonizing because your performance temporarily gets much worse, bruising your ego. 🏗️" },
    { id: 'q12', question: "When are your neural pathways primarily wrapped in Myelin?", options: ['While drinking coffee', 'While taking an exam', 'While you are engaged in Deep Sleep', 'While watching TV'], answer: 2, explanation: "Practice fires the signal; sleep physically builds the high-speed Myelin highway. 🛌" },
    { id: 'q13', question: "Why do adults struggle to learn new languages compared to babies?", options: ['Their vocal cords harden', 'Adult brains have pruned unused pathways, requiring agonizing deliberate practice to force neuroplasticity', 'Adults are lazier', 'Babies have larger brains'], answer: 1, explanation: "Adults don't have the chaotic, sponge-like open networks of an infant; we must manually force rewiring. 🧠" },
    { id: 'q14', question: "Why did London Taxi drivers develop physically thicker hippocampi?", options: ['It was genetic', 'Driving causes brain swelling', 'Intense memorization of 25,000 streets forced physical structural changes in the brain', 'From talking to passengers'], answer: 2, explanation: "Extreme deliberate practice literally forces the brain to grow like a weightlifter's muscle! 🚕" },
    { id: 'q15', question: "Choking under pressure happens when an expert:", options: ['Forgets the rules', 'Abandons their automated basal ganglia and tries to consciously overthink their movements using the prefrontal cortex', 'Is improperly hydrated', 'Lacks passion'], answer: 1, explanation: "Conscious thought is slow and clunky. Flow is fast and automated. Stress forces you out of Flow! 😰" },
    { id: 'q16', question: "The philosophy of 'Aggregation of Marginal Gains' (British Cycling) focuses on:", options: ['Finding one massive 50% improvement', 'Steroids', 'Improving every single tiny detail by 1%', 'Riding faster'], answer: 2, explanation: "Hundreds of tiny 1% optimizations compound into unbeatable world-dominating performance. 📈" },
    { id: 'q17', question: "Why do 'prodigies' appear naturally gifted?", options: ['They are aliens', 'They were exposed to intense, high-quality deliberate practice from an extremely early age', 'They have magic genes', 'They don\'t have to practice'], answer: 1, explanation: "Behind almost every 'genius' is a tyrant parent or coach who forced 10,000 hours of deliberate practice before puberty. 🎻" },
    { id: 'q18', question: "Why do top musicians practice at agonizingly slow speeds?", options: ['Because they are tired', 'To ensure mistake-free performance so they don\'t bake microscopic errors into their Myelin', 'To annoy the neighbors', 'To stretch their fingers'], answer: 1, explanation: "Speed is a byproduct of perfectly insulated neural pathways. Accuracy must come first. ⏳" },
    { id: 'q19', question: "Mental visualization (like visualizing a free throw) works because:", options: ['It builds arm muscle', 'It triggers the exact same motor neurons as reality, thickening the myelin sheath without physical movement', 'It uses magic', 'It scares the opponent'], answer: 1, explanation: "The brain cannot perfectly distinguish between vivid mental simulation and physical action! 👁️" },
    { id: 'q20', question: "Ultimate mastery of a narrow domain almost always requires:", options: ['Complete life balance', 'Sacrificing other areas of life (relationships, health, hobbies)', '8 hours of television', 'A high IQ'], answer: 1, explanation: "True world-class dominance requires asymmetric, obsessive sacrifice. Balance is the enemy of extremes. ⚖️" },
  ],

  relatedTopics: ['study_tips', 'brain_structure', 'cognitive_biases', 'earn_money'],
};
