export default {
  id: 'measurement_units',
  title: 'Measurement & SI Units',
  subtitle: 'How humanity agreed to count the universe 📏',
  emoji: '📏',
  category: 'Foundations',
  accentKey: 'ruler',

  hook: {
    question: "Did you know that NASA lost a $327 million Mars orbiter in 1999 because one team used metres and another used feet? 🤯",
    reveal: "The Mars Climate Orbiter — destroyed because of a unit mismatch. One engineering team used metric (Newtons), another used imperial (pound-force), and no one noticed until the spacecraft slammed into Mars. Measurement isn't just a school subject — it's the foundation of all science, engineering, trade, and medicine. A nurse who miscalculates a drug dose by a factor of 10 can kill. A bridge engineer who confuses kg and lbs builds something that collapses. Units ARE the language of the physical universe. 🚀",
    emoji: '📏',
  },

  theory: [
    { id: 'why_measure', title: 'Why Measurement? 🌍', color: '#FFD166', bgGradient: ['#2A1A00', '#05050A'], icon: '🌍', svgIcon: 'globe', content: "Measurement is the act of comparing a quantity to a **standard unit**. Without agreed standards, trade, science, and engineering would be impossible.\n\nHistorically, units were based on the human body:\n🤚 **Inch** — width of a human thumb\n🦶 **Foot** — length of a human foot (King Henry I's actual foot!)\n✋ **Cubit** — elbow to fingertip (~45cm)\n\nThe problem: whose body? Egyptian royal cubits vs ordinary cubits caused contract disputes in construction. Ancient markets were rife with fraud because merchants used non-standard weights.\n\n**The French Revolution created the metric system in 1799** — based on nature, not bodies. The metre was defined as 1/10,000,000th of the distance from the North Pole to the Equator.\n\nToday the **International System of Units (SI)** is used by 96% of the world's population in everyday life. The United States, Myanmar, and Liberia still officially use imperial — the only holdouts from the metric revolution. 🌍", highlight: "A NASA spacecraft worth $327 million was destroyed because one team used feet and another used metres! 📏" },
    { id: 'si_system', title: 'The SI System 🔢', color: '#00C8FF', bgGradient: ['#001A28', '#05050A'], icon: '🔢', svgIcon: 'ruler', content: "The **International System of Units (SI)** has 7 base units from which ALL other units are derived:\n\n📏 **metre (m)** — length\n⚖️ **kilogram (kg)** — mass\n⏱️ **second (s)** — time\n🌡️ **kelvin (K)** — temperature\n⚡ **ampere (A)** — electric current\n💡 **candela (cd)** — luminous intensity\n🧪 **mole (mol)** — amount of substance\n\n**Derived units** combine base units:\n🔵 Newton (N) = kg·m/s² (force)\n🔵 Joule (J) = kg·m²/s² (energy)\n🔵 Watt (W) = J/s = kg·m²/s³ (power)\n🔵 Pascal (Pa) = N/m² (pressure)\n🔵 Hertz (Hz) = 1/s (frequency)\n\nIn 2019, ALL SI units were redefined in terms of **fundamental physical constants** — the speed of light, Planck's constant, the elementary charge, Boltzmann's constant! Now 1 kilogram doesn't rely on a physical platinum cylinder in Paris — it's defined by the laws of physics themselves. 🌟", highlight: "In 2019, SI units were redefined using fundamental physical constants — the kilogram no longer depends on a metal cylinder in Paris! 🔢" },
    { id: 'prefixes', title: 'SI Prefixes: Scale of the Universe 🌌', color: '#06C57E', bgGradient: ['#001A10', '#05050A'], icon: '🌌', svgIcon: 'galaxy', content: "SI prefixes let us express numbers from the subatomic to the intergalactic:\n\n**Large:**\n🔴 Tera (T) = 10¹² (1 trillion) — a 1TB hard drive holds 1 trillion bytes\n🔴 Giga (G) = 10⁹ (1 billion) — a 3GHz processor does 3 billion cycles/second\n🔴 Mega (M) = 10⁶ (1 million) — 1 Megapixel = 1 million pixels\n🔴 Kilo (k) = 10³ (1 thousand) — 1km = 1,000m\n\n**Small:**\n🔵 Milli (m) = 10⁻³ — 1mm = 0.001m\n🔵 Micro (μ) = 10⁻⁶ — a human hair is 70 micrometres wide\n🔵 Nano (n) = 10⁻⁹ — DNA is 2 nanometres wide\n🔵 Pico (p) = 10⁻¹² — atomic bonds are ~150 picometres long\n\n**Mind-bending scale comparison:**\n🌌 Observable universe: ~8.8×10²⁶ metres\n🧬 DNA width: ~2×10⁻⁹ metres\n⚛️ Proton radius: ~8.8×10⁻¹⁶ metres\n\nThe ratio of the universe to a proton is 10⁴² — a 1 followed by 42 zeros! 🤯", highlight: "The ratio of the observable universe to a proton is 10⁴² — SI prefixes let scientists span this entire range! 🌌" },
    { id: 'conversion', title: 'Unit Conversion: Dimensional Analysis ⚗️', color: '#FF6B9D', bgGradient: ['#2A001A', '#05050A'], icon: '⚗️', svgIcon: 'flask', content: "**Dimensional analysis** is the systematic method for converting between units — it cannot fail if applied correctly.\n\n**The method:** Write the starting quantity, then multiply by conversion fractions (equal to 1) that cancel unwanted units.\n\n**Example:** Convert 60 miles/hour to metres/second:\n60 mi/hr × (1609 m / 1 mi) × (1 hr / 3600 s) = 26.8 m/s ✅\n\nEach fraction = 1 (numerator and denominator are equal quantities), so the VALUE doesn't change — only the UNITS do!\n\n**The deadly nurse example:** A doctor orders 0.5 mg of a drug. The nurse confuses mg (milligrams) and mL (millilitres — concentration-dependent). Wrong unit = wrong dose. Dimensional analysis would catch this — the units don't cancel correctly if you mix mass and volume!\n\n**Temperature conversion (the awkward ones):**\n🌡️ °C to K: K = °C + 273.15 (Kelvin has no negative values)\n🌡️ °C to °F: °F = (°C × 9/5) + 32\n\n**Significant figures:** You cannot gain precision through conversion! 60 miles (1 sig fig) → 100 metres, not 96,560.64 metres. False precision is as bad as imprecision! ⚗️", highlight: "Dimensional analysis is infallible — nurses who skip it can give patients 10x overdoses because they mix up mg and mL! ⚗️" },
    { id: 'precision_accuracy', title: 'Precision vs Accuracy 🎯', color: '#9B59B6', bgGradient: ['#1A0028', '#05050A'], icon: '🎯', svgIcon: 'target', content: "Two concepts students constantly confuse — and they are completely different!\n\n**Accuracy** — how close a measurement is to the TRUE value\n**Precision** — how close REPEATED measurements are to EACH OTHER\n\n**The dartboard analogy:**\n🎯 Accurate + Precise = Darts clustered around the bullseye ✅\n🎯 Precise but not accurate = Darts tightly clustered but far from bullseye ❌\n🎯 Accurate but not precise = Darts scattered around the bullseye ❌\n🎯 Neither = Darts all over the place ❌\n\n**Types of error:**\n🔴 **Random error** — unpredictable fluctuations; reduced by repeating and averaging (e.g. reaction time variation)\n🔴 **Systematic error** — consistent offset in one direction; not reduced by repeating (e.g. a scale that always reads 0.3g too heavy)\n\n**Resolution vs precision:** A ruler showing mm has RESOLUTION of 1mm (smallest graduation). But human reading error means PRECISION is typically ±0.5mm.\n\n**Measuring uncertainty:** All measurements have uncertainty. 4.25 ± 0.05 cm tells you both the value AND how much you trust it. Reporting without uncertainty is misleading! 📏", highlight: "Precision = reproducibility. Accuracy = correctness. You can be precise but totally wrong, or accurate but inconsistent! 🎯" },
    { id: 'scientific_notation', title: 'Scientific Notation ✏️', color: '#3498DB', bgGradient: ['#001018', '#05050A'], icon: '✏️', svgIcon: 'book', content: "**Scientific notation** expresses very large or small numbers as a × 10ⁿ where 1 ≤ a < 10.\n\n**Why it matters:**\n🌌 Distance to Andromeda: 2,537,000,000,000,000,000,000 m → 2.537×10²¹ m\n⚛️ Proton mass: 0.00000000000000000000000000167 kg → 1.67×10⁻²⁷ kg\n\n**Converting to scientific notation:**\n1) Move decimal until you have a number from 1-9.99\n2) Count decimal places moved = exponent\n3) Right moves = positive; Left moves = negative\n\n**Calculator EE button:** 6.02 × 10²³ → type '6.02 EE 23' (never type '6.02 × 10 ^ 23' — causes errors!)\n\n**Avogadro's Number: 6.022×10²³**\nThe number of atoms in exactly 12g of Carbon-12. If you had 6.022×10²³ grains of sand, they would fill the Pacific Ocean 100 times! 🏖️\n\n**Order of magnitude** — comparing by powers of 10:\nThe universe is 10⁴² times bigger than a proton (42 orders of magnitude)\nThe difference between a bacterium and a whale is 'only' 11 orders of magnitude! 🐋", highlight: "Avogadro's number (6.022×10²³) grains of sand would fill the Pacific Ocean 100 times — scientific notation makes this thinkable! ✏️" },
    { id: 'measuring_instruments', title: 'Measuring Instruments 🔭', color: '#E67E22', bgGradient: ['#2A1000', '#05050A'], icon: '🔭', svgIcon: 'microscope', content: "Each instrument is designed to minimise a specific type of uncertainty:\n\n**Length:**\n📏 Ruler/Tape: ±0.5mm resolution\n📐 Vernier calliper: ±0.02mm (the extra scale lets you read fractions of millimetres)\n🔩 Micrometer screw gauge: ±0.001mm (reads to a micrometre!)\n\n**Mass:**\n⚖️ Balance: ±0.1g (general lab use)\n⚖️ Analytical balance: ±0.0001g (pharmaceutical, analytical chemistry)\n\n**Volume:**\n🧪 Beaker: ±5% (approximate only, for heating)\n🧪 Measuring cylinder: ±1% (note the **meniscus** — read at the bottom!)\n🧪 Burette: ±0.05mL (for precise titration in chemistry)\n🧪 Micropipette: ±0.5% (DNA/biology — measures microlitres!)\n\n**Temperature:**\n🌡️ Mercury thermometer: ±0.5°C\n🌡️ Digital thermocouple: ±0.1°C\n🌡️ Infrared thermometer: ±1°C (non-contact; used in COVID screening)\n\n**Calibration** — comparing your instrument against a known standard regularly. A thermometer in 100°C boiling water that reads 99.5°C has a +0.5°C systematic error. All precision measurements require periodic calibration! ⚙️", highlight: "A micropipette measures volumes to ±0.5% — critical for DNA experiments where 0.1μL too much can ruin a PCR result! 🔭" },
    { id: 'time', title: 'Measuring Time: The Atomic Clock ⏱️', color: '#1ABC9C', bgGradient: ['#001A14', '#05050A'], icon: '⏱️', svgIcon: 'timer', content: "Time is the most precisely measured quantity in physics — and the story of its measurement changed history.\n\n**How we got here:**\n☀️ Sundials (3500 BC) — accurate to ~15 minutes\n⏳ Water clocks (Clepsydras) — first portable timekeeping\n⚙️ Mechanical pendulum clock (1656) — accurate to ±15 seconds/day\n🔭 Marine chronometer (1735) — allowed longitude navigation; saved thousands of ships\n⚛️ Quartz watch (1927) — ±1 second/month\n⚛️ **Caesium-133 Atomic Clock** (1955) — accurate to ±1 second per 300 MILLION years!\n\n**The atomic second (SI definition):** The duration of 9,192,631,770 oscillations of caesium-133 atoms when transitioning between two hyperfine levels. This is exact by definition!\n\n**Why atomic clocks matter today:**\n📍 **GPS** requires synchronisation to within 20-30 nanoseconds — your phone's position accuracy of 3 metres comes from timing light travel time to GPS satellites\n🌐 **Internet timing** — network protocols require timestamps accurate to milliseconds\n🔬 **Gravitational time dilation** — GPS satellites actually run FASTER (Einstein's relativity) and must be corrected for 38 microseconds/day! 🚀", highlight: "GPS works because atomic clocks are accurate to 1 second per 300 million years — without relativity correction, GPS would drift 11km per day! ⏱️" },
    { id: 'base_units_redefined', title: 'The 2019 SI Redefinition 🌟', color: '#A855F7', bgGradient: ['#1A0028', '#05050A'], icon: '🌟', svgIcon: 'sparkle', content: "On 20 May 2019, all 7 SI base units were simultaneously redefined — the biggest change in measurement in human history.\n\n**The problem with the old kilogram:**\nFor 130 years, 1 kilogram was defined as the mass of a platinum-iridium cylinder in Paris (**Le Grand K**). But physical objects change! Measurements showed Le Grand K was losing mass relative to copies stored globally — by about 50 micrograms. If Le Grand K changed, then by definition, EVERY kilogram in the world changed.\n\n**The solution — physical constants:**\nAll 7 SI base units are now defined by fixing the numerical values of 7 fundamental constants:\n\n🎯 **Planck's constant (h)** = 6.62607015×10⁻³⁴ J·s → defines the kilogram\n🎯 **Speed of light (c)** = 299,792,458 m/s → defines the metre\n🎯 **Elementary charge (e)** = 1.602176634×10⁻¹⁹ C → defines the ampere\n🎯 **Boltzmann constant (k)** = 1.380649×10⁻²³ J/K → defines the kelvin\n\n**Why this is revolutionary:** These constants are the same EVERYWHERE in the universe. An alien civilisation with the same physics knowledge could recreate our kilogram independently. For the first time, measurement standards are truly universal — tied to Nature, not to a metal object in a vault in France. 🌌", highlight: "The 2019 SI redefinition tied the kilogram to Planck's constant — now our units are universal, reproducible anywhere in the universe! 🌟" },
    { id: 'imperial_metric', title: 'Imperial vs Metric: The War of Units ⚔️', color: '#E74C3C', bgGradient: ['#2A0005', '#05050A'], icon: '⚔️', svgIcon: 'balance', content: "The metric vs imperial debate is more than cultural preference — it has real costs.\n\n**Why metric wins scientifically:**\n🔢 Based on powers of 10 (1km = 1,000m = 100,000cm = 1,000,000mm)\n🔢 Consistent prefixes across all units\n🔢 Easy conversion: no \"12 inches to a foot, 3 feet to a yard, 1760 yards to a mile\"\n🔢 **99.5% of peer-reviewed science uses SI**\n\n**The real costs of imperial:**\n💸 The US pays an estimated **$1 billion+ per year** in extra costs from maintaining imperial measurements alongside metric in international trade and engineering\n💥 Mars Climate Orbiter ($327M) — metric/imperial mismatch\n⛽ 1983 Gimli Glider — Air Canada Boeing 767 ran out of fuel mid-flight; ground crew had incorrectly converted between pounds and kilograms of fuel. Emergency landing on an abandoned airstrip!\n🏋️ 1999 Mt Washington weather record: a measurement reading was converted from the wrong unit — wrong record stood until reanalysis in 2010\n\n**Why the US didn't switch:**\nCongress authorised the metric system in 1866. The Metric Conversion Act of 1975 made it 'voluntary'. Lack of mandate = no switch. The cost to convert road signs, tools, and habits was deemed too high — a classic coordination failure. 🔄", highlight: "The Gimli Glider Boeing 767 nearly crash-landed because crew confused kg and lbs for fuel — the metric-imperial divide has caused disasters! ⚔️" },
  ],

  lab: {
    title: "Unit Converter & Precision Lab 📏",
    description: "Convert between units using dimensional analysis, calibrate virtual instruments, and discover the precision limits of different measuring tools!",
    hint: "Try converting extreme values — see where precision breaks down. Adjust instrument precision and watch how measurement uncertainty propagates!",
    scientistModeHint: "Scientist Mode: see dimensional analysis equations in real time, significant figure tracking, and uncertainty propagation formulas.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why the metre was originally defined using the Earth's size? 🌍", answer: "The French Academy of Sciences in 1791 defined the metre as one ten-millionth of the distance from the North Pole to the Equator through Paris. They sent surveyors to measure this arc during the French Revolution (while being arrested multiple times as spies!). The calculation was slightly wrong due to the Earth being an oblate spheroid, not a perfect sphere. But the spirit — a unit tied to Nature, not a king's body part — was revolutionary and led to the metric system spreading worldwide. 📏", emoji: '🌍' },
    { id: 'dyk2', question: "Do you know why GPS satellites need to account for Einstein's relativity? ⏱️", answer: "GPS satellites orbit at 20,200km altitude and travel at ~14,000km/h. Einstein's Special Relativity slows their clocks by 7 microseconds/day (time passes slower when moving fast). But General Relativity speeds them up by 45 microseconds/day (time passes faster in weaker gravity). Net effect: +38 microseconds/day. Without correcting for this, GPS positions would drift by 11km per day! Einstein predicted this 50 years before GPS existed. 🛸", emoji: '⏱️' },
    { id: 'dyk3', question: "Do you know why a microgram and a milligram mix-up in a hospital can be fatal? 💊", answer: "Heparin, an anticoagulant, is dosed in units. Digoxin, a heart drug, is dosed in micrograms. Mix-up: digoxin dose expressed in mg versus μg = 1000x overdose. In 2007, three premature babies at a US hospital died when given Heparin 1000 units/mL instead of 10 units/mL — a nurse grabbed the wrong concentration vial. Unit literacy in medicine literally saves lives. All medication orders must state both the dose AND the concentration explicitly, with dimensional analysis verification. 🏥", emoji: '💊' },
    { id: 'dyk4', question: "Do you know why Avogadro's number is exactly 6.02214076×10²³? 🧪", answer: "Before 2019, 1 mole was defined as the number of atoms in exactly 12g of carbon-12. After the 2019 redefinition, 1 mole is defined by fixing Avogadro's constant at exactly 6.02214076×10²³ mol⁻¹. This means 12g of carbon-12 is no longer exactly 12g — but the difference is far too small to ever measure! The reason for the redefinition: Avogadro's number is now tied to fundamental physics, not a physical sample of carbon. Any civilisation in the universe with the same physics knowledge could independently determine the exact same number. 🌌", emoji: '🧪' },
    { id: 'dyk5', question: "Do you know why the second is defined by counting caesium atom vibrations instead of Earth's rotation? 🌍", answer: "Earth's rotation is SLOWING DOWN due to tidal friction. In the dinosaur age, a day was only 23 hours. We add 'leap seconds' every few years to keep UTC (atomic time) in sync with solar time. By the year 4000, one Earth day will be 25 hours! The caesium-133 atomic second never changes — it ticks at the same rate regulated by quantum mechanics, immune to any physical influence. In 2023, scientists developed optical lattice clocks accurate to 1 second per 300 BILLION years. ⏰", emoji: '🌍' },
  ],

  quiz: [
    { id: 'q1', question: "How many base units are in the SI (International System of Units)? 🔢", options: ['5', '6', '7', '10'], answer: 2, explanation: "The 7 SI base units are: metre (length), kilogram (mass), second (time), ampere (current), kelvin (temperature), candela (luminosity), and mole (amount). ALL other units are mathematically derived from these 7! 🔢" },
    { id: 'q2', question: "What is the difference between accuracy and precision? 🎯", options: ['They mean the same thing in scientific measurement', 'Accuracy = closeness to true value; Precision = reproducibility of measurements', 'Accuracy is for digital instruments; precision is for analogue ones', 'Precision means more decimal places; accuracy means fewer'], answer: 1, explanation: "Accuracy: how close to the true value. Precision: how reproducible your measurements are. You can be precise but wrong (systematic error), or accurate but imprecise (random error). Perfect measurement is both! 🎯" },
    { id: 'q3', question: "Convert 60 miles/hour to metres/second. Speed of light = not needed, 1 mile = 1609m. 🚗", options: ['16.7 m/s', '26.8 m/s', '36.0 m/s', '100 m/s'], answer: 1, explanation: "60 mi/hr × (1609 m/mi) × (1 hr/3600 s) = 60 × 1609 / 3600 = 26.8 m/s. This is dimensional analysis — multiply by fractions equal to 1 to cancel units systematically! ⚗️" },
    { id: 'q4', question: "Why was the kilogram redefined in 2019? ⚖️", options: ['The cylinder was too expensive to maintain', 'Physical metal objects change mass over time; the new definition ties it to an unchanging physical constant', 'Scientists switched to pounds for better accuracy', 'The original kilogram was found to be incorrect by 1%'], answer: 1, explanation: "Le Grand K (a platinum cylinder in Paris) was drifting by ~50 micrograms over time. In 2019, the kilogram was redefined using Planck's constant h — an unchanging quantum constant the same everywhere in the universe! ⚖️" },
    { id: 'q5', question: "What is 0.000000082 metres in correct scientific notation? ✏️", options: ['82×10⁻⁹ m', '8.2×10⁻⁸ m', '0.82×10⁻⁷ m', '8.2×10⁻⁷ m'], answer: 1, explanation: "Move the decimal 8 places right to get 8.2 (must be between 1 and 9.99). Moved right means negative exponent: 8.2×10⁻⁸ m. This is 82 nanometres — about the diameter of a small virus! ✏️" },
    { id: 'q6', question: "What is systematic error? 🔴", options: ['Random fluctuations in measurements', 'A consistent offset that affects all measurements the same way in one direction', 'Errors made by students when recording data', 'Errors found in the textbook formulas'], answer: 1, explanation: "Systematic error: a scale that always reads 0.3g too heavy. No amount of repeating fixes this — you need to recalibrate the instrument! Compare to random error (reading fluctuations) which can be reduced by averaging multiple measurements. 🔴" },
    { id: 'q7', question: "A nurse is given an order for 0.5 mg. Which unit conversion is CORRECT? 💊", options: ['0.5 mg = 5000 μg', '0.5 mg = 500 μg', '0.5 mg = 50 μg', '0.5 mg = 0.0005 μg'], answer: 1, explanation: "1 mg = 1000 μg (milli = 10⁻³, micro = 10⁻⁶, ratio = 10³ = 1000). So 0.5 mg = 500 μg. Getting this wrong by a factor of 10 in either direction is a common and potentially lethal medication error! 💊" },
    { id: 'q8', question: "Why does GPS require atomic clock accuracy? 📍", options: ['To synchronise internet servers globally', 'Because light travels 30cm per nanosecond — tiny timing errors cause large position errors', 'To prevent signal interference from other satellites', 'To track satellite battery levels'], answer: 1, explanation: "GPS calculates your position from the TIME it takes radio signals (travelling at light speed) to reach you from multiple satellites. Light travels 30cm per nanosecond — a 100ns timing error = 30 metre position error. GPS requires timing accurate to ~20 nanoseconds! 🛰️" },
    { id: 'q9', question: "What does 'kilo' mean as an SI prefix? 🔢", options: ['100', '1,000', '10,000', '1,000,000'], answer: 1, explanation: "Kilo (k) = 10³ = 1,000. So 1 kilometre = 1,000 metres, 1 kilogram = 1,000 grams, 1 kilojoule = 1,000 joules. Key prefixes: milli (10⁻³), kilo (10³), Mega (10⁶), Giga (10⁹), Tera (10¹²). 🔢" },
    { id: 'q10', question: "Why is it wrong to report 60 miles converted to metres as 96,560.64 metres? 📏", options: ['The conversion factor is wrong', 'You cannot convert between imperial and metric', 'The original measurement (60 miles) has only 1-2 significant figures; reporting 7 is false precision', 'Metres should be rounded to the nearest 10'], answer: 2, explanation: "Significant figures: '60 miles' likely means 6×10¹ — 1 or 2 significant figures. You cannot gain precision through conversion — the answer should be 97,000m (2 sig figs) or 100,000m (1 sig fig). Reporting 96,560.64m implies you measured 60 miles to ±0.01 miles precision — you almost certainly didn't! 📏" },
    { id: 'q11', question: "What SI prefix represents 10⁻⁹ (one billionth)? 🔬", options: ['Micro (μ)', 'Milli (m)', 'Nano (n)', 'Pico (p)'], answer: 2, explanation: "Nano (n) = 10⁻⁹. DNA is about 2 nanometres wide. Modern processors use 3-5 nanometre transistor technology. The prefix comes from Greek 'nanos' meaning 'dwarf'. One nanometre is about 10 atoms wide! 🔬" },
    { id: 'q12', question: "What is the SI base unit for measuring temperature? 🌡️", options: ['Celsius (°C)', 'Fahrenheit (°F)', 'Kelvin (K)', 'Rankine (°R)'], answer: 2, explanation: "Kelvin (K) is the SI base unit for temperature. 0 K = absolute zero (−273.15°C) — the lowest possible temperature. Kelvin uses the same interval size as Celsius but starts at absolute zero. In science, we always use Kelvin for thermodynamic calculations! 🌡️" },
    { id: 'q13', question: "What is a meniscus and why does it matter in liquid measurement? 🧪", options: ['A type of measuring cylinder', 'The curved surface of a liquid in a container — you must read at the bottom of the curve', 'A chemical indicator for pH measurement', 'The foam that forms when pouring liquids'], answer: 1, explanation: "When water is in a glass container, adhesion to the walls pulls the edges upward, creating a concave meniscus. You must read at the BOTTOM of the curve for an accurate measurement. Mercury forms a convex meniscus (read at top) because cohesion is stronger than adhesion! 🧪" },
    { id: 'q14', question: "What destroyed the Mars Climate Orbiter in 1999? 🚀", options: ['A solar storm damaged its electronics', 'One team used metric units while another used imperial — causing a navigation error', 'The spacecraft ran out of fuel due to a calculation error', 'A software bug caused it to crash into Mars'], answer: 1, explanation: "Lockheed Martin used pound-force·seconds (imperial) for thruster data, while NASA's Jet Propulsion Lab expected Newton-seconds (metric). This $327 million unit mismatch caused the orbiter to enter Mars' atmosphere too low and disintegrate! 🚀" },
    { id: 'q15', question: "What is the difference between a Vernier calliper and a micrometer? 📐", options: ['Verniers measure length; micrometers measure mass', 'Verniers have ±0.02mm precision; micrometers have ±0.001mm precision', 'There is no difference — they are the same instrument', 'Verniers are digital; micrometers are analogue'], answer: 1, explanation: "A Vernier calliper uses a sliding scale to read ±0.02mm. A micrometer screw gauge uses a rotating thimble with finer graduations to achieve ±0.001mm — 20× more precise! Use Verniers for general lab work, micrometers for precision engineering. 📐" },
    { id: 'q16', question: "How does dimensional analysis prevent errors in calculations? ⚗️", options: ['It checks if the numerical answer is reasonable', 'It ensures units on both sides of an equation are consistent — wrong units mean wrong physics', 'It converts all measurements to metric automatically', 'It averages multiple measurements to reduce error'], answer: 1, explanation: "Dimensional analysis checks that units cancel correctly. If you're calculating speed and get kg instead of m/s, you made an error! This systematic approach is infallible — nurses, pilots, and engineers use it to prevent fatal miscalculations. ⚗️" },
    { id: 'q17', question: "What is the significance of the number 9,192,631,770 in modern physics? ⚛️", options: ['It is Avogadro"s number, It is the number of caesium-133 oscillations that define one second', 'It is the speed of light in furlongs per fortnight', 'It is the number of atoms in 1 gram of hydrogen'], answer: 1, explanation: "The SI second is defined as exactly 9,192,631,770 oscillations of the caesium-133 atom's hyperfine transition. This atomic definition makes time the most precisely measured quantity in all of physics — accurate to 1 second per 300 million years! ⚛️" },
    { id: 'q18', question: "Why do GPS satellites need to correct for Einstein's relativity? 🛰️", options: ['Relativity affects radio signal frequency', 'Special relativity slows satellite clocks and general relativity speeds them up — net +38μs/day', 'Relativity changes the speed of light at high altitude', 'Only special relativity matters for GPS'], answer: 1, explanation: "Special relativity: satellite clocks run 7μs/day slower (high speed). General relativity: clocks run 45μs/day faster (weaker gravity). Net: +38μs/day. Without correction, GPS would drift 11km/day! Einstein predicted this 50 years before GPS existed. 🛰️" },
    { id: 'q19', question: "What is the resolution of a measuring instrument? 📏", options: ['How accurate the instrument is', 'The smallest change in measurement the instrument can detect', 'The range of values the instrument can measure', 'How often the instrument needs calibration'], answer: 1, explanation: "Resolution is the smallest graduation or increment an instrument can read. A ruler with mm markings has 1mm resolution. A digital scale showing 0.01g has 0.01g resolution. Higher resolution ≠ higher accuracy — a miscalibrated instrument can be high-resolution but inaccurate! 📏" },
    { id: 'q20', question: "Why can only 3 countries in the world officially use the imperial system? 🌍", options: ['Imperial is patented by the UK government', 'Most countries adopted the metric system for its base-10 simplicity and scientific standardisation', 'The UN banned imperial units in 1975', 'Imperial units are less accurate than metric'], answer: 1, explanation: "The metric system's base-10 structure (1km = 1000m = 1,000,000mm) makes conversions trivial compared to imperial (1 mile = 5280 feet = 63,360 inches). Only the USA, Myanmar, and Liberia haven't fully switched. The US alone pays ~$1 billion/year in extra costs from maintaining dual systems! 🌍" },
  ],

  relatedTopics: ['scientific_method', 'matter_states', 'atoms_molecules', 'heat_temperature'],
};