// ─────────────────────────────────────────────────────────
//  TOPIC: BE A GOOD CITIZEN
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'good_citizen',
  title: 'Be a Good Citizen',
  subtitle: 'The social contract and community survival 🌍🤝',
  emoji: '🏙️',
  category: 'Society',
  accentKey: 'civics',

  hook: {
    question: "Imagine you find a wallet with $100 in it on an empty street. No cameras. No witnesses. What do you do? 💵",
    reveal: "If everyone keeps the wallet, we live in a society of thieves where no one trusts anyone. If everyone returns the wallet, we live in a high-trust society where you never have to lock your doors. Being a 'good citizen' isn't just about following laws to avoid prison; it is actively constructing the Invisible Web of Trust that prevents human civilization from collapsing into chaos. Let's look at the math behind empathy and civic duty! 🕸️🤝",
    emoji: '⚖️',
  },

  theory: [
    {
      id: 'social_contract',
      title: 'The Social Contract 📜',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '📜',
      svgIcon: 'book',
      content: "Philosophers like Thomas Hobbes and Jean-Jacques Rousseau proposed the idea of the **Social Contract**.\n\nBefore civilization, humans lived in a 'State of Nature' where you had absolute freedom, but life was \"nasty, brutish, and short\" because anyone could kill you for your food. \nTo survive, we made a deal: We sacrifice some of our absolute freedom (I agree not to steal from you), and in return, society guarantees our safety. Law isn't a cage; it's a mutual defense treaty! 🛡️",
      highlight: "You surrender your right to harm others, in exchange for not being harmed. 🤝",
    },
    {
      id: 'tragedy_of_commons',
      title: 'The Tragedy of the Commons 🐑',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🐑',
      svgIcon: 'eye',
      content: "Imagine a village shares a single pasture (The Commons). Every farmer thinks: 'If I add just ONE extra sheep, I make more money, and it barely hurts the grass.'\n\nBut if *every* farmer uses this selfish logic, they add 100 sheep, the grass is destroyed, the sheep starve, and the entire village dies. \nThis is the **Tragedy of the Commons**. It explains pollution, overfishing, and traffic jams. Short-term selfish logic directly causes long-term collective suicide! 📉",
      highlight: "If everyone takes 'just a little extra', there is eventually nothing left for anyone. 🍂",
    },
    {
      id: 'high_trust_societies',
      title: 'High-Trust Societies 🤝',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🤝',
      svgIcon: 'lock',
      content: "Economists divide the world into High-Trust and Low-Trust societies. \n\nIn a **High-Trust Society** (like Denmark or Japan), citizens trust strangers. People leave strollers outside cafes, businesses run smoothly without massive legal contracts, and crime is incredibly low. \nIn a Low-Trust Society, you have to lock everything, hire guards, and assume everyone is trying to cheat you. Trust is the ultimate economic superpower! 📈",
      highlight: "A society without trust spends all its money on locks instead of schools. 🔐",
    },
    {
      id: 'civic_duty',
      title: 'Rights vs Responsibilities ⚖️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'refresh',
      content: "We love talking about our **Rights** (Freedom of Speech, Right to a Fair Trial). But every Right is paid for by a **Responsibility** (Civic Duty).\n\nYou only have a right to a jury trial because other citizens give up their time to serve on a jury! You only have a right to clean water because citizens pay taxes to build facilities.\nIf everyone demands Rights but refuses their Responsibilities, the society goes bankrupt and collapses! 🏛️",
      highlight: "A Right is a check you cash. A Responsibility is the deposit that funds the bank. 🏦",
    },
    {
      id: 'the_shopping_cart',
      title: 'The Shopping Cart Theory 🛒',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🛒',
      svgIcon: 'target',
      content: "The ultimate test of a good citizen is the **Shopping Cart Theory**.\n\nReturning a shopping cart to the proper stall is easy, helpful, and courteous. HOWEVER, it is not illegal to abandon it. You will not be fined or arrested for leaving it in the parking lot. \nTherefore, returning the cart is the purest test of morality. You do the right thing simply because it is right, with no physical threat forcing you to do it. 🌟",
      highlight: "Who are you when the law isn't watching? 👁️",
    },
    {
      id: 'empathy_gap',
      title: 'The Empathy Gap 🌉',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🌉',
      svgIcon: 'users',
      content: "Biologically, our brains evolved in tribes of 150 people (Dunbar's Number). We are hardwired to feel deep empathy for our family, but not for strangers on the other side of a massive city. \n\nThis is the **Empathy Gap**. A good citizen uses their Prefrontal Cortex to logically bridge this gap, treating strangers with respect even when their tribal biology tells them not to care about them. Civilization is the triumph of logic over primitive tribalism! 🧠",
      highlight: "Empathy for your family is instinct. Empathy for a stranger is civilization. 🏙️",
    },
    {
      id: 'veil_of_ignorance',
      title: 'The Veil of Ignorance 🎭',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🎭',
      svgIcon: 'eye',
      content: "Philosopher John Rawls created the ultimate thought experiment for justice: **The Veil of Ignorance**. \n\nImagine you are designing a brand new society. You get to make all the laws. \nHOWEVER, you don't know who you will be born as in this society. You might be born rich, poor, disabled, healthy, a minority, or the majority. \nHow would you structure the laws? You would make them as fair as possible for the weakest members, just in case you ended up being one of them! ⚖️",
      highlight: "Justice is designing the rules so they protect the person you hope you never become. 🛡️",
    },
    {
      id: 'digital_citizenship',
      title: 'Digital Citizenship 💻',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '💻',
      svgIcon: 'cloud',
      content: "We now live in two worlds: Physical and Digital.\n\n**Digital Citizenship** means applying the same ethical rules online as you do in person. The 'Online Disinhibition Effect' makes people feel anonymous, turning otherwise normal people into cruel trolls. \nA good digital citizen doesn't spread unverified rumors (Fake News), doesn't cyberbully, and remembers there is a crushing, breathing human being behind every avatar. 🌐",
      highlight: "Anonymity is the acid test of character. 🎭",
    },
    {
      id: 'broken_windows',
      title: 'Broken Windows Theory 🪟',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🪟',
      svgIcon: 'waves',
      content: "The **Broken Windows Theory** suggests that visible signs of crime or decay (like a broken window on a factory) create an environment that encourages *more* serious crime. \n\nIf a window is broken and nobody fixes it, it signals to the community: 'Nobody cares here.' Soon, graffiti appears. Then, muggings. \nBut if a community instantly fixes the window, it signals: 'We are watching, and we care.' Small acts of daily maintenance prevent societal collapse! 🧱",
      highlight: "A society unravels not by massive explosions, but by thousands of unfixed tiny cracks. 🕸️",
    },
    {
      id: 'paying_taxes',
      title: 'Taxes: The Price of Civilization 💵',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '💵',
      svgIcon: 'chart',
      content: "Nobody likes paying taxes. But Oliver Wendell Holmes famously said: **'Taxes are what we pay for a civilized society.'** \n\nTaxes fund the invisible infrastructure keeping you alive: the FDA checking your food for poison, the roads you drive on, the firefighters who answer 911, and the schools educating the people who will one day become your doctors. \nTaxes are the group-subscription fee for belonging to the modern world! 💳",
      highlight: "Without taxes, you don't have a society; you have a lawless jungle. 🐅",
    },
    {
      id: 'active_bystander',
      title: 'The Active Bystander 🦸‍♂️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🦸‍♂️',
      svgIcon: 'zap',
      content: "We learned about the Bystander Effect (where everyone ignores an emergency). A good citizen practices being an **Active Bystander**. \n\nThis means consciously breaking the social freeze. If you see someone being harassed on the subway, you do not look away. You intervene directly, or you use the 'Distract' method (asking the victim for directions to break the harasser's focus). \nCourage isn't the absence of fear; it is acting despite it to protect the vulnerable. 🛡️",
      highlight: "Evil succeeds when good people look at their phones. 📱",
    },
    {
      id: 'environmental_stewardship',
      title: 'Environmental Stewardship 🌍',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🌍',
      svgIcon: 'sparkle',
      content: "A good citizen's responsibility extends beyond people to the Earth itself.\n\nEvery piece of plastic you throw on the ground will outlive you by hundreds of years. **Stewardship** means recognizing that we do not own the planet; we are just renting it from our grandchildren. \nRecycling, conserving water, and supporting green energy are civic duties to the humans who haven't even been born yet! 🌱",
      highlight: "We inherit the earth from our ancestors, but we borrow it from our children. 👶",
    },
    {
      id: 'civil_discourse',
      title: 'Civil Discourse 🗣️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🗣️',
      svgIcon: 'users',
      content: "Democracy dies when people stop talking to each other. \n\n**Civil Discourse** is the ability to debate a controversial issue without attacking the other person's character (Ad Hominem). It means listening to *understand*, not just listening to *reply*. \nA good citizen knows that the person across the aisle isn't an 'enemy to be destroyed,' but a fellow citizen who simply has a different hypothesis on how to fix the country. 🤝",
      highlight: "If you want to change someone's mind, you must first respect their humanity. ❤️",
    },
    {
      id: 'voting_power',
      title: 'The Power of the Vote 🗳️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🗳️',
      svgIcon: 'star',
      content: "Many people don't vote because they think: 'My one vote out of 100 million doesn't matter.'\n\nThis is a mathematical fallacy! If everyone thinks that way, dictators take over. Voting is not just about moving a statistic by 1; it is a sacred ritual. Every time you vote, you are renewing the Social Contract and asserting your power as a sovereign architect of the state. \nIf voting didn't matter, corrupt politicians wouldn't work so hard to stop you from doing it! 👑",
      highlight: "Your vote is your voice. Silence is consent to whatever happens. 🗣️",
    },
    {
      id: 'the_ripple_effect',
      title: 'The Ripple Effect 🌊',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🌊',
      svgIcon: 'refresh',
      content: "You might feel small, but human behavior is contagious. \n\nWhen you hold the door for someone, mirror neurons in their brain fire, making them 30% more likely to hold the door for the next person. Good citizenship creates a profound **Ripple Effect** across the network. \nOne act of kindness at 8 AM can multiply mathematically, altering the days of 100 strangers by 5 PM! 🌅",
      highlight: "You are the pebble. Society is the pond. Make a good splash. 💧",
    },
  ],

  lab: {
    title: "The Commons Tragedy 🐑🌍",
    description: "Welcome to the Village! You and 3 AI villagers share a fishing lake. You must decide how many fish to catch each round. If you take maximum (3), you get rich! But if everyone takes maximum, the lake depletes and everyone starves. If you take minimum (1), the lake regenerates. Can you maximize your own wealth without triggering ecological collapse and destroying the village? 🎣📉",
    hint: "If you act selfishly to get rich quickly, the AI will learn and violently overfish to copy you! You have to lead by example, demonstrating self-restraint (taking 1 or 2) to establish a 'High-Trust' baseline in the village.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Game Theory matrices (Nash Equilibrium mapping), Nash-Defection rates, and Ecosystem carrying-capacity math.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we have stoplights at intersections? 🚦",
      answer: "The Social Contract in action! If everyone just drives whenever they want (total freedom), everyone dies in a crash. We all mutually agree to surrender our freedom to drive forward for 60 seconds (the red light) so that we can ALL eventually get home alive. Law creates order out of chaos! 🛑",
      emoji: '🚔',
    },
    {
      id: 'dyk2',
      question: "Do you know why people leave trash in a movie theater but not in a friend's house? 🍿",
      answer: "Diffusion of Responsibility! At a friend's house, the social contract is direct and personal. In a massive theater, the brain thinks, 'I paid for a ticket, and someone else is paid to clean this up, so my responsibility is zero.' A good citizen cleans up anyway! 🗑️",
      emoji: '🎬',
    },
    {
      id: 'dyk3',
      question: "Do you know why jury duty is mandatory? 👨‍⚖️",
      answer: "Because justice cannot exist without it! If only people who 'wanted' to be there showed up, juries would be filled exclusively with vigilantes with extreme biases. By forcing random citizens to serve, the law guarantees that an accused person is judged by a balanced slice of real, normal humanity. ⚖️",
      emoji: '🧑‍🤝‍🧑',
    },
    {
      id: 'dyk4',
      question: "Do you know why paying taxes is actually cheaper for you in the long run? 💵",
      answer: "Economies of scale! If you had to personally hire armed guards for your house, build your own roads, test your own water for pathogens, and home-school your kids, it would cost millions of dollars a year. Taxes pool our money together to buy civilized infrastructure at an incredible wholesale discount! 🏢",
      emoji: '💰',
    },
    {
      id: 'dyk5',
      question: "Do you know why it's illegal to yell 'Fire!' in a crowded theater when there is no fire? 🔥",
      answer: "Because Rights have limits! Freedom of Speech protects your right to criticize the government, but it does NOT protect your right to cause a deadly panic that crushes people to death. Your rights end exactly where another citizen's right to physical safety begins. 🛑",
      emoji: '🗣️',
    },
    {
      id: 'dyk6',
      question: "Do you know why high-trust countries like Denmark are so wealthy? 🤝",
      answer: "Low 'Friction' costs! In low-trust countries, businesses have to spend millions on lawyers, complex contracts, extreme security, and insurance just to operate. In high-trust countries, business deals happen with a handshake. They spend that saved money on innovation and schools instead! 🚀",
      emoji: '🌍',
    },
    {
      id: 'dyk7',
      question: "Do you know why the Internet makes people incredibly mean (cyberbullying)? 💻",
      answer: "The Online Disinhibition Effect. In real life, if you insult someone, you see their face drop, and your brain's empathy center (mirror neurons) fires, making you feel bad. Online, the screen blocks the facial feedback. Without biological empathy kicking in, humans revert to sociopathic behavior! 🎭",
      emoji: '🤬',
    },
    {
      id: 'dyk8',
      question: "Do you know why fixing a broken window lowers the murder rate? 🪟",
      answer: "The Broken Windows Theory! An unfixed window sends a psychological signal to criminals that 'there are no rules here.' It invites drug dealers, which invites violence. But when the community immediately cleans graffiti and fixes glass, criminals think 'this area is highly monitored' and they leave! 🧱",
      emoji: '📉',
    },
    {
      id: 'dyk9',
      question: "Do you know why we are supposed to vote even if our state always goes to one party? 🗳️",
      answer: "The Mandate of the Masses! Politicians look at vote counts to gauge public momentum. Even if your candidate loses, if they get 40% of the vote instead of 10%, the winning politician is forced to moderate their extreme policies to appease the massive growing minority. Every single vote changes the temperature! 🌡️",
      emoji: '📊',
    },
    {
      id: 'dyk10',
      question: "Do you know why people volunteer to pick up trash on the beach for free? 🏖️",
      answer: "Self-Transcendence! Beyond the biological 'Helper's High', psychology shows that taking ownership of a public space makes the brain feel deeply connected to the universe. It shifts your identity from 'A helpless consumer' to 'An Architect of the World.' It is profoundly meaningful! 🌍",
      emoji: '✨',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the 'Social Contract'?", options: ['A contract you sign at work', 'Giving up absolute freedom to harm others in exchange for society protecting you', 'A social media terms of service', 'A peace treaty'], answer: 1, explanation: "Law isn't a cage; it's a mutual defense pact! 🛡️" },
    { id: 'q2', question: "The 'Tragedy of the Commons' explains why:", options: ['Comedy is popular', 'Short-term selfish logic destroys shared resources (like overfishing a lake)', 'Farmers are sad', 'Sheep run away'], answer: 1, explanation: "If everyone takes 'just one extra', society collapses. 🐑" },
    { id: 'q3', question: "A 'High-Trust Society' is characterized by:", options: ['Lots of lawyers', 'High crime rates', 'Leaving strollers outside and low economic friction', 'Nobody speaking to each other'], answer: 2, explanation: "Trust is the ultimate economic superpower! 🤝" },
    { id: 'q4', question: "Every Right you have (like a trial by jury) is paid for by someone else's:", options: ['Money', 'Civic Responsibility (like serving on a jury)', 'Mistakes', 'Tears'], answer: 1, explanation: "Rights are checks cashed from the bank of Responsibilities! 🏦" },
    { id: 'q5', question: "The 'Shopping Cart Theory' is the ultimate test of character because:", options: ['Carts are heavy', 'Returning it is good, but there is zero legal punishment for abandoning it. You do it entirely out of internal morals', 'Carts cost money', 'Carts have wheels'], answer: 1, explanation: "Who are you when the law isn't watching? 🛒" },
    { id: 'q6', question: "Biologically, humans evolved an 'Empathy Gap', which means we:", options: ['Don\'t care about anything', 'Are hardwired to only care about our tribe/family, and must use logic to care about strangers', 'Jump over gaps', 'Hate our families'], answer: 1, explanation: "Civilization requires expanding our empathy beyond biology. 🌉" },
    { id: 'q7', question: "John Rawls' 'Veil of Ignorance' asks you to design laws under what condition?", options: ['With your eyes closed', 'Not knowing if you will be born rich, poor, minority, or disabled', 'While asleep', 'While holding a weighted scale'], answer: 1, explanation: "You would make the rules fair for the weakest, just in case you become the weakest! ⚖️" },
    { id: 'q8', question: "What causes the 'Online Disinhibition Effect' (cyberbullying)?", options: ['A computer virus', 'The screen blocks facial feedback, preventing mirror neurons from triggering empathy', 'Fast internet', 'Keyboards'], answer: 1, explanation: "Without seeing the tears, the brain acts like a sociopath. 💻" },
    { id: 'q9', question: "The 'Broken Windows Theory' suggests that:", options: ['Glass is fragile', 'Visible signs of neglect and small crimes signal \'nobody cares\', inviting violent crime', 'Windows should be open', 'Crime only happens near glass'], answer: 1, explanation: "Small acts of maintenance prevent total societal collapse! 🪟" },
    { id: 'q10', question: "Why do we pay taxes?", options: ['To punish us', 'To buy shared civilized infrastructure (roads, FDA, schools) at a massive group discount', 'Because the king said so', 'To lose money'], answer: 1, explanation: "Taxes are the subscription fee for the modern world! 💵" },
    { id: 'q11', question: "An 'Active Bystander' is someone who:", options: ['Runs quickly past a crime', 'Consciously breaks the freeze to intervene or distract a harasser', 'Films the emergency on their phone', 'Stands actively'], answer: 1, explanation: "Evil succeeds when good people look at their phones. 🦸‍♂️" },
    { id: 'q12', question: "Environmental Stewardship means treating the planet as something we:", options: ['Own completely', 'Don\'t care about', 'Are renting from our own grandchildren', 'Bought from aliens'], answer: 2, explanation: "We borrow the earth from the humans who aren't born yet! 🌍" },
    { id: 'q13', question: "What is 'Civil Discourse'?", options: ['Yelling on the street', 'Debating an issue respectfully without attacking the other person\'s character', 'A college class', 'Refusing to speak'], answer: 1, explanation: "You listen to understand, not just to reply! 🗣️" },
    { id: 'q14', question: "Even if your political party always loses in your state, why should you vote?", options: ['You get a sticker', 'Vote margins shift momentum, forcing winners to moderate extreme policies to appease the minority', 'It is the law', 'It wastes paper'], answer: 1, explanation: "A 40% loss changes the laws entirely differently than a 10% loss! 🗳️" },
    { id: 'q15', question: "The 'Ripple Effect' of good citizenship works because:", options: ['Water ripples', 'Human behavior is contagious via mirror neurons; one kindness multiplies across the city', 'Laws enforce it', 'People are fake'], answer: 1, explanation: "Your single act of holding a door alters the psychology of the next 10 strangers! 🌊" },
    { id: 'q16', question: "Why do we have stoplights?", options: ['They are pretty', 'We surrender our absolute freedom to drive so we can prevent total chaotic death at intersections', 'To sell electricity', 'To annoy us'], answer: 1, explanation: "Minor inconveniences prevent major catastrophes! 🚦" },
    { id: 'q17', question: "Why does the 'Bystander Effect' happen in crowded theaters?", options: ['Diffusion of Responsibility: you assume someone else is paid to handle it', 'Theaters are dark', 'Everyone is asleep', 'Popcorn is tasty'], answer: 0, explanation: "When 50 people divide 1 responsibility, nobody feels accountable! 🚶‍♂️" },
    { id: 'q18', question: "Jury duty is a random draft of citizens because:", options: ['It is a punishment', 'Justice requires a balanced slice of real humanity, not just vigilantes', 'Courts are poor', 'It is fun'], answer: 1, explanation: "It is the ultimate expression of the civic responsibility that buys a fair trial! 👨‍⚖️" },
    { id: 'q19', question: "Low-trust societies waste billions of dollars on:", options: ['Ice cream', 'Friction costs like lawyers, security guards, and complex contracts', 'Parks', 'Schools'], answer: 1, explanation: "When nobody trusts anyone, the economy slows to a crawl! 📉" },
    { id: 'q20', question: "Picking up trash on a beach provides a psychological boost called:", options: ['Sunburn', 'Self-Transcendence (shifting from consumer to an Architect of the World)', 'Muscle growth', 'Boredom'], answer: 1, explanation: "Taking ownership of public space fills the existential vacuum! ✨" },
  ],

  relatedTopics: ['why_be_good', 'cognitive_biases', 'manipulation_tactics'],
};
