// ─────────────────────────────────────────────────────────
//  TOPIC: WEALTH LOOPS
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'wealth_loops',
  title: 'Wealth Loops',
  subtitle: 'The secret engines that build massive wealth on autopilot 🔄',
  emoji: '🌀',
  category: 'Finance',
  accentKey: 'success',

  hook: {
    question: "Why do some people get richer while working LESS, while others work harder and stay the same? 🌀",
    reveal: "The secret is not 'working hard.' It is 'Loops.' Most people live in a straight line: Work -> Get Paid -> Spend -> Zero. Wealthy people build self-sustaining loops where money makes more money, which makes even MORE money, until the engine becomes unstoppable. Let's master the 7 greatest loops of wealth. 🔄💸",
    emoji: '🌀',
  },

  theory: [
    {
      id: 'loop_concept',
      title: 'Lines vs Circles 🔄',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔄',
      svgIcon: 'refresh',
      content: "Most people are trapped in a **Linear Trap**: they trade 1 hour of time for 10 rupees. If they stop working, the money stops. \n\nA **Wealth Loop** is a circle. You build it once, and then it generates money automatically. That money is then put BACK into the loop to make it spin even faster. Eventually, the loop spins so fast that it creates wealth even while you sleep. 😴",
      highlight: "Linear systems scale with effort; Loops scale with time. ⏳",
    },
    {
      id: 'compounding_loop',
      title: 'The Snowball Loop ❄️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '❄️',
      svgIcon: 'trending-up',
      content: "The Loop: **Invest → Earn Profit → Reinvest Profit → Earn More.** \n\nImagine a tiny snowball rolling down a mountain. As it rolls, it picks up more snow. The bigger it gets, the more snow it picks up every second. If you take a piece of snow (profit) to buy a candy bar, you slow down the snowball. If you leave it alone, it becomes an unstoppable avalanche! 🏔️",
      highlight: "Don't eat your golden seeds; plant them! 🦢",
    },
    {
      id: 'real_estate_loop',
      title: 'The Tenant Loop 🏠',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🏠',
      svgIcon: 'home',
      content: "The Loop: **Buy House → Rent It → Use Rent to Pay Loan → Own Asset for Free.** \n\nThis is the ultimate loop where someone else buys your asset for you. You put down a small amount, and the tenant effectively pays the bank every month. After 20 years, the loan vanishes, and you own a giant building for 'free.' You used the tenant's income to build your own castle. 🏰",
      highlight: "In this loop, the tenant is your wealth engine. 🤝",
    },
    {
      id: 'dividend_loop',
      title: 'The Fruit Loop 📈',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📈',
      svgIcon: 'bar-chart',
      content: "The Loop: **Buy Dividend Stocks → Get Cash → Buy More Stocks → Get More Cash.** \n\nSome companies share their profits with you every 3 months. If you use that 'Fruit' (Cash) to buy more 'Trees' (Stocks), your next harvest will be even bigger. You are using the company's own success to buy more of the company! Eventually, the fruit harvest pays all your bills. 🍒",
      highlight: "Compound your ownership, not just your cash! 💹",
    },
    {
      id: 'business_growth_loop',
      title: 'The Double Engine Loop 🏢',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🏢',
      svgIcon: 'activity',
      content: "The Loop: **Business Profit → Invest Surplus → Investment Returns Fund Business.** \n\nA business can be risky. But if you take your profits and put them in the safe stock market, you create a 'Safety Net.' If your business has a bad month, your investments can pay the rent. One engine feeds the other, making your whole life indestructible. 🛡️",
      highlight: "Use one engine to protect the other. 🏗️",
    },
    {
      id: 'skill_income_loop',
      title: 'The Accelerator Loop 🧠',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🧠',
      svgIcon: 'cpu',
      content: "The Loop: **Learn Skill → Earn More → Invest More → Grow Faster.** \n\nIf you earn ₹30k and save ₹5k, it takes forever to be rich. But if you spend ₹10k to learn a high-value skill (like Coding), and your income jumps to ₹1 Lakh, you can now invest ₹50k every month! Investing in your brain is the 'Turbo Button' for all your other loops. 🚀",
      highlight: "Your brain is the highest ROI asset you will ever own. 💡",
    },
    {
      id: 'tax_saving_loop',
      title: 'The Free Money Loop 📜',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '📜',
      svgIcon: 'shield',
      content: "The Loop: **Earn → Use Tax Savers → Save Tax → Invest the Saved Tax.** \n\nMost people treat a tax refund like a 'bonus' for a vacation. Loopers take that saved money and put it back into the market. Over 30 years, just reinvesting the money the government *didn't* take can create an extra ₹1 Crore! It's effectively 'Free Money' from the government. 🏛️",
      highlight: "Tax saved is pure profit. Reinvest it! 💸",
    },
    {
      id: 'credit_loop',
      title: 'The Dangerous Loop (Leverage) ⚠️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚠️',
      svgIcon: 'zap',
      content: "The Loop: **Borrow Low → Invest High → Repay → Keep the Gap.** \n\nThis is how the ultra-rich use 'Debt' as a weapon. If you can borrow at 8% and invest in an asset that makes 15%, you are making 7% profit on money you didn't even have! But be careful—if the investment drops to 5%, you still owe 8%, and the loop can crush you. 🧨",
      highlight: "Leverage is a double-edged sword: it magnifies everything. 🎲",
    },
    {
      id: 'loop_velocity',
      title: 'The Speed of Wealth 🏎️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🏎️',
      svgIcon: 'zap',
      content: "How fast your loop grows depends on **Friction.** \n\nFriction is anything that slows down the circle: taxes, fees, and emotional spending. Every time you withdraw money from your 'Compounding Loop' to buy a new phone, you stop the momentum and have to start the engine all over again. Minimize friction to reach speed! 🛑",
      highlight: "The first 5 years are the hardest. Don't stop the spin! 🧗",
    },
    {
      id: 'financial_freedom',
      title: 'The Self-Sustaining Goal 🕊️',
      color: '#e60606ff',
      bgGradient: ['#1A1A1A', '#050D0A'],
      icon: '🕊️',
      svgIcon: 'star',
      content: "The final goal is to have your loops generate more money than you spend. \n\nWhen your Dividends + Rent + Interest exceed your monthly bills, you have won the game of finance. The loop is now self-sustaining. You no longer 'have' to work—you only work if you want to. You have traded your 'Linear Time' for 'Infinite Freedom.' 🏆",
      highlight: "Freedom is when the system works for you. 🕊️",
    },
  ],

  lab: {
    title: "The Loop Engine 🌀",
    description: "Welcome to the Loops Lab! Here you can simulate the 7 power-engines. Watch how 'Reinvesting' changes the graph from a flat line to a rocket ship. Test the 'Skill Ladder' to see how learning today changes your life in 20 years! 📈",
    hint: "Try the 'Reinvest Returns' toggle. Notice how the blue line starts to curve UP much faster when you leave the profit inside the loop. That's the secret of the rich!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks 'Negative Arbitrage' math and 'Inflation Friction' models for professional loop analysis.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the first ₹1 Crore is the hardest? 🧊",
      answer: "Momentum! To get the first ₹1 Crore, YOU have to do all the work. But once you have it, at 12% return, your money earns ₹12 Lakhs a year on its own. That ₹12 Lakhs starts compounding too. Eventually, your money is working much harder than you ever could! 🏗️",
      emoji: '📈',
    },
    {
      id: 'dyk2',
      question: "Do you know why rich people never say 'I can't afford it'? 🧠",
      answer: "They ask: 'How can I buy this with a loop?' Instead of using their salary to buy a car, they use their salary to buy a rental property. Then they use the *rent* from that house to pay for the car. In the end, they have the car AND the house! They never spend their principal. 🏠🏎️",
      emoji: '🧠',
    },
    {
      id: 'dyk3',
      question: "Do you know why 'DRIP' is the ultimate loop hack? 🏦",
      answer: "Dividend Reinvestment Plan! It automatically takes your dividends and buys more shares instantly without you even seeing the money. This removes 'Friction' and stops you from spending the profit on junk. It's the 'Set and Forget' mode for wealth! 💹",
      emoji: '💹',
    },
    {
      id: 'dyk4',
      question: "Do you know why 'Investing in Yourself' is the highest ROI? 🚀",
      answer: "If you have ₹10,000, a 10% stock return is only ₹1,000. But if you spend that ₹10,000 on a skill that raises your salary by ₹20,000 *every month*, your return is 2,400% per year! Stocks keep wealth; Skills build it. 🧠",
      emoji: '💡',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Leverage' is the #1 cause of bankruptcy? 🎲",
      answer: "The 'Margin' Danger! If you borrow ₹90 Lakhs to buy a ₹1 Crore house, and the house price drops by just 10%, YOU HAVE LOST 100% of your own ₹10 Lakhs. Leverage makes you look like a genius when things go up, but it destroys you when they go down. 🧨",
      emoji: '⚠️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the 'Loop Breaker'?", options: ["Investing too much", "Spending your profit instead of reinvesting it", "Using a bank", "Buying gold"], answer: 1, explanation: "If you take the seeds out of the soil, the tree stops growing! 🛑" },
    { id: 'q2', question: "In the Real Estate Loop, who is paying for your house?", options: ["The Bank", "The Government", "The Tenant (via rent)", "The Builder"], answer: 2, explanation: "The tenant's rent covers the debt, building your wealth for 'free'! 🏠" },
    { id: 'q3', question: "Why is the Skill Loop best for beginners?", options: ["Because skills are fun", "Because it increases the 'fuel' (income) you can pour into other loops", "It's required by law", "It saves tax"], answer: 1, explanation: "Higher income lets you invest larger amounts faster! 🚀" },
    { id: 'q4', question: "What is 'Positive Arbitrage'?", options: ["A type of math", "Borrowing at a low rate and investing at a higher rate", "Paying off all debt", "Saving 100% of income"], answer: 1, explanation: "You pocket the difference between the cost and the return! 💹" },
    { id: 'q5', question: "What should you do with a tax refund in a loop?", options: ["Buy a new phone", "Go on a vacation", "Reinvest it into the market", "Keep it in cash"], answer: 2, explanation: "Reinvesting 'found money' creates a secret extra engine! 📜" },
    { id: 'q6', question: "The Dividend Loop relies on:", options: ["Companies sharing profits with you", "The stock price going down", "Paying the bank", "Selling everything"], answer: 0, explanation: "Dividends are your slice of the company's success! 📈" },
    { id: 'q7', question: "Why are the first 5 years of a loop so hard?", options: ["Because of taxes", "Because the growth is slow and requires the most discipline", "The bank takes the money", "It's illegal to start early"], answer: 1, explanation: "Compounding looks flat at the start; the curve happens later! 🧗" },
    { id: 'q8', question: "In the Double Engine Loop, what is the 'Safety Net'?", options: ["A literal net", "Your investments protecting your business from a bad month", "A bank loan", "The government"], answer: 1, explanation: "One engine supports the other when things get tough! 🏢" },
    { id: 'q9', question: "What is 'Negative Arbitrage'?", options: ["Losing a game", "When your loan cost is HIGHER than your investment return", "Paying no tax", "Having zero debt"], answer: 1, explanation: "Debt becomes a trap if it costs more than it earns! ⚠️" },
    { id: 'q10', question: "What is the 'Golden Rule' of compounding?", options: ["Invest only in gold", "Withdraw profits often", "Reinvest 100% of returns during the build phase", "Avoid the stock market"], answer: 2, explanation: "Reinvesting is what makes it a loop! 🔄" },
    { id: 'q11', question: "What does 'Velocity' mean in wealth loops?", options: ["How fast you drive", "How often your returns are reinvested (Daily vs Yearly)", "The speed of light", "The amount of money"], answer: 1, explanation: "Faster cycles mean more compounding 'hits'! 🏎️" },
    { id: 'q12', question: "When are you 'Financially Free'?", options: ["When you have ₹100 Crores", "When your loops pay for all your monthly bills forever", "When you have zero debt", "When you get a raise"], answer: 1, explanation: "Freedom is when your system works for you! 🕊️" },
    { id: 'q13', question: "What is 'Friction' in a loop?", options: ["A type of physics", "Taxes, fees, and emotional spending that slow you down", "The speed of the bank", "The number of shares"], answer: 1, explanation: "Friction drains the energy from your wealth engine! 🛑" },
    { id: 'q14', question: "Why is reinvesting tax savings 'Free Money'?", options: ["Because it's a gift", "It's money you already 'lost' to the government, now recovered and put to work", "It's illegal", "It has zero risk"], answer: 1, explanation: "It's 'Found' money that most people waste! 📜" },
    { id: 'q15', question: "What is the risk of the Real Estate Loop?", options: ["The house might get dirty", "The tenant leaves and you have to pay the EMI yourself", "The grass grows too long", "The bank closes"], answer: 1, explanation: "Vacancy risk can break the loop if you aren't prepared! ⚠️" },
    { id: 'q16', question: "The most important 'First Loop' for a beginner is:", options: ["The Credit Loop", "The Skill → Income Loop", "The Real Estate Loop", "The Gold Loop"], answer: 1, explanation: "Build your income engine first to fuel everything else! 🚀" },
    { id: 'q17', question: "What is DRIP?", options: ["Water leaking", "Dividend Reinvestment Plan", "Daily Return Income Portfolio", "Digital Real Estate Investment"], answer: 1, explanation: "It's the autopilot mode for your dividend loop! 💹" },
    { id: 'q18', question: "Compound Interest is also known as:", options: ["The 8th Wonder", "A bank trick", "Magic money", "Simple math"], answer: 0, explanation: "It's the most powerful force in the financial universe! ❄️" },
    { id: 'q19', question: "Why ask 'How can I buy this with a loop'?", options: ["To sound smart", "To force your brain to find assets instead of just spending cash", "To get a loan", "To avoid the shop"], answer: 1, explanation: "It shifts your mindset from a Consumer to a Builder! 🧠" },
    { id: 'q20', question: "The ultimate Wealth Loop is:", options: ["Lottery → Spend → Broke", "Earn → Invest → Compound → Freedom", "Borrow → Spend → Debt → Work", "Work → Tax → Spend → Zero"], answer: 1, explanation: "It's the most reliable path to a free life! 🏆" }
  ],

  relatedTopics: ['investing', 'personal_finance', 'real_estate_finance'],
};
