// ─────────────────────────────────────────────────────────
//  TOPIC: FREE WILL
//  Category: Philosophy & Neuroscience
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'free_will',
  title: 'Free Will',
  subtitle: 'Are You Just a Biological Robot? 🤖🧬',
  emoji: '🤖',
  category: 'Philosophy',
  accentKey: 'free_will',

  hook: {
    question: "Think of a random color right now. You chose it freely, right? But what if neuroscientists could scan your brain and tell you which color you were going to pick, 300 milliseconds BEFORE you were consciously aware of your own choice?",
    reveal: "Welcome to the terrifying debate over **Free Will**.\n\nFor most of history, we assumed that we are the conscious authors of our lives. But modern physics and neuroscience suggest a disturbing alternative: Every thought you have is just the unavoidable result of chemical reactions in your brain, dictated by the laws of physics tracing all the way back to the Big Bang. \nIf everything is just atoms bouncing in a predictable chain reaction, do you actually make any choices? Are you a free mind, or just a biological robot? Let's break the illusion. 🧠🔬",
    emoji: '🔬',
  },

  theory: [
    {
      id: 'what_is_free_will',
      title: "What is Free Will? 🦅",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'wind',
      svgIcon: 'star',
      content: "Traditionally, **Free Will** means that you could have acted differently. \nIf you chose to eat a salad today, free will means that rewinding the universe to that exact moment, you could have miraculously chosen a burger instead. \nIt implies that your conscious 'Mind' sits outside the physical rules of the universe and acts as a pure, uncaused 'First Cause'.",
      highlight: "If you don't have free will, you are essentially a passenger watching a movie of your own life. 🍿",
    },
    {
      id: 'hard_determinism',
      title: "Hard Determinism ⛓️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'lock',
      svgIcon: 'lock',
      content: "**Determinism** is the belief that every single event in the universe, including human action, is the direct, unavoidable result of prior causes.\nThink of the universe as a giant game of billiards. When the cue ball breaks the triangle, every ball's path is strictly predictable if you know the physics. \nDeterminists argue that your brain is just a biological billiard table. Atoms bounce mechanically, causing thoughts.",
      highlight: "In a deterministic universe, the decision you just made was guaranteed to happen 14 billion years ago. 🕰️",
    },
    {
      id: 'laplaces_demon',
      title: "Laplace's Demon 👁️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'eye',
      svgIcon: 'eye',
      content: "In 1814, Pierre-Simon Laplace proposed a famous thought experiment:\nImagine a super-intelligent computer (a Demon) that knows the exact location and momentum of every single atom in the universe right now, and perfectly understands the laws of physics.\nBecause physics is strict cause-and-effect, this Demon could accurately calculate the entire future of the universe. It could predict what you will eat for breakfast in 10 years.",
      highlight: "If the future is 100% predictable, then the future is already written. 📖",
    },
    {
      id: 'the_illusion',
      title: "Why does it *feel* like I have free will? 🎭",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'cloud-off',
      svgIcon: 'cloud',
      content: "Arthur Schopenhauer famously said: *'A man can do what he wants, but not want what he wants.'*\nSure, you can grab a cup of coffee because you 'wanted' to. But *why* did you want it? You didn't consciously create the desire for coffee. The desire just popped into your consciousness from your subconscious biology, and you obeyed it.\nYou feel free because you are acting out your desires, but you do not author the desires themselves.",
      highlight: "You cannot choose your own desires. They are given to you by genetics and environment. 🧬",
    },
    {
      id: 'the_libet_experiment',
      title: "The Libet Experiment (Neuroscience) 🔬",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "In the 1980s, Benjamin Libet ran a terrifying experiment. He hooked subjects up to EEG brain scanners and told them to flex their wrist whenever they felt the 'urge' to do so.\nThe results broke philosophy: The brain scanner detected the decision to move a full 300 milliseconds BEFORE the person was consciously aware they had made a choice.\nYour subconscious brain makes the decision first in the dark, and then later 'notifies' your conscious mind.",
      highlight: "By the time you 'decide' to do something, your brain has already started doing it. 🧠",
    },
    {
      id: 'genes_and_environment',
      title: "Nature vs. Nurture 🌍",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'globe',
      svgIcon: 'users',
      content: "Sam Harris, a modern determinist, argues that every choice you make is the result of exactly two things:\n1. Your Genetic DNA (which you didn't choose).\n2. Your Environment and upbringing (which you didn't choose).\nSince the only things constructing your mind are things you had zero control over, claiming 'my mind made a free choice' makes no logical sense.",
      highlight: "You are a victim of a biological and environmental lottery. 🎰",
    },
    {
      id: 'libertarian_free_will',
      title: "Libertarian Free Will 🦅",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'feather',
      svgIcon: 'target',
      content: "The opposite of Determinism is **Libertarian Free Will** (not the political party!).\nThis is the belief that human consciousness is special. It breaks the laws of physics. We are 'Unmoved Movers'. \nThis requires believing in Dualism—that the 'Mind' or 'Soul' is made of magic, non-physical stuff, and can somehow forcefully guide our physical brain atoms to make choices.",
      highlight: "This framework is required by almost all major religions, otherwise God is punishing robots. ⚖️",
    },
    {
      id: 'quantum_mechanics',
      title: "Does Quantum Mechanics Save Us? ⚛️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'aperture',
      svgIcon: 'star',
      content: "Determinists relied on classical physics (billiard balls). But in the 1920s, Quantum Mechanics proved that subatomic particles do NOT follow predictable, strict cause-and-effect rules. Quantum events are truly random.\nMany people cheered: *'Aha! The universe isn't perfectly deterministic! Free will is saved!'*\nBut wait: If your decisions are driven by random quantum accidents in your brain, then your actions are random. *Randomness* is not *Freedom*.",
      highlight: "If a quantum dice roll makes you slap someone, you still didn't 'freely' choose to do it. 🎲",
    },
    {
      id: 'compatibilism',
      title: "Compatibilism (The Compromise) 🤝",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'shuffle',
      svgIcon: 'activity',
      content: "**Compatibilism** (held by philosophers like Daniel Dennett) tries to merge the two.\nThey admit that Determinism is real: Yes, physics rules the brain. \nBut they redefine 'Free Will'. They say: You have 'Free Will' as long as no one is *physically holding a gun to your head*. Even if your inner desires are determined by biology, as long as you are free to *act* on those determined desires without external coercion, you are 'free'.",
      highlight: "Compatibilists say Hard Determinists are using an impossible, magical definition of freedom. 📖",
    },
    {
      id: 'the_problem_with_compatibilism',
      title: "Just Changing the Definition? 📝",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'edit-2',
      svgIcon: 'eye',
      content: "Hard determinists (like Sam Harris) hate Compatibilism. They accuse them of changing the dictionary definition of Free Will just to avoid a depressing truth.\nKant famously called Compatibilism a 'wretched subterfuge' (a miserable trick) and 'word jugglery'.\nIf a puppet loves its strings, it is still a puppet.",
      highlight: "Calling a completely determined action 'free' is just playing games with language. 🎭",
    },
    {
      id: 'morality_and_justice',
      title: "If We Are Robots, What About Justice? ⚖️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'shield',
      svgIcon: 'lock',
      content: "This is the terrifying social problem. If a murderer was biologically destined to murder due to bad brain chemistry and a terrible childhood, how can we blame him?\nIf Hard Determinism is true, 'Retributive Justice' (punishing people because they 'deserve' to suffer) is pure sadism. You are torturing a malfunctioning robot.\nInstead, the justice system should only be about *rehabilitation* and *containment* (keeping dangerous machines locked away to protect others).",
      highlight: "Without free will, revenge is illogical. We must replace hatred with pity. 🛑",
    },
    {
      id: 'the_tumor',
      title: "The Brain Tumor Defense 🧠",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'alert-circle',
      svgIcon: 'flame',
      content: "In 1966, Charles Whitman murdered 16 people in Texas. Before dying, he wrote a note begging for an autopsy, because he couldn't control his violent thoughts.\nDoctors found a pecan-sized tumor pressing against his amygdala (the brain's emotion center). The tumor made him do it. We instantly forgive him.\nBut Determinists argue: ALL human behavior is caused by brain structures. A tumor is just a really obvious one. Therefore, no one is truly 'guilty'.",
      highlight: "We are all at the mercy of our brain chemistry. 🧪",
    },
    {
      id: 'fatalism',
      title: "Fatalism (Why get out of bed?) 🛌",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'cloud',
      content: "If the future is already written, shouldn't you just stay in bed? This is **Fatalism**.\nBut Determinism is not Fatalism. Staying in bed is an action that will cause a consequence (getting fired).\nYour choices absolutely still *matter* in terms of cause-and-effect. It's just that the choice you eventually make was always going to be the choice you made.",
      highlight: "Your actions are guaranteed, but they are still the bridge to the future. 🌉",
    },
    {
      id: 'illusion_of_self',
      title: "The Illusion of the 'Self' 👤",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'user-x',
      svgIcon: 'zap',
      content: "Eastern philosophy (like Buddhism) figured this out thousands of years before neuroscientists.\nThey realized that if you sit in meditation long enough, you see that you do not 'think' your thoughts. Thoughts simply appear out of the void of consciousness.\nThere is no 'Self' or 'CEO' inside your brain making choices. There is only a stream of experiences happening on their own.",
      highlight: "Thoughts think themselves. 🧘‍♂️",
    },
    {
      id: 'conclusion',
      title: "The Empathy Upgrade 💖",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'heart',
      svgIcon: 'star',
      content: "Accepting a lack of free will does not have to be depressing. It is actually the ultimate key to human empathy.\nIf you realize that every annoying, mean, or successful person is just reacting to their genetic lottery and past trauma, arrogance dissolves. Hatred dissolves. \nYou realize we are all in the exact same boat, riding a wave we do not control.",
      highlight: "Forgive everyone, including yourself. No one authored their own brain. 🌊",
    },
  ],

  lab: {
    title: "The Prediction Engine 🔮",
    description: "Welcome to Laplace's Demon terminal. As a biological machine, your brain follows patterns. Play a quick game of 'Rock, Paper, Scissors' against the AI. Can the algorithm analyze your subconscious patterns and predict your 'free' choices before you make them?",
    hint: "Humans are terrible at being random. If you try to 'outsmart' the computer, you will fall into an even more predictable psychological pattern.",
    scientistModeHint: "Markov Mode 🧑‍🔬: The engine tracks non-random state transitions. If you played Rock twice, the probability of Paper increases due to the gambler's fallacy.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do humans feel a 'CEO' inside their head?", answer: "Evolutionarily, consciousness is a biological dashboard. Just like a car's dashboard shows you speed and fuel but doesn't actually 'drive' the engine, consciousness gives you a summary of what the brain is doing. But the dashboard mistakes itself for the driver. Our ego creates the illusion of a 'Self' to help us navigate social structures. 🏎️", emoji: '🧠' },
    { id: 'dyk2', question: "Can Quantum Randomness give us Free Will?", answer: "No. Think about it: If the neurons firing in your brain are determined solely by the strict laws of physics, you are a robot. But if those neurons suddenly fire because of a totally 'random' quantum glitch, you are now a malfunctioning robot acting on a glitch. Neither scenario gives your 'Consciousness' the control. Randomness destroys free will just as much as determinism does. 🎲", emoji: '⚛️' },
    { id: 'dyk3', question: "Why did the Supreme Court care about neuroscience?", answer: "Because the entire legal system relies on 'Mens Rea' (Guilty Mind)—the idea that the criminal *freely chose* to commit the crime. As brain scans get better, defense attorneys increasingly argue: 'My client's pre-frontal cortex is chemically damaged. He literally could not control his impulses. It's not a crime, it's a medical condition.' This threatens the very foundation of criminal justice. ⚖️", emoji: '🏛️' },
    { id: 'dyk4', question: "Why is 'Compatibilism' the most popular view among philosophers?", answer: "Because Hard Determinism is too depressing and destroys the legal system, while Libertarian Free Will violates the laws of physics. Compatibilism is the safe middle ground. By redefining 'free will' to just mean 'I am not currently in handcuffs', philosophers can accept science while still holding people morally responsible for their actions. 🤝", emoji: '📝' },
    { id: 'dyk5', question: "What did Schopenhauer mean by 'You cannot want what you want'?", answer: "Right now, you might want a slice of pizza. But why don't you want a bowl of gravel? Because your biology dictates your desires. Even if you decide to eat gravel right now just to 'prove me wrong', your new desire is just 'the desire to be rebellious', which was also generated by your brain chemistry. You are always a slave to whatever desire happens to be strongest. 🍕", emoji: '⛓️' },
  ],

  quiz: [
    { id: 'q1', question: "Historically, what does 'Libertarian Free Will' mean in philosophy?", options: ["Political party affiliation", "Consciousness independent of physical laws", "Animals lacking spiritual souls", "Predictability of all events"], answer: 1, explanation: "It requires believing the Mind is pure magic outside of physics. 🦅" },
    { id: 'q2', question: "What is 'Hard Determinism'?", options: ["A physical geological formation", "Events caused by prior conditions", "The belief in nihilism", "A rigorous physical exercise"], answer: 1, explanation: "We are biological billiard balls. ⛓️" },
    { id: 'q3', question: "What was the terrifying implication of 'Laplace’s Demon'?", options: ["Existence of supernatural beings", "Perfect predictability of the future", "Poor scientific methodology", "Technological threat to humanity"], answer: 1, explanation: "If physics is strictly cause-and-effect, the future is unavoidable. 👁️" },
    { id: 'q4', question: "According to Sam Harris and other determinists, your choices are 100% the result of which two things?", options: ["Personal diet and exercise", "Biological inheritance and upbringing", "Astrological and planetary influence", "Supernatural and spiritual forces"], answer: 1, explanation: "You are the victim of a biological lottery. 🌍" },
    { id: 'q5', question: "What did the famous 'Libet Experiment' using brain scanners discover in the 1980s?", options: ["Brain composition is water", "Subconscious choice precedes awareness", "Frequency of human deception", "Evidence of human agency"], answer: 1, explanation: "Your brain decides in the dark, then 'notifies' your conscious mind later. 🔬" },
    { id: 'q6', question: "What does Schopenhauer's quote 'A man can do what he wants, but not want what he wants' mean?", options: ["General state of confusion", "Acting on unchosen desires", "Universal state of sadness", "Negative nature of desire"], answer: 1, explanation: "You can't choose your desires any more than you choose your heartbeat. 🎭" },
    { id: 'q7', question: "Why do some people think Quantum Mechanics 'saves' free will?", options: ["Use of scientific terminology", "Randomness in subatomic particles", "Ability to achieve flight", "Endorsement by famous physicists"], answer: 1, explanation: "However, randomness still isn't freedom. ⚛️" },
    { id: 'q8', question: "Why do Determinists argue that Quantum Mechanics DOES NOT save free will?", options: ["Invalidity of quantum physics", "Randomness is not agency", "Size of subatomic particles", "Complexity of mathematical models"], answer: 1, explanation: "A malfunctioning glitchy robot is still a robot. 🎲" },
    { id: 'q9', question: "What is **Compatibilism**?", options: ["Social networking application", "Acting on desires without coercion", "General social agreement", "Form of political governance"], answer: 1, explanation: "It makes scientific reality compatible with moral responsibility. 🤝" },
    { id: 'q10', question: "Why do Hard Determinists (like Kant and Sam Harris) criticize Compatibilism?", options: ["Dislike of philosophical compromise", "Redefining terms to avoid truth", "Lack of conceptual understanding", "Financial costs of belief"], answer: 1, explanation: "Kant called it a 'wretched subterfuge'. 📝" },
    { id: 'q11', question: "If Hard Determinism is absolutely true, what happens to the concept of 'Retributive Justice' (punishing someone because they 'deserve' it)?", options: ["Improvement of legal systems", "Illogical punishment of machines", "No change in concept", "Increased wealth for judges"], answer: 1, explanation: "Without free will, revenge makes zero logical sense. ⚖️" },
    { id: 'q12', question: "How should a Determinist society structure its justice system?", options: ["Absence of legal rules", "Rehabilitation and societal protection", "Exclusive use of execution", "Practice of public torture"], answer: 1, explanation: "We treat criminals like a dangerous hurricane: contain the damage, don't hate the wind. 🛡️" },
    { id: 'q13', question: "In the Charles Whitman case (the sniper with the brain tumor), what was the philosophical lesson?", options: ["Negative impact of tumors", "Behavior caused by brain structure", "Danger of firearms", "Inherent moral evil"], answer: 1, explanation: "We are all entirely at the mercy of our brain chemistry. 🧠" },
    { id: 'q14', question: "What is 'Fatalism'?", options: ["State of general unhappiness", "Belief that actions are futile", "Affection for destiny", "Excessive food consumption"], answer: 1, explanation: "Determinism says your actions still *cause* the future, they were just predetermined actions. 🛌" },
    { id: 'q15', question: "How does Eastern Philosophy (like Buddhism) view the concept of Free Will?", options: ["Religious prayer for agency", "Absence of a central self", "Belief in ultimate control", "Disregard for the concept"], answer: 1, explanation: "Thoughts think themselves. 🧘‍♂️" },
    { id: 'q16', question: "Why can losing the belief in Free Will actually INCREASE human empathy?", options: ["Transformation into a robot", "Understanding others' lack of control", "Increase in personal wealth", "Inducing a state of sleep"], answer: 1, explanation: "Forgive everyone, they are just riding a biological wave. 💖" },
    { id: 'q17', question: "What is 'Dualism' (a concept required for Libertarian Free Will)?", options: ["Holding multiple occupations", "Non-physical mind controlling matter", "Combat involving swords", "Possession of two brains"], answer: 1, explanation: "Science generally rejects Dualism because it breaks the laws of thermodynamics. 👤" },
    { id: 'q18', question: "According to illusionists, why did evolution give us the illusion of Free Will?", options: ["Divine will and intention", "Biological survival and accountability", "Deception of artificial intelligence", "Aesthetic appeal of agency"], answer: 1, explanation: "It is an incredibly useful survival dashboard. 🧬" },
    { id: 'q19', question: "If you try to prove you have free will by doing something completely random right now, what does a Determinist say?", options: ["Praise for the attempt", "Rebellion was biologically determined", "Disruption of the simulation", "High level of intelligence"], answer: 1, explanation: "The brain just shifted into \"prove him wrong\" mode. 🤖" },
    { id: 'q20', question: "Which philosopher called Compatibilism 'word jugglery'?", options: ["Socrates", "Immanuel Kant", "Plato", "Karl Marx"], answer: 1, explanation: "He hated changing the definition of words to hide from the truth. 🛑" },
  ],

  relatedTopics: ['consciousness', 'ethics_morality', 'absurdism'],
};
