// ─────────────────────────────────────────────────────────
//  TOPIC: ORGANIC CHEMISTRY - THE SCIENCE OF LIFE
//  Category: Chemistry / Advanced
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'organic_chemistry',
  title: 'Organic Chemistry',
  subtitle: 'The architecture of carbon-based life 💎🧬',
  emoji: '🧬',
  category: 'Chemistry',
  accentKey: 'organic',

  hook: {
    question: "How can the same element (Carbon) be found in the lead of your pencil, the diamond in a ring, and even the DNA in your cells? ✏️💎🧬",
    reveal: "Because Carbon is the 'LEGO brick' of the universe! It has a unique ability to bond with itself and other atoms into nearly infinite shapes—long chains, complex rings, and double-helix spirals. Organic Chemistry is the study of these Carbon structures. It covers everything from the plastics in your phone to the proteins in your muscles. Let's learn to build life! 🏗️",
    emoji: '🧪',
  },

  theory: [
    {
      id: 'carbon_versatility',
      title: 'The Versatile Carbon 💎',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '💎',
      svgIcon: 'atom',
      content: "Carbon is the 'Superstar' of the periodic table. Why? Because it has exactly **4 valence electrons** 8️⃣.\n\nThis means it's perfectly balanced. It can share electrons with four other atoms at once, forming incredibly stable 'Tetrahedral' shapes. Carbon also has a special property called **Catenation**—the ability to form long, stable chains and branches with itself. \n\nWithout Carbon's ability to build complex, 3D structures, life as we know it would be impossible. We are quite literally 'Carbon-Based Lifeforms.' 🌊",
      highlight: "Carbon's 4 valence electrons make it the ultimate building block for complexity. 🧱",
    },
    {
      id: 'hydrocarbons',
      title: 'Hydrocarbons: The Fuel ⛽',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '⛽',
      svgIcon: 'zap',
      content: "The simplest organic molecules are **Hydrocarbons**—made only of Carbon and Hydrogen. They are the primary source of the world's energy.\n\n• **Alkanes:** Single bonds only ($C-C$). Used for heating gas (Methane, Propane) 🔥.\n• **Alkenes:** At least one double bond ($C=C$). Used to make plastics (Ethylene).\n• **Alkynes:** At least one triple bond ($C≡C$). Extremely high energy (Acetylene torches) 🔦.\n\nAs the carbon chain gets longer (Pentane, Hexane, Octane), the molecule changes from a gas to a liquid like gasoline! ⛽",
      highlight: "Every fuel you use is just a chain of Carbon and Hydrogen. ⚡",
    },
    {
      id: 'functional_groups',
      title: 'Functional Groups: The Personality 🎭',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🎭',
      svgIcon: 'flask',
      content: "A hydrocarbon is just the 'skeleton'. To give it a 'personality', we add **Functional Groups**.\n\nImagine a generic car. Adding a siren makes it a police car 🚔; adding a ladder makes it a fire truck 🚒. \n\n• **Hydroxyl (-OH):** Turns the molecule into an **Alcohol** (like ethanol in hand sanitizer) 🧼.\n• **Carboxyl (-COOH):** Turns it into an **Organic Acid** (like the acetic acid in vinegar) 🥗.\n• **Amine (-NH2):** Found in proteins and DNA—essential for biology. 🧬",
      highlight: "Functional groups determine exactly how an organic molecule will behave and react. 🧪",
    },
    {
      id: 'isomers',
      title: 'Isomers: The Molecular Twins 👯',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '👯',
      svgIcon: 'grid',
      content: "**Isomers** are molecules that have the same exact atoms (formula) but arranged in a different shape 🧩.\n\nIt's like having 10 LEGO bricks. You can build a tower or a square. Even though they have the same bricks, the two buildings look and act differently.\n\nIn medicine, isomers are critical. One version might cure a headache, while its twin (mirror image) might be completely useless or even toxic! Shape is everything in organic chemistry. 💊",
      highlight: "Two molecules can have the same 'parts' but completely different 'fates' based on their shape. 🧬",
    },
    {
      id: 'polymers_plastics',
      title: 'Polymers: Giant Molecules 🧶',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧶',
      svgIcon: 'link',
      content: "**Polymers** are giant molecules made of thousands of repeating units called 'Monomers' ⛓️.\n\nNature uses polymers for everything: Cellulose in trees 🌳, DNA in cells, and Proteins in silk. \n\nHumans learned to make synthetic polymers, which we call **Plastics**. By changing the monomer (the LEGO brick), we can make plastic that is clear like water bottles, stretchy like spandex, or strong enough to stop a bullet like Kevlar! 🛡️",
      highlight: "We live in the 'Polymer Age'—almost every object you touch is a long chain of repeats. 🧱",
    },
    {
      id: 'aromatics',
      title: 'Aromatics: The Rings of Smell 🍎',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🍎',
      svgIcon: 'star',
      content: "Some carbon atoms bond into rings of 6, called **Benzene rings** 🎡. These are known as **Aromatic** compounds.\n\nThey got this name because many of them have very strong smells. The smell of vanilla, cinnamon, and almonds all come from aromatic rings. 👃\n\nBeyond just smelling nice, these rings are incredibly stable and form the basis of many modern spices, dyes, and medicines like Aspirin. 💊",
      highlight: "Beautiful smells and vital medicines often start with a simple ring of 6 carbons. 💍",
    },
    {
      id: 'saturated_vs_un',
      title: 'Saturated vs Unsaturated Fats 🍔',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🍔',
      svgIcon: 'target',
      content: "You've seen these words on food labels, but they are pure organic chemistry terms!\n\n• **Saturated:** Every carbon is 'Saturated' with hydrogen. The chain is straight 📏. These pack together tightly, turning into solids (like butter or animal fat).\n• **Unsaturated:** There is a double bond ($C=C$). This causes a 'kink' or bend in the chain 🦴. Because they are bent, they can't pack tightly and stay liquid at room temperature (like olive oil) 🫒.\n\nYour body needs both, but 'Trans-fats' (artificially straightened fats) can clog your arteries! 🚫",
      highlight: "The difference between butter and oil is just a single double-bond kink! 🧈",
    },
    {
      id: 'alcohols_acids',
      title: 'Alcohols, Acids & Esters 🍷🐢',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🍷',
      svgIcon: 'beaker',
      content: "When Alcohols meet Organic Acids, a magical reaction called **Esterification** happens ✨.\n\nThey combine to form an **Ester** and release water. Esters are the molecules responsible for almost all fruity smells! 🍓🍍\n\n• Ethanol + Acetic Acid $\\rightarrow$ Ethyl Acetate (smells like fruit/nail polish remover).\n• If you add an -OH group to a ring, you get **Phenol**, which was the world's first surgical antiseptic! 🧼",
      highlight: "Fruity scents and sterile surgery rooms are both thanks to functional group swaps. 🍍",
    },
    {
      id: 'biomolecules',
      title: 'The Big Four: Biomolecules 🥩🍰',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🥩',
      svgIcon: 'sparkle',
      content: "Everything in your body is made from four 'Super-Organic' molecules:\n\n1. **Carbohydrates:** Chains of sugars used for fast energy (Bread, Fruit) 🔋.\n2. **Lipids:** Long chains (fats) used for long-term storage and cell walls 🛡️.\n3. **Proteins:** Complex folded chains of amino acids (Muscles, Enzymes) 💪.\n4. **Nucleic Acids:** Your DNA and RNA—the information storage for life 🧬.\n\nEach one is just a variation of Carbon, Hydrogen, Oxygen, and Nitrogen. ☁️",
      highlight: "You are essentially a very complex, self-replicating organic chemical reaction. 🧬",
    },
    {
      id: 'future_carbon',
      title: 'The Future: Carbon Tech 🚀',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🚀',
      svgIcon: 'cpu',
      content: "Organic chemistry isn't just about old chemicals; it's the future of technology.\n\n• **Graphene:** A single-atom-thick sheet of carbon that is 200x stronger than steel! 🛡️\n• **Carbon Nanotubes:** Tiny tubes that could eventually build a 'Space Elevator' to reach orbit 🌌.\n• **OLEDs:** The screen on your phone likely uses 'Organic Light-Emitting Diodes'—carbon molecules that glow when shocked with electricity! 📱\n\nThe age of metals is shifting toward the age of Carbon. 💎",
      highlight: "From your phone screen to space elevators, the future is Carbon. 💎",
    },
  ],

  lab: {
    title: "Molecule Architect Lab 🧱🧬",
    description: "Become a molecular engineer! Start with a carbon base and snap on Functional Groups like Alcohol (-OH) or Acid (-COOH). Watch how the molecule's properties change, see its 3D 'sp3' bond structure, and discover its real-world use case in real-time! 🧪",
    hint: "Try building 'Ethanol' by adding 2 Carbons and a Hydroxyl group. Or try 'Acetic Acid' (Vinegar) by adding a Carboxyl group. Watch the name update at the top!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks IUPAC nomenclature rules, bond-angle calculations ($109.5^\\circ, 120^\\circ, 180^\\circ$), and hybridization ($sp^1, sp^2, sp^3$) labels.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why diamonds and pencil lead are made of the same thing? ✏️💎",
      answer: "It's all about 'Allotropes'! In a diamond, every carbon is bonded to 4 others in a rigid 3D lattice, making it the hardest material on Earth. In graphite (pencil lead), carbons form flat 2D sheets that slide over each other—which is why it leaves a mark on paper! Same atoms, different architecture. 📐",
      emoji: '📐',
    },
    {
      id: 'dyk2',
      question: "Do you know why 'Teflon' pans never let food stick? 🍳",
      answer: "Teflon is Polytetrafluoroethylene (PTFE). It replaces all Hydrogens with Fluorine atoms. Fluorine is so 'greedy' for its own electrons that it refuses to bond or even interact with anything else—even food! The carbon chain is protected by a 'shield' of Fluorine that nothing can penetrate. 🛡️",
      emoji: '🛡️',
    },
    {
      id: 'dyk3',
      question: "Do you know why ripe bananas smell like... bananas? 🍌",
      answer: "Esters! As a banana ripens, enzymes produce **Isoamyl Acetate**, an ester. Just a few molecules of this in the air are enough to trigger your nose. Many candy flavors are actually just 100% pure lab-made esters of specific organic chains! 🍬",
      emoji: '🍌',
    },
    {
      id: 'dyk4',
      question: "Do you know why we call them 'Organic' if they aren't always 'Alive'? 🌿",
      answer: "History! Early scientists believed that carbon-based molecules had a 'Life Force' (Vitalism) and could never be made in a lab. In 1828, Friedrich Wöhler made urea (an animal waste product) from inorganic salt, proving that 'vitalism' was wrong. We kept the name, but now we know organic just means 'The Chemistry of Carbon'. 🕰️",
      emoji: '🧪',
    },
    {
      id: 'dyk5',
      question: "Do you know why carbon monoxide ($CO$) is so deadly? 💨🚫",
      answer: "Molecular Hijacking! Your blood's hemoglobin is designed to carry Oxygen ($O_2$). But Carbon Monoxide is an organic 'mimic' that bonds to hemoglobin 200x more tightly than oxygen does. It takes the seat and refuses to leave, effectively 'suffocating' your cells from the inside out. 🛑",
      emoji: '💀',
    },
  ],

  quiz: [
    { id: 'q1', question: "How many valence electrons does Carbon have?", options: ["2", "4", "6", "8"], answer: 1, explanation: "Having 4 electrons allows Carbon to form four stable bonds, making it the perfect building block! 🍀" },
    { id: 'q2', question: "What is a 'Hydrocarbon' made of?", options: ["Hydrogen and Oxygen", "Carbon and Hydrogen", "Carbon and Water", "Nitrogen and Carbon"], answer: 1, explanation: "These simple molecules form the basis of all fuels like methane and gasoline! ⛽" },
    { id: 'q3', question: "Which functional group turns a chain into an ALCOHOL?", options: ["The carboxyl group", "The hydroxyl group", "The amine group", "The methyl group"], answer: 1, explanation: "The Hydroxyl group (-OH) is the signature of all alcohols! 🧼" },
    { id: 'q4', question: "Molecules with the same formula but different shapes are called:", options: ["Isotopes", "Isomers", "Ions", "Allotropes"], answer: 1, explanation: "Isomers prove that in organic chemistry, architecture is just as important as atoms! 👯" },
    { id: 'q5', question: "Giant molecules made of repeating units (monomers) are called:", options: ["Atoms", "Polymers", "Electrolytes", "Isomers"], answer: 1, explanation: "From DNA to plastics, polymers are the giants of the molecular world! 🧶" },
    { id: 'q6', question: "Why is a double-bond 'kink' important in cooking oils?", options: ["Improves the overall flavor", "Keeps the oil liquid", "Raises the boiling point", "Increases the vitamin content"], answer: 1, explanation: "These kinks define the difference between solid butter and liquid oil! 🫒" },
    { id: 'q7', question: "Which shape does a single carbon atom usually form when bonding to four others?", options: ["Flat square shape", "Tetrahedral pyramid shape", "Straight linear shape", "Circular ring shape"], answer: 1, explanation: "The 109.5° angle of a tetrahedron provides the most stable spacing! 📐" },
    { id: 'q8', question: "Found in proteins, which functional group contains Nitrogen?", options: ["The carboxyl group", "The hydroxyl group", "The amine group", "The phosphate group"], answer: 2, explanation: "Amines are essential for amino acids, the building blocks of muscles! 💪" },
    { id: 'q9', question: "The reaction between an alcohol and an acid to produce a fruity smell is:", options: ["Oxidation", "Esterification", "Combustion", "Fermentation"], answer: 1, explanation: "Esters are nature's perfumes! 🍓" },
    { id: 'q10', question: "What is an 'Aromatic' compound's signature structure?", options: ["Long straight carbon chain", "Six carbon benzene ring", "Cross shaped carbon structure", "Four carbon square structure"], answer: 1, explanation: "Benzene rings are incredibly stable and common in spices and medicine! 🍩" },
    { id: 'q11', question: "Which polymer makes up the structure of trees and paper?", options: ["Starch molecules", "Cellulose fibers", "Polyethylene chains", "DNA strands"], answer: 1, explanation: "Cellulose is the most abundant organic polymer on Earth! 🌳" },
    { id: 'q12', question: "Carbon Nanotubes are roughly how many times stronger than steel?", options: ["2x", "10x", "100x", "10,000x"], answer: 2, explanation: "Their unique atomic structure makes them the strongest tension material known! 🏗️" },
    { id: 'q13', question: "What is the simplest hydrocarbon (one carbon, four hydrogens)?", options: ["Ethane", "Methane", "Propane", "Butane"], answer: 1, explanation: "Methane (CH4) is a powerful greenhouse gas and fuel! 🔥" },
    { id: 'q14', question: "Why do 'saturated' fats stay solid at room temperature?", options: ["They have higher mass", "Straight chains pack tightly", "They lack carbon atoms", "They are naturally frozen"], answer: 1, explanation: "Like stacked bricks, straight chains don't slide easily! 🧱" },
    { id: 'q15', question: "The study of Carbon and its compounds was named 'Organic' because:", options: ["Derived from only plants", "Linked to living things", "Stands for oxygen rich", "Named for marketing reasons"], answer: 1, explanation: "We now know we can make them in labs, but the historical name stuck! 🏺" },
    { id: 'q16', question: "Nucleic acids (DNA) primarily store which of the following?", options: ["Energy storage", "Genetic information", "Structural support", "Thermal regulation"], answer: 1, explanation: "DNA is the hard drive of your body's biological programming! 🧬" },
    { id: 'q17', question: "Surgical antiseptic was first pioneered using which organic compound?", options: ["Simple sugar", "Phenol compound", "Refined gasoline", "Distilled vinegar"], answer: 1, explanation: "Lister used Phenol to save millions of people from post-surgery infections! 🧼" },
    { id: 'q18', question: "Which element is the ONLY one capable of building life's complex chains?", options: ["Silicon element", "Gold element", "Carbon element", "Iron element"], answer: 2, explanation: "Carbon's 4-bond stability and catenation are unique in the universe! 💎" },
    { id: 'q19', question: "An organic molecule that tastes sour (like vinegar or lemon) likely has which group?", options: ["The alcohol group", "The carboxylic group", "The amine group", "The alkene group"], answer: 1, explanation: "The Carboxyl group (-COOH) donates H+ ions, creating that sour acid taste! 🍋" },
    { id: 'q20', question: "Polymers like plastics are mostly made from which raw material?", options: ["Natural wood", "Crude oil", "Iron ore", "Salt water"], answer: 1, explanation: "We refine the carbon chains found in oil to build our modern world of plastics! ⛽" },
  ],

  relatedTopics: ['atoms_molecules', 'chemical_bonding', 'biochemistry_basics'],
};
