// ─────────────────────────────────────────────────────────
//  TOPIC: EMOTIONS & MOTIVATION
//  Category: Psychology / Neuroscience
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'emotions_motivation',
  title: 'Emotions & Motivation',
  subtitle: 'The chemical drivers of your life 🧠⚡',
  emoji: '🧠',
  category: 'Psychology',
  accentKey: 'emotions',

  hook: {
    question: "Why do you feel a knot in your stomach when you're nervous, or a warm glow in your chest when you see someone you love? ❤️",
    reveal: "Because emotions aren't just 'feelings'—they are a high-speed survival system! Your brain uses a cocktail of chemicals (neurotransmitters) and electrical signals to tell your body exactly how to react to the world before you even have a conscious thought. Motivation is the 'fuel' that these emotions create to drive you toward your goals. Let's look under the hood of your mind! 🏎️💨",
    emoji: '🔥',
  },

  theory: [
    {
      id: 'what_is_emotion',
      title: 'What are Emotions? 🎭',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🎭',
      svgIcon: 'brain',
      content: "An emotion is a complex psychological state that involves three distinct components: \n1. **Subjective Experience:** How YOU feel (Happy, Sad, Angry) 😊.\n2. **Physiological Response:** What your body does (Heart rate up, sweating, pupils dilating) 💓.\n3. **Behavioral Response:** Your expression or action (Smiling, running away, yelling) 🏃‍♂️.\n\nEmotions are your brain's 'Compass'. They tell you what is important, what is dangerous, and what is worth doing again.",
      highlight: "Emotions are the body's 'Action Signals'—designed to move us toward survival! 🏃‍♀️",
    },
    {
      id: 'limbic_system',
      title: 'The Emotional Center 🏛️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'target',
      content: "Emotions aren't made in your 'thinking' brain (the Cortex). They are born in the deeper, older **Limbic System** 🧠.\n\n• **Amygdala:** The 'Alarm'. It processes fear and survival instincts in milliseconds. It tells you to jump *before* you even see the snake 🐍.\n• **Hippocampus:** It attaches memories to emotions. This is why you remember your $1^{st}$ heartbreak or your graduation so vividly 🎓.\n• **Hypothalamus:** The command center that sends the 'Emergency' signals to your heart and lungs.",
      highlight: "The Amygdala can 'hijack' your brain, making you react before you think! 🛑",
    },
    {
      id: 'dopamine_reward',
      title: 'The Motivation Molecule 🏆',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🏆',
      svgIcon: 'zap',
      content: "**Dopamine** is the molecule of 'More'. It is the chemical basis for **Motivation**.\n\nContrary to popular belief, Dopamine isn't just about 'pleasure'. It is about the *Anticipation* of a reward. It is the chemical that makes you want to check your phone, finish a game, or go for a run 🏃.\n\nWhen we achieve something, the 'Reward Pathway' (VTA/Nucleus Accumbens) fires a burst of Dopamine. This feels so good that our brain records exactly how we did it so we can repeat the behavior in the future! 🔄",
      highlight: "Dopamine is the 'Chase' molecule—it drives us toward our goals. 🎯",
    },
    {
      id: 'basic_vs_complex',
      title: 'Basic vs Complex Emotions 🧭',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🧭',
      svgIcon: 'grid',
      content: "Psychologist Paul Ekman discovered 7 **Basic Emotions** that are universal to every human on Earth, regardless of culture: Joy, Sadness, Anger, Fear, Disgust, Surprise, and Contempt 🌍.\n\n**Complex Emotions** (like Guilt, Pride, or Jealousy) are like 'secondary colors'. They are a mix of basic emotions and sociocultural learning.\n\nFor example, **Awe** is a mix of Surprise and Fear; **Nostalgia** is a mix of Joy and Sadness. Your emotional palette is as diverse as a painter's canvas! 🎨",
      highlight: "Basic emotions are 'hardware' we are born with; complex ones are 'software' we learn. 💻",
    },
    {
      id: 'intrinsic_vs_ex',
      title: 'Why do we do things? ⛽',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '⛽',
      svgIcon: 'waves',
      content: "Motivation comes from two different gas tanks:\n\n• **Extrinsic Motivation:** Doing something for a reward (Money, Grades, Applause) 🏆. This is great for short-term tasks, but can fade quickly.\n• **Intrinsic Motivation:** Doing something because the activity itself is the reward (Learning for fun, playing an instrument you love) 🎸. \n\nResearch shows that if you start paying someone for a hobby they love, their intrinsic motivation actually *drops*! This is the Overjustification Effect. 📉",
      highlight: "Intrinsic motivation (joy from the work) is the secret to long-term success. 🌟",
    },
    {
      id: 'regulatory_brain',
      title: 'Emotional Regulation 🧘',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🧘',
      svgIcon: 'sparkle',
      content: "Self-control is the battle between your **Amygdala** (The Child) and your **Prefrontal Cortex** (The Adult) 🧠.\n\nWhen you feel an intense emotion, your PFC tries to 'appraise' the situation. This is called **Cognitive Reappraisal**. \nInstead of thinking 'I'm terrified of this speech,' you can tell your brain 'I'm excited for this opportunity!' 🎤\n\nBy changing the *Label* you give to the biological feeling, you can actually change the result of the emotion! This is the core of Emotional Intelligence (EQ).",
      highlight: "The Prefrontal Cortex is the 'CEO' that calms down the emotional alarms. 🏛️",
    },
    {
      id: 'maslow_hierarchy',
      title: 'The Pyramid of Needs 🏔️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🏔️',
      svgIcon: 'book',
      content: "Abraham Maslow proposed that our motivations are arranged in a **Hierarchy of Needs**:\n\n1. **Physiological:** Air, food, water, sleep 🥗.\n2. **Safety:** Job, home, health 🏠.\n3. **Love/Belonging:** Friends, family 🫂.\n4. **Esteem:** Respect, status, confidence 🎖️.\n5. **Self-Actualization:** Reaching your full potential 🌟.\n\nYou generally cannot focus on your 'Grand Purpose' (Top) if you are hungry or scared (Bottom). Your brain prioritizes survival before self-improvement. 🧱",
      highlight: "Motivation flows from survival at the bottom to fulfillment at the top. 🔝",
    },
    {
      id: 'stress_response',
      title: 'The Stress Loop 🚨',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🚨',
      svgIcon: 'zap',
      content: "Stress is your brain's reaction to a challenge. It triggers the **HPA Axis**, releasing **Cortisol** and Adrenaline 🧪.\n\n• **Eustress (Good Stress):** Short-term excitement that helps you perform (like before a big game) ⚡.\n• **Distress (Bad Stress):** Long-term pressure that breaks down the body and mind 📉.\n\nChronic stress keeps the Amygdala 'on' all the time, which can actually shrink the Hippocampus (where memories are made). This is why it's so hard to learn when you're stressed out! 🤯",
      highlight: "Small stress keeps you sharp; chronic stress wears you down. ⚖️",
    },
    {
      id: 'facial_feedback',
      title: 'The Smile Hack 😃',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '😃',
      svgIcon: 'eye',
      content: "The **Facial Feedback Hypothesis** suggests that your muscles can tell your brain how to feel. \n\nIf you force yourself to smile (by holding a pencil in your teeth), your brain receives signals from your facial nerves and starts releasing 'happy' chemicals! 🧪\n\nIt's a two-way street: Emotions move your face, but moving your face can move your emotions. Power-posing or standing tall can actually lower your Cortisol and raise your Confidence! 💪",
      highlight: "You can 'trick' your brain into feeling better just by changing your body language. ✨",
    },
    {
      id: 'flow_state',
      title: 'Flow: The Ultimate State 🌊',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌊',
      svgIcon: 'waves',
      content: "The peak of motivation is called **Flow** (being 'in the zone') 🏄.\n\nThis happens when a task is perfectly balanced—not too easy (Boredom) and not too hard (Anxiety). In Flow, you lose track of time, your ego vanishes, and you perform at your absolute best ⏱️.\n\nBiologically, your brain shuts down its expensive 'Inner Critic' (Self-Monitoring) to focus 100% on the task. This is the state of mind where masters like Athletes, Artists, and Programmers do their best work. 🎨🖌️",
      highlight: "Flow is the 'Sweet Spot' between boredom and anxiety. 🎯",
    },
  ],

  lab: {
    title: "The Emotional Dashboard 🧠🎛️",
    description: "Take control of the brain's heavy machinery! Balance the sliders for Dopamine, Serotonin, and Cortisol. Trigger external life events like 'Win 🏆', 'Fail 📉', or 'Meditate 🧘' and watch how the chemical balance shifts your mood in real-time. Can you find the recipe for 'Flow'? 🧪",
    hint: "Try triggering a 'Stress' event and then use 'Breathing Exercises' to lower your Cortisol levels. Watch how the Prefrontal Cortex (the Adult) tries to calm down the glowing Amygdala (the Alarm).",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks VTA/Nucleus Accumbens firing rates, synaptic neurotransmitter density, and Cortisol decay constants.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why children born blind still smile when they are happy? 😊",
      answer: "Because basic emotions are 'Hardcoded' into your genes! They haven't seen a smile to copy it—their brain simple knows the command to lift the corners of the mouth when the 'Reward Pathway' is triggered. It's a universal human language! 🧬",
      emoji: '🌍',
    },
    {
      id: 'dyk2',
      question: "Do you know why 'Hanger' (Hungry-Anger) is a real biological thing? 🍔😤",
      answer: "Low Blood Sugar! Your brain's self-control (PFC) is the most energy-hungry part of your body. When you're hungry, your brain cuts power to the 'Polite Adult' brain first, leaving the 'Angry Child' brain (Amygdala) in charge of your personality. Feed the brain to fix the mood! 🍩",
      emoji: '🔋',
    },
    {
      id: 'dyk3',
      question: "Do you know why it's so hard to stop scrolling social media? 📱🌀",
      answer: "Variable Reward! Like a slot machine, social media gives you 'Dopamine Hits' at random intervals. Your brain loves 'Maybe' more than 'Yes.' The anticipation of a 'good post' keeps the Dopamine flowing, making the habit incredibly hard to break! 🎰",
      emoji: '🎰',
    },
    {
      id: 'dyk4',
      question: "Do you know why you feel happy when someone ELSE wins a race? 🏃‍♂️✨",
      answer: "Mirror Neurons! Your brain has special cells that fire both when you do something AND when you watch someone else do it. They allow us to feel **Empathy**. Your brain is literally 'simulating' their joy as if it were your own! 🧠👯",
      emoji: '🤝',
    },
    {
      id: 'dyk5',
      question: "Do you know why you can't tickle yourself? 🧤🚫",
      answer: "Prediction! Motivation is tied to your cerebellum's ability to predict movement. When you try to tickle yourself, your motor system tells your brain exactly what's coming. The brain ignores it as 'Unimportant/Known.' Surprise is a key ingredient for the tickle-emotion! 🤫",
      emoji: '🧠',
    },
  ],

  quiz: [
    { id: 'q1', question: "Which brain structure is the 'Emotional Alarm' responsible for fear?", options: ['Hippocampus', 'Amygdala', 'Frontal Lobe', 'Cerebellum'], answer: 1, explanation: "The Amygdala processes danger signals in milliseconds, often before you consciously see the threat! 🚨" },
    { id: 'q2', question: "Which chemical is known as the molecule of 'Motivation and Anticipation'?", options: ['Adrenaline', 'Dopamine', 'Melatonin', 'Sodium'], answer: 1, explanation: "Dopamine drives the 'Chase' for a reward, not just the pleasure of getting it! 🏆" },
    { id: 'q3', question: "How many 'Universal Basic Emotions' did Paul Ekman discover?", options: ['3', '7', '12', '100+'], answer: 1, explanation: "Joy, Sadness, Anger, Fear, Disgust, Surprise, and Contempt are recognized by humans everywhere! 🌍" },
    { id: 'q4', question: "What describes the state of perfect balance where you lose track of time and perform your best?", options: ['Drowsiness', 'Flow State', 'Anxiety', 'Euphoria'], answer: 1, explanation: "Flow happens when a task is perfectly matched to your skill level! 🌊" },
    { id: 'q5', question: "Doing a task for the pure joy of the activity itself is called:", options: ['Extrinsic Motivation', 'Intrinsic Motivation', 'Calculated Motivation', 'Stress'], answer: 1, explanation: "Intrinsic means the 'Inner' reward is enough! 🌟" },
    { id: 'q6', question: "According to Maslow, which needs must be met FIRST before anything else?", options: ['Esteem', 'Safety', 'Physiological (Food/Water)', 'Love'], answer: 2, explanation: "You can't reach your full potential if you are hungry or dying of thirst! 🥗" },
    { id: 'q7', question: "What is the 'good' type of short-term stress that improves performance called?", options: ['Distress', 'Eustress', 'Pro-stress', 'Adrenaline'], answer: 1, explanation: "Eustress (like before a game) keeps you sharp and ready to act! ⚡" },
    { id: 'q8', question: "The 'Smile Hack' (forcing a smile to feel happy) is an example of:", options: ['The Placebo Effect', 'The Facial Feedback Hypothesis', 'Hypnosis', 'Hindsight Bias'], answer: 1, explanation: "Facial nerves send signals back to the brain to trigger 'Happy chemistry'! 😊" },
    { id: 'q9', question: "Which chemical 'breaks down' the body if it stays at high levels due to chronic stress?", options: ['Dopamine', 'Serotonin', 'Cortisol', 'Glucose'], answer: 2, explanation: "Cortisol is the 'Stress Hormone' that can be toxic at high, long-term levels. 📉" },
    { id: 'q10', question: "Which part of the brain acts as the 'Adult' that regulates emotional impulses?", options: ['Amygdala', 'Prefrontal Cortex (PFC)', 'Brainstem', 'Thalamus'], answer: 1, explanation: "The PFC is the CEO of the brain, handling logic and regulation! 🏛️" },
    { id: 'q11', question: "Why do social media companies use 'Variable Rewards' (like slot machines)?", options: ['To save electricity', 'To keep Dopamine levels high through anticipation', 'Because they are random', 'To make you bored'], answer: 1, explanation: "The 'Maybe' of a notification is more addictive than the 'Yes' of a known one! 📱" },
    { id: 'q12', question: "A 'Complex Emotion' like Jelousy or Pride is usually:", options: ['A mix of basic emotions + social learning', 'A myth', 'Only felt by adults', 'Made in the liver'], answer: 0, explanation: "Complex emotions are like the 'secondary colors' of the mind! 🎨" },
    { id: 'q13', question: "Mirror Neurons in the brain are the biological basis for:", options: ['Vision', 'Empathy (feeling others\' feelings)', 'Memory', 'Balance'], answer: 1, explanation: "They fire when we watch others, allowing us to 'simulate' their experience! 🤝" },
    { id: 'q14', question: "The 'Overjustification Effect' says that paying someone for a hobby they love will likely:", options: ['Make them better', 'Decrease their intrinsic motivation', 'Make them happy', 'Have no effect'], answer: 1, explanation: "External rewards can sometimes 'kill' the internal joy of a task! 💸" },
    { id: 'q15', question: "What is 'Emotional Intelligence' (EQ)?", options: ['The ability to do math quickly', 'The ability to recognize and regulate emotions in yourself and others', 'Having no emotions', 'A high IQ score'], answer: 1, explanation: "EQ is often more important for life success than IQ! 🌟" },
    { id: 'q16', question: "Which structure attaches strong emotional weight to your memories?", options: ['The Retina', 'The Hippocampus', 'The Skull', 'The Spinal Cord'], answer: 1, explanation: "The Hippocampus works with the Amygdala to 'save' emotional moments in HD! 🎞️" },
    { id: 'q17', question: "Why is 'Hanger' (Hunger + Anger) common?", options: ['Food makes you mean', 'Low energy makes the Prefrontal Cortex (self-control) shut down', 'Digestion is loud', 'No reason'], answer: 1, explanation: "Self-control is expensive energy-wise; if you're out of fuel, the PFC fails! 🍔" },
    { id: 'q18', question: "What chemical is released during 'Rest and Digest' to calm the heart?", options: ['Adrenaline', 'Serotonin / Acetylcholine', 'Caffeine', 'Oxygen'], answer: 1, explanation: "Serotonin helps stabilize mood and calm the stress response! 🧘" },
    { id: 'q19', question: "Awe is described as a combination of which two basic emotions?", options: ['Joy and Sadness', 'Surprise and Fear', 'Anger and Disgust', 'None of these'], answer: 1, explanation: "Surprise at the scale + Fear/respect of the power = Awe! 🌌" },
    { id: 'q20', question: "In 'Flow State', your brain's 'Inner Critic' (self-monitoring) usually:", options: ['Works harder', 'Shuts down to allow 100% focus', 'Changes color', 'Stops breathing'], answer: 1, explanation: "By turning off the critic, you allow pure, unhindered performance! 🎨" },
  ],

  relatedTopics: ['brain_structure', 'cognitive_biases', 'memory_how_it_works', 'learning_behavior'],
};
