// ─────────────────────────────────────────────────────────
//  TOPIC: CONSCIOUSNESS
//  Category: Philosophy & Cognitive Science
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'consciousness',
  title: 'Consciousness',
  subtitle: 'The Greatest Mystery in the Universe 🧠✨',
  emoji: '🧠',
  category: 'Philosophy',
  accentKey: 'consciousness',

  hook: {
    question: "How does wet, squishy meat inside your skull somehow generate the feeling of being *alive*?",
    reveal: "Welcome to the hardest problem in science.\n\nWe know how the heart pumps blood. We know how the stomach digests food. But we have absolutely no idea how 86 billion neurons firing electrical signals somehow create the *subjective experience* of seeing the color red, tasting chocolate, or feeling sadness.\nIf the universe is just made of dead atoms, how did dead atoms suddenly wake up and start feeling things? Are you just a highly complex biological calculator, or is there a 'ghost in the machine'? Let's dive into **Consciousness**. 🌌👻",
    emoji: '👻',
  },

  theory: [
    {
      id: 'what_is_consciousness',
      title: "What is Consciousness? 👁️",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'eye',
      svgIcon: 'star',
      content: "Consciousness is simply **Subjective Experience**.\nPhilosopher Thomas Nagel famously defined it like this: An organism is conscious if there is *'something it is like'* to be that organism.\nThere is 'something it is like' to be a bat (flying around, using sonar, feeling hungry). But there is *nothing* it is like to be a rock. A rock doesn't feel or experience anything. It is dark inside.",
      highlight: "Consciousness is the fact the lights are on inside your head. 💡",
    },
    {
      id: 'the_easy_problems',
      title: "The 'Easy' Problems 🧩",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'settings',
      svgIcon: 'activity',
      content: "Philosopher David Chalmers divided the study of the brain into 'Easy Problems' and 'The Hard Problem'.\nThe 'Easy' problems are figuring out the *mechanics* of the brain: How do we process visual information? How do we store memories? How do we react to stimuli?\nThese are just computational tasks. Biologists will eventually map all of this out. It is difficult, but intellectually 'easy' because it's just biology.",
      highlight: "Mapping the hardware of the brain is the 'Easy' part. 🗺️",
    },
    {
      id: 'the_hard_problem',
      title: "The 'Hard' Problem of Consciousness 🧱",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert-octagon',
      svgIcon: 'flame',
      content: "But **The Hard Problem** is: *Why does the processing of information feel like anything at all?*\nYour computer processes visual information from its webcam, but the computer doesn't *experience* seeing. It doesn't have an inner life.\nWhy didn't evolution just make humans unconscious biological robots (Philosophical Zombies) that perfectly survive, reproduce, and process data, but with no inner movie playing inside their heads?",
      highlight: "Why is there an 'I' watching everything? Nobody knows. 🤯",
    },
    {
      id: 'qualia',
      title: "Qualia (The Raw Feeling) 🍷",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'droplet',
      svgIcon: 'zap',
      content: "At the center of The Hard Problem is **Qualia** (pronounced kwah-lee-ah).\nQualia are the raw, subjective feelings of an experience. \nThe *physics* of a red apple is just light waves hitting your retina at 700 nanometers. But the *qualia* is the actual, indescribable, vivid *feeling* of 'Redness' that explodes in your mind.\nYou cannot explain the feeling of 'Redness' to a blind person using math or physics.",
      highlight: "Science can measure the brain, but science cannot measure a feeling. 📏",
    },
    {
      id: 'mary_in_the_black_and_white_room',
      title: "Mary's Room (Thought Experiment) ⬛⬜",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'box',
      svgIcon: 'lock',
      content: "Imagine Mary, the world's smartest neuroscientist. She has spent her entire life locked in a secretly painted Black-and-White room. \nShe learns *every single physical fact* there is to know about color vision. She knows exactly how light hits the eye, how neurons fire, and how the brain processes the color red by reading black-and-white textbooks.\nOne day, the door opens, and she steps outside and sees a Red Apple for the first time.",
      highlight: "Did she learn something new? Yes: She finally learned what red *feels* like. Therefore, physical facts are not the whole story. 🍎",
    },
    {
      id: 'dualism',
      title: "Solution 1: Dualism (The Ghost) 👻",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'wind',
      svgIcon: 'eye',
      content: "How do we solve the Hard Problem? \n**Dualism** (championed by Descartes) says: The universe is made of TWO different kinds of stuff: Physical stuff (atoms) and Mental stuff (the soul/mind).\nYour brain doesn't *generate* consciousness; your brain is just a radio receiver tuning into a non-physical signal (the Soul). \nThe problem? Science hates Dualism because it violates the laws of physics. How does a non-physical soul push physical atoms around in the brain?",
      highlight: "Dualism claims the mind is literal magic floating outside of physics. ✨",
    },
    {
      id: 'physicalism',
      title: "Solution 2: Physicalism / Materialism 🔬",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'cpu',
      svgIcon: 'activity',
      content: "**Physicalism** says: Magic isn't real. There is only matter. \nTherefore, consciousness is just an illusion generated by complex computation.\nJust like hydrogen is a gas and oxygen is a gas, but when you combine them they somehow create 'wetness' (water). Physicalists argue that when you combine 86 billion neurons, they somehow create 'consciousness' as an emergent property.",
      highlight: "You are just meat that hallucinated it had a soul. 🥩",
    },
    {
      id: 'panpsychism',
      title: "Solution 3: Panpsychism (The Universe is Awake) 🌌",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'sun',
      svgIcon: 'star',
      content: "This sounds crazy, but it's becoming highly respected in modern philosophy.\n**Panpsychism** argues: You can't get consciousness out of dead matter. Therefore, matter was NEVER dead. \nConsciousness is a fundamental property of the universe, just like mass or electrical charge. Even a single electron has a tiny, microscopic sliver of 'experience'. When billions of them group together in a human brain, they form a complex, unified consciousness.",
      highlight: "The entire universe is fundamentally 'awake' on a microscopic level. ⚛️",
    },
    {
      id: 'the_chinese_room',
      title: "The Chinese Room (John Searle) 🇨🇳",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'message-square',
      svgIcon: 'target',
      content: "Can Artificial Intelligence become conscious? \nImagine a man locked in a room. He doesn't know a word of Chinese. People slide Chinese symbols under the door. He uses a giant rulebook to find the matching symbol to send back.\nTo the people outside, the room is 'fluent' in Chinese. But the man inside understands absolutely nothing. He is just following rules.\nPhilosopher John Searle argues computers are exactly like this. They process syntax (rules) without ever having semantics (understanding or feeling).",
      highlight: "ChatGPT doesn't understand what it is saying; it's just a man in a room following a rulebook. 🤖",
    },
    {
      id: 'philosophical_zombies',
      title: "Philosophical Zombies 🧟",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'user-x',
      svgIcon: 'cloud',
      content: "A **Philosophical Zombie** (p-zombie) is a thought experiment: Imagine a creature that is physically identical to you. It cries, laughs, and talks about its feelings exactly like you do.\nBut inside, it is completely dark. It has zero subjective experience. It is a biological robot faking consciousness perfectly.\nIf p-zombies are logically possible, it proves that physical behavior (crying/laughing) does not guarantee the existence of consciousness.",
      highlight: "How do you know everyone else isn't a zombie? You are the only one you know is conscious. 🧠",
    },
    {
      id: 'split_brain',
      title: "Split-Brain Patients (Where is the 'I'?) ✂️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'scissors',
      svgIcon: 'zap',
      content: "To cure severe epilepsy, doctors sometimes sever the corpus callosum (the bridge connecting the left and right halves of the brain).\nCrazy things happen: The left hand might button up a shirt, while the right hand tries to unbutton it! The two hemispheres can disagree.\nNeurologists believe cutting the brain in half literally splits the consciousness into two separate entities trapped in one skull. Which one is 'You'?",
      highlight: "If you physically split the brain, do you split the soul? 🤯",
    },
    {
      id: 'the_transporter_paradox',
      title: "The Star Trek Transporter 🌀",
      color: '#009688',
      bgGradient: ['#001A15', '#000805'],
      icon: 'send',
      svgIcon: 'cloud',
      content: "Imagine a teleportation machine. It scans every atom in your body, perfectly destroys you on Earth, and perfectly reconstructs you on Mars using new atoms.\nThe person on Mars will have your memories, your personality, and claim to be you.\nBut did *you* survive? Or did you die on Earth, and a brand new clone just woke up on Mars convinced it is you? If consciousness is just information, you survived. If consciousness is tied to the original physical brain, you died.",
      highlight: "Every time you sleep, your consciousness turns off. Are you the same person who went to sleep? 🛌",
    },
    {
      id: 'the_binding_problem',
      title: "The Binding Problem 🧩",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'link',
      svgIcon: 'lock',
      content: "Right now, you are looking at your phone. Your brain processes the *shape* of the phone in one area, the *color* in another, and the *weight* in another.\nBut you don't experience a fractured reality. You experience one, perfectly unified, seamless movie of 'holding a phone'.\nHow does the brain instantly stitch millions of independent neurological processes into one single, unified 'Self'? Science has no idea. This is the Binding Problem.",
      highlight: "Who is the audience watching the seamless movie in your head? 🎬",
    },
    {
      id: 'illusionism',
      title: "Illusionism (It doesn't exist) 🪄",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'eye-off',
      svgIcon: 'eye',
      content: "The most hardcore materialists (like Daniel Dennett) adopt **Illusionism**.\nThey argue that the Hard Problem is fake. Qualia doesn't exist. You *think* you have a rich inner movie playing in your head, but that's just an illusion created by the brain's data processing to help the organism survive.\nConsciousness is a user interface. Just like files on a computer desktop aren't *really* manila folders (they are 1s and 0s), your feelings aren't *really* real. They are just a biological dashboard.",
      highlight: "Are you hallucinating your own existence? 😲",
    },
    {
      id: 'conclusion',
      title: "The Final Frontier 🚀",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'compass',
      svgIcon: 'star',
      content: "We have mapped the edges of the universe. We have split the atom. We have sequenced DNA.\nBut the one thing that is closest to us—our own awareness—remains completely unexplained by modern science. \nThe Hard Problem of Consciousness is the final boss of Human Knowledge. Until we solve it, we don't truly understand what we are.",
      highlight: "The universe is looking back at itself through your eyes right now. 🌌👁️",
    },
  ],

  lab: {
    title: "The Chinese Room 🇨🇳🤖",
    description: "Welcome to Searle's Room. You are an AI algorithm. A human passes a symbol into the room. You must look it up in the rulebook, find the corresponding output symbol, and pass it back. Try to convince the person outside that you 'understand' Chinese.",
    hint: "Pay attention to your own experience. Are you learning the language, or just following blind instructions?",
    scientistModeHint: "Syntax vs Semantics 🧑‍🔬: Notice that pattern matching (syntax) produces identical external behavior to true comprehension (semantics), making external Turing tests philosophically useless.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do some scientists think the universe might be a giant brain?", answer: "Because of Panpsychism. If consciousness is a fundamental property of matter (like gravity), then as matter clumps together into more complex structures, consciousness scales up. The cosmic web of galaxies looks shockingly similar to the neural network of a human brain. Some philosophers argue the universe itself might have a slow, macroscopic form of consciousness we can't comprehend. 🌌", emoji: '🧠' },
    { id: 'dyk2', question: "Why did scientists cut the brains of severe epilepsy patients in half?", answer: "Epilepsy is caused by electrical storms moving back and forth between the left and right hemispheres of the brain. By cutting the 'corpus callosum' (the bridge between them), the storm can't spread, curing the seizures. But it led to terrifying side effects, like 'Alien Hand Syndrome', where the left hemisphere has no idea what the right hemisphere (controlling the left hand) is doing, proving consciousness can literally be physically cut in two. ✂️", emoji: '⚡' },
    { id: 'dyk3', question: "Why do we call it a 'Philosophical Zombie'?", answer: "Because regular movie zombies are slow, rotting, and want brains. A Philosophical Zombie is physically and functionally identical to a normal human. It smiles when you give it a gift. But it has no 'inner experience'. It's a thought experiment to prove that physical behavior does not equal conscious experience. If a robot fakes crying perfectly, is it sad? 🧟", emoji: '🤖' },
    { id: 'dyk4', question: "Why does the color Red present a crisis for Physics?", answer: "Because physics only deals with quantitative properties (mass, spin, charge, wavelength). A wavelength of 700nm has no inherent 'redness' in the universe. 'Red' only exists inside the subjective theater of a conscious mind. Therefore, physicalism (the belief that everything is physical) is missing a massive chunk of reality: the qualitative feeling of things (Qualia). 🍎", emoji: '🌈' },
    { id: 'dyk5', question: "Why is Anesthesia a massive medical mystery?", answer: "We use it every day for surgery, but we still don't completely understand *how* it turns consciousness off! We know it disrupts neural communication, but we don't know the exact mechanism that causes the 'lights to go out' in the brain. It highlights perfectly that we have no idea what the actual switch for consciousness is. 🏥", emoji: '💉' },
  ],

  quiz: [
    { id: 'q1', question: "How did Thomas Nagel fundamentally define 'Consciousness'?", options: ["Having a high intelligence level", "Having a subjective internal experience", "Being in a wakeful state", "Having the ability to speak"], answer: 1, explanation: "There is nothing it is like to be a rock. There is something it is like to be a bat. 🦇" },
    { id: 'q2', question: "Who coined the term 'The Hard Problem of Consciousness'?", options: ["The philosopher Socrates", "The philosopher David Chalmers", "The philosopher René Descartes", "The physicist Albert Einstein"], answer: 1, explanation: "He split the brain's functions into Easy (mechanics) and Hard (experience). 🧠" },
    { id: 'q3', question: "What is 'The Hard Problem of Consciousness'?", options: ["Solving complex mathematical equations", "Explaining why physical processes feel subjective", "Maintaining focus during long tasks", "Acquiring a second language fluently"], answer: 1, explanation: "Why is the movie playing inside your head? 🎬" },
    { id: 'q4', question: "What are 'Qualia'?", options: ["A specific species of bird", "Raw subjective feelings of experience", "Lines of complex computer code", "Individual cells within the brain"], answer: 1, explanation: "You can't explain 'red' to a blind person using math. That's qualia. 🍎" },
    { id: 'q5', question: "In the 'Mary's Room' thought experiment, what happens when Mary (who knows all physical facts about color vision but lived in a black/white room) finally sees a red apple?", options: ["She suffers a fatal accident", "She gains new non-physical knowledge", "She loses her sense of sight", "She consumes the red fruit"], answer: 1, explanation: "Experience provides knowledge that textbooks cannot. ⬛⬜" },
    { id: 'q6', question: "What is 'Dualism' (Descartes' solution)?", options: ["Possessing two separate physical brains", "Reality consists of matter and mind", "A style of competitive combat", "A specific psychological mood disorder"], answer: 1, explanation: "The brain is just a radio receiving a signal from a non-physical source. 👻" },
    { id: 'q7', question: "Why do modern physicists largely reject Dualism?", options: ["Fear of supernatural spiritual entities", "It violates fundamental laws of physics", "Dislike for early modern philosophy", "The theory is considered outdated"], answer: 1, explanation: "Magic interacting with matter breaks physics. ✨" },
    { id: 'q8', question: "What does 'Physicalism/Materialism' argue about consciousness?", options: ["Prioritizing the purchase of goods", "Consciousness is a physical process", "The importance of regular exercise", "The scientific rejection of gravity"], answer: 1, explanation: "Just like H2O creates 'wetness', atoms create 'awareness'. 🥩" },
    { id: 'q9', question: "What does **Panpsychism** propose?", options: ["Kitchen utensils possess living spirits", "Consciousness is a fundamental universal property", "Humanity suffers from collective insanity", "Extraterrestrial beings control human actions"], answer: 1, explanation: "The universe was never 'dead'. It was always awake on a micro level. 🌌" },
    { id: 'q10', question: "What is John Searle's 'Chinese Room' thought experiment designed to prove?", options: ["The difficulty of learning Mandarin", "Symbol manipulation is not true understanding", "The benefits of international travel", "The physical dimensions of architecture"], answer: 1, explanation: "ChatGPT is just the man in the room moving symbols around blindly. 🤖" },
    { id: 'q11', question: "What is a 'Philosophical Zombie' (p-zombie)?", options: ["A monster from horror cinema", "A person lacking internal subjective experience", "Someone over-caffeinated and hyperactive", "A deceased human physical body"], answer: 1, explanation: "It proves that physical behavior does not guarantee inner experience. 🧟" },
    { id: 'q12', question: "What crazy phenomenon occurs in 'Split-Brain' patients (those with a severed corpus callosum)?", options: ["Significant increase in cognitive intelligence", "Brain hemispheres acting as separate minds", "The total cessation of sleep", "The complete loss of long-term memory"], answer: 1, explanation: "You literally split the 'Self' in half with a scalpel. ✂️" },
    { id: 'q13', question: "What does the 'Star Trek Transporter Paradox' question?", options: ["The feasibility of interstellar travel", "Whether identity survives atomic reconstruction", "The energy costs of teleportation", "The existence of extraterrestrial life"], answer: 1, explanation: "Are you just 'Information', or are you tied to your original physical meat? 🌀" },
    { id: 'q14', question: "What is 'The Binding Problem' in neuroscience?", options: ["The physical act of tying laces", "How the brain unifies sensory data", "The repair of damaged literature", "The physical connection of neurons"], answer: 1, explanation: "Who is the audience member watching the movie in your head? 🎞️" },
    { id: 'q15', question: "What is 'Illusionism' (supported by Daniel Dennett)?", options: ["The performance of stage magic", "Subjective experience is a biological illusion", "The creation of optical artwork", "The theory that reality is dreaming"], answer: 1, explanation: "Your feelings are just the icons on a computer desktop. They aren't 'real'. 🪄" },
    { id: 'q16', question: "According to Panpsychism, why does the universe have consciousness?", options: ["Divine intervention by a creator", "Consciousness is inherent in all matter", "A random cosmic biological accident", "The influence of solar radiation"], answer: 1, explanation: "Nothing comes from nothing. Consciousness must be fundamental. ⚛️" },
    { id: 'q17', question: "Why is 'The Hard Problem of Consciousness' considered harder than Physics or Chemistry?", options: ["The use of large numbers", "Subjective experience cannot be measured objectively", "The lack of scientific effort", "The requirement for advanced mathematics"], answer: 1, explanation: "You can't put 'Sadness' under a microscope. 🔬" },
    { id: 'q18', question: "If you believe artificial intelligence (like ChatGPT) actually 'understands' what it is saying, you are disagreeing with which thought experiment?", options: ["The ethical Trolley Problem", "The Chinese Room experiment", "The Mary's Room experiment", "The Veil of Ignorance theory"], answer: 1, explanation: "Searle argues Syntax (rules) does not equal Semantics (understanding). 🇨🇳" },
    { id: 'q19', question: "What is an 'Emergent Property' (as claimed by physicalists)?", options: ["The purchase of physical property", "New properties arising from complex systems", "A medical crisis in hospitals", "A formal legal written document"], answer: 1, explanation: "Complex networks generate completely new states of reality. 💧" },
    { id: 'q20', question: "Why is understanding consciousness ultimately the 'Final Boss' of knowledge?", options: ["It determines final academic grades", "It is the lens of all experience", "It grants humans supernatural abilities", "It provides cures for all illnesses"], answer: 1, explanation: "Without consciousness, the universe is just a dark room filled with rocks. 🌌" },
  ],

  relatedTopics: ['free_will', 'nihilism', 'absurdism'],
};
