// ─────────────────────────────────────────────────────────
//  TOPIC: CORPORATE FINANCE
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'corporate_finance',
  title: 'Business Finance',
  subtitle: "How the world's biggest companies play the money game 🏢",
  emoji: '💼',
  category: 'Finance',
  accentKey: 'success',

  hook: {
    question: "How can a startup like Uber lose $5 Billion in one year but still be worth billions of dollars? 🤯",
    reveal: "Because in the corporate world, profit isn't the only thing that matters! Sometimes companies intentionally burn money like rocket fuel to grow fast and conquer the world before their rivals do. It's like a high-stakes race where the prize is being the only survivor. Let's decode the secret rules of big business! 🚀💸",
    emoji: '📈',
  },

  theory: [
    {
      id: 'revenue_vs_profit',
      title: 'Top Line vs Bottom Line 📉',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '📉',
      svgIcon: 'chart',
      content: "**Revenue (Top Line):** Every single rupee that comes into the shop. If you sell 100 toys for ₹10 each, your Revenue is ₹1,000.\n\n**Profit (Bottom Line):** What is left after paying for the plastic, the workers, the rent, and the lights. If those costs were ₹800, your Profit is only ₹200. You can have massive revenue but zero profit—this is why big numbers can be tricky! 🧠",
      highlight: "Revenue is vanity; Profit is sanity. 🧠",
    },
    {
      id: 'balance_sheet_basics',
      title: 'The Financial X-Ray ⚖️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'balance',
      content: "The **Balance Sheet** is an X-ray of what a company owns and owes at one exact second. \n\nIt follows one law: **Assets = Liabilities + Equity.** \n**Assets:** The company's 'Stuff' (Cash, Buildings, IP). \n**Liabilities:** The company's 'Debt' (Bank loans, bills). \n**Equity:** What is left for the owners. If a company has ₹100 of stuff and ₹80 of debt, the owners only 'own' ₹20 of the business. 🏥",
      highlight: "The Balance Sheet proves if a company is healthy or secretly dying. 🏥",
    },
    {
      id: 'cash_flow',
      title: 'The Oxygen (Cash Flow) 🌬️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🌬️',
      svgIcon: 'refresh',
      content: "A company can be 'Profitable' on paper but still die tomorrow! \n\nHow? If you sell ₹1 Crore of goods, you have ₹1 Crore of 'Revenue.' But if the customer takes 6 months to pay you, you have ZERO cash today. Without cash, you can't pay your employees' salaries tomorrow. **Cash Flow** is the physical movement of money. Running out of cash is like running out of oxygen. 💀",
      highlight: "Cash is the lifeblood of a company. No cash, no business. 💀",
    },
    {
      id: 'equity_vs_debt',
      title: 'Loans vs Partners 💰',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '💰',
      svgIcon: 'target',
      content: "When a company needs money to build a new factory, they have two choices:\n\n**Debt:** Take a bank loan. You must pay interest every month, but you keep 100% control of the company. \n**Equity:** Sell a 'Slice' of the company to an investor. You don't have to pay them back if you fail, but you give up a piece of all future profits forever! It's like choosing between a bill and a partner. ⚖️",
      highlight: "Debt costs you cash; Equity costs you ownership. ⚖️",
    },
    {
      id: 'startup_funding_rounds',
      title: 'The Rocket Fuel (Rounds) 🚀',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🚀',
      svgIcon: 'star',
      content: "Startups raise money in 'Stages':\n\n**Seed:** Just an idea. You get a little money to see if it works.\n**Series A:** You have a product and customers. You get millions to build a team.\n**Series B & C:** You are growing fast and want to crush everyone. You get hundreds of millions. \nWith every stage, the founders own a smaller and smaller piece of their own 'Pie' (Dilution). 🍰",
      highlight: "Funding rounds are fuel for the growth engine. 🚀",
    },
    {
      id: 'the_ipo',
      title: 'The Grand Listing (IPO) 🔔',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🔔',
      svgIcon: 'zap',
      content: "An **IPO (Initial Public Offering)** is when a private company finally sells its shares to EVERYONE on the Stock Market. \n\nWhy? To raise billions of dollars from regular people. This is the day the founders and early investors finally get 'Rich' by selling their shares. Once public, the company has to tell all its secrets to the government every 3 months. 🏁",
      highlight: "The IPO is the 'Finish Line' for early investors. 🏁",
    },
    {
      id: 'valuation_multiples',
      title: 'The Price Tag (Valuation) 🧮',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🧮',
      svgIcon: 'book',
      content: "How much is a company worth? It's usually a multiple of their profit. \n\nIf a company makes ₹1 Crore and investors pay ₹15 Crores for it, it has a **PE Ratio** of 15. Tech companies get HUGE multiples (like 50x) because people believe they will be 100x bigger in the future. Valuation is just a guess about how bright the future looks! 🔮",
      highlight: "Valuation is about tomorrow, not just today. 🔮",
    },
    {
      id: 'burn_rate_runway',
      title: 'The Countdown (Runway) 🔥',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🔥',
      svgIcon: 'alert',
      content: "Startups often lose money on purpose to grow fast. \n\n**Burn Rate:** How much money they lose every month. \n**Runway:** How many months until they have ₹0 left in the bank. \nIf you have ₹1 Crore and lose ₹10 Lakhs a month, your 'Runway' is 10 months. You must either start making profit or raise more money before the timer hits zero! 🛫",
      highlight: "Never let the runway hit zero. 🛫",
    },
    {
      id: 'b2b_vs_b2c',
      title: 'People vs Companies 🏢',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🏢',
      svgIcon: 'shield',
      content: "**B2C (To Consumers):** Selling shoes or apps to normal people (like Netflix or Nike). Requires lots of ads and millions of small sales.\n\n**B2B (To Businesses):** Selling software or engines to other companies (like Microsoft or Boeing). One sale can be worth ₹100 Crores! It takes years to make one sale, but once you win, you have a customer for life. 🏢",
      highlight: "B2C is about emotion; B2B is about logic and ROI. 🧠",
    },
    {
      id: 'bankruptcy_liquidation',
      title: 'The End (Bankruptcy) 💀',
      color: '#e4a11cff',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '💀',
      svgIcon: 'lock',
      content: "When a company can't pay its bills, it 'dies.' \n\nThe courts take over and sell all the 'Stuff' (laptops, buildings) for cash. The banks get their money back first. The regular workers get paid second. The poor shareholders (the people who bought the stock) are at the VERY bottom. Usually, they get ₹0. This is the risk you take when you buy a piece of a company! 📉",
      highlight: "In a crash, debt gets paid; equity gets wiped. 💀",
    },
  ],

  lab: {
    title: "The CEO Dashboard 🏢",
    description: "Welcome to the Corporate Lab! Explore 3 modes: The Break-Even calculator (how many toys do you need to sell just to survive?), the Startup Runway simulator (can you raise money before you hit zero?), and the Dilution Pie Chart (watch your ownership shrink as you get rich!) 📊",
    hint: "Try the 'Runway' mode. Increase your marketing spend (Burn Rate) and see how it speeds up your growth but shortens your life! It's a dangerous balance.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Pre-Money vs Post-Money math and Employee Stock Option (ESOP) dilution models.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why Amazon paid zero tax for many years? 📦",
      answer: "Reinvestment! The government wants companies to grow. If Amazon made $1 Billion in profit but spent that $1 Billion on 50,000 new workers and 10 new warehouses, their 'Taxable Profit' becomes zero. They aren't 'hiding' money; they are building the future! 🏭",
      emoji: '🏛️',
    },
    {
      id: 'dyk2',
      question: "Do you know why software companies have infinite profit? 🚀",
      answer: "Zero Marginal Cost! If Ford wants to sell one more car, they have to buy steel and glass. If Microsoft wants to sell one more copy of Windows, it costs them ₹0 to copy the code. This is why tech companies can grow to billions of users with very little extra cost! 💻",
      emoji: '🧠',
    },
    {
      id: 'dyk3',
      question: "Do you know why founders get fired from their own companies? 🚪",
      answer: "Dilution! Every time a founder takes money from investors, they give away a 'Slice' of the company. Eventually, they own less than 51%. Now, they aren't the boss anymore—the 'Board of Directors' is. If the Board thinks the founder is doing a bad job, they can legally kick them out of their own building! ⚖️",
      emoji: '📉',
    },
    {
      id: 'dyk4',
      question: "Do you know why 'Subscriptions' are the favorite business model? ☁️",
      answer: "Predictability! Wall Street loves companies like Netflix or Adobe because they know EXACTLY how much money is coming in next month. It's much safer than a shop that has to wait for customers to walk in the door. Predictable money is worth 10x more to investors! 🔄",
      emoji: '💸',
    },
    {
      id: 'dyk5',
      question: "Do you know why a high PE Ratio is a warning sign? ⚠️",
      answer: "Priced for Perfection! A high PE means investors think the company will be a superstar. If the company is only 'pretty good' instead of 'perfect,' the stock price will crash because the illusion is broken. It's like a movie that has too much hype! 💥",
      emoji: '📉',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is Revenue?", options: ["The profit after taxes", "The total money coming in from sales", "The cost of the factory", "The amount of debt"], answer: 1, explanation: "Revenue is the total 'Top Line' cash! 📉" },
    { id: 'q2', question: "What is the law of the Balance Sheet?", options: ["Profit = Revenue - Cost", "Assets = Liabilities + Equity", "Sales = Ads + Luck", "Money = Time + Effort"], answer: 1, explanation: "Everything you own must be paid for by debt or equity! ⚖️" },
    { id: 'q3', question: "Why is 'Cash Flow' the oxygen of a business?", options: ["It helps workers breathe", "You need actual cash to pay salaries today, not just 'paper profit' from future bills", "It is only for tech companies", "It's required by the fire department"], answer: 1, explanation: "Without cash, a profitable company can die tomorrow! 🌬️" },
    { id: 'q4', question: "What is 'Equity Financing'?", options: ["Taking a bank loan", "Selling a 'Slice' of the company to an investor", "Buying a new car", "Closing the company"], answer: 1, explanation: "You trade ownership for cash and shared risk! 💰" },
    { id: 'q5', question: "What happens during 'Dilution'?", options: ["The founder gets more money", "The founder's percentage of the company gets smaller", "The company's logo changes", "The stock price doubles"], answer: 1, explanation: "You trade a large slice of a small pie for a small slice of a huge pie! 🍰" },
    { id: 'q6', question: "What is an IPO?", options: ["An international police order", "The first time a company sells its shares to the general public", "A type of business loan", "A secret meeting"], answer: 1, explanation: "It's when the company joins the stock market! 🔔" },
    { id: 'q7', question: "What does the PE Ratio tell you?", options: ["The weight of the building", "How many years of profit you are paying to buy the company", "The number of employees", "The tax rate"], answer: 1, explanation: "It's the price tag relative to the earnings! 🧮" },
    { id: 'q8', question: "What is a startup's 'Runway'?", options: ["A place for planes", "How many months until the company runs out of cash", "The length of the office", "The speed of growth"], answer: 1, explanation: "It's the countdown to survival! 🔥" },
    { id: 'q9', question: "B2B stands for:", options: ["Back to Business", "Business to Business (selling to other companies)", "Buy 2 get 1 free", "Better 2 Best"], answer: 1, explanation: "It's about selling high-value stuff to other firms! 🏢" },
    { id: 'q10', question: "Who gets paid LAST if a company fails?", options: ["The Bank", "The Employees", "The Stockholders (Equity owners)", "The Government"], answer: 2, explanation: "Equity owners take the biggest risk and get wiped first! 💀" },
    { id: 'q11', question: "Why do tech companies grow so fast?", options: ["They use better computers", "Zero Marginal Cost—copying software costs almost nothing", "They don't pay taxes", "They have more money"], answer: 1, explanation: "Infinite scaling with zero extra cost! 🚀" },
    { id: 'q12', question: "Why might a founder be fired from their own firm?", options: ["They were too loud", "They lost control of the majority of shares (dilution)", "The police said so", "They became too rich"], answer: 1, explanation: "Whoever owns the most shares is the boss! 🚪" },
    { id: 'q13', question: "SaaS stands for:", options: ["Sales and Advanced Systems", "Software as a Service (Subscriptions)", "Storage and Automotive Services", "Security and Safety"], answer: 1, explanation: "Investors love the predictable monthly cash! ☁️" },
    { id: 'q14', question: "Reinvesting profit to grow usually means:", options: ["Paying zero tax legally", "Paying double tax", "Going bankrupt", "Breaking the law"], answer: 0, explanation: "The government rewards growth with tax breaks! 🏭" },
    { id: 'q15', question: "What is a 'Burn Rate'?", options: ["How fast the building is on fire", "The amount of cash a startup loses every month", "The rate of employee quitting", "The speed of the factory"], answer: 1, explanation: "It's how fast the cash fuel is being used! 🔥" },
    { id: 'q16', question: "The 'Bottom Line' is:", options: ["Total sales", "Net Profit", "Total debt", "The footer of the website"], answer: 1, explanation: "It's the ultimate truth of the business! 📉" },
    { id: 'q17', question: "A 'Unicorn' is a startup worth:", options: ["₹1 Crore", "₹10,000 Crores ($1 Billion+)", "₹100", "Zero"], answer: 1, explanation: "It's a rare and magical level of success! 🦄" },
    { id: 'q18', question: "Venture Capitalists (VCs) invest in:", options: ["Safe banks", "High-risk startups with huge potential", "Gold mines", "Grocery stores"], answer: 1, explanation: "They bet on the rockets of the future! 🚀" },
    { id: 'q19', question: "What is 'Pre-Money' Valuation?", options: ["The money in the vault", "The value of the company BEFORE new investment", "The profit from last year", "The cost of the office"], answer: 1, explanation: "It's the starting price of the negotiation! 🧮" },
    { id: 'q20', question: "The primary job of a CEO is:", options: ["Doing all the work", "Making sure the company never runs out of cash fuel", "Fixing the computers", "Answering the phones"], answer: 1, explanation: "Keep the rocket flying and the fuel tank full! 🛫" }
  ],

  relatedTopics: ['investing', 'real_estate_finance', 'taxation'],
};
