// ─────────────────────────────────────────────────────────
//  TOPIC: PERIODIC TRENDS
//  Category: Chemistry / Foundations
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'periodic_trends',
  title: 'Periodic Trends',
  subtitle: 'The hidden patterns of the elements 🧪✨',
  emoji: '🧪',
  category: 'Chemistry',
  accentKey: 'periodic',

  hook: {
    question: "Why does dropping a tiny piece of Potassium in water cause a purple explosion, while dropping Lithium just makes a few bubbles? 💥",
    reveal: "Because of a 'Periodic Trend'! In the same group, atoms get larger as you go down. The larger the atom, the further away its outer electron is from the positive core. Potassium's electron is so loosely held that it literally jumps off the moment it touches water, releasing massive energy! Chemistry isn't random—it's predictable. Let's find the patterns! 🔍",
    emoji: '🧐',
  },

  theory: [
    {
      id: 'mendeleev_legacy',
      title: 'Mendeleev\'s Map 🗺️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🗺️',
      svgIcon: 'grid',
      content: "In 1869, Dmitri Mendeleev did something incredible. He arranged the 63 known elements not just by weight, but by their *repeating properties* (Periodicity).\n\nHe was so confident in the pattern that he left empty gaps in his table 🔲. He predicted that elements like 'Gallium' and 'Germanium' would be discovered to fill them, even describing their exact density and color before they were ever found! \n\nToday, we arrange the table by **Atomic Number** (number of protons). This reveals the fundamental physics of the universe! 🌌",
      highlight: "The table is arranged so that elements in the same vertical column (Group) have similar personalities. 👯",
    },
    {
      id: 'periods_groups',
      title: 'Periods vs Groups 📐',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📐',
      svgIcon: 'grid',
      content: "To read the table, you must know the difference between the 'Elevator' and the 'Hallway':\n\n• **Groups (Columns):** The vertical families (1 to 18). Elements in a group have the same number of **Valence Electrons** (outer electrons). This is why they react similarly! 👥\n• **Periods (Rows):** The horizontal lines (1 to 7). Moving across a period adds one proton and one electron. Every new period starts a new 'shell' or layer of electrons, just like an onion! 🧅\n\nGroups = Personality. Periods = Size/Layers.",
      highlight: "Group 1 (Alkali Metals) are all 'explosive' in water because they all have exactly 1 lonely outer electron! 💣",
    },
    {
      id: 'atomic_radius',
      title: 'Atomic Radius: Size Matters 📏',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '📏',
      svgIcon: 'target',
      content: "Atomic Radius is the distance from the center of the nucleus to the edge of the electron cloud.\n\n• **Down a Group:** Atoms get BIGGER 📈. Each step down adds a whole new energy shell (onion layer).\n• **Across a Period:** Atoms get SMALLER 📉. Wait, why? As you move right, you add more protons to the center. This stronger positive 'magnet' pulls the electron shells in tighter, shrinking the atom!\n\nFrancium (bottom left) is the giant of the table, while Helium (top right) is the tiny marble.",
      highlight: "Moving right makes the nucleus 'stronger', pulling the atom into a tighter, smaller ball! 🧲",
    },
    {
      id: 'ionization_energy',
      title: 'Ionization Energy: Holding On ✊',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '✊',
      svgIcon: 'zap',
      content: "Ionization Energy (IE) is how much energy is required to kick an electron out of an atom. It's a measure of how tightly an atom 'grips' its electrons.\n\n• **Down a Group:** IE decreases 📉. Since the atom is larger, the outer electron is far away from the 'attraction' of the nucleus. It's easy to steal!\n• **Across a Period:** IE increases 📈. Since the atom is smaller and the nucleus is stronger, the grip is like a vice. \n\nNoble Gases (Group 18) have the highest IE. They refuse to let go of their perfect electron set! ✋",
      highlight: "Low IE means 'Easy to steal from.' High IE means 'I'm holding onto my electrons forever!' 🔒",
    },
    {
      id: 'electronegativity',
      title: 'Electronegativity: The Bully 😈',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '😈',
      svgIcon: 'link',
      content: "Electronegativity is an atom's hunger for *other* atoms' electrons. Think of it as a tug-of-war 🧶.\n\n**Fluorine** is the undisputed king of electronegativity (4.0). It is the 'Bully' of the periodic table—it will rip electrons away from almost anything. \n\n• **Trend:** Increases as you move **UP** and to the **RIGHT**. \nCesium and Francium (bottom left) are the most generous (lowest electronegativity)—they are happy to give electrons away. This difference in 'greed' is what creates chemical bonds! 🖇️",
      highlight: "Electronegativity determines who wins the tug-of-war in a chemical bond. 🥇",
    },
    {
      id: 'electron_affinity',
      title: 'Electron Affinity: The Gift 🎁',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🎁',
      svgIcon: 'star',
      content: "Electron Affinity is the energy released when an atom *gains* an electron. It's like the atom is 'happy' to receive a gift.\n\nHalogens (Group 17) have the highest electron affinity. They have 7 valence electrons and are DESPERATE for just 1 more to complete their set of 8. When they get that one electron, they release a huge burst of energy. \n\nNoble gases have zero electron affinity—they are already full and don't want your gifts! 🙅‍♂️",
      highlight: "Group 17 atoms are the 'hungriest' to complete their 8-electron shell. 🍕",
    },
    {
      id: 'metallic_character',
      title: 'Metallic Character 🔨',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔨',
      svgIcon: 'cpu',
      content: "Metallic character is how easily an atom loses electrons. Metals are 'givers'—they lose electrons to become shiny, conductive, and strong 💪.\n\n• **Trend:** Increases toward the **Bottom Left** (Francium).\nOn the far left, you have the Alkali Metals. In the middle, the Transition Metals (Gold, Iron). On the right, the Non-Metals (Oxygen, Nitrogen). \n\nThe boundary between them is a 'Staircase' of **Metalloids** like Silicon, which can act as both a metal and a non-metal—this is why we use them to build computer chips! 💻",
      highlight: "The table is a map of 'Givers' (Left) and 'Takers' (Right). ↔️",
    },
    {
      id: 'valence_reactivity',
      title: 'Valency & The Octet Rule 8️⃣',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '8️⃣',
      svgIcon: 'atom',
      content: "In chemistry, **8 is the magic number**. This is the **Octet Rule**.\n\nAtoms are most stable when their outer shell is full (8 electrons). \n• Group 1 has 1 electron (needs to lose 1).\n• Group 17 has 7 electrons (needs to gain 1).\n\nWhen a Group 1 atom meets a Group 17 atom, it's a perfect match! The giver gives, the taker takes, and both end up with a full shell of 8. This 'desire' for 8 is what causes almost all chemical reactions on Earth! 🔥",
      highlight: "Reactivity is just the desperate struggle for atoms to reach the number 8. 🎯",
    },
    {
      id: 'noble_gases',
      title: 'Noble Gas Stability 🛡️',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "The Noble Gases (Group 18) are the 'Royalty' of the table. They have a full outer shell (8 electrons) and are perfectly stable 🧘.\n\nBecause they have everything they need, they don't react with anything. Helium, Neon, Argon—they never form bonds, never explode, and never burn. \n\nAncient Egyptians would have found the air we breathe contains Argon, but they never would have known because it's invisible and does nothing! We use Neon in signs because when you shock it with electricity, it glows without catching fire. 💡",
      highlight: "Noble gases are 'Noble' because they refuse to mix with common elements. 👑",
    },
    {
      id: 'predicting_unknown',
      title: 'Predicting the Future 🔮',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🔮',
      svgIcon: 'search',
      content: "Periodic trends allow scientists to be prophets. \n\nWhen we create new, artificial elements in particle accelerators (like Oganesson, element 118), we don't have enough of it to even see it with a microscope. It only exists for a fraction of a second ⏱️.\n\nBut because it sits in Group 18, scientists *know* it will behave like a gas and won't be very reactive. We can describe the chemistry of elements that don't even belong on Earth, simply by looking at where they sit on Mendeleev's map. 🌌",
      highlight: "Knowledge of trends turns the periodic table into a crystal ball for chemistry. 🔮",
    },
  ],

  lab: {
    title: "Periodic Flux Lab 🧪",
    description: "Navigate the mini-periodic table and toggle dynamic trend heatmaps! Scale atoms by their Atomic Radius, visualize the tug-of-war for Electronegativity, and trigger reactions based on Valency ⚡",
    hint: "Toggle 'Radius' mode and watch the atoms of the Alkali Metals (Group 1) grow as you move down. Switch to 'Electronegativity' to see Fluorine glow as the ultimate bully! Tap an element to see its electron shell map.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Effective Nuclear Charge ($Z_{eff}$) calculations and Ionization energy curves (kJ/mol).",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why the first shell has only 2 electrons, but the rest have 8? 🐚",
      answer: "It's due to Quantum Mechanics! The first energy level (n=1) only has one 'S' sub-orbital, which can only hold 2 electrons. That's why the first row of the table (Hydrogen and Helium) is so short! Row 2 adds 'P' orbitals, allowing for 6 more, totaling 8. ⚛️",
      emoji: '🤏',
    },
    {
      id: 'dyk2',
      question: "Do you know why Helium is on the right, even though it only has 2 electrons? 🎈",
      answer: "Because properties are more important than electron count! Even though Helium only has 2 electrons, its shell is FULL (for its size). This makes it perfectly stable and 'Noble', so it belongs in Group 18 with its stable cousins Neon and Argon, rather than Group 2! 🛡️",
      emoji: '⚖️',
    },
    {
      id: 'dyk3',
      question: "Do you know why most magnets are made of middle-table elements like Iron? 🧲",
      answer: "Trends in 'Unpaired Electrons'! Elements in the D-block (transition metals) often have 'empty seats' in their energy shells. These lonely electrons can all spin in the same direction, creating a strong magnetic field. Elements like Fluorine or Neon have no empty seats, so they can't be magnetic! 🚫",
      emoji: '🏗️',
    },
    {
      id: 'dyk4',
      question: "Do you know why Fluorine is the most reactive element on the whole table? 💥",
      answer: "It's the perfect storm of trends! Fluorine is tiny (top of its group), so its nucleus is very close to its edge. It has 7 valence electrons, so it only needs ONE more. This combination makes it the most electron-hungry, aggressive 'thief' in nature. It will even set water or sand on fire! 🔥",
      emoji: '🦷',
    },
    {
      id: 'dyk5',
      question: "Do you know why Silicon is used for all our computer chips? 💻",
      answer: "It's a Metalloid! It sits right on the 'staircase' trend line. This means under some conditions it acts as an insulator (stops electricity), and under others, it acts as a conductor (allows electricity). This 'Switch' behavior is the 1 and 0 of every computer ever built! ⚡",
      emoji: '🥪',
    },
  ],

  quiz: [
    { id: 'q1', question: "Who is the primary architect of the first modern Periodic Table?", options: ["Scientist Isaac Newton", "Scientist Dmitri Mendeleev", "Scientist Marie Curie", "Scientist Albert Einstein"], answer: 1, explanation: "In 1869, Mendeleev famously left gaps for yet-to-be-discovered elements, proving the power of periodicity! 🗺️" },
    { id: 'q2', question: "What vertical columns on the Periodic Table are called:", options: ["The horizontal periods", "The vertical groups", "The electron shells", "The atomic steps"], answer: 1, explanation: "Groups contain 'families' of elements with similar personalities and reaction styles! 👥" },
    { id: 'q3', question: "Across a period (left to right), what happens to the size of atoms (Atomic Radius)?", options: ["They get larger", "They get smaller", "They stay the same", "They disappear"], answer: 1, explanation: "Moving right adds more protons, which pull the electron shells in tighter, shrinking the atom! 📏" },
    { id: 'q4', question: 'Which of these is the most "Bully-like" (Electronegative) element?', options: ["The element Oxygen", "The element Gold", "The element Fluorine", "The element Sodium"], answer: 2, explanation: "Fluorine is the king of greed—it has the highest electronegativity of 4.0! 😈" },
    { id: 'q5', question: "Where would you find the largest atoms on the periodic table?", options: ["Top right corner", "Bottom left corner", "In the middle", "All are same size"], answer: 1, explanation: "Francium (bottom left) has many layers of electrons and a relatively weak nucleus hold, making it a giant! 📈" },
    { id: 'q6', question: "What is the 'Magic Number' of valence electrons most atoms want to reach to be stable?", options: ["Two valence electrons", "Four valence electrons", "Eight valence electrons", "Eighteen valence electrons"], answer: 2, explanation: "The Octet Rule! A full shell of 8 is the goal of almost every chemical reaction. 🎯" },
    { id: 'q7', question: "Why are Noble Gases (Group 18) so unreactive?", options: ["Too many protons", "Full outer shell", "High atomic weight", "Low gas temperature"], answer: 1, explanation: "Since they are at '8', they have no reason to give or take electrons from anyone else! 🛡️" },
    { id: 'q8', question: "As you move DOWN a group, Ionization Energy (the effort to steal an electron):", options: ["Ionization energy increases", "Ionization energy decreases", "Ionization energy stays same", "Ionization energy varies"], answer: 1, explanation: "As the atom gets larger, the outer electron is further from the nucleus and much easier to kick out! 📉" },
    { id: 'q9', question: "What is the horizontal row on the periodic table called?", options: ["A vertical group", "A horizontal period", "A table segment", "An electron orbit"], answer: 1, explanation: "A period (1-7) represents a new 'layer' of electrons being filled. 🧅" },
    { id: 'q10', question: "Which group is known for being EXTREMELY hungy for 1 electron and having high affinity?", options: ["Alkali Metal group", "Noble Gas group", "Halogen element group", "Transition Metal group"], answer: 2, explanation: "Halogens like Chlorine have 7 electrons—they are desperate for just 1 more! 🍕" },
    { id: 'q11', question: "What is unique about 'Metalloids' like Silicon and Germanium?", options: ["They are radioactive", "They act as semiconductors", "They are liquid metals", "They are all gases"], answer: 1, explanation: "Sitting on the trend line allows them to act as both metal and non-metal, perfect for computer switches! 💻" },
    { id: 'q12', question: "Why does adding a proton across a period make an atom SMALLER?", options: ["Protons occupy less space", "Positive charge pulls electrons", "Electrons shrink in size", "Atomic size actually increases"], answer: 1, explanation: "The 'coulombic attraction' between the positive center and negative cloud increases. 🧲" },
    { id: 'q13', question: "Which element is calculated as the 'Noble gas of row 1'?", options: ["The element Hydrogen", "The element Nitrogen", "The element Helium", "The element Oxygen"], answer: 2, explanation: "Even with only 2 electrons, its shell is full, so it's a stable Noble Gas! 🎈" },
    { id: 'q14', question: "Metallic character (the ability to lose electrons) increases toward:", options: ["The top right", "The bottom left", "The top left", "The bottom right"], answer: 1, explanation: "Gigantic atoms on the bottom left lose electrons almost by accident! 🔨" },
    { id: 'q15', question: "What happens when you go from Sodium to Potassium (down Group 1)?", options: ["They become less reactive", "They become more reactive", "They turn into gases", "No properties change"], answer: 1, explanation: "Since Potassium is larger, it loses its outer electron even more easily than Sodium, making it more explosive! 💥" },
    { id: 'q16', question: "Elements in the same vertical column usually have the same number of:", options: ["Total proton count", "Total neutron count", "Valence electron count", "Total electron count"], answer: 2, explanation: "Valence (outer) electrons determine an element's 'personality' or reaction style. 👤" },
    { id: 'q17', question: "Which trend is the OPPOSITE of Atomic Radius?", options: ["The electronegativity trend", "The period number", "The atomic weight", "The atomic density"], answer: 0, explanation: "Small atoms are 'greedy' (High EN). Large atoms are 'giving' (Low EN). ↔️" },
    { id: 'q18', question: "Valency refers to:", options: ["Total proton count", "Atom's combining power", "Natural element color", "Total atomic weight"], answer: 1, explanation: "Valency tells you if an atom needs to lose 1, gain 2, or stay at 0 to reach the octet! 🖇️" },
    { id: 'q19', question: "What are the only two rows that have elements with a 'Metallic Character' trend of zero?", options: ["Rows one and two", "Row seven only", "Noble gas group elements", "Only the bottom row"], answer: 2, explanation: "Noble gases don't act as metals OR non-metals in reactions, they just stay neutral. 🛡️" },
    { id: 'q20', question: "Why can scientists predict properties of element 118 even before seeing it?", options: ["They are simply guessing", "They use trend periodicity", "Einstein predicted the properties", "It consists of gold"], answer: 1, explanation: "The map has no unknown territory; every square has a predictable behavior based on its neighbors! 🔮" },
  ],

  relatedTopics: ['atoms_molecules', 'chemical_bonding', 'periodic_table'],
};
