// ─────────────────────────────────────────────────────────
//  TOPIC: MENTAL SYNDROMES
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'mental_syndromes',
  title: 'Mental Syndromes',
  subtitle: 'Imposter Syndrome, Dunning-Kruger, & cognitive traps 🧠🪤',
  emoji: '🧠',
  category: 'Society',
  accentKey: 'psychology',

  hook: {
    question: "Have you ever felt like a complete fraud, terrified that people will suddenly realize you don't belong here? 🎭",
    reveal: "You aren't alone. In fact, the smarter and more competent a person is, the MORE likely they are to feel like a fraud! Meanwhile, the most incompetent people in the room are usually the loudest and most confident. Why? Because the human brain is riddled with hilarious, frustrating 'bugs.' Let's patch these psychological vulnerabilities by learning how to spot them! 🐛💻",
    emoji: '🔍',
  },

  theory: [
    {
      id: 'dunning_kruger',
      title: 'The Dunning-Kruger Effect 🏔️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏔️',
      svgIcon: 'target',
      content: "The **Dunning-Kruger Effect** is a cognitive bias where people with low ability at a task grossly *overestimate* their ability. \n\nWhy? Because the skills required to be good at a task are the EXACT SAME skills required to recognize you are bad at it! If you don't know the rules of chess, you don't realize how terrible your chess moves are. You sit at the 'Peak of Mount Stupid' feeling like a Grandmaster! ♟️",
      highlight: "Incompetence renders a person blind to their own incompetence. 👁️",
    },
    {
      id: 'imposter_syndrome',
      title: 'Imposter Syndrome 🎭',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎭',
      svgIcon: 'eye',
      content: "The opposite of Dunning-Kruger is **Imposter Syndrome**. High-achieving individuals suffer from chronic self-doubt and feel like 'frauds' who will eventually be exposed.\n\nThey attribute their massive success to luck, timing, or deceiving others, rather than their own intellect or hard work. \nIronically, true 'imposters' don't get Imposter Syndrome—they are too busy enjoying the Dunning-Kruger effect! 🏆",
      highlight: "If you feel like you're faking it, it's actually proof that you aren't. 🛡️",
    },
    {
      id: 'learned_helplessness',
      title: 'Learned Helplessness ⛓️',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⛓️',
      svgIcon: 'lock',
      content: "Discovered by Martin Seligman, **Learned Helplessness** occurs when an animal or human repeatedly endures painful stimuli they cannot escape.\n\nEventually, they 'learn' that they have no control over their environment. \nCrucially, when they *are* finally given a way to escape later on, they don't even try. They just sit and accept the pain. This is the root cause of many severe depressions! 🧠",
      highlight: "You aren't actually trapped; your brain just learned to stop trying the door. 🚪",
    },
    {
      id: 'confirmation_bias',
      title: 'Confirmation Bias 🪞',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🪞',
      svgIcon: 'refresh',
      content: "The brain is extremely lazy. To save energy, it uses **Confirmation Bias**.\n\nOnce you form an opinion, you subconsciously filter the world to only see evidence that *confirms* your belief, while ignoring or attacking evidence that *contradicts* it. \nIf you think you are unlucky, your brain highlights red lights and forgets green lights. You literally build a false reality out of cherry-picked data! 🍒",
      highlight: "You don't see the world as it is; you see the world as YOU are. 👁️",
    },
    {
      id: 'fundamental_attribution',
      title: 'Fundamental Attribution Error 🎯',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🎯',
      svgIcon: 'users',
      content: "When *someone else* cuts you off in traffic, you think: 'What a terrible, selfish human being!' (You attribute it to their *character*).\n\nWhen *you* cut someone off, you think: 'I am so sorry, I had a blind spot and I'm rushing to the hospital!' (You attribute it to your *circumstances*).\n\nThis double-standard is the **Fundamental Attribution Error**—we excuse ourselves based on context, but judge others based on character. ⚖️",
      highlight: "To be kinder, assume everyone else is also rushing to the hospital. 🚑",
    },
    {
      id: 'halo_effect',
      title: 'The Halo Effect 😇',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '😇',
      svgIcon: 'star',
      content: "The **Halo Effect** is our tendency to let one positive trait completely overshadow everything else about a person.\n\nMost commonly, this applies to beauty. If someone is highly attractive, our subconscious brain automatically assumes they are also smart, funny, moral, and trustworthy! ✨\nThis is why attractive people get lighter prison sentences and higher salaries in the real world. Biology is extremely unfair! 🧬",
      highlight: "We are biologically wired to trust good-looking people. Don't fall for it! 🛑",
    },
    {
      id: 'cognitive_dissonance',
      title: 'Cognitive Dissonance 🤯',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🤯',
      svgIcon: 'zap',
      content: "When you hold two conflicting beliefs simultaneously, it creates psychological pain known as **Cognitive Dissonance**.\n\nFor example: 'I am a smart, healthy person' AND 'I smoke cigarettes.' \nTo relieve this pain, instead of quitting smoking (hard), the brain invents a delusion (easy): 'My grandfather smoked and lived to 90, so the science is wrong!' Your brain will literally break logic to protect its ego! 🛡️",
      highlight: "Your brain would rather tell a ridiculous lie than admit a painful truth. 🤥",
    },
    {
      id: 'sunk_cost',
      title: 'The Sunk Cost Fallacy ⚓',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚓',
      svgIcon: 'waves',
      content: "Why do we stay in terrible relationships or watch terrible movies all the way to the end?\n\nThe **Sunk Cost Fallacy**. Our brains violently hate losing things. If we invested 2 hours into a bad movie, turning it off feels like we 'lost' 2 hours. \nSo, we watch another 2 hours to try and justify the initial investment. We throw good time after bad time! ⏳",
      highlight: "Past pain does not justify future pain. Cut your losses immediately! ✂️",
    },
    {
      id: 'bystander_effect',
      title: 'The Bystander Effect 🚶‍♂️',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🚶‍♂️',
      svgIcon: 'users',
      content: "If you have a heart attack in public, you are actually safer if there is only 1 person around than if there are 50! \n\nThis is the **Bystander Effect** (Diffusion of Responsibility). When 50 people see an emergency, everyone assumes someone *else* is going to call 911. As a result, nobody does. \nIf you are ever in trouble in a crowd, point directly to one person and say: 'YOU in the red shirt, call 911!' 🚨",
      highlight: "Responsibility divided by 50 equals zero. Pinpoint your instructions. 🎯",
    },
    {
      id: 'spotlight_effect',
      title: 'The Spotlight Effect 🔦',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔦',
      svgIcon: 'eye',
      content: "Have you ever spilled coffee on your shirt and felt like the entire city was staring at you in judgment? \n\nThe **Spotlight Effect** is our tendency to massively overestimate how much people notice about us. \nIn reality, everyone else is the main character in their own mind, worrying about their own coffee stains. Nobody cares about yours! This realization is the ultimate freedom from social anxiety. 🕊️",
      highlight: "You are the center of your universe, but a background extra in theirs. 🎭",
    },
    {
      id: 'baader_meinhof',
      title: 'The Frequency Illusion 🚗',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🚗',
      svgIcon: 'refresh',
      content: "You buy a red Honda Civic. Suddenly, everywhere you go, you see red Honda Civics! Did everyone buy one today? \n\nNo. This is the **Baader-Meinhof Phenomenon** (Frequency Illusion). Your brain simply upgraded 'Red Civic' from irrelevant background noise to 'High Priority.' \nIt completely warps your statistical perception of the world. What you focus on expands! 🔍",
      highlight: "The universe didn't change; your brain's spam-filter did. 🧽",
    },
    {
      id: 'paradox_of_choice',
      title: 'Analysis Paralysis 🛒',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🛒',
      svgIcon: 'lock',
      content: "Having 3 options is great. Having 300 options is psychological torture. \n\nThe **Paradox of Choice** causes Decision Fatigue. With so many options, the brain worries that it will make the 'wrong' choice. \nFurthermore, when you finally pick one, you compare it to the 299 things you rejected, naturally breeding regret. Limit your options if you want to be happy! 🎛️",
      highlight: "Infinite choices lead to infinite regrets. Embrace constraints. 🧱",
    },
    {
      id: 'pollyanna_principle',
      title: 'The Pollyanna Principle 🌸',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🌸',
      svgIcon: 'heart',
      content: "We often talk about the brain's Negativity Bias, but memory works differently. \n\nThe **Pollyanna Principle** (or Rosy Retrospection) is the tendency to remember the past as far better than it actually was. The brain intentionally forgets the boring/painful parts of a vacation and only remembers the highlight reel. \nThis is why people are always nostalgic for 'the good old days' (which were actually terrible at the time!). 📼",
      highlight: "Your memory is an editor, and it loves deleting the boring scenes. 🎬",
    },
    {
      id: 'placebo_nocebo',
      title: 'Placebo & Nocebo 💊',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '💊',
      svgIcon: 'brain',
      content: "The **Placebo Effect** is famous: taking a sugar pill cures your headache because you *believe* it will. \n\nBut beware the **Nocebo Effect**: If doctors tell you a harmless medicine will cause nausea, your brain will physically construct severe nausea! \nExpectations literally alter your biochemistry. If you expect a conversation to be awkward, your brain will tense your vocal cords to guarantee it is! 🗣️",
      highlight: "Your beliefs are instructions sent directly to your biology. 🧬",
    },
    {
      id: 'combating_bugs',
      title: 'Patching the System 🛠️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🛠️',
      svgIcon: 'shield',
      content: "How do we survive a brain with so many bugs? \n\n1. **Metacognition:** Think about your thinking. Pause and ask, 'Is this a fact, or is this the Sunk Cost Fallacy?' 🤔\n2. **Seek Disconfirming Evidence:** Actively try to prove yourself wrong. (Fights Confirmation Bias). \n3. **De-center yourself:** Remember that nobody is staring at you in the grocery store! \n\nAwareness is the antivirus. 🛡️",
      highlight: "You cannot upgrade your hardware, but you can constantly patch your software! 💻",
    },
  ],

  lab: {
    title: "The Syndrome Simulator 📊🧠",
    description: "Welcome to the Cognitive Lab. Your task is to manipulate the sliders for a simulated human. Adjust their 'Actual Competence' vs. 'Self-Perceived Competence,' and tweak their 'External vs Internal Attribution' (Who do they blame for failure/success?). Watch as the grid maps them into textbook extreme psychological states like Dunning-Kruger Peak, Imposter Syndrome, or crushing Learned Helplessness! 🎛️",
    hint: "To trigger Imposter Syndrome, give the subject maximum Actual Competence, but force them to attribute all their success to External factors (like 'Luck'). Their brain will panic and feel like a fraud!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks neural DMN (Default Mode Network) activity readouts and Epistemic Confidence intervals.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why conspiracy theorists are so incredibly confident? 👽",
      answer: "The Dunning-Kruger effect! Complex geopolitics and science are incredibly hard to understand. It takes a Ph.D. to realize how little we actually know. A conspiracy theory offers a simple, 10-minute explanation. The person gains a tiny bit of knowledge and immediately rockets to the 'Peak of Mount Stupid,' feeling like they cracked the code to the universe! 🏔️",
      emoji: '🛸',
    },
    {
      id: 'dyk2',
      question: "Do you know why we blame traffic on 'stupid drivers' but excuse ourselves when we speed? 🏎️",
      answer: "The Fundamental Attribution Error! Your brain has access to ALL your own context ('I'm speeding because my wife is in labor'). You have zero access to a stranger's context, so your lazy brain defaults to 'They must just be an evil/stupid person.' It's an energy-saving shortcut! ⚖️",
      emoji: '🚗',
    },
    {
      id: 'dyk3',
      question: "Do you know why intelligent students often assume exams were 'too easy' if they finished quickly? 📝",
      answer: "Imposter Syndrome (and the False Consensus Effect). They assume that because a task was easy for *them*, it must be easy for *everyone else*. They completely fail to recognize their own exceptional talent, dismissing it as baseline normal! 🧠",
      emoji: '🎓',
    },
    {
      id: 'dyk4',
      question: "Do you know why we vote for taller politicians? 🕴️",
      answer: "The Halo Effect! From an evolutionary standpoint, tall/attractive people were healthier and made better hunters, so the tribe instinctively followed them. Our modern brains still use this ancient heuristic, mistakenly assuming height equals moral leadership! 👑",
      emoji: '🗳️',
    },
    {
      id: 'dyk5',
      question: "Do you know why it's so hard to quit a terrible relationship of 5 years? 💔",
      answer: "The Sunk Cost Fallacy. Your brain treats time exactly like money. It refuses to accept that it 'wasted' 5 years, so it forces you to spend a 6th year trying to fix the unfixable. You are paying a debt to the past with the currency of your future! ⏳",
      emoji: '⚓',
    },
    {
      id: 'dyk6',
      question: "Do you know why a sugar pill can actually shrink a tumor? 💊",
      answer: "The Placebo Effect! The brain is a pharmacy. If you truly believe a pill will heal you, the Prefrontal Cortex signals the endocrine system to release actual pain-killing endorphins and immune-boosting hormones. Belief is a biological instruction manual! 🧬",
      emoji: '🏥',
    },
    {
      id: 'dyk7',
      question: "Do you know why nobody calls 911 when a crime happens in a crowded area? 🚨",
      answer: "The Bystander Effect. The brain runs a subconscious math equation: 'Risk / Number of people.' If there are 100 people around, you feel only 1% responsible. You assume someone else is dialing, and so does every single other person in the crowd! 📱",
      emoji: '🚶‍♂️',
    },
    {
      id: 'dyk8',
      question: "Do you know why social anxiety usually drops drastically by age 40? 🎂",
      answer: "The collapse of the Spotlight Effect. Teenagers feel like they are on a brightly lit stage being judged. By age 40, your brain has collected enough data to realize the humbling, freeing truth: nobody is thinking about you. They are only thinking about themselves! 🔦",
      emoji: '🕊️',
    },
    {
      id: 'dyk9',
      question: "Do you know why we feel depressed when scrolling through Netflix with thousands of options? 🍿",
      answer: "The Paradox of Choice. Cavemen only had two choices: berry or meat. The human brain cannot compute 4,000 movies. It goes into 'Analysis Paralysis', drains massive amounts of glucose, and ultimately feels regret about whatever movie it picks! 🎬",
      emoji: '😫',
    },
    {
      id: 'dyk10',
      question: "Do you know why abused elephants won't break a tiny rope tied to their leg? 🐘",
      answer: "Learned Helplessness! When they were babies, the rope was too strong to break, so they learned \"struggle is useless.\" As massive adults, they could easily snap it, but the mental chain in their brain is completely unbreakable! ⛓️",
      emoji: '🐘',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the Dunning-Kruger effect?", options: ['Being smart', 'When incompetent people grossly overestimate their skills', 'Fear of heights', 'When smart people fail'], answer: 1, explanation: "Incompetent people lack the skill required to realize how incompetent they are! 🏔️" },
    { id: 'q2', question: "Imposter Syndrome commonly affects:", options: ['Only teenagers', 'Highly competent, successful people who think they are frauds', 'Nobody', 'Animals'], answer: 1, explanation: "They attribute their hard-earned success to luck or deception! 🎭" },
    { id: 'q3', question: "What causes 'Learned Helplessness'?", options: ['Being lazy', 'Repeatedly enduring painful situations you cannot escape, leading you to eventually stop trying', 'Reading books', 'Exercise'], answer: 1, explanation: "The brain turns off the 'escape' protocol to save energy. ⛓️" },
    { id: 'q4', question: "Confirmation Bias is the brain's tendency to:", options: ['Be honest', 'Only see evidence that confirms its existing beliefs, ignoring the rest', 'Count things twice', 'Forget names'], answer: 1, explanation: "Your brain selectively builds a reality out of cherry-picked data! 🍒" },
    { id: 'q5', question: "The Fundamental Attribution Error explains why we:", options: ['Hate numbers', 'Excuse our own bad behavior via context, but blame others\' bad behavior on their character', 'Eat too much', 'Learn fast'], answer: 1, explanation: "I tripped because of a crack. You tripped because you are clumsy! ⚖️" },
    { id: 'q6', question: "Because of the 'Halo Effect', humans tend to assume that attractive people are also:", options: ['Evil', 'Smart, moral, and trustworthy', 'Poor', 'Bad drivers'], answer: 1, explanation: "One glowing trait (looks) blinds us to everything else! 😇" },
    { id: 'q7', question: "Cognitive Dissonance is the psychological pain caused by:", options: ['Loud noises', 'Holding two conflicting beliefs at the same time (e.g. knowing smoking kills, but smoking anyway)', 'Headaches', 'Overeating'], answer: 1, explanation: "The brain often invents delusions just to stop this mental friction! 🤯" },
    { id: 'q8', question: "The 'Sunk Cost Fallacy' makes us:", options: ['Swim faster', 'Stay in bad situations (like a movie or relationship) just because we already invested time into it', 'Save money', 'Buy boats'], answer: 1, explanation: "We throw away our future just to avoid admitting we wasted our past! ⚓" },
    { id: 'q9', question: "According to the Bystander Effect, if you need help in a crowd, what should you do?", options: ['Scream generally', 'Point directly to one specific person and tell them to call 911', 'Run away', 'Play dead'], answer: 1, explanation: "You must break the 'diffusion of responsibility' by singling someone out! 🎯" },
    { id: 'q10', question: "The 'Spotlight Effect' is the irrational feeling that:", options: ['You need a flashlight', 'Everyone around you is staring at you and judging your minor flaws', 'You are famous', 'The sun is too bright'], answer: 1, explanation: "Spoiler alert: Nobody cares about the coffee stain on your shirt! 🔦" },
    { id: 'q11', question: "The Baader-Meinhof Phenomenon (Frequency Illusion) explains why:", options: ['You see a car everywhere after you buy it', 'Songs get stuck in your head', 'Math is hard', 'Germany is cold'], answer: 0, explanation: "Your brain upgraded that car from 'background noise' to 'priority data'! 🚗" },
    { id: 'q12', question: "The 'Paradox of Choice' states that having thousands of options usually leads to:", options: ['Total happiness', 'Decision fatigue, paralysis, and regret', 'Speedy choices', 'Wealth'], answer: 1, explanation: "The human brain cannot compute infinity. It prefers simple, constrained choices. 🛒" },
    { id: 'q13', question: "The Pollyanna Principle explains why we often:", options: ['Wear pink', 'Over-romanticize the past and forget the bad parts (Nostalgia)', 'Hate flowers', 'Eat candy'], answer: 1, explanation: "Your memory is a sneaky editor that deletes the boring scenes! 🌸" },
    { id: 'q14', question: "The Nocebo Effect proves that:", options: ['Pills are fake', 'If you expect a negative outcome, your biology will often construct it physically', 'Doctors lie', 'Water is healthy'], answer: 1, explanation: "It is the evil twin of the Placebo effect. Your expectations command your body! 💊" },
    { id: 'q15', question: "To combat Confirmation Bias, you should actively try to:", options: ['Argue louder', 'Seek out evidence that proves yourself WRONG', 'Watch the news', 'Sleep more'], answer: 1, explanation: "It is incredibly uncomfortable, but it is the only way to find the truth! 🪞" },
    { id: 'q16', question: "Someone at the 'Peak of Mount Stupid' (Dunning-Kruger) usually feels:", options: ['Depressed', 'Extremely confident in their abilities', 'Scared', 'Sleepy'], answer: 1, explanation: "They don't know enough to know how much they don't know! 🏔️" },
    { id: 'q17', question: "Someone suffering from Imposter Syndrome attributes their success to:", options: ['Hard work', 'Luck, timing, or deceiving others', 'Genetics', 'Books'], answer: 1, explanation: "They refuse to accept that their own intellect earned the prize. 🎭" },
    { id: 'q18', question: "A captive elephant not breaking a tiny rope is an example of:", options: ['A magic trick', 'Learned Helplessness', 'Evolution', 'Poor diet'], answer: 1, explanation: "The physical chain is weak, but the mental chain is unbreakable! 🐘" },
    { id: 'q19', question: "Cognitive Dissonance often leads people to:", options: ['Invent illogical excuses to justify bad behavior', 'Become smarter', 'Lift weights', 'Stop breathing'], answer: 0, explanation: "To protect the ego, the brain will literally reject scientific reality! 🛡️" },
    { id: 'q20', question: "If you feel socially anxious at a party, reminding yourself of the Spotlight Effect helps you realize:", options: ['You are glowing', 'Nobody is actually scrutinizing you', 'You need to perform', 'The lights are hot'], answer: 1, explanation: "Everyone else is too busy worrying about their own outfits! 🕊️" },
  ],

  relatedTopics: ['cognitive_biases', 'manipulation_tactics', 'mental_health_basics'],
};
