export default {
  // ── IDENTITY ────────────────────────────────
  id: 'atoms_molecules',
  title: 'Atoms & Molecules',
  subtitle: 'The incredibly tiny building blocks of reality ⚛️',
  emoji: '⚛️',
  category: 'Foundations',
  accentKey: 'chemistry',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "Empty space. If you took all the empty space out of the atoms in your body, do you know how small you would be?",
    reveal: "You would be the size of a grain of sand! 🏖️ Atoms are 99.999% completely empty space. The chair you are sitting on, the phone you are holding, and the stars in the sky are entirely made up of empty space held together by invisible energetic forces. The solid reality you feel is just a trick of physics. Let's zoom in a trillion times and see what the universe is really made of! 🔬",
    emoji: '🌌',
  },

  // ── THEORY CARDS (10) ───────────────────────
  theory: [
    {
      id: 'what_is_atom',
      title: 'What is an Atom? 🧱',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧱',
      svgIcon: 'atom',
      content: "An atom is the fundamental building block of all matter. Everything you can touch, breathe, or see is made of atoms.\n\nThe word \"atom\" comes from Greek, meaning \"uncuttable\". For a long time, scientists thought atoms were the smallest possible things in the universe, tiny solid spheres that could not be broken.\n\nNow we know that atoms are actually complex miniature systems, almost like tiny solar systems, made up of even smaller pieces called subatomic particles.",
      highlight: "A single grain of sand contains roughly 50 quintillion (50,000,000,000,000,000,000) atoms!",
    },
    {
      id: 'the_nucleus',
      title: 'The Nucleus: Heavy & Tiny 🎯',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🎯',
      svgIcon: 'target',
      content: "At the exact center of every atom lies the **Nucleus**.\n\nThe nucleus contains two main particles:\n1. **Protons:** Positively charged (+) particles.\n2. **Neutrons:** Particles with no charge (neutral).\n\nThe nucleus is incredibly tiny compared to the whole atom, but it contains 99.9% of the atom's entire weight! It is bound together by the Strong Nuclear Force, the most powerful force in the universe.",
      highlight: "If an atom were the size of a giant football stadium, the heavy nucleus would be the size of a single pea sitting on the 50-yard line. 🏟️",
    },
    {
      id: 'electrons',
      title: 'Electrons & The Empty Space ⚡',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '⚡',
      svgIcon: 'lightning',
      content: "Swarming around the heavy nucleus at near light-speed are **Electrons**.\n\nElectrons are negatively charged (-) particles. They are thousands of times smaller and lighter than protons. They don't orbit in perfect planetary rings; instead, they exist in blurry probability 'clouds' or 'shells'.\n\nBecause positive (protons) and negative (electrons) attract each other, the electrons are trapped orbiting the nucleus. The massive gap between the nucleus and the electron cloud is made of absolutely nothing. Pure empty space.",
      highlight: "When you touch a table, you aren't actually touching it! Your electrons are magnetically repelling the table's electrons. You are basically levitating! 🧲",
    },
    {
      id: 'elements',
      title: 'Elements: Built by Protons 🥇',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🥇',
      svgIcon: 'grid',
      content: "What makes gold shiny and yellow, but oxygen an invisible gas? It all comes down to the number of **Protons**.\n\nThe number of protons in an atom's nucleus strictly determines what Element it is.\n- 1 Proton = Hydrogen (Lightest gas)\n- 6 Protons = Carbon (Basis of life)\n- 79 Protons = Gold (Heavy, shiny metal)\n\nChanging the number of protons literally completely changes the physical material. This is what ancient Alchemists were trying to do when they tried to turn lead into gold!",
      highlight: "There are 118 known elements in the universe. Everything is just a different combination of these 118 'Legos'. 🧩",
    },
    {
      id: 'isotopes',
      title: 'Isotopes & Radioactivity ☢️',
      color: '#A855F7',
      bgGradient: ['#1A0A1F', '#050D0A'],
      icon: '☢️',
      svgIcon: 'radiation',
      content: "While Protons determine the element, what about Neutrons?\n\nNeutrons act like nuclear 'glue', holding the pushing protons together. If an atom has the same number of protons but a *different* number of neutrons, it is called an **Isotope**.\n\nCarbon normally has 6 protons and 6 neutrons (Carbon-12). But Carbon-14 has 8 neutrons. This makes the nucleus unstable and wobbly. To fix itself, it shoots off pieces of itself as energy. We call this **Radioactivity**!",
      highlight: "Scientists use the slow radioactive decay of Carbon-14 to date ancient dinosaur bones and mummies! 🦴",
    },
    {
      id: 'molecules',
      title: 'Molecules: The Team Up 🤝',
      color: '#3B82F6',
      bgGradient: ['#0A1220', '#050D0A'],
      icon: '🤝',
      svgIcon: 'link',
      content: "Atoms rarely like to be alone. To become completely stable, they team up and share their outer electrons with other atoms. \n\nWhen two or more atoms bond together, they form a **Molecule** or a **Compound**.\n\nTake water, for example. It is made of two Hydrogen atoms and one Oxygen atom (H₂O). Hydrogen is explosive gas. Oxygen is fire-fueling gas. But bond them together? You get liquid water that puts out fires! The molecule acts entirely differently than its ingredients.",
      highlight: "A single drop of water contains about 1.5 sextillion (1,500,000,000,000,000,000,000) H₂O molecules! 💧",
    },
    {
      id: 'quantum',
      title: 'The Quantum Realm 🎇',
      color: '#FF007F',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '🎇',
      svgIcon: 'sparkle',
      content: "When you zoom inside an atom, the normal rules of physics literally stop working. Welcome to Quantum Mechanics.\n\nIn this realm, electrons can exist in multiple places at the exact same time (Superposition), disappear and reappear on the other side of walls (Quantum Tunneling), and communicate instantly across the universe (Entanglement).\n\nIf you find this confusing, don't worry. Famous physicist Richard Feynman famously said: \"I think I can safely say that nobody understands quantum mechanics.\"",
      highlight: "Without the bizarre rules of Quantum tunneling, the Sun wouldn't be able to fuse atoms and shine! ☀️",
    },
    {
      id: 'ions',
      title: 'Ions & Electricity 🔋',
      color: '#00D4A0',
      bgGradient: ['#001A13', '#050D0A'],
      icon: '🔋',
      svgIcon: 'battery',
      content: "Normally, an atom has the exact same number of (+) protons and (-) electrons, making it neutral (0 charge).\n\nBut electrons are on the very outside of the atom, meaning they can easily be knocked off or stolen!\n- If an atom loses an electron, it becomes positively charged.\n- If it gains an electron, it becomes negatively charged.\n\nThese charged atoms are called **Ions**. The flow of these stolen electrons jumping from atom to atom is exactly what we call **Electricity**! ⚡",
      highlight: "Salt dissolves in water by breaking into charged Ions, which allows salt water to conduct electricity perfectly! 🌊",
    },
    {
      id: 'states',
      title: 'Temperature & Movement 🌡️',
      color: '#FF7A59',
      bgGradient: ['#1A0905', '#050D0A'],
      icon: '🌡️',
      svgIcon: 'thermometer',
      content: "Even when looking at a solid rock, the atoms inside are violently vibrating. \n\n**Temperature** is nothing more than the speed of atomic movement.\n- **Solids:** Atoms are locked together, vibrating slightly.\n- **Liquids:** Atoms are moving fast enough to slide past each other.\n- **Gases:** Atoms are flying around wildly, bouncing off walls.\n\nIf you freeze something to -273.15°C (Absolute Zero), the atoms completely stop moving. Heat something up enough, and the electrons rip off entirely, forming Plasma!",
      highlight: "The Sun, lightning bolts, and neon signs are all made of Plasma—the 4th state of matter! 🌩️",
    },
    {
      id: 'origin',
      title: 'We Are Stardust ✨',
      color: '#7B2CBF',
      bgGradient: ['#0D051A', '#050D0A'],
      icon: '✨',
      svgIcon: 'star',
      content: "Where did all these atoms come from?\n\nImmediately after the Big Bang, the universe only had the simplest atoms: Hydrogen and Helium. \nTo make bigger atoms like Carbon, Oxygen, and Iron, you need insane amounts of heat and pressure. The only place in the universe hot enough to smash these together is the core of a massive Star. \n\nWhen those stars exploded as Supernovas, they blasted these heavy elements across the galaxy. Eventually, those atoms clumped together to form Earth, and you.",
      highlight: "Every atom of iron in your blood, and calcium in your bones, was literally forged inside an exploding star billions of years ago. You are star-stuff. 🌌",
    },
  ],
  
  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Quantum Physics Lab 🔬",
    description: "Welcome to the subatomic realm! Play 4 distinct mini-games to build nuclei out of protons, drop electrons into quantum shells, combine explosive gases into life-giving water, and appreciate the terrifying scale of the microscopic universe.",
    hint: "If you build an unstable isotope, the atom will turn red and vibrate. Make sure your electrons fill the inner orbital completely before using the outer shell!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time atomic mass values and exact quantum shell electron configurations.",
  },

  // ── DO YOU KNOW WHY (5) ─────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we can't 'see' a single atom? 👁️",
      answer: "Because atoms are actually smaller than the wavelengths of visible light! Since a light wave is too big to hit an atom and bounce back to your eye, using a regular optical microscope is physically impossible. Scientists have to use electron microscopes, which fire tiny electrons instead of light, to map out the shape of atoms. 🔬",
      emoji: '🔦',
    },
    {
      id: 'dyk2',
      question: "Do you know why dropping a tiny piece of Sodium metal in water causes it to violently explode? 💥",
      answer: "A Sodium atom is highly unstable because it has exactly 1 lonely electron in its outer shell. It desperately wants to get rid of it. Water (H₂O) strongly pulls electrons. When they touch, the Sodium rips its own electron off so violently and rapidly that it generates immense heat, igniting the hydrogen gas and causing an explosion! 🎆",
      emoji: '🔥',
    },
    {
      id: 'dyk3',
      question: "Do you know why diamond and graphite (pencil lead) look completely different but are both made 100% of Carbon atoms? ✏️💎",
      answer: "The atoms are identical, but the *bonds* (the way they connect to each other) are completely different! In graphite, the carbon atoms form flat sheets that easily slide off (perfect for leaving a mark on paper). In diamond, they form an ultra-strong 3D tetrahedral grid, locking them permanently into place and making it one of the hardest materials on Earth! 📐",
      emoji: '💎',
    },
    {
      id: 'dyk4',
      question: "Do you know why radiation from unstable atoms is dangerous to humans? ☢️",
      answer: "Unstable radioactive atoms (isotopes) shed excess energy by firing out high-speed particles. These atomic 'bullets' are so small and fast they shoot straight through your body. If they hit the DNA molecules inside your cells, they can shatter the delicate Double Helix bonds. This 'typo' can cause the cell to malfunction and eventually turn into cancer. 🩹",
      emoji: '⚕️',
    },
    {
      id: 'dyk5',
      question: "Do you know why Hydrogen is the most common element in the entire universe? 🌌",
      answer: "Because it is the absolute simplest atom to build! Hydrogen requires just 1 Proton and 1 Electron. Immediately after the Big Bang cooled down enough for particles to form, the universe was instantly flooded with these simple pairs. Over 74% of the visible mass of the universe is still just Hydrogen! 🎈",
      emoji: '1️⃣',
    },
  ],

  // ── QUIZ (20) ───────────────────────────────
  quiz: [
    { id: 'q1', question: "What is an atom?", options: ['A type of star', 'A biological cell', 'The fundamental building block of all matter', 'A chemical explosion'], answer: 2, explanation: "An atom is the smallest unit of ordinary matter. Everything is made of atoms! 🧱" },
    { id: 'q2', question: "What particles are found in the heavy nucleus of the atom?", options: ['Electrons and Photons', 'Protons and Neutrons', 'Neutrons and Electrons', 'Only Protons'], answer: 1, explanation: "The dense center nucleus is made of positively charged Protons and neutral Neutrons. 🎯" },
    { id: 'q3', question: "What orbits the nucleus at incredibly high speeds?", options: ['Protons', 'Photons', 'Electrons', 'Quarks'], answer: 2, explanation: "Tiny, negatively charged Electrons orbit the nucleus in blurry probability clouds. ⚡" },
    { id: 'q4', question: "Most of the space inside an atom is:", options: ['Pure empty space', 'Filled with air', 'Filled with liquid water', 'Packed tightly with protons'], answer: 0, explanation: "Atoms are 99.999% completely empty space! 🌌" },
    { id: 'q5', question: "Which particle defines what specific 'Element' an atom is (like Gold vs Oxygen)?", options: ['Number of Electrons', 'Number of Protons', 'Number of Neutrons', 'Size of the atom'], answer: 1, explanation: "The number of Protons (the Atomic Number) strictly defines the identity of the element. 🥇" },
    { id: 'q6', question: "If an atom has 1 Proton, what element is it?", options: ['Oxygen', 'Iron', 'Carbon', 'Hydrogen'], answer: 3, explanation: "Hydrogen is element #1, possessing only 1 Proton. 🎈" },
    { id: 'q7', question: "What happens if an atom has too many or too few neutrons?", options: ['It becomes a different element', 'It becomes an unstable, radioactive Isotope', 'It explodes instantly', 'It turns into liquid'], answer: 1, explanation: "Changing the neutrons creates an Isotope. If the ratio is bad, it becomes unstable and emits radiation. ☢️" },
    { id: 'q8', question: "When two or more atoms bond together, what do they form?", options: ['A Molecule', 'An Ion', 'Protons', 'A Black Hole'], answer: 0, explanation: "Atoms join chemically to form Molecules, like H2O (Water) or CO2 (Carbon Dioxide). 🔗" },
    { id: 'q9', question: "If an atom steals an electron and becomes negatively charged, it is called an:", options: ['Isotope', 'Ion', 'Alloy', 'Quark'], answer: 1, explanation: "Charged atoms (that have lost or gained electrons) are called Ions. Flowing Ions create electricity! 🔋" },
    { id: 'q10', question: "What is the science that describes how confusingly particles behave when you zoom incredibly close?", options: ['Relativity', 'Thermodynamics', 'Quantum Mechanics', 'Kinetics'], answer: 2, explanation: "Quantum Mechanics describes the terrifyingly weird rules of the microscopic universe. 🎇" },
    { id: 'q11', question: "Which force is responsible for holding the repulsive protons together inside the nucleus?", options: ['Gravity', 'Electromagnetism', 'The Strong Nuclear Force', 'Friction'], answer: 2, explanation: "The Strong Nuclear Force is exactly what it sounds like—the strongest force in the universe, locking protons together. 💪" },
    { id: 'q12', question: "What do atoms do when a substance is frozen to 'Absolute Zero'?", options: ['They shrink', 'They turn invisible', 'They stop moving completely', 'They multiply'], answer: 2, explanation: "Temperature is just atomic vibration. At absolute zero, they lose all energy and completely stop. 🧊" },
    { id: 'q13', question: "If objects are mostly empty space, why don't you fall through your chair?", options: ['Gravity holds you up', 'Your atoms are physically solid', 'The electrons repel each other', 'Air pressure'], answer: 2, explanation: "The negative electrons of your pants electromagnetically repel the negative electrons of the chair! You are hovering! 🧲" },
    { id: 'q14', question: "How many elements currently exist on the Periodic Table?", options: ['About 50', 'Exactly 118', 'Thousands', '4 (Earth, Fire, Wind, Water)'], answer: 1, explanation: "There are currently 118 known elements. Everything in the universe is a combination of these 118 base 'legos'. 🧪" },
    { id: 'q15', question: "Which atoms were forged shortly after the Big Bang?", options: ['Iron and Gold', 'Carbon and Oxygen', 'Only Hydrogen and Helium', 'All 118 elements'], answer: 2, explanation: "The Big Bang only created the simplest atoms. All the rest had to be forged inside stars much later. 💥" },
    { id: 'q16', question: "Carbon-12 and Carbon-14 differ in their number of:", options: ['Protons', 'Neutrons', 'Electrons', 'Quarks'], answer: 1, explanation: "They are Isotopes! They are both Carbon (6 Protons), but have different numbers of Neutrons. ☢️" },
    { id: 'q17', question: "In a stable, neutral atom, the number of Protons is exactly equal to the number of:", options: ['Neutrons', 'Nuclei', 'Quarks', 'Electrons'], answer: 3, explanation: "The (+) Protons perfectly cancel out the (-) Electrons to make the atom electrically neutral (0 charge). ⚖️" },
    { id: 'q18', question: "When atoms are heated so intensely that their electrons are entirely ripped off, it forms a fluid called:", options: ['Gas', 'Plasma', 'Liquid', 'Solid'], answer: 1, explanation: "Plasma is the 4th state of matter, found in stars and lightning bolts! 🌩️" },
    { id: 'q19', question: "What is the formula for a Water molecule?", options: ['CO2', 'O2', 'NaCl', 'H2O'], answer: 3, explanation: "Water is H2O: 2 Hydrogen atoms sharing electrons with 1 Oxygen atom! 💧" },
    { id: 'q20', question: "Where were all the heavy atoms in your body (like Carbon, Oxygen, and Iron) originally created?", options: ['Inside the Earth', 'During the Big Bang', 'Inside an exploding star (Supernova)', 'In the ocean'], answer: 2, explanation: "You are literally stardust. The extreme pressure of an exploding star forged the atoms that make up your body. ✨" },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['chemical_bonding', 'periodic_table', 'forces_motion'],
};
