export default {
  id: 'periodic_table',
  title: 'Periodic Table Basics',
  subtitle: 'The most powerful organising chart in all of science 🧪',
  emoji: '🧪',
  category: 'Foundations',
  accentKey: 'grid',

  hook: {
    question: "Did you know Dmitri Mendeleev predicted three undiscovered elements in 1869 — and when they were found, they matched his predictions so precisely it was called miraculous? 🤯",
    reveal: "Mendeleev noticed that when elements were arranged by atomic mass, properties REPEATED at regular intervals. He left BLANK SPACES for elements not yet discovered, predicted their properties, and was proven right when Gallium (1875), Scandium (1879), and Germanium (1886) were found — perfectly matching his predictions. The periodic table isn't just a wall chart — it's a map of reality. Every element was predicted before it was found. Every reaction between every atom in the universe follows the table's rules. It is arguably humanity's greatest scientific achievement. ⚗️",
    emoji: '🧪',
  },

  theory: [
    { id: 'history', title: 'The Table\'s Origins 📜', color: '#FDCB6E', bgGradient: ['#2A1A00', '#05050A'], icon: '📜', svgIcon: 'book', content: "The periodic table has a fascinating history of discovery:\n\n**Key milestones:**\n1661 — Robert Boyle defines 'element' as a substance that cannot be chemically simplified\n1789 — Antoine Lavoisier lists 33 elements (including 'light' and 'heat' — wrong but early!)\n1803 — John Dalton proposes atomic theory\n1829 — Johann Döbereiner notices 'triads' — groups of 3 elements with similar properties\n1863 — John Newlands proposes 'octave rule' — properties repeat every 8 elements (laughed out of the Royal Society!)\n🏆 1869 — **Dmitri Mendeleev** arranges 63 known elements by atomic mass, leaves gaps, predicts missing elements → THE periodic table\n1913 — Henry Moseley discovers atomic NUMBER (protons), not mass, is the true organising principle\n\n**Why Mendeleev, not Lothar Meyer?**\nGerman chemist Lothar Meyer produced virtually the same table at the same time. Mendeleev gets credit because he made bold PREDICTIONS and was proven right. Science rewards successful prediction! 🎯\n\nToday: 118 elements confirmed. Elements 119 and beyond are being synthesised but have half-lives of milliseconds. The table may extend to period 8 — 'superactinides'. ⚗️", highlight: "Mendeleev predicted three undiscovered elements in 1869 — when found years later, their properties matched his predictions almost exactly! 📜" },
    { id: 'structure', title: 'Table Structure: Periods & Groups 🔢', color: '#00CEFF', bgGradient: ['#001A28', '#05050A'], icon: '🔢', svgIcon: 'grid', content: "The periodic table is organised into **periods** (rows) and **groups** (columns):\n\n**Periods (7 horizontal rows):**\n📊 Each period = new electron shell being filled\n📊 Period 1: 2 elements (H, He)\n📊 Period 2: 8 elements (Li to Ne)\n📊 Period 6: 32 elements (including lanthanides)\n📊 Period 7: 32 elements (including actinides — mostly radioactive!)\n\n**Groups (18 vertical columns):**\n🔵 **Group 1: Alkali Metals** (Li, Na, K...) — highly reactive, soft, 1 valence electron\n🔵 **Group 2: Alkaline Earth Metals** (Mg, Ca...) — reactive, 2 valence electrons\n🟡 **Group 17: Halogens** (F, Cl, Br, I) — extremely reactive nonmetals, 7 valence electrons\n🟢 **Group 18: Noble Gases** (He, Ne, Ar) — chemically inert, 8 valence electrons (full shell!)\n\n**Main regions:**\n⚙️ **Metals** (left+centre, ~80 elements): shiny, malleable, conductive\n❌ **Nonmetals** (upper right, 17 elements): dull, brittle, poor conductors\n🔮 **Metalloids/Semimetals** (zigzag boundary): properties of both (Silicon — semiconductors!)\n🔴 **Transition Metals** (middle block): complex chemistry, multiple oxidation states, coloured compounds 🎨", highlight: "Silicon sits on the metal-nonmetal boundary as a metalloid semiconductor — this property makes all computer chips possible! 🔢" },
    { id: 'atomic_number', title: 'Atomic Number: The Identity 🔬', color: '#6C5CE7', bgGradient: ['#0A001A', '#05050A'], icon: '🔬', svgIcon: 'atom', content: "The **atomic number** (Z) = number of **protons** in the nucleus. This is what makes an element what it is.\n\nChange the proton count and you have a completely different element:\n1 proton = Hydrogen\n2 protons = Helium\n6 protons = Carbon\n79 protons = Gold\n\n**Why proton number, not mass?**\nAtoms can have different numbers of **neutrons** (isotopes) with the same chemistry but different mass. Mendeleev originally used mass and occasionally put elements in the wrong order because of this. Moseley fixed this using X-ray frequency measurements in 1913!\n\n**Isotopes:**\n🔬 Carbon-12 (6p, 6n) — stable, 98.9% of carbon\n🔬 Carbon-13 (6p, 7n) — stable, 1.1%\n🔬 Carbon-14 (6p, 8n) — radioactive! Used for radiocarbon dating (half-life 5,730 years)\n\n**Atomic mass = weighted average of isotopes:**\nChlorine has mass 35.45 — because 75% is Cl-35 and 25% is Cl-37.\n\n**Ions:**\nAtoms that gain electrons → anions (negative): F⁻, O²⁻\nAtoms that lose electrons → cations (positive): Na⁺, Ca²⁺\nProton count doesn't change — only electron count! An iron nail (Fe) and rust (Fe³⁺) have the same atomic number — just different electron counts. 🔴", highlight: "Changing proton count changes the element entirely — but atoms can gain/lose electrons (ions) or neutrons (isotopes) while remaining the same element! 🔬" },
    { id: 'electron_config', title: 'Electron Configuration ⚡', color: '#00B894', bgGradient: ['#001A14', '#05050A'], icon: '⚡', svgIcon: 'lightning', content: "**Electron configuration** determines ALL chemical behaviour — what bonds an element forms, what compounds it makes, how it reacts.\n\n**Shell model (simplified):**\n🔵 Electrons occupy shells (energy levels). Inner shells fill before outer ones.\n🔵 Max electrons per shell: 2, 8, 8, 18... (Aufbau principle)\n\n**Example:** Sodium (Na, Z=11)\n→ Shell 1: 2 electrons\n→ Shell 2: 8 electrons\n→ Shell 3: 1 electron ← the LONE valence electron!\nThis single outer electron is why Na is extremely reactive and why it forms Na⁺.\n\n**Valence electrons** — the outermost shell electrons — determine chemical reactivity:\n🟢 1 valence e⁻ = very reactive metal (alkali metals)\n🟡 7 valence e⁻ = very reactive nonmetal (halogens)\n✅ 8 valence e⁻ = extremely stable, inert (noble gases — complete shell, 'octet'!)\n\n**The Octet Rule:** Atoms react to achieve 8 valence electrons (noble gas configuration). This drives ALL of chemistry!\n\n**Subshells (quantum model):** s, p, d, f orbitals have different shapes. Transition metals fill d orbitals — their partially-filled d orbitals give them multiple oxidation states and coloured compounds (why copper is blue in solution, why iron is red as rust!).", highlight: "ALL of chemistry is driven by the Octet Rule — atoms react specifically to get 8 valence electrons (full outer shell)! ⚡" },
    { id: 'periodic_trends', title: 'Periodic Trends: Patterns Across the Table 📈', color: '#FF7675', bgGradient: ['#2A0A00', '#05050A'], icon: '📈', svgIcon: 'chart', content: "Properties change in predictable trends across the table — this is what makes the periodic table POWERFUL.\n\n**Atomic Radius:**\n↔️ Across a period (left → right): DECREASES (more protons pull electrons closer)\n↕️ Down a group (top → bottom): INCREASES (more electron shells)\n\n**Ionisation Energy** (energy to remove an electron):\n↔️ Left → right: INCREASES (harder to remove electron; more nuclear pull)\n↕️ Top → bottom: DECREASES (outer electrons are further from nucleus; easier to remove)\n\n**Electronegativity** (tendency to attract bonding electrons):\n↔️ Left → right: INCREASES\n↕️ Top → bottom: DECREASES\n🏆 Most electronegative: Fluorine (F) — the most electronegative element in existence!\n\n**Metallic Character:**\n↔️ Left → right: DECREASES\n↕️ Top → bottom: INCREASES\n\n**These trends explain everything:**\n💥 Why Na reacts violently with water (low IE, loses e⁻ easily)\n💧 Why F picks up electrons from almost anything (highest EN)\n🔋 Why Li-ion batteries work (Li has tiny radius; easy ion transport)\n🌡️ Why noble gases have very low boiling points (no reactivity = only weak London forces!) 📊", highlight: "Fluorine is the most electronegative element in existence — it attracts electrons so strongly it can react with noble gases like Xenon! 📈" },
    { id: 'elements_of_life', title: 'Elements of Life 🌱', color: '#00B894', bgGradient: ['#001A14', '#05050A'], icon: '🌱', svgIcon: 'leaf', content: "Only a tiny fraction of elements are necessary for life:\n\n**The Big 4 (95% of living matter):**\n⚛️ **Oxygen (O)** — 65% of body mass (mostly in water)\n⚛️ **Carbon (C)** — 18% (backbone of ALL organic molecules)\n⚛️ **Hydrogen (H)** — 10% (water, organic molecules)\n⚛️ **Nitrogen (N)** — 3.3% (proteins, DNA)\n\n**Essential elements (smaller amounts):**\n🔴 Calcium — bones/teeth (hydroxyapatite), nerve signalling\n🔴 Phosphorus — DNA backbone, ATP (energy), cell membranes\n🔴 Iron — haemoglobin carries O₂ (you need 4g total!)\n🔴 Iodine — thyroid hormone (thyroxine)\n🔴 Potassium/Sodium — nerve impulses (ion channels)\n🔴 Zinc — 300+ enzyme cofactors\n\n**Carbon's uniqueness:**\nCarbon forms 4 stable bonds in any direction → can build unlimited chain, ring, and branching structures → 10 million+ known organic compounds vs ~500,000 for all other elements combined!\nThis is why carbon is the basis of life, not silicon (same group, same number of bonds, but silicon-silicon bonds are weaker and silicon-oxygen bonds are too strong → silicates, not biochemistry!). 🌿", highlight: "Carbon forms 10 million+ known compounds compared to 500,000 for all other elements combined — its 4-bond geometry makes life possible! 🌱" },
    { id: 'alkali_metals', title: 'Alkali Metals: Group 1 Explosions 💥', color: '#FD79A8', bgGradient: ['#2A001A', '#05050A'], icon: '💥', svgIcon: 'lightning', content: "**Alkali metals (Group 1):** Li, Na, K, Rb, Cs, Fr — the most reactive metals on Earth.\n\nAll have 1 valence electron, which is easily lost → metal + 1 charge ion\n\n**Reactivity increases down the group:**\n🔵 Li reacts slowly with water — gentle fizzing\n🟡 Na reacts vigorously — jumps across water, catches fire\n🔴 K reacts violently — purple flame, explodes\n🟠 Rb reacts explosively — ignites in humid air alone\n⚡ Cs reacts catastrophically\n🌌 Fr (francium) — radioactive, half-life 22 minutes; barely exists naturally!\n\n**Why reactivity increases:**\nDown the group: more electron shells → valence electron farther from nucleus → easier to remove (lower ionisation energy) → more reactive!\n\n**Why are they stored in oil?**\nAlkali metals react so violently with water or air (oxygen + moisture) they must be kept submerged in mineral oil. Cesium even reacts with ice at −100°C!\n\n**Uses:**\n⚡ Lithium-ion batteries (Li)\n🔦 Street lamps, NaCl table salt (Na)\n🌿 Fertilisers (K, as potassium)\n💊 Lithium carbonate — treats bipolar disorder\n📸 Cesium — atomic clocks!", highlight: "Cesium reacts EXPLOSIVELY with water — and even reacts with ice at −100°C! Francium is so radioactive it barely exists in nature! 💥" },
    { id: 'noble_gases', title: 'Noble Gases: The Loners 🏆', color: '#B2BEC3', bgGradient: ['#1A1A1A', '#05050A'], icon: '🏆', svgIcon: 'sparkle', content: "**Noble gases (Group 18):** He, Ne, Ar, Kr, Xe, Rn — the laziest elements on the periodic table.\n\nAll have 8 valence electrons (full outer shell) → zero need to react → chemical inertness.\n\n**Historical note:** They were called 'inert gases' until 1962 when Neil Bartlett made the first noble gas compound — XePtF₆ (xenon platinum hexafluoride). The scientific community was shocked. Now over 2,000 xenon and krypton compounds are known. Radon forms compounds too. Only helium, neon, and argon remain truly inert.\n\n**Why can xenon react at all?**\nXe in Period 5 — outer electrons are far from nucleus (low effective nuclear charge). Fluorine's extreme electronegativity can pull electron density from Xe. But this only works with the most electronegative elements!\n\n**Uses:**\n🎈 Helium — balloons, MRI cooling (liquid He at −269°C), deep sea diving mix\n💡 Neon — neon signs (glows red-orange when ionised)\n🔦 Argon — welding protection, lightbulb filling\n📸 Krypton/Xenon — flash photography, car headlights, anaesthesia (Xe!)\n☢️ Radon — naturally occurring radioactive gas; #2 cause of lung cancer after smoking! Seeps from granite rocks. Ventilate your basement! 🏠", highlight: "Noble gases were believed completely inert until 1962 when xenon was forced to react — the scientific community was genuinely shocked! 🏆" },
    { id: 'transition_metals', title: 'Transition Metals: The Colourful Core 🎨', color: '#FDCB6E', bgGradient: ['#2A1A00', '#05050A'], icon: '🎨', svgIcon: 'sparkle', content: "**Transition metals (Groups 3-12):** 38 elements with complex, beautiful chemistry — and they fill the middle of the periodic table.\n\n**What makes them special:**\n🔄 **Multiple oxidation states** — iron: Fe, Fe²⁺, Fe³⁺; copper: Cu, Cu⁺, Cu²⁺; manganese: Mn²⁺ to Mn⁷⁺!\n🎨 **Coloured compounds** — partially filled d-orbitals interact with light:\n• Copper(II) compounds: blue/green (copper sulfate — blue!)\n• Iron(III) compounds: brown/orange (rust!)\n• Chromium(III): green; Chromium(VI): orange (toxic!)\n• Manganese(VII): deep purple (permanganate solution)\n• Cobalt(II): pink; Nickel(II): green\n⚗️ **Catalytic activity** — partially filled d orbitals can form temporary bonds with reactants:\n• Iron catalyst in Haber process (NH₃ fertiliser production — feeds half the world!)\n• Platinum/Palladium in car catalytic converters\n• Vanadium pentoxide in sulfuric acid production\n\n**Everyday transition metals:**\n🔩 Iron (construction, haemoglobin)\n⚡ Copper (wiring, plumbing)\n🌟 Gold (electronics, currency)\n🔬 Titanium (aircraft, medical implants — body-compatible!)\n💎 Platinum (catalysts, jewellery, cancer drugs — cisplatin!) 🏥", highlight: "Transition metals' partially filled d-orbitals create coloured compounds AND catalytic properties — iron catalyst in Haber process feeds half the world! 🎨" },
    { id: 'radioactivity', title: 'Radioactive Elements ☢️', color: '#00CEC9', bgGradient: ['#001A18', '#05050A'], icon: '☢️', svgIcon: 'atom', content: "Elements beyond lead (Z=82) in the periodic table are all unstable and radioactive — their nuclei spontaneously decay.\n\n**Types of radioactive decay:**\n⬇️ **Alpha (α) decay** — nucleus ejects He-4 (2p + 2n): Z decreases by 2, mass by 4\n⬇️ **Beta (β) decay** — neutron → proton + electron (+ antineutrino): Z increases by 1\n⬆️ **Gamma (γ) radiation** — high-energy photon emitted (no mass change)\n\n**Half-life** — time for half the atoms to decay:\n⏱️ Uranium-238: 4.47 billion years (Earth's age!)\n⏱️ Carbon-14: 5,730 years (radiocarbon dating!)\n⏱️ Iodine-131: 8 days (thyroid cancer treatment)\n⏱️ Polonium-210: 138 days (used to assassinate Alexander Litvinenko!)\n⏱️ Francium-223: 22 minutes\n\n**Nuclear fission:**\nU-235 splits when hit by a neutron → releases 200 MeV + 2-3 more neutrons → chain reaction! Nuclear power exploits this (controlled) for electricity. Nuclear bombs exploit it uncontrolled.\n\n**Medical uses of radioactivity:**\n🏥 PET scans use F-18 (110 min half-life) to image metabolic activity\n🏥 Tc-99m (6 hour half-life) is the most used medical radioisotope — bone scans!\n🏥 I-131 targets thyroid tissue to destroy thyroid cancer without surgery\n🏥 Radium-223 treats bone metastases from prostate cancer ☢️", highlight: "Uranium-238's half-life equals Earth's age — by measuring uranium-to-lead ratios in rocks, geologists date the Earth at 4.54 billion years! ☢️" },
  ],

  lab: {
    title: "Element Builder Lab 🧪",
    description: "Build any element by adjusting proton count — watch electron shells fill and predict chemical properties! Discover which elements explode with water and which glow!",
    hint: "Try building alkali metals (1 valence electron) vs noble gases (8 valence electrons). Push to the unstable heavy elements and watch radioactive decay!",
    scientistModeHint: "Scientist Mode: see electron configuration notation, ionisation energy values, electronegativity numbers, and orbital diagrams as you build elements.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why gold is gold-coloured while most metals are grey/silver? ✨", answer: "Gold's colour comes from relativistic quantum mechanics! Gold is heavy enough that its inner electrons travel at ~58% of the speed of light. Einstein's special relativity causes these electrons to acquire extra mass, shrinking their orbitals and affecting the energy gap between electron shells. This slightly shifts which wavelengths of light the 5d-6s orbital transition absorbs — into the blue range. Since gold absorbs blue light, it reflects yellow/red — giving it that characteristic golden colour. Silver and platinum don't have this relativistic effect! 🌟", emoji: '✨' },
    { id: 'dyk2', question: "Do you know why helium makes your voice squeaky? 🎈", answer: "Your voice pitch depends on the speed of sound in the gas in your vocal tract. Sound travels at 1007 m/s in helium vs 343 m/s in air — about 3x faster! This means resonant frequencies of your vocal tract are 3x higher in helium, producing that characteristic squeak. Importantly, this doesn't change the frequency your vocal cords vibrate at directly — it changes which harmonics resonate in your throat. WARNING: inhaling helium from a tank (not balloons) can cause deadly embolism — never do it! 🎵", emoji: '🎈' },
    { id: 'dyk3', question: "Do you know why neon signs can produce so many colours if neon itself only glows red? 💡", answer: "Pure neon gas in a vacuum tube glows red-orange when electrically excited. But 'neon signs' actually use many different gases and coatings! Argon gas + mercury vapour glows blue. Yellow comes from neon inside yellow-coated glass. Green comes from argon + mercury inside green-coated glass. Red, orange, and pink come from pure neon. White uses argon/mercury with a white powder coating. A single neon sign may contain 5 different gases! The 'neon' name stuck even though most modern signs use other noble gases. 🌈", emoji: '💡' },
    { id: 'dyk4', question: "Do you know why mercury is liquid at room temperature when most metals are solid? 🌡️", answer: "Mercury (Hg) is the only metal liquid at room temperature. Like gold, it has strong relativistic effects — its inner electrons travel at ~58% of light speed, contracting s-orbital electrons, reducing their ability to form metallic bonding, weakening the metallic lattice. This dramatically lowers mercury's melting point to −39°C. The relativistic effect also explains why mercury is a poor electrical conductor for a metal (contracted s-orbitals don't participate well in electron sea conduction). One of the most striking examples of Einstein's relativity showing up in everyday physical properties! 🌟", emoji: '🌡️' },
    { id: 'dyk5', question: "Do you know why the element selenium (Se) is essential to health but toxic in overdose — just like medicine? 💊", answer: "Selenium is essential at 55 μg/day (its location in proteins like glutathione peroxidase protects against cell damage). But above 400 μg/day, it causes selenosis: hair loss, nail loss, nerve damage, and a garlic breath odour (from the exhaled selenium compound dimethylselenide). Brazil nuts average 70-90μg of selenium each — just 4-5 nuts per day could push you into the toxic range! This dose-dependent toxicity applies to almost all elements — the 16th-century physician Paracelsus said 'The dose makes the poison'. Water itself is lethal in extreme amounts! 💧", emoji: '💊' },
  ],

  quiz: [
    { id: 'q1', question: "What does the atomic number of an element tell you? 🔬", options: ["Number of neutrons in nucleus", "Total mass of the atom", "Number of protons in nucleus", "Number of outer shell electrons"], answer: 2, explanation: "Atomic number = proton count. Change the proton count and you CHANGE the element entirely. Mendeleev originally used atomic mass (and got some orders wrong). Moseley (1913) showed proton number is the true organising principle! 🔬" },
    { id: 'q2', question: "Why are noble gases chemically inert? ✅", options: ["They are too light to react", "They have full outer shells", "They exist only as single atoms", "They lack any reactive energy"], answer: 1, explanation: "Noble gases have complete outer electron shells (8 valence electrons, except He with 2). Under the Octet Rule, having a full shell means no drive to gain, lose, or share electrons — chemical inertness! Until 1962, scientists believed this was absolute. 🏆" },
    { id: 'q3', question: "Moving left to right across a period, what happens to atomic radius? 📏", options: ["It increases across the period", "It stays constant throughout", "It decreases across the period", "It alternates between sizes"], answer: 2, explanation: "Across a period: atomic number (protons) increases, but electrons are added to the SAME shell. More nuclear charge pulls ALL electrons closer — radius shrinks! Sodium (Na) atom is larger than chlorine (Cl) even though Cl has more electrons. 📈" },
    { id: 'q4', question: "Why does potassium (K) react more violently with water than sodium (Na)? 💥", options: ["Potassium has more protons", "Potassium loses electrons more easily", "Potassium has higher melting points", "Potassium molecules are larger"], answer: 1, explanation: "Down Group 1, each element has more electron shells — the valence electron is progressively further from the nucleus and screened by inner shells → lower ionisation energy → easier to lose → MORE reactive! K is more reactive than Na for exactly this reason. 💥" },
    { id: 'q5', question: "What makes carbon uniquely suited to be the basis of life? 🌱", options: ["Carbon is the most abundant", "Carbon forms four stable bonds", "Carbon has ideal atomic mass", "Carbon reacts with biological elements"], answer: 1, explanation: "Carbon forms 4 stable covalent bonds in any geometry — enabling chains, rings, branches, and complex 3D structures. This creates 10+ million organic compounds vs ~500,000 for all other elements combined! Silicon (same group, 4 bonds) makes weaker Si-Si bonds and too-strong Si-O bonds → silicates, not life. 🌱" },
    { id: 'q6', question: "What is the half-life of a radioactive substance? ⏱️", options: ["Time for complete substance decay", "Time for half atoms decay", "Energy released per second", "Temperature for fastest decay"], answer: 1, explanation: "Half-life: time for 50% of atoms to decay. After 2 half-lives: 25% remain. After 10: 0.1%. Carbon-14 (half-life 5,730 years) is used for radiocarbon dating organic materials up to ~50,000 years old! ⏱️" },
    { id: 'q7', question: "Why do transition metals form coloured compounds? 🎨", options: ["They absorb dyes from soil", "They have partially filled d-orbitals", "They have high atomic mass", "They only form ionic compounds"], answer: 1, explanation: "Transition metal ions have partially filled d-orbitals. When visible light hits them, specific wavelengths are absorbed to excite electrons between d-orbital energy levels. The reflected wavelengths give the colour: Cu²⁺ absorbs red, reflects blue-green → blue! 🎨" },
    { id: 'q8', question: "What is Mendeleev's greatest achievement in creating the periodic table? 🏆", options: ["He listed all known elements", "He predicted unknown element properties", "He discovered the proton", "He synthesised new heavy elements"], answer: 1, explanation: "Mendeleev left deliberate blank spaces in his 1869 table and predicted the properties of missing elements. When Gallium (1875), Scandium (1879), and Germanium (1886) were found — matching his predictions almost exactly — it proved the periodic system was real science, not coincidence! 🏆" },
    { id: 'q9', question: "What determines whether an element is a metal, nonmetal, or metalloid? 🔮", options: ["Their position and electron configuration", "Their colour and surface shine", "Their initial discovery temperature", "Their total number of neutrons"], answer: 0, explanation: "Position in the table = electron configuration = chemical and physical properties. Metals (left) have low IE, lose electrons easily. Nonmetals (right) have high EN, gain electrons. Metalloids (zigzag boundary like Si, Ge, As) have intermediate electron configurations — semiconductor behaviour! 🔮" },
    { id: 'q10', question: "Why is fluorine the most electronegative element? ⚡", options: ["It has smallest atomic number", "It has high nuclear charge", "It has many outer electrons", "It follows standard chemical convention"], answer: 1, explanation: "Fluorine (Period 2, Group 17): smallest radius of all halogens, highest effective nuclear charge pulling on bonding electrons. Its 7 valence electrons desperately need one more for the octet — it grabs electrons from almost ANYTHING, including some noble gas compounds! 🏆" },
    { id: 'q11', question: "What are 'Isotopes'? 🔬", options: ["Atoms with different proton counts", "Atoms with different neutron counts", "Atoms that have lost electrons", "Elements with same atomic mass"], answer: 1, explanation: "Isotopes are variants of a chemical element which differ in neutron number, although all isotopes of a given element have the same number of protons. ⚛️" },
    { id: 'q12', question: "What are 'Valence Electrons'? ⚡", options: ["Electrons found in the nucleus", "Electrons in the outermost shell", "Total number of atom electrons", "Electrons carrying an electric current"], answer: 1, explanation: "Valence electrons are the electrons in the outermost shell of an atom and determine how the atom will react chemically. 🧪" },
    { id: 'q13', question: "Which group contains the 'Alkali Metals'? 💥", options: ["Group 1", "Group 2", "Group 17", "Group 18"], answer: 0, explanation: "Group 1 elements (except Hydrogen) are Alkali Metals. They are very reactive and stored in oil to prevent reaction with air/water! 🛢️" },
    { id: 'q14', question: "What are 'Halogens' known for? 🧂", options: ["Being inert and unreactive", "Highly reactive Group 17 non-metals", "Being excellent heat conductors", "Having one electron shell"], answer: 1, explanation: "Halogens (Group 17) are very reactive non-metals that often form salts (like NaCl) when reacting with metals. 🧂" },
    { id: 'q15', question: "What is the 'Octet Rule' in chemistry? 🎱", options: ["Atoms must have eight protons", "Atoms preferring eight valence electrons", "Elements grouped in eight periods", "Reactions taking exactly eight seconds"], answer: 1, explanation: "The Octet Rule states that atoms are most stable when they have a full outer shell of 8 electrons, which drives most chemical reactions. 🛡️" },
    { id: 'q16', question: "What is 'Ionization Energy'? ⚡", options: ["The total energy of ions", "Energy needed to remove electrons", "The speed of moving electrons", "The total weight of atoms"], answer: 1, explanation: "Ionization energy is the energy needed to pull an electron away from an atom. It increases across a period and decreases down a group! 📈" },
    { id: 'q17', question: "What are 'Metalloids'? 🔮", options: ["Extremely heavy metal elements", "Elements between metals and non-metals", "Artificial elements from a lab", "Gases acting like metals"], answer: 1, explanation: "Metalloids (like Silicon) have properties of both metals and non-metals and are essential for making computer chips (semiconductors)! 💻" },
    { id: 'q18', question: "Which element is the primary 'backbone' of all organic molecules? 🌱", options: ["Oxygen", "Carbon", "Nitrogen", "Iron"], answer: 1, explanation: "Carbon is the basis of all life on Earth because it can form stable, complex chains and structures with 4 bonds. 🧬" },
    { id: 'q19', question: "What is a 'Cation'? ➕", options: ["A neutrally charged atom", "A positively charged ion", "A negatively charged ion", "A radioactive particle"], answer: 1, explanation: "A Cation is a positive ion. Think of the 't' in Cation as a plus sign (+)! It forms when an atom loses negative electrons. ➕" },
    { id: 'q20', question: "What is an 'Anion'? ➖", options: ["A positively charged ion", "A negatively charged ion", "An atom with no electrons", "A stable noble gas"], answer: 1, explanation: "An Anion is a negative ion. It forms when an atom gains one or more negative electrons. ➖" },
  ],

  relatedTopics: ['atoms_molecules', 'chemical_bonding', 'matter_states', 'energy_types'],
};
