// ─────────────────────────────────────────────────────────
//  TOPIC: TAXATION
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'taxation',
  title: 'Taxation & Economy',
  subtitle: 'The subscription fee for civilization 🏛️',
  emoji: '📜',
  category: 'Finance',
  accentKey: 'civics',

  hook: {
    question: "If you get a raise that pushes you into a 'higher tax bracket', do you actually take home LESS money? 📉",
    reveal: "No! This is the biggest money myth in the world. Tax brackets are like buckets. Only the *extra* money that spills into the new bucket is taxed at the higher rate. You will NEVER lose money by earning more! Let's decode the matrix of taxes. 🏛️💸",
    emoji: '💸',
  },

  theory: [
    {
      id: 'why_taxes_exist',
      title: 'The Civilization Subscription 🏛️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'star',
      content: "Taxes are like a subscription fee (like Netflix) to live in a country. \n\nWithout taxes, there would be no roads, no public schools, no police, and no space rockets. The government doesn't 'make' money; it collects a small piece from everyone to build the things that we all use. It's the price we pay to live in a civilized world.",
      highlight: "Taxes build the world we share. 🌍",
    },
    {
      id: 'direct_vs_indirect',
      title: 'Visible vs Invisible Taxes 🎯',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🎯',
      svgIcon: 'eye',
      content: "**Direct Tax:** You pay this directly based on your wealth (like Income Tax). If you don't earn, you don't pay.\n\n**Indirect Tax:** These are hidden in the price of things (like GST). When you buy a chocolate bar or a toy, a few rupees go to the government automatically. Even a kid pays indirect taxes every time they spend their pocket money! 🛒",
      highlight: "Earnings are taxed directly; Spending is taxed indirectly. 🛍️",
    },
    {
      id: 'marginal_tax_brackets',
      title: 'The Tax Buckets 🪜',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🪜',
      svgIcon: 'chart',
      content: "Tax brackets are like a series of buckets. \n\nBucket 1 (the bottom) is tax-free! Once Bucket 1 is full, the extra money spills into Bucket 2, which is taxed at 5%. Only the money in Bucket 2 is taxed at 5%. Your bottom money is still free! This is why earning more is always better—you only pay the high rate on the 'Spillover.' 🪣",
      highlight: "You only pay the higher rate on the money that spills over. 🪣",
    },
    {
      id: 'effective_tax_rate',
      title: 'The Real Truth (Effective Rate) 📊',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📊',
      svgIcon: 'target',
      content: "**Marginal Rate:** The tax on your *last* rupee (e.g., 30%). \n**Effective Rate:** The *actual* percentage of your total money that went to the government (e.g., 15%). \n\nBecause of the free buckets and lower buckets, the 'Effective' rate is what matters for your wallet. Don't let the big 30% number scare you—it's not the whole story!",
      highlight: "Effective rate is the real cost of living in society. 👛",
    },
    {
      id: 'tax_deductions',
      title: "The Government's Bribe 🎩",
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🎩',
      svgIcon: 'shield',
      content: "The government *wants* you to do smart things like save for retirement or buy health insurance. \n\nTo encourage you, they offer **Deductions.** It's like a legal bribe! If you invest ₹1 Lakh in a retirement fund, the government pretends you didn't earn that money at all. They ignore it, so you pay zero tax on it. It's a reward for being responsible! 🧠",
      highlight: "Deductions are the government's reward for smart choices. 🧠",
    },
    {
      id: 'tax_evasion_vs_avoidance',
      title: 'The IQ Test (Planning vs Evasion) ⚖️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'alert',
      content: "**Tax Evasion:** Lying about your money or hiding it in a suitcase. This is a crime and leads to prison! 🚨\n\n**Tax Planning:** Using the legal rules (like deductions) to pay as little as possible. This is smart and 100% legal. The government actually writes these rules to help the economy move! It's like a financial IQ test. 🧠",
      highlight: "Evasion is a crime; Planning is a superpower. ⚖️",
    },
    {
      id: 'capital_gains',
      title: 'Investing Taxes 📈',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📈',
      svgIcon: 'refresh',
      content: "When you sell a stock or a house for a profit, you pay **Capital Gains Tax.** \n\n**Short-Term:** If you sell fast (less than 1 year), you pay more tax. The government thinks you're 'gambling.' \n**Long-Term:** If you hold for more than 1 year, the tax is much lower. The government rewards you for being patient and helping the economy grow over time. ⏳",
      highlight: "Patience is rewarded with lower taxes. ⏳",
    },
    {
      id: 'gst_vat',
      title: 'The Hidden 18% (GST) 🛍️',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🛍️',
      svgIcon: 'book',
      content: "GST (Goods and Services Tax) is a tax on *everything* you buy. \n\nWhen a shop sells you a shirt, they take your money and send a slice to the government. The business doesn't actually 'pay' the tax; they just collect it from YOU! Ultimately, the final consumer (the person using the product) is the one who pays for all the roads and bridges. 🛒",
      highlight: "You pay taxes every time you buy a chocolate bar. 🍫",
    },
    {
      id: 'tds_form16',
      title: 'The Automatic Cut (TDS) ✂️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '✂️',
      svgIcon: 'lock',
      content: "The government doesn't trust people to save their tax money until the end of the year. \n\nSo they invented **TDS (Tax Deducted at Source).** Before your boss even gives you your salary, they legally chop off the tax and send it straight to the government. You never even see the money! It's the government making sure they get their subscription fee first. 💸",
      highlight: "TDS ensures the government gets paid first. 💸",
    },
    {
      id: 'old_vs_new_regime',
      title: 'Simple vs Complex 🔄',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🔄',
      svgIcon: 'balance',
      content: "India now has two ways to pay tax: \n\n**Old Regime:** Complex, but you get lots of deductions (rewards) for investing. Good for people who save a lot. \n**New Regime:** Simple math, lower rates, but zero deductions. Good for people who just want a simple life. You have to pick the one that leaves more money in your pocket! 🧮",
      highlight: "Pick the system that lets you keep more of your own money! 🧮",
    },
  ],

  lab: {
    title: "The Tax Optimizer ⚖️",
    description: "Welcome to the Tax Lab! Here you can see the 'Bucket' system in action. Test how a raise affects your wallet, use 'Legal Magic' (Deductions) to lower your bill, and see how much the government takes from your favorite snacks! 📈",
    hint: "Try the 'Bucket Simulator' mode. Watch how your first few lakhs of income stay totally green (Tax-Free)! Only the top money gets hit with the tax brush.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks exact Cess and Surcharge math for ultra-high earners and corporate tax structures.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why Billionaires (like Elon Musk) pay almost 0% Income Tax? 💼",
      answer: "Because they don't have a 'Salary'! Their wealth is in company stock. Since they haven't 'sold' the stock, it's not income. If they need cash, they take a bank loan using the stock as a guarantee. Loans aren't taxed! They literally live off borrowed money to avoid the tax man. 🤯",
      emoji: '🏦',
    },
    {
      id: 'dyk2',
      question: "Do you know why junk food and cigarettes have 'Sin Taxes'? 🚬",
      answer: "Discouragement! The government wants people to be healthy because sick people cost the country money. By making 'bad' things super expensive with extra taxes, they hope you'll stop. Plus, they make a massive amount of money from people who are addicted! 💰",
      emoji: '🍷',
    },
    {
      id: 'dyk3',
      question: "Do you know why tax filing is so hard to do? 📜",
      answer: "Money! In some countries, the government just sends you a bill. But in others, big tax-filing companies spend millions to keep the laws confusing. They WANT it to be hard so you have to pay them to help you! It's a multi-billion dollar business built on confusion. 🧑‍⚖️",
      emoji: '💼',
    },
    {
      id: 'dyk4',
      question: "Do you know why businesses get better tax rules than you? 🚚",
      answer: "Reinvestment! If a business spends its profit on new trucks or hiring workers, the government lets them deduct that. Why? Because new trucks and new workers help the whole country grow. The government uses the tax code to 'steer' where big companies spend their money. 🏭",
      emoji: '⚙️',
    },
    {
      id: 'dyk5',
      question: "Do you know why GST hits the poor harder than the rich? 🛒",
      answer: "Flat Math! If a billionaire and a poor person both buy a ₹10 biscuit, they both pay ₹1 in tax. For the billionaire, ₹1 is nothing. For the poor person, that ₹1 could have bought more food. This is called a 'Regressive Tax'—it hurts the people with less money more. 📉",
      emoji: '⚖️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What are taxes primarily used for?", options: ["To make the President rich", "To pay for public roads, schools, and safety", "To buy gold for the vault", "To print new newspapers"], answer: 1, explanation: "Taxes are the shared cost of our civilization! 🏛️" },
    { id: 'q2', question: "What is an 'Indirect Tax'?", options: ["A tax you pay once a year", "A hidden tax in the price of things you buy (like GST)", "A tax on your age", "A type of bank fee"], answer: 1, explanation: "You pay it every time you go to the store! 🎯" },
    { id: 'q3', question: "If you move to a higher tax bracket, you:", options: ["Lose money overall", "Only pay the higher rate on the 'extra' money that spilled over", "The government takes your whole salary", "Nothing happens"], answer: 1, explanation: "You ALWAYS take home more money after a raise! 🪜" },
    { id: 'q4', question: "What is your 'Effective' Tax Rate?", options: ["The highest bracket you hit", "The actual percentage of total money that went to taxes", "A penalty for being late", "The rate for businesses"], answer: 1, explanation: "It's the real truth about your wallet! 📊" },
    { id: 'q5', question: "A 'Tax Deduction' is like:", options: ["A fine", "A legal 'bribe' to reward you for smart choices", "A type of credit card", "Hiding money under a bed"], answer: 1, explanation: "The government 'ignores' that income as a reward! 🎩" },
    { id: 'q6', question: "Tax Evasion is:", options: ["Smart planning", "A crime that leads to prison", "Required by law", "Only for kids"], answer: 1, explanation: "Lying about money is illegal! ⚖️" },
    { id: 'q7', question: "Capital Gains Tax applies when you:", options: ["Earn a salary", "Sell an asset (like a stock) for a profit", "Buy groceries", "Open a bank account"], answer: 1, explanation: "It's a tax on the money your assets made! 📈" },
    { id: 'q8', question: "Why is Long-Term tax lower than Short-Term?", options: ["Because the government is lazy", "To reward patient investors who help the economy", "Because 1 year is a magic number", "There is no reason"], answer: 1, explanation: "Patience is a virtue the government rewards! ⏳" },
    { id: 'q9', question: "What does GST stand for?", options: ["Government Savings Trust", "Goods and Services Tax", "Global Sales Tariff", "General Super Tax"], answer: 1, explanation: "It's the tax on almost everything we consume! 🛍️" },
    { id: 'q10', question: "Who really pays the GST in the end?", options: ["The factory", "The shop owner", "The final consumer (YOU!)", "The bank"], answer: 2, explanation: "Businesses just collect it and pass it up! 🛒" },
    { id: 'q11', question: "What is TDS?", options: ["Total Debt System", "Tax Deducted at Source (chopped from salary automatically)", "Trust in Digital Sales", "Targeted Debt Savings"], answer: 1, explanation: "The government takes their cut before you even see it! ✂️" },
    { id: 'q12', question: "The New Tax Regime is designed to be:", options: ["More expensive", "Simpler, with lower rates but zero deductions", "Harder for humans", "Only for seniors"], answer: 1, explanation: "It's the 'Easy Mode' of the tax world! 🔄" },
    { id: 'q13', question: "Billionaires avoid income tax by:", options: ["Bribing everyone", "Holding stock and taking loans against it instead of a salary", "Hiding in another country", "Doing magic"], answer: 1, explanation: "If you don't 'sell', you aren't 'taxed'! 💼" },
    { id: 'q14', question: "A 'Sin Tax' is meant to:", options: ["Make you a better person", "Discourage unhealthy things like smoking", "Pay for churches", "Make junk food free"], answer: 1, explanation: "It's a tax on 'bad' habits! 🚬" },
    { id: 'q15', question: "Why is GST called 'Regressive'?", options: ["It's very old", "It hurts poor people more because the flat tax is a bigger piece of their wealth", "It makes people move backward", "Only rich people pay it"], answer: 1, explanation: "A ₹5 tax is nothing to a rich person, but a lot to a poor one! 📉" },
    { id: 'q16', question: "Why is tax filing hard to do in the US?", options: ["Computers are broken", "Tax-filing companies want to keep it confusing to make money", "The government likes puzzles", "People are bad at math"], answer: 1, explanation: "Confusion is a business! 🧑‍⚖️" },
    { id: 'q17', question: "If the government wants more electric cars, they will:", options: ["Ban all other cars", "Offer tax deductions for buying electric ones", "Make electric cars free", "Increase taxes on everyone"], answer: 1, explanation: "Deductions are the steering wheel of the economy! ⚙️" },
    { id: 'q18', question: "Form 16 is your proof that:", options: ["You are a citizen", "Your boss already paid your tax via TDS", "You have no debt", "You passed a math test"], answer: 1, explanation: "It's your receipt for pre-paid taxes! 📜" },
    { id: 'q19', question: "Which of these has NO GST?", options: ["A new phone", "A restaurant pizza", "Your monthly salary", "A movie ticket"], answer: 2, explanation: "Salaries get Income Tax, not GST! 💵" },
    { id: 'q20', question: "Tax Planning is basically:", options: ["Illegal hacking", "Using the rules legally to pay less and save more", "Hiding money in a vault", "Buying lottery tickets"], answer: 1, explanation: "It's using the rules exactly as they were written! 🎩" }
  ],

  relatedTopics: ['personal_finance', 'banking', 'corporate_finance'],
};
