export default {
  id: 'cryptography',
  title: 'Cryptography',
  subtitle: 'The dark art of digital secrets 🔐',
  emoji: '🔑',
  category: 'Technology',
  accentKey: 'cyber',

  hook: {
    question: "When you type your credit card into Amazon, the data literally flies through the open air across public Wi-Fi networks. Why doesn't a hacker sitting next to you just read it? 💳",
    reveal: "Because of Encryption! The millisecond you hit submit, your phone uses extreme advanced mathematics to physically scramble your card number into a completely random string of pure gibberish (like 'X9$qLp!'). Even if the hacker steals it from the air, they mathematically cannot unscramble it without Amazon's private key! 👾",
    emoji: '🛡️',
  },

  theory: [
    { id: '1', title: 'The Caesar Cipher', color: '#00D4FF', bgGradient: ['#002A35', '#050A0F'], icon: '📜', svgIcon: 'cube', content: "In 50 B.C., Julius Caesar sent secret military messages by taking the alphabet and physically shifting every letter by 3 spaces. \n\n'A' became 'D', 'B' became 'E'. The word 'CAT' mathematically becomes 'FDW'! Enemies intercepting the message just saw gibberish. This is the absolute foundation of all encryption.", highlight: "Caesar is easily defeated today. A computer can attempt all 26 possible alphabet shifts in 0.0001 seconds! ⏱️" },
    { id: '2', title: 'Symmetric Encryption', color: '#39FF14', bgGradient: ['#0A200A', '#050A0F'], icon: '🗝️', svgIcon: 'link', content: "**Symmetric Encryption** uses the EXACT same physical key to lock and unlock the digital box. \n\nImagine putting a secret letter into a safe, locking it with an iron key, and sending the safe to your friend. The massive problem? You now have to mail your friend the iron key so they can open it! If a spy intercepts the mail truck carrying the key, your encryption is 100% useless.", highlight: "Symmetric Encryption is blazing fast but incredibly dangerous for internet use because sharing the key is vulnerable! 🚨" },
    { id: '3', title: 'Asymmetric Encryption (Public Key)', color: '#FFD166', bgGradient: ['#2A2A00', '#050A0F'], icon: '🔓', svgIcon: 'target', content: "Also known as Public Key Cryptography, this mathematically brilliant system uses TWO keys! \n\nYou generate a **Public Key** (which acts like an open padlock) and a mathematically linked **Private Key** (the only key that can open that specific padlock). You give out the open padlocks to everyone on the internet!", highlight: "Anyone can snap the padlock shut on a box of data, but ONLY YOU possess the Private Key to actually unlock and read it! 🌍" },
    { id: '4', title: 'Hash Functions', color: '#A855F7', bgGradient: ['#1A0A2A', '#050A0F'], icon: '#️⃣', svgIcon: 'grid', content: "A **Hash** is a mathematical one-way meat grinder. \n\nIf you drop the word 'HELLO' into a SHA-256 hash grinder, it spits out a highly specific 64-character string of garbage. Unlike encryption, you can NEVER mathematically un-grind the meat to get 'HELLO' back! It is heavily completely strictly utterly definitively destroyed.", highlight: "If you change even one single letter from 'HELLO' to 'HELLA', the entire 64-character hash completely radically changes! 肉" },
    { id: '5', title: 'Passwords & Salting', color: '#FF4D6D', bgGradient: ['#2A0A1A', '#050A0F'], icon: '🧂', svgIcon: 'sparkle', content: "Websites DO NOT save your actual password. \n\nWhen you create an account, they throw your password through a Hash Grinder and save the output garbage. When you log in next week, they hash what you type and see if the two garbage outputs perfectly match! To be extra secure, they add **Salt** (random hidden text) to your password before grinding it.", highlight: "If a hacker steals Amazon's database, they only get a list of useless ground-up hashes, not your real password! 🛡️" },
    { id: '6', title: 'Brute Force Attacks', color: '#FF3131', bgGradient: ['#200A0A', '#050A0F'], icon: '💥', svgIcon: 'pulse', content: "A **Brute Force Attack** is the simplest, dumbest hacking method ever invented. \n\nThe hacker essentially just uses a massive supercomputer to guess every possible password combination until one magically works. 'A', 'B', 'C', 'AA', 'AB', etc. \nBecause modern computers can guess 10 Billion passwords a second, short passwords fall instantly.", highlight: "A 6-character password cracks in 2 seconds. A 12-character mixed password takes over 34,000 years! Length is strength! ⏳" },
    { id: '7', title: 'HTTPS & SSL/TLS', color: '#00D4A0', bgGradient: ['#00201A', '#050A0F'], icon: '🔒', svgIcon: 'lock', content: "When you see the padlock icon in your web browser (HTTPS), it means your phone and the website have aggressively established a secure encrypted tunnel. \n\nEven if you are using an open, dangerous Starbucks Wi-Fi network, any hacker 'sniffing' your data will purely only see scrambled mathematical garbage passing through the air.", highlight: "Without HTTPS, your credit card number would fly through the air completely visible in plain English text! 💳" },
    { id: '8', title: 'End-to-End Encryption (E2EE)', color: '#6C5CE7', bgGradient: ['#100A20', '#050A0F'], icon: '📱', svgIcon: 'waves', content: "Apps like WhatsApp and Signal use **End-to-End Encryption**. \n\nThis strictly means the message is scrambled on your actual physical phone, flies across the internet, hits the company servers, and only unscrambles when it reaches your friend's physical phone.", highlight: "Even if the CEO of WhatsApp was held at gunpoint, they mathematically cannot read your messages because the server only holds locked boxes! 🤐" },
    { id: '9', title: 'Quantum Cryptography', color: '#FFB347', bgGradient: ['#201000', '#050A0F'], icon: '⚛️', svgIcon: 'planet', content: "Standard encryption relies on math problems being 'too hard' for normal massive computers to solve. \n\nHowever, a true **Quantum Computer** could theoretically bypass traditional math and shred modern encryption like tissue paper. To fight this, engineers are building Quantum Encryption that uses the actual physical state of subatomic photons to lock data!", highlight: "In Quantum encryption, if a hacker even looks at the data, the laws of physics heavily guarantee the data instantly collapses and destroys itself! 💥" },
    { id: '10', title: 'The Enigma Code', color: '#55EFC4', bgGradient: ['#0A2010', '#050A0F'], icon: '📠', svgIcon: 'cpu', content: "During WWII, Nazi Germany used a mechanical encryption device called the **Enigma Machine**. \n\nIt featured a series of physical rotors that furiously scrambled messages in 158 Quintillion different combinations. It was believed to be mathematically completely unbreakable by human minds.", highlight: "Alan Turing famously built the very first digital computer purely to aggressively brute-force and successfully crack the Enigma code! 🏆" }
  ],

  lab: {
    title: "Cyber-Decryption Terminal 👾",
    description: "Welcome to the Cryptography Engine. Construct an XOR Cipher and launch a Brute Force Attack.",
    hint: "Change the Cipher Shift wheel and watch the Hexadecimal array alter.",
    scientistModeHint: "Scientist Mode reveals exact ASCII byte conversion tables.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do websites aggressively force you to include an uppercase letter, a number, and a symbol (!@#) in your password? 😡", answer: "A hacker's 'Brute Force' program can guess a lowercase 6-letter password in 2 seconds. By adding symbols and numbers, you exponentially multiply the math. A 12-character mixed password takes a supercomputer 34,000 years to crack! 🕒", emoji: '💥' },
    { id: 'dyk2', question: "Why is '123456' mathematically terrifying? 😱", answer: "Brute force programs don't just guess randomly. They use 'Dictionary Attacks', trying a massive list of the 10 million most common passwords first. If your password is 'password123', the hacker solves it in 0.00001 seconds on the very first try!", emoji: '📖' },
    { id: 'dyk3', question: "Why don't we just use End-to-End Encryption for everything on the internet? 📱", answer: "E2EE is incredibly processor intensive. If Netflix tried to End-to-End encrypt a massive 4K movie stream using complex Asymmetric keys, your phone's processor would physically overheat and the battery would die in 5 minutes! We reserve the heavy math for small text messages.", emoji: '🔋' },
    { id: 'dyk4', question: "How does the FBI sometimes legally hack encrypted iPhones? 🕵️‍♂️", answer: "They aggressively don't crack the encryption directly! Breaking modern AES encryption is mathematically impossible. Instead, they exploit physical bugs in the phone's software to bypass the lock screen entirely, or guess your simple 4-digit PIN using robotic fingers!", emoji: '🤖' },
    { id: 'dyk5', question: "Why does your physical ATM card have a metallic microchip on the front now? 💳", answer: "Old magnetic stripes just had your raw credit card number coded in plain text! Anyone could skim it. The gold microchip acts as a tiny physical computer that aggressively generates a highly unique, one-time cryptographic code for every single purchase. Skimming a chip is mathematically useless!", emoji: '🔒' }
  ],

  quiz: [
    { id: 'q1', question: "What did the ancient Caesar Cipher explicitly do to hide messages?", options: ['Melted the paper', 'Shifted every letter in the alphabet by a certain number', 'Wrote in invisible ink', 'Translated to Latin'], answer: 1, explanation: "It simply shifted letters down the alphabet." },
    { id: 'q2', question: "Why can't you reverse a cryptographic Hash back into the original password?", options: ['It uses quantum physics', "It's mathematically a one-way 'meat grinder' function", 'It requires a physical key', 'It deletes the source file'], answer: 1, explanation: "Hashing permanently destroys the structure of the input, leaving only a mathematical fingerprint." },
    { id: 'q3', question: "What is the primary danger heavily associated with Symmetric Encryption?", options: ['It is too slow', 'It breaks your computer', 'You have to securely share the one physical key with the other person', 'It uses too much internet data'], answer: 2, explanation: "If someone steals the key while you are transferring it, they crack your whole system." },
    { id: 'q4', question: "What acts as an 'open padlock' that anybody can use to lock a box of data before sending it to you?", options: ['Symmetric Key', 'Public Key', 'Hash Function', 'Caesar Shift'], answer: 1, explanation: "Your Public Key can aggressively lock data, but only your Private Key can open it." },
    { id: 'q5', question: "To prevent hackers from easily reverse-engineering stolen hashed passwords, websites mathematically inject what into the password before hashing?", options: ['Pepper', 'Sugar', 'Salt (Random Data)', 'Water'], answer: 2, explanation: "Salt adds random garbage text to make your hash completely unique." },
    { id: 'q6', question: "What aggressively simple attack involves a computer trying every highly possible password combination ('A', 'B', 'C', 'AA') until it works?", options: ['Phishing', 'Social Engineering', 'Brute Force', 'DDoS'], answer: 2, explanation: "A brute force attack strictly relies purely on computational guessing power." },
    { id: 'q7', question: "What does the 'S' in HTTPS signify?", options: ['Super', 'Secure', 'Simple', 'System'], answer: 1, explanation: "Secure! It means the website has established an encrypted TLS tunnel." },
    { id: 'q8', question: "Why is End-to-End Encryption (E2EE) considered the absolute gold standard for messaging apps?", options: ['It makes messages faster', 'It prevents data loss', 'No one, not even the app company themselves, can mathematically read the messages', 'It uses emojis'], answer: 2, explanation: "The message strictly only decrypts when it reaches the physical phone of the receiver." },
    { id: 'q9', question: "What technology threatens to completely shred modern mathematical encryption in the next few decades?", options: ['AI', 'Quantum Computers', '5G Towers', 'Fiber Optics'], answer: 1, explanation: "Quantum computers don't calculate in 1s and 0s, allowing them to bypass traditional math locks." },
    { id: 'q10', question: "Who famously cracked the German Enigma code during WWII by building one of the first computers?", options: ['Albert Einstein', 'Alan Turing', 'Nikola Tesla', 'Bill Gates'], answer: 1, explanation: "Turing built the 'Bombe' machine to brute-force the Enigma combinations." },
    { id: 'q11', question: "What is a 'Dictionary Attack'?", options: ['Throwing books at a server', 'A brute-force script that only guesses the most common real-world words and passwords', 'Translating code', 'Hacking the Oxford servers'], answer: 1, explanation: "Hackers save time by guessing 'password123' before guessing 'X9$qLp!'." },
    { id: 'q12', question: "What is the primary reason to use a Password Manager?", options: ['To type faster', 'To save battery', 'It allows you to securely have a complex, 20-character unique password for every single website', 'To block ads'], answer: 2, explanation: "A manager remembers the massive impossible passwords so you don't have to!" },
    { id: 'q13', question: "If you shift the word 'A' by 1 in a Caesar Cipher, what is the encrypted ciphertext?", options: ['Z', '1', 'B', 'AA'], answer: 2, explanation: "'A' physically shifts one letter down the alphabet to become 'B'." },
    { id: 'q14', question: "What happens if you change exactly one letter of the input before putting it through a Hash Function?", options: ['The output changes by one letter', 'The entire 64-character output drastically and completely changes', 'Nothing happens', 'The computer crashes'], answer: 1, explanation: "Hashes are extremely sensitive. Any tiny change totally violently alters the output." },
    { id: 'q15', question: "What is physically stored on the metallic microchip on modern credit cards?", options: ['Your name', 'Your raw credit card number in text', 'A tiny computer that generates a unique one-time cryptographic code for every purchase', 'A GPS tracker'], answer: 2, explanation: "The chip generates math, unlike the magnetic stripe which just stored dumb text." },
    { id: 'q16', question: "Why is a 12-character password exponentially stronger than an 8-character password?", options: ['It uses more RAM', 'The math of combinations scales exponentially, adding thousands of years to a brute-force attack', 'It looks cooler', 'The CPU gets tired'], answer: 1, explanation: "Every character added multiplies the total number of combinations severely!" },
    { id: 'q17', question: "If a hacker intercepts an Asymmetrically encrypted message flying over public Wi-Fi, what do they see?", options: ['The plain message', 'A hash of the message', 'Scrambled mathematical gibberish', 'Blank space'], answer: 2, explanation: "Without the private key, the intercepted data is purely useless locked gibberish." },
    { id: 'q18', question: "What type of cipher was the Enigma Machine fundamentally based on?", options: ['A mechanical rotor-based polyalphabetic substitution cipher', 'A simple Hash', 'Asymmetric keys', 'A digital block cipher'], answer: 0, explanation: "It used physical internal wheels to change the Caesar shift on every single keystroke!" },
    { id: 'q19', question: "What makes Quantum Encryption fundamentally unhackable by observers?", options: ['The math is too long', 'The laws of physics explicitly state that measuring a quantum state instantly collapses and destroys the data', 'It uses magic', 'It is not connected to Wi-Fi'], answer: 1, explanation: "Physics prevents hackers from physically looking at the photons without triggering alarms." },
    { id: 'q20', question: "When your browser clearly displays 'HTTPS' with a padlock, what specific protocol is securing your data?", options: ['FTP', 'SSL/TLS', 'TCP', 'IP'], answer: 1, explanation: "Transport Layer Security (TLS) forms the encrypted tunnel between your physical device and the server." }
  ],
  relatedTopics: ['digital_circuits', 'internet_how_it_works'],
};
