// ─────────────────────────────────────────────────────────
//  TOPIC: DEPRESSION (अवसाद)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'depression',
  title: 'Depression',
  subtitle: 'Understanding the Heavy Fog 🌧️🧠',
  emoji: '🌧️',
  category: 'Mental Health',
  accentKey: 'depression',

  hook: {
    question: "Is depression just 'extreme sadness' that you need to 'snap out of'?",
    reveal: "No. Sadness is an emotion; depression is an illness. When you're sad, the world looks bad, but you still feel like *you*. When you're depressed, the 'you' feels broken or missing altogether.\n\nScientifically, depression physically alters your brain—shrinking the memory center (hippocampus) and misfiring the reward center. Telling a depressed person to 'just be happy' is like telling someone with a broken leg to 'just walk faster'. Let's explore what's really happening under the hood. 🧠📉🧩",
    emoji: '🧩',
  },

  theory: [
    {
      id: 'not_just_sadness',
      title: "Sadness vs. Depression 🌧️",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'cloud-rain',
      svgIcon: 'cloud',
      content: "Sadness is a normal reaction to loss or disappointment. It comes in waves and usually doesn't destroy your self-esteem.\n\n**Depression (Major Depressive Disorder)** is a constant, heavy blanket. It doesn't need a 'reason' to exist. It strips away your ability to feel pleasure (Anhedonia) and your sense of self-worth. If sadness is a cold, depression is pneumonia.",
      highlight: "You can be depressed even when everything in your life is going 'perfectly'. ⚖️",
    },
    {
      id: 'brain_chemistry',
      title: "The Chemical Myth 🧪",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'flask',
      svgIcon: 'eye',
      content: "For decades, we were told depression is just a 'chemical imbalance' (too little serotonin).\n\nModern neuroscience shows it's much more complex. It's about faulty **neural circuitry**, nerve cell growth, and nerve connections. Stress literally kills neurons in the hippocampus. Antidepressants don't just 'add chemicals'; they stimulate new nerve growth (Neurogenesis) over weeks to repair the circuits.",
      highlight: "Depression is less like an empty gas tank and more like a computer with corrupted wiring. 🔌",
    },
    {
      id: 'the_black_dog',
      title: "The 'Black Dog' Analogy 🐕‍🦺",
      color: '#424242',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'lock',
      content: "Winston Churchill famously called his depression his 'Black Dog'.\n\nWhen the black dog is small, it just follows you around. When it gets big, it sits on your chest and makes it hard to breathe. It steals your appetite, your sleep, and your joy. The goal of treatment isn't to kill the dog, but to learn how to tame it and tie it up.",
      highlight: "Externalizing the illness helps: 'I have depression', not 'I am broken'. You are the sky; depression is just the weather. ☁️",
    },
    {
      id: 'anhedonia',
      title: "Anhedonia: The Theft of Joy 🔕",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'volume-x',
      svgIcon: 'snowflake',
      content: "One of the core symptoms of depression is **Anhedonia**—the inability to feel pleasure.\n\nFood tastes like cardboard. Music sounds like noise. Hobbies you loved feel like chores. This happens because the brain's reward system (dopamine pathways) shuts down. You're not being 'lazy' or 'ungrateful'; your brain ceases to register dopamine hits.",
      highlight: "It's the psychological equivalent of losing your sense of taste. 👅🚫",
    },
    {
      id: 'spoon_theory',
      title: "The Spoon Theory 🥄",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'battery-charging',
      svgIcon: 'battery',
      content: "Used for chronic illness, it perfectly explains depressive exhaustion:\nImagine you start the day with 10 'spoons' of energy.\n• Getting out of bed: 2 spoons.\n• Showering: 3 spoons.\n• Calling a friend: Takes 4 spoons.\nSuddenly, you have 1 spoon left by noon. Healthy people have unlimited spoons; depressed people have a strict, tiny budget.",
      highlight: "When someone with depression cancels plans, it's not because they don't love you. They are simply out of spoons. 🥄",
    },
    {
      id: 'cognitive_triad',
      title: "Beck's Cognitive Triad 🔺",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'triangle',
      svgIcon: 'target',
      content: "Psychiatrist Aaron Beck discovered that depression warps your perception into a dark triangle:\n1. **Negative view of self**: 'I am worthless/unlovable.'\n2. **Negative view of the world**: 'Everyone is against me/life is unfair.'\n3. **Negative view of the future**: 'Things will never get better.'\n\nThis isn't reality; it's the depression lying to you.",
      highlight: "Depression is a lens that filters out all the light and only lets the darkness through. 🕶️",
    },
    {
      id: 'rumination',
      title: "Rumination: The Broken Record 🔄",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'refresh-ccw',
      svgIcon: 'activity',
      content: "**Rumination** is obsessively chewing on negative thoughts, past mistakes, or perceived flaws.\n\nIt feels like you are 'problem-solving', but you are actually just spinning your tires in the mud, digging a deeper rut. Rumination exhausts your brain and deepens the depressive state.",
      highlight: "Action is the enemy of rumination. Doing *anything* breaks the mental loop. 🛠️",
    },
    {
      id: 'inflammation_link',
      title: "Is It an Allergic Reaction? 🦠",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "Groundbreaking new research suggests depression might be linked to the immune system. \n\nChronic stress causes systemic **inflammation**. The immune system releases cytokines, which cross the blood-brain barrier and cause 'sickness behavior' (lethargy, social withdrawal). Essentially, your brain thinks it's fighting a virus, so it forces you to retreat and sleep.",
      highlight: "Your body might literally be treating modern stress as a physical infection. 🤒",
    },
    {
      id: 'types_of_depression',
      title: "It's Not One Size Fits All 🎭",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'grid',
      svgIcon: 'users',
      content: "Depression comes in many flavors:\n• **MDD**: Severe, episodic depression.\n• **PDD (Dysthymia)**: A low-grade, constant cloud that lasts for years.\n• **SAD**: Seasonal Affective Disorder (winter depression due to lack of sunlight).\n• **High-Functioning**: Hiding the pain. You go to work, smile, achieve, and then collapse at home.",
      highlight: "The most dangerous type is the one you hide behind a perfect smile. 😊💔",
    },
    {
      id: 'the_vicious_cycle',
      title: "The Downward Spiral 🌪️",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'download',
      svgIcon: 'compass',
      content: "Depression feeds itself through a vicious cycle:\nFeel exhausted/worthless → Isolate from friends/stop hobbies → Feel more lonely and useless → Brain loses stimulation → Feel even more exhausted.\n\nTo break it, you have to do the *opposite* of what the depression tells you to do—which is incredibly hard.",
      highlight: "Depression demands isolation, but connection is the cure. 🤝",
    },
    {
      id: 'treatment_therapy',
      title: "CBT: Rewiring the Brain 🧠",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'tool',
      svgIcon: 'brain',
      content: "**Cognitive Behavioral Therapy (CBT)** is the gold standard for treatment. \nIt teaches you that Thoughts create Feelings, which drive Behaviors. \nBy catching the lies your brain tells you ('nobody likes me') and rationally challenging them ('I have evidence they do'), you can physically rewire the neural pathways in your brain.",
      highlight: "Don't believe everything you think. Your brain can, and will, lie to you. 🤥",
    },
    {
      id: 'treatment_bio',
      title: "Meds & Lifestyle: The Foundation 💊",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'heart',
      svgIcon: 'leaf',
      content: "Therapy is the map, but biology is the vehicle.\n• **Antidepressants (SSRIs)**: Give your brain a scaffolding so therapy can work.\n• **Sleep & Sun**: Circadian rhythm disruption causes deep mood drops.\n• **Exercise**: Acts like medicine; it releases BDNF, a compound that grows new brain cells.",
      highlight: "Pills don't teach skills, but they can get you out of bed so you can learn the skills. 🪜",
    },
    {
      id: 'how_to_help_others',
      title: "How to Help a Friend 🆘",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'users',
      svgIcon: 'heart',
      content: "What NOT to say:\n🚫 'Cheer up!'\n🚫 'Other people have it worse.'\n🚫 'It's all in your head.'\n\nWhat TO say/do:\n✅ 'I'm here for you, no matter what.'\n✅ Do small tasks for them (bring food, do laundry).\n✅ Sit with them in the dark. Don't rush to 'fix' them.",
      highlight: "Empathy doesn't require fixing. It just requires presence. 🛋️",
    },
    {
      id: 'suicide_warning',
      title: "The Ultimate Danger (Trigger Warning) ⚠️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "When pain exceeds resources, the brain looks for an escape.\nMost people who are suicidal don't actually want to die; they just want the unbearable pain to stop.\n\nWarning signs include giving away possessions, sudden calmness (after severe depression), and withdrawing. **Always take it seriously.** Asking someone directly, 'Are you thinking about suicide?' does NOT plant the idea; it often relieves them.",
      highlight: "If you feel this way, please stay. The world is better with you in it. Pain is temporary, but death is permanent. 🙏",
    },
    {
      id: 'hope_neuroplasticity',
      title: "Healing is Possible 🌅",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'sun',
      svgIcon: 'star',
      content: "Because of **Neuroplasticity**, your brain is always changing. \nDepression does not have to be a life sentence. With time, therapy, support, and sometimes medication, you can grow new neural pathways. The fog *does* lift. The color *does* come back.",
      highlight: "You have survived 100% of your bad days. Keep going. 🛤️",
    },
  ],

  lab: {
    title: "Cognitive Reframing Engine Matrix",
    description: "Your subject's brain is stuck in a downward rumination spiral! Use CBT (Cognitive Behavioral Therapy) principles to 'catch, challenge, and reframe' negative thoughts before their energy (spoon) meter hits zero.",
    hint: "Identify the logical extreme in the thought. Are they 'mind-reading' or 'catastrophizing'? Counter with evidence!",
    scientistModeHint: "Psychiatry Overdrive: Unlock active neurotransmitter simulation and Beck's Triad categorization.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why does depression make you physically hurt?", answer: "The brain processes physical pain and emotional pain in the exact same areas (anterior cingulate cortex). Severe emotional distress literally triggers pain signals in the body, causing unexplained aches, heaviness, and chest tightness. 🤕", emoji: '💔' },
    { id: 'dyk2', question: "Why do depressed people struggle to make basic decisions?", answer: "Depression impairs the prefrontal cortex—the CEO of the brain responsible for logic and decision-making. Suddenly, choosing what to eat for dinner feels like trying to solve advanced calculus. 😵‍💫", emoji: '🧠' },
    { id: 'dyk3', question: "Why is morning time often the worst?", answer: "Many people experience 'diurnal variation,' where depression is most punishing right after waking up. It's linked to cortisol (stress hormone) spikes in the morning. Ironically, forcing yourself to get sunlight immediately can help reset this. 🌅", emoji: '⏰' },
    { id: 'dyk4', question: "Why isn't 'High-Functioning' a clinical diagnosis?", answer: "Because 'high-functioning' only describes how useful you are to capitalism/others, not how much you are suffering inside. Many highly successful people are privately dealing with severe dysthymia. 🎭", emoji: '👔' },
    { id: 'dyk5', question: "Why does cleaning your room actually help a little?", answer: "Depression causes overwhelming chaos in the mind. The brain seeks external order to feel safe. Achieving a small, visible task like making the bed gives a tiny hit of dopamine and proves to the brain: 'I am capable of change.' 🛏️", emoji: '🧹' },
  ],

  quiz: [
    { id: 'q1', question: "What is Anhedonia?", options: ['Extreme anger', 'The inability to feel pleasure', 'Talking constantly', 'Fear of spiders'], answer: 1, explanation: "Anhedonia shuts down the brain's reward system, making hobbies and food feel empty. 🔕" },
    { id: 'q2', question: "How does depression actually affect the brain physically?", options: ['It makes the brain heavier', 'It can shrink the hippocampus (memory center) and reduce nerve growth', 'It turns the brain blue', 'No physical changes occur'], answer: 1, explanation: "Depression is neurotoxic over long periods, but neuroplasticity can repair it. 🧠" },
    { id: 'q3', question: "What does 'The Spoon Theory' describe?", options: ['Cooking habits', 'The limited energy budget people with chronic illness or depression have', 'A new diet', 'How to take medicine'], answer: 1, explanation: "Every small task costs a 'spoon' of energy, and depressed people start with very few. 🥄" },
    { id: 'q4', question: "According to Beck's Cognitive Triad, depression causes negative views of what three things?", options: ['Work, money, pets', 'Self, the World, and the Future', 'Past, present, friends', 'Diet, exercise, sleep'], answer: 1, explanation: "This triad forms the core of depressive thinking according to Cognitive Behavioral Therapy. 🔺" },
    { id: 'q5', question: "What is 'Rumination'?", options: ['Eating too fast', 'Obsessively looping negative thoughts in your mind without finding a solution', 'Sleeping all day', 'Running away'], answer: 1, explanation: "Like a cow chewing cud, the brain chews on the same painful thought endlessly. 🔄" },
    { id: 'q6', question: "What is the new scientific theory connecting depression to the body's immune system?", options: ['Depression is a cold', 'Stress causes inflammation, making the brain act like it has a physical infection', 'The stomach hurts', 'Too much sugar'], answer: 1, explanation: "Inflammatory cytokines can cause 'sickness behavior', leading to withdrawal. 🦠" },
    { id: 'q7', question: "What is 'Dysthymia' (PDD)?", options: ['A type of medicine', 'A long-term, low-grade depression that lasts for years', 'Sudden panic', 'Being overly happy'], answer: 1, explanation: "It's like a constant dull ache rather than a sharp, intense pain. 🌫️" },
    { id: 'q8', question: "What is the primary danger of the 'Downward Spiral'?", options: ['Dizziness', 'Isolation leads to less stimulation, which deepens the depression, causing more isolation', 'Financial ruin', 'Getting a cold'], answer: 1, explanation: "Depression tricks you into doing exactly what makes the depression worse. 🌪️" },
    { id: 'q9', question: "What is the core principle of Cognitive Behavioral Therapy (CBT)?", options: ['Hypnosis', 'Crying it out', 'Thoughts create feelings, which drive behaviors; changing thoughts changes everything', 'Taking vitamins'], answer: 2, explanation: "By challenging distorted thoughts, CBT rewires the brain's pathways. 🧠" },
    { id: 'q10', question: "What is a helpful way to support a depressed friend?", options: ['Tell them others have it worse', 'Tell them to snap out of it', 'Sit with them and do small, practical tasks for them without judgment', 'Force them to go to a party'], answer: 2, explanation: "Presence and practical help without toxic positivity are best. 🛋️" },
    { id: 'q11', question: "Why shouldn't you say 'cheer up' to a depressed person?", options: ['It costs money', 'It implies depression is just a choice and invalidates their illness', 'They might hit you', 'It makes them sleep'], answer: 1, explanation: "You wouldn't tell someone with asthma to 'just breathe normally'. 🚫" },
    { id: 'q12', question: "If someone is severely depressed, asking them 'Are you thinking about suicide?' will...", options: ['Plant the idea in their head', 'Is a dangerous thing to do', 'Will usually not plant the idea, but instead show them you are a safe person to talk to', 'Will make them angry'], answer: 2, explanation: "Direct, compassionate questions are crucial for preventing tragedy. 🤝" },
    { id: 'q13', question: "What does 'Neuroplasticity' mean for a depressed brain?", options: ['The brain is plastic', 'The brain can grow new neural pathways and heal, meaning depression is treatable', 'The brain melts', 'You need surgery'], answer: 1, explanation: "Neuroplasticity is the biological mechanism of hope. 🌱" },
    { id: 'q14', question: "How does exercise act chemically in a depressed brain?", options: ['It burns calories', 'It releases BDNF, which acts like fertilizer for new brain cells', 'It hurts muscles', 'It has no effect'], answer: 1, explanation: "Exercise is one of the most powerful natural neuro-regenerators. 🏃‍♂️" },
    { id: 'q15', question: "What is Seasonal Affective Disorder (SAD)?", options: ['Crying at movies', 'Depression triggered by changes in seasons, usually due to lack of sunlight in winter', 'Allergies', 'Hating summer'], answer: 1, explanation: "Light therapy is often highly effective for this subtype. ☀️" },
    { id: 'q16', question: "What does 'externalizing the illness' (like the Black Dog analogy) achieve?", options: ['Makes you want a pet', 'Helps you realize I have an illness rather than I am a broken person', 'Makes it worse', 'Cures it instantly'], answer: 1, explanation: "Separating your identity from the disease is vital for recovery. 🐕‍🦺" },
    { id: 'q17', question: "Why do antidepressants take weeks to work?", options: ['Pharmacy delays', "They don't just add chemicals; they trigger biological processes to grow new nerve connections", 'They are weak', 'They need to dissolve'], answer: 1, explanation: "Neurogenesis (growing neurons) takes time, unlike taking an aspirin for a headache. 💊" },
    { id: 'q18', question: "When someone with depression cancels plans last minute, what is usually happening?", options: ['They hate you', 'They are lazy', 'Their energy spoons are depleted and their brain feels overwhelmed', 'They are selfish'], answer: 2, explanation: "It's a symptom of the illness, not a reflection of their feelings for you. 🥄" },
    { id: 'q19', question: "Why is high-functioning depression dangerous?", options: ['Because it spreads', 'Because from the outside the person looks fine and successful, meaning they rarely get help', 'Because they work too hard', 'It is not dangerous'], answer: 1, explanation: "The mask of perfection hides the internal suffering until they collapse. 🎭" },
    { id: 'q20', question: "What is the relationship between physical and emotional pain in the brain?", options: ['They are totally different', 'They are processed in the same brain regions, which is why depression physically hurts', 'Only physical pain is real', 'Emotional pain is fake'], answer: 1, explanation: "Heartbreak and heavy depression register on brain scans similarly to physical injury. 🤕" },
  ],

  relatedTopics: ['anxiety', 'burnout', 'science_of_emotion'],
};
