// ─────────────────────────────────────────────────────────
//  TOPIC: PERSONAL FINANCE
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'personal_finance',
  title: 'Personal Finance',
  subtitle: 'Master the art of managing your own money 💸',
  emoji: '💰',
  category: 'Finance',
  accentKey: 'success',

  hook: {
    question: "Why do some people with huge salaries stay poor, while some with small salaries become millionaires? 🧙‍♂️",
    reveal: "Because it's not about how much you EARN, it's about how much you KEEP. Imagine your income is a bucket of water. If the bucket has 10 holes, it doesn't matter how much water you pour in—it will always be empty. Personal finance is the art of plugging those holes! 🪣💧",
    emoji: '💎',
  },

  theory: [
    {
      id: 'pay_yourself_first',
      title: 'Pay Yourself First 🏆',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🏆',
      svgIcon: 'star',
      content: "Imagine you get a pizza with 10 slices. Most people give 5 slices to the landlord, 3 to the grocery store, and 2 to Netflix. They have 0 left for themselves! \n\n**Pay Yourself First** means you take 2 slices and put them in your 'Future Box' *before* anyone else even smells the pizza. You learn to survive on the remaining 8 slices. This one trick makes you a millionaire over time.",
      highlight: "Don't save what's left after spending; spend what's left after saving! 🍕",
    },
    {
      id: 'rule_50_30_20',
      title: 'The 50/30/20 Rule 📊',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '📊',
      svgIcon: 'chart',
      content: "The simplest money map ever created: \n\n**50% Needs:** Things you *must* have to survive (Rent, Food, Electricity). \n**30% Wants:** Things that make life fun but aren't vital (Netflix, Pizza, Toys). \n**20% Savings:** Money for your future self. \n\nIf your 'Needs' are more than 50%, you are in the 'Danger Zone.' You need to either find a cheaper house or earn more money!",
      highlight: "A budget is just a plan for your dreams, written in numbers. 🎯",
    },
    {
      id: 'emergency_fund_core',
      title: "The 'Financial Shield' 🛡️",
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "Life loves to throw curveballs. Your car breaks down, or you lose your job. \n\nAn **Emergency Fund** is 6 months of living expenses kept in a safe place. Think of it as a magical shield. When a 'disaster' hits, most people panic and go into debt. But if you have your shield, that disaster becomes just a tiny 'inconvenience.' It lets you sleep like a baby even when the world is chaotic.",
      highlight: "An emergency fund turns a crisis into a boring weekend. 😴",
    },
    {
      id: 'lifestyle_inflation',
      title: 'The Lifestyle Trap 🎈',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎈',
      svgIcon: 'alert',
      content: "When people earn more money, they usually buy a bigger car or a fancier phone. This is **Lifestyle Inflation**. \n\nIt's like running on a treadmill—you're moving fast but going nowhere! If you earn ₹20k more but spend ₹20k more, you aren't any richer. The secret to wealth is keeping your expenses low while your income grows. Invest the 'Gap' in the middle to buy your freedom.",
      highlight: "If you spend everything you earn, you're just a high-paid servant to your stuff. 🏰",
    },
    {
      id: 'net_worth',
      title: 'Your Financial Weight ⚖️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'balance',
      content: "Salary is just 'speed.' **Net Worth** is your actual 'weight.' \n\nFormula: **(Everything you OWN) - (Everything you OWE) = Net Worth.** \nIf you drive a BMW but owe the bank ₹50 Lakhs and have zero savings, you are actually 'poorer' than a kid with a piggy bank and zero debt! Don't look at what people have; look at what they actually *keep*.",
      highlight: "True wealth is the money you DON'T see. It's the money that stays in the bank. 💰",
    },
    {
      id: 'sinking_funds',
      title: 'The Sinking Fund 🚢',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🚢',
      svgIcon: 'refresh',
      content: "Birthdays and Holidays happen every year, yet they always 'surprise' people into debt. \n\nA **Sinking Fund** is a mini-piggy bank for things you know are coming. If you need ₹12,000 for a trip next December, you save ₹1,000 every month starting now. When December comes, you pay with zero stress! You are effectively 'pre-paying' for your fun.",
      highlight: "Predictable expenses are not emergencies. Plan for them! 🗓️",
    },
    {
      id: 'smart_goals',
      title: 'Money Time Travel 🎯',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🎯',
      svgIcon: 'target',
      content: "Saying 'I want to be rich' is a wish. A goal needs to be S.M.A.R.T. \n\n**S**pecific: 'I want a bike.' \n**M**easurable: 'It costs ₹2 Lakhs.' \n**A**ctionable: 'I'll save ₹10k a month.' \n**R**ealistic: 'I can afford this.' \n**T**ime-bound: 'I'll have it in 20 months.' \nWhen you have a plan, you are literally sending a gift to your future self through time.",
      highlight: "A goal without a deadline is just a daydream. 💭",
    },
    {
      id: 'needs_vs_wants',
      title: 'The 24-Hour Rule ⏳',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '⏳',
      svgIcon: 'eye',
      content: "Your brain is easily tricked. Advertisements make you think you *need* a new toy when you actually just *want* it. \n\nUse the **24-Hour Rule**: If you want to buy something expensive, wait exactly one day. The 'Dopamine Spark' (the fake excitement) will fade away. If you still want it 24 hours later, go for it! This simple trick will save you thousands of rupees from impulse buying stuff you'll forget in a week.",
      highlight: "Waiting is the superpower that builds empires. 🔑",
    },
    {
      id: 'zero_based_budget',
      title: 'The Cookie Jar Budget 🧾',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🧾',
      svgIcon: 'book',
      content: "In a **Zero-Based Budget**, every single rupee has a 'job.' \n\nImagine you have 100 cookies. You put 50 in the 'Rent Jar,' 30 in the 'Food Jar,' and 20 in the 'Future Jar.' You have 0 cookies left unassigned. If you have cookies left over, they will magically 'disappear' (you'll spend them on junk). Give every rupee a mission before the month starts, and you'll never wonder where it went.",
      highlight: "Tell your money where to go, instead of asking where it went! 🏃‍♂️",
    },
    {
      id: 'psychology_of_spending',
      title: 'The Wealth Illusion 🧠',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🧠',
      svgIcon: 'brain',
      content: "We often buy things just to show other people how much money we have. \n\nBut here's the irony: **Spending money to look rich is the fastest way to stay poor.** True wealth is silent. It's the freedom to quit a job you hate, to travel, or to help others. Wealth is the collection of things you *didn't* buy. Don't build a life that looks good on the outside but feels empty on the inside.",
      highlight: "No one is as impressed with your car as you are. 🎭",
    },
  ],

  lab: {
    title: "The Wealth Factory 🎛️",
    description: "Welcome to your personal financial laboratory! Toggle currencies and explore 3 powerful tools: The 50/30/20 Budget Splitter, the Expense Leak Detector, and the Savings Goal Time Machine. See how small changes today create a massive future! 📉",
    hint: "Try reducing your 'Wants' by just 10% and see how many YEARS it shaves off your 'Savings Goal' timeline. Small tweaks = Big wins!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks precision math, showing the exact daily compounding effects and inflation-adjusted future values.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why swiping a Card feels easier than giving Cash? 💳",
      answer: "Pain! Handing over physical cash activates the 'pain centers' in your brain. You literally feel the loss. Swiping a card removes that friction, so your brain doesn't realize it's losing anything until it's too late. Studies show people spend 20% more when using cards! 🧠",
      emoji: '💸',
    },
    {
      id: 'dyk2',
      question: "Do you know why a daily cup of coffee can cost you a House? ☕",
      answer: "The 'Latte Factor'! If you spend ₹200 on coffee every day, that's ₹6,000 a month. If you invested that ₹6,000 at 12% interest, in 30 years it would be worth over ₹2 Crores! You are literally 'drinking' a luxury apartment over time. 📈",
      emoji: '☕',
    },
    {
      id: 'dyk3',
      question: "Do you know why your Savings Account is secretly 'Losing' money? 📉",
      answer: "The Inflation Monster! If your bank pays you 3% interest but prices of milk and bread go up by 6% (Inflation), your money is actually losing 3% of its 'buying power' every year. Your money is melting like a block of ice in the sun! 🧊",
      emoji: '⚠️',
    },
    {
      id: 'dyk4',
      question: "Do you know why rich people often drive old, boring cars? 🚗",
      answer: "Opportunity Cost! A new car loses 20% of its value the moment you drive it home. Rich people would rather put that money into assets that grow. They know that a ₹20 Lakh car today could be ₹2 Crores in the stock market in 20 years. They value freedom more than a shiny steering wheel. 🎭",
      emoji: '🎭',
    },
    {
      id: 'dyk5',
      question: "Do you know why automation is the 'Cheat Code' of wealth? 🤖",
      answer: "Willpower is weak! If you 'try' to save every month, you'll eventually forget or get tempted. By setting up an automatic transfer the day your salary arrives, you remove your own brain from the equation. You adapt to living on less without even noticing! ⚙️",
      emoji: '🔄',
    },
  ],

  quiz: [
    { id: 'q1', question: "What does 'Pay Yourself First' mean?", options: ["Buying yourself a gift", "Saving money before paying any other bills", "Asking for a raise", "Keeping cash under your bed"], answer: 1, explanation: "Prioritize your future self before you prioritize the landlord! 🏆" },
    { id: 'q2', question: "In the 50/30/20 rule, what is the 20% for?", options: ["Netflix and fun", "Rent and food", "Savings and investments", "Taxes"], answer: 2, explanation: "20% is the fuel for your future wealth! 📊" },
    { id: 'q3', question: "How much should be in a full Emergency Fund?", options: ["₹1,000", "1 month of pay", "3 to 6 months of living expenses", "As much as possible"], answer: 2, explanation: "It's your financial shield against life's curveballs! 🛡️" },
    { id: 'q4', question: "What is 'Lifestyle Inflation'?", options: ["The price of bread going up", "Increasing your spending every time you earn more money", "A type of bank loan", "The stock market crashing"], answer: 1, explanation: "It's the treadmill that keeps high-earners poor! 🎈" },
    { id: 'q5', question: "How do you calculate your Net Worth?", options: ["Your monthly salary", "Everything you Own minus everything you Owe", "Your credit score", "The cash in your wallet"], answer: 1, explanation: "It's your true financial weight! ⚖️" },
    { id: 'q6', question: "What is a 'Sinking Fund'?", options: ["A fund for a boat", "A savings bucket for predictable upcoming expenses", "A debt that keeps growing", "Money you lost in a scam"], answer: 1, explanation: "It's pre-paying for your future fun! 🚢" },
    { id: 'q7', question: "In S.M.A.R.T. goals, what does the 'T' stand for?", options: ["Tax-free", "Time-bound", "Total amount", "Technology"], answer: 1, explanation: "A goal needs a deadline to be real! ⏳" },
    { id: 'q8', question: "Why should you wait 24 hours before buying something expensive?", options: ["To wait for a sale", "To let the 'Fake Excitement' (Dopamine) fade away", "To check with your bank", "To see if the store closes"], answer: 1, explanation: "Logic takes over after the spark dies! 🧠" },
    { id: 'q9', question: "What is a 'Zero-Based Budget'?", options: ["Spending zero money", "Giving every single rupee a specific 'job'", "Having zero debt", "Starting a business with zero money"], answer: 1, explanation: "If you don't give money a job, it wanders off! 🧾" },
    { id: 'q10', question: "According to the 'Wealth Illusion', true wealth is:", options: ["The expensive things you own", "The money you haven't spent yet (freedom)", "Your annual salary", "Your followers on social media"], answer: 1, explanation: "Wealth is the silent power of choice. 🎭" },
    { id: 'q11', question: "Why do people spend more with cards than with cash?", options: ["Cards have more money", "Swiping removes the psychological 'pain' of losing cash", "Cards are faster", "Cash is dirty"], answer: 1, explanation: "The brain doesn't feel the loss without the paper! 💳" },
    { id: 'q12', question: "The 'Latte Factor' teaches us that:", options: ["Coffee is healthy", "Small daily expenses can add up to millions over time", "You should never buy coffee", "Banks like cafes"], answer: 1, explanation: "Small leaks sink big ships over 30 years! ☕" },
    { id: 'q13', question: "Why is a savings account 'melting' like ice?", options: ["Banks have freezers", "Inflation makes prices go up faster than the bank pays interest", "People withdraw too much", "Computers get hot"], answer: 1, explanation: "If prices rise faster than your interest, you are losing power! 🧊" },
    { id: 'q14', question: "Why do rich people often buy used cars?", options: ["They can't afford new ones", "New cars lose 20% value instantly (Opportunity Cost)", "Used cars are faster", "To save on taxes"], answer: 1, explanation: "They'd rather invest the difference in things that grow! 🚗" },
    { id: 'q15', question: "Why is automation the best way to save?", options: ["It uses AI", "It removes human emotion and willpower from the decision", "It is required by law", "It makes the bank happy"], answer: 1, explanation: "Don't trust your brain; trust the machine! 🤖" },
    { id: 'q16', question: "Which is a 'Need' in a 50/30/20 budget?", options: ["Video games", "Basic groceries and rent", "A luxury watch", "A vacation"], answer: 1, explanation: "Needs are things you require for survival! 🏠" },
    { id: 'q17', question: "A negative Net Worth means:", options: ["You are a bad person", "You owe more money than you own in assets", "You have zero income", "You are a billionaire"], answer: 1, explanation: "Debt outweighs your value! ⚖️" },
    { id: 'q18', question: "A Sinking Fund for a yearly insurance payment is:", options: ["An emergency", "Smart planning for a predictable expense", "A waste of time", "A type of investment"], answer: 1, explanation: "It turns a 'surprise' into a non-event! 🗓️" },
    { id: 'q19', question: "What is the primary enemy of a Savings Account?", options: ["The Bank Manager", "Inflation", "The Stock Market", "Credit Cards"], answer: 1, explanation: "Inflation eats the value of your cash while you sleep! ⚠️" },
    { id: 'q20', question: "Personal finance is mostly about:", options: ["Complex math", "Human behavior and discipline", "Knowing the right stock", "Having a high-paying job"], answer: 1, explanation: "It's 80% behavior and only 20% math! 🧠" }
  ],

  relatedTopics: ['debt_credit', 'investing', 'financial_literacy'],
};
