// ─────────────────────────────────────────────────────────
//  TOPIC: MANIPULATION TACTICS
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'manipulation_tactics',
  title: 'Manipulation & Influence',
  subtitle: 'How to recognize and defend your mind 🛡️🧠',
  emoji: '🛡️',
  category: 'Society',
  accentKey: 'logic',

  hook: {
    question: "Have you ever bought something you didn't need, just because the salesperson gave you a 'free' coffee first? ☕",
    reveal: "That wasn't an accident. You fell victim to the 'Rule of Reciprocity'—a hardwired psychological loophole in the human brain. Every day, marketers, politicians, and toxic individuals use scientifically proven tactics to bypass your logic and hijack your decision-making. To defend your mind, you must learn the playbook of the manipulators. Let's build your mental armor! ⚔️🛡️",
    emoji: '♟️',
  },

  theory: [
    {
      id: 'weaponized_psychology',
      title: 'Weaponized Psychology ⚔️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚔️',
      svgIcon: 'brain',
      content: "Psychological manipulation happens when someone uses your natural cognitive biases against you to get what they want. \n\nDr. Robert Cialdini famously identified the '6 Principles of Influence': Reciprocity, Scarcity, Authority, Consistency, Liking, and Social Proof. \nWhile these principles help society function, manipulators use them as 'weapons of automatic influence' to trigger a mindless compliance reflex in your brain. 🤖",
      highlight: "Manipulation bypasses your critical thinking and targets your evolved instincts. 🧠",
    },
    {
      id: 'reciprocity',
      title: '1. Reciprocity (The Free Gift) 🎁',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎁',
      svgIcon: 'link',
      content: "The Rule of Reciprocity states that we feel deeply obligated to repay debts. \n\nIf someone gives you a 'free' sample at the grocery store, they aren't being nice; they are triggering thousands of years of evolutionary guilt! Your brain hates being in social 'debt'. \nOften, you will buy a $10 product just to resolve the uncomfortable feeling of accepting a 50-cent piece of cheese. 🧀",
      highlight: "A 'free' gift is never free; it is a psychological down-payment on your money. 💸",
    },
    {
      id: 'scarcity',
      title: '2. Scarcity (Only 2 Left!) ⏳',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⏳',
      svgIcon: 'lock',
      content: "The brain computes value based on availability. If something is rare, the brain assumes it must be incredibly valuable. \n\n**Scarcity** causes panic. When a website says 'Only 2 rooms left at this price!' or 'Sale ends in 5 minutes!', your Amygdala fires. The fear of missing out (FOMO) completely shuts down your logical Prefrontal Cortex. You stop asking 'Do I need this?' and start asking 'How do I beat the other buyers to it?' 🏃‍♂️",
      highlight: "Artificial scarcity manufactures artificial panic. Slow down! 🛑",
    },
    {
      id: 'authority',
      title: '3. Authority (Trust the Lab Coat) 🥼',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🥼',
      svgIcon: 'shield',
      content: "From childhood, we are trained to obey authority figures. \n\nManipulators exploit this by adopting the *symbols* of authority: a lab coat, a clipboard, an expensive suit, or a blue verification checkmark. \nIn the famous Milgram Experiment, normal people delivered what they thought were lethal electric shocks to a stranger simply because a guy in a grey lab coat sternly told them: 'The experiment requires that you continue.' ⚡",
      highlight: "We often obey the *appearance* of authority without verifying its truth. 🔍",
    },
    {
      id: 'consistency',
      title: '4. Consistency (Foot in the Door) 🚪',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🚪',
      svgIcon: 'target',
      content: "Humans have a deep psychological need to appear consistent to themselves and others. \n\n**The Foot-in-the-Door Technique** asks you for a tiny, harmless favor (like signing a petition). Once you say 'Yes,' you view yourself as a 'supporter' of that cause. \nA week later, they ask for a massive donation. Because you want to remain consistent with your new identity, you are 300% more likely to say yes! 📈",
      highlight: "A tiny 'Yes' today is a psychological trapdoor for a massive 'Yes' tomorrow. 🪤",
    },
    {
      id: 'social_proof',
      title: '5. Social Proof (The Laugh Track) 👏',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '👏',
      svgIcon: 'users',
      content: "When we are uncertain, we look to see what everyone else is doing. \n\nWhy do terrible sitcoms use laugh tracks? Because our brain hears others laughing and concludes, 'This must be funny.' \nWhy do bartenders put fake tips in their tip jars at the start of the night? To create the illusion that 'everyone else is tipping, so you should too.' We are herd animals, terrified of stepping out of line. 🐑",
      highlight: "If 1,000 people do a foolish thing, it is still a foolish thing. 🛑",
    },
    {
      id: 'gaslighting',
      title: 'Gaslighting (Eroding Reality) 🌫️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🌫️',
      svgIcon: 'cloud',
      content: "Moving from marketing to toxic relationships, **Gaslighting** is a form of psychological abuse where the manipulator makes you question your own memory, perception, or sanity.\n\nThey say things like, 'I never said that, you\'re crazy,' or 'You\'re overreacting as always.' \nOver time, you stop trusting your own brain and become completely dependent on the manipulator to tell you what 'reality' is. It is the ultimate form of control. 🕷️",
      highlight: "Gaslighting replaces your internal truth with their fictional narrative. 📖",
    },
    {
      id: 'love_bombing',
      title: 'Love Bombing ❤️💣',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '💣',
      svgIcon: 'heart',
      content: "**Love Bombing** is a tactic used by cults and narcissists at the beginning of a relationship.\n\nThey overwhelm you with extreme affection, gifts, and declarations of love ('We are soulmates!'). This floods your brain with dopamine and oxytocin, making you completely addicted to their validation. \n\nOnce you are hooked and your defenses are down, they withdraw the love and begin the cycle of control and abuse. 📉",
      highlight: "Extreme, unearned affection early in a relationship is a major red flag. 🚩",
    },
    {
      id: 'door_in_the_face',
      title: 'Door in the Face 🚪💥',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '💥',
      svgIcon: 'zap',
      content: "The opposite of Foot-in-the-Door! \n\nSomeone asks you for a massive, unreasonable favor: 'Can you volunteer 20 hours a week for a year?' You immediately say NO. \nThen, they sigh and say, 'Okay... could you just donate $10 then?' \n\nYou feel relief, and you feel like they made a 'concession.' Because of Reciprocity, you feel obligated to make a concession too. You give the $10. (The $10 was their real goal all along!) 🎯",
      highlight: "They create an extreme contrast so the actual request looks tiny by comparison. ⚖️",
    },
    {
      id: 'fear_mongering',
      title: 'Fear-Mongering & Salvation 😱',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '😱',
      svgIcon: 'alert',
      content: "Fear is the oldest, most powerful emotion in the brain. \n\nPoliticians and advertisers use this two-step formula:\n1. Invent or exaggerate a terrifying threat (Crime! Germs! Economic collapse!). This shuts down your logical brain. 🚨\n2. Immediately offer themselves (or their product) as the ONLY salvation from that threat. \n\nYou vote for them or buy their product not out of logic, but out of sheer biological panic. 🛡️",
      highlight: "If someone is making you terrified, ask who benefits from your fear. 🕵️‍♂️",
    },
    {
      id: 'the_decoy_effect',
      title: 'The Decoy Effect (Pricing) 🍿',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🍿',
      svgIcon: 'chart',
      content: "Why is the large popcorn at the movies only 50 cents more than the medium? \n\nThey don't want you to buy the medium. The medium is a **Decoy**. \nIf there was only Small ($3) and Large ($7), many people would buy the small. But by adding the Medium for $6.50, your brain compares the Medium and Large and thinks: 'Wow, the Large is such a great deal!' \n\nThey manipulated your anchor point to force an up-sell. 📈",
      highlight: "Decoys exist to make the more expensive option look mathematically logical. 🧮",
    },
    {
      id: 'sunk_cost_fallacy',
      title: 'Sunk Cost Trap ⚓',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '⚓',
      svgIcon: 'waves',
      content: "Manipulators love the **Sunk Cost Fallacy**.\n\nOnce you invest time, money, or emotion into something (a bad investment, a toxic relationship), it becomes incredibly painful to quit. You think, 'I can't give up now, I've already put 3 years into this!' \n\nManipulators will keep demanding more from you, knowing you are too invested to walk away. Remember: The time you spent is already gone. Don't waste the future trying to fix the past! ⏳",
      highlight: "Holding onto a mistake just because you spent a long time making it is irrational. ✂️",
    },
    {
      id: 'guilt_tripping',
      title: 'Guilt Tripping 🥺',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🥺',
      svgIcon: 'heart',
      content: "Guilt Tripping is a form of emotional blackmail. \n\nInstead of making a direct request, the manipulator makes you feel responsible for their negative emotions. 'It's fine, go out with your friends. I'll just sit here alone like always.' \n\nThey weaponize your empathy against you. By making you feel bad, they force you to change your behavior to 'rescue' them from their self-imposed suffering. 🛟",
      highlight: "Healthy relationships use direct requests; toxic ones use emotional blackmail. 🗣️",
    },
    {
      id: 'the_silent_treatment',
      title: 'The Silent Treatment 🤐',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🤐',
      svgIcon: 'lock',
      content: "Stonewalling or giving someone 'The Silent Treatment' is not just annoying; it is a profound psychological punishment. \n\nHumans need social feedback to feel safe. When a manipulator turns cold and silent, your brain registers it as social abandonment (which hurts like physical pain). \n\nYou eventually break down and apologize (even if you did nothing wrong) just to restore the emotional connection. It's a power play! ♟️",
      highlight: "Silence can be louder and more violent than a scream. 🌪️",
    },
    {
      id: 'defending_the_mind',
      title: 'The Mental Shield 🛡️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "How do you defeat manipulation? \n\n1. **Create Space:** Manipulators rely on urgency. The phrase 'Let me think about it for 24 hours' destroys 90% of sales tactics. ⏱️\n2. **Identify the Feeling:** If a situation makes you feel sudden Guilt, Fear, or Undue Obligation, STOP. Your emotional alarm is ringing. 🚨\n3. **Set Boundaries:** 'No' is a complete sentence. You do not owe an explanation. \n\nYour mind is your fortress. Draw the bridge! 🏰",
      highlight: "Time is the enemy of the manipulator. Never make a major decision in a panic. ⏳",
    },
  ],

  lab: {
    title: "The Influence Shield 🛡️🗣️",
    description: "You have been targeted by 'Auto-Sales-Bot 3000'! It wants you to buy an overpriced Premium subscription. The Bot will use various psychological manipulation tactics. Your job is to analyze its dialogue, correctly identify the 'Tactical Fallacy' it is using (e.g., Scarcity, Reciprocity, Decoy), and select the appropriate logical defense to deflect the attack! 🧠⚔️",
    hint: "If the Bot says 'We just gave you a free upgrade, so surely you can sign up for a year!', it is weaponizing Reciprocity. Deflect it by recognizing that a 'gift' with strings attached is just a bribe!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks NLP (Neuro-Linguistic Programming) detection, Amygdala hijack probabilities, and real-time cognitive bias mapping.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why Apple stores let you play with their devices for hours without bothering you? 🍏",
      answer: "The Endowment Effect! The longer you physically hold an object, the more your brain subconsciously begins to feel like you already 'own' it. When you finally put it down to leave, it feels like a 'loss.' You buy it just to avoid the pain of losing 'your' new iPad! 📱",
      emoji: '🛒',
    },
    {
      id: 'dyk2',
      question: "Do you know why charities send you personalized address labels in the mail with their donation request? ✉️",
      answer: "Reciprocity on a mass scale! The label costs them 2 cents to print. But because they gave you a 'gift', you feel an immense, uncomfortable obligation to send them a $20 check in return. It increases their donation rate by nearly double compared to just asking for money! 💸",
      emoji: '🎁',
    },
    {
      id: 'dyk3',
      question: "Do you know why car salespeople always have to 'go check with their manager'? 🚗",
      answer: "Authority and Exhaustion. First, it establishes the unseen manager as the ultimate 'Authority', removing the salesperson's ability to negotiate. Second, it leaves you sitting alone for 15 minutes, intentionally draining your cognitive energy (Decision Fatigue) so you will just agree when they come back!  خ",
      emoji: '💤',
    },
    {
      id: 'dyk4',
      question: "Do you know why cults isolate new members from their family and friends immediately? 🏕️",
      answer: "Destroying the Reality Check. Cults rely on Gaslighting and extreme indoctrination. By removing your friends and family, they remove your external 'Social Proof.' If the only people you talk to believe the cult leader is a god, your brain eventually shifts its reality to match the herd. 🐑",
      emoji: '🛑',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Limited Edition' sneakers sell out in seconds even if they are ugly? 👟",
      answer: "Scarcity hijacking the primate brain! In the wild, scarce resources meant life or death. The label 'Limited Edition' bypasses your aesthetic judgment and triggers a primal hoarding instinct. You aren't buying the shoe; you are buying the feeling of 'winning' a scarce resource. 🏆",
      emoji: '🔥',
    },
    {
      id: 'dyk6',
      question: "Do you know why conspiracy theorists tell you to 'Do your own research'? 🕵️‍♂️",
      answer: "The Consistency Principle! If they just tell you the theory, you might reject it. But if they convince you to spend 4 hours watching YouTube videos to 'connect the dots' yourself, you invest your own time and ego into the theory. Once you 'discover' it, Cognitive Dissonance prevents you from admitting you wasted your time! 🧩",
      emoji: '🕸️',
    },
    {
      id: 'dyk7',
      question: "Do you know why infomercials always have a studio audience gasping in amazement? 😮",
      answer: "Social Proof. Your brain thinks: 'If 100 people are amazed by this mop, it must be the greatest mop in human history.' Even when you consciously know they are paid actors, the subconscious herd-mentality module in your brain still urges you to buy it! 📺",
      emoji: '👏',
    },
    {
      id: 'dyk8',
      question: "Do you know why narcissists 'Hover' or come back months after a breakup? 🛸",
      answer: "Intermittent Reinforcement (Variable Rewards). Just like a slot machine, a toxic ex will randomly reappear to drop a tiny breadcrumb of affection. This random spike of dopamine keeps you perpetually 'hooked' and waiting for the next payout, preventing you from fully healing and moving on. 🎰",
      emoji: '💔',
    },
    {
      id: 'dyk9',
      question: "Do you know why restaurants put one incredibly expensive $100 steak on the menu? 🥩",
      answer: "Price Anchoring! They know almost nobody will buy the $100 steak. But simply seeing it 'anchors' your brain to a high number. Suddenly, the $40 chicken dish looks like a perfectly reasonable, frugal bargain, instead of the overpriced meal it actually is! ⚓",
      emoji: '💰',
    },
    {
      id: 'dyk10',
      question: "Do you know why asking 'Why are you mad?' is sometimes a manipulation tactic? 😡",
      answer: "It's called 'Baiting.' If you are perfectly calm, but a manipulator repeatedly asks 'Why are you getting so defensive?', they are trying to provoke a reaction. Once you eventually get frustrated and raise your voice, they say, 'See? You are crazy and aggressive.' They manufactured the reaction to validate their narrative! 🎣",
      emoji: '🎭',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the psychological 'Rule of Reciprocity'?", options: ["Physical law of gravity", "Urge to repay favors", "Being kind to others", "Recycling paper products"], answer: 1, explanation: "If they give you a free coffee, your brain screams 'I OWE THEM!' ☕" },
    { id: 'q2', question: "When a website says 'Only 1 item left in stock!', which tactic is it using?", options: ["Appealing to authority", "Using social proof", "Building personal liking", "Creating artificial scarcity"], answer: 3, explanation: "Scarcity triggers primitive FOMO, shutting down the logical brain! ⏳" },
    { id: 'q3', question: "The Milgram Experiment (where people delivered shocks) proved the terrifying power of:", options: ["Power of electricity", "Obedience to authority", "Rule of reciprocity", "Need for consistency"], answer: 1, explanation: "We are deeply conditioned to blindly obey symbols of authority! 🥼" },
    { id: 'q4', question: "What is the 'Foot in the Door' technique?", options: ["Kicking a physical door", "Starting with large requests", "Starting with small requests", "Selling footwear products"], answer: 2, explanation: "Once you say 'Yes' to the tiny thing, you want to remain consistent! 🚪" },
    { id: 'q5', question: "Using fake laugh tracks on TV comedies relies on:", options: ["Rule of reciprocity", "Use of social proof", "Principle of scarcity", "Appeal to authority"], answer: 1, explanation: "Our brains hear the 'herd' laughing and decide we should laugh too! 👏" },
    { id: 'q6', question: "What is 'Gaslighting'?", options: ["Lighting a gas stove", "Questioning one's own reality", "Paying for fuel", "Using sales tactics"], answer: 1, explanation: "It is psychological warfare designed to make you rely on their version of reality! 🌫️" },
    { id: 'q7', question: "What is 'Love Bombing'?", options: ["Watching romantic movies", "Overwhelming with excessive affection", "Giving boxes of chocolate", "Writing romantic poetry"], answer: 1, explanation: "It happens early in toxic relationships to create rapid addiction and dependency! 💣❤️" },
    { id: 'q8', question: "The 'Door in the Face' technique involves:", options: ["Compromising after large rejection", "Slamming heavy doors", "Escaping locked rooms", "Selling home doors"], answer: 0, explanation: "They use extreme contrast to make their real goal look tiny! ⚖️" },
    { id: 'q9', question: "Fear-mongering in politics or ads usually follows what structure?", options: ["Telling jokes for money", "Creating panic then salvation", "Reading factual reports", "Singing catchy songs"], answer: 1, explanation: "They manufacture the poison so they can sell you the antidote! 😱" },
    { id: 'q10', question: "A movie theater offers Small ($3), Medium ($6.50), and Large ($7) popcorn. What is the Medium?", options: ["A good financial deal", "A decoy for comparison", "The healthy food option", "A simple pricing mistake"], answer: 1, explanation: "The Medium exists purely to manipulate your perception of the Large! 🍿" },
    { id: 'q11', question: "What is the 'Sunk Cost Fallacy'?", options: ["A sinking ship", "Continuing due to investment", "Losing loose change", "Standard accounting practice"], answer: 1, explanation: "Don't let the time you already wasted be an excuse to waste more! ⚓" },
    { id: 'q12', question: "Guilt Tripping is fundamentally a form of:", options: ["Emotional blackmail for rescue", "Giving friendly advice", "Using logical reasoning", "Standard business negotiation"], answer: 0, explanation: "It weaponizes the victim's empathy against them! 🥺" },
    { id: 'q13', question: "Using 'The Silent Treatment' to punish someone is biologically cruel because:", options: ["Silence being loud", "Social pain as physical", "Hurting the ears", "Causing extreme sleepiness"], answer: 1, explanation: "It is a power-play designed to force the victim into submission! 🤐" },
    { id: 'q14', question: "What is the single most effective defense against high-pressure sales tactics?", options: ["Yelling at sellers", "Waiting twenty-four hours", "Buying the product", "Crying in public"], answer: 1, explanation: "Time allows the emotional Amygdala to cool down and the logical PFC to turn on! ⏱️" },
    { id: 'q15', question: "The 'Endowment Effect' (like holding an iPad in a store) works because:", options: ["Bright screen displays", "Feeling of ownership", "Heavy physical weight", "Charging the device"], answer: 1, explanation: "You buy the product just to avoid the psychological pain of 'losing' it! 🍏" },
    { id: 'q16', question: "Why do restaurants put a $150 item on the menu that nobody buys?", options: ["Targeting wealthy customers", "Anchoring for comparison", "A printing mistake", "Reserved for chefs"], answer: 1, explanation: "Seeing the high number first 'anchors' your expectations! ⚓" },
    { id: 'q17', question: "Cults use extreme 'Social Proof' by doing what to new members?", options: ["Distributing religious books", "Isolating from outsiders", "Providing free meals", "Enforcing sleep schedules"], answer: 1, explanation: "Without an external reality-check, your brain conforms to the people around you! ⛺" },
    { id: 'q18', question: "If a toxic ex randomly texts you a compliment months after a breakup, they are using:", options: ["Finding true love", "Using intermittent rewards", "Dialing wrong numbers", "Showing genuine kindness"], answer: 1, explanation: "They are pulling the slot-machine lever in your brain! 🎰" },
    { id: 'q19', question: "What is 'Baiting'?", options: ["Catching wild fish", "Provoking an emotional snap", "Cooking a meal", "Hiding from others"], answer: 1, explanation: "They manufacture a negative reaction to make you look like the bad guy! 🎣" },
    { id: 'q20', question: "Which brain structure is entirely bypassed when a manipulator uses 'Scarcity' (Panic/FOMO)?", options: ["The Amygdala region", "The Prefrontal Cortex", "The Brainstem area", "The Visual Cortex"], answer: 1, explanation: "Panic shuts down the adult brain and puts the emotional child in charge! 🧠" },
  ],

  relatedTopics: ['cognitive_biases', 'social_media_trap', 'emotions_motivation'],
};
