// ─────────────────────────────────────────────────────────
//  TOPIC: FINANCIAL LITERACY
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'financial_literacy',
  title: 'Financial Literacy',
  subtitle: 'The math of money, markets, and freedom 📈💰',
  emoji: '📈',
  category: 'Society',
  accentKey: 'civics',

  hook: {
    question: "If you save $100 a month under your mattress for 40 years, you'll have $48,000. But if you invest that exact same amount in an index fund... how much will you have? 🏦",
    reveal: "Over $500,000! That is the staggering, magical power of Compound Interest. The vast majority of people spend 40 hours a week working for money, but zero hours learning how to make money work for them. Financial literacy isn't about becoming a greedy billionaire; it is about buying your own time and freedom back from the system. Let's decode the matrix of money! 🔓💸",
    emoji: '💸',
  },

  theory: [
    {
      id: 'fiat_money',
      title: 'What is Money? (Fiat currency) 💵',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '💵',
      svgIcon: 'star',
      content: "Money used to be backed by physical gold (The Gold Standard). But today, all global money is **Fiat Currency**. \n\nFiat simply means 'by decree'. A $100 bill is just a piece of green cotton paper with zero intrinsic value. It only has value because we all collectively hallucinate and agree that the government says it has value! Money is simply an accounting system for measuring trust and energy exchange. 🤝",
      highlight: "Money is a shared illusion holding global civilization together. 🌍",
    },
    {
      id: 'inflation_tax',
      title: 'Inflation (The Invisible Thief) 🎈',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎈',
      svgIcon: 'alert',
      content: "Because Fiat money isn't tied to gold, governments can print as much as they want. When they print trillions of new dollars, the 'supply' of money goes up, making every dollar you own worth mathematically less! \n\nThis is **Inflation**. Historically, inflation sits around 2-3% per year. This means if you hide $10,000 in your mattress, after 25 years, it will have lost half of its purchasing power! \nSaving cash makes you poorer every single day. 📉",
      highlight: "Inflation is an invisible tax on people holding cash. 💸",
    },
    {
      id: 'assets_vs_liabilities',
      title: 'Assets vs Liabilities ⚖️',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'target',
      content: "Robert Kiyosaki ('Rich Dad Poor Dad') defined the ultimate rule of wealth:\n\n1. **An Asset:** Something that puts money IN your pocket whether you work or not (Stocks, real estate, a business). 📈\n2. **A Liability:** Something that takes money OUT of your pocket (A new car loan, an expensive watch, massive credit card debt). 📉\n\nPoor people buy stuff. Middle-class people buy liabilities they think are assets. Rich people buy producing assets! 🛡️",
      highlight: "Don't work for money. Accrue assets that work for you. 🤖",
    },
    {
      id: 'compound_interest',
      title: 'Compound Interest (The 8th Wonder) 🏔️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🏔️',
      svgIcon: 'refresh',
      content: "Albert Einstein allegedly called **Compound Interest** the 8th wonder of the world. \n\nIf you invest $1,000 and it grows 10%, you have $1,100. The magic happens the next year: you don't just earn 10% on your original $1,000... you earn 10% on the *new $100 too*. Your interest earns interest! \nOver 30 years, this causes the graph to violently curve upward exponentially. Time is the ultimate multiplier of wealth! ⏳",
      highlight: "He who understands it, earns it... he who doesn't... pays it. (Einstein) 🤯",
    },
    {
      id: 'the_stock_market',
      title: 'The Stock Market 📈',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📈',
      svgIcon: 'chart',
      content: "A 'Stock' isn't a magical casino chip; it is partial legal ownership of a living, breathing business. \n\nWhen you buy 1 share of Apple, you literally own a microscopic fraction of Apple. Every time someone buys an iPhone, a fraction of a penny of profit rightfully belongs to you in the form of a 'Dividend' or a rising stock price! \nThe Stock Market is simply a giant grocery store where people buy and sell slices of human productivity. 🛒",
      highlight: "Investing isn't gambling; it is owning human innovation. 🧠",
    },
    {
      id: 'index_funds',
      title: 'Index Funds (The Golden Ticket) 🎫',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🎫',
      svgIcon: 'shield',
      content: "Picking individual stocks is incredibly dangerous. If you put all your money in Blockbuster video in 1999, you went bankrupt. \n\nInstead, you should buy an **Index Fund** (like the S&P 500). An Index Fund is a basket that holds a tiny piece of the 500 biggest companies in America all at once! \nIf 10 companies go bankrupt, it doesn't matter because the other 490 grow! You are simply betting that the economy as a whole will be better in 30 years than it is today. 🇺🇸",
      highlight: "Don't look for the needle in the haystack. Just buy the haystack! (John Bogle) 🌾",
    },
    {
      id: 'dollar_cost_averaging',
      title: 'Dollar Cost Averaging (DCA) 🗓️',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🗓️',
      svgIcon: 'waves',
      content: "Timing the market is impossible. If you try to 'buy low and sell high', your emotions will force you to panic and lose money. \n\nThe proven math strategy is **Dollar Cost Averaging (DCA)**. You automatically invest exactly $100 every single month, no matter what. When the market is high, you buy fewer shares. When the market crashes, everything is on sale, and your $100 buys MORE shares! \nDCA removes human emotion from investing completely. 🤖",
      highlight: "Consistency beats intensity every single time. ⏱️",
    },
    {
      id: 'credit_scores',
      title: 'Your Credit Score (The Financial GPA) 💳',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '💳',
      svgIcon: 'lock',
      content: "A **Credit Score** (FICO) is a three-digit number showing banks how trustworthy you are. \n\nIf you have a high score, banks trust you, and they will give you a mortgage with a tiny 3% interest rate. If your score is terrible, they will charge you an 8% interest rate! On a 30-year house loan, that terrible credit score will literally cost you hundreds of thousands of extra dollars in interest payments. 🏠💸",
      highlight: "A bad credit score is the most expensive mistake you can ever make. 🛑",
    },
    {
      id: 'credit_cards',
      title: 'Credit Cards: A Double-Edged Sword ⚔️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '⚔️',
      svgIcon: 'alert',
      content: "Credit cards are tools. If you pay your balance in full *every single month*, you build an amazing credit score and get free points/cash-back. \n\nBut if you carry a balance, the bank hits you with 25% APR (Annual Percentage Rate). **This is Compound Interest working AGAINST you!** Credit card debt grows exponentially like a cancer, trapping millions of people in modern financial serfdom. ⛓️",
      highlight: "Use a credit card exactly like a debit card: Never spend money you don't already have in the bank! 🏦",
    },
    {
      id: 'emergency_fund',
      title: 'The Emergency Fund (Financial Armor) 🛡️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🛡️',
      svgIcon: 'shield',
      content: "Before you invest a single penny, you must build an **Emergency Fund**. \n\nThis is 3-6 months of living expenses sitting in pure, boring cash in a savings account. \nWhy? Because life is chaotic. Cars break down, hospitals happen, and people get fired. If you don't have an emergency fund, you are forced to use high-interest credit cards to survive the disaster, instantly throwing you into a debt spiral! 🌪️",
      highlight: "An emergency fund isn't an investment. It is insurance against disaster. ☂️",
    },
    {
      id: 'the_latte_factor',
      title: 'Opportunity Cost (The Latte Factor) ☕',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '☕',
      svgIcon: 'refresh',
      content: "Every dollar you spend has an **Opportunity Cost**. \n\nIf you buy a $5 coffee today, you don't just lose $5. You lose what that $5 *would have become* if you invested it. Assuming a 10% market return, that $5 coffee today actually cost your retirement account $87 in 35 years! \nYou don't have to stop drinking coffee, but you must realize that small daily expenses compound into massive lost fortunes! 📉",
      highlight: "Focus on increasing income, but never ignore the math of daily leaks. 💧",
    },
    {
      id: 'taxes_marginal',
      title: 'Marginal Tax Brackets 📜',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '📜',
      svgIcon: 'book',
      content: "People constantly misunderstand taxes. \n\nIf you get a raise that bumps you into the '30% tax bracket', people cry: 'Oh no! Now I lose 30% of my whole paycheck!' \nThis is false! The tax system is **Marginal**. You only pay 30% on the *new money* that spills over into the new bucket! Earning more money will NEVER result in you taking home less money overall. Mathematical fact! 📊",
      highlight: "Never refuse a raise out of a completely false fear of taxes! 📈",
    },
    {
      id: 'good_debt_bad_debt',
      title: 'Good Debt vs Bad Debt ⚖️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'target',
      content: "Debt is not always evil; business owners use it to get rich. \n\n**Bad Debt:** Borrowing money to buy something that plummets in value (a car loan, a TV on a credit card). You pay interest on a dying asset! 🚗📉\n**Good Debt:** Borrowing money at a low interest rate to buy something that goes UP in value and pays you (a mortgage on a rental property). The asset's growth pays off the debt for you! 🏠📈",
      highlight: "Debt is a chainsaw: It can build a house, or cut off your arm. 🪚",
    },
    {
      id: 'fire_movement',
      title: 'F.I.R.E. (Financial Independence) 🔥',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🔥',
      svgIcon: 'zap',
      content: "A massive modern movement is **F.I.R.E.** (Financial Independence, Retire Early). \n\nThe math is simple: The '4% Rule' states that once your invested portfolio is 25 times your annual living expenses, you can withdraw 4% a year forever without running out of money (because the market grows 7% after inflation). \nIf you need $40k a year to live, you need $1 million. Once you hit that number, working becomes entirely optional! 🏌️‍♂️",
      highlight: "Wealth isn't having fancy cars. Wealth is waking up and controlling your own time. ⏱️",
    },
    {
      id: 'the_psychology_of_money',
      title: 'The Psychology of Money 🧠',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧠',
      svgIcon: 'eye',
      content: "Morgan Housel wrote: 'Doing well with money has little to do with how smart you are and a lot to do with how you behave.' \n\nDoctors and engineers go bankrupt all the time because they suffer from greed, panic, and ego. A janitor who quietly invests $100 a month in an index fund for 40 years and never checks the news will retire a multi-millionaire. \nInvesting isn't a math problem; it's an emotional discipline problem! 🧘‍♂️",
      highlight: "To get rich, you need math. To stay rich, you need humility. 🛡️",
    },
  ],

  lab: {
    title: "The Compound Engine 📈",
    description: "Welcome to the Wealth Simulator. Set your Monthly Contribution and adjust the expected Annual Return (Stock Market vs Mattress). Watch how the blue curve (Principal) compares to the massive green curve (Compound Interest) over 40 years. Play with the timeline. Notice how 90% of the explosive wealth is generated in the final 5 years of the simulation! Time is literally money! ⏳💸",
    hint: "Try comparing a 2% return (Savings Account) vs an 8% return (S&P 500 Index Fund) over 40 years. The difference isn't '4 times as much', it is exponentially staggering!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Continuous Compounding Equation $A = Pe^{rt}$, Inflation Adjusted Real-Yields, and logarithmic scaling.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why wealthy people rarely pay high taxes? 🏛️",
      answer: "The tax code is designed to reward investment! If you work for a paycheck (W2 Income), you get taxed at massive rates (up to 37%). But if your money comes from owning assets that go up in value (Long-Term Capital Gains), the tax rate is massively lower (15-20%). The system heavily taxes physical labor, but rewards capital ownership! 📉",
      emoji: '💼',
    },
    {
      id: 'dyk2',
      question: "Do you know why Warren Buffett won a $1 Million bet against Hedge Fund managers? 📉",
      answer: "In 2007, Buffett famously bet that a boring, unmanaged S&P 500 Index Fund would beat the return of highly paid, elite Wall Street hedge fund managers over 10 years. By 2017, the boring Index fund gained 85%, while the 'genius' hedge funds (eaten alive by their own high fees) barely made 22%. Boring math always beats Wall Street gambling! 🐢",
      emoji: '👴',
    },
    {
      id: 'dyk3',
      question: "Do you know why new cars are often terrible financial decisions? 🚗",
      answer: "Depreciation! The second you drive a brand-new $40,000 car off the dealer lot, it historically loses 10-20% of its value instantly. By year 5, it has lost 60% of its value! Taking out a debt loan (where you pay interest) to buy an asset that rapidly destroys its own value is the mathematical definition of Bad Debt! 📉",
      emoji: '💸',
    },
    {
      id: 'dyk4',
      question: "Do you know why a 1% mutual fund fee can destroy your retirement? 🧛‍♂️",
      answer: "Because of compound mathematics! If a Wall Street advisor charges you a 'tiny' 1% management fee, they aren't just taking 1% of your gains; they are taking 1% of your total balance every year. Over 40 years, that 'tiny' 1% fee will legally siphon away nearly 30% of your total lifetime wealth. Never pay high fees; buy low-cost Vanguard index funds instead! 🤯",
      emoji: '📊',
    },
    {
      id: 'dyk5',
      question: "Do you know why starting investing at age 20 is mathematically vastly superior to starting at age 30? ⏳",
      answer: "If you invest $200/month from age 20 to 30, and then STOP totally, you will have MORE money at age 65 than someone who invests $200/month from age 30 to 65! The 10 extra years of compounding time at the very beginning creates an unstoppable snowball effect that pure money later on can never catch up to! ☃️",
      emoji: '⏰',
    },
    {
      id: 'dyk6',
      question: "Do you know why banks desperately want to send college students credit cards? 💳",
      answer: "They are hunting for lifetime debt-slaves. College students usually lack financial literacy and reliable incomes. Banks know that if a student racks up just $3,000 of pizza debt at a 25% interest rate, and only makes the 'Minimum Payment' each month, they will be paying the bank interest for the next 15 years, paying back thousands of dollars more than they borrowed. 🎣",
      emoji: '🎓',
    },
    {
      id: 'dyk7',
      question: "Do you know why a house isn't always an amazing investment? 🏠",
      answer: "Hidden maintenance and opportunity costs! While your house values goes up 3-5% a year, you are bleeding money paying property taxes, a 30-year interest mortgage, roof repairs, and insurance. The actual historical return of a primary residence after expenses is roughly 0% above inflation. A house is a great place to live, but the stock market generates real wealth faster! 🏗️",
      emoji: '🛠️',
    },
    {
      id: 'dyk8',
      question: "Do you know why Lottery winners frequently go bankrupt within 5 years? 🎰",
      answer: "A lack of financial psychology! Wealth is a mirror: It amplifies who you already are. If you don't know how to budget $3,000 a month, giving you $30 Million doesn't fix your behavior; it gives you the liquidity to execute terrible, destructive ideas on a massive scale. They instantly buy liabilities (mansions/yachts) instead of producing assets. ⛵",
      emoji: '💸',
    },
    {
      id: 'dyk9',
      question: "Do you know why fiat currency requires the government to force you to pay taxes in it? 💵",
      answer: "That is the anchor of its value! You might try to invent your own currency ('Dave-Bucks') to trade with your friends. But the US Government says: 'At the end of the year, you MUST owe us US Dollars, or we put you in jail.' Because 330 million people are forced to acquire US Dollars to stay out of jail, the dollar is given guaranteed demand and value! 🏛️",
      emoji: '⚖️',
    },
    {
      id: 'dyk10',
      question: "Do you know why 'Timing the market' is a fool's errand? 📉",
      answer: "Because the market's massive gains happen in incredibly short, unpredictable bursts. J.P. Morgan research proved that from 2002 to 2022, if you just missed the 10 BEST single days in the market, your overall 20-year return was cut entirely in HALF! If you try to guess when to pull your money out, you will inevitably miss the sudden rocket-ship recovery days. Time IN the market beats timing the market! 🚀",
      emoji: '⏱️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What does 'Fiat Currency' mean?", options: ["Currency backed by physical gold", "Government-issued money with no backing", "Money produced by car companies", "Old currency no longer in use"], answer: 1, explanation: "It is a collective illusion of trust! 💵" },
    { id: 'q2', question: "Inflation is technically:", options: ["Physical expansion of air balloons", "Decrease in money's purchasing power", "Increase in personal job income", "General decrease in market prices"], answer: 1, explanation: "An invisible tax on people holding raw cash! 🎈" },
    { id: 'q3', question: "According to strict financial rules, a Liability is something that:", options: ["Something that takes money away", "Something that adds to wealth", "An enjoyable personal activity", "A physically heavy object"], answer: 0, explanation: "Poor people buy stuff. Rich people buy Assets. ⚖️" },
    { id: 'q4', question: "What is Compound Interest?", options: ["A reduction in interest rates", "Interest earned on previous interest", "A standard monthly bank fee", "A complex scientific theory"], answer: 1, explanation: "The 8th wonder of the world that creates an exponential curve! 🏔️" },
    { id: 'q5', question: "When you buy a 'Stock', you are actually:", options: ["Purchasing a gambling token", "Partial ownership in a company", "Buying physical sheets of paper", "Lending money to the government"], answer: 1, explanation: "You own a microscopic slice of human productivity! 📈" },
    { id: 'q6', question: "Why is an 'Index Fund' (like the S&P 500) highly recommended?", options: ["A low-cost investment option", "Broad diversification across many companies", "A guarantee of high returns", "A complex and confusing strategy"], answer: 1, explanation: "Don't find the needle. Buy the haystack! 🎫" },
    { id: 'q7', question: "What is 'Dollar Cost Averaging' (DCA)?", options: ["A standard mathematics examination", "Investing fixed amounts regularly", "Purchasing foreign currency", "Calculating market moving averages"], answer: 1, explanation: "Consistency beats intensity! 🗓️" },
    { id: 'q8', question: "A bad Credit Score will financially harm you because:", options: ["Banks refusing to communicate", "Higher interest rates on loans", "Legal penalties and jail time", "No impact on financial life"], answer: 1, explanation: "Your financial GPA dictates the cost of debt! 💳" },
    { id: 'q9', question: "Credit Card debt is incredibly dangerous because:", options: ["The physical material of cards", "Extremely high interest rates", "Frequent phone calls from banks", "Illegal financial activity"], answer: 1, explanation: "Never spend money you don't already have in the bank! ⚔️" },
    { id: 'q10', question: "Why do financial experts beg you to build a 3-6 month 'Emergency Fund'?", options: ["Hiding cash from others", "Protection against unexpected expenses", "Capital for buying stocks", "Savings for a new vehicle"], answer: 1, explanation: "It is insurance against the chaos of the universe! 🛡️" },
    { id: 'q11', question: "What is 'Opportunity Cost' (e.g. the Latte factor)?", options: ["The price of daily coffee", "Potential gains given up today", "The value of lost time", "Rules for local cafes"], answer: 1, explanation: "Small daily leaks sink massive ships over time! ☕" },
    { id: 'q12', question: "If a raise bumps you into a 'higher tax bracket', will you take home less money overall?", options: ["Always results in less pay", "Higher rates apply only to extra income", "Sometimes results in less pay", "Taxes are not real"], answer: 1, explanation: "Never refuse a raise out of fear of taxes! 📜" },
    { id: 'q13', question: "What is an example of 'Good Debt'?", options: ["Debt used for vacations", "Loans for appreciating assets", "High-interest vehicle loans", "Borrowing money to gamble"], answer: 1, explanation: "Good debt builds businesses. Bad debt buys depreciating toys! ⚖️" },
    { id: 'q14', question: "In the F.I.R.E. movement, the '4% Rule' states you can safely retire when your invested portfolio reaches:", options: ["One million dollars total", "Twenty-five times annual expenses", "One hundred times annual salary", "Five hundred thousand dollars"], answer: 1, explanation: "The market growth outpaces the 4% withdrawal rate! 🔥" },
    { id: 'q15', question: "Morgan Housel famously said doing well with money is mostly about:", options: ["High intelligence and math skills", "Behavior and emotional discipline", "Pure luck and timing", "Inheriting wealth from parents"], answer: 1, explanation: "A patient janitor will beat a manic Wall Street stock picker! 🧠" },
    { id: 'q16', question: "Why did Warren Buffett win his $1 Million bet against the Hedge Funds?", options: ["Using unfair advantages", "Index funds beating active managers", "A total market crash", "Picking a single winning stock"], answer: 1, explanation: "Boring math beats gambling! 📉" },
    { id: 'q17', question: "Why is an actively managed mutual fund with a 'small' 1% fee actually terribly expensive?", options: ["An affordable investment cost", "Significant loss of long-term wealth", "Poor behavior from managers", "A flat one-hundred dollar fee"], answer: 1, explanation: "Never underestimate the math of compound subtraction! 🧛‍♂️" },
    { id: 'q18', question: "Starting to invest at age 20 is vastly superior to starting at 30 because:", options: ["Higher intelligence at youth", "More time for compound growth", "Fewer personal living expenses", "Lower prices for stocks"], answer: 1, explanation: "Time is the most powerful variable in the compounding equation! ⏳" },
    { id: 'q19', question: "Buying a brand new car off the lot is structurally a bad financial move because:", options: ["Dishonest car sales tactics", "Rapid loss of asset value", "High cost of fuel", "Frequent mechanical failures"], answer: 1, explanation: "Paying interest on a dying asset! 🚗" },
    { id: 'q20', question: "J.P. Morgan research on 'Timing the Market' proved that:", options: ["Benefits of day trading", "Missing best days reduces returns", "Market timing works perfectly", "Financial markets are fraudulent"], answer: 1, explanation: "Time IN the market beats timing the market! 🚀" },
  ],

  relatedTopics: ['cognitive_biases', 'good_citizen', 'meaningful_life'],
};
