// @ts-nocheck
// ─────────────────────────────────────────────────────────
//  TOPIC: BURNOUT (बर्नआउट)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'burnout',
  title: 'Burnout',
  subtitle: 'The Collapse of the System 🔋🔥',
  emoji: '🔋',
  category: 'Mental Health',
  accentKey: 'burnout',

  hook: {
    question: "Why does a weekend of sleep not fix your exhaustion?",
    reveal: "Because you aren't just 'tired'; your biological stress-response system is completely broken.\n\nMost people confuse Stress with Burnout. Stress is 'Too Much' (too many emails, too much panic, too much adrenaline). Burnout is 'Not Enough' (no energy, no motivation, no care). It is the psychological equivalent of a car running out of oil until the engine physically seizes up. Let's study how the brain shuts down when it can no longer cope with modern life. 🛑📉🚗",
    emoji: '🛑',
  },

  theory: [
    {
      id: 'stress_vs_burnout',
      title: "Stress vs. Burnout 📊",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "**Stress** is characterized by over-engagement, urgency, and hyperactivity. It primarily causes physical damage (heart attacks).\n**Burnout** is characterized by disengagement, blunted emotions, and helplessness. It primarily causes emotional damage.\nIf stress is drowning in an ocean of water, burnout is wandering in a desert with no water at all.",
      highlight: "Stressed people believe 'If I just get everything done, I'll be fine.' Burned-out people don't care if it gets done at all. 🏜️",
    },
    {
      id: 'the_cortisol_crash',
      title: "The Cortisol Crash 📉",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'trending-down',
      svgIcon: 'alert',
      content: "When you are stressed, your adrenal glands pump out **Cortisol** (the stress hormone) to give you energy to 'fight or flee'.\nBut if the stress never stops (toxic job, bad marriage), the adrenal glands eventually fatigue. They stop producing cortisol entirely.\nWithout cortisol, you physically cannot drag yourself out of bed. Your body initiates a forced shutdown.",
      highlight: "Burnout is not a mindset issue; it is a physiological gland failure. 🩺",
    },
    {
      id: 'three_components',
      title: "The 3 Pillars of Burnout 🏛️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'battery-charging',
      svgIcon: 'lock',
      content: "According to the World Health Organization (WHO), burnout has three distinct dimensions:\n1. **Exhaustion**: Complete energy depletion.\n2. **Cynicism/Depersonalization**: Feeling detached from your job or treating clients/colleagues like objects rather than humans.\n3. **Reduced Efficacy**: Working very hard but accomplishing absolutely nothing.",
      highlight: "Cynicism is the ultimate red flag. When you stop caring about people, the system is failing. 🚩",
    },
    {
      id: 'the_cause',
      title: "The Six Mismatches 🧩",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'alert-triangle',
      svgIcon: 'eye',
      content: "Burnout isn't just caused by 'working too many hours'. It's caused by a mismatch between you and your environment. The 6 mismatches are:\n1. Workload (Too much)\n2. Control (Micromanagement)\n3. Reward (Low pay or no recognition)\n4. Community (Toxic coworkers)\n5. Fairness (Favoritism)\n6. Values (Having to do things you find immoral).",
      highlight: "You can work 80 hours a week and not burn out if you are highly rewarded and align with the values. 🎯",
    },
    {
      id: 'decision_fatigue',
      title: "Decision Fatigue ⚖️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'layers',
      svgIcon: 'target',
      content: "Every single decision you make—from what to wear to how to reply to an email—burns a tiny amount of glucose in your prefrontal cortex.\nWhen the glucose is gone, you hit **Decision Fatigue**. You either start making reckless choices (eating junk food) or become completely paralyzed and cannot decide what to watch on Netflix.",
      highlight: "Steve Jobs wore the exact same outfit every day to save his brain's 'decision energy' for important things. 👕",
    },
    {
      id: 'completion_of_stress_cycle',
      title: "Completing the Stress Cycle 🏃‍♂️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'check-circle',
      svgIcon: 'heart',
      content: "In the wild, a zebra runs from a lion (stress), escapes, and then shakes its body to 'complete the biological stress cycle'.\nModern humans deal with 'invisible lions' (emails, bills). We sit at our desks, stressed but motionless. The stress chemicals get trapped in our bodies.\nTo avoid burnout, you must manually complete the cycle every day via exercise, crying, deep breathing, or a 20-second hug.",
      highlight: "You have to tell your body that you survived the lion. 🦁",
    },
    {
      id: 'revenge_bedtime_procrastination',
      title: "Revenge Bedtime Procrastination 🦉",
      color: '#673AB7',
      bgGradient: ['#1A0030', '#050010'],
      icon: 'moon',
      svgIcon: 'star',
      content: "Do you stay up until 2 AM scrolling on your phone, even though you are exhausted and have to work tomorrow?\nThis is a psychological phenomenon where people who have no control over their daytime life refuse to sleep in order to regain some 'freedom' during the quiet hours of the night.",
      highlight: "You are stealing sleep from your future self to buy 2 hours of freedom today. ⏳",
    },
    {
      id: 'the_myth_of_multitasking',
      title: "The Multitasking Illusion 🤹‍♂️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'cpu',
      svgIcon: 'zap',
      content: "The human brain cannot multitask. It 'task-switches'.\nEvery time you switch from writing a report to checking a text message, your brain takes an 'attentional penalty'. It takes an average of 23 minutes to fully regain deep focus after an interruption.\nConstant task-switching exhausts the brain's fuel reserves rapidly, accelerating burnout.",
      highlight: "Multitasking makes you 40% less productive and severely stresses the brain. 🛑",
    },
    {
      id: 'vacations_dont_work',
      title: "Why Vacations Fail 🏖️",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'sun',
      svgIcon: 'compass',
      content: "Many burned-out people think, 'I just need a week off.'\nBut if you take a week off and return to the exact same toxic environment (the 6 mismatches), your burnout will return within 48 hours.\nYou cannot cure burnout by occasionally stepping out of the fire; you have to put the fire out.",
      highlight: "A vacation is a pause button, not a cure. ⏸️",
    },
    {
      id: 'the_hero_syndrome',
      title: "The Hero Syndrome 🦸‍♂️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'star',
      svgIcon: 'users',
      content: "A major internal cause of burnout is the belief that 'If I don't do it, everything will collapse.'\nThis forces you to overcompensate for lazy coworkers or bad systems. While it feels good to be 'the hero' in the short term, the system learns to rely entirely on your self-sacrifice.\nLetting small things fail is often the only way to force management to fix the broken system.",
      highlight: "Learn the art of letting the plate drop. 🍽️💥",
    },
    {
      id: 'brownout',
      title: "The 'Brownout' 🕯️",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'battery',
      svgIcon: 'activity',
      content: "Before a complete burnout, you experience a **Brownout**.\nHalf the lights are on. You can still do your job, but you do the bare minimum ('Quiet Quitting'). You lose all passion, stop volunteering for projects, and constantly complain.\nThis is the warning phase. If you do not intervene here, a total physical collapse is imminent.",
      highlight: "A brownout is your body whispering before it starts screaming. 🗣️",
    },
    {
      id: 'the_cynicism_trap',
      title: "The Cynicism Trap 🕳️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'frown',
      svgIcon: 'lock',
      content: "As burnout progresses, idealism turns into bitter cynicism.\nTeachers start resenting students. Nurses start resenting patients. You begin to believe that no one appreciates you and everyone is an idiot.\nCynicism is the brain's defense mechanism: *'If I stop caring completely, they can't hurt me anymore.'*",
      highlight: "Cynicism feels like a shield, but it is actually a cage. 🛡️",
    },
    {
      id: 'active_rest',
      title: "Passive vs. Active Rest 🧘‍♂️",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'coffee',
      svgIcon: 'leaf',
      content: "**Passive Rest**: Scrolling TikTok or watching Netflix. It stops the expenditure of energy, but it rarely refills the tank.\n**Active Rest**: Walking in nature, reading fiction, cooking, or doing a hobby. These activities actively recharge the parasympathetic nervous system.\nTo cure burnout, you need *restoration*, not just *inactivity*.",
      highlight: "Staring at a screen for 3 hours is not rest; it is digital anesthesia. 📡",
    },
    {
      id: 'radical_boundary',
      title: "The Radical Boundary 🚧",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'minus-circle',
      svgIcon: 'shield',
      content: "Curing burnout requires ruthless boundary setting. \nThis means leaving work at 5 PM on the dot, turning off email notifications on weekends, and saying 'No' to additional projects regardless of the pressure.\nBurnout recovery forces you to choose: Your health, or someone else's expectations.",
      highlight: "'No' is a complete sentence. 🛑",
    },
    {
      id: 'meaning_vs_burnout',
      title: "Meaning as the Antidote ✨",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'compass',
      svgIcon: 'heart',
      content: "Viktor Frankl noted, 'Those who have a 'why' to live, can bear with almost any 'how'.'\nBurnout thrives in meaninglessness. Doing hard work is fine; doing hard work *that doesn't matter* destroys the soul.\nIf you cannot change your job, you must find a hobby, charity, or project outside of work that gives you profound meaning to counteract the burnout.",
      highlight: "Burnout is often not about the volume of work, but the emptiness of the work. 🌌",
    },
  ],

  lab: {
    title: "The Battery Drain Simulator 🔋⚖️",
    description: "You are managing a subject's 'Prefrontal Battery'. Demands (meetings, emails, decisions) constantly drain the battery. You must strategically deploy 'Active Rest' interventions before the battery hits 0%, but if you ignore too many demands, their career will crash. Balance the tightrope.",
    hint: "Passive rest (scrolling) slows the drain but doesn't refill. You must use high-level Active Rest (nature, exercise) to actually recharge.",
    scientistModeHint: "Physiology Mode 🧑‍🔬: Monitor Cortisol depletion and Parasympathetic recovery rates.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do we always get sick right at the start of a vacation?", answer: "The 'Let-Down Effect'. During high stress, cortisol suppresses your immune system to focus purely on survival. When the stress finally stops (e.g., you go on vacation), cortisol levels drop, the immune system rebounds, realizes there are viruses in your body, and triggers a massive inflammatory response (fever/cold). 🤒", emoji: '🏖️' },
    { id: 'dyk2', question: "Why does burnout cause severe memory problems?", answer: "Chronic stress physically damages the hippocampus, the part of the brain responsible for learning and memory. The brain literally shrinks under prolonged burnout, making you forget meetings, names, or where you put your keys. 🧠", emoji: '📉' },
    { id: 'dyk3', question: "Why do you suddenly drop hobbies you used to love when burned out?", answer: "Anhedonia. To conserve the tiny amount of energy it has left, the burned-out brain turns off the 'reward' centers (dopamine). Everything, even playing video games or reading, suddenly feels like a chore that takes too much effort. 🎮", emoji: '🚫' },
    { id: 'dyk4', question: "Why is taking a shower where most people get their best ideas?", answer: "A shower is a 'low-demand' environment. It requires zero decision-making, it is physically comforting, and there are no screens. The brain finally enters the 'Default Mode Network', allowing creative, subconscious thoughts to bubble to the surface. 🚿", emoji: '💡' },
    { id: 'dyk5', question: "Why do burned-out people often crave highly sugary or salty junk food?", answer: "The brain uses 20% of your body's energy. When depleted, it screams for fast, easily metabolizable energy (sugar/carbs) to keep the engine running temporarily. It is a biological SOS signal, not a lack of willpower. 🍩", emoji: '🍕' },
  ],

  quiz: [
    { id: 'q1', question: "What is the primary difference between Stress and Burnout?", options: ['Stress is emotional; Burnout is physical', 'Stress is \'Too much\' (hyperactivity); Burnout is \'Not enough\' (empty, uncaring, collapsed)', 'There is no difference', 'Burnout is easily cured with sleep'], answer: 1, explanation: "Stress makes you panic about failing. Burnout makes you not care if you fail. 🏜️" },
    { id: 'q2', question: "What happens to your Cortisol levels in deep burnout?", options: ['They skyrocket', 'They collapse completely because the adrenal glands are fatigued (Adrenal Fatigue)', 'They stay normal', 'Cortisol turns into dopamine'], answer: 1, explanation: "Without cortisol, you physically lack the energy to get out of bed. 📉" },
    { id: 'q3', question: "According to the WHO, what are the three pillars of Burnout?", options: ['Hunger, Thirst, Sleep', 'Exhaustion, Cynicism (detachment), and Reduced Efficacy (getting nothing done)', 'Anger, Sadness, Fear', 'Headaches, Back pain, Fever'], answer: 1, explanation: "Starting to view clients/coworkers with total cynicism is the biggest red flag. 🚩" },
    { id: 'q4', question: "What is 'Revenge Bedtime Procrastination'?", options: ['Sleeping at work', 'Refusing to go to sleep despite being tired in order to reclaim some \'free time\' control at night', 'Waking up early to exercise', 'Fighting with your spouse at night'], answer: 1, explanation: "It is an act of rebellion against a daytime schedule you do not control. 🦉" },
    { id: 'q5', question: "Why is 'Multitasking' terrible for burnout?", options: ['It breaks the computer', 'The brain cannot multitask; task-switching rapidly burns through the brain\'s limited glucose fuel', 'It makes you too smart', 'It is actually highly effective'], answer: 1, explanation: "You pay a massive 'attentional penalty' every time you switch apps. 🤹‍♂️" },
    { id: 'q6', question: "What is the biological definition of 'completing the stress cycle'?", options: ['Working until the project is done', 'Signaling to your body (via exercise, crying, deep breathing) that the \'threat\' is gone and it can relax', 'Drinking coffee', 'Sleeping 8 hours'], answer: 1, explanation: "If you don't run from the lion, you must physically burn off the adrenaline somehow. 🏃‍♂️" },
    { id: 'q7', question: "What is a 'Brownout'?", options: ['A power failure', 'The warning phase before burnout: you do the bare minimum, complain, and lose all passion', 'Working in the dark', 'Forgetting names'], answer: 1, explanation: "Your body is whispering to you before it decides to scream. 🕯️" },
    { id: 'q8', question: "Why doesn't a one-week vacation cure burnout?", options: ['Vacations are boring', 'Because if you return to the exact same toxic environment (mismatches), the burnout returns immediately', 'You need two weeks', 'The sun causes stress'], answer: 1, explanation: "Taking breaks from the fire doesn't put the fire out. 🏖️" },
    { id: 'q9', question: "What is 'Decision Fatigue'?", options: ['Not knowing what to eat', 'The prefrontal cortex running out of glucose after making too many choices, leading to reckless or paralyzed decision-making', 'Choosing the wrong job', 'Playing too much chess'], answer: 1, explanation: "This is why Mark Zuckerberg and Steve Jobs wear the same clothes every day. ⚖️" },
    { id: 'q10', question: "What is the danger of the 'Hero Syndrome' at work?", options: ['You get paid too much', 'You overcompensate for a broken system, burning yourself out, and preventing management from seeing the actual flaws', 'You become arrogant', 'Coworkers like you too much'], answer: 1, explanation: "Sometimes you have to let the ball drop so the company realizes the juggling act is impossible. 🦸‍♂️" },
    { id: 'q11', question: "What is the difference between Active and Passive rest?", options: ['Active is outdoors; Passive is indoors', 'Passive (scrolling TV) just stops energy expenditure. Active (nature walk) actually refills the parasympathetic nervous system', 'Passive is sleeping; Active is running', 'Active rest makes you tired'], answer: 1, explanation: "Binge-watching Netflix is digital anesthesia, not true rest. 🧘‍♂️" },
    { id: 'q12', question: "Why do we often get sick as soon as a vacation starts?", options: ['Airplanes have germs', 'The drop in stress hormones (cortisol) allows the suppressed immune system to finally attack viruses, causing a sudden inflammatory response', 'Different food', 'Changes in weather'], answer: 1, explanation: "The 'Let-Down Effect'. Your body finally feels safe enough to be sick. 🤒" },
    { id: 'q13', question: "Which of the following is NOT one of the 6 mismatches that cause burnout?", options: ['Unfairness', 'Having too many friends at work', 'Lack of control', 'Values conflict'], answer: 1, explanation: "Community and strong relationships actually protect AGAINST burnout. 🧩" },
    { id: 'q14', question: "How does burnout affect the physical brain?", options: ['It increases size', 'Chronic stress chemically damages and shrinks the Hippocampus, causing severe memory and learning issues', 'It changes eye color', 'It makes you smarter'], answer: 1, explanation: "Burnout literally causes brain damage over long periods. 🧠" },
    { id: 'q15', question: "Why do burned-out people lose interest in their favorite hobbies?", options: ['They get too busy', 'The brain shuts down its dopamine (reward) centers to conserve its severely depleted energy reserves', 'They find new hobbies', 'They get lazy'], answer: 1, explanation: "This symptom is called Anhedonia. 🚫" },
    { id: 'q16', question: "What is the most effective antidote to burnout, according to psychology?", options: ['Drinking more water', 'Finding deep \'Meaning\' or \'Why\' in your work or hobbies', 'Working on weekends', 'Getting a promotion'], answer: 1, explanation: "People can endure immense work if they believe the work profoundly matters. ✨" },
    { id: 'q17', question: "Cynicism in burnout acts as a defense mechanism to do what?", options: ['Make people laugh', "Protect you from further emotional pain by cutting off all emotional investment ('If I don't care, it can't hurt')", 'Get promoted', 'Save time'], answer: 1, explanation: "It feels like a shield, but it emotionally isolates you. 🕳️" },
    { id: 'q18', question: "In the context of burnout, what is a 'Boundary'?", options: ['A fence around the office', 'A strict absolute rule protecting your time and energy (e.g., no emails after 6 PM)', 'A meeting room', 'A promotion requirement'], answer: 1, explanation: "You must choose your health over someone else's mild inconvenience. 🚧" },
    { id: 'q19', question: "Why do burned-out people crave junk food?", options: ['It tastes better', 'The energy-depleted brain sends SOS signals craving fast, easily metabolizable glucose (sugar/carbs) for immediate fuel', 'It is cheap', 'Habit'], answer: 1, explanation: "It is a physiological survival reflex, not a lack of discipline. 🍩" },
    { id: 'q20', question: "What environment allows the brain's 'Default Mode Network' to work (like getting ideas in the shower)?", options: ['A loud office', 'A low-demand environment with zero decision-making, allowing the subconscious to process information', 'A movie theater', 'A stressful exam'], answer: 1, explanation: "Your brain needs empty space to connect the dots. 🚿" },
  ],

  relatedTopics: ['stress', 'overthinking', 'depression'],
};
