// ─────────────────────────────────────────────────────────
//  TOPIC: LEARNING & BEHAVIOR
//  Category: Psychology / Logic
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'learning_behavior',
  title: 'Learning & Behavior',
  subtitle: 'The logic of habits and conditioning 🐕🔔',
  emoji: '🐕',
  category: 'Psychology',
  accentKey: 'behavior',

  hook: {
    question: "If I ring a bell every time I feed a dog, eventually the dog will start drooling just by hearing the bell, even if there is NO food. Why? 🐕🔔",
    reveal: "Because your brain is a 'Pattern-Matching' machine! **Learning** is the process of creating new connections between ideas or behaviors. From the way you learned to walk, to the way you've formed a habit of checking your phone, your brain is constantly using 'Conditioning' to decide what's useful and what's not. Let's learn to hack your own habits! 🧠🛠️",
    emoji: '📈',
  },

  theory: [
    {
      id: 'what_is_learning',
      title: 'What is Learning? 🧠',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧠',
      svgIcon: 'eye',
      content: "In psychology, **Learning** isn't just about reading books. It is defined as a *permanent change in behavior* as a result of experience 📉.\n\nYour brain is always asking: 'If I do X, does Y happen?' \n\nLearning allows us to adapt to our environment. We learn which foods taste good, which people to trust, and which shortcuts to take home. We do this through two main methods: **Classical Conditioning** (Associations) and **Operant Conditioning** (Rewards and Punishments).",
      highlight: "Learning is your brain's way of predicting the future based on the past. 🔮",
    },
    {
      id: 'classical_conditioning',
      title: 'Pavlov\'s Bell: Associations 🔔',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🔔',
      svgIcon: 'zap',
      content: "Ivan Pavlov accidentally discovered **Classical Conditioning** while studying dogs. \n\nHe realized that if a neutral stimulus (a Bell) is repeatedly paired with a meaningful one (Food), the brain starts to treat the Neutral one as the meaningful one! 🐕\n\n• **Unconditioned Stimulus:** Food 🥩\n• **Unconditioned Response:** Drooling 🤤\n• **Conditioned Stimulus:** The Bell 🔔\n\nThis is why the 'ping' of a notification makes you feel excited before you even see the message! 📱",
      highlight: "Classical conditioning connects a 'Trigger' to a 'Feeling' automatically. 🔄",
    },
    {
      id: 'operant_conditioning',
      title: 'Skinner: Actions & Results ⚙️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '⚙️',
      svgIcon: 'target',
      content: "While Pavlov focused on triggers, B.F. Skinner focused on **Consequences**. This is **Operant Conditioning**.\n\nHe believed that behavior is shaped by what happens AFTER you act. \n• If you do something and get a reward, you'll do it again (Reinforcement) ✅.\n• If you do something and get a 'punishment' (like a shock or a fine), you'll stop doing it (Punishment) ❌.\n\nHe used 'Skinner Boxes' to train pigeons to play ping-pong and rats to pull levers just by using pellets of food! 🐦🏓",
      highlight: "Behavior that is rewarded is repeated; behavior that is punished is avoided. ⚖️",
    },
    {
      id: 'reinforcement_types',
      title: 'Reinforcement vs Punishment 🍎⚡',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🍎',
      svgIcon: 'waves',
      content: "There are four ways to change a behavior:\n\n1. **Positive Reinforcement:** Adding something GOOD (Giving a dog a treat for sitting) 🍖.\n2. **Negative Reinforcement:** Removing something BAD (The annoying car beep stops when you buckle your seatbelt) 🔔.\n3. **Positive Punishment:** Adding something BAD (Getting a ticket for speeding) 🏎️.\n4. **Negative Punishment:** Removing something GOOD (Taking away a teenager's phone) 📱.\n\n**Note:** Reinforcement always *increases* behavior; Punishment always *decreases* it.",
      highlight: "Negative Reinforcement is NOT punishment—it's an 'Escape' from something annoying! 🛡️",
    },
    {
      id: 'habit_formation',
      title: 'The Habit Loop 🔁',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🔁',
      svgIcon: 'link',
      content: "Habits are 'Autopilot' programs in your brain. They follow a 3-step loop:\n\n1. **The Cue:** A trigger (Walking into the kitchen) 🚶‍♂️.\n2. **The Routine:** The action (Opening the fridge) 🥘.\n3. **The Reward:** The dopamine hit (Finding a snack) 🍪.\n\nWhen a habit is formed, a part of your brain called the **Basal Ganglia** takes over. You stop 'thinking' about the action, and your brain goes into 'save energy' mode. This is why you can drive home and realized you didn't 'consciously' think about a single turn! 🚗💨",
      highlight: "To break a habit, you must identify the Cue and change the Reward! 🛠️",
    },
    {
      id: 'variable_ratio',
      title: 'The Casino Trick: Variable Ratio 🎰',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🎰',
      svgIcon: 'star',
      content: "Skinner discovered that the MOST addictive way to reinforce a behavior is **Variable Ratio Reinforcement**.\n\nThis means the reward comes at a *random* time. If a rat gets food *every* time it pulls a lever, it stops when it's full. But if it gets food *sometimes* (like a slot machine), it will pull the lever forever, even if it's starving! 🎰\n\nThis is why video games use 'Loot Boxes' and social media uses 'Refresh Feeds'—the uncertainty of 'Maybe I'll win this time' is the strongest hook for your brain! 📱💥",
      highlight: "Uncertainty creates the strongest, hardest-to-break behaviors. 🎣",
    },
    {
      id: 'social_learning',
      title: 'Bandura: Observational Learning 👯',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '👯',
      svgIcon: 'grid',
      content: "You don't have to experience everything yourself to learn. Albert Bandura proved we learn by watching others: **Observational Learning** 📺.\n\nHe showed that children who watched an adult hit a 'Bobo Doll' were much more likely to be aggressive themselves. \n\nThis uses **Mirror Neurons** in the brain. When you watch someone cook, your brain 'simulates' the movements. This is how we learn language, culture, and social skills without ever being explicitly 'trained.' 🗣️",
      highlight: "We are 'Social Sponges'—we absorb the behaviors we see around us! 🧽",
    },
    {
      id: 'cognitive_maps',
      title: 'Cognitive Maps: The Mental GPS 🗺️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🗺️',
      svgIcon: 'paperplane',
      content: "Is all learning just rewards? No! Edward Tolman discovered **Latent Learning** 💤.\n\nHe put rats in a maze with NO food. They seemed like they weren't learning anything. But the moment he put food at the end, they finished the maze perfectly! \n\nThey had been building a **Cognitive Map** (a mental layout) while exploring. They learned the information, but only used it when there was a motivation to do so. This proves that your brain is always gathering data, even when you aren't 'trying' to learn. 🕵️‍♂️",
      highlight: "You are always learning in the background, even without a reward. 📂",
    },
    {
      id: 'biological_limits',
      title: 'Biological Preparedness 🦁',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🦁',
      svgIcon: 'shield',
      content: "Not all behaviors are equally easy to learn. We are 'Prepared' by evolution to learn certain things fast 🧬.\n\nFor example, if you eat a new fruit and get sick 6 hours later, you will instantly DEVELOP a 'Taste Aversion' to that fruit forever. But you won't develop an aversion to the music that was playing while you ate it! 🎵\n\nOur brains are wired to connect **Stomach Pain $\rightarrow$ Food** and **Sight $\rightarrow$ Danger**. We are biologically 'ready' to learn what keeps us alive. 🌳",
      highlight: "Evolution has 'pre-wired' your brain to learn certain associations instantly. 🛡️",
    },
    {
      id: 'shaping',
      title: 'Shaping: Building Complexity 🏗️',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🏗️',
      svgIcon: 'flask',
      content: "How do you teach a dog to bring you a soda? You can't just wait for it to happen and reward it. You use **Shaping** 🦴.\n\nShaping is rewarding 'Successive Approximations' of a behavior:\n1. Reward the dog for looking at the soda. 🥤\n2. Reward it for touching the soda. 🐾\n3. Reward it for picking up the soda. 👄\n\nBy rewarding small steps, you can 'carve' a complex behavior out of simple ones. This is exactly how humans learn complex skills like piano or coding! 🎹💻",
      highlight: "Great skills are built by layering many small, rewarded successes. 🧗‍♂️",
    },
  ],

  lab: {
    title: "The Training Maze Lab 🐁🧀",
    description: "Step into the role of a behavioral scientist! A virtual creature is in a complex maze. Use 'Positive Reinforcement' (Food 🧀) or 'Sensory Triggers' (Buzzer 🔔) to shape its behavior. Watch the 'Neural Paths' grow thicker as the AI learns the pattern. Can you achieve 100% Learning Accuracy in under 10 trials? 🧪",
    hint: "Try rewarding the creature ONLY when it turns right. Over several trials, you'll see its 'Decision Probability' shift. Don't punish too much, or the creature may develop 'Learned Helplessness' and stop moving!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks the 'Reward Prediction Error' graph, the Rescorla-Wagner learning constant ($\alpha$), and real-time synaptic weight metrics.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why Pavlov's dogs were actually a bit of a disaster? 🐕🧪",
      answer: "Pavlov wasn't a psychologist—he was a biologist studying digestion! He had to cut holes in the dogs' cheeks to collect saliva. The dogs started drooling when they heard the *footsteps* of the lab assistants bringing food. Pavlov was annoyed because it 'ruined' his data on stomach acid, but he eventually realized the 'Mental Secretions' were a way more important discovery! 🔬",
      emoji: '👣',
    },
    {
      id: 'dyk2',
      question: "Do you know why casinos have no windows and loud noises? 🎰🚫",
      answer: "Sensory Conditioning! The flashing lights and jingling coins act as 'Secondary Reinforcers'. They keep your brain in a state of high Dopamine arousal. Without windows (to see the time) and with constant 'Wins' (even if they are small), your brain loses its ability to track logic and stays in the 'Variable Ratio' loop! 🕰️",
      emoji: '🎰',
    },
    {
      id: 'dyk3',
      question: "Do you know why you can't tickle yourself (Behavioral answer)? 🧤",
      answer: "Reaffirmation! Your brain's motor system sends a 'copy' of your movement (Efference Copy) to the sensory system saying 'I am doing this.' Because it's 100% predictable, there is no 'Surprise' or 'Response' needed. Learning requires a gap between what you expect and what happens! 🤫",
      emoji: '🧠',
    },
    {
      id: 'dyk4',
      question: "Do you know why 'Learned Helplessness' is so dangerous? 🛑",
      answer: "In a famous experiment, dogs were given shocks they couldn't escape. Eventually, even when the cage was opened, they didn't try to leave. They had 'Learned' that effort was useless. This is a core component of human depression—the belief that your actions have no power over your environment. 📉",
      emoji: '😔',
    },
    {
      id: 'dyk5',
      question: "Do you know why Pigeons were trained to guide missiles in WWII? 🐦🚀",
      answer: "Skinner's project! He used operant conditioning to train pigeons to peck at a silhouette of a ship on a screen. Their pecking would adjust the missile's fins. It actually worked perfectly in tests! The military eventually cancelled it because they thought 'Pigeon-guided missiles' sounded too ridiculous, despite the perfect math. 🏗️",
      emoji: '🎖️',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the process of creating a link between a neutral trigger and a natural response?", options: ["Process of operant conditioning", "Process of classical conditioning", "Formation of habit loops", "Process of behavioral shaping"], answer: 1, explanation: "Pavlov's Bell is the classic example of this 'Pattern Matching'! 🔔" },
    { id: 'q2', question: "In Skinner's work, anything that INCREASES a behavior is called:", options: ["A form of punishment", "A form of reinforcement", "A type of trigger", "A type of cue"], answer: 1, explanation: "Reinforcement (Positive or Negative) always makes a behavior more likely to happen again! ✅" },
    { id: 'q3', question: "Removing an annoying beep when you put on your seatbelt is an example of:", options: ["Example of positive reinforcement", "Example of negative reinforcement", "Example of positive punishment", "Example of negative punishment"], answer: 1, explanation: "You are removing something BAD to reward a GOOD behavior. That's Negative Reinforcement! 🛡️" },
    { id: 'q4', question: "Which reinforcement schedule is the MOST addictive (like a slot machine)?", options: ["Fixed ratio reinforcement schedule", "Fixed interval reinforcement schedule", "Variable ratio reinforcement schedule", "Constant reinforcement schedule"], answer: 2, explanation: "Because the reward is 'Random,' the brain stays hooked on the 'Maybe'! 🎰" },
    { id: 'q5', question: "A plan of a maze or city built in your mind without rewards is called a:", options: ["A mental habit loop", "A mental cognitive map", "A mental Skinner box", "A mental learning curve"], answer: 1, explanation: "Latent learning allows us to map the world even when we aren't 'trying' to learn! 🗺️" },
    { id: 'q6', question: "What are the special brain cells that fire when you watch someone else act?", options: ["Specialized habit neurons", "Specialized mirror neurons", "Specialized dopamine neurons", "Specialized glial cells"], answer: 1, explanation: "Mirror neurons are the basis for Observational Learning and Empathy! 👯" },
    { id: 'q7', question: "Teaching a complex trick (like a dog bringing a soda) in small steps is called:", options: ["Process of behavioral conditioning", "Process of behavioral shaping", "Process of cognitive mapping", "Process of stimulus fading"], answer: 1, explanation: "Shaping layers small successes to build one giant skill! 🧗‍♂️" },
    { id: 'q8', question: "Taking away a child's toy for being mean is an example of:", options: ["Example of positive punishment", "Example of negative punishment", "Example of negative reinforcement", "Example of classical conditioning"], answer: 1, explanation: "You are removing something GOOD to decrease a bad behavior. That's Negative Punishment! 📱" },
    { id: 'q9', question: "The part of the brain responsible for the 'Autopilot' routine of habits is:", options: ["The prefrontal cortex region", "The basal ganglia region", "The brain's amygdala region", "The brain's cerebellum region"], answer: 1, explanation: "The Basal Ganglia stores your learned 'Scripts' to save brain energy! 🧠" },
    { id: 'q10', question: "Why is it easy to develop a fear of snakes but hard to develop a fear of cars?", options: ["Inherent fear response mechanism", "Biological preparedness for survival", "Learned utility of objects", "Environmental exposure to stimuli"], answer: 1, explanation: "Evolution has pre-wired us to be wary of threats that plagued our ancestors for millions of years! 🐍" },
    { id: 'q11', question: "Who performed the 'Bobo Doll' experiment on observational learning?", options: ["The researcher Ivan Pavlov", "The researcher B.F. Skinner", "The researcher Albert Bandura", "The researcher Edward Tolman"], answer: 2, explanation: "Bandura proved that children 'copy' the aggression they see in adults. 📺" },
    { id: 'q12', question: "What is 'Extinction' in learning?", options: ["Death of a species", "Loss of learned behavior", "Formation of new habits", "Natural cycle of sleep"], answer: 1, explanation: "If the bell rings 100 times with NO food, the dog eventually stops drooling. The learning has 'extinguished'! 📉" },
    { id: 'q13', question: "What are the three parts of the 'Habit Loop'?", options: ["Start, middle, and end", "Cue, routine, and reward", "Trigger, action, and punishment", "Wake, work, and sleep"], answer: 1, explanation: "Cue (The signal) -> Routine (The habit) -> Reward (The Dopamine)! 🔁" },
    { id: 'q14', question: "The 'Little Albert' experiment showed that which emotion can be conditioned?", options: ["The emotion of joy", "The emotion of fear", "The sensation of hunger", "The state of sleep"], answer: 1, explanation: "Watson showed that a baby could be 'trained' to fear a white rat by pairing it with loud noises. 👶🔊" },
    { id: 'q15', question: "What is 'Learned Helplessness'?", options: ["Helping other people learn", "Belief in lack of control", "State of general laziness", "Type of human intelligence"], answer: 1, explanation: "This happens when a person or animal experiences uncontrollable failures. 🛑" },
    { id: 'q16', question: "A treat (Food) given to a dog for sitting is which type of reinforcement?", options: ["Type of positive reinforcement", "Type of negative reinforcement", "Type of artificial reinforcement", "Type of social reinforcement"], answer: 0, explanation: "Adding something GOOD to increase a behavior! 🍖" },
    { id: 'q17', question: "Why do we remember the smell of an old school building so vividly?", options: ["High volume of sensory input", "Emotional and sensory connection", "Illusion of sensory input", "Random recall of memories"], answer: 1, explanation: "Associations between smell and place are some of the strongest in the brain! 🏫" },
    { id: 'q18', question: "What happens to the 'Neural Path' in the brain as a habit is repeated?", options: ["The neural path weakens", "The neural path strengthens", "The neural path disappears", "The neural path calcifies"], answer: 1, explanation: "The brain turns a 'dirt path' into a 'highway' for the electricity to flow faster! 🏎️💨" },
    { id: 'q19', question: "The 'Rescorla-Wagner' model says learning depends on how much a result is:", options: ["Expected by the subject", "Surprising to the subject", "Large in its magnitude", "Delayed in its timing"], answer: 1, explanation: "If the reward is exactly what you expected, you don't 'learn' anything new! ⚡" },
    { id: 'q20', question: "Which animal did Skinner train to guide WWII missiles?", options: ["Trained laboratory rats", "Trained homing pigeons", "Trained domesticated dogs", "Trained domesticated cats"], answer: 1, explanation: "Project Orcon proved pigeons had a high capacity for pecking-based guidance! 🐦🚀" },
  ],

  relatedTopics: ['cognitive_biases', 'emotions_motivation', 'brain_structure'],
};
