// ─────────────────────────────────────────────────────────
//  TOPIC: MEANINGFUL LIFE
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'meaningful_life',
  title: 'Meaningful Life',
  subtitle: 'The psychology of purpose and Ikigai 🧭🔥',
  emoji: '🧭',
  category: 'Society',
  accentKey: 'philosophy',

  hook: {
    question: "Why do some people survive unimaginable horrors, while others crumble under minor stress? What is their secret? 🏔️",
    reveal: "The secret is 'Meaning.' Holocaust survivor and psychiatrist Viktor Frankl realized that those who survived the camps weren't necessarily the physically strongest; they were the ones who had a 'Why'—a deep purpose to live for. Science shows that having a purposeful life doesn't just make you happier, it actually changes your biology, boosting your immune system and increasing your lifespan! Let's build your 'Why.' 🧱✨",
    emoji: '🔥',
  },

  theory: [
    {
      id: 'frankl_meaning',
      title: 'Man\'s Search for Meaning 📖',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '📖',
      svgIcon: 'book',
      content: "Psychiatrist Viktor Frankl famously wrote: **'He who has a *why* to live for can bear almost any *how*.'** \n\nHe believed that a human's deepest drive is not pleasure (Freud) or power (Adler), but the pursuit of Meaning. When life lacks meaning, we fill the void with destructive habits (addictions, blind consumerism, aggression) to numb the existential pain. 🛡️\n\nMeaning is the ultimate psychological armor against tragedy.",
      highlight: "Meaning makes suffering endurable. Without meaning, even comfort feels empty. 🪹",
    },
    {
      id: 'ikigai_concept',
      title: 'Ikigai: The Reason to Wake Up 🌅',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🌅',
      svgIcon: 'target',
      content: "In Okinawa, Japan (one of the world's 'Blue Zones' where people regularly live past 100), there is no word for 'Retirement.' Instead, there is **Ikigai**—'the reason for which you wake up in the morning.'\n\nIkigai is found at the intersection of 4 things:\n1. What you LOVE ❤️\n2. What you are GOOD AT 🛠️\n3. What the world NEEDS 🌍\n4. What you can be PAID FOR 💰\n\nFinding the sweet spot between these four is the recipe for a long, fulfilled life.",
      highlight: "Ikigai is the perfect balance of passion, mission, vocation, and profession. ⚖️",
    },
    {
      id: 'the_hero_journey',
      title: 'The Hero\'s Journey 🗡️',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🗡️',
      svgIcon: 'zap',
      content: "Why do we love movies like Star Wars or Harry Potter? Because they follow **The Hero's Journey**, a mythological structure discovered by Joseph Campbell. 🌌\n\nEvery great story maps to human psychology: The hero is called to adventure, faces a terrifying abyss, learns a lesson, and returns transformed. \n\nWe love these stories because this is how our brains make sense of our own lives. Seeing your own struggles as 'The Abyss' turns meaningless pain into a meaningful quest! 🛡️",
      highlight: "You are the protagonist of your own life. Frame your struggles as a quest, not a curse. 🧗‍♂️",
    },
    {
      id: 'intrinsic_goals',
      title: 'Intrinsic vs Extrinsic Goals 🎯',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🎯',
      svgIcon: 'eye',
      content: "Psychology divides our life goals into two categories:\n\n• **Extrinsic Goals:** Wealth, Fame, and Beauty. (Driven by ego and external validation). 💵\n• **Intrinsic Goals:** Personal growth, deep relationships, and helping the community. (Driven by internal values). 🌱\n\nStudies show that people who achieve their Extrinsic goals often become *more* depressed, because they realize the 'prize' didn't fix them. People who chase Intrinsic goals report massive boosts in lifelong joy! 📈",
      highlight: "Chasing fame is chasing a mirage. Chasing growth is planting a garden. 🌳",
    },
    {
      id: 'logotherapy',
      title: 'Logotherapy: Healing through Meaning 🗣️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🗣️',
      svgIcon: 'brain',
      content: "Developed by Viktor Frankl, **Logotherapy** is a form of psychotherapy that focuses on the future, rather than the past. \n\nInstead of asking 'Why am I depressed?' (looking backward), Logotherapy asks 'What is life asking of me right now?' (looking forward) 🧭.\n\nAccording to Logotherapy, meaning can be found in three ways:\n1. By creating a work or doing a deed. 🔨\n2. By experiencing something or encountering someone (Love). ❤️\n3. By the attitude we take toward unavoidable suffering. 🛡️",
      highlight: "You cannot always choose your situation, but you ALWAYS choose your attitude. 🧠",
    },
    {
      id: 'nietzsche_abyss',
      title: 'Nietzsche and the Abyss 🕳️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🕳️',
      svgIcon: 'alert',
      content: "Philosopher Friedrich Nietzsche declared 'God is dead'—not as a victory, but as a warning. He feared that without traditional religion, society would fall into **Nihilism** (the belief that life is completely meaningless). 🌪️\n\nTo survive the 'Abyss' of a meaningless universe, he said we must become the *Übermensch* (Overman). This means taking the terrifying ultimate responsibility of creating your OWN meaning, rather than waiting for society or the universe to hand it to you. ⚡",
      highlight: "Meaning is not something you 'find' under a rock. It is something you actively 'forge'. ⚒️",
    },
    {
      id: 'biology_of_purpose',
      title: 'The Biology of Purpose 🧬',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧬',
      svgIcon: 'shield',
      content: "Purpose isn't just poetry; it's biology. \n\nResearch from the field of Psychoneuroimmunology shows that people who score high in 'Life Purpose' have lower levels of inflammatory markers (like Cortisol) and higher counts of natural killer (NK) immune cells. 🩸\n\nHaving a biological reason to wake up literally orders your cells to stay healthy and fight off disease! A meaningful life adds up to 7 years to your lifespan! ⏳",
      highlight: "Your immune system listens to your mind. A purposeful mind builds a resilient body. 🛡️",
    },
    {
      id: 'memento_mori',
      title: 'Memento Mori: Remember Death 💀',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '💀',
      svgIcon: 'moon',
      content: "The Stoics practiced **Memento Mori**—the daily meditation on one's own death. \n\nThis isn't meant to be depressing! By reminding yourself that you will die, the trivial annoyances of life (traffic, a rude comment) instantly lose their power. 🌬️\n\nDeath provides the ultimate deadline. It forces you to ask: 'If I only had one year left, would I spend it arguing on the internet, or would I finally write that book?' 📖",
      highlight: "A deadline makes the work happen. Death is the ultimate deadline for a good life. ⏳",
    },
    {
      id: 'legacy_generativity',
      title: 'Generativity: Leaving a Legacy 🌱',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🌱',
      svgIcon: 'users',
      content: "Psychologist Erik Erikson stated that in our adult years, we face the conflict of **Generativity vs. Stagnation**.\n\nGenerativity means making your mark on the world through creating or nurturing things that will outlast you (raising children, planting trees, mentoring the next generation) 🌳.\n\nStagnation is becoming self-absorbed and failing to contribute. True meaning is almost always found in planting seeds for a harvest you will never get to see. 🌻",
      highlight: "A society grows great when old men plant trees whose shade they know they shall never sit in. 🌳",
    },
    {
      id: 'the_absurd',
      title: 'Camus and The Absurd 🎭',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🎭',
      svgIcon: 'waves',
      content: "Albert Camus wrote about 'The Absurd'—the conflict between the human desire for meaning and the silent, meaningless universe. 🌌\n\nHe used the myth of Sisyphus, a man condemned to push a boulder up a hill for eternity, only for it to roll back down. It is the ultimate meaningless task. \n\nBut Camus concluded: **'One must imagine Sisyphus happy.'** The very act of rebellion, of choosing to push the boulder with a smile despite the absurdity, is the ultimate victory of the human spirit! 🧗‍♂️",
      highlight: "Defy the silence of the universe by choosing joy in the struggle. 💥",
    },
    {
      id: 'existential_vacuum',
      title: 'The Existential Vacuum 🕳️',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🕳️',
      svgIcon: 'lock',
      content: "When people have enough money to live, but no purpose to live for, they fall into the **Existential Vacuum**. \n\nThis usually manifests as 'Sunday Neurosis'—that feeling of depression and emptiness that hits on a Sunday afternoon when the rush of the workweek stops. 🕰️\n\nNature abhors a vacuum. If you don't fill it with meaning, it will automatically fill itself with anxiety, boredom, and addiction. ⚠️",
      highlight: "Boredom is the mind's alarm system telling you that your life lacks purpose. 🚨",
    },
    {
      id: 'wu_wei',
      title: 'Wu Wei: Effortless Action 🌊',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🌊',
      svgIcon: 'refresh',
      content: "In Daoism, there is the concept of **Wu Wei** (Non-doing or Effortless Action).\n\nSometimes, chasing meaning too desperately drives it away. Wu Wei teaches us to align with the natural flow of life, like a swimmer riding a current rather than fighting it 🏊‍♂️.\n\nYou cannot 'force' a plant to grow by pulling on its leaves; you provide water and sun, and it grows naturally. Let meaning emerge organically from good daily actions. 🌱",
      highlight: "Stop trying to force the river. Learn to navigate the current. 🛶",
    },
    {
      id: 'flow_and_mastery',
      title: 'Mastery and the Ego 🥋',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🥋',
      svgIcon: 'target',
      content: "Pursuing mastery in a skill (like martial arts, programming, or painting) provides profound meaning.\n\nWhy? Because mastery requires the suppression of the Ego. You have to admit you are bad at something for a long time to get good at it 📉.\n\nThe act of submitting yourself to a craft larger than yourself naturally provides a structured 'Path' (a Dao) through life, shielding you from existential dread. 🎨",
      highlight: "Mastery is the process of carving away your ego until only the art remains. 🗿",
    },
    {
      id: 'responsibility',
      title: 'The Weight of Responsibility 🏋️‍♂️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏋️‍♂️',
      svgIcon: 'link',
      content: "We often think we want ultimate freedom—no rules, no obligations. \n\nBut total freedom leads to paralysis (The Paradox of Choice). Psychology has found that humans actually crave **Responsibility**. 🧱\n\nTaking responsibility for a child, a business, or a community ties you to the world. It makes your actions matter. You willingly bear a heavy load, and in return, the load gives your life gravity and traction. 🌍",
      highlight: "The heaviest burden is having nothing to carry. 🛒",
    },
    {
      id: 'self_transcendence',
      title: 'Self-Transcendence 🌄',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🌄',
      svgIcon: 'star',
      content: "Maslow's Hierarchy of Needs originally ended with 'Self-Actualization' (reaching your own potential).\n\nHowever, right before he died, Maslow added a final, higher tier: **Self-Transcendence**. 🏔️\n\nThis is the realization that the ultimate meaning of life is devoting yourself to something *beyond* yourself. Whether it's an ideal, a scientific discovery, fighting for justice, or loving another person, true meaning is found in giving yourself away. 🤝",
      highlight: "You fully realize yourself only when you forget yourself in the service of others. ❤️",
    },
  ],

  lab: {
    title: "The Ikigai Engine ⚙️🏵️",
    description: "Align your life's GPS! You are presented with four sliders representing the core pillars of Ikigai: Passion ❤️, Mission 🌍, Vocation 🛠️, and Profession 💰. Adjust the balance to see how an excessive focus on one pillar creates emotional syndromes (like 'Wealthy but Empty' or 'Passionate but Starving'). Find the perfect center to ignite the 'Ikigai Reaction'! 🧬",
    hint: "If you max out 'What you can be paid for' and zero out the others, you'll experience extreme 'Sunday Neurosis' (Boredom & Emptiness). Balance is key!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Logotherapy resilience metrics, existential vacuum depth, and real-time biological immune marker simulations.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why volunteering has been linked to a longer lifespan? 🤝⏳",
      answer: "The 'Mother Teresa Effect'! Helping others reduces the stress hormone Cortisol and releases Oxytocin. Oxytocin literally repairs damage to blood vessels and lowers blood pressure. Acting selflessly is one of the best cardiovascular medicines known to science! ❤️",
      emoji: '🩺',
    },
    {
      id: 'dyk2',
      question: "Do you know why creating 'Art' (even if it's bad) is so good for you? 🎨",
      answer: "The feeling of 'Agency'! The modern world often makes us feel like cogs in a machine. Creating something—a drawing, a poem, a wooden chair—proves to your brain that you have the power to alter reality. It is a fundamental assertion of existence! 🛠️",
      emoji: '🖌️',
    },
    {
      id: 'dyk3',
      question: "Do you know why the saying goes 'Midlife Crisis' and not 'Twenties Crisis'? 🏎️",
      answer: "The Generativity Shift. In our 20s and 30s, we are driven by 'Accumulation' (getting a job, a house, a partner). Around 45, the accumulation phase naturally ends. If a person hasn't transitioned to 'Generativity' (giving back/mentoring), they hit an existential wall and panic (leading to buying a sports car)! 📉",
      emoji: '🧱',
    },
    {
      id: 'dyk4',
      question: "Do you know why philosophers advocate 'Amor Fati' (Love of Fate)? 🌪️",
      answer: "Because rejecting reality causes suffering! If something terrible happens, you can spend years angry that it happened (wishing the past was different). Amor Fati means accepting exactly what happened, embracing it, and deciding to build your meaning precisely *from* the ashes of that event. 🔥",
      emoji: '💪',
    },
    {
      id: 'dyk5',
      question: "Do you know why Sunday afternoons often feel depressing? 🕰️",
      answer: "The Existential Vacuum! During the week, your time is structured by work. When Sunday afternoon arrives and the chores are done, the structure vanishes. If you don't have deep meaning in your life, the silence of the afternoon forces you to face the emptiness. 🕳️",
      emoji: '🛋️',
    },
    {
      id: 'dyk6',
      question: "Do you know why 'Finding Yourself' is actually terrible advice? 🗺️",
      answer: "Because you aren't a hidden treasure buried under a rock! The concept of 'finding yourself' assumes your identity is static. In reality, you 'Create Yourself' through your actions and responsibilities. Meaning isn't found; it is forged by the hammer of daily habits! ⚒️",
      emoji: '🔥',
    },
    {
      id: 'dyk7',
      question: "Do you know why pain can sometimes feel good (like running a marathon)? 🏃‍♂️",
      answer: "Context! Pain without meaning is torture. Pain WITH meaning is a 'Challenge' or a 'Sacrifice.' When the brain believes pain is serving a higher purpose (like breaking a personal record), it releases Endorphins to support the effort, turning agony into triumph! 🏅",
      emoji: '🏔️',
    },
    {
      id: 'dyk8',
      question: "Do you know why the residents of Okinawa live so long? 🌅",
      answer: "Ikigai and 'Moai'. Alongside having a daily purpose (Ikigai), they form 'Moais'—lifelong social support groups of 5 friends committed to each other for life. This rock-solid social baseline completely eliminates chronic stress from their nervous systems! 🫂",
      emoji: '🗾',
    },
    {
      id: 'dyk9',
      question: "Do you know why we love underdog stories so much? 🐕🥊",
      answer: "Identification with the Struggle! We all feel oppressed by the difficulty of life. Watching Rocky Balboa get beaten down and keep standing up gives our own brain the psychological blueprint that 'We can survive the hits too.' It's vicarious resilience! 🥊",
      emoji: '🎬',
    },
    {
      id: 'dyk10',
      question: "Do you know why having total, unrestricted freedom can cause anxiety? 🗝️",
      answer: "The Paralysis of Infinite Choice. If you can do *anything*, choosing *one* thing means sacrificing infinite other possibilities. The human brain cannot compute infinity. We are much happier when we choose a specific constraint (like a marriage, a career, or a town) and build deeply within it! ⚓",
      emoji: '🚪',
    },
  ],

  quiz: [
    { id: 'q1', question: "Viktor Frankl wrote 'Man's Search for Meaning' after observing what makes humans survive:", options: ["A healthy diet", "Extreme personal wealth", "Finding a deep purpose", "Total social isolation"], answer: 2, explanation: "He observed this while surviving the unimaginable horrors of a concentration camp. 🏔️" },
    { id: 'q2', question: "What is the Japanese concept of 'Ikigai'?", options: ["A martial arts style", "A reason for living", "A traditional cooking method", "A morning sleep routine"], answer: 1, explanation: "It is the perfect intersection of passion, mission, vocation, and profession! 🌅" },
    { id: 'q3', question: "Which of the following is an 'Intrinsic' goal?", options: ["Gaining social media followers", "Buying a luxury car", "Building a deep friendship", "Becoming a company CEO"], answer: 2, explanation: "Intrinsic goals are internal and growth-focused, not driven by ego! 🌱" },
    { id: 'q4', question: "Nietzsche warned that without structure, society might fall into 'Nihilism'. What is Nihilism?", options: ["Belief in universal meaning", "Belief that life is meaningless", "Study of the Nile river", "A specific political party"], answer: 1, explanation: "Nihilism is the dangerous 'Abyss' of believing nothing matters. 🕳️" },
    { id: 'q5', question: "Having a strong 'Life Purpose' actually changes your biology by:", options: ["Boosting the immune system", "Increasing blood sugar levels", "Softening the bone structure", "Changing natural eye color"], answer: 0, explanation: "A purposeful mind commands a resilient, healthy body! 🧬" },
    { id: 'q6', question: "The Stoic practice of 'Memento Mori' means:", options: ["Remember the early morning", "Remember your own mortality", "Acquiring more financial wealth", "Honoring your mother's memory"], answer: 1, explanation: "Meditating on death provides the ultimate deadline to stop wasting your life! 💀" },
    { id: 'q7', question: "According to Erik Erikson, adults face the conflict of 'Generativity vs. Stagnation'. What is Generativity?", options: ["Generating electrical power", "Nurturing things that outlast you", "Staying in one location", "Accumulating personal wealth"], answer: 1, explanation: "It is the act of planting trees you will never sit under! 🌳" },
    { id: 'q8', question: "What did Albert Camus conclude about Sisyphus pushing the boulder?", options: ["He should give up", "He is constantly suffering", "He finds joy in struggle", "He needs better tools"], answer: 2, explanation: "Rebelling against meaninglessness by choosing joy is the ultimate victory! 🧗‍♂️" },
    { id: 'q9', question: "The 'Existential Vacuum' often manifests as:", options: ["High motivation on Mondays", "Feelings of weekend emptiness", "General fatigue on Tuesdays", "Common physical flu symptoms"], answer: 1, explanation: "When work stops, the lack of meaning becomes painfully obvious! 🛋️" },
    { id: 'q10', question: "Daoism teaches 'Wu Wei', which means:", options: ["Intense physical labor", "Taking effortless action", "Winning military battles", "Sleeping very deeply"], answer: 1, explanation: "Stop forcing the river; learn to ride its current! 🌊" },
    { id: 'q11', question: "Why does total unrestricted freedom often cause anxiety?", options: ["Freedom is strictly illegal", "It causes choice paralysis", "Lack of entertainment options", "Running out of oxygen"], answer: 1, explanation: "Infinite options short-circuit the brain. We need some boundaries to build deeply! ⚓" },
    { id: 'q12', question: "Maslow added a final tier to his hierarchy right before he died. What was it?", options: ["Reaching self-actualization", "Accumulating great wealth", "Serving something beyond yourself", "Achieving global fame"], answer: 2, explanation: "The highest state of human existence is giving yourself away to a cause! 🌄" },
    { id: 'q13', question: "Logotherapy, designed by Viktor Frankl, primarily focuses on:", options: ["Fixing past mistakes", "Comparing oneself to peers", "Focusing on future responsibilities", "Taking psychiatric medication"], answer: 2, explanation: "It asks: 'What does life need from you right now?' 🧭" },
    { id: 'q14', question: "Why is 'Finding Yourself' considered a flawed psychological concept?", options: ["Humans are too small", "Identity must be created", "Navigation tools are expensive", "People rarely get lost"], answer: 1, explanation: "You are not a hidden treasure; you are the blacksmith at the forge! ⚒️" },
    { id: 'q15', question: "What is 'Amor Fati'?", options: ["Embracing whatever happens", "A love of food", "Hating one's destiny", "A fear of spiders"], answer: 0, explanation: "Embracing your struggles allows you to use them as fuel! 🔥" },
    { id: 'q16', question: "Why does the human brain love 'The Hero\'s Journey' (like Star Wars)?", options: ["Interest in space travel", "The need for transformation", "Enjoyment of loud noises", "The story is short"], answer: 1, explanation: "We frame our own struggles as a heroic quest to give them meaning! 🗡️" },
    { id: 'q17', question: "What happens when you achieve 'Extrinsic' goals (like buying a massive mansion)?", options: ["Experiencing eternal joy", "Adapting without feeling fulfilled", "Developing a physical glow", "Stopping the aging process"], answer: 1, explanation: "The Hedonic Treadmill guarantees that external prizes fade quickly! 🏆" },
    { id: 'q18', question: "The 'Mother Teresa Effect' refers to:", options: ["Living in South Asia", "Health benefits from helping", "Walking without shoes", "Raising financial donations"], answer: 1, explanation: "Selflessness is actually biologically self-serving! ❤️" },
    { id: 'q19', question: "What does 'Mastery' of a skill require you to suppress?", options: ["Your natural breathing", "Your personal ego", "Your bank account", "Your physical eyesight"], answer: 1, explanation: "To get good, you must accept being bad for a very long time! 📉" },
    { id: 'q20', question: "A life devoid of responsibility usually feels:", options: ["A perfect existence", "Meaningless and anxious", "A permanent vacation", "A very busy schedule"], answer: 1, explanation: "We crave the 'traction' that carrying a heavy load provides! 🏋️‍♂️" },
  ],

  relatedTopics: ['happiness_science', 'cognitive_biases', 'emotions_motivation'],
};
