export default {
  id: 'ai_machine_learning',
  title: 'AI & Machine Learning',
  subtitle: 'Teaching silicon to think like humans 🧠',
  emoji: '🤖',
  category: 'Technology',
  accentKey: 'cyber', // Using a cyber/neon tone

  hook: {
    question: "Did you know the AI algorithm that recommends your next TikTok video operates using the exact same core mathematics as the AI that drives a Tesla autonomously down a highway? 🚗",
    reveal: "It's entirely true! At their absolute core, both of these massive multi-billion dollar systems are simply 'Neural Networks'. They don't 'know' what a video or a car is. They just aggressively multiply millions of numbers through a mathematical web until the numbers eventually output the 'correct' decision! 🤯",
    emoji: '📈',
  },

  theory: [
    { id: '1', title: 'What actually IS Artificial Intelligence?', color: '#00D4FF', bgGradient: ['#002A35', '#050A0F'], icon: '🤖', svgIcon: 'cpu', content: "Artificial Intelligence (AI) isn't magic, and it's not a human brain in a box. It is purely the science of mathematically programming computers to aggressively recognize **deep patterns** and actively make decisions without being explicitly step-by-step programmed for that exact specific scenario.", highlight: "Traditional Coding: 'If X happens, do exactly Y.' \nAI Coding: 'Here are 10,000 examples of X. Figure out how to predict Y yourself.' 🎯" },
    { id: '2', title: 'Machine Learning (ML)', color: '#39FF14', bgGradient: ['#0A200A', '#050A0F'], icon: '📈', svgIcon: 'grid', content: "**Machine Learning** is the massive sub-field of AI where we literally stop trying to write the rules. Instead, we aggressively feed the computer colossal amounts of raw Data (like 50,000 pictures of cats). \n\nThe algorithm continuously guesses, fails, mathematically scores its own failure, and subtly adjusts its internal math until it stops failing!", highlight: "Machine Learning is exactly like learning to ride a bike! You aren't given a math equation to balance; you just fall over 50 times until your brain silently learns the pattern. 🚴" },
    { id: '3', title: 'The Artificial Neuron', color: '#FFD166', bgGradient: ['#2A2A00', '#050A0F'], icon: '🔌', svgIcon: 'link', content: "Inside the human brain, biological neurons fire electricity. In AI, an **Artificial Neuron (Node)** is just a tiny, simple math function. \n\nIt takes multiple numerical inputs, multiplies each by a specific **Weight**, adds a **Bias** number, and spits out a final number. Alone, one neuron is completely stupid. But link 10 million of them together, and they can paint the Mona Lisa!", highlight: "A single piece of digital math is dumb. Millions working exactly in mathematical sync create an illusion of profound intelligence! 🧠" },
    { id: '4', title: 'Weights and Biases', color: '#FF3131', bgGradient: ['#200A0A', '#050A0F'], icon: '⚖️', svgIcon: 'target', content: "When an AI 'learns', what is actually happening physically? \n\nEvery connection between neurons has a **Weight** (how important that connection is) and a **Bias** (an aggressive baseline adjustment). When AI trains, it is quite literally just slowly tweaking these decimal numbers slightly up or down to get a better result next time.", highlight: "If an AI misidentifies a dog as a cat, the algorithm harshly punishes the network, forcing the mathematical 'Weights' to shift so it doesn't make that exact mistake twice. 📉" },
    { id: '5', title: 'Neural Networks (Deep Learning)', color: '#A855F7', bgGradient: ['#1A0A2A', '#050A0F'], icon: '🕸️', svgIcon: 'pulse', content: "When you aggressively stack thousands of artificial neurons into deep physical massive 'Layers', you create a **Neural Network**! \n\nThe first layer might just look at raw pixels. The second layer recognizes 'edges'. The third recognizes 'circles'. By the fierce 50th layer, the network fully recognizes 'A Golden Retriever's face'!", highlight: "We call it 'Deep' Learning exclusively because the vast mathematical network has incredibly 'deep' hidden layers buried in the middle doing the complex heavy lifting! 🏗️" },
    { id: '6', title: 'Training Data & Garbage In, Garbage Out', color: '#FF4D6D', bgGradient: ['#2A0A1A', '#050A0F'], icon: '🗑️', svgIcon: 'cube', content: "An AI is rigorously only as smart as the data it heavily consumes. \n\nIf you train a medical AI aggressively exclusively on photographs of young people, it will critically fail to diagnose skin conditions on older people. This is heavily known in computer science as **GIGO** (Garbage In, Garbage Out). Data bias is immensely mathematically dangerous!", highlight: "If you aggressively feed an AI pure toxic, biased, or bad data, it will absolutely perfectly learn how to be brilliantly toxic and biased! ⚠️" },
    { id: '7', title: 'Generative AI & LLMs (Like ChatGPT)', color: '#00D4A0', bgGradient: ['#00201A', '#050A0F'], icon: '✍️', svgIcon: 'sparkle', content: "Large Language Models (LLMs) like ChatGPT don't actually \"understand\" English! \n\nThey have aggressively read massively over 500 Billion words from the entire internet. When you ask it a question, it is purely using colossal statistics to aggressively calculate what the mathematically highest-probability *next word* should be in the sentence!", highlight: "It is essentially an unimaginably powerful version of the 'Auto-Complete' tool on your phone's keyboard! 📱" },
    { id: '8', title: 'The Black Box Problem', color: '#6C5CE7', bgGradient: ['#100A20', '#050A0F'], icon: '📦', svgIcon: 'lock', content: "Modern Deep Learning networks have billions of mathematically tangled weights. \n\nThis creates a terrifying **Black Box**. When a banking AI radically denies your mortgage loan, sometimes even the top software engineers who physically built the AI cannot specifically explain exactly mathematically *why* it made that exact decision! The math is too dense for human brains.", highlight: "We know HOW the AI learns, but we mathematically cannot trace the exact path of a single thought inside a trillion-parameter network! 🕵️" },
    { id: '9', title: 'Overfitting', color: '#FFB347', bgGradient: ['#201000', '#050A0F'], icon: '🎯', svgIcon: 'waves', content: "If you aggressively train an AI too intensely on the exact same dataset, it commits **Overfitting**.\n\nImagine a student memorizing exactly the answers to the practice math test (A, B, C, D) but profoundly failing to learn the actual math formulas. When the real test arrives, they completely fail. The AI literally perfectly memorizes the training data but fails completely in the real world!", highlight: "The AI stops learning the 'concept' and just lazily memorizes the exact specific inputs you gave it. 📝" },
    { id: '10', title: 'The Turing Test', color: '#55EFC4', bgGradient: ['#0A2010', '#050A0F'], icon: '🗣️', svgIcon: 'planet', content: "In 1950, genius Alan Turing proposed the ultimate test of true AI: \n\nIf a human judge aggressively texts back-and-forth blindly with a computer and a real human, and strictly cannot tell which one is the actual machine, the machine has successfully passed the **Turing Test** of artificial intelligence!", highlight: "Modern LLMs pass the Turing Test effortlessly every single day. The new challenge is figuring out if they are truly 'thinking' or just brilliant mimics. 🎭" }
  ],

  lab: {
    title: "Gradient Descent Engine 🧠",
    description: "Welcome to the Perceptron Training Matrix. You must violently adjust the neural weights to mathematically divide the Blue dataset from the Red dataset. Can you train the model?",
    hint: "Use the sliders to manually push the physical decision boundary line. If you get stuck, hit the 'Train Network' button to watch the AI's Gradient Descent auto-solve the math!",
    scientistModeHint: "Scientist Mode rigorously reveals the Sigmoid Activation Function and live Neural Loss (MSE) calculations updates.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why AI struggles so aggressively to draw human hands accurately? ✋", answer: "Hands are terrifyingly complex! They have extreme flexibility, overlapping fingers, and countless unique poses. In the millions of training images, hands drastically look entirely different every time (clenched, waving, pointing). The AI mathematically hallucinates trying to average all those contradictory images together!", emoji: '🎨' },
    { id: 'dyk2', question: "Do you know why Google Maps can perfectly predict heavy traffic jams before you even leave home? 🗺️", answer: "It is using the live GPS velocity data of thousands of anonymous Android phones physically driving on that highway right now! The AI model wildly crunches millions of real-time speed numbers to instantly predict exactly where the bottleneck is forming.", emoji: '🚦' },
    { id: 'dyk3', question: "Do you know why Deepfakes are so incredibly mathematically realistic today? 🎭", answer: "They use severe GANs (Generative Adversarial Networks). Two AIs fight to the death! AI #1 violently tries to forge a fake video. AI #2 aggressively acts as the police, trying to detect the fake. They brutally compete millions of times until AI #1 gets so flawlessly good that even AI #2 cannot mathematically spot the fake anymore!", emoji: '⚔️' },
    { id: 'dyk4', question: "Do you know why simple CAPTCHAs asked you to 'Click all the Stoplights' for years? 🚦", answer: "You were literally working for free! Google aggressively used those millions of human clicks as highly-accurate, free training data to successfully teach their billion-dollar self-driving car AI algorithms exactly what crosswalks and stoplights look like!", emoji: '🛑' },
    { id: 'dyk5', question: "Do you know why 'AI Hallucinations' occur, where ChatGPT confidently lies to your face? 🤥", answer: "Because LLMs fundamentally do not have a concept of absolute 'Truth'. They only generate the most statistically probable next word. If the math aggressively suggests a fake historical fact sounds highly plausible and structurally correct, it will confidently output the lie flawlessly!", emoji: '🎲' }
  ],

  quiz: [
    { id: 'q1', question: "What fundamental concept heavily describes 'Machine Learning'?", options: ["Writing specific line-by-line instructions", "Finding patterns in large datasets", "Building physical robotic brains", "Teaching computers human emotions"], answer: 1, explanation: "Machine Learning is precisely about abandoning strict manual programming and letting the profound algorithms organically discover the heavy statistical patterns alone." },
    { id: 'q2', question: "A single Artificial Neuron completely relies on two specific mathematical numbers called:", options: ["Bytes and bits", "Pixels and frames", "Weights and biases", "Protons and electrons"], answer: 2, explanation: "Weights intensely multiply the input, and the Bias drastically shifts the final result. Tweak these, and the neuron 'learns'!" },
    { id: 'q3', question: "What does the powerful term 'GIGO' severely warn AI developers about?", options: ["Graphic In, Graphic Out", "Garbage In, Garbage Out", "Gravity Is Gravity Output", "Great Input, Good Output"], answer: 1, explanation: "If you furiously feed an AI brutally biased, flawed, or terrible data, its output will absolutely reflect that precise garbage flawlessly." },
    { id: 'q4', question: "Why is a massive Neural Network aggressively called 'Deep Learning'?", options: ["Computers buried deep underground", "Using complex philosophical logic", "Many layers of hidden neurons", "Highly classified mathematical formulas"], answer: 2, explanation: "The 'Depth' strictly refers to the sheer massive number of hidden mathematical layers the data violently passes through to reach an extremely complex final answer." },
    { id: 'q5', question: "If an AI drastically perfectly memorizes its training data but completely fails fundamentally on brand new real-world data, this absolute failure is called:", options: ["The model underfitting", "The data bootstrapping", "The model overfitting", "The AI hallucination"], answer: 2, explanation: "Overfitting fiercely means the AI lazily memorized the answers to the exact test rather than truly learning the deep foundational concept." },
    { id: 'q6', question: "Large Language Models (LLMs) like ChatGPT generate highly human-like text purely by:", options: ["Understanding the sentence's meaning", "Searching a massive dictionary", "Predicting the next likely word", "Using a hidden human operator"], answer: 2, explanation: "It is an incredibly complex auto-complete. It heavily relies on profound statistics to forcefully guess the next highest-probability word!" },
    { id: 'q7', question: "The terrifying 'Black Box' problem in modern AI heavily refers to:", options: ["Hardware overheating and failing", "Hidden logic behind AI decisions", "Hackers stealing training data", "AI refusing to provide answers"], answer: 1, explanation: "Because there are billions of wildly entangled weights, mathematically tracing exactly why an AI aggressively rejected a specific prompt is almost physically impossible." },
    { id: 'q8', question: "The famous 1950 test designed to definitively determine if a computer can successfully trick a human into believing it is genuinely alive is:", options: ["The Turing Test", "The Einstein Theorem", "The Asimov Benchmark", "The Matrix Protocol"], answer: 0, explanation: "Alan Turing aggressively proposed that if you physically cannot tell the difference between the machine and a human through pure text, it essentially possesses AI." },
    { id: 'q9', question: "How do extremely powerful Generative Adversarial Networks (GANs) brilliantly create flawless deepfakes?", options: ["Stealing clips from the internet", "Competing networks creating and detecting", "Using automated Photoshop scripts", "Manual painting by human artists"], answer: 1, explanation: "By forcing two entirely distinct AIs into heavy gladiatorial mathematical combat, the 'Generator' AI becomes flawlessly hyper-realistic." },
    { id: 'q10', question: "When an AI confidently perfectly outputs a completely mathematically fake, fabricated piece of information, it is heavily known as:", options: ["A system glitch", "A kernel panic", "A hallucination", "A memory leak"], answer: 2, explanation: "A Hallucination aggressively happens when the AI's complex statistics confidently link the completely wrong distinct words together into what absolutely falsely sounds like a perfectly legitimate fact." },
    { id: 'q11', question: "What critically highly valuable resource powers absolute modern Machine Learning more than absolutely anything else?", options: ["Rare gold metal bars", "Massive volumes of data", "Radioactive plutonium fuel rods", "Pure silicon crystal wafers"], answer: 1, explanation: "Without incredibly massive oceans of clean, raw data, the brilliant deep AI algorithms are absolutely rendered totally completely thoroughly useless." },
    { id: 'q12', question: "If an AI fiercely strictly follows exact manual coded rules like 'If User = Admin, then Open Door', is it definitively Machine Learning?", options: ["Yes, it is machine learning", "No, it is traditional programming", "Only if the computer is fast", "Only if it uses Python"], answer: 1, explanation: "Machine Learning heavily absolutely requires the computer to aggressively dynamically adjust its own mathematical behavior entirely without strict explicit IF/THEN rules." },
    { id: 'q13', question: "Why do AI image generators terribly completely fail to accurately mathematically draw human hands?", options: ["AI models hate human hands", "Fingers contain toxic data", "Complex geometry in training data", "Clashing pixel color values"], answer: 2, explanation: "Our hands drastically fold into countless profound chaotic shapes. The AI tragically attempts to mathematically average out all of these wild contradictions, creating monstrous 7-fingered blobs." },
    { id: 'q14', question: "When a human heavily completes a CAPTCHA clicking exactly on 'all the bicycles', they are secretly:", options: ["Testing internet connection speed", "Providing free AI training data", "Hacking into a secure mainframe", "Running a deep virus scan"], answer: 1, explanation: "Google fiercely aggressively crowdsourced millions of hours of free human labor to flawlessly cleanly carefully label specific images for their powerful self-driving algorithms!" },
    { id: 'q15', question: "What acts as the primary absolute lifeblood completely fueling modern AI growth?", options: ["Clean drinking water", "Large organized datasets", "Stable electricity supply", "Pure silicon material"], answer: 1, explanation: "Without billions of points of raw pristine data, an AI completely starves and dies fundamentally." },
    { id: 'q16', question: "Inside deep neural networks, what exactly mathematically adjusts itself to learn from mistakes?", options: ["The computer RAM", "The weights and biases", "The CPU clock speed", "The hard drive storage"], answer: 1, explanation: "Weights and Biases physically shift up and down to change the mathematical output." },
    { id: 'q17', question: "What acts as the 'punishment' metric strictly telling the AI how wrong its last guess was?", options: ["The network router", "The loss function", "The security firewall", "The system BIOS"], answer: 1, explanation: "The Loss Function mathematically calculates the exact gap between the AI's bad guess and the correct answer." },
    { id: 'q18', question: "Which algorithm actively forces the neural network to adjust its weights by mathematical descending down the slope of the Loss curve?", options: ["Gradient Descent algorithm", "Bubble Sort algorithm", "Quicksort algorithm", "Binary Search algorithm"], answer: 0, explanation: "Gradient Descent is the physical engine of learning, mathematically rolling 'down a hill' until the error rate hits the bottom (zero)." },
    { id: 'q19', question: "A single Artificial Neuron's pure mathematical formula generally looks exactly like:", options: ["The formula E = mc²", "The formula y = mx + b", "The formula (Input × Weight) + Bias", "The formula a² + b² = c²"], answer: 2, explanation: "Every neuron individually just multiplies its input by its strict Weight and adds a Bias!" },
    { id: 'q20', question: "What prevents a neural network from just outputting linear identical numbers and allows it to map complex curved data (like images)?", options: ["The internal battery", "The activation function", "The hard drive", "The computer monitor"], answer: 1, explanation: "Activation Functions (like Sigmoid or ReLU) inject complex mathematical 'curves' (non-linearity) into the network!" }
  ],
  relatedTopics: ['digital_circuits', 'binary_computers'],
};
