const fs = require('fs');
const path = require('path');

const TOPICS_DIR = path.join(__dirname, '..', 'topics');
const TARGET_LANG = 'hi';
const DELAY_MS = 1500;

let translate;

async function initTranslator() {
  const mod = await import('google-translate-api-x');
  translate = mod.default || mod;
}

const delay = ms => new Promise(res => setTimeout(res, ms));

async function translateText(text, targetLang) {
  if (!text || typeof text !== 'string' || text.trim() === '') return text;
  if (text.length < 3) return text;
  if (/^[^\w\s]+$/.test(text)) return text;

  try {
    const result = await translate(text, { 
        to: targetLang,
        client: 'gtx',
        tld: 'co.in',
        fallbackBatch: false, 
    });
    return result.text || text;
  } catch (err) {
    console.error(`  ⚠️  Translation failed for: "${text.substring?.(0, 40) || 'batch'}..." → ${err.message}`);
    if (err.message.includes('Too Many Requests') || err.message.includes('429')) {
      console.log(`\n  ⚠️ Rate limit hit. Cooling down for 10s...`);
      await delay(10000);
    }
    return text;
  }
}

// ── Generate the config_hi.js file content ───────────────────────
function generateFileContent(config) {
  const json = JSON.stringify(config, null, 2);
  return `// ─────────────────────────────────────────────────────────
//  AUTO-GENERATED HINDI TRANSLATION
//  Generated by: scripts/translate.js
//  DO NOT EDIT MANUALLY — Re-run the script to regenerate.
// ─────────────────────────────────────────────────────────

export default ${json};
`;
}

// ── Load a config.js file ──────
function loadConfig(configPath) {
  let content = fs.readFileSync(configPath, 'utf-8');
  content = content.replace(/export\s+default\s+/, 'module.exports = ');
  const tempPath = configPath.replace('.js', '_temp.js');
  fs.writeFileSync(tempPath, content, 'utf-8');
  delete require.cache[require.resolve(tempPath)];
  const config = require(tempPath);
  fs.unlinkSync(tempPath);
  return config;
}

async function main() {
  console.log('Initializing translator...');
  await initTranslator();
  console.log('Done.');

  const topicDirs = fs.readdirSync(TOPICS_DIR).filter(d => fs.statSync(path.join(TOPICS_DIR, d)).isDirectory());

  let fixedCount = 0;

  for (const dir of topicDirs) {
    const configHiPath = path.join(TOPICS_DIR, dir, 'config_hi.js');
    if (!fs.existsSync(configHiPath)) continue;

    try {
      const configHi = loadConfig(configHiPath);
      let needsFix = false;

      if (configHi.doYouKnowWhy && Array.isArray(configHi.doYouKnowWhy)) {
        for (let i = 0; i < configHi.doYouKnowWhy.length; i++) {
          const dykw = configHi.doYouKnowWhy[i];
          if (dykw.answer && typeof dykw.answer === 'string') {
            // Check if it's mostly English (contains many a-z characters)
            const englishChars = dykw.answer.match(/[a-zA-Z]/g);
            if (englishChars && englishChars.length > 20) {
              needsFix = true;
              console.log(`Translating DYKW answer in topic: ${dir}`);
              let translated = await translateText(dykw.answer, TARGET_LANG);
              
              // Handle apostrophes in Hindi translation (prevents syntax errors)
              translated = translated.replace(/'/g, "\\'");
              
              configHi.doYouKnowWhy[i].answer = translated;
              await delay(DELAY_MS);
            }
          }
        }
      }

      if (needsFix) {
        const fileContent = generateFileContent(configHi);
        fs.writeFileSync(configHiPath, fileContent, 'utf-8');
        console.log(`✅ Fixed translations in: ${dir}`);
        fixedCount++;
      }
    } catch (err) {
      console.error(`❌ Failed processing ${dir}: ${err.message}`);
    }
  }

  console.log(`\n🎉 Finished! Fixed DYKW translations in ${fixedCount} topics.`);
}

main();
