// ─────────────────────────────────────────────────────────
//  TOPIC: STOICISM
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'stoicism',
  title: 'Stoicism',
  subtitle: 'The Art of Invincibility 🛡️🏛️',
  emoji: '🛡️',
  category: 'Philosophy',
  accentKey: 'stoicism',

  hook: {
    question: "Imagine losing all your money, being exiled from your country, and watching your reputation burn... and not feeling even an ounce of anxiety.",
    reveal: "This isn't a superpower; it is **Stoicism**. In the ancient world, from Roman Emperors to enslaved people, the Stoics figured out a psychological hack: You cannot control the world, but you have absolute dictator-level control over how you react to it. \n\nBy mastering the mind, they built internal fortresses that no tragedy, insult, or heartbreak could penetrate. Let's learn the operating system for mental invincibility. 🏛️🧠",
    emoji: '🏛️',
  },

  theory: [
    {
      id: 'what_is_stoicism',
      title: "What is Stoicism? 🗿",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'shield',
      svgIcon: 'lock',
      content: "Stoicism is an ancient Greek philosophy founded in Athens by Zeno of Citium around 300 BC.\nMost people think 'Stoic' means being an emotionless robot. This is false.\nStoicism isn't about *suppressing* emotions; it is about *domesticating* them. It is a practical toolkit for reducing negative emotions (anger, fear, grief) and maximizing positive ones (joy, peace, resilience).",
      highlight: "A Stoic feels emotions, but refuses to let the emotions drive the car. 🏎️",
    },
    {
      id: 'the_dichotomy_of_control',
      title: "The Dichotomy of Control ⚖️",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'sliders',
      svgIcon: 'target',
      content: "This is the core operating principle of Stoicism, taught by Epictetus.\nYou must ruthlessly divide the world into two lists:\n1. **Things you control:** Your thoughts, your actions, your choices.\n2. **Things you do NOT control:** The weather, the economy, traffic, other people's opinions of you, sickness, and death.",
      highlight: "If it's in your control, fix it. If it's not, let it go immediately. 🎈",
    },
    {
      id: 'the_big_three',
      title: "The Big Three 🤴👨‍🏫👔",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'users',
      svgIcon: 'star',
      content: "The three most famous Stoics came from wildly different lives:\n1. **Marcus Aurelius**: The Emperor of Rome. The most powerful man on Earth.\n2. **Epictetus**: A crippled Roman slave.\n3. **Seneca**: A mega-wealthy political advisor.\nThe fact that the Emperor and the Slave both used the exact same philosophy proves that Stoicism works regardless of your circumstances.",
      highlight: "Your external status does not determine your internal freedom. 🦅",
    },
    {
      id: 'it_is_not_events',
      title: "It's Not the Event 🧠",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'eye',
      svgIcon: 'eye',
      content: "*'People are not disturbed by things, but by the views they take of them.'* — Epictetus\nIf it rains on your wedding day, the rain isn't 'bad'. The rain is just water falling from the sky. Your *judgment* ('This ruined my day!') is what causes the suffering.\nEvents are 100% neutral. You apply the label 'good' or 'bad' to them.",
      highlight: "Suffering is not caused by reality. Suffering is caused by your interpretation of reality. 🎭",
    },
    {
      id: 'memento_mori',
      title: "Memento Mori 💀",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'lock',
      content: "**Memento Mori** means: *'Remember that you must die.'*\nStoics intentionally meditated on their own death daily. Why? Because when you remember that you could die today, you stop wasting time on petty arguments, scrolling on your phone, or caring about getting 'likes' on a post.\nDeath is the ultimate filter for what actually matters.",
      highlight: "You could leave life right now. Let that determine what you do and say and think. ⏳",
    },
    {
      id: 'amor_fati',
      title: "Amor Fati 🔥",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'heart',
      svgIcon: 'heart',
      content: "**Amor Fati** means: *'Love of Fate.'*\nThe Stoics (and later Nietzsche) believed you shouldn't just 'tolerate' bad luck—you should enthusiastically embrace it.\nGot fired? Great, time to reinvent myself. Stuck in traffic? Great, I can listen to an audiobook. A fire burns like a Stoic: whatever you throw into a fire simply turns into fuel for the fire.",
      highlight: "The obstacle is the way. (Marcus Aurelius) 🧱➡️🛣️",
    },
    {
      id: 'premeditatio_malorum',
      title: "Negative Visualization 🎬",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'video',
      svgIcon: 'eye',
      content: "**Premeditatio Malorum** (The Premeditation of Evils).\nStoics practiced imagining the absolute worst-case scenarios: losing their wealth, their loved ones, or their reputation.\nThis creates an 'anti-fragility' in the mind. First, it makes you violently grateful for what you currently have. Second, if disaster actually strikes, you are already mentally prepared for it.",
      highlight: "He who fears he will suffer, already suffers because of his fear. 👻",
    },
    {
      id: 'virtue_is_the_only_good',
      title: "Virtue is the Only Good 💎",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'award',
      svgIcon: 'target',
      content: "To a Stoic, money, health, and fame are 'Preferred Indifferents'. It's nice to have them, but they cannot make you a *good person*.\nThe only true good in the world is **Virtue** (Moral Excellence), broken into four pillars:\n1. Courage\n2. Temperance (Self-discipline)\n3. Justice\n4. Wisdom",
      highlight: "You can be poor, sick, and imprisoned, and still be a perfect human if you are virtuous. 🧘‍♂️",
    },
    {
      id: 'the_view_from_above',
      title: "Macromnesia (View from Above) 🦅",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'cloud',
      svgIcon: 'cloud',
      content: "When Marcus Aurelius felt overwhelmed by being Emperor, he would use a technique called the **View From Above**.\nHe would imagine his mind floating up out of his body, looking down at his palace, then his city, then the Roman Empire, then the whole Earth.\nSuddenly, his 'massive' political problems looked like tiny ants scurrying around. Perspective kills anxiety.",
      highlight: "Zoom out until your problems disappear. 🌍",
    },
    {
      id: 'internal_citadel',
      title: "The Inner Citadel 🏰",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'shield',
      svgIcon: 'lock',
      content: "The world is chaotic. People will lie to you, markets will crash, diseases will spread.\nThe Stoic builds an **Inner Citadel**—a fortress of the mind. No matter what madness is happening outside the walls, inside the fortress, there is total calm and rational control.\nYou cannot control the storm, but you can build a waterproof house.",
      highlight: "Nobody can force you to think a thought you don't want to think. You are sovereign. 👑",
    },
    {
      id: 'anger_management',
      title: "Seneca on Anger 🌋",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'alert-triangle',
      svgIcon: 'flame',
      content: "Seneca wrote an entire book on *Anger*. He believed anger is a temporary madness caused by having the wrong expectations.\nYou get angry in traffic because you *expected* the roads to be clear. If you expect people to be annoying, traffic to be slow, and coffee to spill, you won't get angry when it happens.",
      highlight: "Anger is the gap between your expectations and reality. Lower your expectations. 📉",
    },
    {
      id: 'time_management',
      title: "On the Shortness of Life ⏳",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'clock',
      svgIcon: 'zap',
      content: "Seneca noted: *'It is not that we have a short time to live, but that we waste a lot of it.'*\nPeople fiercely protect their money and property, but they let anyone steal their time (social media, gossip, annoying acquaintances). \nTime is the only non-renewable resource in the universe. Guard it like a dragon guards gold.",
      highlight: "You act like mortals in all that you fear, and like immortals in all that you desire. 🐉",
    },
    {
      id: 'journaling',
      title: "The Ultimate Life Hack: Journaling 📓",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'edit-3',
      svgIcon: 'eye',
      content: "The most famous Stoic book, *'Meditations'* by Marcus Aurelius, was never meant to be published. \nIt was literally his private diary. Every night, the most powerful man on Earth sat in his tent and wrote down his failures, analyzed his anger, and reminded himself to be better tomorrow.\nIf it worked for the Roman Emperor, it will work for you.",
      highlight: "Writing down your thoughts removes them from the chaotic loop of your brain. 🧠",
    },
    {
      id: 'sympatheia',
      title: "Sympatheia: The Cosmic Web 🕸️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'share-2',
      svgIcon: 'users',
      content: "Despite focusing on internal control, Stoics were not selfish. \nThey believed in **Sympatheia**—the idea that all humans are deeply interconnected parts of an intelligent universe. \nMarcus Aurelius said: *'What is bad for the hive is bad for the bee.'* We are made to work together like the upper and lower rows of teeth. To hate someone is to work against nature.",
      highlight: "We are all cells in the same cosmic body. 🩸",
    },
    {
      id: 'conclusion',
      title: "A Philosophy for Action ⚔️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'zap',
      svgIcon: 'zap',
      content: "Stoicism is not meant to be debated in a classroom. It is meant to be used on a battlefield, in a hospital waiting room, or during a brutal breakup.\nIt is the martial art of the mind. \nRead the texts, practice the Dichotomy of Control daily, and slowly watch yourself become invincible to the chaos of the world.",
      highlight: "Don't explain your philosophy. Embody it. (Epictetus) 🥋",
    },
  ],

  lab: {
    title: "The Citadel Sorter ⚖️🏰",
    description: "Welcome to the training grounds. A barrage of stressful events will be thrown at you. You must rapidly sort them into what is 'Within My Control' and what is 'Outside My Control'. If you try to control the uncontrollable, your anxiety will spike.",
    hint: "Rule of thumb: You only control your own thoughts, choices, and actions. Everything else (other people, the past, the weather) belongs outside the walls.",
    scientistModeHint: "Dichotomy Mode 🧑‍🔬: Epictetus states that confusing the two categories is the root cause of all human psychological suffering.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why is CBT (Cognitive Behavioral Therapy) directly based on Stoicism?", answer: "CBT, the gold standard of modern therapy, is essentially Stoicism in a lab coat. It operates on the core Stoic principle: Events don't cause negative emotions; your *beliefs* about the events do. By changing your internal narrative, you change your brain chemistry. 🧠", emoji: '🔬' },
    { id: 'dyk2', question: "Why did a crippled slave (Epictetus) and an Emperor (Marcus Aurelius) agree on philosophy?", answer: "Because power does not prevent suffering. Marcus faced plagues, betrayals, and endless wars. Epictetus faced torture and poverty. Stoicism proved that psychological resilience is universal and totally independent of your bank account or social status. 👑", emoji: '⛓️' },
    { id: 'dyk3', question: "Did the Stoics really think it was bad to feel 'sad'?", answer: "No. The Stoics recognized 'First Movements' (instinctive reactions). If someone scares you, you *will* flinch. If a dog dies, you *will* cry. That's biology. The Stoic goal is the 'Second Movement': actively choosing not to let that initial grief turn into long-term bitterness or despair. 💧", emoji: '🛡️' },
    { id: 'dyk4', question: "Why did Seneca say that 'Anger is a temporary madness'?", answer: "Because when you are angry, your prefrontal cortex (logic center) shuts down and your amygdala (animal brain) takes over. You literally lose your intelligence. Seneca noted that acting in anger always causes more damage than the thing that made you angry in the first place. 🌋", emoji: '📉' },
    { id: 'dyk5', question: "Why do Stoics stare at skulls or carry 'Memento Mori' coins?", answer: "Not to be morbid, but for perspective. When you are furious that a barista got your coffee order wrong, touching a coin that reminds you 'I am going to die soon' instantly vaporizes the petty anger. It forces you to spend your emotional energy only on things that actually matter. 💀", emoji: '🪙' },
  ],

  quiz: [
    { id: 'q1', question: "What is the core principle of Epictetus's 'Dichotomy of Control'?", options: ['Controlling other people', 'Dividing all things into what you can control (your thoughts/actions) and what you cannot (everything else)', 'Learning martial arts', 'Trying to control the weather'], answer: 1, explanation: "Focus 100% of your energy only on what you can control. ⚖️" },
    { id: 'q2', question: "What does the word 'Stoic' actually mean in the modern philosophical sense?", options: ['Being an emotionless robot', 'Repressing all your feelings', 'Someone who acknowledges emotions but does not let them dictate their actions; remaining calm under pressure', 'Someone who hates pleasure'], answer: 2, explanation: "Stoics feel emotions, they just refuse to be enslaved by them. 🛡️" },
    { id: 'q3', question: "According to Epictetus, what causes human suffering?", options: ['Bad luck', 'Other people', 'Not the events themselves, but our interpretation and judgments about those events', 'Lack of money'], answer: 2, explanation: "A traffic jam is just cars on a road. Your belief that 'traffic is unfair to me' causes the anger. 🧠" },
    { id: 'q4', question: "What is 'Memento Mori'?", options: ['A type of coffee', 'The practice of meditating on your own inevitable death to gain perspective and appreciate time', 'A Roman holiday', 'A battle formation'], answer: 1, explanation: "Remembering you will die prevents you from wasting time on petty things. 💀" },
    { id: 'q5', question: "What does 'Amor Fati' mean?", options: ['Love of Fate: enthusiastically embracing everything that happens to you, good or bad, as fuel for your growth', 'Love of family', 'Hatred of destiny', 'Blind luck'], answer: 0, explanation: "A fire burns everything thrown into it. 💥" },
    { id: 'q6', question: "Who was Marcus Aurelius?", options: ['A famous baker', 'A crippled slave who became a teacher', 'The Emperor of Rome and author of the private diary \'Meditations\'', 'A Greek god'], answer: 2, explanation: "The most powerful man on Earth was a practicing Stoic. 👑" },
    { id: 'q7', question: "What is 'Premeditatio Malorum' (Negative Visualization)?", options: ['A spell', 'Intentionally imagining the worst-case scenario (losing your job/family) so you are mentally prepared and deeply grateful for today', 'Being a pessimist who hates life', 'A punishment for slaves'], answer: 1, explanation: "It makes you 'anti-fragile' against disaster. 🎬" },
    { id: 'q8', question: "For a Stoic, what is the *only* true good in the universe?", options: ['Pleasure', 'Wealth', 'Fame', 'Virtue (Moral Excellence)'], answer: 3, explanation: "Money and health are nice, but they can't make you a 'good person'. 💎" },
    { id: 'q9', question: "What are the four pillars of Stoic Virtue?", options: ['Money, Power, Respect, Fear', 'Courage, Temperance (Discipline), Justice, Wisdom', 'Earth, Wind, Fire, Water', 'Past, Present, Future, Void'], answer: 1, explanation: "These four virtues guide every Stoic decision. 🏛️" },
    { id: 'q10', question: "What technique did Marcus Aurelius use to shrink his problems?", options: ['Drinking wine', 'The View from Above: zooming his perspective out to see the Earth from space, making his problems look like ants', 'Sleeping heavily', 'Shouting at walls'], answer: 1, explanation: "Zooming out fundamentally kills anxiety. 🦅" },
    { id: 'q11', question: "According to Seneca, what causes 'Anger'?", options: ['Bad people', 'Having the wrong expectations. (e.g. You expected life to be perfectly fair, and when it wasn\'t, your brain panicked)', 'Spicy food', 'Lack of sleep (only)'], answer: 1, explanation: "Anger is the gap between expectation and reality. Lower expectations. 🌋" },
    { id: 'q12', question: "What did Seneca say about Time?", options: ['Time is money', 'Life isn\'t too short, we just waste a massive amount of it on pointless things', 'Time travel is possible', 'We should sleep more'], answer: 1, explanation: "Guard your time like a dragon guards gold. ⏳" },
    { id: 'q13', question: "What is the 'Inner Citadel'?", options: ['A famous Roman fort', 'The impenetrable fortress of the mind. Even if the outside world is chaotic, your mind can remain calm and rational', 'A book by Epictetus', 'A type of meditation'], answer: 1, explanation: "You can't control the storm, but you can build a waterproof house. 🏰" },
    { id: 'q14', question: "Did the Stoics believe humans should isolate themselves from society?", options: ['Yes, people are annoying', 'No, they believed in \'Sympatheia\'—the idea that all humans are connected like parts of a body, and we must help each other', 'Yes, to protect their energy', 'They only liked philosophers'], answer: 1, explanation: "What is bad for the hive is bad for the bee. 🐝" },
    { id: 'q15', question: "Which ancient Stoic began his life as a crippled slave?", options: ['Seneca', 'Zeno', 'Epictetus', 'Marcus Aurelius'], answer: 2, explanation: "Despite being a slave, his mind was freer than most free men. ⛓️" },
    { id: 'q16', question: "How does modern CBT (Cognitive Behavioral Therapy) relate to Stoicism?", options: ['It doesn\'t', 'CBT is a direct descendant of Stoicism, using the idea that changing your \'story/judgement\' about an event changes your psychological reaction', 'CBT disproved Stoicism', 'CBT is physical therapy'], answer: 1, explanation: "Therapists literally prescribe Stoicism to cure anxiety. 🔬" },
    { id: 'q17', question: "What was the original purpose of Marcus Aurelius' famous book 'Meditations'?", options: ['To teach his son', 'To become famous', 'To write the laws of Rome', 'It was his private bedtime diary. He never intended for anyone else to read it'], answer: 3, explanation: "It is the ultimate proof of the power of journaling. 📓" },
    { id: 'q18', question: "How would a Stoic react to someone insulting them?", options: ['Punch them', 'Realize that the other person\'s opinion is \'outside their control\', and therefore ignore it completely', 'Cry privately', 'Insult them back louder'], answer: 1, explanation: "Nobody can insult you without your permission. 🚫" },
    { id: 'q19', question: "For a Stoic, wealth, health, and reputation are considered:", options: ['Evil', 'The ultimate goal', '\'Preferred Indifferents\'. It\'s fine to have them, but they are not required for a happy, virtuous life', 'Dangerous'], answer: 2, explanation: "They are nice bonuses, but totally unnecessary for a good life. 💰" },
    { id: 'q20', question: "Stoicism is best described as:", options: ['A religion', 'A theoretical debate framework', 'An operating system / practical toolkit for the mind meant to be used in the real, chaotic world', 'A political party'], answer: 2, explanation: "It is the martial art of the mind. 🥋" },
  ],

  relatedTopics: ['absurdism', 'nihilism', 'existentialism'],
};
