// ─────────────────────────────────────────────────────────
//  TOPIC: STUDY TIPS & MEMORY
//  Category: Personal Development
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'study_tips',
  title: 'Hacking Your Memory',
  subtitle: 'The neuroscience of learning faster 🧠⚡',
  emoji: '🧠',
  category: 'Personal Development',
  accentKey: 'study_tips',

  hook: {
    question: "Have you ever read an entire chapter of a textbook, closed the book, and realized you literally don't remember a single sentence? 📖👻",
    reveal: "You aren't broken, and you aren't stupid! Your brain is an extreme energy-saver. It aggressively deletes any information it considers 'useless for survival'. If you just passively drag your eyes over words, your brain tosses them in the trash instantly. To actually learn, you have to biologically trick your brain into believing that this information is a matter of life or death! 🧬🔥",
    emoji: '💭',
  },

  theory: [
    {
      id: 'forgetting_curve',
      title: "The Ebbinghaus Forgetting Curve 📉",
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '📉',
      svgIcon: 'chart',
      content: "In 1885, Hermann Ebbinghaus discovered a terrifying truth about human memory: **We forget roughly 50% of everything we learn within one hour.** 😱\n\nIf you attend a 1-hour lecture and don't review it, within a week your memory of it drops to nearly zero. The brain is like a leaky bucket; unless you actively plug the holes, the water (information) vanishes.\n\nMemories aren't static files saved on a hard drive; they are living neural pathways that physically decay if not used. 🕸️",
      highlight: "Unless you interrupt the forgetting process, your brain is programmed to delete what you learn. 🗑️",
    },
    {
      id: 'spaced_repetition',
      title: "Spaced Repetition ⏱️",
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '⏱️',
      svgIcon: 'target',
      content: "The ultimate memory hack is **Spaced Repetition**. Instead of cramming for 5 hours straight (which your brain immediately dumps), you review the material just as you are about to forget it. 📅\n\nReview intervals:\n• Day 1\n• Day 3\n• Day 7\n• Day 30\n\nEvery time you force your brain to recall the information right before it fades, the neural trace becomes physically thicker, covered in **myelin**, making the speed of recall lighting-fast and permanent! ⚡",
      highlight: "Cramming builds fragile short-term memories. Spaced repetition builds bulletproof long-term memories. 🛡️",
    },
    {
      id: 'illusion_of_competence',
      title: "The Illusion of Competence 🎭",
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🎭',
      svgIcon: 'eye',
      content: "Rereading your notes or highlighting text in neon colors feels incredibly productive. But it's a trap! 🚫\n\nThis is called **Passive Learning**. When you look at the textbook, your brain recognizes the words and says, 'Oh yeah, I know this.' But *recognition* is not *recall*.\n\nWhen you get to the exam and the book isn't there to trigger your recognition, your mind goes completely blank. You were suffering from the Illusion of Competence. 👻",
      highlight: "Highlighting a book is just coloring. It is not learning. 🖍️",
    },
    {
      id: 'active_recall',
      title: "Active Recall 🤔",
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🤔',
      svgIcon: 'zap',
      content: "If you want to actually learn, you must use **Active Recall**. This means closing the book, putting away your notes, and forcing your brain to retrieve the information from scratch. 🧠💥\n\nRetrieval is like going to the mental gym. Reading a textbook is just watching someone else lift weights. It feels difficult because it *is* difficult—you are literally forcing neurons to physically fire and wire together inside your skull. 💪",
      highlight: "Testing yourself is the strongest way to learn. Flashcards > Note-taking. 📇",
    },
    {
      id: 'feynman',
      title: "The Feynman Technique 👨‍🏫",
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '👨‍🏫',
      svgIcon: 'users',
      content: "Named after Nobel Prize-winning physicist Richard Feynman, this technique is ruthless in exposing your weak spots: \n\n**Explain the concept to a 5-year-old.** 🧒\n\nIf you can't explain it using simple, everyday language, you don't actually understand it. You just memorized complex vocabulary. \nWhen you attempt to teach it (even to a stuffed animal or an empty room), your brain instantly halts at the parts you don't truly grasp. 🧩",
      highlight: "Jargon hides ignorance. If you can't explain it simply, you don't understand it well enough. 🗣️",
    },
    {
      id: 'pomodoro',
      title: "The Pomodoro Technique 🍅",
      color: '#FF6B6B',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🍅',
      svgIcon: 'clock',
      content: "Focus is a biologically depleting resource, like stamina. Studying for 4 hours straight leads to diminishing returns and massive burnout. 📉\n\nInstead, use **Pomodoros** (named after a tomato-shaped kitchen timer):\n1️⃣ Pick a single task.\n2️⃣ Set a timer for 25 minutes of intense, unbroken focus.\n3️⃣ Take a 5-minute *complete* break (look away from screens!).\n\nThis pulses your brain, allowing for maximum intensity without the burnout crash. 🔄",
      highlight: "Sprint, rest, repeat. Don't try to run a mental marathon without water breaks. 🏃‍♂️💨",
    },
    {
      id: 'diffuse_mode',
      title: "Focused vs. Diffuse Thinking 🌌",
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🌌',
      svgIcon: 'planet',
      content: "Your brain operates in two distinct modes:\n**Focused Mode:** High concentration, like a tight flashlight beam. Used for math, logic, and intense reading. 🔦\n**Diffuse Mode:** Relaxed, wandering thought, like a wide lantern. Used for creativity, connecting ideas, and big-picture understanding. 🏮\n\nYou cannot be in both modes at once! When you get hopelessly stuck on a math problem, staring at it harder doesn't help. You need to switch to Diffuse mode by going for a walk. 🚶‍♂️",
      highlight: "The 'Aha!' moment always happens in Diffuse Mode! 💡",
    },
    {
      id: 'interleaving',
      title: "Interleaving: Mix It Up 🔀",
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🔀',
      svgIcon: 'refresh',
      content: "When studying, we usually do 'Blocked Practice' (e.g., doing 20 addition problems, then 20 subtraction problems). \n\n**Interleaving** is the process of mixing different types of problems together randomly (Addition, Subtraction, Multiplication). \n\nIt feels much harder, and you will make more mistakes, but studies show it dramatically improves your ability to choose the *correct strategy* during an exam, rather than just acting like a robot! 🤖",
      highlight: "Mixing up your study topics forces the brain to adapt instantly, creating deeper understanding. 🌪️",
    },
    {
      id: 'sleep_consolidation',
      title: "Sleep & Memory Consolidation 🛌",
      color: '#8A2BE2',
      bgGradient: ['#150020', '#050D0A'],
      icon: '🛌',
      svgIcon: 'cloud',
      content: "Pulling an all-nighter is the worst thing you can do for an exam. \n\nMemories acquired during the day are fragile and stored in the hippocampus. While you sleep—specifically during Deep Sleep and REM—your brain physically replays the day's experiences, moving them into the neocortex for permanent 'hard drive' storage. 💾\n\nWithout sleep, that data transfer never happens, and the memories are simply wiped away to make room for the next day. 🧹",
      highlight: "Sleep is not lost time; it is the physical act of learning. 🧠💤",
    },
    {
      id: 'parkinsons_law',
      title: "Parkinson's Law ⏳",
      color: '#FF8C00',
      bgGradient: ['#1A0C00', '#050D0A'],
      icon: '⏳',
      svgIcon: 'alert',
      content: "**'Work expands so as to fill the time available for its completion.'**\n\nIf you give yourself 3 weeks to write an essay, it will take 3 weeks of miserable, slow procrastination.\nIf you give yourself 3 hours to write that exact same essay, you will ruthlessly prioritize, focus intensely, and finish it in 3 hours. ⚡\n\nCreate artificial, aggressive deadlines to force your brain into a state of high-alert focus (flow state). 🎯",
      highlight: "Tight deadlines cure perfectionism and procrastination. ⏰",
    },
    {
      id: 'dual_coding',
      title: "Dual Coding Theory 🖼️+📝",
      color: '#00FA9A',
      bgGradient: ['#001A0D', '#050D0A'],
      icon: '🖼️',
      svgIcon: 'grid',
      content: "Our brains process visual information and verbal/textual information using completely different channels. \n\nIf you only read a text, you are only using one channel. **Dual Coding** means combining words with visuals (diagrams, timelines, mind maps, or doodles). \n\nBy engaging both the visual and verbal processing centers simultaneously, you create a double-strong neural pathway to the same memory! 🔗",
      highlight: "Always draw what you are studying. A terrible doodle is better than a perfect paragraph of text. 🖍️",
    },
    {
      id: 'state_dependent',
      title: "State-Dependent Memory 🌡️",
      color: '#1E90FF',
      bgGradient: ['#000D1A', '#050D0A'],
      icon: '🌡️',
      svgIcon: 'shield',
      content: "Memories are tied to the physical context and emotional state you were in when you learned them. \n\nIf you study while lying in your warm, comfortable bed, but take the exam sitting in a freezing cold, stressful classroom, your brain struggles to access the files! 🥶\n\nTo maximize recall, mimic the testing environment while you study: sit at a hard desk, keep the room quiet (no music), and time yourself. ⏱️",
      highlight: "Practice how you play. The exact physical environment matters. 🏟️",
    },
    {
      id: 'multitasking_penalty',
      title: "The Multitasking Penalty 🤹‍♂️",
      color: '#FF1493',
      bgGradient: ['#1A000D', '#050D0A'],
      icon: '🤹‍♂️',
      svgIcon: 'lock',
      content: "You cannot listen to a podcast, check TikTok, and study simultaneously.\n\nThe human brain is incapable of parallel processing complex tasks. Instead, it performs **Task-Switching**. Every time you glance at your phone, your brain violently drops the study context and loads the social media context. \n\nThis 'switch cost' drains cognitive energy, destroys focus, and decreases retention by up to 40%. Put the phone in another room! 📵",
      highlight: "Multitasking is just giving 20% of your attention to 5 different things and doing them all poorly. 📉",
    },
    {
      id: 'zeigarnik',
      title: "The Zeigarnik Effect 🧩",
      color: '#32CD32',
      bgGradient: ['#051A05', '#050D0A'],
      icon: '🧩',
      svgIcon: 'star',
      content: "Why do you remember the cliffhanger of a TV show so vividly, but immediately forget the plot of an episode that concluded nicely?\n\nRussian psychologist Bluma Zeigarnik noted that **human brains remember uncompleted or interrupted tasks better than completed ones.** \n\nYou can hack this! Stop your study session right *in the middle* of a fascinating topic or equation. Your brain will implicitly keep working on it in the background, itching to finish! 🏃‍♂️",
      highlight: "Leave things deliberately unfinished to keep your subconscious hooked. 🪝",
    },
    {
      id: 'nutrition_hydration',
      title: "Brain Fuel 💧🍇",
      color: '#00FFFF',
      bgGradient: ['#001A1A', '#050D0A'],
      icon: '💧',
      svgIcon: 'heart',
      content: "The brain is only 2% of your body weight but uses a massive 20% of your body's energy. It is a biological engine that needs premium fuel! 🏎️\n\nA 2% drop in hydration causes a noticeable drop in cognitive function and focus. Furthermore, heavy carbohydrate meals (like pizza) cause insulin spikes followed by crashes, making you incredibly sleepy. 🍕💤\n\nDrink water constantly and eat steady-burn foods (nuts, berries, protein) during intense study sessions.",
      highlight: "You can't run high-performance software on starved hardware. Drink water! 🚰",
    },
  ],

  lab: {
    title: "Neuro-Sync Simulator 🧠⚡",
    description: "You have 30 days before the Final Exam! Manage your 'Cognitive Load', 'Recall Strength', and 'Fatigue'. Will you use precise Spaced Repetition, or panic and Cram the night before? Watch the live neural pathways decay or strengthen based on your strategic choices!",
    hint: "Running 'Active Recall' increases fatigue massively, but creates permanent knowledge. 'Passive Reading' feels easy, but the knowledge evaporates in 24 hours. Don't let Fatigue hit 100% or you will Burn Out! 📉",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unveils raw Ebbinghaus $\\beta$-decay coefficients, Cortisol thresholds, and Synaptic Myelination variables in real-time.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why testing yourself works even when you get the answer wrong? ❌", answer: "The 'Hypercorrection Effect'! When you make a mistake and are immediately corrected, the brain experiences a tiny shock of surprise. This emotional jolt acts like superglue, making the *correct* answer stick in your memory far stronger than if you had just read it right the first time! 💡", emoji: '💥' },
    { id: 'dyk2', question: "Do you know why learning right before bed is a superpower? 🛌", answer: "During sleep, your brain consolidates the things you learned *most recently* and *most emotionally* first. By studying right before sleeping (and not scrolling TikTok afterward), you ensure that the study material is the highest priority item sent to the neocortex for permanent storage! 💾", emoji: '🌙' },
    { id: 'dyk3', question: "Do you know why highlighting text can actually LOWER your test scores? 🖍️", answer: "Highlighting draws your eyes to isolated keywords, causing you to lose the 'big picture' context connecting the concepts. Furthermore, it gives you a massive false sense of security (Illusion of Competence), causing you to study *less* because you feel you've 'handled it'. 🚫", emoji: '📉' },
    { id: 'dyk4', question: "Do you know why you should study in different rooms? 🚪", answer: "Contextual Variability! If you always study in the exact same chair, your memory becomes tied to that specific environment. If you vary your environment (a café, a library, the park), the brain is forced to divorce the information from the background context, making the memory robust and accessible *anywhere*. 🌍", emoji: '☕' },
    { id: 'dyk5', question: "Do you know why listening to music with lyrics ruins reading comprehension? 🎧", answer: "Your brain has a singular 'Phonological Loop' for processing language. When you read text, you use it. When you hear lyrics, you use it. The two streams aggressively collide, causing a cognitive traffic jam. If you must have music, use instrumental/lo-fi without lyrics! 🎹", emoji: '🎵' },
    { id: 'dyk6', question: "Do you know why exercise is the ultimate study drug? 🏃‍♀️", answer: "Cardio exercise triggers the release of BDNF (Brain-Derived Neurotrophic Factor), which neuroscientists call 'Miracle-Gro for the brain'. It literally stimulates the growth of new neurons in the hippocampus, expanding your hardware capacity for memory! 🧠✨", emoji: '🏋️‍♂️' },
    { id: 'dyk7', question: "Do you know why memory athletes build 'Palaces' in their minds? 🏰", answer: "Evolution prioritized spatial memory (remembering where food/predators are) over abstract symbols. By visualizing placing data (like playing cards) into physical rooms of a house you know well (The Method of Loci), you hijack millions of years of evolutionary hardware to memorize impossible amounts of data! 🗝️", emoji: '🏛️' },
    { id: 'dyk8', question: "Do you know why flashcards eventually stop working if you don't shuffle them? 🃏", answer: "Serial Position Effect. Your brain starts memorizing the *order* of the cards rather than the *answers*. You'll know 'Card B' comes after 'Card A', but you won't actually know the concept itself. Always shuffle! 🌪️", emoji: '🔀' },
    { id: 'dyk9', question: "Do you know why stress makes your mind go blank during an exam? 😰", answer: "High stress releases Cortisol, which triggers the 'Fight or Flight' amygdala response. This aggressively shuts down the prefrontal cortex (the logic/memory part of the brain) because in nature, you don't need logic to run from a tiger! Deep breathing tells the brain the tiger is gone, turning logic back on. 🐅", emoji: '🧘' },
    { id: 'dyk10', question: "Do you know why drinking caffeine late ruins tomorrow's study session? ☕", answer: "Caffeine has a half-life of 6 hours. If you drink a coffee at 4 PM, half of it is still in your brain at 10 PM, blocking adenosine receptors. This completely destroys your 'Slow Wave' deep sleep, meaning memory consolidation fails. You wake up effectively suffering from mild amnesia of yesterday! ❌", emoji: '📉' },
  ],

  quiz: [
    { id: 'q1', question: "What does the Ebbinghaus Forgetting Curve mathematically prove?", options: ['Memory is perfect if you are smart', 'We forget 50% of new learning within an hour if not reviewed', 'Learning happens in dreams', 'Repetition is unnecessary'], answer: 1, explanation: "Without active disruption, the brain aggressively prunes new memories almost immediately to save energy. 📉" },
    { id: 'q2', question: "Which technique is known as the 'ultimate memory hack' for permanent retention?", options: ['Cramming the night before', 'Passive rereading', 'Spaced Repetition', 'Listening to audiobooks while sleeping'], answer: 2, explanation: "Spaced Repetition forces recall at the exact moment you are about to forget, thickening the myelin sheath around the memory. ⏱️" },
    { id: 'q3', question: "Rereading a textbook makes you feel like you know the material, but you fail the test. This is:", options: ['The Zeigarnik Effect', 'The Illusion of Competence', 'Context-Dependent Memory', 'Dual Coding'], answer: 1, explanation: "Recognition (looking at an answer) is not the same as Recall (generating the answer from scratch). 🎭" },
    { id: 'q4', question: "Active Recall involves:", options: ['Closing the book and retrieving information from your brain', 'Highlighting the most active verbs in a sentence', 'Reading out loud', 'Drinking caffeine before studying'], answer: 0, explanation: "Testing yourself is the strongest method; it acts like a mental workout that physically strengthens synapses. 🏋️‍♂️" },
    { id: 'q5', question: "The Feynman Technique requires you to:", options: ['Use high-level scientific jargon', 'Explain the concept simply, as if to a 5-year-old', 'Draw a complex mind map', 'Study physics exclusively'], answer: 1, explanation: "Teaching a concept in simple terms exposes the gaps in your own understanding. Jargon hides ignorance! 🧒" },
    { id: 'q6', question: "A standard Pomodoro cycle consists of:", options: ['60 mins work, 0 breaks', '25 mins focused work, 5 mins break', '5 mins work, 25 mins break', 'Work until you fall asleep'], answer: 1, explanation: "The 25/5 rhythm prevents cognitive burnout while maximizing peak attention spans. 🍅" },
    { id: 'q7', question: "When you are stuck on a complex coding or math problem, what is the biological solution?", options: ['Stare harder at the screen', 'Take a walk to switch into Diffuse Mode', 'Drink more coffee to increase Focus Mode', 'Switch to a harder problem'], answer: 1, explanation: "Diffuse Mode allows the subconscious mind to make wide, creative connections you cannot make under tight focus. 🚶‍♂️" },
    { id: 'q8', question: "Interleaving your study sessions means:", options: ['Leaving the room every 10 minutes', 'Mixing different subjects or problem types together randomly', 'Studying under the bed covers', 'Only doing one type of problem for 5 hours'], answer: 1, explanation: "Mixing topics forces the brain to adapt and learn *when* to apply a strategy, not just how. 🔀" },
    { id: 'q9', question: "During which phase of sleep does the brain move facts to the permanent neocortex?", options: ['Stage 1 Light Sleep', 'Deep Sleep and REM', 'While falling asleep', 'Waking up'], answer: 1, explanation: "Memory consolidation primarily occurs during Deep (Slow Wave) and REM sleep. All-nighters destroy this process. 🛌" },
    { id: 'q10', question: "Parkinson's Law states that:", options: ['Gravity affects apples', 'Work expands to fill the time available', 'Older people learn slower', 'Brains shrink under stress'], answer: 1, explanation: "If you give yourself 3 weeks, it takes 3 weeks. If you artificially cut the deadline to 3 hours, you do it in 3 hours via hyper-focus! ⏳" },
    { id: 'q11', question: "Dual Coding Theory suggests you should combine:", options: ['Math and Science', 'Visuals (drawings) with Verbal (text)', 'Coffee and Tea', 'Two languages at once'], answer: 1, explanation: "Using two processing channels simultaneously builds double-strong neural anchors. 🖼️📝" },
    { id: 'q12', question: "State-Dependent Memory is why you should:", options: ['Only study in the state of California', 'Mimic the physical environment of an exam while studying', 'Drink alcohol to relax', 'Study in bed'], answer: 1, explanation: "Memory retrieval is heavily linked to the environmental and emotional state you were in when encoding it. 🪑" },
    { id: 'q13', question: "Why is 'Multitasking' while studying a biological myth?", options: ['Humans have only two hands', 'The brain can only rapidly switch tasks, burning energy via switch costs', 'Internet speeds are too slow', 'It\'s not a myth'], answer: 1, explanation: "The brain cannot parallel process complex thought. Dropping and loading contexts destroys focus and IQ. 🤹‍♂️" },
    { id: 'q14', question: "According to the Zeigarnik Effect, the brain remembers:", options: ['Numbers better than words', 'Completed tasks better than uncompleted tasks', 'Uncompleted or interrupted tasks better than completed ones', 'Faces better than names'], answer: 2, explanation: "Leaving a study session deliberately unfinished in the middle keeps your subconscious 'hooked' on solving it. 🧩" },
    { id: 'q15', question: "Even a 2% drop in hydration causes:", options: ['Blindness', 'A noticeable drop in cognitive function and focus', 'Hair loss', 'Memory erasure'], answer: 1, explanation: "The brain is extremely sensitive to biological fuel drops; stay hydrated! 💧" },
    { id: 'q16', question: "Why does the 'Hypercorrection Effect' make failures useful?", options: ['It doesn\'t', 'Getting an answer wrong and being corrected causes an emotional shock that superglues the correct memory', 'It punishes you', 'It makes you re-read the chapter'], answer: 1, explanation: "The shock of a mistake makes the brain highly plastic for a few seconds. ⚡" },
    { id: 'q17', question: "What is BDNF?", options: ['A tax form', 'Brain-Derived Neurotrophic Factor, released during exercise to grow new neurons', 'A type of caffeine', 'A bad chemical'], answer: 1, explanation: "Cardio exercise acts as 'Miracle-Gro' for your hippocampus, enhancing memory hardware. 🏃‍♂️" },
    { id: 'q18', question: "Memory athletes use the 'Method of Loci' (Memory Palaces) to hijack what evolutionary trait?", options: ['Flight response', 'Spatial memory for locations', 'Dietary tracking', 'Social gossip'], answer: 1, explanation: "We evolved to remember physical environments flawlessly to survive. Mapping abstract data to physical rooms makes them unforgettable! 🏛️" },
    { id: 'q19', question: "Why does extreme stress (cortisol) make your mind go blank?", options: ['It turns off the prefrontal cortex to prioritize the survival amygdala', 'It erases the hippocampus physically', 'It causes sleepiness', 'It drops blood pressure'], answer: 0, explanation: "Running from a tiger doesn't require complex calculus, so the brain shuts off logic centers. 🐅" },
    { id: 'q20', question: "Music WITH lyrics ruins study comprehension due to collisions in the:", options: ['Visual cortex', 'Phonological Loop', 'Motor cortex', 'Occipital lobe'], answer: 1, explanation: "Reading text and hearing words compete for the exact same auditory processing band in the brain. 🎵" },
  ],

  relatedTopics: ['brain_structure', 'memory_how_it_works', 'learning_behavior', 'social_media_trap'],
};
