// ─────────────────────────────────────────────────────────
//  TOPIC: FEAR (डर)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'fear',
  title: 'Fear',
  subtitle: 'The Biology of Survival & Terror 🦇🧠',
  emoji: '😱',
  category: 'Mental Health',
  accentKey: 'fear',

  hook: {
    question: "Why do we actively line up to pay money to be terrified in haunted houses and on roller-coasters, but freeze in terror when we have to speak in public?",
    reveal: "Because your brain knows the difference between 'Safe Fear' and 'Social Death'.\n\nFear is not a weakness; it is an ancient evolutionary software program designed to keep your ancestors from being eaten by lions. But in the modern world, without lions, this software turns inward. It makes us terrified of rejection, failure, and the unknown. Let's decode the biology of terror and learn how to use it rather than be used by it. 🦁🎢🧬",
    emoji: '🧬',
  },

  theory: [
    {
      id: 'biology_of_fear',
      title: "The Alarm Bell 🔔",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'bell',
      svgIcon: 'flame',
      content: "When you encounter a threat, sensory data travels to the **Amygdala** (the brain's alarm system) before it even reaches your visual cortex.\n\nYou react to a snake jump *before* you are even fully conscious that it is a snake. The amygdala floods your body with glutamate and adrenaline, hijacking your body to ensure survival at all costs.",
      highlight: "In a true fear state, your body reacts before your conscious mind even knows what is happening. ⚡",
    },
    {
      id: 'goosebumps_science',
      title: "Why Do We Get Goosebumps? 🥶",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'wind',
      svgIcon: 'snowflake',
      content: "When afraid, the tiny muscles at the base of your hair follicles contract, causing **goosebumps** (piloerection).\n\nWhy? Millions of years ago, when our ancestors were covered in fur, this made them puff up and look physically larger and more intimidating to predators (like a frightened cat). Today, we just get bumpy arms. It's an evolutionary ghost.",
      highlight: "Your fear response is a fossil from a time when you were covered in fur. 🐾",
    },
    {
      id: 'classical_conditioning',
      title: "How We Learn Fear (Little Albert) 👶🐶",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'link',
      svgIcon: 'target',
      content: "In 1920, John B. Watson conducted the controversial 'Little Albert' experiment. He showed a baby a white rat (no fear). Then, he banged a loud metal bar behind the baby whenever the rat appeared.\nSoon, the baby was terrified of the rat, and eventually, anything white and furry (like a Santa beard).\n**Classical Conditioning** means we 'pair' a neutral object with a traumatic event.",
      highlight: "Most of your fears are not natural; you learned them by association. 🧩",
    },
    {
      id: 'fear_extinction',
      title: "Unlearning Fear (Extinction) ✂️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'scissors',
      svgIcon: 'leaf',
      content: "If fear is learned, it can be unlearned. This is called **Fear Extinction**.\n\nIt requires the Prefrontal Cortex (the logical brain) to actively inhibit the Amygdala. You do this through repeated, safe exposure. If you fear dogs, you spend time with a friendly dog until the brain overwrites the old 'Dog = Danger' file with a new 'Dog = Safe' file.",
      highlight: "You don't delete the fear memory; you build a stronger, new 'safety' memory over it. 🏗️",
    },
    {
      id: 'phobias',
      title: "Phobias: The Irrational Terror 🕷️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'alert-triangle',
      svgIcon: 'lock',
      content: "A phobia is an intense, irrational fear of a specific trigger.\n• **Arachnophobia**: Fear of spiders.\n• **Claustrophobia**: Fear of enclosed spaces.\n• **Trypophobia**: Fear of clustered holes.\nMany phobias are evolutionary. We are genetically predisposed to fear snakes and heights because those things killed our ancestors. It's much harder to develop a phobia of cars, even though cars are deadlier today.",
      highlight: "Phobias are evolutionary survival traits that are firing at the wrong time in history. 🕰️",
    },
    {
      id: 'social_fear',
      title: "The Ultimate Fear: Rejection 👥",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'users',
      svgIcon: 'users',
      content: "For ancient humans, being rejected by the tribe meant starvation and death in the wilderness. \n\nThis is why public speaking (Glossophobia) often ranks as a greater fear than death itself. When you stand on a stage and people stare at you, your primitive brain interprets it as: 'They are judging me. If I fail, they will banish me, and I will die.'",
      highlight: "Shame and embarrassment physically register in the brain as a threat to survival. 🎭",
    },
    {
      id: 'safe_fear',
      title: "Horror Movies & Rollercoasters 🎢",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'film',
      svgIcon: 'heart',
      content: "Why do we love haunted houses?\nIt's called **Recreational Fear**. When you are on a rollercoaster, your amygdala screams 'DANGER!', flooding you with adrenaline and dopamine. \nBut a split-second later, your cortex whispers, 'You are strapped in. You are safe.' You get the biochemical high of survival without the actual risk of dying.",
      highlight: "Horror movies are a safe playground for the nervous system to practice feeling terror. 🍿",
    },
    {
      id: 'the_freeze_response',
      title: "Playing Dead (The Freeze Response) 🧊",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'pause-circle',
      svgIcon: 'snowflake',
      content: "We talk about 'Fight or Flight', but often forget **Freeze**.\nWhen a threat is overwhelming and you can't run or fight, the body paralyzes itself. Heart rate drops, and pain receptors dull (dissociation). \nLike a possum playing dead, it's a desperate biological attempt to make a predator lose interest or to minimize the pain of an attack.",
      highlight: "Freezing during a trauma is not 'weakness' or 'cowardice'. It is a hardwired survival instinct. 🛡️",
    },
    {
      id: 'fear_of_unknown',
      title: "Nyctophobia (Fear of the Dark) 🌑",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'eye',
      content: "We are not actually afraid of the dark; we are afraid of what is *in* the dark.\n\nHumans are highly visual creatures. When our primary sense (vision) is removed, the brain attempts to fill in the blanks using its worst-case scenario generator. The fear of the unknown is the ultimate master fear because the imagination is always scarier than reality.",
      highlight: "H.P. Lovecraft: 'The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.' 👁️",
    },
    {
      id: 'contagion',
      title: "Fear is Highly Contagious 🦠",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'share-2',
      svgIcon: 'activity',
      content: "Have you ever sneezed because someone else did? Fear works the same way.\nHumans emit chemosignals (pheromones) in their sweat when terrified. If you smell the sweat of a terrified person, your own amygdala activates. Panicking crowds are driven by this invisible, biological contagion. We are wired to catch fear from each other to survive as a group.",
      highlight: "Panic spreads faster than any virus on earth. 🏃‍♂️🏃‍♀️",
    },
    {
      id: 'turning_fear_to_excitement',
      title: "Fear vs. Excitement (Anxiety Reappraisal) 🎯",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'zap',
      svgIcon: 'star',
      content: "Biologically, Fear and Excitement are almost identical (racing heart, sweaty palms, high adrenaline). \n\nHarvard research shows that if you are nervous before a presentation, telling yourself 'I need to calm down' fails 90% of the time. Instead, saying out loud, **'I am excited!'** tricks the brain into interpreting the adrenaline as enthusiasm rather than terror.",
      highlight: "You cannot drop from 'High Panic' to 'Calm'. But you can pivot from 'Panic' to 'Excitement'. 🚀",
    },
    {
      id: 'courage_muscle',
      title: "Courage is a Muscle 💪",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'shield',
      svgIcon: 'lock',
      content: "Courage is not the absence of fear. Courage is the *management* of fear.\n\nNeuroplasticity proves that every time you face a fear, you literally thicken the neural pathways in your prefrontal cortex, making it stronger at overriding the amygdala in the future. The more you do what scares you safely, the braver you biologically become.",
      highlight: "Action breeds confidence. Inaction breeds fear. 🧱",
    },
    {
      id: 'media_fear_mongering',
      title: "The Media's Hacks 📺",
      color: '#673AB7',
      bgGradient: ['#1A0030', '#050010'],
      icon: 'tv',
      svgIcon: 'alert',
      content: "News outlets and politicians know how to hijack your amygdala.\nBy constantly displaying threats (crime, disease, war), they trigger your survival instinct, forcing you to keep watching them for 'safety updates'. \nWhen your brain is in fear mode, it cannot think critically. You become highly susceptible to manipulation and taking extreme actions.",
      highlight: "A frightened population is an easily controlled population. 📰",
    },
    {
      id: 'fear_of_failure',
      title: "Atychiphobia (Fear of Failure) 📉",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'trending-down',
      svgIcon: 'compass',
      content: "Many talented people paralyze themselves because they fear failing.\nBut failure is the core mechanism of human learning. Toddlers fall thousands of times before walking, but they don't feel 'shame'. As adults, we attach our self-worth to the outcome.\nThe cure is redefining failure from 'I am bad' to 'I am collecting data'.",
      highlight: "Perfect is the enemy of good. Do it badly, but do it. 🛠️",
    },
    {
      id: 'the_other_side',
      title: "What's on the Other Side? 🌅",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'sun',
      svgIcon: 'heart',
      content: "'Everything you've ever wanted is on the other side of fear.' - George Addair\n\nFear often acts as a compass. The thing that scares you the most (asking for a raise, expressing love, starting a business) is usually exactly what you need to do to grow. If it didn't matter to you, you wouldn't be afraid. Use the fear to point true north.",
      highlight: "Don't ask how to stop being afraid. Ask what is worth being afraid for. 🧭",
    },
  ],

  lab: {
    title: "Phobia Extinction Simulator 🕷️🛡️",
    description: "You (or your subject) have a severe phobia! Guide the Prefrontal Cortex to build 'Safety Memories' and overwrite the Amygdala's panic signals through progressive, safe exposure.",
    hint: "Start small. You cannot jump straight to holding a spider; start with looking at a cartoon picture of one!",
    scientistModeHint: "Behavioral Psych Mode 🧑‍🔬: Toggle active Glutamate tracking and classical conditioning pairing analysis.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do your pupils dilate when you are terrified?", answer: "Your eyes widen (pupils dilate) to let in maximum light so you can see threats more clearly, especially in the dark, and plan an escape route. The 'wide-eyed with terror' look is a biological light-gathering mechanism. 👀", emoji: '👁️' },
    { id: 'dyk2', question: "Why do we freeze like a deer in headlights?", answer: "Predators (like T-Rexes or lions) are incredibly sensitive to movement. Freezing is the brain's desperate attempt to say, 'I am a rock, ignore me!' It works brilliantly in the jungle, but terribly against an oncoming car. 🦌", emoji: '🧊' },
    { id: 'dyk3', question: "Why is 'stage fright' so common?", answer: "Standing elevated in front of a staring crowd triggers the ancient 'predator prey' instinct. A group of staring eyes usually meant a pack of wolves was assessing you for dinner. Public speaking is biologically interpreted as being hunted! 🐺", emoji: '🎤' },
    { id: 'dyk4', question: "Why does fear make our voices high and squeaky?", answer: "When adrenaline floods the system, muscles restrict and tighten, including your vocal cords. Tighter cords produce a higher-pitch frequency, which often comes out as a squeal or a squeaky voice during panic. 🗣️", emoji: '🐭' },
    { id: 'dyk5', question: "Why do some people love scary movies and others hate them?", answer: "It has to do with how quickly your brain clears dopamine. Sensation-seekers (thrill lovers) get a massive, lasting dopamine hit from surviving the 'scare' in a movie, making it feel like a reward. Others just feel the exhausting cortisol spike. 🍿", emoji: '🎢' },
  ],

  quiz: [
    { id: 'q1', question: "What is the primary function of the Amygdala?", options: ['Digesting food', 'Acting as the brain\'s alarm system to detect threats instantly', 'Storing childhood memories', 'Controlling breathing'], answer: 1, explanation: "It reacts to threats before your conscious mind even processes what is happening. 🚨" },
    { id: 'q2', question: "Why do humans get goosebumps when they are afraid?", options: ['To feel cold', 'It\'s an evolutionary reflex from when we had fur, intended to puff the fur out and make us look bigger to predators', 'To sweat more', 'Because of ghosts'], answer: 1, explanation: "Like a frightened cat puffing up its tail, we are trying to look intimidating. 🥶" },
    { id: 'q3', question: "What did the 'Little Albert' experiment demonstrate?", options: ['Babies love rats', 'Fears can be learned through Classical Conditioning (pairing a neutral object with a scary sound)', 'Babies are fearless', 'Rats are dangerous'], answer: 1, explanation: "Many of our modern fears are learned associations, not natural instincts. 👶" },
    { id: 'q4', question: "What is 'Fear Extinction'?", options: ['Killing spiders', 'The process of the logical brain overwriting a fear memory with a new \'safety\' memory through safe exposure', 'Forgetting the past', 'Taking medicine'], answer: 1, explanation: "You don't delete fear; you build a stronger safety learning on top of it. ✂️" },
    { id: 'q5', question: "Why are humans genetically predisposed to fear snakes and spiders?", options: ['Because they are ugly', 'These threats actively killed our ancestors, so survival instincts were passed down', 'Movies tell us to', 'They are fast'], answer: 1, explanation: "It is much harder to develop a phobia of cars or guns, because they are too new in our evolutionary history. 🐍" },
    { id: 'q6', question: "Why does public speaking cause terror for many people?", options: ['They hate talking', 'The primitive brain interprets a staring crowd as a pack of predators OR as a threat of social banishment (death in ancient times)', 'Voices hurt', 'The lights are bright'], answer: 1, explanation: "Social rejection used to be a literal death sentence. 👥" },
    { id: 'q7', question: "What is 'Recreational Fear'?", options: ['Fearing sports', 'Seeking out scary but safe experiences (like horror movies/rollercoasters) to get an adrenaline high without actual danger', 'Fear of parks', 'Being afraid of fun'], answer: 1, explanation: "The brain enjoys surviving a threat when it knows it is ultimately safe. 🎢" },
    { id: 'q8', question: "What is the biological purpose of the 'Freeze' response?", options: ['To take a nap', 'To avoid being noticed by predators that are highly sensitive to movement, or to numb the pain of an attack', 'To get cold', 'To confuse friends'], answer: 1, explanation: "Freezing is an involuntary, hardwired survival mechanism, not a sign of cowardice. 🧊" },
    { id: 'q9', question: "Why is the fear of the dark (Nyctophobia) so common?", options: ['The dark is evil', 'Without vision, the brain’s worst-case scenario generator takes over to protect us from unknown threats', 'Ghosts live in the dark', 'Bats'], answer: 1, explanation: "We aren't afraid of the dark; we are afraid of what is hidden in it. 🌑" },
    { id: 'q10', question: "How does the media use fear manipulation?", options: ['By telling jokes', 'By showing constant threats to trigger the amygdala, making viewers highly attentive and easy to influence', 'By lowering volume', 'By using bright colors'], answer: 1, explanation: "A frightened brain struggles to think critically and seeks safety from authority. 📺" },
    { id: 'q11', question: "What is a highly effective way to reframe performance anxiety (Harvard research)?", options: ['Telling yourself to calm down', 'Saying \'I am excited!\' to trick the brain into interpreting the adrenaline as enthusiasm', 'Holding your breath', 'Drinking milk'], answer: 1, explanation: "You can't jump from panic to calm easily, but you can pivot from panic to excitement since the biology is similar. 🎯" },
    { id: 'q12', question: "How is 'Courage' defined neuroscientifically?", options: ['Having no fear', 'The prefrontal cortex actively stepping in to manage and override the amygdala’s alarm signals', 'Big muscles', 'Yelling loudly'], answer: 1, explanation: "Courage is a brain muscle that thickens every time you use it. 💪" },
    { id: 'q13', question: "What causes fear to be 'contagious' in a crowd?", options: ['Eye contact', 'Humans emit chemosignals (pheromones) when terrified that directly trigger the amygdala in others nearby', 'Loud noises', 'Text messages'], answer: 1, explanation: "We are biologically wired to share panic to ensure the whole tribe survives a hidden threat. 🦠" },
    { id: 'q14', question: "Why do your pupils dilate when terrified?", options: ['To look cute', 'To let in maximum light so you can see the threat and escape routes more clearly', 'To cry', 'To hide'], answer: 1, explanation: "Wide eyes are a biological flashlight for the brain. 👀" },
    { id: 'q15', question: "What is Atychiphobia?", options: ['Fear of heights', 'Fear of failure, which often paralyzes people from trying new things', 'Fear of flying', 'Fear of spiders'], answer: 1, explanation: "We must redefine failure as 'collecting data' rather than an attack on self-worth. 📉" },
    { id: 'q16', question: "Are most phobias rational?", options: ['Yes, completely', 'No, they are intense, irrational fears where the alarm system goes off despite no actual life-threatening danger presently', 'Yes, they protect us daily', 'They are just preferences'], answer: 1, explanation: "The alarm is real, but the fire is an illusion. 🕷️" },
    { id: 'q17', question: "Why did the baby in the 'Little Albert' experiment become afraid of a Santa beard?", options: ['Santa is scary', 'Generalization: The brain started fearing anything that shared traits (white and furry) with the original conditioned fear (the rat)', 'The beard was fake', 'Loud noises'], answer: 1, explanation: "Fear easily spills over into similar-looking things to keep us 'extra' safe. 🎅" },
    { id: 'q18', question: "What is the biological reason our vocal cords squeak when scared?", options: ['We want to be quiet', 'Adrenaline causes muscles to tighten, including vocal cords, resulting in a higher pitch', 'We forget how to talk', 'Lungs shrink'], answer: 1, explanation: "Tension creates high frequency. 🗣️" },
    { id: 'q19', question: "How does exposure therapy work practically?", options: ['Throwing someone into a snake pit instantly', 'Gradual, safe, step-by-step exposure to the fear until the brain learns it is safe (e.g., looking at a photo first)', 'Sleeping a lot', 'Ignoring the fear'], answer: 1, explanation: "You must walk the brain slowly down the stairs, not push it off the cliff. 🪜" },
    { id: 'q20', question: "What does George Addair mean by 'Everything you've ever wanted is on the other side of fear'?", options: ['Fear is good', 'Fear often points exactly to what we need to do for personal growth; it acts as a compass', 'Run away from goals', 'Don\'t be afraid'], answer: 1, explanation: "If it didn't matter to your growth, you wouldn't care enough to be afraid. 🌅" },
  ],

  relatedTopics: ['anxiety', 'trauma', 'phobias'],
};
