export default {
  id: "momentum_collisions",
  title: "Momentum",
  subtitle: "The brutal rules of massive impacts 💥",
  emoji: "💥",
  category: "Physics",
  accentKey: "physics",

  hook: {
    question: "Why does a tiny 9-gram bullet absolutely violently obliterate a giant watermelon, but a 10-pound bowling ball completely bouncing off your foot just hurts a bit? 🍉",
    reveal: "The staggering power of Kinetic Energy and Momentum! A bullet is incredibly insanely furiously fast. Because kinetic energy mathematically squares the speed ($v^2$), a tiny bullet physically carries massively exponentially more violent chaotic energy than the slow, brutally heavy bowling ball! 🎳",
    emoji: "💥",
  },

  theory: [
    {
      id: "mom_0",
      title: "Momentum: Unstoppable Mass 🚂",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "🚂",
      svgIcon: "truck",
      content: "Momentum ($p = mv$) is strictly physically defined as Mass completely multiplied by Velocity. \n\nIf a massive freight train is moving at literally 1 mph, it still violently furiously possesses completely unstoppable momentum! You mathematically cannot just stop it by pushing on it, because its colossal mass guarantees absolute brutal physical dominance!",
      highlight: "Momentum dictates exactly how hard it is to forcefully fiercely stop a moving object from completely crushing you! 🛑",
    },
    {
      id: "mom_1",
      title: "Kinetic Energy: The Exploding Force 💥",
      color: "#FF3131",
      bgGradient: ["#200A0A", "#050D0A"],
      icon: "💥",
      svgIcon: "zap",
      content: "While Momentum rises linearly, **Kinetic Energy** ($KE = 1/2 mv^2$) completely violently squares the velocity! \n\nIf you simply mathematically double your driving speed, your physical destructive kinetic energy completely instantly quadruples! This is exactly why high-speed car crashes are entirely radically perfectly deadly compared to slow fender-benders.",
      highlight: "Speed is mathematically fundamentally radically perfectly deadlier than sheer mass! 🏎️",
    },
    {
      id: "mom_2",
      title: "Conservation of Momentum: The Cosmic Law ⚖️",
      color: "#FFD166",
      bgGradient: ["#2A2A00", "#050D0A"],
      icon: "⚖️",
      svgIcon: "shield",
      content: "The total momentum in a completely sealed, perfectly isolated system absolutely strictly can NEVER magically change! \n\nIf a fiercely fast billiard ball purely completely smashes directly into a totally stopped billiard ball, the total combined momentum before the intense physical crash is completely 100% exactly mathematically identical to the total combined momentum after the brutal crash! It is a flawless eternal cosmic rule!",
      highlight: "Even when entire violent stars rapidly aggressively collide, the massive math is completely absolutely perfectly balanced! 🌟",
    },
    {
      id: "mom_3",
      title: "Elastic Collisions: Flawless Bounces 🏀",
      color: "#39FF14",
      bgGradient: ["#0A200A", "#050D0A"],
      icon: "🏀",
      svgIcon: "target",
      content: "In a completely pure perfectly **Elastic Collision**, the objects furiously completely violently bounce off each other without totally strictly losing ANY kinetic energy to heat or physical sound! \n\nThey perfectly violently completely repel! This technically almost entirely only exists right at the absolute purely atomic level where perfect force fields fiercely force electrons to dramatically fiercely bounce back!",
      highlight: "Newton's Cradle aggressively actively beautifully strictly powerfully entirely demonstrates highly near-perfect elastic collisions! ⚪⚪⚪",
    },
    {
      id: "mom_4",
      title: "Inelastic Collisions: The Brutal Crunch 🚗",
      color: "#A855F7",
      bgGradient: ["#1A0A1F", "#050D0A"],
      icon: "🚗",
      svgIcon: "alert-triangle",
      content: "In completely entirely exactly pure **Inelastic Collisions**, massive extreme physical kinetic energy is forcefully brutally violently lost! \n\nWhen two total fully physical cars rapidly completely severely crash head-on, their heavy metal forcefully violently entirely utterly bends, crumples, and furiously intensely physically absolutely screams! The massive lost kinetic utterly completely purely escapes entirely strictly forcefully right absolutely flawlessly totally intensely perfectly as pure raw frictional heat and absolutely totally fiercely loud chaotic acoustic sound!",
      highlight: "The cars utterly stick fiercely completely terribly completely furiously heavily fiercely together in total entire absolute perfect twisted chaotic utter ruin! 🚓",
    },
    {
      id: "mom_5",
      title: "Impulse: The Gentle Catch 🧤",
      color: "#FF9F1C",
      bgGradient: ["#201000", "#050D0A"],
      icon: "🧤",
      svgIcon: "heart",
      content: "Impulse ($J = F \Delta t$) is the total change in momentum. \n\nYou can dramatically reduce the violent impact force by simply increasing the time of the collision! This is why a baseball catcher always pulls their hand back while catching a wild 100mph fastball. By increasing the stop-time, they fiercely lower the crushing peak force on their hand!",
      highlight: "Airbags in cars work exactly on this rule—they fiercely increase your collision time to keep your head from exploding! 🛡️",
    },
    {
      id: "mom_6",
      title: "Recoil: The Kickback 🔫",
      color: "#6C5CE7",
      bgGradient: ["#100A20", "#050D0A"],
      icon: "🔫",
      svgIcon: "zap",
      content: "Conservation of momentum forces every action to have an equal and opposite reaction! \n\nWhen a cannon fires a heavy iron ball forward, the cannon must aggressively kick backward with the exact same total amount of momentum! Since the cannon is much heavier, it moves slower, but the physics is absolutely perfectly strictly balanced by the universe!",
      highlight: "This is exactly how rockets work! They violently throw gas out the bottom to push the ship upward with equal momentum! 🚀",
    },
    {
      id: "mom_7",
      title: "Angular Momentum: The Silent Spin 🎡",
      color: "#F43F5E",
      bgGradient: ["#200A10", "#050D0A"],
      icon: "🎡",
      svgIcon: "refresh",
      content: "Spinning objects have their own special version of momentum! \n\nOnce something is spinning violently, it fiercely resists changing its axis. This is why a bicycle stays perfectly upright while moving—the spinning wheels aggressively fight gravity to maintain their orientation! This is known as the Gyroscopic Effect.",
      highlight: "Ice skaters spin faster when they pull their arms in because they are mathematically conserving their angular momentum! ⛸️",
    },
    {
      id: "mom_8",
      title: "Center of Mass: The Balance Point ⚖️",
      color: "#8B5CF6",
      bgGradient: ["#150A20", "#050D0A"],
      icon: "⚖️",
      svgIcon: "target",
      content: "Every object, no matter how chaotic its shape, has a single magic invisible point where all its mass perfectly averages out! \n\nWhen you throw a spinning hammer through the air, it might look like pure madness, but its **Center of Mass** is actually following a perfectly smooth, elegant mathematical parabola through the void!",
      highlight: "The center of mass of the Earth and Moon isn't inside Earth—it's a point slightly below the surface! 🌍",
    },
    {
      id: "mom_9",
      title: "Frame of Reference: Relative Motion 🚂",
      color: "#EC4899",
      bgGradient: ["#200A15", "#050D0A"],
      icon: "🚂",
      svgIcon: "activity",
      content: "Momentum is always measured relative to something else! \n\nIf you are walking at 3 mph inside a train moving at 100 mph, you have different momentum depending on who is watching. To your friend on the train, you are slow; to the person on the tracks, you are a 103 mph human bullet! Physics absolutely demands a strict Frame of Reference!",
      highlight: "You are currently moving at 67,000 mph relative to the Sun! You have massive hidden momentum right now! 🌌",
    },
  ],

  lab: {
    title: "Inelastic Crash Course 🏎️",
    description: "Welcome to the Absolute Collision Pit. Brutally smash objects into unbreakable sheer walls to mathematically calculate sheer devastating destruction force and impulse spread!",
    hint: "Max the speed completely up to mathematically force utter chaotic damage and heavy explosive haptic impacts!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time exact raw force values and pure kinetic energy equations.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why cars are designed to completely 'Crumple' in a crash? 🚗",
      answer: "To save your life! By designing the front of the car to collapse like a tin can, engineers aggressively increase the 'Impulse Time' of the crash. This reduces the peak crushing force on the passengers, turning a lethal stop into a survivable one! 🛡️",
      emoji: "💥",
    },
    {
      id: "dyk2",
      question: "Do you know why you bend your knees when you jump off a high wall? 🦵",
      answer: "Physics! If you kept your legs locked, you would stop instantly with a bone-shattering force. By bending your knees, you increase the time it takes to stop your momentum, which fiercely lowers the force on your joints! 📉",
      emoji: "🦴",
    },
    {
      id: "dyk3",
      question: "Do you know why a follow-through is vital in sports like golf or tennis? 🏌️",
      answer: "The longer your racket is in contact with the ball, the more 'Impulse' you deliver! By following through, you maximize the time of the force, allowing you to transfer way more momentum to the ball for a faster shot! 🎾",
      emoji: "⚡",
    },
    {
      id: "dyk4",
      question: "Do you know how Spacecraft change direction in a void? 🛸",
      answer: "Recoil! Since there is no air to push against, rockets must throw mass (gas) in the opposite direction. The ship and the exhaust gas push off each other with equal and opposite momentum, allowing the ship to turn! 🚀",
      emoji: "🌌",
    },
    {
      id: "dyk5",
      question: "Do you know why heavy trucks take so long to stop? 🚛",
      answer: "Massive Momentum! Even if they have powerful brakes, the sheer mass of the truck means it takes a huge amount of work and time to reduce that momentum to zero. They have way more 'Inertia' than a tiny car! 🛑",
      emoji: "⚖️",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What is the mathematical definition of Momentum?",
      options: ["Gravity x Height", "Mass x Velocity", "Force / Area", "Energy + Heat"],
      answer: 1,
      explanation: "Momentum ($p$) is simply how much mass is moving and how fast it is going! 🚂",
    },
    {
      id: "q2",
      question: "In what type of collision is Kinetic Energy perfectly preserved?",
      options: ["Inelastic Collision", "Explosive Collision", "Elastic Collision", "Crunchy Collision"],
      answer: 2,
      explanation: "Elastic collisions are like perfect bounces where no energy is lost to heat or sound! 🏀",
    },
    {
      id: "q3",
      question: "What happens to your Kinetic Energy if you double your car's speed?",
      options: ["It doubles", "It stays the same", "It quadruples (increases 4x)", "It triples"],
      answer: 2,
      explanation: "Kinetic energy depends on speed squared ($1/2 mv^2$). 2 squared is 4! 🏎️",
    },
    {
      id: "q4",
      question: "What is 'Conservation of Momentum'?",
      options: ["Momentum is lost forever", "Total momentum stays the same in a closed system", "Momentum only exists on Earth", "Momentum turns into gravity"],
      answer: 1,
      explanation: "The universe strictly forbids momentum from just vanishing—it always transfers! ⚖️",
    },
    {
      id: "q5",
      question: "Why do airbags protect you in a car crash?",
      options: ["They move you out of the way", "They increase the time of impact to reduce force", "They are made of metal", "They stop the car instantly"],
      answer: 1,
      explanation: "Increasing the impact time (Impulse) dramatically lowers the peak crushing force! 🛡️",
    },
    {
      id: "q6",
      question: "Which has more momentum: A heavy truck at rest or a flying mosquito?",
      options: ["The truck", "The mosquito", "They are equal", "Neither has any"],
      answer: 1,
      explanation: "If an object isn't moving (velocity = 0), it has ZERO momentum, no matter how heavy! 🦟",
    },
    {
      id: "q7",
      question: "What is 'Impulse'?",
      options: ["A type of energy", "The change in momentum", "A magnetic force", "The weight of an object"],
      answer: 1,
      explanation: "Impulse is the result of a force acting over a period of time! ⏱️",
    },
    {
      id: "q8",
      question: "A rocket moving in space is a perfect example of what principle?",
      options: ["Conduction", "Recoil and Conservation of Momentum", "Buoyancy", "Static Electricity"],
      answer: 1,
      explanation: "Rockets move by throwing mass backward to push themselves forward! 🚀",
    },
    {
      id: "q9",
      question: "What happens in a perfectly 'Inelastic' collision?",
      options: ["Objects bounce perfectly", "Objects stick together and lose kinetic energy", "Objects disappear", "Objects speed up"],
      answer: 1,
      explanation: "Inelastic crashes are 'sticky' and lose lots of energy to heat and sound! 🚗",
    },
    {
      id: "q10",
      question: "What allows a bicycle to stay upright while moving?",
      options: ["The rider's weight", "Angular Momentum of the spinning wheels", "The wind", "Magnetic tires"],
      answer: 1,
      explanation: "Spinning objects work like gyroscopes to resist tipping over! 🎡",
    },
    {
      id: "q11",
      question: "Why is a bullet so much more deadly than a slow-moving rock of the same mass?",
      options: ["It is sharper", "It has way more Kinetic Energy due to high speed", "It is magnetic", "It is heavier"],
      answer: 1,
      explanation: "Velocity is the 'High Voltage' of destructive energy! 💥",
    },
    {
      id: "q12",
      question: "The 'Center of Mass' is essentially the object's...",
      options: ["Heaviest part", "Geometric center", "Average balance point", "Magnetic pole"],
      answer: 2,
      explanation: "It's the magic point where the object behaves as if all its mass is concentrated! ⚖️",
    },
    {
      id: "q13",
      question: "If two skaters on ice push off each other, what happens?",
      options: ["One falls over", "They both move backwards with equal momentum", "Only one moves", "They both stick together"],
      answer: 1,
      explanation: "The total momentum must remain zero (if they started still)! ⛸️",
    },
    {
      id: "q14",
      question: "Newton's Cradle demonstrates which type of collision most closely?",
      options: ["Inelastic", "Nearly Elastic", "Explosive", "Frictionless"],
      answer: 1,
      explanation: "The balls bounce with very little energy lost to heat! ⚪",
    },
    {
      id: "q15",
      question: "What units are commonly used for Momentum?",
      options: ["Newtons", "Joules", "kg·m/s", "Watts"],
      answer: 2,
      explanation: "Mass (kg) multiplied by Velocity (m/s) gives kg·m/s! 📏",
    },
    {
      id: "q16",
      question: "Can a light object have more momentum than a heavy object?",
      options: ["No, impossible", "Yes, if it moves fast enough", "Only in space", "Only if it is magnetic"],
      answer: 1,
      explanation: "Speed can make up for a lack of mass! 🏃‍♂️",
    },
    {
      id: "q17",
      question: "Why does a gun 'kick' when fired?",
      options: ["Air pressure", "Recoil momentum equal to the bullet's momentum", "The heat of the explosion", "Gravity pulling on the trigger"],
      answer: 1,
      explanation: "Action and Reaction! The bullet goes forward, the gun goes back. 💥",
    },
    {
      id: "q18",
      question: "What is an 'Isolated System' in physics?",
      options: ["A system in a vacuum", "A system with no external forces acting on it", "A system that is frozen", "A system with only one object"],
      answer: 1,
      explanation: "Momentum is only perfectly conserved when outside forces don't interfere! 🧊",
    },
    {
      id: "q19",
      question: "How do padding and helmets protect athletes?",
      options: ["By making them invisible", "By increasing impulse time to reduce force", "By making them heavier", "By cooling them down"],
      answer: 1,
      explanation: "Padding absorbs the energy over a longer time interval! 🛡️",
    },
    {
      id: "q20",
      question: "If all internal forces in the universe cancel out, what is the 'Total Momentum' of the universe?",
      options: ["Infinite", "Zero", "Constantly increasing", "It depends on the time"],
      answer: 1,
      explanation: "From the Big Bang's reference frame, the sum of all momentum vectors is zero! 🌌",
    },
  ],

  relatedTopics: ["forces_motion", "gravity"],
};
