// ─────────────────────────────────────────────────────────
//  TOPIC: EASTERN PHILOSOPHY
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'eastern_philosophy',
  title: 'Eastern Philosophy',
  subtitle: 'The Art of Letting Go 🎋🧘',
  emoji: '🎋',
  category: 'Philosophy',
  accentKey: 'eastern_philosophy',

  hook: {
    question: "Western philosophy tells you to 'Conquer the World'. Eastern philosophy asks: *'Who is the You that is trying to conquer it?'*",
    reveal: "Welcome to a completely different operating system for the human mind.\n\nWhile Greek philosophers were busy categorizing logic and arguing about politics, ancient thinkers in India and China were looking *inward*. They noticed that human suffering isn't caused by a lack of money or power. It is caused by a fundamental hallucination about who you are and how the universe works.\nFrom the Buddha dismantling the 'Self', to Laozi teaching the power of doing *nothing* (Wu Wei), Eastern Philosophy isn't about acquiring more knowledge. It's about unlearning everything that makes you anxious. Take a deep breath. Let's begin. 🌬️☯️",
    emoji: '☯️',
  },

  theory: [
    {
      id: 'east_vs_west',
      title: "East vs. West 🌎",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'map',
      svgIcon: 'star',
      content: "Broadly speaking, Western Philosophy (Greece, Europe) is **Analytic**. It chops the world into tiny pieces (atoms, categories, true/false) to control it. Man is separate from Nature.\nEastern Philosophy (India, China, Japan) is **Holistic**. It views the universe as one interconnected, flowing organism. Man is *not* separate from Nature; man is an expression of Nature, like a wave is an expression of the ocean.",
      highlight: "The West tries to conquer the river. The East learns to swim with the current. 🌊",
    },
    {
      id: 'buddhism_the_problem',
      title: "Buddhism: The Diagnosis 🩺",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'activity',
      svgIcon: 'flame',
      content: "Siddhartha Gautama (The Buddha) wasn't a god; he was essentially a psychological doctor.\nHis diagnosis of humanity was the **First Noble Truth: Dukkha (Suffering/Dissatisfaction)**.\nHe pointed out that even when you are happy, you are secretly anxious because you know the happiness will end. Life is a constant, exhausting treadmill of wanting something, getting it, getting bored, and wanting something else.",
      highlight: "Suffering isn't just physical pain; it's the background hum of anxiety that you are never truly 'done'. 🏃",
    },
    {
      id: 'the_cause_of_suffering',
      title: "The Cause: Attachment 🪢",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'link',
      svgIcon: 'lock',
      content: "Why do we suffer? The **Second Noble Truth** states the cause is *Attachment (Tanha)*.\nWe try to hold onto things that are constantly changing (youth, money, relationships). \nThe universe is fluid, but the human ego tries to freeze it. When the universe naturally shifts and destroys what we tried to freeze, we feel pain. \nSuffering = Pain × Resistance.",
      highlight: "You don't suffer because things break. You suffer because you expected them to last forever. ⏳",
    },
    {
      id: 'impermanence_anicca',
      title: "Anicca (Impermanence) 🍂",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'wind',
      svgIcon: 'cloud',
      content: "To cure attachment, Buddhism teaches **Anicca** (Impermanence). \nAbsolutely nothing in the universe is solid or lasting. Mountains turn to dust. Empires fall. Your own cells regenerate entirely every 7 years.\nIf you truly internalize that *everything* is temporary, you stop clinging tightly to it. You can enjoy a beautiful flower without crying when it eventually wilts.",
      highlight: "This too shall pass. (Both the good times and the bad times). 🌸",
    },
    {
      id: 'the_illusion_of_self',
      title: "Anatta (No-Self) 👤",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'user-x',
      svgIcon: 'eye',
      content: "This is Buddhism's most terrifying and liberating concept: **Anatta (No-Self)**.\nYou feel like there is a 'CEO' inside your head—a permanent 'You' driving your body. \nThe Buddha argued this 'Self' is a hallucination. 'You' are just a temporary bundle of physical matter, memories, and sensations constantly shifting. If you have no permanent 'Self', then who is there to be insulted? Who is there to be anxious?",
      highlight: "If you remove the ego, 90% of your daily problems instantly evaporate, because there is no 'me' to be offended. 💨",
    },
    {
      id: 'nirvana',
      title: "Nirvana (Blowing Out the Flame) 🕯️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'cloud-off',
      svgIcon: 'zap',
      content: "The ultimate goal in Buddhism is not going to Heaven, but reaching **Nirvana**.\nNirvana literally translates to 'Blowing out' (like a candle).\nIt is not a place. It is a psychological state where the fires of greed, hatred, and delusion have been permanently extinguished. You realize the illusion of the ego, stop fighting the flow of the universe, and exist in absolute, completely undisturbed peace.",
      highlight: "Freedom is not getting what you want. Freedom is dropping the desire to want it. 🕊️",
    },
    {
      id: 'hinduism_brahman',
      title: "Hinduism: You Are The Universe 🕉️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'globe',
      svgIcon: 'star',
      content: "In ancient Indian philosophy (Vedanta), the ultimate reality of the universe is called **Brahman** (a single, infinite, divine consciousness).\nYour individual soul is called **Atman**.\nThe central, explosive realization of Hinduism is: *Atman is Brahman*. \nYou are not a puny mortal placed *into* the universe. You *are* the universe experiencing itself in human form.",
      highlight: "Tat Tvam Asi (Thou Art That). You are the ocean in a drop. 🌊",
    },
    {
      id: 'maya_the_illusion',
      title: "Maya (The Great Play) 🎭",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'monitor',
      svgIcon: 'cloud',
      content: "If we are eternal, infinite consciousness, why do we feel so small and stressed?\nHinduism explains this using **Maya** (Illusion/Magic).\nImagine God gets bored of being infinite, so He plays a game of hide-and-seek with Himself. He splits into billions of lifeforms and gives them amnesia so the 'game' feels real and dangerous.\nYour struggles, your job, your fears... they are just part of the cosmic VR game.",
      highlight: "Enlightenment (Moksha) is just waking up from the game and remembering who you really are. 🎮",
    },
    {
      id: 'karma',
      title: "Karma (Action and Reaction) ⚖️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'refresh-cw',
      svgIcon: 'activity',
      content: "In the West, people think **Karma** is a magical judge that punishes bad people ('Karma's a bitch').\nIn the East, Karma just translates to 'Action'. It is the spiritual equivalent of Newton's Third Law (Every action has a reaction).\nIf you plant an apple seed, an apple tree grows. If you act with hatred, you cultivate a hateful mind that suffers. There is no cosmic judge; your actions are just planting seeds that *will* bear fruit in your own psychology.",
      highlight: "You aren't punished *for* your anger; you are punished *by* your anger. 🌱",
    },
    {
      id: 'taoism_the_way',
      title: "Taoism: The Way of Nature ☯️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'aperture',
      svgIcon: 'target',
      content: "Moving to ancient China, Laozi wrote the *Tao Te Ching* (around 400 BC).\nThe **Tao** translates to 'The Way' or the hidden rhythm of the universe.\nTaoism notices that Nature doesn't hurry, yet everything is accomplished. Trees don't 'try' to grow. Water doesn't 'try' to flow downhill. \nThey argue human misery comes from our ego constantly fighting, resisting, and trying to force outcomes against the natural grain of the universe.",
      highlight: "A good traveler has no fixed plans and is not intent on arriving. 🚶‍♂️",
    },
    {
      id: 'wu_wei',
      title: "Wu Wei (Effortless Action) 🛶",
      color: '#009688',
      bgGradient: ['#001A15', '#000805'],
      icon: 'feather',
      svgIcon: 'lock',
      content: "The core superpower of Taoism is **Wu Wei** (Doing nothing, or 'Effortless Action').\nThis doesn't mean being lazy on the couch. It means being in the 'Zone' or 'Flow State'.\nThink of a master martial artist or a jazz musician. When they perform brilliantly, they aren't 'thinking' or forcing it. Their ego disappears, and the action flows through them perfectly aligned with the moment.",
      highlight: "Don't push the river; it flows by itself. 🌊",
    },
    {
      id: 'yin_yang',
      title: "Yin and Yang 🌗",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'move',
      svgIcon: 'eye',
      content: "In the West, we view opposites as enemies at war (God vs. Devil, Good vs. Evil, Light vs. Dark).\nTaoism views opposites as **Yin and Yang**—mutually dependent partners dancing together.\nYou cannot have a 'Front' without a 'Back'. You cannot have 'Up' without 'Down'. You cannot realize what 'Joy' is unless you have experienced 'Sorrow'. \nTherefore, fighting to eliminate all negative things is impossible and foolish. You must harmonize with both.",
      highlight: "Silence only has meaning because of sound. 🎶",
    },
    {
      id: 'zen_buddhism',
      title: "Zen: Shut Up and Drink Tea 🍵",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'coffee',
      svgIcon: 'zap',
      content: "When Buddhism traveled to China and Japan, it mixed with Taoism to create **Zen**.\nZen is profoundly anti-intellectual. You cannot read your way to Enlightenment. Thinking about the universe is exactly what separates you from it.\nZen masters use 'Koans' (unsolvable riddles like 'What is the sound of one hand clapping?') to short-circuit the logical brain. When the thinking mind finally breaks down, pure awareness remains.",
      highlight: "When hungry, eat. When tired, sleep. Stop overcomplicating existence. 🧘‍♂️",
    },
    {
      id: 'alan_watts',
      title: "Alan Watts: The Cosmic Dance 🕺",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'music',
      svgIcon: 'star',
      content: "British philosopher Alan Watts was famous for translating these Eastern concepts for Westerners in the 1960s.\nHe famously noted: We treat life like a journey with a destination (retiring rich, going to heaven). But life is not a journey; it is a **Dance** or a musical composition.\nYou don't listen to music just to reach the final chord. You listen to enjoy the dancing along the way.\nWe work so hard for the future that we completely miss the present.",
      highlight: "You are an aperture through which the universe is looking at and exploring itself. 🔭",
    },
    {
      id: 'conclusion',
      title: "The Cure for Modern Anxiety 🌅",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'sun',
      svgIcon: 'star',
      content: "Modern life is obsessed with controlling the future, building the ego, and acquiring things. This leads to burnout and massive anxiety.\nEastern Philosophy offers the antidote: Surrender.\nRealize the self is an illusion. Accept impermanence. Stop forcing the universe to obey your ego. Drop into the present moment.\nYou don't need to conquer the world to find peace. Peace is what remains when you stop trying to conquer it.",
      highlight: "Let go, or be dragged. 🍃",
    },
  ],

  lab: {
    title: "The Wu Wei Simulator 🛶",
    description: "Welcome to the Taoist River. The philosophy of Wu Wei (Effortless Action) states that forcing things creates destructive friction. You must navigate the river to the ocean. \nIf you try to aggressively steer the boat (tapping wildly), you will capsize. If you do absolutely nothing, you will hit the rocks. You must find the precise balance of 'Flow'.",
    hint: "Do not tap aggressively. Tap only when absolutely necessary to gently nudge the trajectory. Less is more.",
    scientistModeHint: "Algorithm Mode 🧑‍🔬: The input listener penalizes high-frequency tap rates. It rewards low-latency, minimal adjustments (sparse optimization).",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do Buddhists meditate?", answer: "Meditation is not about relaxing or 'clearing your mind'. It is a rigorous scientific laboratory for your own consciousness. By sitting completely still and observing your thoughts, you eventually realize you aren't creating them. They just appear. This directly proves the concept of 'Anatta' (No-Self). Once you see the ego is an illusion, your anxieties lose their grip on you. 🧘‍♂️", emoji: '🧠' },
    { id: 'dyk2', question: "Why is the symbol of Yin and Yang a circle instead of a straight line?", answer: "In Western thought, time and progress are a straight line (moving from bad to good, or earth to heaven). In Eastern thought, reality is cyclical. Day turns into night, which turns back into day. Summer into Winter. Life into Death. The circle represents that opposites constantly swirl into each other, and the dot inside each color shows that every extreme contains the seed of its opposite. ☯️", emoji: '🔄' },
    { id: 'dyk3', question: "Why do Zen Masters hit their students with sticks?", answer: "Historically, Zen monasteries used mild physical shocks (like a sudden strike with the 'keisaku' stick) not as punishment, but to snap a student out of a daydream. The goal of Zen is to be 100% fiercely present in the current moment. If a student is sitting there lost in intellectual thoughts about the Buddha, a sudden WHACK snaps their awareness instantly back to physical reality. 🎋", emoji: '🥢' },
    { id: 'dyk4', question: "Why did the Buddha say human desire is like drinking saltwater?", answer: "Because drinking saltwater to quench your thirst only makes you thirstier. This is the essence of 'Dukkha' (Suffering). When you buy a new phone, the happiness lasts a week. Then the baseline resets, and you immediately desire the *next* model. We are trapped on a 'hedonic treadmill'. The only way to win the game is to stop drinking the saltwater (Attachment). 🌊", emoji: '📱' },
    { id: 'dyk5', question: "Why don't Hindus fear Death?", answer: "Because of 'Maya' and 'Brahman'. If you think you are a separate, isolated ego trapped in a meat bag, death is terrifying—it is the end of 'You'. But if you realize that 'You' are actually the infinite universe temporarily playing the role of a human, then death is just taking off a costume. A wave crashing on the shore doesn't die; it just goes back to being the ocean. 🌊", emoji: '🎭' },
  ],

  quiz: [
    { id: 'q1', question: "Broadly speaking, how does Eastern Philosophy view humanity's relationship with Nature?", options: ['Man is meant to conquer Nature', 'Man is not separate; Man is an expression of Nature, like a wave on the ocean', 'Nature is evil and must be avoided', 'Nature is a simulation'], answer: 1, explanation: "We don't 'come into' the world, we 'grow out of' it. 🌊" },
    { id: 'q2', question: "What is the First Noble Truth in Buddhism?", options: ['God is great', 'Dukkha: Life is inherently characterized by suffering and dissatisfaction', 'Money brings happiness', 'Always tell the truth'], answer: 1, explanation: "Even happiness has a background hum of anxiety because we know it will end. 🩺" },
    { id: 'q3', question: "According to Buddhism, what is the root cause of our suffering?", options: ['Bad luck', 'Attachment / Clinging (Tanha) to temporary things', 'Demons', 'Eating meat'], answer: 1, explanation: "Suffering = Pain × Resistance to change. 🪢" },
    { id: 'q4', question: "What does the Buddhist concept of 'Anicca' mean?", options: ['Meditation', 'Impermanence: Absolutely everything in the universe is temporary and constantly changing', 'Eternal life', 'The soul'], answer: 1, explanation: "If you know the flower will wilt, you don't cry when it happens. 🍂" },
    { id: 'q5', question: "What is the terrifying but liberating Buddhist concept of 'Anatta'?", options: ['Flying', 'No-Self: The ego is an illusion. There is no permanent \"You\" inside your head', 'Reincarnation', 'A type of yoga'], answer: 1, explanation: "If there is no 'me', who is there to be insulted? 👤" },
    { id: 'q6', question: "What does 'Nirvana' literally translate to?", options: ['Heaven', 'Blowing out (extinguishing the fires of greed, hatred, and delusion)', 'A rock band', 'Ultimate power'], answer: 1, explanation: "It is not a place, it is a psychological state of absolute peace. 🕯️" },
    { id: 'q7', question: "In Hinduism (Vedanta), what is 'Brahman'?", options: ['A caste system', 'The single, infinite, divine consciousness that makes up the ultimate reality of all things', 'A type of food', 'A specific god of war'], answer: 1, explanation: "Atman (your soul) is secretly Brahman. You are the universe in disguise. 🕉️" },
    { id: 'q8', question: "What is 'Maya' in Hindu philosophy?", options: ['A month', 'The Great Illusion: The cosmic matrix/game that makes infinite consciousness feel separate, small, and mortal', 'A sacred river', 'The god of destruction'], answer: 1, explanation: "Your daily struggles are just a highly immersive VR game. 🎭" },
    { id: 'q9', question: "How does the Eastern concept of 'Karma' differ from the Western popular idea?", options: ['It only applies to animals', 'It is not a cosmic judge punishing you; it is just Action and Reaction. You are punished BY your anger, not FOR it', 'It means \"bad luck\"', 'It means \"destiny\"'], answer: 1, explanation: "Plant an apple seed, get an apple tree. ⚖️" },
    { id: 'q10', question: "What does the 'Tao' translate to in Taoism?", options: ['The Ruler', 'The Way (the natural, flowing rhythm of the universe)', 'The End', 'The Mind'], answer: 1, explanation: "Laozi wrote the Tao Te Ching to explain how to live in rhythm with it. ☯️" },
    { id: 'q11', question: "What is 'Wu Wei', the core superpower of Taoism?", options: ['Kung Fu', 'Effortless Action/Doing Nothing: Being in the \"Flow State\" without ego or aggressive force', 'Strict meditation', 'Eating rice'], answer: 1, explanation: "Don't push the river; it flows by itself. 🛶" },
    { id: 'q12', question: "How does the concept of Yin and Yang view opposites?", options: ['They must destroy each other', 'They are mutually dependent partners (you can\'t have \"Up\" without \"Down\", \"Joy\" without \"Sorrow\")', 'One is good, one is evil', 'They don\'t exist'], answer: 1, explanation: "Fighting to eliminate the 'negative' side of life is mathematically impossible. 🌗" },
    { id: 'q13', question: "Why is Zen Buddhism so anti-intellectual?", options: ['Because reading is hard', 'Because thinking about the universe separates you from it. You cannot read your way to Enlightenment; you must directly experience the present moment', 'They don\'t like books', 'It was a political rule'], answer: 1, explanation: "When hungry, eat. Stop overcomplicating existence. 🍵" },
    { id: 'q14', question: "What is a 'Koan' in Zen?", options: ['A sword', 'An unsolvable riddle (like \"the sound of one hand clapping\") designed to short-circuit the logical brain and shatter the ego', 'A prayer', 'A song'], answer: 1, explanation: "It breaks the computer of your mind so pure awareness can shine through. ⚡" },
    { id: 'q15', question: "Alan Watts famously compared life to what, rather than a 'journey'?", options: ['A test', 'A Dance or Musical Composition (You don\'t listen to a song just to reach the final chord)', 'A battle', 'A prison'], answer: 1, explanation: "We work so hard for the 'future' that we miss the dance of the present. 🕺" },
    { id: 'q16', question: "Why did the Buddha compare human desire (the hedonic treadmill) to drinking saltwater?", options: ['It tastes bad', 'Because trying to satisfy desires by acquiring things only makes you thirstier for MORE things', 'Water is scarce', 'It makes you sick'], answer: 1, explanation: "After you get the new phone, you immediately desire the next one. 🌊" },
    { id: 'q17', question: "In Eastern Philosophy, why is death not something to be terrified of?", options: ['You get to be a ghost', 'Because the separate \"You\" was always an illusion. The wave crashes, but it just goes back to being the Ocean', 'You become a god', 'You respawn instantly'], answer: 1, explanation: "Death is just taking off a tight shoe. 🌌" },
    { id: 'q18', question: "If a Taoist is faced with a difficult, aggressive opponent in an argument, what would they likely do using 'Wu Wei'?", options: ['Yell louder', 'Yield and use the opponent\'s own aggressive energy against them (like water flowing around a rock)', 'Punch them', 'Run away crying'], answer: 1, explanation: "Softness overcomes hardness. Water carves through stone. 💧" },
    { id: 'q19', question: "What is the ultimate psychological goal of Western Philosophy compared to Eastern Philosophy?", options: ['East is science, West is art', 'The West seeks to categorise, control and conquer reality. The East seeks to surrender, let go, and harmonize with reality', 'Both are exactly the same', 'West seeks magic, East seeks math'], answer: 1, explanation: "Conquer the world vs. Conquer the mind. 🌎" },
    { id: 'q20', question: "According to Eastern thought, when you sit quietly in meditation, what are you proving to yourself?", options: ['You are smart', 'That your thoughts just \"appear\" without your permission, proving that the ego/controller is an illusion', 'You can sleep sitting up', 'That magic is real'], answer: 1, explanation: "Meditation is a scientific laboratory for the mind. 🧘‍♂️" },
  ],

  relatedTopics: ['stoicism', 'free_will', 'consciousness'],
};
