// ─────────────────────────────────────────────────────────
//  TOPIC: ARGUMENTS FOR & AGAINST GOD'S EXISTENCE
//  Category: Religion & God
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'god_arguments',
  title: 'Arguments For & Against God',
  subtitle: 'The strongest cases on BOTH sides — presented fairly ⚖️🔥',
  emoji: '⚖️',
  category: 'Religion & God',
  accentKey: 'god_arguments',

  hook: {
    question: "Across 3,000 years of philosophy, the greatest minds in human history — Aristotle, Aquinas, Descartes, Pascal, Hume, Kant, Darwin, Russell, Plantinga — have ALL tried to settle the God question. So why is it STILL unsettled?",
    reveal: "Because it's not an evidence problem — it's a FRAMEWORK problem.\n\nBoth sides are looking at the SAME universe and drawing opposite conclusions. The theist sees fine-tuning, consciousness, and morality as proof of design. The atheist sees suffering, natural explanations, and Occam's Razor as proof of no design.\n\nThe arguments don't cancel each other out — they reveal that the question 'Does God exist?' may depend on which ASSUMPTIONS you start with, not on what evidence you find. And that's both terrifying and beautiful. 🧩",
    emoji: '💡',
  },

  theory: [
    {
      id: 'cosmological',
      title: "FOR: The Cosmological Argument 🌌",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'galaxy',
      svgIcon: 'rocket',
      content: "**The Argument (Thomas Aquinas, ~1270):**\n\n1. Everything that exists has a cause.\n2. Nothing can cause itself.\n3. An infinite chain of causes is impossible (infinite regress).\n4. Therefore, there must be an UNCAUSED First Cause.\n5. This First Cause is what we call God.\n\n**Why It's Strong**: The universe DID begin (Big Bang). Something must have caused it. Infinite regress seems absurd.\n\n**Why It's Challenged**: Why can't the First Cause be a natural process? And the argument doesn't prove a PERSONAL God — just a cause.",
      highlight: "Even atheist philosopher Bertrand Russell admitted: 'The argument that there must be a First Cause is one I find very difficult to answer.' 🤔",
    },
    {
      id: 'teleological',
      title: "FOR: The Teleological (Design) Argument 🎯",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'target',
      svgIcon: 'target',
      content: "**The Argument (William Paley, 1802):**\n\nIf you find a watch on a beach, you infer a watchmaker. The universe is infinitely more complex than a watch — therefore it implies a universe-maker.\n\n**Modern Version (Fine-Tuning)**:\nThe physical constants of the universe are calibrated to an incomprehensibly precise degree. Change the gravitational constant by 1 part in 10^60, and no stars form. No stars = no carbon = no life.\n\n**Why It's Strong**: The precision is scientifically verified. Pure chance seems astronomically unlikely.\n\n**Why It's Challenged**: The Multiverse theory (infinite random universes) explains it without God. Also, Darwin showed biological 'design' arises from natural selection, not a designer.",
      highlight: "The probability of a universe with our constants arising by chance: approximately 1 in 10^229. That's a number with 229 zeros. 🎲",
    },
    {
      id: 'moral_for',
      title: "FOR: The Moral Argument 🧭",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'compass',
      svgIcon: 'scale',
      content: "**The Argument (C.S. Lewis, Immanuel Kant):**\n\n1. Objective moral truths exist (e.g., torturing babies is REALLY wrong, not just unpopular).\n2. Objective truths require a ground/foundation.\n3. That foundation cannot be human opinion (opinions change) or evolution (evolution explains WHY we feel moral, not WHY morality is binding).\n4. Therefore, an objective moral lawgiver (God) must exist.\n\n**Why It's Strong**: Most people intuitively feel that some things are TRULY wrong, not just culturally disliked.\n\n**Why It's Challenged**: Maybe morality IS just evolutionary instinct dressed up as cosmic law. Maybe we're deluded into THINKING it's objective when it's really subjective.",
      highlight: "C.S. Lewis went from atheist to Christian specifically because he couldn't explain objective morality without God. 📖",
    },
    {
      id: 'ontological',
      title: "FOR: The Ontological Argument 🧠",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'brain',
      svgIcon: 'lock',
      content: "**The Argument (Anselm of Canterbury, 1078):**\n\n1. God is defined as the greatest conceivable being.\n2. A being that exists in reality is greater than one that exists only in imagination.\n3. Therefore, the greatest conceivable being MUST exist in reality.\n4. Therefore, God exists — by pure logic, no evidence needed!\n\n**Why It's Fascinating**: It's a purely logical proof requiring zero empirical evidence.\n\n**Why It's Challenged**: You can't 'define' things into existence. Using the same logic, you could 'prove' the existence of a 'greatest conceivable island' — but that's absurd. Existence is not a property you can add to definitions.",
      highlight: "This argument has been debated for 950 years straight. Philosophers STILL cannot agree whether it's brilliant or sophistry. 🤯",
    },
    {
      id: 'experiential',
      title: "FOR: The Argument from Religious Experience ✨",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'sparkle',
      svgIcon: 'eye',
      content: "**The Argument:**\n\nBillions of people across unconnected cultures and centuries report direct personal experiences of the divine — visions, answered prayers, mystical unity, near-death experiences.\n\nThe sheer volume, consistency, and cross-cultural nature of these reports constitutes evidence that SOMETHING real is being encountered.\n\n**Why It's Strong**: These experiences are the most personally convincing evidence for believers. You can't argue someone out of an experience they've had.\n\n**Why It's Challenged**: Neuroscience can reproduce 'god experiences' by stimulating the temporal lobe or administering psilocybin. If the brain can generate the experience artificially, it might always be generating it artificially.",
      highlight: "William James catalogued thousands of mystical experiences and concluded they were 'real' to the experiencer — even if unexplainable. 🌟",
    },
    {
      id: 'evil_argument',
      title: "AGAINST: The Problem of Evil 💀",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert',
      svgIcon: 'alert',
      content: "**The Argument (Epicurus, ~300 BCE):**\n\n1. If God is all-powerful, He CAN prevent suffering.\n2. If God is all-good, He WOULD want to prevent suffering.\n3. Suffering exists (children get cancer, earthquakes kill innocents).\n4. Therefore, an all-powerful AND all-good God cannot exist.\n\n**Why It's Strong**: It's the single most cited reason for atheism. Child suffering is viscerally compelling — no abstract theology can neutralize it.\n\n**Why It's Challenged**:\n• **Free Will Defense**: God allows evil so humans can have genuine moral choice.\n• **Soul-Making**: Suffering builds character (John Hick).\n• **Greater Good**: God permits temporary suffering for a larger plan we can't see.\n• **Mystery**: God's reasons transcend human comprehension.",
      highlight: "The Problem of Evil has been called 'the rock upon which theism sinks' — 2,300 years and STILL no universally accepted answer. ⚓",
    },
    {
      id: 'occam_razor',
      title: "AGAINST: Occam's Razor ✂️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'scissors',
      svgIcon: 'bolt',
      content: "**The Argument:**\n\nOccam's Razor states: Do not multiply entities beyond necessity. The simplest explanation is usually correct.\n\nIf natural processes (physics, chemistry, evolution) can explain the universe WITHOUT invoking a supernatural being, then God is an unnecessary addition — and should be 'shaved off' by Occam's Razor.\n\n**Why It's Strong**: Science has progressively replaced supernatural explanations with natural ones for centuries. The trend suggests no God is needed.\n\n**Why It's Challenged**: Occam's Razor is a heuristic (rule of thumb), NOT a law. Sometimes the simplest explanation is wrong (quantum mechanics is absurdly complex but true). And 'simplest' is subjective — a theist would argue ONE God is simpler than an accidental universe.",
      highlight: "Ironically, William of Occam — who proposed the Razor — was a Franciscan FRIAR who believed in God. His razor was never meant to shave God away! ✂️",
    },
    {
      id: 'natural_explanations',
      title: "AGAINST: Argument from Natural Explanations 🔬",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'microscope',
      svgIcon: 'microscope',
      content: "**The Argument:**\n\nEvery phenomenon previously attributed to God has eventually received a natural explanation:\n• Lightning → Electrical discharge (not Zeus)\n• Disease → Germs (not divine punishment)\n• Biodiversity → Natural selection (not special creation)\n• The cosmos → Big Bang + physics (not 'Let there be light')\n\nThis track record suggests that ALL remaining 'mysteries' (consciousness, origin of life) will also be explained naturally — making God permanently unnecessary.\n\n**Why It's Challenged**: Explaining the mechanisms of nature doesn't prove there's no designer BEHIND the mechanisms. Understanding how a painting was made doesn't prove there's no painter.",
      highlight: "Laplace, when asked by Napoleon why God wasn't in his physics, replied: 'Sire, I had no need of that hypothesis.' 🎙️",
    },
    {
      id: 'divine_hiddenness',
      title: "AGAINST: Divine Hiddenness 🫥",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'eye',
      svgIcon: 'lock',
      content: "**The Argument (J.L. Schellenberg, 1993):**\n\n1. If a loving God existed, He would want ALL people to know Him.\n2. A loving God would not hide himself from sincere seekers.\n3. Millions of honest, open-minded people search for God and find nothing.\n4. Therefore, a loving God probably doesn't exist.\n\n**Why It's Strong**: If God truly loves us and wants a relationship, why is He so hard to find? Why does He allow billions to be born into the 'wrong' religion?\n\n**Why It's Challenged**:\n• Perhaps God values free will so much that He hides to prevent coerced belief.\n• Perhaps God is found through experience, not evidence — and evidence would destroy faith.\n• Perhaps 'finding God' requires moral/spiritual readiness, not just intellectual searching.",
      highlight: "Mother Teresa privately revealed she experienced decades of spiritual 'darkness' — not feeling God's presence despite absolute faith. 🕯️",
    },
    {
      id: 'evolution_against',
      title: "AGAINST: Argument from Poor Design 🦷",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "**The Argument:**\n\nIf God is a perfect designer, why is the design so... imperfect?\n\n• Our eyes have a blind spot (the octopus eye doesn't)\n• Wisdom teeth serve no purpose and cause pain\n• The human birth canal is dangerously narrow\n• 99.9% of all species that ever lived went EXTINCT\n• The recurrent laryngeal nerve takes an absurd detour in giraffes\n\nThese design flaws are perfectly explained by evolution's blind, incremental process — but are hard to explain from an intelligent designer.\n\n**Why It's Challenged**: Maybe 'poor design' serves purposes we don't understand. Also, this only argues against a PERFECT designer — not against any designer at all.",
      highlight: "The human spine is essentially a modified fish skeleton forced to walk upright — causing the universal human back pain. 🐟➡️🧍‍♂️😫",
    },
    {
      id: 'pascals_wager',
      title: "SPECIAL: Pascal's Wager — The Gambler's Argument 🎰",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'dice',
      svgIcon: 'chart',
      content: "**Pascal's Wager (1670):**\n\n• If God exists and you believe → Infinite reward (Heaven)\n• If God exists and you don't believe → Infinite punishment (Hell)\n• If God doesn't exist and you believe → Minor cost (wasted some Sundays)\n• If God doesn't exist and you don't believe → Minor gain (slept in on Sundays)\n\nConclusion: Believing is the rational bet — the potential payoff is infinite!\n\n**Why It's Clever**: Bypasses the evidence question entirely — it's pure risk management.\n\n**Why It Fails**: Which God do you bet on? (There are thousands!) And can you CHOOSE to genuinely believe something? Forced belief isn't genuine belief — and an omniscient God would know you're faking.",
      highlight: "Pascal himself knew the Wager wasn't a proof — he called it a 'foot in the door' to get skeptics to START considering faith. 🚪",
    },
    {
      id: 'problem_of_hell',
      title: "AGAINST: The Problem of Eternal Hell 🔥",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'flame',
      svgIcon: 'fire',
      content: "**The Argument:**\n\nIf God punishes finite human sins with INFINITE torture in Hell:\n\n1. This is infinitely disproportionate (would you sentence someone to eternal prison for jaywalking?)\n2. An infinitely merciful God cannot perform infinitely merciless punishment\n3. A child born in the 'wrong' country to the 'wrong' religion goes to Hell through no fault of their own\n\n**Why It's Strong**: Even many Christians find eternal Hell morally repugnant.\n\n**Why It's Challenged**: \n• Many theologians reinterpret Hell as separation from God, not literal fire\n• Annihilationism: The damned are simply destroyed, not tortured forever\n• Universalism: Everyone is eventually saved (growing view in progressive Christianity)",
      highlight: "Pope Francis has suggested that Hell may be 'the state of those who separate themselves from God' — not a place of torture. 🔄",
    },
    {
      id: 'natural_theology',
      title: "FOR: Natural Theology — God Through Reason 📐",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'book',
      svgIcon: 'compass',
      content: "**Natural Theology** tries to prove God through reason and observation of nature ALONE — no faith, no revelation, no holy books required.\n\nKey arguments:\n1. **Contingency**: Everything in the universe is contingent (could have NOT existed). But the universe EXISTS. Why? Something non-contingent (necessary) must ground it.\n2. **Beauty**: The universe's mathematical elegance (E=mc², golden ratio, fractal geometry) seems to reflect an underlying intelligence.\n3. **Information**: DNA contains coded information. Information always implies a mind.\n\n**Why It's Strong**: Uses logic accessible to everyone regardless of religion.\n\n**Why It's Challenged**: Each step involves an interpretive leap. Beauty and elegance might be projections of the human mind, not features of reality.",
      highlight: "Mathematical physicist Roger Penrose: 'There is something going on that is not fully computational. Something beyond algorithms.' 🔢",
    },
    {
      id: 'reformed_epistemology',
      title: "SPECIAL: Is Belief in God 'Properly Basic'? 🏗️",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'foundation',
      svgIcon: 'shield',
      content: "**Alvin Plantinga's Reformed Epistemology:**\n\nSome beliefs are 'properly basic' — they're rational to hold WITHOUT evidence:\n• You believe the external world exists (you can't prove it; you might be dreaming)\n• You believe other people have minds (you can't prove it; they might be robots)\n• You trust your memory (you can't prove yesterday's memories are real)\n\nPlantinga argues that **belief in God is properly basic too** — a foundational belief that is rational even without proof, just like your belief that the world exists.\n\n**Why It's Strong**: It reverses the burden of proof — the atheist must now explain why God-belief is LESS basic than belief in other minds.\n\n**Why It's Challenged**: If God-belief is properly basic, so is belief in unicorns or Allah or Zeus. The concept may be too permissive.",
      highlight: "You cannot prove you're not a brain in a jar — yet you rationally believe you're real. Plantinga says God-belief has the same logical status. 🧠🫙",
    },
    {
      id: 'honest_reckoning',
      title: "The Honest Reckoning — Where Do We Stand? 🏳️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'scale',
      svgIcon: 'compass',
      content: "After 3,000 years of the God debate, here is the honest scorecard:\n\n**Arguments FOR God**: Cosmological, Teleological, Moral, Ontological, Experiential, Fine-Tuning, Natural Theology\n**Arguments AGAINST God**: Problem of Evil, Occam's Razor, Natural Explanations, Divine Hiddenness, Poor Design, Problem of Hell\n\nNeither side has a knockout punch. The debate persists because:\n1. The evidence is genuinely ambiguous\n2. Starting assumptions determine conclusions\n3. The question may be structurally unanswerable by human cognition\n\nThe most intellectually courageous position is not arrogant certainty on either side — it is **honest, humble uncertainty** paired with a passionate commitment to seeking truth.",
      highlight: "The philosopher who has thought most deeply about God is usually the LEAST certain — in either direction. 🤔",
    },
  ],

  lab: {
    title: "The Great Debate Engine ⚖️🔥",
    description: "Step into history's greatest intellectual arena! Rate each argument's strength (1-10), see how your evaluations compare to the philosopher consensus, and discover your own 'Belief Spectrum' position at the end.",
    hint: "Don't rate based on what you WANT to be true — rate based on logical strength. The strongest arguments are often for the side you disagree with!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Bayesian weight distributions, philosopher voting data, and epistemic confidence analysis.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why Blaise Pascal invented BOTH probability theory AND the famous God wager? 🎲", answer: "Pascal was a mathematical genius who invented probability theory at age 16. He then applied his own statistical framework to the biggest gamble of all — God's existence. His 'Wager' is essentially decision theory applied to theology: when the stakes are infinite, even a tiny probability of God existing makes belief the rational bet. He turned faith into a math problem! 🧮", emoji: '🎰' },
    { id: 'dyk2', question: "Do you know why Aquinas's 'Five Ways' were not original arguments? 🏛️", answer: "Thomas Aquinas (1270 CE) is credited with the Five Proofs for God, but they were actually adaptations of arguments from ARISTOTLE (a pagan Greek, 350 BCE) and IBN SINA / AVICENNA (a Muslim philosopher, 1000 CE). A Catholic monk synthesized a pagan's logic through an Islamic thinker's framework! The God debate has always been cross-cultural. 🌐", emoji: '📚' },
    { id: 'dyk3', question: "Do you know why Dostoevsky said 'If God does not exist, everything is permitted'? 📖", answer: "In 'The Brothers Karamazov', Dostoevsky argued that without God, there is no objective morality — and without objective morality, there is no rational reason NOT to commit any act. This doesn't prove God exists — it reveals the terrifying CONSEQUENCES if God doesn't. Many atheists live extremely ethically, but they struggle to philosophically ground WHY anyone SHOULD. 🌀", emoji: '🔥' },
    { id: 'dyk4', question: "Do you know why Charles Darwin's wife burned some of his private letters? 🔥", answer: "Emma Darwin was a devout Christian married to the man who dismantled the argument from design. Darwin's private letters reveal agonizing inner conflict about God. Emma reportedly destroyed some letters she considered too dangerous — possibly containing Darwin's harshest criticisms of religion. We may never know his most honest private thoughts. 💌", emoji: '✉️' },
    { id: 'dyk5', question: "Do you know why the most famous atheist of the 20th century (Antony Flew) switched to theism at age 81? 🔄", answer: "Antony Flew spent 50 years as the world's most prominent atheist philosopher. Then, at 81, he announced he now believed in God — specifically because of DNA. He argued that the information encoded in DNA is so complex that it implies an intelligent source. He didn't convert to any religion — just to belief in 'some sort of deity'. The atheist world was stunned. 🧬", emoji: '🤯' },
  ],

  quiz: [
    { id: 'q1', question: "The Cosmological Argument argues for God's existence by claiming:", options: ["The cosmos is beautiful", "Everything requires a first cause", "Space is infinitely large", "Stars prove a creator"], answer: 1, explanation: "Aquinas's First Way: the chain of causes can't go back infinitely. 🌌" },
    { id: 'q2', question: "The Design/Teleological Argument is MOST strengthened by:", options: ["Animals possess natural beauty", "Universal constants are fine-tuned", "Sunsets show artistic intent", "Human intelligence is unique"], answer: 1, explanation: "The precision is scientifically measured — the debate is about its CAUSE. 🎯" },
    { id: 'q3', question: "C.S. Lewis became a Christian because he couldn't explain:", options: ["Nature is too complex", "Objective morality requires God", "Miracles happen in history", "The Bible is accurate"], answer: 1, explanation: "The Moral Argument: if morality is truly objective, its ground can't be human opinion. 🧭" },
    { id: 'q4', question: "The Ontological Argument's key weakness is:", options: ["The argument is brief", "Definitions cannot prove existence", "It uses complex language", "It relies on math"], answer: 1, explanation: "Existence is not a property you can add to a definition. Gaunilo's Island refutation. 🏝️" },
    { id: 'q5', question: "The Problem of Evil argues against God using:", options: ["Scientific data disproves it", "Suffering contradicts a good God", "Historical evidence is lacking", "It is an emotion"], answer: 1, explanation: "Epicurus posed this 2,300 years ago. No universally accepted solution exists. 💀" },
    { id: 'q6', question: "The 'Free Will Defense' responds to the Problem of Evil by saying:", options: ["Evil is an illusion", "Choice requires possible evil", "Suffering is actually good", "God lacks total power"], answer: 1, explanation: "A world without the POSSIBILITY of evil is a world without genuine freedom. 🗽" },
    { id: 'q7', question: "Occam's Razor favors atheism by arguing:", options: ["Razors represent logical simplicity", "Natural explanations are simpler", "The author was an atheist", "Simplicity proves every theory"], answer: 1, explanation: "Ironically, William of Occam himself was a Franciscan monk who believed in God. ✂️" },
    { id: 'q8', question: "The Argument from Poor Design involves:", options: ["Weather patterns are chaotic", "Biological flaws suggest evolution", "Artistic quality is subjective", "Humans could be better"], answer: 1, explanation: "A perfect designer wouldn't give giraffes a nerve that takes a ridiculous detour. 🦒" },
    { id: 'q9', question: "Pascal's Wager is ultimately FLAWED because:", options: ["The math is flawed", "It ignores which god", "Gambling is morally wrong", "God does not gamble"], answer: 1, explanation: "Which God? And an omniscient God would know you're faking belief. 🎰" },
    { id: 'q10', question: "Divine Hiddenness challenges theism by asking:", options: ["Heaven is not visible", "God hides from seekers", "The sky is blue", "God's house is hidden"], answer: 1, explanation: "Many honest, open-minded seekers search for God and find silence. Why? 🫥" },
    { id: 'q11', question: "The 'greatest conceivable island' counterargument targets:", options: ["The Cosmological Argument", "The Ontological Argument's logic", "The Moral Argument", "The logic of Pascal's Wager"], answer: 1, explanation: "If you can 'define' God into existence, you can 'define' a perfect island too — proving the method is flawed. 🏝️" },
    { id: 'q12', question: "Alvin Plantinga's 'properly basic' belief concept argues:", options: ["Belief requires empirical evidence", "Belief in God is foundational", "God is a simple concept", "Philosophy is mostly unnecessary"], answer: 1, explanation: "You can't prove the world exists either — yet you rationally believe it does. 🏗️" },
    { id: 'q13', question: "The Argument from Religious Experience is weakened by:", options: ["People often tell lies", "Brain stimulation mimics experiences", "Religious people are wrong", "Psychology is not real"], answer: 1, explanation: "If the brain can generate 'God' artificially, maybe it's ALWAYS generating it artificially. 🧪" },
    { id: 'q14', question: "The problem with eternal Hell as punishment is:", options: ["Hell is physically cold", "Infinite punishment is disproportionate", "Nobody goes to Hell", "Hell is a metaphor"], answer: 1, explanation: "Even many theologians now reject literal eternal torture as incompatible with a loving God. 🔥" },
    { id: 'q15', question: "Antony Flew, history's most famous atheist, converted to theism because of:", options: ["A miracle occurred", "DNA complexity implies intelligence", "A near-death experience", "Social peer pressure"], answer: 1, explanation: "DNA's information complexity convinced him that pure blind chemistry was insufficient. 🧬" },
    { id: 'q16', question: "The Argument from Natural Explanations says God is unnecessary because:", options: ["God is a boring concept", "Science explains divine events", "Nature is actually God", "Science disproved God"], answer: 1, explanation: "Lightning is electricity, not Zeus. Disease is germs, not divine punishment. The pattern is clear. 🔬" },
    { id: 'q17', question: "Dostoevsky's 'If God doesn't exist, everything is permitted' implies:", options: ["Dostoevsky was a criminal", "Morality lacks objective foundation", "Nothing matters in life", "God is inherently evil"], answer: 1, explanation: "This doesn't prove God exists — it reveals the implications if He doesn't. 📖" },
    { id: 'q18', question: "Aquinas's Five Ways were actually based on arguments from:", options: ["The Holy Bible", "Aristotle's logic via others", "Social media trends", "His own original ideas"], answer: 1, explanation: "The God-proof project has always been cross-cultural. A Catholic used a pagan's logic via Islamic thought. 🌐" },
    { id: 'q19', question: "The Fine-Tuning Argument is countered by:", options: ["Ignoring the data", "Multiverses make life inevitable", "Changing the constants", "Using better telescopes"], answer: 1, explanation: "But the Multiverse itself is untestable and unfalsifiable — creating an ironic symmetry with theism. 🌌" },
    { id: 'q20', question: "After 3,000 years, the God debate remains unsettled because:", options: ["Effort has been insufficient", "The evidence is ambiguous", "The topic is unimportant", "Philosophers have given up"], answer: 1, explanation: "The most thoughtful philosopher is usually the LEAST certain — humility is the mark of genuine inquiry. ⚖️" },
  ],

  relatedTopics: ['science_vs_god', 'how_religion_evolved', 'consciousness', 'ethics_morality'],
};
