export default {
  // ── IDENTITY ────────────────────────────────
  id: 'ancient_civilizations',
  title: 'Ancient Civilizations',
  subtitle: 'Egypt, Indus, Rome — the empires that built our world 🏛️',
  emoji: '🏛️',
  category: 'History',
  accentKey: 'ancient',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "In 500 BCE, the Persian Empire, Greek city-states, Chinese Zhou dynasty, Maya civilization, AND Indian kingdoms ALL existed at the same time 🌍 — but none of them knew the others existed! How is that even possible?",
    reveal: "The ancient world was HUGE but travel was slow — a letter from Rome to China would take over a year! 📜 Yet these civilizations independently invented writing, mathematics, agriculture, and complex governments. The Sumerians invented the wheel in 3500 BCE. Egyptians built the Great Pyramid (2.3 million stones!) in 2560 BCE. The Maya discovered zero. The Romans built roads that STILL exist after 2000 years! Each civilization solved the same human problems in wildly different ways. Their ideas didn't die — they became YOUR world. Democracy? Greece. Your calendar? Egypt + Rome. The number system? India. \"All roads lead to Rome\" — and all of history leads to YOU! 🤯",
    emoji: '💭',
  },

  // ── THEORY CARDS (10) ───────────────────────
  theory: [
    {
      id: 'what_is_civ',
      title: 'What Makes a Civilization? 🌍',
      color: '#D4A74A',
      bgGradient: ['#2A2010', '#0D0D1A'],
      icon: '🌍',
      svgIcon: 'globe',
      content: "A *civilization* is more than just a group of people — it's a complex society with specific features that distinguish it from simpler communities. Historians identify *7 characteristics* of civilization:\n\n🏙️ *1. Cities* — Large, permanent settlements (Ur had 65,000 people in 2000 BCE!)\n🌾 *2. Agriculture* — Surplus food production freed people for other work\n✍️ *3. Writing* — Recording information (cuneiform, hieroglyphs, Indus script)\n⚖️ *4. Government* — Laws, rulers, bureaucracy to organize society\n⛪ *5. Religion* — Shared beliefs that unified large populations\n🎨 *6. Social classes* — Priests, warriors, merchants, farmers, slaves\n🔧 *7. Technology* — Tools, architecture, engineering achievements\n\nThe key innovation was *agriculture* (the Neolithic Revolution, ~10,000 BCE). When humans stopped hunting and started farming, they could settle in one place, grow surplus food, and free some people to become priests, soldiers, craftsmen, and rulers.\n\nAlmost ALL early civilizations arose near *rivers* — the Tigris-Euphrates, Nile, Indus, and Yellow River. Rivers provided water for irrigation, fertile flood soil, fish for food, and transportation for trade. 🌊",
      highlight: "7 characteristics define civilization: Cities, Agriculture, Writing, Government, Religion, Social Classes, and Technology! 🏛️",
    },
    {
      id: 'mesopotamia',
      title: 'Mesopotamia — Cradle of Civilization 🏗️',
      color: '#FF9F1C',
      bgGradient: ['#2A1800', '#0D0D1A'],
      icon: '🏗️',
      svgIcon: 'construction',
      content: "Mesopotamia (\"land between rivers\" in Greek) lay between the Tigris and Euphrates rivers in modern-day Iraq. It's called the *Cradle of Civilization* because it gave humanity many \"firsts\":\n\n📜 *Cuneiform writing* (~3500 BCE) — The world's first writing system! Wedge-shaped marks pressed into clay tablets. Over 500,000 tablets have been found.\n\n☸️ *The wheel* (~3500 BCE) — First used for pottery, then adapted for carts and chariots.\n\n⚖️ *Code of Hammurabi* (~1754 BCE) — 282 laws carved on a stone stele. Famous for \"an eye for an eye.\" It established that law should be *written and public*.\n\n🏛️ *Ziggurats* — Massive stepped temples reaching toward the heavens. The Ziggurat of Ur was 30 meters tall!\n\n🔢 *Base-60 math* — This is why we have 60 seconds in a minute, 60 minutes in an hour, and 360° in a circle!\n\nKey civilizations within Mesopotamia: *Sumerians* (3500 BCE), *Akkadians* (2334 BCE, first empire under Sargon), *Babylonians* (Hammurabi), and *Assyrians* (fearsome military empire). The region fell to the Persian Empire in 539 BCE. 🗡️",
      highlight: "Mesopotamia gave us writing, the wheel, the first law code, and the reason your clock has 60 seconds! ⏰",
      formula: '60s × 60min = 3,600s/hr (base-60 legacy)',
    },
    {
      id: 'egypt',
      title: 'Ancient Egypt — Gift of the Nile 🏺',
      color: '#FFD166',
      bgGradient: ['#2A2200', '#0D0D1A'],
      icon: '🏺',
      svgIcon: 'sparkle',
      content: "\"Egypt is the gift of the Nile\" — Herodotus wrote this in 440 BCE, and he was right! Every year, the Nile flooded, depositing rich silt that made the desert bloom. Ancient Egypt lasted *3,000 years* (3100-30 BCE) — the longest-lasting civilization in history!\n\n🔺 *Pyramids* — The Great Pyramid of Giza (built ~2560 BCE) used 2.3 million limestone blocks, each weighing ~2.5 tons. It was the tallest structure on Earth for 3,800 years! Its base is level to within 2.1 cm across 230 meters — incredible precision.\n\n✍️ *Hieroglyphs* — 700+ symbols combining pictures and sounds. The Rosetta Stone (found 1799) unlocked them: same text in hieroglyphs, Demotic, and Greek!\n\n🧬 *Mummification* — 70-day process to preserve bodies for the afterlife. Organs removed (except the heart!), body dried with natron salt, wrapped in linen.\n\n💊 *Medicine* — The Edwin Smith Papyrus (~1600 BCE) describes 48 surgical cases with rational treatments — no magic! Egyptians performed brain surgery, set broken bones, and had dentists.\n\n📅 *Calendar* — 365-day calendar with 12 months of 30 days + 5 extra days. Rome later adopted and modified it — the basis of our modern calendar! ☀️",
      highlight: "Egypt lasted 3,000 years, built the Great Pyramid with 2.3 million blocks, and invented the 365-day calendar we still use! 🏛️",
    },
    {
      id: 'indus',
      title: 'Indus Valley — The Forgotten Giants 🌊',
      color: '#4ECDC4',
      bgGradient: ['#0A2520', '#0D0D1A'],
      icon: '🌊',
      svgIcon: 'water',
      content: "The *Indus Valley Civilization* (3300-1300 BCE) in modern Pakistan/India was the LARGEST ancient civilization by area — bigger than Egypt and Mesopotamia combined! Yet it was \"forgotten\" until 1921 when archaeologists discovered Mohenjo-daro and Harappa.\n\n🏙️ *Urban planning* — The world's FIRST planned cities! Grid-pattern streets, standardized brick sizes (4:2:1 ratio — used everywhere across 1,500 km!), public buildings, and granaries.\n\n🚿 *Drainage & sanitation* — Every house had a private bathroom connected to covered drains under the streets! The \"Great Bath\" of Mohenjo-daro (12×7 meters) was the world's first public pool/bath. This sanitation level wasn't matched in Europe until the 1800s! 🤯\n\n⚖️ *Standardized weights* — Precise cubic stone weights following a binary sequence: 1, 2, 4, 8, 16, 32, 64... This suggests organized trade and government regulation.\n\n🔤 *Undeciphered script* — Over 4,000 inscriptions found, but the Indus script remains a MYSTERY! About 400 symbols. Computer analysis suggests it's a real language, but we can't read it.\n\nThe civilization's decline (~1900 BCE) is debated: drought, river course changes, earthquakes, or a combination. No evidence of invasion contradicts earlier theories. 🌊",
      highlight: "The Indus Valley had the world's first planned cities with drainage — sanitation that Europe didn't match for 3,000 years! 🚿",
    },
    {
      id: 'china',
      title: 'Ancient China — The Middle Kingdom 🏯',
      color: '#FF6B9D',
      bgGradient: ['#2A0D18', '#0D0D1A'],
      icon: '🏯',
      svgIcon: 'flag',
      content: "Ancient China called itself *Zhongguo* (\"Middle Kingdom\") — believing it was the center of the world. Chinese civilization is the oldest *continuous* civilization, spanning from the Xia Dynasty (~2070 BCE) to today!\n\n🧱 *The Great Wall* — Built across multiple dynasties (started ~7th century BCE, major construction under Qin Shi Huang 221 BCE). Total length: over *21,196 km* — visible from low orbit! It took over 2,000 years and millions of workers.\n\n*The Four Great Inventions* changed the entire world:\n📄 *Paper* (105 CE, Cai Lun) — Before paper: bamboo strips, silk, clay. Paper spread to the Arab world (751 CE) then Europe (12th century).\n🧭 *Compass* (~200 BCE) — First used for feng shui, later for navigation. Enabled the Age of Exploration!\n🧨 *Gunpowder* (~850 CE, Tang Dynasty) — Originally used for fireworks and Taoist alchemy. Later: rockets, bombs, then spread to Europe.\n🖨️ *Printing* (868 CE, block printing; 1040 CE, movable type by Bi Sheng) — 400 years before Gutenberg!\n\n🐉 *Silk Road* — A 7,000 km trade network connecting China to Rome. Not just silk — ideas, religions, diseases, and technologies traveled both ways. A shirt in Rome cost a soldier's yearly salary! 🎭\n\n👨‍🏫 *Confucius* (551-479 BCE) emphasized moral governance, filial piety, and education — his teachings shaped East Asian culture for 2,500 years.",
      highlight: "China's Four Great Inventions — paper, compass, gunpowder, printing — literally reshaped every civilization on Earth! 📄🧭🧨🖨️",
    },
    {
      id: 'greece',
      title: 'Ancient Greece — Birth of Western Thought 🏛️',
      color: '#6C63FF',
      bgGradient: ['#1A1040', '#0D0D1A'],
      icon: '🏛️',
      svgIcon: 'balance',
      content: "Ancient Greece wasn't a single country but a collection of *city-states* (poleis) — Athens, Sparta, Corinth, Thebes — often at war with each other but united by language, religion, and culture.\n\n🗳️ *Democracy* — Athens created it in 508 BCE under Cleisthenes. Every male citizen could vote directly on laws in the Assembly (Ekklesia). About 40,000 citizens — but women, slaves, and foreigners were excluded.\n\n🧠 *Philosophy* — The \"Big Three\": Socrates (questioning everything), Plato (ideal forms, *The Republic*), Aristotle (logic, biology, physics — tutor of Alexander the Great!). The word \"philosophy\" literally means \"love of wisdom.\"\n\n🏟️ *Olympic Games* — Started 776 BCE in Olympia. Athletes competed nude! Only men could participate. Winners got olive wreaths. Wars paused during the Olympics (Olympic Truce).\n\n📐 *Mathematics* — Pythagoras (a²+b²=c²), Euclid (*Elements* — the most influential math textbook for 2,000 years), Archimedes (pi, levers, \"Eureka!\").\n\n🎭 *Theater* — Greeks invented drama! Tragedies (Sophocles' *Oedipus Rex*) and comedies (Aristophanes) performed in open-air amphitheaters seating 14,000. The word \"theater\" comes from Greek *theatron* (\"viewing place\"). 🎭",
      highlight: "Greece gave us democracy, philosophy, the Olympics, and the mathematical foundations we still use today! 🏛️",
      formula: 'a² + b² = c² (Pythagoras, ~530 BCE)',
    },
    {
      id: 'rome',
      title: 'Roman Empire — All Roads Lead to Rome 🛤️',
      color: '#C3B1E1',
      bgGradient: ['#1A1028', '#0D0D1A'],
      icon: '🛤️',
      svgIcon: 'shield',
      content: "Rome grew from a small city (founded 753 BCE, legend says by Romulus & Remus raised by a wolf!) into the greatest empire the Western world had ever seen — spanning 5 million km² and ~56 million people at its peak.\n\n🛤️ *Roads* — 400,000 km of roads connected the empire! Built in layers (stone foundation, gravel, paving stones) — some still exist after 2,000 years. Couriers could travel 80 km/day. \"All roads lead to Rome\" was literally true.\n\n🏟️ *Engineering* — Romans invented *concrete* (opus caementicium, using volcanic ash) that's stronger than modern concrete! The Pantheon's unreinforced concrete dome (43m span) built in 126 CE is STILL the world's largest. Aqueducts carried 1 million m³ of water daily to Rome.\n\n⚖️ *Law* — Roman law is the foundation of legal systems in most of Europe and the Americas. Concepts like \"innocent until proven guilty,\" right to a fair trial, and written statutes all come from Rome.\n\n🏛️ *Republic → Empire* — Rome was a Republic (509-27 BCE) with a Senate, then became an Empire under Augustus. Julius Caesar's assassination (44 BCE, \"Et tu, Brute?\") is history's most famous political murder.\n\n📝 *Latin* — The Roman language evolved into Italian, Spanish, French, Portuguese, and Romanian. Over 60% of English words have Latin roots! 🗣️",
      highlight: "Roman concrete is stronger than modern concrete, their roads lasted 2,000 years, and 60% of English words come from their language! 🏛️",
    },
    {
      id: 'maya',
      title: 'Maya Civilization — Masters of Time 🗿',
      color: '#00E5A0',
      bgGradient: ['#001A10', '#0D0D1A'],
      icon: '🗿',
      svgIcon: 'star',
      content: "While Europe was in the Middle Ages, the Maya had already built stunning pyramid-cities, a writing system, and the most accurate ancient calendar — all without metal tools, the wheel (for transport), or draft animals!\n\n📅 *Calendar systems* — The Maya used THREE calendars simultaneously: The *Haab* (365-day solar), *Tzolk'in* (260-day religious), and the *Long Count* (tracking thousands of years). Their year length calculation: 365.2420 days — just 0.0002 days off the true value! More accurate than the European Gregorian calendar of 1582.\n\n0️⃣ *Zero* — The Maya independently invented the concept of zero around 350 CE — one of only three civilizations to do so (along with India and Babylon). This was centuries before zero reached Europe!\n\n🌟 *Astronomy* — Maya astronomers predicted eclipses, tracked Venus with 99.9% accuracy, and aligned temples to astronomical events. The descending serpent shadow at Chichén Itzá on the equinox required stunning mathematical precision. 🐍\n\n🍫 *Chocolate* — The Maya were the first to cultivate cacao and make *xocoatl* (bitter chocolate drink). They used cacao beans as currency!\n\n*\"Disappearance\"* — The Maya didn't vanish! Classic cities were abandoned (~900 CE, likely due to drought/warfare), but *6 million Maya people* live in Central America today, speaking 30+ Maya languages! 🌱",
      highlight: "Maya calendars were more accurate than European ones, they independently invented zero, and 6 million Maya people are alive today! 🗿",
    },
    {
      id: 'persia',
      title: 'Persian Empire — The First Superpower 🌐',
      color: '#FF6B6B',
      bgGradient: ['#2A0D0D', '#0D0D1A'],
      icon: '🌐',
      svgIcon: 'globe',
      content: "The *Achaemenid Persian Empire* (550-330 BCE) was the world's first superpower — at its peak under Darius I, it stretched from Egypt to India, controlling 44% of the world's population (~50 million people!). 🌍\n\n📜 *Cyrus the Great* (559-530 BCE) — Founded the empire by conquering Babylon in 539 BCE. The *Cyrus Cylinder* is considered the world's first declaration of human rights! It decreed religious freedom, abolished slavery, and allowed conquered peoples to keep their customs.\n\n📮 *Royal Road & Postal system* — The 2,700 km Royal Road from Sardis to Susa had relay stations every 25 km. Mounted couriers could deliver a message across the empire in just 7 days! Herodotus wrote: \"Neither snow nor rain nor heat nor darkness stops these couriers\" — sound familiar? It inspired the US Postal Service motto! ✉️\n\n🌸 *Paradise gardens* — The word \"paradise\" comes from the Old Persian *pairidaeza* (\"walled garden\"). Persian gardening influenced gardens worldwide.\n\n💧 *Qanats* — Underground water channels stretching up to 70 km, using gravity to bring mountain water to desert cities. Some built 2,500 years ago STILL function today!\n\nThe empire fell to Alexander the Great in 330 BCE, but Persian culture profoundly influenced Greek, Roman, and Islamic civilizations. 🌟",
      highlight: "Persia controlled 44% of the world's population, issued the first human rights declaration, and inspired the US Postal Service motto! 📮",
    },
    {
      id: 'legacy',
      title: 'Legacy — Ancient Ideas in YOUR Life 🔗',
      color: '#A8EDEA',
      bgGradient: ['#0A1A18', '#0D0D1A'],
      icon: '🔗',
      svgIcon: 'link',
      content: "Ancient civilizations didn't disappear — their innovations became the *foundation of modern life*. Nearly everything you use daily has ancient roots:\n\n⏰ *Time* — 60 seconds/minute, 60 minutes/hour? Mesopotamian base-60 math. 24-hour day? Egyptian sundials. 7-day week? Babylonian astronomy (one day per visible celestial body).\n\n📝 *Alphabet* — Phoenician → Greek → Latin → English. The letter A was originally an upside-down ox head (the Phoenician letter *aleph* 𐤀)!\n\n🏛️ *Government* — Democracy from Athens. Republic/Senate from Rome. \"Innocent until proven guilty\" from Roman law. Federal postal system inspired by Persia.\n\n📐 *Math* — Hindu-Arabic numerals (1,2,3...) from India via Arab traders. Zero from Maya/India. Geometry from Egypt/Greece. Algebra from Babylonian/Arab mathematicians.\n\n🏗️ *Architecture* — Concrete from Rome. Arches from Mesopotamia. Domes from Rome. City planning grids from the Indus Valley.\n\n💊 *Medicine* — Surgical techniques from Egypt. Hippocratic oath from Greece. Herbal medicine from China.\n\n🍫 *Food* — Chocolate from Maya. Wheat from Mesopotamia. Rice from China. The very concept of *restaurants* traces to ancient Roman *thermopolia*!\n\nEvery time you check the time, vote, use a number, walk on a road, or eat chocolate — you're using ancient technology. YOU are living proof that these civilizations succeeded beyond their wildest dreams! 🌟",
      highlight: "Your clock, alphabet, laws, math, roads, and even chocolate ALL come from ancient civilizations — you use ancient tech every day! 🔗",
    },
  ],

  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Civilization Explorer Lab 🏛️🗺️",
    description: "Map ancient empires, travel through time, compare civilizations & match achievements! 🌍",
    hint: "Try the Timeline mode to see which civilizations existed at the same time — then Compare mode to see who excelled at what! Use Match mode to test your knowledge of ancient achievements. 🏛️",
    scientistModeHint: "In Scientist Mode 🧑‍🔬: unlock population growth data, trade route analysis, and GDP estimates for ancient economies!",
  },

  // ── DO YOU KNOW WHY (5) ─────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why there are 60 seconds in a minute and 360 degrees in a circle? ⏰",
      answer: "The Sumerians of Mesopotamia (~3500 BCE) used a base-60 number system! They chose 60 because it's divisible by 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, and 30 — making fractions easy. This system spread to Babylonian astronomy, then Greek astronomy, then medieval clocks. Over 5,000 years later, every clock you see still runs on Sumerian math! 🔢",
      emoji: '🤔',
    },
    {
      id: 'dyk2',
      question: "Do you know why ALL major ancient civilizations developed near rivers? 🌊",
      answer: "Rivers solved the 4 biggest survival problems: 1) Water for irrigation = food surplus = freed people for other jobs. 2) Annual floods deposited mineral-rich silt = free fertilizer. 3) Rivers = highways for trade (boats > walking). 4) Fish = reliable protein source. The Tigris-Euphrates, Nile, Indus, and Yellow River each independently birthed civilizations — proving rivers are the #1 prerequisite for complex society! 🌾",
      emoji: '🌟',
    },
    {
      id: 'dyk3',
      question: "Do you know why the Maya civilization 'disappeared' — or did it? 🗿",
      answer: "The Maya NEVER disappeared! Classic-era cities were abandoned around 900 CE, likely due to prolonged drought (tree ring analysis confirms a 200-year drought), overpopulation, warfare, and deforestation. But the people survived! Today, over 6 MILLION Maya people live in Guatemala, Mexico, Belize, and Honduras, speaking 30+ Maya languages. The 'Mystery of the Missing Maya' is a European myth — they've been there the whole time! 🌱",
      emoji: '💡',
    },
    {
      id: 'dyk4',
      question: "Do you know why Roman concrete lasts 2,000 years but modern concrete cracks in 50? 🏛️",
      answer: "Romans mixed volcanic ash (pozzolana) with lime and seawater. Scientists discovered in 2017 that seawater actually makes it STRONGER over time — it causes a mineral called tobermorite to grow in the cracks, reinforcing the structure! Modern Portland cement doesn't have this self-healing property. The Pantheon's unreinforced dome (43m span, built 126 CE) is STILL the world's largest — after 1,900 years! Engineers today are studying Roman recipes to make better concrete. 🧱",
      emoji: '🤔',
    },
    {
      id: 'dyk5',
      question: "Do you know why the US Postal Service motto talks about 'neither snow nor rain'? 📮",
      answer: "It comes from the Greek historian Herodotus describing the PERSIAN postal system from 2,500 years ago! He wrote about the Royal Road's couriers: 'Neither snow nor rain nor heat nor gloom of night stays these couriers from the swift completion of their appointed rounds.' The Persian Angarium system had relay stations every 25 km, with fresh horses — a message could cross the empire (2,700 km) in just 7 days! The USPS inscribed this ancient Persian praise on their New York headquarters in 1914. ✉️",
      emoji: '💡',
    },
  ],

  // ── QUIZ (20) ───────────────────────────────
  quiz: [
    { id: 'q1', question: "What is Mesopotamia often called? 🏗️", options: ['Cradle of Civilization', 'Gift of the Nile', 'Middle Kingdom', 'Eternal City'], answer: 0, explanation: "Mesopotamia is the 'Cradle of Civilization' — it gave us writing, the wheel, law codes, and base-60 math! 🏛️" },
    { id: 'q2', question: "Which river was crucial to Ancient Egypt? 🌊", options: ['Tigris', 'Indus', 'Nile', 'Yellow River'], answer: 2, explanation: "The Nile's annual floods deposited fertile silt, making agriculture possible in the desert. Herodotus called Egypt 'the gift of the Nile!' 🌊" },
    { id: 'q3', question: "How many stone blocks make up the Great Pyramid? 🔺", options: ['230,000', '2.3 million', '23 million', '230 million'], answer: 1, explanation: "2.3 million limestone blocks, each averaging 2.5 tons! The base is level to within 2.1 cm across 230 meters. Built ~2560 BCE. 🏛️" },
    { id: 'q4', question: "What is special about the Indus Valley script? 🔤", options: ['It used 26 letters', 'It read right to left', 'It remains undeciphered', 'It was numeric only'], answer: 2, explanation: "Over 4,000 inscriptions with ~400 symbols have been found, but the Indus script is STILL undeciphered — one of archaeology's greatest mysteries! 🔤" },
    { id: 'q5', question: "Who invented paper? 📄", options: ['Egyptians', 'Greeks', 'Chinese (Cai Lun)', 'Romans'], answer: 2, explanation: "Cai Lun invented paper in 105 CE using bark, hemp, and rags. It didn't reach Europe until the 12th century — over 1,000 years later! 📄" },
    { id: 'q6', question: "What did Athens create in 508 BCE? 🗳️", options: ['The first army', 'Democracy', 'The first theater', 'The alphabet'], answer: 1, explanation: "Cleisthenes established democracy in Athens. Every male citizen could vote directly on laws. It's the foundation of modern democratic governments! 🗳️" },
    { id: 'q7', question: "What is the Pythagorean theorem? 📐", options: ['E=mc²', 'a²+b²=c²', 'F=ma', 'πr²'], answer: 1, explanation: "a² + b² = c² — the relationship between the sides of a right triangle. Attributed to Pythagoras (~530 BCE), though the Babylonians knew it 1,000 years earlier! 📐" },
    { id: 'q8', question: "How long is the Great Wall of China? 🧱", options: ['2,100 km', '6,400 km', '21,196 km', '50,000 km'], answer: 2, explanation: "Over 21,196 km including all branches! Built across multiple dynasties starting from the 7th century BCE. It's NOT visible from space with the naked eye — that's a myth! 🧱" },
    { id: 'q9', question: "What did Cyrus the Great's Cylinder declare? 📜", options: ['War on Greece', 'Human rights & religious freedom', 'Himself as a god', 'Building the pyramids'], answer: 1, explanation: "The Cyrus Cylinder (539 BCE) declared religious freedom, abolished slavery, and allowed conquered peoples to keep customs — the world's first human rights charter! 📜" },
    { id: 'q10', question: "Who independently invented the concept of zero? 0️⃣", options: ['Romans and Greeks', 'Egyptians and Persians', 'Maya, India, and Babylon', 'Chinese and Japanese'], answer: 2, explanation: "Only three civilizations independently discovered zero: Maya (~350 CE), India (~5th century CE), and Babylon (~300 BCE). Romans had NO zero — try math with Roman numerals! 0️⃣" },
    { id: 'q11', question: "What made Roman concrete so special? 🏛️", options: ['It was painted', 'It used volcanic ash and gets stronger with seawater', 'It was made of gold', 'It was lighter than air'], answer: 1, explanation: "Roman concrete (opus caementicium) used volcanic ash and seawater, which causes strengthening minerals to grow over centuries. The Pantheon dome still stands after 1,900 years! 🧱" },
    { id: 'q12', question: "How accurate was the Maya calendar? 📅", options: ['Off by 30 days', 'Off by 7 days', 'Off by 0.0002 days', 'Perfectly accurate'], answer: 2, explanation: "The Maya calculated the year as 365.2420 days — the true value is 365.2422. They were off by just 0.0002 days! More accurate than the European Gregorian calendar! 📅" },
    { id: 'q13', question: "What is the Rosetta Stone? 🗿", options: ['A magical gemstone', 'A text in 3 scripts that unlocked hieroglyphs', 'A Roman building', 'A Maya calendar'], answer: 1, explanation: "Found in 1799, the Rosetta Stone has the same text in hieroglyphs, Demotic, and Greek. Jean-François Champollion used it to decode hieroglyphs in 1822! 🔑" },
    { id: 'q14', question: "What does 'Zhongguo' (China's name for itself) mean? 🏯", options: ['Dragon Land', 'Middle Kingdom', 'Great Empire', 'Silk Country'], answer: 1, explanation: "Zhongguo (中国) means 'Middle Kingdom' — ancient Chinese believed their civilization was the center of the world! 🌏" },
    { id: 'q15', question: "How many km of roads did the Roman Empire build? 🛤️", options: ['4,000 km', '40,000 km', '400,000 km', '4 million km'], answer: 2, explanation: "400,000 km of roads! Built in layers of stone and gravel. Some are still used today, 2,000 years later. Couriers could travel 80 km per day. 🛤️" },
    { id: 'q16', question: "Where does the word 'paradise' come from? 🌸", options: ['Greek mythology', 'Old Persian (pairidaeza = walled garden)', 'Egyptian hieroglyphs', 'Latin religion'], answer: 1, explanation: "From Old Persian 'pairidaeza' meaning 'walled garden.' Persian emperors built elaborate gardens that inspired the concept of paradise in multiple religions! 🌸" },
    { id: 'q17', question: "What brick ratio did the Indus Valley use everywhere? 🧱", options: ['1:1:1', '3:2:1', '4:2:1', '5:3:1'], answer: 2, explanation: "EVERY Indus Valley brick across 1,500 km was 4:2:1 ratio — suggesting a centralized authority enforcing standards across an enormous area! Amazing engineering standardization. 🧱" },
    { id: 'q18', question: "What was cacao used as by the Maya? 🍫", options: ['Medicine only', 'Paint pigment', 'Currency and drink', 'Building material'], answer: 2, explanation: "Maya used cacao beans as money AND made xocoatl (bitter chocolate drink)! A rabbit cost 10 beans, a slave cost 100. They invented chocolate! 🍫" },
    { id: 'q19', question: "How fast could a message cross the Persian Empire's Royal Road? 📮", options: ['1 day', '7 days', '30 days', '1 year'], answer: 1, explanation: "Just 7 days across 2,700 km! Relay stations every 25 km with fresh horses. Normal travel took 90 days. The postal system inspired Herodotus's famous quote about couriers. ✉️" },
    { id: 'q20', question: "How many of the 7 characteristics of civilization must a society have? 🏛️", options: ['At least 3', 'Exactly 5', 'All 7', 'At least 1'], answer: 2, explanation: "All 7: Cities, Agriculture, Writing, Government, Religion, Social Classes, and Technology. Missing any one, and historians classify it as a 'complex society' rather than a full civilization! 🏛️" },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['industrial_revolution', 'world_wars', 'colonization', 'indian_freedom'],
};
