export default {
  id: 'chemical_bonding',
  title: 'Chemical Bonding',
  subtitle: 'Ionic, Covalent & Metallic — the glue of matter 🔗',
  emoji: '🔗',
  category: 'Chemistry',
  accentKey: 'chemical',

  hook: {
    question: "Why doesn't the diamond on a ring just crumble into pencil dust? 💎 After all, diamond and pencil lead are BOTH made of pure carbon atoms — literally the same element!",
    reveal: "Diamond has each carbon atom covalently bonded to 4 neighbors in a rigid 3D tetrahedral lattice — one of the strongest structures in nature! Each C-C bond releases 346 kJ/mol of energy. Breaking every bond in a 1-carat diamond would need enough energy to lift a car 2 meters off the ground! Meanwhile, pencil graphite has weak van der Waals forces between flat carbon sheets — that's why it slides right off. same atoms, wildly different bonds! 🤯",
    emoji: '💭',
  },

  theory: [
    {
      id: 'what_is_bonding',
      title: 'What is Chemical Bonding? 🔗',
      color: '#4ECDC4',
      bgGradient: ['#143430', '#0D0D1A'],
      icon: '🔗',
      svgIcon: 'link',
      content: "Atoms are almost never found alone in nature. They join together through *chemical bonds* — forces of attraction that hold atoms together in molecules and compounds. 🧲\n\nBut *why* do atoms bond? The answer lies in their electrons. In 1916, Gilbert Newton Lewis proposed that atoms bond to achieve a *stable electron configuration* — typically 8 valence electrons, known as the *octet rule*. 🎯\n\nThink of it like everyone wanting a full pizza 🍕 — atoms with incomplete outer shells 'share' or 'trade' electron slices with other atoms until everyone is satisfied!",
      highlight: "Atoms bond by transferring, sharing, or delocalizing electrons to reach a stable configuration — the octet rule! 🎯",
    },
    {
      id: 'octet_lewis',
      title: 'Lewis Structures & the Octet Rule 📝',
      color: '#6C63FF',
      bgGradient: ['#1A1040', '#0D0D1A'],
      icon: '📝',
      svgIcon: 'molecule',
      content: "A *Lewis dot structure* shows how valence electrons are arranged around atoms in a molecule. Each dot represents one valence electron. 🔵\n\nTo draw a Lewis structure:\n1️⃣ Count total valence electrons from all atoms\n2️⃣ Place bonding pairs (shared) between bonded atoms\n3️⃣ Fill remaining as lone pairs to satisfy the octet\n\nThe *shared pairs formula* helps:\n*Shared e⁻ = Needed − Available*\nwhere Needed = 8 per atom (2 for H), Available = sum of valence electrons.\n\nLewis structures also show *double bonds* (4 shared e⁻, like O₂) and *triple bonds* (6 shared e⁻, like N₂ — one of the strongest bonds at 945 kJ/mol!). ⚡",
      highlight: "Lewis structures reveal bonding: Shared pairs = Needed electrons − Available electrons! 📐",
    },
    {
      id: 'bond_types',
      title: 'Ionic vs Covalent vs Metallic ⚡',
      color: '#FF9F1C',
      bgGradient: ['#2A1800', '#0D0D1A'],
      icon: '⚡',
      svgIcon: 'lightning',
      content: "The *electronegativity difference* (ΔEN) between two atoms determines the bond type:\n\n🔴 *ΔEN ≥ 1.7 → Ionic bond*\nOne atom steals electrons completely. Sodium (EN=0.9) meets Chlorine (EN=3.0): ΔEN = 2.1 → Na⁺Cl⁻. NaCl forms a crystal lattice! 💎\n\n🟡 *0.4 < ΔEN < 1.7 → Polar covalent*\nElectrons are shared but pulled toward the more electronegative atom. In HF: ΔEN = 1.9 → the electron cloud shifts toward Fluorine, creating partial charges δ⁺H—Fδ⁻. 🧲\n\n🟢 *ΔEN ≤ 0.4 → Nonpolar covalent*\nElectrons are shared equally. In H₂: ΔEN = 0, perfectly symmetrical sharing! ⚖️",
      highlight: "ΔEN determines the bond: <0.4 = nonpolar covalent, 0.4-1.7 = polar covalent, >1.7 = ionic! ⚡",
    },
    {
      id: 'vsepr_geometry',
      title: 'Molecular Shape: VSEPR Theory 🏗️',
      color: '#FF6B9D',
      bgGradient: ['#2A0D18', '#0D0D1A'],
      icon: '🏗️',
      svgIcon: 'atom',
      content: "The *shape* of a molecule determines its properties! VSEPR theory (Valence Shell Electron Pair Repulsion) predicts geometry by saying: *electron pairs around a central atom repel each other and arrange as far apart as possible*. 🎯\n\nKey geometries:\n📐 *Linear* (180°): CO₂\n📐 *Trigonal planar* (120°): BF₃\n📐 *Tetrahedral* (109.5°): CH₄\n📐 *Bent* (104.5°): H₂O\n\nLone pairs take up MORE space than bonding pairs, which *squeezes* bond angles: methane (CH₄) = 109.5°, water (H₂O) = 104.5°. 📏",
      highlight: "VSEPR: electron pairs repel to max distance — this determines molecular geometry and polarity! 🏗️",
    },
    {
      id: 'intermolecular',
      title: 'Beyond Bonds: Intermolecular Forces 🌐',
      color: '#C3B1E1',
      bgGradient: ['#1A1028', '#0D0D1A'],
      icon: '🌐',
      svgIcon: 'globe',
      content: "Chemical bonds hold atoms within a molecule, but *intermolecular forces* (IMFs) hold molecules to each other. They're much weaker but they determine boiling point and state of matter! 🌡️\n\n*Types of IMFs:*\n💨 *London dispersion forces*: Present in ALL molecules. Caused by random electron movement.\n🧲 *Dipole-dipole forces*: Between polar molecules. \n💧 *Hydrogen bonds*: Special dipole-dipole when H is bonded to F, O, or N.",
      highlight: "Intermolecular forces determine melting/boiling points and the states of matter! 🌐",
    },
    {
      id: 'electronegativity',
      title: 'Electronegativity: The Tug-of-War 🧲',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧲',
      svgIcon: 'activity',
      content: "Electronegativity is an atom's ability to attract shared electrons in a bond. 🏹\n\nFluorine is the 'Goliath' of electronegativity with a score of 4.0, while Francium is a 'David' at 0.7. When atoms with different EN values bond, the electron cloud is asymmetrical. This creates a **Dipole** — a molecule with a positive and negative end. ⚡",
      highlight: "Higher electronegativity means the atom 'hogs' the electrons! 🐷",
    },
    {
      id: 'metallic_sea',
      title: 'Metallic Bonds: The Electron Sea 🌊',
      color: '#39FF14',
      bgGradient: ['#0A200A', '#050D0A'],
      icon: '🌊',
      svgIcon: 'anchor',
      content: "In metals, valence electrons are not bound to any specific atom. Instead, they form a **delocalized 'Sea of Electrons'** that flows freely around positive metal kernels! 🔋\n\nThis 'sea' acts as a glue, allowing metal ions to slide past each other without shattering (malleability) and carrying electric current across the material (conductivity). It's why metals are shiny, bendable, and hot! 🥄",
      highlight: "Free-flowing electrons give metals their unique strength and shine! ✨",
    },
    {
      id: 'bond_energy',
      title: 'Bond Energy: The Strength 🔋',
      color: '#FF4D6D',
      bgGradient: ['#2A0A10', '#050D0A'],
      icon: '🔋',
      svgIcon: 'zap',
      content: "Breaking a chemical bond always REQUIRES energy (Endothermic), while forming a bond always RELEASES energy (Exothermic). 🌡️\n\n**Bond Enthalpy** is the amount of energy needed to break 1 mole of a bond. Triple bonds (like N₂ at 945 kJ/mol) are much harder to break than single bonds (like C-C at 346 kJ/mol). Shorter bonds are generally stronger bonds!",
      highlight: "Triple bonds are the ultra-strength cables of the molecular world! 💪",
    },
    {
      id: 'coordinate_covalent',
      title: 'Coordinate Covalent: Charity 🤝',
      color: '#F97316',
      bgGradient: ['#201000', '#050D0A'],
      icon: '🤝',
      svgIcon: 'heart',
      content: "In a normal covalent bond, each atom contributes one electron. In a **Coordinate Covalent Bond**, one atom 'donates' BOTH electrons to the shared pair! 🎁\n\nThis happens in molecules like Carbon Monoxide (CO) or the Ammonium ion (NH₄⁺). One atom acts as a donor (Lewis Base) and the other as an acceptor (Lewis Acid). Once formed, it is identical to any other covalent bond!",
      highlight: "Sometimes one atom brings both 'slices' to the electron pizza party! 🍕",
    },
    {
      id: 'lattice_energy',
      title: 'Lattice Energy: Ionic Strength 🏛️',
      color: '#8B5CF6',
      bgGradient: ['#150A20', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'layers',
      content: "Ionic compounds don't form single molecules; they form massive, repeating 3D structures called **Crystal Lattices**. 💎\n\n**Lattice Energy** is the energy released when these gaseous ions come together to form the solid crystal. The smaller the ions and the higher their charge (like Mg²⁺ vs Na⁺), the stronger the lattice and the higher the melting point! This is why salt crystals are so hard and brittle.",
      highlight: "Lattice energy is the internal 'magnet strength' holding a crystal together! 🧲",
    },
  ],

  lab: {
    title: "The Atomic Matchmaker 🔗",
    description: "Welcome to the Bond Construction Zone. Violently smash atoms together to observe the transition from Covalent sharing to Ionic theft based on Electronegativity!",
    hint: "Try picking Fluorine (EN 4.0) to see it aggressively steal electrons from weaker metals!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time ΔEN values and calculated Lattice Enthalpy equations.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why water (H₂O) is liquid while methane (CH₄) is a gas? 💧",
      answer: "Hydrogen Bonding! Water molecules have strong dipoles that attract each other like magnets. Methane is nonpolar and only has weak London forces, so its molecules' grip on each other is too weak to stay liquid! 🧊",
      emoji: '🤔',
    },
    {
      id: 'dyk2',
      question: "Do you know why you can bend a metal spoon but salt shatters? 🥄",
      answer: "The 'Electron Sea'! In metals, atoms can slide past each other because the electrons are free. In salt, shifting atoms puts SAME charges next to each other (Cl⁻ next to Cl⁻), causing instant massive repulsion and a crack! 💥",
      emoji: '🌟',
    },
    {
      id: 'dyk3',
      question: "Do you know why noble gases (He, Ne, Ar) are so 'lazy'? 🎈",
      answer: "The Octet Rule! They already have a full house of 8 valence electrons. They are chemically 'satisfied' and have no reason to bond, share, or steal from anyone else! 💡",
      emoji: '💡',
    },
    {
      id: 'dyk4',
      question: "Do you know how geckos walk on walls? 🦎",
      answer: "London Dispersion Forces! Geckos have millions of tiny hair-like structures on their feet. These create enough temporary van der Waals forces with the wall surface to hold their entire body weight! 🧗",
      emoji: '🦎',
    },
    {
      id: 'dyk5',
      question: "Do you know why diamonds are the hardest material? 💎",
      answer: "3D Covalent Network! Unlike normal molecules, every single carbon atom in a diamond is covalently bonded to four others in a perfect, rigid 3D lattice. It's essentially one giant, single molecule! 🏗️",
      emoji: '💎',
    },
  ],

  quiz: [
    {
      id: 'q1',
      question: "What happens to electrons in an ionic bond? 🔋",
      options: ['They are shared equally', 'They are transferred from one atom to another', 'They are destroyed', 'They form a delocalized sea'],
      answer: 1,
      explanation: "In ionic bonds, electrons transfer from metal to nonmetal, creating oppositely charged ions! ⚡",
    },
    {
      id: 'q2',
      question: "What is the electronegativity threshold for an Ionic bond?",
      options: ['ΔEN > 0.4', 'ΔEN > 1.0', 'ΔEN > 1.7', 'ΔEN > 3.0'],
      answer: 2,
      explanation: "Pauling's scale suggests that a difference of 1.7 or more results in an ionic bond! 📊",
    },
    {
      id: 'q3',
      question: "How many valence electrons are needed for most atoms to be stable?",
      options: ['2', '4', '6', '8'],
      answer: 3,
      explanation: "This is the Octet Rule! Atoms strive for 8 electrons in their outer shell. 🎯",
    },
    {
      id: 'q4',
      question: "Which molecule is polar?",
      options: ['CO₂ (Linear)', 'H₂O (Bent)', 'CH₄ (Tetrahedral)', 'N₂'],
      answer: 1,
      explanation: "The bent shape of water keeps its polar bonds from cancelling out! 💧",
    },
    {
      id: 'q5',
      question: "What is the bond angle in a Tetrahedral molecule like Methane?",
      options: ['90°', '104.5°', '109.5°', '120°'],
      answer: 2,
      explanation: "Tetrahedral molecules repel electron pairs to exactly 109.5 degrees! 🏗️",
    },
    {
      id: 'q6',
      question: "Which bond is the strongest and shortest?",
      options: ['Single bond', 'Double bond', 'Triple bond', 'Hydrogen bond'],
      answer: 2,
      explanation: "Triple bonds share 6 electrons, pulling the atoms much tighter together! 💪",
    },
    {
      id: 'q7',
      question: "The 'delocalized sea of electrons' is found in...",
      options: ['Ionic bonds', 'Covalent bonds', 'Metallic bonds', 'Hydrogen bonds'],
      answer: 2,
      explanation: "Metallic bonds allow electrons to flow freely, which is why metals conduct electricity! 🌊",
    },
    {
      id: 'q8',
      question: "What happens during bond FORMATION?",
      options: ['Energy is absorbed', 'Energy is released', 'Nothing happens', 'Mass is lost'],
      answer: 1,
      explanation: "Bond formation is an EXOTHERMIC process—it releases energy! 🌡️",
    },
    {
      id: 'q9',
      question: "Which force is the strongest Intermolecular force?",
      options: ['London Dispersion', 'Dipole-Dipole', 'Hydrogen Bonding', 'Gravity'],
      answer: 2,
      explanation: "Hydrogen bonds are special, super-strong dipole attractions! 💧",
    },
    {
      id: 'q10',
      question: "A bond where one atom provides BOTH shared electrons is called:",
      options: ['Polar bond', 'Ionic bond', 'Coordinate Covalent', 'Double bond'],
      answer: 2,
      explanation: "In Coordinate Covalent bonds, one atom donates a lone pair to share with another! 🎁",
    },
    {
      id: 'q11',
      question: "What is Electronegativity?",
      options: ['The mass of an atom', 'The number of protons', 'The ability to attract shared electrons', 'The size of the nucleus'],
      answer: 2,
      explanation: "Electronegativity measures the 'tug' an atom has on bonding electrons! 🧲",
    },
    {
      id: 'q12',
      question: "Why are ionic compounds brittle?",
      options: ['They are too soft', 'They lack electrons', 'Shifted layers push same charges together', 'They are made of gas'],
      answer: 2,
      explanation: "Misaligning a crystal forces (+) ions next to (+) ions, causing an explosion of repulsion! 💥",
    },
    {
      id: 'q13',
      question: "Lattice Energy is specifically associated with...",
      options: ['Metal wires', 'Gas molecules', 'Ionic crystals', 'Lone pairs'],
      answer: 2,
      explanation: "Lattice energy is the strength of the 3D 'scaffolding' in ionic solids! 🏛️",
    },
    {
      id: 'q14',
      question: "VSEPR theory is based on...",
      options: ['Proton attraction', 'Electron pair repulsion', 'Atomic mass', 'Radioactivity'],
      answer: 1,
      explanation: "It stands for Valence Shell Electron Pair Repulsion! 🏗️",
    },
    {
      id: 'q15',
      question: "Which element has the HIGHEST Electronegativity?",
      options: ['Hydrogen', 'Oxygen', 'Fluorine', 'Sodium'],
      answer: 2,
      explanation: "Fluorine (4.0) is the most electron-hungry element on the periodic table! 👑",
    },
    {
      id: 'q16',
      question: "Bond Enthalpy is the energy required to...",
      options: ['Form a bond', 'Break a bond', 'Melt a crystal', 'Heat a gas'],
      answer: 1,
      explanation: "Breaking bonds is endothermic and requires an input of Enthalpy! 🔋",
    },
    {
      id: 'q17',
      question: "Which geometry has a bond angle of 180°?",
      options: ['Tetrahedral', 'Bent', 'Linear', 'Trigonal Planar'],
      answer: 2,
      explanation: "Linear molecules (like CO₂) keep their groups at maximum opposite ends! 📏",
    },
    {
      id: 'q18',
      question: "London Dispersion forces increase as...",
      options: ['Temperature drops', 'Molecule size/electrons increase', 'Electronegativity drops', 'Bonds get shorter'],
      answer: 1,
      explanation: "More electrons mean bigger temporary 'shifting' dipoles! 💨",
    },
    {
      id: 'q19',
      question: "An atom with 2 bonding and 2 lone pairs has what shape?",
      options: ['Linear', 'Tetrahedral', 'Bent', 'Trigonal Pyramidal'],
      answer: 2,
      explanation: "The two lone pairs push the bonds into a V-shape, like water! 💧",
    },
    {
      id: 'q20',
      question: "What is the primary factor in determining bond type?",
      options: ['Atomic Number', 'Difference in Electronegativity (ΔEN)', 'Specific Heat', 'Crystal Shape'],
      answer: 1,
      explanation: "The 'En gap' determines if atoms share (covalent) or steal (ionic)! ⚖️",
    },
  ],

  relatedTopics: ['chemical_reactions', 'periodic_trends', 'acids_bases_ph', 'organic_chemistry'],
};
