export default {
  id: 'matter_states',
  title: 'States of Matter',
  subtitle: 'Why everything exists in exactly the right form 🧊🌊💨',
  emoji: '⚗️',
  category: 'Foundations',
  accentKey: 'snowflake',

  hook: {
    question: "Did you know that plasma — the least-known state of matter — makes up over 99% of all visible matter in the universe? 🤯",
    reveal: "You've been taught there are 3 states of matter. There are actually at least 5 — and the one you weren't taught (plasma) is everywhere you look in the night sky. Every star, every lightning bolt, every neon sign is plasma. The other mystery state — Bose-Einstein condensate — was only created on Earth in 1995 and behaves like a superfluid with zero viscosity. Matter is far stranger than solid, liquid, gas. Understanding states of matter explains everything from why ice floats (saving all aquatic life), to how superconductors work, to what the inside of stars is made of. 🌟",
    emoji: '⚗️',
  },

  theory: [
    { id: 'solid', title: 'Solid: Locked in Place 🧊', color: '#74B9FF', bgGradient: ['#001020', '#05050A'], icon: '🧊', svgIcon: 'snowflake', content: "In a **solid**, particles are tightly packed in fixed positions — held in place by strong intermolecular forces. They vibrate in place but cannot move past each other.\n\n**Properties:**\n🔒 **Fixed shape and fixed volume**\n🔒 Very low compressibility (nearly incompressible)\n🔒 High density\n🔒 Slow diffusion (particles can't easily move)\n\n**Crystal vs Amorphous:**\n💎 **Crystalline solids** — particles in a regular, repeating 3D lattice: diamonds, salt (NaCl), metals, quartz. Long-range order. Sharp melting points because all bonds break simultaneously.\n🪟 **Amorphous solids** — particles in random arrangements: glass, rubber, plastic, wax. Short-range order only. Don't have a sharp melting point — they soften gradually (glass transition temperature).\n\n**Is glass actually a slow-flowing liquid?** This is a myth! Old windows are thicker at the bottom because glassblowers of the past installed them thicker-side-down. Glass flows at its melting point (~1400°C) — at room temperature, glass is rigid for millions of years. 🌟\n\n**Metals:** Metal atoms release electrons to form a 'sea of electrons' — explaining electrical conductivity, thermal conductivity, and metallic lustre! ⚡", highlight: "The myth that glass is a slow liquid is false — historical thick-bottomed windows were installed that way intentionally! 🧊" },
    { id: 'liquid', title: 'Liquid: The Flexible Middle 🌊', color: '#0984E3', bgGradient: ['#001A30', '#05050A'], icon: '🌊', svgIcon: 'waves', content: "In a **liquid**, particles are still close together but can slide past each other freely — intermolecular forces are strong enough to maintain volume but not shape.\n\n**Properties:**\n💧 **Fixed volume but no fixed shape** (takes container's shape)\n💧 Near-incompressible (hydraulic systems exploit this!)\n💧 Higher diffusion than solids\n💧 Surface tension (strong hydrogen bonds in water create a 'skin')\n\n**Surface tension** is why:\n🦟 Water striders walk on water\n💧 Round water drops form spheres (minimum surface area)\n🧼 Soap reduces surface tension (allowing water to penetrate fabrics)\n\n**Viscosity:** Resistance to flow. Honey (high viscosity) vs water (low viscosity). Temperature increases reduce viscosity — hot honey flows easily! This is why engine oil needs the right viscosity grade.\n\n**Water: The anomaly that made life possible:**\n❄️ Water EXPANDS when it freezes (most liquids contract)\n❄️ Ice is LESS dense than liquid water (H₂O hydrogen bonds)\n❄️ This means ice floats — keeping liquid water beneath it where life can survive! If ice sank, Earth's oceans would freeze solid and all aquatic life would die. 🐟\n\n**Capillary action:** Water rises in narrow tubes against gravity (how plants lift water from roots to leaves — 100 metres upward in tall trees!). 🌳", highlight: "Ice floating on water saved all aquatic life — if ice were denser than water like most substances, Earth's oceans would freeze solid! 🌊" },
    { id: 'gas', title: 'Gas: Maximum Freedom 💨', color: '#55EFC4', bgGradient: ['#001A14', '#05050A'], icon: '💨', svgIcon: 'waves', content: "In a **gas**, particles move at very high speeds (~500 m/s for N₂ at room temperature) with negligible intermolecular forces. Particles are ~10x further apart than in liquid.\n\n**Properties:**\n💨 **No fixed shape, no fixed volume** — expands to fill any container\n💨 **Highly compressible** (why gas canisters can store large quantities)\n💨 Fast diffusion (why smells spread quickly)\n💨 Low density (air at standard conditions: 1.2 kg/m³ vs water: 1000 kg/m³)\n\n**Kinetic Theory of Gases:**\nParticles are in constant, random motion. ALL gas behaviour can be explained by:\n1. Particle size is negligible vs space between them\n2. Collisions are perfectly elastic (no energy lost)\n3. Intermolecular forces are negligible\n\n**Gas Laws:**\n📊 **Boyle's Law:** P₁V₁ = P₂V₂ (pressure and volume are inversely proportional at constant T)\n📊 **Charles's Law:** V/T = constant (volume proportional to temperature in Kelvin)\n📊 **Gay-Lussac's:** P/T = constant (pressure proportional to temperature in Kelvin)\n📊 **Ideal Gas Law:** PV = nRT (combines all three!)\n\n**Real vs Ideal gases:** Real gases deviate under high pressure or low temperature (particles are no longer truly negligible). At extreme conditions: gases LIQUIFY. 💧", highlight: "Gas particles move at ~500 m/s at room temperature — the Ideal Gas Law PV=nRT predicts all gas behaviour from just these 4 variables! 💨" },
    { id: 'plasma', title: 'Plasma: The 4th State 🌟', color: '#FD79A8', bgGradient: ['#2A001A', '#05050A'], icon: '🌟', svgIcon: 'sparkle', content: "**Plasma** is a gas heated so extremely that electrons are stripped from atoms, creating a soup of free electrons and positively charged ions. It makes up **99% of all visible matter** in the universe.\n\n**Properties:**\n⚡ **Electrically conductive** (free electrons carry charge)\n⚡ Responds strongly to magnetic and electric fields\n⚡ Extremely high energy\n⚡ Glows (emits light as electrons recombine)\n\n**Plasma you've seen:**\n☀️ Stars (including the Sun) — entire stellar interiors are plasma\n⚡ Lightning bolts — the air ionises instantly into plasma at 30,000K!\n📺 Plasma TV screens — tiny plasma cells excite phosphors\n💡 Neon signs — neon gas ionised into plasma by electric current\n🔥 Flame (partially plasma)\n🌌 Aurora Borealis — solar wind plasma interacting with Earth's magnetic field\n\n**Nuclear Fusion and Plasma:**\nFusion reactors (ITER in France) contain plasma at 150,000,000°C — hotter than the SUN's core! The plasma is confined by magnetic fields (Tokamak design) because no physical container could withstand these temperatures.\n\n**Why fusion matters:** A fusion power plant burning sea water (deuterium) could power civilisation essentially forever with minimal waste. We've been 30 years away from achieving it for 60 years running — but ITER may finally crack it! ⚡", highlight: "Plasma makes up 99% of visible universe — ITER fusion reactor contains plasma at 150 million°C, 10x hotter than the Sun's core! 🌟" },
    { id: 'phase_changes', title: 'Phase Changes & Energy ♻️', color: '#FDCB6E', bgGradient: ['#2A1A00', '#05050A'], icon: '♻️', svgIcon: 'cycle', content: "Phase changes are the transitions between states, driven by energy (heat) changes:\n\n**Heating transitions:**\n🧊→🌊 **Melting/Fusion** — solid → liquid (absorbs energy, breaks lattice)\n🌊→💨 **Vaporisation**:\n  - **Evaporation** — surface only, below boiling point\n  - **Boiling** — throughout liquid at boiling point\n🧊→💨 **Sublimation** — solid → gas directly (dry ice CO₂, iodine, freeze-dried food)\n\n**Cooling transitions:**\n💨→🌊 **Condensation** — gas → liquid (dew, clouds, rain)\n🌊→🧊 **Freezing/Solidification** — liquid → solid\n💨→🧊 **Deposition** — gas → solid directly (frost on windows, snowflakes!)\n\n**Latent Heat — the hidden energy:**\nDuring a phase change, temperature DOES NOT CHANGE even though you're adding heat!\nThe energy goes into **breaking or forming bonds**, not heating.\n\n🌡️ Latent heat of fusion for water: 334 J/g (melting ice)\n🌡️ Latent heat of vaporisation: 2260 J/g (boiling water!) — 7x more!\n\nThis explains why:\n💧 Steam burns are worse than boiling water burns (steam deposits 2,260 J/g extra as it condenses)\n❄️ Sweating cools you — evaporation absorbs huge energy from your skin!\n☁️ Clouds release latent heat as water vapour condenses — powering storms! ⛈️", highlight: "Steam burns are worse than boiling water burns because steam deposits 2,260 J/g of latent heat as it condenses on your skin! ♻️" },
    { id: 'phase_diagrams', title: 'Phase Diagrams: Mapping Matter 📊', color: '#A29BFE', bgGradient: ['#10002A', '#05050A'], icon: '📊', svgIcon: 'chart', content: "A **phase diagram** maps which state of matter exists at each combination of temperature and pressure.\n\n**Key points on a phase diagram:**\n🔴 **Triple Point** — unique T&P where all three phases coexist simultaneously (for water: 0.01°C, 611.7 Pa)\n🔴 **Critical Point** — beyond this, liquid and gas become indistinguishable (supercritical fluid)\n📈 **Fusion curve** — boundary between solid and liquid\n📈 **Vaporisation curve** — boundary between liquid and gas\n📈 **Sublimation curve** — boundary between solid and gas\n\n**Water's unusual phase diagram:**\nThe fusion curve slopes BACKWARD (toward lower pressure) — uniquely, increasing pressure MELTS ice!\nThis is why:\n⛸️ Ice skating works — the small contact area creates enormous pressure, briefly melting the ice for lubrication (actually mostly friction heat)\n🧊 Glaciers flow — the ice at the base melts under the weight above\n\n**Supercritical fluids:**\nBeyond the critical point, a substance behaves like both liquid AND gas simultaneously:\n☕ Supercritical CO₂ (31°C, 73 atm) is used to decaffeinate coffee without solvents!\n🏭 Supercritical water is used in waste treatment — it dissolves organic compounds at high efficiency.\n🔬 Key for pharmaceutical processing, dry cleaning (replacing toxic solvents!)", highlight: "Water's fusion curve slopes backward — increasing pressure melts ice, which is why glaciers flow and ice skating works! 📊" },
    { id: 'bec', title: 'Bose-Einstein Condensate 🌌', color: '#6C5CE7', bgGradient: ['#0A001A', '#05050A'], icon: '🌌', svgIcon: 'galaxy', content: "**Bose-Einstein Condensate (BEC)** is the rarest state of matter — a gas cooled to within billionths of degrees of absolute zero (−273.15°C), where quantum effects dominate macroscopically.\n\n**History:** Predicted by Satyendra Nath Bose and Albert Einstein in 1924. First created in a lab by Cornell and Wieman at University of Colorado in 1995 → **Nobel Prize in Physics 2001**.\n\n**How it forms:**\nAt extremely low temperatures, atoms slow almost to a standstill. Quantum wavelengths of individual atoms become so large they OVERLAP — atoms lose individual identity and behave as one giant quantum object (single quantum state).\n\n**Bizarre properties:**\n🌀 **Superfluidity** — flows with ZERO viscosity, no friction. BEC flows upward and out of containers!\n🌀 **Vortex lattices** — when spun, forms precise quantised vortices (quantum mechanics visible at macroscopic scale)\n🌀 **Slows light** — Lene Hau slowed light to 17 m/h (bicycle speed!) through a BEC in 1999; later STOPPED it entirely\n🌀 **Atom lasers** — coherent matter waves emitted like laser photons\n\n**Temperature:** A few hundred nanokelvin (0.0000001 K) — the COLDEST places in the known universe! Colder than the cosmic microwave background radiation (2.7K). Scientists have made matter colder than outer space. 🥶", highlight: "Bose-Einstein Condensate slowed light to bicycle speed (17 m/h) and later STOPPED it entirely — the coldest matter in the known universe! 🌌" },
    { id: 'kinetic_theory', title: 'Kinetic Molecular Theory ⚡', color: '#00B894', bgGradient: ['#001A14', '#05050A'], icon: '⚡', svgIcon: 'lightning', content: "The **Kinetic Molecular Theory (KMT)** explains ALL observable properties of matter from particle-level behaviour:\n\n**Core assumptions:**\n1. Matter is made of tiny particles in constant, random motion\n2. The average kinetic energy of particles is proportional to temperature (in Kelvin)\n3. Collisions between particles and walls are perfectly elastic\n4. No intermolecular forces in ideal gases\n\n**KE = ½mv²** — particle kinetic energy relates mass and speed.\n\n**Why temperature = kinetic energy:**\n🌡️ Heat something → particles speed up → higher average KE → higher temperature\n🌡️ Cool something → particles slow down → lower KE → lower temperature\n🌡️ Absolute zero (0 K = −273.15°C) → minimum possible particle motion → minimum possible energy\n\n**Maxwell-Boltzmann distribution:**\nIn ANY gas sample, particles have a range of speeds — not all the same. A bell-shaped distribution where:\n• Some particles are very slow (just reflected from wall)\n• Most are near the average (related to temperature)\n• Some are very fast (random collision gains)\n\n**Why evaporation cools:**\nOnly the FASTEST particles escape the liquid surface (they have enough energy to overcome intermolecular forces). This removes the most energetic particles from the sample — so the remaining liquid's average kinetic energy drops → temperature decreases! ❄️", highlight: "Evaporation cools because only the fastest particles escape — removing them drops the average kinetic energy (temperature) of the remaining liquid! ⚡" },
    { id: 'intermolecular_forces', title: 'Intermolecular Forces 🔗', color: '#E17055', bgGradient: ['#2A0A00', '#05050A'], icon: '🔗', svgIcon: 'link', content: "**Intermolecular forces (IMF)** are attractions between molecules that determine physical properties — melting point, boiling point, viscosity, surface tension. They are NOT the same as chemical bonds within molecules.\n\n**Strongest to weakest:**\n\n💪 **Hydrogen bonds** — hydrogen bonded to F, O, or N forms a strong partial positive charge attracting a nearby F, O, or N. Up to 8x stronger than van der Waals.\n🔹 Water: O−H···O hydrogen bonds (explains water's anomalously high boiling point of 100°C — should be −80°C without H-bonds!)\n🔹 DNA: two strands held together by H-bonds between base pairs\n🔹 Protein folding: 3D structure maintained by H-bonds\n\n⚡ **Dipole-dipole interactions** — polar molecules attract oppositely charged ends\n\n🌊 **London Dispersion Forces (van der Waals)** — weakest but universal (exist in ALL molecules):\n• Temporary dipoles from electron movement cause attractions\n• Larger molecules = stronger London forces (more electrons)\n• This is why iodine (I₂) is solid, bromine (Br₂) is liquid, and chlorine (Cl₂) is gas at room temperature — same chemical structure, just more electrons and stronger forces as you go down the periodic table!\n\n🦎 **Gecko feet:** Van der Waals forces between billions of nano-scale hairs allow geckos to walk on ceilings — purely physics, no glue! 🔬", highlight: "Without hydrogen bonds, water would boil at −80°C and life would be impossible — gecko feet use van der Waals forces to walk on ceilings! 🔗" },
    { id: 'matter_cosmos', title: 'Dark Matter: 95% of the Universe 🌌', color: '#2D3436', bgGradient: ['#0A0A14', '#05050A'], icon: '🌌', svgIcon: 'blackhole', content: "Here's the most humbling fact in physics: **Ordinary matter (solid, liquid, gas, plasma) makes up only about 5% of the universe's total energy content.**\n\n**The other 95%:**\n🌑 **Dark Matter (~27%):** Matter that doesn't emit, absorb, or reflect light. Detected only through gravitational effects:\n• Galaxies rotate wrong — outer stars orbit too fast (extra mass must be there)\n• Gravitational lensing shows more mass than visible matter accounts for\n• Galaxy cluster collisions show mass distribution different from visible matter\n\n🌌 **Dark Energy (~68%):** Unknown energy causing the universe's expansion to ACCELERATE. Einstein's cosmological constant may describe it. Nobody knows what it is.\n\n**Candidates for dark matter:**\n🔮 WIMPs (Weakly Interacting Massive Particles)\n🔮 Axions\n🔮 Sterile neutrinos\n🔮 Primordial black holes\n\n**No dark matter particle has ever been directly detected.** The most sensitive detectors on Earth (deep underground to shield from cosmic rays) have found nothing. This is one of the biggest open questions in all of science.\n\n**The punchline:** Everything you've ever seen, touched, eaten, or thought about — every atom, every galaxy visible in the night sky — is just 5% of what exists. 🤯", highlight: "Everything you've ever seen or touched is only 5% of the universe — dark matter and dark energy make up the other 95%, and we have no idea what they are! 🌌" },
  ],

  lab: {
    title: "Phase Change Simulator ⚗️",
    description: "Control temperature and pressure to drive matter through all states — solid, liquid, gas, and plasma! Watch particles respond in real time.",
    hint: "Try hitting the triple point (0.01°C, low pressure) — or push temperature past 10,000K to ionise gas into plasma! 🌡️",
    scientistModeHint: "Scientist Mode: see real phase diagram coordinates, entropy calculations, and latent heat equations as you change state.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why water is the only common substance that becomes LESS dense when it freezes? ❄️", answer: "Water molecules form hydrogen bonds. In liquid water, these bonds constantly break and reform, allowing molecules to pack together relatively efficiently. When water freezes, ALL hydrogen bonds lock into a permanent hexagonal crystal lattice structure. This lattice actually has MORE SPACE between molecules than liquid water — ice is about 9% less dense. This expansion caused by the lattice structure is why your pipes burst when they freeze, why glaciers carve landscapes, and most importantly why ice floats on water, insulating the liquid below and making aquatic life possible through Arctic winters! ❄️", emoji: '❄️' },
    { id: 'dyk2', question: "Do you know why cooking at altitude takes longer? 🏔️", answer: "Boiling point depends on atmospheric pressure! At higher elevations, atmospheric pressure is lower. Since water boils when its vapour pressure equals atmospheric pressure, lower atmospheric pressure means water boils at lower temperatures. At sea level: 100°C. At the top of Mount Everest (8849m): only 69°C. Pasta and eggs need a specific temperature to cook — they take longer because the boiling water is cooler! Pressure cookers work in reverse — they increase pressure above 1 atm, raising the boiling point to 120°C+ and cooking food faster and more thoroughly. 🍳", emoji: '🏔️' },
    { id: 'dyk3', question: "Do you know why superhot steam at 120°C can exist as still a gas despite being above 100°C? 🌡️", answer: "100°C is the boiling point of water at 1 atmosphere (standard atmospheric pressure). But the boiling point changes with pressure! Inside a pressure cooker at 2 atmospheres, water boils at 120°C. At 200 atmospheres, water boils at around 365°C. Above the critical point (374°C, 218 atm), liquid and gas become indistinguishable — supercritical water simultaneously has the dissolving power of liquid and the diffusion of gas. It's used to destroy toxic waste! Steam at 120°C at 1 atm is 'superheated' — it exists as a gas because no pressure is forcing it to condense. 💧", emoji: '🌡️' },
    { id: 'dyk4', question: "Do you know why lightning heats air to 5 times the temperature of the Sun's surface? ⚡", answer: "The Sun's surface is about 5,500°C. A single lightning bolt heats the nearby air to ~30,000°C! This happens because lightning is an electric arc — billions of charged electrons accelerate through the air. They collide with nitrogen and oxygen molecules with such force that electrons are stripped from atoms, creating plasma in microseconds. The plasma instantly expands, creating the sound wave we hear as thunder. The bright flash IS the plasma glowing as electrons recombine with ions. All of this energy is packed into a channel 2-3cm wide! 🌩️", emoji: '⚡' },
    { id: 'dyk5', question: "Do you know why dry ice doesn't melt — it just disappears? 🌫️", answer: "Dry ice is solid carbon dioxide (CO₂). At normal atmospheric pressure, CO₂'s triple point is at −56.6°C. Below this, CO₂ can only be solid or gas — liquid CO₂ simply cannot exist at 1 atmosphere! The 'dry ice' goes straight from solid to gas (sublimation) at −78.5°C without ever forming a puddle of liquid. The cold fog you see around dry ice is condensed water vapour from the air being super-cooled, not CO₂ itself. To get liquid CO₂ you need more than 5.1 atmospheres of pressure — which is why CO₂ fire extinguishers release cloudy gas, not liquid. ☁️", emoji: '🌫️' },
  ],

  quiz: [
    { id: 'q1', question: "In which state of matter do particles have a fixed volume but no fixed shape? 🌊", options: ['Solid', 'Liquid', 'Gas', 'Plasma'], answer: 1, explanation: "Liquid particles are still close together (fixed volume) but can slide past each other freely (no fixed shape — takes container's shape). Solid = fixed volume AND shape. Gas = neither fixed! 🌊" },
    { id: 'q2', question: "Why does water expand when it freezes, unlike most substances? ❄️", options: ['Ice contains more air than liquid water', 'Water molecules form a hexagonal H-bond lattice in ice that has more space between molecules', 'Cold temperatures add mass to the water', 'Ice has different chemical composition to liquid water'], answer: 1, explanation: "Water's hydrogen bond lattice in ice creates hexagonal channels — ice is ~9% less dense than liquid water. This is why ice floats, pipes burst when frozen, and aquatic life survives Arctic winters under the ice! ❄️" },
    { id: 'q3', question: "What makes up 99% of all visible matter in the observable universe? 🌟", options: ['Solid matter (rocks and planets)', 'Liquid water in alien oceans', 'Gas clouds in nebulae', 'Plasma (stars, lightning, etc.)'], answer: 3, explanation: "Stars are plasma, lightning is plasma, and plasma permeates space. Every star you see in the night sky is an enormous ball of plasma. Gas and plasma together dominate the universe's visible matter — solid and liquid are comparatively rare! 🌟" },
    { id: 'q4', question: "What happens to temperature during a phase change (e.g. melting ice)? 🌡️", options: ['Temperature rises continuously as energy is added', 'Temperature stays constant while energy goes into breaking/forming bonds', 'Temperature drops temporarily then rises again', 'Temperature rises twice as fast during phase change'], answer: 1, explanation: "Latent heat: during melting (or boiling), all added energy breaks intermolecular bonds — none goes into kinetic energy. So temperature stays flat on a heating curve! This is why ice-water at 0°C stays at 0°C until the last bit of ice melts. 🌡️" },
    { id: 'q5', question: "What is the triple point of a substance? 📊", options: ['The temperature where it melts three times', 'The specific temperature and pressure where solid, liquid, and gas phases coexist simultaneously', 'The point where pressure triples its volume', 'The temperature where three different substances react'], answer: 1, explanation: "At the triple point, all three phases exist in equilibrium simultaneously! For water it is 0.01°C and 611.7 Pa (0.6% of atmospheric pressure). Phase diagrams plot which state exists at each T-P combination. 📊" },
    { id: 'q6', question: "Why does evaporating sweat cool your skin? ❄️", options: ['Water is naturally cold and removes body heat', 'Only the slowest-moving water molecules evaporate, leaving behind cooler water', 'Only the fastest-moving molecules have enough energy to escape the liquid, removing energy from the remaining liquid', 'Sweat dissolves heat energy from your skin surface'], answer: 2, explanation: "Evaporation is selective! Only the fastest molecules can escape the liquid surface (overcoming intermolecular forces). Removing the most energetic particles drops the average kinetic energy of those remaining — temperature falls! This is pure kinetic molecular theory! ⚡" },
    { id: 'q7', question: "What is a Bose-Einstein Condensate? 🌌", options: ['An extremely hot plasma found near black holes', 'A gas cooled to near absolute zero where atoms behave as one quantum entity with zero viscosity', 'A liquid with higher density than any solid', 'A type of amorphous solid found in space'], answer: 1, explanation: "At billionths of a degree above absolute zero, quantum wavelengths of atoms overlap — they lose individual identity and behave as one giant quantum object with superfluid properties. Lene Hau slowed light to bicycle speed through one! 🌌" },
    { id: 'q8', question: "Why does water boil at only 69°C at the top of Mount Everest? 🏔️", options: ['Different atmospheric chemicals reduce activation energy', 'Lower atmospheric pressure means vapour pressure equals atmospheric at lower temperatures', 'Higher altitude means gravity is weaker, so less energy needed', 'Cold temperatures change water\'s chemical properties'], answer: 1, explanation: "Boiling occurs when vapour pressure = atmospheric pressure. At altitude, atmospheric pressure is lower — so water reaches vapour pressure = atmospheric at only 69°C! This is why pressure cookers raise the boiling point (to 120°C+ at 2 atm) for faster cooking. 🍳" },
    { id: 'q9', question: "How does capillary action allow trees to lift water 100 metres upward? 🌳", options: ['Trees use pumps in their root systems', 'Adhesion of water to xylem walls and cohesion between water molecules creates a continuous column pulled upward', 'Osmosis creates high enough pressure to push water up', 'Photosynthesis at the top creates a vacuum that pulls water up'], answer: 1, explanation: "Water's cohesion (H-bonds between its own molecules) and adhesion (H-bonds with xylem walls) allow water to form a continuous column. Evaporation at leaves pulls the column upward via transpiration — capillary action supplements this! 🌳" },
    { id: 'q10', question: "What is sublimation? 🌫️", options: ['Solid melting into liquid under high pressure', 'Converting from solid directly to gas without passing through liquid', 'Liquid turning to solid under extreme cold', 'Gas condensing directly to solid (like frost)'], answer: 1, explanation: "Sublimation: solid → gas (skipping liquid). Dry ice (CO₂) sublimes at normal atmospheric pressure because liquid CO₂ cannot exist below 5.1 atm. The reverse (gas → solid) is called deposition — how snowflakes and frost form! ❄️" },
  ],

  relatedTopics: ['atoms_molecules', 'heat_temperature', 'energy_types', 'scientific_method'],
};
