// ─────────────────────────────────────────────
//  TOPIC: ELECTRICITY & CIRCUITS v2.0
//  Category: Physics
// ─────────────────────────────────────────────

export default {
  id: 'electricity_circuits',
  title: 'Electricity & Circuits',
  subtitle: "The invisible force that powers our world ⚡",
  emoji: '⚡',
  category: 'Physics',
  accentKey: 'electricity',

  // ── CURIOSITY HOOK ────────────────────────
  hook: {
    question: "If electricity travels at nearly light-speed (~300,000 km/s), why does it take an hour to charge your phone? 🤔",
    reveal: "The electromagnetic SIGNAL travels near light-speed, but individual electrons drift at a snail's pace — about 0.02 cm/s! It's like a tube packed with marbles: push one in, and one pops out the other end instantly, even though no single marble moved far. Your phone charges slowly because it needs billions of electrons to fill the battery capacity, not just the signal! 🤯",
    emoji: '💭',
  },

  // ── THEORY CARDS (10 CARDS) ──────────────────────────
  theory: [
    {
      id: 'what_is_charge',
      title: "Electric Charge & Atoms ⚛️",
      color: '#FFD166',
      bgGradient: ['#201800', '#0D0D1A'],
      icon: '⚡',
      svgIcon: 'lightning',
      content: "Everything is made of atoms, which contain **protons** (+) and **electrons** (-). Charge is a fundamental property that causes matter to experience a force in electromagnetic fields.\n\nLike charges repel, while opposite charges attract. In most materials, charges are balanced, so things seem neutral. But in conductors, some electrons are 'free' to wander between atoms, creating the possibility of flow! 🔌",
      highlight: "Electric charge is the 'fuel' of the universe. 1 Coulomb of charge contains 6.24 quintillion electrons! ⚛️",
    },
    {
      id: 'voltage_pressure',
      title: "Voltage: Electrical Pressure 💪",
      color: '#4ECDC4',
      bgGradient: ['#0A2020', '#0D0D1A'],
      icon: '🔋',
      svgIcon: 'zap',
      content: "**Voltage (V)** is the electrical potential difference between two points. Think of it as 'electrical pressure' that pushes charges through a circuit.\n\nA battery is like a water pump: it creates high pressure at one end and low pressure at the other. Electrons want to move from high pressure to low, creating flow. Without voltage, charges just sit still! 🧪",
      highlight: "Voltage (Volts) is the 'push' that gets charges moving. No voltage = no current! 🔋",
    },
    {
      id: 'current_flow',
      title: "Current: The Flow Rate 🌊",
      color: '#FF6B6B',
      bgGradient: ['#250A0A', '#0D0D1A'],
      icon: '🌊',
      svgIcon: 'waves',
      content: "**Current (I)** is the rate at which electric charge flows past a specific point. It is measured in **Amperes (Amps)**.\n\nIf voltage is the pressure, current is the actual volume of water moving through the pipe per second. High current means many electrons are flowing at once. A single lightning bolt can carry over 30,000 Amps! ⚡",
      highlight: "Current (Amps) measures flow rate: how many coulombs of charge pass by every second. 🌊",
    },
    {
      id: 'resistance_obstacle',
      title: "Resistance: The Friction 🚧",
      color: '#6C63FF',
      bgGradient: ['#1A1040', '#0D0D1A'],
      icon: '🚧',
      svgIcon: 'balance',
      content: "**Resistance (R)** is the opposition to current flow. Every material (except superconductors) fights back against moving electrons.\n\nThink of it as friction in a pipe. A narrow pipe (thin wire) has high resistance. A wide pipe (thick wire) has low resistance. We use **Resistors** to control exactly how much current flows in our gadgets! 🔧",
      highlight: "Resistance (Ohms Ω) is 'electrical friction.' It turns electrical energy into heat! 🚧",
    },
    {
      id: 'ohms_law_master',
      title: "Ohm's Law: The Golden V=IR 📐",
      color: '#FFD166',
      bgGradient: ['#201800', '#0D0D1A'],
      icon: '📐',
      svgIcon: 'grid',
      content: "In 1827, Georg Ohm discovered that Current, Voltage, and Resistance are perfectly linked:\n\n**V = I × R**\n\nIf you want more current, you can either INCREASE the voltage (push harder) or DECREASE the resistance (clear the path). This simple equation is the foundation for every smartphone, airplane, and satellite ever built! 🛰️",
      highlight: "V=IR links pressure, flow, and friction. It's the most important formula in electronics! 📐",
      formula: "V = I × R",
    },
    {
      id: 'series_circuitry',
      title: "Series: The Single Loop 🔗",
      color: '#FF9F1C',
      bgGradient: ['#201000', '#0D0D1A'],
      icon: '🔗',
      svgIcon: 'link',
      content: "In a **Series Circuit**, components are connected one after another in a single loop. There is only one path for the electrons to follow.\n\nPros: Simple to build.\nCons: If one light bulb breaks, the whole loop is interrupted and everything goes out! Also, the voltage 'splits' between all components, so more bulbs = dimmer lights. 🎄",
      highlight: "Series = 1 Path. If the path breaks, the entire circuit stops! 🔗",
    },
    {
      id: 'parallel_circuitry',
      title: "Parallel: The Multi-Path ⚡",
      color: '#00D4FF',
      bgGradient: ['#0A1A25', '#0D0D1A'],
      icon: '⚡',
      svgIcon: 'sun',
      content: "In a **Parallel Circuit**, components sit on their own individual branches. Electrons can choose which path to take.\n\nThis is how your house is wired! Turning off the kitchen light doesn't turn off your TV, because they are on different branches. Every branch gets the FULL voltage of the battery! 🏠",
      highlight: "Parallel = Many Paths. Every branch acts independently and gets full voltage! ⚡",
    },
    {
      id: 'ac_vs_dc',
      title: "AC vs DC: The Battle ⚔️",
      color: '#FF4D6D',
      bgGradient: ['#200A0E', '#0D0D1A'],
      icon: '⚔️',
      svgIcon: 'refresh',
      content: "**DC (Direct Current)**: Electrons flow in one direction only. Used in batteries and your phone.\n\n**AC (Alternating Current)**: Electrons jiggle back and forth 50-60 times a second. Used in wall outlets.\n\nNikola Tesla (AC) and Thomas Edison (DC) fought a famous 'War of Currents.' AC won for power grids because it can be sent over long distances with minimal loss! 🔌",
      highlight: "AC jiggles; DC flows straight. AC powers your home; DC powers your phone! ⚔️",
    },
    {
      id: 'conductors_insulators',
      title: "Conductors & Insulators 🧤",
      color: '#A855F7',
      bgGradient: ['#150A20', '#0D0D1A'],
      icon: '🧤',
      svgIcon: 'shield',
      content: "**Conductors** (like Copper and Gold) have loose electrons that move easily. **Insulators** (like Rubber and Glass) hold their electrons tight.\n\nThis is why wires are made of metal (to let flow happen) but wrapped in plastic (to stop you from getting shocked!). Pure water is actually an insulator; it's the dissolved minerals in normal water that make it conduct! 💧",
      highlight: "Conductors share; Insulators hoard. Use both to control the flow safely! 🧤",
    },
    {
      id: 'semiconductors_future',
      title: "Semiconductors & Chips 🤖",
      color: '#00E5A0',
      bgGradient: ['#0A2518', '#0D0D1A'],
      icon: '🤖',
      svgIcon: 'cpu',
      content: "Materials like **Silicon** are 'Semiconductors' — they can switch between being a conductor and an insulator. \n\nThis switching ability allows us to create **Transistors**, which act as tiny on/off gates. Modern computer chips contain billions of these gates, allowing for the complex logic that powers AI, Video Games, and the Internet! 🖥️",
      highlight: "Semiconductors are 'smart' materials that power the digital age through switching! 🤖",
    },
  ],

  // ── DO YOU KNOW WHY (5 FACTS) ───────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk_birds',
      question: "Why can birds sit on high-voltage power lines without getting shocked? 🐦",
      answer: "Electricity only flows when there's a difference in potential (Voltage). Since the bird is only touching one wire, its whole body stays at the same voltage. Zero difference = zero current. If the bird touched the grounded pole and the wire at the same time... ZAP! ⚡",
      emoji: '🐦',
    },
    {
      id: 'dyk_battery',
      question: "Why do batteries eventually 'die'? 🔋",
      answer: "Batteries use chemical reactions to push electrons. Over time, the chemicals inside are used up, and the 'potential' to move electrons drops. The 'dead' battery isn't empty of electrons; it just lost the chemical 'pressure' to push them forward! 🧪",
      emoji: '🔋',
    },
    {
      id: 'dyk_speed',
      question: "If electrons move so slowly, why does a light turn on instantly? 💡",
      answer: "It's like a garden hose already filled with water. As soon as you turn the tap at one end, water starts coming out the other. You didn't wait for 'new' water to travel the length; you just pushed the water already inside! 🌊",
      emoji: '💡',
    },
    {
      id: 'dyk_lightning',
      question: "Is lightning AC or DC? ⚡",
      answer: "Lightning is actually a massive pulse of Direct Current (DC). It flows from the negatively charged cloud to the positively charged ground in one massive, violent burst of energy! ⛈️",
      emoji: '⛈️',
    },
    {
      id: 'dyk_human',
      question: "Does the human body run on electricity? 🧠",
      answer: "Yes! Your brain and nerves send signals using tiny pulses of electricity called 'Action Potentials.' You are literally a biological computer powered by electrical ionic gradients! ⚡",
      emoji: '🧠',
    },
  ],

  // ── QUIZ (20 QUESTIONS) ──────────────────────────────────
  quiz: [
    {
      id: 'q1',
      question: "What is the unit for measuring electrical 'pressure' (Voltage)? 🔋",
      options: ['Amps', 'Ohms', 'Volts', 'Watts'],
      answer: 2,
      explanation: "Voltage is measured in Volts (V). It represents the potential difference that pushes charges through a circuit. ⚡",
    },
    {
      id: 'q2',
      question: "Which of these is the most commonly used conductor in household wiring? 🔌",
      options: ['Glass', 'Plastic', 'Copper', 'Rubber'],
      answer: 2,
      explanation: "Copper is an excellent conductor with very low resistance, making it ideal for wiring! 🥉",
    },
    {
      id: 'q3',
      question: "In Ohm's Law (V=IR), what happens to current if resistance increases (voltage stays same)? 📐",
      options: ['Current increases', 'Current decreases', 'Current stays same', 'Circuit explodes'],
      answer: 1,
      explanation: "Resistance opposes flow. If you increase the friction (resistance) but don't push harder (voltage), the flow rate (current) goes down! 📉",
    },
    {
      id: 'q4',
      question: "What device is used to safely break a circuit if the current gets too high? 🛡️",
      options: ['Transformer', 'Capacitor', 'Circuit Breaker', 'Antenna'],
      answer: 2,
      explanation: "Circuit breakers and fuses 'trip' or blow to prevent wires from overheating and causing fires! 🔥",
    },
    {
      id: 'q5',
      question: "Which type of circuit provides multiple paths for current? ⚡",
      options: ['Series', 'Parallel', 'Linear', 'Static'],
      answer: 1,
      explanation: "Parallel circuits have multiple branches. This is why households use parallel wiring. 🏠",
    },
    {
      id: 'q6',
      question: "What did Nikola Tesla champion during the 'War of Currents'? ⚔️",
      options: ['Direct Current (DC)', 'Alternating Current (AC)', 'Static Electricity', 'Battery Power'],
      answer: 1,
      explanation: "Tesla championed Alternating Current (AC) because it could be easily stepped up and sent over long distances. 🌊",
    },
    {
      id: 'q7',
      question: "What is the unit of electrical Resistance? 🚧",
      options: ['Ohm (Ω)', 'Watt (W)', 'Henry (H)', 'Farad (F)'],
      answer: 0,
      explanation: "Resistance is measured in Ohms (Ω), named after Georg Simon Ohm. 📐",
    },
    {
      id: 'q8',
      question: "What material properties allow semiconductors like Silicon to work? 🤖",
      options: ['Only conductor', 'Only insulator', 'Can switch between both', 'Transparent'],
      answer: 2,
      explanation: "Semiconductors can be tuned to conduct or insulate, which allows them to act as digital switches (transistors)! 🖥️",
    },
    {
      id: 'q9',
      question: "The rate of flow of electric charge is called: 🌊",
      options: ['Voltage', 'Power', 'Current', 'Capacitance'],
      answer: 2,
      explanation: "Current is the flow rate of charge, measured in Amps. 🌊",
    },
    {
      id: 'q10',
      question: "What is the combined resistance of two 10Ω resistors in series? 🔗",
      options: ['5Ω', '10Ω', '20Ω', '100Ω'],
      answer: 2,
      explanation: "In series, you just add them up: 10 + 10 = 20Ω. ➕",
    },
    {
      id: 'q11',
      question: "What is the combined resistance of two 10Ω resistors in parallel? ⚡",
      options: ['5Ω', '10Ω', '20Ω', '100Ω'],
      answer: 0,
      explanation: "In parallel, two identical paths halve the overall resistance. 1/R = 1/10 + 1/10 = 2/10, so R = 5Ω. 📉",
    },
    {
      id: 'q12',
      question: "Which particle within the atom is primarily responsible for electrical current in metals? ⚛️",
      options: ['Proton', 'Neutron', 'Electron', 'Quark'],
      answer: 2,
      explanation: "Electrons are light and located outside the nucleus, making them easy to move as charge carriers. ⚡",
    },
    {
      id: 'q13',
      question: "Electrical Power is calculated using which formula? 💡",
      options: ['P = V + I', 'P = V - I', 'P = V / I', 'P = V × I'],
      answer: 3,
      explanation: "Power (Watts) = Voltage (Volts) × Current (Amps). 💡",
    },
    {
      id: 'q14',
      question: "A material that achieves zero electrical resistance at low temperatures is a: ❄️",
      options: ['Semiconductor', 'Superconductor', 'Dielectric', 'Resistor'],
      answer: 1,
      explanation: "Superconductors allow electricity to flow forever without ANY energy loss to heat! 💎",
    },
    {
      id: 'q15',
      question: "What happens to the brightness of 3 bulbs in series if you add a 4th bulb? 🔗",
      options: ['Brighter', 'Dimmer', 'Stays same', 'They explode'],
      answer: 1,
      explanation: "More bulbs in series add more resistance, lowering the current and splitting the voltage further. Result: dimmer bulbs. 🕯️",
    },
    {
      id: 'q16',
      question: "What component is used to store electrical energy in an electric field? 🔋",
      options: ['Resistor', 'Inductor', 'Capacitor', 'Diode'],
      answer: 2,
      explanation: "Capacitors store charge and can release it quickly. They are like small, high-speed temporary batteries! ⚡",
    },
    {
      id: 'q17',
      question: "In a house, what protects humans from accidental electric shocks by sensing leaks? 🏠",
      options: ['Fuse', 'GFCI / RCD', 'Battery', 'Switch'],
      answer: 1,
      explanation: "GFCI (Ground Fault Circuit Interrupters) measure current balance. If a leak is detected (e.g., through a person), it cuts power in milliseconds! 🛡️",
    },
    {
      id: 'q18',
      question: "Static electricity (like rubbing a balloon) is caused by the transfer of: 🎈",
      options: ['Protons', 'Neutrons', 'Electrons', 'Atoms'],
      answer: 2,
      explanation: "Rubbing surfaces peels electrons off one material and onto another, creating an imbalance of charge. ⚡",
    },
    {
      id: 'q19',
      question: "Why do high-voltage power lines use transformers? 🗼",
      options: ['To look cool', 'To change DC to AC', 'To step voltage up/down', 'To slow down light'],
      answer: 2,
      explanation: "Transformers step voltage up for efficient transmission (low losses) and down for safe home use. ⚡",
    },
    {
      id: 'q20',
      question: "How many paths for current flow exist in a parallel circuit with 3 branches? ⚡",
      options: ['1', '2', '3', '4'],
      answer: 2,
      explanation: "Every branch in a parallel circuit provides its own independent path for current! 🛣️",
    },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['magnetism', 'energy_types', 'digital_circuits', 'forces_motion', 'quantum_basics'],
};
