// ─────────────────────────────────────────────────────────
//  TOPIC: NIHILISM
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'nihilism',
  title: 'Nihilism',
  subtitle: 'The Freedom of Nothingness 🕳️🌌',
  emoji: '🕳️',
  category: 'Philosophy',
  accentKey: 'nihilism',

  hook: {
    question: "In 5 billion years, the Sun will expand and incinerate the Earth. Every achievement, every painting, every memory—gone forever. Why do anything at all?",
    reveal: "This terrifying thought is the gateway to **Nihilism**. Nihilism arrives when we realize that the universe does not care about us, and life has no built-in, intrinsic meaning.\n\nFor many, this realization causes crushing despair. But for others, it is the ultimate liberation. If nothing matters in the grand scheme of the cosmos, then every mistake you make is equally meaningless, and you are entirely free to enjoy this brief flash of consciousness. Let's stare into the abyss. 👁️‍🗨️🌠",
    emoji: '🌠',
  },

  theory: [
    {
      id: 'what_is_nihilism',
      title: "What is Nihilism? 😶‍🌫️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'slash',
      svgIcon: 'eye',
      content: "The word comes from the Latin *nihil*, meaning 'nothing'.\nNihilism is the philosophical view that life is without objective meaning, purpose, or intrinsic value. \nThere is no grand plan. We were not put here for a reason. We are just biological accidents on a wet rock floating in an infinite, silent void.",
      highlight: "Nihilism states that the universe is indifferent to your existence. 🌑",
    },
    {
      id: 'nietzsche_god_is_dead',
      title: "\"God is Dead\" ⛪📉",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'crosshair',
      svgIcon: 'flame',
      content: "Friedrich Nietzsche famously wrote: *'God is dead. God remains dead. And we have killed him.'*\nHe was not celebrating. He meant that the Enlightenment and the rise of Science had destroyed the idea of a Creator. \nWithout God as the foundation for morality and meaning, Nietzsche foresaw a terrifying crisis: humanity would descend into despair and bloody wars (which happened in the 20th century).",
      highlight: "When the sky is empty, what prevents humanity from falling apart? 🌪️",
    },
    {
      id: 'cosmic_insignificance',
      title: "Cosmic Insignificance 🔭",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'globe',
      svgIcon: 'star',
      content: "The Milky Way galaxy has 100 billion stars. The observable universe has 2 trillion galaxies. \nHuman history has existed for a fraction of a millisecond on the cosmic calendar. \nOur daily anxieties—embarrassing ourselves at work, losing a video game, getting a bad haircut—are mathematically less than microscopic in the grand scale of reality.",
      highlight: "You are a speck of dust. Your problems are a speck of dust on a speck of dust. 🦠",
    },
    {
      id: 'types_of_nihilism',
      title: "The Four Flavors 🍨",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'layers',
      svgIcon: 'lock',
      content: "1. **Cosmic Nihilism**: The universe is so vast that humanity is utterly insignificant.\n2. **Existential Nihilism**: Human life has no intrinsic meaning or ultimate purpose.\n3. **Moral Nihilism**: There is no objective 'right' or 'wrong'. Morals are just human inventions.\n4. **Epistemological Nihilism**: It is impossible to know any absolute truth.",
      highlight: "Nihilism dismantles everything you thought was 'real' or 'important'. 🏗️",
    },
    {
      id: 'passive_nihilism',
      title: "Passive Nihilism (Despair) 🪫",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'frown',
      svgIcon: 'activity',
      content: "When confronted with the meaninglessness of the universe, the **Passive Nihilist** surrenders.\nThey say: *'Life has no meaning, therefore I should do nothing, care about nothing, and just wait to die.'*\nThis leads to severe depression, extreme apathy, and viewing all human effort as a sad, pointless joke.",
      highlight: "Passive nihilism is a black hole that consumes the will to live. 🕳️",
    },
    {
      id: 'active_nihilism',
      title: "Active Nihilism (Creation) 🔋",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'zap',
      svgIcon: 'zap',
      content: "The **Active Nihilist** (which Nietzsche advocated for) views meaninglessness as a blank canvas.\nThey say: *'Life has no pre-written meaning. Therefore, I am perfectly free to write my own.'*\nIf there is no script, you cannot make a mistake. Active nihilists destroy the old, fake values of society to build new, authentic ones for themselves.",
      highlight: "A blank map means you get to draw the roads. 🗺️",
    },
    {
      id: 'the_uber_mensch',
      title: "The Übermensch 🦸‍♂️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'star',
      svgIcon: 'target',
      content: "To survive the 'death of God', Nietzsche proposed a goal for humanity: The **Übermensch** (Superman).\nThe Übermensch is someone who creates their own values, loves their earthly life, and refuses to rely on the 'comfort' of an afterlife. They accept the brutal suffering of the world and overcome it through pure willpower and art.",
      highlight: "The Übermensch is the cure to the disease of meaninglessness. 🧬",
    },
    {
      id: 'amor_fati',
      title: "Amor Fati: Love of Fate ❤️‍🔥",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'heart',
      svgIcon: 'heart',
      content: "Nietzsche also introduced **Amor Fati** (Love of Fate).\nDon't just *accept* your pain, your failures, and your meaningless existence—*love* them. \nIf you had to live your exact life over and over for all eternity (The Eternal Recurrence), would you be happy? Amor Fati is learning to say 'Yes' to the chaos of your destiny.",
      highlight: "Do not wish for the universe to be different. Love it exactly as it is. 🌪️",
    },
    {
      id: 'optimistic_nihilism',
      title: "Optimistic Nihilism 🌈",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'smile',
      svgIcon: 'users',
      content: "A modern internet philosophy popularized by Kurzgesagt.\n**Optimistic Nihilism** argues: You only get one shot at consciousness. It is a fleeting, accidental spark in a cold universe. \nSince you will be deleted forever in a few decades, don't waste time being anxious. Eat a donut. Hug a dog. Love someone deeply. Enjoy the flash.",
      highlight: "If the universe has no purpose, you get to dictate what its purpose is. 🍩",
    },
    {
      id: 'moral_nihilism',
      title: "Are Murder and Charity the Same? ⚖️",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'alert-triangle',
      svgIcon: 'lock',
      content: "**Moral Nihilists** argue that 'good' and 'evil' only exist in human minds. The universe doesn't care if an asteroid hits a hospital or a barren rock.\nBut wait! If nothing is objectively 'wrong', is murder okay?\nNo. Even without a cosmic rulebook, we have biology. Suffering *feels* bad physically and mentally. Empathy and social cooperation are biological imperatives, not divine laws.",
      highlight: "The universe doesn't care if you kick a puppy, but the puppy cares. That is enough. 🐕",
    },
    {
      id: 'the_anxiety_cure',
      title: "Nihilism as an Anxiety Cure 💊",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'wind',
      svgIcon: 'leaf',
      content: "Nihilism can be the ultimate cure for overthinking and social anxiety. \nAre you terrified of saying something stupid at a party? Realize that in 100 years, everyone at that party will be dead. In 10,000 years, human civilization might be dust. \nYour embarrassment literally does not matter. The pressure is completely off.",
      highlight: "Cosmic insignificance is a highly effective armor against daily stress. 🛡️",
    },
    {
      id: 'art_and_creation',
      title: "Art as the Only Salvation 🎨",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'pen-tool',
      svgIcon: 'eye',
      content: "If truth is unattainable and life is meaningless, what is left?\nNietzsche believed that **Art** is the highest human achievement. It is the only thing that makes the brutality of existence bearable.\nWe create art, music, and stories to impose our own beautiful interpretations onto a chaotic, silent universe.",
      highlight: "We have art in order not to die of the truth. (Nietzsche) 🌌",
    },
    {
      id: 'the_void_stares_back',
      title: "The Danger of the Abyss 🕳️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'eye-off',
      svgIcon: 'flame',
      content: "Nietzsche warned: *'If you gaze long enough into an abyss, the abyss will gaze back into you.'*\nFlirting with nihilism is dangerous. If you tear down all societal values without having the strength to create your own (becoming the Übermensch), you will fall into total despair.\nYou cannot stay in the destruction phase forever.",
      highlight: "Nihilism is a hammer to destroy old walls, but you still need a home to live in. 🔨",
    },
    {
      id: 'the_absurd',
      title: "The Bridge to Absurdism 🌉",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'fast-forward',
      svgIcon: 'compass',
      content: "Nihilism says: 'There is no meaning.'\nAlbert Camus took this further into **Absurdism**: 'Humans have a desperate, biological need for meaning in a universe that absolutely refuses to give it to them. That contradiction is The Absurd.'\nCamus argued we shouldn't despair, nor should we invent fake meaning. We should accept the absurdity and rebel against it by living passionately.",
      highlight: "Nihilism is the diagnostic. Absurdism is the prescription. 🩺",
    },
    {
      id: 'conclusion',
      title: "The Ultimate Responsibility 👑",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'award',
      svgIcon: 'star',
      content: "Nihilism removes the safety net of the universe. There is no karma, no destiny, and no cosmic parent coming to save you.\nYou are entirely alone in the void. \nThis places 100% of the responsibility for your happiness and morality squarely on your own shoulders. It is terrifying, but it is the ultimate freedom.",
      highlight: "You are the dictator of your own reality. Rule it well. 🏛️",
    },
  ],

  lab: {
    title: "Cosmic Zoom-Out 🔭🌌",
    description: "You are suffering from an acute social anxiety attack due to an embarrassing mistake. Apply the lens of 'Optimistic Nihilism'. Zoom out from your microscopic problem to the edge of the observable universe to annihilate the anxiety.",
    hint: "Keep zooming out. Compare the lifespan of your embarrassment to the lifespan of a Red Dwarf star.",
    scientistModeHint: "Astrophysical Mode 🧑‍🔬: Visualize scale relativity. Earth diameter (12,742 km) vs entire Laniakea Supercluster (500 million light-years).",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do we feel 'Existential Dread' primarily in our late teens/20s?", answer: "During late adolescence, the prefrontal cortex develops the capacity for abstract reasoning. For the first time, your brain has the hardware to step outside its ego and realize its own mortality and insignificance. The 'safeguards' of childhood drop, exposing you to the void. 🧠", emoji: '🕳️' },
    { id: 'dyk2', question: "Why does staring at the night sky make us feel both small and peaceful?", answer: "The 'Overview Effect'. Seeing the sheer scale of the cosmos triggers awe, which neurologically shrinks the ego. When your brain realizes it is objectively tiny, it physically stops pumping the stress hormones assigned to your 'big' daily problems. 🌠", emoji: '🧘‍♂️' },
    { id: 'dyk3', question: "Did Nietzsche actually think it was a 'good thing' that God was dead?", answer: "No! 'God is dead' was not a celebration; it was a dire warning. He feared that without the moral foundation of religion, Europe would fall into brutal, nihilistic wars (which perfectly predicted WWI, WWII, and the rise of totalitarianism). He sought a replacement system before society collapsed. 🛑", emoji: '💥' },
    { id: 'dyk4', question: "Why do internet memes lean so heavily into Nihilism today?", answer: "Modern generations face severe economic uncertainty, climate anxiety, and digital isolation. Using 'Optimistic Nihilism' memes (e.g., a cute dog saying 'nothing matters') is a profound psychological defense mechanism to cope with an overwhelming lack of control. 📱", emoji: '🐶' },
    { id: 'dyk5', question: "If a Moral Nihilist doesn't believe in objective right and wrong, why don't they commit crimes?", answer: "Because objective morality and subjective empathy are different. The universe doesn't care if you steal, but human biology is wired for cooperation. We possess 'mirror neurons' that make us physically feel the pain of others. We don't commit crimes because it hurts our tribe, not because the cosmos forbids it. 🤝", emoji: '🧬' },
  ],

  quiz: [
    { id: 'q1', question: "What is the core premise of Nihilism?", options: ["Being unkind to others", "The universe is simulated", "Life lacks inherent meaning", "Worshipping many different gods"], answer: 2, explanation: "The universe is indifferent to your existence. 🌑" },
    { id: 'q2', question: "What did Friedrich Nietzsche mean when he wrote 'God is dead'?", options: ["The death of a deity", "Loss of religious moral foundations", "A fictional literary story", "Critique of church architecture"], answer: 1, explanation: "It was a grim warning of a coming crisis, not a celebration. ⛪" },
    { id: 'q3', question: "What is 'Passive Nihilism'?", options: ["Finding joy in nothingness", "Despair and apathy toward life", "Ignoring all philosophical thought", "Engaging in constant conflict"], answer: 1, explanation: "Passive nihilists decide that if the game doesn't matter, they just won't play. 🪫" },
    { id: 'q4', question: "How does 'Active Nihilism' differ from Passive?", options: ["Increased physical activity levels", "Creating personal values and meaning", "A deep hatred of art", "Belief in a higher power"], answer: 1, explanation: "If there is no script, you get to write your own. 🔋" },
    { id: 'q5', question: "What is Nietzsche's concept of the 'Übermensch' (Superman)?", options: ["A fictional comic hero", "One who creates personal values", "A powerful political dictator", "An elite professional athlete"], answer: 1, explanation: "The Übermensch is the cure for the disease of meaninglessness. 🦸‍♂️" },
    { id: 'q6', question: "What is 'Optimistic Nihilism'?", options: ["Practicing religion with joy", "Finding freedom in cosmic indifference", "Desiring eternal physical life", "A complex mathematical formula"], answer: 1, explanation: "It turns cosmic dread into a license to enjoy the moment. 🍩" },
    { id: 'q7', question: "What does 'Moral Nihilism' claim?", options: ["Belief that everyone is evil", "Rejection of objective morality", "Encouragement to break laws", "Belief that only good exists"], answer: 1, explanation: "An asteroid hitting a hospital isn't 'evil' to the universe; it's just rocks hitting rocks. ⚖️" },
    { id: 'q8', question: "How can Nihilism actually help cure social anxiety?", options: ["Encouraging silence in public", "Realizing mistakes are cosmically insignificant", "Increasing levels of anxiety", "Instilling fear in others"], answer: 1, explanation: "Cosmic insignificance drops the pressure of life to zero. 🛡️" },
    { id: 'q9', question: "What does the phrase 'Amor Fati' mean?", options: ["The concept of blind love", "Embracing one's fate entirely", "A deep fear of destiny", "The final end of time"], answer: 1, explanation: "Don't just accept your fate. Fall in love with it. ❤️‍🔥" },
    { id: 'q10', question: "What did Nietzsche consider to be the highest human achievement to combat a meaningless universe?", options: ["Scientific discovery and progress", "Creating art to impose meaning", "Accumulating vast personal wealth", "Engaging in strategic warfare"], answer: 1, explanation: "'We have art in order not to die of the truth.' 🎨" },
    { id: 'q11', question: "What happens if you stare too long into the abyss, according to Nietzsche?", options: ["Losing one's physical sight", "The abyss stares back", "Falling into a deep pit", "Discovering a divine presence"], answer: 1, explanation: "Flirting with absolute nothingness is psychologically dangerous. 🕳️" },
    { id: 'q12', question: "How is Absurdism different from Nihilism?", options: ["They are identical concepts", "Rebelling against the search for meaning", "Using humor to explain life", "Relying on scientific evidence"], answer: 1, explanation: "Camus said we must embrace the Absurd and live passionately anyway. 🌉" },
    { id: 'q13', question: "Why do Moral Nihilists generally avoid committing crimes if they believe nothing is objectively 'wrong'?", options: ["Fear of law enforcement", "Natural empathy and biology", "Lack of physical energy", "General laziness and apathy"], answer: 1, explanation: "We avoid hurting others due to our biology, not cosmic rulebooks. 🤝" },
    { id: 'q14', question: "What is 'Epistemological Nihilism'?", options: ["Fear of empty spaces", "Denial of absolute truth", "Destruction of physical structures", "A deep love for nature"], answer: 1, explanation: "It questions the very foundation of human knowledge. 🧠" },
    { id: 'q15', question: "What is the 'Overview Effect' (experienced by astronauts)?", options: ["Headaches caused by space", "Perspective shift from space", "Memory loss regarding names", "Nausea from orbital motion"], answer: 1, explanation: "Zooming out fundamentally alters how important you think you are. 🔭" },
    { id: 'q16', question: "If the universe has no inherent purpose, what is the 'Active' Nihilist's response?", options: ["Expressing sadness through crying", "Inventing a personal purpose", "Sleeping for long periods", "Consulting with scientific experts"], answer: 1, explanation: "You are entirely responsible for the meaning of your life. 👑" },
    { id: 'q17', question: "Why makes the concept of 'Eternal Recurrence' so difficult to accept?", options: ["Complex mathematical calculations", "Living the same life forever", "The excessive time required", "The need for perfect memory"], answer: 1, explanation: "Living a life you'd be willing to repeat for eternity is the highest goal. 🔄" },
    { id: 'q18', question: "Why are internet memes heavily saturated with Optimistic Nihilism?", options: ["Desire to appear intelligent", "Coping with global uncertainty", "Humor involving domestic animals", "Generating significant financial profit"], answer: 1, explanation: "Laughing at the void makes it less scary. 📱" },
    { id: 'q19', question: "Atheism and Nihilism are often linked, but how do they differ?", options: ["Differences in religious structure", "Nihilism rejects all meaning", "They are exactly the same", "Historical age of the ideas"], answer: 1, explanation: "You can be an atheist and still believe human life has objective purpose (Secular Humanism), but a nihilist rejects even that. ⚖️" },
    { id: 'q20', question: "What is the 'freedom' of Nihilism?", options: ["Access to free food", "Inability to truly fail", "Absence of physical gravity", "Exemption from paying taxes"], answer: 1, explanation: "The pressure of 'doing it right' is completely removed. 🌌" },
  ],

  relatedTopics: ['atheism', 'existentialism', 'stoicism'],
};
