// ─────────────────────────────────────────────────────────
//  TOPIC: ENLIGHTENMENT
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'enlightenment',
  title: 'Age of Enlightenment',
  subtitle: 'The Birth of Modern Reason 🧠💡',
  emoji: '💡',
  category: 'Philosophy',
  accentKey: 'enlightenment',

  hook: {
    question: "For thousands of years, if you wanted to know the truth about the universe, human rights, or how to govern a country, you asked a King or a Priest. No questions allowed. Then, a massive intellectual earthquake changed history forever.",
    reveal: "This earthquake was the **Age of Enlightenment** (17th–18th Century).\n\nSuddenly, brilliant minds like Kant, Voltaire, Locke, and Rousseau began to argue a radical new idea: *Human beings shouldn't blindly trust authority. We should trust our own Reason and the Scientific Method.*\nThis single philosophical movement destroyed ancient monarchies, birthed modern democracy, ended witch hunts, and built the world you live in today. Let's explore the era that dragged humanity out of the dark ages. 🏛️🌍",
    emoji: '🌍',
  },

  theory: [
    {
      id: 'what_was_the_enlightenment',
      title: "What Was It? 🕯️",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'sun',
      svgIcon: 'eye',
      content: "The Age of Enlightenment (also called the Age of Reason) was an intellectual and cultural movement in Europe during the 1600s and 1700s.\nIts core belief was simple but explosive: **Reason (logic and evidence) is the primary source of authority and truth.**\nBefore this, truth was dictated by religious dogma and absolute monarchs. The Enlightenment replaced blind faith with skeptical, rigorous inquiry.",
      highlight: "It was humanity's collective transition from childhood (blind obedience) to adulthood (thinking for oneself). 🧠",
    },
    {
      id: 'sapere_aude',
      title: "Sapere Aude! 🦅",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'zap',
      svgIcon: 'target',
      content: "The German philosopher **Immanuel Kant** wrote an essay titled *What is Enlightenment?*.\nHe summarized the entire movement in two Latin words: **Sapere Aude!**\nIt translates to: *'Dare to know!'* or *'Have the courage to use your own understanding!'*\nKant argued that humanity had been lazy and cowardly, letting priests and kings do their thinking for them. It was time to wake up.",
      highlight: "Enlightenment is man's release from his self-incurred immaturity. (Kant) 🛡️",
    },
    {
      id: 'john_locke',
      title: "John Locke & Human Rights 📜",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'file-text',
      svgIcon: 'lock',
      content: "John Locke (1632–1704) was an English philosopher who fundamentally changed politics.\nHe argued that human beings are born with **Natural Rights**: Life, Liberty, and Property. These rights are not given by a King; they are yours by default as a human being.\nIf a government fails to protect these rights, Locke argued that the people have the absolute right to overthrow that government.",
      highlight: "This single idea directly inspired the American and French Revolutions. 💥",
    },
    {
      id: 'tabula_rasa',
      title: "Tabula Rasa (The Blank Slate) ⬜",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'square',
      svgIcon: 'eye',
      content: "Another massive idea from Locke was **Tabula Rasa** (The Blank Slate).\nBefore Locke, kings argued they were born with 'Divine Right' (inherently superior), and peasants were born to serve.\nLocke argued that every human mind is born completely blank. Everything you know comes from *experience* and *education*. Therefore, all men are fundamentally equal at birth.",
      highlight: "If we are all born blank slates, then no one is naturally born to be a ruling king or a slave. ⚖️",
    },
    {
      id: 'voltaire',
      title: "Voltaire: Freedom of Speech 🗣️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'mic',
      svgIcon: 'users',
      content: "Voltaire was a witty, fiercely sarcastic French writer who spent his life attacking the Catholic Church and the French Monarchy's censorship.\nHe famously championed **Freedom of Speech** and religious tolerance.\nThough he was a 'Deist' (believed in a Creator but not a specific religion), he violently opposed religious fanaticism and dogma that led to wars and executions.",
      highlight: "I disapprove of what you say, but I will defend to the death your right to say it. (Attributed to Voltaire's beliefs) ⚔️",
    },
    {
      id: 'rousseau',
      title: "Rousseau & The Social Contract 🤝",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'users',
      svgIcon: 'users',
      content: "Jean-Jacques Rousseau wrote a book called *The Social Contract* (1762).\nHe famously began it with: *'Man is born free, and everywhere he is in chains.'*\nRousseau argued that a government is only legitimate if it is based on the 'General Will' of the people. The people make a 'contract' with the state to obey laws, but only if the state serves the people.",
      highlight: "The people are the ultimate source of political power. 👑➡️🧍‍♂️",
    },
    {
      id: 'the_encyclopedie',
      title: "The Ultimate Weapon: The Encyclopédie 📚",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'book',
      svgIcon: 'star',
      content: "To combat ignorance, Denis Diderot organized the creation of the *Encyclopédie* (1751).\nIt was a massive collection of all human knowledge—science, arts, crafts, and philosophy—written by Enlightenment thinkers.\nThe goal was to democratize knowledge so that anyone could learn without needing a priest. The Pope and the French King tried to ban it, but it spread like wildfire.",
      highlight: "Knowledge is power, and the Encyclopédie gave that power to the public. 🔥",
    },
    {
      id: 'scientific_revolution',
      title: "The Scientific Foundation 🔭",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'aperture',
      svgIcon: 'activity',
      content: "The Enlightenment didn't happen in a vacuum. It was triggered by the **Scientific Revolution**.\nWhen Isaac Newton released his laws of physics, he proved that the universe runs on predictable, mathematical rules, not the unpredictable whims of gods.\nPhilosophers realized: *If science can explain the motion of the planets using Reason, why can't we use Reason to fix human society and government?*",
      highlight: "The Scientific Method was violently ripped from physics and applied to politics. 🚀",
    },
    {
      id: 'separation_of_powers',
      title: "Montesquieu: Dividing Power ⚔️",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'layout',
      svgIcon: 'lock',
      content: "Baron de Montesquieu observed that whenever one person (a king) has all the power, they become a tyrant.\nTo prevent tyranny, he invented the concept of the **Separation of Powers**.\nHe argued government hardware should be split into three branches: Executive, Legislative, and Judicial. They must constantly check and balance each other.",
      highlight: "Almost every modern democratic constitution is built directly on this Enlightenment principle. 🏛️",
    },
    {
      id: 'deism',
      title: "Deism: The Clockmaker God 🕰️",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'clock',
      svgIcon: 'zap',
      content: "Many Enlightenment thinkers (like Thomas Jefferson and Voltaire) were not Atheists, they were **Deists**.\nThey believed God is like a 'Cosmic Clockmaker'. God built the universe, set up the laws of physics, wound the clock, and then stepped back.\nGod does not interfere. Therefore, there are no miracles, no divine interventions, and praying for rain is useless. We must study the 'clock' (science) to survive.",
      highlight: "God gave us Reason, not magic. ⚙️",
    },
    {
      id: 'adam_smith',
      title: "Adam Smith: The Free Market 💰",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'dollar-sign',
      svgIcon: 'heart',
      content: "Scottish philosopher Adam Smith applied Enlightenment logic to economics in *The Wealth of Nations* (1776).\nHe argued against kings controlling the economy (Mercantilism) and proposed the **Free Market** (Capitalism).\nHe claimed that if individuals act in their own self-interest, an 'Invisible Hand' will naturally guide the economy to produce what society needs, generating wealth for everyone.",
      highlight: "Economic freedom was added to the list of human rights. 🪙",
    },
    {
      id: 'mary_wollstonecraft',
      title: "Wollstonecraft: Equality for Women 👩‍⚖️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'shield',
      svgIcon: 'eye',
      content: "While male philosophers preached 'all men are equal', they largely ignored women.\nMary Wollstonecraft wrote *A Vindication of the Rights of Woman* (1792).\nUsing Locke's 'Blank Slate' theory, she argued furiously that women only appeared inferior to men because they were denied education. If women were given the same education, they would be equally rational.",
      highlight: "She laid the intellectual foundation for modern feminism. 📖",
    },
    {
      id: 'dark_side',
      title: "The Dark Side (Imperialism) 🌑",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'eye-off',
      svgIcon: 'flame',
      content: "The Enlightenment had a massive blind spot. \nWhile European philosophers wrote beautiful essays about 'Liberty' and 'Natural Rights', European empires were simultaneously expanding the brutal Transatlantic Slave Trade and violently colonizing the world.\nSome thinkers contorted 'Reason' to try and justify scientific racism, falsely categorizing humanity to excuse slavery.",
      highlight: "The men who wrote 'all men are created equal' often owned slaves. ⛓️",
    },
    {
      id: 'the_french_revolution',
      title: "The Bloodbath: The French Revolution 🗡️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'scissors',
      svgIcon: 'activity',
      content: "The Enlightenment ideas (Liberty, Equality, Fraternity) eventually boiled over into the French Revolution (1789).\nThe peasants overthrew the toxic monarchy. But implementing 'pure reason' turned bloody. \nDuring the 'Reign of Terror', thousands of people were executed by the guillotine for allegedly betraying Enlightenment ideals. It proved that human nature is messy and cannot be fixed *only* by logic.",
      highlight: "Reason without empathy can become a new form of tyranny. 🩸",
    },
    {
      id: 'conclusion',
      title: "The Legacy of Light 🌅",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'award',
      svgIcon: 'star',
      content: "Despite its flaws, the Enlightenment is the operating system of the modern world.\nDemocracy, freedom of speech, human rights, public schools, science-based medicine, and the separation of church and state all trace their roots directly back to these few decades of explosive thinking.\nBecause of them, you are allowed to read this app today without asking a priest for permission.",
      highlight: "Never stop questioning authority. Dare to know. 🧠💡",
    },
  ],

  lab: {
    title: "The Constitution Forge 📜🔨",
    description: "You have just overthrown an absolute monarch. The peasants are rioting. You must draft a new Constitution using Enlightenment principles. If you rely on Dogma or tyranny, your new nation will collapse.",
    hint: "Apply Locke (Rights), Montesquieu (Separation), and Beccaria (Fair Justice). Reject 'Divine Right' and 'Absolute Power'.",
    scientistModeHint: "Rationalist Mode 🧑‍🔬: Ensure the Legislative, Executive, and Judicial variables maintain absolute equilibrium to prevent systemic tyranny.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why did the Pope ban the Encyclopédie?", answer: "Before the Encyclopédie, the Catholic Church controlled the flow of information. If you wanted to know how the world worked, the Church told you. By putting science, craft, and philosophy into a publicly accessible book based on 'Reason' rather than 'Revelation', it destroyed the Church's monopoly on truth. 📚", emoji: '🔥' },
    { id: 'dyk2', question: "Why is Thomas Jefferson heavily tied to the Enlightenment?", answer: "Jefferson was deeply obsessed with John Locke. When drafting the American Declaration of Independence, Jefferson literally copy-pasted Locke's Enlightenment philosophy ('Life, Liberty, and the pursuit of Happiness' instead of Locke's 'Property') to justify breaking away from the British King. 🇺🇸", emoji: '📜' },
    { id: 'dyk3', question: "Did the Enlightenment philosophers hate religion?", answer: "Not all of them. Many were Deists who believed in God. What they hated was *Dogma* (believing things without evidence) and *Theocracy* (priests holding political power). They heavily attacked the Catholic Church because it was severely corrupt, burned scientists at the stake, and hoarded immense wealth. ⛪", emoji: '⚔️' },
    { id: 'dyk4', question: "Why was 'The Blank Slate' theory so revolutionary?", answer: "Because if the mind is a blank slate, then a King is only a King because he happened to be born in a castle and given a royal education. A peasant is only a peasant because he was denied education. It proved that the class system was an artificial human invention, not a biological or divine law. ⬜", emoji: '⚖️' },
    { id: 'dyk5', question: "Why is the guillotine considered a 'product of the Enlightenment'?", answer: "Before the Revolution, executions were brutal torture spectacles (drawing and quartering, breaking on the wheel). Dr. Guillotin proposed the machine as a 'humane', painless, and scientifically efficient method of execution that treated all citizens equally, regardless of class. A dark application of 'Reason'. 🪓", emoji: '🩸' },
  ],

  quiz: [
    { id: 'q1', question: "What was the core belief of the Age of Enlightenment?", options: ["Magic controls the world", "Reason is the primary authority", "Only the wealthy should learn", "Tradition is the only truth"], answer: 1, explanation: "Blind faith was replaced by rigorous, skeptical inquiry. 🧠" },
    { id: 'q2', question: "What does Immanuel Kant's famous motto 'Sapere Aude' mean?", options: ["Save the gold", "Dare to use your reason", "Obey the ruling monarch", "Speak softly and listen"], answer: 1, explanation: "Humanity's transition from childhood to adulthood. 🦅" },
    { id: 'q3', question: "According to John Locke, what are the 'Natural Rights' every human is born with?", options: ["Free food and housing", "Life, liberty, and property", "The right to rule", "The right to conflict"], answer: 1, explanation: "These rights are yours by birth, not gifted by a government. 📜" },
    { id: 'q4', question: "What happens if a government violates the Natural Rights of the people, according to Locke?", options: ["The people must accept it", "The people may overthrow it", "The laws remain unchanged", "The monarch gains more power"], answer: 1, explanation: "This idea directly sparked the American and French Revolutions. 💥" },
    { id: 'q5', question: "What is Locke's concept of 'Tabula Rasa'?", options: ["A spicy food sauce", "The mind is a blank slate", "A secret magic trick", "A new flying machine"], answer: 1, explanation: "It destroyed the idea of 'Divine Right' bloodlines. ⬜" },
    { id: 'q6', question: "Which Enlightenment thinker is most famous for fiercely defending Freedom of Speech and attacking religious dogma?", options: ["The writer Voltaire", "The scientist Isaac Newton", "The astronomer Galileo Galilei", "The philosopher Plato"], answer: 0, explanation: "He was sarcastic, witty, and hated censorship. 🗣️" },
    { id: 'q7', question: "What did Baron de Montesquieu propose to prevent political tyranny?", options: ["A larger national army", "The separation of powers", "Higher taxes for kings", "Universal judicial authority"], answer: 1, explanation: "The hardware framework for modern democracies. 🏛️" },
    { id: 'q8', question: "What is 'Deism', a belief held by many Enlightenment thinkers?", options: ["Belief in multiple gods", "God as a clockmaker creator", "The rejection of all gods", "Worship of the natural sun"], answer: 1, explanation: "They believed God gave us Reason, not magic. 🕰️" },
    { id: 'q9', question: "How did the Scientific Revolution trigger the Enlightenment?", options: ["It caused widespread illness", "Applying logic to human society", "Proving the moon was cheese", "Inventing modern gunpowder"], answer: 1, explanation: "The Scientific Method was applied to government. 🔭" },
    { id: 'q10', question: "What was the purpose of Diderot's *Encyclopédie*?", options: ["To hide government secrets", "To spread all human knowledge", "To sell commercial advertising", "To publish epic poems"], answer: 1, explanation: "Knowledge is power, and the Encyclopédie gave it to the public. 📚" },
    { id: 'q11', question: "Jean-Jacques Rousseau wrote *The Social Contract*. What was its main argument?", options: ["Contracts are legally boring", "Government follows the general will", "Kings own all property", "Humans should live in nature"], answer: 1, explanation: "The people are the ultimate source of political power. 🤝" },
    { id: 'q12', question: "Who was Adam Smith?", options: ["A professional baker", "A free market economist", "A powerful ruling king", "The printing press inventor"], answer: 1, explanation: "He wrote *The Wealth of Nations* in 1776. 💰" },
    { id: 'q13', question: "What did Mary Wollstonecraft argue in *A Vindication of the Rights of Woman*?", options: ["Women should be queens", "Women need equal education", "Women should stay home", "Men are completely useless"], answer: 1, explanation: "The intellectual foundation of feminism. 👩‍⚖️" },
    { id: 'q14', question: "What was a major 'blind spot' or hypocrisy of the Enlightenment era?", options: ["They hated classical music", "Supporting liberty while practicing slavery", "They lacked mathematical skills", "They forgot how to read"], answer: 1, explanation: "The men who wrote 'all men are created equal' often owned slaves. 🌑" },
    { id: 'q15', question: "Which major historical event was the direct, bloody result of Enlightenment ideas boiling over?", options: ["World War I", "The French Revolution", "Building the Great Pyramids", "The Fall of Rome"], answer: 1, explanation: "They overthrew the king, but the pursuit of 'pure reason' led to the guillotine. 🗡️" },
    { id: 'q16', question: "Why did Kant believe humanity had been in a state of 'immaturity'?", options: ["People were physically short", "Relying on others for thought", "There were no public schools", "People had poor diets"], answer: 1, explanation: "He begged humans to have the courage to think for themselves. 🧠" },
    { id: 'q17', question: "What is the 'Invisible Hand' theory by Adam Smith?", options: ["A literal ghost", "Self-interest guides the market", "A secret government agency", "A powerful magic spell"], answer: 1, explanation: "Economic freedom added to the lists of natural rights. 🪙" },
    { id: 'q18', question: "How did the Enlightenment view 'Tradition'?", options: ["Tradition was perfect", "Skepticism toward old customs", "Reviving ancient Roman culture", "They loved traditional values"], answer: 1, explanation: "Reason destroys tradition. 🛡️" },
    { id: 'q19', question: "Which of the following modern ideas is NOT a product of the Enlightenment?", options: ["Establishing democratic government", "Separation of church and state", "Absolute divine monarchy", "Protecting freedom of speech"], answer: 2, explanation: "The Enlightenment specifically destroyed Absolute Monarchy. 👑" },
    { id: 'q20', question: "Why did the Pope and Kings try to ban the Enlightenment philosophers' books?", options: ["They used poor grammar", "To prevent challenges to power", "The books were too long", "They hated French authors"], answer: 1, explanation: "An educated public is impossible to enslave. 🔥" },
  ],

  relatedTopics: ['existentialism', 'stoicism', 'atheism'],
};
