// ─────────────────────────────────────────────────────────
//  TOPIC: WHY BE GOOD?
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'why_be_good',
  title: 'Why Be Good?',
  subtitle: 'The philosophy and biology of ethics ⚖️❤️',
  emoji: '⚖️',
  category: 'Society',
  accentKey: 'ethics',

  hook: {
    question: "If you had a magic ring that made you completely invisible, so you could steal and hurt people without EVER getting caught... would you still be a good person? 💍",
    reveal: "This is the Ring of Gyges, a famous thought experiment by Plato. It asks the ultimate question: Are humans good because we love goodness, or just because we are terrified of going to jail? For thousands of years, philosophers and neuroscientists have fiercely debated the nature of morality. Is ethics just a math equation (Utilitarianism), or is it a strict set of unbreakable rules (Deontology)? Let's find your moral compass! 🧭✨",
    emoji: '🔍',
  },

  theory: [
    {
      id: 'what_is_ethics',
      title: 'What is Ethics? 🤔',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🤔',
      svgIcon: 'book',
      content: "**Ethics** isn't just about 'not breaking the law'. The law allowed slavery for hundreds of years, but slavery was always fundamentally unethical! \n\nEthics is the philosophical study of *objective right and wrong*. It explores how we *ought* to act toward conscious creatures. It forces us to ask: What do we value? Human happiness? Avoiding pain? Fairness? \nWithout an ethical framework, we are just animals reacting to instincts. 🦁",
      highlight: "The law tells you what you *must* do. Ethics tells you what you *should* do. ⚖️",
    },
    {
      id: 'utilitarianism',
      title: 'Utilitarianism (The Math of Morality) 🧮',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🧮',
      svgIcon: 'users',
      content: "Created by Jeremy Bentham and John Stuart Mill, **Utilitarianism** states that the 'right' action is whatever causes you to maximize the total happiness (or minimize the total suffering) for the greatest number of people. \n\nIt is entirely focused on *outcomes*. To a strict utilitarian, lying is completely fine... IF that lie prevents 10 people from getting hurt. Morality becomes a ruthless calculus equation! ➕➖",
      highlight: "The ends absolutely justify the means. The only metric is total worldwide happiness. 📈",
    },
    {
      id: 'deontology',
      title: 'Deontology (The Rules) 📜',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📜',
      svgIcon: 'lock',
      content: "The opposite of Utilitarianism is **Deontology**, heavily developed by Immanuel Kant. \n\nDeontology states that morality is based on absolute, unbreakable *Rules*, regardless of the outcome. To Kant, lying is wrong. Period. Even if you lie to a murderer to protect your hidden friend! \nTo a deontologist, you cannot control the chaotic outcomes of the world, but you *can* control whether you obey the moral law. ⚖️",
      highlight: "The ends NEVER justify the means. Wrong actions are always wrong. 🛑",
    },
    {
      id: 'categorical_imperative',
      title: 'The Categorical Imperative 🌍',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🌍',
      svgIcon: 'target',
      content: "Kant gave us a tool to figure out what these absolute rules are: **The Categorical Imperative**. \n\nBefore you act, ask this: *'Would I be okay if EVERY single human on Earth did this exact same thing at the exact same time?'* \nIf you steal a candy bar, imagine a world where 8 billion people are stealing simultaneously. Commerce collapses. Humanity starves. Since it fails the test, stealing is objectively, categorically wrong! ❌",
      highlight: "Act only according to a rule that you wish would become a universal law of nature. 🌌",
    },
    {
      id: 'virtue_ethics',
      title: 'Virtue Ethics (Becoming Good) ⚔️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '⚔️',
      svgIcon: 'star',
      content: "Forget the math (Utilitarianism) and forget the rules (Deontology). Aristotle believed in **Virtue Ethics**. \n\nAristotle didn't care about judging individual actions. He said morality is about *Character*. Are you cultivating virtues like courage, honesty, and temperance? \nIf you relentlessly train your character to be virtuous, you don't need a rulebook to tell you not to steal; your very identity prevents it. A good tree naturally bears good fruit! 🌳",
      highlight: "Don't ask 'What is the right action?' Ask 'What kind of person should I become?' 🦸‍♂️",
    },
    {
      id: 'the_trolley_problem',
      title: 'The Trolley Problem 🚋',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🚋',
      svgIcon: 'zap',
      content: "The ultimate ethical test! A runaway train is heading toward 5 workers who will die. You stand next to a lever. If you pull it, the train diverts to a track with only 1 worker, killing him to save the 5. \n\n• **Utilitarian:** PULL IT! 1 death is mathematically better than 5 deaths. \n• **Deontologist:** DO NOT PULL IT! Pulling it means you actively committed a murder. Letting it go means the universe took 5 lives, but your soul is clean. \nWhat do you do?! 🤯",
      highlight: "Ethics is rarely Good vs Evil. It is usually Nightmare A vs Nightmare B. 🦇",
    },
    {
      id: 'altruism_biology',
      title: 'The Biology of Altruism 🫀',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🫀',
      svgIcon: 'heart',
      content: "Why be good? Let's leave philosophy and look at Neuroscience. \n\nEvolution hardwired us for **Altruism** (selflessness). When humans perform an act of kindness, the brain floods with *Oxytocin* (the bonding hormone), *Dopamine* (reward), and *Serotonin* (mood regulation). \nThis chemical cocktail reduces blood pressure, lowers cortisol, and literally heals your heart. You are a biological machine designed to help others! 🧬",
      highlight: "Being cruel degrades your biology. Being kind physically extends your lifespan. ⏱️",
    },
    {
      id: 'the_machiavellian_view',
      title: 'Machiavellianism 🐍',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🐍',
      svgIcon: 'lock',
      content: "In contrast to virtue, Niccolò Machiavelli wrote 'The Prince' as a manual for ruthless power.\n\nHe argued that morality was a weakness. **Machiavellianism** states that it is better to be feared than loved, and that a leader should lie, cheat, and destroy their rivals to maintain power. \nWhile this works briefly for dictators, science shows that Machiavellian individuals suffer from profound paranoia, isolation, and stress-induced heart attacks. 📉",
      highlight: "Ruthlessness buys temporary power, but it bankrupts your soul and your biology. 🕸️",
    },
    {
      id: 'moral_foundations',
      title: 'Moral Foundations Theory 🏛️',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'users',
      content: "Why do good people disagree so violently on politics? \n\nJonathan Haidt's **Moral Foundations Theory** proves we have different taste buds for morality. \nSome people value *Care and Fairness* above all else (typically Liberals). Others value *Loyalty, Authority, and Sanctity* just as highly (typically Conservatives). \nWhen you argue politics, you aren't fighting evil people; you are talking to people who emphasize a completely different moral foundation! 🧱",
      highlight: "Understanding morality as a 'spectrum' is the key to preventing hatred. 🤝",
    },
    {
      id: 'nietzsche_ubermensch',
      title: 'Nietzsche & Beyond Good/Evil 🦅',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🦅',
      svgIcon: 'eye',
      content: "Friedrich Nietzsche violently attacked traditional ethics. He argued that ideas like 'meekness' and 'pity' were 'Slave Morality' invented by weak people to control the strong. \n\nHe suggested we move *Beyond Good and Evil* to become the **Übermensch** (Superman). The Superman creates his OWN values, forging his own destiny with absolute power and aesthetic beauty. \nNietzsche's ideas are brilliant but extremely dangerous if misapplied! ⚡",
      highlight: "He challenged us to stop following the herd and author our own meaning. ✍️",
    },
    {
      id: 'kohlberg_stages',
      title: 'Kohlberg’s Stages of Morality 📈',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '📈',
      svgIcon: 'chart',
      content: "How does a child learn right from wrong? Lawrence Kohlberg mapped it out:\n1. **Pre-conventional:** I'm good so I don't get punished by mom. 👶\n2. **Conventional:** I'm good because it's the law and society expects it. 🧑\n3. **Post-conventional:** I'm good because I believe in universal human rights, even if I have to break an unjust law to defend them! 🦸‍♂️\n\nMany adults never make it to stage 3! 🧗‍♂️",
      highlight: "Are you obeying out of fear, or acting out of profound principle? ⚖️",
    },
    {
      id: 'ethical_egoism',
      title: 'Ethical Egoism (Ayn Rand) 🏢',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏢',
      svgIcon: 'target',
      content: "**Ethical Egoism** (championed by Ayn Rand) argues that the greatest moral act you can perform is acting in your absolute rational *self-interest*. \n\nRand argued that altruism (sacrificing yourself for others) is destructive. She believed that if everyone ruthlessly pursued their own excellence and traded fairly, society would reach its maximum potential. \nCritics argue this philosophy creates a brutal, terrifying world for the poor and disabled. 📉",
      highlight: "Is selfishness a virtue, or is it the destruction of humanity? 🪞",
    },
    {
      id: 'the_buddhist_view',
      title: 'The Buddhist View (Karma & Compassion) 🪷',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🪷',
      svgIcon: 'refresh',
      content: "Eastern philosophy offers a different view: Morality isn't about rules; it is about *Karma* (cause and effect). \n\nBuddhism teaches that the illusion of the 'Self' causes all suffering. If you realize that you and the stranger on the street are essentially the same universal energy, hurting them is literally hurting yourself! \nAbsolute, boundless compassion for all living things isn't just a duty; it is the natural result of waking up. 🌅",
      highlight: "You cannot harm another without simultaneously causing damage to your own soul. 🗡️",
    },
    {
      id: 'the_banality_of_evil',
      title: 'The Banality of Evil 📎',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '📎',
      svgIcon: 'cloud',
      content: "Hannah Arendt coined the phrase **The Banality of Evil** after covering the trial of a Nazi war criminal. \n\nShe was shocked to discover he wasn't a psychotic, cackling cartoon villain. He was an incredibly boring, normal bureaucrat who simply 'followed orders' and stopped thinking for himself. \nTrue evil rarely announces itself with a cape and a sword. It usually happens quietly in office buildings when normal people stop caring. 🏢🗄️",
      highlight: "Evil thrives on apathy, routine, and a refusal to question authority. 🛑",
    },
    {
      id: 'why_be_good_conclusion',
      title: 'So, Why Be Good? ✨',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '✨',
      svgIcon: 'shield',
      content: "If there is no invisible magical ring... why be good? \n\nBecause being 'bad' isolates you, causes extreme biological stress, and destroys the social trust required for human civilization to exist. \nBut beyond that... being good is the ultimate expression of human freedom. You have the power to inject light into a chaotic, dark universe. You be good because the world is fragile, and goodness is the only architect that can hold it together. 🌌❤️",
      highlight: "A life devoid of an ethical code is a life devoid of meaning. 🧭",
    },
  ],

  lab: {
    title: "The Ethical Compass ⚖️🚋",
    description: "Welcome to the Morality Machine. A catastrophe is unfolding: 5 people are trapped on Track A, and 1 person is on Track B. You control the Ethics Sliders. Shift the weights between 'Utilitarianism' (focusing on numbers) and 'Deontology' (focusing on rules/guilt). See how the philosophical framework literally alters the decision output! Which philosophy matches your personal conscience? 🎛️",
    hint: "If you slide Utilitarianism to 100%, the machine will ruthlessly sacrifice the 1 person to save 5. If you slide Deontology to 100%, the machine will refuse to 'pull the lever', letting nature take its course because actively killing is a rule violation.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Bentham's 'Felicific Calculus' outputs, Kantian Categorical violation flags, and neuro-moral activity mapping.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why psychopaths excel in the business world? 👔",
      answer: "Lack of Amygdala empathy! While a normal CEO might lose sleep over firing 500 people, a psychopath's brain does not process emotional guilt. This allows them to make ruthlessly efficient, ice-cold utilitarian decisions that maximize profits at the expense of human suffering. Around 4% to 12% of CEOs display psychopathic traits! 🏢",
      emoji: '📈',
    },
    {
      id: 'dyk2',
      question: "Do you know why giving to charity literally gives you a 'Helper's High'? 🥰",
      answer: "Evolutionary Biology! Because human survival relied on the tribe working together, your brain evolved a chemical reward system for altruism. When you help someone, your brain releases a massive surge of Endorphins (similar to a runner's high) followed by Oxytocin (the love hormone)! 🧬",
      emoji: '🫀',
    },
    {
      id: 'dyk3',
      question: "Do you know why we feel worse stealing $5 cash than stealing a $5 pen? 🖊️",
      answer: "Psychological Distance! Dan Ariely's research proved that the further away an item gets from 'raw money', the easier it is to bypass our moral compass. Our brain easily rationalizes taking a pen ('the company has millions of them'), but physically taking cash triggers a profound 'I am a thief' response! 💵",
      emoji: '📏',
    },
    {
      id: 'dyk4',
      question: "Do you know why babies as young as 6 months prefer 'helpful' puppets over 'mean' ones? 🍼",
      answer: "Morality is partially innate! Yale's Baby Lab showed infants a puppet show where a good puppet helps open a box, and a bad puppet slams it shut. Over 80% of babies reached for the helpful puppet afterward. We are born with a baseline 'moral grammar' before society even teaches us! 👶",
      emoji: '🧸',
    },
    {
      id: 'dyk5',
      question: "Do you know why people blame victims (e.g., 'They shouldn't have been walking there')? 🛡️",
      answer: "The 'Just-World Hypothesis'. The human brain is terrified of the idea that bad things happen to good people randomly. To protect its own sanity, the brain prefers to believe the universe is 'fair'. If the universe is fair, then the victim MUST have done something to deserve it. It is a psychological defense mechanism! 🌎",
      emoji: '⚖️',
    },
    {
      id: 'dyk6',
      question: "Do you know why anonymity turns normal people into horrific internet trolls? 💻",
      answer: "The 'Ring of Gyges' effect! In psychology, it's called Deindividuation. When you remove a person's name and face, you disconnect them from social accountability. Without the fear of the tribe punishing them, their darkest, suppressed inner monsters are let off the leash. 🐉",
      emoji: '🎭',
    },
    {
      id: 'dyk7',
      question: "Do you know why Kant believed you could NEVER lie, even to save a life? 📜",
      answer: "Because logic breaks! Kant argued that if 'lying to save a life' became a universal rule, nobody would ever believe anyone anymore. Language and trust would completely collapse, meaning your lie wouldn't even work! His Deontology was terrified of contradictions. 😵",
      emoji: '🏛️',
    },
    {
      id: 'dyk8',
      question: "Do you know why you care more about a local dog trapped in a well, than 10,000 people starving halfway across the world? 🐕",
      answer: "The Identifiable Victim Effect! Our primitive brains cannot compute large numbers or abstract statistics (10,000 people). We feel no emotional pull. But show us one specific, named face (a dog or a child in a well), and our empathy circuits explode with urgency. Statistics don't bleed! 🩸",
      emoji: '📉',
    },
    {
      id: 'dyk9',
      question: "Do you know why 'Moral Licensing' ruins diets and ethical behavior? 🥗",
      answer: "The brain keeps a moral scoreboard! If you eat a healthy salad for lunch (acting 'good'), your brain grants you a 'license' to cheat and eat an entire cake for dinner (acting 'bad'). This extends to morality: people who donate to charity often act more selfishly later in the day, feeling they 'earned' the right to be bad! 📝",
      emoji: '💳',
    },
    {
      id: 'dyk10',
      question: "Do you know why Nietzsche said 'God is dead', and why it terrified him? 🦅",
      answer: "It wasn't a celebration; it was a warning! Nietzsche realized that science was destroying religious belief in Europe. Without God as the objective source of morality, he predicted humanity would fall into terrifying Nihilism resulting in massive wars (which soon happened). He begged humanity to create its own strong values before it was too late! 🌩️",
      emoji: '💀',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the core difference between Law and Ethics?", options: ['Law is written; Ethics is spoken', 'Law tells you what must be done to avoid jail; Ethics explores what is objectively right to do', 'Law is for adults; Ethics is for kids', 'There is no difference'], answer: 1, explanation: "An action can be 100% legal, but completely unethical! ⚖️" },
    { id: 'q2', question: "Utilitarianism is the ethical theory that states you should:", options: ['Only care about utilities like water', 'Follow strict rules', 'Maximize the total happiness/well-being for the greatest number of people', 'Read books'], answer: 2, explanation: "It is a math equation where the Ends absolutely justify the Means! 🧮" },
    { id: 'q3', question: "Deontology (Duty Ethics) argues that morality is based on:", options: ['Absolute, unbreakable rules (Ends NEVER justify Means)', 'Predicting the future', 'Emotions', 'Animals'], answer: 0, explanation: "Deontologists focus on DOING the right thing, ignoring the consequences. 📜" },
    { id: 'q4', question: "Kant's 'Categorical Imperative' asks you to test an action by imagining:", options: ['If animals did it', 'If EVERY human on earth did it simultaneously (Universal Law)', 'If it caused pain', 'If a king did it'], answer: 1, explanation: "If universalizing the action collapses society, the action is categorically wrong! 🌍" },
    { id: 'q5', question: "Virtue Ethics (Aristotle) focuses on:", options: ['Building good character habits (courage, honesty) rather than writing rules', 'Doing math', 'Screaming', 'Building houses'], answer: 0, explanation: "A good tree naturally drops good fruit. Cultivate the tree! 🌳" },
    { id: 'q6', question: "In the famous 'Trolley Problem', pulling the lever to kill 1 person to save 5 is the textbook example of:", options: ['Utilitarianism', 'Deontology', 'Virtue Ethics', 'Nihilism'], answer: 0, explanation: "Using math to minimize total human death! 🚋" },
    { id: 'q7', question: "Biologically, what happens when you perform an act of altruism (kindness)?", options: ['Cortisol spikes', 'The brain unleashes Oxytocin and Endorphins, reducing stress and healing the body', 'You lose hair', 'Your heart stops'], answer: 1, explanation: "Ethics is built directly into your endocrine system! 🫀" },
    { id: 'q8', question: "Niccolò Machiavelli ('The Prince') argued that:", options: ['Love is the answer', 'Kindness is a weakness; leaders must be ruthless and feared to maintain power', 'We must run away', 'Trees are pretty'], answer: 1, explanation: "The dark psychology of power and manipulation! 🐍" },
    { id: 'q9', question: "According to Moral Foundations Theory, why do conservatives and liberals argue?", options: ['Because one side is evil', 'Because they emphasize completely different moral \'taste buds\' (e.g., Care vs. Loyalty/Sanctity)', 'Because they hate words', 'Magic'], answer: 1, explanation: "You aren't fighting a villain; you are fighting someone who weights authority higher than fairness! ⚖️" },
    { id: 'q10', question: "Lawrence Kohlberg's final 'Post-Conventional' stage of morality is when a person:", options: ['Complies to avoid punishment', 'Acts from profound universal principles, even if it forces them to break an unjust law', 'Cries', 'Sleeps all day'], answer: 1, explanation: "It is the realm of MLK and Gandhi! 🧗‍♂️" },
    { id: 'q11', question: "What does 'The Banality of Evil' (Hannah Arendt) mean?", options: ['Evil is funny', 'Evil is often committed by boring, normal people who simply \'follow orders\' and stop thinking', 'Evil is ugly', 'Evil is magic'], answer: 1, explanation: "The most horrific things are done by bureaucrats stamping papers. 📎" },
    { id: 'q12', question: "Ethical Egoism (Ayn Rand) argues that the greatest absolute moral good is:", options: ['Giving money to charity', 'Pursuing your own rational self-interest completely', 'Hugging', 'Swimming'], answer: 1, explanation: "She believed altruism was a plague that destroyed achievement! 🏢" },
    { id: 'q13', question: "The 'Ring of Gyges' thought experiment asks:", options: ['Would you wear a ring?', 'If you had a ring that made you invisible/immune to punishment, would you still be a good person?', 'Can rings fly?', 'What is gold?'], answer: 1, explanation: "It tests whether we love being good, or merely fear the police! 💍" },
    { id: 'q14', question: "What is Buddhist 'Karma' fundamentally about regarding ethics?", options: ['Magic points', 'Because we are all one energy, hurting someone else is literally damaging your own self/soul', 'A bank account', 'Animals'], answer: 1, explanation: "Compassion is the logical result of recognizing the illusion of separation! 🪷" },
    { id: 'q15', question: "The 'Identifiable Victim Effect' explains why we:", options: ['Donate massive amounts to save one specific dog, but ignore the deaths of 10,000 abstract humans', 'Victimize people', 'Cannot identify friends', 'Lose our keys'], answer: 0, explanation: "The primitive brain cannot compute large statistics, so it feels zero empathy for numbers. 📉" },
    { id: 'q16', question: "What is 'Moral Licensing'?", options: ['A driver license', 'Acting \'good\' (like eating a salad) causes the brain to grant itself permission to act \'bad\' (eating cake) later', 'A college degree', 'Paying for water'], answer: 1, explanation: "The brain keeps a scorecard of your behavior! 📝" },
    { id: 'q17', question: "The 'Just-World Hypothesis' causes humans to:", options: ['Build globes', 'Blame innocent victims because it is too terrifying to accept that the universe is cruel and random', 'Plant trees', 'Hate planets'], answer: 1, explanation: "We comfort ourselves by pretending bad things only happen to bad people. 🌎" },
    { id: 'q18', question: "Why do some psychopaths succeed as CEOs?", options: ['They are aliens', 'A lack of Amygdala empathy allows them to make ice-cold utilitarian decisions that maximize profit', 'They sleep less', 'They yell'], answer: 1, explanation: "They lack the biological brakes (guilt) that stop normal people. 👔" },
    { id: 'q19', question: "Nietzsche's 'Übermensch' (Superman) is a concept about:", options: ['Flying over cities', 'Throwing away herd morality to forge your own powerful, aesthetic values and meaning', 'Wearing capes', 'Lifting heavy weights'], answer: 1, explanation: "A terrifyingly beautiful challenge to become the author of your own existence. 🦅" },
    { id: 'q20', question: "Ultimately, without ethics, human civilization would:", options: ['Be fun', 'Instantly collapse into a primitive, brutal struggle for survival', 'Be quiet', 'Evolve instantly'], answer: 1, explanation: "Moral philosophy is the glue holding the atoms of society together. 🧱" },
  ],

  relatedTopics: ['good_citizen', 'meaningful_life', 'social_media_trap'],
};
