// ─────────────────────────────────────────────────────────
//  TOPIC: LONELINESS (अकेलापन)
//  Category: Mental Health
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'loneliness',
  title: 'Loneliness',
  subtitle: 'The Biological Hunger for Connection 🌕🧠',
  emoji: '🌕',
  category: 'Mental Health',
  accentKey: 'loneliness',

  hook: {
    question: "Why does being rejected by a group hurt just as much as breaking a bone?",
    reveal: "Because to your brain, they are the exact same emergency.\n\nLoneliness is not just a 'sad feeling'. It is a biological drive, exactly like hunger or thirst. If you are hungry, your body is saying 'Find food before you starve.' When you are lonely, your body is screaming, 'Find your tribe before you are eaten by a predator.' Let's explore the shocking biology of isolation and how it physically changes the brain. 🐺🏕️🧩",
    emoji: '🐺',
  },

  theory: [
    {
      id: 'loneliness_vs_alone',
      title: "Solitude vs. Loneliness 🧘‍♂️",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'user',
      svgIcon: 'eye',
      content: "**Being Alone (Solitude)** is a physical state. You can be blissfully happy reading a book alone in a cabin. It restores your energy.\n\n**Loneliness** is a psychological state. It is the gap between the social connections you *want* and the ones you *have*. This is why you can feel intensely lonely in a crowded room, at a party, or even in a marriage.",
      highlight: "Loneliness isn't about being by yourself; it's about feeling unseen and disconnected. 🔭",
    },
    {
      id: 'biological_hunger',
      title: "The Hunger Signal 🍔",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'radio',
      svgIcon: 'activity',
      content: "Evolutionary biologists view loneliness as a biological warning system.\nMillions of years ago, a human separated from the tribe would quickly die from starvation, cold, or predators. To prevent this, the brain evolved 'Loneliness' as a painful alarm bell to force you to return to the group.\nJust as physical pain protects your body from fire, social pain protects you from isolation.",
      highlight: "You aren't broken for feeling lonely; your survival software is just working perfectly. 🚨",
    },
    {
      id: 'brain_overlap',
      title: "The Pain Matrix 🧠",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'activity',
      svgIcon: 'zap',
      content: "When neuroscientists put socially rejected people in fMRI scanners, they found something astonishing: the *dorsal anterior cingulate cortex* lighted up.\nThis is the exact same brain region that processes physical pain.\nTo your brain, a heart-wrenching breakup or being left out of a group chat causes literal, neurological pain. Tylenol has even been shown to slightly reduce the pain of rejection.",
      highlight: "'Broken heart' is not just poetry; it is a neurological reality. 💔",
    },
    {
      id: 'hypervigilance',
      title: "The Paranoia Effect 🦇",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'eye',
      svgIcon: 'alert',
      content: "When you are lonely, your brain assumes you are without the protection of a tribe, so it goes into **Hyper-vigilance mode**.\nIt constantly scans the environment for threats. Because of this, a lonely brain starts misinterpreting neutral social cues as hostile.\nIf a friend is quiet, a healthy brain thinks: 'They must be tired.' A lonely brain thinks: 'They hate me.'",
      highlight: "Loneliness creates a distorted lens that makes the world look colder and crueler than it actually is. 🕶️",
    },
    {
      id: 'the_vicious_cycle',
      title: "The Loneliness Spiral 🌪️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'refresh-ccw',
      svgIcon: 'compass',
      content: "Because of hyper-vigilance, lonely people become defensive, awkward, or cynical. \nThey push people away to avoid 'inevitable' rejection. \nThis creates a tragic, self-fulfilling prophecy:\nFeel Lonely → Assume people don't like you → Act defensively/Withdraw → People pull away → Feel more lonely.",
      highlight: "The lonely brain tricks you into destroying the exact connections you are starving for. 🧱",
    },
    {
      id: 'health_impact',
      title: "As Deadly as Smoking 🚬",
      color: '#673AB7',
      bgGradient: ['#1A0030', '#050010'],
      icon: 'heart',
      svgIcon: 'flame',
      content: "Dr. John Cacioppo's research found that chronic loneliness is a severe medical condition.\nBecause the lonely body is in a constant state of 'Fight or Flight' stress, cortisol levels remain chronically high. This causes inflammation, high blood pressure, and damages the immune system.\nMedical consensus states that chronic loneliness is as lethal as smoking 15 cigarettes a day.",
      highlight: "Loneliness doesn't just hurt your feelings; it damages your cardiovascular system. 🩺",
    },
    {
      id: 'social_baseline_theory',
      title: "Social Baseline Theory 🧗‍♂️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'users',
      svgIcon: 'target',
      content: "Psychologist James Coan found that when people looked at a steep hill while alone, they estimated it was 10-20% steeper than it actually was.\nWhen they stood with a friend, the hill looked flatter.\n**Social Baseline Theory** argues that the human brain assumes 'togetherness' is the default state. When we are alone, our brain perceives the entire physical world as more difficult, heavier, and more dangerous.",
      highlight: "The presence of a friend literally changes how your eyes perceive physical obstacles. ⛰️",
    },
    {
      id: 'dunbars_number',
      title: "Dunbar's Number 📊",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'pie-chart',
      svgIcon: 'users',
      content: "Anthropologist Robin Dunbar proposed that the human brain can only maintain about **150 stable social relationships** due to the size of our neocortex.\nOf those, only about 5 form your 'inner circle' (closest support), and 15 form your 'sympathy group' (good friends).\nYou don't need 1,000 Instagram followers to beat loneliness; you just need 3-5 people who would help you move a couch.",
      highlight: "Quality of connection crushes quantity. Depth matters more than width. 🛋️",
    },
    {
      id: 'modern_epidemic',
      title: "The Illusion of Connection 📱",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'smartphone',
      svgIcon: 'lock',
      content: "We are the most 'connected' generation in history, yet the loneliest.\nWhy? Social media provides 'junk food' connection. It gives you small hits of dopamine (likes), but lacks the deep, oxytocin-releasing vulnerable connection of a face-to-face conversation. \nIt's like eating a diet of only candy; you are full, but totally malnourished.",
      highlight: "A text message doesn't release oxytocin (the bonding hormone). A hug or hearing a voice does. 🍬",
    },
    {
      id: 'parasocial_relationships',
      title: "Parasocial Relationships 📺",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'tv',
      svgIcon: 'star',
      content: "When lonely, the brain tries to find substitutes. \nA **Parasocial Relationship** is a one-sided bond formed with a podcaster, YouTuber, or fictional character. Your brain processes them as a 'real' friend, providing temporary relief from loneliness.\nWhile normal in small doses, relying on them heavily prevents you from seeking actual human bonds that require two-way effort and vulnerability.",
      highlight: "The podcaster doesn't know you exist. They cannot help you when you fall. 🎙️",
    },
    {
      id: 'vulnerability',
      title: "The Cure: Vulnerability 🛡️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'unlock',
      svgIcon: 'shield',
      content: "To cure loneliness, you have to bypass the 'Hyper-vigilance' defense mechanism.\nThis requires **Vulnerability**: sharing genuine thoughts, fears, or mistakes with someone, risking judgment.\nIf you only ever present a 'perfect' fake version of yourself to the world, and people like you, you will *still* feel lonely—because you know they don't like the *real* you.",
      highlight: "Perfection creates distance. Flaws create connection. 🪞",
    },
    {
      id: 'micro_interactions',
      title: "The Power of Micro-Interactions ☕",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'coffee',
      svgIcon: 'heart',
      content: "You don't need a soulmate to start lowering cortisol levels.\nSociologists have found that **Micro-Interactions**—smiling at a barista, chatting with a cashier, or greeting a neighbor—provide immediate, measurable boosts in belonging.\nThese small 'weak ties' signal to the primal brain: 'You are part of a community. You are safe.'",
      highlight: "Don't look at your phone in line. Look up. Those 30 seconds of small talk are medicine. 👋",
    },
    {
      id: 'shared_purpose',
      title: "Side-by-Side Connection 🚶‍♂️🚶‍♀️",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'map',
      svgIcon: 'compass',
      content: "Many people (especially men) struggle to build friendships via 'face-to-face' talking. \nEvolutionarily, a lot of human bonding happens 'side-by-side' while working toward a **Shared Purpose**—hunting, building, or defending.\nJoining a volunteer group, a sports league, or a coding club bypasses the awkwardness of 'forced conversation' and builds organic bonds through shared effort.",
      highlight: "If you want friends, don't look for friends. Look for a shared mission. 🎯",
    },
    {
      id: 'self_compassion',
      title: "Befriending Yourself 🧘‍♀️",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'heart',
      svgIcon: 'leaf',
      content: "If you cannot be alone without feeling lonely, you are in bad company.\nThe foundation of curing loneliness is **Self-Compassion**. If your internal monologue is constantly criticizing you ('You are a loser, no one likes you'), you are creating a hostile environment inside your own head.\nTreat yourself with the same gentle grace you would offer a lost child.",
      highlight: "You are the only person you will spend every second of your life with. Make peace with them. 🕊️",
    },
    {
      id: 'asking_for_help',
      title: "Making the First Move ♟️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'chevrons-up',
      svgIcon: 'users',
      content: "The lonely brain says: 'If they wanted to hang out, they would call me.'\nBut the reality is: *Everyone else is lonely and waiting for someone to call them too.*\nTaking the initiative to reach out, plan a coffee, or say 'I've been feeling isolated lately' requires massive courage, but it breaks the stalemate. Be the person who organizes the dinner.",
      highlight: "Stop waiting for an invitation. Become the inviter. 💌",
    },
  ],

  lab: {
    title: "The Hyper-Vigilance Distorter 🕶️📲",
    description: "Your subject is experiencing severe loneliness, putting their brain into 'hyper-vigilance' mode. In this mode, neutral text messages look like hostile rejections. You must analyze incoming texts, recognize the distortion, and choose the healthy, non-defensive response before the relationship is destroyed.",
    hint: "The lonely brain ALWAYS assumes the worst intention. Look for the most generous interpretation of the ambiguous text.",
    scientistModeHint: "Cognitive Parsing Mode 🧑‍🔬: Decrypt linguistic ambiguity and track perceived rejection bias.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do we feel physically cold when we are lonely?", answer: "Studies show that social exclusion literally lowers body temperature! Subjects who recalled a time they were rejected estimated the room temperature to be significantly colder than subjects who recalled being loved. 'Cold shoulder' is a biological fact. 🥶", emoji: '❄️' },
    { id: 'dyk2', question: "Why does being lonely make you crave warm baths or hot drinks?", answer: "Since physical warmth and social warmth are processed in the same area of the brain (the Insula), holding a hot mug of coffee or taking a hot shower physically 'tricks' the brain into feeling a temporary sensation of social comfort. ☕", emoji: '🛀' },
    { id: 'dyk3', question: "Why do lonely people often talk 'too much' when they finally get someone's attention?", answer: "It's called the 'Starvation Response'. Just like someone who hasn't eaten in days might gorge themselves and get a stomach ache if presented with a buffet, a socially starved person might overshare or monopolize a conversation, accidentally pushing the other person away. 🗣️", emoji: '🍽️' },
    { id: 'dyk4', question: "Why do we fall asleep faster when someone we trust is next to us?", answer: "In the wild, sleeping alone meant you had to keep one ear open for predators (hyper-vigilance). When sleeping next to a trusted tribe member, your brain knows 'they will keep watch', allowing your nervous system to fully power down into deep REM sleep. 😴", emoji: '🛏️' },
    { id: 'dyk5', question: "Why do lonely brains wake up more often during the night?", answer: "Micro-awakenings. A lonely brain does not feel completely safe, so it evolutionarily prevents you from sinking into prolonged, vulnerable deep sleep. It wakes you up slightly to check for tigers! 🐅", emoji: '👀' },
  ],

  quiz: [
    { id: 'q1', question: "What is the difference between Solitude and Loneliness?", options: ["Solitude is temporary, loneliness is permanent", "Solitude is pleasant, loneliness is distressing", "Solitude is harmful, loneliness is helpful", "Both terms mean the same thing"], answer: 1, explanation: "You can be alone and happy (Solitude). You can be in a crowd and miserable (Loneliness). 🧘‍♂️" },
    { id: 'q2', question: "Evolutionarily, why does loneliness feel so painful?", options: ["To punish bad social behavior", "To signal a need for connection", "Because the brain physically shrinks", "It is a biological glitch"], answer: 1, explanation: "Pain is the body's way of saying: 'Fix this right now or you will die.' 🚨" },
    { id: 'q3', question: "Which physical ailment uses the SAME brain region as social rejection?", options: ["The common cold symptoms", "Physical pain from an injury", "Chronic asthma attacks", "Severe seasonal allergies"], answer: 1, explanation: "The dorsal anterior cingulate cortex processes both a broken arm and a broken heart. 💔" },
    { id: 'q4', question: "What is 'Hyper-vigilance' in a lonely brain?", options: ["Having superior physical eyesight", "Scanning for social threats", "Sleeping for long periods", "Forgetting people's names"], answer: 1, explanation: "The lonely brain expects to be attacked, so it sees attacks everywhere. 🕶️" },
    { id: 'q5', question: "How physically dangerous is chronic, long-term loneliness to the human body?", options: ["It causes mild headaches", "As lethal as heavy smoking", "It is physically harmless", "It improves immune function"], answer: 1, explanation: "Constant cortisol (stress) destroys the cardiovascular system over time. 🚬" },
    { id: 'q6', question: "What does the 'Social Baseline Theory' suggest?", options: ["People prefer standing in lines", "The brain's default is togetherness", "Everyone should act the same", "Math is harder when alone"], answer: 1, explanation: "Your brain calculates 'I don't have help, so this mountain is dangerous.' ⛰️" },
    { id: 'q7', question: "What is 'Dunbar\'s Number'?", options: ["A complex mathematical equation", "Limit of 150 stable relationships", "Number of social media followers", "A specific emergency phone number"], answer: 1, explanation: "You don't need thousands of connections. You only need a core 5, and a solid 15. 📊" },
    { id: 'q8', question: "Why doesn't scrolling social media cure loneliness?", options: ["It costs too much data", "Lacks deep, vulnerable connection", "Screens emit too much light", "It only works during mornings"], answer: 1, explanation: "You can starve to death while eating an endless amount of cotton candy. 📱" },
    { id: 'q9', question: "What is a 'Parasocial Relationship'?", options: ["Dating a spiritual ghost", "One-sided bond with a celebrity", "A professional work relationship", "Hating a specific person"], answer: 1, explanation: "It tricks the brain into feeling accompanied, but requires no real vulnerability. 📺" },
    { id: 'q10', question: "What is required to form a genuine connection and overcome loneliness?", options: ["Being a perfect person", "Vulnerability and sharing true self", "Having a lot of money", "Being a very funny person"], answer: 1, explanation: "If you only show people a fake mask, they only love the mask. You stay lonely. 🛡️" },
    { id: 'q11', question: "Why do 'Micro-Interactions' (like chatting with a barista) matter?", options: ["Getting free coffee rewards", "Signaling safety to the brain", "Wasting valuable daily time", "Burning extra physical calories"], answer: 1, explanation: "Small moments of eye contact and an exchange of smiles are daily medicine. ☕" },
    { id: 'q12', question: "What is the 'Loneliness Spiral' (Self-fulfilling prophecy)?", options: ["A physical state of dizziness", "Defensive behavior pushing others away", "A pattern of losing weight", "A habit of walking alone"], answer: 1, explanation: "The brain's defense mechanism accidentally ruins the connections you desperately want. 🌪️" },
    { id: 'q13', question: "Are men or women more likely to bond 'side-by-side' (Shared Purpose)?", options: ["Women bonding through conversation", "Men bonding through shared activities", "Both genders bonding through talk", "Neither gender bonding through work"], answer: 1, explanation: "Evolutionarily, hunters bonded by staring at the prey together, not at each other. 🚶‍♂️🚶‍♀️" },
    { id: 'q14', question: "What physical sensation can temporarily 'trick' the brain into feeling socially comforted?", options: ["Being extremely cold", "Feeling physical warmth", "Experiencing physical pain", "Being physically wet"], answer: 1, explanation: "Physical and social warmth are processed in the same part of the brain (Insula). 🛀" },
    { id: 'q15', question: "Why do lonely people often suffer from poor sleep quality?", options: ["Watching too much television", "Brain scanning for threats", "Consuming too much caffeine", "The bed is too hard"], answer: 1, explanation: "The lonely brain keeps one eye open for tigers. 🐅" },
    { id: 'q16', question: "What is the best way to break a long period of isolation?", options: ["Waiting for a text", "Taking initiative to connect", "Moving to another country", "Complaining to people online"], answer: 1, explanation: "Be the inviter. Assume everyone else is also scared to ask. ♟️" },
    { id: 'q17', question: "Why is 'Self-Compassion' the foundation of curing loneliness?", options: ["It makes you arrogant", "Criticizing yourself makes solitude unbearable", "It costs too much money", "It is a waste of time"], answer: 1, explanation: "You cannot escape your own mind. Make it a safe place to live. 🧘‍♀️" },
    { id: 'q18', question: "Why is taking Tylenol sometimes effective for heartbreak?", options: ["It lowers high fevers", "Rejection triggers physical pain regions", "It makes you feel sleepy", "It acts as a placebo"], answer: 1, explanation: "While true, taking pills is not a long-term solution for social isolation! 💊" },
    { id: 'q19', question: "What happens when a socially 'starved' person finally talks to someone?", options: ["They become very quiet", "Oversharing to find connection", "They become very angry", "They fall asleep quickly"], answer: 1, explanation: "It's important to pace yourself, just like eating after a long fast. 🍽️" },
    { id: 'q20', question: "Why does rejection make us feel physically colder?", options: ["The heart rate slows down", "It lowers perceived body temperature", "The skin becomes very sensitive", "Blood pressure drops significantly"], answer: 1, explanation: "The slang term 'getting the cold shoulder' is biologically accurate. 🥶" },
  ],

  relatedTopics: ['depression', 'anxiety', 'evolutionary_psychology'],
};
