export default {
  // ── IDENTITY ────────────────────────────────
  id: 'photosynthesis',
  title: 'Photosynthesis',
  subtitle: 'The ultimate solar-powered factory 🌿',
  emoji: '🌿',
  category: 'Biology',
  accentKey: 'leaf',

  // ── CURIOSITY HOOK ──────────────────────────
  hook: {
    question: "Did you know that every single breath of oxygen you take right now was created by a plant splitting water in half? 🤯",
    reveal: "Plants are the ultimate magicians! They literally build solid wood, tasty fruits, and colorful flowers out of thin air (CO2) and sunshine. It's the most important chemical reaction on Earth. Without photosynthesis, all the animals—including us—would starve and suffocate. We are entirely running on solar energy captured by plants! 🌞🌿🌍",
    emoji: '☀️',
  },

  // ── THEORY CARDS ────────────────────────────
  theory: [
    {
      id: 'what_is_photosynthesis',
      title: 'What is Photosynthesis? 🌱',
      color: '#39FF14',
      bgGradient: ['#0D2B0D', '#0A0A0F'],
      icon: '🌱',
      svgIcon: 'leaf',
      content: "Photosynthesis is the process by which plants, algae, and some bacteria turn *light energy into chemical energy*. \n\nThink of a leaf as a tiny, highly advanced solar panel. But instead of generating electricity, it uses the sun's energy to *cook up food* (sugar) from simple ingredients available in its environment.\n\nHere's the recipe: \n🔹 **Sunlight** (Energy)\n🔹 **Carbon dioxide (CO₂)** from the air\n🔹 **Water (H₂O)** from the roots\n\nThe plant mixes these together to create **Glucose (sugar)** for its own fuel, and magically releases **Oxygen (O₂)** as a waste product, which is what we breathe! 🌬️",
      highlight: "Plants take in sunlight, water, and CO₂, and produce sugar and oxygen! 🌱",
    },
    {
      id: 'the_chloroplast',
      title: 'The Chloroplast: The Factory 🏭',
      color: '#00D4FF',
      bgGradient: ['#0A1A25', '#0A0A0F'],
      icon: '🏭',
      svgIcon: 'microscope',
      content: "Where does this magic happen? Inside plant cells, there are tiny green structures called **chloroplasts**. \n\nEach leaf cell contains 10 to 100 chloroplasts. Inside them, you'll find stacks of disc-like structures called **thylakoids** (looking like stacks of green pancakes 🥞) which form **grana**. \n\nThe empty fluid-filled space around the grana is called the **stroma**.\n\nIt's this tiny cellular factory where the light-dependent reactions (in the thylakoids) and the Calvin cycle (in the stroma) take place. This microscopic machinery is what keeps our entire planet alive! 🌍",
      highlight: "Chloroplasts are the miniature green factories inside plant cells where photosynthesis happens! 🏭",
    },
    {
      id: 'chlorophyll',
      title: 'Chlorophyll: The Solar Panel ☀️',
      color: '#22C55E',
      bgGradient: ['#052010', '#0A0A0F'],
      icon: '☀️',
      svgIcon: 'sun',
      content: "Why are plants green? It's all because of a special pigment called **chlorophyll**, located inside the thylakoids.\n\nChlorophyll acts as a biological solar panel. Its job is to capture photons (particles of light). It is incredibly good at absorbing **red and blue** light wavelengths, but it is terrible at absorbing **green** light.\n\nBecause it can't use green light, it *reflects* it back to our eyes! That's right—plants are green precisely because green is the one color of light they *reject*. 💥",
      highlight: "Plants look green because chlorophyll absorbs red/blue light and reflects the green light! ☀️",
    },
    {
      id: 'light_reactions',
      title: 'Phase 1: The Light Reactions ⚡',
      color: '#FACC15',
      bgGradient: ['#2A250A', '#0A0A0F'],
      icon: '⚡',
      svgIcon: 'lightning',
      content: "Photosynthesis happens in two main stages. Phase 1 is the **Light-Dependent Reactions**, which occur in the thylakoid membrane, only while the sun is shining.\n\nHere is the step-by-step:\n1️⃣ **Light hits chlorophyll**, exciting its electrons like a power boost.\n2️⃣ **Water is split** (H₂O) into oxygen, protons (H⁺), and electrons. The plant releases the O₂ so we can breathe!\n3️⃣ The energized electrons travel down an **electron transport chain**.\n4️⃣ This movement powers the creation of two energy-carrying molecules: **ATP** (cellular batteries) and **NADPH** (electron carriers).\n\nPhase 1's main goal: Store solar energy in temporary batteries! 🔋",
      highlight: "Sunlight is captured to make ATP and NADPH, and water is split to release Oxygen! ⚡",
    },
    {
      id: 'calvin_cycle',
      title: 'Phase 2: The Calvin Cycle 🔄',
      color: '#F43F5E',
      bgGradient: ['#2A0A10', '#0A0A0F'],
      icon: '🔄',
      svgIcon: 'cycle',
      content: "Phase 2 is the **Light-Independent Reactions** (or Calvin Cycle). Even if it's called 'light-independent,' it relies on the batteries charged in Phase 1, so it mostly happens during the day too. It takes place in the fluid **stroma**.\n\nNow the plant actually builds the sugar!\n1️⃣ The plant breathes in **CO₂** from the air.\n2️⃣ An important enzyme called **RuBisCO** grabs the CO₂.\n3️⃣ The plant uses the energy from the **ATP & NADPH** (made in phase 1) to force the carbon molecules together.\n4️⃣ After a few turns of the cycle, out pops **glucose**, a high-energy sugar! 🍬\n\nThis glucose can be used immediately for energy, stored as starch, or used to build plant tissue like wood (cellulose).",
      highlight: "The Calvin Cycle uses ATP and NADPH to turn CO₂ gas from the air into solid glucose sugar! 🔄",
    },
    {
      id: 'two_photosystems',
      title: 'The Two-Photon Boost 🚀',
      color: '#A855F7',
      bgGradient: ['#1E0A2A', '#0A0A0F'],
      icon: '🚀',
      svgIcon: 'rocket',
      content: "Here is a mind-blowing detail: one photon of light isn't strong enough on its own to charge the electrons for the Calvin cycle. \n\nSo, plants invented a clever trick: the **Z-Scheme**.\n\nThey use **two** separate light-harvesting clusters (Photosystem II and Photosystem I). \n🔹 First, *Photosystem II* absorbs a photon to split water and give the electron its first energy boost.\n🔹 The electron travels, losing some energy to make ATP.\n🔹 Then, it arrives at *Photosystem I*, where a **second photon** hits it, giving it another massive boost of energy so it can successfully form NADPH!\n\nIt takes a double-hit combo of light to make photosynthesis work! ☀️+☀️",
      highlight: "Electrons need two separate boosts of light energy (Photosystem II & I) to successfully power the dark reactions! 🚀",
    },
    {
      id: 'rubisco_flaw',
      title: 'RuBisCO: The Clumsy Enzyme 🤪',
      color: '#FF9F1C',
      bgGradient: ['#2A1A0A', '#0A0A0F'],
      icon: '🤪',
      svgIcon: 'flask',
      content: "**RuBisCO** is the enzyme responsible for grabbing CO₂ from the air. It is arguably the most important protein on Earth, and also the most abundant. \n\nBut there is a catch: **it's incredibly clumsy!** \n\nAbout 20% of the time, RuBisCO accidentally grabs **Oxygen** instead of CO₂. When this happens, photosynthesis runs *backwards* in a wasteful process called **photorespiration**.\nThe plant burns up energy and accidentally releases CO₂ back into the air. This mistake costs plants up to 50% of their energy!\n\nWhy is the most important enzyme so bad at its job? Because when RuBisCO evolved billions of years ago, there was almost zero oxygen in the atmosphere! 🌋",
      highlight: "RuBisCO accidentally grabs Oxygen instead of CO₂, causing the plant to waste massive amounts of energy! 🤪",
    },
    {
      id: 'environmental_factors',
      title: 'Limits to Growth: Light, Temp, CO₂ 🌡️',
      color: '#8B5CF6',
      bgGradient: ['#150A2A', '#0A0A0F'],
      icon: '🌡️',
      svgIcon: 'thermometer',
      content: "Photosynthesis is a delicate chemical dance that depends entirely on its environment. Changing just one factor changes the entire outcome:\n\n🌤️ **Light Intensity:** More light means more energy, but only up to a point! Once all chloroplasts are working at max speed, adding more light won't help. This is called the 'Saturation Point'.\n\n💨 **CO₂ Levels:** If CO₂ runs low, the Calvin cycle starves and everything stops, even in bright sunlight.\n\n🌡️ **Temperature:** Photosynthesis relies on enzymes, which have a Goldilocks zone (~25°C - 35°C). If it gets too cold, they slow down. **If it gets too hot (>40°C), the enzymes melt (denature) and totally break down**, stopping photosynthesis completely! 🔥",
      highlight: "Photosynthesis can be entirely stopped if there isn't enough Light, not enough CO₂, or if Temperatures get too hot! 🌡️",
    },
    {
      id: 'c3_c4_cam',
      title: 'Desert Survivors: C4 and CAM 🌵',
      color: '#EC4899',
      bgGradient: ['#2A0A1A', '#0A0A0F'],
      icon: '🌵',
      svgIcon: 'sun',
      content: "Most plants (like trees and rice) use standard photosynthesis, called **C3**. But in hot, dry environments, keeping pores (stomata) open to breathe CO₂ causes them to lose too much water and die.\n\nTo survive, some plants evolved superpowers! 🦸‍♀️\n\n🌽 **C4 Plants** (like corn and sugarcane) physically separate the clumsy RuBisCO enzyme into special deep tissues away from oxygen to prevent wasteful photorespiration.\n\n🌵 **CAM Plants** (like cacti and pineapples) found a time-hack: they only open their pores **at night** to collect CO₂ when it's cool, store it as acid, and then run photosynthesis during the day with their pores tightly closed to save water! 🌙",
      highlight: "Cacti open their pores to breathe at night to avoid losing water during hot sunny days! 🌵",
    },
    {
      id: 'global_impact',
      title: 'The Great Oxidation Event 🌍',
      color: '#06B6D4',
      bgGradient: ['#0A2A2A', '#0A0A0F'],
      icon: '🌍',
      svgIcon: 'globe',
      content: "About 2.4 billion years ago, Earth had a toxic atmosphere with virtually no oxygen. Then, tiny ocean microbes called **cyanobacteria** invented photosynthesis.\n\nAs they rapidly reproduced, they started pumping toxic waste into the atmosphere: **Oxygen!** 😱\n\nThis caused the **Great Oxidation Event**. For the bacteria alive at the time, oxygen was a lethal poison, causing Earth's first mass extinction! But it transformed the planet. \n\nThe oxygen created the Ozone layer (protecting us from UV radiation) and paved the way for complex life forms—like animals and eventually humans—that *depend* on oxygen to survive. Without photosynthesis, we literally wouldn't exist! 🙌",
      highlight: "Photosynthesis invented Oxygen 2.4 billion years ago, forever changing our planet's atmosphere! 🌍",
    },
  ],

  // ── LAB DESCRIPTION ─────────────────────────
  lab: {
    title: "Molecular Leaf Lab 🔬🌿",
    description: "Control light, CO₂, and temperature to maximize glucose production! Don't let your chloroplast overheat! 🔥",
    hint: "Try switching the light to green wavelength and see how the leaf reacts! Then see what happens if you push the temperature above 45°C...",
    scientistModeHint: "In Scientist Mode 🧑‍🔬: discover the true power of manipulating light saturation points and photorespiration mechanics!",
  },

  // ── DO YOU KNOW WHY ─────────────────────────
  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why leaves turn red and yellow in autumn? 🍂",
      answer: "Leaves actually contain red/yellow pigments (carotenoids) all year round! But in summer, the massive amount of green chlorophyll covers them up. As winter approaches, the tree stops making chlorophyll and breaks it down to save energy. Once the green fades, the beautiful hidden yellows and reds are finally revealed! 🍁",
      emoji: '🍂',
    },
    {
      id: 'dyk2',
      question: "Do you know why talking to your plants actually helps them grow? 🗣️🪴",
      answer: "It's not because they like your voice! When you speak near a plant, you are exhaling warm, concentrated Carbon Dioxide (CO₂) right onto their leaves. Since plants need CO₂ for the Calvin cycle, you are basically breathing 'plant food' directly into their faces! 🌬️🌱",
      emoji: '🗣️',
    },
    {
      id: 'dyk3',
      question: "Do you know why we don't use green light bulbs in greenhouses? 💡",
      answer: "Because plants are basically 'green-blind'! Chlorophyll absorbs red and blue light to power photosynthesis but physically physically rejects green light, reflecting it back. If you shine only green light on a plant, it will starve to death because it cannot absorb the energy! 🚫🟢",
      emoji: '💡',
    },
    {
      id: 'dyk4',
      question: "Do you know why plants need so much water but only use 1% of it for food? 💧",
      answer: "Plants use less than 1% of the water they absorb for the actual photosynthesis reaction! The other 99% is evaporated through tiny pores in their leaves (transpiration). This evaporation acts like a giant biological air conditioner, pulling more water up from the roots and keeping the leaf cool under the blazing hot sun! 🧊",
      emoji: '💧',
    },
    {
      id: 'dyk5',
      question: "Do you know why the Amazon rainforest is called the 'Lungs of the Earth'? 🌳",
      answer: "It produces 20% of the world's oxygen! The billions of trees taking in CO₂ and releasing O₂ through photosynthesis continuously refresh our atmosphere. However, it also uses up almost all that oxygen itself at night for respiration, meaning the true net-oxygen producers of the world are tiny algae in the ocean! 🌊",
      emoji: '🌳',
    },
  ],

  // ── QUIZ ────────────────────────────────────
  quiz: [
    {
      id: 'q1',
      question: "What are the three main ingredients needed for photosynthesis? 🌱",
      options: ['Oxygen, Sugar, Water', 'Sunlight, CO₂, Water', 'Sunlight, Oxygen, Soil', 'Nitrogen, Water, CO₂'],
      answer: 1,
      explanation: "Plants act as solar-powered factories: they take in Sunlight (energy), Carbon Dioxide (CO2) from the air, and Water (H2O) from the roots! ☀️+🌬️+💧",
    },
    {
      id: 'q2',
      question: "Which organelle inside plant cells is responsible for photosynthesis? 🏭",
      options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Ribosome'],
      answer: 2,
      explanation: "Photosynthesis happens inside the Chloroplasts, which contain the green pigment chlorophyll. 🏭",
    },
    {
      id: 'q3',
      question: "Why do most plants appear green to the human eye? 🟢",
      options: ['They absorb all green light', 'They reflect green light', 'They produce green sugar', 'The sky gives them a green tint'],
      answer: 1,
      explanation: "Chlorophyll absorbs red and blue light to use for energy, but it reflects green light away! Since the green light bounces off the leaf and into our eyes, plants look green. 👁️🌿",
    },
    {
      id: 'q4',
      question: "What is the primary product of the Calvin cycle (Light-Independent Reactions)? 🍬",
      options: ['Oxygen', 'Water', 'Glucose (Sugar)', 'ATP'],
      answer: 2,
      explanation: "During the Calvin Cycle, the plant uses energy to bind Carbon Dioxide molecules together to construct Glucose (sugar)! 🍬",
    },
    {
      id: 'q5',
      question: "Where does the Oxygen that plants release come from? 🌬️",
      options: ['From splitting CO₂', 'From splitting Water (H₂O)', 'From Glucose', 'From sunlight'],
      answer: 1,
      explanation: "During the light-dependent reactions, plants split Water (H₂O) into electrons, hydrogen protons, and Oxygen (O2)! The O2 is then released as a 'waste' product that we breathe! 💧",
    },
    {
      id: 'q6',
      question: "What happens to the enzymes in photosynthesis if the temperature rises above 45°C? 🔥",
      options: ['They work twice as fast', 'They consume twice as much CO2', 'They denature and the process stops', 'They produce water instead of sugar'],
      answer: 2,
      explanation: "Enzymes like RuBisCO are delicate proteins. Above ~40-45°C, they literally melt (denature) and lose their shape, shutting down photosynthesis entirely! 🔥",
    },
    {
      id: 'q7',
      question: "What is 'photorespiration'? 🤪",
      options: ['When plants breathe at night', 'When RuBisCO accidentally grabs Oxygen instead of CO₂', 'When plants absorb extra light', 'The process of roots absorbing water'],
      answer: 1,
      explanation: "Because RuBisCO evolved in an environment with no oxygen, it is clumsy! About 20% of the time, it grabs Oxygen instead of CO2, causing the plant to burn energy wastefully in 'photorespiration'. 🤪",
    },
    {
      id: 'q8',
      question: "How do CAM plants (like cacti) survive in hot, dry environments? 🌵",
      options: ['They don\'t use photosynthesis', 'They only open their stomata (pores) at night', 'They reflect all sunlight', 'They have roots that create water from air'],
      answer: 1,
      explanation: "CAM plants hack the system by only opening their pores at night to breathe in CO2 when it's cool outside, preventing their moisture from evaporating in the blazing hot daytime sun! 🌙",
    },
    {
      id: 'q9',
      question: "In the Z-Scheme of the light reactions, how many photons of light are needed to fully charge an electron? 🚀",
      options: ['1', '2', '4', '10'],
      answer: 1,
      explanation: "It takes TWO photons! One hits Photosystem II to give the electron its first jump, and a second one hits Photosystem I later on to give it the final boost to make NADPH! ☀️+☀️",
    },
    {
      id: 'q10',
      question: "What are the two energy-carrying molecules produced in the Light Reactions that power the Calvin Cycle? 🔋",
      options: ['Glucose and Oxygen', 'DNA and RNA', 'ATP and NADPH', 'Dopamine and Serotonin'],
      answer: 2,
      explanation: "The Light Reactions use solar energy to charge up tiny molecular batteries called ATP and NADPH, which then travel to the stroma to power the Calvin Cycle's sugar-building machinery! 🔋⚡",
    },
  ],

  // ── RELATED TOPICS ──────────────────────────
  relatedTopics: ['cell_structure', 'ecosystems', 'energy_types', 'evolution_natural'],
};
