// ─────────────────────────────────────────────────────────
//  TOPIC: COGNITIVE BIASES - THE BRAIN'S SHORTCUTS
//  Category: Psychology / Logic
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'cognitive_biases',
  title: 'Cognitive Biases',
  subtitle: "Why your brain lies to you every day 🧠🎭",
  emoji: '🎭',
  category: 'Psychology',
  accentKey: 'logic',

  hook: {
    question: "Do you believe you're a better-than-average driver? 🚗",
    reveal: "Statistically, over 80% of people believe they are 'above average'—which is mathematically impossible! This is a **Cognitive Bias**. Your brain isn't a perfect logic machine; it's a survival machine that takes dangerous shortcuts to save energy. These 'shortcuts' often lead to systematic errors in judgment that affect everything from how you spend money to who you vote for. Let's unmask the glitches in your mind! 🔍",
    emoji: '🧠',
  },

  theory: [
    {
      id: 'anchoring_bias',
      title: 'Anchoring Bias ⚓',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '⚓',
      svgIcon: 'target',
      content: "The first piece of information you hear about a subject becomes an 'Anchor' that your brain uses to judge everything else that follows.\n\nImagine you see a shirt with a 'was $100' tag, now on sale for '$40'. Your brain anchors to the $100, making $40 look like a steal 👗. But if you had seen the same shirt for $40 with no reference, you might think it's expensive!\n\nNegotiators and marketers use this constantly. Once an anchor is set in your mind, it's incredibly hard to drift away from it, even if the number was completely random.",
      highlight: "The first number you hear 'anchors' your judgment, even if it's irrelevant! ⚓",
    },
    {
      id: 'confirmation_bias',
      title: 'Confirmation Bias 🕵️‍♂️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🕵️‍♂️',
      svgIcon: 'search',
      content: "This is the 'Grandmother' of all biases. Your brain actively seeks out information that agrees with what you *already* believe, and ignores everything that contradicts it.\n\nIf you believe a certain diet is healthy, you will notice every news story praising it and dismiss every study saying it's dangerous. In the age of social media algorithms, this bias creates 'Filter Bubbles' where we only ever see our own opinions reflected back at us 🫧.\n\nIt feels good to be 'right', but confirmation bias makes it almost impossible to learn new truths.",
      highlight: "We don't see things as they are; we see things as WE are. 🧘",
    },
    {
      id: 'dunning_kruger',
      title: 'Dunning-Kruger Effect 📉',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '📉',
      svgIcon: 'chart',
      content: "This bias explains why people who know very little about a subject often feel the most confident. \n\nWhen you first start learning something (like Chess or Coding), you don't yet know enough to see how much you *don't* know. This leads to a peak of 'Overconfidence' 🏔️.\n\nTrue experts, on the other hand, often suffer from the opposite: **Imposter Syndrome**. Because they know how complex the subject is, they assume everyone else must know as much as they do. The more you know, the less certain you become!",
      highlight: "The less someone knows, the more confident they tend to be! 🧗",
    },
    {
      id: 'availability_heuristic',
      title: 'Availability Heuristic 🦈',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🦈',
      svgIcon: 'zap',
      content: "Your brain judges how likely something is based on how easily you can remember an example of it.\n\nMany people are terrified of shark attacks or plane crashes, but aren't afraid of driving a car 🚗. Statistically, driving is thousands of times more dangerous! But shark attacks are dramatic and vivid in our memories because of movies and news. \n\nBecause the memory is 'Available' and easy to find, your brain mistakenly thinks it's a common danger. We ignore the silent, boring risks (like heart disease) in favor of the loud, rare ones.",
      highlight: "Loud, rare events feel more dangerous than quiet, common ones. 📣",
    },
    {
      id: 'sunk_cost_fallacy',
      title: 'Sunk Cost Fallacy 💸',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '💸',
      svgIcon: 'trash',
      content: "This is the tendency to continue an endeavor just because you've already invested time, money, or effort into it—even if it's currently failing.\n\nHave you ever finished a terrible movie just because you paid for the ticket? 🎟️ Or stayed in a bad relationship 'because of the history'? \n\nLogic says: the money/time is GONE regardless. You should choose what makes you happiest *now*. But our brains hate 'wasting' previous effort, so we throw good money after bad. Professional poker players learn to master this by folding losing hands early.",
      highlight: "Don't spend more time on a mistake just because you spent a lot of time making it. 🛑",
    },
    {
      id: 'halo_effect',
      title: 'The Halo Effect 😇',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '😇',
      svgIcon: 'sparkle',
      content: "If you think someone is physically attractive, your brain automatically assumes they are also kind, intelligent, and funny 🪄. This is the **Halo Effect**.\n\nOur brains take one positive trait and let it 'glow' over the person's entire character. This is why celebrities are often asked for their opinions on complex political or scientific issues—even if they have no expertise! \n\nThe opposite is the **Horn Effect**, where one negative trait (like being late once) makes us assume the person is generally lazy or incompetent.",
      highlight: "We let one visible trait blind us to a person's actual character. 🎭",
    },
    {
      id: 'self_serving_bias',
      title: 'Self-Serving Bias 🥳',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🥳',
      svgIcon: 'star',
      content: "This is the brain's defense mechanism for your ego. \n\nWhen you succeed, you give yourself 100% of the credit ('I'm a genius!'). But when you fail, you blame 'Bad Luck' or 'The System' ('The test was unfair!') 📉.\n\nWhile this keeps our self-esteem high, it prevents us from learning from our mistakes. To grow, you have to realize that your successes involve some luck, and your failures involve some personal error. Balancing this is the key to true mental maturity.",
      highlight: "Success is mine; failure is 'The Universe's fault.' 🛡️",
    },
    {
      id: 'hindsight_bias',
      title: 'Hindsight Bias 🕰️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🕰️',
      svgIcon: 'history',
      content: "Also known as the 'I-knew-it-all-along' effect. After an event happens, we convince ourselves that we predicted it exactly 🔮.\n\nBefore a big sports game, you might be unsure. But after your team loses, you yell, 'I knew they weren't ready!' \n\nThis happens because your brain immediately overwrites your old 'uncertain' memory with the new 'certain' outcome. Hindsight bias makes the world look more predictable than it really is, making us overconfident about predicting the *future*.",
      highlight: "Everything looks obvious once you already know the answer. 🧩",
    },
    {
      id: 'framing_effect',
      title: 'The Framing Effect 🖼️',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🖼️',
      svgIcon: 'grid',
      content: "How information is presented (framed) changes how we feel about it, even if the facts are identical.\n\n• Option A: 'This yogurt is 90% Fat-Free!' 😋\n• Option B: 'This yogurt contains 10% Fat.' 🤢\n\nMathematically, these are the exact same thing. But Option A feels like a healthy choice, while Option B feels greasy. \n\nPoliticians and advertisers are masters of framing. They don't lie to you; they just choose the 'frame' that triggers your emotions instead of your logic 🖼️.",
      highlight: "It's not just WHAT you say, but HOW you say it that controls the mind. 🗣️",
    },
    {
      id: 'survivorship_bias',
      title: 'Survivorship Bias 🛩️',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '🛩️',
      svgIcon: 'shield',
      content: "We tend to focus on the 'survivors' and ignore the 'failures' that we can't see. \n\nIn WWII, the military wanted to add armor to the parts of planes that had the most bullet holes. But mathematician Abraham Wald realized they should add armor to the places with NO holes—because the planes hit there were the ones that *didn't* make it back! 🛩️\n\nWe see famous college dropouts like Bill Gates and think dropping out makes you rich. We don't see the millions of dropouts who are struggling, because they aren't on the news. Don't let the visible 'winners' distort your view of reality.",
      highlight: "Don't judge the world only by the winners you can see. 🏟️",
    },
  ],

  lab: {
    title: "The Bias Trap Lab 🧪",
    description: "Step into the psychologist's office! Participate in rapid-fire interactive tests designed to trigger your internal biases. Experience 'Anchoring' in real-time and see if you can escape the 'Framing Effect' in our decision-making simulator! 🧠⚡",
    hint: "In the 'Anchor' game, watch how a random number shown at the start subtly influences your final estimate. Can you remain objective in 'Scientist Mode' by viewing raw data before the 'Vivid' description?",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks 'System 1 vs System 2' processing time metrics and statistical variance charts.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we have these biases if they make us wrong? 🦁",
      answer: "Survival! Our ancestors lived in a dangerous world where taking too long to think meant being eaten by a lion. A brain that says 'Stripes in grass = RUN' (even if it's just a shadow) is more likely to survive than a brain that waits for a 100% logical proof. Biases are the 'Heuristics' (mental rules of thumb) that kept us alive for millions of years! 🦴",
      emoji: '🍖',
    },
    {
      id: 'dyk2',
      question: "Do you know why the average person thinks they are 'smarter than average'? 🧠",
      answer: "The 'Illusory Superiority' bias! To survive as a social animal, high self-esteem is a massive advantage. Our brains 'protect' us by magnifying our strengths and downplaying our flaws. If we were 100% realistic about our abilities, we'd probably be too scared to ever try anything new! 🧗",
      emoji: '🏆',
    },
    {
      id: 'dyk3',
      question: "Do you know why you always feel like you're in the slowest line at the store? 🛒",
      answer: "The 'Negativity Bias'! You don't record a memory when the line moves fast because it's 'normal.' But when you're stuck, you feel frustrated and angry. Your brain flags those painful moments with heavy emotion, making them much easier to remember. You only remember the slow times, creating the illusion of a cosmic conspiracy! 🕰️",
      emoji: '🛒',
    },
    {
      id: 'dyk4',
      question: "Do you know why expensive medicine often works better than cheap medicine? 💊",
      answer: "The Placebo Effect meets the 'Price-Quality' bias! Because we associate 'Expensive' with 'Better', our brains actually release more reward chemicals and painkillers when we take a $50 pill compared to a $1 pill—even if the actual ingredients are identical! Your expectation of relief creates the relief. ✨",
      emoji: '🧪',
    },
    {
      id: 'dyk5',
      question: "Do you know why you find the 'Perfect' social media post just when you need it? 📱",
      answer: "Baader-Meinhof Phenomenon (Frequency Illusion). Once you learn something new, you start seeing it everywhere. Your brain isn't finding 'more' of it; it's just finally stopped *ignoring* it. Now that the data is 'relevant', your brain's filter lets it through every time! 🧠",
      emoji: '📡',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is a 'Cognitive Bias'?", options: ['A type of brain injury', 'A mental shortcut that can lead to errors in judgment', 'A logical proof', 'A photographic memory'], answer: 1, explanation: "Biases are the 'firmware' glitches in our mental operating system! 🎭" },
    { id: 'q2', question: "Which bias makes us seek out only information we already agree with?", options: ['Anchoring Bias', 'Confirmation Bias', 'The Halo Effect', 'Hindsight Bias'], answer: 1, explanation: "We love being right more than we love being true! 🕵️‍♂️" },
    { id: 'q3', question: "The 'Anchoring Bias' refers to our tendency to rely too heavily on:", options: ['The most recent info', 'The first piece of info we hear', 'Information from experts', 'Information that is scary'], answer: 1, explanation: "The first number or price 'anchors' our expectations for everything else! ⚓" },
    { id: 'q4', question: "Why do beginners often feel more confident than experts (Dunning-Kruger Effect)?", options: ['Experts are lazy', 'Beginners don\'t yet know enough to see their own incompetence', 'Beginners are naturally smarter', 'Experts forget things'], answer: 1, explanation: "Knowledge brings humility because it reveals how truly complex a subject is! 📉" },
    { id: 'q5', question: "Which bias makes us stay in a bad relationship or movie just because we've already spent time on it?", options: ['Halo Effect', 'Sunk Cost Fallacy', 'Self-Serving Bias', 'Framing Effect'], answer: 1, explanation: "Don't throw good time after bad! 💸" },
    { id: 'q6', question: "If you think a '90% fat-free' burger is better than a '10% fat' burger, you are falling for:", options: ['The Halo Effect', 'The Framing Effect', 'Confirmation Bias', 'Survivorship Bias'], answer: 1, explanation: "The 'Frame' changed your feeling, but the fact stayed the same! 🖼️" },
    { id: 'q7', question: "The tendency to judge the danger of a plane crash by how easily you can recall news about them is:", options: ['The Availability Heuristic', 'The Dunning-Kruger Effect', 'Negativity Bias', 'The Placebo Effect'], answer: 0, explanation: "Drama in memory makes rare things feel common! 🦈" },
    { id: 'q8', question: "What is the 'Halo Effect'?", options: ['Believing in angels', 'Assuming an attractive person is also kind and smart', 'Seeing light around people', 'Forgetting someone\'s name'], answer: 1, explanation: "We let one good quality 'blind' us to everything else! 😇" },
    { id: 'q9', question: "Attributing your success to hard work and your failure to 'bad luck' is:", options: ['The Halo Effect', 'The Self-Serving Bias', 'Hindsight Bias', 'Logical Reasoning'], answer: 1, explanation: "It protects the ego but prevents learning from mistakes! 🥳" },
    { id: 'q10', question: "Which bias makes you say 'I knew that would happen!' after a sports game ends?", options: ['The Future Fallacy', 'Hindsight Bias', 'Confirmation Bias', 'Anchoring'], answer: 1, explanation: "Everything is obvious once you have the answer! 🕰️" },
    { id: 'q11', question: "Survivorship Bias happens when we:", options: ['Focus only on winners and ignore the losers we can\'t see', 'Try too hard to survive', 'Ignore the news', 'Believe in ghosts'], answer: 0, explanation: "We judge reality by the 'survivors', forgetting the millions who failed! 🛩️" },
    { id: 'q12', question: "Why do humans have biases at all?", options: ['Our brains are broken', 'They are survival \'rules of thumb\' for quick decisions', 'We are born evil', 'They are a side effect of language'], answer: 1, explanation: "Quick decisions saved our ancestors from predators! 🦁" },
    { id: 'q13', question: "Negotiators starting with an absurdly high price are trying to trigger your:", options: ['Framing Effect', 'Anchoring Bias', 'Halo Effect', 'Sunk Cost Fallacy'], answer: 1, explanation: "They want to set a high anchor so their second price looks like a 'deal'. ⚓" },
    { id: 'q14', question: "The 'Horn Effect' is the opposite of the:", options: ['Confirmation Bias', 'Halo Effect', 'Dunning-Kruger Effect', 'Placebo Effect'], answer: 1, explanation: "One bad trait makes us assume everything about the person is bad. 👿" },
    { id: 'q15', question: "Why do 'Filter Bubbles' happen on the internet?", options: ['The internet is slow', 'Algorithms trigger our Confirmation Bias', 'Hackers change the news', 'The computers are biased'], answer: 1, explanation: "Computers show us what we like, which traps us in our own beliefs! 🕵️‍‍♂️" },
    { id: 'q16', question: "What is the 'System 1' part of the brain responsible for?", options: ['Slow, logical math', 'Fast, automatic, biased thinking', 'Dreams', 'The heartbeat'], answer: 1, explanation: "System 1 is the 'Fast' brain where most biases live. ⚡" },
    { id: 'q17', question: "When you start seeing a 'new' car everywhere after just learning about it, it is the:", options: ['Placebo Effect', 'Baader-Meinhof Phenomenon', 'Sunk Cost', 'Halo Effect'], answer: 1, explanation: "Your brain's filter just started letting that relevant info through! 📱" },
    { id: 'q18', question: "Which bias is most likely used to sell you 'Standard' vs 'Premium' gas?", options: ['Anchoring', 'Decoy Effect / Framing', 'Hindsight', 'None'], answer: 1, explanation: "The 'Standard' price makes 'Premium' look better by comparison! 🖼️" },
    { id: 'q19', question: "The 'Illusory Superiority' bias explains why 80% of people think they are:", options: ['Bad at driving', 'Above-average at almost everything', 'Invisible', 'Smarter than Einstein'], answer: 1, explanation: "We overestimate ourselves to maintain high self-esteem! 🏆" },
    { id: 'q20', question: "How can you beat cognitive biases?", options: ['By being smarter', 'By learning about them and sloooowing down your thinking', 'By ignoring everyone else', 'You can\'t'], answer: 1, explanation: "Awareness is half the battle. Use 'System 2' to double-check your gut! 🧠" },
  ],

  relatedTopics: ['memory_how_it_works', 'brain_structure', 'probability_stats'],
};
