// ─────────────────────────────────────────────────────────
//  TOPIC: MEMORY - HOW IT WORKS
//  Category: Psychology / Neuroscience
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'memory_how_it_works',
  title: 'How Memory Works',
  subtitle: 'The architecture of your mental library 🧠📖',
  emoji: '🧠',
  category: 'Psychology',
  accentKey: 'memory',

  hook: {
    question: "Why can you remember the lyrics to a song from 10 years ago, but can't remember where you put your keys 5 minutes ago? 🔑",
    reveal: "Because your brain treats those two memories completely differently! One is locked in 'Long-Term Storage' using physical protein changes in your neurons, while the other was just a temporary electrical pattern in your 'Working Memory' that vanished as soon as you got distracted. Discover the fascinating biological machinery that builds your past! 🏗️",
    emoji: '🎭',
  },

  theory: [
    {
      id: 'what_is_memory',
      title: 'What is Memory? 🎞️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🎞️',
      svgIcon: 'brain',
      content: "Memory is not a single 'thing' or a video recording. It is the brain's ability to encode, store, and retrieve information 🧠.\n\nBiologically, a memory is a specific pattern of neurons firing together. When you learn something new, the connections between those neurons (synapses) get physically stronger. This is called *Long-Term Potentiation* (LTP).\n\nThink of your brain like a massive forest. The first time you walk a path, it's hard to find. But the more you walk it, the clearer and wider the path becomes. Eventually, it's a paved highway! 🛣️",
      highlight: "Memory is the physical strengthening of connections between neurons! 🔗",
    },
    {
      id: 'sensory_memory',
      title: 'The Sensory Gate 🚪',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🚪',
      svgIcon: 'eye',
      content: "Every second, your senses (eyes, ears, skin) are bombarded with millions of bits of data. Your brain can't store it all, so it uses **Sensory Memory**.\n\n• **Iconic Memory:** A visual 'after-image' that lasts for about 0.5 seconds 👁️.\n• **Echoic Memory:** An auditory 'echo' that lasts for 3-4 seconds 👂.\n\nThis is why if someone asks 'Were you even listening?' you can sometimes repeat the last 3 words they said even if you weren't paying attention—your Echoic memory is still holding the echo!",
      highlight: "Sensory memory is the initial filter that decides what is worth noticing. 🔍",
    },
    {
      id: 'working_memory',
      title: 'Working Memory (Short-Term) ⚡',
      color: '#00E5FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '⚡',
      svgIcon: 'zap',
      content: "Information that passes the sensory gate enters **Working Memory**. This is your 'Mental Scratchpad' 📝.\n\nIt is incredibly limited. Most humans can only hold about **7 items** (± 2) in their working memory at once. If you try to remember a 10-digit phone number, your brain will likely 'drop' the middle digits unless you use hacks.\n\nWorking memory is highly volatile. If you get distracted for even a few seconds, the data is erased completely. This is why you walk into a room and forget why you went there—your working memory was hijacked by a new thought! 🛑",
      highlight: "Working memory has a 'Magic Number' of 7. It is the bottleneck of your consciousness. 🧴",
    },
    {
      id: 'long_term',
      title: 'Long-Term Storage 🗄️',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🗄️',
      svgIcon: 'grid',
      content: "If you pay enough attention or repeat information, it moves into **Long-Term Memory** (LTM). \n\nUnlike your scratchpad, LTM has a virtually infinite capacity. It's more like a giant library 🏛️. There are two main sections:\n\n1. **Explicit Memory:** Facts and events you consciously remember (Current President, your 10th birthday).\n2. **Implicit Memory:** Habits and skills you do without thinking (Riding a bike, typing on a keyboard) 🚲.\n\nMoving data from scratchpad to library is called *Consolidation*.",
      highlight: "Skills (Implicit) are stored in different brain areas than facts (Explicit)! 🔄",
    },
    {
      id: 'encoding',
      title: 'Encoding: Making it Stick 🛠️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🛠️',
      svgIcon: 'target',
      content: "Encoding is the process of turning a sensory experience into a biological memory trace.\n\nThere are three levels of encoding:\n• **Visual:** What it looks like (Weakest) 👁️\n• **Acoustic:** What it sounds like (Middle) 👂\n• **Semantic:** What it *means* (Strongest) 💡\n\nIf you want to remember a word, don't just look at it. Connect it to a story, a joke, or a feeling. This is called *Elaborative Rehearsal*. The more 'hooks' you give a memory, the harder it is for it to fall out of your head!",
      highlight: "Semantic encoding (giving data meaning) is the #1 secret to a better memory! 🧩",
    },
    {
      id: 'retrieval',
      title: 'Retrieval: Finding the File 🔍',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🔍',
      svgIcon: 'search',
      content: "Remembering is actually 'Retrieving' data from the library. Sometimes, the file is there, but you can't find the path to it. This is the **Tip-of-the-Tongue** phenomenon 👅.\n\nRetrieval works best using **Cues**. \nIf you study for a test while listening to jazz music, you will actually perform better on the test if jazz music is playing! This is called *Context-Dependent Memory*.\n\nYour brain also uses *State-Dependent Memory*. If you are happy when you learn something, you'll remember it better when you are happy again! 😊",
      highlight: "Memories aren't lost; usually, we just lost the 'search terms' to find them. 🔑",
    },
    {
      id: 'hippocampus',
      title: 'The Hippocampus: The Librarian 🏛️',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🏛️',
      svgIcon: 'sparkle',
      content: "The **Hippocampus** is a small, seahorse-shaped structure deep in your brain. It is the 'Librarian' of your memories 🧠.\n\nIts job isn't to *store* the books, but to index them and tell them where to go. While you sleep, the hippocampus 'replays' your day and ships memories off to the permanent storage in the Cortex. This is why sleep is CRITICAL for learning 😴.\n\nIf your hippocampus is damaged, you develop *Anterograde Amnesia*—you can remember your past, but you can never form a new memory again. You would be stuck in the present forever.",
      highlight: "The Hippocampus 'consolidates' memories while you sleep! 🌙",
    },
    {
      id: 'forgetting',
      title: 'Forgetting & Interference 🗑️',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🗑️',
      svgIcon: 'radiation',
      content: "Why do we forget? Usually, it's not because the data vanished, but because of **Interference**.\n\n• **Proactive Interference:** Old memories block new ones (Calling your new girlfriend by your ex's name) 😅.\n• **Retroactive Interference:** New memories block old ones (Learning a new phone number makes you forget your old one).\n\nHermann Ebbinghaus discovered the **Forgetting Curve**: you forget 50% of what you learn within 20 minutes unless you review it! This is why *Spaced Repetition* is so effective.",
      highlight: "If you don't review, 80% of new info is gone in 24 hours. 📉",
    },
    {
      id: 'mnemonics',
      title: 'Mnemonics & Memory Hacks 🛠️',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🛠️',
      svgIcon: 'book',
      content: "You can 'hack' your 7-item bottleneck using **Chunking**. Instead of remembering 1, 9, 4, 5 (4 items), remember the year 1945 (1 item)! 🧠\n\nOther power-tools:\n• **The Method of Loci:** Imagine walking through your house and placing items you need to remember in different rooms. Visualizing the location uses your powerful spatial brain 🏠.\n• **Acronyms:** Like **VIBGYOR** for the colors of the rainbow 🌈.\n• **The Baker/baker Effect:** People remember that a man's *profession* is a baker better than remembering his *last name* is Baker, because the profession has more hooks (smell, bread, oven)!",
      highlight: "Visual and spatial hacks are the most powerful because humans are visual animals. 👁️",
    },
    {
      id: 'false_memories',
      title: 'False Memories & Construction 🧩',
      color: '#888888',
      bgGradient: ['#111111', '#050D0A'],
      icon: '🧩',
      svgIcon: 'hash',
      content: "Here is the scariest part: your memories are NOT recordings. They are **Reconstructions**.\n\nEvery time you 'retrieve' a memory, you take it out of the library, look at it, and then put it back. But as you look at it, you might accidentally fold a page or add a new detail. This is called *Reconsolidation*.\n\nStudies by Elizabeth Loftus show that just by changing one word in a question (e.g., 'How fast was the car *smashing*' vs '*hitting*'), scientists can make people 'remember' broken glass that was never actually there! 🚗💥",
      highlight: "Your memory changes every single time you think about it! 🎭",
    },
  ],

  lab: {
    title: "Neural Memory Lab 🧪",
    description: "Experience the struggle of memory consolidation! Catch incoming sensory packets, 'chunk' them to save space in your Working Memory, and drag them to the Hippocampus to lock them in before 'Interference' distracts you ⚡",
    hint: "Try 'Chunking' mode in Scientist Mode to see how grouped data lasts longer! Watch out for the phone/notification icons—they represent distractions that wipe your Working Memory scratchpad.",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays 'Active Synapse Weight' and the decay rate of Echoic vs Iconic memory buffers.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why we can't remember being a baby (Infantile Amnesia)? 👶",
      answer: "It's because your Hippocampus—the 'Librarian'—isn't fully developed until age 3 or 4! Plus, as a baby, you didn't have language yet. Since we encode most adult memories using words (Semantic Encoding), your brain simply doesn't have the 'dictionary' required to translate those early baby feelings into permanent files! 📖",
      emoji: '🧸',
    },
    {
      id: 'dyk2',
      question: "Do you know why you walk into a room and instantly forget why? 🚪",
      answer: "This is known as the 'Doorway Effect'! Your brain uses doorframes as 'event boundaries.' When you walk through a door, your brain clears your Working Memory scratchpad to prepare for a totally new environment. It 'archives' the previous room's thoughts, but sometimes they get lost in the shuffle! 🏠",
      emoji: '🤔',
    },
    {
      id: 'dyk3',
      question: "Do you know why testing yourself is 10x better than re-reading? 📝",
      answer: "Re-reading is just 'Encoding' (Input). Testing is 'Retrieval' (Output). The biological path to *finding* a memory is what needs exercise, not just the path to *storing* it. Every time you struggle to remember a fact, you are physically widening the 'highway' to that neuron cluster! 🛣️",
      emoji: '💡',
    },
    {
      id: 'dyk4',
      question: "Do you know why weird and dirty jokes are easier to remember? 🔞",
      answer: "The Von Restorff Effect! Your brain is an efficiency machine that ignores the 'normal.' Anything that is shocking, funny, or weird triggers the Amygdala (emotion center). The Amygdala stands next to the Hippocampus and yells 'THIS IS IMPORTANT, SAVE IT!', making the memory stick much harder than a boring math formula. 🤡",
      emoji: '🔥',
    },
    {
      id: 'dyk5',
      question: "Do you know why 'Pulling an All-Nighter' to study is a terrible idea? 😴",
      answer: "Because memories are fragile 'drafts' when you first learn them. They only become permanent during Deep Sleep and REM sleep. If you don't sleep, the Hippocampus never gets to 'upload' the data to the Cortex. You might remember it for 2 hours, but it will be gone by the time the test starts! 🌙",
      emoji: '📉',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the physical process of strengthening connections between neurons to form a long-term memory?", options: ["Process of synaptic pruning", "Long-term potentiation process", "Process of cell division", "Metabolic processing of cells"], answer: 1, explanation: "LTP is the 'paving of the highway' between neurons, making the signal fire easier next time! 🔗" },
    { id: 'q2', question: "Which type of memory holds a visual 'after-image' for only half a second?", options: ["Working memory storage", "Echoic memory storage", "Iconic memory storage", "Implicit memory storage"], answer: 2, explanation: "Iconic memory is the split-second visual buffer of your eyes! 👁️" },
    { id: 'q3', question: "How many items can the average human hold in their Working Memory scratchpad at once?", options: ["Around three items", "Seven plus or minus two", "Exactly twelve items", "Unlimited storage capacity"], answer: 1, explanation: "Known as Miller's Law, the magic number is 7! This is the bottleneck of human thought. 🧴" },
    { id: 'q4', question: "Why is semantic encoding (giving info meaning) more effective than just looking at a word?", options: ["Uses more electrical energy", "Creates more neural connections", "Processes information faster", "Occurs within the eyes"], answer: 1, explanation: "The more you connect a new fact to things you already know, the more 'search terms' you have to find it later! 🧩" },
    { id: 'q5', question: "Which brain structure acts as the 'Librarian', indexing and consolidating memories during sleep?", options: ["The Cerebellum structure", "The Amygdala structure", "The Hippocampus structure", "The Frontal Lobe structure"], answer: 2, explanation: "The Hippocampus (seahorse) is the master of new memory formation and consolidation. 🏛️" },
    { id: 'q6', question: "What happens if a person has 'Anterograde Amnesia'?", options: ["Forgetting childhood events", "Losing the ability to speak", "Inability to form new memories", "Forgetting physical skills"], answer: 2, explanation: "Like the movie Memento, they are stuck in a 5-minute loop of the present because they can't 'save' new data. 🔄" },
    { id: 'q7', question: "Which memory type stores skills like riding a bike or swimming that you do without conscious thought?", options: ["Explicit memory type", "Implicit procedural memory", "Semantic memory type", "Sensory memory type"], answer: 1, explanation: "Implicit memory is 'muscle memory' stored largely in the cerebellum! 🚲" },
    { id: 'q8', question: "The 'Tip-of-the-Tongue' phenomenon is an example of a failure in:", options: ["Failure of encoding", "Failure of storage", "Failure of retrieval", "Failure of sleep"], answer: 2, explanation: "The data is in your head (stored), but you've lost the path to 'access' or retrieve it! 🔍" },
    { id: 'q9', question: "What is 'Chunking'?", options: ["Deleting old memories", "Grouping info into units", "Repeating information aloud", "Sleeping after studying"], answer: 1, explanation: "Chunking '1, 7, 7, 6' into '1776' turns 4 units into 1, effectively doubling your memory capacity! 🧠" },
    { id: 'q10', question: "Why does the 'Doorway Effect' make you forget why you walked into a kitchen?", options: ["Magnetic pull of doorways", "Brain clears working memory", "Dehydration affecting focus", "Light changes affecting recall"], answer: 1, explanation: "Your brain 'clears the slate' for a new environment when you cross a threshold. 🏠" },
    { id: 'q11', question: "According to the Forgetting Curve, how much new information is lost within 24 hours if not reviewed?", options: ["About ten percent", "Exactly fifty percent", "Up to eighty percent", "Exactly zero percent"], answer: 2, explanation: "Without review, the 'path' in the forest grows over incredibly quickly! 📉" },
    { id: 'q12', question: "What is 'Proactive Interference'?", options: ["New info blocks old", "Old info blocks new", "Forgetting due to trauma", "Enhanced memory from caffeine"], answer: 1, explanation: "Pro-active (forward) interference means your 'past' is messing with your 'present'. 😅" },
    { id: 'q13', question: "Every time you recall a memory, it is temporarily 'unlocked' and can be changed. This is called:", options: ["Process of serialization", "Process of reconsolidation", "Process of encryption", "Process of pruning"], answer: 1, explanation: "Memories are not static; they are live files that get re-saved with new edits every time you think of them! 🎭" },
    { id: 'q14', question: "Which level of encoding is generally the WEAKEST?", options: ["Encoding semantic meaning", "Encoding acoustic sound", "Encoding visual appearance", "Encoding emotional connection"], answer: 2, explanation: "Just looking at the shape of letters is 'shallow' processing and rarely lasts. 👁️" },
    { id: 'q15', question: "Why is sleep so important for students after a day of learning?", options: ["Clearing out toxins", "Consolidating memories to cortex", "Resetting the eyes", "Preventing physical hunger"], answer: 1, explanation: "Sleep is when the 'Librarian' moves books from the temporary cart to the permanent shelves. 🌙" },
    { id: 'q16', question: "What 'hack' involves imagining a physical house and placing items you need to remember in rooms?", options: ["The Punnett Square", "The Method of Loci", "The Baker Effect", "The Flashcard Method"], answer: 1, explanation: "Humans have evolved incredible spatial memory for finding food/shelter—the Memory Palace borrows this power! 🏠" },
    { id: 'q17', question: "Explicit memory contains which two sub-types?", options: ["Implicit and Explicit", "Sensory and Echoic", "Semantic and Episodic", "Working and Permanent"], answer: 2, explanation: "Explicit memory is everything you can 'declare' or say out loud. 🗣️" },
    { id: 'q18', question: "What describes the finding that we remember items at the BEGINNING and END of a list better than the middle?", options: ["The Middle-Bias effect", "Serial Position Effect", "The Ebbinghaus Rule", "The Chunking Factor"], answer: 1, explanation: "Primacy (start) and Recency (end) effects make the middle of a list a 'dead zone' for memory. 📏" },
    { id: 'q19', question: "Which structure attaches 'emotions' to memories, making scary or funny things stick better?", options: ["The Thalamus structure", "The Amygdala structure", "The Cerebellum structure", "The Retina structure"], answer: 1, explanation: "The Amygdala flags emotional events as 'Priority', forcing the brain to save them in more detail. 🔥" },
    { id: 'q20', question: "Why should you study in a quiet environment if you know the exam will be in a quiet room?", options: ["Proactive Interference effect", "State-Dependent Memory effect", "Context-Dependent Memory effect", "Semantic Encoding effect"], answer: 2, explanation: "Your brain uses environmental cues (silence, smells, sounds) as 'anchors' to help find the memory later! 🤫" },
  ],

  relatedTopics: ['brain_structure', 'cognitive_biases', 'nervous_system'],
};
