// ─────────────────────────────────────────────────────────
//  TOPIC: CLIMATE SCIENCE
//  Category: Earth / Biology
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'climate_change',
  title: 'Climate Science',
  subtitle: 'The physics of the Earth system and global tipping points 🌍🌡️',
  emoji: '🌍',
  category: 'Biology',
  accentKey: 'nature',

  hook: {
    question: "How can throwing an invisible, odorless gas into the sky literally melt a continent of ice 5,000 miles away? 🧊",
    reveal: "It all comes down to the physics of light and heat. Our atmosphere is a miraculous, delicate blanket. Certain gases act as 'one-way mirrors.' They let the sun's explosive light in, but completely trap the Earth's escaping heat. By burning 300 million years of fossilized sunlight in a single century, humanity has accidentally wrapped the Earth in an extra thermal blanket. The ice is melting, and the clock is ticking. Let's look at the science! ⏱️🌡️",
    emoji: '🔥',
  },

  theory: [
    {
      id: 'weather_vs_climate',
      title: 'Weather vs. Climate 🌦️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🌦️',
      svgIcon: 'cloud',
      content: "Many people say: 'It's snowing outside! Global warming is fake!' \n\nThis fundamentally confuses Weather with Climate. \n• **Weather:** Your current mood (Happy today, sad tomorrow). The short-term state of the atmosphere in one specific place. ☔\n• **Climate:** Your overall personality (Generally a happy person). The long-term average of weather patterns over 30+ years across the entire globe. 🌍\nA cold winter in New York does not negate a massive mathematical rise in the overall temperature of the entire planet. 📈",
      highlight: "Weather tells you what to wear today. Climate tells you what closet to buy. 🧥",
    },
    {
      id: 'the_greenhouse_effect',
      title: 'The Greenhouse Effect 🪟',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🪟',
      svgIcon: 'target',
      content: "The Earth owes its life to the **Greenhouse Effect**. Without it, we would be a frozen, dead ice-ball (-18°C) like Mars! \n\nHere is how it works: The Sun shoots high-energy shortwave radiation (Light) at us. It easily passes through the air and hits the dirt. The dirt absorbs it and re-emits it as low-energy longwave radiation (Heat). \nBUT! Certain gases in the sky (like CO2) are completely opaque to 'Heat'. The heat tries to escape into space, hits the CO2, and bounces BACK to the dirt! 🪃",
      highlight: "The atmosphere is literally a giant, invisible greenhouse made of gas. 🍅",
    },
    {
      id: 'greenhouse_gases',
      title: 'The Usual Suspects (GHGs) 💨',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '💨',
      svgIcon: 'shield',
      content: "What makes a **Greenhouse Gas (GHG)**? It has to be a complex, wiggly molecule. \n\nOxygen (O2) and Nitrogen (N2) make up 99% of the air. They have only 2 atoms. They are tight and rigid—heat passes right through them! \nBut CO2, Methane (CH4), and Water Vapor (H2O) have 3+ atoms. When heat hits them, they physically wiggle, vibrate, and absorb the photon! Methane is actually 25x stronger at trapping heat than CO2, but CO2 stays in the air for thousands of years. ⏳",
      highlight: "It takes 3 atoms to tango with heat. 💃",
    },
    {
      id: 'carbon_cycle',
      title: 'The Carbon Cycle & Fossil Fuels 🦖',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🦖',
      svgIcon: 'refresh',
      content: "Carbon naturally moves between the sky, the oceans, and the trees in a brilliant, balanced circle called the **Carbon Cycle**. \n\nBut millions of years ago, dead plants and dinosaurs got buried deep underground, trapping their carbon. Over millions of years of pressure, they turned into Coal and Oil. \nWhen we dig that ancient oil up and burn it in our cars, we are ripping 'locked' carbon out of the ground and injecting it into the delicate, modern sky. We broke the balance! ⚖️",
      highlight: "Fossil fuels are just ancient, buried sunlight. ☀️",
    },
    {
      id: 'the_keeling_curve',
      title: 'The Keeling Curve 📈',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '📈',
      svgIcon: 'chart',
      content: "For 800,000 years, CO2 levels in the atmosphere never went above 300 parts per million (ppm). We know this from drilling ancient ice cores in Antarctica. \n\nThen, the Industrial Revolution happened. Scientist Charles Keeling started measuring CO2 in Hawaii in 1958. His graph, the **Keeling Curve**, is the most terrifying chart in human history. It shows an explosive, vertical spike up to 420+ ppm! \nWe have pushed the atmosphere into a chemical state that human beings have *never* existed in. 🧪",
      highlight: "The numbers don't lie. We are running a massive, uncontrolled chemistry experiment on the only planet we have. 🔬",
    },
    {
      id: 'albedo_effect',
      title: 'The Albedo Effect (Tipping Point 1) 🧊',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🧊',
      svgIcon: 'waves',
      content: "**Albedo** is the measure of how 'reflective' a surface is. \n\nWhite ice is like a mirror—it reflects 90% of the sun's heat back into space safely. Dark blue ocean water is like a black shirt—it absorbs 90% of the heat! \nBecause the Earth is warming, the Arctic ice is melting. That leaves dark ocean behind. The dark ocean absorbs more heat, which melts MORE ice! This is a **Positive Feedback Loop**. Once all the ice is gone, the warming violently accelerates. 🚤",
      highlight: "Melting the world's mirror triggers a catastrophic acceleration in heating. 🪞",
    },
    {
      id: 'ocean_acidification',
      title: 'Ocean Acidification (The Evil Twin) 🌊',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🌊',
      svgIcon: 'alert',
      content: "Global warming has an evil twin: **Ocean Acidification**. \n\nThe ocean acts as a sponge, soaking up 30% of the CO2 we pump into the sky. But when CO2 mixes with H2O, it literally turns into Carbonic Acid! \nSince the Industrial Revolution, the oceans have become 30% more acidic. This acid physically dissolves the calcium shells of oysters, crabs, and the coral reefs. If the coral reefs die, the entire marine food chain collapses! 🐠",
      highlight: "We are slowly turning the ocean into a giant bath of weak acid. 🧪",
    },
    {
      id: 'sea_level_rise',
      title: 'Sea Level Rise 🌊',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🌊',
      svgIcon: 'shield',
      content: "Why are sea levels rising? Two reasons:\n1. **Melting Land Ice:** Glaciers in Greenland and Antarctica holding trillions of tons of frozen freshwater are melting, dumping perfectly good water into the salty ocean. 🏔️\n2. **Thermal Expansion:** Physics 101 states that when water gets warmer, the molecules vibrate faster and physically expand! \nEven a 1-meter rise will flood Miami, Mumbai, and entire Pacific island nations, creating hundreds of millions of 'Climate Refugees'. 🏃‍♂️",
      highlight: "When the ice melts, the map of the world has to be redrawn. 🗺️",
    },
    {
      id: 'permafrost_methane',
      title: 'Permafrost (Tipping Point 2) 🥶',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🥶',
      svgIcon: 'lock',
      content: "In Siberia and Alaska, the ground is permanently frozen (**Permafrost**). Trapped inside this frozen dirt are billions of tons of dead, frozen plants. \n\nAs the Arctic warms, the permafrost thaws. The dead plants begin to rot, releasing massive amounts of **Methane (CH4)** into the sky. Because Methane is 25x stronger than CO2, this triggers *another* feedback loop! If the permafrost fully melts, it will release more greenhouse gases than all of human history combined! 🧨",
      highlight: "A ticking time bomb buried under the ice. 💣",
    },
    {
      id: 'extreme_weather',
      title: 'Extreme Weather Steroids 🌪️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🌪️',
      svgIcon: 'zap',
      content: "Climate change doesn't usually 'create' the hurricane. It puts the hurricane on **Steroids**. \n\nA warmer atmosphere can hold exponentially MORE water vapor. This means when it rains, it drops apocalyptic, biblical floods. Conversely, a hotter atmosphere acts as a giant hairdryer, sucking moisture out of the dirt, causing devastating wildfires (like Australia and California). \nWe are weaponizing the weather system! ⛈️",
      highlight: "It's not just warming. It's 'Global Weirding'—violent, unpredictable extremes. 🎭",
    },
    {
      id: 'the_sixth_extinction',
      title: 'The Sixth Mass Extinction 💀',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '💀',
      svgIcon: 'star',
      content: "Earth has had 5 mass extinctions (like the asteroid that killed the dinosaurs). \n\nScientists warn we have triggered the **Sixth Mass Extinction**. Animals and plants cannot evolve fast enough to survive a temperature change that happens in 100 years instead of 100,000 years! \nA million species are currently at risk of total annihilation. As ecosystems collapse like Jenga towers, the human food supply will be threatened. 🐝",
      highlight: "We are the asteroid. ☄️",
    },
    {
      id: 'renewable_energy',
      title: 'The Cure: Renewables ☀️',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '☀️',
      svgIcon: 'battery',
      content: "How do we stop it? We have to stop burning dead things! \n\nWe must switch instantly to **Renewable Energy**: Solar, Wind, Hydro, and Nuclear power. \nIn the last decade, the cost of solar panels has plummeted by 90%! It is now mathematically *cheaper* to build a new solar farm than to keep an old coal plant running. The technology exists to save the world; the only thing missing is the political courage to execute it. ⚡",
      highlight: "The stone age didn't end because we ran out of stones. We found something better! 💡",
    },
    {
      id: 'paris_agreement',
      title: 'The Paris Agreement (1.5°C) 🤝',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🤝',
      svgIcon: 'users',
      content: "In 2015, 196 countries signed the **Paris Agreement**. \n\nThe central goal: We MUST prevent the global average temperature from rising more than **1.5°C (2.7°F)** above pre-industrial levels. \nIf we cross 1.5°C, scientists warn we cross the 'Tipping Points' (Permafrost melting, Amazon rainforest dying). Once we cross a tipping point, the Earth takes over the warming, and humanity loses the ability to stop it! 🛑",
      highlight: "1.5 degrees isn't a goal line; it's a cliff edge. 🧗‍♂️",
    },
    {
      id: 'carbon_footprint',
      title: 'Individual vs Systemic Change 👣',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '👣',
      svgIcon: 'book',
      content: "The concept of a 'Personal Carbon Footprint' was actually invented by the oil company BP in 2004! \n\nWhy? To shift the blame onto YOU! While recycling and eating less meat is wonderful, individual actions CANNOT solve this crisis. 100 giant corporations are responsible for 71% of all global emissions! \nThe only way to win is through systemic legislation: Carbon taxes, banning coal, and massive government investment in green grids. 🏛️",
      highlight: "Don't just change your lightbulbs. Change your politicians! 🗳️",
    },
    {
      id: 'solar_radiation_management',
      title: 'Geoengineering (Plan B) 🪞',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🪞',
      svgIcon: 'cloud',
      content: "If we fail to stop burning oil, scientists are terrified we will have to use **Geoengineering**. \n\nThis involves using airplanes to spray millions of tons of sulfur particles into the high stratosphere. These particles act as tiny mirrors, blocking 1% of the sun's light from hitting the Earth, rapidly cooling the planet. \nThe horrifying catch? It could permanently ruin global rainfall patterns, causing famines. It is literally playing God with the sky! ⚡",
      highlight: "Geoengineering isn't a cure. It's a terrifying emergency surgery. 🔪",
    },
  ],

  lab: {
    title: "Global Thermostat 🌡️🧊",
    description: "Welcome to the Climate Physics Simulator! You control the composition of the atmosphere. Incoming Yellow Photons from the sun bounce off the Earth and turn into Red Infrared (Heat) Photons. Adjust the 'CO2 Concentration' slider and watch how the gas blocks the heat from escaping into the abyss! Watch the global temperature rise and the brilliant white 'Albedo Ice' melt away into dark oceans! Can you prevent thermal runaway? 🎛️",
    hint: "As you crank up the CO2, the heat particles literally get trapped in the atmosphere, desperately bouncing back and forth. The temperature gauge will spike. Try to maintain a delicate balance where heat escapes exactly as fast as sunlight enters!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Radiative Forcing variables (W/m²), Planck feedback parameters, and real-time parts-per-million (ppm) tracking.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why a parked car gets so hot in the sun? 🚗",
      answer: "A car is a literal miniature version of the Greenhouse Effect! The glass windows are exactly like CO2. They allow high-energy sunlight to pass right through and hit the black leather seats. The seats absorb it and emit invisible 'infrared heat'. But glass is completely opaque to infrared heat! The heat is trapped, bouncing around the cabin, baking you alive! 🔥",
      emoji: '🥵',
    },
    {
      id: 'dyk2',
      question: "Do you know why the planet Venus is 864°F (hot enough to melt lead), even though Mercury is much closer to the sun? 🪐",
      answer: "The ultimate runaway Greenhouse Effect! Venus has a ridiculously thick atmosphere made of 96% Carbon Dioxide. This traps absolute 100% of the heat it receives. It is the terrifying warning system of our solar system: If you dump enough CO2 into the sky, you boil the oceans and turn the planet into a literal oven oven! 🛸",
      emoji: '🔥',
    },
    {
      id: 'dyk3',
      question: "Do you know why eating beef is terrible for the climate? 🐄",
      answer: "Cow Burps! Cows are ruminants. When they digest grass in their massive stomachs, bacteria ferments the food and produces vast amounts of Methane gas (CH4), which the cow burps out into the sky. Because there are 1.5 billion cows being raised for meat globally, their burps account for over 10% of total global greenhouse gas emissions! 🍔",
      emoji: '🥩',
    },
    {
      id: 'dyk4',
      question: "Do you know why melting sea-ice (like around the North Pole) does NOT directly raise sea levels? 🧊",
      answer: "Physics (Archimedes' principle)! Fill a glass of water with ice cubes right to the brim. When the ice melts, the water doesn't overflow! The ice was already displacing its own exact weight in water. Sea-ice melting is bad because of the Albedo effect (losing the mirror). It is melting LAND-ICE (like Greenland) that actively adds *new* water to the ocean and ruins Miami! 🌊",
      emoji: '⚓',
    },
    {
      id: 'dyk5',
      question: "Do you know why scientists drill massive tubes of ancient ice out of Antarctica? 🔬",
      answer: "They are reading the ultimate history book! As snow falls over millions of years, it traps teeny tiny bubbles of the atmosphere. When scientists pull up a 3-mile long ice core, they can literally crush the ice, release the tiny bubbles, and measure EXACTLY how much CO2 was in the sky 800,000 years ago! The ice has a flawless memory! ❄️",
      emoji: '📜',
    },
    {
      id: 'dyk6',
      question: "Do you know why 'Ocean Acidification' causes oysters and corals to simply dissolve? 🦪",
      answer: "Chemistry! Oysters and corals build their hard shells by pulling Calcium Carbonate out of the seawater. But when the ocean absorbs human CO2, it creates Carbonic Acid. This acid aggressively eats free carbonate ions, meaning the oysters literally don't have the bricks to build their houses. Worse, if it gets too acidic, their existing shells dissolve right off their bodies while they are still alive! ☠️",
      emoji: '🌊',
    },
    {
      id: 'dyk7',
      question: "Do you know why planting trees is amazing, but won't save us entirely? 🌳",
      answer: "It's a math problem! A mature tree only absorbs about 48 pounds of CO2 a year. Humanity emits about 40 BILLION tons of CO2 a year! We would have to plant a new forest the size of the entire United States every single year just to break even. We *must* plant trees, but we cannot avoid shutting off the fossil fuel pipe at the source! 📉",
      emoji: '🧮',
    },
    {
      id: 'dyk8',
      question: "Do you know why the military views Climate Change as the ultimate 'Threat Multiplier'? 🪖",
      answer: "Wars aren't fought over weather; they are fought over bread and water. Severe droughts destroy crops. Starving farmers flee to overcrowded cities, causing massive riots and civil wars (this was the root trigger of the horrific Syrian Civil War). When millions of climate refugees crash borders looking for food, the military goes onto full alert! 🚨",
      emoji: '🛡️',
    },
    {
      id: 'dyk9',
      question: "Do you know why an oil company (Exxon) secretly knew about climate change in the 1970s? 🛢️",
      answer: "Their own brilliant scientists predicted it! Exxon's supercomputers in 1977 accurately modeled exactly how much CO2 would heat the planet by 2020. They knew the truth, but they buried the data! Instead of switching to solar, they spent millions of dollars funding fake think-tanks to successfully confuse the public for 40 years just to protect their profits! 🤫",
      emoji: '📜',
    },
    {
      id: 'dyk10',
      question: "Do you know why painting the roofs of houses white is actually a brilliant climate policy? 🏠",
      answer: "Micro-Albedo! A black asphalt roof absorbs the sun's heat, turning cities into massive 'Urban Heat Islands'. People then run energy-guzzling Air Conditioners to survive! By simply painting the roof white, it reflects the sun's radiation right back into deep space before it can turn into trapped heat. It saves electricity and cools the entire neighborhood! 🖌️",
      emoji: '🪞',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the difference between Weather and Climate?", options: ['None', 'Weather is short-term (mood), Climate is the 30-year global average (personality)', 'Weather is hot, Climate is cold', 'Climate is local only'], answer: 1, explanation: "A snowstorm in Texas does not cancel out the math of global warming! 📈" },
    { id: 'q2', question: "How does the 'Greenhouse Effect' work?", options: ['Glass falls from the sky', 'Gases let shortwave sunlight in, but block/absorb the longwave heat trying to escape back into space', 'The sun gets closer to Earth', 'Plants generate heat'], answer: 1, explanation: "We are throwing an invisible thermal blanket over the planet! 🪟" },
    { id: 'q3', question: "Why are CO2 and Methane greenhouse gases, but Oxygen (O2) is not?", options: ['They smell bad', 'They are complex molecules (3+ atoms) that wiggle and physically absorb heat radiation. O2 is too tight to trap it.', 'They are heavy', 'They are liquid'], answer: 1, explanation: "It takes 3 atoms to tango with a heat photon! 💃" },
    { id: 'q4', question: "What is a Fossil Fuel (Coal/Oil) fundamentally?", options: ['Dinosaur bones', 'Ancient, prehistoric sunlight trapped inside buried plants/organisms for millions of years', 'Magic dirt', 'Burned wood'], answer: 1, explanation: "We are digging up carbon that the earth safely buried millions of years ago, and throwing it into the sky! 🦖" },
    { id: 'q5', question: "What does the terrifying 'Keeling Curve' prove?", options: ['Math is hard', 'Through ice cores, we see CO2 spiked vertically from a natural 300 ppm to an unnatural 420+ ppm right as the Industrial Revolution began', 'Ice is cold', 'Hawaii is hot'], answer: 1, explanation: "The numbers do not lie. We did this. 📈" },
    { id: 'q6', question: "What is the 'Albedo Effect' feedback loop?", options: ['A music theory', 'White ice reflects heat into space. As we melt the ice, the dark ocean gets revealed, which absorbs more heat, melting EVEN MORE ice!', 'A type of cloud', 'Snow falling'], answer: 1, explanation: "Melting the mirror accelerates the burning! 🧊" },
    { id: 'q7', question: "Global warming's evil twin, 'Ocean Acidification', is caused by:", options: ['Fish dying', 'The ocean absorbing human CO2, which creates Carbonic Acid and physically dissolves the shells of oysters and coral reefs', 'Plastic straws', 'Ships leaking oil'], answer: 1, explanation: "We are turning the oceans into a giant, weak acid bath! 🌊" },
    { id: 'q8', question: "Which of the following causes the most catastrophic Sea-Level Rise?", options: ['Melting sea-ice cubes', 'The melting of massive LAND-ICE (like Greenland) and Thermal Expansion (warm water vibrates and physically expands)', 'Rainfall', 'High tides'], answer: 1, explanation: "An overflowing bathtub of physics! 🌊" },
    { id: 'q9', question: "What terrifying 'Ticking Time Bomb' lurks in the melting Siberian Permafrost?", options: ['Zombies', 'Billions of tons of dead, frozen plants that will rot and release massive amounts of highly potent Methane (CH4) gas', 'Frozen dinosaurs', 'Hidden gold'], answer: 1, explanation: "A horrific feedback loop that could wipe out humanity! 🥶" },
    { id: 'q10', question: "How does Climate Change put Extreme Weather like hurricanes on 'Steroids'?", options: ['It pays them money', 'A warmer atmosphere holds exponentially more water vapor, leading to massive floods when it rains', 'It changes the wind', 'It makes lightning stronger'], answer: 1, explanation: "Global Warming is actually 'Global Weirding'—violent, unpredictable extremes! 🌪️" },
    { id: 'q11', question: "Why are scientists warning about the 'Sixth Mass Extinction'?", options: ['A giant asteroid is coming', 'The planet is heating so rapidly (100 years instead of 100,000) that plants and animals literally cannot evolve fast enough to survive', 'Aliens', 'Too many humans'], answer: 1, explanation: "We have become the asteroid destroying the ecosystems! ☄️" },
    { id: 'q12', question: "The central goal of the Paris Agreement is to mathematically prevent the giant planetary temperature from rising more than _______ above pre-industrial levels.", options: ['5 degrees', '1.5°C (2.7°F)', '10 degrees', '0 degrees'], answer: 1, explanation: "1.5 degrees isn't a goal line; it is a cliff edge. 🧗‍♂️" },
    { id: 'q13', question: "The concept of a 'Personal Carbon Footprint' was heavily advertised by oil companies because:", options: ['They care about animals', 'They wanted to manipulate the public into blaming themselves, distracting from the fact that 100 giant corporations cause 71% of all emissions', 'They love math', 'They wanted smaller shoes'], answer: 1, explanation: "Individual recycling cannot solve systemic corporate pollution. We must change the system! 👣" },
    { id: 'q14', question: "Geoengineering (Plan B) involves spraying Sulfur particles from airplanes into the stratosphere to act as a mirror. Why is this horrifying?", options: ['It costs $10', 'It could permanently destroy global rainfall and cause massive famines by accident; it is playing God with the sky', 'It looks ugly', 'Birds will get mad'], answer: 1, explanation: "It is an unproven emergency surgery for the planet. 🪞" },
    { id: 'q15', question: "Why is the planet Venus hot enough to melt lead?", options: ['It is closest to the sun', 'It has a 96% CO2 atmosphere, creating an absolute runaway Greenhouse Effect (a terrifying warning to Earth)', 'It has lava', 'It spins fast'], answer: 1, explanation: "CO2 traps the heat until the entire planet turns into an oven! 🪐" },
    { id: 'q16', question: "Why does eating beef massively accelerate Climate Change?", options: ['Cows breathe heavily', 'Cows digest grass by fermenting it, burping out massive amounts of Methane (CH4), a gas 25x worse than CO2', 'Cows are heavy', 'They eat all the plants'], answer: 1, explanation: "1.5 billion cows burping heat-trapping gas into the sky! 🐄" },
    { id: 'q17', question: "Why does planting trees, while helpful, NOT completely solve the climate crisis?", options: ['Trees hate CO2', 'Mathematical volume. We emit 40 Billion tons of CO2 a year. We would need to plant a forest the size of America every year to break even', 'Trees drop leaves', 'Oxygen is bad'], answer: 1, explanation: "You cannot bail out a sinking Titanic with a teaspoon. You must fix the hole! 🌳" },
    { id: 'q18', question: "Why does the military consider Climate Change the ultimate 'Threat Multiplier'?", options: ['They hate the rain', 'Droughts destroy crops, creating millions of starving, migrating climate refugees, causing riots and massive regional civil wars', 'Tanks sink in mud', 'Snow blocks roads'], answer: 1, explanation: "Desperate, starving people have nothing to lose. 🪖" },
    { id: 'q19', question: "Why did oil companies secretly bury their own science reports in the 1970s?", options: ['They forgot', 'Their supercomputers perfectly predicted global warming, but they hid the truth and funded fake think-tanks to protect their multi-trillion dollar profits', 'They lost the paper', 'Computers crashed'], answer: 1, explanation: "They sold out the future of humanity for next quarter's profit margin. 🛢️" },
    { id: 'q20', question: "Why is painting city roofs white actually brilliant physics?", options: ['It looks nice', 'Micro-Albedo! The white paint reflects the sun\'s energy directly back into space instead of absorbing it as heat, cooling massive cities', 'It stops rain', 'Birds like it'], answer: 1, explanation: "Create tiny, cheap mirrors to combat the sun! 🏠" },
  ],

  relatedTopics: ['photosynthesis', 'ecosystems', 'energy_types'],
};
