export default {
  id: "demo_facts",
  title: "The Human Brain",
  subtitle: "10 Mind-Blowing Facts",
  category: "Psychology & Mind",
  accentKey: "psychology",
  facts: [
    {
      id: "f1",
      title: "Fact 1",
      content: "The human brain generates about **20 watts of electrical power**—enough to power a dim lightbulb!",
      color: "#FF6B6B",
      bgGradient: ["#2B1A1D", "#0A0506"],
      svgIcon: "zap",
    },
    {
      id: "f2",
      title: "Fact 2",
      content: "Information in your brain can travel at speeds up to **268 miles per hour** (431 km/h).",
      color: "#4ECDC4",
      bgGradient: ["#152B29", "#040D0C"],
      svgIcon: "activity",
    },
    {
      id: "f3",
      title: "Fact 3",
      content: "Your brain is mostly water! It consists of about **73% water**, and even 2% dehydration can affect attention and memory.",
      color: "#3B82F6",
      bgGradient: ["#101E36", "#040914"],
      svgIcon: "droplet",
    },
    {
      id: "f4",
      title: "Fact 4",
      content: "The human brain can store an estimated **2.5 million gigabytes** of digital memory.",
      color: "#F59E0B",
      bgGradient: ["#2B1E0C", "#0A0702"],
      svgIcon: "database",
    },
    {
      id: "f5",
      title: "Fact 5",
      content: "Your brain **cannot feel pain**. There are no pain receptors in the brain itself, which is why surgeons can perform brain surgery on awake patients.",
      color: "#8B5CF6",
      bgGradient: ["#1E1236", "#090514"],
      svgIcon: "shield",
    },
    {
      id: "f6",
      title: "Fact 6",
      content: "Every time you learn something new or form a memory, your brain creates **new physical connections** between neurons.",
      color: "#10B981",
      bgGradient: ["#0B2117", "#030A06"],
      svgIcon: "git-branch",
    },
    {
      id: "f7",
      title: "Fact 7",
      content: "The amygdala, the part of the brain that controls fear, can process threats and trigger a reaction in just **20 milliseconds**.",
      color: "#EF4444",
      bgGradient: ["#2B0C0C", "#0A0202"],
      svgIcon: "alert-triangle",
    },
    {
      id: "f8",
      title: "Fact 8",
      content: "We actually have a \"second brain\"! The gut contains about **100 million neurons** that communicate directly with the brain in your head.",
      color: "#EC4899",
      bgGradient: ["#2A0C1C", "#0A0208"],
      svgIcon: "heart",
    },
    {
      id: "f9",
      title: "Fact 9",
      content: "During sleep, your brain acts like a dishwasher. It uses cerebrospinal fluid to **flush out toxic waste** that builds up during the day.",
      color: "#6366F1",
      bgGradient: ["#12132B", "#05050A"],
      svgIcon: "moon",
    },
    {
      id: "f10",
      title: "Fact 10",
      content: "The human brain is fully developed around age **25**, meaning your frontal lobe (responsible for decision-making) is still maturing through early adulthood.",
      color: "#14B8A6",
      bgGradient: ["#0B211E", "#030A09"],
      svgIcon: "trending-up",
    }
  ]
};
