// ─────────────────────────────────────────────────────────
//  TOPIC: EXISTENTIALISM
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'existentialism',
  title: 'Existentialism',
  subtitle: 'Condemned to be Free 🧬⛓️',
  emoji: '🧬',
  category: 'Philosophy',
  accentKey: 'existentialism',

  hook: {
    question: "A paperknife is designed by someone to cut paper. It has a meaning before it even exists. Are humans like paperknives?",
    reveal: "For centuries, religion and philosophy said YES: God designed humans with a specific purpose (an 'essence'), and our job is to discover it.\n\nBut in the 20th century, Jean-Paul Sartre introduced **Existentialism**, arguing the exact opposite: You were born totally by accident, with zero pre-programmed purpose. This terrifying lack of purpose means you are 'condemned to be free'. You literally have to invent who you are from scratch. Let's explore the heavy burden of absolute freedom. 🎭🗝️",
    emoji: '🗝️',
  },

  theory: [
    {
      id: 'existence_precedes_essence',
      title: "Existence Precedes Essence 🧬",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'file-text',
      svgIcon: 'star',
      content: "This is the core slogan of Existentialism, coined by Jean-Paul Sartre.\n**Essence** means 'what a thing is meant to do'. A chair's essence is to be sat on. Its essence was decided *before* it was built.\nFor humans, **Existence precedes Essence**. You *exist* first (you pop into the world randomly). Only *afterward* do you create your essence through your actions, choices, and beliefs.",
      highlight: "You are not born a hero or a coward. You *make* yourself one. 🔨",
    },
    {
      id: 'jean_paul_sartre',
      title: "Jean-Paul Sartre 🚬",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'user',
      svgIcon: 'eye',
      content: "Sartre (1905–1980) was a French philosopher who made Existentialism famous in post-WWII Paris.\nWalking through the cafes of Paris, smoking his pipe, he argued that human beings are essentially 'nothingness' until they act. \nHe famously rejected the 1964 Nobel Prize in Literature because he didn't want any institution to turn him into an 'institution' and limit his freedom.",
      highlight: "Sartre believed we are nothing but the sum of our actions. 🎬",
    },
    {
      id: 'condemned_to_be_free',
      title: "Condemned to be Free ⛓️",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'unlock',
      svgIcon: 'unlock',
      content: "Sartre wrote: *'Man is condemned to be free.'*\nWhy 'condemned'? Because freedom is not just a gift; it is a crushing, terrifying weight. \nIf there is no God, no cosmic destiny, and no human nature, then you cannot blame *anyone* for who you are. You can't blame your parents, your star sign, or society. You are 100% responsible for your life.",
      highlight: "Absolute freedom means absolute responsibility. You have zero excuses. ⚖️",
    },
    {
      id: 'anguish_of_choice',
      title: "Existential Anguish (Angst) 😨",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'alert-triangle',
      svgIcon: 'zap',
      content: "Have you ever stood near a cliff edge and realized, *'I could jump right now if I wanted to.'*?\nThat dizzying feeling is **Existential Anguish**. It is the horrifying realization that you are completely in control of your destiny.\nWe don't fear the drop; we fear ourselves and our own absolute freedom. Every time we make a major life choice (career, marriage), we feel this anguish because we have no guidebook.",
      highlight: "Anguish is the vertigo of freedom. 🌪️",
    },
    {
      id: 'bad_faith',
      title: "Lying to Yourself (Bad Faith) 🎭",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'frown',
      svgIcon: 'users',
      content: "To escape the terrifying pressure of freedom, humans often commit **Bad Faith (Mauvaise Foi)**.\nBad Faith is lying to yourself. It is pretending you *have* to do something, as if you are an object rather than a free human.\nExamples of Bad Faith: *'I have to stay in this miserable job, I have no choice.'* or *'I can't change, I'm just a Virgo.'*",
      highlight: "Telling yourself 'I have no choice' is the ultimate existential sin. You always have a choice. 🚪",
    },
    {
      id: 'the_waiter',
      title: "The Cafe Waiter Analogy ☕",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'coffee',
      svgIcon: 'eye',
      content: "Sartre famously described a waiter in a cafe who moves a bit too mechanically, pours coffee a bit too eagerly, and acts like a robot.\nThe waiter is acting in **Bad Faith**. He is convincing himself that he *is* a waiter, entirely defined by his job, rather than a free human being who just *chooses* to serve coffee right now. He is letting his job strip him of his humanity.",
      highlight: "You are not your job. Your job is just a role you are choosing to play today. 👔",
    },
    {
      id: 'authenticity',
      title: "Authenticity 🏔️",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'target',
      svgIcon: 'target',
      content: "The opposite of Bad Faith is **Authenticity**.\nLiving authentically means carrying the heavy weight of freedom without complaining. It means acknowledging your past, your circumstances, and your biology, but refusing to let them determine your future.\nAn authentic person says: *'I am in a terrible situation, but how I react to it is entirely my choice.'*",
      highlight: "Authenticity is the courage to author your own story without using excuses. 🖋️",
    },
    {
      id: 'simone_de_beauvoir',
      title: "Simone de Beauvoir 📖",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'book-open',
      svgIcon: 'star',
      content: "De Beauvoir (Sartre's lifelong romantic and philosophical partner) was a foundational Existentialist.\nIn her masterpiece *The Second Sex*, she applied Existentialism to gender, writing: *'One is not born, but rather becomes, a woman.'*\nShe argued that 'femininity' is not a biological given, but a societal essence forced upon women. True freedom means rejecting forced societal essences.",
      highlight: "Biology is not destiny. Society creates the cage; you choose whether to stay in it. 🦅",
    },
    {
      id: 'the_look',
      title: "Hell is Other People 🔥",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'users',
      svgIcon: 'flame',
      content: "In Sartre's play *No Exit*, a character famously says: *'Hell is other people.'*\nHe didn't mean that people are annoying. He meant **The Look**. \nWhen you are alone, you are totally free. But when someone else looks at you, they instantly judge you, label you, and turn you into an 'object' in their mind (e.g., 'He is just a quiet guy'). This robs you of your subjective freedom.",
      highlight: "We suffer because we allow the judgments of others to trap us into identities we didn't choose. 👁‍🗨",
    },
    {
      id: 'facticity_vs_transcendence',
      title: "Facticity vs. Transcendence ⚖️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'layers',
      svgIcon: 'lock',
      content: "Existentialists divide reality into two parts:\n**Facticity**: The facts you cannot change (where you were born, your height, your painful past).\n**Transcendence**: Your ability to choose what to do *next*.\nBad faith is saying: *'Because of my Facticity, I have no Transcendence.'* (Because I had a bad childhood, I cannot be a good parent).",
      highlight: "You cannot change the cards you were dealt, but you freely choose how to play them. 🃏",
    },
    {
      id: 'kierkegaard',
      title: "The Christian Existentialist ✝️",
      color: '#9E9E9E',
      bgGradient: ['#151515', '#050505'],
      icon: 'crosshair',
      svgIcon: 'cloud',
      content: "Before Sartre, there was Søren Kierkegaard (early 1800s), the 'father' of Existentialism.\nUnlike Sartre, Kierkegaard believed in God. But he believed that religion shouldn't be about blindly following church rules. \nHe argued that true faith requires a terrifying, lonely, absurd 'Leap of Faith' into the unknown, requiring total personal responsibility.",
      highlight: "Even if you choose God, you are still making a terrifyingly free personal choice. 🌌",
    },
    {
      id: 'radical_responsibility',
      title: "Radical Responsibility 🌍",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'globe',
      svgIcon: 'users',
      content: "Sartre argued that because we are totally free, we are responsible not just for ourselves, but for all of humanity.\nWhen you make a choice, you are essentially saying: *'This is how a human being ought to act.'*\nIf you choose to be dishonest, you are validating dishonesty for the world. This makes every choice incredibly heavy.",
      highlight: "In choosing myself, I choose man. 🌐",
    },
    {
      id: 'freedom_vs_happiness',
      title: "Freedom Over Happiness ⚖️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'smile',
      svgIcon: 'zap',
      content: "Existentialism does not guarantee happiness. In fact, living authentically often makes you *less* happy because you cannot hide behind comforting lies.\nBut for an Existentialist, **Freedom** is a higher value than Happiness.\nWould you rather be a happy slave in a matrix, or a sad, free human in reality? Existentialists always choose reality.",
      highlight: "Comfort is the enemy of authenticity. 🛡️",
    },
    {
      id: 'dostoevsky',
      title: "If God is Dead... 🪓",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'slash',
      svgIcon: 'lock',
      content: "Russian novelist Fyodor Dostoevsky heavily influenced Existentialism.\nIn *The Brothers Karamazov*, a character declares: *'If God does not exist, everything is permitted.'*\nSartre agreed with this! Without a divine rule-giver, there are no absolute moral laws written in the stars. We must have the courage to invent our own morals, and hold ourselves strictly to them.",
      highlight: "Without a cosmic parent to tell us what is 'good', we must do the terrifying work of defining it ourselves. 📝",
    },
    {
      id: 'conclusion',
      title: "The Ultimate Empowerment 💪",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'award',
      svgIcon: 'star',
      content: "Existentialism sounds depressing at first glance (Anguish, Despair, Condemned).\nBut once you accept it, it is the most empowering philosophy in history. \nIt means you are not broken. You are not destined to fail. You are not trapped by your past. Every morning you wake up, you are a blank slate with the power to reinvent yourself.",
      highlight: "You are the artist, the paintbrush, and the canvas. Make a masterpiece. 🎨",
    },
  ],

  lab: {
    title: "Bad Faith Detector 🎭🩻",
    description: "Welcome to the Existential Clinic. Patients will present their life problems. You must scan their language for 'Bad Faith' (Mauvaise Foi)—lying to themselves by pretending they have no choice. Identify the excuse and prescribe Radical Freedom.",
    hint: "Anytime someone says 'I have to', 'I was born this way', or 'Society makes me', they are dodging the painful responsibility of their own freedom.",
    scientistModeHint: "Ontological Mode 🧑‍🔬: Differentiate strictly between 'Facticity' (unalterable facts) and 'Transcendence' (future choices).",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why did Sartre name his play 'No Exit'?", answer: "Because the three characters are locked in a room together for eternity. They soon realize there is no physical torture device—they just mentally torture each other through 'The Look' (constantly judging and labeling each other). They are trapped because they seek external validation instead of internal authenticity. 🚪", emoji: '🔥' },
    { id: 'dyk2', question: "Why do we feel 'vertigo' or 'anxiety' about making life choices?", answer: "Because your brain realizes that nothing is physically stopping you from making a chaotic choice. When choosing a career, you feel 'Anguish' because there is no 'correct' cosmic answer; you have to invent the answer, and you are 100% responsible if it fails. 🌪️", emoji: '🧠' },
    { id: 'dyk3', question: "Did Sartre regret ignoring biology?", answer: "Yes. Later in life, Sartre admitted that his early theory ('humans are 100% blank slates') was slightly too extreme. He acknowledged that poverty, biology, and systemic oppression severely limit a person's options. However, he maintained that *how you react* to that oppression is still a free choice. 📉", emoji: '⚖️' },
    { id: 'dyk4', question: "Why a 'cafe waiter'?", answer: "Sartre spent hours writing in French cafes. He noticed a waiter who was excessively bowing, balancing trays perfectly, and acting like a caricature of a waiter. Sartre realized the man was playing a game of 'make-believe' to escape his complex humanity, trading freedom for an easy, pre-packaged 'Essence'. ☕", emoji: '👔' },
    { id: 'dyk5', question: "Why did Simone de Beauvoir say 'One is not born a woman'?", answer: "She meant that you are born purely as a biological female (Facticity), but society immediately starts forcing a specific 'Essence' on you (how to dress, act passive, be quiet). She argued that conforming to these forced gender roles without questioning them is living in Bad Faith. 👩‍🎓", emoji: '📖' },
  ],

  quiz: [
    { id: 'q1', question: "What is the core slogan of Existentialism?", options: ['I think, therefore I am', 'Existence precedes Essence', 'God is dead', 'Everything happens for a reason'], answer: 1, explanation: "You exist first, and then you build your own purpose. 🧬" },
    { id: 'q2', question: "If 'Essence' comes before 'Existence' for a paperknife, what does that mean?", options: ['It was invented before the paper', 'The concept and purpose of the knife existed in the creator\'s mind before the knife was physically manufactured', 'It has no meaning', 'It is made of wood'], answer: 1, explanation: "Religion says humans are like the paperknife (God designed us for a purpose). Existentialism says NO. 🔪" },
    { id: 'q3', question: "What did Jean-Paul Sartre mean by 'Condemned to be free'?", options: ['Jail sentences', 'Freedom is not a joyful gift; it is a heavy, inescapable burden because you are 100% responsible for your life without excuses', 'Freedom is illegal', 'Humans want to be slaves'], answer: 1, explanation: "You have no guidebook to blame your failures on. ⛓️" },
    { id: 'q4', question: "What is 'Bad Faith' (Mauvaise Foi)?", options: ['A terrible church', 'Lying to yourself by pretending you are an object with no choice, running away from the anxiety of absolute freedom', 'Trusting the wrong person', 'Bad credit scores'], answer: 1, explanation: "Saying 'I am forced to do this' is the ultimate existential lie. 🎭" },
    { id: 'q5', question: "In Sartre's example, why is the Cafe Waiter in Bad Faith?", options: ['He spit in the coffee', 'He is acting like a robotic caricature of a waiter to avoid dealing with his complex freedom as a human being', 'He hates his job', 'He quit'], answer: 1, explanation: "He is pretending his job is his 'Essence'. ☕" },
    { id: 'q6', question: "What is the opposite of Bad Faith in Existentialism?", options: ['Good Karma', 'Authenticity: taking full responsibility for your freedom and authoring your own story without making excuses', 'Religion', 'Money'], answer: 1, explanation: "Authenticity means holding the heavy weight of freedom. 🏔️" },
    { id: 'q7', question: "What does Simone de Beauvoir's quote, 'One is not born, but rather becomes, a woman' mean?", options: ['Biology isn\'t real', 'While one is born biologically female, society forces a pre-packaged \'Essence\' of femininity onto them, which must be rebelled against to find true freedom', 'Age matters', 'Women are superior'], answer: 1, explanation: "Applying Existentialism to gender roles and societal conditioning. 📖" },
    { id: 'q8', question: "What did Sartre mean by 'Hell is other people'?", options: ['Parties are annoying', 'The \'Look\' of another person instantly judges you, labels you, and reduces you to an object in their mind, stripping you of your subjective freedom', 'Demons are real', 'We should all live alone'], answer: 1, explanation: "We suffer because we allow others' judgments to define us. 🔥" },
    { id: 'q9', question: "What is 'Facticity' in Existentialism?", options: ['Fake news', 'The unalterable facts of your life that you did not choose (e.g., your birth year, your genetics, your past traumas)', 'Your future goals', 'Math equations'], answer: 1, explanation: "You cannot change your Facticity, but you choose how to react to it. ⚖️" },
    { id: 'q10', question: "If Facticity is what you cannot change, what is 'Transcendence'?", options: ['A cool word', 'Your absolute freedom to make choices moving forward, transcending your past', 'Flying', 'Meditation'], answer: 1, explanation: "The past does not dictate the future. 🚀" },
    { id: 'q11', question: "What is 'Existential Anguish'?", options: ['Stomach aches', 'The dizzying, terrifying vertigo of realizing you have absolute freedom and no cosmic guidebook to make choices for you', 'Fear of spiders', 'Anger at God'], answer: 1, explanation: "Standing at the cliff edge and realizing you are perfectly free to jump or not. 😨" },
    { id: 'q12', question: "Who is considered the 'Father of Existentialism' (even though he was a devout Christian)?", options: ['Atheist John', 'Søren Kierkegaard: he believed faith required a terrifying, lonely, personal \'Leap into the absurd\'', 'The Pope', 'Martin Luther'], answer: 1, explanation: "He emphasized personal responsibility in choosing God, rather than blind herd religion. ✝️" },
    { id: 'q13', question: "Why did Sartre reject the Nobel Prize in Literature?", options: ['He hated the prize money', 'He didn\'t want an institution to turn him into an \'object\' or a labeled \'Nobel Winner\', which would limit his radical freedom', 'He was tired', 'He thought someone else deserved it'], answer: 1, explanation: "He refused to be defined by society's labels. ✖️" },
    { id: 'q14', question: "What does 'Radical Responsibility' mean?", options: ['Recycling', 'Because you are perfectly free, your choices don\'t just define you, they declare to the universe: \'This is how humanity ought to act\'', 'Taking care of pets', 'Paying taxes'], answer: 1, explanation: "In choosing myself, I choose man. 🌍" },
    { id: 'q15', question: "How does Existentialism relate to Dostoevsky's quote: 'If God does not exist, everything is permitted'?", options: ['It proves God exists', 'Existentialists agree with it! Without God, there are no objective moral laws. We bear the terrifying burden of inventing our own morals', 'It is about crime', 'It makes people evil'], answer: 1, explanation: "We must be the authors of our own moral code. 🪓" },
    { id: 'q16', question: "Which value does an Existentialist prioritize highest?", options: ['Comfort', 'Happiness', 'Wealth', 'Freedom (Authenticity)'], answer: 3, explanation: "Better to be an authentic, struggling human than a happy robot in 'Bad Faith'. 🛡️" },
    { id: 'q17', question: "If a person says, 'I cheat on tests because my star sign is Gemini', this is an example of:", options: ['Astrology working', 'Bad Faith: using an external label to escape the responsibility of their free action', 'Facticity', 'Science'], answer: 1, explanation: "Blaming the stars is intellectually cowardly. 🎭" },
    { id: 'q18', question: "How does Existentialism differ from Stoicism?", options: ['They are the same', 'Stoicism focuses on controlling your internal reaction to the world. Existentialism focuses on authoring your very purpose and identity from scratch', 'Stoicism hates freedom', 'Existentialism likes weather'], answer: 1, explanation: "Stoicism is about resilience; Existentialism is about identity. 🧬" },
    { id: 'q19', question: "Why can Existentialism be viewed as an 'empowering' philosophy?", options: ['It gives you magic powers', 'Once you accept there is no destiny, you realize you are a blank slate every single morning with the power to completely reinvent yourself', 'It promises heaven', 'It gives you money'], answer: 1, explanation: "You are never 'stuck' in an identity you don't want. 💪" },
    { id: 'q20', question: "In Existentialism, humans are NOTHING until they...", options: ['Sleep', 'Act. We are purely the sum of our actions and choices, not our secret inner thoughts', 'Are born', 'Pray'], answer: 1, explanation: "If you want to be a hero, holding 'heroic thoughts' isn't enough. You must do heroic actions. 🎬" },
  ],

  relatedTopics: ['absurdism', 'nihilism', 'stoicism'],
};
