// ─────────────────────────────────────────────────────────
//  TOPIC: WHY SCIENCE CAN'T DISPROVE GOD
//  Category: Religion & God
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'science_vs_god',
  title: 'Why Science Can\'t Disprove God',
  subtitle: 'The honest limits of human knowledge 🔬🔮',
  emoji: '🔬',
  category: 'Religion & God',
  accentKey: 'science_vs_god',

  hook: {
    question: "If science is so powerful that it can split atoms, decode DNA, and photograph black holes 55 million light-years away — why can't it simply answer the most basic question humanity has ever asked: 'Does God exist?'",
    reveal: "Because the question 'Does God exist?' is not a scientific question at all. Science can only investigate things that are **measurable, testable, and falsifiable**. God — by almost every theological definition — is defined as existing OUTSIDE space, time, and matter.\n\nAsking science to detect God is like asking a metal detector to find love. The tool is extraordinary — it's just designed for a completely different category of reality. This doesn't prove God exists. It doesn't prove God doesn't exist. It proves that the question itself lives outside science's jurisdiction. 🧪📏🚫",
    emoji: '🤔',
  },

  theory: [
    {
      id: 'demarcation_problem',
      title: "The Demarcation Problem 🚧",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'target',
      svgIcon: 'shield',
      content: "Philosophy of science has a famous unsolved problem: **Where exactly does science end and non-science begin?**\n\nKarl Popper proposed the answer: Science is anything that can be **falsified** (proven wrong by evidence). If no possible experiment could ever disprove your claim, your claim is not scientific — it's metaphysical.\n\nMost God-claims are unfalsifiable by design. 'God exists outside space and time' cannot be tested by ANY instrument that operates within space and time. This doesn't make the claim wrong — it makes it **outside science's jurisdiction**.",
      highlight: "Unfalsifiable ≠ False. It means science literally cannot deliver a verdict — guilty OR innocent. ⚖️",
    },
    {
      id: 'methodological_naturalism',
      title: "Methodological Naturalism 🧪",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'flask',
      svgIcon: 'microscope',
      content: "Science operates under **Methodological Naturalism** — the working assumption that ONLY natural causes will be considered when explaining phenomena.\n\nThis is NOT a claim that the supernatural doesn't exist. It's a **methodological rule**: 'For the purposes of doing science, we will only look for natural explanations.'\n\nA detective investigating a murder doesn't check for ghosts — not because ghosts definitely don't exist, but because the detective's METHOD requires physical evidence. Science works the same way. It's a self-imposed limitation, not a proof of anything.",
      highlight: "Science says: 'We CHOOSE to look only at natural causes.' It does NOT say: 'Natural causes are ALL that exist.' 🔍",
    },
    {
      id: 'god_of_gaps',
      title: "The 'God of the Gaps' Fallacy ⚠️",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'alert-triangle',
      svgIcon: 'alert',
      content: "Throughout history, people used God to explain things science hadn't figured out yet:\n• 'Why does lightning strike?' → Zeus/Thor!\n• 'Why do people get sick?' → God's punishment!\n• 'How did life begin?' → God created it!\n\nBut as science advanced, these gaps shrank. This is the **God of the Gaps** fallacy — using God as a placeholder for ignorance.\n\nHowever, the sophisticated theist responds: 'I'm not saying God explains the gaps. I'm saying God explains why there's a natural order AT ALL.' That's a fundamentally different claim that gap-closing can't touch.",
      highlight: "Every time science closes a gap, 'God of the Gaps' retreats. But 'God of the Whole System' doesn't. 🧩",
    },
    {
      id: 'fine_tuning',
      title: "The Fine-Tuning Argument 🎯",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'target',
      svgIcon: 'star',
      content: "The fundamental constants of physics (gravitational constant, speed of light, nuclear forces) appear to be fine-tuned to an absurd degree:\n\n• If gravity were 0.00000000000000000000000000000000000001% stronger, the universe would have collapsed instantly.\n• If the nuclear strong force were 2% weaker, no atoms beyond hydrogen would exist.\n\nThis is scientifically verified. The debate is about **interpretation**:\n• **Theist**: This proves an intelligent designer calibrated the dials.\n• **Atheist**: The Multiverse theory suggests infinite universes with random constants — we just happen to be in the lucky one.\n\nNeither can be tested. Both are faith-based extrapolations.",
      highlight: "The probability of our universe's constants occurring by chance has been estimated at 1 in 10^229. Science confirms the precision; it cannot confirm the cause. 🎲",
    },
    {
      id: 'first_cause',
      title: "The First Cause Problem ⏮️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'clock',
      svgIcon: 'compass',
      content: "Science traces every effect to a prior cause. But this creates an infinite regress:\n\n• The Big Bang caused the universe → What caused the Big Bang?\n• Quantum fluctuations in a vacuum → What caused the vacuum to exist?\n• The laws of physics → What caused the laws of physics?\n\nAt some point, you must either accept:\n1. **An uncaused first cause** (which theists call God)\n2. **An infinite regression** (causes going back forever with no beginning)\n3. **A brute fact** — 'The universe just exists, and that's that.'\n\nScience cannot determine which of these three is correct. Each is a philosophical position, not a scientific one.",
      highlight: "Stephen Hawking said: 'Because there is a law like gravity, the universe can create itself from nothing.' Critics respond: 'But who created the law of gravity?' 🐔🥚",
    },
    {
      id: 'consciousness_blind_spot',
      title: "The Consciousness Blind Spot 🧠",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'eye',
      svgIcon: 'brain',
      content: "Science has no explanation for **subjective conscious experience** — why it FEELS like something to be you.\n\nWe understand that neurons fire. We understand brain chemistry. But we have ZERO understanding of why those physical processes produce the inner movie of 'being alive.'\n\nDavid Chalmers calls this the **Hard Problem of Consciousness**. It may be the one phenomenon that physical science is structurally incapable of explaining — because the observer IS the phenomenon being observed.\n\nMany theists argue consciousness is evidence of a non-physical dimension (soul/spirit). Many scientists argue we just haven't solved it YET.",
      highlight: "No amount of brain scanning tells you what it FEELS like to see red. The subjective is invisible to the objective. 🔴",
    },
    {
      id: 'moral_argument',
      title: "The Moral Argument 🧭",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'compass',
      svgIcon: 'scale',
      content: "Science can describe WHAT humans do. It cannot prescribe what they SHOULD do.\n\n• Evolution explains why altruism exists (it aids survival)\n• But evolution CANNOT say murder is objectively WRONG — only that societies punishing murder survive longer\n\nThe **Moral Argument** for God says: If objective morality exists (torturing babies is TRULY wrong, not just culturally unpopular), then there must be a moral lawgiver outside of human opinion.\n\nThe atheist responds: 'Morality is a human construct — useful, but not objective.'\n\nScience has no way to test which position is correct.",
      highlight: "Hume's Guillotine: You cannot logically derive an 'ought' from an 'is'. Science describes what IS. Morality prescribes what OUGHT to be. ✂️",
    },
    {
      id: 'problem_of_evil',
      title: "The Problem of Evil 💀",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert',
      svgIcon: 'alert',
      content: "The most powerful argument AGAINST God's existence is purely logical, not scientific:\n\n1. If God is all-powerful, He CAN prevent suffering.\n2. If God is all-good, He WOULD prevent suffering.\n3. Suffering exists.\n4. Therefore, an all-powerful, all-good God cannot exist.\n\nTheological responses include:\n• **Free Will Defense**: God allows evil so humans can have genuine choice.\n• **Soul-Making**: Suffering builds character and spiritual growth.\n• **Mystery**: God's reasons are beyond human comprehension.\n\nNote: This entire debate is philosophical, not scientific. No experiment can test it.",
      highlight: "Epicurus posed this paradox 2,300 years ago. It remains the strongest challenge to theism — and it has nothing to do with science. 🏛️",
    },
    {
      id: 'scientism',
      title: "Scientism — When Science Overreaches 🦾",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'alert-triangle',
      svgIcon: 'lock',
      content: "**Scientism** is the philosophical position that science is the ONLY valid source of knowledge — and that anything science can't measure doesn't exist.\n\nThe problem? Scientism is self-refuting.\n\nThe claim 'Only scientific statements are meaningful' is itself NOT a scientific statement — it's a philosophical one. It cannot be tested in a lab. It's a circular belief system that uses itself to validate itself.\n\nMany prominent scientists (like Einstein, Heisenberg, and Gödel) explicitly warned against scientism. Science is the best tool for understanding the PHYSICAL world. It was never designed to be the only tool for understanding ALL of reality.",
      highlight: "Einstein: 'Science without religion is lame; religion without science is blind.' — He meant both have limits. 👓",
    },
    {
      id: 'multiverse',
      title: "The Multiverse — Science's Own 'Faith'? 🌌",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'galaxy',
      svgIcon: 'planet',
      content: "To explain the universe's fine-tuning WITHOUT God, many physicists propose the **Multiverse** — an infinite number of parallel universes, each with different physical constants.\n\nBut here's the uncomfortable truth: The Multiverse is **not testable, not observable, and not falsifiable**. By Popper's own standard, it is NOT a scientific theory — it's a theoretical extrapolation.\n\nIronically, believing in an infinite number of undetectable parallel universes requires a type of 'faith' remarkably similar to the 'faith' scientists accuse religion of.\n\nThe Multiverse may be true. God may be true. Neither can currently be verified by science.",
      highlight: "Physicist Paul Davies: 'The multiverse theory requires as much faith as theology.' 🪞",
    },
    {
      id: 'godel_incompleteness',
      title: "Gödel's Incompleteness — Math Has Limits Too 🔢",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'hash',
      svgIcon: 'lock',
      content: "In 1931, mathematician Kurt Gödel proved something devastating: **Any sufficiently complex logical system contains true statements that CANNOT be proven within that system.**\n\nTranslation: Even mathematics — the purest form of rational inquiry — has inherent, inescapable blind spots.\n\nIf pure logic itself has limits, then a system built ON logic (science) must have even MORE limits. There will always be truths that exist beyond what any formal system can reach.\n\nGödel himself believed this implied the existence of a reality beyond the physical — though he kept this belief private.",
      highlight: "If even MATH can't prove everything, how could science — which is less precise than math — possibly prove or disprove God? 🤷‍♂️",
    },
    {
      id: 'category_error',
      title: "The Category Error 🏷️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'grid',
      svgIcon: 'target',
      content: "Asking 'Can science disprove God?' commits a **Category Error** — applying the tools of one category to a question from a completely different category.\n\nExamples of category errors:\n• 'What does the color blue smell like?'\n• 'How much does love weigh?'\n• 'What is the mathematical formula for beauty?'\n\nThese aren't stupid questions — they're questions addressed to the wrong department. Science investigates the NATURAL world. Most God-concepts are defined as supernatural. Using a natural tool on a supernatural question is a fundamental mismatch.",
      highlight: "Wittgenstein: 'Whereof one cannot speak, thereof one must be silent.' Some questions live outside language AND science. 🤫",
    },
    {
      id: 'burden_of_proof',
      title: "The Burden of Proof — Who Must Prove What? ⚖️",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'scale',
      svgIcon: 'scale',
      content: "In logic, the **Burden of Proof** falls on whoever makes the claim:\n\n• Theist says: 'God exists.' → Must provide evidence.\n• Atheist says: 'God does NOT exist.' → Must also provide evidence (proving a negative is extremely hard).\n• Agnostic says: 'I don't know.' → No burden; but no answers either.\n\nThe honest position is that BOTH sides carry a burden. The theist must explain why their specific God-concept is plausible. The strong atheist must explain how they can definitively rule out ALL possible God-concepts across ALL possible dimensions of reality.",
      highlight: "Philosopher Bertrand Russell's 'Celestial Teapot': You can't disprove an invisible orbiting teapot, but that doesn't make believing in one reasonable. 🫖",
    },
    {
      id: 'personal_experience',
      title: "Religious Experience — Data or Delusion? ✨",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'sparkle',
      svgIcon: 'eye',
      content: "Billions of humans across all cultures report personal experiences of the divine — visions, answered prayers, near-death experiences, overwhelming feelings of universal love.\n\nScience can explain SOME of these:\n• Temporal lobe epilepsy produces god-like visions\n• Oxygen deprivation explains tunnel-of-light NDEs\n• Psilocybin triggers mystical experiences\n\nBut explaining the MECHANISM doesn't disprove the CONTENT. A radio's circuits explain HOW it receives a signal — they don't prove the signal isn't real.\n\nThe hard question remains: Is religious experience evidence of God, or evidence of brain glitches?",
      highlight: "William James (1902): 'To the person who has had one, a mystical experience is as real as any other fact.' 🌟",
    },
    {
      id: 'honest_conclusion',
      title: "The Honest Conclusion — Intellectual Humility 🙏",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'leaf',
      svgIcon: 'heart',
      content: "The intellectually honest conclusion is uncomfortable for BOTH sides:\n\n**Science cannot disprove God** because God, by most definitions, exists outside its testable domain.\n\n**Science cannot prove God either** for the exact same reason.\n\nThis leaves us with a genuine mystery — a question that may be **permanently, structurally unanswerable** by the human mind.\n\nRichard Feynman captured this perfectly: 'I can live with doubt, and uncertainty, and not knowing. I think it's much more interesting to live not knowing than to have answers which might be wrong.'\n\nThe bravest position is not certainty. It is comfortable uncertainty.",
      highlight: "The most honest words in human language might be: 'I don't know — and I'm okay with that.' 🕊️",
    },
  ],

  lab: {
    title: "The Epistemology Engine ⚖️🔬",
    description: "Evaluate claims by categorizing them as Scientific (testable), Philosophical (logical but not testable), or Metaphysical (beyond both). Watch how the Certainty Meter shifts as you correctly classify different God-related and science-related claims!",
    hint: "Not every claim about God is unscientific, and not every scientific claim is certain. The boundaries are blurrier than you think!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Popper falsifiability scores, Bayesian probability overlays, and epistemic confidence intervals.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why Einstein believed in God but rejected organized religion? 🧔", answer: "Einstein described himself as believing in 'Spinoza's God' — not a personal God who answers prayers, but the rational, mathematical harmony underlying the laws of nature. He said: 'I want to know God's thoughts; the rest are details.' He rejected the personal God of the Bible but was awestruck by the universe's inexplicable order. 🌌", emoji: '🔭' },
    { id: 'dyk2', question: "Do you know why the Big Bang theory was originally MOCKED as religious propaganda? 💥", answer: "The Big Bang theory was first proposed in 1927 by Georges Lemaître — a Catholic priest AND physicist! Critics, including Fred Hoyle (who coined the mocking name 'Big Bang'), dismissed it as religious wishful thinking because 'the universe had a beginning' sounded too much like Genesis 1:1. Ironically, the 'religious' theory turned out to be scientifically vindicated. 🧑‍🔬✝️", emoji: '💣' },
    { id: 'dyk3', question: "Do you know why Charles Darwin never called himself an atheist? 🐵", answer: "Despite destroying the argument from biological design, Darwin only called himself an 'agnostic' (a term his friend Thomas Huxley invented). Darwin wrote: 'The mystery of the beginning of all things is insoluble by us; and I for one must be content to remain an agnostic.' He considered the question genuinely unanswerable. 📖", emoji: '🧬' },
    { id: 'dyk4', question: "Do you know why the founder of genetics was a monk? 🧬", answer: "Gregor Mendel, the father of genetics, was an Augustinian friar who conducted pea plant experiments in his monastery garden. Many pioneering scientists were deeply religious — including Newton, Faraday, Leibniz, Pasteur, and Lemaître. The 'science vs. religion war' narrative is largely a modern construction. 🌱", emoji: '⛪' },
    { id: 'dyk5', question: "Do you know why quantum mechanics actually made the God-debate HARDER, not easier? ⚛️", answer: "Classical physics was deterministic — everything had a clear cause. This made God seem unnecessary. But quantum mechanics revealed that at the subatomic level, events are fundamentally random and indeterminate. The 'observer effect' suggested consciousness might play a role in reality itself. Suddenly, the universe looked far more mysterious than materialists had assumed. 🤯", emoji: '🔮' },
  ],

  quiz: [
    { id: 'q1', question: "Karl Popper's criterion for a claim to be 'scientific' is that it must be:", options: ['Popular', 'Falsifiable (capable of being proven wrong by evidence)', 'Published in a journal', 'Believed by most people'], answer: 1, explanation: "If no experiment could possibly disprove it, it's metaphysics, not science. 🧪" },
    { id: 'q2', question: "Methodological Naturalism means:", options: ['Only natural things exist', 'Science CHOOSES to investigate only natural causes, without claiming supernatural causes don\'t exist', 'God is a natural being', 'Nature is God'], answer: 1, explanation: "It's a self-imposed limitation of method, NOT a metaphysical claim about all reality. 🔍" },
    { id: 'q3', question: "The 'God of the Gaps' fallacy is:", options: ['Using God to explain everything', 'Using God as a placeholder explanation for things science hasn\'t explained yet', 'Believing in God', 'A scientific theory'], answer: 1, explanation: "Gap-filling with God is risky because science keeps closing gaps. 'God of the Whole System' is different. ⚠️" },
    { id: 'q4', question: "The Fine-Tuning Argument notes that the universe's physical constants are:", options: ['Random and meaningless', 'Precisely calibrated to an almost impossible degree for life to exist', 'Poorly designed', 'Constantly changing'], answer: 1, explanation: "This precision is scientifically measured and undisputed. The CAUSE is what's debated. 🎯" },
    { id: 'q5', question: "The First Cause Problem asks:", options: ['Who created humans?', 'What caused the very first cause in the chain of causes? Science cannot answer this.', 'Why?', 'When did time begin?'], answer: 1, explanation: "Infinite regress, uncaused cause, or brute fact — all three are philosophical positions. ⏮️" },
    { id: 'q6', question: "The 'Hard Problem of Consciousness' is:", options: ['Building a smarter computer', 'Explaining why physical brain processes produce subjective inner experience', 'Learning to meditate', 'Understanding sleep'], answer: 1, explanation: "We know neurons fire. We have NO idea why that produces the inner 'movie' of being alive. 🧠" },
    { id: 'q7', question: "Hume's Guillotine states:", options: ['You should cut things', 'You cannot logically derive what OUGHT to be from what IS', 'Science is always right', 'Morality is objective'], answer: 1, explanation: "Science describes what IS. Morality prescribes what OUGHT to be. The gap between them is unbridgeable. ✂️" },
    { id: 'q8', question: "The Problem of Evil challenges theism by arguing:", options: ['Evil is fun', 'If God is all-powerful and all-good, the existence of suffering is logically contradictory', 'Science has disproved God', 'Evil doesn\'t exist'], answer: 1, explanation: "This is a purely LOGICAL argument — no science required. It's 2,300 years old. 💀" },
    { id: 'q9', question: "Scientism is problematic because:", options: ['Science is bad', 'The claim \'only scientific statements are meaningful\' is itself NOT a scientific statement — it\'s self-refuting', 'It\'s too expensive', 'Scientists don\'t like it'], answer: 1, explanation: "Scientism uses philosophy to declare philosophy useless. That's a contradiction. 🦾" },
    { id: 'q10', question: "The Multiverse theory is similar to theism in that:", options: ['Both are religious', 'Both propose an untestable, unfalsifiable, unobservable entity to explain the universe', 'Both involve prayer', 'Both are ancient'], answer: 1, explanation: "Infinite undetectable universes require the same type of 'faith' that theism does. 🌌" },
    { id: 'q11', question: "Gödel's Incompleteness Theorems prove that:", options: ['Math is wrong', 'Any sufficiently complex logical system contains true statements it CANNOT prove within itself', 'God exists', 'Science is useless'], answer: 1, explanation: "Even pure mathematics has blind spots — so science must have even more. 🔢" },
    { id: 'q12', question: "A 'Category Error' in the science-vs-God debate means:", options: ['God is in the wrong category', 'Applying the tools of one domain to questions belonging to a fundamentally different domain', 'Science has categories', 'Theists categorize incorrectly'], answer: 1, explanation: "Asking science to find God is like asking a thermometer to measure beauty. Wrong tool. 🏷️" },
    { id: 'q13', question: "The Burden of Proof falls on:", options: ['Only the theist', 'Only the atheist', 'Whoever makes the claim — BOTH sides carry it for their respective claims', 'No one'], answer: 2, explanation: "'God exists' requires evidence. 'God definitely does NOT exist' also requires evidence. ⚖️" },
    { id: 'q14', question: "Science can explain the MECHANISM of a religious experience (brain chemistry), but:", options: ['This proves it\'s fake', 'Explaining HOW something happens doesn\'t prove the experience has no real external source', 'Brain chemistry disproves God', 'Religious experience is just epilepsy'], answer: 1, explanation: "Understanding how a radio works doesn't prove the radio signal isn't real. 📻" },
    { id: 'q15', question: "Einstein's personal view of God was:", options: ['Strict atheism', 'Biblical fundamentalism', 'Belief in Spinoza\'s God — the rational mathematical harmony of nature, not a personal God', 'Agnosticism'], answer: 2, explanation: "Einstein revered the universe's mysterious order but rejected a God who answers prayers. 🧔" },
    { id: 'q16', question: "The Big Bang theory was first proposed by:", options: ['An atheist', 'A Catholic priest and physicist (Georges Lemaître)', 'NASA', 'Stephen Hawking'], answer: 1, explanation: "The 'universe had a beginning' hypothesis was initially mocked as religious propaganda! 💥" },
    { id: 'q17', question: "Darwin considered himself:", options: ['A devout Christian', 'An atheist', 'An agnostic — the question was genuinely unanswerable', 'A Hindu'], answer: 2, explanation: "Darwin never crossed from 'I see no evidence for God' to 'God definitely doesn\'t exist.' 🐵" },
    { id: 'q18', question: "Quantum mechanics made the God-debate harder because:", options: ['It proved God', 'It revealed fundamental randomness and observer-dependent reality, making the universe far more mysterious', 'It disproved God', 'It had nothing to do with God'], answer: 1, explanation: "The universe at the quantum level behaves nothing like the tidy, mechanical clockwork materialists expected. ⚛️" },
    { id: 'q19', question: "Richard Feynman's approach to the God question was:", options: ['Militant atheism', 'Fundamentalist belief', 'Comfortable with uncertainty: \'I can live with doubt and not knowing\'', 'Ignoring it completely'], answer: 2, explanation: "Feynman modeled intellectual humility. He found mystery more interesting than false certainty. 🕊️" },
    { id: 'q20', question: "The most intellectually honest conclusion about science and God is:", options: ['Science has disproved God', 'Science has proved God', 'Science can neither prove nor disprove God — the question may be permanently outside its jurisdiction', 'The question is meaningless'], answer: 2, explanation: "The bravest position is not certainty in either direction — it is comfortable, honest uncertainty. 🙏" },
  ],

  relatedTopics: ['how_religion_evolved', 'god_arguments', 'consciousness', 'free_will'],
};
