// ─────────────────────────────────────────────────────────
//  TOPIC: HAPPINESS SCIENCE
//  Category: Society
//  Standard: v2.0 Extreme (15 Cards, 10 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'happiness_science',
  title: 'Science of Happiness',
  subtitle: 'The evidence-based guide to a joyful life ☀️🧬',
  emoji: '☀️',
  category: 'Society',
  accentKey: 'happiness',

  hook: {
    question: "If you won the lottery tomorrow, would you be happier a year from now? What if you lost the ability to walk? 🎲",
    reveal: "Shockingly, studies show that one year later, both lottery winners and accident victims return to almost exactly the same baseline level of happiness. This is the great paradox of the human mind: we are TERRIBLE at predicting what will actually make us happy! The good news? Science has spent decades studying the 'Happiest People on Earth' and has found exactly what the recipe for joy really is. It's not money, and it's not fame. Let's find out! 🧪✨",
    emoji: '📈',
  },

  theory: [
    {
      id: 'hedonic_treadmill',
      title: 'The Hedonic Treadmill 🏃‍♂️',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🏃‍♂️',
      svgIcon: 'target',
      content: "The **Hedonic Treadmill** is the human tendency to rapidly adapt to a new situation—good or bad—and return to a baseline level of happiness. 📉\n\nWhen you buy a new phone, you are thrilled for a week. A month later, it's just 'your phone.' You adapt. \nSo, you buy something else, trying to get that thrill back. You are running on a treadmill, working incredibly hard but staying in the exact same emotional spot. \n\nThis is why chasing 'Things' never results in permanent joy. 🛍️❌",
      highlight: "We adapt to luxury as quickly as we adapt to hardship. Materialism is a trap! 🪤",
    },
    {
      id: 'genetics_of_joy',
      title: 'The 50-10-40 Rule 🧬',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🧬',
      svgIcon: 'zap',
      content: "Psychologist Sonja Lyubomirsky proposed a pie chart for what determines our happiness:\n\n• **50% is Genetics:** You have a biological 'set point' based on your DNA. Some people are naturally more cheerful. 🧬\n• **10% is Circumstances:** Money, health, where you live, and what you own. Yes, only 10%! 🏡\n• **40% is Intentional Activity:** The choices you make, your habits, and how you perceive the world. 🧠\n\nThis means a massive chunk of your joy is entirely within your control! 🎛️",
      highlight: "You cannot change your genes, but you control the massive 40% chunk! 💪",
    },
    {
      id: 'eudaimonia_vs_hedonia',
      title: 'Hedonia vs Eudaimonia 🍰🏔️',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '⚖️',
      svgIcon: 'brain',
      content: "The Ancient Greeks defined two types of happiness:\n\n1. **Hedonia:** Pleasure. Eating cake, playing a video game, relaxing. It feels great, but fades instantly. 🍰\n2. **Eudaimonia:** Meaning and fulfillment. Raising a child, writing a book, climbing a mountain. It is often difficult and painful in the moment, but provides deep, lasting satisfaction. 🏔️\n\nA happy life requires a balance of both, but modern society almost exclusively sells us 'Hedonia.' 🛒",
      highlight: "Pleasure is feeling good now. Meaning is feeling good about your life. 🕰️",
    },
    {
      id: 'the_grant_study',
      title: 'The 80-Year Harvard Study 🎓',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🎓',
      svgIcon: 'users',
      content: "In 1938, Harvard started the longest study of human life ever conducted. They tracked 724 men for 80 years to find what makes a 'good life.' \n\nThe result? It wasn't wealth, cholesterol levels, or fame.\n\n**'Good relationships keep us happier and healthier. Period.'** 🫂\n\nPeople with strong social connections lived longer, their brains stayed sharper, and they reported higher joy. Loneliness is as toxic to the body as smoking 15 cigarettes a day! 🚬",
      highlight: "The quality of your relationships determines the quality of your life. ❤️",
    },
    {
      id: 'gratitude_practice',
      title: 'The Neuroscience of Gratitude 🙏',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '🙏',
      svgIcon: 'eye',
      content: "Gratitude is not just 'fluff'—it is serious neuroscience. \n\nYour brain has a Negativity Bias; it notices bad things 3x more than good things to keep you safe. Practicing Gratitude (like writing down 3 good things a day) forces your brain to scan the world for the positive 🔍.\n\nOver time, this literally rewires your neural pathways (Neuroplasticity), making it biologically easier to feel happy and lowering Cortisol (stress) levels! 🧠✨",
      highlight: "Gratitude is weightlifting for your brain's happiness muscles. 🏋️‍♂️",
    },
    {
      id: 'impact_of_money',
      title: 'Money & Happiness 💵',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '💵',
      svgIcon: 'lock',
      content: "Does money buy happiness? Yes... but only up to a point. 📈\n\nMoney buys happiness when it lifts you out of poverty. It removes the stress of paying for food, shelter, and medicine. \n\nHowever, studies show that once your basic needs are comfortably met (around $75k - $100k a year depending on the city), extra money provides almost zero additional daily happiness. A billionaire does not laugh 1000x more than a middle-class teacher! 🧑‍🏫",
      highlight: "Money is a shield against misery, but it is not an engine for joy. 🛡️",
    },
    {
      id: 'buying_experiences',
      title: 'Experiences > Things ✈️',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '✈️',
      svgIcon: 'waves',
      content: "If you have $500, what should you buy to maximize happiness? A watch or a weekend trip? \n\nScience says: **Buy the trip.** 🏕️\n\n1. You adapt to the watch quickly (Hedonic Treadmill). \n2. The trip gives you 'Anticipation Joy' before you go.\n3. The trip connects you with others.\n4. Most importantly, experiences become part of your **Identity**. You are the sum of your memories, not the sum of your gadgets! 📸",
      highlight: "Things rust and break. Memories grow sweeter with time. 🕰️",
    },
    {
      id: 'flow_state',
      title: 'The Power of Flow 🌊',
      color: '#00D4A0',
      bgGradient: ['#001A10', '#050D0A'],
      icon: '🌊',
      svgIcon: 'grid',
      content: "Mihaly Csikszentmihalyi discovered that people are happiest not when relaxing, but when they are completely absorbed in a challenging task. He called this **Flow**. 🏄‍♂️\n\nIn Flow (doing a puzzle, coding, painting, sports), your ego vanishes. You lose track of time. Your brain is perfectly balanced between boredom (too easy) and anxiety (too hard). \n\nThe happiest people design their lives to have frequent moments of Flow. 🎨",
      highlight: "True joy is found in deep engagement, not passive entertainment. ⚡",
    },
    {
      id: 'helping_others',
      title: 'The Helper\'s High 🤝',
      color: '#FF4444',
      bgGradient: ['#1A0505', '#050D0A'],
      icon: '🤝',
      svgIcon: 'users',
      content: "From an evolutionary perspective, humans survived by cooperating. Our brains heavily reward us for helping our tribe. 🌍\n\nWhen you spend money on someone else, volunteer, or do a random act of kindness, your brain releases a massive cocktail of **Oxytocin, Dopamine, and Serotonin**, known as the 'Helper's High.' \n\nScans show the brain's reward center lights up more when GIVING a gift than when RECEIVING one! 🎁",
      highlight: "Selfishness is biologically punishing; generosity is biologically rewarding. ❤️",
    },
    {
      id: 'impact_of_sleep',
      title: 'The Foundation: Sleep 💤',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '💤',
      svgIcon: 'cloud',
      content: "You can do all the gratitude journaling in the world, but if you sleep 4 hours a night, you will be miserable. 📉\n\nSleep is when the brain flushes out toxins (the Glymphatic system) and regulates the Amygdala (the fear center). A sleep-deprived brain is hyper-reactive to negative events and 'numb' to positive ones.\n\nGetting 7-9 hours of sleep is the single most effective 'biological hack' for daily emotional stability! 🛌",
      highlight: "Sleep is the armor that protects your mental health. 🛡️",
    },
    {
      id: 'social_media_drain',
      title: 'The Social Media Drain 📱',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📱',
      svgIcon: 'shield',
      content: "As screen time increases, global happiness metrics fall. Why? \n\n1. **Upward Comparison:** We constantly compare our messy real lives to the filtered 'highlight reels' of others. \n2. **Displacement:** Time on phones takes away from time outside, time sleeping, and face-to-face interactions (which actually build Oxytocin). \n\nThe brain evolved to connect with eyes and voices, not pixels and likes. 📉",
      highlight: "Pixels cannot replace the biological need for human presence. 🫂",
    },
    {
      id: 'post_traumatic_growth',
      title: 'Post-Traumatic Growth 🌱',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '🌱',
      svgIcon: 'sparkle',
      content: "We've all heard of PTSD, but psychology also studies **PTG (Post-Traumatic Growth)**. \n\nMany people who undergo severe crises emerge with a dramatically increased appreciation for life, stronger relationships, and a deeper sense of meaning. \n\nPain shatters our 'normal' worldview, forcing us to rebuild it with better priorities. You aren't defined by your trauma; you are defined by the meaning you build from it. 🧱",
      highlight: "A broken bone often heals stronger at the break. Mindsets can too. 💪",
    },
    {
      id: 'choice_paradox',
      title: 'The Paradox of Choice 🛒',
      color: '#FF007F',
      bgGradient: ['#1A000A', '#050D0A'],
      icon: '🛒',
      svgIcon: 'lock',
      content: "We think having more options makes us happier. Science says the opposite! 🪤\n\nWhen faced with 50 types of jam at the store (or thousands of movies on Netflix), the brain gets overwhelmed. This is **Decision Fatigue**. \n\nFurthermore, when you finally pick one, you are likely to feel regret ('What if the other one was better?'). Limiting your choices actually provides freedom and peace of mind! 🎬",
      highlight: "Too much freedom is paralyzing. Constraints breed contentment. 🎛️",
    },
    {
      id: 'mind_wandering',
      title: 'A Wandering Mind is Unhappy 💭',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '💭',
      svgIcon: 'brain',
      content: "A famous Harvard study tracked people's thoughts via an app. It found that people’s minds wander 47% of the time. \n\nCrucially, it found that people were **significantly less happy** when their minds were wandering, regardless of what they were physically doing! \n\nEven if you are doing chores, focusing 100% on the chore makes you happier than dreaming about a vacation. Presence is the key to joy. 🧘‍♂️",
      highlight: "Happiness is not about being somewhere else; it's about being fully here. 📍",
    },
    {
      id: 'synthesizing_happiness',
      title: 'Synthesizing Happiness 🧪',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧪',
      svgIcon: 'flask',
      content: "Dan Gilbert showed that 'Natural Happiness' is what we get when we get what we wanted. \n\n'Synthetic Happiness' is what we make when we DON'T get what we wanted. \nPeople assume synthetic happiness is 'fake,' but brain scans show it is functionally identical! Over time, the person who didn't get the job convinces themselves it was for the best, and they become genuinely happy with the outcome. \n\nYour brain has an immune system for sadness! 🛡️💯",
      highlight: "You have the power to manufacture human joy out of thin air. ✨",
    },
  ],

  lab: {
    title: "The Joy Synthesizer 🎛️✨",
    description: "You have exactly 24 'Energy Tokens' to spend in a day. You must distribute them across different life activities: Wealth/Work 🏦, Relationships 🫂, Health/Sleep 🛌, and Entertainment/Scrolling 📱. Watch how your daily combination affects the Long-Term Happiness Meter. Can you find the perfect, science-backed balance for a fulfilled life? ⚖️",
    hint: "Maxing out 'Entertainment' gives you a temporary 'Hedonic Spike', but it decays instantly. You absolutely must hit the baseline minimums for 'Sleep' and 'Relationships' to build a solid foundation!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Oxytocin receptor density graphs, Cortisol baseline shifts, and the Hedonic Adaptation ($\\alpha$) decay rate.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why complaining literally rewires your brain to be sad? 🗣️📉",
      answer: "Neuroplasticity! When you complain, your brain neurons fire together. 'Neurons that fire together, wire together.' Compulsive complaining physically builds a highly efficient neural highway for negative thoughts, making it biologically easier to be angry than happy in the future! 🧠💥",
      emoji: '🚧',
    },
    {
      id: 'dyk2',
      question: "Do you know why anticipating a vacation is often better than the vacation itself? ✈️",
      answer: "Dopamine peaks in anticipation! The brain loves forecasting and imagining perfect scenarios. When you are on the actual trip, you have to deal with lost luggage and bad weather. The 'dream' provides a pure dopamine hit without the friction of reality! 🏖️",
      emoji: '🎢',
    },
    {
      id: 'dyk3',
      question: "Do you know why winning the lottery can actually ruin people's lives? 💰",
      answer: "The contrast effect! When you get a massive, instantaneous rush of dopamine (like 100 million dollars), the brain's receptors down-regulate to protect themselves. Suddenly, normal joys—like a sunset, a joke, or a good meal—are no longer stimulating enough to register. The brain becomes numb! 🎲",
      emoji: '📉',
    },
    {
      id: 'dyk4',
      question: "Do you know why experiences make us happier than physical possessions? 🎟️",
      answer: "We 'adapt' to our living room sofa, so we stop noticing it. But an experience (like a concert or taking a cooking class) is fleeting, so we never adapt to it. Furthermore, we edit our memories over time to forget the bad parts and amplify the good parts! 🕰️",
      emoji: '💭',
    },
    {
      id: 'dyk5',
      question: "Do you know why social connections are the biggest predictor of longevity? 🫂",
      answer: "Safety! Evolutionary biology dictates that the brain feels 'safe' from predators when surrounded by a trusted tribe. When you are lonely, the brain assumes you are vulnerable, keeping the HPA axis (Stress response) constantly active. It wears out your immune system! 🛡️",
      emoji: '🧬',
    },
    {
      id: 'dyk6',
      question: "Do you know why forcing yourself to smile when you are sad actually kinda works? 😃",
      answer: "The Facial Feedback Hypothesis! The brain monitors the muscles in your face to decide how it should feel. If you hold a pen in your teeth (forcing a smile), the brain receives the signal: 'Oh, muscles are in the smile position, I should release some Serotonin!' It's a biological two-way street. 🛣️",
      emoji: '✏️',
    },
    {
      id: 'dyk7',
      question: "Do you know why elderly people generally report being happier than 20-somethings? 👵👴",
      answer: "The 'Positivity Effect.' As people realize their time is limited, they stop investing emotional energy into things they can't control (like what strangers think of them) and exclusively invest in meaningful relationships. They prune the nonsense out of their lives! ✂️",
      emoji: '⏳',
    },
    {
      id: 'dyk8',
      question: "Do you know why you feel a 'high' after finishing a hard workout? 🏃‍♀️",
      answer: "Endorphins! Endorphins are the body's natural painkillers, released to mask the micro-tears in your muscles. They bind to the exact same neural receptors as morphine, creating a feeling of profound peace and euphoria! 💉",
      emoji: '🏋️‍♂️',
    },
    {
      id: 'dyk9',
      question: "Do you know why buying a huge, expensive house doesn't usually increase happiness? 🏡",
      answer: "The commute! Often, people buy big houses far away from the city. They adapt to the big house in 3 months, but they NEVER adapt to sitting in 2 hours of stressful traffic every single day. The daily irritation of the commute completely destroys the joy of the extra bathroom! 🚗",
      emoji: '🚦',
    },
    {
      id: 'dyk10',
      question: "Do you know why 'Awe' is considered a super-emotion? 🌌",
      answer: "When you look at the Grand Canyon or a starry sky, you feel 'Awe.' Science shows that awe dramatically temporarily shrinks the 'Ego' (the Default Mode Network in the brain). When you feel small compared to the universe, your daily anxieties literally feel smaller and less important too! 🌠",
      emoji: '🔭',
    },
  ],

  quiz: [
    { id: 'q1', question: "What psychological concept explains why lottery winners return to a normal level of happiness after a year?", options: ['The Hedonic Treadmill', 'The Placebo Effect', 'Cognitive Dissonance', 'Flow State'], answer: 0, explanation: "We rapidly adapt to new fortunes (and tragedies) and go back to our baseline! 🏃‍♂️" },
    { id: 'q2', question: "According to the 50-10-40 rule, what percentage of your happiness is determined by your daily intentional choices?", options: ['10%', '40%', '50%', '99%'], answer: 1, explanation: "You have control over a massive 40% chunk of your joy! 🎛️" },
    { id: 'q3', question: "What is the difference between Hedonia and Eudaimonia?", options: ['Hedonia is meaning, Eudaimonia is money', 'Hedonia is pleasure/fun, Eudaimonia is deep meaning/purpose', 'They are the exact same thing', 'Hedonia is bad, Eudaimonia is illegal'], answer: 1, explanation: "You need cake (Hedonia) AND a purpose (Eudaimonia) for a balanced life! ⚖️" },
    { id: 'q4', question: "According to the 80-Year Harvard Grant Study, what is the #1 predictor of human happiness and health?", options: ['Genetics', 'The quality of your relationships', 'Having over $100k salary', 'Exercising daily'], answer: 1, explanation: "Good relationships protect our brains and our bodies! 🫂" },
    { id: 'q5', question: "Why does the human brain notice an insult 3x more than a compliment?", options: ['Humans are mean', 'The Negativity Bias (evolutionary survival tactic)', 'It doesn\'t', 'Poor memory'], answer: 1, explanation: "In the wild, ignoring a compliment is fine. Ignoring a threat gets you eaten! 🦁" },
    { id: 'q6', question: "Does money buy happiness?", options: ['Never', 'Yes, limitlessly', 'Only up to the point where basic needs and security are comfortably met', 'Only for lottery winners'], answer: 2, explanation: "Money buys relief from poverty-stress, but after ~$80k, the joy curve flattens out. 💵" },
    { id: 'q7', question: "To get the most 'Happiness ROI', science suggests you should spend your spare money on:", options: ['Experiences (like trips/events)', 'Physical things (like a nicer car)', 'Designer clothes', 'Stock market only'], answer: 0, explanation: "Experiences become part of your identity and give you memories you never 'adapt' to! ✈️" },
    { id: 'q8', question: "What occurs in a 'Flow State'?", options: ['You fall asleep', 'You become totally absorbed in a challenge and lose track of time', 'You feel extreme anxiety', 'You watch TV'], answer: 1, explanation: "Flow is the sweet spot between boredom and anxiety. 🌊" },
    { id: 'q9', question: "The 'Helper\'s High' is caused by the release of which chemicals when we do something kind?", options: ['Cortisol and Adrenaline', 'Oxytocin, Dopamine, and Serotonin', 'Only Melatonin', 'Sugar'], answer: 1, explanation: "We are biologically wired to feel immense joy when we help our tribe! ❤️" },
    { id: 'q10', question: "What is considered the 'biological foundation' without which mental health regulation is nearly impossible?", options: ['Caffeine', 'Adequate Sleep (7-9 hours)', 'Vegetables', 'Meditation'], answer: 1, explanation: "Without sleep, the Amygdala goes rogue and everything feels like a threat! 🛌" },
    { id: 'q11', question: "What happens to the brain if you complain constantly?", options: ['It clears out the bad feelings', 'Neuroplasticity makes your brain highly efficient at being negative', 'Nothing', 'You get smarter'], answer: 1, explanation: "Neurons that fire together wire together. You are training your brain to be miserable! 📉" },
    { id: 'q12', question: "PTG stands for:", options: ['Pre-Traumatic Grief', 'Post-Traumatic Growth', 'Personal Time Gathering', 'Peak Training Goals'], answer: 1, explanation: "Many people emerge from tragedy with a deeper, richer appreciation for life! 🌱" },
    { id: 'q13', question: "The 'Paradox of Choice' means that having thousands of options (like on Netflix) usually makes us:", options: ['Extremely happy', 'Overwhelmed, fatigued, and regretful', 'Smarter', 'Wealthy'], answer: 1, explanation: "Too much choice paralyzes the brain! 🪤" },
    { id: 'q14', question: "A Harvard study found that people are significantly happier when:", options: ['Their minds are wandering/daydreaming', 'They are fully focused on the present moment, even doing chores', 'They are asleep', 'They are thinking about the future'], answer: 1, explanation: "A wandering mind is an unhappy mind! 🧘‍♂️" },
    { id: 'q15', question: "What is 'Synthesized Happiness'?", options: ['Joy from fake goods', 'The genuine happiness the brain manufactures when you don\'t get what you wanted', 'Lying to yourself', 'Taking medicine'], answer: 1, explanation: "Your brain's psychological immune system makes you realize 'it was for the best'! ✨" },
    { id: 'q16', question: "Why does anticipating a vacation often bring more pure joy than the trip itself?", options: ['Trips are boring', 'Dopamine peaks in anticipation, free from the friction of reality', 'You save money', 'The brain hates traveling'], answer: 1, explanation: "The 'dream' of the trip is mathematically perfect. Reality has lost luggage. 🎢" },
    { id: 'q17', question: "What is the evolutionary purpose of loneliness feeling physically painful?", options: ['To punish bad people', 'To signal that you are separated from the tribe and vulnerable to predators', 'To help you sleep', 'No purpose'], answer: 1, explanation: "The pain of exclusion is a biological alarm telling you to get back to the group! 🐺" },
    { id: 'q18', question: "Elderly people are generally happier than young adults mostly because of the 'Positivity Effect', which means:", options: ['They have more money', 'They realize time is short and only invest in meaningful, positive things', 'They forget the bad', 'They don\'t work'], answer: 1, explanation: "They prune the nonsense and drama out of their lives! ✂️" },
    { id: 'q19', question: "Buying a large house with a 2-hour daily commute often decreases happiness because:", options: ['Houses are ugly', 'You adapt to the house, but you never adapt to the unpredictable stress of traffic', 'Gas is expensive', 'You get lost'], answer: 1, explanation: "Traffic is a daily, un-adaptable micro-trauma! 🚗" },
    { id: 'q20', question: "Feeling extreme 'Awe' (like looking at stars) increases well-being by:", options: ['Making you sleepy', 'Temporarily shrinking the ego/Default Mode Network, making your problems feel smaller', 'Improving eyesight', 'Warming you up'], answer: 1, explanation: "Awe gives your anxious ego a much-needed break! 🌌" },
  ],

  relatedTopics: ['social_media_trap', 'emotions_motivation', 'meaningful_life'],
};
