// ─────────────────────────────────────────────────────────
//  TOPIC: GREATEST PHILOSOPHERS
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'greatest_philosophers',
  title: 'Greatest Philosophers',
  subtitle: 'The Titans of Human Thought 🏛️📜',
  emoji: '🏛️',
  category: 'Philosophy',
  accentKey: 'greatest_philosophers',

  hook: {
    question: "Imagine being so smart that your ideas shape the laws, religions, and governments of the entire planet for the next 2,000 years. Who were these people?",
    reveal: "They were the **Philosophers**. Before there was Google, before modern science, and before psychology, there were just people sitting in the dirt, asking dangerously deep questions.\n\nFrom a Greek man who annoyed people so much they executed him, to a French guy who doubted his own existence, these are the heavyweights of human history. Their ideas are the hidden operating system running in your brain right now. Let's meet the Titans. 🧠⚡",
    emoji: '⚡',
  },

  theory: [
    {
      id: 'the_big_three_greeks',
      title: "The Big Three 🇬🇷",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'users',
      svgIcon: 'star',
      content: "Western philosophy fundamentally starts with a lineage of three Greek teachers in Athens, living around 400 BC.\n**Socrates** taught **Plato**. \n**Plato** taught **Aristotle**. \n**Aristotle** taught Alexander the Great.\nThese three men effectively invented the rules of logic, ethics, and science that the entire Western world is built upon.",
      highlight: "Everything written since is just footnotes to Plato. (Alfred North Whitehead) 🏛️",
    },
    {
      id: 'socrates',
      title: "Socrates (The Gadfly) 🪰",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'help-circle',
      svgIcon: 'flame',
      content: "Socrates (470–399 BC) never wrote a single book. He just walked around Athens asking powerful people annoying, probing questions until they realized they knew nothing.\nHe called himself a 'gadfly' stinging the lazy horse of Athens into waking up.\nHis core philosophy: *'I know that I know nothing.'* Recognizing your own ignorance is the first step to wisdom.",
      highlight: "He annoyed the government so much they executed him with poisoned hemlock for 'corrupting the youth'. ☠️",
    },
    {
      id: 'plato',
      title: "Plato: The Allegory of the Cave 🕯️",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'eye',
      svgIcon: 'eye',
      content: "Plato (Socrates' student) believed the physical world is just a set of cheap, fake copies of a perfect, invisible realm called the 'World of Forms'.\nIn his **Allegory of the Cave**, he imagined prisoners chained in a dark cave, staring at shadows on a wall. They think the shadows are 'reality'.\nThe philosopher is the one who breaks the chains, walks outside into the sunlight, and sees the true nature of reality.",
      highlight: "Most people are completely content staring at shadows. Don't be most people. 🧗",
    },
    {
      id: 'aristotle',
      title: "Aristotle: The First Scientist 🔭",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'aperture',
      svgIcon: 'activity',
      content: "While Plato stared at the heavens, Aristotle pointed at the dirt.\nHe rejected the 'invisible world' and believed truth is found by observing the physical world right in front of you. He essentially invented biology, physics, and formalized logic.\nFor ethics, he believed in the **Golden Mean**—virtue is the perfect balance between two extremes (e.g., Courage is perfectly balanced between Cowardice and Recklessness).",
      highlight: "We are what we repeatedly do. Excellence, then, is not an act, but a habit. 🧬",
    },
    {
      id: 'rene_descartes',
      title: "Descartes: I Think Therefore I Am 🧠",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'cpu',
      svgIcon: 'target',
      content: "Fast forward to 1637. French philosopher René Descartes decided to delete everything he knew and start from zero. \nHe asked: *'How do I know I'm not in a simulation run by an Evil Demon? How do I know anything is real?'*\nHe realized he could doubt everything EXCEPT the fact that he was doubting. \n**Cogito, ergo sum** ('I think, therefore I am'). Because he is thinking, he must exist.",
      highlight: "Doubt everything until you reach a truth that is impossible to doubt. 🛡️",
    },
    {
      id: 'machiavelli',
      title: "Machiavelli: The Dark Prince 👑",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'moon',
      svgIcon: 'lock',
      content: "Niccolò Machiavelli wrote *The Prince* (1513) as a brutal, practical guide on how to get and keep political power.\nBefore him, philosophers said leaders should be 'good' and 'virtuous'. \nMachiavelli said: Being 'good' will get you killed. A leader must learn how to be cruel, deceptive, and feared, because humans are naturally selfish and treacherous. *'It is better to be feared than loved.'*",
      highlight: "He divorced ethics from politics. The ends justify the means. 🗡️",
    },
    {
      id: 'immanuel_kant',
      title: "Kant: The Categorical Imperative ⚖️",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'sliders',
      svgIcon: 'users',
      content: "Immanuel Kant (1724–1804) wanted to create a universal rule for morality that didn't rely on religion.\nHe invented the **Categorical Imperative**: *'Act only according to that maxim whereby you can, at the same time, will that it should become a universal law.'*\nSimply: Before you steal, ask 'What if EVERYONE in the world stole?'. Society would collapse. Therefore, stealing is objectively wrong. No exceptions.",
      highlight: "Never treat a human being merely as a 'means to an end'. 🚫",
    },
    {
      id: 'baruch_spinoza',
      title: "Spinoza: God is Nature 🌿",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'globe',
      svgIcon: 'cloud',
      content: "Baruch Spinoza (1632–1677) was excommunicated by his religious community for a radical idea.\nHe argued that God is not a bearded man in the sky making choices. Instead, **God is the universe itself** (Pantheism).\nTo Spinoza, the laws of physics, the stars, and the trees *are* God. Therefore, praying for miracles is foolish because the universe operates on strict, unbreakable mathematical necessity.",
      highlight: "Albert Einstein famously said, 'I believe in Spinoza's God.' ⚛️",
    },
    {
      id: 'arthur_schopenhauer',
      title: "Schopenhauer: The King of Pessimism 🌧️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'cloud-drizzle',
      svgIcon: 'frown',
      content: "Arthur Schopenhauer (1788–1860) believed the universe is driven by a blind, irrational, endless force he called **The Will**.\nThe Will constantly makes us desire things (food, money, love). Once we get them, we get bored. If we don't get them, we are in pain.\n*'Life swings like a pendulum backward and forward between pain and boredom.'* He believed the only escape was asceticism (giving up desires) and enjoying Art.",
      highlight: "Desire is suffering. (He was heavily influenced by Buddhism). 🧘‍♂️",
    },
    {
      id: 'friedrich_nietzsche',
      title: "Nietzsche: The Hammer 🔨",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'zap',
      svgIcon: 'zap',
      content: "Friedrich Nietzsche (1844–1900) wrote philosophy with a hammer, smashing every existing societal value.\nHe declared **'God is Dead'**—warning that science had eroded religious morality, paving the way for Nihilism.\nHis solution was the **Übermensch** (Superman): a human who rejects the weak 'slave morality' of society, embraces the chaos of the world, and aggressively creates their own values through the 'Will to Power'.",
      highlight: "What does not kill me makes me stronger. 💪",
    },
    {
      id: 'karl_marx',
      title: "Karl Marx: Class Struggle ☭",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'users',
      svgIcon: 'activity',
      content: "Karl Marx (1818–1883) didn't just want to think about the world; he wanted to overthrow it. \n*The philosophers have only interpreted the world; the point is to change it.*\nHe argued that all of human history is driven by **Class Struggle** (the rich owners vs the poor workers). In capitalism, the workers (Proletariat) are exploited. He predicted they would violently rise up to create a classless, communist society.",
      highlight: "Workers of the world, unite! You have nothing to lose but your chains. ⛓️",
    },
    {
      id: 'thomas_hobbes',
      title: "Hobbes: The Leviathan 🐉",
      color: '#795548',
      bgGradient: ['#1A100A', '#0A0502'],
      icon: 'shield',
      svgIcon: 'lock',
      content: "Thomas Hobbes (1588–1679) had a horribly negative view of human nature. \nHe argued that the natural state of humanity is a 'war of all against all' where life is *'nasty, brutish, and short.'*\nTo avoid murdering each other, humans must agree to hand over all their rights to an absolute, terrifying dictator (The Leviathan) who will force them to behave in exchange for safety.",
      highlight: "We trade our freedom for the guarantee that we won't be murdered in our sleep. 🗡️",
    },
    {
      id: 'david_hume',
      title: "Hume: The Skeptic 🤷",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'help-circle',
      svgIcon: 'eye',
      content: "David Hume (1711–1776) famously woke Kant up from his 'dogmatic slumber'.\nHume was a radical empiricist. He argued that we cannot actually *prove* cause and effect. Just because the sun rose yesterday, doesn't logically prove it will rise tomorrow. \nHe also argued that *'Reason is, and ought only to be the slave of the passions.'* Meaning: Logic doesn't drive humans; emotions do.",
      highlight: "We are feeling machines that think, not thinking machines that feel. 💖",
    },
    {
      id: 'ludwig_wittgenstein',
      title: "Wittgenstein: The Language Trap 🗣️",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'message-circle',
      svgIcon: 'target',
      content: "Ludwig Wittgenstein (1889–1951) was a 20th-century genius who argued that almost ALL philosophical problems are actually just confusions about language.\n*The limits of my language mean the limits of my world.*\nHe compared language to a 'game' with specific rules. If we use a word in the wrong 'game', we create imaginary problems. He basically told philosophers to shut up about things they can't clearly define.",
      highlight: "Whereof one cannot speak, thereof one must be silent. 🤐",
    },
    {
      id: 'conclusion',
      title: "The Great Conversation 🗨️",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'award',
      svgIcon: 'star',
      content: "Philosophy is not a dead subject. It is a 2,500-year-old conversation where each thinker reads the previous one and says, 'You are wrong, and here is why.'\nBy studying them, you don't have to reinvent the wheel. You get to stand on the shoulders of giants.\nThe Matrix, modern democracy, AI ethics, and capitalism are all just echoes of these ancient conversations.",
      highlight: "You are the newest participant in the Great Conversation. What is your philosophy? 🎤",
    },
  ],

  lab: {
    title: "The Quote Decoder 💬🕵️‍♂️",
    description: "You have entered the Hall of Titans. Anonymous philosophical quotes will appear. You must use your knowledge of their core ideologies to match the quote to the correct philosopher. Is it optimistic, pessimistic, logical, or rebellious?",
    hint: "Identify the tone. Strict rules = Kant. Pessimism = Schopenhauer. Power = Machiavelli or Nietzsche. Logic/Observation = Aristotle.",
    scientistModeHint: "Attribution Mode 🧑‍🔬: Analyze the dialectic phrasing. Mentions of 'Will', 'Class', or 'Categorical' are direct giveaways.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why did Socrates hate democracy?", answer: "Socrates famously compared society to a ship. Would you randomly select passengers to sail the ship, or would you hire an educated, trained captain? He believed that letting uneducated, easily manipulated people vote on complex political issues would inevitably lead to disaster and demagogues. Athens proved him right by democratically voting to execute him. 🚢", emoji: '🗳️' },
    { id: 'dyk2', question: "Why is 'The Matrix' fundamentally based on Descartes and Plato?", answer: "Plato's 'Allegory of the Cave' asks: What if your entire reality is just shadows on a wall? Thousands of years later, Descartes asked: What if an Evil Demon is tricking my senses to simulate reality? 'The Matrix' just modernized these exact questions, swapping the 'Evil Demon' for AI machines and 'shadows' for computer code. 💻", emoji: '💊' },
    { id: 'dyk3', question: "Did Machiavelli really believe you should be evil?", answer: "No. He believed a leader's ONLY moral obligation is to protect the State and keep it stable. If being 'good' causes the State to collapse in war, then you are a bad leader. Therefore, doing 'evil' things (like lying or executions) to maintain peace is actually a political virtue. He called it 'Realpolitik'. 🗡️", emoji: '⚖️' },
    { id: 'dyk4', question: "Why does Kant's 'Categorical Imperative' ban lying, even to save a life?", answer: "Kant believed moral rules must be absolute, or they are useless. If you lie to a murderer to save your friend, you are validating 'lying' for the universe. Kant argued you must always tell the truth, and whatever happens after that is the murderer's moral responsibility, not yours. (Many people think this is too extreme). 🗣️", emoji: '🛑' },
    { id: 'dyk5', question: "Why did Schopenhauer think Music was the highest art form?", answer: "He believed everything in the universe was a manifestation of the painful, irrational 'Will'. But while paintings and poems represent *things* in the world, Music directly represents the 'Will' itself, independent of the physical world. Listening to music provides a temporary, magical escape from human suffering. 🎵", emoji: '🎹' },
  ],

  quiz: [
    { id: 'q1', question: "Who are 'The Big Three' Greek philosophers in chronological order?", options: ['Socrates, Plato, Aristotle', 'Aristotle, Socrates, Plato', 'Plato, Kant, Marx', 'Homer, Socrates, Descartes'], answer: 0, explanation: "Socrates taught Plato, who taught Aristotle. 🇬🇷" },
    { id: 'q2', question: "What was Socrates' famous realization about wisdom?", options: ['He knew everything', '\'I know that I know nothing.\'', 'Math is the only truth', 'Books are useless'], answer: 1, explanation: "Recognizing your own ignorance is the first step to wisdom. 🪰" },
    { id: 'q3', question: "In Plato's 'Allegory of the Cave', what do the shadows on the wall represent?", options: ['Movie theaters', 'The fake, physical reality that most humans mistake for the ultimate truth', 'Gods', 'Animals'], answer: 1, explanation: "The philosopher breaks the chains to see the true Sun outside. 🕯️" },
    { id: 'q4', question: "Which philosopher is considered the 'First Scientist' because he focused on observing physical reality?", options: ['Plato', 'Aristotle', 'Socrates', 'Nietzsche'], answer: 1, explanation: "He rejected Plato's invisible 'World of Forms' and looked at the dirt. 🔭" },
    { id: 'q5', question: "What does Descartes' phrase 'Cogito, ergo sum' mean?", options: ['I think, therefore I am', 'To be or not to be', 'God is dead', 'Knowledge is power'], answer: 0, explanation: "He could doubt everything except the fact that he was doubting. 🧠" },
    { id: 'q6', question: "According to Machiavelli's *The Prince*, is it better for a leader to be loved or feared?", options: ['Loved, because love lasts forever', 'Feared, because people are selfish and will betray you when it is profitable, but fear keeps them in line', 'Neither', 'Both equally'], answer: 1, explanation: "The ends justify the means. 👑" },
    { id: 'q7', question: "What is Immanuel Kant's 'Categorical Imperative'?", options: ['A military strategy', 'A rule saying you should only take actions that you would want everyone else in the world to take (a universal law)', 'A grammar rule', 'A type of diet'], answer: 1, explanation: "If everyone stealing makes society collapse, then stealing is always wrong. ⚖️" },
    { id: 'q8', question: "What did Baruch Spinoza believe about God?", options: ['God hates us', 'God is the universe itself (Pantheism); the laws of physics and nature are God', 'There are multiple gods', 'God does not exist'], answer: 1, explanation: "Einstein famously believed in Spinoza's God. 🌿" },
    { id: 'q9', question: "Which philosopher is known as the 'King of Pessimism'?", options: ['Karl Marx', 'Arthur Schopenhauer, who believed life swings like a pendulum between pain and boredom', 'Thomas Hobbes', 'David Hume'], answer: 1, explanation: "He believed the universe was driven by a blind, irrational 'Will'. 🌧️" },
    { id: 'q10', question: "Who famously declared that 'God is Dead'?", options: ['Kant', 'Friedrich Nietzsche', 'Aristotle', 'Descartes'], answer: 1, explanation: "He warned that science had destroyed the moral foundation of society. 🔨" },
    { id: 'q11', question: "What did Karl Marx believe was the driving force of all human history?", options: ['Religion', 'Class Struggle (the war between the rich owners and the exploited workers)', 'Geography', 'Random luck'], answer: 1, explanation: "Workers of the world, unite! ☭" },
    { id: 'q12', question: "According to Thomas Hobbes in *Leviathan*, what is the natural state of humanity?", options: ['Peaceful and loving', 'A \'war of all against all\' where life is nasty, brutish, and short', 'Democratic', 'A magical garden'], answer: 1, explanation: "He believed we need a terrifying dictator to force us to behave. 🐉" },
    { id: 'q13', question: "What did David Hume mean by 'Reason is the slave of the passions'?", options: ['Smart people are emotional', 'Human behavior is ultimately driven by emotions and desires, not by cold logic', 'We should not go to school', 'Robots will take over'], answer: 1, explanation: "We are feeling machines that think. 🤷" },
    { id: 'q14', question: "What did Ludwig Wittgenstein believe about philosophical problems?", options: ['They are too hard to solve', 'Almost all of them are actually just confusions about language and playing the wrong \'language games\'', 'They require math', 'Only priests can solve them'], answer: 1, explanation: "Whereof one cannot speak, thereof one must be silent. 🗣️" },
    { id: 'q15', question: "What did Nietzsche mean by the 'Übermensch' (Superman)?", options: ['A comic character', 'A future human who rejects society\'s weak morals and aggressively creates their own values out of the chaos', 'A king', 'A perfect athlete'], answer: 1, explanation: "The cure for Nihilism. 🦸‍♂️" },
    { id: 'q16', question: "Aristotle's concept of 'The Golden Mean' suggests that virtue is:", options: ['Having a lot of gold', 'The perfect balance between two extremes (e.g., courage is between cowardice and recklessness)', 'Being mean to people', 'Only doing half a job'], answer: 1, explanation: "Excellence is a habit of balance. 🧬" },
    { id: 'q17', question: "Why did Socrates hate the idea of Democracy?", options: ['He wanted to be king', 'He believed letting uneducated people vote on complex issues was like letting passengers steer a ship instead of a trained captain', 'He hated crowds', 'He didn\'t believe in laws'], answer: 1, explanation: "Athens proved him right by democratically voting to kill him. 🚢" },
    { id: 'q18', question: "According to Marx, in capitalism, who is being exploited?", options: ['The kings', 'The Proletariat (the working class)', 'The bourgeoisie (owners)', 'The computers'], answer: 1, explanation: "He believed the workers produce the value, but the owners steal the profit. ☭" },
    { id: 'q19', question: "If a leader lies to their citizens to prevent a civil war, which philosopher would most strongly AGREE with this tactic?", options: ['Immanuel Kant', 'Niccolò Machiavelli', 'Socrates', 'Schopenhauer'], answer: 1, explanation: "The ends (preventing war) justify the means (lying). 👑" },
    { id: 'q20', question: "Which philosopher inspired the concept of 'The Matrix' simulation?", options: ['Marx', 'Descartes (by worrying an Evil Demon was tricking his senses)', 'Hobbes', 'Voltaire'], answer: 1, explanation: "Doubt everything until you reach something impossible to doubt. 💻" },
  ],

  relatedTopics: ['stoicism', 'existentialism', 'enlightenment'],
};
