export default {
  id: 'light_optics',
  title: 'Light & Optics',
  subtitle: 'The ultimate speed limit of the universe 💡',
  emoji: '💡',
  category: 'Foundations',
  accentKey: 'light',

  hook: {
    question: "Did you know that when you look at the stars at night, you are actually time-travelling? ⏳",
    reveal: "Light takes time to travel through space! The light from our Sun takes 8 minutes to reach Earth. The light from the nearest star takes 4 years. If a star 1,000 light-years away exploded today, the human race wouldn't know for a thousand years. Light is not just illumination; it is the fundamental information carrier of the entire universe! 🚀",
    emoji: '🔭',
  },

  theory: [
    { id: '1', title: 'What is Light?', color: '#FF6B9D', bgGradient: ['#2A0A15', '#05050A'], icon: '☀️', svgIcon: 'lightbulb', content: "Light is a form of **electromagnetic radiation** that human eyes can naturally detect. It travels incredibly fast: exactly **299,792,458 meters per second** in a vacuum! It's composed of tiny packets of pure energy called **photons**, which possess zero rest mass.\n\nPhotons are technically the basic unit that makes up all light. Albert Einstein proved that light behaves as both a wave and a particle simultaneously (Wave-Particle Duality).", highlight: "Light travels so fast it could circle the entire Earth 7.5 times in one single second! ⚡" },
    { id: '2', title: 'The Electromagnetic Spectrum', color: '#00D4FF', bgGradient: ['#001A2A', '#05050A'], icon: '🌈', svgIcon: 'grid', content: "**Visible light** is just an incredibly tiny sliver of the full true electromagnetic spectrum.\n\nThe spectrum ranges from colossal **Radio Waves** (which can be kilometers long), down to Microwaves, Infrared, Visible Light, Ultraviolet, X-Rays, and finally ultra-high energy **Gamma Rays** (smaller than an atom).\n\nThey all travel at the exact same speed of light, but they have radically different *frequencies* and energy levels.", highlight: "Your WiFi uses microwaves, while your eyes use visible light. It's the exact same 'stuff', just vibrating at different speeds! 📡" },
    { id: '3', title: 'Reflection Mechanics', color: '#39FF14', bgGradient: ['#0A2A0A', '#05050A'], icon: '🪞', svgIcon: 'sparkle', content: "Reflection occurs when photons bounce off a surface. The **Law of Reflection** states that the angle of incidence (incoming angle) perfectly equals the angle of reflection (bouncing angle).\n\nIf the surface is perfectly smooth (like a silver mirror), you get **specular reflection**, which preserves the image. If the surface is rough at a microscopic level (like paper), the light scatters in every direction, which is called **diffuse reflection**.", highlight: "Without diffuse reflection, you wouldn't be able to see non-glowing objects like tables, chairs, or other people! 🥸" },
    { id: '4', title: 'Refraction & Speed Limits', color: '#FFB347', bgGradient: ['#2A1A00', '#05050A'], icon: '💎', svgIcon: 'planet', content: "**Refraction** is the bending of a light beam as it passes from one transparent medium (like air) into another (like glass or water).\n\nWhy does it bend? Because light actually **slows down** when entering a denser material! In water, light travels at only 225,000 km/s. In a diamond, it plummets to 124,000 km/s. When the light beam hits the new material at an angle, the side of the beam that hits first slows down first, causing the whole beam to pivot and bend.", highlight: "Refraction is what makes a straw look broken in a glass of water, and it's how the soft gel lenses in your eyes focus light! 👁️" },
    { id: '5', title: 'Total Internal Reflection', color: '#A855F7', bgGradient: ['#1A0A2A', '#05050A'], icon: '🌐', svgIcon: 'link', content: "When light tries to move from a denser medium (glass) to a less dense one (air) at a very steep angle, it hits a boundary called the **critical angle**. Beyond this angle, the light beam bends so severely that it cannot escape at all—it gets 100% reflected back inside!\n\nThis phenomenon perfectly traps the light, allowing it to bounce endlessly down a glass tube without losing energy.", highlight: "Total Internal Reflection is the optical trick that makes fiber-optic internet possible, shooting lasers across ocean floors! 💻" },
    { id: '6', title: 'Dispersion & Prisms', color: '#FFD166', bgGradient: ['#2A2A00', '#05050A'], icon: '🔼', svgIcon: 'cube', content: "White light is actually a chaotic mixture of **all colors** in the visible spectrum. \n\nBecause different colors have different wavelengths, they bend by different amounts when refracted. Violet light (short wavelength) bends the most, while Red light (long wavelength) bends the least. When white light hits a triangular glass **prism**, this varying bending splits the beam entirely, fanning it out into a beautiful rainbow. This is called **Dispersion**.", highlight: "Isaac Newton was the first to realize that white light isn't pure, but is actively composed of every colour of the rainbow! 🎨" },
    { id: '7', title: 'Diffraction: Bending Around Corners', color: '#4FC9C0', bgGradient: ['#0A2A2A', '#05050A'], icon: '〰️', svgIcon: 'waves', content: "**Diffraction** is the slight bending of light as it passes around the edge of an object or through a tiny slit. \n\nBecause light travels as a wave, when it hits a small hole, the wave 'bulges' outward on the other side, spreading into the shadow region. This proves conclusively that light is a wave! The size of the hole must be similar to the wavelength of the light for this to be highly noticeable.", highlight: "Diffraction is why you can hear someone speaking around a corner, but you cannot see them! 🔊" },
    { id: '8', title: 'Absorption & Color', color: '#FF3131', bgGradient: ['#2A000A', '#05050A'], icon: '🍎', svgIcon: 'target', content: "Why is an apple red? It's not actually generating red light!\n\nWhen white sunlight hits an object, the object's chemical structure **absorbs** certain wavelengths of light and **reflects** others. An apple absorbs all the blue, green, and yellow photons, converting their energy into heat. It ONLY reflects the red photons back into your eye. \n\nTherefore, black objects absorb almost all light (getting very hot), while white objects reflect almost all light.", highlight: "Things don't 'have' color. Their color is just the specific wavelength of light they reject and bounce into your eyeballs! 👁️" },
    { id: '9', title: 'The Doppler Effect for Light', color: '#6C5CE7', bgGradient: ['#1A0A2A', '#05050A'], icon: '🚨', svgIcon: 'lightning', content: "Just like the pitch of an ambulance siren drops as it speeds away from you, light also changes depending on how fast its source is moving!\n\nIf a star is flying away from Earth at massive speeds, its light waves get stretched out. Stretched waves look redder to our eyes, an effect called **Redshift**. If it's flying toward us, the waves get compressed, looking bluer (**Blueshift**).", highlight: "Redshift is how Edwin Hubble proved the entire universe is expanding—almost every galaxy we look at is visibly stretched 'red'! 🌌" },
    { id: '10', title: 'Polarization', color: '#55EFC4', bgGradient: ['#0A2A1A', '#05050A'], icon: '😎', svgIcon: 'shield', content: "Light waves usually vibrate in all possible directions. But a **Polarizing filter** is like a microscopic picket fence—it blocks all light waves except those vibrating on one specific geometric axis.\n\nSince glare reflecting off water or roads is mostly horizontally polarized, sunglasses with vertically polarized filters block the glare completely while letting normal scattered light through!", highlight: "3D cinema glasses use two different polarization filters—one for your left eye, one for your right—to feed you two separate images! 👓" }
  ],

  lab: {
    title: "Optical Bench Simulator 🔭",
    description: "Welcome to the Optical Physics Engine. Take control of a high-powered laser, a glass prism, and diverse atmospheric mediums. Your objective is to mathematically manipulate the angle of incidence to discover Total Internal Reflection.",
    hint: "If the Prism's angle of incidence exactly reaches the glass critical barrier of 42 degrees, a mathematical event occurs.",
    scientistModeHint: "Scientist Mode reveals exact Snell's Law matrices (n₁sinθ1) and photon component trajectories.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why the sky is blue? 🟦", answer: "It's due to an atomic effect called Rayleigh scattering! Gas molecules in Earth's atmosphere scatter short-wavelength light (blue and violet) much more aggressively than long-wavelength light (red). While there is violet light scattering, human eyes are vastly more sensitive to blue, so the sky looks brilliant blue!", emoji: '☁️' },
    { id: 'dyk2', question: "Do you know why sunsets are brilliant red and orange? 🌅", answer: "When the Sun is low on the horizon, its light has to pass through significantly more of Earth's atmosphere to reach your eyes. By the time it reaches you, almost all the blue and green light has already been scattered away, leaving only the long-wavelength reds and oranges to pierce through the thick air!", emoji: '🌇' },
    { id: 'dyk3', question: "Do you know why a diamond sparkles so much? 💎", answer: "Diamonds have an incredibly high 'refractive index', meaning light slows down drastically when entering them, bending sharply. Combined with precise, brilliant geometric cuts from jewelers, light enters the diamond and undergoes massive Total Internal Reflection, bouncing around inside the crystal multiple times before finally escaping into your eye!", emoji: '✨' },
    { id: 'dyk4', question: "Do you know why a mirage looks like water on a hot desert road? 🏜️", answer: "The extreme heat from the asphalt drastically heats up the air touching it. Hot air is less dense than cold air. When sunlight travels from the dense cool air above into the thin hot air below, it refracts (bends) upward in a U-shape right into your eyes. You are actually looking at a refracted image of the blue sky, which your brain misinterprets as a puddle of water!", emoji: '🥵' },
    { id: 'dyk5', question: "Do you know why infrared cameras can essentially see in the dark? 🦉", answer: "Every object that has heat emits electromagnetic radiation. Humans emit a frequency of light located in the 'Infrared' spectrum. We can't see it naturally, but specialized night-vision sensors can catch these thermal photons, allowing them to map out body heat even when there is absolutely zero visible light in the room!", emoji: '🔥' }
  ],

  quiz: [
    { id: 'q1', question: "What is the approximate speed of light in a perfect vacuum?", options: ['343 meters per second', '3,000 kilometers per second', '299,792 kilometers per second', 'It is utterly infinite'], answer: 2, explanation: "Light travels at exactly 299,792,458 meters per second in a vacuum, completely acting as the absolute upper speed limit for any information in the universe." },
    { id: 'q2', question: "Which primary color of visible light has the longest wavelength?", options: ['Red', 'Yellow', 'Green', 'Violet'], answer: 0, explanation: "Red has the longest wavelength (lowest energy) of visible light, while violet has the shortest wavelength (highest energy)." },
    { id: 'q3', question: "What fundamental physical phenomenon makes fiber-optic internet cables work?", options: ['Diffraction', 'Diffuse Reflection', 'Total Internal Reflection', 'Atomic Dispersion'], answer: 2, explanation: "Total Internal Reflection! Because the angle is steeper than the critical angle, laser light cannot escape the glass tube and bounces perfectly down the fiber." },
    { id: 'q4', question: "Which electromagnetic wave possesses the highest energy and shortest wavelength?", options: ['Microwaves', 'Ultraviolet', 'X-Rays', 'Gamma Rays'], answer: 3, explanation: "Gamma rays are the most energetic form of light, produced by supernovae and black holes." },
    { id: 'q5', question: "If a green leaf absorbs blue and red light, what happens to the green light?", options: ['It is destroyed', 'It is converted into heat', 'It is reflected backwards', 'It diffracts through the stem'], answer: 2, explanation: "A green leaf reflects green light back into your eye, while aggressively absorbing the blue and red photons to power photosynthesis." },
    { id: 'q6', question: "What happens to the speed of light when it transitions from air into solid glass?", options: ['It accelerates', 'It remains perfectly constant', 'It slows down', 'It shatters into smaller photons'], answer: 2, explanation: "Light fundamentally slows down in denser mediums. In typical glass, its speed drops from 300,000 km/s to around 200,000 km/s, which causes the beam to bend (refract)." },
    { id: 'q7', question: "What process splits white light into a rainbow fan when passing through a prism?", options: ['Dispersion', 'Polarization', 'Interference', 'Combustion'], answer: 0, explanation: "Dispersion is the separation of white light into colors, resulting from the fact that different colours bend by varying amounts." },
    { id: 'q8', question: "Why do polarized sunglasses heavily reduce road glare?", options: ['They tint all light darker', 'They completely block horizontally oscillating light waves', 'They absorb UV radiation only', 'They refract scattered photons downwards'], answer: 1, explanation: "Glare off roads and water is intensely horizontally polarized. Sunglasses use vertical polarization filters, acting like a fence that completely blocks the horizontal glare." },
    { id: 'q9', question: "The slight bending of light as it passes tightly around a physical corner is known as:", options: ['Refraction', 'Reflection', 'Diffraction', 'Total Internal Reflection'], answer: 2, explanation: "Diffraction occurs when a wave hits an obstacle or a narrow slit, causing the wavefront to slightly bend around the physical barrier." },
    { id: 'q10', question: "If a distant galaxy is flying wildly away from Earth, its light waves stretch. What is this called?", options: ['Blueshift', 'The Doppler Effect (Redshift)', 'Wavelength Compression', 'Diffraction Spikes'], answer: 1, explanation: "Redshift! Because the source is speeding away, the light waves are stretched, moving them toward the longer, red end of the spectrum." },
    { id: 'q11', question: "Which Law states 'The angle of incidence strictly equals the angle of reflection'?", options: ["Snell's Law", "Newton's First Law", "The Law of Reflection", "The Inverse Square Law"], answer: 2, explanation: "The Law of Reflection simply dictates that whatever angle a ray of light hits a flat mirror, it will perfectly bounce away at that exact identical angle." },
    { id: 'q12', question: "The specific angle at which refracted light cannot escape and undergoes Total Internal Reflection is called:", options: ['The Optimal Angle', 'The Brewster Angle', 'The Apex', 'The Critical Angle'], answer: 3, explanation: "The Critical Angle is the precise geometric barrier. Any angle steeper than this causes the light to be entirely trapped inside the denser medium." },
    { id: 'q13', question: "Photons, the fundamental particle of light, have how much mass?", options: ['Extremely heavy mass', 'The mass of a neutron', 'Exactly Zero rest mass', 'Negative mass'], answer: 2, explanation: "Photons have absolutely zero rest mass, allowing them to permanently travel at the ultimate speed limit of the cosmos without requiring infinite kinetic energy." },
    { id: 'q14', question: "What type of reflection occurs when light scatters perfectly cleanly off a flat silver mirror?", options: ['Diffuse Reflection', 'Specular Reflection', 'Total Internal Reflection', 'Refractive Reflection'], answer: 1, explanation: "Specular reflection bounces rays perfectly in parallel, retaining a crystal clear image of whatever it reflected." },
    { id: 'q15', question: "Your bones absorb this type of light while your skin lets it pass through, allowing doctors to image your skeleton:", options: ['Infrared', 'Ultraviolet', 'Microwaves', 'X-Rays'], answer: 3, explanation: "X-Rays possess such high energy that they slice straight through soft tissue, but are blocked by the dense calcium composing your physical bones." },
    { id: 'q16', question: "Which property directly determines the 'Pitch/Color' of the electromagnetic wave?", options: ['Amplitude', 'Frequency (Wavelength)', 'Speed', 'Polarization'], answer: 1, explanation: "Frequency—the number of waves arriving per second—determines the exact color of the light or the pitch of the sound!" },
    { id: 'q17', question: "Who famously proved that white light is a compound of all colours using a glass prism?", options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'], answer: 1, explanation: "Isaac Newton essentially founded the science of optics when he experimentally split a sunbeam with a prism, proving white light was not a pure element." },
    { id: 'q18', question: "If you see a completely black car getting exceptionally hot in the sun, this is because it is:", options: ['Reflecting all wavelengths', 'Refracting the heat', 'Absorbing all visible wavelengths', 'Generating internal kinetic force'], answer: 2, explanation: "Black surfaces absorb nearly all incoming visible light, transforming that massive electromagnetic energy directly into intense thermal heat." },
    { id: 'q19', question: "What do we call a material where light passes through but is heavily scattered, preventing clear images?", options: ['Transparent', 'Opaque', 'Translucent', 'Luminous'], answer: 2, explanation: "Translucent materials (like frosted glass or wax paper) let light energy through, but scatter the photons so thoroughly you cannot see detailed structures behind them." },
    { id: 'q20', question: "Which of these forces can heavily bend a beam of light in a vacuum?", options: ['Magnetic fields', 'Electric currents', 'Extreme Gravity', 'Absolute zero cold'], answer: 2, explanation: "According to Einstein's General Relativity, massive gravity (like a Black Hole) warps spacetime itself, fundamentally curving the path of photons." }
  ],

  relatedTopics: ['waves_sound', 'heat_temperature'],
};
