// ─────────────────────────────────────────────────────────
//  TOPIC: ETHICS & MORALITY
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'ethics_morality',
  title: 'Ethics & Morality',
  subtitle: 'How to be Good without God ⚖️🤔',
  emoji: '⚖️',
  category: 'Philosophy',
  accentKey: 'ethics_morality',

  hook: {
    question: "A runaway trolley is about to kill 5 tied-up workers. You can pull a lever to divert it onto another track, but there is 1 tied-up worker there. Do you pull the lever and kill 1 to save 5?",
    reveal: "Almost everyone says YES. But wait... what if you are a surgeon with 5 dying patients who need organs? Can you kidnap 1 healthy person off the street, harvest their organs, and let them die to save the 5 patients? It's the exact same math (kill 1 to save 5), but now almost everyone says NO. That is murder.\n\nWhy does our morality flip so wildly? Welcome to **Ethics**, the study of what is right, what is wrong, and why human intuition is completely broken. Let's explore the three massive ethical frameworks secretly battling inside your head right now. 🧠🔪",
    emoji: '🔪',
  },

  theory: [
    {
      id: 'what_is_ethics',
      title: "What is Ethics? 🧭",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'compass',
      svgIcon: 'star',
      content: "For thousands of years, morality was simple: God wrote a rulebook, and you followed it, or you went to Hell (Divine Command Theory).\nBut as society secularized during the Enlightenment, philosophers realized a terrifying fact: If God didn't write the rules, *we* have to invent them from scratch. \n**Ethics** is the systematic, logical attempt to figure out how humans ought to behave without relying on ancient religious texts.",
      highlight: "In a universe with no cosmic rulebook, how do we define 'Good'? 🌌",
    },
    {
      id: 'consequentialism_utilitarianism',
      title: "1. Utilitarianism (The Math of Happiness) 🧮",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'percent',
      svgIcon: 'activity',
      content: "The first major framework is **Utilitarianism**, championed by Jeremy Bentham and John Stuart Mill.\nTheir rule is brilliantly simple: **An action is 'Good' if it maximizes happiness and minimizes suffering for the maximum number of people.** \nIt is pure mathematical morality (Consequentialism). The *intentions* don't matter. Only the *results* matter.",
      highlight: "Utilitarians pull the lever in the Trolley Problem without hesitation. 5 lives > 1 life. 🚂",
    },
    {
      id: 'the_problem_with_utilitarianism',
      title: "The Flaw in the Math 🩸",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert-triangle',
      svgIcon: 'flame',
      content: "Utilitarianism sounds perfect until you test it.\nScenario: The Romans threw Christians to the lions in the Colosseum for entertainment. \nIf 1 Christian suffers terribly (-100 points), but 50,000 Romans experience great joy watching (+50,000 points), Utilitarian math says the execution is morally GOOD. \nUtilitarianism completely ignores individual human rights in favor of 'the greater good'.",
      highlight: "Utilitarianism can logically justify slavery and torture if it makes the majority happy. ⚔️",
    },
    {
      id: 'deontology',
      title: "2. Deontology (The Absolute Rules) 🛑",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'slash',
      svgIcon: 'lock',
      content: "Horrified by Utilitarian math, Immanuel Kant invented **Deontology** (Rule-based ethics).\nKant argued: To be moral is to follow absolute, universal, unbreakable rules (The Categorical Imperative), regardless of the consequences.\nExample: Lying is universally wrong. Therefore, if a murderer is at your door asking where your friend is, you MUST tell the truth. Your duty is to be honest; the murder is the murderer's fault, not yours.",
      highlight: "Deontologists DO NOT pull the lever. Pulling it makes you a murderer of 1. You cannot play God. 🛡️",
    },
    {
      id: 'the_problem_with_deontology',
      title: "The Flaw in the Rules 🤖",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'cpu',
      svgIcon: 'target',
      content: "The problem with Deontology is that it makes humans act like psychopathic robots.\nIf you follow rules so rigidly that you let innocent people die because you refuse to tell a small lie, are you really being moral?\nDeontology cannot handle nuance. It breaks down in extreme situations where two absolute rules conflict (e.g., 'Do not lie' vs. 'Do not let people die').",
      highlight: "Strict Deontology often ends in a bloodbath of 'moral purity'. 🩸",
    },
    {
      id: 'virtue_ethics',
      title: "3. Virtue Ethics (Building Character) 🏋️‍♂️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'user-check',
      svgIcon: 'star',
      content: "Tired of math and rigid rules, modern philosophers resurrected Aristotle's **Virtue Ethics**.\nInstead of asking 'What is the right *action*? (pull lever/don't lie)', Virtue Ethics asks: **'What kind of *person* should I be?'**\nMorality isn't a math equation; it's a skill you practice. By repeatedly practicing virtues (Courage, Honesty, Empathy), you build a good character, and a good character naturally makes good choices.",
      highlight: "Don't memorize a rulebook. Train yourself to be a hero, and you'll act like one when the time comes. 🦸‍♂️",
    },
    {
      id: 'the_trolley_problem',
      title: "The Trolley Problem Analyzed 🚂",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'shuffle',
      svgIcon: 'activity',
      content: "Philippa Foot invented the Trolley Problem in 1967 to prove humans don't use just one ethical framework; we are completely inconsistent.\nWhen we pull the lever (kill 1 to save 5), we are using **Utilitarianism**.\nWhen we refuse to push the fat man off the bridge to stop the train (kill 1 to save 5), we suddenly switch to **Deontology** ('I cannot actively commit murder').",
      highlight: "Our brain bounces wildly between 'the greater good' and 'absolute rules' depending on our emotions. 🤯",
    },
    {
      id: 'moral_relativism',
      title: "Moral Relativism 🌍",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'globe',
      svgIcon: 'eye',
      content: "As humans began exploring other continents, they noticed every culture had different morals.\n**Moral Relativism** argues that there are no objective moral truths. Morality is just a cultural invention, like shaking hands or bowing. \nWhat is 'right' in society A might be 'terribly wrong' in society B, and neither society is objectively correct because there is no 'cosmic ruler' to measure against.",
      highlight: "Relativism promotes tolerance, but it also means you cannot objectively condemn another culture's atrocities. ⚖️",
    },
    {
      id: 'moral_objectivism',
      title: "Moral Objectivism 🏔️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'anchor',
      svgIcon: 'target',
      content: "In contrast, **Moral Objectivism** argues that some things are objectively right or wrong, regardless of culture.\nJust like 2+2=4 is true everywhere, Objectivists argue that 'Torturing babies for fun' is objectively evil across all times and galaxies, even if a culture votes that it is okay.\nSam Harris argues that objectively, morality is the science of moving away from the 'worst possible misery for everyone'.",
      highlight: "If morality is completely relative, then the word 'progress' has no meaning. 📈",
    },
    {
      id: 'ethical_egoism',
      title: "Ethical Egoism (Ayn Rand) 🪙",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'dollar-sign',
      svgIcon: 'lock',
      content: "**Ethical Egoism** argues that the most moral action is whatever serves your own self-interest. Ayn Rand championed this.\nShe argued that 'altruism' (sacrificing yourself for others) is actually evil because it demands you destroy your own life.\nEgoists believe that if everyone aggressively pursued their own rational self-interest and traded value for value, society would be much richer and more honest.",
      highlight: "Selfishness is a virtue. Self-sacrifice is a vice. (Ayn Rand's controversial view). 🦅",
    },
    {
      id: 'the_veil_of_ignorance',
      title: "John Rawls: The Veil of Ignorance 🙈",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'eye-off',
      svgIcon: 'users',
      content: "How do we build a morally fair society? John Rawls invented an epic thought experiment: **The Veil of Ignorance**.\nImagine you are designing the rules of a new society, but you have no idea who you will be born as. You could be born a billionaire, a slave, paralyzed, male, female, or a minority.\nBecause you don't know your fate, you will mathematically design a society that takes care of its weakest members, just in case you end up being one.",
      highlight: "A society is only moral if you are willing to enter it randomly. 🎲",
    },
    {
      id: 'peter_singer',
      title: "Peter Singer: The Drowning Child 🌊",
      color: '#009688',
      bgGradient: ['#001A15', '#000805'],
      icon: 'life-buoy',
      svgIcon: 'heart',
      content: "Modern Utilitarian Peter Singer uses this analogy: If you see a child drowning in a shallow pond, you would jump in to save them, even if it ruined your $200 shoes.\nBut right now, thousands of children are dying of malaria, and you could save one by donating $200 to charity. \nWhy is distance an excuse? Singer argues that buying luxury items instead of saving lives makes us morally complicit in murder.",
      highlight: "Proximity does not change morality. 🌍",
    },
    {
      id: 'nihilism_and_ethics',
      title: "The Threat of Moral Nihilism 🕳️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'x-circle',
      svgIcon: 'cloud',
      content: "Lurking beneath all these debates is **Moral Nihilism**: The terrifying idea that 'Good' and 'Evil' are literally just fairy tales adults invented to control each other.\nIf a lion eats a gazelle, it is not 'evil', it is just biology. Nihilists argue humans are just biology too. Murder isn't 'evil', it's just an action we dislike for survival reasons.\nWithout a cosmic lawgiver, morality might just be an illusion.",
      highlight: "Are we inherently moral beings, or just smart apes with anxiety? 🦍",
    },
    {
      id: 'ai_ethics',
      title: "The Ultimate Test: AI Ethics 🤖",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'cpu',
      svgIcon: 'activity',
      content: "Ethics is no longer just hypothetical. We are currently teaching ethics to Artificial Intelligence.\nWhen a self-driving car's brakes fail, who should it hit? The 5 pedestrians or the brick wall (killing its own passenger)? \nEngineers are literally forced to program Utilitarianism or Deontology into code. If they choose poorly, machines will execute the wrong ethical framework at light speed.",
      highlight: "Philosophy is no longer harmless debates in cafes; it is programming code for weaponized machines. 🚗",
    },
    {
      id: 'conclusion',
      title: "Why It Matters 🌅",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'target',
      svgIcon: 'star',
      content: "You will never find a perfect ethical system. Utilitarianism allows slavery. Deontology allows innocent people to die. \nBut abandoning ethics means surrendering to chaos.\nMoral philosophy forces us to critically exam *why* we do what we do, pushing humanity slowly upward away from our primal, violent past and toward a more conscious future.",
      highlight: "You make ethical choices every single day. Now you know the code running behind them. 🧠",
    },
  ],

  lab: {
    title: "The Trolley Simulator 🚂💀",
    description: "Welcome to the Moral Test Track. The brakes have failed. You are the track operator. You will face 3 variations of the Trolley Problem. Your choices will reveal which philosophical framework is secretly controlling your brain.",
    hint: "Pay attention to your inconsistencies. Do you switch from Utilitarian to Kantian when you have to use your own hands?",
    scientistModeHint: "Algorithm Mode 🧑‍🔬: Track the divergence point between Consequentialist logic and emotional Deontological recoil in your responses.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do we pull the lever for the 5 workers, but REFUSE to push the Fat Man off the bridge to stop the train?", answer: "Neuroscience proves our brain has a 'proximity' bias. Pulling a distant lever feels like 'math', activating the logical part of our brain (Utilitarianism). But using our hands to physically push a man triggers our emotional, primal disgust, activating absolute rules in our brain (Deontology). Our morality depends on distance! 🧠", emoji: '🚂' },
    { id: 'dyk2', question: "Why does Utilitarianism theoretically support the Roman Colosseum?", answer: "Because it purely calculates the sum of 'happiness/pleasure' versus 'pain'. If 50,000 Romans get +5 pleasure from watching a brutal execution (Total: 250,000 pleasure points), and 1 victim suffers -50,000 pain points, the math calculates a net-positive of +200,000. It proves that majorities can justify terrorizing minorities if 'most people' are happy. ⚔️", emoji: '🧮' },
    { id: 'dyk3', question: "Why did Kant say you must NEVER lie?", answer: "Because Kant based morality on 'Reason'. If you make it a universal law that 'It is okay to lie when convenient', then the very concept of 'truth' collapses. If everyone lies constantly, words lose their meaning, and society breaks down. Therefore, acting reasonably means you must act in a way that wouldn't destroy logic if everyone copied you. 🛑", emoji: '⚖️' },
    { id: 'dyk4', question: "Why is 'The Veil of Ignorance' such a powerful thought experiment?", answer: "Because humans are naturally selfish. If you are rich, you will design tax laws that favor the rich. The only way to bypass your own selfishness is to force your brain to pretend it might be born into poverty or sickness tomorrow. It genetically hacks our selfish instincts into designing a fair, empathetic society. 🙈", emoji: '🎲' },
    { id: 'dyk5', question: "Why do programmers struggle with AI Ethics in self-driving cars?", answer: "Because a car can't have 'feelings'. If a car calculates that swerving into a pregnant woman will save 5 old men, it will do it instantly under Utilitarian logic. But wait, what if the car buyer realizes: 'The car I bought will sacrifice ME if it saves two pedestrians.' Nobody would buy the car! Ethics in AI isn't philosophy anymore; it's economics and software liability. 🚗", emoji: '🤖' },
  ],

  quiz: [
    { id: 'q1', question: "What is Utilitarianism?", options: ['A religion', 'An ethical framework stating an action is morally good if it maximizes overall happiness for the most people', 'A diet plan', 'A political party'], answer: 1, explanation: "Focus entirely on the consequences. The math of morality. 🧮" },
    { id: 'q2', question: "What is the primary danger or flaw of Utilitarianism?", options: ['It uses math', 'It can logically justify atrocities like slavery or torture if it makes the majority of the population slightly happier', 'It makes you sad', 'It loves trains'], answer: 1, explanation: "It ignores individual, inalienable human rights. ⚔️" },
    { id: 'q3', question: "What is Immanuel Kant's Deontology?", options: ['The study of teeth', 'Rule-based ethics: you must follow absolute moral rules regardless of the consequences (e.g., NEVER lie)', 'The study of dinosaurs', 'Following feelings'], answer: 1, explanation: "Focus entirely on your 'duty', not the results. 🛑" },
    { id: 'q4', question: "Why does Deontology break down in extreme situations?", options: ['It is too old', 'Because if you rigidly follow absolute rules, you might let innocent people die because you refuse to tell a small lie', 'It costs too much', 'People can\'t read'], answer: 1, explanation: "It removes human nuance and empathy. 🤖" },
    { id: 'q5', question: "What does Aristotle's 'Virtue Ethics' focus on?", options: ['Praying everyday', 'Asking \'what kind of person should I be?\' and practicing good habits to build character, rather than following rigid rules', 'Maximizing money', 'Calculating happiness'], answer: 1, explanation: "Morality is a skill you practice, not an equation. 🏋️‍♂️" },
    { id: 'q6', question: "In the classic Trolley Problem, pulling the lever to kill 1 and save 5 represents which ethical framework?", options: ['Deontology', 'Utilitarianism (Sacrificing the minority for the greater good)', 'Relativism', 'Nihilism'], answer: 1, explanation: "5 > 1. 🚂" },
    { id: 'q7', question: "If you REFUSE to push the Fat Man off the bridge to stop the train, which framework are you leaning towards?", options: ['Utilitarianism', 'Deontology (Following the absolute rule: \'Do not actively commit murder with your own hands\')', 'Egoism', 'Democracy'], answer: 1, explanation: "Your brain switches frameworks when your hands get dirty. 🔪" },
    { id: 'q8', question: "What is Moral Relativism?", options: ['Loving your relatives', 'The belief that there are no objective moral truths; morality is just a cultural invention and differs everywhere', 'The ultimate truth', 'Physics'], answer: 1, explanation: "What is right in one culture might be wrong in another. 🌍" },
    { id: 'q9', question: "What is the biggest problem with hardcore Moral Relativism?", options: ['It is confusing', 'If no morality is objectively true, then you cannot logically condemn another culture for committing brutal atrocities', 'It is boring', 'It makes people angry'], answer: 1, explanation: "If it's relative, you can't say the Nazis were 'objectively' wrong. ⚖️" },
    { id: 'q10', question: "What does Moral Objectivism argue?", options: ['We are all objects', 'That some actions (like torturing children) are objectively evil across all times and galaxies, regardless of culture', 'That only objects matter', 'That culture is everything'], answer: 1, explanation: "Just like Mathematics, morality has universal truths. 🏔️" },
    { id: 'q11', question: "What does Ethical Egoism (Ayn Rand) claim?", options: ['Be nice', 'That the most moral action is whatever serves your own rational self-interest. Selfishness is a virtue', 'Give everything to the poor', 'Don\'t think'], answer: 1, explanation: "Altruism is viewed as self-destruction. 🪙" },
    { id: 'q12', question: "What is John Rawls' thought experiment, 'The Veil of Ignorance'?", options: ['A magic spell', 'You must design society\'s rules without knowing if you will be born rich, poor, healthy, or sick, forcing you to design it fairly', 'Wearing a mask', 'A religion'], answer: 1, explanation: "It mathematically hacks our selfishness into empathy. 🙈" },
    { id: 'q13', question: "When modern philosopher Peter Singer talks about the 'Drowning Child', what is he arguing?", options: ['Kids should learn to swim', 'That letting a child die of disease far away is morally identical to watching a child drown next to you. Distance does not change moral duty', 'Ponds are dangerous', 'Water is wet'], answer: 1, explanation: "He argues buying luxury items makes us morally terrible. 🌊" },
    { id: 'q14', question: "What is Moral Nihilism?", options: ['Loving nature', 'The terrifying idea that \'Good\' and \'Evil\' are just imaginary concepts invented by humans, and nothing is inherently wrong', 'Being a good person', 'Worshipping zero'], answer: 1, explanation: "If a lion killing isn't evil, why is a human killing evil? 🕳️" },
    { id: 'q15', question: "Why are self-driving cars causing an ethics crisis?", options: ['They are too fast', 'Programmers are being literally forced to turn hypothetical Trolley Problems into hard code, executing ethical frameworks at light speed', 'They don\'t use gas', 'They are ugly'], answer: 1, explanation: "Philosophy is now software engineering. 🤖" },
    { id: 'q16', question: "If you think the 'Surgeon' variation of the Trolley Problem (killing 1 healthy person to harvest organs for 5 dying people) is WRONG, you are using:", options: ['Utilitarianism', 'Deontology (Medical duty and rights trumps the math of 5>1)', 'Relativism', 'Math'], answer: 1, explanation: "The exact same math as the lever, but our brains reject it. ⚕️" },
    { id: 'q17', question: "If a Deontologist was hiding Anne Frank in their attic, and the Nazis asked if they were hiding anyone, what would the Deontologist do?", options: ['Lie', 'Tell the truth (Because an absolute rule is NEVER lie, and breaking the rule is always wrong)', 'Fight', 'Run away'], answer: 1, explanation: "This is the classic, horrifying flaw of rigid Deontology. 🛑" },
    { id: 'q18', question: "Which ethical framework fundamentally relies on the 'intention' of the person rather than the 'results' of the action?", options: ['Consequentialism', 'Deontology / Kantianism', 'Nihilism', 'Mathematics'], answer: 1, explanation: "If you follow your duty, the end result doesn't matter. 🛡️" },
    { id: 'q19', question: "What does 'Divine Command Theory' argue?", options: ['Science is real', 'An action is morally good strictly because it is commanded by God, bypassing human logic', 'Kings rule us', 'Aliens are real'], answer: 1, explanation: "Morality is dictated, not discovered. 📜" },
    { id: 'q20', question: "Why do philosophers believe studying ethics is necessary?", options: ['To pass tests', 'Because humans make ethical choices every day. Abandoning ethics means surrendering to primal chaos and violence', 'To be annoying at parties', 'They want money'], answer: 1, explanation: "It is the OS of civilization. 🌅" },
  ],

  relatedTopics: ['existentialism', 'enlightenment', 'free_will'],
};
