// ─────────────────────────────────────────────────────────
//  TOPIC: ETHICS & MORALITY
//  Category: Philosophy
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'ethics_morality',
  title: 'Ethics & Morality',
  subtitle: 'How to be Good without God ⚖️🤔',
  emoji: '⚖️',
  category: 'Philosophy',
  accentKey: 'ethics_morality',

  hook: {
    question: "A runaway trolley is about to kill 5 tied-up workers. You can pull a lever to divert it onto another track, but there is 1 tied-up worker there. Do you pull the lever and kill 1 to save 5?",
    reveal: "Almost everyone says YES. But wait... what if you are a surgeon with 5 dying patients who need organs? Can you kidnap 1 healthy person off the street, harvest their organs, and let them die to save the 5 patients? It's the exact same math (kill 1 to save 5), but now almost everyone says NO. That is murder.\n\nWhy does our morality flip so wildly? Welcome to **Ethics**, the study of what is right, what is wrong, and why human intuition is completely broken. Let's explore the three massive ethical frameworks secretly battling inside your head right now. 🧠🔪",
    emoji: '🔪',
  },

  theory: [
    {
      id: 'what_is_ethics',
      title: "What is Ethics? 🧭",
      color: '#3F51B5',
      bgGradient: ['#0A0A1F', '#05050A'],
      icon: 'compass',
      svgIcon: 'star',
      content: "For thousands of years, morality was simple: God wrote a rulebook, and you followed it, or you went to Hell (Divine Command Theory).\nBut as society secularized during the Enlightenment, philosophers realized a terrifying fact: If God didn't write the rules, *we* have to invent them from scratch. \n**Ethics** is the systematic, logical attempt to figure out how humans ought to behave without relying on ancient religious texts.",
      highlight: "In a universe with no cosmic rulebook, how do we define 'Good'? 🌌",
    },
    {
      id: 'consequentialism_utilitarianism',
      title: "1. Utilitarianism (The Math of Happiness) 🧮",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'percent',
      svgIcon: 'activity',
      content: "The first major framework is **Utilitarianism**, championed by Jeremy Bentham and John Stuart Mill.\nTheir rule is brilliantly simple: **An action is 'Good' if it maximizes happiness and minimizes suffering for the maximum number of people.** \nIt is pure mathematical morality (Consequentialism). The *intentions* don't matter. Only the *results* matter.",
      highlight: "Utilitarians pull the lever in the Trolley Problem without hesitation. 5 lives > 1 life. 🚂",
    },
    {
      id: 'the_problem_with_utilitarianism',
      title: "The Flaw in the Math 🩸",
      color: '#F44336',
      bgGradient: ['#1F0505', '#0A0000'],
      icon: 'alert-triangle',
      svgIcon: 'flame',
      content: "Utilitarianism sounds perfect until you test it.\nScenario: The Romans threw Christians to the lions in the Colosseum for entertainment. \nIf 1 Christian suffers terribly (-100 points), but 50,000 Romans experience great joy watching (+50,000 points), Utilitarian math says the execution is morally GOOD. \nUtilitarianism completely ignores individual human rights in favor of 'the greater good'.",
      highlight: "Utilitarianism can logically justify slavery and torture if it makes the majority happy. ⚔️",
    },
    {
      id: 'deontology',
      title: "2. Deontology (The Absolute Rules) 🛑",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'slash',
      svgIcon: 'lock',
      content: "Horrified by Utilitarian math, Immanuel Kant invented **Deontology** (Rule-based ethics).\nKant argued: To be moral is to follow absolute, universal, unbreakable rules (The Categorical Imperative), regardless of the consequences.\nExample: Lying is universally wrong. Therefore, if a murderer is at your door asking where your friend is, you MUST tell the truth. Your duty is to be honest; the murder is the murderer's fault, not yours.",
      highlight: "Deontologists DO NOT pull the lever. Pulling it makes you a murderer of 1. You cannot play God. 🛡️",
    },
    {
      id: 'the_problem_with_deontology',
      title: "The Flaw in the Rules 🤖",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'cpu',
      svgIcon: 'target',
      content: "The problem with Deontology is that it makes humans act like psychopathic robots.\nIf you follow rules so rigidly that you let innocent people die because you refuse to tell a small lie, are you really being moral?\nDeontology cannot handle nuance. It breaks down in extreme situations where two absolute rules conflict (e.g., 'Do not lie' vs. 'Do not let people die').",
      highlight: "Strict Deontology often ends in a bloodbath of 'moral purity'. 🩸",
    },
    {
      id: 'virtue_ethics',
      title: "3. Virtue Ethics (Building Character) 🏋️‍♂️",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'user-check',
      svgIcon: 'star',
      content: "Tired of math and rigid rules, modern philosophers resurrected Aristotle's **Virtue Ethics**.\nInstead of asking 'What is the right *action*? (pull lever/don't lie)', Virtue Ethics asks: **'What kind of *person* should I be?'**\nMorality isn't a math equation; it's a skill you practice. By repeatedly practicing virtues (Courage, Honesty, Empathy), you build a good character, and a good character naturally makes good choices.",
      highlight: "Don't memorize a rulebook. Train yourself to be a hero, and you'll act like one when the time comes. 🦸‍♂️",
    },
    {
      id: 'the_trolley_problem',
      title: "The Trolley Problem Analyzed 🚂",
      color: '#212121',
      bgGradient: ['#111111', '#000000'],
      icon: 'shuffle',
      svgIcon: 'activity',
      content: "Philippa Foot invented the Trolley Problem in 1967 to prove humans don't use just one ethical framework; we are completely inconsistent.\nWhen we pull the lever (kill 1 to save 5), we are using **Utilitarianism**.\nWhen we refuse to push the fat man off the bridge to stop the train (kill 1 to save 5), we suddenly switch to **Deontology** ('I cannot actively commit murder').",
      highlight: "Our brain bounces wildly between 'the greater good' and 'absolute rules' depending on our emotions. 🤯",
    },
    {
      id: 'moral_relativism',
      title: "Moral Relativism 🌍",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'globe',
      svgIcon: 'eye',
      content: "As humans began exploring other continents, they noticed every culture had different morals.\n**Moral Relativism** argues that there are no objective moral truths. Morality is just a cultural invention, like shaking hands or bowing. \nWhat is 'right' in society A might be 'terribly wrong' in society B, and neither society is objectively correct because there is no 'cosmic ruler' to measure against.",
      highlight: "Relativism promotes tolerance, but it also means you cannot objectively condemn another culture's atrocities. ⚖️",
    },
    {
      id: 'moral_objectivism',
      title: "Moral Objectivism 🏔️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'anchor',
      svgIcon: 'target',
      content: "In contrast, **Moral Objectivism** argues that some things are objectively right or wrong, regardless of culture.\nJust like 2+2=4 is true everywhere, Objectivists argue that 'Torturing babies for fun' is objectively evil across all times and galaxies, even if a culture votes that it is okay.\nSam Harris argues that objectively, morality is the science of moving away from the 'worst possible misery for everyone'.",
      highlight: "If morality is completely relative, then the word 'progress' has no meaning. 📈",
    },
    {
      id: 'ethical_egoism',
      title: "Ethical Egoism (Ayn Rand) 🪙",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'dollar-sign',
      svgIcon: 'lock',
      content: "**Ethical Egoism** argues that the most moral action is whatever serves your own self-interest. Ayn Rand championed this.\nShe argued that 'altruism' (sacrificing yourself for others) is actually evil because it demands you destroy your own life.\nEgoists believe that if everyone aggressively pursued their own rational self-interest and traded value for value, society would be much richer and more honest.",
      highlight: "Selfishness is a virtue. Self-sacrifice is a vice. (Ayn Rand's controversial view). 🦅",
    },
    {
      id: 'the_veil_of_ignorance',
      title: "John Rawls: The Veil of Ignorance 🙈",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'eye-off',
      svgIcon: 'users',
      content: "How do we build a morally fair society? John Rawls invented an epic thought experiment: **The Veil of Ignorance**.\nImagine you are designing the rules of a new society, but you have no idea who you will be born as. You could be born a billionaire, a slave, paralyzed, male, female, or a minority.\nBecause you don't know your fate, you will mathematically design a society that takes care of its weakest members, just in case you end up being one.",
      highlight: "A society is only moral if you are willing to enter it randomly. 🎲",
    },
    {
      id: 'peter_singer',
      title: "Peter Singer: The Drowning Child 🌊",
      color: '#009688',
      bgGradient: ['#001A15', '#000805'],
      icon: 'life-buoy',
      svgIcon: 'heart',
      content: "Modern Utilitarian Peter Singer uses this analogy: If you see a child drowning in a shallow pond, you would jump in to save them, even if it ruined your $200 shoes.\nBut right now, thousands of children are dying of malaria, and you could save one by donating $200 to charity. \nWhy is distance an excuse? Singer argues that buying luxury items instead of saving lives makes us morally complicit in murder.",
      highlight: "Proximity does not change morality. 🌍",
    },
    {
      id: 'nihilism_and_ethics',
      title: "The Threat of Moral Nihilism 🕳️",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'x-circle',
      svgIcon: 'cloud',
      content: "Lurking beneath all these debates is **Moral Nihilism**: The terrifying idea that 'Good' and 'Evil' are literally just fairy tales adults invented to control each other.\nIf a lion eats a gazelle, it is not 'evil', it is just biology. Nihilists argue humans are just biology too. Murder isn't 'evil', it's just an action we dislike for survival reasons.\nWithout a cosmic lawgiver, morality might just be an illusion.",
      highlight: "Are we inherently moral beings, or just smart apes with anxiety? 🦍",
    },
    {
      id: 'ai_ethics',
      title: "The Ultimate Test: AI Ethics 🤖",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'cpu',
      svgIcon: 'activity',
      content: "Ethics is no longer just hypothetical. We are currently teaching ethics to Artificial Intelligence.\nWhen a self-driving car's brakes fail, who should it hit? The 5 pedestrians or the brick wall (killing its own passenger)? \nEngineers are literally forced to program Utilitarianism or Deontology into code. If they choose poorly, machines will execute the wrong ethical framework at light speed.",
      highlight: "Philosophy is no longer harmless debates in cafes; it is programming code for weaponized machines. 🚗",
    },
    {
      id: 'conclusion',
      title: "Why It Matters 🌅",
      color: '#FFB300',
      bgGradient: ['#1F1A00', '#0A0800'],
      icon: 'target',
      svgIcon: 'star',
      content: "You will never find a perfect ethical system. Utilitarianism allows slavery. Deontology allows innocent people to die. \nBut abandoning ethics means surrendering to chaos.\nMoral philosophy forces us to critically exam *why* we do what we do, pushing humanity slowly upward away from our primal, violent past and toward a more conscious future.",
      highlight: "You make ethical choices every single day. Now you know the code running behind them. 🧠",
    },
  ],

  lab: {
    title: "The Trolley Simulator 🚂💀",
    description: "Welcome to the Moral Test Track. The brakes have failed. You are the track operator. You will face 3 variations of the Trolley Problem. Your choices will reveal which philosophical framework is secretly controlling your brain.",
    hint: "Pay attention to your inconsistencies. Do you switch from Utilitarian to Kantian when you have to use your own hands?",
    scientistModeHint: "Algorithm Mode 🧑‍🔬: Track the divergence point between Consequentialist logic and emotional Deontological recoil in your responses.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Why do we pull the lever for the 5 workers, but REFUSE to push the Fat Man off the bridge to stop the train?", answer: "Neuroscience proves our brain has a 'proximity' bias. Pulling a distant lever feels like 'math', activating the logical part of our brain (Utilitarianism). But using our hands to physically push a man triggers our emotional, primal disgust, activating absolute rules in our brain (Deontology). Our morality depends on distance! 🧠", emoji: '🚂' },
    { id: 'dyk2', question: "Why does Utilitarianism theoretically support the Roman Colosseum?", answer: "Because it purely calculates the sum of 'happiness/pleasure' versus 'pain'. If 50,000 Romans get +5 pleasure from watching a brutal execution (Total: 250,000 pleasure points), and 1 victim suffers -50,000 pain points, the math calculates a net-positive of +200,000. It proves that majorities can justify terrorizing minorities if 'most people' are happy. ⚔️", emoji: '🧮' },
    { id: 'dyk3', question: "Why did Kant say you must NEVER lie?", answer: "Because Kant based morality on 'Reason'. If you make it a universal law that 'It is okay to lie when convenient', then the very concept of 'truth' collapses. If everyone lies constantly, words lose their meaning, and society breaks down. Therefore, acting reasonably means you must act in a way that wouldn't destroy logic if everyone copied you. 🛑", emoji: '⚖️' },
    { id: 'dyk4', question: "Why is 'The Veil of Ignorance' such a powerful thought experiment?", answer: "Because humans are naturally selfish. If you are rich, you will design tax laws that favor the rich. The only way to bypass your own selfishness is to force your brain to pretend it might be born into poverty or sickness tomorrow. It genetically hacks our selfish instincts into designing a fair, empathetic society. 🙈", emoji: '🎲' },
    { id: 'dyk5', question: "Why do programmers struggle with AI Ethics in self-driving cars?", answer: "Because a car can't have 'feelings'. If a car calculates that swerving into a pregnant woman will save 5 old men, it will do it instantly under Utilitarian logic. But wait, what if the car buyer realizes: 'The car I bought will sacrifice ME if it saves two pedestrians.' Nobody would buy the car! Ethics in AI isn't philosophy anymore; it's economics and software liability. 🚗", emoji: '🤖' },
  ],

  quiz: [
    { id: 'q1', question: "What is Utilitarianism?", options: ["A religious belief system", "Maximizing happiness for most people", "A specific dietary regimen", "A modern political ideology"], answer: 1, explanation: "Focus entirely on the consequences. The math of morality. 🧮" },
    { id: 'q2', question: "What is the primary danger or flaw of Utilitarianism?", options: ["It relies on complex math", "It can justify harming minorities", "It causes emotional distress", "It ignores modern technology"], answer: 1, explanation: "It ignores individual, inalienable human rights. ⚔️" },
    { id: 'q3', question: "What is Immanuel Kant's Deontology?", options: ["The study of dental health", "Following absolute moral rules strictly", "The study of prehistoric life", "Acting based on personal feelings"], answer: 1, explanation: "Focus entirely on your 'duty', not the results. 🛑" },
    { id: 'q4', question: "Why does Deontology break down in extreme situations?", options: ["It is an outdated system", "Rigid rules can cause harm", "It is too expensive", "It requires high literacy levels"], answer: 1, explanation: "It removes human nuance and empathy. 🤖" },
    { id: 'q5', question: "What does Aristotle's 'Virtue Ethics' focus on?", options: ["Daily religious prayer habits", "Developing good character and habits", "Maximizing personal financial wealth", "Calculating the total happiness"], answer: 1, explanation: "Morality is a skill you practice, not an equation. 🏋️‍♂️" },
    { id: 'q6', question: "In the classic Trolley Problem, pulling the lever to kill 1 and save 5 represents which ethical framework?", options: ["Strict rule-based deontology", "The utilitarian greater good", "Cultural moral relativism", "Existential moral nihilism"], answer: 1, explanation: "5 > 1. 🚂" },
    { id: 'q7', question: "If you REFUSE to push the Fat Man off the bridge to stop the train, which framework are you leaning towards?", options: ["The utilitarian perspective", "The deontological perspective", "The ethical egoist perspective", "The democratic perspective"], answer: 1, explanation: "Your brain switches frameworks when your hands get dirty. 🔪" },
    { id: 'q8', question: "What is Moral Relativism?", options: ["Caring for family members", "Morality based on cultural norms", "The search for truth", "Laws of physical science"], answer: 1, explanation: "What is right in one culture might be wrong in another. 🌍" },
    { id: 'q9', question: "What is the biggest problem with hardcore Moral Relativism?", options: ["It is logically confusing", "Cannot condemn cultural atrocities", "It is intellectually boring", "It causes social anger"], answer: 1, explanation: "If it's relative, you can't say the Nazis were 'objectively' wrong. ⚖️" },
    { id: 'q10', question: "What does Moral Objectivism argue?", options: ["Humans are physical objects", "Universal truths exist for everyone", "Only material objects matter", "Culture defines all morality"], answer: 1, explanation: "Just like Mathematics, morality has universal truths. 🏔️" },
    { id: 'q11', question: "What does Ethical Egoism (Ayn Rand) claim?", options: ["Always being kind", "Acting in rational self-interest", "Giving wealth to others", "Avoiding all critical thinking"], answer: 1, explanation: "Altruism is viewed as self-destruction. 🪙" },
    { id: 'q12', question: "What is John Rawls' thought experiment, 'The Veil of Ignorance'?", options: ["A mystical magic spell", "Designing society without knowing status", "Wearing a physical mask", "A new religious movement"], answer: 1, explanation: "It mathematically hacks our selfishness into empathy. 🙈" },
    { id: 'q13', question: "When modern philosopher Peter Singer talks about the 'Drowning Child', what is he arguing?", options: ["Teaching children to swim", "Distance doesn't change moral duty", "Ponds are inherently dangerous", "Basic facts about water"], answer: 1, explanation: "He argues buying luxury items makes us morally terrible. 🌊" },
    { id: 'q14', question: "What is Moral Nihilism?", options: ["A love for nature", "Morality is an imaginary concept", "Being a virtuous person", "Worshipping the number zero"], answer: 1, explanation: "If a lion killing isn't evil, why is a human killing evil? 🕳️" },
    { id: 'q15', question: "Why are self-driving cars causing an ethics crisis?", options: ["They travel too fast", "Coding ethical choices into machines", "They use electric power", "They have unattractive designs"], answer: 1, explanation: "Philosophy is now software engineering. 🤖" },
    { id: 'q16', question: "If you think the 'Surgeon' variation of the Trolley Problem (killing 1 healthy person to harvest organs for 5 dying people) is WRONG, you are using:", options: ["The utilitarian framework", "The deontological framework", "The relativist framework", "The mathematical framework"], answer: 1, explanation: "The exact same math as the lever, but our brains reject it. ⚕️" },
    { id: 'q17', question: "If a Deontologist was hiding Anne Frank in their attic, and the Nazis asked if they were hiding anyone, what would the Deontologist do?", options: ["Tell a protective lie", "Tell the absolute truth", "Fight the intruders physically", "Attempt to run away"], answer: 1, explanation: "This is the classic, horrifying flaw of rigid Deontology. 🛑" },
    { id: 'q18', question: "Which ethical framework fundamentally relies on the 'intention' of the person rather than the 'results' of the action?", options: ["The consequentialist framework", "The deontological framework", "The nihilist framework", "The mathematical framework"], answer: 1, explanation: "If you follow your duty, the end result doesn't matter. 🛡️" },
    { id: 'q19', question: "What does 'Divine Command Theory' argue?", options: ["Science explains all reality", "Morality comes from God's commands", "Kings have absolute power", "Extraterrestrial life is real"], answer: 1, explanation: "Morality is dictated, not discovered. 📜" },
    { id: 'q20', question: "Why do philosophers believe studying ethics is necessary?", options: ["To pass academic tests", "To guide daily human choices", "To debate at parties", "To earn more money"], answer: 1, explanation: "It is the OS of civilization. 🌅" },
  ],

  relatedTopics: ['existentialism', 'enlightenment', 'free_will'],
};
