export default {
  id: 'forces_motion',
  title: 'Forces & Motion',
  subtitle: 'Newton rules the universe 🪐',
  emoji: '🎯',
  category: 'Foundations',
  accentKey: 'gravity',

  hook: {
    question: "If you physically shoot a bullet completely horizontally from a rifle, and forcefully drop another identical bullet from your hand at the exact identical time... which hits the ground first? 🔫",
    reveal: "They hit the ground at the exact same millisecond! Horizontal motion and vertical gravity fall are two completely mathematically independent forces. Gravity rigorously pulls both bullets down at exactly 9.8m/s², completely ignoring that one is flying aggressively forward at supersonic speeds! 🎯",
    emoji: '☄️',
  },

  theory: [
    { id: '1', title: 'Newton\'s First Law (Inertia)', color: '#7B6FFF', bgGradient: ['#1A002A', '#05050A'], icon: '🚀', svgIcon: 'planet', content: "Also known formally as the **Law of Inertia**: An object at rest aggressively stays at rest, and an object strictly in motion stays completely in motion with the exact same speed and same direction, strictly unless actively acted upon heavily by an unbalanced external force (like severe friction or pure gravity).", highlight: "If you throw a heavy wrench violently in deep space, it will keep traveling perfectly forever until it physically crashes! 🌌" },
    { id: '2', title: 'Newton\'s Second Law (F=ma)', color: '#FF3131', bgGradient: ['#2A000A', '#05050A'], icon: '🏎️', svgIcon: 'target', content: "Force explicitly equals mass times its acceleration (**F = ma**). \n\nThis mathematically severely means the heavier a massive object inherently is, the enormously more profound force you critically need to radically accelerate it. Or conversely, the significantly more force you rapidly apply to a given heavy mass, the viciously faster it will violently speed up.", highlight: "This is precisely why it's incredibly easy to vigorously push a lightweight bicycle, but terrifyingly difficult to push a massively heavy parked truck! 🚗" },
    { id: '3', title: 'Newton\'s Third Law (Action/Reaction)', color: '#00D4FF', bgGradient: ['#001A2A', '#05050A'], icon: '🤜', svgIcon: 'link', content: "For strictly every physical action, there is an exactly equal and mathematically opposite severe reaction! \n\nWhen you push physically against a strict wall, the heavy wall violently pushes exactly that hard cleanly back against your physical hand. Space rockets fiercely move forward in pure space not by physically pushing against air (there literally is none!), but by violently aggressively throwing heavy mass fiercely backward so fiercely that the violent reaction completely throws the massive heavy rocket violently forward!", highlight: "You absolutely do not physically safely walk by specifically pushing yourself happily forward; you efficiently strictly walk by actively pushing the heavy massive Earth violently backward! 🌍" },
    { id: '4', title: 'Universal Gravity', color: '#FFB347', bgGradient: ['#2A1A00', '#05050A'], icon: '🍎', svgIcon: 'cube', content: "**Gravity** is the invisible, profound attractive force rigorously acting entirely between ALL massive physical bodies in the vast universe.\n\nOn heavy Earth, gravity fiercely pulls fiercely exactly downwards at a strict acceleration of **-9.81 m/s²**. Regardless of intense heavy mass, if you entirely eliminate severe air resistance, a heavy solid steel bowling ball and a tiny lightweight feather will rigorously drop and crash perfectly flawlessly identically simultaneously!", highlight: "Gravity is literally infinite! The massive heavy gravity of your physical body is currently technically visibly profoundly pulling heavily intensely strictly accurately significantly definitely mathematically precisely pulling on the distant Andromeda Galaxy! 🌌" },
    { id: '5', title: 'Friction: The Natural Brake', color: '#FFD166', bgGradient: ['#2A2A00', '#05050A'], icon: '🔥', svgIcon: 'zap', content: "**Friction** is the resistive force that occurs when two surfaces slide (or try to slide) against each other. It effectively converts kinetic energy into internal thermal heat!\n\nThere are two main types: **Static Friction** (limiting the start of motion) and **Kinetic Friction** (opposing ongoing motion). Without it, you couldn't walk, drive, or even hold a pencil!", highlight: "Friction is the reason your hands get warm when you rub them together aggressively! 🔥" },
    { id: '6', title: 'Momentum & Impulse', color: '#A855F7', bgGradient: ['#1A0A2A', '#05050A'], icon: '☄️', svgIcon: 'lightning', content: "**Momentum** ($p = mv$) determines how difficult it is to stop a moving object. A slow-moving train and a high-speed bullet both possess terrifying momentum.\n\n**Impulse** ($J = F \Delta t$) is the change in momentum. Airbags work by increasing the *time* of collision, which drastically reduces the *force* exerted on your body.", highlight: "Momentum is why a heavy truck takes so much longer to stop than a small car! 🚛" },
    { id: '7', title: 'Circular Motion', color: '#00D4FF', bgGradient: ['#001A2A', '#05050A'], icon: '🎡', svgIcon: 'waves', content: "When an object moves in a circle, it is constantly accelerating because its *direction* is constantly changing, even if its speed is constant!\n\nThis requires a **Centripetal Force** pulling it toward the center. If you swing a ball on a string and the string snaps, the ball won't fly 'outward'—it will fly off in a perfectly straight line tangent to the circle.", highlight: "Gravity acts as the centripetal force that keeps the Moon trapped in its beautiful orbit! 🌕" },
    { id: '8', title: 'Air Resistance & Drag', color: '#55EFC4', bgGradient: ['#0A2A1A', '#05050A'], icon: '🌬️', svgIcon: 'shield', content: "**Air Resistance** (or Drag) is a type of friction caused by air molecules crashing into a moving object. \n\nThe faster you move, the more air molecules you hit per second, meaning drag increases exponentially with speed! This is why competitive cyclists wear aerodynamic helmets and crouch down to minimize their 'frontal area'.", highlight: "In a total vacuum, a lead weight and a fluffy feather fall at the exact same speed! 🪶" },
    { id: '9', title: 'Terminal Velocity', color: '#FF3131', bgGradient: ['#2A000A', '#05050A'], icon: '🪂', svgIcon: 'target', content: "When an object falls, gravity pulls it down while air resistance pushes it up. As it speeds up, the drag force grows. \n\nEventually, the upward drag exactly equals the downward pull of gravity. The net force becomes zero, and the object stops accelerating, falling at a steady speed called **Terminal Velocity**.", highlight: "A skydiver's terminal velocity is about 120 mph, but they can reach 200 mph by tucking into a 'bullet' shape! 🦅" },
    { id: '10', title: 'Pressure & Area', color: '#00D4A0', bgGradient: ['#002A20', '#05050A'], icon: '👟', svgIcon: 'grid', content: "**Pressure** is force distributed over a specific area ($P = F / A$). \n\nYou can walk on soft snow using wide snowshoes because they spread your weight (force) over a massive area, drastically reducing the pressure. Conversely, a sharp needle exerts massive pressure because its tiny tip concentrates force onto a microscopic area.", highlight: "This is why a bed of nails doesn't hurt—your weight is spread across hundreds of points! 📍" }
  ],

  lab: {
    title: "Trajectory Master Lab 🎯",
    description: "Launch the High-Fidelity Physics Engine. Take control of a projectile cannon with precision vector decomposition. Toggle gravity, atmosphere, and object mass to master Newtonian mechanics.",
    hint: "Toggle 'Scientist Mode' to see the Vx and Vy vectors split in real-time.",
    scientistModeHint: "Scientist Mode reveals the instantaneous parabolic matrix and velocity components.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why astronauts float in the space station? 🚀", answer: "They aren't technically weightless! Gravity on the ISS is still 90% as strong as on Earth's surface. They float because they are in 'free fall' — falling toward Earth while moving sideways so fast that they constantly 'miss' the planet.", emoji: '🛰️' },
    { id: 'dyk2', question: "Do you know why you lean backwards when a bus suddenly stops? 🚌", answer: "Inertia! Your body is in motion and want to stay in motion. When the bus stops, your feet stop with the floor, but your upper body 'remembers' the forward speed and tries to keep going at 40mph!", emoji: '🤸' },
    { id: 'dyk3', question: "Do you know why a bed of nails doesn't pierce your skin? 📍", answer: "Pressure = Force / Area. By laying on hundreds of nails, your weight is distributed across so many points that the pressure on any single nail is lower than what's needed to break your skin!", emoji: '🪶' },
    { id: 'dyk4', question: "Do you know why you can't hear an explosion in space? 🌌", answer: "Sound requires a medium (like air or water) to travel through. Space is a vacuum—there are no atoms to vibrate, so the explosion happens in total silence!", emoji: '🤫' },
    { id: 'dyk5', question: "Do you know why heavy trucks take so long to stop? 🚛", answer: "Momentum ($p = mv$). Because a truck has massive mass, it possesses colossal momentum. Stopping it requires either a huge force or a very long period of time (distance).", emoji: '🛑' }
  ],

  quiz: [
    { id: 'q1', question: "Which equation represents Newton's Second Law?", options: ["The equation E=mc²", "The equation V=IR", "The equation F=ma", "The equation W=Fd"], answer: 2, explanation: "Force equals mass times acceleration." },
    { id: 'q2', question: "Newton's First Law is also known as the Law of:", options: ["The Law of Gravity", "The Law of Inertia", "The Law of Momentum", "The Law of Pressure"], answer: 1, explanation: "Inertia is the tendency of an object to resist changes in motion." },
    { id: 'q3', question: "In a vacuum, if you drop a bowling ball and a feather, which hits first?", options: ["The ball hits first", "The feather hits first", "Both hit at once", "Neither object will fall"], answer: 2, explanation: "Without air resistance, gravity accelerates all objects at precisely 9.8m/s² regardless of mass." },
    { id: 'q4', question: "What is the standard unit of Force?", options: ["The unit is Joule", "The unit is Watt", "The unit is Newton", "The unit is Pascal"], answer: 2, explanation: "Named after Sir Isaac Newton, the Newton (N) is the unit of force." },
    { id: 'q5', question: "Terminal velocity is reached when drag force equals:", options: ["The force of velocity", "The force of mass", "The force of friction", "The force of gravity"], answer: 3, explanation: "When upward air resistance perfectly balances downward gravity, acceleration stops." },
    { id: 'q6', question: "What happens to your upper body when a car suddenly accelerates?", options: ["Body leans forward", "Body stays still", "Body leans backward", "Body lifts up"], answer: 2, explanation: "Inertia! Your body wants to stay at rest while the car pushes forward." },
    { id: 'q7', question: "Which force keeps a satellite in orbit?", options: ["The magnetic force", "The gravitational force", "The frictional force", "The air resistance"], answer: 1, explanation: "Gravity pulls the satellite toward Earth, acting as a centripetal force that curves its path." },
    { id: 'q8', question: "Momentum is the product of mass and:", options: ["Product of mass time", "Product of mass distance", "Product of mass velocity", "Product of mass acceleration"], answer: 2, explanation: "Momentum (p) = Mass (m) × Velocity (v)." },
    { id: 'q9', question: "Why do skydivers use parachutes?", options: ["To increase gravity", "To decrease mass", "To increase air resistance", "To change direction"], answer: 2, explanation: "Parachutes have a huge surface area, generating massive drag to lower terminal velocity." },
    { id: 'q10', question: "Pressure is calculated as Force divided by:", options: ["Divided by mass", "Divided by area", "Divided by volume", "Divided by time"], answer: 1, explanation: "P = F / A. Smaller area equals higher pressure." },
    { id: 'q11', question: "If you double the force on an object, what happens to its acceleration?", options: ["The acceleration halves", "The acceleration stays same", "The acceleration doubles", "The acceleration quadruples"], answer: 2, explanation: "Since F=ma, force and acceleration are directly proportional." },
    { id: 'q12', question: "Which surfaces would have the highest friction?", options: ["Ice on ice", "Rubber on concrete", "Glass on glass", "Oil on metal"], answer: 1, explanation: "Rubber and concrete both have rough microscopic textures that lock together." },
    { id: 'q13', question: "An object moving in a circle has a constant speed but a changing:", options: ["The object's mass", "The object's energy", "The object's velocity", "The object's volume"], answer: 2, explanation: "Velocity is speed PLUS direction. Since direction is changing, velocity is changing (acceleration)." },
    { id: 'q14', question: "Impulse is defined as Force multiplied by:", options: ["Force multiplied by mass", "Force multiplied by distance", "Force multiplied by time", "Force multiplied by velocity"], answer: 2, explanation: "Impulse ($J = F \Delta t$) causes a change in momentum." },
    { id: 'q15', question: "What is the acceleration due to gravity on Earth's surface?", options: ["Exactly 1.6 m/s²", "Exactly 5.0 m/s²", "Exactly 9.8 m/s²", "Exactly 12.4 m/s²"], answer: 2, explanation: "Earth's gravity accelerates objects at roughly 9.8 meters per second squared." },
    { id: 'q16', question: "If the net force on an object is zero, the object must be:", options: ["Object stays at rest", "Object moves constantly", "Rest or constant speed", "Object starts accelerating"], answer: 2, explanation: "Newton's First Law: zero net force means zero CHANGE in motion." },
    { id: 'q17', question: "What happens to the pressure if you decrease the area but keep force constant?", options: ["The pressure decreases", "The pressure stays same", "The pressure increases", "The pressure disappears"], answer: 2, explanation: "P = F / A. Dividing by a smaller number makes the result larger." },
    { id: 'q18', question: "The 'Law of Action and Reaction' is Newton's:", options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Newton's Universal Law"], answer: 2, explanation: "The Third Law states every action has an equal and opposite reaction." },
    { id: 'q19', question: "Why is it harder to push a full shopping cart than an empty one?", options: ["There is less friction", "There is less gravity", "There is more inertia", "There is more resistance"], answer: 2, explanation: "More mass means more inertia, which resists acceleration (F=ma)." },
    { id: 'q20', question: "A projectile's horizontal motion is independent of its:", options: ["The horizontal speed", "The vertical motion", "The intended target", "The initial launch"], answer: 1, explanation: "Gravity only affects vertical motion; horizontal velocity stays constant (ignoring air)." }
  ],

 

  relatedTopics: ['heat_temperature', 'work_power'],
};
