export default {
  id: "pressure_fluids",
  title: "Pressure & Fluids",
  subtitle: "The crushing weight of oceans and air 🌊",
  emoji: "🌊",
  category: "Physics",
  accentKey: "physics",

  hook: {
    question: "How does a standard terrifying 3,000-pound Great White Shark physically aggressively float perfectly still without sinking like a massive heavy rock? 🦈",
    reveal: "The violent power of Buoyancy! The shark physically forcibly displaces essentially 3,000 massive pounds of heavy ocean water with its massive body. According exactly to Archimedes' Principle, the furiously displaced heavy liquid physically aggressively fights to return, violently mathematically pushing the heavy shark perfectly strictly directly upward! ⚖️",
    emoji: "🌊",
  },

  theory: [
    {
      id: "pf_0",
      title: "Pressure: The Crushing Force 🔨",
      color: "#00E5FF",
      bgGradient: ["#001A20", "#050D0A"],
      icon: "🔨",
      svgIcon: "target",
      content: "Pressure ($P = F / A$) mathematically rigidly dictates entirely exactly how aggressively a specific physical force is spread over a specific area! \n\nIf a 100-pound woman strictly violently steps completely on your foot with completely flat sneakers, it hurts. If she absolutely entirely steps on you utterly fiercely with a razor-sharp stiletto heel, the brutally tiny microscopic area violently multiplies the true pressure mathematically, perfectly aggressively crushing your bones! 👠",
      highlight: "Force is exactly physically completely innocent; Pressure is what actually furiously aggressively utterly painfully cuts your skin! 🔪",
    },
    {
      id: "pf_1",
      title: "Atmospheric Pressure: The Air Ocean 🌬️",
      color: "#A855F7",
      bgGradient: ["#1A0A1F", "#050D0A"],
      icon: "🌬️",
      svgIcon: "wind",
      content: "You are absolutely permanently aggressively living completely perfectly right at the bottom of a violently massive 60-mile-deep ocean of gas! \n\nThe severe crushing sheer physical massive weight of all that tall air is actively brutally heavily pressing down physically on every exact square inch of your completely entirely human body with strictly rigidly specifically 14.7 pounds of severe force! 🏋️",
      highlight: "Your body is intensely mathematically strictly aggressively pushing furiously utterly back outward just so you strictly explicitly totally fundamentally don't forcefully collapse! 💥",
    },
    {
      id: "pf_2",
      title: "Archimedes' Principle (Buoyancy) ⚖️",
      color: "#FFD166",
      bgGradient: ["#2A2A00", "#050D0A"],
      icon: "⚖️",
      svgIcon: "anchor",
      content: "If you physically drop a heavy solid object perfectly straight rapidly down into the exact absolute middle of water, the totally exact physical volume of that object utterly brutally violently pushes the same exact volume of total water drastically furiously away! \n\nThe water fights back heavily firmly upwards! The absolutely true mathematically perfectly calculated strictly aggressive 'Upward Buoyant Force' completely aggressively furiously absolutely exactly equals the incredibly fierce pure absolute physical total weight of the aggressively pushed total liquid! 🌊",
      highlight: "Heavy immense steel utterly physically massive cruise ships explicitly aggressively perfectly forcefully mathematically completely strictly actually incredibly perfectly totally utterly beautifully effectively essentially purely float forever! 🚢",
    },
    {
      id: "pf_3",
      title: "Pascal's Principle: Hydraulic Power 🚜",
      color: "#39FF14",
      bgGradient: ["#0A200A", "#050D0A"],
      icon: "🚜",
      svgIcon: "layers",
      content: "Liquids are fundamentally incompressible! \n\nIf you apply pressure to a confined liquid, that pressure is transmitted perfectly and instantly in every direction! This allows us to use 'Hydraulics'. By pushing a small piston over a long distance, we can use the transmitted pressure to lift a massive truck on a large piston with almost zero effort! 🏗️",
      highlight: "This is exactly how car brakes and heavy construction excavators generate thousands of pounds of force! 🚜",
    },
    {
      id: "pf_4",
      title: "Bernoulli's Principle: Flight Magic ✈️",
      color: "#3B82F6",
      bgGradient: ["#0A1220", "#050D0A"],
      icon: "✈️",
      svgIcon: "wind",
      content: "Fast-moving fluids (like air) exert LOWER pressure than slow-moving fluids! \n\nAirplane wings are designed so that air moves faster over the curved top than the flat bottom. This creates a high-pressure zone below and a low-pressure zone above, which literally sucks the entire massive 500,000-pound plane up into the sky! 🌤️",
      highlight: "Gravity is constantly pulling down, but Bernoulli's math is violently pushing up! 🛫",
    },
    {
      id: "pf_5",
      title: "Density: The Sink-or-Swim Rule 🧊",
      color: "#F59E0B",
      bgGradient: ["#201500", "#050D0A"],
      icon: "🧊",
      svgIcon: "box",
      content: "Density is how much 'stuff' is packed into a space ($D = m / V$). \n\nIf an object is denser than the fluid it's in, it will sink like a stone. If it's less dense, it will float effortlessly. This is why a massive 1,000-foot iron ship floats—because its internal empty space makes its *average* density lower than water! 🚢",
      highlight: "Ice floats because it is strictly less dense than liquid water, which is a rare miracle in physics! ❄️",
    },
    {
      id: "pf_6",
      title: "Viscosity: The Friction of Liquids 🍯",
      color: "#8B5CF6",
      bgGradient: ["#150A20", "#050D0A"],
      icon: "🍯",
      svgIcon: "droplet",
      content: "Viscosity is the internal resistance of a fluid to flow! \n\nWater has low viscosity and splashes everywhere. Honey has extremely high viscosity and moves like a slow, sluggish monster. It's essentially 'liquid friction' caused by the molecules aggressively grabbing onto each other as they try to move! 🥞",
      highlight: "Lava has such high viscosity it can support objects on its surface before they slowly melt or sink! 🌋",
    },
    {
      id: "pf_7",
      title: "Surface Tension: The Water Skin 🕷️",
      color: "#10B981",
      bgGradient: ["#0A2015", "#050D0A"],
      icon: "🕷️",
      svgIcon: "activity",
      content: "At the surface of a liquid, molecules are pulled together so tightly they form a literal 'skin'! \n\nThis is called Surface Tension. It's strong enough to support small insects (like Water Striders) and even allows you to carefully float a metal paperclip on a glass of water if you don't break the bond! 💧",
      highlight: "Soap works by aggressively destroying surface tension, allowing water to sneak into tiny gaps and wash away dirt! 🧼",
    },
    {
      id: "pf_8",
      title: "The Capillary Effect: Defying Gravity 🌿",
      color: "#EC4899",
      bgGradient: ["#200A15", "#050D0A"],
      icon: "🌿",
      svgIcon: "thermometer",
      content: "Fluids can actually crawl UP narrow tubes against gravity! \n\nThis is called Capillary Action. It's caused by 'Adhesion' (liquid sticking to the walls) and 'Cohesion' (liquid sticking to itself). This is exactly how giant 300-foot Redwood trees pull water from the deep earth all the way to their highest leaves without a pump! 🌲",
      highlight: "This is also why the corner of a paper towel can suck up an entire spill instantly! 🧻",
    },
    {
      id: "pf_9",
      title: "Hydrostatic Pressure: Deep Sea Crushing 🤿",
      color: "#0EA5E9",
      bgGradient: ["#0A1D20", "#050D0A"],
      icon: "🤿",
      svgIcon: "shield",
      content: "The deeper you go in a liquid, the higher the pressure becomes! \n\nFor every 10 meters you dive in the ocean, the pressure increases by exactly one full Atmosphere. At the bottom of the Mariana Trench, the pressure is so violent it would crush a standard submarine like an empty soda can! 🌊",
      highlight: "Deep-sea creatures survive by having internal pressures that exactly match the crushing monster outside! 🦑",
    },
  ],

  lab: {
    title: "Buoyancy Tank ⚓",
    description: "Welcome to the Liquid Pressure Chamber. Violently drop massively dense physical objects into different fluids. Observe if they sink or float based on Archimedes' math!",
    hint: "Change the Fluid Type to Mercury (massively dense) to see even heavy Iron anvils float like corks!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Displays real-time Displaced Volume and calculated Buoyant Force in Newtons.",
  },

  doYouKnowWhy: [
    {
      id: "dyk1",
      question: "Do you know why deep-sea divers can't just swim to the surface instantly? 🫧",
      answer: "The Bends! At high pressure, Nitrogen gas dissolves into your blood. If you rise too fast, the pressure drops instantly and the gas turns back into bubbles in your veins—exactly like opening a shaken soda bottle! It can be lethal! 🏥",
      emoji: "🫧",
    },
    {
      id: "dyk2",
      question: "Do you know why ships have a 'Plimsoll Line' on their side? 🚢",
      answer: "Safety! Different waters have different densities (Fresh vs Salt vs Cold). The line tells the captain exactly how deep the ship can safely sit without the buoyancy failing and sinking the ship! ⚓",
      emoji: "📏",
    },
    {
      id: "dyk3",
      question: "Do you know how Submarines sink and rise on command? 🛟",
      answer: "Ballast Tanks! By pumping water into tanks, the sub becomes denser than the ocean and sinks. By blowing the water out with air, it becomes less dense and floats back to the top! 🌊",
      emoji: "🚤",
    },
    {
      id: "dyk4",
      question: "Do you know why your ears 'pop' in an airplane? ✈️",
      answer: "Pressure difference! As the plane rises, the air pressure outside your eardrum drops. The air trapped *inside* your ear stays at ground pressure and pushes out. The 'pop' is the pressure successfully equalizing through your Eustachian tubes! 👂",
      emoji: "💥",
    },
    {
      id: "dyk5",
      question: "Do you know how a suction cup works? 🪠",
      answer: "It uses the Air Ocean! By pushing the air out from under the cup, you create a low-pressure zone. The 14.7 pounds of atmospheric pressure outside aggressively pins the cup to the surface! 🌪️",
      emoji: "💨",
    },
  ],

  quiz: [
    {
      id: "q1",
      question: "What is the formula for Pressure?",
      options: ["Mass x Velocity", "Force / Area", "Energy x Time", "Gravity - Weight"],
      answer: 1,
      explanation: "Pressure ($P$) depends on how much force you concentrate on a specific area! 🔨",
    },
    {
      id: "q2",
      question: "What is the standard Atmospheric Pressure at sea level?",
      options: ["1.5 lbs", "100 lbs", "14.7 lbs per sq inch", "Zero"],
      answer: 2,
      explanation: "We are being crushed by about 15 pounds of air on every square inch of our skin! 🌬️",
    },
    {
      id: "q3",
      question: "Archimedes' Principle states that Buoyant Force equals...",
      options: ["The object's weight", "The density of the air", "The weight of the displaced fluid", "The depth of the water"],
      answer: 2,
      explanation: "Water pushes up with the same force as the weight of the water the object 'kicked out'! ⚓",
    },
    {
      id: "q4",
      question: "Why do airplanes get 'Lift'?",
      options: ["They are lighter than air", "Bernoulli's Principle (Low pressure on top of wing)", "Magnetic propulsion", "Solar sails"],
      answer: 1,
      explanation: "Fast air on top creates a low-pressure zone that pulls the plane up! ✈️",
    },
    {
      id: "q5",
      question: "What happens to pressure as you go deeper in the ocean?",
      options: ["It decreases", "It stays the same", "It increases massively", "It turns into heat"],
      answer: 2,
      explanation: "The deeper you go, the more the 'Ocean Column' above you weighs! 🌊",
    },
    {
      id: "q6",
      question: "In hydraulics, Pascal's Principle says pressure in a confined fluid travels...",
      options: ["Upward only", "Downward only", "Equally in all directions", "Towards the center"],
      answer: 2,
      explanation: "Squeeze one part, and the force is transmitted perfectly everywhere! 🚜",
    },
    {
      id: "q7",
      question: "Why does ice float on water?",
      options: ["It is colder", "It is strictly LESS dense than liquid water", "It is magnetic", "It is trapped air"],
      answer: 1,
      explanation: "Water is one of the few substances that expands when it freezes! ❄️",
    },
    {
      id: "q8",
      question: "What is 'Viscosity'?",
      options: ["The color of a fluid", "The resistance of a fluid to flow", "The weight of a fluid", "The boiling point"],
      answer: 1,
      explanation: "High viscosity means the fluid is 'thick' and slow (like honey)! 🍯",
    },
    {
      id: "q9",
      question: "Surface Tension allows some insects to walk on water because...",
      options: ["They have wings", "Water molecules at the surface form a 'skin'", "They are magnetic", "The water is frozen"],
      answer: 1,
      explanation: "Cohesion at the surface creates a strong, elastic-like membrane! 🕷️",
    },
    {
      id: "q10",
      question: "How do trees pull water up hundreds of feet?",
      options: ["Gravity", "Capillary Action", "Solar power", "Magnetic roots"],
      answer: 1,
      explanation: "Liquid sticking to narrow tubes crawls up against gravity! 🌿",
    },
    {
      id: "q11",
      question: "Which of these fluids is the MOST viscous?",
      options: ["Water", "Air", "Molasses/Honey", "Alcohol"],
      answer: 2,
      explanation: "Honey resists flow way more than water or air! 🥞",
    },
    {
      id: "q12",
      question: "If a ship moves from fresh water to very salty water, it will...",
      options: ["Sink deeper", "Float higher", "Stay the same", "Capsize"],
      answer: 1,
      explanation: "Salty water is denser, so it provides more buoyant force! 🌊",
    },
    {
      id: "q13",
      question: "Why do stiletto heels damage floors more than flat shoes?",
      options: ["They are heavier", "The force is concentrated on a tiny area (higher pressure)", "They are sharper", "They are made of wood"],
      answer: 1,
      explanation: "Small Area = Massive Pressure! 👠",
    },
    {
      id: "q14",
      question: "A barometer is used to measure...",
      options: ["Wind speed", "Atmospheric Pressure", "Water depth", "Temperature"],
      answer: 1,
      explanation: "Barometers track the weight of the air ocean above us! 🌬️",
    },
    {
      id: "q15",
      question: "What happens to a balloon if you take it to the bottom of the pool?",
      options: ["It expands", "It shrinks (contracts)", "It pops instantly", "It stays the same"],
      answer: 1,
      explanation: "The water pressure squeezes the air inside, making it smaller! 🎈",
    },
    {
      id: "q16",
      question: "Suction cups 'stick' because of what?",
      options: ["Glue", "The 14.7 lbs of air pressure pushing on the outside", "Static electricity", "Internal motors"],
      answer: 1,
      explanation: "Vacuum inside + High Pressure outside = Stuck! 🪠",
    },
    {
      id: "q17",
      question: "What is an 'Incompressible' fluid?",
      options: ["A fluid that can't freeze", "A fluid whose volume doesn't change under pressure (like water)", "A fluid that disappears", "A gas"],
      answer: 1,
      explanation: "Liquids generally don't shrink when you squeeze them! ⚖️",
    },
    {
      id: "q18",
      question: "Why does a hot air balloon rise?",
      options: ["Hot air is lighter (less dense) than cold air", "Engines", "Wings", "Magnets"],
      answer: 0,
      explanation: "Hot air expands, making the balloon overall less dense than the atmosphere! 🎈",
    },
    {
      id: "q19",
      question: "Which metal is so dense that an iron anvil will actually FLOAT in it?",
      options: ["Gold", "Silver", "Mercury (Liquid metal)", "Lead"],
      answer: 2,
      explanation: "Mercury is 13 times denser than water! 🧪",
    },
    {
      id: "q20",
      question: "Density is mathematically defined as...",
      options: ["Force x Area", "Mass / Volume", "Energy / Time", "Weight + Gravity"],
      answer: 1,
      explanation: "How much mass is packed into a specific amount of space! 🧊",
    },
  ],

  relatedTopics: ["forces_motion", "gravity"],
};
