// ─────────────────────────────────────────────────────────
//  TOPIC: HOW RELIGION EVOLVED
//  Category: Religion & God
//  Standard: v2.0 Extreme (15 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'how_religion_evolved',
  title: 'How Religion Evolved',
  subtitle: 'From cave paintings to cathedrals — why humans invented gods 🏛️🧬',
  emoji: '🏛️',
  category: 'Religion & God',
  accentKey: 'how_religion_evolved',

  hook: {
    question: "Why did EVERY human civilization in history — from isolated Amazonian tribes to ancient Egyptians to modern metropolises — independently invent some form of religion, even when they had absolutely zero contact with each other?",
    reveal: "Because religion is not an 'invention' at all. It is a biological byproduct of how our brains evolved. Our ancestors' brains were wired to detect agency (\"Was that rustling a lion or the wind?\"). The ones who assumed 'lion' survived. The ones who assumed 'wind' got eaten.\n\nThis 'Hyperactive Agency Detection Device' (HADD) caused us to see intentional agents EVERYWHERE — in storms, in disease, in death. Those imagined agents became spirits. Spirits became gods. Gods became religions. You worship because your ancestors were paranoid — and paranoia kept them alive. 🧠⚡",
    emoji: '🌍',
  },

  theory: [
    {
      id: 'animism',
      title: "Animism — Everything is Alive 🌿",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'leaf',
      svgIcon: 'eye',
      content: "The oldest form of religion (100,000+ years ago) was **Animism** — the belief that EVERYTHING has a spirit. Rocks, rivers, trees, animals, even the wind.\n\nEarly humans didn't separate themselves from nature. They saw the world as a living, breathing, conscious organism. A thunderstorm wasn't weather; it was an angry sky-spirit. A flowing river was a water goddess.\n\nAnimism has no priests, no holy books, no temples. The entire natural world IS the temple.",
      highlight: "Animism is still practiced today by over 300 million indigenous people worldwide. 🌏",
    },
    {
      id: 'shamanism',
      title: "Shamanism — The First Priests 🥁",
      color: '#9C27B0',
      bgGradient: ['#1A0025', '#0A0010'],
      icon: 'star',
      svgIcon: 'sparkle',
      content: "As tribes grew, certain individuals claimed they could **communicate with the spirits** directly — through trances, hallucinogenic plants, rhythmic drumming, or near-death experiences.\n\nThese were the **Shamans** — humanity's first spiritual leaders. They served as healers, weather-controllers, mediators between the living and the dead.\n\nShamans gained enormous social power. This was the first time in human history that spiritual authority translated into political authority — a pattern that would repeat for the next 100,000 years.",
      highlight: "The word 'Shaman' comes from the Tungus people of Siberia. It means 'one who knows'. 🧙‍♂️",
    },
    {
      id: 'ancestor_worship',
      title: "Ancestor Worship — The Dead are Watching 💀",
      color: '#FF9800',
      bgGradient: ['#1F1500', '#0A0800'],
      icon: 'history',
      svgIcon: 'eye',
      content: "As humans developed language and memory, a powerful new idea emerged: **the dead don't truly disappear**. Your grandmother's voice still echoes in your head. Her rules still control your behavior.\n\nThis led to **Ancestor Worship** — the belief that dead relatives become powerful spirits who can bless or curse the living.\n\nThis was psychologically genius: it ensured social rules survived beyond any single lifetime. 'Don't steal — Grandfather is watching!' worked far better than 'Don't steal because I said so.'",
      highlight: "Ancestor worship remains the dominant spiritual practice in China, Japan, and much of Africa. 🏮",
    },
    {
      id: 'polytheism',
      title: "Polytheism — Gods for Everything ⚡",
      color: '#FF5722',
      bgGradient: ['#1F0A00', '#0A0500'],
      icon: 'zap',
      svgIcon: 'star',
      content: "When humans invented agriculture (~10,000 BCE), small tribes became large civilizations. Animism couldn't scale — you can't have a personal relationship with a river spirit when 50,000 people live along that river.\n\nSo spirits were organized into **Pantheons** — ranked hierarchies of specialized gods. A Sun god, a War god, a Fertility goddess, a God of the Harvest.\n\nGreece had Olympians. Egypt had Ra and Osiris. India had Brahma, Vishnu, Shiva. Norse had Odin, Thor, Loki. Each god controlled one domain, and if you wanted rain, you prayed to the rain god SPECIFICALLY.",
      highlight: "Hinduism (~4000 years old) is the world's oldest living polytheistic religion. 🕉️",
    },
    {
      id: 'temple_priest_class',
      title: "The Priest Class — Religion Gets Organized 🏛️",
      color: '#FFC107',
      bgGradient: ['#1F1800', '#0A0A00'],
      icon: 'users',
      svgIcon: 'shield',
      content: "Polytheism required TEMPLES — permanent buildings where sacrifices could be performed. Temples required full-time staff: **Priests**.\n\nPriests became the only people who could 'correctly' interpret the gods' will. This created a permanent religious bureaucracy that:\n\n1. Collected wealth (offerings, tithes, taxes)\n2. Controlled information (literacy was restricted to priests)\n3. Legitimized kings (\"God chose our king!\")\n4. Wrote laws and declared them divine\n\nReligion was no longer just spiritual — it became the operating system of civilization.",
      highlight: "In ancient Egypt, temples owned 1/3 of all farmland in the entire country. 🏦",
    },
    {
      id: 'monotheism_revolution',
      title: "The Monotheism Revolution — ONE God 🔥",
      color: '#2196F3',
      bgGradient: ['#001530', '#00050A'],
      icon: 'sun',
      svgIcon: 'target',
      content: "Around 1350 BCE, Egyptian Pharaoh **Akhenaten** attempted history's first monotheistic experiment — worshipping only the sun disc Aten. It failed spectacularly.\n\nBut around 600 BCE, the ancient Israelites succeeded. **Judaism** declared: there is only ONE God, and He has a personal covenant with ONE people.\n\nThis was revolutionary because it claimed that the entire universe — storms, harvests, war, love — was controlled by a single, unified intelligence with a MORAL agenda. The universe wasn't chaotic; it had a singular purpose.",
      highlight: "Judaism gave birth to both Christianity and Islam — making it arguably the most influential religion in human history. ✡️",
    },
    {
      id: 'axial_age',
      title: "The Axial Age — Philosophy Meets Religion 🧠",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'book',
      svgIcon: 'brain',
      content: "Between 800–200 BCE, something astonishing happened simultaneously across the world:\n\n• **Greece**: Socrates, Plato, Aristotle questioned everything\n• **India**: Buddha and Mahavira rejected ritual for inner awakening\n• **China**: Confucius and Laozi built ethical systems\n• **Persia**: Zoroaster introduced cosmic Good vs. Evil\n• **Israel**: Prophets demanded social justice over sacrifice\n\nKarl Jaspers called this the **Axial Age** — the pivot point of human consciousness. Religion shifted from 'how to appease angry gods' to 'how should a human being live?'",
      highlight: "Five of the world's most influential thinkers (Buddha, Confucius, Socrates, Zoroaster, Isaiah) were all alive within 200 years of each other. 🤯",
    },
    {
      id: 'christianity_spread',
      title: "Christianity — How a Sect Conquered the World ✝️",
      color: '#E91E63',
      bgGradient: ['#1F0010', '#0A0008'],
      icon: 'globe',
      svgIcon: 'chart',
      content: "Christianity started as a tiny Jewish sect of maybe 120 people after Jesus of Nazareth's crucifixion (~33 CE).\n\nWithin 300 years, it had conquered the entire Roman Empire. How?\n\n1. **Universal appeal**: Unlike Judaism, it was open to ALL ethnicities\n2. **Social welfare**: Early Christians cared for the sick during plagues when pagan priests fled\n3. **Martyrdom**: Persecution created sympathy and 'proof' of conviction\n4. **Constantine's conversion** (312 CE): A Roman Emperor adopting it was the tipping point\n\nOnce the state backed it, conversion became politically advantageous.",
      highlight: "Christianity went from 0 to 2.4 billion adherents — the largest religion in human history. 📈",
    },
    {
      id: 'islam_rise',
      title: "Islam — From Desert to Global Civilization 🌙",
      color: '#4CAF50',
      bgGradient: ['#0A1F0A', '#050A05'],
      icon: 'moon',
      svgIcon: 'globe',
      content: "In 610 CE, a merchant named Muhammad in Mecca reported receiving divine revelations from the Angel Jibreel (Gabriel). These revelations became the **Quran**.\n\nIslam spread with extraordinary speed because:\n\n1. **Simplicity**: Five clear pillars anyone could follow\n2. **Egalitarianism**: No priest class; direct relationship with God\n3. **Military expansion**: Arab armies conquered Persia, North Africa, Spain\n4. **Trade networks**: Muslim merchants spread Islam across Asia and Africa peacefully\n5. **Scholarship**: The Islamic Golden Age (800–1300 CE) preserved Greek knowledge while Europe had forgotten it",
      highlight: "Islam is the fastest-growing major religion today, with 1.9 billion followers worldwide. 🕌",
    },
    {
      id: 'eastern_religions',
      title: "Eastern Religions — A Different Path 🧘",
      color: '#FF9800',
      bgGradient: ['#1F1200', '#0A0800'],
      icon: 'lotus',
      svgIcon: 'compass',
      content: "Eastern religions evolved along a fundamentally different axis than Western ones:\n\n**Hinduism**: No single founder. An ancient, evolving tapestry of rituals, philosophies, and stories. Believes in **Brahman** — a single ultimate reality that manifests as everything.\n\n**Buddhism**: Founded by Siddhartha Gautama (~500 BCE). Explicitly avoids god-claims. Focuses entirely on ending suffering through mental discipline.\n\n**Taoism**: Founded by Laozi. The 'Tao' (Way) is the natural flow of the universe. Don't fight it; align with it.\n\nNotice: Eastern religions focus on **inner transformation**, while Western ones focus on **obedience to an external God**.",
      highlight: "The Buddha explicitly refused to answer the question 'Does God exist?' — calling it an unanswerable distraction. 🤐",
    },
    {
      id: 'reformation',
      title: "The Protestant Reformation — Religion Splits 📜",
      color: '#9C27B0',
      bgGradient: ['#150020', '#0A0010'],
      icon: 'scroll',
      svgIcon: 'bolt',
      content: "By the 1500s, the Catholic Church had become spectacularly corrupt — selling 'indulgences' (literally paying money to reduce time in Hell).\n\nIn 1517, Martin Luther nailed 95 complaints to a church door in Wittenberg, Germany. He argued that salvation came through **faith alone**, not through the Church.\n\nThis ignited the **Protestant Reformation**, which:\n• Split Christianity into Catholic and Protestant branches\n• Triggered devastating religious wars across Europe\n• Emphasized **individual Bible reading** (which required literacy, which fueled the printing press, which fueled the Enlightenment)\n\nOne angry monk accidentally created the modern world.",
      highlight: "Luther's 95 Theses went viral thanks to the printing press — essentially history's first 'tweet storm'. 🖨️",
    },
    {
      id: 'secularism_rise',
      title: "The Rise of Secularism — God Gets Fired 🏢",
      color: '#607D8B',
      bgGradient: ['#101515', '#050A0A'],
      icon: 'building',
      svgIcon: 'lock',
      content: "The Enlightenment (1600s–1800s) introduced a radical idea: **Reason, not revelation, should guide society.**\n\nScientists like Galileo, Newton, and Darwin provided natural explanations for phenomena previously attributed to God. Philosophers like Voltaire and Locke argued for separation of church and state.\n\nResult: Modern secular democracies where:\n• Laws come from constitutions, not holy books\n• Science, not scripture, is taught in schools\n• Freedom OF religion became freedom FROM religion\n\nFor the first time in 100,000 years, religion lost its monopoly on truth.",
      highlight: "Today, 'Nones' (people with no religious affiliation) are the fastest-growing 'religious' group in America and Europe. 📉",
    },
    {
      id: 'cognitive_science',
      title: "Cognitive Science of Religion — Why We Believe 🧬",
      color: '#00BCD4',
      bgGradient: ['#001520', '#000A0A'],
      icon: 'brain',
      svgIcon: 'microscope',
      content: "Modern cognitive science has identified the exact brain mechanisms that produce religious belief:\n\n1. **HADD** (Hyperactive Agency Detection): We see 'someone' behind random events\n2. **Theory of Mind**: We imagine gods have thoughts, desires, and plans\n3. **Teleological Thinking**: Children naturally assume everything exists 'for a purpose'\n4. **Pattern Recognition**: We find meaningful patterns in pure randomness\n5. **Mortality Salience**: Terror of death motivates afterlife beliefs\n\nReligion is not a random cultural accident. It is what happens when a social brain confronts an indifferent universe.",
      highlight: "Children as young as 3 spontaneously attribute purpose to natural objects ('Rocks are for climbing') even without religious teaching. 👶",
    },
    {
      id: 'social_glue',
      title: "Religion as Social Glue — Survival Advantage 🤝",
      color: '#8BC34A',
      bgGradient: ['#0A1F05', '#050A02'],
      icon: 'users',
      svgIcon: 'heart',
      content: "Anthropologists discovered that religious groups consistently outcompete non-religious ones in the Darwinian struggle. Why?\n\n1. **Costly Signaling**: Proving loyalty through painful rituals (fasting, circumcision, dietary laws) filters out free-riders\n2. **Shared Rituals**: Synchronized dancing, singing, and praying release oxytocin and bond strangers into a tribe\n3. **Supernatural Punishment**: 'God is always watching' is the cheapest possible surveillance system\n4. **Cooperation**: Groups with a shared God cooperate better than groups without one\n\nReligion may be factually wrong but socially indispensable — at least until we build better alternatives.",
      highlight: "Studies show religious communes last 4x longer than secular communes because costly rituals filter out free-riders. 📊",
    },
    {
      id: 'future_religion',
      title: "The Future of Religion — What Comes Next? 🔮",
      color: '#6366F1',
      bgGradient: ['#0A0A30', '#050010'],
      icon: 'rocket',
      svgIcon: 'chart',
      content: "Religion isn't disappearing — it's transforming:\n\n• **Spiritual but not religious**: Fastest-growing category. People want meaning without institutions.\n• **AI religions**: Already emerging. Way of the Future (by an ex-Google engineer) briefly worshipped AI as a godhead.\n• **Digital rituals**: Virtual church services, meditation apps, online prayer groups\n• **Psychedelic spirituality**: Psilocybin research at Johns Hopkins triggers 'mystical experiences' indistinguishable from spontaneous religious visions\n• **Transhumanism**: If we upload consciousness to computers, does the soul come with it?\n\nHumans will ALWAYS need meaning. The packaging will change, but the hunger never dies.",
      highlight: "70% of participants in psilocybin trials rated their experience as one of the top 5 most meaningful events of their entire lives. 🍄",
    },
  ],

  lab: {
    title: "The Civilization Faith Engine ⏳🏛️",
    description: "Guide a tribe from 50,000 BCE to modern times. Watch how belief systems evolve as population grows, knowledge increases, and social complexity rises. Will your civilization discover monotheism, stay polytheistic, or go secular?",
    hint: "Each era has unique pressures. High social complexity without belief systems leads to collapse. Too much dogma stifles science!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks HADD activation coefficients, Durkheimian solidarity indices, and cognitive load metrics per era.",
  },

  doYouKnowWhy: [
    { id: 'dyk1', question: "Do you know why humans bury their dead with flowers and tools? 💐", answer: "The oldest known intentional burial is ~100,000 years old (Qafzeh Cave, Israel). Burying the dead with items suggests that even Neanderthals may have believed in some form of afterlife. Flowers found in Shanidar Cave burials (Iraq, ~60,000 BCE) hint at mourning rituals predating modern humans! 🌸", emoji: '⚰️' },
    { id: 'dyk2', question: "Do you know why almost every culture has a Flood Myth? 🌊", answer: "Noah's Ark, the Hindu Manu, the Sumerian Utnapishtim, the Greek Deucalion — nearly every ancient culture has a story about a great flood. This is likely because early civilizations settled near rivers (Nile, Tigris, Indus, Yellow) that actually DID catastrophically flood every few centuries. Real trauma became mythical memory. 🏔️", emoji: '🚢' },
    { id: 'dyk3', question: "Do you know why churches have stained glass windows? 🪟", answer: "In medieval Europe, over 90% of the population was illiterate. They couldn't read the Bible even if they wanted to. Stained glass windows were essentially 'Biblical Netflix' — they told the stories of Jesus visually, so uneducated peasants could absorb Christian theology just by looking up during mass! 🎨", emoji: '⛪' },
    { id: 'dyk4', question: "Do you know why the number 7 is considered 'holy' in almost every religion? 7️⃣", answer: "Seven visible celestial bodies were known to the ancient world: Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn. Since the heavens were divine, the number of visible 'gods' in the sky (7) became sacred. This gave us 7-day weeks, 7 deadly sins, 7 heavens in Islam, 7 chakras in Hinduism, and 7 as the 'lucky' number worldwide! ✨", emoji: '🌟' },
    { id: 'dyk5', question: "Do you know why atheism was practically impossible before 1700? 🤔", answer: "Before modern science, there was literally NO alternative explanation for why the sun rose, why seasons changed, why babies were born, or why people died. Saying 'There is no God' was like saying 'There is no explanation for anything.' Atheism only became thinkable after Newton, Darwin, and germ theory provided non-divine explanations for natural phenomena. 🔬", emoji: '🧪' },
  ],

  quiz: [
    { id: 'q1', question: "The OLDEST form of religious belief in human history is:", options: ['Christianity', 'Animism (everything has a spirit)', 'Islam', 'Monotheism'], answer: 1, explanation: "Animism predates ALL organized religions by tens of thousands of years. 🌿" },
    { id: 'q2', question: "A Shaman in early human society was:", options: ['A military leader', 'A person who claimed to communicate with spirits through trances', 'A farmer', 'A scientist'], answer: 1, explanation: "Shamans were humanity's first spiritual intermediaries — the prototype for all priests. 🥁" },
    { id: 'q3', question: "Ancestor Worship was psychologically effective because:", options: ['Dead people actually watch you', 'It made social rules survive beyond one lifetime by attributing them to powerful dead relatives', 'It was fun', 'Caves were boring'], answer: 1, explanation: "'Grandfather is watching!' is far more compelling than any human-made law. 💀" },
    { id: 'q4', question: "Polytheism (many gods) emerged primarily because:", options: ['People got bored of one god', 'Agriculture created large civilizations that needed specialized, organized spiritual systems', 'Zeus was real', 'Monotheism hadn\'t been invented yet'], answer: 1, explanation: "A city of 50,000 needs a rain god, a war god, and a harvest god — a single spirit won't scale. 🏛️" },
    { id: 'q5', question: "The Priest Class gained power primarily by:", options: ['Being stronger fighters', 'Controlling access to the gods, information (literacy), and wealth (offerings)', 'Being elected democratically', 'Being the best farmers'], answer: 1, explanation: "Priests were the original gatekeepers — controlling truth itself. 🔑" },
    { id: 'q6', question: "The first known attempt at monotheism was by:", options: ['Moses', 'Jesus', 'Egyptian Pharaoh Akhenaten (~1350 BCE)', 'Muhammad'], answer: 2, explanation: "Akhenaten tried to force Egypt to worship only the sun disc Aten. It failed after his death. ☀️" },
    { id: 'q7', question: "The Axial Age (800-200 BCE) was significant because:", options: ['The Earth tilted on its axis', 'Multiple civilizations independently shifted religion from ritual to ethical philosophy', 'Nothing happened', 'Humans learned to write'], answer: 1, explanation: "Buddha, Confucius, Socrates, and Isaiah all emerged in this 600-year window. 🤯" },
    { id: 'q8', question: "Christianity spread through the Roman Empire primarily because:", options: ['Military conquest only', 'Universal appeal, social welfare during plagues, and eventual state backing by Emperor Constantine', 'Magic', 'It was the only religion'], answer: 1, explanation: "Early Christians nursed the sick during plagues while pagan priests fled — winning converts through compassion. ✝️" },
    { id: 'q9', question: "Islam spread rapidly due to:", options: ['Violence only', 'Its simplicity, egalitarianism, military expansion, trade networks, AND preservation of ancient knowledge', 'Weather conditions', 'Roman support'], answer: 1, explanation: "Islam combined spiritual accessibility with intellectual achievement during the Islamic Golden Age. 🌙" },
    { id: 'q10', question: "A key difference between Eastern and Western religions is:", options: ['Eastern religions are newer', 'Eastern religions focus on inner transformation; Western ones focus on obedience to an external God', 'They are identical', 'Eastern religions have more gods'], answer: 1, explanation: "Buddhism doesn't even require belief in God — it focuses entirely on ending suffering through mental training. 🧘" },
    { id: 'q11', question: "Martin Luther's Protestant Reformation was triggered by:", options: ['A war', 'The Catholic Church selling indulgences (pay money to reduce Hell-time)', 'A scientific discovery', 'An earthquake'], answer: 1, explanation: "Luther's fury at the monetization of salvation split Christianity forever. 📜" },
    { id: 'q12', question: "The Enlightenment challenged religion by arguing that:", options: ['God didn\'t exist', 'Reason, not divine revelation, should guide society and laws', 'Science was evil', 'Kings should be priests'], answer: 1, explanation: "Thinkers like Voltaire argued for separating church from state — a radical idea at the time. 💡" },
    { id: 'q13', question: "HADD (Hyperactive Agency Detection Device) explains why humans:", options: ['See intentional agents behind random events (like faces in clouds)', 'Can run fast', 'Need sleep', 'Like music'], answer: 0, explanation: "Your brain assumes rustling bushes = lion, not wind. This paranoia created the template for gods. 🧠" },
    { id: 'q14', question: "Religious groups outcompete non-religious ones because:", options: ['God helps them', 'Costly rituals filter free-riders, shared rituals bond strangers, supernatural punishment is cheap surveillance', 'They have more weapons', 'They eat better'], answer: 1, explanation: "'God is watching' is the cheapest police force ever invented. 👁️" },
    { id: 'q15', question: "The 'Nones' (no religious affiliation) are:", options: ['A new religion', 'The fastest-growing religious category in America and Europe', 'Atheists only', 'A small minority'], answer: 1, explanation: "Many 'Nones' still believe in a higher power — they just reject organized religious institutions. 📉" },
    { id: 'q16', question: "Nearly every ancient culture has a Great Flood myth because:", options: ['Noah\'s flood was global', 'Early civilizations settled near rivers that really did catastrophically flood', 'Aliens caused floods', 'It rained a lot in 3000 BCE'], answer: 1, explanation: "Real river flooding along the Nile, Tigris, and Indus became mythologized into divine punishment stories. 🌊" },
    { id: 'q17', question: "Hinduism is unique among world religions because:", options: ['It has a single founder', 'It has no single founder, no single holy book, and evolved organically over ~4000 years', 'It was founded in 500 CE', 'It is a monotheistic religion'], answer: 1, explanation: "Hinduism is more like a civilization's entire spiritual ecosystem than a single organized religion. 🕉️" },
    { id: 'q18', question: "Stained glass windows in medieval churches were essentially:", options: ['Just decoration', 'Visual Bible stories for an illiterate population', 'Light filters', 'Tax receipts'], answer: 1, explanation: "Over 90% of medieval Europeans couldn't read. Stained glass was Biblical Netflix. 🪟" },
    { id: 'q19', question: "The number 7 is holy in most religions because:", options: ['It\'s mathematically special', 'There were 7 visible celestial bodies (Sun, Moon, 5 planets) in the ancient sky', 'God likes 7', 'Random chance'], answer: 1, explanation: "Ancient skywatchers saw 7 'gods' in the sky — making 7 the divine number. ✨" },
    { id: 'q20', question: "The future of religion will most likely involve:", options: ['Complete disappearance', 'Transformation into spiritual-but-not-religious movements, digital rituals, and meaning without institutions', 'A return to animism', 'One world religion conquering all others'], answer: 1, explanation: "The hunger for meaning is eternal. Only the packaging changes across millennia. 🔮" },
  ],

  relatedTopics: ['science_vs_god', 'world_religions', 'god_arguments', 'eastern_philosophy'],
};
