// ─────────────────────────────────────────────────────────
//  TOPIC: INVESTING
//  Category: Finance
//  Standard: v2.0 Extreme (10 Cards, 5 Facts, 20 Questions)
// ─────────────────────────────────────────────────────────

export default {
  id: 'investing',
  title: 'Investing Mastery',
  subtitle: 'Building a forest of money trees 🌳',
  emoji: '🚀',
  category: 'Finance',
  accentKey: 'success',

  hook: {
    question: "If you want to become a billionaire, you just need to work hard and save your salary, right? 💼",
    reveal: "Wrong! You cannot 'save' your way to wealth. Inflation is like a monster that eats your cash while you sleep. The only way to win is to build a 'Money Tree'—an asset that grows and produces fruit (money) even when you aren't working. Welcome to the world of Investing! 🌳💰",
    emoji: '🚀',
  },

  theory: [
    {
      id: 'investing_vs_saving',
      title: 'Seeds vs Fruit 🍎',
      color: '#4ECDC4',
      bgGradient: ['#0A1A1A', '#050D0A'],
      icon: '🍎',
      svgIcon: 'balance',
      content: "**Saving** is like keeping your seeds in a jar. They are safe, but they never grow. Eventually, they might even rot (Inflation).\n\n**Investing** is like planting those seeds in fertile soil. It's riskier because a storm might come, but over time, those seeds grow into giant trees that produce thousands of new fruits. You save for today; you invest for your future kingdom.",
      highlight: "Saving is defensive; Investing is offensive. ⚔️",
    },
    {
      id: 'what_are_stocks',
      title: 'The Pizza Slice (Stocks) 🍕',
      color: '#00D4FF',
      bgGradient: ['#001A20', '#050D0A'],
      icon: '🍕',
      svgIcon: 'chart',
      content: "When you buy a stock, you aren't just buying a number on a screen. You are buying a tiny slice of a real pizza (a company like Apple or Disney).\n\nIf the company sells more iPhones or movies, the whole pizza gets bigger, and your slice becomes more valuable! You literally own a piece of the smartest people in the world working for you while you sleep.",
      highlight: "Buying a stock means you are the boss of a giant company. 👔",
    },
    {
      id: 'what_are_bonds',
      title: 'The I.O.U. (Bonds) 📜',
      color: '#FFD166',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '📜',
      svgIcon: 'book',
      content: "Stocks are 'owning', but Bonds are 'loaning.' \n\nA **Bond** is a fancy I.O.U. note. You lend your money to a government or a big company, and they promise to pay you back with a little extra 'Thank You' money (Interest) every year. Bonds are like the slow, steady turtle. They don't run as fast as stocks, but they almost never fall over.",
      highlight: "Stocks are the engine; Bonds are the brakes. 🏎️",
    },
    {
      id: 'mutual_funds',
      title: 'The Fruit Basket 🧺',
      color: '#A855F7',
      bgGradient: ['#1A0830', '#050D0A'],
      icon: '🧺',
      svgIcon: 'star',
      content: "Picking one winning stock is like trying to guess which single apple in a store is the tastiest. It's hard!\n\nA **Mutual Fund** is like a giant basket filled with 100 different types of fruits. If one apple goes bad, you still have 99 other delicious fruits. A professional 'Chef' (Fund Manager) picks the fruits for you, but they charge you a fee for their help.",
      highlight: "Don't put all your eggs in one basket. Buy the whole store! 🛒",
    },
    {
      id: 'index_funds',
      title: 'The Robot Garden 🤖',
      color: '#FF9F1C',
      bgGradient: ['#1A0D05', '#050D0A'],
      icon: '🤖',
      svgIcon: 'shield',
      content: "An **Index Fund** is a mutual fund run by a computer robot instead of a human chef.\n\nIt doesn't try to guess the best stocks; it just buys the top 500 biggest companies automatically. Because robots work for free, the fees are almost zero! Historically, these 'lazy' robot funds beat 90% of the smartest human investors over long periods of time.",
      highlight: "Don't look for the needle; just buy the whole haystack! 🌾",
    },
    {
      id: 'risk_vs_return',
      title: 'The Rollercoaster 🎢',
      color: '#FF6B9D',
      bgGradient: ['#1A0D10', '#050D0A'],
      icon: '🎢',
      svgIcon: 'alert',
      content: "Investing is like a rollercoaster. Sometimes it goes up high (Profit), and sometimes it drops fast (Risk). \n\nIf you want the big thrills (High Returns), you have to be brave enough to handle the drops. If you stay on the ride until the end, you usually finish much higher than you started. But if you jump off during a drop (Panic Selling), you get hurt!",
      highlight: "Volatility is the price of admission for wealth. 🎟️",
    },
    {
      id: 'sip_magic',
      title: 'The Snowball (SIP) ❄️',
      color: '#00FF7F',
      bgGradient: ['#051A10', '#050D0A'],
      icon: '❄️',
      svgIcon: 'refresh',
      content: "A **SIP** is like rolling a tiny snowball down a giant mountain every single month.\n\nIt doesn't matter if the sun is out or it's raining; you just keep rolling. When the market 'crashes', your snowball actually gets BIGGER because you are buying shares at a 'Sale' price. By the time you reach the bottom of the mountain, you have a massive, unstoppable avalanche of wealth.",
      highlight: "Consistency is more powerful than luck. 🏔️",
    },
    {
      id: 'asset_allocation',
      title: 'The Balanced Diet 🥧',
      color: '#FF69B4',
      bgGradient: ['#1A0D14', '#050D0A'],
      icon: '🥧',
      svgIcon: 'target',
      content: "You shouldn't eat only candy (Stocks) or only broccoli (Bonds). You need a mix!\n\nWhen you are young, you can eat more candy because your stomach can handle it. As you get older, you need more broccoli to stay healthy. **Asset Allocation** is just picking the right mix for your age so you don't get a 'financial stomach ache' when the market moves.",
      highlight: "Your mix determines 90% of your success. ⚖️",
    },
    {
      id: 'power_of_early',
      title: 'The Time Machine ⏳',
      color: '#6C63FF',
      bgGradient: ['#100A30', '#050D0A'],
      icon: '⏳',
      svgIcon: 'zap',
      content: "Time is the 'Fertilizer' for your money tree. \n\nIf you start at age 20, you only need to plant a few seeds to have a forest by age 60. But if you wait until age 40, you have to plant thousands of seeds every day just to catch up! Starting 10 years earlier can literally make you 5 times richer with the exact same amount of money.",
      highlight: "The best time to plant a tree was 20 years ago. The second best time is NOW. 🌳",
    },
    {
      id: 'bull_bear_markets',
      title: 'Bulls vs Bears 🐂🐻',
      color: '#D4A74A',
      bgGradient: ['#1A1505', '#050D0A'],
      icon: '🐂',
      svgIcon: 'eye',
      content: "The market has two moods:\n\n**Bull Market 🐂:** The bull thrusts its horns UP! Everyone is happy, and prices go higher.\n**Bear Market 🐻:** The bear swipes its claws DOWN! Everyone is scared, and prices drop.\nSmart investors know that the Bear is just a 'Sale' at the store. They buy when everyone else is running away in fear.",
      highlight: "Be greedy when others are fearful. 🧠",
    },
  ],

  lab: {
    title: "The Money Tree Lab 🌳",
    description: "Welcome to the Wealth Simulator! Here you can test your 'seeds' in different soils. Watch your SIP snowball grow, compare the steady Turtle (Bonds) to the fast Rabbit (Stocks), and use the Time Machine to see how starting today changes your life forever! 💸",
    hint: "Try the 'Time Machine' mode. Delaying your investment by just 5 years can cost you millions of rupees in the end. Time is your greatest asset!",
    scientistModeHint: "Scientist Mode 🧑‍🔬: Unlocks Monte Carlo math, showing the 'wobble' of the market and the 95% probability of your future wealth.",
  },

  doYouKnowWhy: [
    {
      id: 'dyk1',
      question: "Do you know why inflation makes cash 'rot' like old fruit? 🍎",
      answer: "Because of the 'Invisible Thief'! If you keep ₹100 in your pocket for 20 years, it will still be ₹100, but it will only buy you 2 candies instead of 20. Inflation makes things more expensive, so your cash loses its 'superpower' over time. You MUST invest just to stay even! 📉",
      emoji: '📉',
    },
    {
      id: 'dyk2',
      question: "Do you know why human stock-pickers usually lose to a Robot? 🤖",
      answer: "Ego and Fees! Humans get scared and sell at the wrong time, or they get greedy and buy at the peak. They also charge you a lot of money for their 'advice.' A Robot Index Fund doesn't have feelings and works for almost free. Over 20 years, the boring Robot almost always wins. 🤖",
      emoji: '👔',
    },
    {
      id: 'dyk3',
      question: "Do you know why Dividends are like 'Free Fruit'? 🍒",
      answer: "A dividend is a company saying 'Thank You' for owning us. They send you cash just for holding their stock. If you use that cash to buy MORE of that stock, your tree gets bigger, and next year you get even more fruit! This is how the ultra-rich live without ever working. 🍒",
      emoji: '🧱',
    },
    {
      id: 'dyk4',
      question: "Do you know why you shouldn't check your stocks every day? 🙈",
      answer: "The 'Jiggle'! Every day, stock prices jiggle up and down for no reason. If you watch the jiggles, you'll get stressed and do something silly. But if you look at the graph over 10 years, it's a beautiful smooth line going up. Check your trees once a year, not once a minute! 🌳",
      emoji: '🎢',
    },
    {
      id: 'dyk5',
      question: "Do you know why Gold is a 'Shield' but not a 'Tree'? 🛡️",
      answer: "Gold is a shiny rock. It doesn't grow, it doesn't invent iPhones, and it doesn't produce fruit. It just sits there. It's a great shield to protect you during a war or a crisis, but it won't build you a forest of wealth like a living, breathing business will. 🪙",
      emoji: '🪙',
    },
  ],

  quiz: [
    { id: 'q1', question: "What is the main difference between Saving and Investing?", options: ["Saving is for kids, Investing is for adults", "Saving keeps money safe; Investing makes money grow", "Investing is illegal in some countries", "There is no difference"], answer: 1, explanation: "Saving is for today's emergency; Investing is for tomorrow's freedom! 🍎" },
    { id: 'q2', question: "When you buy a 'Stock', you are buying:", options: ["A lottery ticket", "A slice of ownership in a real company", "A loan to the government", "Digital video game money"], answer: 1, explanation: "You are the boss of a piece of that business! 🍕" },
    { id: 'q3', question: "What is a 'Bond'?", options: ["A secret spy mission", "A loan you give to a company or government for interest", "A type of glue", "A high-risk stock"], answer: 1, explanation: "Bonds are I.O.U. notes that pay you back with interest! 📜" },
    { id: 'q4', question: "Why is a Mutual Fund like a 'Fruit Basket'?", options: ["It contains actual fruit", "It holds many different stocks to keep your money safe", "It is only sold in grocery stores", "It is always healthy"], answer: 1, explanation: "Diversification means one bad apple won't ruin your whole basket! 🧺" },
    { id: 'q5', question: "An 'Index Fund' is special because:", options: ["It is run by a computer robot with very low fees", "It only buys gold", "It is managed by the world's smartest human", "It guarantees you will never lose money"], answer: 0, explanation: "Robots are cheaper and more disciplined than humans! 🤖" },
    { id: 'q6', question: "What does the 'Bore' in Bull Market represent?", options: ["Sleeping", "A bear swiping down", "A bull thrusting UP with its horns", "A type of forest"], answer: 2, explanation: "Bulls push UP; Bears swipe DOWN! 🐂" },
    { id: 'q7', question: "Why is a 'SIP' (Snowball) better than a one-time investment for most people?", options: ["It's faster", "It builds a habit and buys more when prices are low (on sale)", "It's a secret code", "The bank pays you to do it"], answer: 1, explanation: "Consistency beats timing the market! ❄️" },
    { id: 'q8', question: "What is 'Asset Allocation'?", options: ["Buying as much as possible", "Picking the right mix of Stocks and Bonds for your age", "Hiding money from parents", "Picking the best single stock"], answer: 1, explanation: "It's your financial balanced diet! 🥧" },
    { id: 'q9', question: "Why is time considered the 'Fertilizer' of money?", options: ["It smells bad", "It allows compound interest to turn small seeds into giant forests", "It's only for farmers", "Money doesn't actually grow"], answer: 1, explanation: "The longer you wait, the bigger the tree! ⏳" },
    { id: 'q10', question: "What should you do in a 'Bear Market' (Prices dropping)?", options: ["Panic and sell everything", "Cry", "Stay calm and keep buying 'on sale'", "Call the police"], answer: 2, explanation: "Bears create sales. Don't run from a discount! 🐻" },
    { id: 'q11', question: "What is a 'Dividend'?", options: ["A math problem", "A 'Thank You' payment from a company to its owners", "A tax penalty", "The price of a stock"], answer: 1, explanation: "It's the fruit from your money tree! 🍒" },
    { id: 'q12', question: "Why is an Index Fund called 'Buying the Haystack'?", options: ["It's made of dried grass", "Instead of looking for one winning needle, you just buy the whole market", "It's only for horses", "It's very cheap"], answer: 1, explanation: "Own everything and you can't miss the winners! 🌾" },
    { id: 'q13', question: "The 'Risk/Return' rule says:", options: ["High returns always have high risk", "You can get rich with zero risk", "Risk is for losers", "Return is guaranteed"], answer: 0, explanation: "The rollercoaster thrills cost a ticket of risk! 🎢" },
    { id: 'q14', question: "What is 'Inflation'?", options: ["A balloon popping", "The 'Invisible Thief' that makes prices go up and cash value go down", "A type of investment", "A bank fee"], answer: 1, explanation: "It eats your cash like a monster! 📉" },
    { id: 'q15', question: "Why is it bad to check your portfolio every day?", options: ["It drains your battery", "Small daily 'jiggles' make you feel stressed and take bad actions", "The bank will lock your account", "It's illegal"], answer: 1, explanation: "Focus on the forest, not the jiggling leaves! 🙈" },
    { id: 'q16', question: "If you have 40 years to invest, your mix should have:", options: ["More Stocks (Candy) for growth", "More Bonds (Broccoli) for safety", "Only Cash", "Only Gold"], answer: 0, explanation: "You have time to recover from the rollercoaster! 🎢" },
    { id: 'q17', question: "Compound Interest is often called:", options: ["The 8th Wonder of the World", "A magic trick", "A bank scam", "The boring math"], answer: 0, explanation: "It turns pennies into millions over time! ❄️" },
    { id: 'q18', question: "Why is physical Gold considered a 'Hedge'?", options: ["It grows in a garden", "It protects your value during a crisis or war (like a shield)", "It pays high dividends", "It's easy to eat"], answer: 1, explanation: "It's a shield, not a tree! 🛡️" },
    { id: 'q19', question: "What is 'Volatility'?", options: ["A type of fuel", "The up-and-down 'jiggle' of stock prices", "A guaranteed profit", "A bank holiday"], answer: 1, explanation: "It's the jiggle of the ride! 🎢" },
    { id: 'q20', question: "The most important factor in investing success is:", options: ["Being lucky", "Having a lot of money", "Time and Patience", "Knowing a secret stock"], answer: 2, explanation: "Patience is the superpower of the rich! ⏳" }
  ],

  relatedTopics: ['personal_finance', 'banking', 'wealth_loops'],
};
